### PR TITLE
Test fix for flakey test: testIsParallelCollectionSupportedForResults

### LINKED ISSUE #98534: SearchServiceTests.testIsParallelCollectionSupportedForResults fails intermittently
SearchServiceTests.testIsParallelCollectionSupportedForResults fails intermittently

```
12:37:10 org.elasticsearch.search.SearchServiceTests > testIsParallelCollectionSupportedForResults FAILED
12:37:10     java.lang.AssertionError
12:37:10         at __randomizedtesting.SeedInfo.seed([4140C168DE8FB0BB:771A78D5E4B36180]:0)
12:37:10         at org.junit.Assert.fail(Assert.java:86)
12:37:10         at org.junit.Assert.assertTrue(Assert.java:41)
12:37:10         at org.junit.Assert.assertFalse(Assert.java:64)
12:37:10         at org.junit.Assert.assertFalse(Assert.java:74)
12:37:10         at org.elasticsearch.search.SearchServiceTests.testIsParallelCollectionSupportedForResults(SearchServiceTests.java:2096)
```

```
./gradlew ':server:test' --tests "org.elasticsearch.search.SearchServiceTests.testIsParallelCollectionSupportedForResults" -Dtests.seed=4140C168DE8FB0BB -Dtests.locale=es-SV -Dtests.timezone=Africa/Banjul -Druntime.java=20
```

### PR DESCRIPTION
**Pull request by JVerwolf**
Fixes https://github.com/elastic/elasticsearch/issues/98534

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/search/SearchServiceTests.java [hunk 1]
```diff
@@ -2080,27 +2081,47 @@ public void testSupportsParallelCollectionAffectsSlicing() throws Exception {
...
+                        );
+                    } else if (addedAggregation == null || addedAggregation == aggSupportsParallelCollection) {
+                        assertTrue(
+                            "Query phase supports Parallel collection when enabled && does not contain unsupported agg.",
+                            SearchService.isParallelCollectionSupportedForResults(resultsType, searchSourceBuilder, true)
+                        );
+                    }
+                };
+            };
+            boilerplateForExhaustiveSwitch.run();
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/search/SearchServiceTests.java:2123]: what do you need the runnable for? You can have you assertions within the switch without it?

**Review by javanna — CHANGES_REQUESTED** [review]

File: server/src/test/java/org/elasticsearch/search/SearchServiceTests.java (hunk 1 above)
Comment (JVerwolf) [reply server/src/test/java/org/elasticsearch/search/SearchServiceTests.java:2123]: As you are aware, a switch _expression_ (vs statement) is exhaustive. This is a desirable quality here, as now our compiler can help enforce correctness: you _must_ modify this test if you add to the `ResultsType` enum, otherwise this test won't compile.

I come from a Kotlin background which has more ergonomics for strong-typing, which is were I developed these preferences.   Brian Goetz discusses the current Java limitations here: https://stackoverflow.com/a/66217353. 
It turns out that to make a switch exhaustive, one must  return a value to make it an expression.  Returning `void` won't work, and surprisingly, after playing around, this seemed to me to be the least offensive way to do it.

I may be biased, but I think the benefit of strong typing outweighs the slight readability cost here in test code, since enforcing correctness is the goal.  It's a matter of preference, and I'm happy to be persuaded to loose the guarantee in favor of simplicity if you lean in that direction.

File: server/src/test/java/org/elasticsearch/search/SearchServiceTests.java [hunk 2]
```diff
@@ -2080,27 +2081,47 @@ public void testSupportsParallelCollectionAffectsSlicing() throws Exception {
...
+                        "DFS phase supports parallel collection.",
+                        SearchService.isParallelCollectionSupportedForResults(resultsType, searchSourceBuilder, randomBoolean())
+                    );
+                };
+                case QUERY -> () -> {
+                    assertFalse(
+                        "Parallel collection can be disabled for Query Phase.",
+                        SearchService.isParallelCollectionSupportedForResults(resultsType, searchSourceBuilder, false)
+                    );
+                    if (addedAggregation == aggDoesNotSupportParallelCollection) {
```
[the remark this answers is not in the document]
Comment (JVerwolf) [reply server/src/test/java/org/elasticsearch/search/SearchServiceTests.java]: Good point, thanks for the feedback.  I've updated the tests to be much more explicit.  WDYT?

**Comment by JVerwolf** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc

File: server/src/test/java/org/elasticsearch/search/SearchServiceTests.java (hunk 1 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/search/SearchServiceTests.java:2151]: I do  see how a switch is beneficial, but I also think that a runnable here does not really fit in well. I normally work around this switch limitation by adding a default case that throws unsupported operation exception. That fails at runtime instead of at compile time, but we don't add new results type often, actually we very unlikely to add one anytime soon. i agree with the importance of failing for possible new values that are not handled appropriately though.

Another way would be to not require a switc, and use an enumset to iterate over all values that are not DFS or QUERY, and check that concurrency is not enabled for them. This would be maybe a little more readable as follows:

```
assertFalse(
                    "NONE and FETCH phases do not support parallel collection.",
                    SearchService.isParallelCollectionSupportedForResults(NONE, searchSourceBuilderOrNull, randomBoolean())
                );
assertFalse(
                    "NONE and FETCH phases do not support parallel collection.",
                    SearchService.isParallelCollectionSupportedForResults(FETCH, searchSourceBuilderOrNull, randomBoolean())
                );
 assertTrue(
                        "DFS phase always supports parallel collection.",
                        SearchService.isParallelCollectionSupportedForResults(DFS, searchSourceBuilderOrNull, randomBoolean())
                   );

//here goes the rest of the assertions that take QUERY explicitly as argument.

```

I am fine with either of the solutions above (with or without switch) but I would like to remove the runnable part, although I see why you have it. It makes the test difficult to follow. Thanks!

**Review by javanna — APPROVED** [review]
LGTM besides the comment I left

File: server/src/test/java/org/elasticsearch/search/SearchServiceTests.java (hunk 1 above)
Comment (JVerwolf) [reply server/src/test/java/org/elasticsearch/search/SearchServiceTests.java]: Great explanation, thanks!

**Comment by JVerwolf** [comment]
@elasticsearchmachine elasticsearch-ci/part-1
