### PR TITLE
ESQL: Fix flakiness in SessionUtilsTests

### LINKED ISSUE #135377: [CI] SessionUtilsTests testFromPages failing
**Build Scans:**
- [elasticsearch-intake #28985 / part3](https://gradle-enterprise.elastic.co/s/cnxx4pf5taoym)
- [elasticsearch-pull-request #94618 / part-3](https://gradle-enterprise.elastic.co/s/ywnc5isrc6jei)
- [elasticsearch-pull-request #94560 / part-3](https://gradle-enterprise.elastic.co/s/sdvvp2pk6t6vw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.session.SessionUtilsTests.testFromPages" -Dtests.seed=6C573E101E747273 -Dtests.locale=ar-LB -Dtests.timezone=Asia/Yakutsk -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.session.SessionUtilsTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testFromPages'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.RuntimeException: 2 arrays have not been released
```

**Issue Reasons:**
- [main] 3 failures in test testFromPages (3.6% fail rate in 84 executions)
- [main] 2 failures in step part-3 (3.6% fail rate in 56 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (3.6% fail rate in 55 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135398: [CI] SessionUtilsTests testCheckPagesBelowSize failing
**Build Scans:**
- [elasticsearch-intake #29015 / part3](https://gradle-enterprise.elastic.co/s/hqsc3rcugtcxe)
- [elasticsearch-pull-request #94704 / part-3](https://gradle-enterprise.elastic.co/s/gvq25yhqh5lmi)
- [elasticsearch-pull-request #94579 / part-3](https://gradle-enterprise.elastic.co/s/byheexsbj2amq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.session.SessionUtilsTests.testCheckPagesBelowSize" -Dtests.seed=8B56EFEDDE2C69A4 -Dtests.locale=ceb -Dtests.timezone=Asia/Yakutsk -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.session.SessionUtilsTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testCheckPagesBelowSize'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.RuntimeException: 2 arrays have not been released
```

**Issue Reasons:**
- [main] 3 failures in test testCheckPagesBelowSize (2.0% fail rate in 151 executions)
- [main] 2 failures in step part-3 (2.0% fail rate in 101 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.0% fail rate in 99 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by bpintea**
Fix unreleased arrays in SessionUtilsTests.

Closes #135377
Closes #135398

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/SessionUtilsTests.java [hunk 1]
```diff
@@ -172,6 +178,5 @@ private BlockFactory blockFactory(long maxBytes) {
     private static void enqueueBlock(BytesRefBlock.Builder builder, List<Page> pages) {
         Block block = builder.build();
         pages.add(new Page(block));
-        Releasables.close(builder);
```
Comment (bpintea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/SessionUtilsTests.java:175]: Change only makes sure `Releasables.close(builder)` is always called for a created `builder`.
The instance when this didn't happen was when the if-condition within the loop applied just as the while-condition no longer did. In this case a new `builder` was created, but not released.

**Review by fang-xing-esql — APPROVED** [review]

**Comment by bpintea** [comment]
Thanks Fang!
