### PR TITLE
Fix policy manager/parser absolute path checks

### LINKED ISSUE #122662: [CI] PolicyManagerTests class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6453 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/kybx3tmonsajq)
- [elasticsearch-periodic-platform-support #6453 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/oofwszbnhnmku)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests.testGetEntitlementsThrowsOnMissingPluginUnnamedModule" -Dtests.seed=A63A226DF322B467 -Dtests.locale=csw-Cans-CA -Dtests.timezone=Europe/Malta -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [8.18] 2 consecutive failures in class org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests
- [8.18] 2 failures in class org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests (1.6% fail rate in 122 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122663: [CI] PolicyParserTests testPolicyBuilderOnExternalPlugin failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6455 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ugghxuxo57mb6)
- [elasticsearch-periodic-platform-support #6455 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/csmk7j2oq7hk6)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyParserTests.testPolicyBuilderOnExternalPlugin" -Dtests.seed=C15722891840FE0B -Dtests.locale=tk -Dtests.timezone=AST -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyParserTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testPolicyBuilderOnExternalPlugin),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.entitlement.runtime.policy.PolicyParserException: [2:5] policy parsing error for [test-policy.yaml] in scope [entitlement-module-name] for entitlement type [files]: 'path' [/test/path/to/file] must be absolute
```

**Issue Reasons:**
- [8.x] 2 failures in test testPolicyBuilderOnExternalPlugin (1.5% fail rate in 132 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122664: [CI] PolicyParserTests testParseFiles failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6453 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/kybx3tmonsajq)
- [elasticsearch-periodic-platform-support #6453 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/oofwszbnhnmku)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyParserTests.testPolicyBuilder" -Dtests.seed=A63A226DF322B467 -Dtests.locale=seh -Dtests.timezone=Pacific/Wallis -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyParserTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testParseFiles),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.entitlement.runtime.policy.PolicyParserException: [2:5] policy parsing error for [test-policy.yaml] in scope [entitlement-module-name] for entitlement type [files]: 'path' [/test/path/to/file] must be absolute
```

**Issue Reasons:**
- [8.18] 2 consecutive failures in test testParseFiles
- [8.18] 2 failures in test testParseFiles (15.4% fail rate in 13 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122665: [CI] PolicyParserTests testPolicyBuilder failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6453 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/kybx3tmonsajq)
- [elasticsearch-periodic-platform-support #6453 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/oofwszbnhnmku)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyParserTests.testPolicyBuilder" -Dtests.seed=A63A226DF322B467 -Dtests.locale=seh -Dtests.timezone=Pacific/Wallis -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyParserTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testPolicyBuilder),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.entitlement.runtime.policy.PolicyParserException: [2:5] policy parsing error for [test-policy.yaml] in scope [entitlement-module-name] for entitlement type [files]: 'path' [/test/path/to/file] must be absolute
```

**Issue Reasons:**
- [8.18] 2 consecutive failures in test testPolicyBuilder
- [8.18] 2 failures in test testPolicyBuilder (1.6% fail rate in 122 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122666: [CI] PolicyParserFailureTests testEntitlementAbsolutePathWhenRelative failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6453 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/kybx3tmonsajq)
- [elasticsearch-periodic-platform-support #6453 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/oofwszbnhnmku)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyParserFailureTests.testEntitlementAbsolutePathWhenRelative" -Dtests.seed=A63A226DF322B467 -Dtests.locale=yue-Hans-CN -Dtests.timezone=Europe/Ljubljana -Druntime.java=23
```

**Applicable branches:**
8.18

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyParserFailureTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEntitlementAbsolutePathWhenRelative),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Expected exception PolicyParserException but no exception was thrown
```

**Issue Reasons:**
- [8.18] 2 consecutive failures in test testEntitlementAbsolutePathWhenRelative
- [8.18] 2 failures in test testEntitlementAbsolutePathWhenRelative (15.4% fail rate in 13 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122775: [CI] PolicyManagerTests testGetEntitlementsResultIsCached failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6455 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ugghxuxo57mb6)
- [elasticsearch-periodic-platform-support #6455 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/csmk7j2oq7hk6)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests.testGetEntitlementsResultIsCached" -Dtests.seed=C15722891840FE0B -Dtests.locale=ff-Latn-NG -Dtests.timezone=Europe/Madrid -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testGetEntitlementsResultIsCached),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [8.x] 2 failures in test testGetEntitlementsResultIsCached (1.5% fail rate in 132 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122776: [CI] PolicyManagerTests testDuplicateEntitlements failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6455 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ugghxuxo57mb6)
- [elasticsearch-periodic-platform-support #6455 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/csmk7j2oq7hk6)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests.testGetEntitlementsResultIsCached" -Dtests.seed=C15722891840FE0B -Dtests.locale=ff-Latn-NG -Dtests.timezone=Europe/Madrid -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testDuplicateEntitlements),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [8.x] 2 failures in test testDuplicateEntitlements (1.5% fail rate in 132 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122777: [CI] PolicyManagerTests testGetEntitlementsReturnsEntitlementsForPluginUnnamedModule failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6455 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ugghxuxo57mb6)
- [elasticsearch-periodic-platform-support #6455 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/csmk7j2oq7hk6)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests.testGetEntitlementsResultIsCached" -Dtests.seed=C15722891840FE0B -Dtests.locale=ff-Latn-NG -Dtests.timezone=Europe/Madrid -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testGetEntitlementsReturnsEntitlementsForPluginUnnamedModule),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [8.x] 2 failures in test testGetEntitlementsReturnsEntitlementsForPluginUnnamedModule (1.5% fail rate in 132 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122778: [CI] PolicyManagerTests testGetEntitlementsThrowsOnMissingPluginUnnamedModule failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6455 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ugghxuxo57mb6)
- [elasticsearch-periodic-platform-support #6455 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/csmk7j2oq7hk6)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests.testGetEntitlementsResultIsCached" -Dtests.seed=C15722891840FE0B -Dtests.locale=ff-Latn-NG -Dtests.timezone=Europe/Madrid -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyManagerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testGetEntitlementsThrowsOnMissingPluginUnnamedModule),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [8.x] 2 failures in test testGetEntitlementsThrowsOnMissingPluginUnnamedModule (1.5% fail rate in 132 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122779: [CI] PolicyParserFailureTests class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6455 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ugghxuxo57mb6)
- [elasticsearch-periodic-platform-support #6455 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/csmk7j2oq7hk6)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyParserFailureTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyParserFailureTests),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 2 failures in class org.elasticsearch.entitlement.runtime.policy.PolicyParserFailureTests (1.5% fail rate in 132 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ldematte**
This PR changes policy manager/parser tests to rely on real files; this would solve the related CI failures already. 
But we need to remove assert for absolute/relative paths too, as that won't work with mixed windows/linux/mac policies like we already have on server (e.g. /proc/meminfo)

closes #122662
closes #122663
closes #122664 
closes #122665 
closes #122666
closes #122775
closes #122776 
closes #122777 
closes #122778 
closes #122779

### CODE REVIEW

**Review by mosche — APPROVED** [review]
lgtm

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/entitlements/FilesEntitlement.java [hunk 1]
```diff
@@ -120,12 +120,10 @@ public int hashCode() {
         }
 
         static FileData ofPath(Path path, Mode mode) {
-            assert path.isAbsolute();
```
Comment (rjernst) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/entitlements/FilesEntitlement.java:123]: Why do we need to remove these asserts? We can specify absolute and relative paths in Windows. I don't think we should add leniency to make windows testing easier, let's adjust the tests so they aren't assuming `/` is the root path.

Comment (ldematte) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/entitlements/FilesEntitlement.java:123]: It's in the description; the tests are fixed, but the asserts will fail anyway in production code because we have unix paths in policies with a cluster running on windows and vice-versa.

Comment (rjernst) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/entitlements/FilesEntitlement.java:50]: I think we can solve the eg `/proc/meminfo` in a different way: we don't need to add those to the policy on windows. Relaxing the assertions make it unclear why `path` and `relative_path` exist when there is no enforcement on what exists there.

Comment (ldematte) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/entitlements/FilesEntitlement.java:50]: There will always be the matter of policy files; unless we add platform-specific sections to them, we may end up with a mix of absolute paths for different platforms.
I don't think we want that complication (platform-specific sections); if we do, we can address this separately.
