### PR TITLE
Greedily advance safe commit on new global checkpoint

### LINKED ISSUE #48532: PeerRecoveryTargetServiceTests#testPrepareIndexForPeerRecovery failed in CI
This build fails: https://gradle-enterprise.elastic.co/s/a2blc36l3tb4k/console-log?task=:server:test

```
org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests > testPrepareIndexForPeerRecovery FAILED
    java.lang.AssertionError: 
    Expected: <48>
         but: was <47>
        at __randomizedtesting.SeedInfo.seed([C3F8AA3D7B611EE8:18764B67EA0E4848]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests.testPrepareIndexForPeerRecovery(PeerRecoveryTargetServiceTests.java:197)
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests.testPrepareIndexForPeerRecovery" -Dtests.seed=C3F8AA3D7B611EE8 -Dtests.security.manager=true -Dtests.locale=ar-OM -Dtests.timezone=MST7MDT -Dcompiler.java=12 -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by dnhatn**
Today we won't advance the safe commit on a new global checkpoint unless the last commit can become safe. This is not great if we have more than two commits as we can have a new safe commit sooner.

Closes #48532

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/engine/CombinedDeletionPolicy.java [hunk 1]
```diff
@@ -83,6 +84,7 @@ public void onCommit(List<? extends IndexCommit> commits) throws IOException {
             this.safeCommitInfo = SafeCommitInfo.EMPTY;
             this.lastCommit = commits.get(commits.size() - 1);
             this.safeCommit = commits.get(keptPosition);
+            this.nextSafeCommit = keptPosition == commits.size() - 1 ? null : commits.get(keptPosition + 1);
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/engine/CombinedDeletionPolicy.java]: `indexOfKeptCommits`filters out commits that dont match translog uuid. do we need to do the same here?

File: server/src/main/java/org/elasticsearch/index/engine/CombinedDeletionPolicy.java [hunk 2]
```diff
@@ -217,16 +219,12 @@ synchronized boolean hasSnapshottedCommits() {
...
-        final IndexCommit lastCommit = this.lastCommit;
-        if (safeCommit != lastCommit) { // Race condition can happen but harmless
-            final long maxSeqNoFromLastCommit = Long.parseLong(lastCommit.getUserData().get(SequenceNumbers.MAX_SEQ_NO));
-            // We can clean up the current safe commit if the last commit is safe
-            return globalCheckpointSupplier.getAsLong() >= maxSeqNoFromLastCommit;
-        }
-        return false;
+        final IndexCommit nextSafeCommit = this.nextSafeCommit;
+        return nextSafeCommit != null
+            && Long.parseLong(nextSafeCommit.getUserData().get(SequenceNumbers.MAX_SEQ_NO)) <= globalCheckpointSupplier.getAsLong();
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/index/engine/CombinedDeletionPolicy.java]: Could we just store the max-seq-no of `nextSafeCommit` instead? Not a big deal, but I think this method is called more frequently than `onCommit` and thus it seems more logical to parse out the number in `onCommit`.

**Review by henningandersen — APPROVED** [review]
LGTM. Thanks @dnhatn 

I left a very small optional comment only.

File: server/src/main/java/org/elasticsearch/index/engine/CombinedDeletionPolicy.java (hunk 1 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/CombinedDeletionPolicy.java]: Both the safe commit and the next safe commit should have the same translog UUID since we iterate the commit list in reverse.

File: server/src/main/java/org/elasticsearch/index/engine/CombinedDeletionPolicy.java (hunk 2 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/index/engine/CombinedDeletionPolicy.java]: Adjusted in https://github.com/elastic/elasticsearch/pull/48559/commits/d66389ab5df2b11b7a496bd8d86c3d778612a976.

**Review by ywelsch — APPROVED** [review]
LGTM
