### PR TITLE
ESQL: Fix functions emitting warnings with no source

### LINKED ISSUE #122588: ESQL: Functions not serializing their Source and emitting warnings
Some functions in ESQL doesn't serialize their Source. That's fine, as long as it isn't used.

However, some of those functions emit warnings with the `warnExceptions` annotation, which means that their use the Source to get the line numbers, and the text of the function.
If they are executed in a datanode after serialization, the warnings may not be correct.

This is an issue to track and fix them all.

Currently tracked functions that _may_ emit wrong warnings:
- [ ] `DateDiff` 
- [ ] `MvSlice`
- [ ] `MvSum`
- [ ] All children of `BinarySpatialFunction`
- [ ] `Replace`

Most of those aren't confirmed, they just happen to not serialize their source and have a `warnExceptions`

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/122588

- Replaced `Source.EMPTY.writeTo(out)` to `source().writeTo(out)` in functions emitting warnings
  - Did the same on all aggs, as Top emits an error on type resolution. This is not a bug, as type resolution errors should only happen in the coordinator. Another option would be changing Top to not generate that error there, and make it implement instead `PostAnalysisVerificationAware`
- In some cases, we don't even serialize an empty source. So I had to add a new `TransportVersion` to do so
  - As an special case, `ToLower` and `ToUpper` weren't serializing a source, but they don't emit warnings. As they were the only remaining functions not serializing the source, I added it there too

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/TestCaseSupplier.java [hunk 1]
```diff
@@ -117,6 +117,9 @@ public static List<TestCaseSupplier> stringCases(
     @Override
     public TestCase get() {
         TestCase supplied = supplier.get();
+        if (types.size() != supplied.getData().size()) {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/TestCaseSupplier.java:120]: The `for` below wasn't checking the case where the TestCase data had more types than the supplier. This required fixing some cases in Top and Case

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvSliceTests.java
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvSliceTests.java:1]: This was one of the affected functions by the "warnings but no source" problem, but it had no tests for them. So here I added them based on the function errors

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/predicate/operator/comparison/InTests.java [hunk 2]
```diff
@@ -332,6 +286,16 @@ private static void bytesRefs(List<TestCaseSupplier> suppliers, int items) {
         }));
     }
 
+    /**
+     * Returns a list with N dataType1, followed by 1 dataType2.
+     */
+    private static List<DataType> makeTypes(DataType dataType1, DataType dataType2, int n) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/predicate/operator/comparison/InTests.java:292]: Optional:
```suggestion
    private static List<DataType> typesList(DataType dataType1, DataType dataType2, int n) {
```

**Review by bpintea — APPROVED** [review]

**Review by astefan — COMMENTED** [review]
I was expecting to see some changes in IT tests as well, meaning warning message that started having proper line:column numbers.
Do you know why the change in this PR is not "visible" in IT tests?

**Comment by ivancea** [comment]
@astefan From what I saw, there are no CSV tests with warnings for those functions. I'll add some cases + capability for them to double-check.
Unless by "IT tests" you mean other tests I'm not aware of

**Comment by astefan** [comment]
I don't know exactly what we have and what don't for this particular set of functionality this PR is addressing, thus my evasiveness. I am ok with CSV IT tests. Since this involves serializations and, implicitly, type resolution on the data nodes, make sure the queries used trigger this fix properly.

**Review by astefan — APPROVED** [review]
LGTM
