### PR TITLE
Only verify global checkpoint if translog sync occurred

### LINKED ISSUE #46065: TranslogTests.testSyncConcurrently failed on 7.x
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/296/

```
./gradlew :server:test --tests "org.elasticsearch.index.translog.TranslogTests.testSyncConcurrently" -Dtests.seed=825A321609226E9F -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=pt-PT -Dtests.timezone=America/Fort_Wayne -Dcompiler.java=12 -Druntime.java=8
```

```
00:09:29   2> ago 27, 2019 6:09:25 PM com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
00:09:29   2> WARNING: Uncaught exception in thread: Thread[Thread-27,5,TGRP-TranslogTests]
00:09:29   2> java.lang.AssertionError: 
00:09:29   2> Expected: a value equal to or greater than <6484L>
00:09:29   2>      but: <6437L> was less than <6484L>
00:09:29   2> 	at __randomizedtesting.SeedInfo.seed([825A321609226E9F]:0)
00:09:29   2> 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
00:09:29   2> 	at org.junit.Assert.assertThat(Assert.java:956)
00:09:29   2> 	at org.junit.Assert.assertThat(Assert.java:923)
00:09:29   2> 	at org.elasticsearch.index.translog.TranslogTests.lambda$testSyncConcurrently$89(TranslogTests.java:3322)
00:09:29   2> 	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by dnhatn**
We only sync translog if the given offset hasn't synced yet. We can't verify the global checkpoint from the latest translog checkpoint unless a sync has occurred.

CI: https://gradle-enterprise.elastic.co/s/6eahrp3bejona

Closes #46065
Relates #45634

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java [hunk 1]
```diff
@@ -3305,21 +3305,24 @@ public void testSyncConcurrently() throws Exception {
                             }
                             assertNotNull(location);
                             long globalCheckpoint = lastGlobalCheckpoint.get();
+                            final boolean synced;
                             if (randomBoolean()) {
-                                translog.ensureSynced(location);
+                                synced = translog.ensureSynced(location);
                             } else {
-                                translog.sync();
+                                synced = translog.sync();
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/index/translog/TranslogTests.java]: I think we can simply set synced=true here in order to always do the check later. Since `sync()` always sync's if GCP is different from last sync'ed GCP, this should be OK. That also avoids the signature change on `Translog.sync()`

**Review by henningandersen — COMMENTED** [review]
Thanks for adding the additional test @dnhatn . I have a single comment on this only, otherwise looking good.

**Review by henningandersen — APPROVED** [review]
LGTM.

Thanks @dnhatn

**Comment by dnhatn** [comment]
Thanks @henningandersen.
