### PR TITLE
Fix uniquify to handle multiple successive duplicates

### LINKED ISSUE #126883: CollectionUtils.uniquify is incorrect in some cases
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

--

### Problem Description

`CollectionUtils.uniquify(new ArrayList<>(List.of(1, 20, 20, 30, 30, 50)), Comparator.naturalOrder())` produces `[1, 20, 30, 30, 50]` but should produce `[1, 20, 30, 50]`.

### Steps to Reproduce

This test when added to `CollectionUtilsTests` fails.

```
    public void testUniquifyTwoRuns() {
        assertUniquify(List.of(1, 20, 20, 30, 30, 50), Comparator.naturalOrder(), 4);
    }

```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by rjernst**
CollectionUtils.uniquify is based on C++ std::unique. This commit fixes the implementation to correctly match std::unique, so that successive ranges of duplicates are handled.

closes #126883

### CODE REVIEW

**Review by ldematte — APPROVED** [review]
LGTM

File: server/src/test/java/org/elasticsearch/common/util/CollectionUtilsTests.java [hunk 1]
```diff
@@ -78,6 +78,7 @@ public void testUniquify() {
         assertUniquify(List.of(1, 1, 1), Comparator.naturalOrder(), 1);
         assertUniquify(List.of(1, 2, 2, 3), Comparator.naturalOrder(), 3);
         assertUniquify(List.of(1, 2, 2, 2), Comparator.naturalOrder(), 2);
+        assertUniquify(List.of(1, 2, 2, 3, 3, 5), Comparator.naturalOrder(), 4);
```
Comment (lkts) [inline server/src/test/java/org/elasticsearch/common/util/CollectionUtilsTests.java:81]: I think this needs a stronger test. I was thinking about this:
1. Generate random int `s` for the number of unique items in list
2. Generate `s` unique numbers 
3. For each random generate random number of repeats (1  to 10)
4. Put everything in the list
5. uniquify the list
6. compare resulting list with a list of only unique numbers that we have from 2

**Comment by rjernst** [comment]
@ldematte I reworked this back to using iterators. I remembered that the reason to use iterators is to support linked lists, since doing `LinkedList.set(index, value)` is linear.

File: server/src/test/java/org/elasticsearch/common/util/CollectionUtilsTests.java (hunk 1 above)
Comment (rjernst) [reply server/src/test/java/org/elasticsearch/common/util/CollectionUtilsTests.java:82]: I added a random test, see [62cdd9a](https://github.com/elastic/elasticsearch/pull/126889/commits/62cdd9abfc06eac63550691fe6d79a3cf3842bd0)

**Review by lkts — APPROVED** [review]
Thank you!
