### PR TITLE
remove custom metadata if there is nothing to restore

### LINKED ISSUE #81247: Restore snapshot with include_global_state=true is not reverting some custom metadata
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16

**Description of the problem including expected versus actual behavior**:

According to the code:

https://github.com/elastic/elasticsearch/blob/0f108251341303dbf4afabaadc8f1d673a368b0c/server/src/main/java/org/elasticsearch/snapshots/RestoreService.java#L1203

and

https://github.com/elastic/elasticsearch/blob/0f108251341303dbf4afabaadc8f1d673a368b0c/server/src/main/java/org/elasticsearch/snapshots/RestoreService.java#L1410-L1422

when restoring global state from a snapshot we keep existing metadata as a baseline. This means some custom metadata items are going to be preserved as is if they are not present in a global state from the snapshot (if it was taken before the those were configured or even existed).

**Steps to reproduce**:

* start a new cluster
* configure a snapshot repository
* create a snapshot (with include_global_state=true)
* configure any custom metadata that could be restored from a snapshot (for example auto-follow pattern, but not data repository/stream/autoscaling)
restore from the snapshot (with include_global_state=true)

Expected result:

* new custom metadata is set to null

Actual result:

* new custom metadata is kept as is

### PR DESCRIPTION
**Pull request by idegtiarenko**
Currently when restoring global state from the snapshot we create new metadata from existing one and then override it with fields from the snapshot. This behavior could keep custom metadata from the current state if it is not explicitly created in the snapshot.

This bug was discovered when trying to remove auto-followers by restoring from the snapshot created on an empty cluster. Surprisingly such restore did not removed anything while still deleting remotes and breaking auto-followers. 

Closes: #81247
Blocked by: #82019

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/snapshots/RestoreService.java [hunk 1]
```diff
@@ -1480,16 +1478,19 @@ private void applyGlobalStateRestore(ClusterState currentState, Metadata.Builder
...
+            mdBuilder.removeCustomIf((key, value) -> value.isRestorable());
+
+            // restore customs from the snapshot
             if (metadata.customs() != null) {
-                for (Map.Entry<String, Metadata.Custom> cursor : metadata.customs().entrySet()) {
-                    if (RepositoriesMetadata.TYPE.equals(cursor.getKey()) == false
-                        && DataStreamMetadata.TYPE.equals(cursor.getKey()) == false
-                        && cursor.getValue() instanceof Metadata.NonRestorableCustom == false) {
+                for (var entry : metadata.customs().entrySet()) {
+                    if (entry.getValue().isRestorable()) {
```
Comment (idegtiarenko) [inline server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:1488]: This part is tested in SystemDataStreamSnapshotIT and AutoscalingSnapshotsIT. I am working on creating a IT for the scenario mentioned in the pr description.

Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:1488]: This behavior is also covered by CustomMetadataSnapshotIT

File: server/src/main/java/org/elasticsearch/snapshots/RestoreService.java [hunk 2]
```diff
@@ -1470,16 +1468,19 @@ private void applyGlobalStateRestore(ClusterState currentState, Metadata.Builder
                     mdBuilder.put(cursor);
                 }
             }
+
+            // override existing restorable customs (as there might be noting in snapshot to override them)
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:1472]:
```suggestion
            // override existing restorable customs (as there might be nothing in snapshot to override them)
```

File: server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java [hunk 3]
```diff
@@ -132,9 +133,14 @@
...
 
         EnumSet<XContentContext> context();
-    }
 
-    public interface NonRestorableCustom extends Custom {}
+        /**
+         * @return true if this custom could be restored from snapshot
+         */
+        default boolean isRestorable() {
+            return context().contains(XContentContext.SNAPSHOT);
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java:141]: I think this is fine, though I would like to hear the opinion of @original-brownbear.

**Review by henningandersen — COMMENTED** [review]
A few smaller comments, otherwise looking good.

File: server/src/main/java/org/elasticsearch/snapshots/RestoreService.java [hunk 4]
```diff
@@ -1470,16 +1468,19 @@ private void applyGlobalStateRestore(ClusterState currentState, Metadata.Builder
...
+            mdBuilder.removeCustomIf((key, value) -> value.isRestorable());
```
[the remark this answers is not in the document]
Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:1473]: Most of the functionality is covered by `org.elasticsearch.snapshots.CustomMetadataSnapshotIT#testRestoreCustomMetadata`, but you are right, the part of returning back to null settings is missing. I will add it.

[the remark this answers is not in the document]
Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/snapshots/RestoreService.java:1477]: Updated `CustomMetadataSnapshotIT` with `isSnapshottableMetadataInitialized` and added unit test for `removeCustomIf`

File: server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java (hunk 3 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java:142]: Provided the context values are all correct (this was a bit of an issue when me and Ievgen last checked if I remember correctly) this should be fine. I couldn't find any way this would not work since the context isn't something we read from the repo but just have per class => all good from my end.

File: server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java [hunk 5]
```diff
@@ -129,9 +130,14 @@
...
         EnumSet<XContentContext> context();
-    }
 
-    public interface NonRestorableCustom extends Custom {}
+        /**
+         * @return true if this custom could be restored from snapshot
+         */
+        default boolean isRestorable() {
+            return true;
+        }
```
[the remark this answers is not in the document]
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java:143]: That list makes sense to me.

**Review by henningandersen — APPROVED** [review]
LGTM.
