### PR TITLE
Unmute entsearch/rules/40_rule_query_search/Perform a rule query with an organic query that must be rewritten to another query type

### LINKED ISSUE #141200: [CI] EnterpriseSearchRestIT test {p0=entsearch/rules/40_rule_query_search/Perform a rule query with an organic query that must be rewritten to another query type} failing
**Build Scans:**
- [elasticsearch-intake #33694 / part2](https://gradle-enterprise.elastic.co/s/lyiock63xpcks)
- [elasticsearch-pull-request #115889 / part-2](https://gradle-enterprise.elastic.co/s/tcp5g2d64afa2)
- [elasticsearch-pull-request #115751 / part-2](https://gradle-enterprise.elastic.co/s/7ck22t2t6i37q)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ent-search:yamlRestTest" --tests "org.elasticsearch.xpack.entsearch.EnterpriseSearchRestIT.test {p0=entsearch/rules/40_rule_query_search/Perform a rule query with an organic query that must be rewritten to another query type}" -Dtests.seed=42F114C685AAC3B4 -Dtests.locale=nl-SR -Dtests.timezone=America/Argentina/Tucuman -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.entsearch.EnterpriseSearchRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bp0%3Dentsearch%2Frules%2F40_rule_query_search%2FPerform%20a%20rule%20query%20with%20an%20organic%20query%20that%20must%20be%20rewritten%20to%20another%20query%20type%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: java.lang.AssertionError: 
Expected: <4>
     but: was <0>
```

**Issue Reasons:**
- [main] 3 failures in test test {p0=entsearch/rules/40_rule_query_search/Perform a rule query with an organic query that must be rewritten to another query type} (0.4% fail rate in 842 executions)
- [main] 2 failures in step part-2 (0.7% fail rate in 296 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (0.6% fail rate in 340 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by Mikep86**
Unmutes the test muted by https://github.com/elastic/elasticsearch/issues/141200. I cannot reproduce this test failure, so I suggest we unmute it for now and see if it happens again.

~~A timeboxed analysis led me to `SparseVectorQueryBuilder#doToQuery` as the most likely culprit. That method rewrites to (the equivalent of) `MatchNoDocsQuery` when `queryVectors == null`, which may be what's happening here. However, that should never happen and if it does, it should be handled as an error. I changed `doToQuery` to raise an error on this case so that we can catch it in the future. Happy to put this in a separate PR if others feel this should be done independent of unmuting the test.~~ Changing this in a separate PR.

Fixes https://github.com/elastic/elasticsearch/issues/141200

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/search/SparseVectorQueryBuilder.java [hunk 1]
```diff
@@ -217,7 +217,7 @@ protected void doXContent(XContentBuilder builder, Params params) throws IOExcep
     @Override
     protected Query doToQuery(SearchExecutionContext context) throws IOException {
         if (queryVectors == null) {
-            return EMPTY_QUERY_VECTORS;
```
Comment (Mikep86) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/search/SparseVectorQueryBuilder.java:220]: @kderusso Any insight into why we didn't throw an error here initially?

**Review by john-wagster — APPROVED** [review]
seems reasonable to me based on what I reviewed as well

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/search/SparseVectorQueryBuilder.java (hunk 1 above)
Comment (Mikep86) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/search/SparseVectorQueryBuilder.java:220]: This change breaks `SparseVectorQueryBuilderTests#testMustRewrite`. I'm going to separate it out into its own PR for cleanliness.

Comment (kderusso) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/search/SparseVectorQueryBuilder.java:220]: Only thing I can think of is maybe it was to catch an empty field? Looking back at it now I think your fix is correct.

**Review by kderusso — APPROVED** [review]
Went through some past history and can't find a good reason for the match no docs query, so I think this was a bug. Thanks for fixing!
