### PR TITLE
Always set terminated_early if terminate_after is set in the search request

### LINKED ISSUE #33949: SearchResponse.isTerminatedEarly() returns null instead of false
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_181

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04

**Description of the problem including expected versus actual behavior**: `org.elasticsearch.action.search.SearchResponse.isTerminatedEarly()` returns `null` when the result list is too short. It should only return `true` or `false`.

I just upgraded from Elasticsearch 5.6 to 6.4.1 and using the Java transport API, I got an unexpected `NullPointerException` in my existing code by forwarding the return value of `isTerminatedEarly()` as a `boolean`. I had a quick look through git blame, but I don't see any immediate and obvious changes to the function itself, so the behaviour must have changed somewhere deeper in the system.

**Steps to reproduce**:
Run a query which returns a result list shorter than the termination threshold and `isTerminatedEarly()` returns `null`.

### PR DESCRIPTION
**Pull request by jimczi**
Today we set `terminated_early` to true in the response if the query terminated
early due to `terminate_after`. However if `terminate_after` is smaller than
the number of documents in a shard we don't set the flag in the response indicating
that the query was exhaustive. This change fixes this disprepancy by setting
terminated_early to false in the response if the number of documents that match
the query is smaller than the provided `terminate_after` value.

Closes #33949

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/query/QueryPhase.java [hunk 1]
```diff
@@ -282,6 +282,10 @@ static boolean execute(SearchContext searchContext,
             } finally {
                 searchContext.clearReleasables(SearchContext.Lifetime.COLLECTION);
             }
+            if (searchContext.terminateAfter() != SearchContext.DEFAULT_TERMINATE_AFTER
+                    && queryResult.terminatedEarly() == null) {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/query/QueryPhase.java]: I find this logic a bit confusing, would it be possible to have only true or false in QuerySearchResult? What is the difference between null and false again?

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/query/QueryPhase.java]: In 6x we use `true` if the search was early terminated due to `terminate_after` and `null` in all other cases. However in 5x we set it to `false` if `terminate_after` is used but the number of documents that match the query is smaller than the terminate_after value. We broke this behavior in 6x which returns `null` in this case. I think it's less confusing to always set the early terminate flag if `terminate_after` is set in the query, this way users can rely on the fact that it will not be null in the response.

Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/query/QueryPhase.java]: I agree that it is less confusing this way, and I was wondering if it could be made even less confusing by removing the null invariant from QuerySearchResult. I take it that it's more complicated than it seems though.

**Review by javanna — APPROVED** [review]
