### PR TITLE
Fix accessing main files in transport version resources (#133349)

### LINKED ISSUE #133432: [CI] TransportVersionValidationFuncTest cannot change committed ids to a branch failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10246 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/f7sroxjaurxms)
- [elasticsearch-periodic-platform-support #10246 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/hkjllht7ny6t2)
- [elasticsearch-periodic-platform-support #10246 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/uc5izoil7fxaw)
- [elasticsearch-periodic-platform-support #10239 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/bcwiy7jpzrlne)
- [elasticsearch-periodic-platform-support #10239 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/v7775x5zlx2fk)
- [elasticsearch-periodic-platform-support #10239 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/2gznehuf5t2gs)
- [elasticsearch-periodic-platform-support #10232 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/osiqqrzhkfwcg)
- [elasticsearch-periodic-platform-support #10232 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/jnt6skho4f2bk)
- [elasticsearch-periodic-platform-support #10232 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/hm6fgy7uvbokc)
- [elasticsearch-periodic-platform-support #10225 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/kntopbgivk3ik)

**Reproduction Line:**
```
null
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.gradle.internal.transport.TransportVersionValidationFuncTest),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('cannot%20change%20committed%20ids%20to%20a%20branch'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.spockframework.runtime.ConditionNotSatisfiedError: Condition not satisfied:

normalized(givenOutput).contains(normalized(expected))
|          |            |        |          |
|          |            false    |          Transport version definition file [myserver/src/main/resources/transport/definitions/named/existing_92.csv] has modified primary id from 8123000 to 8500000
|          |                     Transport version definition file [myserver/src/main/resources/transport/definitions/named/existing_92.csv] has modified primary id from 8123000 to 8500000
|          =======================================
|          Elasticsearch Build Hamster says Hello!
|            Gradle Version        : 9.0.0
|            OS Info               : Windows Server 2025 10.0 (amd64)
|            JDK Version           : 21.0.7+6-LTS (Eclipse Temurin)
|            JAVA_HOME             : C:/Users/buildkite/.gradle/jdks/eclipse_adoptium-21-amd64-windows.2
|            Random Testing Seed   : A98A
[truncated]
```

**Issue Reasons:**
- [8.19] 18 consecutive failures in test cannot change committed ids to a branch
- [8.19] 17 consecutive failures in step windows-2025_checkpart1_platform-support-windows
- [8.19] 16 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [8.19] 17 consecutive failures in step windows-2019_checkpart1_platform-support-windows
- [8.19] 17 consecutive failures in pipeline elasticsearch-periodic-platform-support
- [8.19] 50 failures in test cannot change committed ids to a branch (64.9% fail rate in 77 executions)
- [8.19] 17 failures in step windows-2025_checkpart1_platform-support-windows (100.0% fail rate in 17 executions)
- [8.19] 16 failures in step windows-2022_checkpart1_platform-support-windows (100.0% fail rate in 16 executions)
- [8.19] 17 failures in step windows-2019_checkpart1_platform-support-windows (100.0% fail rate in 17 executions)
- [8.19] 17 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 17 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by rjernst**
closes #133430
closes #133431
closes #133432

### CODE REVIEW

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionLatest.java [hunk 1]
```diff
@@ -9,14 +9,17 @@
 
 package org.elasticsearch.gradle.internal.transport;
 
+import java.nio.file.Path;
```
Comment (shukrenzibat-crypto) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionLatest.java:12]: - [ ]

Comment (shukrenzibat-crypto) [reply build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionLatest.java:12]:
~~~~

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionLatest.java [hunk 2]
```diff
@@ -9,14 +9,17 @@
...
+
```
Comment (shukrenzibat-crypto) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionLatest.java:13]: ****

File: build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionDefinition.java [hunk 3]
```diff
@@ -9,11 +9,13 @@
 
 package org.elasticsearch.gradle.internal.transport;
 
+import java.nio.file.Path;
```
Comment (shukrenzibat-crypto) [inline build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/transport/TransportVersionDefinition.java:12]:
```suggestion
import java.nio.file.Path;
```

**Review by shukrenzibat-crypto — COMMENTED** [review]
10

**Review by shukrenzibat-crypto — COMMENTED** [review]
11
