### PR TITLE
ESQL: Fix fully pruned aggregates

### LINKED ISSUE #106427: ESQL: keep after stats can lead to non-aggregating query
Consider the query
```
              FROM test
              | STATS by emp_no
              | EVAL x = 1
              | KEEP x
```
This should return a row (with the value `x = 1`) for _each unique value of `emp_no`_.

Instead, it returns one row for each document in `test`.

Inspecting the optimized logical plan shows why (to repro, add as test to `LogicalPlanOptimizerTests.java`):
```
EsqlProject[[x{r}#4]]
\_Eval[[1[INTEGER] AS x]]
  \_Limit[1000[INTEGER]]
    \_EsRelation[test][_meta_field{f}#12, emp_no{f}#6, first_name{f}#7, ge..]
```
The `EsRelation` at the root is wrong, instead there has to be a logical plan that produces the number of unique `emp_no` values. (`Aggregation` can do this.)

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/106427, https://github.com/elastic/elasticsearch/issues/107082, https://github.com/elastic/elasticsearch/issues/102425

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 1]
```diff
@@ -998,11 +1012,17 @@ public LogicalPlan apply(LogicalPlan plan) {
...
                         if (remaining != null) {
                             if (remaining.isEmpty()) {
-                                recheck = true;
-                                p = aggregate.child();
+                                // We still need to have a plan that produces 1 row per group.
+                                if (aggregate.groupings().isEmpty()) {
+                                    p = emptyRow(aggregate.source());
+                                } else {
+                                    // Aggs cannot produce pages with 0 columns, so retain one grouping.
+                                    remaining = List.of((NamedExpression) aggregate.groupings().get(0));
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1023]: Instead of casting, use Expressions.wrapAsNamed or even better make a reference to the group (to avoid copying the alias and its nested expression): Expressions.attribute()

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 2]
```diff
@@ -223,6 +223,69 @@ public void testEmptyProjectionInStat() {
...
+     * EsqlProject[[x{r}#7]]
+     * \_Eval[[1[INTEGER] AS x]]
+     *   \_Limit[1000[INTEGER]]
+     *     \_Aggregate[[emp_no{f}#10],[emp_no{f}#10]]
+     *       \_EsRelation[test][_meta_field{f}#16, emp_no{f}#10, first_name{f}#11, ..]
+     */
+    public void testEmptyProjectInStatWithGroupAndEval() {
+        var plan = plan("""
+            from test
+            | stats c = count(salary) by emp_no
```
Comment (costin) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:269]: Make the example more complicated by adding a filter before stats, use the output of the stats inside the eval and then project it away. the whole dependency tree should be folded out.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec [hunk 3]
```diff
@@ -1227,6 +1227,29 @@ vals:l
...
+| DROP c
+;
+
+x:d
+3.14
+;
+
+emptyProjectInStatWithGroupAndEval
+FROM employees
+| STATS c = COUNT(salary) BY emp_no
```
Comment (costin) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec:1243]: Please add another test, one without any agg (just grouping - STATS by emp_no), another one with multiple groups and another one with a diff agg than count (e.g STATS MIN(salary) by languages).

**Review by costin — APPROVED** [review]

**Comment by alex-spies** [comment]
I'll also add a test to ensure that https://github.com/elastic/elasticsearch/issues/107082 is fixed as it's the same problem.

**Review by bpintea — APPROVED** [review]
LGTM

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.13|[](https://github.com/elastic/elasticsearch/pull/107144)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
