### PR TITLE
Exclude invalid url-encoded strings from randomized tests

### LINKED ISSUE #71077: [CI] URLDecodeProcessorTests testTargetField failing
Reproduced locally for me. Using the same repro line on `master` passed so seems to be specific to `7.x`.

**Build scan:**
https://gradle-enterprise.elastic.co/s/qsk55cm3gwe22/tests/:modules:ingest-common:test/org.elasticsearch.ingest.common.URLDecodeProcessorTests/testTargetField

**Reproduction line:**
`./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.URLDecodeProcessorTests.testTargetField" -Dtests.seed=7D92339A368D8737 -Dtests.security.manager=true -Dtests.locale=sk -Dtests.timezone=Antarctica/Macquarie -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.ingest.common.URLDecodeProcessorTests&tests.test=testTargetField

**Failure excerpt:**
```
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "񪅙"

  at __randomizedtesting.SeedInfo.seed([7D92339A368D8737:16D445542B2A6206]:0)
  at java.net.URLDecoder.decode(URLDecoder.java:194)
  at org.elasticsearch.ingest.common.URLDecodeProcessor.apply(URLDecodeProcessor.java:28)
  at org.elasticsearch.ingest.common.URLDecodeProcessor.process(URLDecodeProcessor.java:36)
  at org.elasticsearch.ingest.common.URLDecodeProcessor.process(URLDecodeProcessor.java:18)
  at org.elasticsearch.ingest.common.AbstractStringProcessor.execute(AbstractStringProcessor.java:75)
  at org.elasticsearch.ingest.common.AbstractStringProcessorTestCase.testTargetField(AbstractStringProcessorTestCase.java:135)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by danhermann**
The randomized testing framework produces some input strings that are not valid URL-encoded strings so the URLDecodeProcessor correctly throws an exception. This change retries any tests that use a string that cannot be URL decoded.

Fixes #71077.

### CODE REVIEW

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/AbstractStringProcessorTestCase.java [hunk 1]
```diff
@@ -127,12 +127,23 @@ public void testNonStringValueWithIgnoreMissing() throws Exception {
...
+        } while (isSupportedValue(ingestDocument.getFieldValue(fieldName, Object.class, ignoreMissing)) == false);
         String targetFieldName = fieldName + "foo";
-        Processor processor = newProcessor(fieldName, randomBoolean(), targetFieldName);
+        Processor processor = newProcessor(fieldName, ignoreMissing, targetFieldName);
         processor.execute(ingestDocument);
         assertThat(ingestDocument.getFieldValue(targetFieldName, expectedResultType()), equalTo(expectedResult(fieldValue)));
     }
+
+    protected boolean isSupportedValue(Object value) {
+        return false;
```
Comment (martijnvg) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/AbstractStringProcessorTestCase.java:147]: I think the default should return `true` here? Because now if this method isn't overwritten, the do-while loop never ends (i think this is why the some of these test fail).

Comment (danhermann) [reply modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/AbstractStringProcessorTestCase.java]: Yep, thanks. I renamed the `isSupportedValue` method from `isUnsupportedValue` but forgot to change the default return value. 🤦‍♂️

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by jbaiera — APPROVED** [review]
LGTM
