### PR TITLE
#101193 Preserve Step Info Across ILM Auto Retries

### LINKED ISSUE #101193: [ILM] Still show step_info for is_auto_retryable_error
### Description

👋 howdy, team! 

Indices can end up in [ILM Explain](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-explain-lifecycle.html) `is_auto_retryable_error:true` and `failed_step_retry_count: +1` looping without (consistent) UI/API information of there being a problem requiring manual user intervention. 

E.g. if you [bootstrap ILM](https://www.elastic.co/guide/en/elasticsearch/reference/8.2/getting-started-index-lifecycle-management.html#ilm-gs-alias-bootstrap) poorly and `hot/rollover/check-rollover-ready` infinitely [errors known issue](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-error-handling.html#_index_lifecycle_rollover_alias_x_does_not_point_to_index_y) `does not point to index` in Elasticsearch logs, the UI/API oscillates but usually does _not_ report any issues to resolve

```
> GET filebeat-8.10.3-electrum_log-2023.10.13/_ilm/explain?only_errors=true
{ "indices": {} }

> GET filebeat-8.10.3-electrum_log-2023.10.13/_ilm/explain
{
  "indices": {
    "filebeat-8.10.3-electrum_log-2023.10.13": {
      "index": "filebeat-8.10.3-electrum_log-2023.10.13",
      "managed": true,
      "policy": "365-days-default",
      "index_creation_date_millis": 1697155202751,
      "time_since_index_creation": "8.66d",
      "lifecycle_date_millis": 1697155202751,
      "age": "8.66d",
      "phase": "hot",
      "phase_time_millis": 1697903938553,
      "action": "rollover",
      "action_time_millis": 1697155203899,
      "step": "check-rollover-ready",
      "step_time_millis": 1697903938553,
      "is_auto_retryable_error": true,
      "failed_step_retry_count": 624,
      "phase_execution": {
        "policy": "365-days-default",
        "phase_definition": {
          "min_age": "0ms",
          "actions": {
            "rollover": {
              "max_age": "1d",
              "max_primary_shard_size": "50gb"
            }
          }
        },
        "version": 4,
        "modified_date_in_millis": 1695888703972
      }
    }
  }
}
```

while in reality the index is fully blocked from progressing as shown in Elasticsearch logs ...
```
[instance-0000000013] policy [365-days-default] for index [filebeat-8.10.3-electrum_metrics-2023.10.17] failed on step [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}]. Moving to ERROR step
java.lang.IllegalArgumentException: index.lifecycle.rollover_alias [alias-electrum_metrics] does not point to index [filebeat-8.10.3-electrum_metrics-2023.10.17] ...
```
... which will require user intervention to resolve. 

A small portion of the time, I can get the example index to show `hot/rollover/ERROR` via API...
```
> GET filebeat-8.10.3-electrum_log-2023.10.13/_ilm/explain?only_errors=true
{
  "indices": {
    "filebeat-8.10.3-electrum_log-2023.10.13": {
      "index": "filebeat-8.10.3-electrum_log-2023.10.13",
      "managed": true,
      "policy": "365-days-default",
      "index_creation_date_millis": 1697155202751,
      "time_since_index_creation": "8.67d",
      "lifecycle_date_millis": 1697155202751,
      "age": "8.67d",
      "phase": "hot",
      "phase_time_millis": 1697903938553,
      "action": "rollover",
      "action_time_millis": 1697155203899,
      "step": "ERROR",
      "step_time_millis": 1697904538636,
      "failed_step": "check-rollover-ready",
      "is_auto_retryable_error": true,
      "failed_step_retry_count": 624,
      "step_info": {
        "type": "illegal_argument_exception",
        "reason": "setting [index.lifecycle.rollover_alias] for index [filebeat-8.10.3-electrum_log-2023.10.13] is empty or not defined"
      },
      "phase_execution": {
        "policy": "365-days-default",
        "phase_definition": {
          "min_age": "0ms",
          "actions": {
            "rollover": {
              "max_age": "1d",
              "max_primary_shard_size": "50gb"
            }
          }
        },
        "version": 4,
        "modified_date_in_millis": 1695888703972
      }
    }
  }
}
```
... which I suspect is related to A) the ILM polling interval and B) the index doesn't error while ILM thinks its executing. However, across a 30min check it only returned error information for <5mins cumulatively so the vast majority of the time I didn't know/realize manual intervention was required.

🙏🏼 Will you kindly consider
1. Having certain `IllegalArgumentException` errors override `IsAutoRetryable` so that intervention-required errors consistently surface? 
2. Always report `step_info` for `is_auto_retryable_error` so that users/Support can tell there is manual intervention required. (Alternatively consider `last_step_info` to signal maybe previous attempt failed but next might not.)

### PR DESCRIPTION
**Pull request by lukewhiting**
This PR does a few things:

* Adds a new field to the Explain ILM lifecycle endpoint (`<target>/_ilm/explain`) called `previous_step_info` that contains the previous step runs `step_info` field contents
* Logic in the Lifecycle step transition logic to copy the step info of a previous run into the new field
* Docs for the new field

Bonus content includes:

* Refactored and simplified test object mutation logic
* ~Refactored test's to use recommended `Clock` interface for time dependent tests rather than custom supplier~ Reverted this as it's too risky / unrelated to PR

Commits are atomic so feel free to review commit by commit if you prefer reviewing smaller chunks

### CODE REVIEW

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java [hunk 1]
```diff
@@ -289,6 +289,7 @@ private static LifecycleExecutionState updateExecutionStateToStep(
 
         // clear any step info or error-related settings from the current step
         updatedState.setFailedStep(null);
+        updatedState.setPreviousStepInfo(existingState.stepInfo());
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java:292]: Don't we also want these statements here https://github.com/elastic/elasticsearch/blob/b977a337e3d28e67e37e5d36634a81a89ef9e705/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java#L183-L183
and here?
https://github.com/elastic/elasticsearch/blob/b977a337e3d28e67e37e5d36634a81a89ef9e705/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java#L429

Or am I missing a reason why we don't need them there?

File: docs/reference/ilm/apis/explain.asciidoc [hunk 2]
```diff
@@ -329,3 +335,6 @@ is true, {ilm-init} will retry the failed step automatically.
 <3> Shows the number of attempted automatic retries to execute the failed
 step.
 <4> What went wrong
+<5> If the step before output a `step_info` or the previous attempt to auto retry this step failed, this field will
```
[the remark this answers is not in the document]
Comment (lukewhiting) [reply docs/reference/ilm/apis/explain.asciidoc:338]: Yeah I agree it's a bit clunky... How about 'produces' or 'emits'?

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java (hunk 1 above)
Comment (lukewhiting) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java:292]: I don't believe so... Line 183 is in a method that calls `updateExecutionStateToStep(...)` on line 173 so the copy should already have happened.

Line 429 is in the method that writes the step info into the internal cluster state so any modifications of the step info will have happened further up the call chain already.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java [hunk 3]
```diff
@@ -133,78 +129,46 @@ public void testGetCurrentStepKey() {
...
+            case 13 -> newState.setSnapshotIndexName(randomValueOtherThan(toMutate.snapshotIndexName(), this::randomString));
+            case 14 -> newState.setSnapshotName(randomValueOtherThan(toMutate.snapshotName(), this::randomString));
+            case 15 -> newState.setDownsampleIndexName(randomValueOtherThan(toMutate.downsampleIndexName(), this::randomString));
+            case 16 -> newState.setIsAutoRetryableError(randomValueOtherThan(toMutate.isAutoRetryableError(), ESTestCase::randomBoolean));
+            case 17 -> newState.setFailedStepRetryCount(randomValueOtherThan(toMutate.failedStepRetryCount(), ESTestCase::randomInt));
+            case 18 -> {
+                return LifecycleExecutionState.EMPTY_STATE;
+            }
+            default -> throw new IllegalStateException("unknown randomization branch");
         }
```
Comment (gmarouli) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionStateTests.java:157]: <3

**Review by gmarouli — COMMENTED** [review]
This is looking good, I would like to double check though if we could test this a bit more, maybe see if we could set-up a minimal integration test that would capture this behaviour. @lukewhiting what do you think? Do you think it's worth it to see if we can make something reasonable?

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java (hunk 1 above)
Comment (lukewhiting) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java:292]: The line numbers you quoted don't seem to line up with what I'm seeing in IndexLifecycleTransition.java :-/ Line 101 is the end of a throw statement and 102 is just a closing bracket... Could you confirm the file and commit hash those line numbers refer to? 

But talking in general about when the update cluster state method is called, I guess there may be a difference in how I interpreted the requirements... I targeted this to only copy the `step_info` at the start of a step (IE to preserve it across runs) and for that copy of the previous attempt to remain unchanged through the next run attempt.

If we were to add copy logic to the method at 429 (Or methods calling it), `previous_step_info` would get updated and overwritten each time the step progress is written to `step_info` during the execution of a step, meaning error messages from a previous run might disappear as that attempt progresses, not really fixing the underlying SDH request for it to stick around during the whole next attempt.

It's also entirely possible I haven't understood things correctly 😅 Feel free to grab me for a quick face to face chat if you think I'm not grasping the logic here :-)

**Comment by lukewhiting** [comment]
> This is looking good, I would like to double check though if we could test this a bit more, maybe see if we could set-up a minimal integration test that would capture this behaviour. @lukewhiting what do you think? Do you think it's worth it to see if we can make something reasonable?

I think an IT would be a great idea! I would also love to do a bit of functional testing on this before it's merged. I'm still not 100% sure on how I would get the cluster into a suitable state to test this so would be great if you have some time to pair on this perhaps?

File: docs/reference/ilm/apis/explain.asciidoc [hunk 4]
```diff
@@ -329,3 +335,5 @@ is true, {ilm-init} will retry the failed step automatically.
 <3> Shows the number of attempted automatic retries to execute the failed
 step.
 <4> What went wrong
+<5> If the step before produces a `step_info` or the previous attempt to auto retry this step failed, this field will contain a copy of that previous attempt's `step_info` field for diagnostic purposes as `step_info` is overwritten during
+each new attempt.
```
[the remark this answers is not in the document]
Comment (lukewhiting) [reply docs/reference/ilm/apis/explain.asciidoc:339]: That's much better wording. Thanks!

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java (hunk 1 above)
Comment (nielsbauman) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java:292]: It looks like Mary is referring to:
https://github.com/elastic/elasticsearch/blob/80dd56398f855923df0c0117abd098fd3023ce36/x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/ExecuteStepsUpdateTask.java#L101-L101

I think your point about not wanting to override `previous_step_info` on _every_ `step_info` makes sense. Otherwise, in the scenario that the issue/SDH describes, `previous_step_info` would get overridden on the second automatic retry attempt. So line 429 indeed doesn't need to be updated - and 183 is indeed already covered by the `updateExecutionStateToStep` call before.

**Comment by lukewhiting** [comment]
> Don't forget to close the issue in the PR description.

Yep :-) I have linked it to this PR so GitHub should auto close it once it's merged but I'll make a note to double check

**Comment by lukewhiting** [comment]
Local functional testing complete.

Method: 
1) Index template created with rollover policy step
2) Index (`ilm-error-test-000001`) created to match template and dummy doc inserted
3) Wait for ILM explain on index to confirm in `check-rollover-ready` state
4) Create new index (`ilm-error-test-000000`) that also matches the template
5) Manually create alias (ilm-error-test) for second index that matches `rollover_alias` of policy
6) ILM explain for the first index enters Error state with step info `index.lifecycle.rollover_alias [ilm-error-test] does not point to index [ilm-error-test-000001]`
7) Wait for auto retry
8) ILM explain for `ilm-error-test-000001` shows following output that matches expected with `failed_step_retry_count` incremented by 1 and `previous_step_info` populated with previous attempts step info.

Test Output:

```json
{
  "indices": {
    "ilm-error-test-000001": {
      "index": "ilm-error-test-000001",
      "managed": true,
      "policy": "365-days-default",
      "index_creation_date_millis": 1727179631766,
      "time_since_index_creation": "19.92m",
      "lifecycle_date_millis": 1727179631766,
      "age": "19.92m",
      "phase": "hot",
      "phase_time_millis": 1727180790334,
      "action": "rollover",
      "action_time_millis": 1727179631820,
      "step": "check-rollover-ready",
      "step_time_millis": 1727180790334,
      "is_auto_retryable_error": true,
      "failed_step_retry_count": 1,
      "previous_step_info": {
        "type": "illegal_argument_exception",
        "reason": "index.lifecycle.rollover_alias [ilm-error-test] does not point to index [ilm-error-test-000001]"
      },
      "phase_execution": {
        "policy": "365-days-default",
        "phase_definition": {
          "min_age": "0ms",
          "actions": {
            "rollover": {
              "max_age": "30d",
              "max_primary_shard_docs": 200000000,
              "min_docs": 1,
              "max_primary_shard_size": "50gb"
            }
          }
        },
        "version": 1,
        "modified_date_in_millis": 1727179591769
      }
    }
  }
}
```

**Comment by nielsbauman** [comment]
@lukewhiting That functional test looks great! Well done! I think it would also be worthwhile to ensure the `previous_step_info` isn't cleared after the _second_ retry, but we can do that in the integration test that we'll be writing.

**Comment by gmarouli** [comment]
@lukewhiting nice work coming up with the test scenario!

> Local functional testing complete.
> 
> Method:
> 
> 1. Index template created with policy that has a rollover step
> 2. Index (`ilm-error-test-000001`) created to match template and dummy doc inserted
> 3. Wait for ILM explain on index to confirm in `check-rollover-ready` state
> 4. Create new index (`ilm-error-test-000000`) that also matches the template
> 5. Manually create alias (`ilm-error-test`) for second index that matches `rollover_alias` of policy
> 6. ILM explain for the first index enters Error state with step info `index.lifecycle.rollover_alias [ilm-error-test] does not point to index [ilm-error-test-000001]`
> 7. Wait for auto retry
> 8. ILM explain for `ilm-error-test-000001` shows following output that matches expected with `failed_step_retry_count` incremented by 1 and `previous_step_info` populated with previous attempts step info.
> 
> Test Output:
> 
> ```json
> {
>   "indices": {
>     "ilm-error-test-000001": {
>       "index": "ilm-error-test-000001",
>       "managed": true,
>       "policy": "365-days-default",
>       "index_creation_date_millis": 1727179631766,
>       "time_since_index_creation": "19.92m",
>       "lifecycle_date_millis": 1727179631766,
>       "age": "19.92m",
>       "phase": "hot",
>       "phase_time_millis": 1727180790334,
>       "action": "rollover",
>       "action_time_millis": 1727179631820,
>       "step": "check-rollover-ready",
>       "step_time_millis": 1727180790334,
>       "is_auto_retryable_error": true,
>       "failed_step_retry_count": 1,
>       "previous_step_info": {
>         "type": "illegal_argument_exception",
>         "reason": "index.lifecycle.rollover_alias [ilm-error-test] does not point to index [ilm-error-test-000001]"
>       },
>       "phase_execution": {
>         "policy": "365-days-default",
>         "phase_definition": {
>           "min_age": "0ms",
>           "actions": {
>             "rollover": {
>               "max_age": "30d",
>               "max_primary_shard_docs": 200000000,
>               "min_docs": 1,
>               "max_primary_shard_size": "50gb"
>             }
>           }
>         },
>         "version": 1,
>         "modified_date_in_millis": 1727179591769
>       }
>     }
>   }
> }
> ```

I think this could be simplified in an java rest test for example:

1. Decrease ILM polling frequency to reduce the test duration
2. Index template created without the rollover alias but with a regular alias and with policy that has a rollover step with `max_doc: 1`
2. Index (`ilm-error-test-000001`) created to match template and dummy doc inserted
3. Wait for ILM explain on index to confirm in `check-rollover-ready` state
4. ILM explain will throw the error `setting [index.lifecycle.rollover_alias] for index` 
5. Wait for auto retry
6. ILM explain for `ilm-error-test-000001` shows following output that matches expected with `failed_step_retry_count` incremented by 1 and `previous_step_info` populated with previous attempts step info.

It's very similar with what you have just a few less steps. Let me know if you want to work on it together.

Nit: I think the `test-update-serverless` can be removed because ILM is not used in serverless. That should speed up ci as well.

**Comment by lukewhiting** [comment]
@nielsbauman @gmarouli Integration test for new field added based on the above manual testing: https://github.com/elastic/elasticsearch/pull/113187/commits/91dac7ed7e0b214a42e9202b38f791fd308d5ff0

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java [hunk 5]
```diff
@@ -257,6 +258,66 @@ public void testExplainOrder() throws Exception {
...
+                + "      \"actions\": {"
+                + "        \"rollover\": {"
+                + "          \"max_docs\": 1"
+                + "        }"
+                + "      }"
+                + "    }"
+                + "  }"
+                + "}"
+                + "}"
+        );
```
Comment (gmarouli) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:279]: Nit: I find `"""` a bit  more readable in case you want to give it a try.

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java [hunk 6]
```diff
@@ -257,6 +258,66 @@ public void testExplainOrder() throws Exception {
...
+                + "  \"settings\": {"
+                + "    \"index.lifecycle.name\": \""
+                + policyName
+                + "\","
+                + "    \"index.lifecycle.rollover_alias\": \""
+                + aliasName
+                + "\""
+                + "  }"
+                + "}"
+                + "}"
```
Comment (gmarouli) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:301]: Same here

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java (hunk 5 above)
Comment (lukewhiting) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:279]: Ohh yeah we're targeting > Java 15 aren't we :D 100% I'll switch it over for a multiline string

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java (hunk 1 above)
Comment (gmarouli) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycleTransition.java:292]: I see, so we only set the previous info when we update the cluster state with the next step not during it's execution. Clear thanks!

**Review by gmarouli — APPROVED** [review]
Left a minor comment but LGTM :)

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java (hunk 5 above)
Comment (lukewhiting) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java]: Done

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java (hunk 6 above)
Comment (lukewhiting) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java]: Done :-)
