### PR TITLE
Fix failures in SessionFactoryLoadBalancingTests

### LINKED ISSUE #32190: [CI] SessionFactoryLoadBalancingTests testRoundRobinWithFailures fails
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/1190/console

Could not reproduce with:
```
REPRODUCE WITH: gradlew :x-pack:plugin:security:test \
  -Dtests.seed=16B5154ACCB4889F \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.support.SessionFactoryLoadBalancingTests \
  -Dtests.method="testRoundRobinWithFailures" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-QA \
  -Dtests.timezone=US/Central

REPRODUCE WITH: gradlew :x-pack:plugin:security:test \
  -Dtests.seed=16B5154ACCB4889F \
  -Dtests.class=org.elasticsearch.xpack.security.authc.ldap.support.SessionFactoryLoadBalancingTests \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC
```

Looks like there are connection issues:
```
10:27:12   2> WARNING: Suite execution timed out: org.elasticsearch.xpack.security.authc.ldap.support.SessionFactoryLoadBalancingTests
10:27:12   1> java.net.BindException: Address already in use: connect
10:27:12   2> ==== jstack at approximately timeout time ====
10:27:12   1> 	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[?:1.8.0_172]
10:27:12   2> "elasticsearch[SessionFactoryLoadBalancingTests thread pool][[timer]]" ID=2333 TIMED_WAITING
10:27:12   2> 	at java.lang.Thread.sleep(Native Method)
10:27:12   1> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_172]
10:27:12   2> 	at org.elasticsearch.threadpool.ThreadPool$CachedTimeThread.run(ThreadPool.java:543)
10:27:12   2> "LDAP Listener Thread (listening on port 63056)" ID=2331 RUNNABLE (in native code)
10:27:12   2> 	at java.net.DualStackPlainSocketImpl.accept0(Native Method)
10:27:12   2> 	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
10:27:12   1> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_172]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.access$101(MockSocket.java:32) ~[mocksocket-1.2.jar:?]
10:27:12   2> 	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
10:27:12   2> 	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.lambda$connect$0(MockSocket.java:66) ~[mocksocket-1.2.jar:?]
10:27:12   1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.connect(MockSocket.java:65) ~[mocksocket-1.2.jar:?]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.connect(MockSocket.java:59) ~[mocksocket-1.2.jar:?]
10:27:12   2> 	- locked java.net.SocksSocketImpl@1d4bb36e
10:27:12   1> 	at java.net.Socket.<init>(Socket.java:434) ~[?:1.8.0_172]
10:27:12   1> 	at java.net.Socket.<init>(Socket.java:328) ~[?:1.8.0_172]
10:27:12   1> 	at org.elasticsearch.mocksocket.MockSocket.<init>(MockSocket.java:54) ~[mocksocket-1.2.jar:?]
```

This leads to test timeouts later.

### PR DESCRIPTION
**Pull request by jaymode**
This change aims to fix failures in the session factory load balancing
tests that mock failure scenarios. For these tests, we randomly shut
down ldap servers and bind a client socket to the port they were
listening on. Unfortunately, we would occasionally encounter failures
in these tests where a socket was already in use and/or the port
we expected to connect to was wrong and in fact was to one of the ldap
instances that should have been shut down.

The failures are caused by the behavior of certain operating systems
when it comes to binding ports and wildcard addresses. It is possible
for a separate application to be bound to a wildcard address and still
allow our code to bind to that port on a specific address. So when we
close the server socket and open the client socket, we are still able
to establish a connection since the other application is already
listening on that port on a wildcard address. Another variant is that
the os will allow a wildcard bind of a server socket when there is
already an application listening on that port for a specific address.

In order to do our best to prevent failures in these scenarios, this
change does the following:

1. Binds a client socket to all addresses in an awaitBusy
2. Adds assumption that we could bind all valid addresses
3. In the case that we still establish a connection to an address that
   we should not be able to, try to bind and expect a failure of not
   being connected

Closes #32190

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java [hunk 1]
```diff
@@ -94,18 +97,19 @@ public void testRoundRobinWithFailures() throws Exception {
...
         final List<InMemoryDirectoryServer> ldapServersList = Arrays.asList(ldapServers);
-        final InetAddress local = InetAddress.getByName("localhost");
-        final MockServerSocket mockServerSocket = new MockServerSocket(0, 0, local);
+        final MockServerSocket mockServerSocket = new MockServerSocket(0, 0);
         final List<Thread> listenThreads = new ArrayList<>();
         final CountDownLatch latch = new CountDownLatch(ldapServersToKill.size());
         final CountDownLatch closeLatch = new CountDownLatch(1);
         try {
+            final AtomicBoolean success = new AtomicBoolean(true);
+            final List<Socket> openMockSockets = Collections.synchronizedList(new ArrayList<>());
```
Comment (bizybot) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java]: I think you wanted to use this, later on, to close them at the end of the test, currently, it is not being used other than collecting the sockets.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java [hunk 2]
```diff
@@ -160,76 +230,163 @@ private MockSocket openMockSocket(InetAddress remoteAddress, int remotePort, Ine
...
+            ldapServersToKill.add(ldapServers[0]); // always kill the first one
+        } else {
+            ldapServersToKill = Collections.singletonList(ldapServers[0]);
         }
+        final List<InMemoryDirectoryServer> ldapServersList = Arrays.asList(ldapServers);
+        final MockServerSocket mockServerSocket = new MockServerSocket(0, 0);
+        final List<Thread> listenThreads = new ArrayList<>();
+        final CountDownLatch latch = new CountDownLatch(ldapServersToKill.size());
+        final CountDownLatch closeLatch = new CountDownLatch(1);
+        final List<Socket> openMockSockets = Collections.synchronizedList(new ArrayList<>());
```
Comment (bizybot) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java]: same here, this can be used at the end of test to close the open sockets.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java [hunk 3]
```diff
@@ -114,15 +118,58 @@ public void testRoundRobinWithFailures() throws Exception {
                 // a mock server socket.
                 // NOTE: this is not perfect as there is a small amount of time between the shutdown
                 // of the ldap server and the opening of the socket
-                logger.debug("opening mock server socket listening on [{}]", port);
+                logger.debug("opening mock client sockets bound to [{}]", port);
                 Runnable runnable = () -> {
```
Comment (bizybot) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java]: may be extract this runnable code into a class `PortBlocker` or some other name?

**Review by bizybot — COMMENTED** [review]
Overall LGTM, should do the trick. I have a few comments and suggestions. Thank you for tackling this.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/LdapTestCase.java [hunk 4]
```diff
@@ -85,11 +88,12 @@ public void startLdap() throws Exception {
                     ldapPassword
                 );
                 X509ExtendedKeyManager keyManager = CertParsingUtils.keyManager(ks, ldapPassword, KeyManagerFactory.getDefaultAlgorithm());
-                final SSLContext context = SSLContext.getInstance("TLSv1.2");
+                final SSLContext context = SSLContext.getInstance(XPackSettings.DEFAULT_SUPPORTED_PROTOCOLS.get(0));
                 context.init(new KeyManager[] { keyManager }, null, null);
                 SSLServerSocketFactory serverSocketFactory = context.getServerSocketFactory();
                 SSLSocketFactory clientSocketFactory = context.getSocketFactory();
-                listeners.add(InMemoryListenerConfig.createLDAPSConfig("ldaps", null, 0, serverSocketFactory, clientSocketFactory));
+                listeners.add(InMemoryListenerConfig.createLDAPSConfig("ldaps", InetAddress.getLoopbackAddress(), 0,
```
[the remark this answers is not in the document]
Comment (jaymode) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/LdapTestCase.java]: Good catch

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java (hunk 1 above)
Comment (jaymode) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/ldap/support/SessionFactoryLoadBalancingTests.java]: We don't need this, so I removed it
