### PR TITLE
Only allow rebalance operations to run if all shard store data is available

### LINKED ISSUE #14387: Shards relocating during rolling restarts
This behaviour is reproducible in v1.6.0 through 2.0.0.  

Expected during rolling restarts that no shard relocations will occur, however there is shard movement occurring while the cluster is in a yellow health state.  

Steps to reproduce:
 1. Create a cluster with at least 3 nodes, 1 index with 2 shards + 1 replica (4 shards total), and index some data.
 2. Stop all indexing
 3. Set allocation: none
 4. _all/_flush/synced
 5. restart a single node
 6. reenable allocation

At step 6, shards are observed to be relocating, in addition to any recovery by sync_id that has occurred.  After recoveries and relocations, the cluster will change to green state.  This was tested in slow motion by limiting bandwidth to one of the nodes in the cluster.

Relocations are **not** observed in a 2 node cluster, or when restarting the entire cluster.

### PR DESCRIPTION
**Pull request by s1monw**
This commit prevents running rebalance operations if the store allocator is
still fetching async shard / store data to prevent pre-mature rebalance decisions
which need to be reverted once shard store data is available. This is typically happening
on rolling restarts which can make those restarts extremely painful.

Closes #14387

this is the 1.7 backport of #14591

### CODE REVIEW

**Comment by s1monw** [comment]
@bleskes can you take a quick look - it's the 1.7 backport

File: src/test/java/org/elasticsearch/test/InternalTestCluster.java [hunk 1]
```diff
@@ -1251,7 +1251,7 @@ public void restartRandomNode(RestartCallback callback) throws Exception {
      * Restarts a random data node in the cluster
      */
     public void restartRandomDataNode() throws Exception {
-        restartRandomNode(EMPTY_CALLBACK);
+        restartRandomDataNode(EMPTY_CALLBACK);
```
Comment (bleskes) [inline src/test/java/org/elasticsearch/test/InternalTestCluster.java]: :)

**Comment by bleskes** [comment]
LGTM
