### PR TITLE
ES|QL: Remove redundant sorts from execution plan

### LINKED ISSUE #120803: ESQL: MV_EXPAND and Sort: wrong optimizations or unplannable with "unknown physical plan node [OrderExec]"
Because `MV_EXPAND` generally cannot be pushed down past a `SORT`, it can cause situations where a `SORT`/`OrderBy` node cannot be combined with a downstream `LIMIT` node. When we cannot combine an `OrderBy` with a `Limit`, it gets mapped to a `OrderExec` - a physical plan node that we cannot map to an operator because we don't implement unbounded sorts (sorts without a built-in limit, i.e. TopNs).

In some cases, queries with `MV_EXPAND` and `SORT` just fail with the cryptic message `unknown physical plan node [OrderExec]`. In other cases, the query is optimized to make it run _somehow_, but I believe this is not actually correct for all cases.

I think this requires:
- A better error message. In fact, I think we shouldn't ever map to `OrderExec`. We probably should implement `PostOptimizationVerificationAware` on the `OrderBy` class and have the verification fail if a node is even present after optimization, ideally with a suggestion on what a user can try to do.
- Double checking the rule `AddDefaultTopN` for correctness.

In the following examples, consider a simple index `test` with fields `field1` and `field2`.

**Example 1**
```
from test* | sort field1 | mv_expand field1 | sort field2 | limit 1
```
This should be impossible to run, but the query **does not fail**. That's because `AddDefaultTopN` turns the `OrderBy` into a `TopN` with limit 10000:
```
[2025-01-24T15:33:30,464][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.AddDefaultTopN applied
TopN[[Order[field2{f}#26,ASC,LAST]],2[INTEGER]]     = TopN[[Order[field2{f}#26,ASC,LAST]],2[INTEGER]]
\_MvExpand[field1{f}#25,field1{r}#27,null]          = \_MvExpand[field1{f}#25,field1{r}#27,null]
  \_OrderBy[[Order[field1{f}#25,ASC,LAST]]]         !   \_TopN[[Order[field1{f}#25,ASC,LAST]],10000[INTEGER]]
    \_EsRelation[test*][field1{f}#25, field2{f}#26] =     \_EsRelation[test*][field1{f}#25, field2{f}#26]
```
This is **simply wrong** in cases where the top 10k documents _by `field1`_ do not include the single top 1 document `by field2`. However, it would be correct to eliminate the `sort field1` altogether, because after the `mv_expand field1` we sort again, anyway. It'd also be correct to exchange the positions of the `mv_expand field1` with `sort field2` because sorting by a non-expanded field is unaffected by the expansion. That means the query is equivalent to
```
from test* | sort field1 | sort field2 | mv_expand field1| limit 1
```
where the two `sorts` next to each other would be pruned by `PushDownAndCombineOrderBy`. This would end up performing the `TopN` operation before the `mv_expand`, allowing us to push this down to Lucene and making the query fast.

**Example 2**
```
from test* | sort field1 | mv_expand field2 | sort field2 | limit 1
```
Again, `AddDefaultTopN` wrongly discards anything other than the top 10k documents by `field1`:
```
[2025-01-24T15:40:45,503][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.AddDefaultTopN applied
TopN[[Order[field2{r}#35,ASC,LAST]],2[INTEGER]]     = TopN[[Order[field2{r}#35,ASC,LAST]],2[INTEGER]]
\_MvExpand[field2{f}#34,field2{r}#35,null]          = \_MvExpand[field2{f}#34,field2{r}#35,null]
  \_OrderBy[[Order[field1{f}#33,ASC,LAST]]]         !   \_TopN[[Order[field1{f}#33,ASC,LAST]],10000[INTEGER]]
    \_EsRelation[test*][field1{f}#33, field2{f}#34] =     \_EsRelation[test*][field1{f}#33, field2{f}#34]
```
In this case, it'd be correct to push down `mv_expand field2` past `sort field1`. If we did that, we'd have two sorts next to each other, essentially as if we had written
```
from test* | mv_expand field2 | sort field1 | sort field2 | limit 1
```
and in this case, the `sort field1` gets correctly eliminated:
```
[2025-01-24T15:45:03,381][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule logical.PushDownAndCombineOrderBy applied
Limit[1[INTEGER]]                                     = Limit[1[INTEGER]]
\_OrderBy[[Order[field2{r}#43,ASC,LAST]]]             = \_OrderBy[[Order[field2{r}#43,ASC,LAST]]]
  \_OrderBy[[Order[field1{f}#41,ASC,LAST]]]           !   \_MvExpand[field2{f}#42,field2{r}#43,null]
    \_MvExpand[field2{f}#42,field2{r}#43,null]        !     \_EsRelation[test*][field1{f}#41, field2{f}#42]
      \_EsRelation[test*][field1{f}#41, field2{f}#42] ! 
```

**Example 3**
```
from test* | sort field1 | mv_expand field1 | sort field1 | limit 1
```
It'd be correct to eliminate  the first `sort field1`. It'd be incorrect _per se_ to exchange the `mv_expand field1` with any of the `sort`s left or right of it to achieve that.

**Example 4**
```
from test* | sort field1 | mv_expand field2 | sort field1 | limit 1
```
It'd be correct to eliminate the first or second `sort field1`. It'd be correct _per se_ to exchange the `mv_expand field1` with any of the `sort`s left or right of it to achieve that. But eliminating/pushgin down the rightmost `sort field1` would lead to a potentially more optimial plan due to being able to push down a `Top1` to Lucene.

**Example 5**
```
from test* | limit 10000 | sort field1 | mv_expand field2 | sort field2 | limit 2
```
In this case, there's not even `AddDefaultTopN` jumping in to the rescue (even though it did so wrongly in Example 2):
```
"error":{"root_cause":[{"type":"esql_illegal_argument_exception","reason":"unknown physical plan node [OrderExec]"}],"type":"esql_illegal_argument_exception","reason":"unknown physical plan node [OrderExec]"},"status":500}
```
Similarly to Example 2, the first `sort field1` is actually fine to eliminate.

**Example 6**
```
from test* | limit 10000 | sort field1 | mv_expand field1 | sort field2 | limit 2
```
The same as in Example 5, we get an illegal argument exception with a 500. But again, the `sort field1` is redundant.

### LINKED ISSUE #120817: ESQL: LOOKUP JOIN and Sort: wrong optimizations or unplannable with "unknown physical plan node [OrderExec]
The same problems from https://github.com/elastic/elasticsearch/issues/120803 also occur with `LOOKUP JOIN`. Although, there may be different solutions because `LOOKUP JOIN` preserves the sort order if there is one.

To summarize:
There are situations where a SORT/OrderBy node cannot be combined with a downstream LIMIT node when there's a `LOOKUP JOIN` in between. When we cannot combine an OrderBy with a Limit, it gets mapped to a OrderExec - a physical plan node that we cannot map to an operator because we don't implement unbounded sorts (sorts without a built-in limit, i.e. TopNs).

In contrast to `MvExpand`, the optimization rule `AddDefaultTopN` doesn't apply because it only works with unary plans (although its application wouldn't be correct, anyway), so more queries fail (instead of running, but incorrectly) with the cryptic message `unknown physical plan node [OrderExec]`.

Similarly to `MV_EXPAND`, I think this requires:

- A better error message. In fact, I think we shouldn't ever map to `OrderExec`. We probably should implement `PostOptimizationVerificationAware` on the OrderBy class and have the verification fail if a node is even present after optimization, ideally with a suggestion on what a user can try to do.
- A new optimization rule that _somehow_ leads to eliminating unbounded sorts, by moving them around, somehow (but correctly) combining them with `Limit`s into `TopN`s, or straight up globally analyzing the plan and checking if the sort can just be removed.

In the following examples, consider a `test` index with fields `x` and `a`, and a lookup index `lookup` with fields `x` and `y`.

**Example 1**:
```
from test | sort x | lookup join lookup on x | sort y

{"error":{"root_cause":[{"type":"esql_illegal_argument_exception","reason":"unknown physical plan node [OrderExec]"}],"type":"esql_illegal_argument_exception","reason":"unknown physical plan node [OrderExec]"},"status":500}
```
The `sort y` is not pushable because it requires a field from `lookup`. But the `sort x` could be pulled up, so the two sorts are next to each other and the `sort y` eliminates the `sort x`.

The combinations `sort some_field | lookup join ...` and `lookup join ... | sort some_field` are always interchangeable as long as `some_field` (or, more generally, all fields that we sort on) exist _before and after_ the `lookup join`. Note that `lookup join` will shadow attributes which are not the join key in case of name conflicts!

**Example 2**:
```
from test | sort a | lookup join lookup on x | sort x

{"error":{"root_cause":[{"type":"esql_illegal_argument_exception","reason":"unknown physical plan node [OrderExec]"}],"type":"esql_illegal_argument_exception","reason":"unknown physical plan node [OrderExec]"},"status":500}
```
Here, both the `sort a` and the `sort x` could be pushed up/down past the `lookup join`, and would in both cases lead to an elimination of the earlier sort. However, in terms of performance it's likely better to have the sort done before the lookup join as long as it's possible to turn that into a `TopN`. Because some times, we can push down a `TopN` to Lucene - and otherwise, performing the `lookup join` on _all documents_ is mighty wasteful.

**Summary**
- `SORT` should likely be pushed down past `LOOKUP JOINs` whenever possible.
- When there is a `SORT` before and after `LOOKUP JOIN`, we should try to eliminate the earlier one if that's correct - or at least issue a useful error message so a user can remove that `SORT` manually.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes: https://github.com/elastic/elasticsearch/issues/120817
Fixes: https://github.com/elastic/elasticsearch/issues/120803

When we have multiple SORT commands in a query, some of them could be redundant.

Eg. 

```
from test | sort x | mv_expand x | sort y | limit 1

from test | sort x | lookup join lookup on x | sort y | limit 1
```

in both cases, the first SORT is practically irrelevant, as the second SORT will reorder the results, and the commands in-between don't rely on the order of results.

In addition, since the second SORT "absorbes" the LIMIT, the first SORT will remain unbounded, and it is problematic, since ES|QL does not support unbounded sort.

This change adds an optimization rule that finds and removes redundant sorts.

A SORT is redundant if all the following conditions are met:
- it is before another SORT.
- all the commands between the two SORTs do not rely on the order of results.

Eg. in `FROM idx | ... | SORT x | <command1> | ... | <commandN> | SORT y`, `SORT x` can be considered redundant:
- because `SORT y` will reorder the results
- but only if none of `<command1>`, `<commandN>` rely on the order of results

Types of commands that could rely on input order are:
- LIMIT: it takes first N results, and if the input is ordered, that order matters
- EVAL with window functions: eg. functions that, for a record, also consider the content of previous/next N records
- STREAMSTATS
- any commands with an inner limit (eg. like MV_EXPAND before [this change](https://github.com/elastic/elasticsearch/pull/120411))

~~At this stage we don't support window functions and STREAMSTATS, but in future we could, so to avoid regressions we consider EVAL and STATS as relevant for order for now.~~

Today we don't support window functions and STREAMSTATS, and we already had rules that do the same thing and don't consider these cases (the old `PruneOrderByBeforeStats` rule), so we'll consider EVAL, FILTER and STATS safe for now.

~~Given this limitation, `AddDefaultTopN` is still in place to make a couple of tests pass, but as reported [here](https://github.com/elastic/elasticsearch/issues/120803), it is most likely incorrect and needs a double-check.~~

Since in some cases we can still have unbounded sorts (eg. `| sort | mv_expand | where`), we also let OrderBy implement `PostOptimizationVerificationAware` and fail validation in a more graceful way.

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -1839,10 +1839,9 @@ public void testCombineOrderByThroughFilter() {
 
     /**
      * Expected
-     * TopN[[Order[first_name{f}#170,ASC,LAST]],1000[INTEGER]]
-     *  \_MvExpand[first_name{f}#170]
-     *    \_TopN[[Order[emp_no{f}#169,ASC,LAST]],1000[INTEGER]]
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1844]: Notice that here you are losing a performance aspect: `mv_expand` is applied on all documents. The idea with a sort (and the **default** pushed down `limit`) in front of `mv_expand` was to have fewer documents to expand from because the expansion is, theoretically, creating even more rows. Before this PR, each node was getting 1000 docs, mv_expanded them and a final sort performed. With this PR, each node is expanding everything, then sorting.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/RemoveRedundantSort.java [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+ *
+ * "sort y" will become a TopN, but "sort x" will remain unbounded, so the query could not be executed.
+ *
+ * In most cases though, last SORT make the previous SORTs redundant,
+ * ie. it will re-sort previously sorted results
+ * often with a different order.
+ *
+ * This rule finds and removes redundant SORTs, making the plan executable.
+ */
+public class RemoveRedundantSort extends OptimizerRules.OptimizerRule<TopN> {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/RemoveRedundantSort.java:41]: It makes sense to combine this with `PruneOrderByBeforeStats` since the logic is similar.
Remove -> Prune

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/RemoveRedundantSort.java [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+                // || unary instanceof Eval
+                // || unary instanceof Aggregate
+                ) {
+                    p = unary.child();
+                    continue;
+                }
+            } else if (p instanceof Join lj) {
+                p = lj.left();
+                // TODO do it also on the right-hand side?
+                continue;
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/RemoveRedundantSort.java:82]: Make the function recursive and let it run on both sides.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/RemoveRedundantSort.java [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+        }
+        return plan.transformDown(p -> {
+            if (p == redundant) {
+                return redundant.child();
+            }
+            return p;
+        });
+    }
+
+    private OrderBy findRedundantSort(TopN plan) {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/RemoveRedundantSort.java:57]: Return a list to perform only one modification (and traversals) on the tree.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/RemoveRedundantSort.java [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+        OrderBy redundant = findRedundantSort(plan);
+        if (redundant == null) {
+            return plan;
+        }
+        return plan.transformDown(p -> {
+            if (p == redundant) {
+                return redundant.child();
+            }
+            return p;
+        });
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/RemoveRedundantSort.java:54]: A bottom up traversal would help collect all pruned sorts in one traversal instead of a top-down per sort:
- those that occur before stats
- those that occur before other sorts

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/OrderBy.java [hunk 6]
```diff
@@ -109,4 +110,9 @@ public void postAnalysisVerification(Failures failures) {
             }
         });
     }
+
+    @Override
+    public void postOptimizationVerification(Failures failures) {
+        failures.add(fail(this, "The query cannot be executed because it would require unbounded sort"));
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/OrderBy.java:116]: I'd rephrase the error message to include an action item for the user: `Unbounded sort not supported yet, please add a limit"

**Review by costin — COMMENTED** [review]
It's great to allow more queries - left a few comments regarding the rule implementation.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java [hunk 7]
```diff
@@ -0,0 +1,116 @@
...
+                    || unary instanceof RegexExtract
+                    || unary instanceof InlineStats
+                    || unary instanceof Lookup
+                // IMPORTANT
+                // If we introduce window functions or order-sensitive aggs (eg. STREAMSTATS),
+                // the previous sort could actually become relevant
+                // so we have to be careful with plans that could use them, ie. the following
+                    || unary instanceof Filter
+                    || unary instanceof Eval
+                    || unary instanceof Aggregate) {
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java:100]: This is safe _now_, as long as we don't have window functions (and, in general, functions/aggs that rely on the order of the input).
We can decide to keep it like this for now and review it when we introduce such capabilities, or we can decide to be more paranoid about future regressions and discard such cases, but in this case we won't be able to completely avoid unbounded sorts.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1]: Let's try to come up with situations where an unbounded sort is unavoidable, and let's add tests for it. I have two reproducers at least:

```
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '
{
  "query": "row x = [1,2,3], y = 1 | sort y | mv_expand x | where x > 2"
}'
{"error":{"root_cause":[{"type":"verification_exception","reason":"Found 1 problem\nline 1:26: Unbounded sort not supported yet, please add a limit"}],"type":"verification_exception","reason":"Found 1 problem\nline 1:26: Unbounded sort not supported yet, please add a limit"},"status":400}
```

Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1]:
```
curl -u elastic-admin:elastic-password -H "Content-Type: application/json" "127.0.0.1:9200/languages" -XPUT -d '{
  "mappings": {        
        "properties": {"language_code": {"type": "integer"}, "name": {"type": "keyword"}}}, "settings": {"index": {"mode": "lookup"}}}'

curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt" -d '
{
  "query": "row language_code = 1, name = \"foo\" | sort name | lookup join languages on language_code | where name == \"English\""
}'

{"error":{"root_cause":[{"type":"verification_exception","reason":"Found 1 problem\nline 1:39: Unbounded sort not supported yet, please add a limit"}],"type":"verification_exception","reason":"Found 1 problem\nline 1:39: Unbounded sort not supported yet, please add a limit"},"status":400}
```

Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1]: The latter _can_ actually be solved by pushing down the lookup join past the `sort` - which'd require ugly renaming due to shadowing. (One of the lookup fields is called `name`, too.) But pushing down past sorts is not always a good idea. For instance, in something like `... | SORT foo | LOOKUP JOIN idx ON field | LIMIT 10`, we really want the limit to be duplicated downwards, not the sort to be pulled upwards.

Let's open a follow-up issue to investigate these situations.

**Review by alex-spies — COMMENTED** [review]
I have 2 small testing suggestions and examples for when unbounded sorts still happen.

Important to point out: with this PR, we won't consider remaining unbounded sorts as bugs anymore, and may miss out on their visibility via 500 status codes. (Relevant e.g. for Serverless.)
Because of this, I think we should point this out in our [limitations](https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-limitations.html), mention that users can help themselves via adding a `LIMIT` + are welcome to open a bug report in case they find an unbounded sort that is actually bounded.

**Review by alex-spies — COMMENTED** [review]
Reviewed everything but the tests. The main rule implementation looks to be correct to me, but I have minor suggestions on how to maybe make it more robust for the future.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/OrderBy.java [hunk 8]
```diff
@@ -109,4 +110,9 @@ public void postAnalysisVerification(Failures failures) {
             }
         });
     }
+
+    @Override
+    public void postOptimizationVerification(Failures failures) {
+        failures.add(fail(this, "Unbounded sort not supported yet, please add a limit"));
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/OrderBy.java:116]: nit: maybe we could include the source in the error message to make this easier for users to understand.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java [hunk 9]
```diff
@@ -0,0 +1,116 @@
...
+                if (toCheck.isEmpty()) {
+                    return result;
+                } else {
+                    p = toCheck.remove(0);
+                }
+            } else if (p instanceof OrderBy ob) {
+                result.put(ob, null);
+                p = ob.child();
+            } else if (p instanceof UnaryPlan unary) {
+                if (unary instanceof Project
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java:86]: +1 on a marker interface (say `SortAware`) under capabilities package so that commands can signal this behavior and the rule can pick it up without extra code modifications.
The rule would then perform a top-down transform and keep only the first sort for a `SortAware` (by default Limit to form topN).

P.S. LogicalPlan is a base class, utility methods (assuming they are used beyond just one rule) should be added elsewhere under `PlannerUtils` or `LogicalPlans`.

**Review by costin — COMMENTED** [review]
"what Alex said"

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1]: Thanks Alex, I'm adding more tests

I also created an issue for the case above: https://github.com/elastic/elasticsearch/issues/121884

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/OrderBy.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/OrderBy.java:116]: 👍 
BWC won't be a problem, right? We are never sending OrderExec to data nodes afaik (we only send a FragmentExec with a logical plan)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+                }
+                return p;
+            });
+        } else {
+            return plan;
+        }
+    }
+
+    private IdentityHashMap<OrderBy, Void> findRedundantSort(LogicalPlan plan) {
+        List<LogicalPlan> toCheck = new ArrayList<>();
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java]: With the addition of `SortAware` interface this method is becoming much smaller and easier to understand.

If you don't mind, I'd prefer to keep the implicit recursion; the difference in terms of readability is really minimal now and it makes me more comfortable in terms of stack depth.

**Comment by luigidellaquila** [comment]
Thanks for the feedback @alex-spies @costin, I added another round of changes that should address your comments

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 11]
```diff
@@ -7270,4 +7233,301 @@ public void testFunctionNamedParamsAsFunctionArgument() {
...
+
+    }
+
+    public void testUnboundedSortSimple() {
+        var query = """
+              ROW x = [1,2,3], y = 1
+              | SORT y
+              | MV_EXPAND x
+              | WHERE x > 2
+            """;
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:7464]: suggestion: Could we have a simple test like this but for LOOKUP JOIN? This test is a nice minimal example.

**Review by alex-spies — APPROVED** [review]
This is super nice. I have only minor suggestions. Thanks Luigi!

**Review by alex-spies — COMMENTED** [review]
nit: maybe it makes sense to move tests related to the new optimizer rule into a dedicated file. The LogicalPlanOptimizerTests file is already huge and it's hard to see what's tested and not.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+ * <code>
+ * | SORT x | MY_COMMAND
+ * </code>
+ * <p>
+ * is equivalent to
+ * <p>
+ * <code>
+ * | MY_COMMAND
+ * </code>
+ * <p>
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java:25]: Good point, let me clarify it

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java [hunk 13]
```diff
@@ -0,0 +1,38 @@
...
+ *
+ * In all the other cases, eg. if the command does not implement this interface, or if dependsOnInputOrder() = true
+ * then we assume that the SORT is still relevant and cannot be pruned.
+ */
+public interface SortAware {
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java:30]: I agree that the name could be more explicative, but that DoubleSort makes me think about numeric sorting ("double" as a numeric type) and I'm afraid it will create more confusion.

I'm not completely against it though. Up to you folks

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java [hunk 14]
```diff
@@ -0,0 +1,38 @@
...
+ * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
+ * or more contributor license agreements. Licensed under the Elastic License
+ * 2.0; you may not use this file except in compliance with the Elastic License
+ * 2.0.
+ */
+
+package org.elasticsearch.xpack.esql.plan.logical;
+
+/**
+ * This interface is intended to check redundancy of a previous SORT.
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java:11]: Uhm... this is not completely true.
Eg. in `SORT foo | STATS count(*)` we have only one sort, and the same is with `SORT foo | AnySortAware | STATS count(*)`

The point is more that the command performs some kind of context-free elaboration, but probably it complicates things even more

[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java:11]: Hm, good point. This may still be the best way to formalize it, however, because
```STATS ...` is (for now) equivalent to `SORT ... | STATS ...` - and therefore, we can infer that the equivalence `SORT | MY_COMMAND | SORT == MY_COMMAND | SORT` is sufficient to prune a `SORT` that's multiple `SortAware`s upstream from a `STATS`.

This equivalence is also necessary, because for any `SortAware`, we will totally turn `SORT | MY_COMMAND | SORT` into `MY_COMMAND | SORT`.

Sorry for the abstract nonsense, but I'm just more at peace if I know that the contract allows us to prove the correctness of the optimizer rule.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java:30]: That's super bikeshed. Please go ahead with the name you prefer :)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java:11]: Let's give it another try. I pushed some changes, probably too verbose, but more comprehensive

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 15]
```diff
@@ -7270,4 +7233,301 @@ public void testFunctionNamedParamsAsFunctionArgument() {
...
+     * 4]]
+     *       \_Grok[foo{r}#5,Parser[pattern=%{WORD:y}, grok=org.elasticsearch.grok.Grok@4d6ad024],[y{r}#13]]
+     *         \_Enrich[ANY,[6c 61 6e 67 75 61 67 65 73 5f 69 64 78][KEYWORD],foo{r}#5,{"match":{"indices":[],"match_field":"id","enrich_
+     * fields":["language_code","language_name"]}},{=languages_idx},[language_code{r}#35, language_name{r}#36]]
+     *           \_Join[LEFT,[language_code{r}#8],[language_code{r}#8],[language_code{f}#31]]
+     *             |_Eval[[TOSTRING(languages{f}#23) AS foo, languages{f}#23 AS language_code]]
+     *             | \_EsRelation[test][_meta_field{f}#26, emp_no{f}#20, first_name{f}#21, ..]
+     *             \_EsRelation[languages_lookup][LOOKUP][language_code{f}#31]
+     */
+    public void testRedundantSortOnMvExpandJoinEnrichGrokDissect() {
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:7398]: Adding one.

> nit: maybe it makes sense to move tests related to the new optimizer rule into a dedicated file.

Let's do it with a separate PR. LogicalPlanOptimizerTests has quite some initialization logic, it will need some refactoring.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java [hunk 16]
```diff
@@ -0,0 +1,38 @@
...
+ * </code>
+ * <p>
+ * is equivalent to
+ * <p>
+ * <code>
+ * | MY_COMMAND
+ * </code>
+ * <p>
+ *
+ * In all the other cases, eg. if the command does not implement this interface, or if dependsOnInputOrder() = true
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java:67]: Sorting is expensive in a distributed system and commands and users should not depend on it.
At the moment, only Limit and the upcoming change point depend on it, all the other commands do not - hence my preference to opt in. That is the default is optimized for the majority of use-cases.

If it's opt in, the presence of the (marker) interface (SortAware) is enough - no need to implement a method, it's redundant.
If it's opt out, use the same marker interface but change its name to reflect the intent, e.g. `SortIgnorant`, `SortIgnorant` and simply use its presence.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java [hunk 17]
```diff
@@ -0,0 +1,84 @@
...
+            });
+        } else {
+            return plan;
+        }
+    }
+
+    /**
+     * breadth-first recursion to find redundant SORTs in the children tree.
+     */
+    private IdentityHashMap<OrderBy, Void> findRedundantSort(LogicalPlan plan) {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java:63]: Hide the implementation by returning the keySet as a `Collection<OrderBy>` on which call `contains`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java [hunk 18]
```diff
@@ -0,0 +1,84 @@
...
+        if (plan instanceof OrderBy || plan instanceof TopN || plan instanceof Aggregate) {
+            IdentityHashMap<OrderBy, Void> redundant = findRedundantSort(((UnaryPlan) plan).child());
+            if (redundant.isEmpty()) {
+                return plan;
+            }
+            return plan.transformDown(p -> {
+                if (redundant.containsKey(p)) {
+                    return ((OrderBy) p).child();
+                }
+                return p;
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneRedundantOrderBy.java:53]: ` -> collection.contains(p) ? ((UnaryPlan) p).child() ? p`

**Review by costin — APPROVED** [review]
Small tweaks. LGTM

**Comment by luigidellaquila** [comment]
Thanks @costin 

>Sorting is expensive in a distributed system and commands and users should not depend on it.
At the moment, only Limit and the upcoming change point depend on it, all the other commands do not - hence my preference to opt in. That is the default is optimized for the majority of use-cases.

I'd prefer to keep it safe and have the optimization happen only when we know it's safe. ES|QL is evolving fast, and the risk of breaking things is pretty high

>If it's opt in, the presence of the (marker) interface (SortAware) is enough - no need to implement a method, it's redundant.
If it's opt out, use the same marker interface but change its name to reflect the intent, e.g. SortIgnorant, SortIgnorant and simply use its presence.

👍 I renamed it `SortAgnostic` (it's the best I could think of, naming is hard...) and I removed the method (we don't need it for now, we'll add it in the future if we want more control on single commands)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java (hunk 16 above)
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/logical/SortAware.java]: > Sorting is expensive in a distributed system and commands and users should not depend on it.
At the moment, only Limit and the upcoming change point depend on it, all the other commands do not - hence my preference to opt in. That is the default is optimized for the majority of use-cases.

@luigidellaquila and I discussed this and we both think that making the optimization opt-out is a bad idea.

Personally, I have a somewhat strong opinion here. I believe that we'd be really doing ourselves a disservice by making the optimization opt-out as this will, per default, silently break correct queries whenever we add a new command. One such command was just merged (https://github.com/elastic/elasticsearch/pull/120998) today.

The key part here is the "silent". It's silent in the code by being opt-out, but more importantly it's silent to users when they get wrong query results. This increases the risk of rolling out buggy commands whose output doesn't make sense and finding the bug in production at a much later point in time.

Forgetting to ask for the opt-out marker when reviewing a PR with a new command is also something that's really easy to do, resp. the number of things that a reviewer needs to know and look out for is increased. And even for new commands that should be fine with removing upstream sorts, I think it's still better if the first implementation doesn't automatically enable the optimization, so that we can enable it later while simultaneously adding tests.

On the other hand, making the optimization opt-in only increases the verbosity a little bit because most plan nodes actually do opt in. I believe the trade offs here are therefore very much in favor of the opt-in solution. And if we want to keep verbosity down, there's still the possibility to create a new subclass of `UnaryPlan` called `StreamingPlan`, opt this one in, and have all our commands that operate in a row-based manner inherit from that.

> If it's opt in, the presence of the (marker) interface (SortAware) is enough - no need to implement a method, it's redundant.
++, @luigidellaquila and I agreed on going this route.

**Comment by costin** [comment]
> SortAgnostic
👍

**Comment by luigidellaquila** [comment]
Thanks folks!
Merging
