### PR TITLE
Replace IntermittentLongGCDisruption with blocking cluster state updates

### LINKED ISSUE #112634: [CI] LazyRolloverDuringDisruptionIT testRolloverIsExecutedOnce failing
**Build Scans:**
- [elasticsearch-periodic #4465 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/6pdave4cyh5my)
- [elasticsearch-periodic #4460 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/xbqcd3ffwktwi)
- [elasticsearch-periodic #4450 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/3wptysdajj26e)
- [elasticsearch-periodic #4445 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/k2qo3z3rzw7k4)
- [elasticsearch-periodic #4431 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/p7av7ijbk6mna)
- [elasticsearch-periodic #4426 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/zm5cogwrnvcd4)
- [elasticsearch-periodic #4416 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/5vrpdxflll6eu)

**Reproduction Line:**
```
./gradlew ':modules:data-streams:internalClusterTest' --tests "org.elasticsearch.datastreams.LazyRolloverDuringDisruptionIT.testRolloverIsExecutedOnce" -Dtests.seed=D19459944507107A -Dtests.locale=lv-LV -Dtests.timezone=UCT -Druntime.java=23
```

**Applicable branches:**
8.15

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testRolloverIsExecutedOnce'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.datastreams.LazyRolloverDuringDisruptionIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=135, name=long_gc_simulation_1, state=RUNNABLE, group=TGRP-LazyRolloverDuringDisruptionIT]
```

**Issue Reasons:**
- [8.15] 7 consecutive failures in step openjdk23_checkpart1_java-matrix
- [8.15] 7 failures in test testRolloverIsExecutedOnce (2.2% fail rate in 320 executions)
- [8.15] 7 failures in step openjdk23_checkpart1_java-matrix (100.0% fail rate in 7 executions)
- [8.15] 7 failures in pipeline elasticsearch-periodic (63.6% fail rate in 11 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #115045: Migrate LazyRolloverDuringDisruptionIT away from long gc disruption
LongGCDisruption is going away because it relies on Thread.resume, which is removed in JDK 23. One test which relies on this disruption scheme is LazyRolloverDuringDisruptionIT. This test should be adjusted to use a different mechanism to block the master service thread.

### PR DESCRIPTION
**Pull request by gmarouli**
In JDK 23 `Thread.resume` has been removed this means that we cannot use `IntermittentLongGCDisruption` that depends on it. 

We simulate the master node disruption with a `CyclicBarrier` that blocks cluster state updates.

Closes: https://github.com/elastic/elasticsearch/issues/115045

The backport will close: https://github.com/elastic/elasticsearch/issues/112634

### CODE REVIEW

File: modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/LazyRolloverDuringDisruptionIT.java [hunk 1]
```diff
@@ -84,7 +99,7 @@ public void onFailure(Exception e) {
         }
 
         // End the disruption so that all pending tasks will complete
-        masterNodeDisruption.stopDisrupting();
+        safeAwait(barrier);
 
         // Wait for all the indexing requests to be processed successfully
         countDownLatch.await();
```
Comment (DaveCTurner) [inline modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/LazyRolloverDuringDisruptionIT.java:105]: unrelated nit: slight preference for `safeAwait(countDownLatch)` here, no sense in waiting forever.

**Review by DaveCTurner — APPROVED** [review]
I left one unrelated-but-nearby suggestion, and another is to use `safeGet(client().execute(...))` rather than `client().execute(...).actionGet()` to avoid the infinite wait & exception mangling. But LGTM either way.

**Comment by gmarouli** [comment]
Thank you for the tips @DaveCTurner! I will fix the code.
