### PR TITLE
Remove throttling from repo analyzer tests

### LINKED ISSUE #111343: [CI] RepositoryAnalysisFailureIT testFailsIfEmptyRegisterRejected failing
**Build Scans:**
- [elasticsearch-periodic #3558 / openjdk22_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/epujyfycs6h5a)
- [elasticsearch-periodic-platform-support #3464 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/adft43icrc7qe)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:snapshot-repo-test-kit:internalClusterTest" --tests "org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalysisFailureIT.testFailsIfEmptyRegisterRejected" -Dtests.seed=BC8CB7E68FD6CB74 -Dtests.locale=hu-HU -Dtests.timezone=AET -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testFailsIfEmptyRegisterRejected'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalysisFailureIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: (a string containing "Elasticsearch observed the storage system underneath this repository behaved incorrectly" and a string containing "not suitable for use with Elasticsearch snapshots" and a string containing "https://www.elastic.co/guide/en/elasticsearch/reference/master/repo-analysis-api.html")
     but: a string containing "Elasticsearch observed the storage system underneath this repository behaved incorrectly" was "[test-repo] Repository analysis timed out. Consider specifying a longer timeout using the [?timeout] request parameter. See [https://www.elastic.co/guide/en/elasticsearch/reference/master/repo-analysis-api.html] for more information. Elasticsearch attempted to remove the data it wrote at [temp-analysis-isBLdGzaQzyPhmuf64cIkw] but may have left some behind. If so, please now remove this data manually."
```

**Issue Reasons:**
- [main] 2 failures in test testFailsIfEmptyRegisterRejected (0.3% fail rate in 655 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DaveCTurner**
In practice most of the time in these tests is spent on throttling,
especially on the read side, and with some seeds this might add up to
tens of seconds of delays. The throttling is not relevant to these
tests, so this commit removes it. With this change, the analysis now
reliably runs quickly enough to use `safeAwait()` and friends to capture
the results.

Closes #111343

### CODE REVIEW

**Comment by DaveCTurner** [comment]
I've run ~8k iterations of the affected tests on this branch using a stressed machine, without a failure now. Prior to this change it'd reliably fail within a few hundred, whether stressed or not.

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java [hunk 1]
```diff
@@ -445,8 +478,18 @@ public boolean acceptsEmptyRegister() {
         }
     }
 
-    private void analyseRepository(RepositoryAnalyzeAction.Request request) {
-        client().execute(RepositoryAnalyzeAction.INSTANCE, request).actionGet(5L, TimeUnit.MINUTES);
+    private RepositoryVerificationException analyseRepository(RepositoryAnalyzeAction.Request request) {
```
Comment (ywangd) [inline x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java:481]: Nit: I wonder whether the method name could be more indicative that it is expected to fail?
```suggestion
    private RepositoryVerificationException analyseRepositoryAndExpectFailure(RepositoryAnalyzeAction.Request request) {
```

**Review by ywangd — APPROVED** [review]
LGTM

I wonder whether repository analysis should always ignore the throttling settings? Or is it  only an issue for tests where timeout cannot be extended indefinitely?

**Review by nicktindall — APPROVED** [review]

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java (hunk 1 above)
Comment (DaveCTurner) [reply x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java]: Fair point, see 68f8328bcb4d.

**Comment by DaveCTurner** [comment]
> I wonder whether repository analysis should always ignore the throttling settings? Or is it only an issue for tests where timeout cannot be extended indefinitely?

The throttling is there to protect the cluster against excessive bandwidth use, and although we don't use any IO bandwidth here we're still burning network bandwidth and we still want to limit that. Also we'd like the performance figures in the results to be somewhat indicative of actual snapshot performance. And finally we've seen some third-party repositories struggle to the point of collapse under high load, and we're not really trying to push them that hard.
