### PR TITLE
Fix testStoragePreventsMove

### LINKED ISSUE #93817: [CI] ReactiveStorageDeciderDecisionTests testStoragePreventsMove failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/gw4irn72s42ok/tests/:x-pack:plugin:autoscaling:test/org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests/testStoragePreventsMove

**Reproduction line:**
```
gradlew ':x-pack:plugin:autoscaling:test' --tests "org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests.testStoragePreventsMove" -Dtests.seed=C63160D29048E869 -Dtests.locale=zh-HK -Dtests.timezone=Africa/Tunis -Druntime.java=19
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests&tests.test=testStoragePreventsMove

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <ShardsSize[sizeInBytes=3, shardIds=[[test-7][0], [test-7][1]]]>
     but: was <ShardsSize[sizeInBytes=2, shardIds=[[test-7][0], [test-7][1]]]>

  at __randomizedtesting.SeedInfo.seed([C63160D29048E869:C67D527F55E78200]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests.verify(ReactiveStorageDeciderDecisionTests.java:415)
  at org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests.verify(ReactiveStorageDeciderDecisionTests.java:399)
  at org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests.verify(ReactiveStorageDeciderDecisionTests.java:395)
  at org.elasticsearch.xpack.autoscaling.storage.ReactiveStorageDeciderDecisionTests.testStoragePreventsMove(ReactiveStorageDeciderDecisionTests.java:246)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

### PR DESCRIPTION
**Pull request by idegtiarenko**
The failure was caused by selected shards that were not in started state (they remained initializing/rebalancing). The fix adds a check to ensure shards are not only assigned byt also started.

Closes: #93817

### CODE REVIEW

File: x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderDecisionTests.java [hunk 1]
```diff
@@ -682,6 +686,7 @@ static ClusterState addDataNodes(DiscoveryNodeRole role, String prefix, ClusterS
 
     static DiscoveryNode newDataNode(DiscoveryNodeRole role, String nodeName) {
         return new DiscoveryNode(
+            nodeName,
```
Comment (idegtiarenko) [inline x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderDecisionTests.java:689]: Uses node name as nodeId. This makes it easier to distinguish hot and warm nodes in routing table output.

File: x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderDecisionTests.java [hunk 2]
```diff
@@ -218,7 +218,11 @@ public void testStoragePreventsMove() {
         do {
             startRandomShards();
             // all of the relevant replicas are assigned too.
-        } while (state.getRoutingNodes().unassigned().stream().map(ShardRouting::shardId).anyMatch(warmShards::contains));
+        } while (haveNonEmptyIntersection(shardIds(state.getRoutingNodes().unassigned()), warmShards)
+            || haveNonEmptyIntersection(
+                shardIds(RoutingNodesHelper.shardsWithState(state.getRoutingNodes(), ShardRoutingState.INITIALIZING)),
+                warmShards
+            ));
```
Comment (idegtiarenko) [inline x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderDecisionTests.java:225]: Following code moves STARTED `warmShards` to the warm nodes (as it is impossible to move INITIALIZING shards), however some of the `warmShards` remained initializing after this loop due to ongoing rebalancing.

For the seed suggested in https://github.com/elastic/elasticsearch/issues/93817 we pick `{[test-7][0], [test-7][1], [test-7][3]}`, however `[test-7][3]` is not initialized.
```
routing_nodes:
-----node_id[hot_1][V]
--------[test-7][4], node[hot_1], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=jCDltr6LSSq3QeoNg0APXA], unassigned_info[[reason=INDEX_CREATED], at[2023-04-04T14:45:02.794Z], delayed=false, allocation_status[no_attempt]], failed_attempts[0], expected_shard_size[1]
-----node_id[hot_0][V]
--------[test-7][0], node[hot_0], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=2rUsaPQdS5SWys9z-H6fng], unassigned_info[[reason=INDEX_CREATED], at[2023-04-04T14:45:02.794Z], delayed=false, allocation_status[no_attempt]], failed_attempts[0], expected_shard_size[1]
--------[test-7][3], node[hot_0], relocating [hot_2], [P], recovery_source[peer recovery], s[INITIALIZING], a[id=fe1k-AAKSPmKJ3g6mcAXCw, rId=A41h2dm5T-WtdRO1bj-2SA], failed_attempts[0], expected_shard_size[0]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-----node_id[hot_3][V]
--------[test-7][1], node[hot_3], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=uttrNnlPSHu_vwR58LJ2BA], unassigned_info[[reason=INDEX_CREATED], at[2023-04-04T14:45:02.794Z], delayed=false, allocation_status[no_attempt]], failed_attempts[0], expected_shard_size[1]
--------[test-7][2], node[hot_3], [P], s[STARTED], a[id=GDO3KyBHRd-qWFVrOxYJRQ], failed_attempts[0]
-----node_id[hot_2][V]
--------[test-7][2], node[hot_2], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=_BsL8zmbRFGK-64C3vp9Og], unassigned_info[[reason=INDEX_CREATED], at[2023-04-04T14:45:02.794Z], delayed=false, allocation_status[no_attempt]], failed_attempts[0], expected_shard_size[1]
--------[test-7][3], node[hot_2], relocating [hot_0], [P], s[RELOCATING], a[id=A41h2dm5T-WtdRO1bj-2SA, rId=fe1k-AAKSPmKJ3g6mcAXCw], failed_attempts[0], expected_shard_size[0]
-----node_id[hot_4][V]
--------[test-7][3], node[hot_4], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=IG5OmNBRRy68DhIlTbpI4Q], unassigned_info[[reason=INDEX_CREATED], at[2023-04-04T14:45:02.794Z], delayed=false, allocation_status[no_attempt]], failed_attempts[0], expected_shard_size[1]
--------[test-7][4], node[hot_4], [P], s[STARTED], a[id=wo_Bx2xqTiyXi3rT09qa6g], failed_attempts[0]

-----node_id[warm_1][V]
--------[test-7][0], node[warm_1], [P], s[STARTED], a[id=XdQDlbUnRHutgARxzBYiMQ], failed_attempts[0]
-----node_id[warm_0][V]
--------[test-7][1], node[warm_0], [P], s[STARTED], a[id=5dlcuq_LQ42gIOYEfcojHw], failed_attempts[0]

---- unassigned
```

File: x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderDecisionTests.java [hunk 3]
```diff
@@ -692,8 +697,7 @@ static DiscoveryNode newDataNode(DiscoveryNodeRole role, String nodeName) {
     }
 
     private static String randomNodeId(RoutingNodes routingNodes, DiscoveryNodeRole role) {
-        return randomFrom(routingNodes.stream().map(RoutingNode::node).filter(n -> n.getRoles().contains(role)).collect(Collectors.toSet()))
-            .getId();
+        return randomValueOtherThanMany(not(node -> node.node().getRoles().contains(role)), () -> randomFrom(routingNodes)).nodeId();
```
Comment (pxsalehi) [inline x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderDecisionTests.java:700]: Maybe I'm misunderstanding this, but why is this change needed? This seems to be not sampling from the same possible set of node IDs compared to the previous code.

Comment (idegtiarenko) [reply x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderDecisionTests.java:700]: This is not required change, I tried to refactor picking the node to not collect to set.
I find `many` confusing in `randomValueOtherThanMany`, this code is keep trying to pick a random node from `routingNodes` (with second argument: `() -> randomFrom(routingNodes)`) for as long as it does not contain requested role (first predicate argument).

I could revert it if you believe this is harder to read then before.

Comment (pxsalehi) [reply x-pack/plugin/autoscaling/src/test/java/org/elasticsearch/xpack/autoscaling/storage/ReactiveStorageDeciderDecisionTests.java:700]: Well, it's up to you. But I find the `filter` variant more straight-forward.

**Review by pxsalehi — APPROVED** [review]

**Comment by idegtiarenko** [comment]
@elasticsearchmachine please run elasticsearch-ci/bwc
