### PR TITLE
Double close on shuffle during field loading

### LINKED ISSUE #130122: [CI] EnrichIT testTopN failing
**Build Scans:**
- [elasticsearch-intake #25170 / part3](https://gradle-enterprise.elastic.co/s/ofbl7l5eeiwym)
- [elasticsearch-periodic #9223 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/x4u3ylypgmy2o)
- [elasticsearch-periodic-platform-support #9234 / ubuntu-2404_platform-support-unix](https://gradle-enterprise.elastic.co/s/lvllwvszlnj6a)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.EnrichIT.testForPushDownEnrichRule" -Dtests.seed=FC9C12DEDB2B3119 -Dtests.locale=kk -Dtests.timezone=SystemV/YST9 -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.EnrichIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTopN'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Request breaker not reset to 0 on node: node_s1
Expected: <0L>
     but: was <1773L>
```

**Issue Reasons:**
- [main] 3 failures in test testTopN (3.6% fail rate in 83 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #130270: [CI] EnrichIT testProfile failing
**Build Scans:**
- [elasticsearch-intake #25170 / part3](https://gradle-enterprise.elastic.co/s/ofbl7l5eeiwym)
- [elasticsearch-periodic #9223 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/x4u3ylypgmy2o)
- [elasticsearch-periodic #9223 / openjdk24_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/k4chrkmrpliya)
- [elasticsearch-pull-request #79406 / part-3](https://gradle-enterprise.elastic.co/s/2vlusk3dibsqq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.EnrichIT.testForPushDownEnrichRule" -Dtests.seed=FC9C12DEDB2B3119 -Dtests.locale=kk -Dtests.timezone=SystemV/YST9 -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.EnrichIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testProfile'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Request breaker not reset to 0 on node: node_s1
Expected: <0L>
     but: was <1773L>
```

**Issue Reasons:**
- [main] 4 failures in test testProfile (1.9% fail rate in 216 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #130426: [CI] EnrichIT testForPushDownEnrichRule failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9234 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/lhqejwr7jho5c)
- [elasticsearch-periodic #9223 / openjdk24_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/k4chrkmrpliya)
- [elasticsearch-pull-request #79406 / part-3](https://gradle-enterprise.elastic.co/s/2vlusk3dibsqq)
- [elasticsearch-pull-request #79385 / part-3](https://gradle-enterprise.elastic.co/s/hf5fue2fcov7q)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.EnrichIT.testForPushDownEnrichRule" -Dtests.seed=B5369236A77C9139 -Dtests.locale=yue-Hans -Dtests.timezone=America/Tortola -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.EnrichIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testForPushDownEnrichRule'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
Expected: <0L>
     but: was <2579L>
```

**Issue Reasons:**
- [main] 4 failures in test testForPushDownEnrichRule (1.9% fail rate in 212 executions)
- [main] 2 failures in step part-3 (2.0% fail rate in 98 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.1% fail rate in 97 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #130790: [CI] EnrichIT testAvgDurationByArtist failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9234 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/dbq4rzm7d4rmi)
- [elasticsearch-periodic #9223 / openjdk24_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/k4chrkmrpliya)
- [elasticsearch-pull-request #79406 / part-3](https://gradle-enterprise.elastic.co/s/2vlusk3dibsqq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.EnrichIT.testAvgDurationByArtist" -Dtests.seed=8EC178310725A02F -Dtests.locale=ia-Latn-001 -Dtests.timezone=Australia/Adelaide -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.EnrichIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAvgDurationByArtist'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Request breaker not reset to 0 on node: node_s1
Expected: <0L>
     but: was <2783L>
```

**Issue Reasons:**
- [main] 3 failures in test testAvgDurationByArtist (1.4% fail rate in 213 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #130792: [CI] EnrichIT testManyDocuments failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9234 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/dbq4rzm7d4rmi)
- [elasticsearch-pull-request #79406 / part-3](https://gradle-enterprise.elastic.co/s/2vlusk3dibsqq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.EnrichIT.testAvgDurationByArtist" -Dtests.seed=8EC178310725A02F -Dtests.locale=ia-Latn-001 -Dtests.timezone=Australia/Adelaide -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.EnrichIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testManyDocuments'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Request breaker not reset to 0 on node: node_s1
Expected: <0L>
     but: was <2783L>
```

**Issue Reasons:**
- [main] 2 failures in test testManyDocuments (0.9% fail rate in 213 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #130831: [CI] EsqlClientYamlIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9241 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/jytfu2tnxufas)
- [elasticsearch-intake #25185 / part3](https://gradle-enterprise.elastic.co/s/4i5m6b7ysyt32)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:yamlRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT.test {p0=esql/130_spatial/cartesian_shape unsortable with limit status code}" -Dtests.seed=AE791190823EE307 -Dtests.locale=it-SM -Dtests.timezone=America/Punta_Arenas -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: circuit breakers not reset to 0Expected a map containing
estimated_size_in_bytes: expected <0> but was <336>
         estimated_size: expected "0b" but was "336b"
               overhead: <1.0> unexpected but ok
    limit_size_in_bytes: <322122547> unexpected but ok
             limit_size: "307.1mb" unexpected but ok
                tripped: <0> unexpected but ok
```

**Issue Reasons:**
- [main] 2 failures in class org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT (1.0% fail rate in 208 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nik9000**
Fixes a bug during field loading where we could double-close blocks if we failed to allocate memory during the un-shuffling portion of field loading from single segments.

Unit test incoming in the followup.

Closes #130426
Closes #130790
Closes #130791
Closes #130792
Closes #130793
Closes #130270
Closes #130788
Closes #130122
Closes #130827
Closes #130831

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperatorTests.java [hunk 1]
```diff
@@ -446,12 +445,6 @@ protected void assertSimpleOutput(List<Page> input, List<Page> results) {
         assertThat(sum, equalTo(expectedSum));
     }
 
-    @Override
-    protected ByteSizeValue enoughMemoryForSimple() {
-        assumeFalse("strange exception in the test, fix soon", true);
-        return ByteSizeValue.ofKb(1);
-    }
-
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/lucene/read/ValuesSourceReaderOperatorTests.java:454]: This test didn't catch any failures, but it would have if we'd made a non-"simple" version. I'll expand this in a followup I think.

File: x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java [hunk 2]
```diff
@@ -98,10 +98,16 @@ protected ByteSizeValue enoughMemoryForSimple() {
...
+        /*
+         * Build the input before building `simple` to handle the rare
+         * cases where `simple` need some state from the input - mostly
+         * this is ValuesSourceReaderOperator.
+         */
         DriverContext inputFactoryContext = driverContext();
         List<Page> input = CannedSourceOperator.collectPages(simpleInput(inputFactoryContext.blockFactory(), between(1_000, 10_000)));
+
+        ByteSizeValue memoryLimitForSimple = enoughMemoryForSimple();
+        Operator.OperatorFactory simple = simple(new SimpleOptions(true));
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java:110]: This shift fixed the test.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromSingleReader.java [hunk 3]
```diff
@@ -65,22 +65,27 @@ public int get(int i) {
             return;
         }
         int[] forwards = docs.shardSegmentDocMapForwards();
-        loadFromSingleLeaf(target, new BlockLoader.Docs() {
-            @Override
-            public int count() {
-                return docs.getPositionCount();
-            }
+        Block[] unshuffled = new Block[target.length];
```
Comment (nik9000) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/read/ValuesFromSingleReader.java:68]: Here's the bug - you can't use the `target` array and then shuffle into it.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks for fixing this!

**Comment by nik9000** [comment]
Merging despite the serverless error. It's unrelated and this blocks a bunch of spurious failures.

**Comment by nik9000** [comment]
9.1 backport: https://github.com/elastic/elasticsearch/pull/130848
