### PR TITLE
ES|QL: No plain strings in Literal

### LINKED ISSUE #129322: ES|QL: Folding of REPLACE with constants throws ClassCastException
```
row txt = "a" |  WHERE MATCH(txt, REPLACE("XS", "X", "U"))
```

```
class java.lang.String cannot be cast to class org.apache.lucene.util.BytesRef (java.lang.String is in module java.base of loader 'bootstrap'; org.apache.lucene.util.BytesRef is in module org.apache.lucene.core@10.2.1 of loader 'app')
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes: https://github.com/elastic/elasticsearch/issues/129322

Making sure that all the `TEXT`, `KEYWORD` and `VERSION` Literals contain a BytesRef (and not a plain `java.lang.String`).

The mix of the two was the reason for some ClassCastExceptions, eg. https://github.com/elastic/elasticsearch/issues/129322

Steps:

- [x] Force the conversion from String to BytesRef inside Literal constructor
- [x] Make all the tests pass
- [x] Replace the forced conversion with an assert, checking that no java.lang.String is passed to the constructor
- [x] Make tests pass again

### CODE REVIEW

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java [hunk 1]
```diff
@@ -122,7 +141,20 @@ public boolean equals(Object obj) {
...
     @Override
     public String toString() {
-        String str = String.valueOf(value);
+        String str;
+        if (dataType == KEYWORD || dataType == TEXT) {
+            str = BytesRefs.toString(value);
+        } else if (dataType == VERSION && value instanceof BytesRef br) {
+            str = new Version(br).toString();
+            // } else if (dataType == IP && value instanceof BytesRef ip) {
+            // str = DocValueFormat.IP.format(ip);
```
Comment (idegtiarenko) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java:153]: Just in case, is this intentionally commented?

Comment (luigidellaquila) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java:153]: Yeah... unfortunately it is, for two reasons:
- IP conversion from/to BytesRefs could trigger assertion errors, and it's pretty annoying in tests
- We are explicitly using strings for IPs in some cases, see [CobineDisjunctions](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineDisjunctions.java#L81-L92); we'll have to change that before we can force IPs as BytesRefs

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java [hunk 2]
```diff
@@ -122,7 +141,20 @@ public boolean equals(Object obj) {
 
     @Override
     public String toString() {
-        String str = String.valueOf(value);
+        String str;
+        if (dataType == KEYWORD || dataType == TEXT) {
+            str = BytesRefs.toString(value);
+        } else if (dataType == VERSION && value instanceof BytesRef br) {
+            str = new Version(br).toString();
```
Comment (ivancea) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java:150]: Is this an improvement? Or were Versions a readable String before?

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/ip.csv-spec [hunk 3]
```diff
@@ -398,7 +398,7 @@ eth0           |gamma          |fe80::cae2:65ff:fece:feb9
 lo0            |gamma          |fe80::cae2:65ff:fece:feb9                                                         |fe81::cae2:65ff:fece:feb9
 ;
 
-cdirMatchEqualsInsOrsIPs
+cicdirMatchEqualsInsOrsIPs
```
Comment (ivancea) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/ip.csv-spec]:
```suggestion
cidrMatchEqualsInsOrsIPs
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvSort.java
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/multivalue/MvSort.java:1]: Nit: I would replace every cast+utf8ToString()  to `BytesRefs.toString()`, if possible

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToIpTests.java [hunk 4]
```diff
@@ -182,8 +183,10 @@ private static String readEvaluator() {
     }
 
     private static String stringEvaluator(ToIp.LeadingZeros leadingZeros) {
+        if (leadingZeros == null) {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToIpTests.java:185]: As this was here before, and in jdk21 the `case null` works (right?), do we need this change?

**Review by ivancea — APPROVED** [review]
LGTM!

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java [hunk 5]
```diff
@@ -45,10 +51,23 @@ public class Literal extends LeafExpression {
...
     }
 
+    private boolean noPlainStrings(Object value, DataType dataType) {
+        if (dataType == KEYWORD || dataType == TEXT || dataType == VERSION) {
+            if (value instanceof String) {
+                return false;
+            }
+            if (value instanceof Collection<?> c) {
+                return c.stream().allMatch(x -> noPlainStrings(x, dataType));
+            }
```
Comment (idegtiarenko) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java]: Nit: consider pattern matching here
```suggestion
            return switch (value) {
                case String s -> false;
                case Collection<?> c -> c.stream().allMatch(x -> noPlainStrings(x, dataType));
                default -> true;
            }
```

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java (hunk 2 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java:150]: We had some cases (mostly unit tests) where we passed plain strings to VERSION literals.
Even for tests it's not a good thing, as we are testing something that is different than the actual production execution.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java (hunk 1 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java:153]: Could you please add this as a comment/todo referencing an issue to resolve it eventually?

File: x-pack/plugin/esql-core/src/test/java/org/elasticsearch/xpack/esql/core/expression/function/scalar/FunctionTestUtils.java [hunk 6]
```diff
@@ -15,10 +16,13 @@
 public final class FunctionTestUtils {
 
     public static Literal l(Object value) {
-        return new Literal(EMPTY, value, DataType.fromJava(value));
+        return l(value, DataType.fromJava(value));
     }
 
     public static Literal l(Object value, DataType type) {
+        if (value instanceof String && (type == DataType.TEXT || type == DataType.KEYWORD)) {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql-core/src/test/java/org/elasticsearch/xpack/esql/core/expression/function/scalar/FunctionTestUtils.java]: NIT: `type == DataType.TEXT || type == DataType.KEYWORD` theck looks a bit cheaper. Do you mind making it first (before instanceof)?

File: x-pack/plugin/esql-core/src/test/java/org/elasticsearch/xpack/esql/core/util/TestUtils.java [hunk 7]
```diff
@@ -39,6 +42,10 @@ public static Literal of(Source source, Object value) {
         if (value instanceof Literal) {
             return (Literal) value;
         }
+        DataType type = DataType.fromJava(value);
+        if (value instanceof String && (type == TEXT || type == KEYWORD)) {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql-core/src/test/java/org/elasticsearch/xpack/esql/core/util/TestUtils.java]: Same here

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/Literal.java:153]: I created [an issue](https://github.com/elastic/elasticsearch/issues/129605) and I'm linking it in a TODO

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/string/Space.java [hunk 8]
```diff
@@ -116,7 +117,7 @@ public ExpressionEvaluator.Factory toEvaluator(ToEvaluator toEvaluator) {
             Object folded = field.fold(toEvaluator.foldCtx());
             if (folded instanceof Integer num) {
                 checkNumber(num);
-                return toEvaluator.apply(new Literal(source(), " ".repeat(num), KEYWORD));
+                return toEvaluator.apply(new Literal(source(), BytesRefs.toBytesRef(" ".repeat(num)), KEYWORD));
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/string/Space.java]: This seems to repeat a lot, I wonder if it is worth introducing:
```
pusblic static Literal.keyword(Source source, String literal) {
    return new Literal(source, BytesRefs.toBytesRef(literal), KEYWORD);
}
```
to simplify construction of string literals?

**Review by idegtiarenko — APPROVED** [review]
:+1:

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToIpTests.java (hunk 4 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/convert/ToIpTests.java:185]: My IntelliJ (Java 21) keeps complaining, but maybe it's some wrong setting on my side

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/string/Space.java (hunk 8 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/string/Space.java]: 👍 I think it makes sense

**Comment by luigidellaquila** [comment]
Thanks for the feedback folks!

**Comment by luigidellaquila** [comment]
Manual backport https://github.com/elastic/elasticsearch/pull/129702
