### PR TITLE
ThreadPool and ThreadContext are not closeable

### LINKED ISSUE #42577: [CI] org.elasticsearch.node.NodeTests failures
This test seems to be failing the time to time with the following error:

```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=716, name=elasticsearch[mock_ node][search][T#1], state=RUNNABLE, group=TGRP-NodeTests]
	at __randomizedtesting.SeedInfo.seed([60CD27ABD7612595:1A041A5993EEF0D6]:0)
Caused by: java.lang.IllegalStateException: threadcontext is already closed
	at __randomizedtesting.SeedInfo.seed([60CD27ABD7612595]:0)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextThreadLocal.ensureOpen(ThreadContext.java:658)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextThreadLocal.get(ThreadContext.java:651)
	at org.elasticsearch.common.util.concurrent.ThreadContext.stashContext(ThreadContext.java:132)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:754)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Examples for this failure are:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=debian-9/230/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu11,nodes=immutable&&linux&&docker/5/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/400/console

every time complains from a different test method. 

Relates to #42350

### PR DESCRIPTION
**Pull request by jaymode**
This commit changes the ThreadContext to just use a regular ThreadLocal
over the lucene CloseableThreadLocal. The CloseableThreadLocal solves
issues with ThreadLocals that are no longer needed during runtime but
in the case of the ThreadContext, we need it for the runtime of the
node and it is typically not closed until the node closes, so we miss
out on the benefits that this class provides.

Additionally by removing the close logic, we simplify code in other
places that deal with exceptions and tracking to see if it happens when
the node is closing.

Closes #42577

### CODE REVIEW

**Review by jpountz — COMMENTED** [review]
I am a bit worried about the short-lived threadlocals that are created e.g. by TransportLogger.

**Comment by jaymode** [comment]
@jpountz I've updated this PR to address concerns regarding the creation of short lived thread locals in non test code

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/SecurityTests.java [hunk 1]
```diff
@@ -146,8 +146,6 @@ protected SSLService getSslService() {
     @Before
     public void cleanup() throws IOException {
         if (threadContext != null) {
-            threadContext.stashContext();
-            threadContext.close();
             threadContext = null;
         }
```
Comment (jpountz) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/SecurityTests.java]: we could remove the `if` statement?

File: server/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java [hunk 2]
```diff
@@ -140,19 +124,13 @@ public StoredContext stashContext() {
                 DEFAULT_CONTEXT.putHeaders(Map.of(Task.X_OPAQUE_ID, context.requestHeaders.get(Task.X_OPAQUE_ID)));
             threadLocal.set(threadContextStruct);
         } else {
-            threadLocal.set(null);
+            threadLocal.set(DEFAULT_CONTEXT);
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java]: Your change sets the default context here, while master sets it to null and then checks for null at read time to return the default context instead. These approaches look equivalent to me and I think your change makes things simpler but I wonder whether I'm missing something?

**Review by jpountz — APPROVED** [review]
Nice cleanup.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/SecurityTests.java (hunk 1 above)
Comment (jaymode) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/SecurityTests.java]: Good catch. I removed it and made it an after method, which makes more sense to me than a Before method.

File: server/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java (hunk 2 above)
Comment (jaymode) [reply server/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java]: Prior to this change, it does make a difference in that the `CloseableThreadLocal` class does more work including executing a section of code that is synchronized across all threads when returning the initial value for the thread local unless the initial value is null; if the initial value is null, nothing gets stored and the synchronized code is skipped. However, once a value has been set the move to setting it null no longer bypasses the synchronized code. The regular ThreadLocal class always executes code when first accessing with an initial value but the code that is executed is not synchronized across all threads so we can make things simpler and just reference the default context instead of a null value.

Comment (jpountz) [reply server/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java]: Thanks for explaining.
