### PR TITLE
[Transform] return results in order

### LINKED ISSUE #104847: [Transform] Terms ordering specified via `"order"` parameter is ignored.
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

This bug report comes from [Elasticsearch discuss forum](https://discuss.elastic.co/t/term-aggregation-ordering-within-a-pivot-transform/351754).

`"order"` parameter ([docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_ordering_by_the_term_value)) is ignored when specified in the `"aggregations"` section of a transform.
It works fine when specified in the search request (outside of transform).

### Steps to Reproduce

1. Create the index
```
PUT my-index
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1
  },
  "mappings": {
    "properties": {
      "group_id": {
        "type": "keyword"
      },
      "item_id": {
        "type": "keyword"
      },
      "item_value": {
        "type": "long"
      }
    }
  }
}
```

2. Populate the index with data
```
POST my-index/_bulk
{"index":{}}
{ "group_id": "gA", "item_id": "iA", "item_value": 1 }
{"index":{}}
{ "group_id": "gA", "item_id": "iB", "item_value": 1 }
{"index":{}}
{ "group_id": "gA", "item_id": "iC", "item_value": 1 }
{"index":{}}
{ "group_id": "gB", "item_id": "iA", "item_value": 1 }
{"index":{}}
{ "group_id": "gB", "item_id": "iB", "item_value": 1 }
{"index":{}}
{ "group_id": "gB", "item_id": "iC", "item_value": 1 }
{"index":{}}
{ "group_id": "gC", "item_id": "iA", "item_value": 1 }
{"index":{}}
{ "group_id": "gC", "item_id": "iB", "item_value": 1 }
{"index":{}}
{ "group_id": "gC", "item_id": "iC", "item_value": 1 }
{"index":{}}
{ "group_id": "gD", "item_id": "iA", "item_value": 1 }
{"index":{}}
{ "group_id": "gD", "item_id": "iB", "item_value": 1 }
{"index":{}}
{ "group_id": "gD", "item_id": "iC", "item_value": 1 }
{"index":{}}
{ "group_id": "gE", "item_id": "iA", "item_value": 1 }
{"index":{}}
{ "group_id": "gE", "item_id": "iB", "item_value": 1 }
{"index":{}}
{ "group_id": "gE", "item_id": "iC", "item_value": 1 }
```

3. Observe that the search request orders the bucket keys descending ("iC", "iB", "iA")
```
GET my-index/_search
{
  "size": 0,
  "aggregations": {
    "groups": {
      "terms": {
        "field": "group_id"
      },
      "aggregations": {
        "items": {
          "terms": {
            "field": "item_id",
            "order": {
              "_key": "desc"
            }
          },
          "aggregations": {
            "value": {
              "sum": {
                "field": "item_value"
              }
            }
          }
        }
      }
    }
  }
}
```

```
{
  "took": 10,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 15,
      "relation": "eq"
    },
    "max_score": null,
    "hits": []
  },
  "aggregations": {
    "groups": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "gA",
          "doc_count": 3,
          "items": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "iC",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iB",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iA",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              }
            ]
          }
        },
        {
          "key": "gB",
          "doc_count": 3,
          "items": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "iC",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iB",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iA",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              }
            ]
          }
        },
        {
          "key": "gC",
          "doc_count": 3,
          "items": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "iC",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iB",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iA",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              }
            ]
          }
        },
        {
          "key": "gD",
          "doc_count": 3,
          "items": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "iC",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iB",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iA",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              }
            ]
          }
        },
        {
          "key": "gE",
          "doc_count": 3,
          "items": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "key": "iC",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iB",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              },
              {
                "key": "iA",
                "doc_count": 1,
                "value": {
                  "value": 1
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

4. Observe that the transform ignored the order
```
GET _transform/_preview
{
  "source": {
    "index": "my-index"
  },
  "pivot": {
    "group_by": {
      "group_id": {
        "terms": {
          "field": "group_id"
        }
      }
    },
    "aggregations": {
      "items": {
        "terms": {
          "field": "item_id",
          "order": {
            "_key": "desc"
          }
        },
        "aggregations": {
          "value": {
            "sum": {
              "field": "item_value"
            }
          }
        }
      }
    }
  }
}
```

```
{
  "preview": [
    {
      "group_id": "gA",
      "items": {
        "iA": {
          "value": 1
        },
        "iB": {
          "value": 1
        },
        "iC": {
          "value": 1
        }
      }
    },
    {
      "group_id": "gB",
      "items": {
        "iA": {
          "value": 1
        },
        "iB": {
          "value": 1
        },
        "iC": {
          "value": 1
        }
      }
    },
    {
      "group_id": "gC",
      "items": {
        "iA": {
          "value": 1
        },
        "iB": {
          "value": 1
        },
        "iC": {
          "value": 1
        }
      }
    },
    {
      "group_id": "gD",
      "items": {
        "iA": {
          "value": 1
        },
        "iB": {
          "value": 1
        },
        "iC": {
          "value": 1
        }
      }
    },
    {
      "group_id": "gE",
      "items": {
        "iA": {
          "value": 1
        },
        "iB": {
          "value": 1
        },
        "iC": {
          "value": 1
        }
      }
    }
  ],
  "generated_dest_index": {
    "mappings": {
      "_meta": {
        "_transform": {
          "transform": "transform-preview",
          "version": {
            "created": "10.0.0"
          },
          "creation_date_in_millis": 1706519277689
        },
        "created_by": "transform"
      },
      "properties": {
        "group_id": {
          "type": "keyword"
        },
        "items": {
          "type": "flattened"
        }
      }
    },
    "settings": {
      "index": {
        "number_of_shards": "1",
        "auto_expand_replicas": "0-1"
      }
    },
    "aliases": {}
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by prwhelan**
Currently, when Transform searches over aggregations, it stores the results in an unordered HashMap. This potentially rearranges search results.

For example, if a user specifies an order in a search request, the search response is in that order. But if the search request is embedded in a Transform request, then Transform response will not preserve the order and the result will look different.

With this change, Transform will always preserve the order of the search response. A search embedded in a Transform should behave as an unembedded search.

Closes #104847

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -1899,20 +1899,32 @@ protected static Map<String, Object> getAlias(final String index, final String a
     }
 
     protected static Map<String, Object> getAsMap(final String endpoint) throws IOException {
-        return getAsMap(client(), endpoint);
+        return getAsMap(client(), endpoint, false);
+    }
+
+    protected static Map<String, Object> getAsMap(final String endpoint, final boolean ordered) throws IOException {
```
Comment (przemekwitek) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1905]: Alternatively, this method could be made `private` and there could be another method `getAsOrderedMap`. This way the test code will be a bit cleaner as there won't be cryptic `true` argument.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 2]
```diff
@@ -1899,20 +1899,32 @@ protected static Map<String, Object> getAlias(final String index, final String a
...
         Response response = client.performRequest(new Request("GET", endpoint));
-        return responseAsMap(response);
+        return responseAsMap(response, ordered);
     }
 
     protected static Map<String, Object> responseAsMap(Response response) throws IOException {
+        return responseAsMap(response, false);
+    }
+
+    protected static Map<String, Object> responseAsMap(Response response, boolean ordered) throws IOException {
```
Comment (przemekwitek) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1922]: Same here, there could be `responseAsOrderedMap` method to avoid passing `ordered` bit from the test code.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java [hunk 3]
```diff
@@ -392,23 +388,17 @@ static class MultiBucketsAggExtractor implements AggValueExtractor {
         public Object value(Aggregation agg, Map<String, String> fieldTypeMap, String lookupFieldPrefix) {
             MultiBucketsAggregation aggregation = (MultiBucketsAggregation) agg;
 
-            HashMap<String, Object> nested = new HashMap<>();
+            var subAggLookupFieldPrefix = lookupFieldPrefix.isEmpty() ? agg.getName() : lookupFieldPrefix + "." + agg.getName();
+            Map<String, Object> nested = Maps.newLinkedHashMapWithExpectedSize(aggregation.getBuckets().size());
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java:392]: Could the `Maps.newLinkedHashMapWithExpectedSize` method be used in line 366 too?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java [hunk 4]
```diff
@@ -495,12 +485,12 @@ static class GeoTileBucketKeyExtractor implements BucketKeyExtractor {
...
             assert key instanceof String;
             Rectangle rectangle = GeoTileUtils.toBoundingBox(key.toString());
-            final Map<String, Object> geoShape = new HashMap<>();
+            final Map<String, Object> geoShape = Maps.newLinkedHashMapWithExpectedSize(2);
             geoShape.put(FIELD_TYPE, POLYGON);
             geoShape.put(
                 FIELD_COORDINATES,
                 Collections.singletonList(
-                    Arrays.asList(
+                    List.of(
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java:493]: Could you also get rid of 2 more `Arrays.asList` usages in this file and replace them with `List.of`?

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 1 above)
Comment (prwhelan) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1905]: Yeah I like that more. Let's do that

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java (hunk 3 above)
Comment (prwhelan) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/pivot/AggregationResultUtils.java:392]: We spoke offline, capturing the convo here: the cases where we're using `new LinkedHashMap` is because we do not have the size available.

> do you think it's okay to add size() and isEmpty() to [InternalAggregations](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregations.java#L60)?

> Sure, it makes perfect sense as InternalAggregations is logically a collection.
If you decide to introduce it, then please make it in a separate PR and send it for review to search/aggregations folks.
Or even better, ask them first if such a change is welcome.

**Review by przemekwitek — APPROVED** [review]
LGTM
