### PR TITLE
Finish role updates in security migration tests before shutdown

### LINKED ISSUE #139055: [CI] MetadataFlattenedMigrationIntegTests testMigrationWithConcurrentUpdates failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11504 / windows-2025_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/vvtfnh3j6uffe)
- [elasticsearch-periodic-platform-support #11485 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/7adja4bcu4jzi)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:security:internalClusterTest" --tests "org.elasticsearch.xpack.security.support.MetadataFlattenedMigrationIntegTests.testMigrationWithConcurrentUpdates" -Dtests.seed=B111850EE5A8E4DE -Dtests.locale=naq -Dtests.timezone=America/Porto_Velho -Druntime.java=25
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.support.MetadataFlattenedMigrationIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMigrationWithConcurrentUpdates'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: unexpected
```

**Issue Reasons:**
- [9.1] 2 failures in test testMigrationWithConcurrentUpdates (1.6% fail rate in 123 executions)
- [9.1] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jfreden**
This PR fixes a race condition in `MetadataFlattenedMigrationIntegTests.testMigrationWithConcurrentUpdates` where the thread that run in parallel to simulate concurrent updates to roles while a security migration happens wasn't done with the security index when the test node shutdown, causing a `NodeClosedException`. 

To address this, a `RefCountingListener` has been added to make sure all updates to complete before the node is shutdown. 

Resolves: https://github.com/elastic/elasticsearch/issues/139055

### CODE REVIEW

**Comment by jfreden** [comment]
This test is only muted on 9.1 so far.

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/support/MetadataFlattenedMigrationIntegTests.java [hunk 1]
```diff
@@ -97,14 +98,14 @@ public void testMigrationWithConcurrentUpdates() throws Exception {
...
-                runUpdateRolesBackground.set(false);
-                executor.shutdown();
-            }
+            waitForMigrationCompletion();
+            runUpdateRolesBackground.set(false);
+            assertAllRolesHaveMetadataFlattened();
+        } finally {
+            // Await all role updates before shutting down
+            roleUpdatesCompleteListener.get();
+            terminate(executor);
```
Comment (jfreden) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/support/MetadataFlattenedMigrationIntegTests.java:107]: Changed to use `terminate` here because it shuts down and awaits with good timeouts for tests.

**Review by richard-dennehy — APPROVED** [review]

**Review by ankit--sethi — APPROVED** [review]

**Comment by jfreden** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/139180)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
