### PR TITLE
Remove ExceptionHelper.detailedMessage

### LINKED ISSUE #19069: Remove uses of `ExceptionHelper.detailedMessage`
This method tries to summarize an exception in a single string. But the entire point of the structured exception work was to get real stack traces. This method just hurts, and does not help. For example, if you have a `NullPointerException`, nothing will help except for the stack trace, but detailedMessage will only emit the exception name.  We should remove all uses of this (there are over 50 right now).

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #19069.

I'm unsure of my approach here, so more opinions would be welcome. Mostly I replaced calls to `ExceptionHelper.detailedMessage` with `e.getMessage()`, which is all well and good but does remove some level of detail. There were a couple of cases where I replaced the method call with a `throw`, in the hope that code elsewhere will catch it and do the right thing.

### CODE REVIEW

**Comment by rjernst** [comment]
I don't think changing these uses to `getMessage()` solves the problem outlined in #19069. We often wrap exceptions, creating deep chains. By changing to getMessage() we omit even more information than detailedMessage is emitting. The problem is we need the actual stack trace. detailedMessage tries to summarize an exception into a single string that omits stack frames from each cause, summarizing as just the exception class + message for each cause. For something like a NullPointerException we lose all information that makes the exception debuggable (the location where the NPE occurred). I think a better substitute would be `ExceptionHelper.stackTrace`?

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/FailedShard.java [hunk 1]
```diff
@@ -42,8 +42,8 @@ public FailedShard(ShardRouting routingEntry, String message, Exception failure,
 
     @Override
     public String toString() {
-        return "failed shard, shard " + routingEntry + ", message [" + message + "], failure [" +
-                   ExceptionsHelper.detailedMessage(failure) + "], markAsStale [" + markAsStale + "]";
+        return "failed shard, shard " + routingEntry + ", message [" + message + "], markAsStale [" + markAsStale + "], failure ["
+            + ExceptionsHelper.stackTrace(failure) + "]";
```
Comment (pugnascotia) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/FailedShard.java]: I changed the order of fields here so that the stack trace comes last.

File: server/src/main/java/org/elasticsearch/cluster/action/shard/ShardStateAction.java [hunk 2]
```diff
@@ -444,10 +444,10 @@ public String toString() {
             components.add("allocation id [" + allocationId + "]");
             components.add("primary term [" + primaryTerm + "]");
             components.add("message [" + message + "]");
+            components.add("markAsStale [" + markAsStale + "]");
             if (failure != null) {
-                components.add("failure [" + ExceptionsHelper.detailedMessage(failure) + "]");
+                components.add("failure [" + ExceptionsHelper.stackTrace(failure) + "]");
```
Comment (pugnascotia) [inline server/src/main/java/org/elasticsearch/cluster/action/shard/ShardStateAction.java]: Also changed the order of elements here, so the stack trace is last.

File: server/src/main/java/org/elasticsearch/ElasticsearchException.java [hunk 3]
```diff
@@ -681,7 +681,7 @@ public String toString() {
             }
             builder.append(' ');
         }
-        return builder.append(ExceptionsHelper.detailedMessage(this).trim()).toString();
+        return builder.append(super.toString().trim()).toString();
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/ElasticsearchException.java]: Won't we lose all stack information by just using the exception tostring?

File: server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGeneratorBuilder.java [hunk 4]
```diff
@@ -490,7 +490,7 @@ public String toString() {
             toXContent(builder, EMPTY_PARAMS);
             return Strings.toString(builder);
         } catch (Exception e) {
-            return "{ \"error\" : \"" + ExceptionsHelper.detailedMessage(e) + "\"}";
+            throw new RuntimeException(e);
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGeneratorBuilder.java]: Do we have a test for this failure case so we know the response is not already too far written to throw/serialize an exception like this?

**Review by rjernst — COMMENTED** [review]
Thanks, this looks better to me. I left a couple last questions, and would also appreicate @jasontedor's opinion on whether using a full stack trace is always appropriate (IMO compared to the useless/reduced info from detailedmessage stacktrace is better).

File: server/src/main/java/org/elasticsearch/ElasticsearchException.java (hunk 3 above)
Comment (pugnascotia) [reply server/src/main/java/org/elasticsearch/ElasticsearchException.java]: Only if whatever's calling `ElasticsearchException.toString()` isn't also printing the stack trace. The problem with calling `ElasticsearchException.stackTrace()` here is that it calls `.toString()` on the exception, so you end up blowing the stack. `detailedMessage()` didn't do this because it essentially reimplemented `Throwable.toString()`. Open to ideas here.

File: server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGeneratorBuilder.java (hunk 4 above)
Comment (pugnascotia) [reply server/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGeneratorBuilder.java]: We do have integration tests in `SearchSuggestIT` with failure cases, but they don't look related to a failure to serialize content. I'd be happy to add a new test - any ideas how to provoke a failure when serialising a `DirectCandidateGeneratorBuilder` to XContent?

**Review by rjernst — APPROVED** [review]
LGTM once CI passes

File: server/src/test/java/org/elasticsearch/action/admin/indices/close/CloseIndexResponseTests.java [hunk 5]
```diff
@@ -113,7 +113,9 @@ protected void assertEqualInstances(CloseIndexResponse expected, CloseIndexRespo
                             assertThat(actualFailure.getNodeId(), equalTo(expectedFailure.getNodeId()));
                             assertThat(actualFailure.index(), equalTo(expectedFailure.index()));
                             assertThat(actualFailure.shardId(), equalTo(expectedFailure.shardId()));
-                            assertThat(actualFailure.reason(), equalTo(expectedFailure.reason()));
+                            // Serialising and deserialising an exception seems to remove the "java.base/" part from the stack trace,
+                            // so these string replacements account for this.
+                            assertThat(actualFailure.reason().replace("java.base/", ""), equalTo(expectedFailure.reason().replace("java.base/", "")));
```
Comment (pugnascotia) [inline server/src/test/java/org/elasticsearch/action/admin/indices/close/CloseIndexResponseTests.java]: I made this change (and again in 1 other class) to get the test to pass, but I don't like it. I'd appreciate other suggestions.

File: server/src/test/java/org/elasticsearch/action/admin/indices/close/CloseIndexResponseTests.java [hunk 6]
```diff
@@ -113,7 +113,11 @@ protected void assertEqualInstances(CloseIndexResponse expected, CloseIndexRespo
                             assertThat(actualFailure.getNodeId(), equalTo(expectedFailure.getNodeId()));
                             assertThat(actualFailure.index(), equalTo(expectedFailure.index()));
                             assertThat(actualFailure.shardId(), equalTo(expectedFailure.shardId()));
-                            assertThat(actualFailure.reason(), equalTo(expectedFailure.reason()));
+                            // Serialising and deserialising an exception seems to remove the "java.base/" part from the stack trace,
+                            // so these string replacements account for this.
+                            assertThat(
+                                actualFailure.reason().replace("java.base/", ""),
```
Comment (rjernst) [inline server/src/test/java/org/elasticsearch/action/admin/indices/close/CloseIndexResponseTests.java]: Can we check for a portion of the failure instead of an exact stack trace?

File: server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java [hunk 7]
```diff
@@ -368,7 +368,7 @@ private void internalRecoverFromStore(IndexShard indexShard) throws IndexShardRe
                         files = Arrays.toString(store.directory().listAll());
                     } catch (Exception inner) {
                         inner.addSuppressed(e);
```
[the remark this answers is not in the document]
Comment (pugnascotia) [reply server/src/main/java/org/elasticsearch/index/shard/StoreRecovery.java]: Agreed, I've removed this line.

File: server/src/test/java/org/elasticsearch/action/admin/indices/close/CloseIndexResponseTests.java (hunk 6 above)
Comment (pugnascotia) [reply server/src/test/java/org/elasticsearch/action/admin/indices/close/CloseIndexResponseTests.java]: Yes, I've reworked both instances of this.

**Comment by pugnascotia** [comment]
@elasticsearch run elasticsearch-ci/1

**Comment by pugnascotia** [comment]
@rjernst I've merged in `master` again, would you mind taking another look?

File: qa/smoke-test-http/build.gradle [hunk 8]
```diff
@@ -23,6 +23,7 @@ apply plugin: 'elasticsearch.rest-test'
 apply plugin: 'elasticsearch.test-with-dependencies'
 
 dependencies {
+    testCompile("com.fasterxml.jackson.core:jackson-databind:2.8.11")
```
Comment (rjernst) [inline qa/smoke-test-http/build.gradle]: nit: we normally do this without the parens so it maintains the "dsl" look

File: server/src/test/java/org/elasticsearch/search/query/SearchQueryIT.java [hunk 9]
```diff
@@ -626,9 +631,23 @@ public void testMultiMatchQuery() throws Exception {
...
-                containsString("NumberFormatException[For input string: \"value1\"]"));
+        //when the number for shards is randomized and we expect failures
+        //we can either run into partial or total failures depending on the current number of shards
+        Matcher<String> reasonMatcher = containsString("NumberFormatException: For input string: \"value1\"");
+        ShardSearchFailure[] shardFailures;
+        try {
+            client().prepareSearch().setQuery(builder).get();
+            shardFailures = searchResponse.getShardFailures();
+            assertThat("Expected shard failures, got none", shardFailures, not(emptyArray()));
+        } catch (SearchPhaseExecutionException e) {
```
Comment (rjernst) [inline server/src/test/java/org/elasticsearch/search/query/SearchQueryIT.java]: we should use expectThrows here

**Review by rjernst — APPROVED** [review]
LGTM, two last nits

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/2
