### PR TITLE
ES|QL: limit query depth to 500 levels

### LINKED ISSUE #107752: ESQL: repetitive function calls could create a stackoverflow error
### Description

A query made simpler to write by `::` (but could probably be replicated with any nested function call) casting operator can lead to StackoverflowError:

`ROW v=123::string::version::string::version::......`

On my computer, ~1923 such casting calls leads to Stackoverflow. Interestingly enough, it's sometimes 1923, sometimes less if I call the query several times.
Also, still interesting, different stack traces where the overflow occurs:

1.

```
        at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:208)
        at org.elasticsearch.xpack.ql.tree.Node.transformDown(Node.java:179)
        at org.elasticsearch.xpack.ql.tree.Node.lambda$transformDown$8(Node.java:179)
        at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:211)
        at org.elasticsearch.xpack.ql.tree.Node.transformDown(Node.java:179)
        at org.elasticsearch.xpack.ql.tree.Node.lambda$transformDown$8(Node.java:179)
        at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:211)
        at org.elasticsearch.xpack.ql.tree.Node.transformDown(Node.java:179)
...
```

2.

```
        at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:501)
        at org.elasticsearch.xpack.esql.evaluator.mapper.EvaluatorMapper.lambda$fold$1(EvaluatorMapper.java:48)
        at org.elasticsearch.xpack.esql.expression.function.scalar.convert.AbstractConvertFunction.toEvaluator(AbstractConvertFunction.java:105)
        at org.elasticsearch.xpack.esql.evaluator.mapper.EvaluatorMapper.fold(EvaluatorMapper.java:48)
        at org.elasticsearch.xpack.esql.expression.function.scalar.EsqlScalarFunction.fold(EsqlScalarFunction.java:30)
        at org.elasticsearch.xpack.esql.evaluator.mapper.EvaluatorMapper$1.eval(EvaluatorMapper.java:51)
        at org.elasticsearch.xpack.esql.expression.function.scalar.convert.AbstractConvertFunction$AbstractEvaluator.eval(AbstractConvertFunction.java:138)
        at org.elasticsearch.xpack.esql.evaluator.mapper.EvaluatorMapper.fold(EvaluatorMapper.java:62)
        at org.elasticsearch.xpack.esql.expression.function.scalar.EsqlScalarFunction.fold(EsqlScalarFunction.java:30)
        at org.elasticsearch.xpack.esql.evaluator.mapper.EvaluatorMapper$1.eval(EvaluatorMapper.java:51)
        at org.elasticsearch.xpack.esql.expression.function.scalar.convert.AbstractConvertFunction$AbstractEvaluator.eval(AbstractConvertFunction.java:138)
        at org.elasticsearch.xpack.esql.evaluator.mapper.EvaluatorMapper.fold(EvaluatorMapper.java:62)
        at org.elasticsearch.xpack.esql.expression.function.scalar.EsqlScalarFunction.fold(EsqlScalarFunction.java:30)
        at org.elasticsearch.xpack.esql.evaluator.mapper.EvaluatorMapper$1.eval(EvaluatorMapper.java:51)
        at org.elasticsearch.xpack.esql.expression.function.scalar.convert.AbstractConvertFunction$AbstractEvaluator.eval(AbstractConvertFunction.java:138)
        at org.elasticsearch.xpack.esql.evaluator.mapper.EvaluatorMapper.fold(EvaluatorMapper.java:62)
```

Shorter queries are caught at parsing time, but it's not an ideal catch either, since the stackoverflow happens and the error is caught, an exception is thrown instead. The JVM could still be ok, but also not always.

```
                "type": "parsing_exception",
                "reason": "line -1:0: ESQL statement is too large, causing stack overflow when generating the parsing tree
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
To avoid StackOverflow errors, this PR adds a hard limit to 500 as maximum query depth, that means

- 500 commands per query at most
- nested expressions can be 500 levels deep at most

The two limits are independent, that means a valid query can have 499 commands AND expressions that are 499 levels deep at the same time.

The limit is enforced at query parse time

Fixes https://github.com/elastic/elasticsearch/issues/107752

### CODE REVIEW

**Review by costin — APPROVED** [review]
👍

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -4023,6 +4026,118 @@ public void testRejectRemoteEnrichAfterCoordinatorEnrich() {
...
+    }
+
+    public void testMaxExpressionDepth_mixed() {
+        String prefix = "abs(";
+        String suffix = " + 12)";
+
+        String from = "row a = 1 | eval b = ";
+
+        StringBuilder queryBuilder = new StringBuilder();
+        queryBuilder.append(prefix.repeat(MAX_EXPRESSION_DEPTH / 2 - 1));
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java:4095]: We need a good explanation in docs about this limitation, because `abs(12)` can be considered as one expression by the end user. `abs(abs(12))` - 2 expressions and so on. In total we have a query that is made of MAX_EXPRESSION_DEPTH / 2 expressions. OR we define MAX_EXPRESSION_DEPTH as 250 and everything we check (expressionbuidler and tests will be against MAX_EXPRESSION_DEPTH * 2).

**Review by astefan — APPROVED** [review]
LGTM with one comment about a possible confusing error message (vs. reality).
Also, have you tested larger max depth numbers? Is this the absolute maximum values we can use?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/PhysicalPlanOptimizerTests.java:4095]: In this specific case it's `abs(a + 12)` (and recursively `abs(abs(a + 12) + 12)`) that is actually two expressions, so the test is coherent with  MAX_EXPRESSION_DEPTH.
We definitely need an explanation for the parentheses alone (eg. `(a)` see my [other comment](https://github.com/elastic/elasticsearch/pull/108089/files#r1584808445) above), because in that case it's really only one expression that accounts for two. I guess we can clarify it in the docs.

**Comment by luigidellaquila** [comment]
> Also, have you tested larger max depth numbers? Is this the absolute maximum values we can use?

@astefan that's not the higher limit we can reach, 1000 is still good for a unit test, but not for all the scenarios in a real deploy (see the failure you identified at ~1923) where the stack is much deeper. 
500 is the best "round" threshold that gives us enough guarantees; in the future, if there is a real need, raising it will be much less problematic than lowering it.
