### PR TITLE
Fix expiration time in ES|QL async

### LINKED ISSUE #135169: [ES|QL] When requesting GET /_query/async/{id}?keep_alive={time} while the query is running keep_alive is ignored
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOs 15.6.1

### Problem Description

When requesting async ESQL query results using 

`GET /_query/async/{id}?keep_alive={time}`

While there query is still running, the new value of `keep_alive` doesn't prevent the query to 404 after the initial `keep_alive` time that was set

### Steps to Reproduce

Start a query with a given DELAY to make sure it's running while you use the GET API

```
POST /_query/async?drop_null_columns
{
   "wait_for_completion_timeout":"200ms",
   "keep_on_completion":true,
   "keep_alive":"10000ms",
   "query":"FROM kibana_sample_data_ecommerce | EVAL delay = DELAY(20000ms) | LIMIT 1",
   "locale":"en",
   "include_ccs_metadata":true
}
```

Use the id of the query to increase the intended `keep_alive` value

`GET /_query/async/{id}?keep_alive=1500000ms`

Then use the following request to get the results of a query, request it after roughly 30s or a little bit more, after the query returned results and the `keep_alive` period is over 

`GET /_query/async/{id}`

then the request will return a 404, because the resource with the actual id as been cleaned up. 

Expected result should be that the `keep_alive` can be extended also in the running state, like it works in DSL

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by dnhatn**
Currently, we incorrectly use the initial keep-alive value when creating the document for the async response. Instead, we should use the latest expiration from the search task, which is updated by get requests.

Closes #135169

### CODE REVIEW

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/async/AsyncTaskManagementService.java [hunk 1]
```diff
@@ -227,7 +225,7 @@ private ActionListener<Response> wrapStoringListener(
                 if (keepOnCompletion) {
                     storeResults(
                         searchTask,
-                        new StoredAsyncResponse<>(response, threadPool.absoluteTimeInMillis() + keepAlive.getMillis()),
+                        new StoredAsyncResponse<>(response, searchTask.getExpirationTimeMillis()),
```
Comment (dnhatn) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/async/AsyncTaskManagementService.java:228]: These lines are the main fix.

**Review by nik9000 — APPROVED** [review]

**Comment by dnhatn** [comment]
Thanks Nik!
