### PR TITLE
Reduce follower cluster state lag timeout for disruption tests

### LINKED ISSUE #91447: [CI] ClusterDisruptionIT testAckedIndexing failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/262tw2urcmfja/tests/:server:internalClusterTest/org.elasticsearch.discovery.ClusterDisruptionIT/testAckedIndexing

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.discovery.ClusterDisruptionIT.testAckedIndexing" -Dtests.seed=F227DC2661BD3347 -Dtests.locale=sr-Latn-RS -Dtests.timezone=America/Halifax -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.discovery.ClusterDisruptionIT&tests.test=testAckedIndexing

**Failure excerpt:**
```
java.lang.AssertionError: failed to reach a stable cluster of [3] nodes. Tried via [node_t0]. last cluster state:
cluster uuid: -XwQ51BpTsyQMw_Wjp7XDg [committed: true]
version: 64
state uuid: XfzY1rwHSNWCym8FAHukTg
from_diff: false
meta data version: 16
   coordination_metadata:
      term: 2
      last_committed_config: VotingConfiguration{JuSgh8LOR9WQxzHHDqqlVQ,teMmveWdQ8eJomW0l7COzg,XZTfvsT_T8G2zfpKc6vMiQ}
      last_accepted_config: VotingConfiguration{JuSgh8LOR9WQxzHHDqqlVQ,teMmveWdQ8eJomW0l7COzg,XZTfvsT_T8G2zfpKc6vMiQ}
      voting tombstones: []
   [test/0e3yQZiiQryESs-x7Qtacw]: v[13], mv[4], sv[1], av[1]
      0: p_term [1], isa_ids [GgrbxbMaTNCpILvZl4Ep7A, vByWNTvzQHKjmYEG4ZNTeg]
      1: p_term [1], isa_ids [v_Fpb5_fRW-Di9kVj35n6g, geKyf7jqSVWDQpWqMVQTmw]
metadata customs:
   index-graveyard: IndexGraveyard[[]]   persistent_tasks: {"last_allocation_id":1,"tasks":[{"id":"health-node","task":{"health-node":{"params":{}}},"allocation_id":1,"assignment":{"executor_node":"JuSgh8LOR9WQxzHHDqqlVQ","explanation":""}}]}
nodes: 
   {node_t1}{XZTfvsT_T8G2zfpKc6vMiQ}{GEOyX6yBQK6q12UWfW01AA}{node_t1}{127.0.0.1}{127.0.0.1:19091}{cdfhilmrstw}
   {node_t2}{JuSgh8LOR9WQxzHHDqqlVQ}{Di5DKi8_Q3OesY4wpcnCfA}{node_t2}{127.0.0.1}{127.0.0.1:19093}{cdfhilmrstw}, master
   {node_t0}{teMmveWdQ8eJomW0l7COzg}{UqjXsHaTQKax1c3zc-P9iA}{node_t0}{127.0.0.1}{127.0.0.1:19092}{cdfhilmrstw}
routing_table (version 14):
-- index [[test/0e3yQZiiQryESs-x7Qtacw]]
----shard_id [test][0]
--------[test][0], node[teMmveWdQ8eJomW0l7COzg], [R], s[STARTED], a[id=vByWNTvzQHKjmYEG4ZNTeg], failed_attempts[0]
--------[test][0], node[JuSgh8LOR9WQxzHHDqqlVQ], [P], s[STARTED], a[id=GgrbxbMaTNCpILvZl4Ep7A], failed_attempts[0]
----shard_id [test][1]
--------[test][1], node[teMmveWdQ8eJomW0l7COzg], relocating [XZTfvsT_T8G2zfpKc6vMiQ], [P], s[RELOCATING], a[id=v_Fpb5_fRW-Di9kVj35n6g, rId=vG7OtoSySlafxcOzoHgVMA], failed_attempts[0], expected_shard_size[225]
--------[test][1], node[JuSgh8LOR9WQxzHHDqqlVQ], [R], s[STARTED], a[id=geKyf7jqSVWDQpWqMVQTmw], failed_attempts[0]

routing_nodes:
-----node_id[teMmveWdQ8eJomW0l7COzg][V]
--------[test][0], node[teMmveWdQ8eJomW0l7COzg], [R], s[STARTED], a[id=vByWNTvzQHKjmYEG4ZNTeg], failed_attempts[0]
--------[test][1], node[teMmveWdQ8eJomW0l7COzg], relocating [XZTfvsT_T8G2zfpKc6vMiQ], [P], s[RELOCATING], a[id=v_Fpb5_fRW-Di9kVj35n6g, rId=vG7OtoSySlafxcOzoHgVMA], failed_attempts[0], expected_shard_size[225]
-----node_id[JuSgh8LOR9WQxzHHDqqlVQ][V]
--------[test][0], node[JuSgh8LOR9WQxzHHDqqlVQ], [P], s[STARTED], a[id=GgrbxbMaTNCpILvZl4Ep7A], failed_attempts[0]
--------[test][1], node[JuSgh8LOR9WQxzHHDqqlVQ], [R], s[STARTED], a[id=geKyf7jqSVWDQpWqMVQTmw], failed_attempts[0]
-----node_id[XZTfvsT_T8G2zfpKc6vMiQ][V]
--------[test][1], node[XZTfvsT_T8G2zfpKc6vMiQ], relocating [teMmveWdQ8eJomW0l7COzg], [P], recovery_source[peer recovery], s[INITIALIZING], a[id=vG7OtoSySlafxcOzoHgVMA, rId=v_Fpb5_fRW-Di9kVj35n6g], failed_attempts[0], expected_shard_size[225]
---- unassigned
customs:
   health: org.elasticsearch.health.metadata.HealthMetadata@ff2c405a

  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.test.ESIntegTestCase.ensureStableCluster(ESIntegTestCase.java:1295)
  at org.elasticsearch.discovery.ClusterDisruptionIT.testAckedIndexing(ClusterDisruptionIT.java:224)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by DiannaHohensee**
It's possible for a node-left task to get interrupted prior to removing
the node from the master's list of faultyNodes. Nodes on the faultyNodes
list do not receive cluster state updates, and are eventually removed.

Subsequently, when the node attempts to rejoin, after test network
disruptions have ceased, the node-join request can succeed, but the
node will never receive the cluster state update, consider the node-join
a failure, and will resend node-join requests until the LagDetector
removes the node from the faultyNodes list.
https://github.com/elastic/elasticsearch/issues/108690 will address the
node-join issue.

Closes #91447

------------------------------------
Much belatedly circling back to this.

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/discovery/ClusterDisruptionIT.java [hunk 1]
```diff
@@ -94,18 +93,11 @@ static ConflictMode randomMode() {
...
 
     /**
-     * Test that we do not loose document whose indexing request was successful, under a randomly selected disruption scheme
+     * Test that we do not lose documents, indexed via requests that return success, under randomly selected disruption schemes.
      * We also collect &amp; report the type of indexing failures that occur.
      * <p>
-     * This test is a superset of tests run in the Jepsen test suite, with the exception of versioned updates
+     * This test is a superset of tests run in the Jepsen test suite, with the exception of versioned updates.
      */
-    @TestIssueLogging(
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/discovery/ClusterDisruptionIT.java:102]: I would suggest leaving this logging in place, although recording it as `@TestIssueLogging` for #41068 is clearly not accurate. Let's make it a `@TestLogging` with `reason = "if this test fails we need all this logging to understand the failure"` or similar.

**Review by DaveCTurner — APPROVED** [review]
LGTM, one suggestion
