### PR TITLE
top_metrics: consistently allow sorting by size>1

### LINKED ISSUE #86663: Incosistent behaviour while setting `rewrite_to_filter_by_filter` to true or false
### Elasticsearch Version

8.3.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

All

### Problem Description

In `rest-api-spec/test/analytics/nested_top_metrics_sort.yml` there are the following two tests:

* `terms order by top metrics size greater than 1 rewrite_to_filter_by_filter false`
* `terms order by top metrics size greater than 1 rewrite_to_filter_by_filter true`

Both tests execute the same query. The only difference is in the setting of `rewrite_to_filter_by_filter`, in one case it is `true` in the other it is `false`. The setting determines if the query is rewritten using the so called "filter by filter" optimisation. Query rewriting is an implementation detail and we should make sure the response provided to the client is the same no matter the value of the setting.

Here one query fails with an exception while the other not. We need to make sure the result is the same. We either fail both or we return the same aggregation result.

NOTE: right now the test is not failing because they are written in such a way to highlight the difference. After fixing the issue we expect to have the same result.

### Steps to Reproduce

Just execute the YAML tests.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by nik9000**
This allows aggregations like `terms` to sort by `top_metrics` aggs who's size is `> 1`. In that case we take the metric with the top sort value. This has been supported when rewriting as filter-by-filter for a while, but not in the compatible collection mode.

Closes #86663

### CODE REVIEW

File: x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/topmetrics/TopMetricsAggregator.java [hunk 1]
```diff
@@ -104,14 +101,7 @@ public boolean hasMetric(String name) {
...
     public double metric(String name, long owningBucketOrd) {
-        assert size == 1;
-        /*
-         * Since size is always 1 we know that the index into the values
-         * array is same same as the bucket ordinal. Also, this will always
-         * be called after we've collected a bucket, so it won't just fetch
-         * garbage.
-         */
-        return metrics.metric(name, owningBucketOrd);
+        return metrics.metric(name, owningBucketOrd * size);
```
Comment (salvatore-campagna) [inline x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/topmetrics/TopMetricsAggregator.java:104]: I don't get why we here compute index as `owningBucketOrd * 2`.

Comment (salvatore-campagna) [reply x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/topmetrics/TopMetricsAggregator.java:104]: Also, if we always take the latest...since `owningBucketOrd * size` should be always the latest element in the array, I guess the actual value will depend on whether data is sorted in ascending or descending order.

**Review by salvatore-campagna — APPROVED** [review]

**Comment by salvatore-campagna** [comment]
LGTM. I just had a couple of questions.

File: x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/topmetrics/TopMetricsAggregator.java (hunk 1 above)
Comment (nik9000) [reply x-pack/plugin/analytics/src/main/java/org/elasticsearch/xpack/analytics/topmetrics/TopMetricsAggregator.java:104]: It's the *first* element in the array.

File: x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/topmetrics/TopMetricsAggregatorTests.java [hunk 2]
```diff
@@ -328,6 +329,50 @@ public void testInsideTerms() throws IOException {
...
+        assertThat(top1.getSortOrder(), equalTo(SortOrder.ASC));
+        assertThat(top1.getTopMetrics(), equalTo(singletonList(top(4.0, 2.0))));
+        Terms.Bucket bucket2 = result.getBuckets().get(1);
+        assertThat(bucket2.getKey(), equalTo(1.0));
+        InternalTopMetrics top2 = bucket2.getAggregations().get("test");
+        assertThat(top2.getSortOrder(), equalTo(SortOrder.ASC));
+        assertThat(top2.getTopMetrics(), equalTo(singletonList(top(1.0, 9.0))));
+    }
+
+    public void testTermsSortedByMulti() throws IOException {
```
Comment (nik9000) [inline x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/topmetrics/TopMetricsAggregatorTests.java:354]: Hmm - I really should collect more than one value here just to test that too.

Comment (nik9000) [reply x-pack/plugin/analytics/src/test/java/org/elasticsearch/xpack/analytics/topmetrics/TopMetricsAggregatorTests.java:354]: Ah! I already do that. I sorry, it's hard to read.....
