### PR TITLE
Rollup jobs should be cleaned up before indices are deleted

### LINKED ISSUE #35295: RollupDocumentationIT.testStartRollupJob fails
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/42/console

```
12:57:00 ERROR   0.36s | RollupDocumentationIT.testStartRollupJob <<< FAILURES!
12:57:00    > Throwable #1: org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:52535], URI [/_xpack/rollup/job/job_1], status line [HTTP/1.1 500 Internal Server Error]
12:57:00    > {"task_failures":[{"task_id":8905,"node_id":"FhzPJ_ibQoS6vX9AbmETzA","status":"INTERNAL_SERVER_ERROR","reason":{"type":"illegal_state_exception","reason":"Could not delete job [job_1] because indexer state is [STOPPING].  Job must be [STOPPED] before deletion."}}],"acknowledged":false}
12:57:00    > 	at __randomizedtesting.SeedInfo.seed([8485FBE4F308CC81:EB88BE3030DD61E3]:0)
12:57:00    > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:687)
12:57:00    > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:218)
12:57:00    > 	at org.elasticsearch.client.documentation.RollupDocumentationIT.deleteRollupJobs(RollupDocumentationIT.java:437)
12:57:00    > 	at org.elasticsearch.client.documentation.RollupDocumentationIT.wipeRollup(RollupDocumentationIT.java:417)
12:57:00    > 	at java.lang.Thread.run(Thread.java:748)
```

Reproduce line (though does not repro locally):

```
REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner -Dtests.seed=8485FBE4F308CC81 -Dtests.class=org.elasticsearch.client.documentation.RollupDocumentationIT -Dtests.method="testStartRollupJob" -Dtests.security.manager=true -Dtests.locale=ru-RU -Dtests.timezone=Africa/Malabo -Dcompiler.java=11 -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by polyfractal**
Rollup jobs should be stopped + deleted before the indices are removed. It's possible for an active rollup job to issue a bulk request, the test ends and the cleanup code deletes all indices.  The in-flight bulk request will then stall + error because the index no-longer exists... but this process might take longer than the StopRollup timeout.

Which means the test fails, and often fails several other tests since the job is still active (e.g. other tests cannot create the same-named job, or fail to stop the job in their cleanup because it's still stalled, etc).  This tends to knock over several tests before the bulk finally times out and the job shuts down.

Instead, we need to simply stop jobs first.  Inflight bulks will resolve quickly, and we can carry on with deleting indices after the jobs are confirmed inactive.

stop-job.asciidoc tended to trigger this issue because it executed an async stop API and then exited, which tended to raise the above timing situation. In can and did happen with other tests though.  As an extra precaution, the doc test was modified to substitute in wait_for_completion to help head off these issues too.

Should, theoretically, close https://github.com/elastic/elasticsearch/issues/35295 and https://github.com/elastic/elasticsearch/issues/38877, both which I think are caused by the same issue.  The timing issue reproduces so rarely it's hard to say for certain, but I'll keep my machine crunching on it too.

### CODE REVIEW

**Review by talevy — APPROVED** [review]
LGTM

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -458,6 +458,15 @@ protected boolean preserveILMPoliciesUponCompletion() {
     }
 
     private void wipeCluster() throws Exception {
+
+        // Cleanup rollup before deleting indices.  A rollup job might have bulks in-flight,
+        // so if we need to fully shut them down first otherwise a job might stall waiting
```
Comment (jimczi) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: nit: s/so if/so/

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/1
