### PR TITLE
Pull alpine image in a retry in Docker tests

### LINKED ISSUE #88651: [CI] DockerTests test071BindMountCustomPathWithDifferentUID failing
Looks like a timeout error that occurs sporadically (https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P90D&search.timeZoneId=Europe/Zurich&tests.container=org.elasticsearch.packaging.test.DockerTests&tests.test=test071BindMountCustomPathWithDifferentUID)

**Build scan:**
https://gradle-enterprise.elastic.co/s/jbwalyqbqnzry/tests/:qa:os:destructiveDistroTest.default-docker/org.elasticsearch.packaging.test.DockerTests/test071BindMountCustomPathWithDifferentUID

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DockerTests&tests.test=test071BindMountCustomPathWithDifferentUID

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c docker run --rm --volume "/tmp/DockerTests13344726983695476209:/mount/tmp/DockerTests13344726983695476209" alpine:3.13 /bin/sh -c "mkdir /mount/tmp/DockerTests13344726983695476209/esDataDir && chown 1500:0 /mount/tmp/DockerTests13344726983695476209/esDataDir && chmod 0770 /mount/tmp/DockerTests13344726983695476209/esDataDir"]
   result: exitCode = [125] stdout = [] stderr = [Unable to find image 'alpine:3.13' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.]

  at __randomizedtesting.SeedInfo.seed([D7A7CCFA9B5049AB:9AEB833D01EECE93]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.util.docker.Docker.executePrivilegeEscalatedShellCmd(Docker.java:368)
  at org.elasticsearch.packaging.util.docker.Docker.mkDirWithPrivilegeEscalation(Docker.java:388)
  at org.elasticsearch.packaging.test.DockerTests.lambda$test071BindMountCustomPathWithDifferentUID$2(DockerTests.java:477)
  at org.elasticsearch.packaging.util.Platforms.onLinux(Platforms.java:63)
  at org.elasticsearch.packaging.test.DockerTests.test071BindMountCustomPathWithDifferentUID(DockerTests.java:474)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #88651. When using an `alpine` image to perform container
fiddling, first explicitly pull the image and do so in a loop, in an
attempt to make things more robust.

### CODE REVIEW

File: qa/os/src/test/java/org/elasticsearch/packaging/util/docker/Docker.java [hunk 1]
```diff
@@ -368,6 +371,24 @@ private static void executePrivilegeEscalatedShellCmd(String shellCmd, Path loca
...
+    private static void ensureImageIsPulled(String image) {
+        // Don't pull if the image already exists. This does also mean that we never refresh it, but that
+        // isn't an issue in CI.
+        if (sh.runIgnoreExitCode("docker image inspect -f '{{ .Id }}' " + image).isSuccess()) {
+            return;
+        }
+
+        Shell.Result result = null;
+        int i = 0;
+        while (i++ < 10) {
```
Comment (mark-vieira) [inline qa/os/src/test/java/org/elasticsearch/packaging/util/docker/Docker.java:383]: I think we should probably do this fewer times (maybe 3) and put a slight delay in between each attempt.

File: qa/os/src/test/java/org/elasticsearch/packaging/util/docker/Docker.java [hunk 2]
```diff
@@ -368,6 +371,24 @@ private static void executePrivilegeEscalatedShellCmd(String shellCmd, Path loca
...
+            result = sh.runIgnoreExitCode("docker pull -q " + image);
```
Comment (mark-vieira) [inline qa/os/src/test/java/org/elasticsearch/packaging/util/docker/Docker.java:384]: Will using `-q` mean we won't get the cause of the error?

**Review by mark-vieira — APPROVED** [review]

**Comment by pugnascotia** [comment]
Backported to `7.17` in 057eea99c6f.
