### PR TITLE
SQL: Escaped wildcard (*) not accepted in LIKE

### LINKED ISSUE #55108: SQL: escaped wildcard (*) not accepted in LIKE pattern
For a query like `SELECT name FROM test WHERE name LIKE '%c*'` ES SQL generates an error. `*` is not a special character in a `LIKE` construct and it's expected to not needing to be escaped, so the previous query should work as is.

The generated error is:
```
{
    "error": {
        "root_cause": [
            {
                "type": "parsing_exception",
                "reason": "line 1:40: Invalid char [*] found in pattern [%c*] at position 2; use [%] or [_] instead"
            }
        ],
        "type": "parsing_exception",
        "reason": "line 1:40: Invalid char [*] found in pattern [%c*] at position 2; use [%] or [_] instead"
    },
    "status": 400
}
```

### PR DESCRIPTION
**Pull request by palesz**
For a query like `SELECT name FROM test WHERE name LIKE '%c*'` ES SQL generates an error. `*` is not a special character in a `LIKE` construct and it's expected to not needing to be escaped, so the previous query should work as is.
In the `LIKE` pattern any `*` character was treated as invalid character and the usage of `%` or `_` was suggested instead. But `*` is a valid, acceptable non-wildcard on the right side of the `LIKE` operator.

Fix: #55108

### CODE REVIEW

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java [hunk 1]
```diff
@@ -29,7 +29,7 @@ private String error(String pattern) {
     }
 
     private LikePattern like(String pattern) {
-        Expression exp = null;
+        Expression exp;
```
Comment (costin) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java:32]: Please revert.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java [hunk 2]
```diff
@@ -270,12 +270,6 @@ public LikePattern visitPattern(PatternContext ctx) {
         if (pattern == null) {
             throw new ParsingException(source(ctx.value), "Pattern must not be [null]");
         }
-        int pos = pattern.indexOf('*');
-        if (pos >= 0) {
-            throw new ParsingException(source(ctx.value),
-                    "Invalid char [*] found in pattern [{}] at position {}; use [%] or [_] instead",
-                    pattern, pos);
-        }
```
Comment (palesz) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:278]: @costin Did I miss anything, is there a reason to keep this check here?

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java [hunk 3]
```diff
@@ -63,8 +63,15 @@ public void testInvalidChar() {
...
+        LikePattern like = like("%string*");
+        assertThat(like.pattern(), is("%string*"));
+        assertThat(like.asJavaRegex(), is("^.*string\\*$"));
+        assertThat(like.asLuceneWildcard(), is("*string\\*"));
+    }
+
+    public void testCannotUseStarWithEscaping() {
         assertThat(error("'|*string' ESCAPE '|'"),
-                is("line 1:11: Invalid char [*] found in pattern [|*string] at position 1; use [%] or [_] instead"));
+            is("line 1:11: Pattern [|*string] is invalid as escape char [|] at position 0 can only escape wildcard chars; found [*]"));
```
Comment (matriv) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java:75]: Should we maybe improve the error message by listing the wildcard chars for LIKE: `%` and `_` ?

**Review by costin — COMMENTED** [review]
Please do use Markdown as in the initial report (even more so when copy-pasting) - it improves readability a lot.

**Review by matriv — COMMENTED** [review]
Looks good, Maybe add one more test with a more complicated string, something like:
`*%*_string*_**%`. Left one more comment about the error message.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:278]: To prevent folks from using `*` instead of `%`. Whether that's still a concern I don't know.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java (hunk 1 above)
Comment (palesz) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java:32]: Will do. I was wondering what is your convention.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:278]: We don't have anything in the docs regarding the `*` and we list only the `%` and `_` 
`*` should be interpreted as a normal char for SQL:
```
postgres=# create table mytable (str varchar(10));
CREATE TABLE

postgres=# insert into mytable values('*test*'), ('as*test*fd');
INSERT 0 2

postgres=# select * from mytable where str like ('%*test*%');
    str
------------
 *test*
 as*test*fd
(2 rows)

postgres=# select * from mytable where str like ('*test*');
  str
--------
 *test*
(1 row)
```

How about adding a NOTE in the docs to explicitly specify that `*`, `?` and the usual regex chars are interpreted as normal chars?

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java:32]: Generally speaking, I don't have a strong preference for explicitly initialising as `null` but some times it helps for readability. In this case we have a clear if/else statement that assigns a value, so imho is not so important.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java (hunk 3 above)
Comment (palesz) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/LikeEscapingParsingTests.java:75]: > Looks good, Maybe add one more test with a more complicated string, something like:
> `*%*_string*_**%`. Left one more comment about the error message.

Will add a new test case, but I will add it to the [LikeConversionTests](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/util/LikeConversionTests.java), since I think that has less to do with `ESCAPE`ing.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java (hunk 2 above)
Comment (palesz) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:278]: AFAIK it is only the MS Access SQL flavour that treats `*` as a wildcard in a `LIKE` pattern, so SQL folks should be fairly used to `*` not being a wildcard. ES customers with less SQL knowledge might not. I think adding a NOTE to the docs does not hurt.

Comment (palesz) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:278]: I am also thinking about removing the restriction on not being able to use `*` as an `ESCAPE` character from (here)[https://github.com/elastic/elasticsearch/blob/50fc9d52097cab6ac8b55625fc8b8f387688de13/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java#L285]. Do you see any good reason to keep that restriction?
As a user `*` would not be my first choice as an `ESCAPE` character, but the parser can handle it since `*` is just a normal character.

Comment (palesz) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:278]: On PostgreSQL, MySQL, SQLite any character can be used as ESCAPE (even wildchars) and any character can be escaped, not just wildcards. PostgreSQL treats the `'%%' ESCAPE '%'` as a non-wildcard `%` character (just as another escaped character), while MySQL and SQLite treat it as a wildcard (special escaping case). I assume it was intentional to behave differently and only allow escaping of the wildchars.

**Comment by palesz** [comment]
Sorry for the `force-push`, I should not have done that.

File: docs/reference/sql/functions/like-rlike.asciidoc [hunk 4]
```diff
@@ -33,8 +33,8 @@ with the `LIKE` operator:
 * The percent sign (%)
 * The underscore (_)
 
-The percent sign represents zero, one or multiple characters. The underscore represents a single number or character. These symbols can be
-used in combinations.
+No other characters have special meaning or act as wildcard. The percent sign represents zero, one or multiple characters.
```
Comment (matriv) [inline docs/reference/sql/functions/like-rlike.asciidoc:36]: Personally I'd add it as a `[NOTE]` below the existing sentence, so that it stands out.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:278]: As I see it, since only `%` and `_` are wildcards for `LIKE` I would only allow escaping of those, but if we go one with this change it shouldn't be part of the bugfix that would be backported, but for next minor release since it's a minor "breaking" change.

Comment (palesz) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:278]: Agree @matriv that allowing escaping any characters should be a separate PR and likely should be in the next minor release only, although technically it is less of a breaking change unless someone depends on the exceptions around escaping non-wildchars. Anyways, this is off topic for this PR.

To clarify: in this current PR I am only removing the special treatment of `*` and the restriction on using `*`as an `ESCAPE` character (wildchars are still not allowed as `ESCAPE` characters). Does this sound good to you?

**Review by bpintea — APPROVED** [review]

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:278]: Sorry for the confusion, but if `*` is not a wildcard anymore, maybe worths removing it as escape character as well in this fix? @costin what do you think?

**Review by matriv — APPROVED** [review]
LGTM. Thx!

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java [hunk 5]
```diff
@@ -288,7 +282,7 @@ public LikePattern visitPattern(PatternContext ctx) {
             } else if (escapeString.length() == 1) {
                 escape = escapeString.charAt(0);
                 // these chars already have a meaning
-                if (escape == '*' || escape == '%' || escape == '_') {
+                if (escape == '%' || escape == '_') {
                     throw new ParsingException(source(escapeCtx.escape), "Char [{}] cannot be used for escaping", escape);
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/ExpressionBuilder.java:286]: On the same idea (which I like) of actually[ mentioning the wildcard chars in the error message itself](https://github.com/elastic/elasticsearch/pull/63428/files#diff-3c0e68f5f3ff479d4817a66493f2d7decb2974c2368cb68bf2bae612b2b91743R301) (for the lazy user who doesn't read the docs and asking "why % char cannot be used for escaping?"), what about adapting this error message to include the reason? Something like `Char [%] cannot be used for escaping as it's one of the wildcard chars [%_]`.

**Review by astefan — APPROVED** [review]
Too late with the review. Sorry about that. Fwiw LGTM, with a minor cosmetic comment. Thanks.
