### PR TITLE
Fix ingest timezone logic

### LINKED ISSUE #51108: ingest date processor parsing
**Elasticsearch version**: 7.4.2

**JVM version** : openjdk version "1.8.0_232"

**OS version** : 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
trying to parse a timestamp with iso8601 format. I expect @timestamp 2020-01-15T**14**:28:09.452+01:00 but it shows 2020-01-15T**15**:28:09.452+01:00.

**Steps to reproduce**:

```
curl -XPOST 'http://localhost:9200/_ingest/pipeline/_simulate' \
-h 'Content-Type: application/json' -d'{
  "pipeline": {
    "processors": [
      {
        "date": {
          "field": "timestamp",
          "timezone": "+0100",
          "formats": [ "ISO8601"]
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "timestamp": "2020-01-15T14:28:09,452"
      }
    }
    ]
}'
```

Result:
```
{
    "docs": [
        {
            "doc": {
                "_index": "_index",
                "_type": "_doc",
                "_id": "_id",
                "_source": {
                    "@timestamp": "2020-01-15T15:28:09.452+01:00",
                    "timestamp": "2020-01-15T14:28:09,452"
                },
                "_ingest": {
                    "timestamp": "2020-01-16T15:06:47.477281Z"
                }
            }
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by pgomulka**
when a timezone is not provided Ingest logic should consider a time to be in a timezone provided as a parameter.
When a timezone is provided Ingest should recalculate a time to the timezone provided as a parameter

closes https://github.com/elastic/elasticsearch/issues/51108

### CODE REVIEW

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/DateFormatTests.java [hunk 1]
```diff
@@ -93,6 +93,15 @@ public void testParseISO8601() {
                 equalTo("2001-01-01T08:00Z"));
     }
 
+    public void testParseWhenZoneNotPresentInText() {
+        assertThat(DateFormat.Iso8601.getFunction(null, ZoneOffset.of("+0100"), null).apply("2001-01-01T00:00:00").toInstant().toEpochMilli(),
+            equalTo(978303600000L));
+        assertThat(DateFormat.Iso8601.getFunction(null, ZoneOffset.of("+0100"), null).apply("2001-01-01T00:00:00").toString(),
+            equalTo("2001-01-01T00:00+01:00"));
+        assertThat(DateFormat.Iso8601.getFunction(null, ZoneOffset.of("+0100"), null).apply("2001-01-01T00:00:00").toString(),
```
Comment (pugnascotia) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/DateFormatTests.java]: This line appears to be identical to the preceding line? Am I missing something?

**Review by pugnascotia — APPROVED** [review]
