### PR TITLE
ESQL: Use a must boolean statement when pushing down to Lucene when scoring is also needed

### LINKED ISSUE #123967: [ES|QL] _score is always 0 when DSL filter is being applied
### Elasticsearch Version

8.18

### Installed Plugins

_No response_

### Java Version

23.0.2

### OS Version

22.6.0 Darwin Kernel Version

### Problem Description

_score is always 0 when DSL filter is being applied. This is extremely important for kibana as prefiltering is always added.

### Steps to Reproduce

Check this:

```
POST _query/async
{
  "query": "FROM movies METADATA _score | WHERE Title: \"Shakespeare\" | sort _score DESC | KEEP Title, _score",
  "locale": "en",
  "include_ccs_metadata": true,
  "filter": {
    "bool": {
      "must": [],
      "filter": [],
      "should": [],
      "must_not": []
    }
  }
}
```

This returns:
```
#! No limit defined, adding default limit of [1000]
{
  "is_running": false,
  "took": 4,
  "is_partial": false,
  "columns": [
    {
      "name": "Title",
      "type": "text"
    },
    {
      "name": "_score",
      "type": "double"
    }
  ],
  "values": [
    [
      "Shakespeare in Love",
      0
    ],
    [
      "Shakespeare in Love",
      0
    ],
    [
      "Shakespeare in Love",
      0
    ]
  ]
}
```

If I remove the DSL:
```
POST _query/async
{
  "query": "FROM movies METADATA _score | WHERE Title: \"Shakespeare\" | sort _score DESC | KEEP Title, _score",
  "locale": "en",
  "include_ccs_metadata": true
}
```

```
#! No limit defined, adding default limit of [1000]
{
  "is_running": false,
  "took": 4,
  "is_partial": false,
  "columns": [
    {
      "name": "Title",
      "type": "text"
    },
    {
      "name": "_score",
      "type": "double"
    }
  ],
  "values": [
    [
      "Shakespeare in Love",
      7.960540771484375
    ],
    [
      "Shakespeare in Love",
      7.960540771484375
    ],
    [
      "Shakespeare in Love",
      7.960540771484375
    ]
  ]
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by astefan**
Fixes https://github.com/elastic/elasticsearch/issues/123967 by using a `must` statement (vs. a `filter` one) when scoring is needed in a query (enabled with `metadata _score`).

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/ReplaceSourceAttributes.java [hunk 1]
```diff
@@ -32,27 +32,38 @@ protected PhysicalPlan rule(EsSourceExec plan) {
...
         attributes.add(docId);
-        if (plan.indexMode() == IndexMode.TIME_SERIES) {
-            Attribute tsid = null, timestamp = null;
-            for (Attribute attr : plan.output()) {
-                String name = attr.name();
-                if (name.equals(MetadataAttribute.TSID_FIELD)) {
-                    tsid = attr;
-                } else if (name.equals(MetadataAttribute.TIMESTAMP_FIELD)) {
-                    timestamp = attr;
+
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/ReplaceSourceAttributes.java:35]: Just refactoring to eliminate double iteration over `plan.output()` attributes.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushFiltersToSource.java [hunk 2]
```diff
@@ -101,7 +101,13 @@ private static PhysicalPlan rewrite(
         if (newPushable.size() > 0) { // update the executable with pushable conditions
             Query queryDSL = TRANSLATOR_HANDLER.asQuery(Predicates.combineAnd(newPushable));
             QueryBuilder planQuery = queryDSL.asBuilder();
-            var query = Queries.combine(Queries.Clause.FILTER, asList(queryExec.query(), planQuery));
+            Queries.Clause combiningQueryClauseType;
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushFiltersToSource.java:104]: This is the actual fix for the bug. Need to add tests.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 3]
```diff
@@ -712,16 +714,43 @@ private static Set<String> subfields(Set<String> names) {
...
                 // This is an ugly hack to push the filter parameter to Lucene
                 // TODO: filter integration testing
-                filter = fragmentFilter != null ? boolQuery().filter(fragmentFilter).must(filter) : filter;
-                LOGGER.debug("Fold filter {} to EsQueryExec", filter);
-                f = f.withFilter(filter);
+                QueryBuilder newFilter;
+                if (fragmentFilter != null) {
+                    newFilter = hasScoring.get()
+                        ? boolQuery().filter(fragmentFilter).must(filter)
+                        : boolQuery().filter(fragmentFilter).filter(filter);
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:748]: This is an enhancement to existent code where we just take the filter from the request and push it down to ES. Whereas, I believe that if the query doesn't need scoring, we should wrap the filter in a `bool` `filter` statement so that scoring is completely ignored when the query is executed on ES.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushFiltersToSource.java [hunk 4]
```diff
@@ -101,7 +101,13 @@ private static PhysicalPlan rewrite(
...
+            if (queryExec.hasScoring()) {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushFiltersToSource.java:105]: `clauseType = queryExec.hasScoring() ? MUST : FILTER`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/EsQueryExec.java [hunk 5]
```diff
@@ -204,6 +205,10 @@ public static boolean isSourceAttribute(Attribute attr) {
         return DOC_ID_FIELD.getName().equals(attr.name());
     }
 
+    public boolean hasScoring() {
+        return attrs().stream().anyMatch(a -> a instanceof MetadataAttribute && a.name().equals(MetadataAttribute.SCORE));
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plan/physical/EsQueryExec.java:209]: `Expressions.anyMatch(a -> a ..)` -> not just a one liner which avoids the stream stack pollution but it also handles the expression tree navigation.
Not needed here but doesn't hurt.

**Review by costin — COMMENTED** [review]
LGTM.
Since ES optimizes must queries into filters, a simpler fix would be to just always use the MUST clause instead and let ES handle it accordingly.
I'm thinking of the latter since it eliminates code on our side AND in time, it might evaluate if scoring is needed then we do (by searching for the score attribute which might not be sufficient in the future).

**Review by costin — APPROVED** [review]
LGTM
