### PR TITLE
Making JsonProcessor stricter so that it does not silently drop data

### LINKED ISSUE #92898: [JSON Processor] Unexpected behavior with payloads starting with integers
### Elasticsearch Version

8.6.0

### Installed Plugins

_No response_

### Java Version

_bundled_ (Elastic Cloud)

### OS Version

N/A (Elastic Cloud)

### Problem Description

The Elasticsearch's JSON Processor is not producing errors when dealing with texts that starts with integers (in general, strings that match the regular expression `/\d+(\s+.*)?/`). In these cases, instead of producing errors, the JSON Processor parses as a integer number the first number encountered. Some examples:

| INPUT  | OUTPUT |
| ------------- | ------------- |
| `"0"`    | `0` |
| `"123 foo"`  | `123`  |
| `"45 this is {\"a\": \"json\"}"`  | `45` |

### Steps to Reproduce

To reproduce the bug we can create a pipeline that only contains the JSON-Processor:

```json
PUT _ingest/pipeline/test-json
{
  "processors": [
    {
      "json": {
        "field": "message",
        "target_field": "test"
      }
    }
  ]
}
```

And simulate the result with the following body (in the table other examples are shown):

```json
GET _ingest/pipeline/test-json/_simulate
{
  "docs": [
    {
      "_source": {
        "message":"0"
      }
    }
  ]
}
```
The result is the following one:

```json
{
  "docs": [
    {
      "doc": {
        "_index": "_index",
        "_id": "_id",
        "_version": "-3",
        "_source": {
          "message": "0",
          "test": 0
        },
        "_ingest": {
          "timestamp": "2023-01-13T08:31:49.758255214Z"
        }
      }
    }
  ]
```

Note that `test` (i.e., the `target_field`) contains an integer and the JSON-Processor did not produced an error. This behavior is unexpected and can lead to documents to not be indexed because `target_field` is of type long instead of Object.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by masseyke**
This PR makes JsonProcessor's JSON parsing a little bit stricter so that we are not silently dropping data when given bad inputs. Previously if the input string began with something that could be parsed as a valid json field, then the processor would grab that and ignore the rest. For example, `123 "foo"` would be parsed as `123`, dropping the `"foo"`. Now by default it will throw an IllegalArgumentException on a string like this. A user can now set the `strict_json_parsing` parameter to false to get the old behavior. For example:
```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "description": "",
    "processors" : [
      {
        "json" : {
          "field" : "message",
          "strict_json_parsing": false
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "message": "123 \"foo\""
      }
    }
  ]
}'
```
Closes #92898

### CODE REVIEW

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/JsonProcessorTests.java [hunk 1]
```diff
@@ -33,7 +36,7 @@ public void testExecute() throws Exception {
         String processorTag = randomAlphaOfLength(3);
         String randomField = randomAlphaOfLength(3);
         String randomTargetField = randomAlphaOfLength(2);
-        JsonProcessor jsonProcessor = new JsonProcessor(processorTag, null, randomField, randomTargetField, false, REPLACE, false);
+        JsonProcessor jsonProcessor = new JsonProcessor(processorTag, null, randomField, randomTargetField, false, REPLACE, false, true);
```
Comment (mattc58) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/JsonProcessorTests.java:39]: These lines in this test file make me wonder if we should add a constructor to `JsonProcessor` which has the default `strict` behavior, and then have the other constructor for allowing the caller to set it. It would at the very least reduce the changes on this file.

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/JsonProcessorTests.java [hunk 2]
```diff
@@ -227,11 +230,85 @@ public void testAddToRootNonRecursiveMerge() throws Exception {
...
+            String value = list.stream().map(val -> Double.toString(val)).collect(Collectors.joining(",", "[", "]"));
+            Object result = JsonProcessor.apply(value, true, true);
+            assertThat(result, instanceOf(List.class));
+            List<Double> resultList = (List<Double>) result;
+            assertThat(resultList.size(), equalTo(list.size()));
+            for (int i = 0; i < list.size(); i++) {
+                assertThat(resultList.get(i), closeTo(list.get(i), .001));
+            }
+        }
+        expectThrows(IllegalArgumentException.class, () -> JsonProcessor.apply("foo", true, true));
```
Comment (mattc58) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/JsonProcessorTests.java:278]: Why are these expected to fail? A comment would help.

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/JsonProcessorTests.java [hunk 3]
```diff
@@ -227,11 +230,85 @@ public void testAddToRootNonRecursiveMerge() throws Exception {
...
+
+        /*
+         * The following are examples of malformed json. Previously apply parsed just the first token and ignored the rest, but it now
+         * throw an IllegalArgumentException unless strictJsonParsing is set to false. See
+         * https://github.com/elastic/elasticsearch/issues/92898.
+         */
+        expectThrows(IllegalArgumentException.class, () -> JsonProcessor.apply("123 foo", true, true));
+        expectThrows(IllegalArgumentException.class, () -> JsonProcessor.apply("45 this is {\"a\": \"json\"}", true, true));
+
+        {
```
Comment (mattc58) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/JsonProcessorTests.java:291]: These are all good. Maybe split into a separate test just to make it clear that we're testing for something different than the code above? Basically, maybe the "strict validation" stuff could be its own test.

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by mattc58 — APPROVED** [review]
I left comments mostly around style but the core logic is +1 LGTM to me

**Review by jbaiera — APPROVED** [review]
Changes LGTM, pending green CI of course. Had one question about breaking vs bug classification.

File: docs/reference/ingest/processors/json.asciidoc [hunk 4]
```diff
@@ -16,6 +16,7 @@ Converts a JSON string into a structured JSON object.
 | `add_to_root`                   | no        | false     | Flag that forces the parsed JSON to be added at the top level of the document. `target_field` must not be set when this option is chosen.
 | `add_to_root_conflict_strategy` | no        | `replace` | When set to `replace`, root fields that conflict with fields from the parsed JSON will be overridden. When set to `merge`, conflicting fields will be merged. Only applicable if `add_to_root` is set to `true`.
 | `allow_duplicate_keys`          | no        | false     | When set to `true`, the JSON parser will not fail if the JSON contains duplicate keys. Instead, the last encountered value for any duplicate key wins.
+| `strict_json_parsing`           | no        | true      | When set to `true`, the JSON parser will strictly parse the field value. When set to `false`, the JSON parser will be more lenient but also more likely to drop parts of the field value. For example if `strict_json_parsing` is set to `true` and the field value is `123 "foo"` then the processor will throw an IllegalArgumentException. But if `strict_json_parsing` is set to `false` then the field value will be parsed as `123`.
```
[the remark this answers is not in the document]
Comment (masseyke) [reply docs/reference/ingest/processors/json.asciidoc:19]: I thought we had agreed it was a bug.

[the remark this answers is not in the document]
Comment (jbaiera) [reply docs/reference/ingest/processors/json.asciidoc:19]: Couldn't remember. If so, all good!

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/JsonProcessorTests.java (hunk 1 above)
Comment (masseyke) [reply modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/JsonProcessorTests.java:39]: Yeah I can do that -- I went back and forth over whether it would be simpler to have another constructor or another required argument to the single constructor.
