### PR TITLE
Make AzureClientProvider shutdown more graceful, unmute test

### LINKED ISSUE #143551: [CI] AzureBlobContainerRetriesTests testWriteLargeBlob failing
**Build Scans:**
- [elasticsearch-periodic #11953 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/xcqsksyelpvwy)
- [elasticsearch-pull-request #125086 / part-1-fips](https://gradle-enterprise.elastic.co/s/vlapxz52no6fa)
- [elasticsearch-pull-request #124444 / part-1](https://gradle-enterprise.elastic.co/s/qhbqybw37rmty)
- [elasticsearch-pull-request #124326 / part-1](https://gradle-enterprise.elastic.co/s/lnawboqlvtlh2)

**Reproduction Line:**
```
./gradlew ":modules:repository-azure:test" --tests "org.elasticsearch.repositories.azure.AzureBlobContainerRetriesTests.testWriteLargeBlob" -Dtests.seed=1BAC42D5659CD79D -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=kxv-IN -Dtests.timezone=Australia/Broken_Hill -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.azure.AzureBlobContainerRetriesTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testWriteLargeBlob'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <0>
     but: was <-6>
```

**Issue Reasons:**
- [main] 4 failures in test testWriteLargeBlob (0.5% fail rate in 802 executions)
- [main] 2 failures in step part-1 (0.4% fail rate in 474 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.6% fail rate in 465 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
There are a couple of different manifestations of the failure here. I'd like to see what's triggering it. I suspect there is an assertion being violated and because of the threading model in the `HttpServer` it gets lost.

I've been running this for a few days in GCP without seeing any failures. 

I made some changes
- Added better logging for the failing test incase it fails again
- Unmuted the test
- Fixed a couple of other sources of test flakiness I saw
- Make the client provider close more gracefully (we wait for the connection pool to close now before we shutdown the event loop)

Shutting down Azure client cleanly is not trivial, I think this work I've done might be enough, but if it's not we might need to revisit how we give it access to our thread-pools, or think about ignoring possibly leaked daemon threads on shutdown.

maybe...
Fixes #143551

### CODE REVIEW

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java [hunk 1]
```diff
@@ -256,8 +263,23 @@ public Scheduler newSingle(ThreadFactory threadFactory) {
...
+        try {
+            // Now safe to shut down the event loop; use bounded wait so node shutdown does not hang
+            eventLoopGroup.shutdownGracefully().await(SHUTDOWN_TIMEOUT_SECONDS, TimeUnit.SECONDS);
+        } catch (InterruptedException e) {
+            Thread.currentThread().interrupt();
+            logger.warn("Interrupted waiting for Azure Netty event loop shutdown", e);
+        } finally {
+            // Now everything is shut down, reset the factory to clear any cached schedulers
+            Schedulers.resetFactory();
+        }
```
Comment (ywangd) [inline modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java]: I am a little suspicious for the blocking waits with hardcoded timeout. Is there no way to chain them with callbacks?

**Review by ywangd — COMMENTED** [review]
I have a question

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java (hunk 1 above)
Comment (nicktindall) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java]: Yeah good point, I'll give it a go. There is nothing in `doClose`, that depends on any of this having occurred, so async should be fine.

Comment (nicktindall) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java]: I wonder if we might still see "leaked threads" detected in tests though. I'll run on GCP to see.

Comment (nicktindall) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java]: The async approach appears to be stable so far. I'll leave for another 24 hours just in case.

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java [hunk 2]
```diff
@@ -256,8 +256,20 @@ public Scheduler newSingle(ThreadFactory threadFactory) {
     @Override
     protected void doStop() {
         closed = true;
-        connectionProvider.dispose();
-        eventLoopGroup.shutdownGracefully().addListener(f -> Schedulers.resetFactory());
+        // Dispose of the connection provider first and wait for it to complete before we close the event loop.
+        connectionProvider.disposeLater()
+            .timeout(Duration.ofSeconds(10))    // Limit how long we wait for the connection provider to close
+            .doFinally(signalType -> {
```
Comment (ywangd) [inline modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java:263]: We may want to log the singalType, maybe in debug in case it is interesting for tests.

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java (hunk 1 above)
Comment (ywangd) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java]: > I wonder if we might still see "leaked threads" detected in tests though. I'll run on GCP to see.

Azure's event loop is backed by Elasticsearch's threadpool. So I think it should all be closed on node shutdown?

**Review by ywangd — APPROVED** [review]
LGTM

File: modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java (hunk 1 above)
Comment (nicktindall) [reply modules/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureClientProvider.java]: The problem is reactor-netty uses the node's scheduled executor to schedule e.g. timeouts, and sometimes those timeouts dispatch things via `Schedulers`, which will create a cached pool if it doesn't exist. 

So if the timeout is scheduled before shutdown and fires after it (and after we've called `Schedulers.resetFactory`). We end up lazily creating a daemon thread pool via `reactor.core.scheduler.Schedulers#newParallel(java.lang.String)`.

That's the "thread leak" we've seen in some of these failures.

But I've been running the code as-is all weekend and it hasn't failed so 🤞 we might be doing things orderly enough to avoid that now.
