### PR TITLE
Fix and unmute SemanticInferenceMetadataFieldsRecoveryTests

### LINKED ISSUE #124383: [CI] SemanticInferenceMetadataFieldsRecoveryTests testSnapshotRecovery {p0=false p1=true} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6878 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/wva5tt73qhwk6)
- [elasticsearch-periodic-platform-support #6878 / oraclelinux-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/6swqb6ozigevs)
- [elasticsearch-periodic #6871 / openjdk17_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/scnhofqjjoi4c)
- [elasticsearch-periodic #6871 / openjdk17_checkpart2_java-fips-matrix](https://gradle-enterprise.elastic.co/s/6wj56vglnvym4)
- [elasticsearch-periodic #6871 / openjdk21_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/aosqrhosuf2j2)
- [elasticsearch-periodic-platform-support #6878 / ubuntu-2004-aarch64_checkpart2_platform-support-arm](https://gradle-enterprise.elastic.co/s/hoirt5flni75y)
- [elasticsearch-pull-request #61498 / part-2](https://gradle-enterprise.elastic.co/s/mgic5gvj7mtii)
- [elasticsearch-pull-request #61486 / part-2-windows](https://gradle-enterprise.elastic.co/s/cdgdg3hhwtl5e)
- [elasticsearch-pull-request #61478 / part-2](https://gradle-enterprise.elastic.co/s/tsmzykkkwh7nw)
- [elasticsearch-periodic #6864 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/eybgy3oeuusps)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.mapper.SemanticInferenceMetadataFieldsRecoveryTests.testSnapshotRecovery {p0=false p1=true}" -Dtests.seed=B9603DA6C4BC43CD -Dtests.locale=kln-KE -Dtests.timezone=Etc/GMT+5 -Druntime.java=24
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.mapper.SemanticInferenceMetadataFieldsRecoveryTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSnapshotRecovery%20%7Bp0%3Dfalse%20p1%3Dtrue%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Error when comparing xContent.
             _inference_fields: 
                      semantic_1: 
                         inference: 
                              chunks: 
                            semantic_1: 
                                       0: 
                                embeddings: 
                                           0: expected Double [0.061877843] but was Double [0.061877847]
                                           1: same [0.39140058]
                                           2: same [0.862135]
                                           3: same [0.20376408]
                                           4: same [0.26110643]
                                           5: same [0.41861713]
                                           6: same [0.26080924]
                                           7: same [0.019912839]
                                           8: same [0.9802829]
                                           9: expected 
[truncated]
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in test testSnapshotRecovery {p0=false p1=true}
- [8.x] 2 consecutive failures in step rhel-9_platform-support-unix
- [8.x] 2 consecutive failures in step rocky-9_platform-support-unix
- [8.x] 18 failures in test testSnapshotRecovery {p0=false p1=true} (13.3% fail rate in 135 executions)
- [8.x] 2 failures in step rhel-9_platform-support-unix (50.0% fail rate in 4 executions)
- [8.x] 2 failures in step part-2 (14.3% fail rate in 14 executions)
- [8.x] 2 failures in step rocky-9_platform-support-unix (66.7% fail rate in 3 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic-platform-support (75.0% fail rate in 4 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic (75.0% fail rate in 4 executions)
- [8.x] 3 failures in pipeline elasticsearch-pull-request (25.0% fail rate in 12 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #124384: [CI] SemanticInferenceMetadataFieldsRecoveryTests testSnapshotRecovery {p0=true p1=false} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6878 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/wva5tt73qhwk6)
- [elasticsearch-periodic-platform-support #6878 / oraclelinux-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/6swqb6ozigevs)
- [elasticsearch-intake #19724 / part2](https://gradle-enterprise.elastic.co/s/goo5tieeiwfwq)
- [elasticsearch-periodic #6871 / openjdk17_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/scnhofqjjoi4c)
- [elasticsearch-periodic #6871 / openjdk17_checkpart2_java-fips-matrix](https://gradle-enterprise.elastic.co/s/6wj56vglnvym4)
- [elasticsearch-periodic #6871 / openjdk21_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/aosqrhosuf2j2)
- [elasticsearch-periodic-platform-support #6878 / ubuntu-2004-aarch64_checkpart2_platform-support-arm](https://gradle-enterprise.elastic.co/s/hoirt5flni75y)
- [elasticsearch-pull-request #61498 / part-2](https://gradle-enterprise.elastic.co/s/mgic5gvj7mtii)
- [elasticsearch-pull-request #61486 / part-2-windows](https://gradle-enterprise.elastic.co/s/cdgdg3hhwtl5e)
- [elasticsearch-pull-request #61478 / part-2](https://gradle-enterprise.elastic.co/s/tsmzykkkwh7nw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.mapper.SemanticInferenceMetadataFieldsRecoveryTests.testSnapshotRecovery {p0=false p1=true}" -Dtests.seed=B9603DA6C4BC43CD -Dtests.locale=kln-KE -Dtests.timezone=Etc/GMT+5 -Druntime.java=24
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.mapper.SemanticInferenceMetadataFieldsRecoveryTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSnapshotRecovery%20%7Bp0%3Dtrue%20p1%3Dfalse%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Error when comparing xContent.
             _inference_fields: 
                      semantic_1: 
                         inference: 
                              chunks: 
                            semantic_1: 
                                       0: 
                                embeddings: 
                                           0: expected Double [0.061877843] but was Double [0.061877847]
                                           1: same [0.39140058]
                                           2: same [0.862135]
                                           3: same [0.20376408]
                                           4: same [0.26110643]
                                           5: same [0.41861713]
                                           6: same [0.26080924]
                                           7: same [0.019912839]
                                           8: same [0.9802829]
                                           9: expected 
[truncated]
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in test testSnapshotRecovery {p0=true p1=false}
- [8.x] 2 consecutive failures in step rhel-9_platform-support-unix
- [8.x] 2 consecutive failures in step rocky-9_platform-support-unix
- [8.x] 19 failures in test testSnapshotRecovery {p0=true p1=false} (14.0% fail rate in 136 executions)
- [8.x] 2 failures in step rhel-9_platform-support-unix (50.0% fail rate in 4 executions)
- [8.x] 2 failures in step part-2 (14.3% fail rate in 14 executions)
- [8.x] 2 failures in step rocky-9_platform-support-unix (66.7% fail rate in 3 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic-platform-support (75.0% fail rate in 4 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic (75.0% fail rate in 4 executions)
- [8.x] 3 failures in pipeline elasticsearch-pull-request (25.0% fail rate in 12 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #124385: [CI] SemanticInferenceMetadataFieldsRecoveryTests testSnapshotRecovery {p0=false p1=false} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6878 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/wva5tt73qhwk6)
- [elasticsearch-periodic-platform-support #6878 / oraclelinux-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/6swqb6ozigevs)
- [elasticsearch-periodic #6871 / openjdk17_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/scnhofqjjoi4c)
- [elasticsearch-periodic #6871 / openjdk17_checkpart2_java-fips-matrix](https://gradle-enterprise.elastic.co/s/6wj56vglnvym4)
- [elasticsearch-periodic #6871 / openjdk21_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/aosqrhosuf2j2)
- [elasticsearch-periodic-platform-support #6878 / ubuntu-2004-aarch64_checkpart2_platform-support-arm](https://gradle-enterprise.elastic.co/s/hoirt5flni75y)
- [elasticsearch-pull-request #61498 / part-2](https://gradle-enterprise.elastic.co/s/mgic5gvj7mtii)
- [elasticsearch-pull-request #61486 / part-2-windows](https://gradle-enterprise.elastic.co/s/cdgdg3hhwtl5e)
- [elasticsearch-pull-request #61478 / part-2](https://gradle-enterprise.elastic.co/s/tsmzykkkwh7nw)
- [elasticsearch-periodic #6864 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/eybgy3oeuusps)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.mapper.SemanticInferenceMetadataFieldsRecoveryTests.testSnapshotRecovery {p0=false p1=true}" -Dtests.seed=B9603DA6C4BC43CD -Dtests.locale=kln-KE -Dtests.timezone=Etc/GMT+5 -Druntime.java=24
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.mapper.SemanticInferenceMetadataFieldsRecoveryTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSnapshotRecovery%20%7Bp0%3Dfalse%20p1%3Dfalse%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Error when comparing xContent.
             _inference_fields: 
                      semantic_1: 
                         inference: 
                              chunks: 
                            semantic_1: 
                                       0: 
                                embeddings: 
                                           0: expected Double [0.061877843] but was Double [0.061877847]
                                           1: same [0.39140058]
                                           2: same [0.862135]
                                           3: same [0.20376408]
                                           4: same [0.26110643]
                                           5: same [0.41861713]
                                           6: same [0.26080924]
                                           7: same [0.019912839]
                                           8: same [0.9802829]
                                           9: expected 
[truncated]
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in test testSnapshotRecovery {p0=false p1=false}
- [8.x] 2 consecutive failures in step rhel-9_platform-support-unix
- [8.x] 2 consecutive failures in step rocky-9_platform-support-unix
- [8.x] 18 failures in test testSnapshotRecovery {p0=false p1=false} (13.3% fail rate in 135 executions)
- [8.x] 2 failures in step rhel-9_platform-support-unix (50.0% fail rate in 4 executions)
- [8.x] 2 failures in step part-2 (14.3% fail rate in 14 executions)
- [8.x] 2 failures in step rocky-9_platform-support-unix (66.7% fail rate in 3 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic-platform-support (75.0% fail rate in 4 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic (75.0% fail rate in 4 executions)
- [8.x] 3 failures in pipeline elasticsearch-pull-request (25.0% fail rate in 12 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jimczi**
Use the TranslogOperationAsserter to compare the raw operations.

Closes #124383
Closes #124384
Closes #124385

### CODE REVIEW

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldTests.java [hunk 1]
```diff
@@ -194,7 +194,8 @@ public static ChunkedInferenceEmbedding randomChunkedInferenceEmbeddingByte(Mode
         for (String input : inputs) {
             byte[] values = new byte[embeddingLength];
             for (int j = 0; j < values.length; j++) {
-                values[j] = randomByte();
+                // to avoid vectors with zero magnitude
+                values[j] = (byte) Math.max(1, randomByte());
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldTests.java:198]: I think we want to do something similar in `randomChunkedInferenceEmbeddingFloat` to avoid a zero magnitude vector and in `randomChunkedInferenceEmbeddingSparse` to avoid creating a sparse vector that generates a score of 0 for the term.

**Review by Mikep86 — APPROVED** [review]
LGTM. Should we backport to 8.18/9.0 to fix the flaky tests there as well?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldTests.java (hunk 1 above)
Comment (jimczi) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldTests.java:198]: Done in https://github.com/elastic/elasticsearch/pull/126784/commits/18c9970b50b6fc6aba4e8e0e64b0a58001f3b5c7
