### PR TITLE
Fail if an object is added after a field with the same name.

### LINKED ISSUE #17567: Conflicted Mapping causes problems during shard initialization
This issue reproduces in ES 2.3.

```http
POST /my-index/_bulk
{"index":{"_type":"type1"}}
{"title":"I am just a string"}
{"index":{"_type":"type2"}}
{"title":{"field":"I am a string in an object"}}

POST /my-index/_close
POST /my-index/_open
```

After opening the index, you'll get something like this in the logs:

```
[2016-04-06 10:24:20,677][WARN ][cluster.action.shard     ] [Anthropomorpho] [my-index][0] received shard failed for target shard [[my-index][0], node[dC8bCuUMRHWqd0dmyqxgwg], [P], v[88], s[INITIALIZING], a[id=HdFXs5PdQI6iT4G5HFyF3w], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-04-06T14:24:20.505Z], details[failed to update mappings, failure IllegalArgumentException[Field [title] is defined as a field in mapping [type1] but this name is already used for an object in other types]]]], indexUUID [LiIeIKE-RvSNnfaBUi9NWw], message [failed to update mappings], failure [IllegalArgumentException[Field [title] is defined as a field in mapping [type1] but this name is already used for an object in other types]]
java.lang.IllegalArgumentException: Field [title] is defined as a field in mapping [type1] but this name is already used for an object in other types
	at org.elasticsearch.index.mapper.MapperService.checkObjectsCompatibility(MapperService.java:473)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:336)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:289)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.processMapping(IndicesClusterStateService.java:387)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyMappings(IndicesClusterStateService.java:348)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:164)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:610)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

Relates to #15243

### PR DESCRIPTION
**Pull request by jpountz**
Today we fail if you try to add a field and an object from another type already
has the same name. However, we do NOT fail if you insert the field first and the
object afterwards. This leads to bad bugs since mappings are not necessarily
parsed in the same order at recovery time, so a mapping update could succeed and
then you would fail to reopen the index.

Closes #17567

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 1]
```diff
@@ -378,13 +381,26 @@ private void checkFieldUniqueness(String type, Collection<ObjectMapper> objectMa
...
+                throw new IllegalArgumentException("[" + objectPath + "] is defined as an object in mapping [" + type
+                        + "] but this name is already used for a field in other types");
+            }
+        }
     }
 
     private void checkObjectsCompatibility(String type, Collection<ObjectMapper> objectMappers, Collection<FieldMapper> fieldMappers, boolean updateAllTypes) {
         assert Thread.holdsLock(this);
 
-        checkFieldUniqueness(type, objectMappers, fieldMappers);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/MapperService.java]: I removed it because we already call checkFieldUniqueness from merge(), which also callo checkObjectsCompatibility.

**Comment by rjernst** [comment]
LGTM
