### PR TITLE
Fix `fields` API with `subobjects: false`

### LINKED ISSUE #96700: `fields` API fails to retrieve subfields of objects with `subobjects: false`
### Elasticsearch Version

8.9.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

macOS

### Problem Description

When setting `subobjects: false`, the `fields` API fails to retrieve subfields.
The `_source` contains the correct subfield value, but the retrieved field gets the parent field's value.

### Steps to Reproduce

Run this test through the yaml test framework:
```yml
  - do:
      indices.create:
        index: test_index
        body:
          mappings:
            subobjects: false

  - do:
      index:
        index: test_index
        refresh: true
        body: >
          {
            "root": "parent",
            "root.subfield": "child"
          }
  - match: {result: "created"}

  - do:
      search:
        index: test_index
        body:
          query:
            term:
              root:
                value: 'parent'
          fields:
            - field: 'root'
            - field: 'root.subfield'
  - match: { hits.hits.0.fields.root.0: 'parent' }
  - match: { hits.hits.0.fields.root\.subfield.0: 'child' }
```

See full failure below.

### Logs

```
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 28,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 1,
  1>         "successful" : 1,
  1>         "skipped" : 0,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : {
  1>           "value" : 1,
  1>           "relation" : "eq"
  1>         },
  1>         "max_score" : 0.2876821,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test_index",
  1>             "_id" : "8acBm4gBiDGez0EIgdKq",
  1>             "_score" : 0.2876821,
  1>             "_source" : {
  1>               "root.subfield" : "child",
  1>               "root" : "parent"
  1>             },
  1>             "fields" : {
  1>               "root.subfield" : [
  1>                 "parent"
  1>               ],
  1>               "root" : [
  1>                 "parent"
  1>               ]
  1>             }
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
...
    Expected: "child"
         but: was "parent"
        at __randomizedtesting.SeedInfo.seed([A0FAA2C731FB678B:28AE9D1D9F070A73]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:572)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:524)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
        at org.elasticsearch.test.cluster.DefaultElasticsearchCluster$1.evaluate(DefaultElasticsearchCluster.java:36)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1623)

        Caused by:
        java.lang.AssertionError:
        Expected: "child"
             but: was "parent"
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:956)
            at org.junit.Assert.assertThat(Assert.java:923)
            at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:99)
            at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:552)
            ... 38 more
```

### PR DESCRIPTION
**Pull request by eyalkoren**
Fixes #96700 

Replacing the logic that detects mapping-related-subfields (not restricted to multi-field) to determine the right source path for field type lookups.
This logic currently relies on the field full name - it splits at the last `.` character into two parts and if the parent (first part) has a mapping, then the full field name is assumed to be a mapping-related subfield and the parent's source path is used for its type lookup.
The proposed logic relies on mappers instead, thus making it suitable for non-mapping-related cases where both parent and subfield have non-object mappings, which is the use case for which `subobjects` setting was added [in the first place](https://github.com/elastic/elasticsearch/pull/86166).

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java [hunk 1]
```diff
@@ -44,12 +45,14 @@ final class FieldTypeLookup {
...
 
         final Map<String, MappedFieldType> fullNameToFieldType = new HashMap<>();
+        final Map<String, String> fullSubfieldNameToParentPath = new HashMap<>();
         final Map<String, DynamicFieldType> dynamicFieldTypes = new HashMap<>();
         final Map<String, Set<String>> fieldToCopiedFields = new HashMap<>();
         for (FieldMapper fieldMapper : fieldMappers) {
             String fieldName = fieldMapper.name();
             MappedFieldType fieldType = fieldMapper.fieldType();
             fullNameToFieldType.put(fieldType.name(), fieldType);
+            fieldMapper.forEach(mapper -> fullSubfieldNameToParentPath.put(mapper.name(), fieldName));
```
Comment (eyalkoren) [inline server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:55]: Note for reviewer: I originally used `fieldMapper.multiFields().forEach()` here, but then path resolution failed for `search_as_you_type` fields, where the source path of subfields is expected to be the parent field's source path.
I switched to relying on `org.elasticsearch.index.mapper.FieldMapper#iterator()` instead, but I am not sure whether this is the desired functionally for all other field mappers that override it.

**Comment by eyalkoren** [comment]
`CoreTestsWithSearchRuntimeFieldsIT` fails because it is not suitable (or because Painless is not suitable 🤔 ) for work with `subobjects: false`. 

This test adds runtime fields to the search request, based on the fields that it finds in the source. For string fields, it tries to add a `<field-name>.keyword` subfield to mimic the default string multi-field mapping, where the values are evaluated through Painless. For the `root.subfield` field, the test tries to evaluate the value for the `root.subfield.keyword` field through this script: [`emit(params._source.root.subfield);`](https://github.com/elastic/elasticsearch/blob/30ae38c77e3780e446b8373b4357c0b25a8e7e5b/x-pack/qa/runtime-fields/core-with-search/src/yamlRestTest/java/org/elasticsearch/xpack/runtimefields/test/search/CoreTestsWithSearchRuntimeFieldsIT.java#L223). Since `subfield` is not really a subfield of `root` in this case, Painless fails with: `dynamic getter [java.lang.String, subfield] not found`.

Hopefully, this failure analysis makes sense.
I am leaving the decision how to resolve that to the team.

<details>
  <summary>Error details</summary>

```
        error:
          root_cause:
          - type: "script_exception"
            reason: "runtime error"
            script_stack:
            - "emit(params._source.root.subfield);"
            - "                        ^---- HERE"
            script: "emit(params._source.root.subfield);"
            lang: "painless"
            position:
              offset: 24
              start: 0
              end: 35
            stack_trace: "org.elasticsearch.script.ScriptException: runtime error\n\tat org.elasticsearch.painless@8.10.0-SNAPSHOT/org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:85)\n\
              \tat org.elasticsearch.painless.PainlessScript$Script.execute(emit(params._source.root.subfield);:1)\n\
              \tat org.elasticsearch.server@8.10.0-SNAPSHOT/org.elasticsearch.script.AbstractFieldScript.runForDoc(AbstractFieldScript.java:158)\n\
            ...
          type: "search_phase_execution_exception"
          reason: "all shards failed"
          phase: "query"
          grouped: true
          failed_shards:
          - shard: 0
            index: "test"
            node: "ouSBrYIxSTqEXrgXN4_uxA"
            reason:
              type: "script_exception"
              reason: "runtime error"
              script_stack:
              - "emit(params._source.root.subfield);"
              - "                        ^---- HERE"
              script: "emit(params._source.root.subfield);"
              lang: "painless"
              position:
                offset: 24
                start: 0
                end: 35
              caused_by:
                type: "illegal_argument_exception"
                reason: "dynamic getter [java.lang.String, subfield] not found"
                stack_trace: "java.lang.IllegalArgumentException: dynamic getter [java.lang.String,\
                  \ subfield] not found\n\tat org.elasticsearch.painless@8.10.0-SNAPSHOT/org.elasticsearch.painless.Def.lookupGetter(Def.java:454)\n\
                  \tat org.elasticsearch.painless@8.10.0-SNAPSHOT/org.elasticsearch.painless.DefBootstrap$PIC.lookup(DefBootstrap.java:171)\n\
                  ...
```

</details>

File: x-pack/qa/runtime-fields/core-with-search/src/yamlRestTest/java/org/elasticsearch/xpack/runtimefields/test/search/CoreTestsWithSearchRuntimeFieldsIT.java [hunk 2]
```diff
@@ -220,7 +220,7 @@ protected boolean handleIndex(IndexRequest index) {
                         }
                         // Strings are funny, the regular dynamic mapping puts them in "name.keyword" so we follow along.
                         Map<String, Object> keyword = new HashMap<>(runtimeFieldLoadingFromSource("keyword"));
-                        keyword.put("script", "emit(params._source." + name + ");");
+                        keyword.put("script", "emit(params._source['" + name + "']);");
```
Comment (felixbarny) [inline x-pack/qa/runtime-fields/core-with-search/src/yamlRestTest/java/org/elasticsearch/xpack/runtimefields/test/search/CoreTestsWithSearchRuntimeFieldsIT.java:223]: If it has an issue resolving nested fields now, you could add an if condition so that the script either emits `params._source." + name.replace('.', '.?')` or `params._source['" + name + "']`, depending on what's non-null.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java [hunk 3]
```diff
@@ -44,12 +45,14 @@ final class FieldTypeLookup {
     ) {
 
         final Map<String, MappedFieldType> fullNameToFieldType = new HashMap<>();
+        final Map<String, String> fullSubfieldNameToParentPath = new HashMap<>();
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:48]: Rather than adding an extra map here I think we can extend the use of `fieldToCopiedFields`.  Multifields are essentially a specialised version of copy_to fields after all.

Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:48]: And maybe rename it to something like `sourceLocations` so that it covers both copy_to and multi_field.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java (hunk 1 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:55]: Yes, `search_as_you_type` is a pain as it exposes its extra fields.  Maybe we can add a method to `FieldMapper` called `sourceUsedBy()` which by default returns the combined values of `copy_to` and multifields, and then `search_as_you_type` can override this and add in its extra fields?  And we can use this to populate the `sourceLocations` map.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java [hunk 4]
```diff
@@ -194,12 +198,8 @@ Set<String> sourcePaths(String field) {
         }
 
         String resolvedField = field;
-        int lastDotIndex = field.lastIndexOf('.');
-        if (lastDotIndex > 0) {
-            String parentField = field.substring(0, lastDotIndex);
-            if (fullNameToFieldType.containsKey(parentField)) {
-                resolvedField = parentField;
-            }
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:202]: It will be so nice to get rid of this, I think it's more or less the last place where we do this annoying dot parsing.

File: x-pack/qa/runtime-fields/core-with-search/src/yamlRestTest/java/org/elasticsearch/xpack/runtimefields/test/search/CoreTestsWithSearchRuntimeFieldsIT.java (hunk 2 above)
Comment (romseygeek) [reply x-pack/qa/runtime-fields/core-with-search/src/yamlRestTest/java/org/elasticsearch/xpack/runtimefields/test/search/CoreTestsWithSearchRuntimeFieldsIT.java:223]: I don't think replacing things with `.?` will work here, as internally the values will be a flat map with dots in the keys, not a series of nested maps.

**Review by romseygeek — CHANGES_REQUESTED** [review]
Thanks for picking this up @eyalkoren!  I left some comments.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java (hunk 1 above)
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:55]: When I found about the `search_as_you_type` problem, I thought of adding an interface method to capture all of these together, but then I found out about the superclass `FieldMapper#iterator()` implementation that does cover all I needed, but my question [above](https://github.com/elastic/elasticsearch/pull/97092#discussion_r1242259492) is whether it actually covers too much now? If so, I'll add a dedicated source-path method as you proposed.

File: x-pack/qa/runtime-fields/core-with-search/src/yamlRestTest/java/org/elasticsearch/xpack/runtimefields/test/search/CoreTestsWithSearchRuntimeFieldsIT.java (hunk 2 above)
Comment (eyalkoren) [reply x-pack/qa/runtime-fields/core-with-search/src/yamlRestTest/java/org/elasticsearch/xpack/runtimefields/test/search/CoreTestsWithSearchRuntimeFieldsIT.java:223]: It seems to work well in its current form for both dotted and nested fields, as the test still covers the entire suite and it passes.

**Review by piergm — COMMENTED** [review]
Thanks @eyalkoren, I left you a comment to possibly avoid the usage of `fullSubfieldNameToParentPath`

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java (hunk 1 above)
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:55]: There are a few non-object mappers that override `#iterator()` which I think might break this in weird ways (e.g. percolator or parent-join) so probably best to have a dedicated method which we can add tests for etc.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java [hunk 5]
```diff
@@ -194,12 +198,8 @@ Set<String> sourcePaths(String field) {
...
+        if (fullSubfieldNameToParentPath.containsKey(field)) {
+            resolvedField = fullSubfieldNameToParentPath.get(field);
         }
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:203]: Sorry if I missed what you meant, please try to let me know where I missed.
I'll get back to this next week.
Thanks for the review! 🙏

[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:203]: Thank you for your response and clarification. I understand your concerns about the proposed solution and the performance impact of sorting the keys. At the end I proposed `Stream.max()` instead of sorting that is better but not optimal. 

Considering the limitations you've mentioned, I do agree with you, relying solely on the `fullNameToFieldType.keySet()` it’s not sufficient for correctly identifying real source paths and the use of a prefix-based approach, as you pointed out, may lead to incorrect matches.

After thinking about it some more I do agree with the [solution proposed](https://github.com/elastic/elasticsearch/pull/97092#discussion_r1254296395) by @romseygeek. 
I apologise for any confusion caused by my previous suggestion.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java (hunk 3 above)
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:48]: @romseygeek I am not sure how nit this would be...
If field `A` is copied to `B`, then we want to be able to tell that `A` is a valid source path for `B`, as well as `B`. If `B` also has a multifield mapping to `B.subfield`, we want to be able to tell that the source paths to `B.subfield` are all `B` source paths. While it's trivial to tell that `B` is a source path for `B.subfield` when going through all mappers, it is not as trivial to tell that `A` is a source path as well. 

To demonstrate, assume that these mappings are iterated in the following order:
1. field `B` mapper is analyzed: 
   - we add a mapping: `B.subfield --> [B]`
2. field `A` mapper is analyzed: 
   - we add a mapping: `B --> [B, A]`
   - we also need to update the former mapping: `B.subfield --> [B, A]`
For every `copy_of`, we would now need to go over all values of the new combined map and look for the `copy_of` source field and update the set with the target field if we find such.

While this is definitely doable, it is much less straightforward than the current algorithm, which does't try to maintain copies of same sets for multifields and instead only [resolve this in lookup time](https://github.com/elastic/elasticsearch/blob/d36f889003fa39339c9f296117fe5223b4dbe1b8/server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java#L200-L205).

Therefore, I still recommend we stick with the additional mapping, but if this doesn't convince you, I will gladly change.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java (hunk 1 above)
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java]: I added a dedicated iterator for this purpose. It currently uses the existing multi-fields and search-as-you-type iterators, but I added unit tests to catch changes in the delegated iterators that may break this.

I excluded copy_to fields because they are treated differently when calculating source paths- as opposed to multi-fields, for copy_to fields we want to add the source field path _**as well as the target field path**_.

**Review by piergm — APPROVED** [review]
LGTM, Thanks @eyalkoren!

**Comment by eyalkoren** [comment]
@romseygeek I addressed your requested changes- one I applied and the other I explained why I think won't improve the current state. I want to get your approval before merging. Thanks!

File: modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/SearchAsYouTypeFieldMapper.java [hunk 6]
```diff
@@ -755,6 +755,11 @@ public Iterator<Mapper> iterator() {
         return concat;
     }
 
+    @Override
+    public Iterator<Mapper> sourcePathUsedBy() {
+        return iterator();
```
Comment (romseygeek) [inline modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/SearchAsYouTypeFieldMapper.java:760]: Do we actually need this override?  It's the same as the superclass.

**Review by romseygeek — APPROVED** [review]
I left a couple of small questions.  I think it may also be worth adding a test that specifically checks that `search_as_you_type` subfields work properly here. But no need for another review, LGTM apart from these.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java [hunk 7]
```diff
@@ -44,12 +45,14 @@ final class FieldTypeLookup {
...
 
         final Map<String, MappedFieldType> fullNameToFieldType = new HashMap<>();
+        final Map<String, String> fullSubfieldNameToParentPath = new HashMap<>();
         final Map<String, DynamicFieldType> dynamicFieldTypes = new HashMap<>();
         final Map<String, Set<String>> fieldToCopiedFields = new HashMap<>();
         for (FieldMapper fieldMapper : fieldMappers) {
             String fieldName = fieldMapper.name();
             MappedFieldType fieldType = fieldMapper.fieldType();
             fullNameToFieldType.put(fieldType.name(), fieldType);
+            fieldMapper.sourcePathUsedBy().forEachRemaining(mapper -> fullSubfieldNameToParentPath.put(mapper.name(), fieldName));
```
[the remark this answers is not in the document]
Comment (eyalkoren) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldTypeLookup.java:55]: `sourcePathUsedBy()` returns an iterator. 
I could use `fieldMapper.forEach` as it is an `Iterable` before, when I used the default `iterator()`, but I can't anymore

File: modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/SearchAsYouTypeFieldMapper.java (hunk 6 above)
Comment (eyalkoren) [reply modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/SearchAsYouTypeFieldMapper.java:760]: It's not using the superclass's, it's using its own (`SearchAsYouTypeFieldMapper.iterator()`), which overrides the superclass's.

**Comment by eyalkoren** [comment]
> I think it may also be worth adding a test that specifically checks that search_as_you_type subfields work properly here

I [extended `SearchAsYouTypeFieldMapperTests `](https://github.com/elastic/elasticsearch/pull/97092/files#diff-31b94057dd17fe5ea61d64a2102a755fdbc79f7eb0f6db325acb22c28d6e17b0R708-R724) to verify that the the implementation includes all `search_as_you_type` subfields as well as any defined multifields and made sure it is tested both [with multifields](https://github.com/elastic/elasticsearch/pull/97092/files#diff-31b94057dd17fe5ea61d64a2102a755fdbc79f7eb0f6db325acb22c28d6e17b0R276-R278) and without. 
Anything else you think I should test?

**Comment by romseygeek** [comment]
> I [extended SearchAsYouTypeFieldMapperTests ](https://github.com/elastic/elasticsearch/pull/97092/files#diff-31b94057dd17fe5ea61d64a2102a755fdbc79f7eb0f6db325acb22c28d6e17b0R708-R724) to verify that the the implementation includes all search_as_you_type subfields as well as any defined multifields and made sure it is tested both [with multifields](https://github.com/elastic/elasticsearch/pull/97092/files#diff-31b94057dd17fe5ea61d64a2102a755fdbc79f7eb0f6db325acb22c28d6e17b0R276-R278) and without.
Anything else you think I should test?

I was thinking that we could build a FieldTypeLookup and check that sourcePaths() works as expected (ie a bit of a higher-level check) but thinking about it your tests are fine.

File: modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/SearchAsYouTypeFieldMapper.java (hunk 6 above)
Comment (eyalkoren) [reply modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/SearchAsYouTypeFieldMapper.java:760]: Sorry, you meant that I could use the super's `iterator()`, which means that it is essentially the same as the super's implementation for `sourcePathUsedBy()`- not only this is true, it means that this is a bug!
I wanted to make it explicit that there is a default behavior for `sourcePathUsedBy()` and a specific override for it, but still not duplicate the code, but what I essentially did is as if I just used `FieldMapper.iterator()`, which we wanted to avoid 🤦‍♂️ 

I will fix

Comment (eyalkoren) [reply modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/SearchAsYouTypeFieldMapper.java]: Fixed with the [latest commit](https://github.com/elastic/elasticsearch/pull/97092/commits/4b99fc7f3d30f16568eef8dedfc44401d042a413).
Thanks for pointing it out! 🙏

**Review by romseygeek — APPROVED** [review]

**Comment by breskeby** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc
