### PR TITLE
Validate V2 templates more strictly

### LINKED ISSUE #43737: Template can be created with wildcard * in the name
**Elasticsearch version** (`bin/elasticsearch --version`): Affect all versions currently

**Description of the problem including expected versus actual behavior**:
It is possible to create a new template with a wildcard in the name. My expectation is that this should be prevented, because it leads to difficulty deleting the template individually.

**Steps to reproduce**:

1. Run: `DELETE _template/test-*`
2. Run `GET _template/test-*`
3. Observe there is no template named "test-*"
4. Run:
```
PUT _template/test-*
{ 
  "order" : 10, 
  "index_patterns" : ["test-*"]
}
```
5. Run:
```
PUT _template/test-inner-*
{ 
  "order" : 10, 
  "index_patterns" : ["test-inner-*"]
}
```
6. Run `GET _template/test-*`
7. Observe that there is a template named "test-*" and "test-inner-*"
8. Run `DELETE _template/test-*`
9. Run `GET _template/test-*`
10. Observe that both "test-*" and "test-inner-*" are no longer present

This behaviour is verified on 6.6.2 and 6.7.0 and 7.6.1

### LINKED ISSUE #46045: Disallow creating index templates with `:` in pattern
**Describe the feature**: Stop allowing `:` in index pattern names for index templates. They are already disallowed in index names so why allow `index_patterns` to contain them? See #23892

**Elasticsearch version** (`bin/elasticsearch --version`):
7.3.1

### PR DESCRIPTION
**Pull request by dakrone**
This commit changes the validation for V2 index and component templates to re-use the same
validation that V1 templates used. This includes things like invalid template names, index patterns,
etc.

This also adds validation that template names do not contain `*` and index patterns do not contain 
`:` (index names can't contain this regardless).

Supercedes #53970
Relates to #53101
Resolves #43737
Resolves #46045

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java [hunk 1]
```diff
@@ -922,70 +924,129 @@ private static void validateTemplate(Settings validateSettings, String mappings,
...
+                        Alias a = new Alias(aliasMeta.alias());
+                        if (aliasMeta.filter() != null) {
+                            a.filter(aliasMeta.filter().string());
+                        }
+                        a.searchRouting(aliasMeta.searchRouting());
+                        a.indexRouting(aliasMeta.indexRouting());
+                        a.isHidden(aliasMeta.isHidden());
+                        a.writeIndex(aliasMeta.writeIndex());
+                        return a;
+                    })
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:966]: Would it make sense to extract this in a separate method and use it in both validate CT/TemplateV2 methods?

**Review by andreidan — APPROVED** [review]
LGTM, thanks for fixing this Lee

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java [hunk 2]
```diff
@@ -922,70 +924,129 @@ private static void validateTemplate(Settings validateSettings, String mappings,
         }
     }
 
-    private void validate(PutRequest request) {
+    private void validate(String name, ComponentTemplate template) {
```
Comment (probakowski) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:927]: These two methods are nearly identical so they can be refactor to avoid duplication
```java
private void validate(String name, ComponentTemplate template) {
    validate(name, template.template(), Collections.emptyList());
}

private void validate(String name, IndexTemplateV2 template) {
    validate(name, template.template(), template.indexPatterns());
}

private void validate(String name, Template template1, List<String> indexPatterns) {
    Optional<Template> maybeTemplate = Optional.ofNullable(template1);
    validate(name,
        maybeTemplate.map(Template::settings).orElse(Settings.EMPTY),
        indexPatterns,
        maybeTemplate.map(Template::aliases)
            .orElse(Collections.emptyMap())
            .values().stream()
            .map(this::toAlias)
            .collect(Collectors.toList()));
}

private Alias toAlias(AliasMetadata aliasMeta) {
    Alias a = new Alias(aliasMeta.alias());
    if (aliasMeta.filter() != null) {
        a.filter(aliasMeta.filter().string());
    }
    a.searchRouting(aliasMeta.searchRouting());
    a.indexRouting(aliasMeta.indexRouting());
    a.isHidden(aliasMeta.isHidden());
    a.writeIndex(aliasMeta.writeIndex());
    return a;
}
```

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java [hunk 3]
```diff
@@ -922,70 +924,129 @@ private static void validateTemplate(Settings validateSettings, String mappings,
...
+        validate(name,
+            template.template().settings(),
+            Collections.emptyList(),
+            Optional.ofNullable(template.template().aliases())
+                .map(aliases -> aliases.values().stream()
+                    .map(aliasMeta -> {
+                        Alias a = new Alias(aliasMeta.alias());
```
Comment (probakowski) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:934]: This block should be refactored to its own method

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java [hunk 4]
```diff
@@ -922,70 +924,129 @@ private static void validateTemplate(Settings validateSettings, String mappings,
...
+
+    private void validate(String name, IndexTemplateV2 template) {
+        Optional<Template> maybeTemplate = Optional.ofNullable(template.template());
+        validate(name,
+            maybeTemplate.map(Template::settings).orElse(Settings.EMPTY),
+            template.indexPatterns(),
+            maybeTemplate
+                .map(Template::aliases)
+                .map(aliasMap -> aliasMap.values().stream()
+                    .map(aliasMeta -> {
```
Comment (probakowski) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:956]: This code can be made less nested if we get out of `Optional` early
```java
.map(Template::aliases)
.orElse(Collections.emptyMap())
```

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java [hunk 5]
```diff
@@ -922,70 +924,129 @@ private static void validateTemplate(Settings validateSettings, String mappings,
...
+            if (indexPattern.contains(":")) {
+                validationErrors.add("index_pattern [" + indexPattern + "] must not contain a ':'");
             }
             if (indexPattern.startsWith("_")) {
-                validationErrors.add("template must not start with '_'");
+                validationErrors.add("index_pattern [" + indexPattern + "] must not start with '_'");
             }
-            if (!Strings.validFileNameExcludingAstrix(indexPattern)) {
-                validationErrors.add("template must not contain the following characters " + Strings.INVALID_FILENAME_CHARS);
+            if (Strings.validFileNameExcludingAstrix(indexPattern) == false) {
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:1011]: Sorry for drive-by commenting, but this might touch another small issue I recently read (https://github.com/elastic/elasticsearch/issues/55606) which points out that we allow asterisks in index patterns, the error message contaisn the character though ("template must not contain the following characters [ , ", *, \, <, |, ,, >, /, ?];]") because we use `Strings.INVALID_FILENAME_CHARS` without removing the asterisk here. Might be worth fixing as well, just wanted to point it out.

Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:1011]: @dakrone sorry, just see you are already aware of that issue. Nevermind.

File: server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java (hunk 2 above)
Comment (dakrone) [reply server/src/main/java/org/elasticsearch/cluster/metadata/MetadataIndexTemplateService.java:927]: Good call, did this, thanks!

**Comment by dakrone** [comment]
@elasticmachine update branch
