### PR TITLE
Merge histograms without losing precision

### LINKED ISSUE #92822: Failure in HDRPercentilesIT.testScriptSingleValued
### CI Link

https://gradle-enterprise.elastic.co/s/4loz5k2jllcvg

### Repro line

`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.aggregations.metrics.HDRPercentilesIT.testScriptSingleValued" -Dtests.seed=928B8BBC20C73401 -Dtests.locale=de-CH -Dtests.timezone=America/Argentina/Catamarca -Druntime.java=19`

### Does it reproduce?

Yes

### Applicable branches

https://github.com/elastic/elasticsearch/pull/92817 (a small change over main)

### Failure history

_No response_

### Failure excerpt

I encountered this a few times in https://github.com/elastic/elasticsearch/pull/92817, which is effectively `main` plus the following patch which should not cause any failures:

```diff
diff --git a/test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java b/test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java
index 18f21cb7368..c51df18675c 100644
--- a/test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java
+++ b/test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java
@@ -152,7 +152,6 @@ import static org.hamcrest.Matchers.equalTo;
 import static org.hamcrest.Matchers.greaterThan;
 import static org.hamcrest.Matchers.greaterThanOrEqualTo;
 import static org.hamcrest.Matchers.not;
-import static org.hamcrest.Matchers.nullValue;
 import static org.junit.Assert.assertEquals;
 import static org.junit.Assert.assertFalse;
 import static org.junit.Assert.assertThat;
@@ -603,6 +602,8 @@ public final class InternalTestCluster extends TestCluster {
             );
         }

+        builder.put(INITIAL_STATE_TIMEOUT_SETTING.getKey(), "0s");
+
         return builder.build();
     }

@@ -731,14 +732,6 @@ public final class InternalTestCluster extends TestCluster {
         updatedSettings.put("node.name", name);
         updatedSettings.put(NodeEnvironment.NODE_ID_SEED_SETTING.getKey(), seed);

-        if (autoManageMasterNodes) {
-            assertThat(
-                "if master nodes are automatically managed then nodes must complete a join cycle when starting",
-                updatedSettings.get(INITIAL_STATE_TIMEOUT_SETTING.getKey()),
-                nullValue()
-            );
-        }
-
         return updatedSettings.build();
     }
```

The failure is as follows:

```
org.elasticsearch.search.aggregations.metrics.HDRPercentilesIT > testScriptSingleValued FAILED	
    java.lang.AssertionError: 	
    Expected: a value less than or equal to <10.00100068359375>	
         but: <10.0068359375> was greater than <10.00100068359375>	
        at __randomizedtesting.SeedInfo.seed([928B8BBC20C73401:2E3A0A78C1851C92]:0)	
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
        at org.junit.Assert.assertThat(Assert.java:956)	
        at org.junit.Assert.assertThat(Assert.java:923)	
        at org.elasticsearch.search.aggregations.metrics.HDRPercentilesIT.assertConsistent(HDRPercentilesIT.java:87)	
        at org.elasticsearch.search.aggregations.metrics.HDRPercentilesIT.testScriptSingleValued(HDRPercentilesIT.java:376)	
```

### PR DESCRIPTION
**Pull request by salvatore-campagna**
For empty histogram aggregations we instantiate by default a DoubleHistogram 
with 3 significant digits precision. The test generates a random value for 
the number of significant digits that is in the range [0, 5]. As a result, if the 
test runs with 4 or 5 significant value digits but the HdrHistogram sketch only 
uses 3, checking errors on results fails since all computations are done with
lower than expected precision.

The issue happens at reduction time in `AbstractInternalHDRPercentiles` when
merging histograms coming from different shards. If a shard returns no data the
sketch is empty but uses 3 significant digits, while for non empty results the
correct number of digits is used. Now, depending on the order sketches are
merged it might happen, for instance, that we merge a sketch using 4 or 5
significant digits into one using 3 significant digits (used for the empty result).
The result, will then use whatever precision is used by the first "merged" object
created. This in some cases leads to correct result and sometimes not.

Here, when merging histograms, we always use the one with higher value of
`numberOfSignificantValueDigits` so to avoid reducing precision of the result.

Note that, as a result of this merging strategy, we can even use just 0 digits
precision for empty results and save on some serialization/deserialization
for empty histograms.

Resolves #92822

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/metrics/HDRPercentilesAggregator.java [hunk 1]
```diff
@@ -55,6 +55,6 @@ public double metric(String name, long bucketOrd) {
 
     @Override
     public InternalAggregation buildEmptyAggregation() {
-        return new InternalHDRPercentiles(name, keys, null, keyed, format, metadata());
+        return new InternalHDRPercentiles(name, keys, new DoubleHistogram(numberOfSignificantValueDigits), keyed, format, metadata());
```
Comment (salvatore-campagna) [inline server/src/main/java/org/elasticsearch/search/aggregations/metrics/HDRPercentilesAggregator.java:58]: Note that in `TDigestPercentilesAggregator#buildEmptyAggregation` we do something similar

```
return new InternalTDigestPercentiles(name, keys, new TDigestState(compression), keyed, formatter, metadata());
```

Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/search/aggregations/metrics/HDRPercentilesAggregator.java:58]: Creating `DoubleHistogram` with a high `numberOfSignificantValueDigits`  consumes a lot of memory. Can we avoid doing this here? Also serialising it would be non trivial.

Can we maybe create the right `DoubleHistogram ` instance in `AbstractInternalHDRPercentiles#reduce(...)` method? Right now it always uses a `EMPTY_HISTOGRAM` in case of an empty bucket. Maybe we create another instances if `numberOfSignificantValueDigits` != 3?

**Review by martijnvg — COMMENTED** [review]
I think last change to this code made the test fail. 
I left a comment.

**Comment by salvatorecampagna** [comment]
I wonder if we should do the same for tdigest too.

**Comment by salvatore-campagna** [comment]
In another PR I will address the issue of using a "zero" histogram object also for TDigest, similar to what we do with HDR.

**Review by martijnvg — APPROVED** [review]
LGTM
