### PR TITLE
[CCR] Adjust list retryable errors

### LINKED ISSUE #33954: [CCR] Tweak the retry-able error list
When a shard follow tasks encounters an error, it determines whether it is a retry-able error or a non retry-able error. A retry-able error is retried in back off like manner. A non retry-able error is not retried and fails the shard follow task.

The follow list of errors is retried at the moment:
* java.net.ConnectException
* java.nio.ClosedChannelException
* "Connecion reset" (any error with this message)
* "connection was aborted" (any exception with this message)
* "forcibly closed" (any exception with this message)
* "Broken pipe" (any exception with this message)
* "Connection timed out" (any exception with this message)
* "Socket is closed" (any exception with this message)
* "Socket closed" (any exception with this message)
* ShardNotFoundException
* IndexNotFoundException
* IllegalIndexShardStateException
* NoShardAvailableActionException
* UnavailableShardsException
* AlreadyClosedException

I think we should make the following changes to this list of retry-able errors:
* Add ElasticsearchSecurityException. For in the case the current user has insufficient privileges while an index is being followed. Prior to following ccr checks whether the current user has sufficient privileges and if not the follow api fails with an error. 
* Add Index block exception. If the leader index gets closed, this exception is returned. 
* Add ClusterBlockException service unavailable. In case for example the leader cluster is without elected master.
* Remove IndexNotFoundException. If the leader / follower index has been deleted, ccr will need to stop the shard follow tasks with an error.

### PR DESCRIPTION
**Pull request by martijnvg**
The following changes were made:
* Added ElasticsearchSecurityException. For in the case the current user has insufficient privileges while an index is being followed. Prior to following ccr checks whether the current user has sufficient privileges and if not the follow api fails with an error.
* Added Index block exception. If the leader index gets closed, this exception is returned.
* Added ClusterBlockException service unavailable. In case for example the leader cluster is without elected master.
* Removed IndexNotFoundException. If the leader / follower index has been deleted, ccr will need to stop the shard follow tasks with an error.

Closes #33954
Depends on #33983

### CODE REVIEW

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java [hunk 1]
```diff
@@ -529,6 +538,114 @@ public void testAttemptToChangeCcrFollowingIndexSetting() throws Exception {
...
+            assertThat(response.getStatsResponses().get(0).status().numberOfFailedFetches(), greaterThanOrEqualTo(1L));
+            assertThat(response.getStatsResponses().get(0).status().fetchExceptions().size(), equalTo(1));
+            ElasticsearchException exception = response.getStatsResponses().get(0).status()
+                .fetchExceptions().entrySet().iterator().next().getValue().v2();
+            assertThat(exception.getMessage(), equalTo("blocked by: [FORBIDDEN/4/index closed];"));
+        });
+
+        client().admin().indices().open(new OpenIndexRequest("index1")).actionGet();
+        client().prepareIndex("index1", "doc", "2").setSource("{}", XContentType.JSON).get();
+        assertBusy(() -> assertThat(client().prepareSearch("index2").get().getHits().totalHits, equalTo(2L)));
```
Comment (dnhatn) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java]: Maybe just use `atLeastDocsIndexed`.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java [hunk 2]
```diff
@@ -529,6 +538,114 @@ public void testAttemptToChangeCcrFollowingIndexSetting() throws Exception {
...
+                .put(IndexMetaData.SETTING_NUMBER_OF_REPLICAS, 0)
+                .build()));
+        ensureGreen("index1");
+
+        final FollowIndexAction.Request followRequest = createFollowRequest("index1", "index2");
+        final CreateAndFollowIndexAction.Request createAndFollowRequest = new CreateAndFollowIndexAction.Request(followRequest);
+        client().execute(CreateAndFollowIndexAction.INSTANCE, createAndFollowRequest).get();
+
+        client().prepareIndex("index1", "doc", "1").setSource("{}", XContentType.JSON).get();
+        assertBusy(() -> assertThat(client().prepareSearch("index2").get().getHits().totalHits, equalTo(1L)));
```
Comment (dnhatn) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java]: Maybe just use `atLeastDocsIndexed`.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java [hunk 3]
```diff
@@ -529,6 +538,114 @@ public void testAttemptToChangeCcrFollowingIndexSetting() throws Exception {
...
+        client().prepareIndex("index1", "doc", "2").setSource("{}", XContentType.JSON).get();
+        assertBusy(() -> {
+            StatsResponses response = client().execute(CcrStatsAction.INSTANCE, new StatsRequest()).actionGet();
+            assertThat(response.getNodeFailures(), empty());
+            assertThat(response.getTaskFailures(), empty());
+            assertThat(response.getStatsResponses(), hasSize(1));
+            assertThat(response.getStatsResponses().get(0).status().numberOfFailedBulkOperations(), greaterThanOrEqualTo(1L));
+        });
+        client().admin().indices().open(new OpenIndexRequest("index2")).actionGet();
+        assertBusy(() -> assertThat(client().prepareSearch("index2").get().getHits().totalHits, equalTo(2L)));
```
Comment (dnhatn) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java]: Same here.

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java [hunk 4]
```diff
@@ -47,7 +54,7 @@
 public abstract class ShardFollowNodeTask extends AllocatedPersistentTask {
 
     private static final int DELAY_MILLIS = 50;
-    private static final Logger LOGGER = Loggers.getLogger(ShardFollowNodeTask.class);
+    private static final Logger LOGGER = LogManager.getLogger(ShardFollowNodeTask.class);
```
Comment (dnhatn) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java]: I am not sure why you changed this.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java [hunk 5]
```diff
@@ -529,6 +538,114 @@ public void testAttemptToChangeCcrFollowingIndexSetting() throws Exception {
...
+    }
+
+    public void testCloseFollowIndex() throws Exception {
+        assertAcked(client().admin().indices().prepareCreate("index1")
+            .setSettings(Settings.builder()
+                .put(IndexSettings.INDEX_SOFT_DELETES_SETTING.getKey(), true)
+                .put(IndexMetaData.SETTING_NUMBER_OF_SHARDS, 1)
+                .put(IndexMetaData.SETTING_NUMBER_OF_REPLICAS, 0)
+                .build()));
+        ensureGreen("index1");
```
Comment (dnhatn) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java]: By default, we will wait until the primary shard gets allocated. Thus, we do not have to call` ensureGreen` if the number of replicas is 0.

**Review by dnhatn — APPROVED** [review]
Thanks @martijnvg for adding many great tests. I left some minor comments. LGTM.

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java (hunk 4 above)
Comment (martijnvg) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java]: It is an unrelated change. `Loggers#getLogger(...)` is deprecated and I just thought that I would change it.

Comment (dnhatn) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowNodeTask.java]: ok, thanks.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java (hunk 1 above)
Comment (dnhatn) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java]: Sorry @martijnvg, I was wrong. We should strictly assert here instead of using at least. I think we should use the previous form.

Comment (martijnvg) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java]: yes, now I think about it that makes sense. I changed that here: 327ef7282bf78413be77945a5b53f620a11e8bdc

Comment (dnhatn) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/ShardChangesIT.java]: Thanks @martijnvg.

**Review by jasontedor — APPROVED** [review]
LGTM.
