### PR TITLE
[ML][Data Frame] deregister scheduler on transform failure

### LINKED ISSUE #40543: [ML] DataFrameTaskFailedStateIT.testFailureStateInteraction failure
The error is 

   > Expected: "Unable to start data frame transform [failure_pivot_1] as it is in a failed state with failure: [task encountered irrecoverable failure: no such index [reviews]]. Use force start to restart data frame transform once error is resolved."
   >      but: was "Unable to start data frame transform [failure_pivot_1] as it is in state [STARTED]"
   >    at __randomizedtesting.SeedInfo.seed([372767333722BFA5:B84F6CD2013B998A]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.dataframe.integration.DataFrameTaskFailedStateIT.testFailureStateInteraction(DataFrameTaskFailedStateIT.java:48)

Which is very strange as there is an assertion that the task state is failed a few lines before.

`
 ./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner -Dtests.seed=372767333722BFA5 -Dtests.class=org.elasticsearch.xpack.dataframe.integration.DataFrameTaskFailedStateIT -Dtests.method="testFailureStateInteraction" -Dtests.security.manager=true -Dtests.locale=smn -Dtests.timezone=America/Puerto_Rico -Dcompiler.java=12 -Druntime.java=12
`

Spotted on my local machine but no doubt it will make an appearance in CI soon.

### PR DESCRIPTION
**Pull request by benwtrent**
If a transform task fails, we should not continually attempt to run it. Currently, since it stays scheduled, it will attempt to run again at every configured interval. A better alternative, is to remove itself from the scheduling engine when it fails. We still get to keep the persistent task in the cluster, but we don't have to worry about the indexer getting scheduled to run again.

Additionally, I fixed the failed state interaction tests since now we have a good way to force task failures (bulk indexing failures). 

Closes #40543

### CODE REVIEW

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java [hunk 1]
```diff
@@ -253,6 +253,7 @@ public synchronized void stop() {
         }
 
         IndexerState state = getIndexer().stop();
+        stateReason.set(null);
```
Comment (benwtrent) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: This was actually a bug. The state reason could still stick around even after the indexer stops. We should make sure that we clear out the reason on `stop` as well as `start`

File: x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFrameTaskFailedStateIT.java [hunk 2]
```diff
@@ -6,87 +6,123 @@
...
         refreshIndex(dataFrameIndex);
 
         // Verify that we have started and that our reason is cleared
-        fullState = getDataFrameState(transformId);
+        fullState = getDataFrameState(TRANSFORM_ID);
         assertThat(XContentMapValues.extractValue("state.reason", fullState), is(nullValue()));
         assertThat(XContentMapValues.extractValue("state.task_state", fullState), equalTo("started"));
         assertThat(XContentMapValues.extractValue("state.indexer_state", fullState), equalTo("started"));
-        assertThat(XContentMapValues.extractValue("stats.search_failures", fullState), equalTo(1));
+        assertThat((int)XContentMapValues.extractValue("stats.index_failures", fullState), greaterThan(0));
```
Comment (benwtrent) [inline x-pack/plugin/data-frame/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/dataframe/integration/DataFrameTaskFailedStateIT.java]: I purposefully made this flexible (we want to see at least ONE indexing failure) as we MAY change how we many indexing failures are allowed for specific indexing issues (e.g. mapping vs cluster issues)

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java (hunk 1 above)
Comment (davidkyle) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: What if the transform fails then is force stopped, should we not preserve the failure reason in that case?

Comment (droberts195) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java]: I don't think we should.  The whole point of keeping the persistent task around when the transform is in the `failed` state is to remember stuff about the failure, like which node it was on and the reason.  By force-stopping a failed transform the user is effectively saying "I've investigated this failure as much as I'll ever want to, now I'm ready to move on".

**Review by davidkyle — APPROVED** [review]
LGTM. Nice job on the failed state test
