### PR TITLE
[Rollup] Validate timezones based on rules not string comparision

### LINKED ISSUE #36229: Rollup searches based on "obsolete" timezones fail
This originated from https://discuss.elastic.co/t/visualizing-rollup-index-with-timezone-result-in-error/159064/2. CC @polyfractal 

To reproduce, follow these steps to create data, a rollup job, and a search on the rolled-up data:

```
PUT test_index

PUT test_index/_doc/1
{
  "utc_time" : "2018-12-02T16:02:19.851Z"
}

PUT _xpack/rollup/job/test_job
{
    "index_pattern": "test_index",
    "rollup_index": "test_index_rollup",
    "cron": "0 * * * * ?",
    "groups": {
      "date_histogram": {
        "interval": "24h",
        "field": "utc_time",
        "time_zone": "Canada/Mountain"
      }
    },
    "metrics": [],
    "page_size": 1000
}

POST _xpack/rollup/job/test_job/_start

GET test_index_rollup/_rollup_search
{  
   "size":0,
   "aggregations":{  
      "2":{  
         "date_histogram":{  
            "field":"order_date",
            "interval":"24h",
            "time_zone":"Canada/Mountain",
            "min_doc_count":1
         }
      }
   }
}
```

The search will fail with this error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "There is not a rollup job that has a [date_histogram] agg on field [order_date] which also satisfies all requirements of query."
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "There is not a rollup job that has a [date_histogram] agg on field [order_date] which also satisfies all requirements of query."
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by polyfractal**
The date_histogram internally converts obsolete timezones (such as `"Canada/Mountain"`) into their modern equivalent (`"America/Edmonton"`). But rollup just stores the TZ as provided by the user in the config.

When checking the TZ for query validation we used a simple string comparison, which would fail due to the date_histo's upgrading behavior (`"Canada/Mountain" != "America/Edmonton"`)

Instead, we should convert both to a `TimeZone` object and check if their rules are compatible.  ~This commit also proactively upgrades the config's TZ to the modern equivalent for good measure, although this isn't strictly necessary and old rollup indices will be fixed just by the query validation tweak.~

This has two side-effects:

- We should not be adding a term filter on `time_zone` to the query. This was obsolete anyway due to filtering on job ID + individual msearch
- Without the need for term filter on `time_zone`, there's no need for the request translator to add filtering clauses at all.  This functionality was removed (although the filtered agg structure remains, can be cleaned up in a followup PR)

It also exposed a bug:

- After verifying the timezones are the same, we need to set the timezone on the rewritten date_histo otherwise it will treat the data as UTC and shift results.

~I think this is going to miss the boat for `6.5.3`, but I'd like to backport it to `6.5.4` when the time comes.  There isn't a workaround if the user indexed rollups with an "obsolete" TZ, and not setting the timezone on the query itself will mess up results.~

Closes #36229

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by polyfractal** [comment]
Jenkins, run the gradle build tests 2

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupJobIdentifierUtils.java [hunk 1]
```diff
@@ -97,11 +98,13 @@ private static void checkDateHisto(DateHistogramAggregationBuilder source, List<
                     if (agg.get(RollupField.AGG).equals(DateHistogramAggregationBuilder.NAME)) {
                         DateHistogramInterval interval = new DateHistogramInterval((String)agg.get(RollupField.INTERVAL));
 
-                        String thisTimezone  = (String)agg.get(DateHistogramGroupConfig.TIME_ZONE);
-                        String sourceTimeZone = source.timeZone() == null ? DateTimeZone.UTC.toString() : source.timeZone().toString();
+                        TimeZone thisTimezone = DateTimeZone.forID((String)agg.get(DateHistogramGroupConfig.TIME_ZONE)).toTimeZone();
```
[the remark this answers is not in the document]
Comment (polyfractal) [reply x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupJobIdentifierUtils.java]: Ah ok, will do.  Thanks for the heads up

**Comment by polyfractal** [comment]
Just a note for posterity: `ZoneId` doesn't "convert" the string representation of obsolete TZ into the new version (like `TimeZone` did).  So Rollup will continue to store whatever the user gives us (provided it is a valid `ZoneId`) and we'll do the rule comparison as before like we did with `TimeZone`.

**Comment by rjernst** [comment]
Should we log a deprecation warning to make the user change to the non-obsolete name of the timezone?

**Comment by polyfractal** [comment]
Do you know if there's a way to get that information from `ZoneId` or other new date/time classes?  I looked around and couldn't find something that would tell me that a particular TZ is deprecated or not, short of using the older `TimeZone` class.  `ZoneId` does have a map of "short name" aliases (`"EST"`, etc) but not the longer deprecated forms like `Japan`.

I don't know the new date stuff well (or even the old stuff well), so I may have overlooked it.

I suppose we could add a static list somewhere ourselves, but that seems less good :)

**Comment by rjernst** [comment]
> I suppose we could add a static list somewhere ourselves

That's what I was thinking. This is just to help with migrating. I don't think it is anything we should maintain for a long time, so it doesn't need to be programmatic just in case more timezone names are deprecated.

**Comment by rjernst** [comment]
Note that I did something similar already in `DateUtils.DEPRECATED_SHORT_TZ_IDS`

**Comment by polyfractal** [comment]
Added a deprecation warning when creating a Rollup job that uses a deprecated/obsolete timezone.  Notably this is only when creating the job, not anything else that touches the job, or search.  I think that's a much bigger task and better suited to a separate PR.

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupJobIdentifierUtils.java [hunk 2]
```diff
@@ -97,11 +98,13 @@ private static void checkDateHisto(DateHistogramAggregationBuilder source, List<
                     if (agg.get(RollupField.AGG).equals(DateHistogramAggregationBuilder.NAME)) {
                         DateHistogramInterval interval = new DateHistogramInterval((String)agg.get(RollupField.INTERVAL));
 
-                        String thisTimezone  = (String)agg.get(DateHistogramGroupConfig.TIME_ZONE);
-                        String sourceTimeZone = source.timeZone() == null ? DateTimeZone.UTC.toString() : source.timeZone().toString();
+                        ZoneId thisTimezone = ZoneId.of(((String)agg.get(DateHistogramGroupConfig.TIME_ZONE)), ZoneId.SHORT_IDS);
+                        ZoneId sourceTimeZone = source.timeZone() == null
+                            ? ZoneId.of(DateHistogramGroupConfig.DEFAULT_TIMEZONE)
```
Comment (rjernst) [inline x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupJobIdentifierUtils.java]: Using `ZoneId.of("UTC")` (as this effectively does) causes printing using formats with this ZoneId to be messed up. They will get a `[UTC]` appended to the end of the time, like `1970-01-02T10:17:36.789Z[UTC]`. Instead, use `ZoneOffset.UTC`.

Comment (polyfractal) [reply x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupJobIdentifierUtils.java]: Urgh, yeah not what was intended.  Fixing, thanks!

**Comment by polyfractal** [comment]
Righto, so swapping over to `ZoneId` in the verification place added a few wrinkles, and it was easier to just entirely switch the config object over to storing a `ZoneId` as well.  Since everything is still serialized/stored as a string, BWC is reasonably easy.

The major change is that `ZoneId` treats UTC as `"Z"`, so the string being stored will change.  There are some extra tests to make sure that older `"UTC"` jobs continue to work as expected.

There's a reasonable amount of converting the `ZoneId`s back to `DateTimeZone`s so that we can use them in the date_histo... this will be cleaned up in the future when the new date/time stuff lands.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/rollup/job/DateHistogramGroupConfig.java [hunk 3]
```diff
@@ -117,15 +120,23 @@ public DateHistogramGroupConfig(final String field,
...
     }
 
     @Override
     public void writeTo(final StreamOutput out) throws IOException {
         interval.writeTo(out);
         out.writeString(field);
         out.writeOptionalWriteable(delay);
-        out.writeString(timeZone);
+        // TODO change version after backport
+        if (out.getVersion().onOrAfter(Version.V_7_0_0)) {
```
Comment (rjernst) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/rollup/job/DateHistogramGroupConfig.java]: This should be the version you intend to backport to. Then disable bwc tests in this PR (in the root build.gradle). When doing the backport, remove the single line change that disabled bwc tests. Finally, followup with re-enabling bwc tests on master. This way the followup change has no possibility for accidentally not matching the backcompat logic since it is written correctly from the beginning.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/extractor/aggregation/RollupDataExtractorFactory.java [hunk 4]
```diff
@@ -120,7 +122,7 @@ private static boolean validInterval(long datafeedInterval, ParsedRollupCaps rol
         if (rollupJobGroupConfig.hasDatehistogram() == false) {
             return false;
         }
-        if ("UTC".equalsIgnoreCase(rollupJobGroupConfig.getTimezone()) == false) {
+        if (ZoneId.of(rollupJobGroupConfig.getTimezone()).getRules().equals(ZoneOffset.UTC.getRules()) == false) {
```
Comment (rjernst) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/extractor/aggregation/RollupDataExtractorFactory.java]: Maybe we should have a DateUtils method for this equality check?

**Review by rjernst — COMMENTED** [review]
I left a few more comments. I'm confused why all the change from UTC to Z. `ZoneId.of("UTC")` should work fine. Perhaps you needed to normalize a ZoneId somewhere?

**Comment by polyfractal** [comment]
Will get back to this early next week, thanks @rjernst.

>  I'm confused why all the change from UTC to Z. ZoneId.of("UTC") should work fine. Perhaps you needed to normalize a ZoneId somewhere?

The issue is that ZoneId's toString() of `UTC` is `"Z"`.  E.g `ZoneId.of("UTC").toString() == "Z"`.  So when the timezone is serialized as a string, it turns into `"Z"`, and when we save it to rollup documents the same thing happens.

I'll poke around again and see if there's a way around it, or if I did something wrong

**Comment by polyfractal** [comment]
Ok, so I was becoming increasingly uncomfortable with how the timezone stuff was spreading everywhere.  I think these changes are probably still needed at some point, but would rather contain that to a refactor PR.

So I backed out the last ZoneId commit, then introduced a new default constant for ZoneIds that is used for comparisons, while the old String default is used for strings.  This keeps the "UTC"/"Z" thing from spreading everywhere.

**Comment by polyfractal** [comment]
Final update, yanked the last remaining pieces of Joda and tweaked the tests according to new master (using Javatime in date_histo gives slightly different results, depending on the timezone you specify).

**Comment by polyfractal** [comment]
@spinscale @pgomulka Might I bother one of you for a review of the javatime stuff, since Ryan is away this week?  The rollup bits should be good, but would appreciate someone to verify the time shenanagins and make sure I didn't do anything silly.

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportPutRollupJobAction.java [hunk 5]
```diff
@@ -115,6 +121,15 @@ public void onFailure(Exception e) {
         });
     }
 
+    static void checkForDeprecatedTZ(PutRollupJobAction.Request request) {
+        String timeZone = request.getConfig().getGroupConfig().getDateHistogram().getTimeZone();
+        String modernTZ = DateUtils.DEPRECATED_LONG_TIMEZONES.get(timeZone);
```
Comment (pgomulka) [inline x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportPutRollupJobAction.java]: DateUtils.of can also do that for you, but you would get a different log message.. Do you think it is worth using instead?

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportRollupSearchAction.java [hunk 6]
```diff
@@ -288,17 +290,16 @@ static QueryBuilder rewriteQuery(QueryBuilder builder, Set<RollupJobCaps> jobCap
             String fieldName = range.fieldName();
             // Many range queries don't include the timezone because the default is UTC, but the query
             // builder will return null so we need to set it here
-            String timeZone = range.timeZone() == null ? DateTimeZone.UTC.toString() : range.timeZone();
+            String timeZone = range.timeZone() == null ? DateHistogramGroupConfig.DEFAULT_ZONEID_TIMEZONE.toString() : range.timeZone();
```
Comment (pgomulka) [inline x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportRollupSearchAction.java]: maybe it would better to keep the ZoneId type as long as it is not needed to be converted?
So here and then passing to rewriteFieldName where it would be converted to string?

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportPutRollupJobAction.java (hunk 5 above)
Comment (pgomulka) [reply x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportPutRollupJobAction.java]: also possibly similar logging/validation should be in RangeQueryBuilder, but there is a separate PR for this https://github.com/elastic/elasticsearch/issues/38449

**Review by pgomulka — COMMENTED** [review]
that looks good in my view, but I don't know rollups all that much so probably I am not the right person to approve

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportPutRollupJobAction.java (hunk 5 above)
Comment (polyfractal) [reply x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportPutRollupJobAction.java]: Will take a look at DateUtils.of, thanks!  I'm not too picky about the error message contents, as long as it describes what's going on.  Would rather reuse code where possible :)

**Comment by polyfractal** [comment]
Thanks @pgomulka!  Will work on the date/time stuff.  Jim previously OK'd the rollup portion, we've just been stuck on the new javatime changes since then :)

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportPutRollupJobAction.java (hunk 5 above)
Comment (polyfractal) [reply x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportPutRollupJobAction.java]: Had a look, `DateUtils.of()` only checks the existing "short" names, while this check is for the "long" names that the IANA have deprecated.  We can modify `DateUtils.of()` to do this check too... but I'll do that in a followup so that this PR doesn't balloon with extra non-rollup deprecations.

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupRequestTranslator.java [hunk 7]
```diff
@@ -220,13 +205,9 @@
                 rolledDateHisto.interval(source.interval());
             }
 
-            String timezone = source.timeZone() == null ? DateTimeZone.UTC.toString() : source.timeZone().toString();
-            filterConditions.add(new TermQueryBuilder(RollupField.formatFieldName(source,
-                DateHistogramGroupConfig.TIME_ZONE), timezone));
+            ZoneId timeZone = source.timeZone() == null ? DateHistogramGroupConfig.DEFAULT_ZONEID_TIMEZONE : source.timeZone();
+            rolledDateHisto.timeZone(timeZone);
```
Comment (polyfractal) [inline x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupRequestTranslator.java]: Note: this has the change of always setting a timezone.  The only practical change is that UTC will be explicitly set now instead of implicit.  Every other timezone will be the same.

I figured this would make debugging a bit easier since there will always be a timezone.

**Comment by polyfractal** [comment]
@jimczi Since it's been a while, would you mind giving this one last sanity check?  I don't think anything substantial has changed since you first looked at it, but there were some minor tweaks along the way as we sorted out the java-time stuff.

The tl;dr: is that obsolete timezones throw a deprecation warning but are accepted, timezones are compared based on rules everywhere, and the code knows how to use obsolete or modern timezones for aggregating.  And there are tests going both ways so we know if this ever breaks.

**Review by jimczi — APPROVED** [review]
LGTM, thanks for adding the tests
