### PR TITLE
Fix `KibanaThreadPoolIT`

### LINKED ISSUE #113939: [CI] KibanaThreadPoolIT testBlockedThreadPoolsRejectUserRequests failing
**Build Scans:**
- [elasticsearch-intake #11132 / part1](https://gradle-enterprise.elastic.co/s/7azawc732yfzg)
- [elasticsearch-periodic #4379 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/wadfccndp7xb6)
- [elasticsearch-intake #11077 / part1](https://gradle-enterprise.elastic.co/s/nd5cyy6igu2cw)
- [elasticsearch-intake #11039 / part1](https://gradle-enterprise.elastic.co/s/g7x32powpq7kw)
- [elasticsearch-pull-request #35835 / part-1](https://gradle-enterprise.elastic.co/s/g5ceixh3i6hdm)
- [elasticsearch-periodic #4371 / openjdk22_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/i2zqbcrb2nzie)
- [elasticsearch-periodic-platform-support #4341 / ubuntu-1804_platform-support-unix](https://gradle-enterprise.elastic.co/s/pivr2j3gpifsi)
- [elasticsearch-intake #10971 / part1](https://gradle-enterprise.elastic.co/s/whaprw6g3q2bg)
- [elasticsearch-pull-request #35666 / part-1](https://gradle-enterprise.elastic.co/s/2y65w7ae6gw62)
- [elasticsearch-pull-request #35543 / part-1](https://gradle-enterprise.elastic.co/s/bjocays6dwuf2)

**Reproduction Line:**
```
./gradlew ":modules:kibana:internalClusterTest" --tests "org.elasticsearch.kibana.KibanaThreadPoolIT.testBlockedThreadPoolsRejectUserRequests" -Dtests.seed=7BFB6DB150801CFE -Dtests.locale=da-GL -Dtests.timezone=America/Monterrey -Druntime.java=22
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testBlockedThreadPoolsRejectUserRequests'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.kibana.KibanaThreadPoolIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Expected exception EsRejectedExecutionException but no exception was thrown
```

**Issue Reasons:**
- [8.x] 18 failures in test testBlockedThreadPoolsRejectUserRequests (3.1% fail rate in 576 executions)
- [8.x] 5 failures in step part1 (6.7% fail rate in 75 executions)
- [8.x] 6 failures in step part-1 (4.8% fail rate in 124 executions)
- [8.x] 2 failures in step openjdk21_checkpart1_java-matrix (14.3% fail rate in 14 executions)
- [8.x] 5 failures in pipeline elasticsearch-intake (6.7% fail rate in 75 executions)
- [8.x] 6 failures in pipeline elasticsearch-pull-request (5.3% fail rate in 114 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic (21.4% fail rate in 14 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic-platform-support (21.4% fail rate in 14 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DaveCTurner**
This test will fail to see the rejection if the GET retries on a
different shard copy, so with this commit we make sure there are no
spare shard copies on which to retry.

Closes #113939

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Prior to this change, the test would fail on my CI machine in a few hundred iterations. I ran this change for 2000 iterations without any failures.

File: modules/kibana/src/internalClusterTest/java/org/elasticsearch/kibana/KibanaThreadPoolIT.java [hunk 1]
```diff
@@ -68,6 +65,7 @@ protected Settings nodeSettings(int nodeOrdinal, Settings otherSettings) {
             .put("thread_pool.write.queue_size", 1)
             .put("thread_pool.get.size", 1)
             .put("thread_pool.get.queue_size", 1)
+            .put(EnableAllocationDecider.CLUSTER_ROUTING_REBALANCE_ENABLE_SETTING.getKey(), EnableAllocationDecider.Rebalance.NONE)
```
Comment (rjernst) [inline modules/kibana/src/internalClusterTest/java/org/elasticsearch/kibana/KibanaThreadPoolIT.java:68]: Can you please add a comment here why this is needed for future readers?

**Review by rjernst — APPROVED** [review]
LGTM

File: modules/kibana/src/internalClusterTest/java/org/elasticsearch/kibana/KibanaThreadPoolIT.java (hunk 1 above)
Comment (mosche) [reply modules/kibana/src/internalClusterTest/java/org/elasticsearch/kibana/KibanaThreadPoolIT.java:68]: 👍 That would help lots

**Review by mosche — APPROVED** [review]
lgtm, thanks for having a look!

File: modules/kibana/src/internalClusterTest/java/org/elasticsearch/kibana/KibanaThreadPoolIT.java (hunk 1 above)
Comment (DaveCTurner) [reply modules/kibana/src/internalClusterTest/java/org/elasticsearch/kibana/KibanaThreadPoolIT.java:69]: ++ see 491b1b774c81c5a2cbed0df053167d0e3ae42f0f

**Comment by DaveCTurner** [comment]
Backports:
- cf63a73084edd091de66b93c2d5e9a3580c19f6c (8.x)
- f3b328ed882936550fb48df744aa705e145799eb (8.17)
