### PR TITLE
Drop top level inner hits in favour of inner hits defined in the query dsl

### LINKED ISSUE #11118: has_child and inner_hits for grandchild hit doesn't work
I'm trying to get `inner_hits` to work on an a two level deep `has_child` query, but the grandchild hits just seem to return an empty array.  If I specify the inner hits at the top level I get the results I want, but its rather too slow. Using inner hits on the has child query seems much faster, but doesn't return the grandchild hits.

Below is an example query:

```json
{
  "from" : 0,
  "size" : 25,
  "query" : {
    "has_child" : {
      "query" : {
        "has_child" : {
          "query" : {
            "filtered" : {
              "query" : {
                "multi_match" : {
                  "query" : "asia",
                  "fields" : [ "_search" ],
                  "operator" : "AND",
                  "analyzer" : "library_synonyms",
                  "fuzziness" : "1"
                }
              },
              "filter" : {
                "and" : {
                  "filters" : [ {
                    "terms" : {
                      "range" : [ "Global" ]
                    }
                  } ]
                }
              }
            }
          },
          "child_type" : "document-ref",
          "inner_hits" : {
            "name" : "document-ref"
          }
        }
      },
      "child_type" : "class",
      "inner_hits" : {
        "size" : 1000,
        "_source" : false,
        "fielddata_fields" : [ "class" ],
        "name" : "class"
      }
    }
  },
  "fielddata_fields" : [ "name" ]
}
```

The `document-ref` inner hits just always returns an empty array.  Should this work (and, if so, any ideas why it isn't?), or is it beyond the means of what inner hits can currently do?

### PR DESCRIPTION
**Pull request by martijnvg**
Also Fixed a limitation that prevent from hierarchical inner hits be defined in query dsl.

Closes #11118

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/query/HasChildQueryBuilder.java [hunk 1]
```diff
@@ -151,12 +153,15 @@ public InnerHitBuilder innerHit() {
...
-        innerHit.setParentChildType(type);
-        innerHit.setQuery(query);
+        innerHit.setParentChildType(type, query);
         this.innerHitBuilder = innerHit;
         return this;
     }
 
+    public void clearInnerHit() {
+        this.innerHitBuilder = null;
+    }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/HasChildQueryBuilder.java]: Not sure we need this. For instance we don't allow to remove sorts on a SearchRequestBuilder.

File: core/src/main/java/org/elasticsearch/index/query/HasChildQueryBuilder.java [hunk 2]
```diff
@@ -151,12 +153,15 @@ public InnerHitBuilder innerHit() {
     }
 
     public HasChildQueryBuilder innerHit(InnerHitBuilder innerHit) {
-        innerHit.setParentChildType(type);
-        innerHit.setQuery(query);
+        innerHit.setParentChildType(type, query);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/HasChildQueryBuilder.java]: Could we avoid modifying the object that is provided?

File: core/src/main/java/org/elasticsearch/index/query/NestedQueryBuilder.java [hunk 3]
```diff
@@ -109,12 +109,15 @@ public InnerHitBuilder innerHit() {
     }
 
     public NestedQueryBuilder innerHit(InnerHitBuilder innerHit) {
-        innerHit.setNestedPath(path);
-        innerHit.setQuery(query);
+        innerHit.setNestedPath(path, query);
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/NestedQueryBuilder.java]: similar concern about modifying the value that is set

File: core/src/main/java/org/elasticsearch/index/query/support/InnerHitBuilder.java [hunk 4]
```diff
@@ -196,19 +227,93 @@ public void writeTo(StreamOutput out) throws IOException {
...
+                hpqb.clearInnerHit();
+            }
+        } else if (qb instanceof NestedQueryBuilder) {
+            NestedQueryBuilder nqb = (NestedQueryBuilder) qb;
+            InnerHitBuilder ihb = nqb.innerHit();
+            if (ihb != null) {
+                addChildInnerHit(ihb);
+                nqb.clearInnerHit();
+            }
+        } else if (qb instanceof ConstantScoreQueryBuilder) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/support/InnerHitBuilder.java]: All these instanceof calls look fragile to me. I'm wondering that query builders could have an API to expose their sum query builders instead?

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/support/InnerHitBuilder.java]: Hmm thinking about it more I think I think the instanceof way would be fine if we had a way to fail if inner hits are defined below an unsupported query?

Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/index/query/support/InnerHitBuilder.java]: true, this would make the result clearer, instead of silently not inlining the child inner hits and error would be thrown.

File: core/src/main/java/org/elasticsearch/index/query/support/InnerHitBuilder.java [hunk 5]
```diff
@@ -196,19 +227,93 @@ public void writeTo(StreamOutput out) throws IOException {
...
+
+    // Inlines the inner hits of leaf queries with this inner hit,
+    // this is for hierarchical inner hits
+    void inlineLeafInnerHits(QueryBuilder<?> qb) {
+        if (qb instanceof HasChildQueryBuilder) {
+            HasChildQueryBuilder hcqb = (HasChildQueryBuilder) qb;
+            InnerHitBuilder ihb = hcqb.innerHit();
+            if (ihb != null) {
+                addChildInnerHit(ihb);
+                hcqb.clearInnerHit();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/support/InnerHitBuilder.java]: here too I think we should avoid modifying query builders that have been provided by the user

**Comment by martijnvg** [comment]
After discussing this PR with @jpountz we decided to make the following changes:
* When inner hits are inlined we shouldn't inline the provided inner hit, because a make a copy and inline that.
* The method that does the inlining relies on a lot of `instanceof` checks and that is fragile. In order to make the integration better we should add a `buildInnerhits()` method that makes an inlined copy of the user specified inner hits in the query dsl. It is a noop on most queries and on nested, has_child and has_parent it actual returned an inlined copy of the inner hit builder. Compound queries like bool query just delegate.

File: core/src/main/java/org/elasticsearch/index/query/BoolQueryBuilder.java [hunk 6]
```diff
@@ -495,6 +497,17 @@ protected boolean doEquals(BoolQueryBuilder other) {
         return this;
     }
 
+    @Override
+    public void collectInnerHitBuilders(Map<String, InnerHitBuilder> innerHits) {
+        List<QueryBuilder<?>> clauses = new ArrayList<>(filter());
+        clauses.addAll(must());
+        clauses.addAll(should());
+        // no need to include must_not (since there will be no hits for it)
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/BoolQueryBuilder.java]: what about filter clauses?

Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/index/query/BoolQueryBuilder.java]: these are provided as constructor argument.

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/BoolQueryBuilder.java]: ohhhhhh! :)

File: core/src/main/java/org/elasticsearch/index/query/HasChildQueryBuilder.java (hunk 2 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/HasChildQueryBuilder.java]: It seem to me that it would be possible to not call `setParentChildType` here, but to make a copy in `extractInnerHitBuilders` and call `setParentChildType` there on the copy? This way we would never modify a setter argument?

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/HasChildQueryBuilder.java]: and we could also make the `setNestedPath` and `setParentChildType` methods pkg-private?

File: core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java [hunk 7]
```diff
@@ -565,17 +628,23 @@ public boolean equals(Object o) {
...
     }
 
     public static InnerHitBuilder fromXContent(QueryParseContext context) throws IOException {
         return PARSER.parse(context.parser(), new InnerHitBuilder(), context);
     }
 
+    public static void extractInnerHits(QueryBuilder<?> query, Map<String, InnerHitBuilder> innerHitBuilders) {
+        if (query instanceof AbstractQueryBuilder) {
+            ((AbstractQueryBuilder) query).extractInnerHitBuilders(innerHitBuilders);
+        }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java]: can you throw an exception in the else clause, eg. "All queries must extend AbstractQueryBuilder but ..."

File: core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java [hunk 8]
```diff
@@ -165,7 +178,35 @@ public InnerHitBuilder(StreamInput in) throws IOException {
...
+        version = other.version;
+        trackScores = other.trackScores;
+        fieldNames = other.fieldNames;
+        fieldDataFields = other.fieldDataFields;
+        scriptFields = other.scriptFields;
+        fetchSourceContext = other.fetchSourceContext;
+        sorts = other.sorts;
+        highlightBuilder = other.highlightBuilder;
+        query = other.query;
+        childInnerHits = other.childInnerHits;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java]: do we need to deep copy some objects in that list?

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java]: also can we have a test for this method? Something that creates a random InnerHitBuilder, makes a copy, ensure that equals returns true, then modifies the copy and makes sure equals return false?

**Comment by jpountz** [comment]
I left some comments. The registration looks better to me. Now I would like to see if we can stop modifying in-place objects that are passed in the QueryBuilder setters?

**Comment by martijnvg** [comment]
@jpountz I've updated the PR. InnerHitBuilders instances are no longer modified in-place.

File: core/src/main/java/org/elasticsearch/index/query/AbstractQueryBuilder.java [hunk 9]
```diff
@@ -273,6 +274,15 @@ protected final void writeQueries(StreamOutput out, List<? extends QueryBuilder<
         return this;
     }
 
+    /**
+     * For internal usage only!
+     *
+     * Extracts the inner hits from the query tree.
+     * While it extract inner hits, child inner hits are inlined into the inner hit builder they belong to.
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/AbstractQueryBuilder.java]: s/extract/extracts/

File: core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java [hunk 10]
```diff
@@ -64,6 +59,7 @@
     public static final ParseField NAME_FIELD = new ParseField("name");
     public static final ParseField NESTED_PATH_FIELD = new ParseField("path");
     public static final ParseField PARENT_CHILD_TYPE_FIELD = new ParseField("type");
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java]: are the NESTED_PATH_FIELD and PARENT_CHILD_TYPE_FIELD still useful? I would have expected them to be useless now that the top level syntax is gone?

File: core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java [hunk 11]
```diff
@@ -347,72 +413,65 @@ public InnerHitBuilder setHighlightBuilder(HighlightBuilder highlightBuilder) {
...
+        this.parentChildType = parentChildType;
+    }
+
+    String getParentChildType() {
+        return parentChildType;
+    }
+
+    void setNestedPath(String nestedPath) {
+        this.nestedPath = nestedPath;
+    }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java]: can we get rid of setParentChildType and setNestedPath now that they seem to be set through the constructore above?

File: core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java (hunk 10 above)
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/index/query/InnerHitBuilder.java]: It is used in the `build(...)` method to decide what sub search context implementation to build.

**Comment by jpountz** [comment]
LGTM
