### PR TITLE
Stabilize fetch chunk tests: breaker busy-wait, avoid acquireResponseStream poll leak

### LINKED ISSUE #147812: [CI] QueryRescoreModeTests testQueryRescoreMode failing
**Build Scans:**
- [elasticsearch-intake #38780 / part1](https://gradle-enterprise.elastic.co/s/mbgivfqwoyuyc)
- [elasticsearch-intake #38649 / part1](https://gradle-enterprise.elastic.co/s/ofgsbbkhvi7oq)
- [elasticsearch-intake #38617 / part1](https://gradle-enterprise.elastic.co/s/4qjudu7yv3owo)
- [elasticsearch-pull-request #141107 / part-1](https://gradle-enterprise.elastic.co/s/jahqqykf3vtwi)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.search.rescore.QueryRescoreModeTests.testQueryRescoreMode" -Dtests.seed=F9773D196F2C1417 -Dtests.locale=fy-NL -Dtests.timezone=Asia/Qatar -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.rescore.QueryRescoreModeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testQueryRescoreMode'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
Created at:
	in [elasticsearch[testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming][generic][T#1]][testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming]
	org.elasticsearch.search.SearchHit.<init>(SearchHit.java:200)
	org.elasticsearch.search.SearchHit.readFrom(SearchHit.java:282)
	org.elasticsearch.search.fetch.chunk.FetchPhaseResponseChunk.ensureDeserialized(FetchPhaseResponseChunk.java:200)
	org.elasticsearch.search.fetch.chunk.FetchPhaseResponseChunk.consumeHits(FetchPhaseResponseChunk.java:154)
	org.elasticsearch.search.fetch.chunk.FetchPhaseResponseStream.writeChunk(FetchPhaseResponseStream.java:84)
	org.elasticsearch.search.fetch.chunk.TransportFetchPhaseResponseChunkAction.lambda$processChunk$3(TransportFetchPhaseResponseChunkAction.java:144)
	org.elasticsearch.action.ActionListener.run(
[truncated]
```

**Issue Reasons:**
- [main] 1 consecutive failures in step part1
- [main] 1 consecutive failures in pipeline elasticsearch-intake
- [main] 4 failures in test testQueryRescoreMode (1.0% fail rate in 407 executions)
- [main] 3 failures in step part1 (3.3% fail rate in 92 executions)
- [main] 3 failures in pipeline elasticsearch-intake (3.3% fail rate in 92 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #147870: [CI] TransportFetchPhaseCoordinationActionTests testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming failing
**Build Scans:**
- [elasticsearch-intake #38831 / part1](https://gradle-enterprise.elastic.co/s/uv3mu73auml4o)
- [elasticsearch-intake #38828 / part1](https://gradle-enterprise.elastic.co/s/puy4aodleby3k)
- [elasticsearch-pull-request #141938 / part-1](https://gradle-enterprise.elastic.co/s/kr6rmew24nvru)
- [elasticsearch-intake #38822 / part1](https://gradle-enterprise.elastic.co/s/cimx6ufrzgmxs)
- [elasticsearch-pull-request #142053 / part-1](https://gradle-enterprise.elastic.co/s/xrhqdiz56e5ao)
- [elasticsearch-pull-request #142026 / part-1](https://gradle-enterprise.elastic.co/s/azznwtr7e4jri)
- [elasticsearch-pull-request #142020 / part-1](https://gradle-enterprise.elastic.co/s/l5gtvtkdhvwus)
- [elasticsearch-intake #38811 / part1](https://gradle-enterprise.elastic.co/s/tucmeryf7ydc4)
- [elasticsearch-pull-request #142011 / part-1](https://gradle-enterprise.elastic.co/s/rd2dvgqpidwce)
- [elasticsearch-pull-request #142005 / part-1](https://gradle-enterprise.elastic.co/s/5htyvtgymg66w)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.search.fetch.chunk.TransportFetchPhaseCoordinationActionTests.testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming" -Dtests.seed=F455853718C33C8D -Dtests.locale=fo-FO -Dtests.timezone=Universal -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.fetch.chunk.TransportFetchPhaseCoordinationActionTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <0L>
     but: was <45L>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming
- [main] 2 consecutive failures in step part1
- [main] 2 consecutive failures in pipeline elasticsearch-intake
- [main] 33 failures in test testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming (4.0% fail rate in 826 executions)
- [main] 9 failures in step part1 (4.7% fail rate in 190 executions)
- [main] 23 failures in step part-1 (4.3% fail rate in 534 executions)
- [main] 9 failures in pipeline elasticsearch-intake (4.7% fail rate in 190 executions)
- [main] 22 failures in pipeline elasticsearch-pull-request (4.3% fail rate in 515 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #147967: [CI] TransportFetchPhaseCoordinationActionTests testDoExecuteReleasesRegistrationOnLastChunkDeserializationFailure failing
**Build Scans:**
- [elasticsearch-intake #38768 / part1](https://gradle-enterprise.elastic.co/s/rbzjsbezvirzk)
- [elasticsearch-pull-request #141849 / part-1](https://gradle-enterprise.elastic.co/s/haw542la5xnci)
- [elasticsearch-pull-request #141836 / part-1](https://gradle-enterprise.elastic.co/s/a2wlcbjkp55fg)
- [elasticsearch-pull-request #141834 / part-1](https://gradle-enterprise.elastic.co/s/xhbtanfbyoch4)
- [elasticsearch-intake #38556 / part1](https://gradle-enterprise.elastic.co/s/dptvehgjza22m)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.search.fetch.chunk.TransportFetchPhaseCoordinationActionTests.testDoExecuteReleasesRegistrationOnLastChunkDeserializationFailure" -Dtests.seed=64961104E1C8D8FD -Dtests.locale=bs-Cyrl -Dtests.timezone=Europe/Oslo -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.fetch.chunk.TransportFetchPhaseCoordinationActionTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDoExecuteReleasesRegistrationOnLastChunkDeserializationFailure'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <0L>
     but: was <3L>
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testDoExecuteReleasesRegistrationOnLastChunkDeserializationFailure
- [main] 1 consecutive failures in step part1
- [main] 1 consecutive failures in pipeline elasticsearch-intake
- [main] 5 failures in test testDoExecuteReleasesRegistrationOnLastChunkDeserializationFailure (1.0% fail rate in 525 executions)
- [main] 2 failures in step part1 (1.8% fail rate in 109 executions)
- [main] 3 failures in step part-1 (0.9% fail rate in 331 executions)
- [main] 2 failures in pipeline elasticsearch-intake (1.8% fail rate in 109 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.9% fail rate in 329 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #147974: [CI] CategoryQueryContextTests testToXContext failing
**Build Scans:**
- [elasticsearch-intake #38776 / part1](https://gradle-enterprise.elastic.co/s/anrjjhqtzb2e2)
- [elasticsearch-pull-request #140918 / part-1](https://gradle-enterprise.elastic.co/s/5q36derkdp2ca)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.search.suggest.completion.CategoryQueryContextTests.testToXContext" -Dtests.seed=5C32DAE4A6ABF4AC -Dtests.locale=en-IL -Dtests.timezone=Europe/Kyiv -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.suggest.completion.CategoryQueryContextTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testToXContext'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
Created at:
	in [elasticsearch[testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming][generic][T#1]][testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming]
	org.elasticsearch.search.SearchHit.<init>(SearchHit.java:200)
	org.elasticsearch.search.SearchHit.readFrom(SearchHit.java:282)
	org.elasticsearch.search.fetch.chunk.FetchPhaseResponseChunk.ensureDeserialized(FetchPhaseResponseChunk.java:200)
	org.elasticsearch.search.fetch.chunk.FetchPhaseResponseChunk.consumeHits(FetchPhaseResponseChunk.java:154)
	org.elasticsearch.search.fetch.chunk.FetchPhaseResponseStream.writeChunk(FetchPhaseResponseStream.java:84)
	org.elasticsearch.search.fetch.chunk.TransportFetchPhaseResponseChunkAction.lambda$processChunk$3(TransportFetchPhaseResponseChunkAction.java:144)
	org.elasticsearch.action.ActionListener.run(
[truncated]
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testToXContext
- [main] 1 consecutive failures in step part1
- [main] 1 consecutive failures in pipeline elasticsearch-intake
- [main] 2 failures in test testToXContext (0.2% fail rate in 829 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by eranweiss-elastic**
Fixes flaky tests and a refcount leak in `TransportFetchPhaseCoordinationActionTests` by waiting on REQUEST circuit breaker usage instead of retrying `acquireResponseStream` inside `assertBusy` + `expectThrows`. Aligns `TransportFetchPhaseResponseChunkActionTests` with async `processChunk` cleanup.

Problem
`TransportFetchPhaseResponseChunkActionTests`: `processChunk` can still run on TRANSPORT_WORKER after the test releases refs; an immediate `breaker.getUsed() == 0` can race `tearDown` and `ESTestCase#allBreakersMemoryReleased`.
`TransportFetchPhaseCoordinationActionTests: assertBusy(() -> expectThrows(ResourceNotFoundException, () -> acquireResponseStream(...)))` leaks refs when the stream is still registered (acquire succeeds, `expectThrows` fails with `AssertionError`, `assertBusy` retries without decRef).
Solution
`testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming`: replace the busy loop with `assertBusy` until REQUEST breaker `getUsed() == 0` only (no following `expectThrows` + `acquireResponseStream`).
`testDoExecuteReleasesRegistrationOnLastChunkDeserializationFailure`: same breaker `assertBusy`, then a single `expectThrows(ResourceNotFoundException`, `() -> activeFetchPhaseTasks.acquireResponseStream(...))` to assert deregistration without a retry loop around acquire.
`TransportFetchPhaseResponseChunkActionTests`: wrap the final breaker release check in `assertBusy`.

Closes https://github.com/elastic/elasticsearch/issues/147812
Closes https://github.com/elastic/elasticsearch/issues/147974
Closes https://github.com/elastic/elasticsearch/issues/147870
Closes https://github.com/elastic/elasticsearch/issues/147967

Unmutes tests.

### CODE REVIEW

**Review by chrisparrinello — APPROVED** [review]
LGTM! Definitely feels like a cleaner solution. Has it slowed down the execution of these tests at all? i.e. there isn't any chance it gets close to waiting the full 10 seconds before timing out, right?

File: server/src/test/java/org/elasticsearch/search/fetch/chunk/TransportFetchPhaseCoordinationActionTests.java [hunk 1]
```diff
@@ -470,8 +483,18 @@ public void testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreamin
...
+        // instead of polling acquireResponseStream, which would tryIncRef on every failed poll and
+        // leak refs, preventing closeInternal from ever being triggered.
         assertBusy(
-            () -> expectThrows(ResourceNotFoundException.class, () -> activeFetchPhaseTasks.acquireResponseStream(taskId, TEST_SHARD_ID))
+            () -> assertThat(
+                "breaker bytes must be zero once stream closeInternal has completed",
+                breakerService.getBreaker(CircuitBreaker.REQUEST).getUsed(),
+                equalTo(0L)
+            )
         );
```
Comment (reugn) [inline server/src/test/java/org/elasticsearch/search/fetch/chunk/TransportFetchPhaseCoordinationActionTests.java:498]: Append after assertBusy:
```java
expectThrows(ResourceNotFoundException.class, () -> activeFetchPhaseTasks.acquireResponseStream(taskId, TEST_SHARD_ID));
```

**Comment by eranweiss-elastic** [comment]
@chrisparrinello nowhere close to 10s.

File: server/src/test/java/org/elasticsearch/search/fetch/chunk/TransportFetchPhaseCoordinationActionTests.java (hunk 1 above)
Comment (eranweiss-elastic) [reply server/src/test/java/org/elasticsearch/search/fetch/chunk/TransportFetchPhaseCoordinationActionTests.java:498]: Done

**Comment by drempapis** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.4|[](https://github.com/elastic/elasticsearch/pull/148936)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
