### PR TITLE
Fix and unmute `testTsdbTemplatesNoKeywordFieldType`

### LINKED ISSUE #135746: [CI] TSDBIndexingIT testTsdbTemplatesNoKeywordFieldType failing
**Build Scans:**
- [elasticsearch-intake #29336 / part1](https://gradle-enterprise.elastic.co/s/njowvk7nxuwwu)
- [elasticsearch-pull-request #95988 / part-1](https://gradle-enterprise.elastic.co/s/dvhza5vmxt3ow)
- [elasticsearch-pull-request #95980 / part-1](https://gradle-enterprise.elastic.co/s/ltcmwcn4mrm5w)
- [elasticsearch-pull-request #95972 / part-1](https://gradle-enterprise.elastic.co/s/4jdnlsdbes2py)
- [elasticsearch-pull-request #95947 / checkpart1_release-tests](https://gradle-enterprise.elastic.co/s/opy4yr62p2ufe)
- [elasticsearch-pull-request #95948 / part-1](https://gradle-enterprise.elastic.co/s/cky53yzaqlz76)
- [elasticsearch-pull-request #95931 / part-1](https://gradle-enterprise.elastic.co/s/lpc256u2ur72s)
- [elasticsearch-pull-request #95914 / part-1](https://gradle-enterprise.elastic.co/s/ccromuzvg2t4o)
- [elasticsearch-pull-request #95909 / part-1](https://gradle-enterprise.elastic.co/s/ofrwmx7dzrn2q)
- [elasticsearch-pull-request #95896 / part-1](https://gradle-enterprise.elastic.co/s/ca4oabkwgb2le)

**Reproduction Line:**
```
./gradlew ":modules:data-streams:internalClusterTest" --tests "org.elasticsearch.datastreams.TSDBIndexingIT.testTsdbTemplatesNoKeywordFieldType" -Dtests.seed=244EF6AB0AD551AD -Dtests.locale=ff-Latn-SL -Dtests.timezone=Asia/Novosibirsk -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.datastreams.TSDBIndexingIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testTsdbTemplatesNoKeywordFieldType'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.indices.InvalidIndexTemplateException: index_template [id] invalid, cause [Validation Failed: 1: [index.mode=time_series] requires a non-empty [index.routing_path];]
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testTsdbTemplatesNoKeywordFieldType
- [main] 11 failures in test testTsdbTemplatesNoKeywordFieldType (4.2% fail rate in 261 executions)
- [main] 9 failures in step part-1 (6.5% fail rate in 139 executions)
- [main] 10 failures in pipeline elasticsearch-pull-request (7.2% fail rate in 138 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by felixbarny**
This following was problematic:

```java
.put("index.routing_path", randomBoolean() ? null : "metricset")
```

Because it set an explicit `null` as the routing path`.

In cases where the following evaluates to `false`, this leads to an error rightfully complaining that the routing path is required:

```java
.put("index.dimensions_tsid_strategy_enabled", randomDouble() < 0.8)
```

### CODE REVIEW

**Review by kkrik-es — APPROVED** [review]

File: modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/TSDBIndexingIT.java [hunk 1]
```diff
@@ -325,20 +325,16 @@ public void testTsdbTemplatesNoKeywordFieldType() throws Exception {
               }
             }""";
         var request = new TransportPutComposableIndexTemplateAction.Request("id");
+        Settings.Builder settingsBuilder = Settings.builder()
+            .put("index.mode", "time_series")
+            .put("index.dimensions_tsid_strategy_enabled", randomDouble() < 0.8);
+        if (randomBoolean()) {
```
Comment (kkrik-es) [inline modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/TSDBIndexingIT.java:331]: Shouldn't this also be always set when the setting above is false?

Comment (kkrik-es) [reply modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/TSDBIndexingIT.java:331]: I'd simply fix as:

```
boolean dimensions_tsid_strategy_enabled = randomDouble() < 0.8;
...
          .put("index.routing_path", dimensions_tsid_strategy_enabled || randomBoolean() ? "metricset" : null)
          .put("index.dimensions_tsid_strategy_enabled", dimensions_tsid_strategy_enabled)
```

Comment (felixbarny) [reply modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/TSDBIndexingIT.java:331]: > Shouldn't this also be always set when the setting above is false?

No, even if `index.dimensions_tsid_strategy_enabled` is `false`, the `routing_path` doesn't need to be set explicitly as this is a data stream template, for which the `routing_path` will be automatically determined if unset. I explicitly want to test all four permutations of strategy enabled true/false and routing path set/unset. Also, routing path unset is different to routing path explicitly set to null. This triggered the test failure in the first place. It's a bit surprising but not sure if it's worth changing. At least not in this PR.

As both explicitly setting `index.routing_path` as well setting `index.dimensions_tsid_strategy_enable` to `false` disables the new index.dimensions-based tsid strategy, I wanted to give disabling that strategy a lower probability with via `randomDouble() < 0.8`.

Comment (felixbarny) [reply modules/data-streams/src/internalClusterTest/java/org/elasticsearch/datastreams/TSDBIndexingIT.java:331]: Note that I also ran this locally with 500 iterations and all have succeeded.
