### PR TITLE
Pass COMPUTERNAME env var to elasticsearch.bat

### LINKED ISSUE #44656: unconfigured-node-name fails with assertion error on windows
https://scans.gradle.com/s/rleubfn3somoa/console-log?task=:qa:unconfigured-node-name:integTestRunner#L34

```
Â» [2019-07-20T09:42:25,054][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [main], exiting
--
Â»  java.lang.AssertionError: null
Â»  	at org.elasticsearch.common.util.concurrent.EsExecutors.daemonThreadFactory(EsExecutors.java:238) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.cluster.service.ClusterApplierService.createThreadPoolExecutor(ClusterApplierService.java:142) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.cluster.service.ClusterApplierService.doStart(ClusterApplierService.java:136) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:59) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.cluster.service.ClusterService.doStart(ClusterService.java:101) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:59) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.node.Node.start(Node.java:706) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:271) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:348) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
Â»  	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by williamrandolph**
When we run bin/elasticsearch with bash, we get a $HOSTNAME builtin that
contains the hostname of the machine the script is running on. When
there's no provided nodename, Elasticsearch uses the HOSTNAME to create
a nodename. On Windows, Powershell provides a $COMPUTERNAME variable for
the same purpose. CMD.EXE provides the same thing, except it's called
%COMPUTERNAME%. bin/elasticsearch.bat sets $HOSTNAME to the value of
$COMPUTERNAME. However, when testclusters invokes bin/elasticsearch.bat,
the COMPUTERNAME variable doesn't get passed in, leaving HOSTNAME null
and breaking an integration test on Windows.

This commit sets COMPUTERNAME in the environment so that our tests get
the value that Elasticsearch would have when bin/elasticsearch.bat is
invoked from the shell.

Fixes #44656

### CODE REVIEW

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 1]
```diff
@@ -642,6 +642,10 @@ private void runElaticsearchBinScript(String tool, String... args) {
         defaultEnv.put("ES_TMPDIR", tmpDir.toString());
         // Windows requires this as it defaults to `c:\windows` despite ES_TMPDIR
         defaultEnv.put("TMP", tmpDir.toString());
+        // Windows needs the COMPUTERNAME variable in order to set HOSTNAME
+        if (System.getenv("COMPUTERNAME") != null) {
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Where is HOSTNAME passed through for linux? Do we actually need to rely on the real system computername or could we pass in a dummy one for tests?

Comment (williamrandolph) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: HOSTNAME is a builtin for Bash, so we don't need to pass it through. I believe it's always available unless you explicitly unset it:

https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

I think a dummy value will work and avoid the need for a null check.

Comment (williamrandolph) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: In fact, the integration test that was failing here just checks that the node name is not an empty string. I'm going to pass in HOSTNAME and COMPUTERNAME explicitly and test for specific values.

**Review by rjernst — APPROVED** [review]
LGTM

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 2]
```diff
@@ -107,6 +107,8 @@
         "is a pre-release version of Elasticsearch",
         "max virtual memory areas vm.max_map_count"
     );
+    private static final String LINUX_DARWIN_HOSTNAME_OVERRIDE = "LinuxDarwinHostname";
```
Comment (atorok) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Is there any value  in providing different values per platform here ? Could we provide one and avoid platform dependent checks in the test ?

Comment (williamrandolph) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Mainly I wanted to convince myself that I understood how the batch scripts set the hostname variable. For Windows, you might think that setting a `$HOSTNAME` environment variable would do the trick, since that's what the bootstrap code ultimately reads, but that would be wrong, since `elasticsearch.bat` will overwrite `$HOSTNAME` with the value in `$COMPUTERNAME` before starting the application.

Since the different platforms determine the host name differently, I think there's value in demonstrating that in an integration test. On the other hand, I see the value in platform independence for these tests (as opposed to the specifically platform-dependent OS tests). Let me know what you think. I will be happy to change this if you'd like me to (and @rjernst, our other reviewer, agrees).

Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: That's a good point. We also test that HOSTNAME doesn't influence Windows this way. 
I would frop "LIUX_DARWIN" and "WINDOWS" from the constant names since we always set them.

**Comment by williamrandolph** [comment]
@elasticmachine Please run elasticsearch-ci/2

**Review by alpar-t — APPROVED** [review]
LGTM! Thanks!

**Comment by jakelandis** [comment]
moved release label to 7.3.2 since it just barely missed the 7.3.1 cutoff.
