### PR TITLE
Text fields are stored by default in TSDB indices

### LINKED ISSUE #97039: Synthetic _source automatically sets store to true on text fields
There are at least some metric related integrations that have templates that use the text field type.
When these integrations are migrated to tsdb, then often this fails initially complaining with the error that text field either needs a subfield of type keyword or should be stored (by setting store=true, enabling stored fields for this field specifically).
This is a bit confusing sometimes, because the error doesn't come from ES directly and takes time to figure out what needs to be changed.

There are two options here, remove the text field from template when upgrading to tsdb or make suggested changes to the field of type text. What often happens is that `store` is set to `true`. However if this is always the intended approach for integrations, should Elasticsearch change the default of `store` to `true` for tsdb?

Relates to #96254

### PR DESCRIPTION
**Pull request by lkts**
Synthetic source requires text fields to be stored or have keyword
sub-field that supports synthetic source. If there are no keyword fields
 users currently have to explicitly set 'store' to 'true' or get a
validation exception. This is not the best experience. It is quite
likely that setting `store` to `true` is  the correct thing to do but
users still get an error and need to investigate it. With this change if
 `store` setting is not specified in such context it  will be set to
 `true` by default. Setting it explicitly to `false` results in the
 exception.

Closes #97039

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 1]
```diff
@@ -460,6 +456,20 @@ private SubFieldInfo buildPhraseInfo(FieldType fieldType, TextFieldType parent)
...
             MultiFields multiFields = multiFieldsBuilder.build(this, context);
+
+            // If synthetic source is used we need to either store this field
+            // to recreate the source or use keyword multi-fields for that.
+            // So if there are no suitable multi-fields we will default to
+            // storing the field without requiring users to explicitly set 'store'.
+            //
+            // If 'store' parameter was explicitly provided we'll let it pass and
+            // fail in TextFieldMapper#syntheticFieldLoader later if needed.
+            if (store.isSet() == false
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:467]: Ideally we would do default values and validation via the `Parameter` class in the `Builder` constructor in the file. Something like this:

```
this.store = Parameter.storeParam(m -> ((TextFieldMapper) m).store, () -> syntheticSource).addValidator(value ->    {
      if (syntheticSource && value == false) {
         throw new IllegalArgumentException("If synthetic source is enabled, then store cannot be set to false");
      }
   });
```

The issue is that now we can't see the details we care about here in the multi fields (`MultiFields.Builder` only keep a map with a `Function` per field name around). 

Note that this way does require [more plumbing and additional changes](https://gist.github.com/martijnvg/2f2067274a8a1d62b4f6353a2979ef93).

If we like to do this approach we may need to make changes to `MultiFields.Builder`, so that we know whether there is a keyword field (either stored or doesn't have normalizer and ignore above) as multi field.

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 2]
```diff
@@ -1473,4 +1480,17 @@ protected void write(XContentBuilder b, Object value) throws IOException {
             )
         );
     }
+
+    private static KeywordFieldMapper getKeywordFieldMapperForSyntheticSource(Iterable<? extends Mapper> multiFields) {
+        for (Mapper sub : multiFields) {
+            if (sub.typeName().equals(KeywordFieldMapper.CONTENT_TYPE)) {
+                KeywordFieldMapper kwd = (KeywordFieldMapper) sub;
+                if (kwd.hasNormalizer() == false && (kwd.fieldType().hasDocValues() || kwd.fieldType().isStored())) {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:1488]: I think we should also check for whether ignore above is used. Otherwise there may be data loss. (as values get trimmed)

**Review by martijnvg — COMMENTED** [review]
Thanks! I left a comment about a potential different direction we may want to take here.

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java (hunk 2 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:1488]: Looks like ignore above is supported https://github.com/elastic/elasticsearch/pull/89466

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java (hunk 1 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:467]: I tried this approach and there is a problem. It is not possible to have `syntheticSource` flag with proposed impl from gist in `MappingParserContext` because it will return if synthetic source is enabled for _currently existing_ mapping or empty mapping in case of index creation. `mappingLookup` will only be updated as a last step after parsing and building new mapping. 

Value that we need is here https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/mapper/MappingParser.java#L147 and it is not available to field mapper builders since builders are created in `RootObjectMapper#parse` which happens before that line.

We could try:
1. Creating metadata field mappers before `RootObjectMapper`. I assume that there is a good reason for that ordering so this is unlikely a solution.
2. Support storing text fields by default only for TSDB indices (and any future index modes that will have synthethic source always enabled) instead of for any index with synthetic source enabled. This works since we know source is synthetic even without parsing the mapping. I think we are mostly interested in this use case anyway so this may be a good solution.
3. Keep initial implementation from this PR.

Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:467]: Thanks for writing down this analysis. It is kind of a pain that we know synthetic source is used after the builders are created. I don't think it is worth changing the construction of mapping builders, since it most likely is a tricky change. 

Regarding option 2, we know if index mode has been set to time series that synthetic source is enabled, and this will also be the case for the new logging index mode. Given that index mode comes from index setting, we know at the time mapping builders are created what the index mode has been set to. So we can use that as well for determining the default value of the `store` attribute. So let's do option 2?

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java (hunk 2 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:1488]: Ah, that is true. I somehow thought that it wasn't. Looking at the keyword field, if the value's length is above the configured ignore malformed then the value is also stored as a stored field (`KeywordFieldMapper#indexValue(...)` method).

**Comment by lkts** [comment]
I have pushed change to use option 2 from the discussion above. 

One issue i discovered is that it is not possible to implement validation using `Parameter#addValidator` API. The problem is that we need to provide full name of the field in the error message e.g. `k8s.pod.agent.name` (as we currently do). It is not possible to get this information in constructor of `TextFieldMapper.Builder`, this information is only exposed during `build()` via `MapperBuilderContext#buildFullName`. We can only report field name as `name` in this case which is obviously confusing. Additionally, performing validation in constructor changes the error returned to user from `illegal_argument_exception` to `illegal_argument_exception` nested inside `mapper_parsing_exception`. I don't think this is a problem by itself but it would mean that errors are different for TSDB indices and non TSDB indices and that seems undesirable.  

As a result i removed validation logic and i am relying on existing code for that.

File: docs/reference/mapping/types/text.asciidoc [hunk 3]
```diff
@@ -133,8 +133,12 @@ The following parameters are accepted by `text` fields:
 <<mapping-store,`store`>>::
 
     Whether the field value should be stored and retrievable separately from
-    the <<mapping-source-field,`_source`>> field. Accepts `true` or `false`
-    (default).
+    the <<mapping-source-field,`_source`>> field. Accepts `true` or `false` (default).
+    To support <<synthetic-source,synthetic `_source`>> this parameter
```
Comment (martijnvg) [inline docs/reference/mapping/types/text.asciidoc:137]: Maybe rename `To support <<synthetic-source,synthetic `_source`>> this parameter` to `If <<synthetic-source,synthetic `_source`>> is enabled, then this parameter`?

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 4]
```diff
@@ -283,12 +283,23 @@ public static class Builder extends FieldMapper.Builder {
 
         final TextParams.Analyzers analyzers;
 
-        public Builder(String name, IndexAnalyzers indexAnalyzers) {
-            this(name, IndexVersion.current(), indexAnalyzers);
+        public Builder(String name, IndexAnalyzers indexAnalyzers, boolean isSyntheticSourceAlwaysUsed) {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:286]: Maybe rename to `synthetcSourceEnabledViaIndexMode`? To indicate that synthetic source is enabled because the index mode enables it.

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 5]
```diff
@@ -1258,7 +1265,7 @@ public Map<String, NamedAnalyzer> indexAnalyzers() {
 
     @Override
     public FieldMapper.Builder getMergeBuilder() {
-        return new Builder(simpleName(), indexCreatedVersion, indexAnalyzers).init(this);
+        return new Builder(simpleName(), indexCreatedVersion, indexAnalyzers, false).init(this);
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:1268]: Always providing `false` here is incorrect. It could disable synthetic source at some point. I think we need record in `TextFieldMapper` class, that synthetic source was enabled, so the right value can be provided here.

File: server/src/main/java/org/elasticsearch/index/query/QueryRewriteContext.java [hunk 6]
```diff
@@ -196,7 +196,7 @@ MappedFieldType failIfFieldMappingNotFound(String name, MappedFieldType fieldMap
         if (fieldMapping != null || allowUnmappedFields) {
             return fieldMapping;
         } else if (mapUnmappedFieldAsString) {
-            TextFieldMapper.Builder builder = new TextFieldMapper.Builder(name, getIndexAnalyzers());
+            TextFieldMapper.Builder builder = new TextFieldMapper.Builder(name, getIndexAnalyzers(), false);
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/query/QueryRewriteContext.java:199]: I think `indexSettings.getMode().isSyntheticSourceEnabled()` can be used here instead?

File: server/src/test/java/org/elasticsearch/index/fielddata/AbstractFieldDataTestCase.java [hunk 7]
```diff
@@ -90,7 +90,7 @@ public <IFD extends IndexFieldData<?>> IFD getForField(String type, String field
             if (docValues) {
                 fieldType = new KeywordFieldMapper.Builder(fieldName, IndexVersion.current()).build(context).fieldType();
             } else {
-                fieldType = new TextFieldMapper.Builder(fieldName, createDefaultIndexAnalyzers()).fielddata(true)
+                fieldType = new TextFieldMapper.Builder(fieldName, createDefaultIndexAnalyzers(), false).fielddata(true)
```
Comment (martijnvg) [inline server/src/test/java/org/elasticsearch/index/fielddata/AbstractFieldDataTestCase.java:93]: I think `indexService.getIndexSettings().getMode().isSyntheticSourceEnabled()` can be used here instead?

File: server/src/test/java/org/elasticsearch/index/fielddata/FilterFieldDataTests.java [hunk 8]
```diff
@@ -52,7 +52,7 @@ public void testFilterByFrequency() throws Exception {
 
         {
             indexService.clearCaches(false, true);
-            MappedFieldType ft = new TextFieldMapper.Builder("high_freq", createDefaultIndexAnalyzers()).fielddata(true)
+            MappedFieldType ft = new TextFieldMapper.Builder("high_freq", createDefaultIndexAnalyzers(), false).fielddata(true)
```
Comment (martijnvg) [inline server/src/test/java/org/elasticsearch/index/fielddata/FilterFieldDataTests.java:55]: I think `indexService.getIndexSettings().getMode().isSyntheticSourceEnabled()` can be used here? This is a test, but it is good to recreate the builder as close as it would be in production.

I think in case of the other test classes this applies too.

**Review by martijnvg — COMMENTED** [review]
> One issue i discovered is that it is not possible to implement validation using Parameter#addValidator API. The problem is that we need to provide full name of the field in the error message e.g. k8s.pod.agent.name (as we currently do). It is not possible to get this information in constructor of TextFieldMapper.Builder, this information is only exposed during build() via MapperBuilderContext#buildFullName. We can only report field name as name in this case which is obviously confusing. 

I agree this part is confusion, so +1 to rely on the currently validation if store is specifically disabled.

This change is looking good, a left a few more (minor) comments.

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java (hunk 4 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:286]: I was trying to express that and your suggestion is so much more clear!

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java (hunk 5 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:1268]: I don't think it can actually disable it since the default value should be already set correctly before that and `init` will pick it up. I do agree it is more clear to store it though.

File: server/src/main/java/org/elasticsearch/index/query/QueryRewriteContext.java (hunk 6 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/query/QueryRewriteContext.java:199]: `indexSettings` can be null, there is a constructor that explicitly sets it to null. I was "inspired" by the line below that always sets `MapperBuilderContext#isSourceSynthetic` to `false` in this context. I'll check index settings and fallback to false.

File: server/src/test/java/org/elasticsearch/index/fielddata/FilterFieldDataTests.java (hunk 8 above)
Comment (lkts) [reply server/src/test/java/org/elasticsearch/index/fielddata/FilterFieldDataTests.java:55]: I have fixed this where it  was possible.

**Comment by lkts** [comment]
CI uncovered another interesting problem. `store` parameter was not serialized here https://github.com/elastic/elasticsearch/blob/2b67444a465ca50a6854c36025fd7f23aac5a117/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java#L1423 because `includeDefaults` seems to be always `false`. During downsampling new index is created which is _not a TSDB index_ and since `store` value was not serialized it defaults to `false`. We successfully transfer synthetic source setting from original index and as a result we now have synthetic source and text field that is not stored.

I have fixed serialization but i honestly don't know if it is a proper solution. I don't really like the state of "defaults can be interpreted differently in different contexts".

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 9]
```diff
@@ -283,19 +285,40 @@ public static class Builder extends FieldMapper.Builder {
...
+            //
+            // If 'store' parameter was explicitly provided we'll reject the request.
+            this.store = Parameter.storeParam(
+                m -> ((TextFieldMapper) m).store,
+                () -> isSyntheticSourceEnabledViaIndexMode && multiFieldsBuilder.hasSyntheticSourceCompatibleKeywordField() == false
+            )
+                // we want to serialize 'true' value even if it is default
+                // since defaults differ for different index modes
+                // and can be interpreted differently is different context
+                .setSerializerCheck((includeDefaults, isConfigured, value) -> includeDefaults || isConfigured || value);
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:313]: A downsampled index should have index.mode=time_series. What exact failure occurs if this check is missing? Maybe we need to change something in `TransportDownsampleAction` instead.

**Comment by lkts** [comment]
@elasticmachine update branch

File: server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java [hunk 10]
```diff
@@ -249,6 +251,61 @@ public void testDefaults() throws IOException {
         assertEquals(DocValuesType.NONE, fieldType.docValuesType());
     }
 
+    public void testStoreParameterDefaults() throws IOException {
```
Comment (martijnvg) [inline server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java:254]: I think this test needs to be adjusted with the serialization logic removed to address the CI failure?

File: docs/reference/mapping/types/text.asciidoc [hunk 11]
```diff
@@ -133,8 +133,12 @@ The following parameters are accepted by `text` fields:
 <<mapping-store,`store`>>::
 
     Whether the field value should be stored and retrievable separately from
-    the <<mapping-source-field,`_source`>> field. Accepts `true` or `false`
-    (default).
+    the <<mapping-source-field,`_source`>> field. Accepts `true` or `false` (default).
+    If <<synthetic-source,synthetic _source>> is enabled, then this
```
Comment (martijnvg) [inline docs/reference/mapping/types/text.asciidoc:137]: Maybe remove `If <<synthetic-source,synthetic _source>> is enabled` part? The `store` param defaults to `true` for tsdb indices, when there is no suitable multi field of type keyword .

**Review by martijnvg — APPROVED** [review]
Left two comments. LGTM otherwise.

File: docs/reference/mapping/types/text.asciidoc (hunk 11 above)
Comment (lkts) [reply docs/reference/mapping/types/text.asciidoc:137]: Woops, thanks. This is leftover.
