### PR TITLE
QL: Add error logging for *QL

### LINKED ISSUE #100801: EQL: log returned exceptions
### Description

We need to make sure we capture the exceptions leading to a non-successful response to the user. 
These should capture any other wrapped exceptions. 
Depending on the cause, they should be log warnings or errors.

### PR DESCRIPTION
**Pull request by bpintea**
This adds loggign for the *QL pluggins.

Exceptions resulting in a 5xx-class responses are logged on `WARN` level, otherwise `DEBUG`.

Fixes #100801, #100802.

### CODE REVIEW

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plugin/RestEqlSearchAction.java [hunk 1]
```diff
@@ -6,13 +6,13 @@
  */
 package org.elasticsearch.xpack.eql.plugin;
 
-import org.apache.logging.log4j.LogManager;
-import org.apache.logging.log4j.Logger;
 import org.elasticsearch.action.ActionListener;
```
Comment (alex-spies) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plugin/RestEqlSearchAction.java:9]: praise: good catch!

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+     * Log the execution time and query when handling an ES|QL response.
+     */
+    public static <Response> ActionListener<Response> wrapWithFailureLogging(
+        ActionListener<Response> actionListener,
+        Logger logger,
+        String queryName
+    ) {
+        return ActionListener.wrap(actionListener::onResponse, ex -> {
+            actionListener.onFailure(ex);
+            logQueryFailure(logger, queryName, ex, null);
```
Comment (alex-spies) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java:77]: Nit: if we log the failure first, there's less chance that we fail inside `onFailure` and don't see the failure.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlResponseListener.java [hunk 3]
```diff
@@ -164,6 +166,7 @@ public ActionListener<EsqlQueryResponse> wrapWithLogging() {
             long timeMillis = stopWatch.stop().getMillis();
             onFailure(ex);
             LOGGER.info("Failed execution of ESQL query.\nQuery string: [{}]\nExecution time: [{}]ms", esqlQuery, timeMillis);
+            logQueryFailure(LOGGER, LOGGING_PREFIX, ex, null);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlResponseListener.java:169]: I have no idea why I didn't log before sending out the failure response :facepalm: but I think we can do the same here.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+
+    private LoggingUtils() {}
+
+    /**
+     * Log the failure of a QL query, that failed with an exception.
+     * @param logger The logger to send the failure message too.
+     * @param queryName The type of QL query. Example `EQL query`. It is prepended to the failure message.
+     * @param throwable The exception the query failed with.
+     * @param preamble An optional message to log along the failure. Can be `null`.
+     */
```
Comment (alex-spies) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java:26]: praise: :heart: for the javadoc

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+import org.elasticsearch.logging.Level;
+import org.elasticsearch.logging.Logger;
+
+public final class LoggingUtils {
+
+    private LoggingUtils() {}
+
+    /**
+     * Log the failure of a QL query, that failed with an exception.
+     * @param logger The logger to send the failure message too.
```
Comment (alex-spies) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java:22]:
```suggestion
     * @param logger The logger to send the failure message to.
```

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+            builder.append("\n");
+            builder.append("suppressing: ");
+            builder.append(t.getClass().getCanonicalName());
+            builder.append(": ");
+            builder.append(t.getMessage());
+            builder.append("\n");
+            builder.append(ExceptionsHelper.formatStackTrace(t.getStackTrace()));
+        }
+
+        Level level = ExceptionsHelper.status(throwable).getStatus() >= 500 ? Level.ERROR : Level.INFO;
```
Comment (alex-spies) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java:63]: suggestion: log level `INFO` should probably be reserved for very important stuff - this might make all e.g. verification exceptions turn into `INFO` level events. I think `DEBUG` would be more appropriate.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/RestSqlQueryAction.java [hunk 7]
```diff
@@ -26,10 +28,13 @@
 
 import static org.elasticsearch.rest.RestRequest.Method.GET;
 import static org.elasticsearch.rest.RestRequest.Method.POST;
+import static org.elasticsearch.xpack.ql.util.LoggingUtils.wrapWithFailureLogging;
 import static org.elasticsearch.xpack.sql.proto.CoreProtocol.URL_PARAM_DELIMITER;
 
 @ServerlessScope(Scope.PUBLIC)
 public class RestSqlQueryAction extends BaseRestHandler {
+    private static final Logger LOGGER = LogManager.getLogger(RestSqlQueryAction.class);
+    private static final String LOGGING_PREFIX = "SQL query";
```
Comment (alex-spies) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/RestSqlQueryAction.java:37]: nit:
```suggestion
    private static final String LOGGING_PREFIX = "SQL request";
```
otherwise it might be confusing if a `_sql/translate` fails.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plugin/RestEqlSearchAction.java [hunk 8]
```diff
@@ -32,10 +32,13 @@
...
 import static org.elasticsearch.rest.RestRequest.Method.GET;
 import static org.elasticsearch.rest.RestRequest.Method.POST;
+import static org.elasticsearch.xpack.ql.util.LoggingUtils.logQueryFailure;
+import static org.elasticsearch.xpack.ql.util.LoggingUtils.wrapWithFailureLogging;
 
 @ServerlessScope(Scope.PUBLIC)
 public class RestEqlSearchAction extends BaseRestHandler {
-    private static Logger logger = LogManager.getLogger(RestEqlSearchAction.class);
+    private static final Logger LOGGER = LogManager.getLogger(RestEqlSearchAction.class);
+    private static final String LOGGING_PREFIX = "EQL query";
```
Comment (alex-spies) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plugin/RestEqlSearchAction.java:41]: similarl nit:
```suggestion
    private static final String LOGGING_PREFIX = "EQL request";
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlResponseListener.java [hunk 9]
```diff
@@ -73,6 +74,7 @@ public TimeValue stop() {
     }
 
     private static final Logger LOGGER = LogManager.getLogger(EsqlResponseListener.class);
+    private static final String LOGGING_PREFIX = "ESQL query";
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlResponseListener.java:77]:
```suggestion
    private static final String LOGGING_PREFIX = "ESQL request";
```

**Review by alex-spies — COMMENTED** [review]
I wonder if we should log all 5xx's as `ERROR` - wouldn't `WARN` suffice? I also have a remark about usage of the `INFO` level.

Otherwise LGTM

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java (hunk 6 above)
Comment (bpintea) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java]: I've updated the levels in accordance to the guidance in `CONTRIBUTING.md`: 5xx -> WARN, 4xx -> DEBUG.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java]: That was my initial thought as well, but our `onFailure` listeners only send the failure and if there's something happening in there we'll have other issues than the one generating the request failure. That and concerns about the logging path failing.
But I've applied your suggestion, logging first should serve better.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlResponseListener.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlResponseListener.java:168]: Updated this too.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java [hunk 10]
```diff
@@ -0,0 +1,80 @@
...
+
+    /**
+     * Log the failure of a QL query, that failed with an exception.
+     * @param logger The logger to send the failure message to.
+     * @param queryName The type of QL query. Example `EQL query`. It is prepended to the failure message.
+     * @param throwable The exception the query failed with.
+     * @param preamble An optional message to log along the failure. Can be `null`.
+     */
+    public static void logQueryFailure(Logger logger, String queryName, Throwable throwable, @Nullable String preamble) {
+        StringBuilder builder = new StringBuilder(queryName);
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java:28]: Check the logger value before going through all the effort of assembling the string, which can be costly.
```
Level level = ExceptionsHelper.status(throwable).getStatus() >= 500 ? Level.WARN : Level.DEBUG;
if (logger.isLevel(level)) {
   // assemble string
  logger.log(level, message)
```

Additionally you can use the supplier as long as the exception is accepted:
`logger.log(level, () -> LoggingUtils.createLoggingMessage(error, queryName, throwable, preamble), throwable)`

The advantage of the latter is separating the error message creation from logging.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java [hunk 11]
```diff
@@ -0,0 +1,80 @@
...
+        }
+
+        Level level = ExceptionsHelper.status(throwable).getStatus() >= 500 ? Level.WARN : Level.DEBUG;
+        logger.log(level, builder.toString());
+    }
+
+    /**
+     * Log the execution time and query when handling an ES|QL response.
+     */
+    public static <Response> ActionListener<Response> wrapWithFailureLogging(
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java:70]: Move this into ql.util.ActionListeners - also please double check if there's no utility you can use already from `ActionListener`.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plugin/RestEqlSearchAction.java [hunk 12]
```diff
@@ -32,10 +32,13 @@
 
 import static org.elasticsearch.rest.RestRequest.Method.GET;
 import static org.elasticsearch.rest.RestRequest.Method.POST;
+import static org.elasticsearch.xpack.ql.util.LoggingUtils.logQueryFailure;
+import static org.elasticsearch.xpack.ql.util.LoggingUtils.wrapWithFailureLogging;
 
 @ServerlessScope(Scope.PUBLIC)
 public class RestEqlSearchAction extends BaseRestHandler {
-    private static Logger logger = LogManager.getLogger(RestEqlSearchAction.class);
+    private static final Logger LOGGER = LogManager.getLogger(RestEqlSearchAction.class);
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plugin/RestEqlSearchAction.java:40]: 👍 on making sure the errors are reported as coming from the SearchAction and NOT from a wrapping listener.

**Review by costin — APPROVED** [review]
LGTM except falling into the common trap of eagerly creating the logging message even when it's not necessary.
Btw, it's typically more useful to indicate at the beginning of the message if the query failed or not to avoid having to scroll:
`Completed/Successful query [...]"
`Errored/Failed query [...]"

Can't think right now of better message prefix that work better.

**Review by alex-spies — APPROVED** [review]
LGTM!

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java (hunk 10 above)
Comment (bpintea) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/LoggingUtils.java]: Ah, thanks. Should have checked on available methods before. the `logger.log(..., Throwable)` does pretty much all what's needed, so I've removed the custom logging and wrapper.

**Comment by bpintea** [comment]
> if the query failed or not 

The logging only occurs on failure. Removed now the prefixes too, will let the class name that the logger adds be the indicator of failing query type.
