### PR TITLE
Use Suppliers To Get Inference Results In Semantic Queries

### LINKED ISSUE #136621: Semantic Query may throw "too many rewrite rounds"
### Elasticsearch Version

_current_

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

Seen in production, `SemanticQueryBuilder` will sometimes throw IllegalStateException due to too many rewrite rounds

### Steps to Reproduce

_N/A_

### Logs (if relevant)

Here is the full trace:

```
java.lang.IllegalStateException: too many rewrite rounds, rewriteable might return new objects even if they are not rewritten
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:96)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.Rewriteable.lambda$rewriteAndFetch$0(Rewriteable.java:104)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.index.query.QueryRewriteContext$1.onResponse(QueryRewriteContext.java:364)
	at org.elasticsearch.inference@9.3.0/org.elasticsearch.xpack.inference.queries.SemanticQueryBuilder.lambda$registerInferenceAsyncAction$8(SemanticQueryBuilder.java:343)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:228)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:222)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:350)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:111)
	at org.elasticsearch.inference@9.3.0/org.elasticsearch.xpack.inference.action.BaseTransportInferenceAction.lambda$inferOnServiceWithMetrics$7(BaseTransportInferenceAction.java:214)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:258)
	at org.elasticsearch.inference@9.3.0/org.elasticsearch.xpack.inference.services.elasticsearch.ElasticsearchInternalService.lambda$inferTextEmbedding$5(ElasticsearchInternalService.java:648)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:198)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:228)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:222)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:350)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:111)
	at org.elasticsearch.ml@9.3.0/org.elasticsearch.xpack.ml.action.TransportInternalInferModelAction$1.sendResponse(TransportInternalInferModelAction.java:449)
	at org.elasticsearch.ml@9.3.0/org.elasticsearch.xpack.ml.action.TransportInternalInferModelAction$1.onResponse(TransportInternalInferModelAction.java:417)
	at org.elasticsearch.ml@9.3.0/org.elasticsearch.xpack.ml.action.TransportInternalInferModelAction$1.onResponse(TransportInternalInferModelAction.java:412)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:228)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:222)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:350)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:111)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:406)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:326)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:222)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:180)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.CancellableFanOut$SubtasksCompletionHandler.run(CancellableFanOut.java:202)
	at org.elasticsearch.base@9.3.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:125)
	at org.elasticsearch.base@9.3.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:77)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:113)
	at org.elasticsearch.base@9.3.0/org.elasticsearch.core.Releasables.close(Releasables.java:39)
	at org.elasticsearch.base@9.3.0/org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:72)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:51)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:314)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:49)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1726)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1504)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:465)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundHandler.handleResponse(InboundHandler.java:419)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundHandler.executeResponseHandler(InboundHandler.java:166)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:134)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:102)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:830)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundPipeline.forwardFragment(InboundPipeline.java:116)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundPipeline.lambda$doHandleBytes$1(InboundPipeline.java:78)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundDecoder.finishMessage(InboundDecoder.java:144)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundDecoder.internalDecode(InboundDecoder.java:129)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundDecoder.decode(InboundDecoder.java:58)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:79)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:69)
	at org.elasticsearch.transport.netty4@9.3.0/org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.channelRead(Netty4MessageInboundHandler.java:54)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.3.0/org.elasticsearch.transport.netty4.NettyByteBufSizer.channelRead(NettyByteBufSizer.java:33)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler@4.1.126.Final/io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1519)
	at io.netty.handler@4.1.126.Final/io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1377)
	at io.netty.handler@4.1.126.Final/io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1428)
	at io.netty.codec@4.1.126.Final/io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.codec@4.1.126.Final/io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.codec@4.1.126.Final/io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.transport@4.1.126.Final/io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.transport@4.1.126.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.126.Final/io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.transport@4.1.126.Final/io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.transport@4.1.126.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:796)
	at io.netty.transport@4.1.126.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:697)
	at io.netty.transport@4.1.126.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:660)
	at io.netty.transport@4.1.126.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.common@4.1.126.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:998)
	at io.netty.common@4.1.126.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```

### PR DESCRIPTION
**Pull request by Mikep86**
Updates the `semantic` query and the semantic query rewrite interceptors to use suppliers when building the inference results map.

This fixes https://github.com/elastic/elasticsearch/issues/136621, which was caused by changes made in https://github.com/elastic/elasticsearch/pull/134956. In particular, gating inference action registration on `queryRewriteContext.hasAsyncActions() == false` caused problems when a query contained many clauses with a `semantic` or intercepted query. The `hasAsyncActions` check would only allow one `semantic`/intercepted query to register inference action(s) per rewrite iteration. If the query contained more than 16 clauses with `semantic` or intercepted queries, the rewrite rounds would be exhausted.

This is fixed through the usage of suppliers, which removes the need for the `queryRewriteContext.hasAsyncActions() == false` check and allows all `semantic`/intercepted queries to register inference actions(s) in the same rewrite round.

This PR also refactors some of the util methods used in `inference` plugin integration tests into a common location.

### CODE REVIEW

File: x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/IntegrationTestUtils.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+                    .prepareDelete(indexName)
+                    .setIndicesOptions(
+                        IndicesOptions.builder().concreteTargetOptions(new IndicesOptions.ConcreteTargetOptions(true)).build()
+                    )
+                    .execute()
+            )
+        );
+    }
+
+    public static XContentBuilder generateMapping(Map<String, String> semanticTextFields) throws IOException {
```
Comment (markjhoy) [inline x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/IntegrationTestUtils.java]: nitpick - if this is specific for a semantic text field type, I'd consider naming it something more specific.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InferenceResultsMapSupplier.java [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+
+package org.elasticsearch.xpack.inference.queries;
+
+import org.elasticsearch.inference.InferenceResults;
+
+import java.util.Map;
+import java.util.Objects;
+import java.util.function.Supplier;
+
+class InferenceResultsMapSupplier implements Supplier<Map<FullyQualifiedInferenceId, InferenceResults>> {
```
Comment (markjhoy) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InferenceResultsMapSupplier.java]: Is this class used? I see a number of parameters and variables of the type `Supplier<Map<FullyQualifiedInferenceId, InferenceResults>>` (which, I think is functionally equivalent), but I'm not seeing any instances of this class `InferenceResultsMapSupplier`. Unless I missed something ;)

Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InferenceResultsMapSupplier.java]: Yes, this is used as the concrete implementation of `Supplier<Map<FullyQualifiedInferenceId, InferenceResults>>`. We purposefully use `Supplier<Map<FullyQualifiedInferenceId, InferenceResults>>` outside of where the supplier should be modified so that the supplier's `set` method can only be called in scopes where that should actually be done.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InterceptedInferenceQueryBuilder.java [hunk 3]
```diff
@@ -321,29 +342,48 @@ private QueryBuilder doRewriteGetInferenceResults(QueryRewriteContext queryRewri
             );
         }
 
+        if (inferenceResultsMapSupplier != null) {
+            // Additional inference results have already been requested, and we are waiting for them to continue the rewrite process
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InterceptedInferenceQueryBuilder.java:346]: Would it make sense to extract the content of this if block into its own method?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InferenceResultsMapSupplier.java [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+    private Map<FullyQualifiedInferenceId, InferenceResults> inferenceResultsMap = null;
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InferenceResultsMapSupplier.java]: Unless we can guarantee `set` and `get` are called from the same thread should this be `volatile`?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InterceptedInferenceQueryBuilder.java (hunk 3 above)
Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InterceptedInferenceQueryBuilder.java:346]: Done in c6ac186a

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InferenceResultsMapSupplier.java (hunk 4 above)
Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InferenceResultsMapSupplier.java]: Done in 27bbd55d

File: x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/IntegrationTestUtils.java (hunk 1 above)
Comment (Mikep86) [reply x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/IntegrationTestUtils.java]: Done in 868dd8a3

**Comment by Mikep86** [comment]
@elasticmachine update branch

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InferenceResultsMapSupplier.java (hunk 2 above)
Comment (benwtrent) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/InferenceResultsMapSupplier.java]: We don't need this class. Please just use `SetOnce`

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java [hunk 5]
```diff
@@ -291,59 +308,116 @@ static Map<FullyQualifiedInferenceId, InferenceResults> getInferenceResults(
...
+        return rewritten;
+    }
+
+    private static GroupedActionListener<Tuple<FullyQualifiedInferenceId, InferenceResults>> createGroupedActionListener(
+        InferenceResultsMapSupplier inferenceResultsMapSupplier,
+        int inferenceRequestCount,
+        ActionListener<?> listener
+    ) {
+        return new GroupedActionListener<>(inferenceRequestCount, listener.delegateFailureAndWrap((l, responses) -> {
+            ImmutableOpenMap.Builder<FullyQualifiedInferenceId, InferenceResults> mapBuilder = ImmutableOpenMap.builder();
```
Comment (benwtrent) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java]: I don't understand why we are using ImmutableOpenMap. Just use a hashmap with a preallocated size.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java [hunk 6]
```diff
@@ -291,59 +308,116 @@ static Map<FullyQualifiedInferenceId, InferenceResults> getInferenceResults(
...
+
+    static Map<FullyQualifiedInferenceId, InferenceResults> mergeInferenceResultsMaps(
+        @Nullable Map<FullyQualifiedInferenceId, InferenceResults> originalInferenceResultsMap,
+        Map<FullyQualifiedInferenceId, InferenceResults> newInferenceResultsMap
+    ) {
+        Map<FullyQualifiedInferenceId, InferenceResults> mergedInferenceResultsMap = newInferenceResultsMap;
+        if (originalInferenceResultsMap != null && originalInferenceResultsMap.isEmpty() == false) {
+            mergedInferenceResultsMap = Stream.concat(
+                originalInferenceResultsMap.entrySet().stream(),
+                newInferenceResultsMap.entrySet().stream()
```
Comment (benwtrent) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java]: This complicated, why can't we just append to the map?

**Review by benwtrent — COMMENTED** [review]
I still don't fully understand why all clusters need to know about all the inference ids. Why wouldn't the rewrites happen fully on the remote clusters, period?

That is a bigger question, shouldn't block this PR. But this logic is absurdly complicated, and suspect has more sneaky bugs that await us.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java (hunk 5 above)
Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java]: I used this type to maintain immutability where possible, but understood how it add complication

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java (hunk 6 above)
Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java]: I think we can do one better and always take the new inference results map. If the existing inference results map doesn't contain the required embeddings, then it means we are either:

- Calculating embeddings on a local cluster
- Calculating embeddings on a remote cluster for a query that does not specify an inference ID override

In either case, we do not need the embeddings in the existing inference results map.

I was reticent to change this at first because it has effects beyond just the bug fix, but it should help address complexity concerns.

**Comment by Mikep86** [comment]
@elasticmachine update branch

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java [hunk 7]
```diff
@@ -291,59 +307,96 @@ static Map<FullyQualifiedInferenceId, InferenceResults> getInferenceResults(
...
+        });
+    }
+
+    static <T extends QueryBuilder> T getNewInferenceResultsFromSupplier(
+        SetOnce<Map<FullyQualifiedInferenceId, InferenceResults>> supplier,
+        T currentQueryBuilder,
+        Function<Map<FullyQualifiedInferenceId, InferenceResults>, T> copyGenerator
+    ) {
+        Map<FullyQualifiedInferenceId, InferenceResults> newInferenceResultsMap = supplier.get();
+        // It's safe to use only the new inference results map (once set) because we can enumerate the scenarios where we need to get
```
Comment (kderusso) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/queries/SemanticQueryBuilder.java:381]: Thanks for the comment here

File: x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/IntegrationTestUtils.java [hunk 8]
```diff
@@ -0,0 +1,101 @@
...
+import java.io.IOException;
+import java.util.Map;
+
+import static org.elasticsearch.test.ESTestCase.TEST_REQUEST_TIMEOUT;
+import static org.elasticsearch.test.ESTestCase.safeGet;
+import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked;
+import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.equalTo;
+
+public class IntegrationTestUtils {
```
Comment (kderusso) [inline x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/IntegrationTestUtils.java:32]: Nice cleanup to consolidate this

**Review by kderusso — COMMENTED** [review]
Changes LGTM

**Review by kderusso — APPROVED** [review]

**Review by benwtrent — COMMENTED** [review]
I think this is OK I haven't reviewed deeply, I will defer to searchorg folks here.

**Comment by Mikep86** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/136868)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
