### PR TITLE
[Rollup] Return empty response when aggs are missing

### LINKED ISSUE #32256: _rollup_search returns a 400 error when the body is empty-ish
CC @polyfractal @jen-huang 

This request:

```
GET test_rollup_index/_rollup_search
{ "size": 0, "aggregations": {} }
```

Gets this response:

```
{
  "error": {
    "root_cause": [
      {
        "type": "action_request_validation_exception",
        "reason": "Validation Failed: 1: no requests added;"
      }
    ],
    "type": "action_request_validation_exception",
    "reason": "Validation Failed: 1: no requests added;"
  },
  "status": 400
}
```

Would it make sense to expect a similar response to this request? Just an idea. If not, then I think I'd prefer an empty result or barring that a helpful error.

```
GET test_rollup_index/_search
{ "size": 0, "aggregations": {} }

{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 308,
    "max_score": 0,
    "hits": []
  }
}
```

### PR DESCRIPTION
**Pull request by polyfractal**
If a search request doesn't contain aggs (or an empty agg object), we should just retun an empty response.  This is how the normal search API works if you specify zero hits and empty aggs.

The existing behavior throws an exception because it tries to send an empty msearch.

Closes #32256

### CODE REVIEW

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupResponseTranslator.java [hunk 1]
```diff
@@ -238,11 +238,41 @@ private static SearchResponse doCombineResponse(SearchResponse liveResponse, Lis
...
+                    rolledResponses.stream().anyMatch(SearchResponse::isTimedOut),
+                    rolledResponses.stream().anyMatch(SearchResponse::isTimedOut),
+                    rolledResponses.stream().mapToInt(SearchResponse::getNumReducePhases).sum());
+
+                int totalShards = rolledResponses.stream().mapToInt(SearchResponse::getTotalShards).sum();
+                int sucessfulShards = rolledResponses.stream().mapToInt(SearchResponse::getSuccessfulShards).sum();
+                int skippedShards = rolledResponses.stream().mapToInt(SearchResponse::getSkippedShards).sum();
+                long took = rolledResponses.stream().mapToLong(r -> r.getTook().getMillis()).sum() ;
+
+                // Shard failures are ignored atm, so returning an empty array is fine
```
Comment (jimczi) [inline x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupResponseTranslator.java]: we should preserve the shard failures in the response, let's do that in a follow up ? We should also sum the number of shards (rollup + normal) in the response.

**Review by jimczi — APPROVED** [review]
I left one comment for a follow up, LGTM otherwise

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupResponseTranslator.java (hunk 1 above)
Comment (polyfractal) [reply x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupResponseTranslator.java]: Yeah, right now we just [fail the search request](https://github.com/elastic/elasticsearch/blob/81c221d478fe4658d8722f4208dac7c17744f7b7/x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupResponseTranslator.java#L206-L222) if there are _any_ failures, which is why we don't bother to send any back right now.  

But I agree it'd be better to send back the failures.  The above was done for simplicity at the time :)

>  We should also sum the number of shards (rollup + normal) in the response.

Hm actually, I should tweak this whole section.  I didn't sum up the shards because we return the live response if it exists.  But it should be a combined sum regardless of if live/rollup exist or not.  I'll tweak it a little to make this section better.

**Comment by polyfractal** [comment]
CI success got a bit stale, so just in case:

jenkins run gradle build tests please
