### PR TITLE
Clarify gid used by docker image process and bind-mount method

### LINKED ISSUE #47929: Dockerised server cannot access bindmounts with the documented group ID
**Elasticsearch version** (`docker run --rm docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0 elasticsearch --version`):
```console
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Version: 7.4.0, Build: oss/docker/22e1767283e61a198cb4db791ea66e3f11ab9910/2019-09-27T08:36:48.569419Z, JVM: 13
```

**Plugins installed**: []

**JVM version** (``docker run --rm docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0 /bin/bash -c 'source "`dirname "$0"`"/elasticsearch-env && "$JAVA" --version' /usr/share/elasticsearch/bin/elasticsearch``):
```console
openjdk 13 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)
```

**OS version** (`uname -srvm`):
```console
Linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64
```

**Description of the problem including expected versus actual behavior**:

[The documentation on bind-mounting configuration into an Elasticsearch Docker container](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/docker.html#_b_bind_mounted_configuration) claims that the container will run Elasticsearch as a user with group ID 1000, and [the notes on defaults underneath](https://www.elastic.co/guide/en/elasticsearch/reference/7.4/docker.html#_notes_for_production_use_and_defaults) contain detailed instructions to create a bind-mountable data directory to be accessed by such a user. However, when I follow these instructions, Elasticsearch fails with this message:
```console
"org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
```

The output below suggests that [the Dockerfile did add a user with this default group](https://github.com/elastic/elasticsearch/blob/v7.4.0/distribution/docker/src/docker/Dockerfile#L19), but [the command that the entrypoint uses to switch to that user's user ID](https://github.com/elastic/elasticsearch/blob/v7.4.0/distribution/docker/src/docker/bin/docker-entrypoint.sh#L34) does not reference that configuration to set the group ID for the user.

```console
% docker run --rm -it --entrypoint='/bin/bash' docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
[root@0e0c8897af8d elasticsearch]# id
uid=0(root) gid=0(root) groups=0(root)
[root@0e0c8897af8d elasticsearch]# grep elasticsearch /etc/passwd
elasticsearch:x:1000:1000::/usr/share/elasticsearch:/bin/bash
[root@0e0c8897af8d elasticsearch]# grep elasticsearch /etc/group 
root:x:0:elasticsearch
elasticsearch:x:1000:
[root@0e0c8897af8d elasticsearch]# chroot --userspec=1000 / /bin/bash
[elasticsearch@0e0c8897af8d /]$ id
uid=1000(elasticsearch) gid=0(root) groups=0(root)
```

**Steps to reproduce**:

 1. As a user that does not have user ID 1000 on the host, create a folder as per the documentation linked above
```bash
sudo -- sh -c 'mkdir esdatadir && chmod g+rwx esdatadir && chgrp 1000 esdatadir'
```

 2. Run a container that mounts the folder read-write as its data dir
```bash
docker run --rm --ulimit nofile=65535:65535 -e "discovery.type=single-node" -v "$PWD/esdatadir:/usr/share/elasticsearch/data" docker.elastic.co/elasticsearch/elasticsearch-oss:7.4.0
```

**Provide logs (if relevant)**:

<details>

```console
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
{"type": "server", "timestamp": "2019-10-11T15:36:59,291Z", "level": "WARN", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "docker-cluster", "node.name": "889776d11c03", "message":
"uncaught exception in thread [main]",                                                                       
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.4.0.jar:7.4.0]",                                                                                                      "at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125) ~[elasticsearch-cli-7.4.0.jar:7.4.0]",
"at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.4.0.jar:7.4.0]",
"Caused by: org.elasticsearch.ElasticsearchException: failed to bind service",
"at org.elasticsearch.node.Node.<init>(Node.java:614) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.node.Node.<init>(Node.java:255) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.4.0.jar:7.4.0]",
"... 6 more"
"Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes",
"at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
"at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]",
"at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]",
"at java.nio.file.Files.createDirectory(Files.java:693) ~[?:?]",
"at java.nio.file.Files.createAndCheckIsDirectory(Files.java:800) ~[?:?]",
"at java.nio.file.Files.createDirectories(Files.java:786) ~[?:?]",
"at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:272) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:209) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:269) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.node.Node.<init>(Node.java:275) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.node.Node.<init>(Node.java:255) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.4.0.jar:7.4.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.4.0.jar:7.4.0]",
"... 6 more"] }
```

</details>

### PR DESCRIPTION
**Pull request by dliappis**
Elasticsearch runs as uid:gid `1000:0` inside the Docker image:
Clarify docs to reflect this and add required packaging test.
Finally, remove unnecessary trailing whitespace characters from the
Docker docs page.

Closes #47929

### CODE REVIEW

**Comment by dliappis** [comment]
Note: not assigning reviewers yet, until packaging CI turns green.

**Comment by dliappis** [comment]
Packaging-matrix job is now green, assigned reviewers.

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java [hunk 1]
```diff
@@ -177,6 +180,30 @@ public void test70BindMountCustomPathConfAndJvmOptions() throws Exception {
...
+
+        final Path tempDataDir = mktempDir(getTempDir());
+        final Path tempEsDataDir = tempDataDir.resolve("esDataDir");
+        // Make the local directory and contents accessible when bind-mounted
+        mkDirWithPrivilegeEscalation(tempEsDataDir, 1500, 0);
+
+        // Restart the container
+        final Map<Path, Path> volumes = Map.of(tempEsDataDir.toAbsolutePath(), Path.of("/usr/share/elasticsearch/data"));
+
+        runContainer(distribution(), volumes, Map.of("ES_JAVA_OPTS", "-Xms512m -Xmx512m"));
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: Do we need the extra env vars here? I don't see any assertions that the values are in effect. You can pass `null` otherwise.

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java [hunk 2]
```diff
@@ -177,6 +180,30 @@ public void test70BindMountCustomPathConfAndJvmOptions() throws Exception {
         assertThat(nodesResponse, containsString("\"using_compressed_ordinary_object_pointers\":\"false\""));
     }
 
+    /**
+     * Check that the default config can be overridden using a bind mount, and that env vars are respected
+     */
+    public void test71BindMountCustomPathWithDifferentUID() throws Exception {
+        copyFromContainer(installation.config("elasticsearch.yml"), tempDir.resolve("elasticsearch.yml"));
+
+        final Path tempDataDir = mktempDir(getTempDir());
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: `tempDir` in `DockerTests` is recreated for each test, so you don't need to create it yourself.

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java [hunk 3]
```diff
@@ -177,6 +180,30 @@ public void test70BindMountCustomPathConfAndJvmOptions() throws Exception {
         assertThat(nodesResponse, containsString("\"using_compressed_ordinary_object_pointers\":\"false\""));
     }
 
+    /**
+     * Check that the default config can be overridden using a bind mount, and that env vars are respected
+     */
+    public void test71BindMountCustomPathWithDifferentUID() throws Exception {
+        copyFromContainer(installation.config("elasticsearch.yml"), tempDir.resolve("elasticsearch.yml"));
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: I don't understand why this file is being copied. I don't see it being modified or used?

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java [hunk 4]
```diff
@@ -177,6 +180,30 @@ public void test70BindMountCustomPathConfAndJvmOptions() throws Exception {
...
+
+        final Path tempDataDir = mktempDir(getTempDir());
+        final Path tempEsDataDir = tempDataDir.resolve("esDataDir");
+        // Make the local directory and contents accessible when bind-mounted
+        mkDirWithPrivilegeEscalation(tempEsDataDir, 1500, 0);
+
+        // Restart the container
+        final Map<Path, Path> volumes = Map.of(tempEsDataDir.toAbsolutePath(), Path.of("/usr/share/elasticsearch/data"));
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: I think you can do:

```suggestion
        final Map<Path, Path> volumes = Map.of(tempEsDataDir.toAbsolutePath(), installation.data);
```

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 2 above)
Comment (pugnascotia) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: Or is this due to the UI / GUI hacking?

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java [hunk 5]
```diff
@@ -281,6 +284,76 @@ public static boolean existsInContainer(Path path) {
...
+        sh.run(command);
+    }
+
+    /**
+     * Create a directory with specified uid/gid using Docker backed privilege escalation.
+     * @param localPath The path to the directory to create.
+     * @param uid The numeric id for localPath
+     * @param gid The numeric id for localPath
+     */
+    public static void mkDirWithPrivilegeEscalation(Path localPath, Integer uid, Integer gid) {
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java]: Why `Integer` instead of `int`?

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java [hunk 6]
```diff
@@ -281,6 +284,76 @@ public static boolean existsInContainer(Path path) {
...
+        args.add("&&");
+        args.add("chown " + uid + ":" + gid + " " + containerPath.toAbsolutePath());
+        args.add("&&");
+        args.add("chmod 0770 " + containerPath.toAbsolutePath());
+        final String command = String.join(" ", args);
+        executePrivilegeEscalatedShellCmd(command, localPath, containerPath);
+
+        final PosixFileAttributes dirAttributes = FileUtils.getPosixFileAttributes(localPath);
+        final Map<String, Integer> numericPathOwnership = FileUtils.getNumericUnixPathOwnership(localPath);
+        assertEquals(localPath.toString() + " has wrong uid", numericPathOwnership.get("uid"), uid);
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java]: Is it not redundant to call `.toString()` when you're already performing a string concatenation?

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java [hunk 7]
```diff
@@ -281,6 +284,76 @@ public static boolean existsInContainer(Path path) {
...
+        assertEquals(localPath.toString() + " has wrong gid", numericPathOwnership.get("gid"), gid);
+        assertEquals(localPath.toString() + " has wrong permissions", dirAttributes.permissions(), p770);
+    }
+
+    /**
+     * Delete a directory using Docker backed privilege escallation.
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java]:
```suggestion
     * Delete a directory using Docker backed privilege escalation.
```

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 1 above)
Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: This is only because I wanted to keep the memory usage to a minimum for this type of test. Default is 1GB which I thought is unnecessary.

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java (hunk 5 above)
Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java]: This is because the result of `getNumericUnixPathOwnership` is stored in the value of a Map in https://github.com/elastic/elasticsearch/pull/49529/files#diff-4d0f4fd724af524a1c9c1bda1873cd0eR251

If you prefer I can also use switch the signature to use `int` here as you suggested and rely on `.intValue()` in the two assertions below.

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 4 above)
Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: Thanks, addressed in d89f795d61b9e645bb903aa9c2693ec18838b18e

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 2 above)
Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: Good point. I removed it in d4d658a3f98c363d0b2b850f41eac4d0a4d3feaa

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 3 above)
Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: Left over. Removed in d89f795d61b9e645bb903aa9c2693ec18838b18e

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java (hunk 5 above)
Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java]: I implemented the latter approach described above in 17d22b7ce193849fe2bc2ef96e97109e4c668765

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java (hunk 6 above)
Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java]: Addressed in 17d22b7ce193849fe2bc2ef96e97109e4c668765

File: qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java (hunk 7 above)
Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/util/Docker.java]: Addressed in c06b8f29d8131e241981288f758e29ca59a428c3

**Comment by dliappis** [comment]
@pugnascotia Thanks for the comments! I think I addressed them with the exception of https://github.com/elastic/elasticsearch/pull/49529#discussion_r350150386 for the reason suggested there. Could you take another pass when there's time?

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 1 above)
Comment (pugnascotia) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: None of the Docker tests do anything exciting right now, or spin up multiple nodes, so we could make this the default. I think the tests should all work the same way though, unless they need to change a setting for the sake of the test.

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java [hunk 8]
```diff
@@ -177,6 +180,29 @@ public void test70BindMountCustomPathConfAndJvmOptions() throws Exception {
         assertThat(nodesResponse, containsString("\"using_compressed_ordinary_object_pointers\":\"false\""));
     }
 
+    /**
+     * Check that the default config can be overridden using a bind mount, and that env vars are respected
+     */
+    public void test71BindMountCustomPathWithDifferentUID() throws Exception {
+//        copyFromContainer(installation.config("elasticsearch.yml"), tempDir.resolve("elasticsearch.yml"));
```
Comment (pugnascotia) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: Maybe remove this line now?

Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: Ugh 🤦‍♂

Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: Removed in f5aa265686d71f1fcbec53f3039b22bc83ca3364, thank you.

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 1 above)
Comment (dliappis) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java]: I opted for not setting the heap in this test: 289f776bcbf0b4ce122614595c7d64883609707f
We can reduce the footprint for all tests, by default, in a future PR.

**Review by debadair — APPROVED** [review]
LGTM

**Review by pugnascotia — APPROVED** [review]
LGTM
