### PR TITLE
Fix mutateInstance() imlementations in inference module

### LINKED ISSUE #134166: Tests misuse randomValueOtherThan() and mutate too many fields at once when testing hashcode and equals methods
### `randomValueOtherThan()`
The `ESTestCase.randomValueOtherThan(T input, Supplier<T> randomSupplier)` method is used to return an object that is not equal to `input` by invoking the `randomSupplier` lambda. The actual implementation of the method uses `Object.equals()` to determine if the object returned by the `randomSupplier` is equal to `input`, and continues generating new objects until `Object.equals()` returns false. This method is useful when an object doesn't have many possible states, to prevent two randomly generated instances happening to be equal.
For example, consider an example class that has two boolean fields:
```
public class MyObject {
    private final boolean firstField;
    private final boolean secondField;

    MyObject(boolean firstField, boolean secondField) {
        this.firstField = firstField;
        this.secondField = secondField;
    }
}
```

If both fields are used in `equals()` then there are only 4 possible states for the object. Randomly generating instances of this object therefore has a 25% chance that any two randomly generated instances will be equal, which could lead to flakiness if a test expects every randomly generated instance to be different:
```
// 25% chance that the two object below are equal
MyObject object1 = new MyObject(randomBoolean(), randomBoolean());
MyObject object2 = new MyObject(randomBoolean(), randomBoolean());

// Objects below are guaranteed not to be equal
MyObject object3 = new MyObject(randomBoolean(), randomBoolean());
MyObject object4 = randomValueOtherThan(object3, () -> new MyObject(randomBoolean(), randomBoolean()));

```
### `mutateInstance()`
 Tests that extend `AbstractWireTestCase` (which is the standard test case for testing wire serialization) must implement `mutateInstance(T instance)`, which is used in `AbstractWireTestCase.testEqualsAndHashcode()` to generate an instance of the class under test that is not equal to the instance returned from `AbstractWireTestCase.createTestInstance()`. The actual implementation of `AbstractWireTestCase.testEqualsAndHashcode()` checks that the mutated object is not equal to the original object, and that the original object is not equal to the mutated object (since `Object.equals()` implementations must be symmetric). 

### Misuse of `randomValueOtherThan()` in `mutateInstance()`
Several tests are using `randomValueOtherThan()` in the `mutateInstance()` method in a way that renders the `AbstractWireTestCase.testEqualsAndHashcode()` test redundant. Consider the below example:
```
protected MyObject mutateInstance(MyObject instance) {
    return randomValueOtherThan(instance, () -> new MyObject(randomBoolean(), randomBoolean()));
}
```
This code will use `equals()` in `randomValueOtherThan()` to check if the new object is equal to the original instance, then pass that object to `AbstractWireTestCase.testEqualsAndHashcode()` to check the behaviour of `equals()`. This makes the test circular, and prevents it from detecting incorrect implementations of `equals()`, since by definition, any new object returned from `randomValueOtherThan()` will return false when compared to the original instance using `equals()`, meaning that the test is effectively asserting that `false == false`.

### Multiple fields changed at once in `mutateInstance()`
In order to comprehensively test the behaviour of `equals()`, only one field should be modified per call of `mutateInstance()`, since modifying multiple fields at once prevents the test from determining if any individual field is being correctly considered in the `equals()` implementation. Consider the following incorrect implementation of `equals()`:
```
public boolean equals(Object o) {
    if (o == null || getClass() != o.getClass()) return false;
    MyObject that = (MyObject) o;
    // This implementation incorrectly does not consider the value of secondField
    return Objects.equals(firstField, that.firstField);
}
```
If both fields were modified every time `mutateInstance()` was called, then we would not be able to determine if the value returned by `equals()` was affected by changes in any one specific field and so would not be able to tell that the `equals()` method was incorrect implemented.

## Solution
`randomValueOtherThan()` should never be used directly with the instance being mutated in `mutateInstance()`. Instead, `randomValueOtherThan()` can be used with the fields on the instance to modify them individually.

A good implementation of the `mutateInstance()` method for the `MyObject` class used in the examples above would be one that only modifies one field from the instance passed into the method. The following pattern of using a switch statement to modify only one field using `randomValueOtherThan()` is used in many tests and results in the correct behaviour:
```
protected MyObject mutateInstance(MyObject instance) throws IOException {
    boolean firstField = instance.getFirstField();
    boolean secondField = instance.getSecondField();
    // Either mutate the first field, or the second field, then return a new object using the new values
    switch (between(0, 1)) {
        case 0 -> firstField = randomValueOtherThan(firstField, () -> randomBoolean());
        case 1 -> secondField = randomValueOtherThan(secondField, () -> randomBoolean());
        default -> throw new AssertionError("Illegal randomisation branch");
    }
    return new MyObject(firstField, secondField);
}
```
The above approach allows us to confirm that two instances of `MyObject` are not equal when only the first field differs, **or** when only the second field differs, which would catch the incorrect `equals()` implementation shown above.

Using IntelliJ's structural search feature, I identified what I think is a comprehensive list of all test classes that are incorrectly using `randomValueOtherThan()` in `mutateInstance()` and which should be fixed. There also exist many other tests that modify multiple fields at once in `mutateInstance()` and which should be fixed, but there is no easy way to identify them en mass, so these should be fixed when they are encountered.

## Affected classes
Below is a list of all test classes where `randomValueOtherThan()` is being misused in `mutateInstance()` grouped by package. The majority of tests needing to be fixed are in the `elasticsearch.x-pack.plugin.ent-search` and `elasticsearch.x-pack.plugin.inference` packages:

- [x] elasticsearch.server package:
```
RolloverConfigurationTests
PutComposableIndexTemplateRequestTests
DeleteSynonymRuleActionRequestSerializingTests
GetSynonymRuleActionRequestSerializingTests
GetSynonymsActionRequestSerializingTests
GetSynonymsActionResponseSerializingTests
GetSynonymsSetsActionRequestSerializingTests
GetSynonymsSetsActionResponseSerializingTests
PutSynonymRuleActionRequestSerializingTests
PutSynonymsActionRequestSerializingTests
SynonymUpdateResponseSerializingTests
DataStreamMetadataTests
NodesShutdownMetadataTests
```

- [x] elasticsearch.x-pack.plugin.autoscaling package:
```
NodeDecisionsWireSerializationTests
NodeDecisionWireSerializationTests
```

- [x] elasticsearch.x-pack.plugin.core package:
```
MigrateToDataTiersRequestTests
HealthApiFeatureSetUsageTests
EnterpriseSearchFeatureSetUsageBWCSerializingTests
DataTiersFeatureSetUsageTests
InferenceContextTests
UnifiedCompletionActionRequestTests
UnifiedCompletionRequestTests
```

- [x] elasticsearch.x-pack.plugin.ent-search package:
```
DeleteAnalyticsCollectionRequestBWCSerializingTests
GetAnalyticsCollectionRequestBWCSerializingTests
GetAnalyticsCollectionResponseBWCSerializingTests
PostAnalyticsEventDebugResponseBWCSerializingTests
PostAnalyticsEventRequestBWCSerializingTests
PostAnalyticsEventResponseBWCSerializingTests
PutAnalyticsCollectionRequestBWCSerializingTests
PutAnalyticsCollectionResponseBWCSerializingTests
AnalyticsEventTests
ConnectorUpdateActionResponseBWCSerializingTests
GetConnectorActionResponseBWCSerializingTests
ListConnectorActionResponseBWCSerializingTests
PostConnectorActionRequestBWCSerializingTests
PostConnectorActionResponseBWCSerializingTests
PutConnectorActionRequestBWCSerializingTests
PutConnectorActionResponseBWCSerializingTests
UpdateConnectorActiveFilteringActionRequestBWCSerializingTests
UpdateConnectorApiKeyIdActionRequestBWCSerializingTests
UpdateConnectorConfigurationActionRequestBWCSerializingTests
UpdateConnectorErrorActionRequestBWCSerializingTests
UpdateConnectorFeaturesActionRequestBWCSerializingTests
UpdateConnectorFilteringActionRequestBWCSerializingTests
UpdateConnectorFilteringValidationActionRequestBWCSerializingTests
UpdateConnectorIndexNameActionRequestBWCSerializingTests
UpdateConnectorLastSeenActionRequestBWCSerializingTests
UpdateConnectorLastSyncStatsActionRequestBWCSerializingTests
UpdateConnectorNameActionRequestBWCSerializingTests
UpdateConnectorNativeActionRequestBWCSerializingTests
UpdateConnectorPipelineActionRequestBWCSerializingTests
UpdateConnectorSchedulingActionRequestBWCSerializingTests
UpdateConnectorServiceTypeActionRequestBWCSerializingTests
UpdateConnectorStatusActionRequestBWCSerializingTests
DeleteConnectorSecretRequestBWCSerializingTests
DeleteConnectorSecretResponseBWCSerializingTests
GetConnectorSecretRequestBWCSerializingTests
GetConnectorSecretResponseBWCSerializingTests
PostConnectorSecretRequestBWCSerializingTests
PostConnectorSecretResponseBWCSerializingTests
PutConnectorSecretRequestBWCSerializingTests
PutConnectorSecretResponseBWCSerializingTests
CancelConnectorSyncJobActionRequestBWCSerializingTests
CheckInConnectorSyncJobActionRequestBWCSerializingTests
ClaimConnectorSyncJobActionRequestBWCSerializingTests
DeleteConnectorSyncJobActionRequestBWCSerializingTests
GetConnectorSyncJobActionRequestBWCSerializingTests
GetConnectorSyncJobActionResponseBWCSerializingTests
ListConnectorSyncJobsActionRequestBWCSerializingTests
ListConnectorSyncJobsActionResponseBWCSerializingTests
PostConnectorSyncJobActionRequestBWCSerializingTests
PostConnectorSyncJobActionResponseBWCSerializingTests
UpdateConnectorSyncJobErrorActionRequestBWCSerializationTests
UpdateConnectorSyncJobIngestionStatsActionRequestBWCSerializingTests
DeleteQueryRuleActionRequestBWCSerializingTests
DeleteQueryRulesetActionRequestBWCSerializingTests
GetQueryRuleActionRequestBWCSerializingTests
GetQueryRuleActionResponseBWCSerializingTests
GetQueryRulesetActionRequestBWCSerializingTests
GetQueryRulesetActionResponseBWCSerializingTests
ListQueryRulesetsActionRequestBWCSerializingTests
ListQueryRulesetsActionResponseBWCSerializingTests
PutQueryRuleActionRequestBWCSerializingTests
PutQueryRuleActionResponseSerializingTests
PutQueryRulesetActionRequestBWCSerializingTests
PutQueryRulesetActionResponseSerializingTests
TestQueryRulesetActionRequestBWCSerializingTests
TestQueryRulesetActionResponseBWCSerializingTests
DeleteSearchApplicationActionRequestBWCSerializingTests
GetSearchApplicationActionRequestBWCSerializingTests
GetSearchApplicationActionResponseBWCSerializingTests
ListSearchApplicationActionRequestBWCSerializingTests
ListSearchApplicationActionResponseBWCSerializingTests
PutSearchApplicationActionRequestBWCSerializingTests
PutSearchApplicationActionResponseBWCSerializingTests
RenderQueryResponseSerializingTests
SearchApplicationSearchRequestBWCSerializingTests
```

- [ ] elasticsearch.x-pack.plugin.inference package:
```
ModelSecretsTests
GetRerankerWindowSizeActionRequestTests
GetRerankerWindowSizeActionResponseTests
InferenceActionResponseTests
PutInferenceModelRequestTests
PutInferenceModelResponseTests
UpdateInferenceModelActionRequestTests
UpdateInferenceModelActionResponseTests
AwsSecretSettingsTests
ModelRegistryMetadataTests
Ai21ChatCompletionServiceSettingsTests
AmazonBedrockChatCompletionServiceSettingsTests
AmazonBedrockChatCompletionTaskSettingsTests
AmazonBedrockEmbeddingsServiceSettingsTests
AnthropicChatCompletionServiceSettingsTests
AnthropicChatCompletionTaskSettingsTests
AzureAiStudioChatCompletionServiceSettingsTests
AzureAiStudioChatCompletionTaskSettingsTests
AzureAiStudioEmbeddingsServiceSettingsTests
AzureAiStudioEmbeddingsTaskSettingsTests
AzureAiStudioRerankServiceSettingsTests
AzureAiStudioRerankTaskSettingsTests
AzureOpenAiSecretSettingsTests
AzureOpenAiCompletionServiceSettingsTests
AzureOpenAiCompletionTaskSettingsTests
AzureOpenAiEmbeddingsServiceSettingsTests
AzureOpenAiEmbeddingsTaskSettingsTests
CohereServiceSettingsTests
CohereCompletionServiceSettingsTests
CohereEmbeddingsServiceSettingsTests
CohereEmbeddingsTaskSettingsTests
CohereRerankServiceSettingsTests
CohereRerankTaskSettingsTests
CustomSecretSettingsTests
CustomServiceSettingsTests
CustomTaskSettingsTests
InputTypeTranslatorTests
QueryParametersTests
CompletionResponseParserTests
RerankResponseParserTests
SparseEmbeddingResponseParserTests
TextEmbeddingResponseParserTests
ElasticInferenceServiceSparseEmbeddingsServiceSettingsTests
ElasticInferenceServiceCompletionServiceSettingsTests
ElasticInferenceServiceDenseTextEmbeddingsServiceSettingsTests
ElasticInferenceServiceRerankServiceSettingsTests
CustomElandInternalTextEmbeddingServiceSettingsTests
RerankTaskSettingsTests
GoogleAiStudioCompletionServiceSettingsTests
GoogleAiStudioEmbeddingsServiceSettingsTests
GoogleVertexAiSecretSettingsTests
GoogleVertexAiEmbeddingsServiceSettingsTests
GoogleVertexAiEmbeddingsTaskSettingsTests
GoogleVertexAiRerankServiceSettingsTests
GoogleVertexAiRerankTaskSettingsTests
HuggingFaceServiceSettingsTests
HuggingFaceChatCompletionServiceSettingsTests
HuggingFaceElserServiceSettingsTests
HuggingFaceRerankTaskSettingsTests
IbmWatsonxChatCompletionServiceSettingsTests
IbmWatsonxEmbeddingsServiceSettingsTests
JinaAIServiceSettingsTests
JinaAIEmbeddingsServiceSettingsTests
JinaAIEmbeddingsTaskSettingsTests
JinaAIRerankServiceSettingsTests
JinaAIRerankTaskSettingsTests
LlamaChatCompletionServiceSettingsTests
LlamaEmbeddingsServiceSettingsTests
MistralChatCompletionServiceSettingsTests
OpenAiChatCompletionServiceSettingsTests
OpenAiEmbeddingsServiceSettingsTests
OpenAiEmbeddingsTaskSettingsTests
DefaultSecretSettingsTests
RateLimitSettingsTests
VoyageAIServiceSettingsTests
VoyageAIEmbeddingsServiceSettingsTests
VoyageAIEmbeddingsTaskSettingsTests
VoyageAIRerankServiceSettingsTests
VoyageAIRerankTaskSettingsTests
```

### PR DESCRIPTION
**Pull request by DonalEvans**
Closes #134166

### CODE REVIEW

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/common/amazon/AwsSecretSettingsTests.java [hunk 1]
```diff
@@ -118,10 +118,17 @@ protected AwsSecretSettings createTestInstance() {
 
     @Override
     protected AwsSecretSettings mutateInstance(AwsSecretSettings instance) throws IOException {
-        return randomValueOtherThan(instance, AwsSecretSettingsTests::createRandom);
+        if (randomBoolean()) {
+            return new AwsSecretSettings(new SecureString(randomAlphaOfLength(10).toCharArray()), instance.secretKey());
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/common/amazon/AwsSecretSettingsTests.java]: should we not use `randomValueOtherThan` here for access/secret key?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureaistudio/completion/AzureAiStudioChatCompletionTaskSettingsTests.java [hunk 2]
```diff
@@ -243,10 +254,22 @@ protected AzureAiStudioChatCompletionTaskSettings mutateInstanceForVersion(
...
-            randomFrom(randomFrom(new Boolean[] { null, randomBoolean() })),
-            randomFrom(new Integer[] { null, randomNonNegativeInt() })
+            randomDoubleOrNull(),
+            randomDoubleOrNull(),
+            randomBooleanOrNull(),
+            randomIntegerOrNull()
         );
     }
+
+    private static Double randomDoubleOrNull() {
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureaistudio/completion/AzureAiStudioChatCompletionTaskSettingsTests.java]: `ESTestCase` already has some methods like that (e.g. `randomFloatOrNull()`). Should we add those there so we don't have to repeat them in each of these tests?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureopenai/completion/AzureOpenAiCompletionServiceSettingsTests.java
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureopenai/completion/AzureOpenAiCompletionServiceSettingsTests.java]: Should we pass here for rate limits `RateLimitSettingsTests::createRandom or null`?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureopenai/AzureOpenAiSecretSettingsTests.java [hunk 3]
```diff
@@ -165,7 +165,22 @@ protected AzureOpenAiSecretSettings createTestInstance() {
 
     @Override
     protected AzureOpenAiSecretSettings mutateInstance(AzureOpenAiSecretSettings instance) throws IOException {
-        return randomValueOtherThan(instance, AzureOpenAiSecretSettingsTests::createRandom);
+        SecureString apiKey = instance.apiKey();
+        SecureString entraId = instance.entraId();
+        if (apiKey == null || entraId == null) {
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureopenai/AzureOpenAiSecretSettingsTests.java:170]: As there is a constructor that accepts the args without doing validation, do we need the complicated logic here?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/cohere/rerank/CohereRerankTaskSettingsTests.java [hunk 4]
```diff
@@ -149,6 +149,14 @@ protected CohereRerankTaskSettings createTestInstance() {
 
     @Override
     protected CohereRerankTaskSettings mutateInstance(CohereRerankTaskSettings instance) throws IOException {
-        return randomValueOtherThan(instance, CohereRerankTaskSettingsTests::createRandom);
+        var topNDocsOnly = instance.getTopNDocumentsOnly();
+        var returnDocuments = instance.getReturnDocuments();
+        var maxChunksPerDoc = instance.getMaxChunksPerDoc();
+        switch (randomInt(2)) {
+            case 0 -> topNDocsOnly = randomValueOtherThan(topNDocsOnly, () -> randomFrom(randomIntBetween(1, 10), null));
+            case 1 -> returnDocuments = randomValueOtherThan(returnDocuments, () -> randomFrom(randomBoolean(), null));
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/cohere/rerank/CohereRerankTaskSettingsTests.java]: If we end up going for a non-null value and the original value is also non-null, should we just negate original to avoid slowing down the test if we're getting very unlucky?

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/googlevertexai/embeddings/GoogleVertexAiEmbeddingsServiceSettingsTests.java [hunk 5]
```diff
@@ -163,10 +197,14 @@ private static GoogleVertexAiEmbeddingsServiceSettings createRandom() {
...
-            randomFrom(new Integer[] { null, randomNonNegativeInt() }),
-            randomFrom(new SimilarityMeasure[] { null, randomFrom(SimilarityMeasure.values()) }),
+            randomIntegerOrNull(),
+            randomIntegerOrNull(),
+            randomFrom(new SimilarityMeasure[] { null, randomSimilarityMeasure() }),
             randomFrom(new RateLimitSettings[] { null, RateLimitSettingsTests.createRandom() })
         );
     }
+
+    private static Integer randomIntegerOrNull() {
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/googlevertexai/embeddings/GoogleVertexAiEmbeddingsServiceSettingsTests.java]: Reuse `ESTestCase.randomNonNegativeIntOrNull()`

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/googlevertexai/embeddings/GoogleVertexAiEmbeddingsTaskSettingsTests.java [hunk 6]
```diff
@@ -243,10 +252,14 @@ protected GoogleVertexAiEmbeddingsTaskSettings mutateInstanceForVersion(
 
     private static GoogleVertexAiEmbeddingsTaskSettings createRandom() {
         var inputType = randomBoolean() ? randomWithoutUnspecified() : null;
-        var autoTruncate = randomFrom(new Boolean[] { null, randomBoolean() });
+        var autoTruncate = randomBooleanOrNull();
         return new GoogleVertexAiEmbeddingsTaskSettings(autoTruncate, inputType);
     }
 
+    private static Boolean randomBooleanOrNull() {
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/googlevertexai/embeddings/GoogleVertexAiEmbeddingsTaskSettingsTests.java]: Reuse `ESTestCase.randomOptionalBoolean()`

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/openai/embeddings/OpenAiEmbeddingsServiceSettingsTests.java [hunk 7]
```diff
@@ -529,7 +530,36 @@ protected OpenAiEmbeddingsServiceSettings createTestInstance() {
...
+        var dimensions = instance.dimensions();
+        var maxInputTokens = instance.maxInputTokens();
+        var dimensionsSetByUser = instance.dimensionsSetByUser();
+        var rateLimitSettings = instance.rateLimitSettings();
+        switch (randomInt(7)) {
+            case 0 -> modelId = randomValueOtherThan(modelId, () -> randomAlphaOfLength(8));
+            case 1 -> uri = randomValueOtherThan(uri, () -> randomFrom(createUri(randomAlphaOfLength(15)), null));
+            case 2 -> organizationId = randomValueOtherThan(organizationId, () -> randomFrom(randomAlphaOfLength(15), null));
+            case 3 -> similarity = randomValueOtherThan(similarity, () -> randomFrom(randomSimilarityMeasure()));
+            case 4 -> dimensions = randomValueOtherThan(dimensions, () -> randomFrom(randomInt(), null));
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/openai/embeddings/OpenAiEmbeddingsServiceSettingsTests.java]: Reuse `ESTestCase.randomIntOrNull`

**Review by dimitris-athanasiou — CHANGES_REQUESTED** [review]
Cool stuff! A couple of comments. Mostly on cleaning up those `randomXorNull` by reusing existing and adding new ones in `ESTestCase`. I didn't comment on all the places where that is relevant.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureaistudio/completion/AzureAiStudioChatCompletionTaskSettingsTests.java (hunk 2 above)
Comment (DonalEvans) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureaistudio/completion/AzureAiStudioChatCompletionTaskSettingsTests.java]: That's a good idea, yeah, I'll add them and update the tests I touched in this PR to use them

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureopenai/completion/AzureOpenAiCompletionServiceSettingsTests.java
Comment (DonalEvans) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureopenai/completion/AzureOpenAiCompletionServiceSettingsTests.java]: I think using a non-null value is better, I'll update this.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureopenai/AzureOpenAiSecretSettingsTests.java (hunk 3 above)
Comment (DonalEvans) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureopenai/AzureOpenAiSecretSettingsTests.java:170]: I'm not seeing a constructor for `AzureOpenAiSecretSettings` that doesn't do the validation that both arguments aren't null. I could add one, but it doesn't seem like it's worth it just to make one test method slightly simpler.

Comment (dimitris-athanasiou) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/services/azureopenai/AzureOpenAiSecretSettingsTests.java:170]: You're right, my eyes ignored `Objects.requireNonNullElse(apiKey, entraId);`

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM
