### PR TITLE
test(SemanticTextFieldMapperTests): use same version indexSettings 

### LINKED ISSUE #146966: [CI] SemanticTextFieldMapperTests testMinimalToMaximal {p0=true p1=ENTERPRISE} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #12139 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/umue6il4wpnbo)
- [elasticsearch-periodic #12167 / openjdk21_checkpart5_java-matrix](https://gradle-enterprise.elastic.co/s/nsfjtetw6gvio)
- [elasticsearch-pull-request #139031 / part-5](https://gradle-enterprise.elastic.co/s/zzlfeqh7nllr4)
- [elasticsearch-pull-request #139031 / part-5](https://gradle-enterprise.elastic.co/s/6macsriza6ebo)
- [elasticsearch-pull-request #139000 / part-5](https://gradle-enterprise.elastic.co/s/mqjn5aglv3lgg)
- [elasticsearch-pull-request #139000 / part-5](https://gradle-enterprise.elastic.co/s/nxc6vpqhyccko)
- [elasticsearch-intake #37996 / part5](https://gradle-enterprise.elastic.co/s/ocqgggylo3y5m)
- [elasticsearch-pull-request #138796 / part-5](https://gradle-enterprise.elastic.co/s/a6he5bcptuf7o)
- [elasticsearch-pull-request #138796 / part-5](https://gradle-enterprise.elastic.co/s/mmsqoovkwq372)
- [elasticsearch-pull-request #138796 / part-5](https://gradle-enterprise.elastic.co/s/jhh7xkrm6ha42)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.mapper.SemanticTextFieldMapperTests.testMinimalToMaximal {p0=true p1=ENTERPRISE}" -Dtests.seed=B86C5F0988451EE9 -Dtests.locale=fur -Dtests.timezone=Asia/Damascus -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.mapper.SemanticTextFieldMapperTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMinimalToMaximal%20%7Bp0%3Dtrue%20p1%3DENTERPRISE%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: Mapping definition for [field] has unsupported parameters:  [rescore_vector : {oversample=3.0}]
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testMinimalToMaximal {p0=true p1=ENTERPRISE}
- [main] 1 consecutive failures in step windows-2022_checkpart5_platform-support-windows
- [main] 1 consecutive failures in step openjdk21_checkpart5_java-matrix
- [main] 1 consecutive failures in pipeline elasticsearch-periodic-platform-support
- [main] 1 consecutive failures in pipeline elasticsearch-periodic
- [main] 19 failures in test testMinimalToMaximal {p0=true p1=ENTERPRISE} (3.4% fail rate in 567 executions)
- [main] 14 failures in step part-5 (4.0% fail rate in 352 executions)
- [main] 2 failures in step part5 (1.7% fail rate in 116 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (66.7% fail rate in 3 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (1.7% fail rate in 343 executions)
- [main] 2 failures in pipeline elasticsearch-intake (1.7% fail rate in 116 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #146967: [CI] SemanticTextFieldMapperTests testMinimalToMaximal {p0=true p1=BASIC} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #12139 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/umue6il4wpnbo)
- [elasticsearch-periodic #12167 / openjdk21_checkpart5_java-matrix](https://gradle-enterprise.elastic.co/s/nsfjtetw6gvio)
- [elasticsearch-pull-request #139031 / part-5](https://gradle-enterprise.elastic.co/s/zzlfeqh7nllr4)
- [elasticsearch-pull-request #139031 / part-5](https://gradle-enterprise.elastic.co/s/6macsriza6ebo)
- [elasticsearch-pull-request #139000 / part-5](https://gradle-enterprise.elastic.co/s/mqjn5aglv3lgg)
- [elasticsearch-pull-request #139000 / part-5](https://gradle-enterprise.elastic.co/s/nxc6vpqhyccko)
- [elasticsearch-intake #37996 / part5](https://gradle-enterprise.elastic.co/s/ocqgggylo3y5m)
- [elasticsearch-pull-request #138796 / part-5](https://gradle-enterprise.elastic.co/s/a6he5bcptuf7o)
- [elasticsearch-pull-request #138796 / part-5](https://gradle-enterprise.elastic.co/s/mmsqoovkwq372)
- [elasticsearch-pull-request #138796 / part-5](https://gradle-enterprise.elastic.co/s/jhh7xkrm6ha42)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.mapper.SemanticTextFieldMapperTests.testMinimalToMaximal {p0=true p1=ENTERPRISE}" -Dtests.seed=B86C5F0988451EE9 -Dtests.locale=fur -Dtests.timezone=Asia/Damascus -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.mapper.SemanticTextFieldMapperTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMinimalToMaximal%20%7Bp0%3Dtrue%20p1%3DBASIC%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: Mapping definition for [field] has unsupported parameters:  [rescore_vector : {oversample=3.0}]
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testMinimalToMaximal {p0=true p1=BASIC}
- [main] 1 consecutive failures in step windows-2022_checkpart5_platform-support-windows
- [main] 1 consecutive failures in step openjdk21_checkpart5_java-matrix
- [main] 1 consecutive failures in pipeline elasticsearch-periodic-platform-support
- [main] 1 consecutive failures in pipeline elasticsearch-periodic
- [main] 19 failures in test testMinimalToMaximal {p0=true p1=BASIC} (3.3% fail rate in 569 executions)
- [main] 14 failures in step part-5 (4.0% fail rate in 353 executions)
- [main] 2 failures in step part5 (1.7% fail rate in 117 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (66.7% fail rate in 3 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (1.7% fail rate in 344 executions)
- [main] 2 failures in pipeline elasticsearch-intake (1.7% fail rate in 117 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mromaios**
fixes https://github.com/elastic/elasticsearch/issues/146966, fixes https://github.com/elastic/elasticsearch/issues/146967

This might have been introduced in https://github.com/elastic/elasticsearch/pull/146211. 

We were using two different index versions, one from `getVersion` and another in `randomIndexSettings`. The test failure happened when the mapper was created with an older index version and the settings included the `rescore_vector` parameter (while both being legacy). 

This caused `testMinimalToMaximal` to fail 
https://github.com/elastic/elasticsearch/blob/843aeddace6f248cd33760e8ce31f5812e9c1440/test/framework/src/main/java/org/elasticsearch/index/mapper/MapperTestCase.java#L528-L537

In this PR we keep the IndexVersion the same across these calls.

### CODE REVIEW

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapperTests.java [hunk 1]
```diff
@@ -296,16 +301,16 @@ private static void validateIndexVersion(IndexVersion indexVersion, boolean useL
...
-        return super.getVersion();
+        return testIndexVersion;
     }
 
     @Override
     protected Settings getIndexSettings() {
         if (useLegacyFormat) {
-            return SemanticInferenceMetadataFieldsMapperTests.randomIndexSettings(true);
+            return Settings.builder()
+                .put(IndexMetadata.SETTING_INDEX_VERSION_CREATED.getKey(), testIndexVersion)
```
Comment (carlosdelest) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapperTests.java:311]: Nit - Another option would be to lazily assign the test version in getVersion(), and use getVersion() here instead of the attribute directly. But it's the same effect.

**Review by carlosdelest — APPROVED** [review]
Makes sense. Thank you for fixing! ❤️

**Review by mayya-sharipova — APPROVED** [review]

**Review by Mikep86 — APPROVED** [review]
LGTM, thanks for fixing this!

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapperTests.java (hunk 1 above)
Comment (mromaios) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapperTests.java:311]: Thanks! I will leave this for a future touch up, as CI is green :D
