### PR TITLE
Use reader for doc stats

### LINKED ISSUE #22285: Broken stats serialization
We have a serialization bug somewhere in the stats serialization code. I've now seen ~~five~~ six independent reports ([2](https://github.com/elastic/elasticsearch/pull/21478#issuecomment-264607855), [4](https://discuss.elastic.co/t/remote-transport-exception-in-5-1-1-w-jdk-1-8-0-111/69607/3), [5](https://discuss.elastic.co/t/remote-transport-exception-in-5-1-1-w-jdk-1-8-0-111/69607/3) and ~~two~~ three more that are not linkable) of:

```
[2016-12-12T09:26:50,081][WARN ][o.e.t.n.Netty4Transport  ] [...] exception caught on transport layer [[id: 0xcbdaf621, L:/...:35678 - R:.../...:9300]], closing connection
java.lang.IllegalStateException: Message not fully read (response) for requestId [...], handler [org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler/org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction$1@44aa70c], error [false]; resetting
    at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1257) ~[elasticsearch-5.1.1.jar:5.1.1]
```

and the related

```
Caused by: java.io.EOFException: tried to read: 91755306 bytes but only 114054 remaining
```

and

```
Caused by: java.lang.IllegalStateException: No routing state mapped for [103]
    at org.elasticsearch.cluster.routing.ShardRoutingState.fromValue(ShardRoutingState.java:71) ~[elasticsearch-5.1.1.jar:5.1.1]
```

It seems to always be in some stats response, either a node stats response, or a cluster stats response and it's coming from `TransportBroadcastByNodeAction` and the single action defined by a lambda in `TransportNodesAction$AsyncAction`. We are blowing reading the stream somewhere and then reading garbage subsequently.

Whatever it is, it's pesky. So far, there is not a reliable reproduction and finding the bug is tricky since these responses serialize the entire world.

The first instance of this led to #21478 so that we know the handler name, #22152 so we can detect corruption earlier, and #22223 to clean up some serialization code. Right now, I do not think we've squashed the issue.

### PR DESCRIPTION
**Pull request by jasontedor**
Today we try to pull stats from index writer but we do not get a
consistent view of stats. Under heavy indexing, this inconsistency can
be very skewed indeed. In particular, it can lead to the number of
deleted docs being reported as negative and this leads to serialization
issues. Instead, we should provide a consistent view of the stats by
using an index reader.

Closes #22285

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java [hunk 1]
```diff
@@ -215,7 +216,11 @@ public void writeLong(long i) throws IOException {
      * Negative numbers are not supported.
      */
     public void writeVLong(long i) throws IOException {
-        assert i >= 0;
+        if (Assertions.ENABLED) {
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java]: Maybe wait for https://github.com/elastic/elasticsearch/pull/22314?

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java]: Yeah, that's fine with me. I just needed this to fail with something that would get caught and sent back in the response instead of uncaught causing the request to timeout. I'll take a look at #22314 now.

**Comment by jasontedor** [comment]
retest this please

File: core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java [hunk 2]
```diff
@@ -2547,33 +2547,6 @@ public void testHandleDocumentFailure() throws Exception {
 
     }
 
-    public void testDocStats() throws IOException {
```
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: can we keep a simple test in `IndexShardTests` pls

**Review by s1monw — COMMENTED** [review]
I left one comment about tests feel free to move on with this once you get a LGTM from nick... I won't be around for a couple of days

File: core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java (hunk 2 above)
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java]: I pushed a test in f3f650624e0cb43de62626e8b15da3163c1fceb9.

File: core/src/test/java/org/elasticsearch/indices/stats/IndexStatsIT.java [hunk 3]
```diff
@@ -1068,4 +1085,101 @@ public void testFilterCacheStats() throws Exception {
         assertThat(response.getTotal().queryCache.getMemorySizeInBytes(), equalTo(0L));
     }
 
+    /*
+     * Test that we can safely concurrently index and get stats. This test was inspired by a serialization issue that arose due to a race
+     * getting doc stats during heavy indexing. The race could lead to deleted docs being negative which would then be serialized as a
+     * variable-length long. Since serialization of variable-length longs was unsupported, the stream would become corrupted. Here, we want
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/indices/stats/IndexStatsIT.java]: Instead of saying "variable-length long" I'd `{@link StreamOutput#writeVLong}`.

File: core/src/test/java/org/elasticsearch/indices/stats/IndexStatsIT.java [hunk 4]
```diff
@@ -1068,4 +1085,101 @@ public void testFilterCacheStats() throws Exception {
...
+     * to test that we can continue to get stats while indexing.
+     */
+    public void testConcurrentIndexingAndStatsRequests() throws BrokenBarrierException, InterruptedException, ExecutionException {
+        final AtomicInteger idGenerator = new AtomicInteger();
+        final int numberOfThreads = Runtime.getRuntime().availableProcessors();
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/indices/stats/IndexStatsIT.java]: numberOf**Indexing**Threads

**Review by nik9000 — APPROVED** [review]
LGTM so long as you rebase on #22314 and remove the Assertions thing.

**Review by s1monw — APPROVED** [review]
LGTM too

**Comment by jasontedor** [comment]
retest this please

**Comment by jasontedor** [comment]
Thanks @nik9000 and @s1monw.

**Comment by hjxhjh** [comment]
do you have the plan to fix this problem in version 2.4.5 @jasontedor  @nik9000

**Comment by jasontedor** [comment]
@hjxhjh This bug is not present in 2.4.5. Also, now that 6.0.0 is released, 2.x is closed for maintenance and will not see any additional releases.
