### PR TITLE
Retry file watch registration

### LINKED ISSUE #89500: [CI] ClusterStateRestCancellationIT testClusterStateRestCancellation failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/swrn2vccdizu6/tests/:qa:smoke-test-http:javaRestTest/org.elasticsearch.http.ClusterStateRestCancellationIT/testClusterStateRestCancellation

**Reproduction line:**
`./gradlew ':qa:smoke-test-http:javaRestTest' --tests "org.elasticsearch.http.ClusterStateRestCancellationIT.testClusterStateRestCancellation" -Dtests.seed=2034D67B43AAFEF0 -Dtests.locale=ca -Dtests.timezone=Europe/Madrid -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.http.ClusterStateRestCancellationIT&tests.test=testClusterStateRestCancellation

**Failure excerpt:**
```
java.lang.IllegalStateException: unable to launch a new watch service

  at __randomizedtesting.SeedInfo.seed([2034D67B43AAFEF0:A2A0FB19FD8E07BE]:0)
  at org.elasticsearch.reservedstate.service.FileSettingsService.startWatcher(FileSettingsService.java:271)
  at org.elasticsearch.reservedstate.service.FileSettingsService.startIfMaster(FileSettingsService.java:142)
  at org.elasticsearch.reservedstate.service.FileSettingsService.doStart(FileSettingsService.java:116)
  at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:43)
  at org.elasticsearch.node.Node.start(Node.java:1372)
  at org.elasticsearch.test.InternalTestCluster$NodeAndClient.startNode(InternalTestCluster.java:982)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:820)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

  Caused by: java.io.IOException: User limit of inotify watches reached

    at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
    at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:266)
    at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:364)
    at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by grcevski**
Registering a file for watching can fail because the OS (Linux) may not have enough inotify keys to hand out. Before failing to start the watch service, we should retry few times to ensure the OS situation isn't a temporary state.

Relates to https://github.com/elastic/elasticsearch/issues/89500

If this enhancement doesn't resolve https://github.com/elastic/elasticsearch/issues/89500, we will need to make a different fix to our gradle test framework that enables testing of the new file settings service. Porting to 8.5.1 because we have CI failures there too.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java [hunk 1]
```diff
@@ -382,16 +384,37 @@ synchronized void stopWatcher() {
...
         }
-        return settingsDir.register(
-            watchService,
-            StandardWatchEventKinds.ENTRY_MODIFY,
-            StandardWatchEventKinds.ENTRY_CREATE,
-            StandardWatchEventKinds.ENTRY_DELETE
-        );
+        WatchKey watchKey = null;
+
+        for (int i = 0; i < REGISTER_RETRY_COUNT; i++) {
```
Comment (thecoop) [inline server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:400]: I don't think we need an exit condition here, as the only exit from this loop should be the `catch`/`throw` below.

File: server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java [hunk 2]
```diff
@@ -382,16 +384,37 @@ synchronized void stopWatcher() {
...
+            try {
+                watchKey = settingsDir.register(
+                    watchService,
+                    StandardWatchEventKinds.ENTRY_MODIFY,
+                    StandardWatchEventKinds.ENTRY_CREATE,
+                    StandardWatchEventKinds.ENTRY_DELETE
+                );
+                break;
+            } catch (IOException e) {
+                if (i == REGISTER_RETRY_COUNT - 1) {
```
Comment (thecoop) [inline server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:410]: Why the `-1`?

File: server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java [hunk 3]
```diff
@@ -382,16 +384,37 @@ synchronized void stopWatcher() {
         }
     }
 
-    private WatchKey enableSettingsWatcher(WatchKey previousKey, Path settingsDir) throws IOException {
+    // package private for testing
+    long retryDelayMillis(int failedCount) {
+        assert failedCount < 31;
+        return 10 * (1 << failedCount) + Randomness.get().nextInt(10);
```
Comment (thecoop) [inline server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:390]: What's the randomness for here?

File: server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java [hunk 4]
```diff
@@ -382,16 +384,37 @@ synchronized void stopWatcher() {
         }
     }
 
-    private WatchKey enableSettingsWatcher(WatchKey previousKey, Path settingsDir) throws IOException {
+    // package private for testing
+    long retryDelayMillis(int failedCount) {
+        assert failedCount < 31;
```
Comment (thecoop) [inline server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:389]: Worth adding a comment that this is just to protect against overflow, normally `failedCount` should be max 5

File: server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java (hunk 2 above)
Comment (grcevski) [reply server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:410]: i = 0, 1, 2, 3, 4, that's 5 attempts.

File: server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java (hunk 3 above)
Comment (grcevski) [reply server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:390]: For jitter, so that two processes launched at the same time don't accidentally overlap.

Comment (thecoop) [reply server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:390]: Ah, so we could have the same files being read by two different ES instances? Fair.

File: server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java (hunk 2 above)
Comment (thecoop) [reply server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:410]: Ah yes, I was puzzled about the interaction with the loop exit condition (which would set i to 5 on exiting)

File: server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java (hunk 3 above)
Comment (thecoop) [reply server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:390]: Maybe max timeout something like 3-5 seconds, I wouldn't want more than that in case it blocked the thread too much

**Review by thecoop — APPROVED** [review]
