### PR TITLE
Tweak LogsdbIndexingRollingUpgradeIT and TsdbIndexingRollingUpgradeIT

### LINKED ISSUE #115755: [CI] TsdbIndexingRollingUpgradeIT testIndexing {upgradedNodes=1} failing
**Build Scans:**
- [elasticsearch-periodic #4618 / openjdk21_8.17.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/v77kxiiic2tky)
- [elasticsearch-periodic #4618 / openjdk21_9.0.0_java-fips-matrix-bwc](https://gradle-enterprise.elastic.co/s/4lbbo65ncn3ac)

**Reproduction Line:**
```
./gradlew ":qa:rolling-upgrade:v8.17.0#bwcTest" -Dtests.class="org.elasticsearch.upgrades.TsdbIndexingRollingUpgradeIT" -Dtests.method="testIndexing {upgradedNodes=1}" -Dtests.seed=4DEC817DFDB26B5D -Dtests.bwc=true -Dtests.locale=luy -Dtests.timezone=US/Mountain -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.TsdbIndexingRollingUpgradeIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testIndexing%20%7BupgradedNodes%3D1%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:37399], URI [/k9s/_search?pretty=true], status line [HTTP/1.1 400 Bad Request]
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Fielddata is disabled on [k8s.pod.name] in [k9s]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [k8s.pod.name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "k9s",
        "node" : "tAYv6RJyQQKHxJg-7gNkxA",
        "reason" : {
          "type" : "illegal_argument_exception",
          "reason" : "Fielddata is disabled on [k8s.pod.name] in [k9s]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [k8s.pod.name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
        }
      }
    ],
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Fielddata is disabled on [k8s.pod.name] in [k9s]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [k8s.pod.name] in order to load field data by uninverting the inverted index. Note that this can use significant memory.",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "Fielddata is disabled on [k8s.pod.name] in [k9s]. Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [k8s.pod.name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
      }
    }
  },
  "status" : 400
}

```

**Issue Reasons:**
- [main] 2 failures in test testIndexing {upgradedNodes=1} (5.3% fail rate in 38 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by martijnvg**
to fix following test bugs:
* Deal with trail already started error.
* Ensure k8s.pod.name field is mapped as keyword

Closes #115755, #115756, #115757, #115758, #115758

### CODE REVIEW

File: qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/LogsdbIndexingRollingUpgradeIT.java [hunk 1]
```diff
@@ -233,7 +235,13 @@ void query(String dataStreamName) throws Exception {
     protected static void startTrial() throws IOException {
         Request startTrial = new Request("POST", "/_license/start_trial");
         startTrial.addParameter("acknowledge", "true");
-        assertOK(client().performRequest(startTrial));
+        try {
+            assertOK(client().performRequest(startTrial));
```
Comment (kkrik-es) [inline qa/rolling-upgrade/src/javaRestTest/java/org/elasticsearch/upgrades/LogsdbIndexingRollingUpgradeIT.java:239]: Remove the `assertOk`? I think I was getting it triggering, despite the try-catch..

**Review by kkrik-es — APPROVED** [review]

**Comment by martijnvg** [comment]
@elasticmachine update branch
