### PR TITLE
[CI] Fix testClientsLifeCycleForSingleProject

### LINKED ISSUE #128707: [CI] S3ClientsManagerTests testClientsLifeCycleForSingleProject failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8514 / ubuntu-2404-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/wfodx6t7dmdqi)
- [elasticsearch-pull-request #73285 / part-1](https://gradle-enterprise.elastic.co/s/tois4bdei4pbo)
- [elasticsearch-pull-request #73209 / part-1](https://gradle-enterprise.elastic.co/s/b5pjgwh4akq7w)

**Reproduction Line:**
```
./gradlew ":modules:repository-s3:test" --tests "org.elasticsearch.repositories.s3.S3ClientsManagerTests.testClientsLifeCycleForSingleProject" -Dtests.seed=1DA36E369C3C1A0E -Dtests.locale=zh-TW -Dtests.timezone=Africa/Dakar -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.s3.S3ClientsManagerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testClientsLifeCycleForSingleProject),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Expected exception IllegalStateException but no exception was thrown
```

**Issue Reasons:**
- [main] 3 failures in test testClientsLifeCycleForSingleProject (2.7% fail rate in 113 executions)
- [main] 2 failures in step part-1 (4.8% fail rate in 42 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (4.9% fail rate in 41 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
More robust test for closed clients holder. Also changes IllegalStateException to AlreadyClosedException for both closed manager and holder.

Resolves: #128707

### CODE REVIEW

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3ClientsManagerTests.java [hunk 1]
```diff
@@ -203,12 +204,15 @@ public void testClientsLifeCycleForSingleProject() throws Exception {
...
-            () -> clientsHolder.client(createRepositoryMetadata(randomFrom(clientName, anotherClientName)))
-        );
-        assertThat(e.getMessage(), containsString("Project [" + projectId + "] clients holder is closed"));
+        assertBusy(() -> {
+            assertTrue(clientsHolder.isClosed());
+            final var e = expectThrows(AlreadyClosedException.class, () -> {
+                var client = clientsHolder.client(createRepositoryMetadata(randomFrom(clientName, anotherClientName)));
+                client.decRef();
+            });
+            assertThat(e.getMessage(), containsString("Project [" + projectId + "] clients holder is closed"));
```
Comment (DaveCTurner) [inline modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3ClientsManagerTests.java]: nit: doing all of this inside the `assertBusy()` means that we will still pass the test if we temporarily throw a different exception during shutdown. It'd be better if we just looped until we see _some_ exception, and then asserted that the first-thrown exception is an `AlreadyClosedException` with the right message.

**Review by DaveCTurner — APPROVED** [review]
LGTM with one small suggestion about a slightly tighter assertion

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3ClientsManagerTests.java (hunk 1 above)
Comment (ywangd) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3ClientsManagerTests.java]: Makes sense. See b995e28b7919836f65631b602185aa374106e13d. Thanks!
