### PR TITLE
[ML][Data Frame] adds index validations to _start data frame transform

### LINKED ISSUE #44104: [ML] Incorrect response when trying to start a data frame transform and the source index is missing
Spotted in 7.3.0

When trying to start a data frame transform but the source data index is missing, the response status code is incorrect, and the error reason is misleading.

Currently the API responds with **500** and the body looks like this:
```json
{
    "error": {
        "root_cause": [
            {
                "type": "runtime_exception",
                "reason": "Failed to deduce dest mappings"
            }
        ],
        "type": "runtime_exception",
        "reason": "Failed to deduce dest mappings",
        "caused_by": {
            "type": "index_not_found_exception",
            "reason": "no such index [the_source_index]",
            "resource.type": "index_or_alias",
            "resource.id": "the_source_index",
            "index_uuid": "_na_",
            "index": "the_source_index"
        }
    },
    "status": 500
}
```

In order to be consistent with the rest of the ML APIs, what we should be receiving instead should be a **409** and a body that looks like this:
```json
{
    "error": {
        "root_cause": [
            {
                "type": "runtime_exception",
                "reason": "Cannot perform requested action because source index [the_source_index] does not exist"
            }
        ],
        "type": "runtime_exception",
        "reason": "Cannot perform requested action because source index [the_source_index]  does not exist",
    },
    "status": 409
}
```

**Steps to reproduce**
1. Create a data frame
2. Remove source index
3. Start data frame
4. Notice that the API responds with a 500 and the error reason can be a bit more clear.

### PR DESCRIPTION
**Pull request by benwtrent**
QA tests brought up an error on failures returned from ES. We are returning a 500 when it SHOULD validate earlier and return similar failures to that of a `PUT _data_frame/transform`. 

Shout out to @dimitris-athanasiou for writing up tests for the similar validations inside the ML plugin. Laid down the significant ground work for testing the validation method :). 

closes #44104

### CODE REVIEW

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+     *
+     * @param config DataFrameTransformConfig to validate
+     * @param clusterState The current ClusterState
+     * @param indexNameExpressionResolver A valid IndexNameExpressionResolver object
+     * @throws ElasticsearchStatusException when a validation fails
+     */
+    public static void check(DataFrameTransformConfig config,
+                             ClusterState clusterState,
+                             IndexNameExpressionResolver indexNameExpressionResolver) {
+
```
Comment (hendrikmuhs) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java]: possible follow up: should we disallow "." - indices?

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+import org.elasticsearch.xpack.core.dataframe.transforms.DataFrameTransformConfig;
+
+import java.util.Arrays;
+import java.util.HashSet;
+import java.util.Set;
+
+public final class SourceDestValidator {
+
+    /**
+     * Validates the DataFrameTransformConfiguration source and destination indices.
```
Comment (hendrikmuhs) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java]: nit: you say validate here but the method name is check

I wonder: there is more validation in `PutDataFrameTransformAction::validate` which also touches destIndex, maybe consolidate?

**Review by hendrikmuhs — COMMENTED** [review]
LGTM, most of my comments are about further enhancements and cleanup, but I think we should do minimal change in 7.3 (this PR) and consider enhancements for 7.4+ (follow up PR)

**Review by davidkyle — APPROVED** [review]
LGTM

Thanks for doing this it also addresses one of the changes required for deferring validation to on `_start` 

https://github.com/elastic/elasticsearch/issues/43439#issuecomment-507715191

No I just have to port the has privilege check

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java (hunk 2 above)
Comment (benwtrent) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java]: @hendrikmuhs I was thinking around that, but all those validations on naming don't need to occur here. 

I can add them for completeness's sake, if this is a strongly desired. But the idea of these validations is that they are more complex than a simple "are the names valid" and require access to the cluster state.

Comment (hendrikmuhs) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java]: validation now happens in 2 places, this isn't obvious to someone who starts reading the code, so minimum some code comment would be nice. Consolidating all the logic in one place would be better but I am not sure if there are technical reasons why it's spread over 2 places. I am not asking for duplication.

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java (hunk 1 above)
Comment (droberts195) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java]: Funily enough @richcollier was just pinging me about the possibility of using data frame transforms on anomaly detector job results.  Maybe instead of outlawing `.` indices we should just log a warning along the lines of "may cause some component to stop working -use at your own risk".

Comment (richcollier) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java]: Yes, we should allow it - I’m already imagining that a data frame job could build a summary index of anomalies (from .ml-anomalies) that are correlated for a different style of reporting or alerting

**Review by hendrikmuhs — APPROVED** [review]
LGTM
