### PR TITLE
Completion types with multi-fields support

### LINKED ISSUE #15115: Indexing completion type fields with multi-fields fails
**Edit:** As it turns out, the issue I originally had was expected behavior, but it would be better if mappings like this would be rejected when someone tries to set them, so I'm leaving the original issue text below:

I'm trying to specify a field like this in 2.1.0:

```
...
"city": {
    "type": "completion",
    "preserve_separators": false,
    "payloads": true,
    "fields": {
        "analyzed": {
            "type": "completion",
            "analyzer": "standard",
            "payloads": true,
        }
    }
}
...
```

Indexing seems to be okay, but when searching, I get an error saying that `"Field [city.analyzed] is not a completion suggest field"`. Am I wrong to expect this to work?

### PR DESCRIPTION
**Pull request by pgomulka**
Mappings with completion type and multi-fields, were not able to index array or
object format on completion fields. Only string format was supproted.
This is fixed by providing multiField parser with externalValueContext with already parsed object

closes #15115

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java [hunk 1]
```diff
@@ -436,8 +436,9 @@ public void parse(ParseContext context) throws IOException {
         Token token = parser.currentToken();
         Map<String, CompletionInputMetaData> inputMap = new HashMap<>(1);
 
-        // ignore null values
-        if (token == Token.VALUE_NULL) {
+        if (context.externalValueSet()) {
+            inputMap = (Map<String, CompletionInputMetaData>) context.externalValue();
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java]: The external value is not always set by another `completion` mapper so you need to check the type.
I think it would be simpler to just add an input field in the `CompletionInputMetaData` class and do something like:
````
 if (context.externalValueSet()) {
   if (context.externalValue().getClass().equals(CompletionInputMetaData.class)) {
     CompletionInputMetaData inputAndMeta = (CompletionInputMetaData) context.externalValue();
     inputMap = Collections.singletonMap(inputAndMeta.input(), inputAndMeta);
   } else {
     inputMap = Collections.singletonMap(context.externalValue().toString(), new CompletionInputMetaData(Collections.<String, Set<CharSequence>>emptyMap(), 1));
  }...
````

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java [hunk 2]
```diff
@@ -182,6 +183,121 @@ public void testParsingFailure() throws Exception {
...
+                    .startObject()
+                    .field("completion", "suggestion")
+                    .endObject()),
+            XContentType.JSON));
+
+        ParseContext.Document indexableFields = parsedDocument.rootDoc();
+        assertSuggestFields(indexableFields.getFields("completion"), 1);
+        assertThat(indexableFields.getFields("completion.analyzed"), arrayWithSize(2));
+    }
+
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: We need a test with a context completion suggester as well.

**Review by jimczi — COMMENTED** [review]
Thanks @pgomulka , it's a good start. I left some comments.

File: server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java (hunk 1 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java]: well spotted, indeed missed these scenarios where external value is set by GeoPointFIeldMapper. Will add test cases and cover that.

Also, good suggestion. Will extend CompletionInputMetaData to include inputField and return that as a toString

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java (hunk 2 above)
Comment (pgomulka) [reply server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: true, will add additional test cases to cover that

**Comment by pgomulka** [comment]
retest this please

**Comment by pgomulka** [comment]
@jimczi I have updated the PR, could you please take a look?

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java [hunk 3]
```diff
@@ -182,6 +184,274 @@ public void testParsingFailure() throws Exception {
...
+        ParsedDocument parsedDocument = defaultMapper.parse(SourceToParse.source("test", "type1", "1", BytesReference
+                .bytes(XContentFactory.jsonBuilder()
+                    .startObject()
+                    .field("completion", "suggestion")
+                    .endObject()),
+            XContentType.JSON));
+
+        ParseContext.Document indexableFields = parsedDocument.rootDoc();
+        assertSuggestFields(indexableFields.getFields("completion"), 1);
+        assertThat(indexableFields.getFields("completion.analyzed"), arrayWithSize(2));
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: Can you check that the field has the expected content?:
```
  assertEquals("suggestion", indexableFields.getFields("completion.analyzed")[0].stringValue());
```

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java [hunk 4]
```diff
@@ -182,6 +184,274 @@ public void testParsingFailure() throws Exception {
...
+
+        ParsedDocument parsedDocument = defaultMapper.parse(SourceToParse.source("test", "type1", "1", BytesReference
+                .bytes(XContentFactory.jsonBuilder()
+                    .startObject()
+                    .array("keywordfield", "key1", "key2", "key3")
+                    .endObject()),
+            XContentType.JSON));
+
+        ParseContext.Document indexableFields = parsedDocument.rootDoc();
+        assertThat(indexableFields.getFields("keywordfield"), arrayWithSize(6));
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: Can you check that the field has the expected content?

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java [hunk 5]
```diff
@@ -182,6 +184,274 @@ public void testParsingFailure() throws Exception {
...
+                                .array("place_type","cafe","food")
+                            .endObject()
+                            .field("weight", 3)
+                        .endObject()
+                    .endObject()),
+            XContentType.JSON));
+
+        ParseContext.Document indexableFields = parsedDocument.rootDoc();
+        assertFieldsOfType(indexableFields.getFields("suggest"), ContextSuggestField.class, 2);
+        assertFieldsOfType(indexableFields.getFields("suggest.subsuggest"), ContextSuggestField.class, 2);
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: Can you check that the field has the expected content?:

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java [hunk 6]
```diff
@@ -182,6 +184,274 @@ public void testParsingFailure() throws Exception {
...
+                .bytes(XContentFactory.jsonBuilder()
+                    .startObject()
+                    .array("suggest", "starbucks","timmy")
+                    .array("cat","cafe","food")
+                    .endObject()),
+            XContentType.JSON));
+
+        ParseContext.Document indexableFields = parsedDocument.rootDoc();
+        assertFieldsOfType(indexableFields.getFields("suggest"), ContextSuggestField.class, 2);
+        assertFieldsOfType(indexableFields.getFields("suggest.subsuggest"), ContextSuggestField.class, 2);
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: Can you check that the field has the expected content?:

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java [hunk 7]
```diff
@@ -182,6 +184,274 @@ public void testParsingFailure() throws Exception {
...
+        ParsedDocument parsedDocument = defaultMapper.parse(SourceToParse.source("test", "type1", "1", BytesReference
+                .bytes(XContentFactory.jsonBuilder()
+                    .startObject()
+                    .field("geofield", "41.12,-71.34")
+                    .endObject()),
+            XContentType.JSON));
+
+        ParseContext.Document indexableFields = parsedDocument.rootDoc();
+        assertThat(indexableFields.getFields("geofield"), arrayWithSize(2));
+        assertSuggestFields(indexableFields.getFields("geofield.analyzed"), 1);
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: Can you check that the field has the expected content?:

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java [hunk 8]
```diff
@@ -182,6 +184,274 @@ public void testParsingFailure() throws Exception {
...
+        ParsedDocument parsedDocument = defaultMapper.parse(SourceToParse.source("test", "type1", "1", BytesReference
+                .bytes(XContentFactory.jsonBuilder()
+                    .startObject()
+                    .field("completion", "suggestion")
+                    .endObject()),
+            XContentType.JSON));
+
+        ParseContext.Document indexableFields = parsedDocument.rootDoc();
+        assertSuggestFields(indexableFields.getFields("completion"), 1);
+        assertThat(indexableFields.getFields("completion.analyzed"), arrayWithSize(1));
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: Can you check that the field has the expected content?:

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java [hunk 9]
```diff
@@ -182,6 +184,274 @@ public void testParsingFailure() throws Exception {
...
+                    .startObject("completion")
+                    .array("input","New York", "NY")
+                    .field("weight",34)
+                    .endObject()
+                    .endObject()),
+            XContentType.JSON));
+
+        ParseContext.Document indexableFields = parsedDocument.rootDoc();
+        assertSuggestFields(indexableFields.getFields("completion"), 2);
+        assertThat(indexableFields.getFields("completion.analyzed"), arrayWithSize(2));
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: Can you check that the field has the expected content?:

File: server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java [hunk 10]
```diff
@@ -182,6 +184,274 @@ public void testParsingFailure() throws Exception {
...
+                    .startObject("completion")
+                        .array("input","New York", "NY")
+                        .field("weight",34)
+                    .endObject()
+                    .endObject()),
+            XContentType.JSON));
+
+        ParseContext.Document indexableFields = parsedDocument.rootDoc();
+        assertSuggestFields(indexableFields.getFields("completion"), 2);
+        assertThat(indexableFields.getFields("completion.analyzed"), arrayWithSize(4));
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/CompletionFieldMapperTests.java]: Can you check that the field has the expected content?:

**Review by jimczi — COMMENTED** [review]
It looks good @pgomulka . I left some comments regarding the tests.

File: server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java [hunk 11]
```diff
@@ -471,14 +472,36 @@ public void parse(ParseContext context) throws IOException {
...
+    }
+
+    private Map<String, CompletionInputMetaData> getInputMapFromExternalValue(ParseContext context) {
+        Map<String, CompletionInputMetaData> inputMap;
+        if (isExternalValueOfClass(context, CompletionInputMetaData.class)) {
+            CompletionInputMetaData inputAndMeta = (CompletionInputMetaData) context.externalValue();
+            inputMap = Collections.singletonMap(inputAndMeta.inputField, inputAndMeta);
+        } else {
+            String fieldName = context.externalValue().toString();
+            inputMap = Collections.singletonMap(fieldName, new CompletionInputMetaData(fieldName, Collections.<String, Set<CharSequence>>emptyMap(), 1));
```
[the remark this answers is not in the document]
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java]: absolutely, will simplify another place in that file to use jdk8 type inference as well

File: server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java [hunk 12]
```diff
@@ -570,13 +593,20 @@ private void parse(ParseContext parseContext, Token token, XContentParser parser
     }
 
     static class CompletionInputMetaData {
+        public final String inputField;
```
[the remark this answers is not in the document]
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/index/mapper/CompletionFieldMapper.java]: good suggestion, this contains the actual value of the input field, so should be more clear

**Comment by pgomulka** [comment]
@jimczi updated the tests and added an additional REST test cover scenarios I couldn't test in a junit test. Can you please have a look?

**Review by jimczi — APPROVED** [review]
LGTM, thanks @pgomulka

**Comment by pgomulka** [comment]
Thank you @jimczi

**Comment by pgomulka** [comment]
going to backport to v6.5.0

**Comment by pgomulka** [comment]
going to back port to v6.5.0
