### PR TITLE
SQL: JDBC: fix access to the Manifest for non-entry JAR URLs

### LINKED ISSUE #56759: SQL: Jdbc driver version detection fails on JBoss Wildfly
When loading the JDBC driver inside JBoss AP/Wildfly, the version discovery fails due to some issues with opening the jar.
```
Opening jar:file:/E:/wildfly-19.1.0.Final/modules/system/layers/base/org/elasticsearch/jdbc/main/x-pack-sql-jdbc-7.7.0.jar!/
```

The following URL, despite being returned by the AP itself when calling `conn.getInputStream`:

```java
URL url = SqlVersion.class.getProtectionDomain().getCodeSource().getLocation();
...
URLConnection conn = url.openConnection();
conn.setUseCaches(false);

try (JarInputStream jar = new JarInputStream(conn.getInputStream())) { <--
```

The underlying error seems to be:
```
Caused by: java.lang.IllegalArgumentException: Detected Elasticsearch JDBC jar but cannot retrieve its version at URLjar:file:/E:/tmp/wildfly/wildfly-19.1.0.Final/modules/system/layers/base/org/elasticsearch/jdbc/main/x-pack-sql-jdbc-7.9.0-SNAPSHOT.jar!/
        at org.elasticsearch.jdbc@7.9.0-SNAPSHOT//org.elasticsearch.xpack.sql.client.ClientVersion.extractVersion(ClientVersion.java:87)
        at org.elasticsearch.jdbc@7.9.0-SNAPSHOT//org.elasticsearch.xpack.sql.client.ClientVersion.<clinit>(ClientVersion.java:71)
        ... 19 more
Caused by: java.io.IOException: no entry name specified
        at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:160)
        at org.elasticsearch.jdbc@7.9.0-SNAPSHOT//org.elasticsearch.xpack.sql.client.ClientVersion.extractVersion(ClientVersion.java:81)
        ... 20 more
```
Which is confusing. Probably the resource/jar handling inside the server is somewhat different causing the jar to not be opened correctly. Some small tests indicate that while the URL if modified can be opened, the jar manifest is missing.
So probably a different URL/approach need to be taken to get a hold of the manifest.

As a separate issue, we could consider not detecting a version as a warning and not an exception...

### PR DESCRIPTION
**Pull request by bpintea**
The JDBC driver will attempt to read its version from the Manifest file
embedded into its JAR. The URL pointing to the JAR can be provided in a
few ways.

So far, accessing the Manfiest was attempted by getting a URLConnection
out of the URL and then getting an input stream out of this connection.
For file JAR URLs, this only works however if the URL points to the
driver as a JAR file entry (i.e. `<sub-url>!/jdbc-driver.jar!/`). If
that's not the case, the JarURLConnection will throw an IOException.

This PR fixes that: in case the URL points to a JAR entry
(`jar:file:<path>/jdbc-driver.jar!/`), the manifest is read directly with
`JarURLConnection#getManifest()`.

Fixes #56759.

### CODE REVIEW

File: x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/VersionTests.java [hunk 1]
```diff
@@ -31,27 +31,74 @@ public void testInvalidVersion() {
...
         Manifest jdbcJarManifest = new Manifest();
         Attributes attributes = jdbcJarManifest.getMainAttributes();
         attributes.put(Attributes.Name.MANIFEST_VERSION, "1.0.0");
         attributes.put(new Attributes.Name("Change"), "abc");
-        attributes.put(new Attributes.Name("X-Compile-Elasticsearch-Version"), "1.2.3");
+        attributes.put(new Attributes.Name("X-Compile-Elasticsearch-Version"), versionString(parts));
 
         // create the jdbc driver file
-        try (JarOutputStream jdbc = new JarOutputStream(Files.newOutputStream(innerJarPath, StandardOpenOption.CREATE), jdbcJarManifest)) {}
+        try (JarOutputStream __ = new JarOutputStream(Files.newOutputStream(jarPath, StandardOpenOption.CREATE), jdbcJarManifest)) {}
```
Comment (astefan) [inline x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/VersionTests.java:61]: :-)

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java [hunk 2]
```diff
@@ -71,23 +72,36 @@
...
+                        JarURLConnection jarConn = (JarURLConnection) conn;
+                        if (jarConn.getEntryName() == null) { // the URL points to a JAR file
+                            manifest = jarConn.getManifest(); // in case of a fat JAR, this would return the outermost JAR's manifest
+                            break;
+                        }
+                    }
+                    try (JarInputStream jar = new JarInputStream(conn.getInputStream())) {
+                        manifest = jar.getManifest();
+                    }
+                } while (false);
```
Comment (astefan) [inline x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:98]: `do { } while (false)` or use a function with the same break conditions (but using `return` to "jump" at the end)?

File: x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/VersionTests.java [hunk 3]
```diff
@@ -31,27 +31,74 @@ public void testInvalidVersion() {
...
+        SqlVersion version = ClientVersion.extractVersion(fileUrl);
+
+        assertEquals(parts[0], version.major);
+        assertEquals(parts[1], version.minor);
+        assertEquals(parts[2], version.revision);
+        assertEquals(versionString(parts), version.version);
+    }
+
+    public void testVersionFromJar() throws IOException {
+        byte[] parts = {1, 2, 3};
```
Comment (astefan) [inline x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/VersionTests.java:80]: Why is this `{1, 2, 3}` and the previous test is `{0, 1, 2}`. It is relevant for these tests to have different versions to test? If not, and for the sake of using whatever versions, can you use a random value?

**Review by astefan — COMMENTED** [review]
Looks good. Appreciate the quick fix for the issue. Left few cosmetic comments.

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java [hunk 4]
```diff
@@ -71,23 +72,36 @@
...
+    // (1) a file URL: file:<path><FS separator><driver name>.jar
+    // (2) jar file URL pointing to a JAR file: jar:<sub-url><separator><driver name>.jar!/
+    // (3) jar file URL pointing to a JAR file entry (likely a fat JAR, but other types are possible): jar:<sub-url>!/driver name>.jar!/
     static SqlVersion extractVersion(URL url) {
+        Manifest manifest = null;
         String urlStr = url.toString();
         if (urlStr.endsWith(".jar") || urlStr.endsWith(".jar!/")) {
             try {
                 URLConnection conn = url.openConnection();
-                conn.setUseCaches(false);
```
Comment (matriv) [inline x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:79]: I think there was a reason for that, but can't remember. @astefan do you ?

**Review by matriv — COMMENTED** [review]
LGTM, left a comment about `setUseCaches(false)`

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 4 above)
Comment (astefan) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:79]: I didn't notice this change when I reviewed this. Good point.
I _think_ I added that because the temporary jars that were created during the test couldn't be cleaned-up properly. And I would keep the `setUseCaches(false)` as is. I was getting something like this:

```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\AppData\Local\Temp\org.elasticsearch.xpack.sql.client.VersionTests_123F282E30B0C58F-001\tempDir-002\foo.jar: java.nio.file.FileSystemException: C:\Users\AppData\Local\Temp\org.elasticsearch.xpack.sql.client.VersionTests_123F282E30B0C58F-001\tempDir-002\foo.jar: The process cannot access the file because it is being used by another process.
   C:\Users\AppData\Local\Temp\org.elasticsearch.xpack.sql.client.VersionTests_123F282E30B0C58F-001\tempDir-002: java.nio.file.DirectoryNotEmptyException: C:\Users\AppData\Local\Temp\org.elasticsearch.xpack.sql.client.VersionTests_123F282E30B0C58F-001\tempDir-002
   C:\Users\AppData\Local\Temp\org.elasticsearch.xpack.sql.client.VersionTests_123F282E30B0C58F-001: java.nio.file.DirectoryNotEmptyException: C:\Users\AppData\Local\Temp\org.elasticsearch.xpack.sql.client.VersionTests_123F282E30B0C58F-001
	at __randomizedtesting.SeedInfo.seed([123F282E30B0C58F]:0)
	at org.apache.lucene.util.IOUtils.rm(IOUtils.java:319)
	at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:216)
	at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Comment (costin) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:79]: Avoid file locking, at least on Windows.

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:98]: This section needs improving.
the `do {} while (false)` is unnecessary. The break can also be removed by checking if the manifest is still null before the try block:

```
if (url.getProtocol()...) {
}

if (manifest == null) {
 try (JarInputStream...)
}
```

Further more, if the entry is not-null what would be the returned manifest?
```
if (url.getProtocol().equals("jar")) {
   JarURLConnection jarConn = (JarURLConnection) conn;
   manifest = jarConn.getManifest(); <-- ? what would this return?

```

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 4 above)
Comment (costin) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:79]: Not sure why my previous comment doesn't show up but it's because it avoids file locking on Windows as it frees the stream early on.

**Review by costin — APPROVED** [review]
Left some comments regarding styling but looks good otherwise, thanks for the fast turnaround!

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 4 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java:79]: Good catch, thanks @matriv. It was unintentional. I've put it back.

File: x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/VersionTests.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/VersionTests.java]: Right, randomising it is a better idea. I've added that, thanks.

File: x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-client/src/main/java/org/elasticsearch/xpack/sql/client/ClientVersion.java]: > do { } while (false)

I thought this might raise some eyebrows. :-)

> or use a function with the same break conditions (but using return to "jump" at the end)?

I've turned the frame loop into a function. Hope this is what you were suggesting.

> the do {} while (false) is unnecessary.

Generally this avoids an unnecessary fetch&compare. 
But in this case if the manifest is still `null` (shouldn't, but if), `conn.getInputStream()` would raise an exception (vs. just returning the "null version").

> if the entry is not-null what would be the returned manifest?

If the entry is not null, it'd simply return the [outermost] JAR's manifest (since the entry can be any class, i.e. non a JAR). Let me know if I still didn't get your question, though.

File: x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/VersionTests.java (hunk 1 above)
Comment (bpintea) [reply x-pack/plugin/sql/sql-client/src/test/java/org/elasticsearch/xpack/sql/client/VersionTests.java:67]: Yeh, `_` is now a keyword (besides a common-ish practice to name unused vars :-) ). I just wanted to have the line within the line len limit and no extra line added.

**Review by costin — APPROVED** [review]

**Review by matriv — APPROVED** [review]
LGTM

**Comment by bpintea** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by astefan — APPROVED** [review]

**Comment by bpintea** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by bpintea** [comment]
@elasticmachine update branch
