### PR TITLE
EQL: Convert wildcards to LIKE in analyzer

### LINKED ISSUE #53104: EQL: Wildcard matching doesn't work
With the execution engine hooked in, it seems that wildcard queries do not match anything:

```
process where process.name == "*" 
```

return no results. Remove the wildcard match or make it exact and results start streaming in.

### PR DESCRIPTION
**Pull request by rw-access**
Addressing the comment thread from https://github.com/elastic/elasticsearch/pull/51558#discussion_r372419383.

Added ReplaceWildcards to the optimizer which detects the `== "wild*card*"` or `!= "wild*card*"` patterns and replaces with LIKE.

~This is branched from #51886, so only the last commit is relevant.~

Update: Resolves #53104

### CODE REVIEW

**Review by costin — CHANGES_REQUESTED** [review]
First pass.
The PR will be easier to complete after https://github.com/elastic/elasticsearch/issues/51929.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java [hunk 1]
```diff
@@ -51,6 +61,60 @@ private LogicalPlan verify(LogicalPlan plan) {
...
     }
 
+    private static class ReplaceWildcards extends AnalyzeRule<Filter> {
+
+        private static boolean isWildcard(Expression expr) {
+            if (expr instanceof Literal) {
+                Literal l = (Literal) expr;
+                if (l.value() instanceof String) {
+                    String s = (String) l.value();
+                    return s.contains("*");
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java]: Would be possible to add more tests that also look at scenarios involving escape characters and [all types of string that eql supports](https://eql.readthedocs.io/en/latest/query-guide/basic-syntax.html#strings)?
Can the `*` be escaped? If so, we should have a test covering this case.

**Review by astefan — COMMENTED** [review]
Left a comment regarding tests.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java [hunk 2]
```diff
@@ -42,4 +60,110 @@ private LogicalPlan verify(LogicalPlan plan) {
...
+                                 .replace("_", escape + "_")
+                                 .replace("*", "%");
+
+            return new LikePattern(likeString, escape);
+        }
+
+        @Override
+        protected LogicalPlan rule(Filter filter) {
+            return filter.transformExpressionsUp(e -> {
+                // expr == "wildcard*phrase"
```
[the remark this answers is not in the document]
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java]: yeah, it is valid grammar, but since it's not `==` or `!=`, this will just be a lexicographical comparison

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java [hunk 3]
```diff
@@ -42,4 +60,110 @@ private LogicalPlan verify(LogicalPlan plan) {
...
+                if (e instanceof Equals) {
+                    Equals eq = (Equals) e;
+
+                    if (isWildcard(eq.right())) {
+                        String wcString = (String) ((Literal) eq.right()).value();
+                        e = new Like(e.source(), eq.left(), toLikePattern(wcString));
+                    }
+                }
+
+                // expr != "wildcard*phrase"
```
[the remark this answers is not in the document]
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java]: I doubt that the functionality has been leveraged by many users, but if a wildcard string is on the left instead of the right, then it's just a normal, non-wildcard comparison and will check for equality or inequality depending on the operator.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java (hunk 1 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java]: yeah, I can add more tests. And there's no escape for `*`. But if you want to perform an exact (+/- case sensitivity) comparison, you can put the wildcard on the left (https://github.com/elastic/elasticsearch/pull/51901#discussion_r375360920). Whether this functionality is good or not is a fair question, and I think it's fair to change this because I doubt any users are aware of the workaround.
```
field == "*wildcard*" <==> field LIKE "%wildcard%"
"*wildcard*" == field <==> field EQ "%wildcard%"
```

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (matriv) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java]: That seems a bit strange to imho. I'd find it more intuitive if `==` and `!=` would work in the same way regardless of right/left positioning of the args.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java (hunk 1 above)
Comment (astefan) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java]: To be honest, I find this more like a bug, rather than feature (that implies an workaround).
A == B and B == A should be equivalent imo. Equality is not a predicate (like `LIKE`) where a certain element sits on the right and another one sits on the left and they are not interchangeable.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java]: That would mean the operators are not consistent since `==` would expand the wildcard while `>` & co would compare against it...

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/analysis/Analyzer.java]: >if a wildcard string is on the left instead of the right, then it's just a normal, non-wildcard comparison and will check for equality or inequality depending on the operator.

Which would make `==` and `!=` non commutative which is a bug.

**Comment by costin** [comment]
I think it's worth discussing the feature and then figure out the implementation for it.

1. if `==` and `!=` are overloaded with the special string with wildcard, the behavior should be consistent with the existing rules.
2. the overloading is dropped in favor of a dedicated construct (`LIKE`) which can introduce its own semantics and syntax. The downside here is backwards compatibility.

**Comment by rw-access** [comment]
Agreed that wildcards should be made commutative. I don't think we should add a new construct like LIKE just yet. In the future, I think it could make sense, after we go through the usual deprecation steps.

I think the main question I have is -- should this be a separate rule in the grammar, or should it be handled in the analyzer?

**Comment by costin** [comment]
If the wildcard can be picked up by the parser through a dedicated rule, I would opt for that.
However I don't see an easy way to do this in the grammar nor the parser itself and considering its commutative nature I would handle it in an optimizer rule.

@andrei how close are you to moving the optimizer rules in?

**Comment by astefan** [comment]
> @andrei how close are you to moving the optimizer rules in?

@costin https://github.com/elastic/elasticsearch/pull/52172

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java [hunk 4]
```diff
@@ -33,6 +43,7 @@ public LogicalPlan optimize(LogicalPlan verified) {
                 new BooleanSimplification(),
                 new BooleanLiteralsOnTheRight(),
                 // needs to occur before BinaryComparison combinations
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java]: The comment seems incorrect as it referred to `PropagateEquals`

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java [hunk 5]
```diff
@@ -45,4 +56,51 @@ public LogicalPlan optimize(LogicalPlan verified) {
...
+            if (expr.foldable()) {
+                Object value = expr.fold();
+                return value instanceof String && value.toString().contains("*");
+            }
+            return false;
+        }
+
+        private static LikePattern toLikePattern(String s) {
+            // pick a character that is guaranteed not to be in the string, because it isn't allowed to escape itself
+            char escape = 1;
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java]: Why not 0?

**Review by costin — APPROVED** [review]
LGTM

**Comment by costin** [comment]
elasticsearch-ci/2 is failing due to a checkstyle violation.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java (hunk 4 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java]: where should ReplaceWildcards() be moved to?

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java (hunk 5 above)
Comment (rw-access) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java]: Looks like there's explicit handling for `\0`
https://github.com/elastic/elasticsearch/blob/bf317e8c4eb301f5ea9ff17a3d9595ae177cfbaf/x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/StringUtils.java#L104
