### PR TITLE
Handle all exceptions in data nodes can match

### LINKED ISSUE #104994: Unsupported Operation Exception querying Frozen Tier data
### Elasticsearch Version

8.12.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

I have an ILM policy with 10 days hot, 80 days frozen. Getting partial results for certain queries. Bounding the query with a date range filter to just hot data produces no errors.

### Steps to Reproduce

For context, an excerpt of the mapping:
```
{
    "dynamic" : "strict",
    "properties" : {
      "@timestamp" : {
        "type" : "date",
        "format" : "date_optional_time||epoch_millis"
      },
      "request_id" : {
        "type" : "keyword",
        "index" : true
      },
      "customer_id" : {
        "type" : "keyword",
        "index" : true
      },
      "ip_address" : {
        "type" : "ip",
        "index" : true
      },
...
}
```

If I do an non-time bounded query, as simple as the following, I get partial results:

```
GET /<my-data-stream>/_search
{
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "customer_id": {
                            "value": "some_value"
                        }
                    }
                },
                {
                    "term": {
                        "ip_address": {
                            "value": "10.0.0.0/32"
                        }
                    }
                }
            ]
        }
    },
    "size": 5,
    "sort": [
        {
            "request_id": {
                "order": "desc"
            }
        }
    ]
}
```

The response metadata shows:
```
    "total": 114,
    "successful": 92,
    "skipped": 0,
    "failed": 22,
```

And the failed section shows many of these for difference partial indices that are in the frozen tier (excerpt):
```
      {
        "shard": 0,
        "index": "partial-.<index-name>-2024.01.19-000006",
        "node": "<node>",
        "reason": {
          "type": "unsupported_operation_exception",
          "reason": "unsupported_operation_exception: null"
        }
      },
```

### Logs (if relevant)

```
[instance-0000000016]
 TransportSearchAction shard failure (partial results response) org.elasticsearch.action.search.ShardSearchFailure: null at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:547) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(Abst
ractSearchAsyncAction.java:476) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:332) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticse
arch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:27) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
 ~[elasticsearch-8.12.0.jar:?]
 at org.el
asticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:553) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1718) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1435) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:475) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:462) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:453) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.executeResponseHandler(InboundHandler.java:145) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:122) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:96) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:825) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:124) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:96) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:61) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.channelRead(Netty4MessageInboundHandler.java:48) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
 at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
 at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1383) ~[?:?]
 at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1246) ~[?:?]
 at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1295) ~[?:?]
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[?:?]
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[?:?]
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[?:?]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) ~[?:?]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) ~[?:?]
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
 at java.lang.Thread.run(Thread.java:1583) ~[?:?]
 Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: unsupported_operation_exception: null at org.elasticsearch.index.engine.frozen.RewriteCachingDirectoryReader$RewriteCachingLeafReader.terms(RewriteCachingDirectoryReader.java:184) ~[?:?]
 at org.apache.lucene.index.FilterLeafReader.terms(FilterLeafReader.java:415) ~[lucene-core-9.9.1.jar:?]
 at org.apache.lucene.index.FilterLeafReader.terms(FilterLeafReader.java:415) ~[lucene-core-9.9.1.jar:?]
 at org.elasticsearch.search.internal.FieldUsageTrackingDirectoryReader$FieldUsageTrackingLeafReader.terms(FieldUsageTrackingDirectoryReader.java:160) ~[elasticsearch-8.12.0.jar:?]
 at org.apache.lucene.index.MultiTerms.getTerms(MultiTerms.java:73) ~[lucene-core-9.9.1.jar:?]
 at org.elasticsearch.search.sort.FieldSortBuilder.getMinMaxOrNull(FieldSortBuilder.java:577) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.search.SearchService.canMatch(SearchService.java:1662) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$3(SearchService.java:533) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.ActionListenerImplementations$DelegatingFailureActionListener.onResponse(ActionListenerImplementations.java:212) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.search.SearchService.lambda$rewriteAndFetchShardRequest$18(SearchService.java:1725) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.index.shard.IndexShard.ensureShardSearchActive(IndexShard.java:3967) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.search.SearchService.lambda$rewriteAndFetchShardRequest$19(SearchService.java:1725) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:109) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:77) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.search.SearchService.rewriteAndFetchShardRequest(SearchService.java:1731) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:526) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.search.SearchTransportService.lambda$registerRequestHandler$7(SearchTransportService.java:435) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$1.doRun(SecurityServerTransportInterceptor.java:565) ~[?:?]
 at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$2.onResponse(SecurityServerTransportInterceptor.java:602) ~[?:?]
 at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler$2.onResponse(SecurityServerTransportInterceptor.java:599) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:623) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:617) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.ShardSearchRequestInterceptor.intercept(ShardSearchRequestInterceptor.java:24) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:621) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:617) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.IndicesAliasesRequestInterceptor.intercept(IndicesAliasesRequestInterceptor.java:124) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:621) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:617) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.UpdateRequestInterceptor.intercept(UpdateRequestInterceptor.java:27) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:621) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:617) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.FieldAndDocumentLevelSecurityRequestInterceptor.intercept(FieldAndDocumentLevelSecurityRequestInterceptor.java:79) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.SearchRequestInterceptor.intercept(SearchRequestInterceptor.java:21) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:621) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:617) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.BulkShardRequestInterceptor.intercept(BulkShardRequestInterceptor.java:85) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:621) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:617) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.SearchRequestCacheDisablingInterceptor.intercept(SearchRequestCacheDisablingInterceptor.java:53) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:621) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:617) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.DlsFlsLicenseRequestInterceptor.intercept(DlsFlsLicenseRequestInterceptor.java:106) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:621) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$1.onResponse(AuthorizationService.java:617) ~[?:?]
 at org.elasticsearch.xpack.security.authz.interceptor.ResizeRequestInterceptor.intercept(ResizeRequestInterceptor.java:98) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService.runRequestInterceptors(AuthorizationService.java:617) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService.handleIndexActionAuthorizationResult(AuthorizationService.java:602) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorizeAction$13(AuthorizationService.java:505) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:1028) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService$AuthorizationResultListener.onResponse(AuthorizationService.java:994) ~[?:?]
 at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.xpack.security.authz.RBACEngine.authorizeIndexAction(RBACEngine.java:379) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService.authorizeAction(AuthorizationService.java:498) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService.maybeAuthorizeRunAs(AuthorizationService.java:435) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService.lambda$authorize$3(AuthorizationService.java:322) ~[?:?]
 at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:178) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.xpack.security.authz.RBACEngine.lambda$resolveAuthorizationInfo$0(RBACEngine.java:151) ~[?:?]
 at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRoles$4(CompositeRolesStore.java:194) ~[?:?]
 at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.lambda$getRole$5(CompositeRolesStore.java:212) ~[?:?]
 at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$0(RoleReferenceIntersection.java:49) ~[?:?]
 at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.support.GroupedActionListener.onResponse(GroupedActionListener.java:56) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.buildRoleFromRoleReference(CompositeRolesStore.java:292) ~[?:?]
 at org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.lambda$buildRole$1(RoleReferenceIntersection.java:53) ~[?:?]
 at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
 at org.elasticsearch.xpack.core.security.authz.store.RoleReferenceIntersection.buildRole(RoleReferenceIntersection.java:53) ~[?:?]
 at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRole(CompositeRolesStore.java:210) ~[?:?]
 at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.getRoles(CompositeRolesStore.java:187) ~[?:?]
 at org.elasticsearch.xpack.security.authz.RBACEngine.resolveAuthorizationInfo(RBACEngine.java:147) ~[?:?]
 at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:338) ~[?:?]
 at org.elasticsearch.xpack.security.transport.ServerTransportFilter.lambda$inbound$1(ServerTransportFilter.java:112) ~[?:?]
 at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.xpack.security.authc.AuthenticatorChain.authenticate(AuthenticatorChain.java:93) ~[?:?]
 at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:262) ~[?:?]
 at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:199) ~[?:?]
 at org.elasticsearch.xpack.security.transport.ServerTransportFilter.authenticate(ServerTransportFilter.java:125) ~[?:?]
 at org.elasticsearch.xpack.security.transport.ServerTransportFilter.inbound(ServerTransportFilter.java:103) ~[?:?]
 at org.elasticsearch.xpack.security.transport.SecurityServerTransportInterceptor$ProfileSecuredRequestHandler.messageReceived(SecurityServerTransportInterceptor.java:629) ~[?:?]
 at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:288) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.handleRequest(InboundHandler.java:273) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:115) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:96) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:825) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:124) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:96) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:61) ~[elasticsearch-8.12.0.jar:?]
 at org.elasticsearch.transport.netty4.Netty4MessageInboundHandler.channelRead(Netty4MessageInboundHandler.java:48) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
 at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
 at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1383) ~[?:?]
 at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1246) ~[?:?]
 at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1295) ~[?:?]
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[?:?]
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[?:?]
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[?:?]
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[?:?]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[?:?]
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[?:?]
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[?:?]
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[?:?]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) ~[?:?]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) ~[?:?]
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[?:?]
 at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[?:?]
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
 at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### PR DESCRIPTION
**Pull request by javanna**
During the can match phase, prior to the query phase, we may have exceptions that are returned back to the coordinating node, handled gracefully as if the shard returned canMatch=true.

During the query phase, we perform an additional rewrite and can match phase to eventually shortcut the query phase for the shard. That needs to handle exceptions as well. Currently, an exception there causes shard failures, while we should rather go ahead and execute the query on the shard.

The issue is addressed by folding the exception handling in SearchService#canMatch, rather than leaving it to its consumers. There isn't a single usecase where a failure on can match does not translate to canMatch=true (besides the bug that this fix is addressing). This has the nice benefit that data nodes will stop sending back exceptions for the coordinator to handle, which is unnecessary given that the handling is always the same.

Closes #104994

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 1]
```diff
@@ -1645,39 +1648,96 @@ public void canMatch(CanMatchNodeRequest request, ActionListener<CanMatchNodeRes
...
     public CanMatchShardResponse canMatch(ShardSearchRequest request) throws IOException {
-        return canMatch(request, true);
+        ReaderContext readerContext = findReaderContext(request.readerId(), request);
+        IndexService indexService = indicesService.indexServiceSafe(request.shardId().getIndex());
+        try (CanMatchContext canMatchContext = new CanMatchContext(request, indexService, readerContext, getKeepAlive(request))) {
+            return canMatch(canMatchContext, true);
+        }
+    }
+
+    static class CanMatchContext implements Releasable {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:1658]: most of the changes in SearchService have a simple goal: make the canMatch method unit testable. Given how difficult it is to recreate a SearchService instance (no wonder it requires spinning up a node like we do in SearchServiceTests), I went for making the method static and have some extensible way to provide what it needs as an argument.

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 2]
```diff
@@ -553,19 +554,21 @@ public void executeQueryPhase(ShardSearchRequest request, SearchShardTask task,
...
-                    canMatchResp = canMatch(clone, false);
+                CanMatchShardResponse canMatchResp;
+                ShardSearchRequest clone = new ShardSearchRequest(orig);
+                try (CanMatchContext canMatchContext = new CanMatchContext(clone, indexService, readerContext, getKeepAlive(request))) {
+                    canMatchResp = canMatch(canMatchContext, false);
                 } catch (Exception exc) {
-                    l.onFailure(exc);
-                    return;
+                    // if can_match throws for some reason, we go ahead with the query phase
+                    canMatchResp = new CanMatchShardResponse(true, null);
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:568]: I added a targeted catch exception for sorting related exceptions, but we still need here a broader one. Based on my proposal below to handle all exceptions in the can match method, perhaps this can go away.

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 3]
```diff
@@ -1687,36 +1747,33 @@ private CanMatchShardResponse canMatch(ShardSearchRequest request, boolean check
...
-                    FieldSortBuilder sortBuilder = FieldSortBuilder.getPrimaryFieldSortOrNull(request.source());
-                    minMax = sortBuilder != null ? FieldSortBuilder.getMinMaxOrNull(context, sortBuilder) : null;
-                } else {
-                    minMax = null;
+                    try {
+                        FieldSortBuilder sortBuilder = FieldSortBuilder.getPrimaryFieldSortOrNull(canMatchContext.request.source());
+                        final MinAndMax<?> minMax = sortBuilder != null ? FieldSortBuilder.getMinMaxOrNull(context, sortBuilder) : null;
+                        return new CanMatchShardResponse(true, minMax);
+                    } catch (Exception e) {
+                        return new CanMatchShardResponse(true, null);
```
[the remark this answers is not in the document]
Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: I have now replaced the catch with a broader one and removed the specific one that I had initially added.

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 2 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: I removed this, given that exception handling is now in callers code.

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 4]
```diff
@@ -1619,6 +1634,7 @@ public void canMatch(CanMatchNodeRequest request, ActionListener<CanMatchNodeRes
         final List<CanMatchNodeResponse.ResponseOrFailure> responses = new ArrayList<>(shardLevelRequests.size());
         for (var shardLevelRequest : shardLevelRequests) {
             try {
+                // TODO remove the exception handling as it's now in canMatch itself
                 responses.add(new CanMatchNodeResponse.ResponseOrFailure(canMatch(request.createShardSearchRequest(shardLevelRequest))));
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:1638]: I left this for a follow-up as I need to add a new transport version and bw comp handling.

File: server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java [hunk 5]
```diff
@@ -0,0 +1,3126 @@
...
+ * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
+ * or more contributor license agreements. Licensed under the "Elastic License
+ * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
+ * Public License v 1"; you may not use this file except in compliance with, at
+ * your election, the "Elastic License 2.0", the "GNU Affero General Public
+ * License v3.0 only", or the "Server Side Public License, v 1".
+ */
+package org.elasticsearch.search;
+
+import org.apache.lucene.index.DirectoryReader;
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java:11]: The diff is hard to follow, but I just renamed the existing SearchServiceTests to SearchServiceSingleNodeTests, and added a new test class with unit tests only, which I called SearchServiceTests

File: x-pack/plugin/frozen-indices/src/internalClusterTest/java/org/elasticsearch/index/engine/frozen/FrozenIndexTests.java [hunk 6]
```diff
@@ -469,27 +468,25 @@ public void testCanMatch() throws IOException {
...
+                        1,
+                        AliasFilter.EMPTY,
+                        1f,
+                        -1,
+                        null,
+                        withoutCommitId,
+                        null
+                    )
+                ).canMatch()
+            );
```
Comment (javanna) [inline x-pack/plugin/frozen-indices/src/internalClusterTest/java/org/elasticsearch/index/engine/frozen/FrozenIndexTests.java:489]: the previous version of the assertion came from retrying PIT requests on search context missing. I don't think it's a good reason to make can match fail on it though, hence I adjusted the test. Retries will be attempted in the query phase.

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 7]
```diff
@@ -1630,42 +1646,102 @@ public void canMatch(CanMatchNodeRequest request, ActionListener<CanMatchNodeRes
...
+                    QueryRewriteContext queryRewriteContext = canMatchContext.getQueryRewriteContext(indexService);
+                    if (queryStillMatchesAfterRewrite(canMatchContext.request, queryRewriteContext) == false) {
                         return new CanMatchShardResponse(false, null);
                     }
                     searcher = readerContext.acquireSearcher(Engine.CAN_MATCH_SEARCH_SOURCE);
                 } catch (SearchContextMissingException e) {
-                    final String searcherId = request.readerId().getSearcherId();
+                    final String searcherId = canMatchContext.request.readerId().getSearcherId();
                     if (searcherId == null) {
                         throw e;
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:1736]: I know we're in a big `try ...` block here but would it make sense to return `CanMatchShardResponse(true ...)` here directly ?

Perhaps a personal preference only so feel free to ignore but it'd aid with readability as we could stop reading this method here as opposed to scrolling to the end to see what's going to happen in the `catch (Exception ...)` block

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 8]
```diff
@@ -1630,42 +1646,102 @@ public void canMatch(CanMatchNodeRequest request, ActionListener<CanMatchNodeRes
...
+                        canMatchContext.getQueryRewriteContext(canMatchContext.indexService)
+                    ) == false) {
                         return new CanMatchShardResponse(false, null);
                     }
-                    IndexShard indexShard = indexService.getShard(request.shardId().getId());
-                    final Engine.SearcherSupplier searcherSupplier = indexShard.acquireSearcherSupplier();
+                    final Engine.SearcherSupplier searcherSupplier = canMatchContext.getShard().acquireSearcherSupplier();
                     if (searcherId.equals(searcherSupplier.getSearcherId()) == false) {
                         searcherSupplier.close();
                         throw e;
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/search/SearchService.java:1747]: Same as before, perhaps return CanMatchShardResponse(true ...) here directly ?

File: server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java (hunk 5 above)
Comment (andreidan) [reply server/src/test/java/org/elasticsearch/search/SearchServiceSingleNodeTests.java:11]: Thanks for the review aid here

**Review by andreidan — APPROVED** [review]
Thanks for fixing this Luca. 

Left a couple of minor, optional, suggestions.

**Review by original-brownbear — APPROVED** [review]
LGTM, would have been nice to do this without the new context class but I see the point :) but :crossed_fingers:  I guess this goes away somewhat shortly anyway :)

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 7 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:1736]: that's a good point. Will change this,

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 8 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/SearchService.java:1747]: yes
