### PR TITLE
Remove _primary and _replica shard preferences

### LINKED ISSUE #26335: Should search preference _primary take primary relocation target into account?
When using the search preference `_primary`, and executing a search on a cluster where a concerned primary is about to complete relocation, it's possible that the search for that primary will fail, as it will hit the primary relocation source just when the relocation is completed and the source shard is shut down. My question is:

Should the  search preference `_primary` take the primary relocation target into account?
Put differently, should `OperationRouting.preferenceActiveShardIterator(...)` return the primary relocation target as backup when specifying `_primary` preference?

Note that the default search preference always takes relocation targets into account (and puts them last together with the "regular" initializing shards).

Related question:

Should the search preference `_replica` also take replica relocation targets into account? 

More background to this:

There was a test failure of SearchWhileCreatingIndexIT which illustrates the issue:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/4012/consoleFull

### PR DESCRIPTION
**Pull request by dnhatn**
The shard preference `_primary`, `_replica` and its variants were useful
for the asynchronous replication. However, with the current impl, they
are no longer useful and should be removed.

Closes #26335

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/cluster/structure/RoutingIteratorTests.java [hunk 1]
```diff
@@ -442,57 +443,15 @@ public void testReplicaShardPreferenceIters() throws Exception {
...
-        assertThat(routing.shardId().id(), anyOf(equalTo(0), equalTo(1)));
-        assertFalse(routing.primary());
-        // finally the primary
-        routing = iter.nextOrNull();
-        assertThat(routing.shardId().id(), anyOf(equalTo(0), equalTo(1)));
-        assertTrue(routing.primary());
+        String[] removedPreferences = {"_primary", "_primary_first", "_replica", "_replica_first"};
+        for (String pref : removedPreferences) {
+            try{
+                operationRouting.searchShards(clusterState, new String[]{"test"}, null, pref);
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/cluster/structure/RoutingIteratorTests.java]: This can be replaced with `expectThrows`.

File: core/src/test/java/org/elasticsearch/index/translog/TruncateTranslogIT.java [hunk 2]
```diff
@@ -210,7 +211,10 @@ public void testCorruptTranslogTruncation() throws Exception {
         logger.info("--> starting the replica node to test recovery");
         internalCluster().startNode();
         ensureGreen("test");
-        assertHitCount(client().prepareSearch("test").setPreference("_replica").setQuery(matchAllQuery()).get(), numDocsToKeep);
+        for(String node : internalCluster().nodesInclude("test")){
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/index/translog/TruncateTranslogIT.java]: Can you add extra spacing like:

```
for( -> for (
)){ -> )) {
```

Your IDE can help with this.

File: core/src/test/java/org/elasticsearch/index/translog/TruncateTranslogIT.java [hunk 3]
```diff
@@ -308,7 +312,9 @@ public void testCorruptTranslogTruncationOfReplica() throws Exception {
         logger.info("--> starting the replica node to test recovery");
         internalCluster().startNode();
         ensureGreen("test");
-        assertHitCount(client().prepareSearch("test").setPreference("_replica").setQuery(matchAllQuery()).get(), totalDocs);
+        for(String node : internalCluster().nodesInclude("test")){
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/index/translog/TruncateTranslogIT.java]: Extra spacing here:

```
for( -> for (
)){ -> )) {
```

File: core/src/test/java/org/elasticsearch/index/translog/TruncateTranslogIT.java [hunk 4]
```diff
@@ -308,7 +312,9 @@ public void testCorruptTranslogTruncationOfReplica() throws Exception {
...
+            assertHitCount(client().prepareSearch("test").setPreference("_only_nodes:"+node).setQuery(matchAllQuery()).get(), totalDocs);
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/index/translog/TruncateTranslogIT.java]: Spacing here:

```
:"+node -> :" + node
```

File: core/src/test/java/org/elasticsearch/search/basic/SearchWhileCreatingIndexIT.java [hunk 5]
```diff
@@ -93,8 +102,13 @@ private void searchWhileCreatingIndex(boolean createIndex, int numberOfReplicas)
             status = client().admin().cluster().prepareHealth("test").get().getStatus();
             internalCluster().ensureAtLeastNumDataNodes(numberOfReplicas + 1);
         }
-        SearchResponse searchResponse = client().prepareSearch("test").setQuery(QueryBuilders.termQuery("field", "test")).execute().actionGet();
-        assertHitCount(searchResponse, 1);
+
+        for(String node : internalCluster().nodesInclude("test")){
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/search/basic/SearchWhileCreatingIndexIT.java]: Spacing here:

```
for( -> for (
)){ -> )) {
```

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java [hunk 6]
```diff
@@ -227,17 +231,15 @@ public void testNewReplicasWork() throws Exception {
...
-            int foundHits1 = (int) XContentMapValues.extractValue("hits.total", responseBody);
-
-            responseBody = toMap(client().performRequest("GET", "/" + index + "/_search",
-                Collections.singletonMap("preference", "_replica")));
-            assertNoFailures(responseBody);
-            int foundHits2 = (int) XContentMapValues.extractValue("hits.total", responseBody);
-            assertEquals(foundHits1, foundHits2);
-            // TODO: do something more with the replicas! index?
+            Set<Integer> counts = new HashSet<>();
+            for(String node : dataNodes(index, client())){
```
Comment (jasontedor) [inline qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: Spacing here:

```
for( -> for (
)){ -> )) {
```

File: qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java [hunk 7]
```diff
@@ -227,17 +231,15 @@ public void testNewReplicasWork() throws Exception {
...
+                Map<String, Object> responseBody = toMap(client().performRequest("GET", "/" + index + "/_search",
+                    Collections.singletonMap("preference", "_only_nodes:"+node)));
```
Comment (jasontedor) [inline qa/full-cluster-restart/src/test/java/org/elasticsearch/upgrades/FullClusterRestartIT.java]: Spacing here:

```
:"+node -> :" + node
```

File: qa/mixed-cluster/src/test/java/org/elasticsearch/backwards/IndexingIT.java [hunk 8]
```diff
@@ -249,9 +246,10 @@ public void testSeqNoCheckpoints() throws Exception {
             updateIndexSetting(index, Settings.builder().put("index.number_of_replicas", 1));
             ensureGreen();
             assertOK(client().performRequest("POST", index + "/_refresh"));
-            // the number of documents on the primary and on the recovered replica should match the number of indexed documents
-            assertCount(index, "_primary", numDocs);
-            assertCount(index, "_replica", numDocs);
+
+            for(Shard shard : buildShards(index, nodes, newNodeClient)){
```
Comment (jasontedor) [inline qa/mixed-cluster/src/test/java/org/elasticsearch/backwards/IndexingIT.java]: Spacing:

```
for( -> for (
)){ -> )) {
```

**Review by jasontedor — COMMENTED** [review]
I left some comments. We will also separately need to deprecate these preferences in the 6.x branch and this PR needs a breaking changes note in the migration docs for 7.0.0.

**Comment by dnhatn** [comment]
@jasontedor, I have addressed your comments. Please have a look. Thank you.

File: docs/reference/migration/migrate_7_0/cluster.asciidoc [hunk 9]
```diff
@@ -11,3 +11,6 @@ cluster names may no longer contain `:`.
 The default value for the `wait_for_active_shards` parameter of the open index API
 is changed from 0 to 1, which means that the command will now by default wait for all
 primary shards of the opened index to be allocated.
+
+==== shard preferences `_primary`, `_primary_first`, `_replica`, and `_replica_first` are removed
```
Comment (jasontedor) [inline docs/reference/migration/migrate_7_0/cluster.asciidoc]: Nit: capitalize `shard` here as it's a section title.

File: core/src/test/java/org/elasticsearch/search/preference/SearchPreferenceIT.java [hunk 10]
```diff
@@ -67,7 +66,7 @@ public void testStopOneNodePreferenceWithRedState() throws InterruptedException,
         refresh();
         internalCluster().stopRandomDataNode();
         client().admin().cluster().prepareHealth().setWaitForStatus(ClusterHealthStatus.RED).execute().actionGet();
-        String[] preferences = new String[] {"_primary", "_local", "_primary_first", "_prefer_nodes:somenode", "_prefer_nodes:server2", "_prefer_nodes:somenode,server2"};
+        String[] preferences = new String[] {"_local", "_prefer_nodes:somenode", "_prefer_nodes:server2", "_prefer_nodes:somenode,server2"};
```
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/search/preference/SearchPreferenceIT.java]: Nit: `[] {` -> `[]{`.

**Review by jasontedor — COMMENTED** [review]
Two more nits and it looks good.

**Comment by jasontedor** [comment]
@dnhatn Please add an area label, a type label, and version labels to this PR.

**Comment by jasontedor** [comment]
@dnhatn I don’t think this should have the deprecation label.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by dnhatn** [comment]
Thanks @jasontedor.

**Comment by yznima** [comment]
@dnhatn 

> The shard preference _primary, _replica and its variants were used for the asynchronous replication.

Based on the PR message, I assume that the replication has been asynchronous at some previous version. Is there a specific version or PR that the replication model has been changed in?
