### PR TITLE
Fix race in ShardFollowTaskReplicationTests

### LINKED ISSUE #127680: [CI] ShardFollowTaskReplicationTests testChangeFollowerHistoryUUID failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8021 / ubuntu-2004_platform-support-unix](https://gradle-enterprise.elastic.co/s/mz2a5fsiibc3a)
- [elasticsearch-pull-request #70242 / part-2](https://gradle-enterprise.elastic.co/s/puojjzkcu6khy)
- [elasticsearch-pull-request #70194 / part-2](https://gradle-enterprise.elastic.co/s/mdlvabgwld4jm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ccr:test" --tests "org.elasticsearch.xpack.ccr.action.ShardFollowTaskReplicationTests.testChangeFollowerHistoryUUID" -Dtests.seed=7FF94D6CE6CB7B86 -Dtests.locale=mn-MN -Dtests.timezone=Pacific/Pohnpei -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ccr.action.ShardFollowTaskReplicationTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testChangeFollowerHistoryUUID),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: shard [test][0], node[s0], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[INITIALIZING], a[id=43gDJAAAQAClXah7AAAAAA], unassigned_info[[reason=REINITIALIZED], at[2025-05-04T05:37:05.095Z], delayed=false, allocation_status[no_attempt]], failed_attempts[0] is not a primary shard in primary mode
```

**Issue Reasons:**
- [main] 3 failures in test testChangeFollowerHistoryUUID (0.9% fail rate in 329 executions)
- [main] 2 failures in step part-2 (1.9% fail rate in 104 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.9% fail rate in 103 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by burqen**
Race:
Test main thread will replace primary on follower such that historyUUID doesn't match with leader anymore. There is a window when the primary is INITIALIZING.
```
String oldHistoryUUID = followerGroup.getPrimary().getHistoryUUID();
// Start window
followerGroup.reinitPrimaryShard();
followerGroup.getPrimary().store().bootstrapNewHistory();
recoverShardFromStore(followerGroup.getPrimary());
// End window
String newHistoryUUID = followerGroup.getPrimary().getHistoryUUID();
```
If ShardFollowNodeTask executes the BulkShardOperationsRequest in this window it will get an assertion error instead of the expected "unexpected history uuid" exception. The assertion error comes from `IndexShard.assertPrimaryMode`:
```
private boolean assertPrimaryMode() {
    assert shardRouting.primary() && replicationTracker.isPrimaryMode()
        : ... is not a primary shard in primary mode";
    return true;
}
```

We avoid the race, or rather, allow the race by treating this assertion error as another manifestation of the expected behavior, namely that the
 bulk request fails.

Changes
- ReplicationAction in test suite now treat AssertionError as RuntimeException and forward it to listener instead of failing with an uncaught exception.
- ShardFollowTaskReplicationTests treat the assertion error "is not a primary shard in primary mode" as an acceptable cause.
- Test removed from muted list

Closes https://github.com/elastic/elasticsearch/issues/127680

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java [hunk 1]
```diff
@@ -679,6 +679,8 @@ public void execute() {
                     TimeValue.timeValueMillis(20),
                     TimeValue.timeValueSeconds(60)
                 ).execute();
+            } catch (AssertionError e) {
+                listener.onFailure(new RuntimeException(e.getMessage(), e));
```
Comment (inespot) [inline test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java]: Let me know if you disagree, but this change feels somewhat broad and slightly risky. Putting the `AssertionError` handling on `ESIndexLevelReplicationTestCase`’s `ReplicationAction` affects every test that extends that base class, not just CCR. While this is not technically muting the assertion error per se, it does change an assertion failure into a listener `onFailure`, which can look like an ordinary replication error. I’m worried that could make real bugs harder to spot, or confuse tests that already expect failures on other paths. But maybe there is precedent for this?

If not, could we somehow narrow the scope of this fix, eg by only handling this in the CCR test’s CcrAction (or around the follow-task bulk path)? Alternatively and potentially preferrable, we could try to quiesce the follow task before mutating history and issuing new indexing, though I am not sure how complex this would be. What do you think?

**Review by inespot — COMMENTED** [review]
Thanks for the detailed explanation! One question

File: test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java (hunk 1 above)
Comment (burqen) [reply test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java]: Great points, and I had similar doubts around this change. I'll try:
> we could try to quiesce the follow task before mutating history and issuing new indexing

What do you think of See [bbec9cf](https://github.com/elastic/elasticsearch/pull/144945/commits/bbec9cf572d2027c0ed9277807087ee706b2f7ad)?

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 2]
```diff
@@ -631,17 +653,28 @@ protected void innerSendBulkShardOperationsRequest(
...
-                        operations,
-                        maxSeqNoOfUpdates
-                    );
-                    ActionListener<BulkShardOperationsResponse> listener = ActionListener.wrap(handler::accept, errorHandler);
-                    new CcrAction(request, listener, followerGroup).execute();
-                };
-                threadPool.executor(ThreadPool.Names.GENERIC).execute(task);
+                boolean acquired = false;
+                try {
+                    acquired = bulkOperationLock.tryLock(SAFE_AWAIT_TIMEOUT.millis(), TimeUnit.MILLISECONDS);
```
Comment (burqen) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: We could have used `null` instead of `NoOpLock` when we don't need the lock, but it felt worth it to avoid an awkward null check here and when releasing.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 3]
```diff
@@ -857,4 +890,29 @@ protected void performOnReplica(BulkShardOperationsRequest request, IndexShard r
         }
     }
 
+    private static class NoOpLock implements Lock {
```
Comment (burqen) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: The only existing no-op lock I found was `org.elasticsearch.index.engine.Engine.NoOpLock`, but I didn't want to introduce a dependency on that.

File: test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java (hunk 1 above)
Comment (inespot) [reply test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java]: Mmm ... I think there is unfortunately still a race here. `threadPool.executor(ThreadPool.Names.GENERIC).execute(task)` submits the task to the thread pool but does not wait for it to complete. So you could still end up with:
1. `innerSendBulkShardOperationsRequest` acquires the lock -> schedules bulk -> unlocks.
2. The test thread takes the write lock and replaces the primary.
3. The bulk starts running on another thread, and `assertPrimaryMode()` gets thrown.

Let me know if you agree with the above, or if I have missed sth!

Possible solutions I could think of:
- Construct the `CcrAction` manually in your test, plug in your own listener and execute the action when you want. Tradeoff: less coverage of the full `ShardFollowNodeTask` loop. Tradeoff: less coverage of the full `ShardFollowNodeTask` loop, and more of a unit-style test. Though other tests may already cover that breadth
- Extending on what you have already started, guard both `innerSendShardChangesRequest` and `innerSendBulkShardOperationsRequest`, track in-flight requests, and only proceed once everything has finished, or hold the read lock until the bulk completes (e.g. unlock in the listener). Maybe your could plug in your own thread executor instead of using the generic one and wait for "no tasks". Tradeoff: more complexity but keeps the original intention of the test.
- Back to your original idea but making it more scoped, construct your own targeted `CcrAction` specifically for this test that catches that `AssertionError` and forwards to `listener.onFailure(...)` so you can assert both fatal exceptions. Tradeoff: blurs the intended “history UUID changed” signal/intention. 

There could definitely be simpler solutions I have not considered here, let me know if you find any!

Comment (burqen) [reply test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java]: You are completely right, good catch! I moved the lock grab/release into the task itself instead. What do you think of that? [10b7353](https://github.com/elastic/elasticsearch/pull/144945/commits/10b735334ef858789e229ea6879a1acd083f43a5)

Comment (inespot) [reply test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java]: Niice, if my understanding is correct this should indeed fix the `assertPrimaryMode` race in `testChangeFollowerHistoryUUID`! 🎉 
Curious on your thoughts, but it feels like this fix is still leaking into shared test infrastructure in a way that might confuse future readers adding new tests: e.g., why is the lock only targeting the primary phase, or why `innerSendBulkShardOperationsRequest` and not `innerSendShardChangesRequest`? 

How would you feel about extracting the current `ShardFollowNodeTask` test implementation into its own subclass (like `CcrAction`) and having a lock-aware extension of it inlined directly inside `testChangeFollowerHistoryUUID`, with the `innerSendBulkShardOperationsRequest` override and a short comment explaining the invariant sitting right next to the reinit code that needs it? 
That way the shared helper stays lock-free, the `NoOpLock` goes away, and the locking rationale lives where it's most useful.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 4]
```diff
@@ -632,14 +654,26 @@ protected void innerSendBulkShardOperationsRequest(
...
-                        followerHistoryUUID,
-                        operations,
-                        maxSeqNoOfUpdates
-                    );
-                    ActionListener<BulkShardOperationsResponse> listener = ActionListener.wrap(handler::accept, errorHandler);
-                    new CcrAction(request, listener, followerGroup).execute();
+                    boolean acquired = false;
+                    try {
+                        acquired = bulkOperationLock.tryLock(SAFE_AWAIT_TIMEOUT.millis(), TimeUnit.MILLISECONDS);
+                        assertTrue(acquired);
```
Comment (inespot) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: If `tryLock` times out, `assertTrue` would throw an AssertionError on the `GENERIC` thread. The thread pool absorbs uncaught exceptions rather than failing the test, so we would end up with the pattern as
the original failure: the test would either hang or produce a confusing failure at a later point. We could instead propagate the timeout through `errorHandler`? That way the task fails with a clear message and surfaces at the `failure.getRootCause().getMessage()` assertion.

Comment (inespot) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Same thing with the `throw new RuntimeException(e)` a couple lines below

File: test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java (hunk 1 above)
Comment (burqen) [reply test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java]: Thanks for the thorough review so far 🙏 What are your thoughts on this one? [1276482](https://github.com/elastic/elasticsearch/pull/144945/commits/12764827c7273f795680cb8984be808a3e1678a9)

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java (hunk 4 above)
Comment (burqen) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Good points as usual! How about this? [fa39179](https://github.com/elastic/elasticsearch/pull/144945/commits/fa39179780a1c38c3c52fa9e265b95af2c45044e)

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 5]
```diff
@@ -857,4 +732,217 @@ protected void performOnReplica(BulkShardOperationsRequest request, IndexShard r
...
+    private class CustomShardFollowNodeTask extends ShardFollowNodeTask {
+        private final ShardFollowTask params;
+        private final ThreadPool threadPool;
+        private final Set<Long> fetchOperations;
+        private final ReplicationGroup followerGroup;
+        private final ReplicationGroup leaderGroup;
+        private final String recordedLeaderIndexHistoryUUID;
+        private final AtomicBoolean stopped;
+
+        public CustomShardFollowNodeTask(
```
Comment (inespot) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Nit: unnecessary public modifier is making checkstyle checks fail

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 6]
```diff
@@ -857,4 +732,217 @@ protected void performOnReplica(BulkShardOperationsRequest request, IndexShard r
...
+            10240,
+            ByteSizeValue.of(512, ByteSizeUnit.MB),
+            TimeValue.timeValueMillis(10),
+            TimeValue.timeValueMillis(10),
+            Collections.emptyMap()
+        );
+        return params;
+    }
+
+    private class CustomShardFollowNodeTask extends ShardFollowNodeTask {
```
Comment (inespot) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Nit: should we call this `TestShardFollowNodeTask` to make it immediately recognizable as a test class among `ShardFollowNodeTask` implementations?"

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 7]
```diff
@@ -249,7 +250,44 @@ public void testChangeFollowerHistoryUUID() throws Exception {
...
+                ShardFollowNodeTask shardFollowTask = new CustomShardFollowNodeTask(params, threadPool, followerGroup, leaderGroup) {
+                    @Override
+                    protected Runnable bulkShardOperationsTask(
+                        String followerHistoryUUID,
+                        List<Translog.Operation> operations,
+                        long maxSeqNoOfUpdates,
+                        Consumer<BulkShardOperationsResponse> handler,
+                        Consumer<Exception> errorHandler
+                    ) {
+                        Runnable inner = super.bulkShardOperationsTask(
```
Comment (inespot) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Nit: `delegate` might be more standard naming here

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 8]
```diff
@@ -249,7 +250,44 @@ public void testChangeFollowerHistoryUUID() throws Exception {
...
+                            operations,
+                            maxSeqNoOfUpdates,
+                            handler,
+                            errorHandler
+                        );
+                        return () -> {
+                            boolean acquired = false;
+                            try {
+                                acquired = replacePrimaryLock.readLock().tryLock(SAFE_AWAIT_TIMEOUT.millis(), TimeUnit.MILLISECONDS);
+                                assertTrue(acquired);
```
Comment (inespot) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Nit: `assertTrue("Failed to grab bulkShardOperationsTask read lock within timeout " + SAFE_AWAIT_TIMEOUT, acquired);`

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 9]
```diff
@@ -249,7 +250,44 @@ public void testChangeFollowerHistoryUUID() throws Exception {
...
+                                inner.run();
+                            } catch (AssertionError e) {
+                                errorHandler.accept(new RuntimeException(e));
+                            } catch (InterruptedException e) {
+                                Thread.currentThread().interrupt();
+                                errorHandler.accept(e);
```
Comment (inespot) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Should the error handling move to the main test class?

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 10]
```diff
@@ -249,7 +250,44 @@ public void testChangeFollowerHistoryUUID() throws Exception {
...
+                            followerHistoryUUID,
+                            operations,
+                            maxSeqNoOfUpdates,
+                            handler,
+                            errorHandler
+                        );
+                        return () -> {
+                            boolean acquired = false;
+                            try {
+                                acquired = replacePrimaryLock.readLock().tryLock(SAFE_AWAIT_TIMEOUT.millis(), TimeUnit.MILLISECONDS);
```
Comment (inespot) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java:276]: Nit: add small comment explaining why we need to lock here

**Review by inespot — APPROVED** [review]
LGTM, with nits, and provided the tests are passing 5000+ times on your local machine :)

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java (hunk 9 above)
Comment (burqen) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Do you mean something like this? [b1a616b](https://github.com/elastic/elasticsearch/pull/144945/commits/b1a616b43a4b69d6f460fec0a56421339b58725f)

Comment (inespot) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Not quite, I meant try/caching the `AssertionError`s, which won't be caught by a `catch(Exception)`. The added outer:
```
try {
    threadPool.executor(ThreadPool.Names.GENERIC).execute(task);
} catch (Exception e) {
    errorHandler.accept(e);
}
```
would just be a repeat of: https://github.com/elastic/elasticsearch/blob/86bad24523ad396af56a07aeb552d8eb060737ad/test/framework/src/main/java/org/elasticsearch/index/replication/ESIndexLevelReplicationTestCase.java#L682-L684

So we want instead of catch `AssertionError`s in the general test class' `bulkShardOperationsTask` and pass them to the errorHandler? Let me know if that makes sense

Comment (burqen) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: I'm not sure I understand you so let me spell my thinking out to see if it clears something up. 

So, we have three "layers".

**Layer 1** - The thread pool execute, `TestShardFollowNodeTask#innerSendBulkShardOperationsRequest`
```
Runnable task = bulkShardOperationsTask(followerHistoryUUID, operations, maxSeqNoOfUpdates, handler, errorHandler);
try {
    threadPool.executor(ThreadPool.Names.GENERIC).execute(task);
} catch (Exception e) {
    errorHandler.accept(e);
}
```

**Layer 2** - The outer runnable where we override `TestShardFollowNodeTask#bulkShardOperationsTask` in `#testChangeFollowerHistoryUUID`
```
Runnable delegate = super.bulkShardOperationsTask(
    followerHistoryUUID,
    operations,
    maxSeqNoOfUpdates,
    handler,
    errorHandler
);
return () -> {
    boolean acquired = false;
    try {
        // Read lock to prevent bulk operations from racing with replacing primary shard
        acquired = replacePrimaryLock.readLock().tryLock(SAFE_AWAIT_TIMEOUT.millis(), TimeUnit.MILLISECONDS);
        assertTrue(
            "Failed to grab bulkShardOperationsTask read lock within timeout " + SAFE_AWAIT_TIMEOUT,
            acquired
        );
        delegate.run();
    } catch (AssertionError | InterruptedException e) {
        throw new RuntimeException(e);
    } finally {
        if (acquired) {
            replacePrimaryLock.readLock().unlock();
        }
    }
};
```
**Layer 3** - The inner runnable `TestShardFollowNodeTask#bulkShardOperationsTask`
```
return () -> {
    BulkShardOperationsRequest request = new BulkShardOperationsRequest(
        params.getFollowShardId(),
        followerHistoryUUID,
        operations,
        maxSeqNoOfUpdates
    );
    ActionListener<BulkShardOperationsResponse> listener = ActionListener.wrap(handler::accept, errorHandler);
    new CcrAction(request, listener, followerGroup).execute();
};
```

We want both `AssertionError`s and other `Exception`s to propagate to the `errorHandler`/`listener`.
- If we catch in layer 3, we will still need to catch in layer 1 or 2. For example the assertion that we grab read lock in time will not be caught by layer 3. I think this is what you are suggesting, but I'm not sure.
- So that leaves layer 1 or 2.

My suggestion was to wrap assertion layers in layer 2 in `RuntimeException` and then catch all exceptions in layer 1. That has the downside of course that only `testChangeFollowerHistoryUUID` benefit from it.

We could also explicitly catch both `AssertionError` and `Exception` in layer 1. Here is a suggestion for that. [be14eb8](https://github.com/elastic/elasticsearch/pull/144945/commits/be14eb846ae30e62fe9de71daac37b5c4e3f87e3)

Comment (inespot) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: > That has the downside of course that only testChangeFollowerHistoryUUID benefit from it.

Yep, so this is what I thought we should make consistent between tests.

Layer 1 + layer 3 works, or alternatively layer 3 + layer 2. Because you are right that you still need to catch the assertion error in layer 2 anyway!

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 11]
```diff
@@ -827,6 +827,8 @@ protected void innerSendBulkShardOperationsRequest(
             Runnable task = bulkShardOperationsTask(followerHistoryUUID, operations, maxSeqNoOfUpdates, handler, errorHandler);
             try {
                 threadPool.executor(ThreadPool.Names.GENERIC).execute(task);
+            } catch (AssertionError e) {
+                errorHandler.accept(new RuntimeException(e));
             } catch (Exception e) {
                 errorHandler.accept(e);
```
Comment (inespot) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java]: Nit: alternatively, you could make this catch `Throwable`, but not super strongly opinionated about this

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java [hunk 12]
```diff
@@ -279,8 +279,8 @@ protected Runnable bulkShardOperationsTask(
                                     acquired
                                 );
                                 delegate.run();
-                            } catch (AssertionError | InterruptedException e) {
-                                throw new RuntimeException(e);
+                            } catch (InterruptedException e) {
```
Comment (inespot) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/ShardFollowTaskReplicationTests.java:282]: I think you were right that we still need to catch `AssertionError` at that level as well right? Because of the lock?

**Comment by burqen** [comment]
Thanks for the thorough review @inespot Merging now 👍
