### PR TITLE
Also use PriorityComparator in shard balancer

### LINKED ISSUE #13249: Prioritized Replica Recovery is reversed by date
Prioritized allocation enables the recovery in the order of `index.priority` > `index.creation_date` > `index.name` (reversed). However, I've found that when allowing it to work based on `index.creation_date` (the default mechanism), it does it in the reverse of the expected order **relative to replicas**.

It's easy enough to reproduce with enough daily indices by manually deleting the replicas from one node, throttling the heck out of recovery, and speeding up monitoring:

```http
PUT /_cluster/settings
{
  "transient": {
    "cluster.routing.allocation.node_concurrent_recoveries" : 1,
    "indices.recovery.concurrent_streams" : 1,
    "indices.recovery.concurrent_small_file_streams" : 1,
    "indices.recovery.max_bytes_per_sec" : "1mb",
    "marvel.agent.interval" : "500ms"
  }
}
```

As I was watching it, I decided to take some screenshots:

1. Reversed Priority 1 of 2

2. Reversed Priority 2 of 2

This also appears to not be honoring the `index.priority` either, as I tried to use it as a workaround and it did not impact the recovery order at all, which makes me assume that this is not even coming into play during replica recovery.

### PR DESCRIPTION
**Pull request by s1monw**
Today we try to allocate primaries first and then replicas
but don't take the index creation date and priority into account
as we do in the GatewayAlloactor.

Closes #13249

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 1]
```diff
@@ -576,7 +579,8 @@ public int compare(ShardRouting o1,
                     if ((indexCmp = o1.index().compareTo(o2.index())) == 0) {
                         return o1.getId() - o2.getId();
                     }
-                    return indexCmp;
+                    final int secondary = secondaryComparator.compare(o1, o2);
+                    return secondary == 0 ? indexCmp : secondary;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: This was a bit hard for me to read due to the order in which comparators are checked. Could it be rewritten in a more idiomatic way, ie.

```java
if (o1.isPrimary() != o2.isPrimary()) {
  return o1.isPrimary() ? -1 : 1;
}
final int secondaryCmp = secondaryComparator.compare(o1, o2);
if (secondaryCmp != 0) {
  return secondaryCmp;
}
final int indexCmp = o1.index().compareTo(o2.index()));
if (indexCmp != 0) {
  return indexCmp;
}
final int idCmp = o1.getId() - o2.getId();
if (idCmp != 0) {
  return idCmp;
}
```
It would be helpful at least for me to see more quickly in which order comparisons are performed.

**Comment by jpountz** [comment]
Left a minor comment, otherwise LGTM

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java (hunk 1 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: I wanted to have the most expensive comparator last though... but I can add a comment?

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: oh I see, indeed a comment would help

**Comment by s1monw** [comment]
@jpountz pushed a new commit

**Comment by s1monw** [comment]
@pickypg can you give this a go?

File: core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 2]
```diff
@@ -576,7 +579,12 @@ public int compare(ShardRouting o1,
                     if ((indexCmp = o1.index().compareTo(o2.index())) == 0) {
                         return o1.getId() - o2.getId();
                     }
-                    return indexCmp;
+                    // this comparator is more expensive than all the others up there
+                    // that's why it's added last even though it could be easier to read
+                    // if we'd apply it earlier. this comparator will only differentiate across
+                    // indices all shared of the same index is treated equally.
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: hmm, is there a typo somewhere in the end (s/shared/shards maybe?), I don't understand it. But otherwise, I would have been happy with just "Apply secondaryComparator last as it is more expensive than other comparators"

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: it's `shards`

**Comment by jpountz** [comment]
LGTM
