### PR TITLE
Flush response stream in `Ec2DiscoveryTests`

### LINKED ISSUE #114088: [CI] Ec2DiscoveryTests testPublicIp failing
**Build Scans:**
- [elasticsearch-periodic #4293 / openjdk23_java-matrix](https://gradle-enterprise.elastic.co/s/yvevjkjy3hth4)
- [elasticsearch-periodic #4253 / openjdk23_java-matrix](https://gradle-enterprise.elastic.co/s/aewh4sbl76imq)

**Reproduction Line:**
```
./gradlew ':plugins:discovery-ec2:test' --tests "org.elasticsearch.discovery.ec2.Ec2DiscoveryTests.testPublicIp" -Dtests.seed=67E5E30A1DC80CD3 -Dtests.locale=ne -Dtests.timezone=America/Virgin -Druntime.java=23
```

**Applicable branches:**
7.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testPublicIp'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.discovery.ec2.Ec2DiscoveryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a collection with size <5>
     but: collection size was <0>
```

**Issue Reasons:**
- [7.17] 2 consecutive failures in step openjdk23_java-matrix
- [7.17] 2 failures in test testPublicIp (0.5% fail rate in 414 executions)
- [7.17] 2 failures in step openjdk23_java-matrix (100.0% fail rate in 2 executions)
- [7.17] 2 failures in pipeline elasticsearch-periodic (18.2% fail rate in 11 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #114089: [CI] Ec2DiscoveryTests testDefaultSettings failing
**Build Scans:**
- [elasticsearch-periodic #4293 / openjdk23_java-matrix](https://gradle-enterprise.elastic.co/s/yvevjkjy3hth4)
- [elasticsearch-periodic #4289 / openjdk23_java-matrix](https://gradle-enterprise.elastic.co/s/3trq3mp6icjse)

**Reproduction Line:**
```
./gradlew ':plugins:discovery-ec2:test' --tests "org.elasticsearch.discovery.ec2.Ec2DiscoveryTests.testPublicIp" -Dtests.seed=67E5E30A1DC80CD3 -Dtests.locale=ne -Dtests.timezone=America/Virgin -Druntime.java=23
```

**Applicable branches:**
7.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testDefaultSettings'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.discovery.ec2.Ec2DiscoveryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a collection with size <5>
     but: collection size was <0>
```

**Issue Reasons:**
- [7.17] 2 consecutive failures in step openjdk23_java-matrix
- [7.17] 2 failures in test testDefaultSettings (1.6% fail rate in 126 executions)
- [7.17] 2 failures in step openjdk23_java-matrix (100.0% fail rate in 2 executions)
- [7.17] 2 failures in pipeline elasticsearch-periodic (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #114090: [CI] Ec2DiscoveryTests testReadHostFromTag failing
**Build Scans:**
- [elasticsearch-periodic #4293 / openjdk23_java-matrix](https://gradle-enterprise.elastic.co/s/yvevjkjy3hth4)
- [elasticsearch-periodic #4265 / openjdk23_java-matrix](https://gradle-enterprise.elastic.co/s/hp2rwcczcb2to)
- [elasticsearch-periodic #4253 / openjdk23_java-matrix](https://gradle-enterprise.elastic.co/s/aewh4sbl76imq)

**Reproduction Line:**
```
./gradlew ':plugins:discovery-ec2:test' --tests "org.elasticsearch.discovery.ec2.Ec2DiscoveryTests.testPublicIp" -Dtests.seed=67E5E30A1DC80CD3 -Dtests.locale=ne -Dtests.timezone=America/Virgin -Druntime.java=23
```

**Applicable branches:**
7.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testReadHostFromTag'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.discovery.ec2.Ec2DiscoveryTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a collection with size <5>
     but: collection size was <0>
```

**Issue Reasons:**
- [7.17] 3 consecutive failures in step openjdk23_java-matrix
- [7.17] 3 failures in test testReadHostFromTag (0.7% fail rate in 415 executions)
- [7.17] 3 failures in step openjdk23_java-matrix (100.0% fail rate in 3 executions)
- [7.17] 3 failures in pipeline elasticsearch-periodic (27.3% fail rate in 11 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DaveCTurner**
This is apparently necessary when running with JDK23. Also cleans up
some warnings in the same test suite.

Closes #114088
Closes #114089
Closes #114090

### CODE REVIEW

File: plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java [hunk 1]
```diff
@@ -144,6 +144,7 @@ protected List<TransportAddress> buildDynamicHosts(Settings nodeSettings, int no
                                 exchange.getResponseHeaders().set("Content-Type", "text/xml; charset=UTF-8");
                                 exchange.sendResponseHeaders(HttpStatus.SC_OK, responseBody.length);
                                 exchange.getResponseBody().write(responseBody);
+                                exchange.getResponseBody().flush();
```
Comment (arteam) [inline plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java:147]: We can also consider closing `exchange` either explicitly or via `try-with-resources`. I believe that's what we do normally do in other `HttpHandlers`.

**Review by arteam — APPROVED** [review]
LGTM

File: plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java (hunk 1 above)
Comment (DaveCTurner) [reply plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2/Ec2DiscoveryTests.java:147]: The control-flow here is a bit weird, I'm ok with failing (and leaking the `exchange`) on exception.
