### PR TITLE
fix(semantic highlighter): add vector similarity queries and bbq_disk support 

### LINKED ISSUE #136056: Min similarity is not handled through the semantic text highlighter
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

`knn` queries that specify a `similarity` and query a `semantic_text` field do not work with semantic highlighting.

I debugged this and traced it down to the fact that we do not handle `VectorSimilarityQuery` in `SemanticTextHighlighter#extractDenseVectorQueries`. I created a quick branch to prove out a fix: https://github.com/Mikep86/elasticsearch/tree/semantic-text_debug-highlighting-with-min-similarity

### Steps to Reproduce

1. Create an index with a `semantic_text` field that uses a dense vector model:

```json
PUT test-index
{
  "mappings": {
    "properties": {
      "inference_field": {
        "type": "semantic_text",
        "inference_id": ".multilingual-e5-small-elasticsearch"
      }
    }
  }
}
```

2. Add some docs to the index

3. Query the field using a `knn` field with a `similarity` value and highlighting enabled:

```json
GET test-index/_search
{
  "query": {
    "knn": {
      "similarity": 0.40,
      "field": "inference_field",
      "query_vector_builder": {
        "text_embedding": {
          "model_text": "foo"
        }
      },
      "k": 10,
      "num_candidates": 100
    }
  },
  "highlight": {
    "fields": {
      "inference_field": {
        "order": "score",
        "number_of_fragments": 1
      }
    }
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by mromaios**
Closes: https://github.com/elastic/elasticsearch/issues/136056

This PR improves the handling of vector based queries in the SemanticTextHighlighter.

- The highlighter will now correctly extract the underlying vector data from queries wrapped in `VectorSimilarityQuery` (e.g. when a `similarity` threshold is set in a `knn` query) as well as vector queries on a `bbq_disk` dense vector type.

----
```
# Create an index
PUT test-index
{
  "mappings": {
    "properties": {
      "inference_field": {
        "type": "semantic_text",
        "inference_id": ".multilingual-e5-small-elasticsearch"
      }
    }
  }
}

# Add a document
POST test-index/_doc/1
{
  "inference_field": "This is a test sentence for semantic search"
}

# Issue a highlighting query  
GET /test-index/_search
{
  "from" : 0,
  "size" : 10,
  "sort" : [
    {
      "_score" : {
        "order" : "asc"
      }
    }
  ],
  "query" : {
    "knn" : {
      "field" : "inference_field",
      "query_vector_builder" : {
        "text_embedding" : {
          "model_text" : "sentence"
        }
      },
      "similarity": 0.8,
      "k" : 12,
      "num_candidates" : 90
    }
  },
  "highlight" : {
    "fields" : {
      "inference_field" : {
        "order" : "score",
        "number_of_fragments" : 1
      }
    }
  }
}

---------------------
{
  "took" : 1811,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [
      {
        "_index" : "test-index",
        "_id" : "1",
        "_score" : 0.92290497,
        "_source" : {
          "inference_field" : "This is a test sentence for semantic search"
        },
        "highlight" : {
          "inference_field" : [
            "This is a test sentence for semantic search"
          ]
        },
        "sort" : [
          0.92290497
        ]
      }
    ]
  }
}
```

### CODE REVIEW

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java [hunk 1]
```diff
@@ -276,12 +278,27 @@ public void visitLeaf(Query query) {
...
+    private VectorData extractVectorData(Query vectorQuery) {
+        if (vectorQuery instanceof KnnFloatVectorQuery knnQuery) {
+            return VectorData.fromFloats(knnQuery.getTargetCopy());
+        } else if (vectorQuery instanceof KnnByteVectorQuery knnQuery) {
+            return VectorData.fromBytes(knnQuery.getTargetCopy());
+        } else if (vectorQuery instanceof RescoreKnnVectorQuery rescoreQuery) {
+            return extractVectorData(rescoreQuery.innerQuery());
+        }
+        // TODO: do we care about AbstractIVFKnnVectorQuery?
+        return null;
```
Comment (mromaios) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java]: 💭 I deviated a bit from the [very clean solution](https://github.com/Mikep86/elasticsearch/commit/c1aeb9bcd12005ac886b155d7ae6a67200e3ecc3)/structure you had @Mikep86, just for discussion. If we raise an exception here we risk changing the current behaviour which allows the query to happen with a no-op. If someone is using it (albeit wrongly) they might get flooded with errors. 

On the other hand it helps with detection. Not sure. WDYT?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java [hunk 2]
```diff
@@ -276,12 +278,27 @@ public void visitLeaf(Query query) {
...
 
+    private VectorData extractVectorData(Query vectorQuery) {
+        if (vectorQuery instanceof KnnFloatVectorQuery knnQuery) {
+            return VectorData.fromFloats(knnQuery.getTargetCopy());
+        } else if (vectorQuery instanceof KnnByteVectorQuery knnQuery) {
+            return VectorData.fromBytes(knnQuery.getTargetCopy());
+        } else if (vectorQuery instanceof RescoreKnnVectorQuery rescoreQuery) {
+            return extractVectorData(rescoreQuery.innerQuery());
+        }
+        // TODO: do we care about AbstractIVFKnnVectorQuery?
```
Comment (mromaios) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java]: 💭 From a quick look in `DenseVectorFieldMapper` https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldMapper.java#L2869-L2882 if the field type is `bbq_disk` the returned vector will be either a 
`DiversifyingChildrenIVFKnnFloatVectorQuery` or a `IVFKnnFloatVectorQuery` both of which extend `AbstractIVFKnnVectorQuery`. These at the moment (AFAICT)  don't have "inner" query getters. Do we need to cover that case as well to be future proof, or am I completely off 😅

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java [hunk 3]
```diff
@@ -208,6 +208,40 @@ public void testNoSemanticField() throws Exception {
...
+    @SuppressWarnings("unchecked")
+    public void testDenseVectorWithSimilarityThreshold() throws Exception {
+        var mapperService = createDefaultMapperService(useLegacyFormat);
+        Map<String, Object> queryMap = (Map<String, Object>) queries.get("dense_vector_1");
+        float[] vector = readDenseVector(queryMap.get("embeddings"));
+        var fieldType = (SemanticTextFieldMapper.SemanticTextFieldType) mapperService.mappingLookup().getFieldType(SEMANTIC_FIELD_E5);
+
+        // TODO: understand why this ends up being a VectorSimilarityQuery with a RescoreKnnVectorQuery innerQuery (InlineRescoreQuery)
+        // with an ESDiversifyingChildrenFloatKnnVectorQuery innerQuery
+        KnnVectorQueryBuilder knnQuery = new KnnVectorQueryBuilder(
```
Comment (mromaios) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java:219]: 📝 This ends up being a VectorSimilarityQuery with a RescoreKnnVectorQuery innerQuery (InlineRescoreQuery) with an ESDiversifyingChildrenFloatKnnVectorQuery innerQuery. ~From what I can tell with the current defaults it will always end up as a rescore query.~

File: docs/changelog/138140.yaml [hunk 4]
```diff
@@ -0,0 +1,5 @@
+pr: 138140
+summary: "Fix(semantic highlighter): handle vector similarity queries"
```
Comment (mromaios) [inline docs/changelog/138140.yaml]:
```suggestion
summary: "Add support for VectorSimilarityQuery in SemanticTextHighlighter to correctly extract and highlight vector-based queries with similarity thresholds and rescoring."
```
Is this too verbose?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java (hunk 2 above)
Comment (mromaios) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java]: Hm, tested with 
```
PUT test-index
{
  "mappings": {
    "properties": {
      "inference_field": {
        "type": "semantic_text",
        "inference_id": ".multilingual-e5-small-elasticsearch",
        "index_options": {
          "dense_vector": {
            "type": "bbq_disk"
          }
        }
      }
    }
  }
}
```
and highlighting doesn't work, so probably need to cover `IVFKnnFloatVectorQuery` too

File: docs/changelog/138140.yaml (hunk 4 above)
Comment (Mikep86) [reply docs/changelog/138140.yaml]: How about something like "Fix semantic highlighting when using a knn query with a minimum similarity and when using bbq_disk"?

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java [hunk 5]
```diff
@@ -266,18 +269,29 @@ public void consumeTerms(Query query, Term... terms) {
...
+                } else if (query instanceof VectorSimilarityQuery similarityQuery) {
+                    visitLeaf(similarityQuery.getInnerKnnQuery(), similarityQuery.getSimilarity());
                 }
             }
+
+            @Override
+            public void visitLeaf(Query query) {
+                visitLeaf(query, null);
+
+            }
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java:293]: Nice use of recursion to solve the problem here ❤️

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java [hunk 6]
```diff
@@ -208,6 +209,74 @@ public void testNoSemanticField() throws Exception {
...
 
+    @SuppressWarnings("unchecked")
+    public void testDenseVectorWithSimilarityThreshold() throws Exception {
+        var mapperService = createDefaultMapperService(useLegacyFormat);
+        Map<String, Object> queryMap = (Map<String, Object>) queries.get("dense_vector_1");
+        float[] vector = readDenseVector(queryMap.get("embeddings"));
+        var fieldType = (SemanticTextFieldMapper.SemanticTextFieldType) mapperService.mappingLookup().getFieldType(SEMANTIC_FIELD_E5);
+
+        // TODO: This ends up being a VectorSimilarityQuery with a RescoreKnnVectorQuery innerQuery (InlineRescoreQuery)
+        // with an ESDiversifyingChildrenFloatKnnVectorQuery innerQuery. Add more cases?
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java]: I don't think we need to worry about adding more cases in this particular test because we don't control how the `knn` query is rewritten. AFAIU the extra cases would be derived from varying the `model_settings` and `index_options` on the semantic text mapping, to do things like use DiskBBQ (already in progress) or use a model that uses byte embeddings.

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java [hunk 7]
```diff
@@ -208,6 +209,74 @@ public void testNoSemanticField() throws Exception {
...
+    // assertHighlightOneDoc(
+    // mapperService,
+    // shardRequest,
+    // sourceToParse,
+    // SEMANTIC_FIELD_E5_DISK_BBQ,
+    // expectedPassages.length,
+    // HighlightBuilder.Order.SCORE,
+    // expectedPassages
+    // );
+    // }
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java]: Any insights on the problems with this case?

**Review by Mikep86 — COMMENTED** [review]
Looks good overall, I like the approach! I think this is good to go with a little more work on the tests 🚀

**Review by kderusso — COMMENTED** [review]
Looks good! On top of Mike's comments, I would love to see a yaml test added under `90_semantic_text_highlighter.yml` as well as the associated BWC. Remember that for yaml tests we'll also need to make sure to create a feature/capability for Green CI 👍

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java (hunk 6 above)
Comment (mromaios) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java]: Cool thanks! I will add a the bbq in progress here, and a couple of yaml ones

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java (hunk 7 above)
Comment (mromaios) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java]: Yep, me 😓🤦

Sooooo, of course we don't create embeddings in the UT, but read them from the gzipped file.
```
var sourceToParse = new SourceToParse("0", readSampleDoc(useLegacyFormat), XContentType.JSON);
```
which I hadn't updated to include the new field.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java (hunk 2 above)
Comment (mromaios) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighter.java]: updated to cover that case

File: docs/changelog/138140.yaml (hunk 4 above)
Comment (mromaios) [reply docs/changelog/138140.yaml]: updated

**Comment by mromaios** [comment]
Thanks both! I addressed the comments and I think it's ready for another 👀 when you get the chance 🙏

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java [hunk 8]
```diff
@@ -208,6 +209,117 @@ public void testNoSemanticField() throws Exception {
...
+            sourceToParse,
+            SEMANTIC_FIELD_E5,
+            expectedPassages.length,
+            HighlightBuilder.Order.SCORE,
+            expectedPassages
+        );
+    }
+
+    @SuppressWarnings("unchecked")
+    public void testDenseVectorWithDiscBBQandSimilarityThreshold() throws Exception {
```
Comment (kderusso) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java]: Total nitpick here 


```suggestion
    public void testDenseVectorWithDiskBBQandSimilarityThreshold() throws Exception {
```

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java [hunk 9]
```diff
@@ -208,6 +209,117 @@ public void testNoSemanticField() throws Exception {
...
+            sourceToParse,
+            SEMANTIC_FIELD_E5_DISK_BBQ,
+            expectedPassages.length,
+            HighlightBuilder.Order.SCORE,
+            expectedPassages
+        );
+    }
+
+    @SuppressWarnings("unchecked")
+    public void testDenseVectorWithDiscBBQ() throws Exception {
```
Comment (kderusso) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java]: Another nitpick 

```suggestion
    public void testDenseVectorWithDiskBBQ() throws Exception {
```

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/90_semantic_text_highlighter_bwc.yml [hunk 10]
```diff
@@ -649,5 +649,156 @@ setup:
...
+  - requires:
+      cluster_features: "semantic_text.highlighter.bbq_and_similarity_support"
+      reason: semantic highlighter fix for disk_bbq index options and knn with similarity
+
+  - do:
+      indices.create:
+        index: test-dense-index-bbq_disk
+        body:
+          settings:
+            index.mapping.semantic_text.use_legacy_format: false
```
Comment (kderusso) [inline x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/90_semantic_text_highlighter_bwc.yml]: For BWC tests we need to set this value to true

```suggestion
            index.mapping.semantic_text.use_legacy_format: true
```

**Review by kderusso — COMMENTED** [review]
Nice work @mromaios ! I have one legit small change and a couple of super nitpicky pieces of feedback, otherwise this looks great to me!

**Review by kderusso — APPROVED** [review]
Approving pending the BWC fix

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java (hunk 8 above)
Comment (mromaios) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java]: Oh, thanks!

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java (hunk 9 above)
Comment (mromaios) [reply x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/highlight/SemanticTextHighlighterTests.java]: 🥏 Thanks!

File: x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/90_semantic_text_highlighter_bwc.yml (hunk 10 above)
Comment (mromaios) [reply x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/90_semantic_text_highlighter_bwc.yml]: Ah got it. Thanks!

**Comment by mromaios** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/138521)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by mromaios** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/138555)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/138558)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
