### PR TITLE
Strengthen elasticsearch plugin version check

### LINKED ISSUE #85336: Check for empty version while verifying Elasticsearch plugins
### Elasticsearch Version

8.2

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Any

### Problem Description

The PluginInfo verification code in Elasticsearch ensures that plugins must match the Elasticsearch they are being installed into. However, if the plugin descriptor properties file contains an empty string, the Version.fromString call would simply return the latest Elasticsearch version.

The bug relates to the following code:

```
        final String esVersionString = propsMap.remove("elasticsearch.version");
        if (esVersionString == null) {
            throw new IllegalArgumentException("property [elasticsearch.version] is missing for plugin [" + name + "]");
        }
        final Version esVersion = Version.fromString(esVersionString);
```

Apart from checking esVersionString for null, we should also check for the String being empty, e.g `Strings.hasLength(esVersionString) == false`.

### Steps to Reproduce

- Take any Elasticsearch plugin from a version other than the current
 
- Manually edit the plugin-descriptor.properties file in the jar and set `elasticsearch.version=`

- Deploy the plugin in the latest version of Elasticsearch 

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by grcevski**
When a plugin specifies an elasticsearch version with an empty string
in their plugin-descriptor.properties file, we don't enforce the
version check. This PR ensures that we check the version string for
empty as well as null value.

Closes #85336

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/plugins/PluginInfoTests.java [hunk 1]
```diff
@@ -84,6 +84,23 @@ public void testReadFromPropertiesElasticsearchVersionMissing() throws Exception
...
+        PluginTestUtil.writePluginProperties(
+            pluginDir,
+            "description",
+            "fake desc",
+            "name",
+            "my_plugin",
+            "version",
+            "1.0",
+            "elasticsearch.version",
+            ""
```
Comment (rjernst) [inline server/src/test/java/org/elasticsearch/plugins/PluginInfoTests.java:98]: Since we are using the Strings util, should we test for non zero length but still empty?

**Review by rjernst — APPROVED** [review]
LGTM
