### PR TITLE
Executes incremental reduce in the search thread pool

### LINKED ISSUE #53411: Partial reduce failures can throw AssertionError
Today we don't expect any failure when running a partial reduce of shard responses.
However there are at least two cases where such failures occur:

- Sorted queries on fields that are of mixed types in the different search indices (e.g.: a field mapped as keyword and double in the same search).
- Partial reduce that creates more than `search.max_buckets`.

There's a race condition in this scenario because the internal counters are not properly accounted.
Technically speaking, a partial reduce that fails should fail the entire request. Currently we execute partial reduce when we receive a new shard response and the buffer is full.  Since we have other shard queries in flight (the search is not over) it's not easy to fail the entire request if a failure occurs. The final reduce is not affected by this bug because it is executed after all shards responded. 

We should propagate the error safely to the final reduce or find a way to early terminate a request in the middle of a search phase. The latter would be a nice free improvements for users that disallows partial results (`"allow_partial_search_results": false`) since today we cannot early terminate the request on the first shard failure even if we know that the user expects an error.

### PR DESCRIPTION
**Pull request by jimczi**
This change forks the execution of partial reduces in the coordinating node to the search thread pool.
It also ensures that partial reduces are executed sequentially and asynchronously in order to limit the
 memory and cpu that a single search request can use but also to avoid blocking a network thread.
If a partial reduce fails with an exception, the search request is cancelled and the reporting of the error is
delayed to the start of the fetch phase (when the final reduce is performed). This ensures that we cleanup the
in-flight search requests before returning an error to the user.

Closes #53411
Relates #51857

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java [hunk 1]
```diff
@@ -0,0 +1,343 @@
...
+import static org.elasticsearch.action.search.SearchPhaseController.mergeTopDocs;
+import static org.elasticsearch.action.search.SearchPhaseController.setShardIndex;
+
+/**
+ * A {@link ArraySearchPhaseResults} implementation that incrementally reduces aggregation results
+ * as shard results are consumed.
+ * This implementation can be configured to batch up a certain amount of results and reduce
+ * them asynchronously in the provided {@link Executor} iff the buffer is exhausted.
+ */
+class QueryPhaseResultConsumer extends ArraySearchPhaseResults<SearchPhaseResult> {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:55]: Was this class only extracted from SearchPhaseController or what changes have been made to it? Maybe for easier reviewing it could have stayed where it was, at least initially? Would that be possible?

File: server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java [hunk 2]
```diff
@@ -634,6 +641,14 @@ public void run() {
         }
     }
 
+    private void cancelTask(SearchTask task, Exception exc) {
+        CancelTasksRequest req = new CancelTasksRequest()
+            .setTaskId(new TaskId(client.getLocalNodeId(), task.getId()))
+            .setReason(exc.getMessage());
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java:647]: Maybe add some prefix to the message? I am always afraid that the exc message may be null or not so understandable, with a prefix we would know for sure where the cancel comes from.

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java [hunk 3]
```diff
@@ -138,6 +140,28 @@ public void execute(SearchContext context) {
...
+            @Override
+            protected void setPivot(int i) {
+
+            }
+
+            @Override
+            protected int comparePivot(int j) {
+                return 0;
+            }
+        };
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java:163]: why do we need to do this compared to before?

**Review by javanna — COMMENTED** [review]
I left a couple of minor comments/questions. I think I will have to look at it another 3/4 times before I can properly review it :)

File: server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java (hunk 3 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/search/fetch/FetchPhase.java]: That's an unrelated change sorry :(. I removed it from this pr.

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 1 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:55]: We could but the change is substantial so I don't think it would help. This PR is a complete rewrite of the `QueryPhaseResultConsumer`.

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java [hunk 4]
```diff
@@ -0,0 +1,343 @@
...
+    @Override
+    void consumeResult(SearchPhaseResult result, Runnable next) {
+        super.consumeResult(result, () -> {});
+        QuerySearchResult querySearchResult = result.queryResult();
+        consumeInternal(querySearchResult, next);
+        progressListener.notifyQueryResult(querySearchResult.getShardIndex());
+    }
+
+    private void consumeInternal(QuerySearchResult result, Runnable next) {
+        boolean shouldExecuteImmediatly = true;
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:132]: s/shouldExecuteImmediatly/executeNextImmediately/?

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java [hunk 5]
```diff
@@ -0,0 +1,343 @@
...
+    private final int topNSize;
+    private final int bufferSize;
+    private final boolean hasTopDocs;
+    private final boolean hasAggs;
+    private final boolean performFinalReduce;
+
+    private final TopDocsStats topDocsStats;
+    private volatile int numReducePhases;
+    private List<SearchShard> processedShards = new ArrayList<>();
+    private boolean hasPartialReduce;
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:73]: I think it is worth a comment about why you can't use `reducedAggs != null`. I believe the reason for that is that you want to set this to true before the reduced aggs are ready.

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java [hunk 6]
```diff
@@ -0,0 +1,343 @@
...
+                    || hasFailure()) {
+                return;
+            }
+            runningTask.compareAndSet(null, queue.peek());
+            task = queue.poll();
+        }
+        executor.execute(new AbstractRunnable() {
+            @Override
+            protected void doRun() throws Exception {
+                List<QuerySearchResult> toConsume = task.consumeBuffer();
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:296]: Do you see the task being consumed twice? It is probably worth a comment explaining why.

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 1 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:55]: Yeah. This looks so much bigger than before and I don't think it would have made review a ton easier to keep it where it was.

**Review by nik9000 — COMMENTED** [review]
I left a few things, mostly small. I think this is the sort of thing that we need, but I also feel like I don't know JVM threading stuff well enough to be super clear. I feel like we're being fairly paranoid here with the threading stuff. Which is probably fine because this won't trigger on small searches. But I don't know enough to be sure that my instinct is right about it either.

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 6 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java]: If the task is cancelled, we nullify the buffer in the task. That's why we need this check, I added a comment in https://github.com/elastic/elasticsearch/pull/58461/commits/1fa48801f433588a8a0de2e64851c1e145cf0640

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 5 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java]: ++, I pushed https://github.com/elastic/elasticsearch/pull/58461/commits/1fa48801f433588a8a0de2e64851c1e145cf0640

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 4 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java]: I pushed https://github.com/elastic/elasticsearch/pull/58461/commits/1fa48801f433588a8a0de2e64851c1e145cf0640

**Comment by jimczi** [comment]
Thanks for looking @nik9000 @javanna . I pushed another commit to address your comments and to simplify the change a bit. Would you mind taking another look ?

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java [hunk 7]
```diff
@@ -0,0 +1,411 @@
...
+import static org.elasticsearch.action.search.SearchPhaseController.setShardIndex;
+
+/**
+ * A {@link ArraySearchPhaseResults} implementation that incrementally reduces aggregation results
+ * as shard results are consumed.
+ * This implementation can be configured to batch up a certain amount of results and reduce
+ * them asynchronously in the provided {@link Executor} iff the buffer is exhausted.
+ */
+class QueryPhaseResultConsumer extends ArraySearchPhaseResults<SearchPhaseResult> {
+    private static final Logger logger = LogManager.getLogger(SearchPhaseController.class);
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:57]: Did you keep the same class here because folks are used to setting the logger for `SearchPhaseController`? If so, its worth a comment. If no, I'd switch this to `QueryPhaseResultConsumer`.

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java [hunk 8]
```diff
@@ -0,0 +1,411 @@
...
+                topDocsList.add(topDocs.topDocs);
+            }
+            newTopDocs = mergeTopDocs(topDocsList,
+                // we have to merge here in the same way we collect on a shard
+                topNSize, 0);
+        } else {
+            newTopDocs = null;
+        }
+
+        final Serialized<InternalAggregations> newAggs;
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java:170]: I think it is more clear to write this is `DelayableWriteable.Serialized<InternalAggregations>`.

**Review by nik9000 — APPROVED** [review]
I had another look this morning and I think I mostly understand it. I left two small things.

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 7 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java]: I switched to `QueryPhaseResultConsumer`, thanks for noticing

File: server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java (hunk 8 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java]: I pushed https://github.com/elastic/elasticsearch/pull/58461/commits/a6c4ff4545a5423f6f53f92e07fb35e3e2ff189a
