### PR TITLE
Avoiding possibility of duplicate index names in IndexLifecycleServiceTests.testExceptionStillProcessesOtherIndices

### LINKED ISSUE #114530: [CI] IndexLifecycleServiceTests.testExceptionStillProcessesOtherIndices fails
### CI Link

https://gradle-enterprise.elastic.co/s/ipx5wbgkxrfhu/tests/task/:x-pack:plugin:ilm:test/details/org.elasticsearch.xpack.ilm.IndexLifecycleServiceTests/testExceptionStillProcessesOtherIndices?top-execution=1

### Repro line

./gradlew ":x-pack:plugin:ilm:test" --tests "org.elasticsearch.xpack.ilm.IndexLifecycleServiceTests.testExceptionStillProcessesOtherIndices" -Dtests.seed=AEBD115E23419286 -Dtests.locale=fr-BJ -Dtests.timezone=Pacific/Auckland -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

I saw this failure on our "lucene_snapshot" integration branch after merging in "main", but the reproduction line also works on "main" so opening as a general CI failure

### PR DESCRIPTION
**Pull request by masseyke**
With certain seeds, two indexes in the test can have the same name, which causes test failures.
Closes #114530

### CODE REVIEW

**Review by PeteGillinElastic — APPROVED** [review]

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/IndexLifecycleServiceTests.java [hunk 1]
```diff
@@ -390,7 +390,10 @@ public void doTestExceptionStillProcessesOtherIndices(boolean useOnMaster) {
         MockAction mockAction = new MockAction(Collections.singletonList(i2mockStep));
         Phase i2phase = new Phase("phase", TimeValue.ZERO, Collections.singletonMap("action", mockAction));
         LifecyclePolicy i2policy = newTestLifecyclePolicy(policy1, Collections.singletonMap(i2phase.getName(), i1phase));
-        Index index2 = new Index(randomAlphaOfLengthBetween(1, 20), randomAlphaOfLengthBetween(1, 20));
+        Index index2 = new Index(
+            randomValueOtherThan(index1.getName(), () -> randomAlphaOfLengthBetween(1, 20)),
+            randomAlphaOfLengthBetween(1, 20)
```
Comment (PeteGillinElastic) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/IndexLifecycleServiceTests.java:395]: I guess it doesn't matter if the UUIDs clash? I'm half wondering whether it's worth doing the same thing for that argument as well... Up to you whether you think it's worthwhile.

Comment (masseyke) [reply x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm/IndexLifecycleServiceTests.java:395]: I initially thought the same, but we actually never use the uuid. I'm not really sure why we bother creating an Index object.
