### PR TITLE
Fix exception handling on DateFormatters.forPattern() with wrong date pattern

### LINKED ISSUE #104124: [CI] DateParseTests testInvalidPattern {TestCase=Basic Case} failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/vutsff4wtk6ya/tests/:x-pack:plugin:esql:test/org.elasticsearch.xpack.esql.expression.function.scalar.date.DateParseTests/testInvalidPattern%20%7BTestCase=Basic%20Case%7D

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.date.DateParseTests.testInvalidPattern {TestCase=Basic Case}" -Dtests.seed=B58D88DABFA27B1B -Dtests.locale=ar-BH -Dtests.timezone=America/Santo_Domingo -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.esql.expression.function.scalar.date.DateParseTests#testInvalidPattern {TestCase=Basic Case}`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testInvalidPattern%20%7BTestCase%3DBasic%20Case%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.expression.function.scalar.date.DateParseTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
junit.framework.AssertionFailedError: Unexpected exception type, expected InvalidArgumentException but got java.lang.ClassCastException: class java.time.format.DateTimeFormatterBuilder$PadPrinterParserDecorator cannot be cast to class java.time.format.DateTimeFormatterBuilder$NumberPrinterParser (java.time.format.DateTimeFormatterBuilder$PadPrinterParserDecorator and java.time.format.DateTimeFormatterBuilder$NumberPrinterParser are in module java.base of loader 'bootstrap')

  at __randomizedtesting.SeedInfo.seed([B58D88DABFA27B1B:3C5A371F01771B04]:0)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2894)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2875)
  at org.elasticsearch.xpack.esql.expression.function.scalar.date.DateParseTests.testInvalidPattern(DateParseTests.java:70)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

  Caused by: java.lang.ClassCastException: class java.time.format.DateTimeFormatterBuilder$PadPrinterParserDecorator cannot be cast to class java.time.format.DateTimeFormatterBuilder$NumberPrinterParser (java.time.format.DateTimeFormatterBuilder$PadPrinterParserDecorator and java.time.format.DateTimeFormatterBuilder$NumberPrinterParser are in module java.base of loader 'bootstrap')

    at java.time.format.DateTimeFormatterBuilder.appendValue(DateTimeFormatterBuilder.java:679)
    at java.time.format.DateTimeFormatterBuilder.appendValue(DateTimeFormatterBuilder.java:437)
    at java.time.format.DateTimeFormatterBuilder.parseField(DateTimeFormatterBuilder.java:2143)
    at java.time.format.DateTimeFormatterBuilder.parsePattern(DateTimeFormatterBuilder.java:1931)
    at java.time.format.DateTimeFormatterBuilder.appendPattern(DateTimeFormatterBuilder.java:1899)
    at org.elasticsearch.common.time.DateFormatters.forPattern(DateFormatters.java:2126)
    at org.elasticsearch.common.time.DateFormatter.forPattern(DateFormatter.java:126)
    at org.elasticsearch.common.time.DateFormatter.forPattern(DateFormatter.java:104)
    at org.elasticsearch.xpack.esql.expression.function.scalar.date.DateParse.toFormatter(DateParse.java:125)
    at org.elasticsearch.xpack.esql.expression.function.scalar.date.DateParse.toEvaluator(DateParse.java:114)
    at org.elasticsearch.xpack.esql.evaluator.EvalMapper.toEvaluator(EvalMapper.java:64)
    at org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.evaluator(AbstractFunctionTestCase.java:205)
    at org.elasticsearch.xpack.esql.expression.function.scalar.date.DateParseTests.lambda$testInvalidPattern$2(DateParseTests.java:72)
    at org.apache.lucene.tests.util.LuceneTestCase._expectThrows(LuceneTestCase.java:3047)
    at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2884)
    at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2875)
    at org.elasticsearch.xpack.esql.expression.function.scalar.date.DateParseTests.testInvalidPattern(DateParseTests.java:70)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
    at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
    at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
    at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
    at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/104124

Apparently there is a bug in `java.time` so that passing a wrong date pattern in some cases results in a `ClassCastException` instead of the expected `InvalidArgumentException` (see comment [here](https://github.com/elastic/elasticsearch/issues/104124#issuecomment-1921755275))

It's quite unlikely to catch this problem in a real production use case, but our randomized tests tripped over it.

The proposed solution is to also catch ClassCastException and in case wrap it in the expected InvalidArgumentException

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParse.java [hunk 1]
```diff
@@ -122,7 +122,15 @@ public ExpressionEvaluator.Factory toEvaluator(Function<Expression, ExpressionEv
     }
 
     private static DateFormatter toFormatter(Object format, ZoneId zone) {
-        return forPattern(((BytesRef) format).utf8ToString()).withZone(zone);
+        String pattern = ((BytesRef) format).utf8ToString();
+        DateFormatter formatter;
+        try {
+            formatter = forPattern(pattern);
+        } catch (ClassCastException e) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParse.java:129]: This catch is too broad, try to make it more specific to the JDK bug.

Also, since the `forPattern` method comes from an ES class (which is used in many other places), why has this issue been visible in ESQL only? Or is not only ESQL, but other places? If there are other places where this behavior can be possible, how did we handle it?

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParse.java:129]: It seems to be extremely unlikely to happen: that API is used by tens of components in ES since 2018, none of them is explicitly managing this exception and I cannot find any bug reports about that.

I guess we caught it because we are running a significant amount of randomized tests that hit that API directly.

The root problem is [here](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/time/DateFormatters.java#L2126): `new DateTimeFormatterBuilder().appendPattern(input)`

Given the low practical impact I tried to keep the fix limited to ESQL, but I can move it to Server

Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParse.java:129]: > It seems to be extremely unlikely to happen

On the contrary: because that API is heavily used in many components in ES, I find it very easy to encounter this JDK bug somewhere else. But it didn't happen so far. So what we do in ESQL or in how we test it, is very specific and different from the rest of Elasticsearch.

Look into why is that. See what is so specific about the test that fails. Knowing exactly why it fails for us and not for the rest of ES can reveal something that can be fixed/adjusted in some other place.

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParse.java:129]: I see your point, it makes sense, I'm moving the fix to server

> So what we do in ESQL or in how we test it, is very specific and different from the rest of Elasticsearch

> Look into why is that. See what is so specific about the test that fails. Knowing exactly why it fails for us and not for the rest of ES can reveal something that can be fixed/adjusted in some other place.

it fails for us because we [randomize](https://github.com/elastic/elasticsearch/pull/105048/files#diff-f5e8b736a246b4a56a08ef1e5e0b3646844db19feaafffe3c63b1d057cf79d9cL108) the input and we run this test four times per build (and still, it failed only once in nine months, since we introduced this function), while the rest of ES most of the times uses constant strings like `forPattern("yyyy-MM-dd")`

File: server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java [hunk 2]
```diff
@@ -1371,4 +1371,11 @@ public void testParsingMissingTimezone() {
         long millisJoda = DateFormatter.forPattern("yyyy-MM-dd HH:mm:ss").parseMillis("2018-02-18 17:47:17");
         assertThat(millisJava, is(millisJoda));
     }
+
+    // see https://bugs.openjdk.org/browse/JDK-8193877
+    public void testNoClassCastException() {
+        String input = "DpNKOGqhjZ";
+        IllegalArgumentException e = expectThrows(IllegalArgumentException.class, () -> DateFormatter.forPattern(input));
+        assertThat(e.getMessage(), containsString(input));
```
Comment (rjernst) [inline server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java:1379]: Let's also check the cause, to make sure we actually got the ClassCastException we expected

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java [hunk 3]
```diff
@@ -103,7 +103,6 @@ public static Iterable<Object[]> parameters() {
         );
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/104124")
     public void testInvalidPattern() {
         String pattern = randomAlphaOfLength(10);
```
Comment (rjernst) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java:107]: How do you know this random pattern will be an invalid date format? This test seems still possibly flaky.

**Review by rjernst — COMMENTED** [review]
Nice find on the JDK bug. We do not do random testing of date patterns, so it makes sense we haven't seen this.

However, I suggest strengthening the ESQL test (or removing it? why are you randomizing date patterns to begin with?). If the point of the test is to see that ESQL propagates invalid formats, then it would seem a singular invalid format would suffice?

File: server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java (hunk 2 above)
Comment (luigidellaquila) [reply server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java:1379]: The only additional information we have here is the exception message, I'll add a check for that.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java (hunk 3 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java:107]: Right, it's very unlikely but it's still possible that `randomAlphaOfLength(10)` returns a valid string pattern , and I don't have a better idea to randomize a string so that it's always invalid. I'll replace it with a constant string, it shoul be enough for our needs.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java [hunk 4]
```diff
@@ -103,9 +103,8 @@ public static Iterable<Object[]> parameters() {
         );
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/104124")
     public void testInvalidPattern() {
-        String pattern = randomAlphaOfLength(10);
+        String pattern = "invalid";
```
Comment (bpintea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java:107]: was the randomisation removal intentional?

File: server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java [hunk 5]
```diff
@@ -1371,4 +1371,12 @@ public void testParsingMissingTimezone() {
         long millisJoda = DateFormatter.forPattern("yyyy-MM-dd HH:mm:ss").parseMillis("2018-02-18 17:47:17");
         assertThat(millisJava, is(millisJoda));
     }
+
+    // see https://bugs.openjdk.org/browse/JDK-8193877
+    public void testNoClassCastException() {
+        String input = "DpNKOGqhjZ";
```
Comment (bpintea) [inline server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java:1377]: Shouldn't we randomise this? Or does the bug only manifest with some input format and this is such an instance? (We should add a comment if such.)

**Review by bpintea — APPROVED** [review]
Left some minor comments, lgtm otherwise.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java (hunk 4 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateParseTests.java:107]: Yes, it was intentional after Ryan's review. The problem is that randomizing the string does not guarantee that you'll get an invalid pattern, so it will make the test flaky. And producing random strings that are always invalid date patterns is not straight-forward

File: server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java (hunk 5 above)
Comment (luigidellaquila) [reply server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java:1377]: It happens only for some specific patterns, I linked the JDK bug as it explains the problem much better than how I could do it in a comment

File: server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java (hunk 2 above)
Comment (rjernst) [reply server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java:1380]: The ClassCastException which was caught by your change is added as the cause to the created IllegalArgumentException. We should be able to check the cause for that?

Comment (luigidellaquila) [reply server/src/test/java/org/elasticsearch/common/time/DateFormattersTests.java:1380]: Yes sorry, I misinterpreted your first comment, I thought you meant to check that the CCE was actually due to the JDK bug, then I realized you just suggested one more assert in the test to check that the `IllegalArgumentException`'s root cause was a CCE.
I fixed it with my latest commit.

**Review by rjernst — APPROVED** [review]
LGTM
