### PR TITLE
Put mapping operations must update metadata of all types.

### LINKED ISSUE #16239: PUT mapping with with search_analyzer and `update_all_types` does not actually update all types
Or `toXContent` is broken.

Reproduce:

```
DELETE test_index

PUT test_index
{
  "mappings": {
    "type1": {
      "properties": {
        "field": {
          "type": "string"
        }
      }
    },
    "type2": {
      "properties": {
        "field": {
          "type": "string"
        }
      }
    }
  }
}

GET test_index/_mapping/field/field?include_defaults

PUT test_index/type1/_mapping?update_all_types
{
  "properties": {
    "field": {
      "type": "string",
      "search_analyzer": "keyword",
      "analyzer": "default"
    }
  }
}

```
In the mapping I retrieve with the GET _mapping API in the mapping only type1 is updated, although with the GET field mapping API I get the correct mapping.

```
GET test_index/_mapping

{
  "test_index": {
    "mappings": {
      "type1": {
        "properties": {
          "field": {
            "type": "string",
            "analyzer": "default",
            "search_analyzer": "keyword"
          }
        }
      },
      "type2": {
        "properties": {
          "field": {
            "type": "string"
          }
        }
      }
    }
  }
}

GET test_index/_mapping/field/field


{
  "test_index": {
    "mappings": {
      "type2": {
        "field": {
          "full_name": "field",
          "mapping": {
            "field": {
              "type": "string",
              "analyzer": "default",
              "search_analyzer": "keyword"
            }
          }
        }
      },
      "type1": {
        "field": {
          "full_name": "field",
          "mapping": {
            "field": {
              "type": "string",
              "analyzer": "default",
              "search_analyzer": "keyword"
            }
          }
        }
      }
    }
  }
}

```

When I restart the node the change has vanished from the field mapping result but still is in the get mapping result.

### PR DESCRIPTION
**Pull request by jpountz**
Today put mapping operations only update metadata of the type that is being
modified, which is not enough since some modifications may have side-effects
on other types.

Closes #16239

### CODE REVIEW

**Comment by jpountz** [comment]
@rjernst could you give it a look?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java [hunk 1]
```diff
@@ -320,28 +319,24 @@ private ClusterState applyRequest(ClusterState currentState, PutMappingClusterSt
 
                     }
                 } else {
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java]: Is this else really necessary anymore? Looks like just some logging?

**Comment by rjernst** [comment]
LGTM

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java (hunk 1 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java]: It is logging only indeed. But whether or not to log things tends to be a bit controversial so I'd rather do it in another change if we want to remove it

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java]: Sure, it was just an observation. :)

**Comment by rjernst** [comment]
@jpountz This is a pretty bad bug for mapping validation, and the fix is relatively simple. Should we put it into 2.2.1?

**Comment by s1monw** [comment]
+1 to 2.2.1 and also port it to 2.1 in case we do a bugfix release there too?

**Comment by jpountz** [comment]
The problem is that 2.2 has another bug: when you update a mapping with `update_all_types=true`, it will not refresh the mapping source of other types (we had this bug since 2.0 and it was fixed as a side-effect of #15539) so this fix alone won't help, we would also need to fix mapping updates to refresh the source of all types. If the consensus is that we should do it, I will do it, but these are big changes so I'm not comfortable pushing them to a bugfix release.

**Comment by travisjeffery** [comment]
Is there a workaround for 2.2? This bug is a really bad bug to leave like it is.

**Comment by rjernst** [comment]
@travisjeffery the workaround would be to explicitly send updates to every type that contains the field you are changing.

**Comment by clintongormley** [comment]
@rjernst @travisjeffery there is no way to do that.  The update-mapping API only works on a single type at a time. The only time you can set the mapping for multiple types is at index creation.

**Comment by rjernst** [comment]
@clintongormley It does work. Updating them in one internal method call doesn't matter. We just need to get the mappings in memory back into the correct state.

```
DELETE test_index

PUT test_index
{
  "mappings": {
    "type1": {
      "properties": {
        "field": {
          "type": "string"
        }
      }
    },
    "type2": {
      "properties": {
        "field": {
          "type": "string"
        }
      }
    }
  }
}

PUT test_index/type1/_mapping?update_all_types=true
{
  "properties": {
    "field": {
      "type": "string",
      "search_analyzer": "keyword",
      "analyzer": "default"
    }
  }
}

GET test_index/_mapping?pretty
{
  "test_index" : {
    "mappings" : {
      "type1" : {
        "properties" : {
          "field" : {
            "type" : "string",
            "analyzer" : "default",
            "search_analyzer" : "keyword"
          }
        }
      },
      "type2" : {
        "properties" : {
          "field" : {
            "type" : "string"
          }
        }
      }
    }
  }
}

PUT test_index/type2/_mapping?update_all_types=true
{
  "properties": {
    "field": {
      "type": "string",
      "search_analyzer": "keyword",
      "analyzer": "default"
    }
  }
}

GET test_index/_mapping?pretty
{
  "test_index" : {
    "mappings" : {
      "type1" : {
        "properties" : {
          "field" : {
            "type" : "string",
            "analyzer" : "default",
            "search_analyzer" : "keyword"
          }
        }
      },
      "type2" : {
        "properties" : {
          "field" : {
            "type" : "string",
            "analyzer" : "default",
            "search_analyzer" : "keyword"
          }
        }
      }
    }
  }
}
```

**Comment by clintongormley** [comment]
Ah I see what you mean: using multiple calls to update mapping, ok

**Comment by fengzhi** [comment]
es 5.2 , I have many types. How can I add my new field to each type . I tryed  put mapping with `update_all_types` but it does not actually update all types.
