### PR TITLE
ESQL: Fix Driver search load millis as nanos bug

### LINKED ISSUE #142986: [CI] LuceneTopNSourceOperatorScoringTests testAccumulateSearchLoad failing
**Build Scans:**
- [elasticsearch-intake #34964 / part3](https://gradle-enterprise.elastic.co/s/gyxb6e4rcfwag)
- [elasticsearch-pull-request #123162 / part-3-fips](https://gradle-enterprise.elastic.co/s/d35rwb456g4mk)
- [elasticsearch-pull-request #122627 / part-3](https://gradle-enterprise.elastic.co/s/r7chyl7qpfowu)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.lucene.query.LuceneTopNSourceOperatorScoringTests.testAccumulateSearchLoad" -Dtests.seed=F577DFFE28ADF5BB -Dtests.locale=ne-Deva-NP -Dtests.timezone=America/Argentina/Salta -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.lucene.query.LuceneTopNSourceOperatorScoringTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAccumulateSearchLoad'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a value equal to or greater than <0.32665280983999984>
     but: <0.29191385875247977> was less than <0.32665280983999984>
```

**Issue Reasons:**
- [main] 3 failures in test testAccumulateSearchLoad (11.1% fail rate in 27 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (8.7% fail rate in 23 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #143111: [CI] LuceneTopNSourceOperatorTests testAccumulateSearchLoad failing
**Build Scans:**
- [elasticsearch-intake #35052 / part3](https://gradle-enterprise.elastic.co/s/5jgdqsflmvj6u)
- [elasticsearch-pull-request #123667 / part-3](https://gradle-enterprise.elastic.co/s/r55e7tcx2idfm)
- [elasticsearch-pull-request #123620 / part-3](https://gradle-enterprise.elastic.co/s/nyypkku6w7ytm)
- [elasticsearch-pull-request #123192 / part-3](https://gradle-enterprise.elastic.co/s/qjwu4wheys2hq)
- [elasticsearch-pull-request #122627 / part-3](https://gradle-enterprise.elastic.co/s/r7chyl7qpfowu)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.lucene.query.LuceneTopNSourceOperatorTests.testAccumulateSearchLoad" -Dtests.seed=6CD24C2BADA4FA2A -Dtests.locale=en-VG -Dtests.timezone=SystemV/MST7 -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.lucene.query.LuceneTopNSourceOperatorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAccumulateSearchLoad'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a value equal to or greater than <0.2237825636258929>
     but: <0.11896610025743493> was less than <0.2237825636258929>
```

**Issue Reasons:**
- [main] 5 failures in test testAccumulateSearchLoad (1.4% fail rate in 366 executions)
- [main] 4 failures in step part-3 (1.5% fail rate in 267 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (1.5% fail rate in 263 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/143111
Fixes https://github.com/elastic/elasticsearch/issues/143086
Fixes https://github.com/elastic/elasticsearch/issues/142986

Introduced in https://github.com/elastic/elasticsearch/pull/142841

The `now` variable holds millis, while the `reportSearchLoad()` expects nanos.
Propagated `nowSupplier` there instead to pass the actual nanos.

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java [hunk 1]
```diff
@@ -175,7 +175,7 @@ public DriverContext driverContext() {
      * thread to do other work instead of blocking or busy-spinning on the blocked operator.
      */
     SubscribableListener<Void> run(TimeValue maxTime, int maxIterations, LongSupplier nowSupplier) {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java]: NIT: here and in `updateStatus` lets rename `nowSupplier` to `currentTimeNanosSupplier`. 
This way it is obvious what time granularity it should supply.
