### PR TITLE
[Test] More reliable wait for index to appear

### LINKED ISSUE #126204: [CI] SharedClusterSnapshotRestoreIT testDeletionOfFailingToRecoverIndexShouldStopRestore failing
**Build Scans:**
- [elasticsearch-intake #21263 / part1](https://gradle-enterprise.elastic.co/s/af456slztu2nk)
- [elasticsearch-pull-request #66140 / part-1](https://gradle-enterprise.elastic.co/s/ocy32bktwizdg)
- [elasticsearch-intake #21259 / part1](https://gradle-enterprise.elastic.co/s/oiobnexiergym)
- [elasticsearch-pull-request #66140 / part-1](https://gradle-enterprise.elastic.co/s/jtelbsupwtgsm)
- [elasticsearch-pull-request #66126 / part-1](https://gradle-enterprise.elastic.co/s/2dhvmuvk7cxfs)
- [elasticsearch-pull-request #66078 / part-1](https://gradle-enterprise.elastic.co/s/ihkxtyuaccin4)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT.testDeletionOfFailingToRecoverIndexShouldStopRestore" -Dtests.seed=127C6CFF1D1C565D -Dtests.locale=fr-BE -Dtests.timezone=Asia/Yakutsk -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testDeletionOfFailingToRecoverIndexShouldStopRestore),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.snapshots.SnapshotRestoreException: [default:test-repo:test-snap/ys7WgC4oQfaufdfgx_fumg] cannot restore index [test-idx] because an open index with same name already exists in the cluster. Either close or delete the existing index or restore the index under a different name by providing a rename pattern and replacement name
```

**Issue Reasons:**
- [main] 6 failures in test testDeletionOfFailingToRecoverIndexShouldStopRestore (3.3% fail rate in 180 executions)
- [main] 2 failures in step part1 (9.5% fail rate in 21 executions)
- [main] 4 failures in step part-1 (5.0% fail rate in 80 executions)
- [main] 2 failures in pipeline elasticsearch-intake (9.5% fail rate in 21 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (3.8% fail rate in 80 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
Relates: #125652
Resolves: #126204

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 1]
```diff
@@ -748,7 +748,7 @@ public void testDeletionOfFailingToRecoverIndexShouldStopRestore() throws Except
 
         logger.info("--> wait for the index to appear");
         // that would mean that recovery process started and failing
-        waitForIndex("test-idx", TimeValue.timeValueSeconds(10));
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java:751]: This is the only caller of `waitForIndex` so I suggest removing the method itself too.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java [hunk 2]
```diff
@@ -748,7 +748,7 @@ public void testDeletionOfFailingToRecoverIndexShouldStopRestore() throws Except
...
+        safeGet(clusterAdmin().prepareHealth(TEST_REQUEST_TIMEOUT, "test-idx").execute());
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java:751]: No need to set a 30s timeout on the request if we're only waiting for 10s:

```suggestion
        safeGet(clusterAdmin().prepareHealth(SAFE_AWAIT_TIMEOUT, "test-idx").execute());
```

**Review by DaveCTurner — APPROVED** [review]
Couple of nits otherwise LGTM.

There's a few other places we call `indexExists()` in an `assertBusy()` which probably want the same treatment.

**Comment by nielsbauman** [comment]
As far as I am concerned, the cluster health API is also a candidate for being run on the local node by default - it's also listed in #101805. I still think that's valuable and worth doing, but that API will probably need the option to run on the master node, as we'll want to be able to wait for all tasks to complete **on the master node** - at least in tests, not sure how valuable that is in production.

This is not something we need to discuss on this PR - I only brought it up here because I noticed we're using the cluster health API here to check the index health - but we might need to discuss an approach sometime later.

**Comment by DaveCTurner** [comment]
++ yeah the cluster health API is kind of a weird one, it's so heavily used in tests to wait for the master node state that I think making it node-local will be fraught with difficulty. We could for instance wait for the node-local state and then reach out to the master to wait for the application to complete? But also it's not particularly heavyweight, it might not be worth the effort to migrate it.
