### PR TITLE
Search performance -  better caching logic for queries on wildcard field

### LINKED ISSUE #75848: Search - better caching logic for queries on wildcard field
A user reported slow performance with the new wildcard field which, oddly, was thousands of times faster when they ran the same query through a profiler.

The reason for the huge difference was revealed in a stack trace of the unprofiled query:

```
94.2% (4.7s out of 5s) cpu usage by thread 'elasticsearch[instance-0000000032][search][T#13]'
     6/10 snapshots sharing following 51 elements
       app//org.apache.lucene.util.compress.LZ4.decompress(LZ4.java:103)
       app//org.apache.lucene.codecs.lucene80.Lucene80DocValuesProducer$BinaryDecoder.decode(Lucene80DocValuesProducer.java:856)
       app//org.apache.lucene.codecs.lucene80.Lucene80DocValuesProducer$19.binaryValue(Lucene80DocValuesProducer.java:904)
       org.elasticsearch.xpack.wildcard.mapper.AutomatonQueryOnBinaryDv$1$1.matches(AutomatonQueryOnBinaryDv.java:56)
       app//org.apache.lucene.search.Weight$DefaultBulkScorer.scoreAll(Weight.java:282)
       app//org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:232)
       app//org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
       app//org.apache.lucene.search.LRUQueryCache.cacheIntoBitSet(LRUQueryCache.java:503)
       app//org.apache.lucene.search.LRUQueryCache.cacheImpl(LRUQueryCache.java:494)
       app//org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight$1.get(LRUQueryCache.java:766)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.req(Boolean2ScorerSupplier.java:165)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:108)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:90)
       app//org.apache.lucene.search.LRUQueryCache$CachingWrapperWeight$1.get(LRUQueryCache.java:765)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.opt(Boolean2ScorerSupplier.java:198)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.getInternal(Boolean2ScorerSupplier.java:113)
       app//org.apache.lucene.search.Boolean2ScorerSupplier.get(Boolean2ScorerSupplier.java:90)
```

There is query caching going on which is something that doesn't happen with profiled queries, hence the speed difference.

For some unknown reason the query caching logic in `LRUQueryCache.cacheIntoBitSet`  had singled out the very expensive `AutomatonQueryOnBinaryDv` normally used to verify a (hopefully) small set of docs that match an approximation query for wildcard/regex queries and decided to ask it to iterate across ALL docs in the index. This should not have happened - the LRUQueryCache should have [favoured](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/search/UsageTrackingQueryCachingPolicy.java#L130) caching the BooleanQuery that the wildcard field uses to contain both the approximation query and the expensive AutomatonQueryOnBinaryDv verifying query. I can't explain why this would happen other than a hashing collision or bug somewhere.
A safer approach that @jtibshirani suggested would be for the wildcard field not to rely on returning a BooleanQuery to combine verification and approximation queries and instead use a new custom query class  with a 2 phase iterator (like IndexOrDocValuesQuery) which would be opaque to the caching infrastructure and therefore it could never try use the expensive AutomatonQueryOnBinaryDv in isolation.

While it would be good to get to the bottom of why LRUQueryCache did what it did, the code is complex and Julie's suggestion is a safer way forward - regardless of how the caching logic may change in future.

### PR DESCRIPTION
**Pull request by markharwood**
Remove use of BooleanQuery in WildcardField regex/wildcard/fuzzy/prefix searches to prevent query caching framework from running the contained verification query clauses across whole index at great expense.

The new BinaryDvConfirmedAutomatonQuery provides a replacement wrapper for the approximation and verification clauses that plays better with caching logic

Closes #75848

### CODE REVIEW

File: x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/ApproximationAndVerificationQuery.java [hunk 1]
```diff
@@ -0,0 +1,250 @@
...
+public final class ApproximationAndVerificationQuery extends Query {
+
+    private final Query approxQuery, verifyQuery;
+
+    /**
+     * Create an {@link ApproximationAndVerificationQuery}. 
+     * @param approxQuery a query that is quick to run across many documents but is only approximate
+     * @param verifyQuery a query used to verify matches (slowly) on individual matches from approxQuery
+     */
+    public ApproximationAndVerificationQuery(Query approxQuery, Query verifyQuery) {
```
Comment (jtibshirani) [inline x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/ApproximationAndVerificationQuery.java:55]: I'm not sure adding this new class is super useful at the moment -- we only have one example right now that fits into this mold. I think it'd be best to just make a targeted fix for `AutomatonQueryOnBinaryDv` as a first iteration. Specifically, maybe this query could take in an approximation query as a parameter, and be renamed to something like `BinaryDvConfirmedAutomatonQuery`?

I suspect that a targeted fix will be clearer and have a lot less boilerplate. We can always follow-up later with a refactor if we encounter more examples of approximation + verification queries?

File: x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java [hunk 2]
```diff
@@ -27,32 +30,65 @@
...
+    private final Query approxQuery;
 
-    public AutomatonQueryOnBinaryDv(String field, String matchPattern, Automaton automaton) {
+    public BinaryDvConfirmedAutomatonQuery(Query approximation, String field, String matchPattern, Automaton automaton) {
+        this.approxQuery = approximation;
         this.field = field;
         this.matchPattern = matchPattern;
         bytesMatcher = new ByteRunAutomaton(automaton);
     }
+    public BinaryDvConfirmedAutomatonQuery(String field, String matchPattern, Automaton automaton) {
```
Comment (jtibshirani) [inline x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java:49]: Mostly a personal preference, but I think it'd be clearer to remove this constructor and force the caller to pass in `MatchAllDocsQuery`. That makes it really clear to the caller this query might do a full scan!

File: x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java [hunk 3]
```diff
@@ -27,32 +30,65 @@
...
+                Scorer approxScorer = approxWeight.scorer(context);
+                if (approxScorer == null) {
+                    // No matches to be had
+                    return null;
+                }
+                DocIdSetIterator approxDisi = approxScorer.iterator();
+                TwoPhaseIterator twoPhase = new TwoPhaseIterator(approxDisi) {
                     @Override
                     public boolean matches() throws IOException {
+                        if (values.advanceExact(approxDisi.docID()) == false)
```
Comment (jtibshirani) [inline x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java:88]: Would it make more sense to assert that `advanceExact` always returns true? It seems like it'd indicate a serious bug in our logic if this returned false.

File: x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/WildcardFieldMapper.java [hunk 4]
```diff
@@ -330,19 +330,17 @@ public Query wildcardQuery(String wildcardPattern, RewriteMethod method, boolean
...
                 : WildcardQuery.toAutomaton(new Term(name(), wildcardPattern));
-            AutomatonQueryOnBinaryDv verifyingQuery = new AutomatonQueryOnBinaryDv(name(), wildcardPattern, automaton);
             if (clauseCount > 0) {
                 // We can accelerate execution with the ngram query
                 BooleanQuery approxQuery = rewritten.build();
-                BooleanQuery.Builder verifyingBuilder = new BooleanQuery.Builder();
-                verifyingBuilder.add(new BooleanClause(approxQuery, Occur.MUST));
-                verifyingBuilder.add(new BooleanClause(verifyingQuery, Occur.MUST));
-                return new ConstantScoreQuery(verifyingBuilder.build());
+                return new ConstantScoreQuery(
```
Comment (jtibshirani) [inline x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/WildcardFieldMapper.java:336]: Do we need to wrap this in a `ConstantScoreQuery`, since this query already uses a `ConstantScoreScorer`?

**Review by jtibshirani — COMMENTED** [review]
This looks good to me! I left some very minor comments.

File: x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/WildcardFieldMapper.java (hunk 4 above)
Comment (markharwood) [reply x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/WildcardFieldMapper.java:336]: Good point. That was a relic from when we wrapped in a BooleanQuery

File: x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java (hunk 3 above)
Comment (markharwood) [reply x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java:88]: Will add an assertion. We'll still need the if for when running without assertions on.

File: x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java (hunk 2 above)
Comment (markharwood) [reply x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java:49]: I did have it that way before and felt like I was repeating the same code but, agreed, it's probably safer to reiterate the match-all point.

**Review by jtibshirani — APPROVED** [review]

File: x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java [hunk 5]
```diff
@@ -83,8 +84,8 @@ public Scorer scorer(LeafReaderContext context) throws IOException {
                     public boolean matches() throws IOException {
                         if (values.advanceExact(approxDisi.docID()) == false)
                         {
-                            // Bug if we have an indexed value but no doc value.
-                            assert false;
+                            // Bug if we have an indexed value (i.e an approxQuery) but no doc value.
+                            assert approxQuery instanceof MatchAllDocsQuery == false;
```
Comment (jtibshirani) [inline x-pack/plugin/wildcard/src/main/java/org/elasticsearch/xpack/wildcard/mapper/BinaryDvConfirmedAutomatonQuery.java]: Can you explain why this assertion changed? The original version seemed correct to me.
