### PR TITLE
[Transform] make shouldStopAtCheckpoint more robust

### LINKED ISSUE #70416: [CI] TransformIT.testStopWaitForCheckpoint
**Build scan**:
https://gradle-enterprise.elastic.co/s/dharwo34gzsem

**Repro line**:
```
./gradlew ':x-pack:plugin:transform:qa:multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformIT.testStopWaitForCheckpoint" \
  -Dtests.seed=733ADC0CFE2A526 \
  -Dtests.security.manager=true \
  -Dtests.locale=und \
  -Dtests.timezone=America/Indiana/Vincennes \
  -Druntime.java=11 \
  -Dtests.fips.enabled=true
```

**Reproduces locally?**:
No

**Applicable branches**:
7.x

**Failure history**:
Rare

**Failure excerpt**:
```
ElasticsearchStatusException[Elasticsearch exception [type=status_exception, reason=Failed to update transform task [transform-wait-for-checkpoint] state value should_stop_at_checkpoint from [true] to [true]]]
```

I noticed in the [logs](https://github.com/elastic/elasticsearch/files/6143061/transform_logs.zip) 

```
java.lang.RuntimeException: Failed to persist transform statistics for transform [transform-wait-for-checkpoint]
	at org.elasticsearch.xpack.transform.persistence.IndexBasedTransformConfigManager.lambda$putOrUpdateTransformStoredDoc$14(IndexBasedTransformConfigManager.java:528) [transform-7.13.0-SNAPSHOT.jar:7.13.0-SNAPSHOT]

....
Caused by: org.elasticsearch.index.engine.VersionConflictEngineException: [data_frame_transform_state_and_stats-transform-wait-for-checkpoint]: version conflict, required seqNo [9], primary term [1]. current document has seqNo [11] and primary term [1]
```

Log files uploaded [here](https://github.com/elastic/elasticsearch/files/6143061/transform_logs.zip)

### PR DESCRIPTION
**Pull request by hendrikmuhs**
shouldStopAtCheckpoint tells transform to stop at the next checkpoint, if
this API is called while a checkpoint is finishing, it can cause a race condition
in state persistence. This is similar to #69551, but this time in a different
place.

With this change `_stop?shouldStopAtCheckpoint=true` does not call doSaveState 
if indexer is shutting down. Still it ensures the job stops after the indexer has
shutdown. Apart from that the change fixes: a logging problem, it adds error 
handling in case of a timeout during `_stop?shouldStopAtCheckpoint=true`. Some
logic has been moved from the task to the indexer.

fixes #70416

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 1]
```diff
@@ -1109,13 +1130,18 @@ private void configurePageSize(Integer newPageSize) {
...
         indexerThreadShuttingDown = false;
-        if (stopCalledDuringIndexerThreadShutdown) {
-            doSaveState(IndexerState.STOPPED, getPosition(), () -> {});
+        if (saveStateRequestedDuringIndexerThreadShutdown) {
+            // if stop has been called and set shouldStopAtCheckpoint to true,
+            // we should stop if we just finished a checkpoint
+            if (context.shouldStopAtCheckpoint() && nextCheckpoint == null) {
+                stop();
+            }
+            doSaveState(getState(), getPosition(), () -> {});
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:1144]: This seems like a bad bug :/

Previously, even if we were waiting to stop at a checkpoint we would just set the indexer to stopped and save state. No wonder we had two things attempting to save state + a weird race condition

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 2]
```diff
@@ -719,9 +737,12 @@ private synchronized boolean addSetStopAtCheckpointListener(
 
     synchronized void stopAndSaveState() {
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java:738]: I know that this name has been the same for a while.

But I think something like `stopAndMaybeSaveState` is better is it will only save state if the indexer is NOT already shutting down + the indexer stopped.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java [hunk 3]
```diff
@@ -363,10 +363,7 @@ public synchronized void stop(boolean force, boolean shouldStopAtCheckpoint) {
         // or has yet to even start one.
         // Either way, this means that we won't get to have onFinish called down stream (or at least won't for some time).
             (indexerState == IndexerState.STARTED && getIndexer().initialRun())) {
-            IndexerState state = getIndexer().stop();
-            if (state == IndexerState.STOPPED) {
-                getIndexer().stopAndSaveState();
-            }
+            getIndexer().stopAndSaveState();
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:366]: 👍

**Review by benwtrent — APPROVED** [review]

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerTests.java [hunk 4]
```diff
@@ -214,7 +223,21 @@ protected void doNextBulk(BulkRequest request, ActionListener<BulkResponse> next
 
         @Override
         protected void doSaveState(IndexerState state, TransformIndexerPosition position, Runnable next) {
+            // assert that the indexer does not call doSaveState again, while its still saving state
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerTests.java:226]:
```suggestion
            // assert that the indexer does not call doSaveState again, while it is still saving state
```

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerTests.java [hunk 5]
```diff
@@ -214,7 +223,21 @@ protected void doNextBulk(BulkRequest request, ActionListener<BulkResponse> next
...
+            // this is only useful togehter with the doSaveStateLatch
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerTests.java:227]:
```suggestion
            // this is only useful together with the doSaveStateLatch
```

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerTests.java [hunk 6]
```diff
@@ -340,6 +363,63 @@ public void testRetentionPolicyExecution() throws Exception {
         }
     }
 
+    /**
+     * This test ensures correct handling of async behavior during indexer shutdown
+     *
+     * Indexer shutdown is not atomic: 1st the state is set back to e.g. STARTED, afterwards state is stored.
+     * State is stored async and is IO based, there it can take time until this is done.
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformIndexerTests.java:370]:
```suggestion
     * State is stored async and is IO based, therefore it can take time until this is done.
```

**Review by przemekwitek — APPROVED** [review]
LGTM
