### PR TITLE
Set lower bound on DLM retention in tests

### LINKED ISSUE #134276: [CI] DataStreamAndIndexLifecycleMixingTests testUpdateIndexTemplateToDataStreamLifecyclePreference failing
**Build Scans:**
- [elasticsearch-periodic #10506 / openjdk23_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/odxzxe22gc2qs)
- [elasticsearch-intake #27942 / part2](https://gradle-enterprise.elastic.co/s/3rbhbvisigegm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ilm:internalClusterTest" --tests "org.elasticsearch.xpack.ilm.DataStreamAndIndexLifecycleMixingTests.testUpdateIndexTemplateToDataStreamLifecyclePreference" -Dtests.seed=DAC0241E6B380204 -Dtests.locale=raj-Deva-IN -Dtests.timezone=Australia/Tasmania -Druntime.java=23
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.DataStreamAndIndexLifecycleMixingTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testUpdateIndexTemplateToDataStreamLifecyclePreference'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
```

**Issue Reasons:**
- [8.19] 2 failures in test testUpdateIndexTemplateToDataStreamLifecyclePreference (0.5% fail rate in 377 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nielsbauman**
The previous randomization logic in these tests could result in a retention sufficiently short enough for the index to (unexpectedly) be deleted by DLM during the test, resulting in a failure.

Fixes #134276

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java [hunk 1]
```diff
@@ -1422,6 +1422,20 @@ public static TimeValue randomPositiveTimeValue() {
         return randomTimeValue(1, 1000);
     }
 
+    /**
+     * Generate a random TimeValue that is at least the provided timeValue.
+     * Chooses a random TimeUnit, adds between 0 and 1000 of that unit to {@code timeValue}, and returns a TimeValue in that unit.
+     */
+    public static TimeValue randomTimeValueOfAtLeast(TimeValue timeValue) {
```
Comment (PeteGillinElastic) [inline test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: Nit: Can we give the parameter a more meaningful name, like `lowerBound`?

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java [hunk 2]
```diff
@@ -1422,6 +1422,20 @@ public static TimeValue randomPositiveTimeValue() {
...
+        final var randomUnit = randomFrom(TimeUnit.values());
+        long lowerBound = timeValue.getMillis();
```
Comment (PeteGillinElastic) [inline test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: This isn't going to work if `timeValue` is in nanos or micros. If e.g. you ask for a `randomTimeValueOfAtLeast(timeValueMicros(500))` you could still get a value less than that: `lowerBound` will be zero, so if `randomUnit` is nanos then you'll definitely violate your method contract, and if it's micros then you have a 50:50 chance of doing so. Something similar happens with e.g. `timeValueMicros(2500)`.

I don't know how much effort we want to put into polishing this test-only utility method. I don't think I'm comfortable with something that might silently fail to do what it says it'll do, though, as that could be really confusing to someone in the future. There are easy options like checking `timeValue.timeUnit()` and throwing an `IllegalArgumentException` (and documenting that it's not supported), or replacing this method with e.g. `randomValueOfAtLeastSeconds(int lowerBoundSeconds)`. Both would be practically fine, but would seem a shame.

Actually doing this correctly seems frustratingly difficult, because you need to figure out the right units to do the maths in. Would it be against the spirit of things to convert to `java.time.Duration`, call `plus`, and convert back?

Alternatively, you could implement `randomTimeValueGreaterThan` more easily. Then I think you could just convert the lower bound into `randomUnit`, and add a random value between 1 and 1000. It wouldn't matter that the conversion rounds down if `randomUnit` is larger than `timeValue.timeUnit()` because you'll be adding at least one `randomUnit` to it.

Comment (PeteGillinElastic) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: For the last option I'm thinking of something like this:
```java
public static TimeValue randomTimeValueGreaterThan(TimeValue lowerBound) {
    TimeUnit randomUnit = randomUnit = randomFrom(TimeUnit.values());
    return new TimeValue(randomUnit.convert(lowerBound.timeUnit(), lowerBound.duration()) + randomLongBetween(1, 1000), randomUnit);
}
```
although n.b. I haven't tested that or thought it through too carefully, and you might want to extract at least one local variable and you probably want to add include an implementation comment explaining why the rounding is okay.

**Review by PeteGillinElastic — APPROVED** [review]
I have one comment which is awkwardly nit-picky but I still feel we need to do _something_ to avoid leaving a booby trap for someone in the future. I've given a few options. I don't want to hold this up, so I'm happy for you to pick one and merge (unless you want to push back or you feel the need for another look).

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java (hunk 2 above)
Comment (nielsbauman) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: Yeah, I thought about this too. I think I kind of dismissed it with "I don't think it's likely that someone will use this with such a low unit", and I think I forgot about it after that. I agree that it's not ideal. I like your suggestion of doing `randomTimeValueGreaterThan` instead, as that's indeed easier to implement _correctly_.

Comment (PeteGillinElastic) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: (Just adding this to help clarify my own thinking: If `lowerBound` is `timeValueSeconds(90)` and `randomUnit` is `MINUTES` then the conversion rounds 90sec down to 1min, but then we add between 1min and 1000min, so the result is between 2min and 1001min, which satisfies the requirement of being greater than 90sec. Whereas if `randomUnit` is `MILLIS` then we convert to 90,000ms and end up with between 90,001 and 91,000ms, which is also valid.)

Comment (PeteGillinElastic) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: > I think I kind of dismissed it with "I don't think it's likely that someone will use this with such a low unit"

Yeah, I agree it's not likely, but experience suggests that if you create an API in a widely-used common library then sooner or later somebody is bound to come along and use it in a way that you'd considered too weird to worry about! And it's better not to silently do something confusing and wrong when they do.

Comment (PeteGillinElastic) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: (My thing does overflow if they e.g. use a lower bound of `timeValueDays(200_000)` and `randomUnit` is `NANOSECONDS`, but I _think_ I'm okay with that?)

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java [hunk 3]
```diff
@@ -1422,6 +1422,18 @@ public static TimeValue randomPositiveTimeValue() {
         return randomTimeValue(1, 1000);
     }
 
+    /**
+     * Generate a random TimeValue that is at least the provided timeValue.
```
Comment (PeteGillinElastic) [inline test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: Nit: Greater than (if you can be bothered).

**Review by PeteGillinElastic — APPROVED** [review]

**Comment by PeteGillinElastic** [comment]
Thanks!

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java (hunk 3 above)
Comment (nielsbauman) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: Good catch!

**Comment by nielsbauman** [comment]
Thanks for the review, Pete!

**Comment by nielsbauman** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/135088)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
