### PR TITLE
Check if the index can be opened and is not corrupted on state listing

### LINKED ISSUE #11226: CorruptedFileTest#testReplicaCorruption fails
This test fails since we get into a cycle of trying to recover the primary from replica 1 and replica 2 which are corrupted, and never end up reaching the non corrupted previous primary shard

### PR DESCRIPTION
**Pull request by s1monw**
We fetch the state version to find the right shard to be started as
the primary. This can return a valid shard state even if the shard is
corrupted and can't even be opened. This commit adds best effort detection
for this scenario and returns an invalid version for the shard if it's corrupted

Closes #11226

### CODE REVIEW

**Comment by s1monw** [comment]
@kimchy can you look

File: src/main/java/org/elasticsearch/index/store/Store.java [hunk 1]
```diff
@@ -383,6 +383,21 @@ public static MetadataSnapshot readMetadataSnapshot(Path indexLocation, ESLogger
...
+     * Returns <code>true</code> iff the given location contains an index an the index
+     * can be successfully opened. This includes reading the segment infos and possible
+     * corruption markers.
+     */
+    public static boolean canOpenIndex(Path indexLocation) throws IOException {
+        try (Directory dir = new SimpleFSDirectory(indexLocation)) {
+            failIfCorrupted(dir, new ShardId("", 1));
+            Lucene.readSegmentInfos(dir);
+            return true;
+        } catch (Exception ex) {
```
Comment (bleskes) [inline src/main/java/org/elasticsearch/index/store/Store.java]: cat we add a trace log here with the exception? Thinking it might be helpful to be able to know why...

File: src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java [hunk 2]
```diff
@@ -125,6 +129,18 @@ protected NodeGatewayStartedShards nodeOperation(NodeRequest request) {
         }
     }
 
+    private boolean canOpenIndex(ShardId shardId, IndexMetaData metaData) throws IOException {
+        // try and see if we an list unallocated
+        if (metaData == null) {
```
Comment (bleskes) [inline src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java]: this is unneeded? we check before we call...

**Comment by bleskes** [comment]
LGTM (left two minor comments).

File: src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java (hunk 2 above)
Comment (s1monw) [inline src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java]: I like the method to be self sufficient to that's why I did that

**Comment by s1monw** [comment]
pushed a new commit - I will push that to master soon
