### PR TITLE
[Entitlements] Fix PolicyUtils and PolicyUtilsTests on Windows

### LINKED ISSUE #126176: [CI] PolicyUtilsTests testFormatFilesEntitlement failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7434 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/6qwkajyj5w7vq)
- [elasticsearch-pull-request #66116 / part-1-windows](https://gradle-enterprise.elastic.co/s/bl3ui66kqkk74)
- [elasticsearch-periodic-platform-support #7427 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/4z72gv7kopxqi)
- [elasticsearch-periodic-platform-support #7420 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/m6uzw4iy77vec)
- [elasticsearch-periodic-platform-support #7413 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/nrdptx3mc5skk)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.PolicyUtilsTests.testFormatFilesEntitlement" -Dtests.seed=C3B0E40F6B977013 -Dtests.locale=ln-CF -Dtests.timezone=America/Los_Angeles -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.PolicyUtilsTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testFormatFilesEntitlement),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: iterable with items ["files [READ_WRITE] \\a\\b", "files [READ] <DATA>/c/d", "files [READ] <DATA>/<setting>"] in any order
     but: not matched: "files [READ_WRITE] C:\\a\\b"
```

**Issue Reasons:**
- [main] 4 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [main] 5 failures in test testFormatFilesEntitlement (2.4% fail rate in 211 executions)
- [main] 4 failures in step windows-2022_checkpart1_platform-support-windows (100.0% fail rate in 4 executions)
- [main] 4 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ldematte**
This PR fixes 2 issues discovered around PolicyUtils (and PolicyUtilsTests) when running CI on Windows:
1. in tests, absolute paths like always are different, this fix updates the tests to account for the difference.
2. on Windows, Files.move was failing because we were parsing the Entitlement policy but not closing the stream in a timely manner. This causes plugin installation (and related CI tests) to fail 70% of the time. Fixed by closing the stream properly

Fixes https://github.com/elastic/elasticsearch/issues/126176

### CODE REVIEW

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/entitlements/FilesEntitlement.java [hunk 1]
```diff
@@ -160,7 +163,7 @@ public FileData withPlatform(Platform platform) {
 
         @Override
         public String description() {
-            return Strings.format("[%s] <%s>/%s%s", mode, baseDir, relativePath, exclusive ? " (exclusive)" : "");
+            return Strings.format("[%s] <%s>%s%s%s", mode, baseDir, SEPARATOR, relativePath, exclusive ? " (exclusive)" : "");
```
Comment (prdoyle) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/entitlements/FilesEntitlement.java:166]: What's the significance of this?

**Review by prdoyle — APPROVED** [review]

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/entitlements/FilesEntitlement.java (hunk 1 above)
Comment (ldematte) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/runtime/policy/entitlements/FilesEntitlement.java:166]: To have separators consistent in the output; on Windows that was looking weird, like `<DATA>/c\d`
This is more cosmetic, but since I fixed the assertion I wanted it to be consistent too.
