### PR TITLE
[Test] Adjust assertions ReloadSecureSettings test for FIPS jvm

### LINKED ISSUE #66880: ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT failures in fips mode
**Build scan**:

https://gradle-enterprise.elastic.co/s/27nxkh3jeyqzm/console-log?task=:x-pack:qa:password-protected-keystore:integTest

**Repro line**:

```
./gradlew ':x-pack:qa:password-protected-keystore:integTest' --tests "org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.testReloadSecureSettingsWithEmptyPassword" -Dtests.seed=779930CF4BC9CD9C -Dtests.security.manager=true -Dtests.locale=sl-SI -Dtests.timezone=America/Hermosillo -Druntime.java=11 -Dtests.fips.enabled=true |  
```

**Reproduces locally?**: yes

**Applicable branches**:

**Failure history**:

**Failure excerpt**:

```
org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT > testReloadSecureSettingsWithEmptyPassword FAILED
    java.lang.AssertionError: 
    Expected: ("Provided keystore password was incorrect" or "Keystore has been corrupted or tampered with")
         but: was "Error generating an encryption key from the provided password"
        at __randomizedtesting.SeedInfo.seed([779930CF4BC9CD9C:39F40225962A5FBB]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.password_protected_keystore.ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.testReloadSecureSettingsWithEmptyPassword(ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.java:80)
```

An exception with "Error generating an encryption key from the provided password" message can now  be thrown in fips mode when a password is short so we need to adjust the matcher when in fips mode

### PR DESCRIPTION
**Pull request by ywangd**
When the JVM is configured to be in FIPS mode, the reload security settings API returns a different error message that is specific to FIPS when given an empty password. This PR adjust the assertions so that they are matched correspondingly.

Resolves: #66880

### CODE REVIEW

File: x-pack/qa/password-protected-keystore/src/test/java/org/elasticsearch/password_protected_keystore/ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.java [hunk 1]
```diff
@@ -78,10 +78,16 @@ public void testReloadSecureSettingsWithEmptyPassword() throws Exception {
             assertThat(entry.getValue(), instanceOf(Map.class));
             final Map<String, Object> node = (Map<String, Object>) entry.getValue();
             assertThat(node.get("reload_exception"), instanceOf(Map.class));
-            assertThat(ObjectPath.eval("reload_exception.reason", node), anyOf(
-                equalTo("Provided keystore password was incorrect"),
-                equalTo("Keystore has been corrupted or tampered with")));
-            assertThat(ObjectPath.eval("reload_exception.type", node), equalTo("security_exception"));
+            if (inFipsJvm()) {
```
Comment (jkakavas) [inline x-pack/qa/password-protected-keystore/src/test/java/org/elasticsearch/password_protected_keystore/ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.java:81]: The "keystore is tampered with is also thrown in fips, see https://github.com/elastic/elasticsearch/pull/57050

File: x-pack/qa/password-protected-keystore/src/test/java/org/elasticsearch/password_protected_keystore/ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.java [hunk 2]
```diff
@@ -78,10 +78,16 @@ public void testReloadSecureSettingsWithEmptyPassword() throws Exception {
...
+                assertThat(ObjectPath.eval("reload_exception.reason", node), containsString(
+                    "Error generating an encryption key from the provided password"));
+                assertThat(ObjectPath.eval("reload_exception.type", node), equalTo("general_security_exception"));
+            } else {
+                assertThat(ObjectPath.eval("reload_exception.reason", node), anyOf(
+                    equalTo("Provided keystore password was incorrect"),
+                    equalTo("Keystore has been corrupted or tampered with")));
+                assertThat(ObjectPath.eval("reload_exception.type", node), equalTo("security_exception"));
+            }
```
Comment (tvernum) [inline x-pack/qa/password-protected-keystore/src/test/java/org/elasticsearch/password_protected_keystore/ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.java:90]: I'm not convinced that we actually care about FIPS vs non-FIPS here do we?
Why wouldn't we just have:
```suggestion
            assertThat(ObjectPath.eval("reload_exception.reason", node), anyOf(
                equalTo("Provided keystore password was incorrect"),
                equalTo("Keystore has been corrupted or tampered with"),
                containsString("Error generating an encryption key from the provided password") // FIPS
            ));
            assertThat(ObjectPath.eval("reload_exception.type", node), 
                // Depends on exact security provider (eg Sun vs BCFIPS)
                anyOf(equalTo("security_exception"), equalTo("general_security_exception"))
            );
```

File: x-pack/qa/password-protected-keystore/src/test/java/org/elasticsearch/password_protected_keystore/ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.java (hunk 1 above)
Comment (ywangd) [reply x-pack/qa/password-protected-keystore/src/test/java/org/elasticsearch/password_protected_keystore/ReloadSecureSettingsWithPasswordProtectedKeystoreRestIT.java:81]: For this specific case, i.e. empty password, the error message should always be 
`Error generating an encryption key from the provided password` because it is generated without even reading the keystore file as opposed to other error messages. With this being said, I like @tvernum's suggestion as well. So we are settled here.

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@albertzaharovits @BigPandaToo I added more people as reviewers since I wasn't sure who would be around to help it out. But I really just need one approval for this simple change. Given @tvernum has approved it, I am going to merge it without further delay. Thanks!
