### PR TITLE
Move in-progress snapshot and restore information from custom metadata to custom cluster state part

### LINKED ISSUE #8102: snapshot should work when cluster is in read_only mode.
I was trying to make a full, consistent backup before an upgrade.  Snapshots are at a moment of time, which doesn't work if clients are still updating your indexes.

I tried putting the cluster into read_only mode by setting cluster.blocks.read_only: true, but running a snapshot returned this error:

    {"error":"ClusterBlockException[blocked by: [FORBIDDEN/6/cluster read-only (api)];]","status":403}

Please consider allowing snapshots to provide a consistent backup by running when in read-only mode.

### PR DESCRIPTION
**Pull request by imotov**
Information about in-progress snapshot and restore processes is not really metadata and should be represented as a part of the cluster state similar to discovery nodes, routing table, and cluster blocks. Since in-progress snapshot and restore information is no longer part of metadata, this refactoring also enables us to handle cluster blocks in more consistent manner and allow creation of snapshots of a read-only cluster.

Closes #8102

### CODE REVIEW

File: src/main/java/org/elasticsearch/cluster/ClusterState.java [hunk 1]
```diff
@@ -249,6 +253,10 @@ public ClusterBlocks getBlocks() {
         return this.customs;
     }
 
+    public <T extends Custom> T custom(String type) {
+        return (T) customs.get(type);
```
Comment (dakrone) [inline src/main/java/org/elasticsearch/cluster/ClusterState.java]: I'm a little fuzzy on this, why do we need to get it out of the `customs` map instead of using the `customPrototype` and getting it there?

Comment (dakrone) [inline src/main/java/org/elasticsearch/cluster/ClusterState.java]: Or, just calling `.customs().get("mycustom")`

Comment (imotov) [inline src/main/java/org/elasticsearch/cluster/ClusterState.java]: `customPrototype` contains a list of dummy (prototype) objects that are used for deserialization when we don't have a concrete implementation to diff against. It is static and changes only when a component needs to register another custom object. In other words you can think of `customPrototypes` as factories. The `custom` map contains the actual objects that are part of the cluster state. 

We could use `.customs().get("mycustom")` but it would return us objects with type `Custom` that we would have to later cast to concrete custom types. This is a convenience method that does this cast for us, so later we can write something like:
```
SnapshotsInProgress snapshotsInProgress = allocation.routingNodes().custom(SnapshotsInProgress.TYPE);
```
instead of
```
SnapshotsInProgress snapshotsInProgress = (SnapshotsInProgress) allocation.routingNodes().custom().get(SnapshotsInProgress.TYPE);
```

**Comment by imotov** [comment]
@dakrone I rebased and pushed the new version. Could you review when you have a chance?

File: core/src/test/java/org/elasticsearch/action/admin/cluster/snapshots/SnapshotBlocksTests.java [hunk 2]
```diff
@@ -126,17 +126,13 @@ public void testCreateSnapshotWithIndexBlocks() {
 
     @Test
     public void testDeleteSnapshotWithBlocks() {
-        logger.info("-->  deleting a snapshot is blocked when the cluster is read only");
+        logger.info("-->  deleting a snapshot is allowed when the cluster is read only");
```
Comment (dakrone) [inline core/src/test/java/org/elasticsearch/action/admin/cluster/snapshots/SnapshotBlocksTests.java]: I understand why we would allow creating a snapshot when the cluster is read-only, but it seems backwards to allow deleting a snapshot, should we document this somewhere in the snapshot & restore documentation?

File: core/src/test/java/org/elasticsearch/cluster/ClusterStateDiffTests.java [hunk 3]
```diff
@@ -245,6 +247,56 @@ private ClusterBlock randomGlobalBlock() {
...
+        T randomCreate(String name);
+
+        /**
+         * Makes random modifications to the part
+         */
+        T randomChange(T part);
+
+    }
+
+    private <T> ClusterState randomClusterStateParts(ClusterState clusterState, String prefix, RandomClusterPart<T> randomPart) {
```
Comment (dakrone) [inline core/src/test/java/org/elasticsearch/cluster/ClusterStateDiffTests.java]: Can you add javadoc for what this function is doing?

File: core/src/test/java/org/elasticsearch/cluster/ClusterStateDiffTests.java [hunk 4]
```diff
@@ -498,33 +546,66 @@ private MetaData randomMetaDataCustoms(final MetaData metaData) {
...
+            }
+
+            @Override
+            public MetaData.Custom randomChange(MetaData.Custom part) {
+                return part;
+            }
+        });
+    }
+
+    private ClusterState.Builder randomClusterStateCustoms(final ClusterState clusterState) {
```
Comment (dakrone) [inline core/src/test/java/org/elasticsearch/cluster/ClusterStateDiffTests.java]: Same here, needs javadocs

File: core/src/test/java/org/elasticsearch/cluster/ClusterStateDiffTests.java (hunk 3 above)
Comment (dakrone) [inline core/src/test/java/org/elasticsearch/cluster/ClusterStateDiffTests.java]: Or just a regular comment is fine.

**Comment by dakrone** [comment]
Left a couple of really minor comments, otherwise LGTM
