### PR TITLE
Fix standard filter BWC check to allow for cacheing bug

### LINKED ISSUE #62644: Standard token filter can still appear in indices created in 7x
Indices that try to use a standard token filter in 7x are supposed to fail. However this detection was broken in previous versions of Elasticsearch (from 7.0 to 7.5) due to a bug, so some indices in 7x may still declare a standard token version that when upgraded to a version with the fix (>=7.6.0) causes issues in the cluster (the index fails to open). I am opening this issue to discuss the possible solutions to fix this discrepancy automatically for users. One solution for instance could be to ignore all `standard` token filter if they are on an index created before the last fix.

### PR DESCRIPTION
**Pull request by romseygeek**
The `standard` tokenfilter was removed by #33310, and should have been 
unuseable in any indexes created since 7.0.  However, a cacheing bug fixed 
by #51092 meant that it was still possible in certain circumstances to create
indexes referencing the `standard` filter in versions up to 7.5.2.  Our checks
in `AnalysisModule` still refer to 7.0.0, however, meaning that a cluster that
contains one of these rogue indexes cannot be upgraded.

This commit adjusts the AnalysisModule checks so that we only refuse to
build a mapping referring to `standard` filter if the index created version is
7.6 or later.

Fixes #62644

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/analysis/AnalysisModule.java [hunk 1]
```diff
@@ -181,7 +181,7 @@ public boolean requiresAnalysisSettings() {
         // Add "standard" for old indices (bwc)
         preConfiguredTokenFilters.register( "standard",
             PreConfiguredTokenFilter.elasticsearchVersion("standard", true, (reader, version) -> {
-                if (version.before(Version.V_7_0_0)) {
+                if (version.before(Version.V_7_6_0)) {
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/indices/analysis/AnalysisModule.java:184]: Can you add a comment here so that we don't forget why it's 7.6 and not 7.0 ?

**Review by jimczi — APPROVED** [review]
I left one comment. Thanks for tackling this so quickly!

**Comment by romseygeek** [comment]
@elasticmachine update branch
