### PR TITLE
Fix `testFollowIndexAndCloseNode`

### LINKED ISSUE #111941: [CI] FollowerFailOverIT testFollowIndexAndCloseNode failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #3757 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/grljzlhhsrcne)
- [elasticsearch-periodic-platform-support #3751 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/rd37bzg47r3x6)

**Reproduction Line:**
```
./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.FollowerFailOverIT.testFollowIndexAndCloseNode" -Dtests.seed=333DBDFDD778F34 -Dtests.locale=es-BO -Dtests.timezone=Australia/Victoria -Druntime.java=22
```

**Applicable branches:**
7.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testFollowIndexAndCloseNode'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ccr.FollowerFailOverIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: mismatched documents [{}]
Expected: <{0=[doc{id='NabXV5EB9g0jrMLt8Hiz seqNo=0 primaryTerm=1 version=1 source= {"f":1}}, doc{id='N6bXV5EB9g0jrMLt8Hi8 seqNo=1 primaryTerm=1 version=1 source= {"f":3}}, doc{id='OKbXV5EB9g0jrMLt8Hi- seqNo=2 primaryTerm=1 version=1 source= {"f":4}}, doc{id='O6bXV5EB9g0jrMLt8HjE seqNo=3 primaryTerm=1 version=1 source= {"f":7}}, doc{id='PqbXV5EB9g0jrMLt8HjK seqNo=4 primaryTerm=1 version=1 source= {"f":10}}, doc{id='P6bXV5EB9g0jrMLt8HjM seqNo=5 primaryTerm=1 version=1 source= {"f":11}}, doc{id='QKbXV5EB9g0jrMLt8HjO seqNo=6 primaryTerm=1 version=1 source= {"f":12}}, doc{id='QqbXV5EB9g0jrMLt8HjR seqNo=7 primaryTerm=1 version=1 source= {"f":14}}, doc{id='S6bXV5EB9g0jrMLt8Hjf seqNo=8 primaryTerm=1 version=1 source= {"f":23}}, doc{id='TqbXV5EB9g0jrMLt8Hjk seqNo=9 primaryTerm=1 version=1 source= {"f":26}}, doc{id='UabXV5EB9g0jrMLt8Hjp seqNo=10 primaryTerm=1 version=1 source= {"f":29}}, doc{id='U6bXV5EB9g0jrMLt8Hjs seqNo=11 primaryTerm=1 version=1 source= {"f":31}}, doc{id='WqbXV5EB9g0jrMLt8Hj8 seqNo=12 primaryTerm=1 version=1 source= {"f":38}}, doc{id='XqbXV5EB9g0jrMLt8XgC seqNo=13 primaryTerm=1 version=1 source= {"f":42}}, doc{id='YabXV5EB9g0jrMLt8XgG seqNo=14 primaryTerm=1 version=1 source= {"f":45}}, doc{id='Y6bXV5EB9g0jrMLt8XgK seqNo=15 primaryTerm=1 version=1 source= {"f":47}}, doc{id='Z6bXV5EB9g0jrMLt8XgQ seqNo=16 primaryTerm=1 version=1 source= {"f":51}}, doc{id='a6bXV5EB9g0jrMLt8XgW seqNo=17 primaryTerm=1 version=1 source= {"f":55}}, doc{id='bKbXV5EB9g0jrMLt8XgY seqNo=18 primaryTerm=1 version=1 source= {"f":56}}, doc{id='babXV5EB9g0jrMLt8Xga seqNo=19 primaryTerm=1 version=1 source= {"f":57}}, doc{id='b6bXV5EB9g0jrMLt8Xgd seqNo=20 primaryTerm=1 version=1 source= {"f":59}}, doc{id='c6bXV5EB9g0jrMLt8Xgl seqNo=21 primaryTerm=1 version=1 source= {"f":63}}, doc{id='dabXV5EB9g0jrMLt8Xgo seqNo=22 primaryTerm=1 version=1 source= {"f":65}}, doc{id='d6bXV5EB9g0jrMLt8Xgr seqNo=23 primaryTerm=1 version=1 source= {"f":67}}, doc{id='eKbXV5EB9g0jrMLt8Xgs seqNo=24 primaryTerm=1 version=1 source= {"f":68}}, doc{id='e6bXV5EB9g0jrMLt8Xgw seqNo=25 primaryTerm=1 version=1 source= {"f":71}}, doc{id='gKbXV5EB9g0jrMLt8Xg4 seqNo=26 primaryTerm=1 version=1 source= {"f":76}}, doc{id='gabXV5EB9g0jrMLt8Xg6 seqNo=27 primaryTerm=1 version=1 source= {"f":77}}, doc{id='g6bXV5EB9g0jrMLt8Xg8 seqNo=28 primaryTerm=1 version=1 source= {"f":79}}, doc{id='i6bXV5EB9g0jrMLt8XhI seqNo=29 primaryTerm=1 version=1 source= {"f":87}}, doc{id='jabXV5EB9g0jrMLt8XhK seqNo=30 primaryTerm=1 version=1 source= {"f":89}}, doc{id='kabXV5EB9g0jrMLt8XhQ seqNo=31 primaryTerm=1 version=1 source= {"f":93}}, doc{id='l6bXV5EB9g0jrMLt8XhY seqNo=32 primaryTerm=1 version=1 source= {"f":99}}, doc{id='mabXV5EB9g0jrMLt8Xhb seqNo=33 primaryTerm=1 version=1 source= {"f":101}}, doc{id='m6bXV5EB9g0jrMLt8Xhd seqNo=34 primaryTerm=1 version=1 source= {"f":103}}, doc{id='nabXV5EB9g0jrMLt8Xhh seqNo=35 primaryTerm=1 version=1 source= {"f":105}}, doc{id='pqbXV5EB9g0jrMLt8Xh0 seqNo=36 primaryTerm=1 version=1 source= {"f":114}}, doc{id='p6bXV5EB9g0jrMLt8Xh4 seqNo=37 primaryTerm=1 version=1 source= {"f":115}}, doc{id='qabXV5EB9g0jrMLt8Xh8 seqNo=38 primaryTerm=1 version=1 source= {"f":117}}, doc{id='qqbXV5EB9g0jrMLt8Xh- seqNo=39 primaryTerm=1 version=1 source= {"f":118}}, doc{id='r6bXV5EB9g0jrMLt8XiF seqNo=40 primaryTerm=1 version=1 source= {"f":123}}, doc{id='sabXV5EB9g0jrMLt8XiI seqNo=41 primaryTerm=1 version=1 source= {"f":125}}, doc{id='tqbXV5EB9g0jrMLt8XiQ seqNo=42 primaryTerm=1 version=1 source= {"f":130}}, doc{id='vabXV5EB9g0jrMLt8Xia seqNo=43 primaryTerm=1 version=1 source= {"f":137}}, doc{id='wKbXV5EB9g0jrMLt8Xif seqNo=44 primaryTerm=1 version=1 source= {"f":140}}, doc{id='wqbXV5EB9g0jrMLt8Xii seqNo=45 primaryTerm=1 version=1 source= {"f":142}}, doc{id='x6bXV5EB9g0jrMLt83gh seqNo=46 primaryTerm=1 version=1 source= {"f":147}}, doc{id='yqbXV5EB9g0jrMLt83gn seqNo=47 primaryTerm=1 version=1 source= {"f":150}}, doc{id='zabXV5EB9g0jrMLt83gu seqNo=48 primaryTerm=1 version=1 source= {"f":153}}, doc{id='zqbXV5EB9g0jrMLt83gw seqNo=49 primaryTerm=1 version=1 source= {"f":154}}, doc{id='1qbXV5EB9g0jrMLt83g_ seqNo=50 primaryTerm=1 version=1 source= {"f":162}}, doc{id='3qbXV5EB9g0jrMLt83hN seqNo=51 primaryTerm=1 version=1 source= {"f":170}}, doc{id='36bXV5EB9g0jrMLt83hP seqNo=52 primaryTerm=1 version=1 source= {"f":171}}, doc{id='56bXV5EB9g0jrMLt83hd seqNo=53 primaryTerm=1 version=1 source= {"f":179}}, doc{id='66bXV5EB9g0jrMLt83hl seqNo=54 primaryTerm=1 version=1 source= {"f":183}}, doc{id='8abXV5EB9g0jrMLt83hy seqNo=55 primaryTerm=1 version=1 source= {"f":189}}, doc{id='9KbXV5EB9g0jrMLt83h3 seqNo=56 primaryTerm=1 version=1 source= {"f":192}}, doc{id='-KbXV5EB9g0jrMLt83h9 seqNo=57 primaryTerm=1 version=1 source= {"f":196}}, doc{id='-abXV5EB9g0jrMLt83h_ seqNo=58 primaryTerm=1 version=1 source= {"f":197}}, doc{id='-6bXV5EB9g0jrMLt83iE seqNo=59 primaryTerm=1 version=1 source= {"f":199}}, doc{id='_6bXV5EB9g0jrMLt83iP seqNo=60 primaryTerm=1 version=1 source= {"f":203}}, doc{id='AabXV5EB9g0jrMLt83mT seqNo=61 primaryTerm=1 version=1 source= {"f":205}}, doc{id='BKbXV5EB9g0jrMLt83mZ seqNo=62 primaryTerm=1 version=1 source= {"f":208}}, doc{id='BqbXV5EB9g0jrMLt83mc seqNo=63 primaryTerm=1 version=1 source= {"f":210}}, doc{id='B6bXV5EB9g0jrMLt83md seqNo=64 primaryTerm=1 version=1 source= {"f":211}}, doc{id='CabXV5EB9g0jrMLt83mg seqNo=65 primaryTerm=1 version=1 source= {"f":213}}, doc{id='C6bXV5EB9g0jrMLt83mj seqNo=66 primaryTerm=1 version=1 source= {"f":215}}, doc{id='D6bXV5EB9g0jrMLt83mq seqNo=67 primaryTerm=1 version=1 source= {"f":219}}, doc{id='EabXV5EB9g0jrMLt83mu seqNo=68 primaryTerm=1 version=1 source= {"f":221}}, doc{id='G6bXV5EB9g0jrMLt83m7 seqNo=69 primaryTerm=1 version=1 source= {"f":231}}, doc{id='H6bXV5EB9g0jrMLt83nC seqNo=70 primaryTerm=1 version=1 source= {"f":235}}, doc{id='IKbXV5EB9g0jrMLt83nF seqNo=71 primaryTerm=1 version=1 source= {"f":236}}, doc{id='IabXV5EB9g0jrMLt83nH seqNo=72 primaryTerm=1 version=1 source= {"f":237}}, doc{id='I6bXV5EB9g0jrMLt83nP seqNo=73 primaryTerm=1 version=1 source= {"f":239}}, doc{id='KqbXV5EB9g0jrMLt83ng seqNo=74 primaryTerm=1 version=1 source= {"f":246}}, doc{id='LabXV5EB9g0jrMLt9HkD seqNo=75 primaryTerm=1 version=1 source= {"f":249}}, doc{id='LqbXV5EB9g0jrMLt9HkF seqNo=76 primaryTerm=1 version=1 source= {"f":250}}, doc{id='MKbXV5EB9g0jrMLt9HkI seqNo=77 primaryTerm=1 version=1 source= {"f":252}}, doc{id='MabXV5EB9g0jrMLt9HkK seqNo=78 primaryTerm=1 version=1 source= {"f":253}}, doc{id='M6bXV5EB9g0jrMLt9HkN seqNo=79 primaryTerm=1 version=1 source= {"f":255}}, doc{id='NqbXV5EB9g0jrMLt9HkS seqNo=80 primaryTerm=1 version=1 source= {"f":258}}, doc{id='OabXV5EB9g0jrMLt9HkY seqNo=81 primaryTerm=1 version=1 source= {"f":261}}, doc{id='OqbXV5EB9g0jrMLt9Hka seqNo=82 primaryTerm=1 version=1 source= {"f":262}}, doc{id='O6bXV5EB9g0jrMLt9Hkd seqNo=83 primaryTerm=1 version=1 source= {"f":263}}, doc{id='P6bXV5EB9g0jrMLt9Hkl seqNo=84 primaryTerm=1 version=1 source= {"f":267}}, doc{id='S6bXV5EB9g0jrMLt9HlA seqNo=85 primaryTerm=1 version=1 source= {"f":279}}, doc{id='TKbXV5EB9g0jrMLt9HlC seqNo=86 primaryTerm=1 version=1 source= {"f":280}}, doc{id='TabXV5EB9g0jrMLt9HlD seqNo=87 primaryTerm=1 version=1 source= {"f":281}}, doc{id='T6bXV5EB9g0jrMLt9HlG seqNo=88 primaryTerm=1 version=1 source= {"f":283}}, doc{id='UKbXV5EB9g0jrMLt9HlH seqNo=89 primaryTerm=1 version=1 source= {"f":284}}], 1=[doc{id='NqbXV5EB9g0jrMLt8Hi5 seqNo=0 primaryTerm=1 version=1 source= {"f":2}}, doc{id='OabXV5EB9g0jrMLt8Hi_ seqNo=1 primaryTerm=1 version=1 source= {"f":5}}, doc{id='PabXV5EB9g0jrMLt8HjI seqNo=2 primaryTerm=1 version=1 source= {"f":9}}, doc{id='RqbXV5EB9g0jrMLt8HjX seqNo=3 primaryTerm=1 version=1 source= {"f":18}}, doc{id='SqbXV5EB9g0jrMLt8Hjd seqNo=4 primaryTerm=1 version=1 source= {"f":22}}, doc{id='TabXV5EB9g0jrMLt8Hjj seqNo=5 primaryTerm=1 version=1 source= {"f":25}}, doc{id='T6bXV5EB9g0jrMLt8Hjm seqNo=6 primaryTerm=1 version=1 source= {"f":27}}, doc{id='UqbXV5EB9g0jrMLt8Hjr seqNo=7 primaryTerm=1 version=1 source= {"f":30}}, doc{id='VKbXV5EB9g0jrMLt8Hjt seqNo=8 primaryTerm=1 version=1 source= {"f":32}}, doc{id='VabXV5EB9g0jrMLt8Hjv seqNo=9 primaryTerm=1 version=1 source= {"f":33}}, doc{id='VqbXV5EB9g0jrMLt8Hjw seqNo=10 primaryTerm=1 version=1 source= {"f":34}}, doc{id='V6bXV5EB9g0jrMLt8Hjx seqNo=11 primaryTerm=1 version=1 source= {"f":35}}, doc{id='XKbXV5EB9g0jrMLt8Hj_ seqNo=12 primaryTerm=1 version=1 source= {"f":40}}, doc{id='ZqbXV5EB9g0jrMLt8XgO seqNo=13 primaryTerm=1 version=1 source= {"f":50}}, doc{id='aabXV5EB9g0jrMLt8XgT seqNo=14 primaryTerm=1 version=1 source= {"f":53}}, doc{id='aqbXV5EB9g0jrMLt8XgV seqNo=15 primaryTerm=1 version=1 source= {"f":54}}, doc{id='cKbXV5EB9g0jrMLt8Xgf seqNo=16 primaryTerm=1 version=1 source= {"f":60}}, doc{id='cqbXV5EB9g0jrMLt8Xgj seqNo=17 primaryTerm=1 version=1 source= {"f":62}}, doc{id='fabXV5EB9g0jrMLt8Xgz seqNo=18 primaryTerm=1 version=1 source= {"f":73}}, doc{id='hKbXV5EB9g0jrMLt8Xg- seqNo=19 primaryTerm=1 version=1 source= {"f":80}}, doc{id='h6bXV5EB9g0jrMLt8XhD seqNo=20 primaryTerm=1 version=1 source= {"f":83}}, doc{id='iabXV5EB9g0jrMLt8XhG seqNo=21 primaryTerm=1 version=1 source= {"f":85}}, doc{id='jqbXV5EB9g0jrMLt8XhM seqNo=22 primaryTerm=1 version=1 source= {"f":90}}, doc{id='j6bXV5EB9g0jrMLt8XhN seqNo=23 primaryTerm=1 version=1 source= {"f":91}}, doc{id='kqbXV5EB9g0jrMLt8XhR seqNo=24 primaryTerm=1 version=1 source= {"f":94}}, doc{id='k6bXV5EB9g0jrMLt8XhT seqNo=25 primaryTerm=1 version=1 source= {"f":95}}, doc{id='labXV5EB9g0jrMLt8XhW seqNo=26 primaryTerm=1 version=1 source= {"f":97}}, doc{id='lqbXV5EB9g0jrMLt8XhX seqNo=27 primaryTerm=1 version=1 source= {"f":98}}, doc{id='mKbXV5EB9g0jrMLt8Xha seqNo=28 primaryTerm=1 version=1 source= {"f":100}}, doc{id='mqbXV5EB9g0jrMLt8Xhc seqNo=29 primaryTerm=1 version=1 source= {"f":102}}, doc{id='nKbXV5EB9g0jrMLt8Xhf seqNo=30 primaryTerm=1 version=1 source= {"f":104}}, doc{id='n6bXV5EB9g0jrMLt8Xhk seqNo=31 primaryTerm=1 version=1 source= {"f":107}}, doc{id='oabXV5EB9g0jrMLt8Xhp seqNo=32 primaryTerm=1 version=1 source= {"f":109}}, doc{id='o6bXV5EB9g0jrMLt8Xht seqNo=33 primaryTerm=1 version=1 source= {"f":111}}, doc{id='pabXV5EB9g0jrMLt8Xhx seqNo=34 primaryTerm=1 version=1 source= {"f":113}}, doc{id='rKbXV5EB9g0jrMLt8XiB seqNo=35 primaryTerm=1 version=1 source= {"f":120}}, doc{id='sKbXV5EB9g0jrMLt8XiH seqNo=36 primaryTerm=1 version=1 source= {"f":124}}, doc{id='s6bXV5EB9g0jrMLt8XiL seqNo=37 primaryTerm=1 version=1 source= {"f":127}}, doc{id='tKbXV5EB9g0jrMLt8XiM seqNo=38 primaryTerm=1 version=1 source= {"f":128}}, doc{id='tabXV5EB9g0jrMLt8XiO seqNo=39 primaryTerm=1 version=1 source= {"f":129}}, doc{id='t6bXV5EB9g0jrMLt8XiS seqNo=40 primaryTerm=1 version=1 source= {"f":131}}, doc{id='u6bXV5EB9g0jrMLt8XiX seqNo=41 primaryTerm=1 version=1 source= {"f":135}}, doc{id='vKbXV5EB9g0jrMLt8XiZ seqNo=42 primaryTerm=1 version=1 source= {"f":136}}, doc{id='vqbXV5EB9g0jrMLt8Xic seqNo=43 primaryTerm=1 version=1 source= {"f":138}}, doc{id='v6bXV5EB9g0jrMLt8Xid seqNo=44 primaryTerm=1 version=1 source= {"f":139}}, doc{id='w6bXV5EB9g0jrMLt83gU seqNo=45 primaryTerm=1 version=1 source= {"f":143}}, doc{id='xabXV5EB9g0jrMLt83gb seqNo=46 primaryTerm=1 version=1 source= {"f":145}}, doc{id='xqbXV5EB9g0jrMLt83ge seqNo=47 primaryTerm=1 version=1 source= {"f":146}}, doc{id='yKbXV5EB9g0jrMLt83gk seqNo=48 primaryTerm=1 version=1 source= {"f":148}}, doc{id='yabXV5EB9g0jrMLt83gl seqNo=49 primaryTerm=1 version=1 source= {"f":149}}, doc{id='0KbXV5EB9g0jrMLt83g1 seqNo=50 primaryTerm=1 version=1 source= {"f":156}}, doc{id='0abXV5EB9g0jrMLt83g3 seqNo=51 primaryTerm=1 version=1 source= {"f":157}}, doc{id='0qbXV5EB9g0jrMLt83g5 seqNo=52 primaryTerm=1 version=1 source= {"f":158}}, doc{id='1KbXV5EB9g0jrMLt83g8 seqNo=53 primaryTerm=1 version=1 source= {"f":160}}, doc{id='16bXV5EB9g0jrMLt83hB seqNo=54 primaryTerm=1 version=1 source= {"f":163}}, doc{id='2qbXV5EB9g0jrMLt83hG seqNo=55 primaryTerm=1 version=1 source= {"f":166}}, doc{id='26bXV5EB9g0jrMLt83hI seqNo=56 primaryTerm=1 version=1 source= {"f":167}}, doc{id='3abXV5EB9g0jrMLt83hL seqNo=57 primaryTerm=1 version=1 source= {"f":169}}, doc{id='4abXV5EB9g0jrMLt83hT seqNo=58 primaryTerm=1 version=1 source= {"f":173}}, doc{id='46bXV5EB9g0jrMLt83hX seqNo=59 primaryTerm=1 version=1 source= {"f":175}}, doc{id='6qbXV5EB9g0jrMLt83hh seqNo=60 primaryTerm=1 version=1 source= {"f":182}}, doc{id='7abXV5EB9g0jrMLt83hq seqNo=61 primaryTerm=1 version=1 source= {"f":185}}, doc{id='7qbXV5EB9g0jrMLt83hs seqNo=62 primaryTerm=1 version=1 source= {"f":186}}, doc{id='86bXV5EB9g0jrMLt83h2 seqNo=63 primaryTerm=1 version=1 source= {"f":191}}, doc{id='9abXV5EB9g0jrMLt83h5 seqNo=64 primaryTerm=1 version=1 source= {"f":193}}, doc{id='9qbXV5EB9g0jrMLt83h6 seqNo=65 primaryTerm=1 version=1 source= {"f":194}}, doc{id='96bXV5EB9g0jrMLt83h8 seqNo=66 primaryTerm=1 version=1 source= {"f":195}}, doc{id='_KbXV5EB9g0jrMLt83iG seqNo=67 primaryTerm=1 version=1 source= {"f":200}}, doc{id='_qbXV5EB9g0jrMLt83iN seqNo=68 primaryTerm=1 version=1 source= {"f":202}}, doc{id='AKbXV5EB9g0jrMLt83mR seqNo=69 primaryTerm=1 version=1 source= {"f":204}}, doc{id='A6bXV5EB9g0jrMLt83mX seqNo=70 primaryTerm=1 version=1 source= {"f":207}}, doc{id='DKbXV5EB9g0jrMLt83ml seqNo=71 primaryTerm=1 version=1 source= {"f":216}}, doc{id='DabXV5EB9g0jrMLt83mm seqNo=72 primaryTerm=1 version=1 source= {"f":217}}, doc{id='E6bXV5EB9g0jrMLt83mw seqNo=73 primaryTerm=1 version=1 source= {"f":223}}, doc{id='FabXV5EB9g0jrMLt83mz seqNo=74 primaryTerm=1 version=1 source= {"f":225}}, doc{id='F6bXV5EB9g0jrMLt83m1 seqNo=75 primaryTerm=1 version=1 source= {"f":227}}, doc{id='GKbXV5EB9g0jrMLt83m3 seqNo=76 primaryTerm=1 version=1 source= {"f":228}}, doc{id='GabXV5EB9g0jrMLt83m5 seqNo=77 primaryTerm=1 version=1 source= {"f":229}}, doc{id='HKbXV5EB9g0jrMLt83m9 seqNo=78 primaryTerm=1 version=1 source= {"f":232}}, doc{id='IqbXV5EB9g0jrMLt83nI seqNo=79 primaryTerm=1 version=1 source= {"f":238}}, doc{id='JabXV5EB9g0jrMLt83nX seqNo=80 primaryTerm=1 version=1 source= {"f":241}}, doc{id='KabXV5EB9g0jrMLt83ne seqNo=81 primaryTerm=1 version=1 source= {"f":245}}, doc{id='MqbXV5EB9g0jrMLt9HkM seqNo=82 primaryTerm=1 version=1 source= {"f":254}}, doc{id='NabXV5EB9g0jrMLt9HkR seqNo=83 primaryTerm=1 version=1 source= {"f":257}}, doc{id='N6bXV5EB9g0jrMLt9HkU seqNo=84 primaryTerm=1 version=1 source= {"f":259}}, doc{id='PqbXV5EB9g0jrMLt9Hkj seqNo=85 primaryTerm=1 version=1 source= {"f":266}}, doc{id='QKbXV5EB9g0jrMLt9Hkq seqNo=86 primaryTerm=1 version=1 source= {"f":268}}, doc{id='QabXV5EB9g0jrMLt9Hks seqNo=87 primaryTerm=1 version=1 source= {"f":269}}, doc{id='QqbXV5EB9g0jrMLt9Hku seqNo=88 primaryTerm=1 version=1 source= {"f":270}}, doc{id='Q6bXV5EB9g0jrMLt9Hkw seqNo=89 primaryTerm=1 version=1 source= {"f":271}}, doc{id='RKbXV5EB9g0jrMLt9Hky seqNo=90 primaryTerm=1 version=1 source= {"f":272}}, doc{id='RqbXV5EB9g0jrMLt9Hk3 seqNo=91 primaryTerm=1 version=1 source= {"f":274}}, doc{id='SKbXV5EB9g0jrMLt9Hk6 seqNo=92 primaryTerm=1 version=1 source= {"f":276}}, doc{id='SabXV5EB9g0jrMLt9Hk8 seqNo=93 primaryTerm=1 version=1 source= {"f":277}}, doc{id='UabXV5EB9g0jrMLt9HlI seqNo=94 primaryTerm=1 version=1 source= {"f":285}}], 2=[doc{id='NKbXV5EB9g0jrMLt8Hiw seqNo=0 primaryTerm=1 version=1 source= {"f":0}}, doc{id='OqbXV5EB9g0jrMLt8HjB seqNo=1 primaryTerm=1 version=1 source= {"f":6}}, doc{id='PKbXV5EB9g0jrMLt8HjG seqNo=2 primaryTerm=1 version=1 source= {"f":8}}, doc{id='QabXV5EB9g0jrMLt8HjP seqNo=3 primaryTerm=1 version=1 source= {"f":13}}, doc{id='Q6bXV5EB9g0jrMLt8HjT seqNo=4 primaryTerm=1 version=1 source= {"f":15}}, doc{id='RKbXV5EB9g0jrMLt8HjU seqNo=5 primaryTerm=1 version=1 source= {"f":16}}, doc{id='RabXV5EB9g0jrMLt8HjV seqNo=6 primaryTerm=1 version=1 source= {"f":17}}, doc{id='R6bXV5EB9g0jrMLt8HjZ seqNo=7 primaryTerm=1 version=1 source= {"f":19}}, doc{id='SKbXV5EB9g0jrMLt8Hja seqNo=8 primaryTerm=1 version=1 source= {"f":20}}, doc{id='SabXV5EB9g0jrMLt8Hjc seqNo=9 primaryTerm=1 version=1 source= {"f":21}}, doc{id='TKbXV5EB9g0jrMLt8Hjh seqNo=10 primaryTerm=1 version=1 source= {"f":24}}, doc{id='UKbXV5EB9g0jrMLt8Hjo seqNo=11 primaryTerm=1 version=1 source= {"f":28}}, doc{id='WKbXV5EB9g0jrMLt8Hjy seqNo=12 primaryTerm=1 version=1 source= {"f":36}}, doc{id='WabXV5EB9g0jrMLt8Hj6 seqNo=13 primaryTerm=1 version=1 source= {"f":37}}, doc{id='W6bXV5EB9g0jrMLt8Hj9 seqNo=14 primaryTerm=1 version=1 source= {"f":39}}, doc{id='XabXV5EB9g0jrMLt8XgB seqNo=15 primaryTerm=1 version=1 source= {"f":41}}, doc{id='X6bXV5EB9g0jrMLt8XgE seqNo=16 primaryTerm=1 version=1 source= {"f":43}}, doc{id='YKbXV5EB9g0jrMLt8XgF seqNo=17 primaryTerm=1 version=1 source= {"f":44}}, doc{id='YqbXV5EB9g0jrMLt8XgI seqNo=18 primaryTerm=1 version=1 source= {"f":46}}, doc{id='ZKbXV5EB9g0jrMLt8XgL seqNo=19 primaryTerm=1 version=1 source= {"f":48}}, doc{id='ZabXV5EB9g0jrMLt8XgN seqNo=20 primaryTerm=1 version=1 source= {"f":49}}, doc{id='aKbXV5EB9g0jrMLt8XgS seqNo=21 primaryTerm=1 version=1 source= {"f":52}}, doc{id='bqbXV5EB9g0jrMLt8Xgb seqNo=22 primaryTerm=1 version=1 source= {"f":58}}, doc{id='cabXV5EB9g0jrMLt8Xgh seqNo=23 primaryTerm=1 version=1 source= {"f":61}}, doc{id='dKbXV5EB9g0jrMLt8Xgn seqNo=24 primaryTerm=1 version=1 source= {"f":64}}, doc{id='dqbXV5EB9g0jrMLt8Xgq seqNo=25 primaryTerm=1 version=1 source= {"f":66}}, doc{id='eabXV5EB9g0jrMLt8Xgu seqNo=26 primaryTerm=1 version=1 source= {"f":69}}, doc{id='eqbXV5EB9g0jrMLt8Xgv seqNo=27 primaryTerm=1 version=1 source= {"f":70}}, doc{id='fKbXV5EB9g0jrMLt8Xgy seqNo=28 primaryTerm=1 version=1 source= {"f":72}}, doc{id='fqbXV5EB9g0jrMLt8Xg1 seqNo=29 primaryTerm=1 version=1 source= {"f":74}}, doc{id='f6bXV5EB9g0jrMLt8Xg2 seqNo=30 primaryTerm=1 version=1 source= {"f":75}}, doc{id='gqbXV5EB9g0jrMLt8Xg7 seqNo=31 primaryTerm=1 version=1 source= {"f":78}}, doc{id='habXV5EB9g0jrMLt8XhA seqNo=32 primaryTerm=1 version=1 source= {"f":81}}, doc{id='hqbXV5EB9g0jrMLt8XhB seqNo=33 primaryTerm=1 version=1 source= {"f":82}}, doc{id='iKbXV5EB9g0jrMLt8XhE seqNo=34 primaryTerm=1 version=1 source= {"f":84}}, doc{id='iqbXV5EB9g0jrMLt8XhH seqNo=35 primaryTerm=1 version=1 source= {"f":86}}, doc{id='jKbXV5EB9g0jrMLt8XhJ seqNo=36 primaryTerm=1 version=1 source= {"f":88}}, doc{id='kKbXV5EB9g0jrMLt8XhO seqNo=37 primaryTerm=1 version=1 source= {"f":92}}, doc{id='lKbXV5EB9g0jrMLt8XhU seqNo=38 primaryTerm=1 version=1 source= {"f":96}}, doc{id='nqbXV5EB9g0jrMLt8Xhi seqNo=39 primaryTerm=1 version=1 source= {"f":106}}, doc{id='oKbXV5EB9g0jrMLt8Xhn seqNo=40 primaryTerm=1 version=1 source= {"f":108}}, doc{id='oqbXV5EB9g0jrMLt8Xhr seqNo=41 primaryTerm=1 version=1 source= {"f":110}}, doc{id='pKbXV5EB9g0jrMLt8Xhv seqNo=42 primaryTerm=1 version=1 source= {"f":112}}, doc{id='qKbXV5EB9g0jrMLt8Xh6 seqNo=43 primaryTerm=1 version=1 source= {"f":116}}, doc{id='q6bXV5EB9g0jrMLt8Xh_ seqNo=44 primaryTerm=1 version=1 source= {"f":119}}, doc{id='rabXV5EB9g0jrMLt8XiD seqNo=45 primaryTerm=1 version=1 source= {"f":121}}, doc{id='rqbXV5EB9g0jrMLt8XiE seqNo=46 primaryTerm=1 version=1 source= {"f":122}}, doc{id='sqbXV5EB9g0jrMLt8XiK seqNo=47 primaryTerm=1 version=1 source= {"f":126}}, doc{id='uKbXV5EB9g0jrMLt8XiT seqNo=48 primaryTerm=1 version=1 source= {"f":132}}, doc{id='uabXV5EB9g0jrMLt8XiU seqNo=49 primaryTerm=1 version=1 source= {"f":133}}, doc{id='uqbXV5EB9g0jrMLt8XiW seqNo=50 primaryTerm=1 version=1 source= {"f":134}}, doc{id='wabXV5EB9g0jrMLt8Xig seqNo=51 primaryTerm=1 version=1 source= {"f":141}}, doc{id='xKbXV5EB9g0jrMLt83gY seqNo=52 primaryTerm=1 version=1 source= {"f":144}}, doc{id='y6bXV5EB9g0jrMLt83gp seqNo=53 primaryTerm=1 version=1 source= {"f":151}}, doc{id='zKbXV5EB9g0jrMLt83gs seqNo=54 primaryTerm=1 version=1 source= {"f":152}}, doc{id='z6bXV5EB9g0jrMLt83gz seqNo=55 primaryTerm=1 version=1 source= {"f":155}}, doc{id='06bXV5EB9g0jrMLt83g6 seqNo=56 primaryTerm=1 version=1 source= {"f":159}}, doc{id='1abXV5EB9g0jrMLt83g- seqNo=57 primaryTerm=1 version=1 source= {"f":161}}, doc{id='2KbXV5EB9g0jrMLt83hD seqNo=58 primaryTerm=1 version=1 source= {"f":164}}, doc{id='2abXV5EB9g0jrMLt83hE seqNo=59 primaryTerm=1 version=1 source= {"f":165}}, doc{id='3KbXV5EB9g0jrMLt83hJ seqNo=60 primaryTerm=1 version=1 source= {"f":168}}, doc{id='4KbXV5EB9g0jrMLt83hR seqNo=61 primaryTerm=1 version=1 source= {"f":172}}, doc{id='4qbXV5EB9g0jrMLt83hV seqNo=62 primaryTerm=1 version=1 source= {"f":174}}, doc{id='5KbXV5EB9g0jrMLt83hY seqNo=63 primaryTerm=1 version=1 source= {"f":176}}, doc{id='5abXV5EB9g0jrMLt83ha seqNo=64 primaryTerm=1 version=1 source= {"f":177}}, doc{id='5qbXV5EB9g0jrMLt83hc seqNo=65 primaryTerm=1 version=1 source= {"f":178}}, doc{id='6KbXV5EB9g0jrMLt83hf seqNo=66 primaryTerm=1 version=1 source= {"f":180}}, doc{id='6abXV5EB9g0jrMLt83hg seqNo=67 primaryTerm=1 version=1 source= {"f":181}}, doc{id='7KbXV5EB9g0jrMLt83ho seqNo=68 primaryTerm=1 version=1 source= {"f":184}}, doc{id='76bXV5EB9g0jrMLt83hu seqNo=69 primaryTerm=1 version=1 source= {"f":187}}, doc{id='8KbXV5EB9g0jrMLt83hw seqNo=70 primaryTerm=1 version=1 source= {"f":188}}, doc{id='8qbXV5EB9g0jrMLt83h0 seqNo=71 primaryTerm=1 version=1 source= {"f":190}}, doc{id='-qbXV5EB9g0jrMLt83iB seqNo=72 primaryTerm=1 version=1 source= {"f":198}}, doc{id='_abXV5EB9g0jrMLt83iJ seqNo=73 primaryTerm=1 version=1 source= {"f":201}}, doc{id='AqbXV5EB9g0jrMLt83mV seqNo=74 primaryTerm=1 version=1 source= {"f":206}}, doc{id='BabXV5EB9g0jrMLt83ma seqNo=75 primaryTerm=1 version=1 source= {"f":209}}, doc{id='CKbXV5EB9g0jrMLt83mf seqNo=76 primaryTerm=1 version=1 source= {"f":212}}, doc{id='CqbXV5EB9g0jrMLt83mi seqNo=77 primaryTerm=1 version=1 source= {"f":214}}, doc{id='DqbXV5EB9g0jrMLt83mo seqNo=78 primaryTerm=1 version=1 source= {"f":218}}, doc{id='EKbXV5EB9g0jrMLt83ms seqNo=79 primaryTerm=1 version=1 source= {"f":220}}, doc{id='EqbXV5EB9g0jrMLt83mv seqNo=80 primaryTerm=1 version=1 source= {"f":222}}, doc{id='FKbXV5EB9g0jrMLt83my seqNo=81 primaryTerm=1 version=1 source= {"f":224}}, doc{id='FqbXV5EB9g0jrMLt83m0 seqNo=82 primaryTerm=1 version=1 source= {"f":226}}, doc{id='GqbXV5EB9g0jrMLt83m6 seqNo=83 primaryTerm=1 version=1 source= {"f":230}}, doc{id='HabXV5EB9g0jrMLt83m_ seqNo=84 primaryTerm=1 version=1 source= {"f":233}}, doc{id='HqbXV5EB9g0jrMLt83nB seqNo=85 primaryTerm=1 version=1 source= {"f":234}}, doc{id='JKbXV5EB9g0jrMLt83nV seqNo=86 primaryTerm=1 version=1 source= {"f":240}}, doc{id='JqbXV5EB9g0jrMLt83nZ seqNo=87 primaryTerm=1 version=1 source= {"f":242}}, doc{id='J6bXV5EB9g0jrMLt83nb seqNo=88 primaryTerm=1 version=1 source= {"f":243}}, doc{id='KKbXV5EB9g0jrMLt83nd seqNo=89 primaryTerm=1 version=1 source= {"f":244}}, doc{id='K6bXV5EB9g0jrMLt83n_ seqNo=90 primaryTerm=1 version=1 source= {"f":247}}, doc{id='LKbXV5EB9g0jrMLt9HkC seqNo=91 primaryTerm=1 version=1 source= {"f":248}}, doc{id='L6bXV5EB9g0jrMLt9HkH seqNo=92 primaryTerm=1 version=1 source= {"f":251}}, doc{id='NKbXV5EB9g0jrMLt9HkP seqNo=93 primaryTerm=1 version=1 source= {"f":256}}, doc{id='OKbXV5EB9g0jrMLt9HkW seqNo=94 primaryTerm=1 version=1 source= {"f":260}}, doc{id='PKbXV5EB9g0jrMLt9Hke seqNo=95 primaryTerm=1 version=1 source= {"f":264}}, doc{id='PabXV5EB9g0jrMLt9Hkg seqNo=96 primaryTerm=1 version=1 source= {"f":265}}, doc{id='RabXV5EB9g0jrMLt9Hk0 seqNo=97 primaryTerm=1 version=1 source= {"f":273}}, doc{id='R6bXV5EB9g0jrMLt9Hk5 seqNo=98 primaryTerm=1 version=1 source= {"f":275}}, doc{id='SqbXV5EB9g0jrMLt9Hk- seqNo=99 primaryTerm=1 version=1 source= {"f":278}}, doc{id='TqbXV5EB9g0jrMLt9HlE seqNo=100 primaryTerm=1 version=1 source= {"f":282}}]}>
     but: was <{0=[doc{id='NabXV5EB9g0jrMLt8Hiz seqNo=0 primaryTerm=1 version=1 source= {"f":1}}, doc{id='N6bXV5EB9g0jrMLt8Hi8 seqNo=1 primaryTerm=1 version=1 source= {"f":3}}, doc{id='OKbXV5EB9g0jrMLt8Hi- seqNo=2 primaryTerm=1 version=1 source= {"f":4}}, doc{id='O6bXV5EB9g0jrMLt8HjE seqNo=3 primaryTerm=1 version=1 source= {"f":7}}, doc{id='PqbXV5EB9g0jrMLt8HjK seqNo=4 primaryTerm=1 version=1 source= {"f":10}}, doc{id='P6bXV5EB9g0jrMLt8HjM seqNo=5 primaryTerm=1 version=1 source= {"f":11}}, doc{id='QKbXV5EB9g0jrMLt8HjO seqNo=6 primaryTerm=1 version=1 source= {"f":12}}, doc{id='QqbXV5EB9g0jrMLt8HjR seqNo=7 primaryTerm=1 version=1 source= {"f":14}}, doc{id='S6bXV5EB9g0jrMLt8Hjf seqNo=8 primaryTerm=1 version=1 source= {"f":23}}, doc{id='TqbXV5EB9g0jrMLt8Hjk seqNo=9 primaryTerm=1 version=1 source= {"f":26}}, doc{id='UabXV5EB9g0jrMLt8Hjp seqNo=10 primaryTerm=1 version=1 source= {"f":29}}, doc{id='U6bXV5EB9g0jrMLt8Hjs seqNo=11 primaryTerm=1 version=1 source= {"f":31}}, doc{id='WqbXV5EB9g0jrMLt8Hj8 seqNo=12 primaryTerm=1 version=1 source= {"f":38}}, doc{id='XqbXV5EB9g0jrMLt8XgC seqNo=13 primaryTerm=1 version=1 source= {"f":42}}, doc{id='YabXV5EB9g0jrMLt8XgG seqNo=14 primaryTerm=1 version=1 source= {"f":45}}, doc{id='Y6bXV5EB9g0jrMLt8XgK seqNo=15 primaryTerm=1 version=1 source= {"f":47}}, doc{id='Z6bXV5EB9g0jrMLt8XgQ seqNo=16 primaryTerm=1 version=1 source= {"f":51}}, doc{id='a6bXV5EB9g0jrMLt8XgW seqNo=17 primaryTerm=1 version=1 source= {"f":55}}, doc{id='bKbXV5EB9g0jrMLt8XgY seqNo=18 primaryTerm=1 version=1 source= {"f":56}}, doc{id='babXV5EB9g0jrMLt8Xga seqNo=19 primaryTerm=1 version=1 source= {"f":57}}, doc{id='b6bXV5EB9g0jrMLt8Xgd seqNo=20 primaryTerm=1 version=1 source= {"f":59}}, doc{id='c6bXV5EB9g0jrMLt8Xgl seqNo=21 primaryTerm=1 version=1 source= {"f":63}}, doc{id='dabXV5EB9g0jrMLt8Xgo seqNo=22 primaryTerm=1 version=1 source= {"f":65}}, doc{id='d6bXV5EB9g0jrMLt8Xgr seqNo=23 primaryTerm=1 version=1 source= {"f":67}}, doc{id='eKbXV5EB9g0jrMLt8Xgs seqNo=24 primaryTerm=1 version=1 source= {"f":68}}, doc{id='e6bXV5EB9g0jrMLt8Xgw seqNo=25 primaryTerm=1 version=1 source= {"f":71}}, doc{id='gKbXV5EB9g0jrMLt8Xg4 seqNo=26 primaryTerm=1 version=1 source= {"f":76}}, doc{id='gabXV5EB9g0jrMLt8Xg6 seqNo=27 primaryTerm=1 version=1 source= {"f":77}}, doc{id='g6bXV5EB9g0jrMLt8Xg8 seqNo=28 primaryTerm=1 version=1 source= {"f":79}}, doc{id='i6bXV5EB9g0jrMLt8XhI seqNo=29 primaryTerm=1 version=1 source= {"f":87}}, doc{id='jabXV5EB9g0jrMLt8XhK seqNo=30 primaryTerm=1 version=1 source= {"f":89}}, doc{id='kabXV5EB9g0jrMLt8XhQ seqNo=31 primaryTerm=1 version=1 source= {"f":93}}, doc{id='l6bXV5EB9g0jrMLt8XhY seqNo=32 primaryTerm=1 version=1 source= {"f":99}}, doc{id='mabXV5EB9g0jrMLt8Xhb seqNo=33 primaryTerm=1 version=1 source= {"f":101}}, doc{id='m6bXV5EB9g0jrMLt8Xhd seqNo=34 primaryTerm=1 version=1 source= {"f":103}}, doc{id='nabXV5EB9g0jrMLt8Xhh seqNo=35 primaryTerm=1 version=1 source= {"f":105}}, doc{id='pqbXV5EB9g0jrMLt8Xh0 seqNo=36 primaryTerm=1 version=1 source= {"f":114}}, doc{id='p6bXV5EB9g0jrMLt8Xh4 seqNo=37 primaryTerm=1 version=1 source= {"f":115}}, doc{id='qabXV5EB9g0jrMLt8Xh8 seqNo=38 primaryTerm=1 version=1 source= {"f":117}}, doc{id='qqbXV5EB9g0jrMLt8Xh- seqNo=39 primaryTerm=1 version=1 source= {"f":118}}, doc{id='r6bXV5EB9g0jrMLt8XiF seqNo=40 primaryTerm=1 version=1 source= {"f":123}}, doc{id='sabXV5EB9g0jrMLt8XiI seqNo=41 primaryTerm=1 version=1 source= {"f":125}}, doc{id='tqbXV5EB9g0jrMLt8XiQ seqNo=42 primaryTerm=1 version=1 source= {"f":130}}, doc{id='vabXV5EB9g0jrMLt8Xia seqNo=43 primaryTerm=1 version=1 source= {"f":137}}, doc{id='wKbXV5EB9g0jrMLt8Xif seqNo=44 primaryTerm=1 version=1 source= {"f":140}}, doc{id='wqbXV5EB9g0jrMLt8Xii seqNo=45 primaryTerm=1 version=1 source= {"f":142}}, doc{id='x6bXV5EB9g0jrMLt83gh seqNo=46 primaryTerm=1 version=1 source= {"f":147}}, doc{id='yqbXV5EB9g0jrMLt83gn seqNo=47 primaryTerm=1 version=1 source= {"f":150}}, doc{id='zabXV5EB9g0jrMLt83gu seqNo=48 primaryTerm=1 version=1 source= {"f":153}}, doc{id='zqbXV5EB9g0jrMLt83gw seqNo=49 primaryTerm=1 version=1 source= {"f":154}}, doc{id='1qbXV5EB9g0jrMLt83g_ seqNo=50 primaryTerm=1 version=1 source= {"f":162}}, doc{id='3qbXV5EB9g0jrMLt83hN seqNo=51 primaryTerm=1 version=1 source= {"f":170}}, doc{id='36bXV5EB9g0jrMLt83hP seqNo=52 primaryTerm=1 version=1 source= {"f":171}}, doc{id='56bXV5EB9g0jrMLt83hd seqNo=53 primaryTerm=1 version=1 source= {"f":179}}, doc{id='66bXV5EB9g0jrMLt83hl seqNo=54 primaryTerm=1 version=1 source= {"f":183}}, doc{id='8abXV5EB9g0jrMLt83hy seqNo=55 primaryTerm=1 version=1 source= {"f":189}}, doc{id='9KbXV5EB9g0jrMLt83h3 seqNo=56 primaryTerm=1 version=1 source= {"f":192}}, doc{id='-KbXV5EB9g0jrMLt83h9 seqNo=57 primaryTerm=1 version=1 source= {"f":196}}, doc{id='-abXV5EB9g0jrMLt83h_ seqNo=58 primaryTerm=1 version=1 source= {"f":197}}, doc{id='-6bXV5EB9g0jrMLt83iE seqNo=59 primaryTerm=1 version=1 source= {"f":199}}, doc{id='_6bXV5EB9g0jrMLt83iP seqNo=60 primaryTerm=1 version=1 source= {"f":203}}, doc{id='AabXV5EB9g0jrMLt83mT seqNo=61 primaryTerm=1 version=1 source= {"f":205}}, doc{id='BKbXV5EB9g0jrMLt83mZ seqNo=62 primaryTerm=1 version=1 source= {"f":208}}, doc{id='BqbXV5EB9g0jrMLt83mc seqNo=63 primaryTerm=1 version=1 source= {"f":210}}, doc{id='B6bXV5EB9g0jrMLt83md seqNo=64 primaryTerm=1 version=1 source= {"f":211}}, doc{id='CabXV5EB9g0jrMLt83mg seqNo=65 primaryTerm=1 version=1 source= {"f":213}}, doc{id='C6bXV5EB9g0jrMLt83mj seqNo=66 primaryTerm=1 version=1 source= {"f":215}}, doc{id='D6bXV5EB9g0jrMLt83mq seqNo=67 primaryTerm=1 version=1 source= {"f":219}}, doc{id='EabXV5EB9g0jrMLt83mu seqNo=68 primaryTerm=1 version=1 source= {"f":221}}, doc{id='G6bXV5EB9g0jrMLt83m7 seqNo=69 primaryTerm=1 version=1 source= {"f":231}}, doc{id='H6bXV5EB9g0jrMLt83nC seqNo=70 primaryTerm=1 version=1 source= {"f":235}}, doc{id='IKbXV5EB9g0jrMLt83nF seqNo=71 primaryTerm=1 version=1 source= {"f":236}}, doc{id='IabXV5EB9g0jrMLt83nH seqNo=72 primaryTerm=1 version=1 source= {"f":237}}, doc{id='I6bXV5EB9g0jrMLt83nP seqNo=73 primaryTerm=1 version=1 source= {"f":239}}, doc{id='KqbXV5EB9g0jrMLt83ng seqNo=74 primaryTerm=1 version=1 source= {"f":246}}, doc{id='LabXV5EB9g0jrMLt9HkD seqNo=75 primaryTerm=1 version=1 source= {"f":249}}, doc{id='LqbXV5EB9g0jrMLt9HkF seqNo=76 primaryTerm=1 version=1 source= {"f":250}}, doc{id='MKbXV5EB9g0jrMLt9HkI seqNo=77 primaryTerm=1 version=1 source= {"f":252}}, doc{id='MabXV5EB9g0jrMLt9HkK seqNo=78 primaryTerm=1 version=1 source= {"f":253}}, doc{id='M6bXV5EB9g0jrMLt9HkN seqNo=79 primaryTerm=1 version=1 source= {"f":255}}, doc{id='NqbXV5EB9g0jrMLt9HkS seqNo=80 primaryTerm=1 version=1 source= {"f":258}}, doc{id='OabXV5EB9g0jrMLt9HkY seqNo=81 primaryTerm=1 version=1 source= {"f":261}}, doc{id='OqbXV5EB9g0jrMLt9Hka seqNo=82 primaryTerm=1 version=1 source= {"f":262}}, doc{id='O6bXV5EB9g0jrMLt9Hkd seqNo=83 primaryTerm=1 version=1 source= {"f":263}}, doc{id='P6bXV5EB9g0jrMLt9Hkl seqNo=84 primaryTerm=1 version=1 source= {"f":267}}, doc{id='S6bXV5EB9g0jrMLt9HlA seqNo=85 primaryTerm=1 version=1 source= {"f":279}}, doc{id='TKbXV5EB9g0jrMLt9HlC seqNo=86 primaryTerm=1 version=1 source= {"f":280}}, doc{id='TabXV5EB9g0jrMLt9HlD seqNo=87 primaryTerm=1 version=1 source= {"f":281}}, doc{id='T6bXV5EB9g0jrMLt9HlG seqNo=88 primaryTerm=1 version=1 source= {"f":283}}, doc{id='UKbXV5EB9g0jrMLt9HlH seqNo=89 primaryTerm=1 version=1 source= {"f":284}}], 2=[doc{id='NKbXV5EB9g0jrMLt8Hiw seqNo=0 primaryTerm=1 version=1 source= {"f":0}}, doc{id='OqbXV5EB9g0jrMLt8HjB seqNo=1 primaryTerm=1 version=1 source= {"f":6}}, doc{id='PKbXV5EB9g0jrMLt8HjG seqNo=2 primaryTerm=1 version=1 source= {"f":8}}, doc{id='QabXV5EB9g0jrMLt8HjP seqNo=3 primaryTerm=1 version=1 source= {"f":13}}, doc{id='Q6bXV5EB9g0jrMLt8HjT seqNo=4 primaryTerm=1 version=1 source= {"f":15}}, doc{id='RKbXV5EB9g0jrMLt8HjU seqNo=5 primaryTerm=1 version=1 source= {"f":16}}, doc{id='RabXV5EB9g0jrMLt8HjV seqNo=6 primaryTerm=1 version=1 source= {"f":17}}, doc{id='R6bXV5EB9g0jrMLt8HjZ seqNo=7 primaryTerm=1 version=1 source= {"f":19}}, doc{id='SKbXV5EB9g0jrMLt8Hja seqNo=8 primaryTerm=1 version=1 source= {"f":20}}, doc{id='SabXV5EB9g0jrMLt8Hjc seqNo=9 primaryTerm=1 version=1 source= {"f":21}}, doc{id='TKbXV5EB9g0jrMLt8Hjh seqNo=10 primaryTerm=1 version=1 source= {"f":24}}, doc{id='UKbXV5EB9g0jrMLt8Hjo seqNo=11 primaryTerm=1 version=1 source= {"f":28}}, doc{id='WKbXV5EB9g0jrMLt8Hjy seqNo=12 primaryTerm=1 version=1 source= {"f":36}}, doc{id='WabXV5EB9g0jrMLt8Hj6 seqNo=13 primaryTerm=1 version=1 source= {"f":37}}, doc{id='W6bXV5EB9g0jrMLt8Hj9 seqNo=14 primaryTerm=1 version=1 source= {"f":39}}, doc{id='XabXV5EB9g0jrMLt8XgB seqNo=15 primaryTerm=1 version=1 source= {"f":41}}, doc{id='X6bXV5EB9g0jrMLt8XgE seqNo=16 primaryTerm=1 version=1 source= {"f":43}}, doc{id='YKbXV5EB9g0jrMLt8XgF seqNo=17 primaryTerm=1 version=1 source= {"f":44}}, doc{id='YqbXV5EB9g0jrMLt8XgI seqNo=18 primaryTerm=1 version=1 source= {"f":46}}, doc{id='ZKbXV5EB9g0jrMLt8XgL seqNo=19 primaryTerm=1 version=1 source= {"f":48}}, doc{id='ZabXV5EB9g0jrMLt8XgN seqNo=20 primaryTerm=1 version=1 source= {"f":49}}, doc{id='aKbXV5EB9g0jrMLt8XgS seqNo=21 primaryTerm=1 version=1 source= {"f":52}}, doc{id='bqbXV5EB9g0jrMLt8Xgb seqNo=22 primaryTerm=1 version=1 source= {"f":58}}, doc{id='cabXV5EB9g0jrMLt8Xgh seqNo=23 primaryTerm=1 version=1 source= {"f":61}}, doc{id='dKbXV5EB9g0jrMLt8Xgn seqNo=24 primaryTerm=1 version=1 source= {"f":64}}, doc{id='dqbXV5EB9g0jrMLt8Xgq seqNo=25 primaryTerm=1 version=1 source= {"f":66}}, doc{id='eabXV5EB9g0jrMLt8Xgu seqNo=26 primaryTerm=1 version=1 source= {"f":69}}, doc{id='eqbXV5EB9g0jrMLt8Xgv seqNo=27 primaryTerm=1 version=1 source= {"f":70}}, doc{id='fKbXV5EB9g0jrMLt8Xgy seqNo=28 primaryTerm=1 version=1 source= {"f":72}}, doc{id='fqbXV5EB9g0jrMLt8Xg1 seqNo=29 primaryTerm=1 version=1 source= {"f":74}}, doc{id='f6bXV5EB9g0jrMLt8Xg2 seqNo=30 primaryTerm=1 version=1 source= {"f":75}}, doc{id='gqbXV5EB9g0jrMLt8Xg7 seqNo=31 primaryTerm=1 version=1 source= {"f":78}}, doc{id='habXV5EB9g0jrMLt8XhA seqNo=32 primaryTerm=1 version=1 source= {"f":81}}, doc{id='hqbXV5EB9g0jrMLt8XhB seqNo=33 primaryTerm=1 version=1 source= {"f":82}}, doc{id='iKbXV5EB9g0jrMLt8XhE seqNo=34 primaryTerm=1 version=1 source= {"f":84}}, doc{id='iqbXV5EB9g0jrMLt8XhH seqNo=35 primaryTerm=1 version=1 source= {"f":86}}, doc{id='jKbXV5EB9g0jrMLt8XhJ seqNo=36 primaryTerm=1 version=1 source= {"f":88}}, doc{id='kKbXV5EB9g0jrMLt8XhO seqNo=37 primaryTerm=1 version=1 source= {"f":92}}, doc{id='lKbXV5EB9g0jrMLt8XhU seqNo=38 primaryTerm=1 version=1 source= {"f":96}}, doc{id='nqbXV5EB9g0jrMLt8Xhi seqNo=39 primaryTerm=1 version=1 source= {"f":106}}, doc{id='oKbXV5EB9g0jrMLt8Xhn seqNo=40 primaryTerm=1 version=1 source= {"f":108}}, doc{id='oqbXV5EB9g0jrMLt8Xhr seqNo=41 primaryTerm=1 version=1 source= {"f":110}}, doc{id='pKbXV5EB9g0jrMLt8Xhv seqNo=42 primaryTerm=1 version=1 source= {"f":112}}, doc{id='qKbXV5EB9g0jrMLt8Xh6 seqNo=43 primaryTerm=1 version=1 source= {"f":116}}, doc{id='q6bXV5EB9g0jrMLt8Xh_ seqNo=44 primaryTerm=1 version=1 source= {"f":119}}, doc{id='rabXV5EB9g0jrMLt8XiD seqNo=45 primaryTerm=1 version=1 source= {"f":121}}, doc{id='rqbXV5EB9g0jrMLt8XiE seqNo=46 primaryTerm=1 version=1 source= {"f":122}}, doc{id='sqbXV5EB9g0jrMLt8XiK seqNo=47 primaryTerm=1 version=1 source= {"f":126}}, doc{id='uKbXV5EB9g0jrMLt8XiT seqNo=48 primaryTerm=1 version=1 source= {"f":132}}, doc{id='uabXV5EB9g0jrMLt8XiU seqNo=49 primaryTerm=1 version=1 source= {"f":133}}, doc{id='uqbXV5EB9g0jrMLt8XiW seqNo=50 primaryTerm=1 version=1 source= {"f":134}}, doc{id='wabXV5EB9g0jrMLt8Xig seqNo=51 primaryTerm=1 version=1 source= {"f":141}}, doc{id='xKbXV5EB9g0jrMLt83gY seqNo=52 primaryTerm=1 version=1 source= {"f":144}}, doc{id='y6bXV5EB9g0jrMLt83gp seqNo=53 primaryTerm=1 version=1 source= {"f":151}}, doc{id='zKbXV5EB9g0jrMLt83gs seqNo=54 primaryTerm=1 version=1 source= {"f":152}}, doc{id='z6bXV5EB9g0jrMLt83gz seqNo=55 primaryTerm=1 version=1 source= {"f":155}}, doc{id='06bXV5EB9g0jrMLt83g6 seqNo=56 primaryTerm=1 version=1 source= {"f":159}}, doc{id='1abXV5EB9g0jrMLt83g- seqNo=57 primaryTerm=1 version=1 source= {"f":161}}, doc{id='2KbXV5EB9g0jrMLt83hD seqNo=58 primaryTerm=1 version=1 source= {"f":164}}, doc{id='2abXV5EB9g0jrMLt83hE seqNo=59 primaryTerm=1 version=1 source= {"f":165}}, doc{id='3KbXV5EB9g0jrMLt83hJ seqNo=60 primaryTerm=1 version=1 source= {"f":168}}, doc{id='4KbXV5EB9g0jrMLt83hR seqNo=61 primaryTerm=1 version=1 source= {"f":172}}, doc{id='4qbXV5EB9g0jrMLt83hV seqNo=62 primaryTerm=1 version=1 source= {"f":174}}, doc{id='5KbXV5EB9g0jrMLt83hY seqNo=63 primaryTerm=1 version=1 source= {"f":176}}, doc{id='5abXV5EB9g0jrMLt83ha seqNo=64 primaryTerm=1 version=1 source= {"f":177}}, doc{id='5qbXV5EB9g0jrMLt83hc seqNo=65 primaryTerm=1 version=1 source= {"f":178}}, doc{id='6KbXV5EB9g0jrMLt83hf seqNo=66 primaryTerm=1 version=1 source= {"f":180}}, doc{id='6abXV5EB9g0jrMLt83hg seqNo=67 primaryTerm=1 version=1 source= {"f":181}}, doc{id='7KbXV5EB9g0jrMLt83ho seqNo=68 primaryTerm=1 version=1 source= {"f":184}}, doc{id='76bXV5EB9g0jrMLt83hu seqNo=69 primaryTerm=1 version=1 source= {"f":187}}, doc{id='8KbXV5EB9g0jrMLt83hw seqNo=70 primaryTerm=1 version=1 source= {"f":188}}, doc{id='8qbXV5EB9g0jrMLt83h0 seqNo=71 primaryTerm=1 version=1 source= {"f":190}}, doc{id='-qbXV5EB9g0jrMLt83iB seqNo=72 primaryTerm=1 version=1 source= {"f":198}}, doc{id='_abXV5EB9g0jrMLt83iJ seqNo=73 primaryTerm=1 version=1 source= {"f":201}}, doc{id='AqbXV5EB9g0jrMLt83mV seqNo=74 primaryTerm=1 version=1 source= {"f":206}}, doc{id='BabXV5EB9g0jrMLt83ma seqNo=75 primaryTerm=1 version=1 source= {"f":209}}, doc{id='CKbXV5EB9g0jrMLt83mf seqNo=76 primaryTerm=1 version=1 source= {"f":212}}, doc{id='CqbXV5EB9g0jrMLt83mi seqNo=77 primaryTerm=1 version=1 source= {"f":214}}, doc{id='DqbXV5EB9g0jrMLt83mo seqNo=78 primaryTerm=1 version=1 source= {"f":218}}, doc{id='EKbXV5EB9g0jrMLt83ms seqNo=79 primaryTerm=1 version=1 source= {"f":220}}, doc{id='EqbXV5EB9g0jrMLt83mv seqNo=80 primaryTerm=1 version=1 source= {"f":222}}, doc{id='FKbXV5EB9g0jrMLt83my seqNo=81 primaryTerm=1 version=1 source= {"f":224}}, doc{id='FqbXV5EB9g0jrMLt83m0 seqNo=82 primaryTerm=1 version=1 source= {"f":226}}, doc{id='GqbXV5EB9g0jrMLt83m6 seqNo=83 primaryTerm=1 version=1 source= {"f":230}}, doc{id='HabXV5EB9g0jrMLt83m_ seqNo=84 primaryTerm=1 version=1 source= {"f":233}}, doc{id='HqbXV5EB9g0jrMLt83nB seqNo=85 primaryTerm=1 version=1 source= {"f":234}}, doc{id='JKbXV5EB9g0jrMLt83nV seqNo=86 primaryTerm=1 version=1 source= {"f":240}}, doc{id='JqbXV5EB9g0jrMLt83nZ seqNo=87 primaryTerm=1 version=1 source= {"f":242}}, doc{id='J6bXV5EB9g0jrMLt83nb seqNo=88 primaryTerm=1 version=1 source= {"f":243}}, doc{id='KKbXV5EB9g0jrMLt83nd seqNo=89 primaryTerm=1 version=1 source= {"f":244}}, doc{id='K6bXV5EB9g0jrMLt83n_ seqNo=90 primaryTerm=1 version=1 source= {"f":247}}, doc{id='LKbXV5EB9g0jrMLt9HkC seqNo=91 primaryTerm=1 version=1 source= {"f":248}}, doc{id='L6bXV5EB9g0jrMLt9HkH seqNo=92 primaryTerm=1 version=1 source= {"f":251}}, doc{id='NKbXV5EB9g0jrMLt9HkP seqNo=93 primaryTerm=1 version=1 source= {"f":256}}, doc{id='OKbXV5EB9g0jrMLt9HkW seqNo=94 primaryTerm=1 version=1 source= {"f":260}}, doc{id='PKbXV5EB9g0jrMLt9Hke seqNo=95 primaryTerm=1 version=1 source= {"f":264}}, doc{id='PabXV5EB9g0jrMLt9Hkg seqNo=96 primaryTerm=1 version=1 source= {"f":265}}, doc{id='RabXV5EB9g0jrMLt9Hk0 seqNo=97 primaryTerm=1 version=1 source= {"f":273}}, doc{id='R6bXV5EB9g0jrMLt9Hk5 seqNo=98 primaryTerm=1 version=1 source= {"f":275}}, doc{id='SqbXV5EB9g0jrMLt9Hk- seqNo=99 primaryTerm=1 version=1 source= {"f":278}}, doc{id='TqbXV5EB9g0jrMLt9HlE seqNo=100 primaryTerm=1 version=1 source= {"f":282}}]}>
```

**Issue Reasons:**
- [7.17] 2 failures in test testFollowIndexAndCloseNode (1.6% fail rate in 128 executions)
- [7.17] 2 failures in step amazonlinux-2023_platform-support-aws (50.0% fail rate in 4 executions)
- [7.17] 2 failures in pipeline elasticsearch-periodic-platform-support (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DaveCTurner**
It's possible that we index enough documents and restart the node while
one of the follower shards is still initializing, and since this is like
a snapshot recovery it won't retry if it fails when the node shuts down.
This commit ensures that at least all the follower primaries have
started before restarting the node.

Closes #111941

### CODE REVIEW

**Review by idegtiarenko — DISMISSED** [review]

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java [hunk 1]
```diff
@@ -164,6 +165,12 @@ public void testFollowIndexAndCloseNode() throws Exception {
         int maxOpsPerRead = followRequest.getParameters().getMaxReadRequestOperationCount();
```
Comment (DiannaHohensee) [inline x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java:165]: I haven't really figured out how this test works yet, but there's an interesting [putFollow() method variation](https://github.com/elastic/elasticsearch/blob/e77dc6dc1324b00ba2ddf15718686e8bd1bcb3a9/x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/CcrIntegTestCase.java#L590) that seems to do something similar to your change

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java [hunk 2]
```diff
@@ -164,6 +165,12 @@ public void testFollowIndexAndCloseNode() throws Exception {
...
         int maxNumDocsReplicated = Math.min(between(50, 500), between(maxOpsPerRead, maxOpsPerRead * 10));
         availableDocs.release(maxNumDocsReplicated / 2 + 1);
+        safeAwait(
```
Comment (DiannaHohensee) [inline x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java:168]: comment with context for the objective of this call, please.

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java (hunk 1 above)
Comment (DaveCTurner) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java:165]: Hmm we're actually calling that method with `ActiveShardCount.ONE` already, so you make a good point. Why are we not already waiting for these shards to be active?

Comment (DiannaHohensee) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java:165]: Oops, I updated the comment and probably raced. What about using `ActiveShardCount.ALL`? We've [got 3 shards](https://github.com/elastic/elasticsearch/blob/e77dc6dc1324b00ba2ddf15718686e8bd1bcb3a9/x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java#L126), not 1.

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java (hunk 2 above)
Comment (DiannaHohensee) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java:168]: Which I think is that we want to wait for primary shards to be ready for indexing, to consistently accept the writes, before we then randomly stop a node and interrupt indexing, and potentially index shard recovery.

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java (hunk 1 above)
Comment (DaveCTurner) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/FollowerFailOverIT.java]: `ActiveShardCount#ALL` is right, but not because there are 3 shards. This parameter applies to each replication group separately, so `ActiveShardCount#ONE` means "wait for all three primaries to be assigned". But in this case we're shutting down one of the nodes, so we need the replicas to be up and running too.

**Review by DiannaHohensee — APPROVED** [review]
