### PR TITLE
CompressorFactory.compressor

### LINKED ISSUE #131605: NotXContentException on invalid xcontent should not cause 500 errors
When indexing documents with invalid xcontent, compressor detection returns a `NotXContentException` which bubbles up as 500 / rest suppressed error. This is a client error and should be a 400 response code instead.

```
org.elasticsearch.common.compress.NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes
	at org.elasticsearch.server@9.2.0/org.elasticsearch.common.compress.CompressorFactory.compressor(CompressorFactory.java:43)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.common.xcontent.XContentHelper.createParser(XContentHelper.java:123)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:89)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:128)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:1087)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:1014)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnPrimary(IndexShard.java:958)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.bulk.TransportShardBulkAction.executeBulkItemRequest(TransportShardBulkAction.java:420)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.bulk.TransportShardBulkAction$2.doRun(TransportShardBulkAction.java:277)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.bulk.TransportShardBulkAction.performOnPrimary(TransportShardBulkAction.java:345)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:182)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.bulk.TransportShardBulkAction.dispatchedShardOperationOnPrimary(TransportShardBulkAction.java:83)
```

In `CompressorFactory.compressor`, we shouldn't be guessing the xContent type if that is already known in 
`XContentHelper.createParser`. That way this would correctly result in a parser error.

Additionally we might consider having `NotXContentException` extend `XContentParseException`, so this results in a 400 status on other legacy code paths as well where we guess the xcontent type.

### PR DESCRIPTION
**Pull request by prdoyle**
`CompressorFactory.compressor` was over-eager in detecting XContent type even when the type was already known.

1. Refactor out a non-detecting version of the `CompressorFactory.compress` method
2. Add a failing unit test for #131605 
3. Fix the bug

Fixes #131605.

### CODE REVIEW

**Comment by prdoyle** [comment]
@mosche - Is this something like what you had in mind?

File: server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java [hunk 1]
```diff
@@ -15,16 +15,35 @@
...
+
+import static java.util.Objects.requireNonNull;
 
 public class CompressorFactory {
 
     public static final Compressor COMPRESSOR = new DeflateCompressor();
 
     public static boolean isCompressed(BytesReference bytes) {
-        return compressor(bytes) != null;
+        return COMPRESSOR.isCompressed(bytes);
```
Comment (mosche) [inline server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: this way you bypass the assert `assert XContentHelper.xContentType(bytes) == null;`, I think we should keep that one

File: server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java [hunk 2]
```diff
@@ -15,16 +15,35 @@
...
+    }
+
+    /**
+     * @deprecated Use {@link #compressor} and {@link #checkXContentType} as appropriate.
+     */
+    @Deprecated
+    @Nullable
+    public static Compressor compressorAndCheckXContentType(BytesReference bytes) {
```
Comment (mosche) [inline server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: Just a thought, maybe rename this variant to `compressorForUnknownXContentType` to rather describe when to use this? Or alternatively use a single `compressor(BytesReference bytes, @Nullable XContentType contentType)`?

File: server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java [hunk 3]
```diff
@@ -34,16 +53,24 @@ public static Compressor compressor(BytesReference bytes) {
...
+        return null;
+    }
 
+    /**
+     * Throw if {@code bytes} do not represent valid XContent.
+     *
+     * @deprecated XContent type detection is deprecated; see {@link XContentHelper#xContentType}.
+     */
+    @Deprecated
+    public static XContentType checkXContentType(BytesReference bytes) {
```
Comment (mosche) [inline server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: Rather than exposing a new deprecated method, can this be kept private to keep the surface clean and simple? For someone without context on this issue, it'll be hard to understand why this exists - and when it should be used.

**Review by mosche — CHANGES_REQUESTED** [review]
Thanks @prdoyle, functionally this looks correct except for the missing assert in  `isCompressed `. Looks like this even fixes some inconsistencies where `uncompress` might have thrown `NotXContentException` rather than `NotCompressedException`.
Though, I think we should try to not expose `checkXContentType`, adding a new deprecated method smells a bit. Can we keep that internal?

File: server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java (hunk 1 above)
Comment (prdoyle) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: This has only one caller, and it's in a test case. I figured it's a good time to just ditch the deprecated behaviour.

File: server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java (hunk 2 above)
Comment (prdoyle) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: Yeah that's a better name.

I'm hesitant to hide deprecated behaviour behind a parameter. Better off in a separate `@Deprecated` method I think.

File: server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java (hunk 3 above)
Comment (prdoyle) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: Yeah you have a point, but IMHO it actually makes more sense to throw an exception when we can't detect the XContent type, rather than return null. Looking through the code, most callers cannot tolerate nulls anyway, and will throw NPE or IllegalArgumentException.

It's probably misplaced in `CompressorFactory` though.

File: server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java (hunk 1 above)
Comment (mosche) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: makes sense, I missed that 👍

File: server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java (hunk 3 above)
Comment (prdoyle) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: Sorry, to clarify: I think actually almost everybody calling `XContentHelper.xContentType` should instead be calling a method that throws if it can't detect the type. Very few callers can actually tolerate being unable to detect the type. This would be that method.

I don't want to risk changing existing behaviour right now, but exposing this version of the method is IMHO a step forward.

Comment (mosche) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: I think this still makes sense in `CompressorFactory` for private use in `compressorAndCheckXContentType`, but exposing it publicly makes it hard to understand when this should be used. You could just call `compressorAndCheckXContentType` rather than `compressor` in the places where you're using `checkXContentType` (well, for the cost of guess the content type twice).

On the other hand, I think you're right and this doesn't belong here at all.
Wondering if the `isAncient` check is really still necessary or alternatively, if it must be guarded by `contentType == null`? There doesn't seem to be a risk of confusing either one. And `compressor` absolutely seems to be the wrong place to throw `NotXContentException`.

Comment (mosche) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: Ah, I didn't see you your previous reply. I agree, how about moving this into XContentHelper then?
As mentioned above, I think it'd be safe to keep the part checking for ancient compression in the compressor itself. It doesn't look like this can collide with xcontent detection.

Comment (mosche) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: btw, good chance to remove some dead code, `xContentTypeMayCompressed` looks entirely unused (and untested)

Comment (prdoyle) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: On second thought, the whole problem here is that this check is throwing the wrong exception. Perhaps this particular method is not the right place to embark on changing all callers to use the same method that throws the same exception. 🤔

Comment (mosche) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: I agree, it's strange this checks and throws `NotXContentException` in `CompressorFactory`. Totally fine on the other hand to throw `IllegalStateException("unsupported compression: index was created before v2.0.0.beta1 and wasn't upgraded?")`

Comment (prdoyle) [reply server/src/main/java/org/elasticsearch/common/compress/CompressorFactory.java]: Ok... I don't really want to risk changing the behaviour too much. I think I'll back off a bit on my refactoring and make more modest changes.

**Comment by prdoyle** [comment]
Ok @mosche I've force-pushed a less ambitious change, with three commits:
1. Refactor out a non-detecting version of the `CompressorFactory.compress` method
2. Add a failing unit test for #131605 
3. Fix the bug

File: server/src/main/java/org/elasticsearch/common/xcontent/XContentHelper.java [hunk 4]
```diff
@@ -120,7 +120,7 @@ public static XContentParser createParser(
     public static XContentParser createParser(XContentParserConfiguration config, BytesReference bytes, XContentType xContentType)
         throws IOException {
         Objects.requireNonNull(xContentType);
-        Compressor compressor = CompressorFactory.compressorForUnknownXContentType(bytes);
+        Compressor compressor = CompressorFactory.compressor(bytes);
```
Comment (prdoyle) [inline server/src/main/java/org/elasticsearch/common/xcontent/XContentHelper.java:123]: In this case, the one call site I _didn't_ change is the bug fix!

**Review by mosche — APPROVED** [review]
lgtm

**Comment by prdoyle** [comment]
For the record... The backport didn't fail; I canceled it when I realized I needed to revert this in `main`.
