### PR TITLE
Suppress `S3RepositoryAnalysisStrongMpusRestIT` in 3rd party runs

### LINKED ISSUE #138762: [CI] S3RepositoryAnalysisStrongMpusRestIT testRepositoryAnalysis failing
**Build Scans:**
- [elasticsearch-periodic #11515 / third-party_s3](https://gradle-enterprise.elastic.co/s/bqpiq4zqch5hc)
- [elasticsearch-periodic-java-ea #97 / third-party_s3](https://gradle-enterprise.elastic.co/s/aavwab4zz67si)
- [elasticsearch-pull-request #106640 / part-2](https://gradle-enterprise.elastic.co/s/4kkrmsqg542ao)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:snapshot-repo-test-kit:qa:s3:javaRestTest" --tests "org.elasticsearch.repositories.blobstore.testkit.analyze.S3RepositoryAnalysisStrongMpusRestIT.testRepositoryAnalysis" -Dtests.seed=80669518903C5E57 -Dtests.locale=ar-ER -Dtests.timezone=Asia/Amman -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.blobstore.testkit.analyze.S3RepositoryAnalysisStrongMpusRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRepositoryAnalysis'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:43459], URI [/_snapshot/repository?verify=true], status line [HTTP/1.1 500 Internal Server Error]
---
error:
  root_cause:
  - type: "repository_verification_exception"
    reason: "[repository] path [main_repo_test_kit_tests80669518903C5E57] is not accessible\
      \ on master node"
  type: "repository_verification_exception"
  reason: "[repository] path [main_repo_test_kit_tests80669518903C5E57] is not accessible\
    \ on master node"
  caused_by:
    type: "null_pointer_exception"
    reason: "host must not be null."
status: 500

```

**Issue Reasons:**
- [main] 2 consecutive failures in step third-party_s3
- [main] 3 failures in test testRepositoryAnalysis (6.1% fail rate in 49 executions)
- [main] 2 failures in step third-party_s3 (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DaveCTurner**
This test suite is only meaningful when running against the local test
fixture so this commit suppresses it in the third-party test runs.

Closes #138762

### CODE REVIEW

File: x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/AbstractS3RepositoryAnalysisRestTestCase.java [hunk 1]
```diff
@@ -26,11 +27,14 @@
 import static org.hamcrest.Matchers.not;
 
 public abstract class AbstractS3RepositoryAnalysisRestTestCase extends AbstractRepositoryAnalysisRestTestCase {
+
+    static final boolean USE_FIXTURE = Booleans.parseBoolean(System.getProperty("tests.use.fixture", "true"));
```
Comment (joshua-adams-1) [inline x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/AbstractS3RepositoryAnalysisRestTestCase.java:31]: What does `"tests.use.fixture"` mean?

**Review by joshua-adams-1 — APPROVED** [review]
LGTM!

File: x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/AbstractS3RepositoryAnalysisRestTestCase.java (hunk 1 above)
Comment (DaveCTurner) [reply x-pack/plugin/snapshot-repo-test-kit/qa/s3/src/javaRestTest/java/org/elasticsearch/repositories/blobstore/testkit/analyze/AbstractS3RepositoryAnalysisRestTestCase.java:31]: It's a somewhat convoluted way to tell whether we're running these tests with credentials etc in the environment variables:

https://github.com/elastic/elasticsearch/blob/b028c0af56597fe66593e2f34afe996504648bbd/x-pack/plugin/snapshot-repo-test-kit/qa/s3/build.gradle#L42

Those environment variables come from the build environment, see e.g.

https://github.com/elastic/elasticsearch/blob/e7975abd842faf8f74c46959a4b351ec76f1ca4f/.buildkite/scripts/third-party-test-credentials.sh#L35-L44
