### PR TITLE
[ML][Data Frame] Add optional defer_validation param to PUT

### LINKED ISSUE #43439: [ML] Make source checks more lax for dataframe transforms
It would be nice to loosen up the checks around Data Frames, even if only optionally.

In beats we create the dataframe as part of process startup, but don't start indexing events till after that, creating a bit of a chicken and egg problem. The exact amount of time can vary due to the fact that events may not come in right away.

It would be useful to define the DataFrame first, before any indices are created. Having it run as a noop before then is a fine outcome. Otherwise, client code needs to be more concerned with order of operations. As-is, creating a dataframe where the source index pattern matches nothing yields the following error:

```
Source index [heartbeat-8.0.0-*] does not exist
```

### PR DESCRIPTION
**Pull request by benwtrent**
This adds the optional boolean parameter `defer_validation` to the `PUT` transform API. This parameter will defer any validations that are considered addressable AFTER the configuration has been created. 

We do many validations eagerly against the current state of the cluster on PUT. This is so any issues can be captured early to prevent failures later when the data frame transform starts running. But, certain validations could be deferred until `_start` as the overall cluster state could have mutated between `PUT` and `_start`. 

The default behavior is to run the validations eagerly.

I did not add any reference or HLRC documentation yet. But will if desired.
@droberts195 
Do we want to document this parameter? It seems like a super user parameter and should almost never be used.

closes #43439

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java [hunk 1]
```diff
@@ -58,6 +58,11 @@ public Request(DataFrameTransformConfig config) {
         public Request(StreamInput in) throws IOException {
             super(in);
             this.config = new DataFrameTransformConfig(in);
+            if (in.getVersion().onOrAfter(Version.CURRENT)) {
+                this.deferValidation = in.readBoolean();
+            } else {
+                this.deferValidation = false;
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java]: In case you decide not to make "deferValidation" member variable final, you can remove the "else" branch here.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java [hunk 2]
```diff
@@ -47,9 +46,10 @@ private PutDataFrameTransformAction() {
         return AcknowledgedResponse::new;
     }
 
-    public static class Request extends AcknowledgedRequest<Request> implements ToXContentObject {
+    public static class Request extends AcknowledgedRequest<Request> {
 
         private final DataFrameTransformConfig config;
+        private boolean deferValidation = false;
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java]: I think this could be made final if you added constructor parameter "deferValidation" and removed setter method.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java [hunk 3]
```diff
@@ -58,6 +58,11 @@ public Request(DataFrameTransformConfig config) {
...
             super(in);
             this.config = new DataFrameTransformConfig(in);
+            if (in.getVersion().onOrAfter(Version.CURRENT)) {
+                this.deferValidation = in.readBoolean();
+            } else {
+                this.deferValidation = false;
+            }
         }
 
         public static Request fromXContent(final XContentParser parser, final String id) throws IOException {
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java]: This method doesn't consider the new field "deferValidation". Is that ok?

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java [hunk 4]
```diff
@@ -213,9 +212,15 @@ private void putDataFrame(DataFrameTransformConfig config, ActionListener<Acknow
         // <2> Put our transform
         ActionListener<Boolean> pivotValidationListener = ActionListener.wrap(
             validationResult -> dataFrameTransformsConfigManager.putTransformConfiguration(config, putTransformConfigurationListener),
-            validationException -> listener.onFailure(
-                new RuntimeException(DataFrameMessages.REST_PUT_DATA_FRAME_FAILED_TO_VALIDATE_DATA_FRAME_CONFIGURATION,
-                    validationException))
+            validationException -> {
+                if (validationException instanceof Pivot.TestQueryException && request.isDeferValidation()) {
```
Comment (przemekwitek) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java]: So are we going to defer selected validations on a case-by-case basis? Or do you follow a concrete rule that says which validations are ok to be deferred?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameRequestConvertersTests.java [hunk 5]
```diff
@@ -66,14 +66,17 @@ public void testPutDataFrameTransform() throws IOException {
         PutDataFrameTransformRequest putRequest = new PutDataFrameTransformRequest(
                 DataFrameTransformConfigTests.randomDataFrameTransformConfig());
         Request request = DataFrameRequestConverters.putDataFrameTransform(putRequest);
-
+        assertFalse(request.getParameters().containsKey("defer_validation"));
```
Comment (przemekwitek) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameRequestConvertersTests.java]: I'd rewrite it to:
assertThat(request.getParameters(), not(hasKey("defer_validation"));

This has the advantage of spitting better message when the assertion fails.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameRequestConvertersTests.java [hunk 6]
```diff
@@ -66,14 +66,17 @@ public void testPutDataFrameTransform() throws IOException {
...
         assertEquals(HttpPut.METHOD_NAME, request.getMethod());
         assertThat(request.getEndpoint(), equalTo("/_data_frame/transforms/" + putRequest.getConfig().getId()));
 
         try (XContentParser parser = createParser(JsonXContent.jsonXContent, request.getEntity().getContent())) {
             DataFrameTransformConfig parsedConfig = DataFrameTransformConfig.PARSER.apply(parser, null);
             assertThat(parsedConfig, equalTo(putRequest.getConfig()));
         }
+        putRequest.setDeferValidations(true);
+        request = DataFrameRequestConverters.putDataFrameTransform(putRequest);
+        assertThat(request.getParameters().get("defer_validation"), equalTo(Boolean.toString(putRequest.getDeferValidations())));
```
Comment (przemekwitek) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameRequestConvertersTests.java]: I'd rewrite it to:
assertThat(request.getParameters(), hasEntry("defer_validation", Boolean.toString(putRequest.getDeferValidations()));

File: client/rest-high-level/src/main/java/org/elasticsearch/client/dataframe/PutDataFrameTransformRequest.java [hunk 7]
```diff
@@ -41,6 +43,19 @@ public DataFrameTransformConfig getConfig() {
         return config;
     }
 
+    public Boolean getDeferValidations() {
```
Comment (przemekwitek) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/dataframe/PutDataFrameTransformRequest.java]: Why is it sometimes spelled singular ("validation") and sometimes plural ("validations")? Is it deliberate?

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java (hunk 4 above)
Comment (davidkyle) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java]: This is coming from `Pivot.validate()` just off the screen isn't it? Why not add a `run_test_query` parameter to that method or break up `Pivot.validate()` to do the supported aggs check and test query in different methods.

File: client/rest-high-level/src/main/java/org/elasticsearch/client/dataframe/PutDataFrameTransformRequest.java (hunk 7 above)
Comment (davidkyle) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/dataframe/PutDataFrameTransformRequest.java]: I'm +1 for the singular `deferValidation`

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java [hunk 8]
```diff
@@ -26,7 +27,14 @@
  */
 public final class SourceDestValidator {
 
-    private SourceDestValidator() {}
+    interface SourceDestValidation {
```
Comment (davidkyle) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java]: 👍

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java [hunk 9]
```diff
@@ -58,6 +58,11 @@ public Request(DataFrameTransformConfig config) {
         public Request(StreamInput in) throws IOException {
             super(in);
             this.config = new DataFrameTransformConfig(in);
+            if (in.getVersion().onOrAfter(Version.CURRENT)) {
```
Comment (hendrikmuhs) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java]: as for check in BWC code like this: you can alternatively set the version, disable BWC in `build.gradle`, do the backports and then re-enable BWC. You need the same number of commits in the end, but using the "`Version.CURRENT` approach" still broke CI, disabling BWC seems to be the better approach now.

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java (hunk 4 above)
Comment (hendrikmuhs) [reply x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/action/TransportPutDataFrameTransformAction.java]: +1 for splitting `Pivot.validate()` into syntax (or config) validation and runtime validation

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java [hunk 10]
```diff
@@ -26,7 +27,14 @@
...
+        boolean isDeferrable();
+        void check(DataFrameTransformConfig config, ClusterState clusterState, IndexNameExpressionResolver indexNameExpressionResolver);
```
Comment (hendrikmuhs) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/SourceDestValidator.java]: nit: I still find it confusing that I have to call `check` and not `validate` on a "validator". (Vice versa it could also be a `SourceDestChecker` if you prefer to keep `check`)

**Review by hendrikmuhs — COMMENTED** [review]
added some comments. 

I think we should document this new parameter but make very clear what the usecase is. Nit: It would be good to add some logging if the parameter is used (debug level).

**Comment by davidkyle** [comment]
> I think we should document this new parameter but make very clear what the usecase

Yes, the source is open after all we should document and explain when it should be use. Remember it only defers so any error will be hit when validations are run on start anyway. 

Also if the has privilege validation is deferrable it should checked on start

**Comment by droberts195** [comment]
> Also if the has privilege validation is deferrable it should checked on start

I don't think this is, because the rule is that the transform accesses the source and destination indices with the security privileges of the user who put it, not the user who starts it.  The has-privileges API can only return the privileges of the current user, so could only check if the user calling start had the necessary privileges, not the user who called put.

This doesn't create a security issue - in the end if the user who put the transform doesn't have permission to read the source index and write to the destination then it won't do these things.  But it _does_ make the error reporting less friendly.

Maybe this can just be documented as a caveat of deferring validation: if you defer validation we assume you've thought about the security aspects of the transform and the transform will run but fail if you haven't.

I think this has actually opened up a can of worms though relating to the security aspects of the envisaged use case for this functionality: none of the built-in Beats roles have permission to put a data frame transform nor create an index other than those currently used by Beats.  If Beats is going to use data frame transforms then the user that Beats connects as needs to have permission to manage data frame transforms and create and write to the destination indices configured in those transforms.  Presumably to restrict abuse we'd have to set aside a pattern for those destination indices and only give the Beats user index permissions on that pattern.  Then we'd have to document what that pattern is and warn users not to let indices storing unrelated confidential data match it.

**Comment by davidkyle** [comment]
👍 makes sense. 

Assuming insufficient privileges causes a detectable exception we should handle that as an irrecoverable failure without retry. 

https://github.com/elastic/elasticsearch/blob/92709f51c13c8a3650ec14de90f034a438fd6b06/x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformTask.java#L803

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java (hunk 3 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java]: Only if I don't add the variable to the ctor. Right now the request assumes that a config is the payload and `deferValidation` is a REST param. I think that this particular input is just fine. I could add the variable as a parameter here and mark it final

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java (hunk 9 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/dataframe/action/PutDataFrameTransformAction.java]: @hendrikmuhs I usually mute the tests before I backport in a separate PR. This way BWC can actually run against my changes and I can find any issues earlier rather than later.

File: docs/reference/data-frames/apis/put-transform.asciidoc [hunk 11]
```diff
@@ -45,6 +45,17 @@ IMPORTANT:  You must use {kib} or this API to create a {dataframe-transform}.
   can contain lowercase alphanumeric characters (a-z and 0-9), hyphens, and
   underscores. It must start and end with alphanumeric characters.
 
+[[put-data-frame-transform-query-parms]]
+==== {api-query-parms-title}
+
+`defer_validations`::
+ (Optional, boolean) When `true`, this will cause deferrable validations to not run.
```
Comment (davidkyle) [inline docs/reference/data-frames/apis/put-transform.asciidoc]: We should include more detail about deferred validations before the second sentence. 

```suggestion
 (Optional, boolean) When `true`, this will cause deferrable validations to not run. Deferrable validations include checks for the existence of the source index and that the user has sufficient privileges, skipping these validations at creation is useful for situations where the source index does not exist but will be created later. Deferred validations are always run when the {dataframe-transform} is started.
```

Comment (droberts195) [reply docs/reference/data-frames/apis/put-transform.asciidoc]: Maybe the very last sentence of that suggested change should be changed to: "Deferred validations are always run when the {dataframe-transform} is started, with the exception of privilege checks. If the user who created the transform does not have the required privileges on the source and destination indices then the transform will start but then fail when it attempts the unauthorized operation."

Comment (lcawl) [reply docs/reference/data-frames/apis/put-transform.asciidoc]: These details are great, thanks!

File: client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameRequestConvertersTests.java [hunk 12]
```diff
@@ -66,14 +68,17 @@ public void testPutDataFrameTransform() throws IOException {
         PutDataFrameTransformRequest putRequest = new PutDataFrameTransformRequest(
                 DataFrameTransformConfigTests.randomDataFrameTransformConfig());
         Request request = DataFrameRequestConverters.putDataFrameTransform(putRequest);
-
+        assertThat(request.getParameters(), not(hasKey("defer_validation")));
         assertEquals(HttpPut.METHOD_NAME, request.getMethod());
```
Comment (przemekwitek) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameRequestConvertersTests.java]: While you are, could you change "assertEquals" to "assertThat(..., equalTo(...)) so that the usage of assertions is consistent in the whole method.

File: docs/java-rest/high-level/dataframe/put_data_frame.asciidoc [hunk 13]
```diff
@@ -20,6 +20,10 @@ A +{request}+ requires the following argument:
 include-tagged::{doc-tests-file}[{api}-request]
 --------------------------------------------------
 <1> The configuration of the {dataframe-transform} to create
+<2> Whether or not to wait to run deferrable validations until `_start` is called.
```
Comment (przemekwitek) [inline docs/java-rest/high-level/dataframe/put_data_frame.asciidoc]: [nit] "Whether or not to wait to run deferrable validations" sounds a bit complicated, but I guess you wanted to avoid "Whether or not to defer deferrable validations until ...". Anyway, I would try to somehow simplify it.

File: docs/reference/data-frames/apis/put-transform.asciidoc [hunk 14]
```diff
@@ -45,6 +45,18 @@ IMPORTANT:  You must use {kib} or this API to create a {dataframe-transform}.
   can contain lowercase alphanumeric characters (a-z and 0-9), hyphens, and
   underscores. It must start and end with alphanumeric characters.
 
+[[put-data-frame-transform-query-parms]]
+==== {api-query-parms-title}
+
+`defer_validations`::
```
Comment (przemekwitek) [inline docs/reference/data-frames/apis/put-transform.asciidoc]: I think it is now singular everywhere.

**Review by przemekwitek — APPROVED** [review]
LGTM

**Review by hendrikmuhs — APPROVED** [review]
LGTM

File: docs/java-rest/high-level/dataframe/put_data_frame.asciidoc (hunk 13 above)
Comment (davidkyle) [reply docs/java-rest/high-level/dataframe/put_data_frame.asciidoc]: Maybe Postpone deferrable validations until _start is called.

**Review by davidkyle — APPROVED** [review]
LGTM
