### PR TITLE
Azure blob store's readBlob() method first checks if the blob exists

### LINKED ISSUE #23480: Getting all snapshots with a secondary only azure repository takes a long time
**Elasticsearch version**: 5.2.1
**Plugins installed**: `repository-azure`

I created an azure storage account with [Read-access geo-redundant storage (RA-GRS)](https://docs.microsoft.com/en-us/azure/storage/storage-redundancy#read-access-geo-redundant-storage).
Then I configure `elasticsearch.yml` with:

```yml
cloud:
    azure:
        storage:
            my_account:
                account: ACCOUNT
                key: KEY
```

Then:

```
PUT _snapshot/primary
{
  "type": "azure",
  "settings": {
    "account": "my_account",
    "container": "container"
  }
}
GET _snapshot/primary/_all
```

This takes less than a second.

```
PUT _snapshot/secondary
{
  "type": "azure",
  "settings": {
    "account": "my_account",
    "container": "container",
    "location_mode": "secondary_only"
  }
}
GET _snapshot/secondary/_all
```

This takes something like 5 minutes.

This seems to be a regression from 5.1 series.

### PR DESCRIPTION
**Pull request by abeyad**
Previously, the Azure blob store would depend on a 404 StorageException
coming back from Azure if trying to open an input stream to a
non-existent blob.  This works for Azure repositories which access a
primary location path.  For those configured to access a secondary
location path, the Azure SDK keeps trying for a long while before
returning a 404 StorageException, causing potential delays in the
snapshot APIs.  This commit makes an initial check if the blob exists in
Azure and returns immediately with a NoSuchFileException, instead of
trying to open the input stream to the blob.

Closes #23480

### CODE REVIEW

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+import org.elasticsearch.test.ESIntegTestCase.ClusterScope;
+
+import static org.hamcrest.Matchers.equalTo;
+import static org.hamcrest.Matchers.lessThanOrEqualTo;
+
+/**
+ * This test needs Azure to run and -Dtests.thirdparty=true to be set
+ * and -Dtests.config=/path/to/elasticsearch.yml
+ * @see AbstractAzureWithThirdPartyIntegTestCase
+ */
```
Comment (dadoonet) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: I think we need to add that this test requires an azure storage account defined as a `Read-access geo-redundant storage (RA-GRS)`.

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+        scope = ESIntegTestCase.Scope.SUITE,
+        supportsDedicatedMasters = false, numDataNodes = 1,
+        transportClientRatio = 0.0)
+public class AzureSnapshotRestoreListSnapshotsTests extends AbstractAzureWithThirdPartyIntegTestCase {
+    public void testList() {
+        Client client = client();
+        logger.info("-->  creating azure primary repository");
+        PutRepositoryResponse putRepositoryResponsePrimary = client.admin().cluster().preparePutRepository("primary")
+                .setType("azure").setSettings(Settings.builder()
+                        .put(Repository.ACCOUNT_SETTING.getKey(), "my_account")
```
Comment (dadoonet) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: I think this is not needed. It should use the default account available.

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java [hunk 3]
```diff
@@ -0,0 +1,76 @@
...
+                        .put(Repository.CONTAINER_SETTING.getKey(), "container")
+                ).get();
+        assertThat(putRepositoryResponsePrimary.isAcknowledged(), equalTo(true));
+        logger.info("-->  creating azure secondary repository");
+        PutRepositoryResponse putRepositoryResponseSecondary = client.admin().cluster().preparePutRepository("secondary")
+                .setType("azure").setSettings(Settings.builder()
+                        .put(Repository.ACCOUNT_SETTING.getKey(), "my_account")
```
Comment (dadoonet) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: I think this is not needed. It should use the default account available.

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+        supportsDedicatedMasters = false, numDataNodes = 1,
+        transportClientRatio = 0.0)
+public class AzureSnapshotRestoreListSnapshotsTests extends AbstractAzureWithThirdPartyIntegTestCase {
+    public void testList() {
+        Client client = client();
+        logger.info("-->  creating azure primary repository");
+        PutRepositoryResponse putRepositoryResponsePrimary = client.admin().cluster().preparePutRepository("primary")
+                .setType("azure").setSettings(Settings.builder()
+                        .put(Repository.ACCOUNT_SETTING.getKey(), "my_account")
+                        .put(Repository.CONTAINER_SETTING.getKey(), "container")
```
Comment (dadoonet) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: May be randomize the container name as we do in `AzureSnapshotRestoreTests`?

```java
    private static String getContainerName() {
        String testName = "snapshot-itest-".concat(RandomizedTest.getContext().getRunnerSeedAsString().toLowerCase(Locale.ROOT));
        return testName.contains(" ") ? Strings.split(testName, " ")[0] : testName;
    }
```

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+                ).get();
+        assertThat(putRepositoryResponsePrimary.isAcknowledged(), equalTo(true));
+        logger.info("-->  creating azure secondary repository");
+        PutRepositoryResponse putRepositoryResponseSecondary = client.admin().cluster().preparePutRepository("secondary")
+                .setType("azure").setSettings(Settings.builder()
+                        .put(Repository.ACCOUNT_SETTING.getKey(), "my_account")
+                        .put(Repository.CONTAINER_SETTING.getKey(), "container")
```
Comment (dadoonet) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: And reuse the randomized container name here?

**Review by dadoonet — APPROVED** [review]
Left small comments. It's good to me.

**Comment by abeyad** [comment]
thanks for the review @dadoonet, I pushed a commit to address your comments and create a random container name each time.

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java [hunk 6]
```diff
@@ -19,58 +19,100 @@
...
-        assertThat(putRepositoryResponseSecondary.isAcknowledged(), equalTo(true));
-
 
         logger.info("--> start get snapshots on primary");
         long startWait = System.currentTimeMillis();
         client.admin().cluster().prepareGetSnapshots("primary").get();
         long endWait = System.currentTimeMillis();
         // definitely should be done in 30s, and if its not working as expected, it takes over 1m
         assertThat(endWait - startWait, lessThanOrEqualTo(30000L));
+        removeContainer(containerName);
```
Comment (dadoonet) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: Why do you remove and create again?

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+                ).get();
+        assertThat(putRepositoryResponseSecondary.isAcknowledged(), equalTo(true));
+
+        logger.info("--> start get snapshots on secondary");
+        startWait = System.currentTimeMillis();
+        client.admin().cluster().prepareGetSnapshots("secondary").get();
+        endWait = System.currentTimeMillis();
+        logger.info("--> end of get snapshots on secondary. Took {} ms", endWait - startWait);
+        assertThat(endWait - startWait, lessThanOrEqualTo(30000L));
+        removeContainer(containerName);
```
Comment (dadoonet) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: May be do that in an After method so it's always removed?

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java [hunk 8]
```diff
@@ -0,0 +1,118 @@
...
+        assertThat(putRepositoryResponsePrimary.isAcknowledged(), equalTo(true));
+
+        logger.info("--> start get snapshots on primary");
+        long startWait = System.currentTimeMillis();
+        client.admin().cluster().prepareGetSnapshots("primary").get();
+        long endWait = System.currentTimeMillis();
+        // definitely should be done in 30s, and if its not working as expected, it takes over 1m
+        assertThat(endWait - startWait, lessThanOrEqualTo(30000L));
+        removeContainer(containerName);
+
```
Comment (dadoonet) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: Remove and create again is not needed I think

**Review by dadoonet — CHANGES_REQUESTED** [review]

**Comment by abeyad** [comment]
I pushed c1926694cc2def0dc7426fb6c8b39b6e0d0e1b07

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java [hunk 9]
```diff
@@ -0,0 +1,121 @@
...
+        scope = ESIntegTestCase.Scope.SUITE,
+        supportsDedicatedMasters = false, numDataNodes = 1,
+        transportClientRatio = 0.0)
+public class AzureSnapshotRestoreListSnapshotsTests extends AbstractAzureWithThirdPartyIntegTestCase {
+
+    private final AzureStorageService azureStorageService = new AzureStorageServiceImpl(readSettingsFromFile());
+    private final String containerName = getContainerName();
+
+    @Before
+    public void setupContainer() {
```
Comment (dadoonet) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: Needed?

**Review by dadoonet — APPROVED** [review]
Great! Left a small last comment.

File: plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java (hunk 9 above)
Comment (abeyad) [inline plugins/repository-azure/src/test/java/org/elasticsearch/repositories/azure/AzureSnapshotRestoreListSnapshotsTests.java]: removed

**Comment by abeyad** [comment]
thanks @dadoonet

**Comment by abeyad** [comment]
5.x commit: 02cd2aef01968530e0dd45cfffac727f8653da77
5.3 commit: 47ae063d0de5eb54f4ab3d0eb865e4bb5245125b
