### PR TITLE
Log suppressed stack traces under DEBUG

### LINKED ISSUE #15329: Option to suppress DocumentAlreadyExistsException
Currently when op_type=create is used, we write the following exception at the INFO level to the ES log file for each document that is rejected.  This can potentially write a ton of entries to the logs, drowning other more important log entries.

```
[2015-12-08 23:01:08,790][INFO ][rest.suppressed          ] /test/type/1 Params: {id=1, index=test, op_type=create, type=type}
[test][[test][3]] DocumentAlreadyExistsException[[type][1]: document already exists]
	at org.elasticsearch.index.engine.InternalEngine.innerCreateNoLock(InternalEngine.java:411)
	at org.elasticsearch.index.engine.InternalEngine.innerCreate(InternalEngine.java:369)
	at org.elasticsearch.index.engine.InternalEngine.create(InternalEngine.java:341)
	at org.elasticsearch.index.shard.IndexShard.create(IndexShard.java:517)
	at org.elasticsearch.index.engine.Engine$Create.execute(Engine.java:789)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1073)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:170)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Maybe we can provide an option to suppress these, or write them to the DEBUG level, etc..

### LINKED ISSUE #16622: Excessive stack trace logging in 2.2
Every 404 on an unknown index in Elasticsearch 2.2 generates a 63 line stack trace in the main log by default. It's not very useful.

Other similarly minor log lines also print stack traces, but it usually seems to only be a few lines which isn't as big of a deal.

It seems rare an end user of Elasticsearch would ever want stack traces on anything but ERROR by default.

### PR DESCRIPTION
**Pull request by bleskes**
To make API's output more easy to read we are suppressing stack traces (#12991) unless explicitly requested by setting `error_trace=true` on the request. To compensate we are logging the stacktrace into the logs so people can look it up even the error_trace wasn't enabled. Currently we do so using the `INFO` level which can be verbose if an api is called repeatedly by some automation.  For example, if someone tries to read from an index that doesn't exist we will respond with a 404 exception and log under info every time. We should reduce the level to `DEBUG` as we do with other API driven errors (internal issues that are not related to the API should be logged by other components already, based on their severity)

Closes #15329
Closes #16622

### CODE REVIEW

**Comment by nik9000** [comment]
I wonder if it makes more sense to have a severity on ESExceptions and use that. The 404 exception can be debug or trace or whatever and unexpected ones can stay info or warn even. I dunno. I'm not picky though.

**Comment by nik9000** [comment]
Actually, we already have a status to return. How about we log all 4xx statuses as debug and all 5xx statuses as info?

**Comment by s1monw** [comment]
> Actually, we already have a status to return. How about we log all 4xx statuses as debug and all 5xx statuses as info?

+1

**Comment by bleskes** [comment]
> Actually, we already have a status to return. How about we log all 4xx statuses as debug and all 5xx statuses as info?

I was thinking along the same line but didn't want to open the discussion (and I also see some downsides). It seems that using rest status occurred to more people. I'll do that.

**Comment by nik9000** [comment]
> I also see some downsides

Please post them when you can. I can't think of any but I certainly don't know all there is to know.

**Comment by bleskes** [comment]
@nik9000 @s1monw I pushed an update

**Comment by nik9000** [comment]
Fine by me.

File: core/src/main/java/org/elasticsearch/rest/BytesRestResponse.java [hunk 1]
```diff
@@ -126,7 +126,11 @@ private static XContentBuilder convert(RestChannel channel, RestStatus status, T
             if (channel.request().paramAsBoolean("error_trace", !ElasticsearchException.REST_EXCEPTION_SKIP_STACK_TRACE_DEFAULT)) {
                 params =  new ToXContent.DelegatingMapParams(Collections.singletonMap(ElasticsearchException.REST_EXCEPTION_SKIP_STACK_TRACE, "false"), channel.request());
             } else {
-                SUPPRESSED_ERROR_LOGGER.info("{} Params: {}", t, channel.request().path(), channel.request().params());
+                if (status.getStatus() < 500) {
+                    SUPPRESSED_ERROR_LOGGER.debug("{} Params: {}", t, channel.request().path(), channel.request().params());
+                } else {
+                    SUPPRESSED_ERROR_LOGGER.info("{} Params: {}", t, channel.request().path(), channel.request().params());
```
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/rest/BytesRestResponse.java]: Since we know this was a 5xx, should this be warn or error?

Comment (bleskes) [inline core/src/main/java/org/elasticsearch/rest/BytesRestResponse.java]: I can go with error. Will update the PR unless people object soon :)

Comment (nik9000) [inline core/src/main/java/org/elasticsearch/rest/BytesRestResponse.java]: I'd prefer warning :smile: Mentally I reserve error for issues like "oh no I'm going to lose data" or "oh boy I have to crash now" rather than "sorry, I'm busted and can't do what you wanted".  That feels like solid warning territory for me.

**Comment by bleskes** [comment]
I updated the PR log with `ERROR` for 5xx codes.

>> I also see some downsides

> Please post them when you can. I can't think of any but I certainly don't know all there is to know.

There are high traffic APIs that can respond with 503  - hitting a node that can't join it's master. Indexing to a shard whose primary is having problems etc. This will spam the logs. I wanted to have an easy win so I think logging an error on 5xx (instead of the current info) and debug on other errors gives an improvement to what we doing now (info all the time).

File: core/src/main/java/org/elasticsearch/rest/BytesRestResponse.java (hunk 1 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/rest/BytesRestResponse.java]: You wish is my command. Warn it is :)

**Comment by nik9000** [comment]
> This will spam the logs. I wanted to have an easy win so I think logging an error on 5xx (instead of the current info) and debug on other errors gives an improvement to what we doing now (info all the time).

That makes sense. I think we should fix that but I don't know how really. On the other hand this change is obviously an improvement and we should get it. LGTM.

**Comment by s1monw** [comment]
@bleskes wanna merge this? LGTM
