### PR TITLE
Do not create missing directories in readonly repo

### LINKED ISSUE #41009: Shared filesystem repository does not respect readonly setting
A user reports the following exception when restoring a snapshot from a readonly filesystem:

```
[2019-04-05T21:46:35,634][WARN ][o.e.s.RestoreService ] [REDACTED] [REDACTED:REDACTED] failed to restore snapshot 
org.elasticsearch.ElasticsearchException: failed to create blob container 
at org.elasticsearch.common.blobstore.fs.FsBlobStore.blobContainer(FsBlobStore.java:71) ~[elasticsearch-6.6.1.jar:6.6.1] 
at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotIndexMetaData(BlobStoreRepository.java:591) ~[elasticsearch-6.6.1.jar:6.6.1] 
at org.elasticsearch.snapshots.RestoreService.restoreSnapshot(RestoreService.java:210) [elasticsearch-6.6.1.jar:6.6.1] 
at org.elasticsearch.action.admin.cluster.snapshots.restore.TransportRestoreSnapshotAction.masterOperation(TransportRestoreSnapshotAction.java:91) [elasticsearch-6.6.1.jar:6.6.1] 
at org.elasticsearch.action.admin.cluster.snapshots.restore.TransportRestoreSnapshotAction.masterOperation(TransportRestoreSnapshotAction.java:49) [elasticsearch-6.6.1.jar:6.6.1] 
at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:124) [elasticsearch-6.6.1.jar:6.6.1] 
at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:211) [elasticsearch-6.6.1.jar:6.6.1] 
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) [elasticsearch-6.6.1.jar:6.6.1] 
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.6.1.jar:6.6.1] 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?] 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?] 
at java.lang.Thread.run(Thread.java:834) [?:?] 
Caused by: java.nio.file.FileSystemException: REDACTED: Read-only file system 
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:100) ~[?:?] 
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?] 
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?] 
at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385) ~[?:?] 
at java.nio.file.Files.createDirectory(Files.java:689) ~[?:?] 
at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796) ~[?:?] 
at java.nio.file.Files.createDirectories(Files.java:782) ~[?:?] 
at org.elasticsearch.common.blobstore.fs.FsBlobStore.buildAndCreate(FsBlobStore.java:88) ~[elasticsearch-6.6.1.jar:6.6.1] 
at org.elasticsearch.common.blobstore.fs.FsBlobStore.blobContainer(FsBlobStore.java:69) ~[elasticsearch-6.6.1.jar:6.6.1] 
... 11 more 
```

The following line looks to be bogus, because it checks for the `readonly` property of the node's settings rather than the repository metadata:

https://github.com/elastic/elasticsearch/blob/022726011ce1d9e4748fd39293a3aeae6954b3ac/server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobStore.java#L45

Relates #26909

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today we erroneously look for a node setting called `readonly` when deciding
whether or not to create a missing directory in a filesystem repository. This
change fixes this by using the repository setting instead.

Closes #41009
Relates #26909

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobStore.java [hunk 1]
```diff
@@ -84,7 +89,7 @@ public void close() {
 
     private synchronized Path buildAndCreate(BlobPath path) throws IOException {
         Path f = buildPath(path);
-        if (!readOnly) {
+        if (readOnly == false) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobStore.java]: Maybe we should also just throw here if `f` doesn't exist as well? I think that would make things a little easier to debug down the line instead of just quietly creating the unusable `BlobContainer` in `#blobcontainer` above and then throwing on all the operations?

File: server/src/test/java/org/elasticsearch/repositories/fs/FsBlobStoreRepositoryIT.java [hunk 2]
```diff
@@ -41,4 +50,62 @@ protected void createTestRepository(String name, boolean verify) {
...
+            .put("location", repoPath).put("readonly", true)));
+
+        final ElasticsearchException exception = expectThrows(ElasticsearchException.class, () ->
+            client().admin().cluster().prepareRestoreSnapshot(repoName, snapshotName).setWaitForCompletion(randomBoolean()).get());
+        assertThat(exception.getRootCause(), instanceOf(NoSuchFileException.class));
+
+        assertFalse("deleted path is not recreated in readonly repository", Files.exists(deletedPath));
+    }
+
+    private void deleteRecursive(Path p) throws IOException {
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/repositories/fs/FsBlobStoreRepositoryIT.java]: I think you can just use `org.elasticsearch.core.internal.io.IOUtils#rm(java.nio.file.Path...)` here? :)

**Review by original-brownbear — APPROVED** [review]
LGTM (assuming tests go green), left two suggestions :)

File: server/src/test/java/org/elasticsearch/repositories/fs/FsBlobStoreRepositoryIT.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/repositories/fs/FsBlobStoreRepositoryIT.java]: Thanks, I was sure we had that somewhere but couldn't find it.

File: server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobStore.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobStore.java]: Hmm. I know what you mean, but today it seems to be ok to make a blob container on a nonexistent path and to treat it as if it is empty. See e.g. `FsBlobStoreTests#testReadOnly` that asserts that this is the desired behaviour. I can't immediately see any problems with changing this, but I think it needs more analysis to be sure.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/common/blobstore/fs/FsBlobStore.java]: Ah right nevermind then :) I guess not throwing here is more aligned with blob stores and the URL repository anyway.
I was only thinking about making the case of e.g. trying to load an index that doesn't exist (i.e. not even its folder exists) a little easier to debug but you're right it's not worth the behaviour change :)
