### PR TITLE
[ML] Wait for shards to initialize after creating ML internal indices

### LINKED ISSUE #54887: [CI] denying access as action [internal:admin/tasks/ban] is not an index or cluster action
An ML test failed in https://gradle-enterprise.elastic.co/s/d5tipghjjliwc

The error was:

```
Failure at [mixed_cluster/90_ml_data_frame_analytics_crud:83]: expected [2xx] status code but api [ml.stop_data_frame_analytics] returned [409 Conflict] [{"error":{"root_cause":[{"type":"status_exception","reason":"cannot close data frame analytics [old_cluster_regression_job] because it failed, use force stop instead","stack_trace":"org.elasticsearch.ElasticsearchStatusException: cannot close data frame analytics [old_cluster_regression_job] because it failed, use force stop instead\n\tat org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.conflictStatusException(ExceptionsHelper.java:67)\n\tat org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.normalStop(TransportStopDataFrameAnalyticsAction.java:143)\n\tat org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.lambda$doExecute$0(TransportStopDataFrameAnalyticsAction.java:111)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.lambda$expandIds$3(TransportStopDataFrameAnalyticsAction.java:131)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.ml.dataframe.persistence.DataFrameAnalyticsConfigProvider.lambda$getMultiple$3(DataFrameAnalyticsConfigProvider.java:133)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:158)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:151)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.xpack.ml.action.TransportGetDataFrameAnalyticsAction.lambda$doExecute$0(TransportGetDataFrameAnalyticsAction.java:63)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.core.action.AbstractTransportGetResourcesAction$1.onResponse(AbstractTransportGetResourcesAction.java:124)\n\tat org.elasticsearch.xpack.core.action.AbstractTransportGetResourcesAction$1.onResponse(AbstractTransportGetResourcesAction.java:97)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:158)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:151)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:545)\n\tat org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:117)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:350)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:344)\n\tat org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:231)\n\tat org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:119)\n\tat org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:125)\n\tat org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:691)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.lang.Thread.run(Thread.java:834)\n"}],"type":"status_exception","reason":"cannot close data frame analytics [old_cluster_regression_job] because it failed, use force stop instead","stack_trace":"org.elasticsearch.ElasticsearchStatusException: cannot close data frame analytics [old_cluster_regression_job] because it failed, use force stop instead\n\tat org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.conflictStatusException(ExceptionsHelper.java:67)\n\tat org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.normalStop(TransportStopDataFrameAnalyticsAction.java:143)\n\tat org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.lambda$doExecute$0(TransportStopDataFrameAnalyticsAction.java:111)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.ml.action.TransportStopDataFrameAnalyticsAction.lambda$expandIds$3(TransportStopDataFrameAnalyticsAction.java:131)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.ml.dataframe.persistence.DataFrameAnalyticsConfigProvider.lambda$getMultiple$3(DataFrameAnalyticsConfigProvider.java:133)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:158)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:151)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.xpack.ml.action.TransportGetDataFrameAnalyticsAction.lambda$doExecute$0(TransportGetDataFrameAnalyticsAction.java:63)\n\tat org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)\n\tat org.elasticsearch.xpack.core.action.AbstractTransportGetResourcesAction$1.onResponse(AbstractTransportGetResourcesAction.java:124)\n\tat org.elasticsearch.xpack.core.action.AbstractTransportGetResourcesAction$1.onResponse(AbstractTransportGetResourcesAction.java:97)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:91)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:158)\n\tat org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:151)\n\tat org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.sendSearchResponse(AbstractSearchAsyncAction.java:545)\n\tat org.elasticsearch.action.search.ExpandSearchPhase.run(ExpandSearchPhase.java:117)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:350)\n\tat org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:344)\n\tat org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:231)\n\tat org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:119)\n\tat org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:125)\n\tat org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:95)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:691)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.lang.Thread.run(Thread.java:834)\n"},"status":409}]
```

However, the server side logs (downloadable from https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=adoptopenjdk11,nodes=general-purpose/616/gcsObjects/) show the following error was the root cause:

```
[2020-04-07T05:23:07,037][WARN ][o.e.x.s.a.AuthorizationService] [v8.0.0-1] denying access as action [internal:admin/tasks/ban] is not an index or cluster action
```

That message is from `x-pack/qa/rolling-upgrade/build/testclusters/v8.0.0-1/logs/v8.0.0.log`.

It looks like the ban action needs to be called from within the system security context, and this does not always happen (although it must happen sometimes by coincidence as the test failure is quite rare).

### LINKED ISSUE #55221: ClassificationIT testSetUpgradeMode_ExistingTaskGetsUnassigned Failure
https://gradle-enterprise.elastic.co/s/75oonfpb3j3mw

```
org.elasticsearch.ElasticsearchException: all shards failedClose stacktrace
at __randomizedtesting.SeedInfo.seed([B5428DD8494405BC:568FC3C8087049D8]:0)
at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:55)
at org.elasticsearch.xpack.ml.action.TransportGetDataFrameAnalyticsStatsAction.lambda$searchStats$8(TransportGetDataFrameAnalyticsStatsAction.java:216)
```

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testSetUpgradeMode_ExistingTaskGetsUnassigned" -Dtests.seed=B5428DD8494405BC -Dtests.security.manager=true -Dtests.locale=es-AR -Dtests.timezone=America/Argentina/Ushuaia -Dcompiler.java=14
HomeTestsorg.elasticsearch.xpack.ml.integration.ClassificationIT » testSetUpgradeMode_ExistingTaskGetsUnassigned
```

### LINKED ISSUE #55807: RegressionIT. testTwoJobsWithSameRandomizeSeedUseSameTrainingSet fails on 7.x
Build 20200427110658-3288FBEC
Log https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/715/console
Build Scans
[7.7.0] https://gradle-enterprise.elastic.co/s/wod4ndjqklih6
[7.6.3] https://gradle-enterprise.elastic.co/s/vrpyflwqudi36
[6.8.9] https://gradle-enterprise.elastic.co/s/mppjhffgu3jg2
[6.8.9] https://gradle-enterprise.elastic.co/s/mwcdcz4fqnbem
[7.7.0] https://gradle-enterprise.elastic.co/s/pu2t7imvl6ygg
[7.6.3] https://gradle-enterprise.elastic.co/s/mn5lnrsmd77sm
https://gradle-enterprise.elastic.co/s/es3gj7z7irvuc

Repro lines:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testTwoJobsWithSameRandomizeSeedUseSameTrainingSet" \
  -Dtests.seed=2EAE3FA5F6E57FDA \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=Australia/Darwin \
  -Dcompiler.java=14 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testTwoJobsWithSameRandomizeSeedUseSameTrainingSet" \
  -Dtests.seed=2EAE3FA5F6E57FDA \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=Australia/Darwin \
  -Dcompiler.java=14 \
  -Druntime.java=8
```

Logs excerpt:
```
ElasticsearchException[all shards failed]; nested: SearchPhaseExecutionException[all shards failed];
	at __randomizedtesting.SeedInfo.seed([2EAE3FA5F6E57FDA:6BA53EC32EE23820]:0)
	at org.elasticsearch.xpack.core.ml.utils.ExceptionsHelper.serverError(ExceptionsHelper.java:55)
	at org.elasticsearch.xpack.ml.action.TransportGetDataFrameAnalyticsStatsAction.lambda$searchStats$8(TransportGetDataFrameAnalyticsStatsAction.java:223)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:83)
	at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:76)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
	at org.elasticsearch.action.search.TransportMultiSearchAction$1.finish(TransportMultiSearchAction.java:178)
	at org.elasticsearch.action.search.TransportMultiSearchAction$1.handleResponse(TransportMultiSearchAction.java:164)
	at org.elasticsearch.action.search.TransportMultiSearchAction$1.onFailure(TransportMultiSearchAction.java:157)
	at org.elasticsearch.action.support.TransportAction$1.onFailure(TransportAction.java:92)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onFailure(ContextPreservingActionListener.java:50)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.raisePhaseFailure(AbstractSearchAsyncAction.java:571)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:551)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:309)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:580)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:393)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:68)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:245)
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59)
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:402)
	at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:639)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1171)
	at org.elasticsearch.transport.InboundHandler.lambda$handleException$2(InboundHandler.java:244)
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:226)
	at org.elasticsearch.transport.InboundHandler.handleException(InboundHandler.java:242)
	at org.elasticsearch.transport.InboundHandler.handlerResponseError(InboundHandler.java:234)
	at org.elasticsearch.transport.InboundHandler.messageReceived(InboundHandler.java:131)
	at org.elasticsearch.transport.InboundHandler.inboundMessage(InboundHandler.java:94)
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:698)
	at org.elasticsearch.transport.InboundPipeline.forwardFragments(InboundPipeline.java:142)
	at org.elasticsearch.transport.InboundPipeline.doHandleBytes(InboundPipeline.java:117)
	at org.elasticsearch.transport.InboundPipeline.handleBytes(InboundPipeline.java:82)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:73)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:227)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Failed to execute phase [query], all shards failed
	... 50 more
```

`testSetUpgradeMode_ExistingTaskGetsUnassigned` was suffering from similar failure (see https://github.com/elastic/elasticsearch/issues/55221). The workaround was to wrap stats action call in `assertBusy` so that intermittent shard failures are retried. There was also suggestion that it may fail due to one of `.ml-state*` or `.ml-stats*` indices being unavailable.

### LINKED ISSUE #57102: DeleteExpiredDataIT.testDeleteExpiredDataWithStandardThrottle test fails for 5 days
**Build scan**:

[7.7.1] https://gradle-enterprise.elastic.co/s/lre3ofg54upw2
[6.8.10] https://gradle-enterprise.elastic.co/s/eudojx2jyn3rm
[6.8.10] https://gradle-enterprise.elastic.co/s/f6pgvpd4zbxxa
[7.7.1] https://gradle-enterprise.elastic.co/s/buujiz2gy4qoq
https://gradle-enterprise.elastic.co/s/xddi3rkcdnyne

**Repro line**:

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.DeleteExpiredDataIT.testDeleteExpiredDataWithStandardThrottle" \
  -Dtests.seed=C7F615C834A73F48 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-DO \
  -Dtests.timezone=Pacific/Kwajalein \
  -Dcompiler.java=14 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.DeleteExpiredDataIT.testDeleteExpiredDataWithStandardThrottle" \
  -Dtests.seed=C7F615C834A73F48 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-DO \
  -Dtests.timezone=Pacific/Kwajalein \
  -Dcompiler.java=14 \
  -Druntime.java=8
```

**Reproduces locally?**:

No

**Applicable branches**:

7.x, 7.8

**Failure history**:

This is a new test.
Started failing on May 20th.
~ 1 failure daily since then

**Failure excerpt**:
 
From 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.8+multijob-unix-compatibility/os=centos-6&&immutable/38/console

```
08:12:19 » WARN ][o.e.x.m.d.DatafeedManager] [integTest-2] Datafeed for [realtime-job-auto-stop] has seen no data in [2] attempts, and never seen any data previously, so stopping...
08:12:19 » WARN ][o.e.p.AllocatedPersistentTask] [integTest-2] task datafeed-realtime-job-auto-stop-datafeed failed with an exception
08:12:19 »  org.elasticsearch.xpack.ml.datafeed.DatafeedJob$EmptyDataCountException: null
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.run(DatafeedJob.java:398) ~[x-pack-ml-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.runRealtime(DatafeedJob.java:188) ~[x-pack-ml-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.executeRealTime(DatafeedManager.java:428) ~[x-pack-ml-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.access$600(DatafeedManager.java:311) [x-pack-ml-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$3.doRun(DatafeedManager.java:235) [x-pack-ml-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
08:12:19 »  	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695) [elasticsearch-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
08:12:19 »  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
08:12:19 »  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
08:12:19 »  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
08:12:19 »  	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
08:12:19 » WARN ][o.e.p.PersistentTasksClusterService] [integTest-2] persistent task datafeed-realtime-job-auto-stop-datafeed failed
08:12:19 »  org.elasticsearch.xpack.ml.datafeed.DatafeedJob$EmptyDataCountException: null
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.run(DatafeedJob.java:398) ~[?:?]
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedJob.runRealtime(DatafeedJob.java:188) ~[?:?]
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.executeRealTime(DatafeedManager.java:428) ~[?:?]
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$Holder.access$600(DatafeedManager.java:311) ~[?:?]
08:12:19 »  	at org.elasticsearch.xpack.ml.datafeed.DatafeedManager$3.doRun(DatafeedManager.java:235) ~[?:?]
08:12:19 »  	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:695) [elasticsearch-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
08:12:19 »  	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.8.0-SNAPSHOT.jar:7.8.0-SNAPSHOT]
08:12:19 »  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
08:12:19 »  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
08:12:19 »  	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
08:12:19 » ERROR][o.e.x.m.p.l.CppLogMessageHandler] [integTest-2] [forecast-it-test-memory-status] [autodetect/470145] [CForecastRunner.cc@495] Forecast cannot be executed as model memory status is not OK
08:12:19 » ERROR][o.e.x.m.p.l.CppLogMessageHandler] [integTest-2] [forecast-it-test-no-data] [autodetect/470211] [CForecastRunner.cc@495] Forecast cannot be executed as job requires data to have been processed and modeled
08:12:19 » WARN ][o.e.x.m.d.DatafeedManager] [integTest-2] [test-lookback-only-given-empty-index] Datafeed lookback retrieved no data
08:12:19 » ERROR][o.e.x.m.p.l.CppLogMessageHandler] [integTest-2] [restore-model-snapshot-job] [autodetect/471151] [CForecastRunner.cc@495] Forecast cannot be executed as job requires data to have been processed and modeled
08:12:19 » WARN ][o.e.x.m.MlAssignmentNotifier] [integTest-2] [realtime-job-test-enable-upgrade-mode] No node found to start datafeed [realtime-job-test-enable-upgrade-mode-datafeed]. Reasons [persistent task cannot be assigned while upgrade mode is enabled.]
08:12:19 » WARN ][o.e.x.m.MlAssignmentNotifier] [integTest-2] [realtime-job-test-enable-upgrade-mode] No node found to start datafeed [realtime-job-test-enable-upgrade-mode-datafeed]. Reasons [cannot start datafeed [realtime-job-test-enable-upgrade-mode-datafeed], because the job's [realtime-job-test-enable-upgrade-mode] state is stale]
08:12:19 » WARN ][o.e.x.m.j.p.a.AutodetectProcessManager] [integTest-2] [realtime-job-test-enable-upgrade-mode] No quantiles could be found for a job with processed records
08:12:19 » WARN ][o.e.x.m.u.p.ResultsPersisterService] [integTest-2] [bulk-failure-retry-job] experienced failure that cannot be automatically retried. Bulk failure message [failure in bulk execution:
08:12:19 »   ↑ repeated 2 times ↑
08:12:19 » WARN ][o.e.x.m.d.DatafeedTimingStatsReporter] [integTest-2] [bulk-failure-retry-job] failed to report datafeed timing stats
08:12:19 »  org.elasticsearch.ElasticsearchException: bulk-failure-retry-job experienced failure that cannot be automatically retried. See logs for bulk failures
```

### LINKED ISSUE #58841: [CI] Test cat data frame analytics single job with header failing
Failed 3 times on 7.x in the past days

Build scan: https://gradle-enterprise.elastic.co/s/7vn6gnjkkthfy

Output:

```
org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=ml/data_frame_analytics_cat_apis/Test cat data frame analytics single job with header} FAILED
    org.elasticsearch.client.ResponseException: method [DELETE], host [http://127.0.0.1:35015], URI [/_ml/data_frame/analytics/dfa-classification-job], status line [HTTP/1.1 503 Service Unavailable]
    {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}
        at __randomizedtesting.SeedInfo.seed([22DBE7B704A1086E:AA8FD86DAA5D6596]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:293)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:263)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:269)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:237)
        at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.deleteAllDataFrameAnalytics(MlRestTestStateCleaner.java:110)
        at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.clearMlMetadata(MlRestTestStateCleaner.java:32)
        at org.elasticsearch.xpack.test.rest.XPackRestIT.clearMlState(XPackRestIT.java:222)
        at org.elasticsearch.xpack.test.rest.XPackRestIT.cleanup(XPackRestIT.java:206)
```

### LINKED ISSUE #59011: [CI] upgraded_cluster/30_ml_jobs_crud/Test open old jobs failed with .ml-state-write not an alias
**Build scan**: https://gradle-enterprise.elastic.co/s/svde5ts33nfki

**Repro line**:

```
./gradlew ':x-pack:qa:rolling-upgrade:v7.6.2#upgradedClusterTest' --tests "org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=upgraded_cluster/30_ml_jobs_crud/Test open old jobs}" \
  -Dtests.seed=95C888B6E2499870 \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-EG \
  -Dtests.timezone=Pacific/Gambier \
  -Druntime.java=8 \
  -Dtests.rest.suite=upgraded_cluster
```

**Reproduces locally?**: No

**Applicable branches**: 7.8 (upgraded from 7.6)

**Failure history**:

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2020-03-03T13:01:09.914Z',mode:absolute,to:'2020-07-03T12:01:15.600Z'))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'%22Test%20open%20old%20jobs%22'),sort:!(process.time-start,desc))

There are many failures of this test over the years, but it has failed for many completely different reasons.  The earliest I could find with this problem was on 5th March 2020.

**Failure excerpt**:

```
java.lang.AssertionError: Failure at [upgraded_cluster/30_ml_jobs_crud:110]: field [] doesn't have a true value
   Expected: not a string equal to "false" ignoring case |  
   but: was "false"
```

The relevant bit of the YAML file is:

```
  - do:
      indices.exists_alias:
        name: ".ml-state-write"
  - is_true: ''
```

We have seen the problem of `.ml-state-write` being a concrete index rather than an alias in clusters outside of CI.  It seems that, very occasionally, it can happen in CI too.

### PR DESCRIPTION
**Pull request by droberts195**
There have been a few test failures that are likely caused by tests
performing actions that use ML indices immediately after the actions
that create those ML indices.  Currently this can result in attempts
to search the newly created index before its shards have initialized.

This change makes the method that creates the internal ML indices
that have been affected by this problem (state and stats) wait for
the shards to be initialized before returning.

Fixes #54887
Fixes #55221
Fixes #55807
Fixes #57102
Fixes #58841
Fixes #59011

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

The test failures are mocking issues in `MlIndexAndAliasTests`

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/utils/MlIndexAndAlias.java [hunk 1]
```diff
@@ -69,13 +72,38 @@ private MlIndexAndAlias() {}
...
+                        .waitForNoRelocatingShards(true)
+                        .waitForNoInitializingShards(true);
+                    executeAsyncWithOrigin(
+                        client.threadPool().getThreadContext(),
+                        ML_ORIGIN,
+                        healthRequest,
+                        ActionListener.<ClusterHealthResponse>wrap(
+                            response -> finalListener.onResponse(response.isTimedOut() == false),
+                            finalListener::onFailure),
+                        (request, listener) -> client.admin().cluster().health(request, listener)
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/utils/MlIndexAndAlias.java:99]: I think you could replace this call with a more concise `client.admin().cluster()::health`.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/utils/MlIndexAndAlias.java [hunk 2]
```diff
@@ -69,13 +72,38 @@ private MlIndexAndAlias() {}
...
     public static void createIndexAndAliasIfNecessary(Client client,
                                                       ClusterState clusterState,
                                                       IndexNameExpressionResolver resolver,
                                                       String indexPatternPrefix,
                                                       String alias,
-                                                      ActionListener<Boolean> listener) {
+                                                      ActionListener<Boolean> finalListener) {
+
+        // If the index and alias were successfully created then wait for the shards of the index that the alias points to be ready
+        ActionListener<Boolean> waitForShardsListener = ActionListener.wrap(
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/utils/MlIndexAndAlias.java:86]: TBH it is always unclear to me how should I name the listener variable: after the action that takes place *inside* the listener or after the action that invokes the listener in the end?
Is there any codebase-wide guideline for that?

**Review by przemekwitek — APPROVED** [review]
LGTM

Thanks for fixing this, just 2 minor comments.

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by droberts195** [comment]
@elasticmachine update branch
