### PR TITLE
Preserve existing mappings on batch mapping updates

### LINKED ISSUE #15129: Batched mapping updates can overwrite existing mappings
The introduction in #14899 of applying mapping updates in batches brought with it a bug that could cause existing mappings to be lost during an update. In particular, in a scenario in which a batch contained updates for at least two distinct existing types on the same index, the existing mappings for all but the first existing type on the index would be lost. This arises because the workflow for applying mapping updates in batches now looks like:

1. [if][1] any of the indices in the request batch do not exist on master, [create][2] them for the purpose of applying the mapping update and [merge][3] in the existing index mappings from the cluster state
2. [apply][4] the mapping updates
3. [if][5] any indices were created, [delete][6] them from master

The code for step 1. [looks like][7]:

```java
for (PutMappingClusterStateUpdateRequest request : tasks) {
  // failures here mean something is broken with our cluster state - fail all tasks by letting exceptions bubble up
  for (String index : request.indices()) {
      if (currentState.metaData().hasIndex(index)) {
          // if we don't have the index, we will throw exceptions later;
          if (indicesService.hasIndex(index) == false) {
              final IndexMetaData indexMetaData = currentState.metaData().index(index);
              IndexService indexService = indicesService.createIndex(nodeServicesProvider, indexMetaData, Collections.EMPTY_LIST);
              indicesToClose.add(indexMetaData.getIndex());
              // make sure to add custom default mapping if exists
              if (indexMetaData.getMappings().containsKey(MapperService.DEFAULT_MAPPING)) {
                  indexService.mapperService().merge(MapperService.DEFAULT_MAPPING, indexMetaData.getMappings().get(MapperService.DEFAULT_MAPPING).source(), false, request.updateAllTypes());
              }
              // only add the current relevant mapping (if exists)
              if (indexMetaData.getMappings().containsKey(request.type())) {
                  indexService.mapperService().merge(request.type(), indexMetaData.getMappings().get(request.type()).source(), false, request.updateAllTypes());
              }
          }
      }
  }
}
```

The flaw is that on the second distinct existing type for the same index, [`indicesService.hasIndex(index) == false`](https://github.com/elastic/elasticsearch/blob/c4a229819406deb4407d8401d698453d936186cf/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java#L234) will evaluate to false (because the [index was created][8] for the first existing type for the index) and the existing mapping will never get merged in. This will then cause the mapping update to overwrite the existing mapping so losing it.

[1]: https://github.com/elastic/elasticsearch/blob/c4a229819406deb4407d8401d698453d936186cf/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java#L234
[2]: https://github.com/elastic/elasticsearch/blob/c4a229819406deb4407d8401d698453d936186cf/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java#L236
[3]: https://github.com/elastic/elasticsearch/blob/c4a229819406deb4407d8401d698453d936186cf/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java#L244
[4]: https://github.com/elastic/elasticsearch/blob/c4a229819406deb4407d8401d698453d936186cf/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java#L250-L257
[5]: https://github.com/elastic/elasticsearch/blob/c4a229819406deb4407d8401d698453d936186cf/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java#L261-L263
[6]: https://github.com/elastic/elasticsearch/blob/c4a229819406deb4407d8401d698453d936186cf/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java#L262
[7]: https://github.com/elastic/elasticsearch/blob/c4a229819406deb4407d8401d698453d936186cf/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java#L229-L249
[8]: https://github.com/elastic/elasticsearch/blob/c4a229819406deb4407d8401d698453d936186cf/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java#L236

### PR DESCRIPTION
**Pull request by jasontedor**
This commit addresses an issues introduced in #14899 to apply mapping
updates in batches. The issue is that an existing mapping for a type
could be lost if that type came in a batch that already contained a
mapping update for another type on the same index. The underlying issue
was that the existing mapping would not be merged in because the merging
logic was only tripped once per index, rather than for all types seeing
updates for each index. Resolving this issue is simply a matter of
ensuring that all existing types seeing updates are merged in.

Closes #15129

### CODE REVIEW

**Comment by jpountz** [comment]
LGTM

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java [hunk 1]
```diff
@@ -221,9 +221,8 @@ public void refreshMapping(final String index, final String indexUUID, final Str
     class PutMappingExecutor implements ClusterStateTaskExecutor<PutMappingClusterStateUpdateRequest> {
         @Override
         public BatchResult<PutMappingClusterStateUpdateRequest> execute(ClusterState currentState, List<PutMappingClusterStateUpdateRequest> tasks) throws Exception {
-            List<String> indicesToClose = new ArrayList<>();
+            Set<String> indicesToClose = new HashSet<>();
             BatchResult.Builder<PutMappingClusterStateUpdateRequest> builder = BatchResult.builder();
-            Map<PutMappingClusterStateUpdateRequest, TaskResult> executionResults = new HashMap<>();
             try {
                 // precreate incoming indices;
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java]: I think this will be clearer if we say - "// precreate incoming indices and popluate them with the relevant types"

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java [hunk 2]
```diff
@@ -231,10 +230,15 @@ public void refreshMapping(final String index, final String indexUUID, final Str
...
-                                indicesToClose.add(indexMetaData.getIndex());
+                                IndexService indexService;
+                                if (indicesService.hasIndex(index) == false) {
+                                    indexService = indicesService.createIndex(nodeServicesProvider, indexMetaData, Collections.EMPTY_LIST);
+                                    indicesToClose.add(index);
+                                } else {
+                                    indexService = indicesService.indexService(index);
+                                }
                                 // make sure to add custom default mapping if exists
                                 if (indexMetaData.getMappings().containsKey(MapperService.DEFAULT_MAPPING)) {
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java]: I think we only want to do this once , when the index is created?

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java [hunk 3]
```diff
@@ -231,10 +230,15 @@ public void refreshMapping(final String index, final String indexUUID, final Str
...
                                     indexService.mapperService().merge(MapperService.DEFAULT_MAPPING, indexMetaData.getMappings().get(MapperService.DEFAULT_MAPPING).source(), false, request.updateAllTypes());
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java]: Re the addition of types - I think we can also just check if it's not there? I'm thinking about batching multiple requests for the same type ( commenting here because the code in question is not in the scope of the change)

**Comment by bleskes** [comment]
good catch. Left some minor comments

File: core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java (hunk 3 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataMappingService.java]: For the record, my other pull request #15123 is changing this logic to add all types anyway when creating such temporary indices since this is needed for cross-type validation that we need eg. for parent/child (today we are missing some validation checks when the master node does not have the mappers locally).
