### PR TITLE
Respect regional AWS STS endpoints

### LINKED ISSUE #89175: Elasticsearch in EKS does not use sts regional endpoints
### Elasticsearch Version

8.3.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux 5.4.196-108.356.amzn2.x86_64

### Problem Description

Elasticsearch in EKS does not honour `eks.amazonaws.com/sts-regional-endpoints=true` for IAM access with AWS regions. It always sends it's API calls to `us-east-1`.

### Steps to Reproduce

Deploy Elasticsearch in EKS using operator with the following env
```
          containers:
            - env:
                - name: AWS_ROLE_SESSION_NAME
                  value: snapshot-repo
                - name: ZONE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['topology.kubernetes.io/zone']
```

Create service account with the annotations
```
  annotations:
    eks.amazonaws.com/role-arn: redacted
    eks.amazonaws.com/sts-regional-endpoints: "true"
```

Create snapshot repo
```
PUT _snapshot/s3backup
{
    "type": "s3",
    "settings": {
      "bucket": "redacted",
      "server_side_encryption": "true",
      "max_restore_bytes_per_sec": "500mb",
      "storage_class": "intelligent_tiering",
      "use_throttle_retries": "true",
      "readonly": "false",
      "base_path": "snapshot",
      "region": "us-west-2",
      "max_snapshot_bytes_per_sec": "500mb",
      "endpoint": "s3.us-west-2.amazonaws.com"
  }
}
```

Run snapshot

View cloudtrail events for service account name

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by arteam**
The AWS SDK supports regional STS endpoints via the `AWS_STS_REGIONAL_ENDPOINTS` environment variable. If the user set it to `regional` and provided the region in the `AWS_REGION` env variable, we should respect that and make the STS client use the regional adjusted STS endpoint like `https://sts.us-west-2.amazonaws.com`.

See https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html

Resolves #89175

### CODE REVIEW

**Comment by smartkathycat** [comment]
Hi @arteam I have a support case 01509874. Customer asks if this can be backported to version 8.6.x? They are now on v8.6.1. Thank you.

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/CustomWebIdentityTokenCredentialsProviderTests.java [hunk 1]
```diff
@@ -125,4 +131,32 @@ public void testCreateWebIdentityTokenCredentialsProvider() throws Exception {
...
+            getEnvironment(),
+            environmentVariables::get,
+            systemProperties::getOrDefault,
+            Clock.systemUTC()
+        );
+        // We can't verify that webIdentityTokenCredentialsProvider's STS client uses the "https://sts.us-west-2.amazonaws.com"
+        // endpoint in a unit test. The client depends on hardcoded RegionalEndpointsOptionResolver that in turn depends
+        // on the system environment that we can't change in the test. So we just verify we that we called `withRegion`
+        // on stsClientBuilder which should internally correctly configure the endpoint when the STS client is built.
+        assertEquals("us-west-2", webIdentityTokenCredentialsProvider.getStsRegion());
```
Comment (volodk85) [inline modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/CustomWebIdentityTokenCredentialsProviderTests.java:158]: Is it possible to get a real client instance and check if its sts endpoint really points where it supposed to?

Comment (arteam) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/CustomWebIdentityTokenCredentialsProviderTests.java:158]: I did check that in a manual test. The problem that I can't do that in a unit test because that requires setting the `AWS_STS_REGIONAL_ENDPOINTS` environment variable. I can set environment variables in the `yamlRestTestSTS` test created from Gradle, but I can't verify that the client would sent requests to the real regional endpoint since `yamlRestTestSTS` works with a mocked S3 service.

Comment (DaveCTurner) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/CustomWebIdentityTokenCredentialsProviderTests.java:158]: We're mocking STS too I think, and using `com.amazonaws.sdk.stsMetadataServiceEndpointOverride` to specify the STS service endpoint? Could we run this same test without that system property, instead using the `AWS_STS_REGIONAL_ENDPOINTS` env var to specify the mock endpoint?

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java [hunk 2]
```diff
@@ -361,10 +363,19 @@ static class CustomWebIdentityTokenCredentialsProvider implements AWSCredentials
...
+            // Check if we need to use regional STS endpoints
+            // https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html
+            if ("regional".equalsIgnoreCase(systemEnvironment.getEnv("AWS_STS_REGIONAL_ENDPOINTS")) && stsRegion != null) {
+                stsClientBuilder.withRegion(stsRegion);
+            } else {
+                // Custom system property used for specifying a mocked version of the STS for testing
+                String customStsEndpoint = jvmEnvironment.getProperty("com.amazonaws.sdk.stsMetadataServiceEndpointOverride", STS_HOSTNAME);
+                // Set the region explicitly via the endpoint URL, so the AWS SDK doesn't make any guesses internally.
+                stsClientBuilder.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(customStsEndpoint, null));
+            }
```
Comment (ywangd) [inline modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java:378]: Should we validate and report error if `AWS_STS_REGIONAL_ENDPOINTS` is set to `regional` but `AWS_REGION_ENV_VAR` has no value or if `AWS_REGION_ENV_VAR` has value but `AWS_STS_REGIONAL_ENDPOINTS` is not `regional` instead of just falling to the `else` branch?

**Comment by arteam** [comment]
@elasticmachine update branch

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java (hunk 2 above)
Comment (arteam) [reply modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java]: Good point! 

I've added logging for the case `AWS_STS_REGIONAL_ENDPOINTS` is to `regional`, but `AWS_REGION` is not set for some reason. The opposite case is not needed, I think. `AWS_REGION` can be automatically injected, but the user can prefer to use the global endpoint or a set custom one via the `com.amazonaws.sdk.stsMetadataServiceEndpointOverride` property. Setting `AWS_STS_REGIONAL_ENDPOINTS` to `regional` should indicate the intent to use regional endpoints.

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/CustomWebIdentityTokenCredentialsProviderTests.java (hunk 1 above)
Comment (arteam) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/CustomWebIdentityTokenCredentialsProviderTests.java:158]: I don't think that will work because custom endpoints and regional endpoints are mutually exclusive. If set `AWS_STS_REGIONAL_ENDPOINTS` in the `yamlRestTestSTS` test, we can't point the S3Client to a `S3Fixture` with mocked credentials. It will use the real regional endpoint like `https://ap-east-1.amazonaws.com`, so we can't successfully authenticate the client.

**Review by ywangd — APPROVED** [review]
LGTM

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/CustomWebIdentityTokenCredentialsProviderTests.java (hunk 1 above)
Comment (DaveCTurner) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/CustomWebIdentityTokenCredentialsProviderTests.java:158]: Ah right I see, we're not mocking name resolution enough to do this yet. Would it be possible to do that?

**Review by volodk85 — APPROVED** [review]
LGTM

**Comment by arteam** [comment]
Thank y'all!
