### PR TITLE
Check latest repoData before applying workaround for missing shardGen file

### LINKED ISSUE #112811: [CI] ConcurrentSnapshotsIT testMasterFailoverOnFinalizationLoop failing
**Build Scans:**
- [elasticsearch-intake #9616 / part1](https://gradle-enterprise.elastic.co/s/jg3wzkm6rcvfw)
- [elasticsearch-pull-request #30594 / part-1](https://gradle-enterprise.elastic.co/s/ahapwor7qmtsk)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailoverOnFinalizationLoop" -Dtests.seed=12763223B2AFCAE1 -Dtests.locale=ca-IT -Dtests.timezone=Pacific/Rarotonga -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testMasterFailoverOnFinalizationLoop'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.snapshots.ConcurrentSnapshotsIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: java.lang.AssertionError: index [index-test/XN-_uSP9Qy2wwGcbUHnr7Q] shard generation [lhcKkX7ET4Cgwv-Q1XgY5g] in [test-repo][[indices][XN-_uSP9Qy2wwGcbUHnr7Q][0]] not found - falling back to reading all shard snapshots
```

**Issue Reasons:**
- [main] 2 failures in test testMasterFailoverOnFinalizationLoop (0.6% fail rate in 328 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
It is expected that the old master may attempt to read a shardGen file that is deleted by the new master. This PR checks the latest repo data before applying the workaround (or throwing AssertionError) for missing shardGen files.

Relates: #112337
Resolves: #112811

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Hmm a master failover is an "expected" situation, we can't have a by-default tripping assertion here.

Could we enhance the check to verify that the root blob is unchanged before running the workaround?

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 1]
```diff
@@ -3883,6 +3893,14 @@ private Tuple<BlobStoreIndexShardSnapshots, ShardGeneration> buildBlobStoreIndex
                     generation
                 );
             } catch (NoSuchFileException noSuchFileException) {
+                final long latestGeneration = latestIndexBlobId();
+                final RepositoryData currentRepositoryData = getRepositoryData(latestGeneration);
+                if (currentRepositoryData.shardGenerations().hasShardGen(new RepositoryShardId(indexId, shardId)) == false) {
+                    // Master has concurrently mutated the shard generation. This can happen when master fails over
+                    // which is "expected". We do not need the following workaround in this case.
+                    throw noSuchFileException;
+                }
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java:3902]: I wanted to simply compare the last known repo generation against the latest generation by listing root blobs. But it seems last known repo generation is not easily available especially when this runs in the context of shard snapshotting. Since this is a rare case, it feels ok to just read the repo data directly and check whether the shard gen still exists. It's slower but we are on a slow path already more or less. Hopefully that works for you.

That said, `BlobStoreRepositoy` class has many method related to fetching and caching repository data. Maybe one (some) of them can be reliably leveraged. Please let me know. Thank you!

**Comment by ywangd** [comment]
@DaveCTurner Thanks for the feedback! I have updated the PR along the line of your suggestion. It's good for another look.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 2]
```diff
@@ -3883,6 +3893,14 @@ private Tuple<BlobStoreIndexShardSnapshots, ShardGeneration> buildBlobStoreIndex
                     generation
                 );
             } catch (NoSuchFileException noSuchFileException) {
+                final long latestGeneration = latestIndexBlobId();
+                final RepositoryData currentRepositoryData = getRepositoryData(latestGeneration);
+                if (currentRepositoryData.shardGenerations().hasShardGen(new RepositoryShardId(indexId, shardId)) == false) {
+                    // Master has concurrently mutated the shard generation. This can happen when master fails over
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java:3899]: I think we're only checking whether the shard has been totally removed here? If the shard still exists then `hasShardGen()` should return `true` but `getShardGen()` will return a different generation from the one we were trying to load.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 3]
```diff
@@ -3883,6 +3893,14 @@ private Tuple<BlobStoreIndexShardSnapshots, ShardGeneration> buildBlobStoreIndex
                     generation
                 );
             } catch (NoSuchFileException noSuchFileException) {
+                final long latestGeneration = latestIndexBlobId();
+                final RepositoryData currentRepositoryData = getRepositoryData(latestGeneration);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java:3897]: These lines can also fail with an exception - if they do, I'd rather we suppressed the exception they throw and went back to throwing the original `noSuchFileException`.

**Review by DaveCTurner — COMMENTED** [review]
Makes sense to me, thanks Yang. Couple of small comments.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 2 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: You are right. I used the wrong method. Got confused by its name. It's now obvious that it does not take a shardGen parameter 🤦 
Pushed fe1cf86524225038ef1b9ea31ce0c2b227223c87
Thanks for spotting it.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 3 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Good point as well. See fe1cf86524225038ef1b9ea31ce0c2b227223c87

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/113155)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
