### PR TITLE
Fix date fields sort formatting with missing values

### LINKED ISSUE #81960: Ascending sort with `missing _first` fails on datefields with missing values
**Elasticsearch version** (`bin/elasticsearch --version`): v8.1.0, v7.16.2 and at least v7.15.1

**Description of the problem including expected versus actual behavior**:

Indexing a document with a missing date time value, then ascending sorting it with `"missing": "_first"` results in `Field Year cannot be printed as the value -292275055 exceeds the maximum print width of 4` if it would be the only document returned, ie `size: 1`.

The formatter is trying to format the sentinel value of `-9223372036854775808`.

**Steps to reproduce**:
```
PUT test
{
  "mappings" : {
    "properties" : {
      "field1" : {
        "type" : "integer"
      },
      "dt" : {
        "type" : "date",
        "format" : "strict_date_time||strict_date_time_no_millis"
      }
    }
  }
}

POST _bulk
{"index":{"_index":"test","_id":"1"}}
{"field1": 1243, "dt": "2021-12-20T23:14:20+00:00"}
{"index":{"_index":"test","_id":"2"}}
{"field2": 4567}

GET test/_search
{
  "size": 1,
  "query": {
    "match_all": {}
  },
  "sort": [
    {
      "dt": {
        "missing": "_first",
        "order": "asc"
      }
    }
  ]
}
```

This is https://github.com/elastic/elasticsearch/issues/73763 with [`targetNumericType == NumericType.DATE`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java#L156)

Using `"missing": 0` works around the issue.

### PR DESCRIPTION
**Pull request by carlosdelest**
Closes https://github.com/elastic/elasticsearch/issues/81960

When formatting date types, take into account `Long.MAX_VALUE` and `Long.MIN_VALUE`. These values can be present when formatting sort values, and the value is missing.

`Long.MIN_VALUE` is transformed into the epoch, and `Long.MAX_VALUE` into "9999-12-31T23:59:59.999999999Z". These values have been chosen as the safest for the predefined date formats, as years are at most represented with 4 digits.

This doesn't prevent custom formats to fail, in which cause an IAE will be thrown.

### CODE REVIEW

**Comment by john-wagster** [comment]
PR looks good and makes sense.  I may be misunderstanding the min value though does this mean we would sort desc min value (as epoch time) before an actual indexed date that's prior to the epoch.  And if so is that a problem?  It wasn't entirely clear to me from the original issue when we specifically encounter Long.MIN_VALUE or Long.MAX_VALUE.

**Comment by carlosdelest** [comment]
@john-wagster 

> It wasn't entirely clear to me from the original issue when we specifically encounter Long.MIN_VALUE or Long.MAX_VALUE.

Those values are encountered when we're sorting values and the field value for a doc is missing. Then, it is replaced by the max / min value possible depending on the sort order (missing: _first or missing: _last) so it is ordered accordingly.

The trick here is that Lucene does not have date field data type, so we're using Long to store them. Hence the returned values make sense from a Long perspective but not from a Date perspective.

Hope it makes sense!

**Review by benwtrent — COMMENTED** [review]
I realize this works, but I am slightly worried about backwards compatiblity. 

Negative dates are valid, dates indexed in the index can be from before 1970, and with this change, missing values will no longer be sorted to before 1970.

**Comment by carlosdelest** [comment]
>  I am slightly worried about backwards compatiblity.

I understand - but right now this use case doesn't work at all, as it is a 400 error. So users who encountered this will have navigated around this problem by using a different format or not formatting sorted results.

> Negative dates are valid, dates indexed in the index can be from before 1970, and with this change, missing values will no longer be sorted to before 1970.

I see your point. Missing values will be sorted correctly, but it's a possibility that the date is less than the epoch and thus doesn't represent the actual value.

The only other options I see for correctly formatting dates that are less than the epoch would be:
- Having custom min / max values depending on the format used - so the standard [date formatters](https://www.elastic.co/docs/reference/elasticsearch/mapping-reference/mapping-date-format) have a specific value for missing values depending on the sort and is used for formatting.
- Use null as a formatted value in these cases - which can potentially break clients that expect a formatted value.
- Do not format the value in these cases and return the raw long value - again, can potentially break clients that expect a formatted value.

What do you think?

File: server/src/main/java/org/elasticsearch/search/DocValueFormat.java [hunk 1]
```diff
@@ -305,6 +305,11 @@ public DateMathParser getDateMathParser() {
 
         @Override
         public String format(long value) {
+            // Handle missing values, represented as Long.MIN_VALUE or Long.MAX_VALUE depending on the sort order
+            if (value == Long.MIN_VALUE || value == Long.MAX_VALUE) {
+                return null;
+            }
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/search/DocValueFormat.java:306]: 🤯 wut

**Comment by rjernst** [comment]
As I [mentioned](https://github.com/elastic/elasticsearch/issues/81960#issuecomment-3169280830) in the linked issue, the real problem is that we are producing illegal long date values to begin with. When processing a doc without a value for a date field we should fallback to the min/max _Instant_ for the given resolution. While this PR may work in this isolated case, it perpetuates the misalignment between date parsing and date processing, likely needing more places to have this additional logic.

**Comment by benwtrent** [comment]
@rjernst Even instant.min/max doesn't actually work. If this were to be fool proof, we need to have a min/max for all common time parsing (e.g. for things that restrict to 4 digit years, -9999 to +9999)

**Comment by carlosdelest** [comment]
@rjernst @benwtrent sorry for the noise as I was not planning to update this PR yet.

I wonder if it makes sense to provide a formatted value in the `null` case - we're obscuring the fact that there is no value there, plus making it quite involved to get it to work right for every possible date format, as min / max values for dates will depend on a potential custom date format the user is using. Should we just return `null` and not do any date formatting?

I understand about bwc - but IIUC this is already returning an error for users that hit this use case, so I don't think there is a proper client handling in this case that we should worry about?

**Comment by rjernst** [comment]
> Should we just return null and not do any date formatting?

That does make sense. Returning any kind of formatted value implies there is a value for the document, when in fact there isn't.

**Comment by carlosdelest** [comment]
@benwtrent @rjernst this is ready for another round of review. This is returning `null` for missing date values. I added a YAML test for end to end testing as well.

Let me know what you think!

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by carlosdelest** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/141147)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by carlosdelest** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/141148)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by carlosdelest** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/141149)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by carlosdelest** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/141151)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by carlosdelest** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/141152)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
