### PR TITLE
Propagate index errors in field_caps

### LINKED ISSUE #68994: Field capabilities API drops shard level exceptions
This is a follow up to #68904 where I observed that exceptions thrown on the shard level by the `field_caps` API are not properly propagated to the caller. Instead we return an empty response. This didn't seem to have been a great issue so far since the biggest error source would have been the only request body parameter, the `index_filter` section, which typically gets parsed and validated already on the coordinating node and then everything is fine.
With introducing the `runtime_mappings` section it is now more likely to have errors in there too, but this part of the request doesn't get properly parsed until it reaches the shard (since we need an SearchExecutionContext to parse it). When there are errors here, usually a MapperParserException is thrown, like for the following request:

```
PUT /my-index/_doc/1
{
  "timestamp": "2012-01-01"
}

POST /my-index/_field_caps?fields=*
{
  "runtime_mappings": {
    "day_of_week": {
      "type": "bad_type",     <---- problem here
      "script": {
        "source": "emit(doc['timestamp'].value.dayOfWeekEnum.getDisplayName(TextStyle.FULL, Locale.ROOT))"
      }
    }
  }
}
```

Currently we get an empty respone (`{ "indices" : [ ], "fields" : { }}`) here instead of throwing an error like e.g. in the `_search` API for the same wrong `runtime_mappings` definition.

### PR DESCRIPTION
**Pull request by cbuescher**
Currently we don't report any exceptions occuring during `field_caps` requestrs back to the user.
This PR adds a new `failure` section to the response which contains exceptions per index, keyed by
the index name the error occured in. In addition the response contains another field `failed_indices`
which reports the number of indices that threw an exception. If all of the requested indices failed,
the whole request fails with a 500 error code, otherwise the request succeeds and it is up to the caller
to check for potential errors in the response body.

Closes #68994

### CODE REVIEW

**Comment by cbuescher** [comment]
This is an example of the response with failures with the changes in this PR:
```
{
	"indices": [...],
	"fields": {
		...
	},
	"failed_indices": 1,
	"failures": {
		"errorindex": {
			"error": {
				"root_cause": [{
					"type": "illegal_argument_exception",
					"reason": "test"
				}],
				"type": "illegal_argument_exception",
				"reason": "test"
			}
		}
	}
}
```

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java [hunk 1]
```diff
@@ -25,18 +26,28 @@
     private final String indexName;
     private final Map<String, IndexFieldCapabilities> responseMap;
     private final boolean canMatch;
+    private final Exception exception;
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesIndexResponse.java:29]: I don't think the exception should be part of the index response. It's already reported in the coordinator node so we don't need this hybrid approach.  `FieldCapabilitiesIndexResponse` should represent a successful response.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java [hunk 2]
```diff
@@ -77,47 +77,43 @@ protected void doExecute(Task task, FieldCapabilitiesRequest request, final Acti
...
+                    public void onResponse(FieldCapabilitiesIndexResponse result) {
+                        if (result.canMatch()) {
+                            indexResponses.add(result);
+                        }
+                        countDown.run();
+                    }
+
+                    @Override
+                    public void onFailure(Exception e) {
+                        indexResponses.add(new FieldCapabilitiesIndexResponse(index, e));
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:113]: We can gather the exception in a synchronized map, no need to build fake `FieldCapabilitiesIndexResponse`.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java [hunk 3]
```diff
@@ -135,27 +131,52 @@ private void countDown() {
...
-                ActionListener.wrap(response -> {
-                    List<FieldCapabilitiesIndexResponse> remotes = new ArrayList<>();
-                    for (FieldCapabilitiesIndexResponse resp : response.getIndexResponses()) {
-                        remotes.add(new FieldCapabilitiesIndexResponse(
-                            RemoteClusterAware.buildRemoteIndexName(clusterAlias, resp.getIndexName()),
-                            resp.get(), resp.canMatch()));
+            remoteClusterClient.fieldCaps(remoteRequest, ActionListener.wrap(response -> {
+                List<FieldCapabilitiesIndexResponse> remotes = new ArrayList<>();
+                for (FieldCapabilitiesIndexResponse resp : response.getIndexResponses()) {
+                    if (resp.getException() == null) {
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:137]: Same here, we can simply add the failures map of the remote response to the local one.

**Review by jimczi — COMMENTED** [review]
The approach looks good to me. I left one comment regarding the reporting of the exception.

**Comment by cbuescher** [comment]
@jimczi thanks for the review, I will rework the part around how to transport back the exceptions.

**Comment by cbuescher** [comment]
@jimczi I pushed and update reworking how the exceptions get transported back.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java [hunk 4]
```diff
@@ -135,25 +132,36 @@ private void countDown() {
...
+                        )
+                    );
+                }
+                for (Map.Entry<String, Exception> entry : response.getFailures().entrySet()) {
+                    indexFailures.put(RemoteClusterAware.buildRemoteIndexName(clusterAlias, entry.getKey()), entry.getValue());
+                }
+                countDown.run();
+            }, e -> {
+                // individual index failures should show up as remote responses containing an exception
+                countDown.run();
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:152]: This case is not handled automatically. We need to add all the indices from that cluster in the index failures map. Since all indices on that cluster failed, maybe that the key in the map could be the cluster name instead ?

Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:152]: Individual index failures on a remote should be handled (there is also a test for it now that should fail otherwise). So you mean this should cover general remote failures? How could this happen? Also asking since I cannot thing around a way of testing this atm...

File: server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesResponse.java [hunk 5]
```diff
@@ -190,4 +230,19 @@ public int hashCode() {
     public String toString() {
         return Strings.toString(this);
     }
+
+    @Override
+    public RestStatus status() {
+        RestStatus status = RestStatus.OK;
+        if (indices.length == 0 && failures.size() > 0) {
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/FieldCapabilitiesResponse.java:237]: Do we need this logic now that we throw an exception if all indices fail ? We could even assert in the ctr that failures  must be empty if indices is empty.

**Review by jimczi — COMMENTED** [review]
Looks good to me. Could you add a test a yml test for ccs as well ?

**Comment by cbuescher** [comment]
@jimczi thanks, I pushed changes that remove the rest status logic you mentioned, reworked the failure collection a bit to be all on a central place and added the test you asked for.

**Review by jimczi — APPROVED** [review]
LGTM, thanks @cbuescher !
