### PR TITLE
ESQL: Fix FieldAttribute name usage in InferNonNullAggConstraint

### LINKED ISSUE #127521: ESQL: InferNonNullAggConstraint using wrong field name for union types
@bpintea found another instance where we use `FieldAttribute#name` instead of `FieldAttribute#fieldName`; in case of union types (and so far only union types), these two differ with `name` being a synthetic string like $$field$converted_to$integer` whereas `fieldName` contains the actual name of the `field` in the index.

C.f. https://github.com/elastic/elasticsearch/pull/127225#issuecomment-2838004556. As outlined in my comment, I think it'd be best to avoid this bug at compile time, by making our [SearchStats](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java) require not just `String`s for field names, but either `EsField`s (contained in every `FieldAttribute`) or a dedicated wrapper class/record like `FieldName` to be returned by `FieldAttribute#fieldName` (but not `FieldAttribute#name`).

### PR DESCRIPTION
**Pull request by alex-spies**
Fix [#127521](https://github.com/elastic/elasticsearch/issues/127521)

I'm starting to fix a couple mis-usages of `FieldAttribute#name` (which is **not** always the actual field name!).

Because mis-usage of this method is currently common, I think we should squash this at compile time where possible. For this, I'm introducing a dedicated wrapper record `FieldName` to be used where field names are really required.

I'm starting with the biggest offender, `SearchStats`, and make this always require a `FieldName`, not a `String` - and make `FieldAttribute#fieldName` handily return an instance of `FieldName` so users of `SearchStats` don't accidentally use the return value of `FieldAttribute#name`.

Just changing the `SearchStats` API by requiring this wrapper automatically forced me to fix the bug in InferNonNullAggConstraint from #127521. It also surfaced another bug, c.f. https://github.com/elastic/elasticsearch/issues/128905.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferNonNullAggConstraint.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ protected LogicalPlan rule(Aggregate aggregate, LocalLogicalOptimizerContext con
                 Expression field = af.field();
                 // ignore literals (e.g. COUNT(1))
                 // make sure the field exists at the source and is indexed (not runtime)
-                if (field.foldable() == false && field instanceof FieldAttribute fa && stats.isIndexed(fa.name())) {
+                if (field.foldable() == false && field instanceof FieldAttribute fa && stats.isIndexed(fa.fieldName())) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferNonNullAggConstraint.java:58]: Yup, this is the actual fix.

**Review by idegtiarenko — APPROVED** [review]

**Review by fang-xing-esql — APPROVED** [review]
Thank you @alex-spies, LGTM! There are a couple of things that I can think of:

The first is more of a nice-to-have. Since the rule was changed specifically to update the field name in the generated `IsNotNull` predicate, it might be helpful to add a test in `LocalLogicalPlanOptimizerTests` to verify this behavior, if we don’t already have one yet. As this should not affect the final results, and this is kind of a performance optimization.

The second is that there are quite a few places where `FieldName.toString()` is being called. I was wondering if there might be a better alternative. One reason is that it’s being called frequently. Another reason is that `toString()` is a general-purpose method. I was thinking to call it like `FieldName.name()`, however that feels a bit redundant. Maybe it doesn't worth overthinking, and it's best to leave it(`toString`) as-is unless there's a better naming suggestion from others.

**Comment by alex-spies** [comment]
> Thank you @alex-spies, LGTM! There are a couple of things that I can think of:
> 
> The first is more of a nice-to-have. Since the rule was changed specifically to update the field name in the generated `IsNotNull` predicate, it might be helpful to add a test in `LocalLogicalPlanOptimizerTests` to verify this behavior, if we don’t already have one yet. As this should not affect the final results, and this is kind of a performance optimization.

This PR comes with such a test [here](https://github.com/elastic/elasticsearch/pull/128910/files#diff-b1566ee39bc5dcb53d8bf773706bebb21905832eb2a2760c8457bda0f704ca6aR726-R745). It tests if the `IsNotNull` is being generated as that's the fixed behavior - previously, we just didn't emit this filter at all for union types.

I considered also adding a physical plan optimizer test, but that would not show anything interesting because we're not able to push the filter down, yet. (And that's a separate problem to solve.)

> The second is that there are quite a few places where `FieldName.toString()` is being called. I was wondering if there might be a better alternative. One reason is that it’s being called frequently. Another reason is that `toString()` is a general-purpose method. I was thinking to call it like `FieldName.name()`, however that feels a bit redundant. Maybe it doesn't worth overthinking, and it's best to leave it(`toString`) as-is unless there's a better naming suggestion from others.

Yeah, that's a bit noisy. I agree that using `.toString()` is not helpful, as that just does the same as `.name()` - I'll fix that.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java [hunk 2]
```diff
@@ -27,14 +27,24 @@
...
- * - parent - the immediate parent of the field; useful for figuring out the type of field (nested vs object)
- * - nestedParent - if nested, what's the parent (which might not be the immediate one)
+ * This class offers:
+ * - name - the name of the attribute, but not necessarily of the field.
+ * - The raw EsField representing the field; for parent.child.grandchild this is just grandchild.
+ * - parentName - the full path to the immediate parent of the field, e.g. parent.child (without .grandchild)
+ *
+ * To adequately represent e.g. union types, the name of the attribute can be altered because we may have multiple synthetic field
+ * attributes that really belong to the same underlying field. For instance, if a multi-typed field is used both as {@code field::string}
+ * and {@code field::ip}, we'll generate 2 field attributes called {@code $$field$converted_to$string} and {@code $$field$converted_to$ip}
```
Comment (craigtaverner) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java:37]: In union-types we do not have multiple names like this, since the name specifies the type we're converting to, not the type we're converting from. So if `field` is IP and KEYWORD in different mappings, the converted field might be `$$field$coverted_to$ip` if the query used `field::ip` to resolve the mapping conflict. A different query might use `field::string` to resolve the conflict, and in that query the attribute gets name `$$field$converted_to$string`. So we only ever generate 1 new attribute, not 2, in the same query.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java [hunk 3]
```diff
@@ -27,14 +27,24 @@
...
+ * but still referring to the same underlying field.
  */
 public class FieldAttribute extends TypedAttribute {
 
+    /**
+     * A field name, as found in the mapping. Includes the whole path from the root of the document.
+     * Implemented as a wrapper around {@link String} to distinguish from the attribute name (which sometimes differs!) at compile time.
+     */
+    public record FieldName(String string) {};
```
Comment (craigtaverner) [inline x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java:46]: Not important, but I think I would name named the parameter `name`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferNonNullAggConstraint.java (hunk 1 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferNonNullAggConstraint.java:58]: This looks so familiar. I'm sure I've done that in a few places before, probably during the union-types work. Pity I was not thorough! What I did was replace `field.name()` with `field.field().getName()`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java [hunk 4]
```diff
@@ -126,32 +126,36 @@ public boolean canUseEqualityOnSyntheticSourceDelegate(FieldAttribute attr, Stri
...
+     * pushed down. This should open up more opportunities for lucene pushdown.
      */
     static LucenePushdownPredicates from(SearchStats stats) {
+        // TODO: use FieldAttribute#fieldName, otherwise this doesn't apply to field attributes used for union types.
+        // C.f. https://github.com/elastic/elasticsearch/issues/128905
         return new LucenePushdownPredicates() {
             @Override
             public boolean hasExactSubfield(FieldAttribute attr) {
-                return stats.hasExactSubfield(attr.name());
+                return stats.hasExactSubfield(new FieldAttribute.FieldName(attr.name()));
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:138]: Why are we not calling attr.fieldName()?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java [hunk 5]
```diff
@@ -126,32 +126,36 @@ public boolean canUseEqualityOnSyntheticSourceDelegate(FieldAttribute attr, Stri
...
             }
 
             @Override
             public boolean isIndexedAndHasDocValues(FieldAttribute attr) {
                 // We still consider the value of isAggregatable here, because some fields like ScriptFieldTypes are always aggregatable
                 // But this could hide issues with fields that are not indexed but are aggregatable
                 // This is the original behaviour for ES|QL, but is it correct?
-                return attr.field().isAggregatable() || stats.isIndexed(attr.name()) && stats.hasDocValues(attr.name());
+                return attr.field().isAggregatable()
+                    || stats.isIndexed(new FieldAttribute.FieldName(attr.name()))
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:147]: As above, Why are we not calling attr.fieldName()?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java [hunk 6]
```diff
@@ -126,32 +126,36 @@ public boolean canUseEqualityOnSyntheticSourceDelegate(FieldAttribute attr, Stri
...
+                        && stats.hasDocValues(new FieldAttribute.FieldName(attr.name()));
```
Comment (craigtaverner) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:148]: One more....

**Review by craigtaverner — APPROVED** [review]
Approved, but I did have some questions and concerns, particularly with creating new FieldName instances in the LucenePushdownPredicates class.

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java (hunk 2 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java:37]: We do generate more than 1; I just confirmed this locally with the example given in the javadoc:
```
Eval[[TOIPLEADINGZEROSREJECTED(?field) AS field1#24, TOSTRING(?field) AS field2#27]] ! Project[[!field, field1{r}#24, field2{r}#27]]
\_UnresolvedRelation[test*]                                                          ! \_Limit[1000[INTEGER],false]
                                                                                     !   \_Eval[[$$field$converted_to$ip{f$}#29 AS field1#24, $$field$converted_to$keyword{f$}#30 AS field2#27]]
                                                                                     !     \_EsRelation[test*][!field, $$field$converted_to$ip{f$}#29, $$field$con..]
```

File: x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java (hunk 3 above)
Comment (alex-spies) [reply x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/expression/FieldAttribute.java:46]: I had this initially, but then you have `attr.fieldName().name()` everywhere - which kinda loses meaning although it's correct.

Do we know of a precedent where we used a wrapper record before? In Rust, it'd be standard to call the wrapped attribute `inner` or `base`, but this is not Rust. ^^"

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferNonNullAggConstraint.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferNonNullAggConstraint.java:58]: Caution!

`field.field().getName()` is wrong in case of subfields! The `EsField` doesn't know about the full path, so this is wrong without also using `field.parentName()`.

I hope this gets easier with the updated javadoc. :/

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java (hunk 4 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:138]: This fails the union type csv tests - I didn't want to fix it in this PR but opened  https://github.com/elastic/elasticsearch/issues/128905

Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:138]: Applies also to the instances below.

**Comment by alex-spies** [comment]
CI is green except for 1 test failure in the Elasticsearch Serverless Checks, which is unrelated and since has been muted on Serverless. This is safe to merge.

**Comment by alex-spies** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/129267)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/129269)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/129272)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
