### PR TITLE
Fix testHistoryRetention

### LINKED ISSUE #45953: CI IndexRecoveryIT. testHistoryRetention failure
The test `IndexRecoveryIT. testHistoryRetention` has been failing intermittently, I can see the following failures:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu12,nodes=general-purpose/166/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/162/console

I could not reproduce locally with the following:
```
./gradlew :server:integTest \
--tests "org.elasticsearch.indices.recovery.IndexRecoveryIT.testHistoryRetention" \
-Dtests.seed=6710600F684A48D6 \
-Dtests.security.manager=true \
-Dtests.locale=ewo \
-Dtests.timezone=Pacific/Pago_Pago \
-Dcompiler.java=12 \
-Druntime.java=12
```

with error:
```
org.elasticsearch.indices.recovery.IndexRecoveryIT > testHistoryRetention FAILED
    java.lang.AssertionError: 
    Expected: is <0>
         but: was <41>
        at __randomizedtesting.SeedInfo.seed([6710600F684A48D6:D366BAB0658A8776]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.indices.recovery.IndexRecoveryIT.testHistoryRetention(IndexRecoveryIT.java:910)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
Disable backgorund sync to ensure that the replica's retention lease
isn't expired (in a slow run that runs into the 30s default background
sync interval) before recovery and we get ops based recovery as 
expected.

Closes #45953

Note: See my reproducer for the original failure here https://github.com/elastic/elasticsearch/issues/45953#issuecomment-532295463 

Relates #45208 which added the logic that is expiring the retention leases here

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java [hunk 1]
```diff
@@ -858,14 +857,14 @@ public void sendRequest(Transport.Connection connection, long requestId, String
...
-    @TestIssueLogging(value = "org.elasticsearch:DEBUG", issueUrl = "https://github.com/elastic/elasticsearch/issues/45953")
     public void testHistoryRetention() throws Exception {
         internalCluster().startNodes(3);
 
         final String indexName = "test";
         client().admin().indices().prepareCreate(indexName).setSettings(Settings.builder()
             .put(IndexMetaData.SETTING_NUMBER_OF_SHARDS, 1)
-            .put(IndexMetaData.SETTING_NUMBER_OF_REPLICAS, 2)).get();
+            .put(IndexMetaData.SETTING_NUMBER_OF_REPLICAS, 2)
+            .put(IndexService.RETENTION_LEASE_SYNC_INTERVAL_SETTING.getKey(), TimeValue.timeValueHours(24))).get();
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/indices/recovery/IndexRecoveryIT.java]:
```suggestion
            .put(IndexSettings.FILE_BASED_RECOVERY_THRESHOLD_SETTING.getKey(), 1.0)).get();
```

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Good catch @original-brownbear, but I have a different idea for the fix. This test should work even if a retention lease sync happens. I think it would be better to suppress the reasonable-history check by setting `index.recovery.file_based_threshold: 1.0`. We're already using the `InternalSettingsPlugin` so it's just a case of using a different setting (see below).

**Comment by original-brownbear** [comment]
Thanks @DaveCTurner makes sense => applied your fix :)

**Review by DaveCTurner — APPROVED** [review]
LGTM
