### PR TITLE
[ML] Fix forecasts deletion action when there are many forecast documents.

### LINKED ISSUE #74989: [ML] Deleting a forecast does not always work
**Elasticsearch version** (`bin/elasticsearch --version`):
Found in 7.14.0 BC1
Also reported in 7.10.1

**Description of the problem including expected versus actual behavior**:
Deleting forecasts does not always work.
This was initially raised when deleting `_all` forecasts where the API would respond as though it worked, but only some of the forecasts were deleted.

**Steps to reproduce**:

Test env: multi-node cluster with the gallery dataset using two multi-metric jobs, with model_plot enabled. 
count partition status 1h
sum(bytes) partition action 1h

1. Create a job with multiple forecasts as elastic superuser
2. Check stats to show count of forecasts `GET _ml/anomaly_detectors/my_job/_stats`
3. In Dev Tools, run `DELETE _ml/anomaly_detectors/my_job/_forecast/_all` - this returns `acknowledged: true`
4. Check stats to show count of forecasts `GET _ml/anomaly_detectors/my_job/_stats` - this shows some forecasts are still remaining.

(note - used a multi-node cluster, enabled model_plot and used larger dataset to make the steps more liable to timing issues. I did not check if this can be replicated with simpler configurations.) 

**Provide logs (if relevant)**:

Error logs do not indicate any problems. The following was logged even though only 3 of 4 forecasts where deleted.
```
[2021-07-06T14:20:06,155][INFO ][o.e.x.m.a.TransportDeleteForecastAction] [node2] Deleted forecast(s) [[GzIwfHoBCuniLktSdnsf, FzIvfHoBCuniLktS9nsd, EzIvfHoBCuniLktSqXtG, DzIvfHoBCuniLktSh3uS]] from job [my_job]
```

**Workarounds**

It was still possible to delete individual forecasts, although one zombie forecast did remain so this may not be a perfect workaround.

```
# To find forecast_id's
GET _sql?format=txt
{
  "query": """
  SELECT job_id, forecast_id, count(*) 
  FROM ".ml-anomalies-*"
  WHERE result_type = 'model_forecast_request_stats'
  OR result_type = 'model_forecast'
  GROUP BY forecast_id, job_id
  """
}

# To delete individual forecast:
DELETE _ml/anomaly_detectors/my_job/_forecast/8zIifHoBCuniLktS63rA
```

### PR DESCRIPTION
**Pull request by przemekwitek**
The request:
```
DELETE _ml/anomaly_detectors/my_job/_forecast/_all
```
might not delete all the forecasts.
It can happen in two situations:
1. There are more than 10 forecasts.
We rely on the default value (`10`) of search request source size. The search will just not return those outstanding forecasts.
2. There are more than 10000 forecast documents total.
When there is a partition field with a high cardinality, there are many documents created for each forecast in the results index.
We restrict DBQ `max_docs` to `10000` so DBQ will not delete those outstanding documents.

This PR fixes both problems.

Fixes https://github.com/elastic/elasticsearch/issues/74989

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastAction.java [hunk 1]
```diff
@@ -105,17 +105,19 @@ protected void doExecute(Task task, DeleteForecastAction.Request request, Action
...
-        source.query(builder);
-
-        SearchRequest searchRequest = new SearchRequest(AnomalyDetectorsIndex.jobResultsAliasedName(jobId));
-        searchRequest.source(source);
+            .ifPresent(query::filter);
+        SearchSourceBuilder source =
+            new SearchSourceBuilder()
+                .size(MAX_FORECAST_TO_SEARCH)
+                .query(query);
+        SearchRequest searchRequest =
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastAction.java:118]: First we query to find the forecast IDs the the job then run a DBQ on that list of forecast IDs. There is an optimisation we can make here to no bring back entire document when only one field (`forecast_id`) is required. Now that the query size is `MAX_FORECAST_TO_SEARCH` instead of 10 not bringing back the entire document is even more important. 

Could you make that change in this PR please

Comment (przemekwitek) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastAction.java:118]: > There is an optimisation we can make here to no bring back entire document when only one field (forecast_id) is required.

3 fields are required:
- forecast_id
- job_id (for parsing)
- status (for validation in line 127

I made the  change to only fetch these 3 fields.
One (small?) issue with that is that we still use `ForecastRequestStats` as a data structure to pass these fields around.
It may bite us in the future if someone tries to access another field from `ForecastRequestStats` forgetting it's incomplete.

**Comment by przemekwitek** [comment]
run elasticsearch-ci/rest-compatibility

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastAction.java [hunk 2]
```diff
@@ -105,24 +106,34 @@ protected void doExecute(Task task, DeleteForecastAction.Request request, Action
...
-        source.query(builder);
-
-        SearchRequest searchRequest = new SearchRequest(AnomalyDetectorsIndex.jobResultsAliasedName(jobId));
-        searchRequest.source(source);
+            .ifPresent(query::filter);
+        SearchSourceBuilder source =
+            new SearchSourceBuilder()
+                .size(MAX_FORECAST_TO_SEARCH)
+                // We only need the following 3 fields, there is no need fetching all of them
+                .fetchSource(
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastAction.java:119]:
```suggestion
                .fetchSource(false)
                .docValueField(ForecastRequestStats.FORECAST_ID.getPreferredName())
                .docValueField(ForecastRequestStats. STATUS.getPreferredName())
```

Then the response does not have to be parsed as the fields can be read directly from doc values and the partially populated `ForecastRequestStats` objects can be removed

```
                            for (SearchHit hit : hits) {
                                forecastStatusString = hit.field(ForecastRequestStats.STATUS.getPreferredName()).getValue());
                                if (ignoreStatus(forecastStatusString)) {
                                    continue;
                                }
                                forecastIds.add(hit.field(ForecastRequestStats.FORECAST_ID.getPreferredName()).getValue());
                            }
```

Comment (przemekwitek) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastAction.java]: Done.

**Review by davidkyle — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastAction.java (hunk 2 above)
Comment (davidkyle) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteForecastAction.java]: thanks

**Comment by przemekwitek** [comment]
run elasticsearch-ci/part-1
