### PR TITLE
[ML] Fix DatafeedJobsIT#testDatafeedTimingStats_DatafeedRecreated

### LINKED ISSUE #63973: DatafeedJobsIT#testDatafeedTimingStats_DatafeedRecreated fails
**Build scan**: https://gradle-enterprise.elastic.co/s/weggtbiofm7zw/console-log?task=:x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner

**Repro line**: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.testDatafeedTimingStats_DatafeedRecreated" -Dtests.seed=862B982F15848C7 -Dtests.security.manager=true -Dtests.locale=ro-RO -Dtests.timezone=Africa/Mogadishu -Druntime.java=8 -Dtests.fips.enabled=true

**Reproduces locally?**: no

**Applicable branches**: any

**Failure history**:
This test has been failing every once in a while in the last months, hard to say when it started. Not sure why an issue was not logged, there seems to be #44335 but it's a very old one.

**Failure excerpt**:

 
  | org.elasticsearch.xpack.ml.integration.DatafeedJobsIT > testDatafeedTimingStats_DatafeedRecreated FAILED |  
  | java.lang.AssertionError: |  
  | Expected: a value greater than <0L> |  
  | but: <0L> was equal to <0L> |  
  | at __randomizedtesting.SeedInfo.seed([862B982F15848C7:CF35BA87409F0E03]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.assertDatafeedStats(DatafeedJobsIT.java:272) |  
  | at org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.lambda$testDatafeedTimingStats_DatafeedRecreated$5(DatafeedJobsIT.java:178) |  
  | at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:951) |  
  | at org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.lambda$testDatafeedTimingStats_DatafeedRecreated$6(DatafeedJobsIT.java:175) |  
  | at org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.testDatafeedTimingStats_DatafeedRecreated(DatafeedJobsIT.java:185)

### PR DESCRIPTION
**Pull request by valeriy42**
Fixes #63973

**Problem**:

The test was failing intermittently with `AssertionError: Expected: a value greater than <0L> but: <0L> was equal to <0L>` due to a race condition between data processing completion and asynchronous datafeed timing stats persistence.

**Root Cause**:
Datafeed timing stats are persisted asynchronously. The test's single assertBusy() block checked both data processing completion AND timing stats simultaneously. Data processing could complete before timing stats persistence finished, causing search_count to still appear as 0.

**Solution**:
Split the assertion into two phases:
- Phase 1: Wait for data processing to complete (processedRecordCount == numDocs)
- Phase 2: Wait for timing stats to be persisted (search_count > 0)
This eliminates the race condition while maintaining the test's validation goals and testing realistic client-observable behavior.

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/DatafeedJobsIT.java [hunk 1]
```diff
@@ -788,7 +794,6 @@ private void startRealtime(String jobId, Integer maxEmptySearches) throws Except
         }, 30, TimeUnit.SECONDS);
     }
 
-    @LuceneTestCase.AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/105239")
```
Comment (valeriy42) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/DatafeedJobsIT.java:791]: Ed actually fixed it in https://github.com/elastic/elasticsearch/pull/114553, but didn't unmute the test.

**Review by prwhelan — APPROVED** [review]
