### PR TITLE
[Transform] Fix transform validation to reject PUT and _start when user lacks remote index permissions

### LINKED ISSUE #95367: [Transform] Behavior is not consistent between `PUT` and `_preview` wrt accessing remote index.
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 21.6.0

### Problem Description

When the user configures remote index in their transform but does not have permissions to access it, `_preview` request will fail with error message: "Source indices have been deleted or closed.".
However, such a transform can be created via `PUT` and started via `_start`. It should not be possible.

Reported by @yangwan

### Steps to Reproduce

1. Configure a transform that accesses remote index.
2. Set up permissions so that the user cannot access the remote index.
3. Run `GET _transform/_preview`
4. Run `PUT _transform/my-transform` with the same config
5. Observe the difference between steps 3. and 4.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by valeriy42**
When a transform is configured with a remote (cross-cluster) source index and the user lacks permissions to access it, the `_preview` API correctly fails -- but `PUT _transform` and `_start` silently succeed, allowing unauthorized transforms to be created and started. The root cause is that `validateQuery` in `AbstractCompositeAggFunction` only checks the response status code, which is `OK` even when `IndicesOptions.LENIENT_EXPAND_OPEN` causes unauthorized indices to be silently ignored. The search returns null aggregations in this case, but unlike `preview()`, `validateQuery()` never checks for that condition.

This PR introduces a `SourceAccessDiagnostics` class that inspects the `SearchResponse` for security-related failures at both the CCS cluster level (SKIPPED/FAILED clusters with `ElasticsearchSecurityException`) and the shard level (`FORBIDDEN`/`UNAUTHORIZED` status). A null-aggregation check is added to `validateQuery()`, but -- critically -- it only rejects the request when a security failure is **positively identified**. When no security failure is found, validation passes through silently. This distinction avoids the regression that caused PR #95318 to be reverted in #95562: that earlier change unconditionally failed on null aggregations, which broke integrations (such as Elastic Defend) that create and start transforms with wildcard source patterns before any matching indices exist. Since `defer_validation` only defers from PUT to `_start`, there was no way for those integrations to bypass the check. Our approach preserves backward compatibility for the empty-indices case while catching the unauthorized-remote-index case. The `preview()` method also delegates to the same diagnostics class, so all three APIs now produce consistent, actionable error messages when a security failure is detected, falling back to the original generic message otherwise.

The multi-cluster YAML integration tests are updated to verify that both `PUT _transform` and `_start` now reject unauthorized remote transforms. A new test case creates a transform with `defer_validation: true` and confirms that `_start` catches the permission issue. Unit tests for `SourceAccessDiagnostics` cover cluster-level SKIPPED/FAILED scenarios, shard-level security exceptions, FORBIDDEN/UNAUTHORIZED status codes, and the fallback to the generic message for non-security failures.

Fixes #95367

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/common/SourceAccessDiagnostics.java [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+    /**
+     * Inspects a {@link SearchResponse} that returned null aggregations and produces
+     * a human-readable error message identifying the likely cause.
+     *
+     * <p>The method checks, in order:
+     * <ol>
+     *   <li>CCS cluster-level failures for security exceptions (SKIPPED or FAILED clusters)</li>
+     *   <li>Top-level shard failures for security exceptions</li>
+     *   <li>Falls back to a generic "deleted or closed" message</li>
+     * </ol>
```
[the remark this answers is not in the document]
Comment (valeriy42) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/common/SourceAccessDiagnostics.java:35]: @copilot open a new pull request to apply changes based on [this feedback](https://github.com/elastic/elasticsearch/pull/142403#discussion_r2799743399)

File: x-pack/plugin/transform/qa/multi-cluster-tests-with-security/src/test/resources/rest-api-spec/test/multi_cluster/80_transform.yml [hunk 2]
```diff
@@ -319,6 +320,30 @@ teardown:
             }
           }
 
+---
+"Batch transform _start from remote cluster when the user is not authorized":
+  - do:
+      headers: { Authorization: "Basic Ym9iOnRyYW5zZm9ybS1wYXNzd29yZA==" }  # This is bob
```
Comment (prwhelan) [inline x-pack/plugin/transform/qa/multi-cluster-tests-with-security/src/test/resources/rest-api-spec/test/multi_cluster/80_transform.yml:326]: hi bob

File: docs/changelog/142403.yaml [hunk 3]
```diff
@@ -0,0 +1,6 @@
+area: "Machine Learning, Transform"
```
Comment (prwhelan) [inline docs/changelog/142403.yaml]:
```suggestion
area: "Transform"
```

Only add the tag for `:ml/Transform`, otherwise the robot starts panicking and fails CI

**Review by prwhelan — APPROVED** [review]
