### PR TITLE
Make feature reset API response more informative

### LINKED ISSUE #71178: Feature reset API should fail fast when `action.destructive_requires_name` is `true`
**Elasticsearch version** (`bin/elasticsearch --version`):
master

**Description of the problem including expected versus actual behavior**:
Calling the feature reset API with `action.destructive_requires_name: true` results in the API
returning as if no failures occurred, but no reset actually took place
**Steps to reproduce**:

 1. Set `action.destructive_requires_name` to `true`
 2. Have some system indices (possibly `.ml-*` related ones)
 3. Call the reset feature API
 4. Notice no failure returned, but reset feature call failed to delete anything

I think to fix this, the API call should blow up when this setting is false to indicate failure.

### PR DESCRIPTION
**Pull request by williamrandolph**
Previously, the Reset API returned a list of which feature states it tried to reset, along with success and failure messages. However, the overall return status was always success (`200 OK`), even if an individual feature state failed. (For example, if wildcard deletions were disabled for associated indices #71150.)

This PR changes the Reset API so that it uses different response codes for different situations: `200 OK` if all reset operations succeed, `207 MULTI STATUS` if some operations succeed and others fail, and `500 INTERNAL SERVER ERROR` if all of the reset operations fail. Clients should check the response code from this API.

The API response now includes formatted stack traces when reset operation fails.

- [x] add documentation about the possible 207 response

Fixes #71178

### CODE REVIEW

**Comment by jaymode** [comment]
Hmm, I wonder if this is a prime example for using an HTTP 207 as discussed in https://github.com/elastic/elasticsearch/issues/60442? It seems like it to me where the behavior of the API is desirable so we know all of the errors rather than the first and have to play whack a mole. Maybe we should instead fix the consumers of the API to check for failures? What do you think?

**Comment by williamrandolph** [comment]
That seems like a good approach here, and I'll see if I can get it working quickly. Otherwise it might be worth making a new issue for it so that we can get some kind of fail-fast behavior into the tests.

File: server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestResetFeatureStateAction.java [hunk 1]
```diff
@@ -39,6 +41,19 @@ public String getName() {
...
         final ResetFeatureStateRequest req = new ResetFeatureStateRequest();
 
-        return restChannel -> client.execute(ResetFeatureStateAction.INSTANCE, req, new RestToXContentListener<>(restChannel));
+        return restChannel -> client.execute(
+            ResetFeatureStateAction.INSTANCE,
+            req,
+            new RestToXContentListener<>(restChannel) {
+                @Override
+                protected RestStatus getStatus(ResetFeatureStateResponse response) {
+                    if (response.hasAllFailures()) {
```
Comment (williamrandolph) [inline server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestResetFeatureStateAction.java:50]: So I've got a 500 if all resets fail, a 207 for mixed responses, and a 200 if all goes well. Does this make sense?

**Comment by williamrandolph** [comment]
I think these test failures have to do with this branch, so I'm looking into them.

File: client/rest-high-level/src/main/java/org/elasticsearch/client/feature/ResetFeaturesResponse.java [hunk 2]
```diff
@@ -47,24 +48,30 @@ public static ResetFeaturesResponse parse(XContentParser parser) {
     public static class ResetFeatureStateStatus {
         private final String featureName;
         private final String status;
+        private final Exception exception;
```
Comment (jaymode) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/feature/ResetFeaturesResponse.java:51]: I cannot comment on the actual line but on line 26, the object parser still uses the "snapshottable" term and is incorrect for this class. Can you address this?

File: client/rest-high-level/src/main/java/org/elasticsearch/client/feature/ResetFeaturesResponse.java [hunk 3]
```diff
@@ -78,5 +85,9 @@ public String getFeatureName() {
         public String getStatus() {
             return status;
         }
+
+        public Exception getException() {
```
Comment (jaymode) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/feature/ResetFeaturesResponse.java:89]: Mark as `@Nullable` and add javadocs to this method and the class?

File: client/rest-high-level/src/main/java/org/elasticsearch/client/feature/ResetFeaturesResponse.java [hunk 4]
```diff
@@ -47,24 +48,30 @@ public static ResetFeaturesResponse parse(XContentParser parser) {
...
             PARSER.declareField(ConstructingObjectParser.constructorArg(),
                 (p, c) -> p.text(), FEATURE_NAME, ObjectParser.ValueType.STRING);
             PARSER.declareField(ConstructingObjectParser.constructorArg(),
                 (p, c) -> p.text(), STATUS, ObjectParser.ValueType.STRING);
+            PARSER.declareObject(ConstructingObjectParser.optionalConstructorArg(),
+                (p, c) -> ElasticsearchException.failureFromXContent(p), EXCEPTION);
         }
 
-        ResetFeatureStateStatus(String featureName, String status) {
+        ResetFeatureStateStatus(String featureName, String status, Exception exception) {
```
Comment (jaymode) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/feature/ResetFeaturesResponse.java:71]:
```suggestion
        ResetFeatureStateStatus(String featureName, String status, @Nullable Exception exception) {
```

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java [hunk 5]
```diff
@@ -94,6 +101,25 @@ public void testResetSystemIndices() throws Exception {
         assertThat(response.getIndices(), arrayContaining("my_index"));
     }
 
+    /**
+     * Evil test - what if the cleanup method fails?
+     */
+    public void testFailFastOnStateCleanupFailure() throws Exception {
```
Comment (jaymode) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java:107]: technically this is not failing fast since we let everything finish before returning a response?

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java [hunk 6]
```diff
@@ -94,6 +101,25 @@ public void testResetSystemIndices() throws Exception {
         assertThat(response.getIndices(), arrayContaining("my_index"));
     }
 
+    /**
+     * Evil test - what if the cleanup method fails?
```
Comment (jaymode) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java:105]:
```suggestion
     * Evil test - test behavior when a cleanup method fails
```

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java [hunk 7]
```diff
@@ -94,6 +101,25 @@ public void testResetSystemIndices() throws Exception {
...
+     */
+    public void testFailFastOnStateCleanupFailure() throws Exception {
+        try {
+            EvilSystemIndexTestPlugin.beEvil = true;
```
Comment (jaymode) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java:109]: This variable should be modified using a synchronized static method for safety

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java [hunk 8]
```diff
@@ -145,4 +171,34 @@ public String getFeatureDescription() {
...
+        @Override
+        public String getFeatureName() {
+            return "EvilSystemIndexTestPlugin";
+        }
+
+        @Override
+        public String getFeatureDescription() {
+            return "a plugin that can be very bad";
+        }
+
```
Comment (jaymode) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java:191]:
```suggestion

public static synchronized void setBeEvil(boolean evil) {
    beEvil = evil;
}

public static synchronized boolean isEvil() {
    return beEvil;
}

```

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java [hunk 9]
```diff
@@ -145,4 +171,34 @@ public String getFeatureDescription() {
...
+        @Override
+        public void cleanUpFeature(
+            ClusterService clusterService,
+            Client client,
+            ActionListener<ResetFeatureStateResponse.ResetFeatureStateStatus> listener) {
+            if (beEvil == false) {
+                listener.onResponse(ResetFeatureStateResponse.ResetFeatureStateStatus.success(getFeatureName()));
+            } else {
+                listener.onResponse(ResetFeatureStateResponse.ResetFeatureStateStatus.failure(getFeatureName(), "problem!"));
+            }
```
Comment (jaymode) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java:201]:
```suggestion
            if (isEvil()) {
                listener.onResponse(ResetFeatureStateResponse.ResetFeatureStateStatus.failure(getFeatureName(), "problem!"));
            } else {
                listener.onResponse(ResetFeatureStateResponse.ResetFeatureStateStatus.success(getFeatureName()));
            }
```

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java [hunk 10]
```diff
@@ -43,7 +44,7 @@ public ResetFeatureStateResponse(StreamInput in) throws IOException {
         this.resetFeatureStateStatusList = in.readList(ResetFeatureStateStatus::new);
     }
 
-    public List<ResetFeatureStateStatus> getItemList() {
+    public List<ResetFeatureStateStatus> getFeatureStateResetStatusList() {
```
Comment (jaymode) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java:47]:
```suggestion
    public List<ResetFeatureStateStatus> getFeatureStateResetStatuses() {
```

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java [hunk 11]
```diff
@@ -92,59 +93,106 @@ public String toString() {
...
+        }
+
+        public static ResetFeatureStateStatus failure(String featureName, Exception exception) {
+            return new ResetFeatureStateStatus(
+                featureName,
+                Status.FAILURE,
+                exception);
+        }
+
+        public static ResetFeatureStateStatus failure(String featureName, String exceptionMessage) {
```
Comment (jaymode) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java:115]: Let's make the caller provide the exception and not allow for a message to be provided without an exception

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java [hunk 12]
```diff
@@ -92,59 +93,106 @@ public String toString() {
...
         public String getFeatureName() {
             return this.featureName;
         }
 
-        public String getStatus() {
+        public Status getStatus() {
             return this.status;
         }
 
+        public Exception getException() {
```
Comment (jaymode) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java:142]: Mark as `@Nullable`

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java [hunk 13]
```diff
@@ -92,59 +93,106 @@ public String toString() {
...
+            return this.exception;
+        }
+
         @Override
         public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
             builder.startObject();
             builder.field("feature_name", this.featureName);
             builder.field("status", this.status);
+            ElasticsearchException.generateFailureXContent(builder, params, exception, true);
```
Comment (jaymode) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java:151]: Guard this with a null check since there was no error?

**Review by jaymode — CHANGES_REQUESTED** [review]
Looking pretty good. I left some comments.

File: server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java (hunk 10 above)
Comment (williamrandolph) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/features/ResetFeatureStateResponse.java:47]: Thanks for catching this. I may read some _Effective Java_ as penance for this mistake.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java (hunk 5 above)
Comment (williamrandolph) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/FeatureStateResetApiIT.java]: Good catch — I've changed the name.

File: client/rest-high-level/src/main/java/org/elasticsearch/client/feature/ResetFeaturesResponse.java [hunk 14]
```diff
@@ -8,21 +8,28 @@
...
 import org.elasticsearch.common.xcontent.ConstructingObjectParser;
 import org.elasticsearch.common.xcontent.ObjectParser;
 import org.elasticsearch.common.xcontent.XContentParser;
 
 import java.util.List;
+import java.util.Objects;
 
+/**
+ * This class represents the response of the Feature State Reset API. It is a
+ * list containing the response of every feature whose state was reset.
```
Comment (jaymode) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/feature/ResetFeaturesResponse.java:23]:
```suggestion
 * list containing the response of every feature whose state can be reset. The
 * response from each feature will indicate success or failure. In the case of a
 * failure, the cause will be returned as well.
```

**Review by jaymode — APPROVED** [review]
LGTM. Please make sure to backport to 7.x and the 7.13 branches so this makes it into the next 7.13 BC.

**Comment by williamrandolph** [comment]
Backport to 7.x: https://github.com/elastic/elasticsearch/pull/72332
Backport to 7.13: https://github.com/elastic/elasticsearch/pull/72341
