### PR TITLE
Try to convince the JVM not to lose stacktraces

### LINKED ISSUE #24376: Run with -XX:-OmitStackTraceInFastThrow
If a particular code path fails enough times the JVM can chose to omit the stack trace for it. [This](http://jawspeak.com/2010/05/26/hotspot-caused-exceptions-to-lose-their-stack-traces-in-production-and-the-fix/) post does a better job of explaining it than I can. I vote that we disable this feature of the JVM because eating debugging information is bad, bad, bad. I've seen this happen in a few situations:
1. When someone sends a ton of failing documents.
2. When someone sends a script that NPEs on a ton of documents. This is especially bad because without the stack trace we can't track down whether the cause is something in the script engine or in the user's scripts. The `script_stack` that we so lovingly build is always empty.
3. In painless's tests when we test the `script_stack`. This is where I first encountered it.

I asked @danielmitterdorfer to do a [benchmark run](https://elasticsearch-benchmarks.elastic.co/no-omit/) with the flag set and he said it didn't really change the performance of things that we measured. I expect it really helps speed up those cases I referenced above at the cost of losing all the nice debugging information that we find so useful. That being said, I don't think the benchmarking we have is really going to be testing the cases where this flag really shines. We don't typically benchmark the "I'm sending a million broken documents" use case. But maybe we don't care if we slow that process down? At lest, not if that speed sacrifices debugging information.

### PR DESCRIPTION
**Pull request by nik9000**
This adds `-XX:-OmitStackTraceInFastThrow` to the JVM arguments
which *should* prevent the JVM from omitting stack traces on
common exception sites. Even though these sites are common, we'd
still like the exceptions to debug them.

This also adds the flag when running tests and adapts some tests
that had workarounds for the absense of the flag.

Closes #24376

### CODE REVIEW

File: modules/lang-painless/src/test/java/org/elasticsearch/painless/ArrayLikeObjectTestCase.java [hunk 1]
```diff
@@ -80,9 +80,14 @@ private void expectOutOfBounds(int index, String script, Object val) {
         IndexOutOfBoundsException e = expectScriptThrows(IndexOutOfBoundsException.class, () ->
             exec(script, singletonMap("val", val), true));
         try {
+            /* If this fails you *might* be missing -XX:-OmitStackTraceInFastThrow in the test jvm
```
Comment (jasontedor) [inline modules/lang-painless/src/test/java/org/elasticsearch/painless/ArrayLikeObjectTestCase.java]: Sorry to nit, I think that this is cleaner for multi-line comments:

```
/*
 * Text goes here.
 * A blank line above and below makes it clean.
 */
```

File: modules/lang-painless/src/test/java/org/elasticsearch/painless/ScriptTestCase.java [hunk 2]
```diff
@@ -128,12 +128,13 @@ public void assertBytecodeHasPattern(String script, String pattern) {
...
-                    if (0 != e.getCause().getStackTrace().length) {
-                        // Without -XX:-OmitStackTraceInFastThrow the jvm can eat the stack trace which causes us to ignore script_stack
-                        AssertionFailedError assertion = new AssertionFailedError("ScriptException should have a scriptStack");
-                        assertion.initCause(e);
-                        throw assertion;
-                    }
+                    /* If this fails you *might* be missing -XX:-OmitStackTraceInFastThrow in the test jvm
+                     * In Eclipse you can add this by default by going to Preference->Java->Installed JREs,
+                     * clicking on the default JRE, clicking edit, and adding the flag to the
+                     * "Default VM Arguments". */
```
Comment (jasontedor) [inline modules/lang-painless/src/test/java/org/elasticsearch/painless/ScriptTestCase.java]: A blank line above and below. 😄

**Review by jasontedor — APPROVED** [review]
I left a comment about multi-line comments but I'm good either way.

File: modules/lang-painless/src/test/java/org/elasticsearch/painless/ArrayLikeObjectTestCase.java (hunk 1 above)
Comment (nik9000) [inline modules/lang-painless/src/test/java/org/elasticsearch/painless/ArrayLikeObjectTestCase.java]: I like the stately form of multiline comments for javadocs and really long comments that have to stand out but I tend to prefer this one for single line comments that happen to be long enough that they end up on multiple lines.  Clear as mud?

**Comment by nik9000** [comment]
Thanks for reviewing @jasontedor! Merged.

File: modules/lang-painless/src/test/java/org/elasticsearch/painless/ArrayLikeObjectTestCase.java (hunk 1 above)
Comment (jasontedor) [inline modules/lang-painless/src/test/java/org/elasticsearch/painless/ArrayLikeObjectTestCase.java]: > Clear as mud?

Indeed. 😐
