### PR TITLE
Fix testResyncAfterPrimaryPromotion

### LINKED ISSUE #52598: [CI] RecoveryDuringReplicationTests.testResyncAfterPrimaryPromotion failing reproducibly
This test just failed and reproduces locally for me.

https://gradle-enterprise.elastic.co/s/lflqfnox2xl4c/tests/nfxodyych4uas-b7kbbqymo3ykc

```
    java.lang.AssertionError: 
    Expected: is <5>
         but: was <1>
        at __randomizedtesting.SeedInfo.seed([F5E9DF78AE4335DB:F82474D3A9A0FC1F]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.replication.RecoveryDuringReplicationTests.testResyncAfterPrimaryPromotion(RecoveryDuringReplicationTests.java:380)
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.index.replication.RecoveryDuringReplicationTests.testResyncAfterPrimaryPromotion" -Dtests.seed=F5E9DF78AE4335DB -Dtests.security.manager=true -Dtests.locale=es-ES -Dtests.timezone=Europe/Uzhgorod -Dcompiler.java=13
```

### PR DESCRIPTION
**Pull request by dnhatn**
Adjusts the assertion as we might eagerly clean up translog during resync since #52556 

Relates #52556
Closes #52598

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/replication/RecoveryDuringReplicationTests.java [hunk 1]
```diff
@@ -378,7 +377,7 @@ public void testResyncAfterPrimaryPromotion() throws Exception {
                     assertThat(source.source.utf8ToString(), is("{ \"f\": \"normal\"}"));
                 }
             }
-            assertThat(translogOperations, is(initialDocs + extraDocs));
```
Comment (dnhatn) [inline server/src/test/java/org/elasticsearch/index/replication/RecoveryDuringReplicationTests.java]: I spent some time to separate these two expectations, but it was more complicated than I thought. I think it's fine to assert like this.

**Comment by dnhatn** [comment]
> testReadLargeBlobWithRetries

@elasticmachine run elasticsearch-ci/1

**Review by ywelsch — APPROVED** [review]
LGTM
