### PR TITLE
Bat scripts to work with JAVA_HOME with parantheses

### LINKED ISSUE #30606: windows elasticsearch.bat file has problems with certains paths
Bug report:

**Elasticsearch version**: 6.2.4
**Plugins installed**: None
**JVM version**: 1.8.0_171
**OS version**: Windows 10 (1511)

**Description of the problem including expected versus actual behavior**:

I cannot start elastic search using `elasticsearch.bat`.
The error message is: `\Common was unexpected at this time.`

**Fix**

%JAVA% is assigned `C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe` in `elasticsearch-env.bat`.
This breaks the last for loop in `elasticsearch.bat`. This can be fixed be changing it to

``for /F "usebackq" %%a in (`CALL %JAVA% -cp "!ES_CLASSPATH!" "org.elasticsearch.tools.launchers.JvmOptionsParser" "!ES_JVM_OPTIONS!" ^|^| echo jvm_options_parser_failed`) do set JVM_OPTIONS=%%a``

See also https://stackoverflow.com/a/30139757/

### LINKED ISSUE #38578: Elasticsearch 7.0.0-alpha2 elasticsearch-plugin \Common is not expected at this time.
**Elasticsearch version**
Version: 7.0.0-alpha2, Build: unknown/unknown/a30e8c2/2018-12-17T12:33:32.311168Z, JVM: 1.8.0_172

**JVM version**
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

**OS version** 
Windows Server 2012 R2 Datacenter

**Description of the problem including expected versus actual behavior**:
Expected to have plugin installed like it worked in previous version.

**Steps to reproduce**:
Upgraded from 6.3.2 to 7.0.0-alpha2 and during install when used old config it ran into errors. 
Turned off geoip ingest plugin let the install to finish. Thought I can enable it again after install, but it seems it is not working. 
```
>"C:\Program Files\Elastic\Elasticsearch\7.0.0-alpha2\bin\elasticsearch-plugin.bat" install ingest-geoip
\Common was unexpected at this time.
```
Did not upgrade Java, from google search it seemed that at some point java update caused similar issues, but this time Java was not updated.
Not sure if it is due to this error, but new version does not start.
```
[2019-02-07T17:30:24,021][ERROR][o.e.b.Bootstrap          ] [TDOSNELIN016] node validation exception
[1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.zen.ping.unicast.hosts, discovery.zen.hosts_provider, cluster.initial_master_nodes] must be configured
[2019-02-07T17:30:24,025][INFO ][o.e.n.Node               ] [TDOSNELIN016] stopping ...
[2019-02-07T17:30:24,126][INFO ][o.e.n.Node               ] [TDOSNELIN016] stopped
[2019-02-07T17:30:24,126][INFO ][o.e.n.Node               ] [TDOSNELIN016] closing ...
[2019-02-07T17:30:24,144][INFO ][o.e.n.Node               ] [TDOSNELIN016] closed
[2019-02-07T17:30:24,149][INFO ][o.e.x.m.p.NativeController] [TDOSNELIN016] Native controller process has stopped - no new native processes can be started
```

### PR DESCRIPTION
**Pull request by pgomulka**
the elasticsearch.bat and elasticsearch-env.bat won't work if JAVA contains parentheses. This seems to be the limitation of FOR /F IN (command) DO syntax.
The JAVA variable present in a command contains a path to a binary to start elasticsearch (with spaces & parans). We can workaround the problem of spaces and parentheses in this path by referring this variable with a CALL command.
Note that executing binaries with CALL is an undocumented behaviour (but works)

closes #38578
closes #38624
closes #33405
closes #30606

### CODE REVIEW

**Comment by pgomulka** [comment]
ok to test

**Review by rjernst — COMMENTED** [review]
Sorry this review never got published before. Some of these comments might have already been addressed.

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 1]
```diff
@@ -193,6 +192,39 @@ public void test50StartAndStop() throws IOException {
...
+
+                sh.runIgnoreExitCode("cmd /c mklink /D 'C:\\Program Files (x86)\\java' $Env:JAVA_HOME");
+
+                sh.getEnv().put("PATH", newPath);
+                sh.getEnv().put("JAVA_HOME", "C:\\Program Files (x86)\\java");
+
+                Archives.runElasticsearch(installation, sh);
+
+                Archives.stopElasticsearch(installation);
+            } catch (IOException e) {
```
[the remark this answers is not in the document]
Comment (pgomulka) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: it is because this code is inside lambda` onWindows( ()-> {here} )`

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 2]
```diff
@@ -193,6 +192,39 @@ public void test50StartAndStop() throws IOException {
...
+            final Shell sh = new Shell();
+            final String originalPath = sh.run("$Env:PATH").stdout.trim();
+            final String javaHome = sh.run("$Env:JAVA_HOME").stdout.trim();
+
+            try {
+                final String newPath = Arrays.stream(originalPath.split(";"))
+                                             .filter(path -> path.contains("Java") == false)
+                                             .collect(joining(";"));
+
+                sh.runIgnoreExitCode("cmd /c mklink /D 'C:\\Program Files (x86)\\java' $Env:JAVA_HOME");
```
[the remark this answers is not in the document]
Comment (pgomulka) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: you mean the symbolic link creation? Is the PS 5 available since certain windows version?

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (rjernst) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: We should change the signature of `PlatformAction.run` to have a checked `Exception`, so that we don't need these intermediate try/catches.

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 3]
```diff
@@ -193,6 +192,39 @@ public void test50StartAndStop() throws IOException {
...
+    public void test51JavaHomeContainParansAndSpace() throws IOException {
+        assumeThat(installation, is(notNullValue()));
+
+        Platforms.onWindows(() -> {
+            final Shell sh = new Shell();
+            final String originalPath = sh.run("$Env:PATH").stdout.trim();
+            final String javaHome = sh.run("$Env:JAVA_HOME").stdout.trim();
+
+            try {
+                final String newPath = Arrays.stream(originalPath.split(";"))
```
[the remark this answers is not in the document]
Comment (pgomulka) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: so the vagrant images are guaranteed not to have java inside PATH? I feel like it wouldn't harm to make sure PATH does not have java in there.

[the remark this answers is not in the document]
Comment (rjernst) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: No, java is in the PATH. I don't think we should change that. In 6.7 I made sure all the tests pass in JAVA_HOME, to avoid triggering the deprecation warning output starting in that version when using java on the PATH. In 7.0+ we no longer look at PATH at all to find java.

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by pgomulka** [comment]
@rjernst would you be able to review this again?

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (rjernst) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: Why do we ingnore the exit code? If this fails, the test cannot proceed right?

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 4]
```diff
@@ -192,7 +194,70 @@ public void test52BundledJdkRemoved() throws IOException {
...
+                Archives.stopElasticsearch(installation);
+
+                String pluginListCommand = installation.bin + "/elasticsearch-plugin list";
+                Result result = sh.run(pluginListCommand);
+                assertThat(result.exitCode, equalTo(0));
+
+            } finally {
+                //clean up sym link
+                sh.runIgnoreExitCode("cmd /c del /F /Q 'C:\\Program Files (x86)\\java' ");
+                sh.getEnv().put("JAVA_HOME", javaHome);
```
Comment (rjernst) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: No need for setting JAVA_HOME here.

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 5]
```diff
@@ -192,7 +194,70 @@ public void test52BundledJdkRemoved() throws IOException {
...
+                Archives.stopElasticsearch(installation);
+
+                String pluginListCommand = installation.bin + "/elasticsearch-plugin list";
+                Result result = sh.run(pluginListCommand);
+                assertThat(result.exitCode, equalTo(0));
+
+
+                FileUtils.rm(Paths.get(temp));
+            } finally {
+                sh.getEnv().put("JAVA_HOME", javaHome);
```
Comment (rjernst) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: ditto, this can be removed

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 6]
```diff
@@ -192,7 +194,70 @@ public void test52BundledJdkRemoved() throws IOException {
...
+
+                //verify ES can start, stop and run plugin list
+                Archives.runElasticsearch(installation, sh);
+
+                Archives.stopElasticsearch(installation);
+
+                String pluginListCommand = installation.bin + "/elasticsearch-plugin list";
+                Result result = sh.run(pluginListCommand);
+                assertThat(result.exitCode, equalTo(0));
+
```
Comment (rjernst) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: nit: extra blank line

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 7]
```diff
@@ -192,7 +194,70 @@ public void test52BundledJdkRemoved() throws IOException {
...
+        Platforms.onLinux(() -> {
+            final Shell sh = new Shell();
+            final String javaHome = sh.run("echo $JAVA_HOME").stdout.trim();
+
+            try {
+
+                // Create temporary directory with a space and link to java binary.
+                // Use it as java_home
+                final String temp = sh.runIgnoreExitCode("mktemp -d --suffix=\"java home\"").stdout.trim();
```
Comment (rjernst) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: Create a temp directory seems error prone, since it may have noexec on some systems. I think this test can use any arbitrary path since it will clean it up afterwards?

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 8]
```diff
@@ -192,7 +194,70 @@ public void test52BundledJdkRemoved() throws IOException {
...
+                final String java = sh.runIgnoreExitCode("which java").stdout.trim();
```
Comment (rjernst) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: Look for $SYSTEM_JAVA_HOME. See other tests that set JAVA_HOME. We no longer use java from the path.

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 9]
```diff
@@ -192,7 +194,70 @@ public void test52BundledJdkRemoved() throws IOException {
...
     }
 
-    public void test60AutoCreateKeystore() {
+    public void test53JavaHomeWithSpecialCharacters() throws Exception {
+        assumeThat(installation, is(notNullValue()));
+
+        Platforms.onWindows(() -> {
+            final Shell sh = new Shell();
+            final String originalPath = sh.run("$Env:PATH").stdout.trim();
+            final String javaHome = sh.run("$Env:JAVA_HOME").stdout.trim();
```
Comment (rjernst) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: JAVA_HOME does not always exist. You need to look for SYSTEM_JAVA_HOME

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 10]
```diff
@@ -192,7 +194,70 @@ public void test52BundledJdkRemoved() throws IOException {
         }
     }
 
-    public void test60AutoCreateKeystore() {
+    public void test53JavaHomeWithSpecialCharacters() throws Exception {
+        assumeThat(installation, is(notNullValue()));
+
+        Platforms.onWindows(() -> {
+            final Shell sh = new Shell();
+            final String originalPath = sh.run("$Env:PATH").stdout.trim();
```
Comment (rjernst) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: No need to mess with the PATH

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/util/Archives.java [hunk 11]
```diff
@@ -255,7 +253,11 @@ private static void verifyDefaultInstallation(Installation es, Distribution dist
         ).forEach(configFile -> assertThat(es.config(configFile), file(File, owner, owner, p660)));
     }
 
-    public static void runElasticsearch(Installation installation, Shell sh) throws IOException {
+    public static void runElasticsearch(Installation installation) throws Exception {
+        runElasticsearch(installation, new Shell());
```
Comment (rjernst) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/util/Archives.java]: I just removed this recently. We need to always pass in a Shell, so we can control when/if JAVA_HOME is set. Please revert this part.

**Review by rjernst — CHANGES_REQUESTED** [review]
There are a lot of unrelated changes to method signatures and whitespace, Can you clean those up so this PR represents just he actual changes to JAVA_HOME with parentheses?

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java (hunk 9 above)
Comment (pgomulka) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: will remove that at all. As per your comment [here](https://github.com/elastic/elasticsearch/pull/39712/files#r270126523) we don't need to clean it up

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java (hunk 7 above)
Comment (pgomulka) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: we create temp directories when starting up as well. If some systems are not supporting this, it would be better to catch that during testing.
Do you have any specific systems we support in mind that would fail on this?

**Comment by pgomulka** [comment]
@rjernst I have removed the unnecessary whitespace changes. We have however already agreed here https://github.com/elastic/elasticsearch/pull/39712#discussion_r265373126 to throw Exception from `PlatformAction`. This would help avoiding unnecessary try/catch blocks.
Also addressed the code review comments

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java (hunk 7 above)
Comment (rjernst) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: Yes we do create temp directories, but we don't try executing anything from them. Why we do we need this to be complicated creating a special temp dir when we can just use an arbitrary path and clean it up afterwards?

**Comment by rjernst** [comment]
Sure, the signature changes are fine, I see the change now.

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java (hunk 7 above)
Comment (pgomulka) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: I see, we can use a regular directory for this. Should be easy. I was thinking that `mktemp` is ok as we use it through a lot of `bats` tests at the moment. Will keep an eye on further migration to avoid it.

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (pgomulka) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: good spot, test should not proceed if this fails

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 12]
```diff
@@ -192,7 +196,63 @@ public void test52BundledJdkRemoved() throws IOException {
...
+
+                Archives.stopElasticsearch(installation);
+
+                String pluginListCommand = installation.bin + "/elasticsearch-plugin list";
+                Result result = sh.run(pluginListCommand);
+                assertThat(result.exitCode, equalTo(0));
+
+            } finally {
+                //clean up sym link
+                sh.runIgnoreExitCode("cmd /c del /F /Q 'C:\\Program Files (x86)\\java' ");
```
Comment (rjernst) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: I don't think we want to ignore the exit? If this fails, later tests could fail?

**Review by rjernst — APPROVED** [review]
LGTM one last request

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java (hunk 12 above)
Comment (pgomulka) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: Actuality I thought that if this fails the rest of the test should continue. JAVA_HOME should not propagate so it won't be visible if failed

Comment (rjernst) [reply qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: If it fails, something is messed up. I think we should stop testing.

**Comment by pgomulka** [comment]
This needs to be backported to 6.7 branch (for 6.7.2 version) and 7.x (for 7.1)

**Comment by jpountz** [comment]
@pgomulka  I'm assuming there is nothing left to backport and removed the backport pending label.
