### PR TITLE
clear auto-follow errors on deleting pattern

### LINKED ISSUE #77723: CCR clear recent auto-follow errors
If auto-following fails, we keep the most recent error per auto-follow pattern around for inclusion into ccr stats. However, when the auto-follow pattern is deleted, we still keep the recent errors and still report them into ccr stats. This can cause confusion, since the ccr stats endpoints report errors that are no longer relevant. Instead we should clear out the recent error for auto-follow patterns that are deleted.

### PR DESCRIPTION
**Pull request by idegtiarenko**
This change clears auto-follow errors that belongs to patterns that are removed by cluster update.

Closes: #77723

### CODE REVIEW

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java [hunk 1]
```diff
@@ -2350,6 +2353,79 @@ public void testFollowerIndexIsCreatedInExecuteAutoFollow() {
...
+        // and applied
+        assertThat(autoFollowCoordinator.getStats().getRecentAutoFollowErrors(), hasKey("pattern1:index1"));
+
+        // when auto-follow pattern `pattern1` is removed
+        autoFollowCoordinator.updateAutoFollowers(
+            createClusterStateWith(createAutoFollowPattern("pattern2", "logs-*"), createAutoFollowPattern("pattern3", "logs-*"))
+        );
+
+        // then stats are removed as well
+        assertThat(autoFollowCoordinator.getStats().getRecentAutoFollowErrors().keySet(), empty());
```
Comment (idegtiarenko) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java:2386]: This could check that unrelated errors are not removed

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java [hunk 2]
```diff
@@ -2350,6 +2353,79 @@ public void testFollowerIndexIsCreatedInExecuteAutoFollow() {
...
+            List.of(
+                new AutoFollowCoordinator.AutoFollowResult("pattern1", new RuntimeException("ClusterStateFetchException")),
+                new AutoFollowCoordinator.AutoFollowResult(
+                    "pattern1",
+                    List.of(Tuple.tuple(new Index("index1", UUIDs.base64UUID()), new RuntimeException("AutoFollowExecutionException")))
+                )
+            )
+        );
+        // and applied
+        assertThat(autoFollowCoordinator.getStats().getRecentAutoFollowErrors(), hasKey("pattern1:index1"));
```
Comment (idegtiarenko) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java:2378]: I was surprised that the second AutoFollowResult cleared the error from the first one. 
Not sure if this is intended behavior.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java [hunk 3]
```diff
@@ -2350,6 +2353,79 @@ public void testFollowerIndexIsCreatedInExecuteAutoFollow() {
...
+            mockClusterService(),
+            new CcrLicenseChecker(() -> true, () -> false),
+            () -> 1L,
+            () -> 1L,
+            Runnable::run
+        );
+    }
+
+    private ClusterState createClusterStateWith(AutoFollowPattern... patterns) {
+        var patternsAsMap = Stream.of(patterns).collect(toMap(AutoFollowPattern::getRemoteCluster, Function.identity()));
```
Comment (idegtiarenko) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java:2402]: Please confirm my understanding: keys in the map are actually RemoteCluster names and this is same as pattern

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java [hunk 4]
```diff
@@ -2350,6 +2353,94 @@ public void testFollowerIndexIsCreatedInExecuteAutoFollow() {
...
+        // when auto-follow pattern `pattern3` is removed
+        var before = autoFollowCoordinator.getStats();
+        autoFollowCoordinator.updateAutoFollowers(createClusterStateWith(Map.of("pattern1", pattern1, "pattern2", pattern2)));
+        autoFollowCoordinator.updateStats(List.of());// actually triggers the purge
+        var after = autoFollowCoordinator.getStats();
+
+        // then stats are removed as well (but only for the removed pattern)
+        assertThat(
+            before.getRecentAutoFollowErrors(),
+            allOf(hasKey("pattern1:logs-1"), hasKey("pattern2:logs-1"), hasKey("pattern3:metrics-1"))
```
Comment (henningandersen) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java:2397]: I think it would be simpler to read using `equalTo` on the `keySet()`? Likewise in the next assert.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java [hunk 5]
```diff
@@ -2350,6 +2353,94 @@ public void testFollowerIndexIsCreatedInExecuteAutoFollow() {
...
+
+        // and stats are published
+        autoFollowCoordinator.updateStats(
+            List.of(
+                new AutoFollowCoordinator.AutoFollowResult("pattern1", new RuntimeException("ClusterStateFetchException")),
+                new AutoFollowCoordinator.AutoFollowResult(
+                    "pattern1",
+                    List.of(Tuple.tuple(new Index("logs-1", UUIDs.base64UUID()), new RuntimeException("AutoFollowExecutionException")))
+                ),
+                new AutoFollowCoordinator.AutoFollowResult("pattern2", new RuntimeException("ClusterStateFetchException")),
```
Comment (henningandersen) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java:2375]: I think we should also test the case where there is no outer level exception, only an exception for a specific index (since that is the "normal" case).

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java [hunk 6]
```diff
@@ -172,6 +174,14 @@ public synchronized AutoFollowStats getStats() {
     }
 
     synchronized void updateStats(List<AutoFollowResult> results) {
+        // purge stats for removed patterns
+        var currentPatterns = this.patterns;
+        recentAutoFollowErrors.keySet().removeIf(key -> {
+            var semicolonPosition = key.indexOf(':');
+            var patternName = semicolonPosition != -1 ? key.substring(0, semicolonPosition) : key;
```
Comment (henningandersen) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java:181]:
```suggestion
            var colonPosition = key.indexOf(':');
            var patternName = colonPosition != -1 ? key.substring(0, colonPosition) : key;
```

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java [hunk 7]
```diff
@@ -172,6 +174,14 @@ public synchronized AutoFollowStats getStats() {
     }
 
     synchronized void updateStats(List<AutoFollowResult> results) {
+        // purge stats for removed patterns
+        var currentPatterns = this.patterns;
+        recentAutoFollowErrors.keySet().removeIf(key -> {
+            var semicolonPosition = key.indexOf(':');
```
Comment (henningandersen) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java:180]: I think we should use `lastIndexOf`, since index-names cannot have `:`, but unfortunately, I think autofollow pattern names can (at least I did not find the protection against it, hope you will test it).

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java [hunk 8]
```diff
@@ -172,6 +174,14 @@ public synchronized AutoFollowStats getStats() {
...
+            var patternName = semicolonPosition != -1 ? key.substring(0, semicolonPosition) : key;
+            return currentPatterns.contains(patternName) == false;
```
Comment (henningandersen) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java:182]: Because patterns can contain `:` (if I am right about that), we need to check if currentPatterns either contain the `patternName` or the `key` and keep it either way.

**Review by henningandersen — COMMENTED** [review]
I left a few smaller comments, otherwise looking good.

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java (hunk 8 above)
Comment (idegtiarenko) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java]: Updated, though I wonder if it is better to change the key type to instead to avoid ambiguity?

Maybe something like:
```
class ErrorKey(String pattern, @Nullable String index)
```
though it would require transforming entire map when reading errors

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java (hunk 3 above)
Comment (henningandersen) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java]: I think we may have touched on this offline, but the keys in the map are actually auto-follow pattern names, which is not the same as the remote cluster name.

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java (hunk 6 above)
Comment (henningandersen) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java]: I think you missed this comment? Since the character we look for is a colon (':'), I think we should name the variable after that rather than the misleading semicolon name.

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java (hunk 8 above)
Comment (henningandersen) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java]: Yes, I agree to this, would be better to change they key type. I prefer the explicit key over using a tuple, since then we can verify that the `pattern` is not null, whereas the other is allowed to be null. And we can make the string concat of `pattern + ':' + index` inside the explicit key class. Feel free to either include into this PR or tackle in a follow-up - as you please.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java (hunk 3 above)
Comment (idegtiarenko) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java]: Correct, I believe this diff is outdated. I will hide it

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java [hunk 9]
```diff
@@ -2350,6 +1929,150 @@ public void testFollowerIndexIsCreatedInExecuteAutoFollow() {
...
+
+        // when auto-follow pattern `pattern3` is removed
+        var before = autoFollowCoordinator.getStats();
+        autoFollowCoordinator.updateAutoFollowers(createClusterStateWith(Map.of("pattern1", pattern1, "pattern2", pattern2)));
+        autoFollowCoordinator.updateStats(List.of());// actually triggers the purge
+        var after = autoFollowCoordinator.getStats();
+
+        // then stats are removed as well (but only for the removed pattern)
+        assertThat(before.getRecentAutoFollowErrors().keySet(), contains("pattern1", "pattern2", "pattern3"));
+        assertThat(after.getRecentAutoFollowErrors().keySet(), allOf(contains("pattern1", "pattern2"), not(contains("pattern3"))));
```
Comment (henningandersen) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java:1960]: This is slightly confusing. `contains` verifies same length and same order, which gives rise to two comments:

1. I think the order is not relevant. So `equalTo` a `Set.of` would be better here, alternatively `containsInAnyOrder`. The test only passes (I think) because of the use of `LinkedHashMap` internally.
2. The `not(contains("pattern3"))` is true  because it is not a list containing only that one element.

I think we should simply use `equalTo` instead.

I think this comment is true for the other `contains` verifications below in this PR.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java [hunk 10]
```diff
@@ -2350,6 +1929,150 @@ public void testFollowerIndexIsCreatedInExecuteAutoFollow() {
...
+        // and stats are published
+        autoFollowCoordinator.updateStats(
+            List.of(
+                new AutoFollowCoordinator.AutoFollowResult("pattern:1", new RuntimeException("ClusterStateFetchException")),
+                new AutoFollowCoordinator.AutoFollowResult("pattern:2", new RuntimeException("ClusterStateFetchException")),
+                new AutoFollowCoordinator.AutoFollowResult("pattern:3", new RuntimeException("ClusterStateFetchException"))
+            )
+        );
+
+        // when auto-follow pattern `pattern3` is removed
```
Comment (henningandersen) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinatorTests.java:2026]: nit:

```suggestion
        // when auto-follow pattern `pattern:3` is removed
```

**Review by henningandersen — COMMENTED** [review]
I left a few comments, will review the latest addition shortly.

**Review by henningandersen — COMMENTED** [review]
One minor nit here, otherwise this looks good.

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java [hunk 11]
```diff
@@ -253,6 +253,8 @@ void updateAutoFollowers(ClusterState followerClusterState) {
             return;
         }
 
+        this.patterns = Set.copyOf(autoFollowMetadata.getPatterns().keySet());
+
```
Comment (henningandersen) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java:257]: I think we should set the patterns to the empty list above when `autoFollowMetadata == null` too (though I think we never go back to null, so mostly for completeness).

**Review by henningandersen — APPROVED** [review]
LGTM.

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java (hunk 11 above)
Comment (idegtiarenko) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java:257]: I believe we are also not clearing/stopping `autoFollowers` once metadata is null. If this happens for whatever reason then it might result in auto-followers still running but not producing any stats

Comment (henningandersen) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/AutoFollowCoordinator.java:257]: Good point, perhaps we can simply add an assert before the return above to express the intent here?
