### PR TITLE
Avoid NPE when disassociateDeadNodes is executed for a node present in the desired balance

### LINKED ISSUE #91517: [CI] rolling-upgrade-multi-cluster tests failing to start node
I've seen three builds fail now witht he same error and this started happening on Nov 7 so it's likely we've introduced something here:

https://gradle-enterprise.elastic.co/scans/failures?failures.failureClassification=all_failures&failures.failureMessage=Execution%20failed%20for%20task%20%27:x-pack:qa:rolling-upgrade-multi-cluster:v8.6.0%23follower%23oneThirdUpgradedTest%27.%0A%3E%20%60cluster%7B:x-pack:qa:rolling-upgrade-multi-cluster:v8.6.0-follower%7D%60%20failed%20to%20wait%20for%20cluster%20health%20yellow%20after%2040%20SECONDS%0A%20%20%20%20IO%20error%20while%20waiting%20cluster%0A%20%20%20%20%20%20503%20Service%20Unavailable&search.relativeStartTime=P28D&search.timeZoneId=America/Los_Angeles#

```
* What went wrong:
Execution failed for task ':x-pack:qa:rolling-upgrade-multi-cluster:v8.6.0#follower#oneThirdUpgradedTest'.
> `cluster{:x-pack:qa:rolling-upgrade-multi-cluster:v8.6.0-follower}` failed to wait for cluster health yellow after 40 SECONDS
    IO error while waiting cluster
      503 Service Unavailable
```

It seems the follower cluster is having issues coming back up after upgrade.

### PR DESCRIPTION
**Pull request by idegtiarenko**
An NPE is thrown when executing `disassociateDeadNodes` for a node that is 
present in a desired balance failing corresponding master state update task. 
As a result this node can no longer join cluster after restarting as it 
remains in a cluster state.

Closes: #91517

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceReconciler.java [hunk 1]
```diff
@@ -415,13 +415,17 @@ private DiscoveryNode findRelocationTarget(
...
-                logger.trace("relocate {} to {}: {}", shardRouting, nodeId, decision);
-                if (decision.type() == Decision.Type.YES) {
-                    return currentNode.node();
-                }
+            if (nodeId.equals(shardRouting.currentNodeId())) {
+                continue;
+            }
+            final var node = routingNodes.node(nodeId);
+            if (node == null) { // node theft the cluster while reconciliation is still in progress
+                continue;
```
Comment (idegtiarenko) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceReconciler.java:423]: I am working on a unit test for this

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceReconciler.java [hunk 2]
```diff
@@ -415,13 +415,17 @@ private DiscoveryNode findRelocationTarget(
...
-                final var decision = canAllocateDecider.apply(shardRouting, currentNode);
-                logger.trace("relocate {} to {}: {}", shardRouting, nodeId, decision);
-                if (decision.type() == Decision.Type.YES) {
-                    return currentNode.node();
-                }
+            if (nodeId.equals(shardRouting.currentNodeId())) {
+                continue;
+            }
+            final var node = routingNodes.node(nodeId);
+            if (node == null) { // node theft the cluster while reconciliation is still in progress
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceReconciler.java:422]: typo nit:

```suggestion
            if (node == null) { // node left the cluster while reconciliation is still in progress
```

**Review by DaveCTurner — APPROVED** [review]
Could we assert the node is not-null in the place where the NPE was happening? Would have been good to see it as an immediate failure at that point, let's avoid any recurrence and document the assumption here.

Otherwise LGTM (one typo nit) no need for another review.
