### PR TITLE
Fix NPE when deleting multiple backing indices on a data stream

### LINKED ISSUE #62272: NPE when deleting multiple backing indices on a data stream
As reported by @Snp3r here: https://github.com/elastic/elasticsearch/pull/55690#issuecomment-691087407:

I've got 500 error, nullpointer exception when I trying to delete multiple backing indices:

`curl -X DELETE "localhost:9200/.ds-my-data-stream-000001,.ds-my-data-stream-000002?pretty"`
`{
  "error" : {
    "root_cause" : [
      {
        "type" : "null_pointer_exception",
        "reason" : null
      }
    ],
    "type" : "null_pointer_exception",
    "reason" : null
  },
  "status" : 500
}`

Deleting one by one is ok:

`curl -X DELETE "localhost:9200/.ds-my-data-stream-000001?pretty"`
`{
  "acknowledged" : true
}
`
`curl -X DELETE "localhost:9200/.ds-my-data-stream-000002?pretty"`
`{
  "acknowledged" : true
}
`

### PR DESCRIPTION
**Pull request by danhermann**
Fixes #62272.

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexServiceTests.java [hunk 1]
```diff
@@ -129,6 +132,29 @@ public void testDeleteBackingIndexForDataStream() {
...
 
+    public void testDeleteMultipleBackingIndexForDataStream() {
+        int numBackingIndices = randomIntBetween(3, 5);
+        int numBackingIndicesToDelete = randomIntBetween(2, numBackingIndices - 1);
+        String dataStreamName = randomAlphaOfLength(6).toLowerCase(Locale.ROOT);
+        ClusterState before = DataStreamTestHelper.getClusterStateWithDataStreams(
+            List.of(new Tuple<>(dataStreamName, numBackingIndices)), List.of());
+
+        List<Integer> indexNumbersToDelete =
+            randomSubsetOf(numBackingIndicesToDelete, IntStream.rangeClosed(1, numBackingIndices).boxed().collect(Collectors.toList()));
```
Comment (martijnvg) [inline server/src/test/java/org/elasticsearch/cluster/metadata/MetadataDeleteIndexServiceTests.java:143]: I think `numBackingIndices` needs to be changed into `numBackingIndices - 1`, otherwise the test tries to delete the write index which would fail.

**Review by martijnvg — APPROVED** [review]
Left one comment, LGTM otherwise.

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows
