### PR TITLE
Context suggester should filter doc values field

### LINKED ISSUE #25404: Suggester context is null for path with index not_analyzed
**Edit:**

On 5.3.1 the context is:
````            
"contexts": {
  "theContext": [
    "null"
  ]
}
````
on 5.4.2 the context is:
````
"contexts": {
  "theContext": [
    "bar",
    "null"
  ]
}
````
The context should be:
````            
"contexts": {
  "theContext": [
    "bar"
  ]
}
````

<hr />

Perhaps this isn't a bug, but I can't find any documentation that suggests this shouldn't work.

When setting a document field `index` to `not_analyzed`, a suggester context using `path` for that document field is null.

I have a user id that's a UUID which I use a term query search on, but I also use the same user id for context in a suggest. I need to set the index to not_analyzed on the UUID so that I can use the term query, but when setting the index to not_analyzed the context the path is null in the suggest and never matches.

The work around is to set the context separately when uploading the document. This causes an extra field in the request (ohmy) and presumably an increase in storage space.

Here's an example showing that the context path works when not specifying an index, but when setting the index to not_analyzed, the context is null.

-----
Mapping without specifying index for `theContext`;
````
curl -XPUT localhost:9200/analyzed -d '{
     "mappings": {
         "indexed" : {
             "properties": {
                 "suggest": {
                     "type": "completion",
                     "contexts": [
                        {
                            "name": "theContext",
                            "type": "category",
                            "path": "theContext"
                         }
                     ]
                 },
                 "theContext": {
                   "type": "string"
                 }
             }
         }
     }
 }'
````
Mapping for `"index": "not_analyzed"` for `theContext`:
````
curl -XPUT localhost:9200/not_analyzed -d '{
     "mappings": {
         "indexed" : {
             "properties": {
                 "suggest": {
                     "type": "completion",
                     "contexts": [
                        {
                            "name": "theContext",
                            "type": "category",
                            "path": "theContext"
                         }
                     ]
                 },
                 "theContext": {
                   "type": "string",
                   "index": "not_analyzed"
                 }
             }
         }
     }
 }'
````
Adding the document to both:
````
curl -XPOST localhost:9200/analyzed/indexed/foo -d '{
	"suggest": {
		"input": ["foo"]
	},
	"theContext": "bar"
}'
curl -XPOST localhost:9200/not_analyzed/indexed/foo -d '{
	"suggest": {
		"input": ["foo"]
	},
	"theContext": "bar"
}'
````
Searching `analyzed` shows `contexts.theContext = bar`:
````
curl -XPOST localhost:9200/analyzed/indexed/_search -d '{
  "suggest" : {
    "foo" : {
      "prefix" : "foo",
      "completion" : {
        "field" : "suggest"
      }
    }
  }
}'
````
````
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "foo": [
      {
        "text": "foo",
        "offset": 0,
        "length": 3,
        "options": [
          {
            "text": "foo",
            "_index": "analyzed",
            "_type": "indexed",
            "_id": "foo",
            "_score": 1,
            "_source": {
              "suggest": {
                "input": [
                  "foo"
                ]
              },
              "theContext": "bar"
            },
            "contexts": {
              "theContext": [
                "bar"
              ]
            }
          }
        ]
      }
    ]
  }
}
````

The same search on `not_analyzed` shows `contexts.theContext = null`:
````
curl -XPOST localhost:9200/not_analyzed/indexed/_search -d '{
  "suggest" : {
    "foo" : {
      "prefix" : "foo",
      "completion" : {
        "field" : "suggest"
      }
    }
  }
}'
````
````
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "foo": [
      {
        "text": "foo",
        "offset": 0,
        "length": 3,
        "options": [
          {
            "text": "foo",
            "_index": "not_analyzed",
            "_type": "indexed",
            "_id": "foo",
            "_score": 1,
            "_source": {
              "suggest": {
                "input": [
                  "foo"
                ]
              },
              "theContext": "bar"
            },
            "contexts": {
              "theContext": [
                "null"
              ]
            }
          }
        ]
      }
    ]
  }
}
````

### PR DESCRIPTION
**Pull request by jimczi**
The context suggester extracts the context field values from the document but it does not filter doc values field coming from Keyword field.
This change filters doc values field when building the context values.

Fixes #25404

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/suggest/completion/context/CategoryContextMapping.java [hunk 1]
```diff
@@ -138,8 +142,11 @@ protected XContentBuilder toInnerXContent(XContentBuilder builder, Params params
             for (IndexableField field : fields) {
                 if (field.fieldType() instanceof KeywordFieldMapper.KeywordFieldType) {
                     values.add(field.binaryValue().utf8ToString());
-                } else {
+                } else if (field.fieldType() instanceof StringFieldType) {
                     values.add(field.stringValue());
+                } else {
+                    // ignore doc_values field
+                    assert field.fieldType() instanceof SortedDocValuesField || field.fieldType() instanceof SortedSetDocValuesField;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/suggest/completion/context/CategoryContextMapping.java]: Can we make it a real exception? As well as fail if none of the fields provided a value so that we fail on numeric fields, or unindexed keyword fields?

**Review by jpountz — COMMENTED** [review]
Your change makes things a bit better, but we do not seem to validate the field that is used in the context mappings so there could be other corner cases like numeric fields or unindexed keyword fields that we should handle? Ideally we'd need to validate this when the mapping is put but it does not seem easy.

**Comment by jimczi** [comment]
@jpountz I pushed a change to address your comment. Indexation now fails if the context field is not a `keyword` or a `text` field. I did not address the case where the field is not indexed, if we want to also check this it would be better to have a validate method on the FieldMapper directly ?

**Review by jpountz — APPROVED** [review]

**Comment by jpountz** [comment]
I agree it would be best this way. I'm a bit unhappy that it is the only field that has such a dependency on other fields though, as it would require to add an additional method to perform the validation while the mappings API is already bloated. When I think about it, it's also a bit broken to require the field to be indexed when we only need to know the value of the field at index-time?
