### PR TITLE
Discard intermediate results upon cancellation for stats endpoints

### LINKED ISSUE #82337: Stats actions should discard intermediate state on cancellation
Most stats actions fan out to various nodes in the cluster and collect per-node responses which are then aggregated into the final result. The per-node responses may sometimes be many MBs in size. If the client cancels the request by closing its connection then we broadcast the cancellation to all the target nodes and wait for them to respond with a `TaskCancelledException` before discarding the intermediate results. It's possible for one of the target nodes to take many minutes to respond to the cancellation if, for instance, it is overwhelmed by GC activity. In that case we retain many MBs of unnecessary intermediate state for many minutes.

We should instead react to the cancellation by immediately discarding the intermediate results and dropping any further results that arrive to free up this unnecessary memory usage. One possible way to do this would be to allow a `CancellableTask` to accumulate listeners which are completed by `CancellableTask#onCancelled()`.

Relates https://github.com/elastic/elasticsearch/issues/55550#issuecomment-785848328 which contains a list of some of the more important cases of this to address.

### PR DESCRIPTION
**Pull request by gmarouli**
Discard intermediate results when a stats request is cancelled.

Next tasks:

- [x] Discuss approach
- [x] Improve understanding of `_cluster/state` request
- [x] Check completeness, did we cover all the endpoints that cause problems
- [x] Implement tests
- [x] Pass tests

Resolves #82337

### CODE REVIEW

**Comment by gmarouli** [comment]
@elasticsearchmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/part-1

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+
+    /**
+     * This method stores a new node response if it is first response encountered from this node and the intermediate responses haven't
+     * been discarded yet. Checking that this is the first time we have received a response from this node is a defensive mechanism to
+     * protect against the possibility of double invocation.
+     * @param nodeIndex, the index that represents a single node of the cluster
+     * @param response, a response can be either a NodeResponse or an error
+     * @return true if it was successfully stored, else false
+     */
+    public boolean maybeAddResponse(int nodeIndex, Object response) {
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:64]: Outside of tests, there are no uses of the return value of `maybeAddResponse`, but every invocation does immediately call `allNodesResponded()` right after adding the response.

Would it make sense to change the return value for this method to indicate whether all responses have been gathered, so that the add-and-check is done at the same time? I think it's fine either way, so up to you whether you like the idea or not.

**Review by dakrone — APPROVED** [review]
This generally looks good to me, I left an optional comment

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java (hunk 1 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:64]: I have been pondering about that too. My concern was that it makes the code more difficult to read (and name). On the other hand combining them would also eliminate the race condition that two answers could trigger the finalizing step. I will change it.

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java]: Done

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+        return responses == null;
+    }
+
+    /**
+     * This method stores a new node response if it is first response encountered from this node and the intermediate responses haven't
+     * been discarded yet. Checking that this is the first time we have received a response from this node is a defensive mechanism to
+     * protect against the possibility of double invocation.
+     * @param nodeIndex, the index that represents a single node of the cluster
+     * @param response, a response can be either a NodeResponse or an error
+     * @return true if this was the first encounter of the last expected response, else false
```
Comment (dakrone) [inline server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:58]: I think this javadoc is incorrect now that you changed the return value of this function

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:58]: It is adjusted to the new return value of the function. But based on your comment I think it is not very clear. What about:
```suggestion
     * @return true if the response was the last missing response and this was the first time it was encountered, else false
```

File: docs/changelog/82685.yaml [hunk 3]
```diff
@@ -0,0 +1,6 @@
+pr: 82685
+summary: Discard intermediate results upon cancellation for stats endpoints
+area: Stats
+type: bug
+issues:
+ - 82337
```
Comment (gmarouli) [inline docs/changelog/82685.yaml:6]: @dakrone I this change doesn't qualify for the changelog. It feels like an internal change that doesn't change any user facing functionality apart from having less OOM :p.

Comment (DaveCTurner) [reply docs/changelog/82685.yaml:6]: I think it's worth documenting things like this here. Sometimes folks are resistant to upgrading, but if someone is suffering from the problem that this PR fixes then it's helpful to be able to point to the docs to show that an upgrade would fix the problem.

File: server/src/main/java/org/elasticsearch/tasks/CancellableTask.java [hunk 4]
```diff
@@ -67,6 +70,16 @@ public final String getReasonCancelled() {
...
     }
 
+    /**
+     * This method registers a listener that needs to be notified when this task is cancelled given that the task is not cancelled yet.
+     */
+    public final boolean registerListener(CancellationListener listener) {
+        if (isCancelled) {
+            return false;
+        }
+        return listeners.add(listener);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/tasks/CancellableTask.java:80]: I think I would expect registering a listener on a cancelled task to complete the listener straight away, similarly to how things like `CompletableFuture#whenComplete` and `ListenableActionFuture#addListener` work. It's probably ok as it's used here but I worry this will trap a future developer.

It's possible that the task is cancelled after we check the `isCancelled` flag but before the listener is added, which would mean this method returns `true` but the listener is never completed.

File: server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java [hunk 5]
```diff
@@ -417,6 +419,22 @@ protected void onCompletion() {
                 }
             }
         }
+
+        @Override
+        public void onCancelled() {
+            try {
+                if (task instanceof CancellableTask t) {
+                    t.ensureNotCancelled();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java:427]: Could we just check `t.isCancelled()` rather than throwing and immediately catching an exception?

File: server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java [hunk 6]
```diff
@@ -417,6 +419,22 @@ protected void onCompletion() {
...
+                }
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java:428]: Since we're handling a cancellation in this method can we assert that the task is always a `CancellableTask` here?

```suggestion
                } else {
                    assert false : "task must be cancellable";
                }
```

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+/**
+ * This class tracks the intermediate responses that will be used to create aggregated cluster response to a request. It also gives the
+ * possibility to discard the intermediate results when asked, for example when the initial request is cancelled, in order to release the
+ * resources.
+ */
+public class NodeResponseTracker {
+
+    private final AtomicInteger counter = new AtomicInteger();
+    private final AtomicReferenceArray<Boolean> receivedResponseFromNode;
+    private volatile AtomicReferenceArray<Object> responses;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:24]: I think we can rely on responses never being `null` (i.e. we can assert this in `trackResponseAndCheckIfLast`, and reject nulls with a NPE too) so there's no need for a separate array of bools.

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+     * been discarded yet. Checking that this is the first time we have received a response from this node is a defensive mechanism to
+     * protect against the possibility of double invocation.
+     * @param nodeIndex, the index that represents a single node of the cluster
+     * @param response, a response can be either a NodeResponse or an error
+     * @return true if this was the first encounter of the last expected response, else false
+     */
+    public boolean trackResponseAndCheckIfLast(int nodeIndex, Object response) {
+        AtomicReferenceArray<Object> responses = this.responses;
+        boolean firstEncounter = receivedResponseFromNode.compareAndSet(nodeIndex, null, true);
+        if (firstEncounter == false) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:63]: Can we assert that this never happens too? It would be a bug I think.

**Review by DaveCTurner — COMMENTED** [review]
Looks good @gmarouli, I left a handful of small comments.

File: server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java (hunk 6 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java:428]: Oh wait I see, we're keeping hold of the exception for later. Forget I said anything...

File: server/src/main/java/org/elasticsearch/tasks/CancellableTask.java (hunk 4 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTask.java:80]: You are right, the way it's set up now it's error prone. I tried to preemptively end but it's not worth it

File: server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java (hunk 5 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java:427]: The reason I did this was to catch the exception and add it as a cause in the `DiscardedResponsesException`. In the odd case that the responses are discarded but you are already processing the results getting the `DiscardedResponsesException` without a cause is not very helpful. What do you think?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java:427]: ++ yes I realised shortly after writing this that we want to capture the exception for later use, and this is the best way to do that.

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java (hunk 7 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:24]: I added this in order to be able to track which node hasn't responded yet after the responses have been discarded since discarding a response is assigning `null` to the array. Another way I can think of approaching in order to have only one array would be to I introduce something that symbolizes a discarded response and use that. What do you think about that approach?

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java (hunk 8 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:63]: If it would be a bug definitely, I like the assertion much more because it is explicit behavior.

File: docs/changelog/82685.yaml (hunk 3 above)
Comment (gmarouli) [reply docs/changelog/82685.yaml:6]: Good point, I will keep it then.

**Comment by gmarouli** [comment]
@dakrone & @DaveCTurner Thank you very much for your comments!

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java (hunk 7 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:24]: Sorry if I'm missing something here - my thinking is that we could distinguish these things with a single field: `responses == null` means we're discarding results, whereas if `responses != null` then we're still collecting results and we can use `responses.compareAndSet(i, null, response)` to capture the response from node `i` without the risk of double-counting.

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:24]: Oh, no maybe I am missing something here, so I think the discussion is good... 

So, the initial code was only "completing" the listener when all the nodes have responded. If we want to preserve this functionality, we still need to track which nodes haven't responded yet even if we get a cancellation, right? 

If we have `responses == null` we can keep counting the times that the `trackResponseAndCheckIfLast(..)` was called but we cannot detect a double call anymore. Maybe that's an acceptable risk or maybe completing the listener after all nodes have responded wasn't a feature but a result of the way the code was structured. I was a bit conservative changing this because I cannot fully guess all the side effects of such a change. 

Is my concern more clear now?

File: server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java (hunk 6 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java:428]: I like the assertion, I would prefer the assertion to be the first statement in the method and then continue assuming this is a `CancellableTask`. 
**Pros:** I see the assertion as a "guard" of the method that ensures everything is ok before moving forward with the execution. 
**Cons:** We cannot use `instanceof` pattern matching.

If you do not have an objection I will move forward with something like this:
```
            assert task instanceof CancellableTask : "task must be cancellable";
            try {
                ((CancellableTask) task).ensureNotCancelled();
            } catch (TaskCancelledException e) {
                nodeResponseTracker.discardIntermediateResponses(e);
            }
```

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java (hunk 7 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:24]: Ah I see. I think we should ignore the risk of a double-call here given the extra complexity it needs to protect against it and the fact that I don't think it actually happens. IMO it should be safe enough just to assert there are no double-calls before cancellation.

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java:24]: That's wonderful, I also had my doubts so since you also lean towards this, I will document it and clean up the code!

File: server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java (hunk 2 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/NodeResponseTracker.java]: Changed based on the most recent version of the code

File: server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java (hunk 6 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/action/support/broadcast/node/TransportBroadcastByNodeAction.java]: Changed.

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/bwc
