### PR TITLE
Core: Revert back to joda's multi date formatters

### LINKED ISSUE #36602: Rework multi date formatter merging causes a throughput drop for http_logs
https://github.com/elastic/elasticsearch/pull/36447 (merged to master in https://github.com/elastic/elasticsearch/commit/c4f437800680a8858131b5a5e7bb370c41d109a9) has caused a performance regression the [http_logs benchmarks](https://elasticsearch-benchmarks.elastic.co/#tracks/http-logs/nightly/30d) on Dec 12, 2018. The numbers below are for [our nightly benchmarking hardware](https://elasticsearch-benchmarks.elastic.co/#) for a single node with 4GB heap.

* Before: median indexing throughput ~ 197000 docs/s
* After: median indexing throughput ~ 155000 docs/s

**Steps to reproduce**

Run a benchmark with Rally and have a look at indexing throughput (note that this will download a benchmark data set with ~ 1.2GB):

```
esrally --runtime-jdk=8 --car="4gheap" --pipeline=from-sources-complete --revision=c4f437800680a8858131b5a5e7bb370c41d109a9 --track=http_logs --challenge=append-no-conflicts-index-only
```

To get the baseline numbers for comparison, point Rally to the previous commit https://github.com/elastic/elasticsearch/commit/1bb6f844fee92d1c240a124499f0c299c09a1daf:

```
esrally --runtime-jdk=8 --car="4gheap" --pipeline=from-sources-complete --revision=1bb6f844fee92d1c240a124499f0c299c09a1daf --track=http_logs --challenge=append-no-conflicts-index-only
```

Note: If you are using Oracle JDK you can also get a profile by specifying `--telemetry=jfr`.

@rjernst can you please take a look at this one?

### PR DESCRIPTION
**Pull request by rjernst**
This commit partially reverts #36447 by using the ability of Joda time's
DateTimeFormatterBuilder to append multiple parsers instead of using the
MergedDateFormatter. The MergedDateFormatter will be removed in a future
change, as it is not as performant due to creating potentially many
exceptions during heavy date parsing. This change is a stop-gap until
that followup is ready.

closes #36602

### CODE REVIEW

**Comment by spinscale** [comment]
there is also an open issue in 6.x regarding exception handling that needs to be properly handled by this to retain BWC https://github.com/elastic/elasticsearch/issues/36598

File: server/src/main/java/org/elasticsearch/common/time/DateFormatter.java [hunk 1]
```diff
@@ -129,19 +129,17 @@ static DateFormatter forPattern(String input) {
...
             }
-            final DateFormatter formatter;
-            if (pattern.startsWith("8")) {
-                // force java 8 date format
-                formatter = DateFormatters.forPattern(pattern.substring(1));
-            } else {
-                formatter = Joda.forPattern(pattern);
-            }
-            formatters.add(formatter);
+            formatters.add(DateFormatters.forPattern(pattern.substring(1)));
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/time/DateFormatter.java]: this needs a check for each of the pattern if it starts with `8` in order to return the proper joda time pattern for sth like `8date_optional_time||date_optional_time`

**Review by spinscale — CHANGES_REQUESTED** [review]

**Comment by spinscale** [comment]
my suggestion to fix is this one https://github.com/spinscale/elasticsearch/commit/6b7b130b4fd5686ea3df05131f9b37b94edf33d3 (there is one last case not covered yet, namely `foo||8foo` though)

File: server/src/main/java/org/elasticsearch/common/time/DateFormatter.java (hunk 1 above)
Comment (rjernst) [reply server/src/main/java/org/elasticsearch/common/time/DateFormatter.java]: Oops, this is leftover. We won't be able to have mixed joda/java formats, so I think only having `8` as the very first character is sufficient (otherwise it would be redundant). I'll move the substring to outside the loop.

**Review by spinscale — APPROVED** [review]
