### PR TITLE
Fix SearchStatesIT.testCanMatch

### LINKED ISSUE #118718: [CI] SearchStatesIT testCanMatch failing
**Build Scans:**
- [elasticsearch-periodic #5755 / 8.2.3_bwc](https://gradle-enterprise.elastic.co/s/a7d4g3is4rwqq)
- [elasticsearch-periodic #5755 / 8.1.3_bwc](https://gradle-enterprise.elastic.co/s/ovelx2boqm4ba)
- [elasticsearch-periodic #5755 / 8.5.3_bwc](https://gradle-enterprise.elastic.co/s/27mvo7hovprjo)
- [elasticsearch-pull-request #49316 / 8.8.2_bwc](https://gradle-enterprise.elastic.co/s/2qnhit62azwe2)
- [elasticsearch-pull-request #49316 / 8.2.3_bwc](https://gradle-enterprise.elastic.co/s/vdpnrttieltsa)
- [elasticsearch-periodic #5750 / 8.15.5_bwc](https://gradle-enterprise.elastic.co/s/tw3ukt6apt5iu)
- [elasticsearch-periodic #5745 / 8.4.3_bwc](https://gradle-enterprise.elastic.co/s/kk7u7umb3yoas)

**Reproduction Line:**
```
./gradlew ":qa:ccs-rolling-upgrade-remote-cluster:v8.2.3#oneThirdUpgraded" -Dtests.class="org.elasticsearch.upgrades.SearchStatesIT" -Dtests.method="testCanMatch" -Dtests.seed=2D13B0A4E68E7C82 -Dtests.bwc=true -Dtests.locale=ksf -Dtests.timezone=America/Toronto -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.SearchStatesIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCanMatch),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a collection with size <3>
     but: collection size was <2>
```

**Issue Reasons:**
- [8.x] 7 failures in test testCanMatch (0.7% fail rate in 1000 executions)
- [8.x] 2 failures in step 8.2.3_bwc (50.0% fail rate in 4 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic (100.0% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by original-brownbear**
Adding back the old style free request to fix CCS BwC situations where we need to proxy requests exactly as is and can't drop the technically redundant original indices.

closes #118718

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/search/SearchTransportService.java [hunk 1]
```diff
@@ -400,14 +400,31 @@ public static void registerRequestHandler(TransportService transportService, Sea
...
             var res = new ScrollFreeContextRequest(in);
             // this handler exists for BwC purposes only, we don't need the original indices to free the context
             OriginalIndices.readOriginalIndices(in);
             return res;
         }, freeContextHandler);
-        TransportActionProxy.registerProxyAction(transportService, FREE_CONTEXT_ACTION_NAME, false, SearchFreeContextResponse::readFrom);
-
+        // BwC handler that translates FREE_CONTEXT_ACTION_NAME into FREE_CONTEXT_SCROLL_ACTION_NAME same way we use
+        // FREE_CONTEXT_SCROLL_ACTION_NAME throughout on local nodes
+        transportService.registerRequestHandler(
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/search/SearchTransportService.java:412]: I'm not too proud of exposing this infrastructure just for a one-off fix to be honest. But then again, hiding it behind some utility method and adding a single-use abstraction for the action-to-action translation seemed even worse. This solution is the minimum amount of code needed as far as I can tell which is quite helpful.

**Review by andreidan — APPROVED** [review]
LGTM, thanks for iterating on this Armin 

Just a note - we'll forward port this to main as well.

**Comment by original-brownbear** [comment]
Thanks Andrei!
