### PR TITLE
Correctly handle ScriptScoreQuery in plain highlighter

### LINKED ISSUE #99700: Plain highlighter throws UOE when using a script_score query wrapping an exists query
### Elasticsearch Version

8.10

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

unix

### Problem Description

If you try and highlight a `script_score` query that further wraps an `exists` query using the `plain` highlighter, you get a stack trace that looks like this:
```
Caused by: java.lang.UnsupportedOperationException
	at org.apache.lucene.search.highlight.WeightedSpanTermExtractor$DelegatingLeafReader.getFieldInfos(WeightedSpanTermExtractor.java:463) ~[lucene-highlighter-9.6.0.jar:?]
	at org.apache.lucene.search.FieldExistsQuery.rewrite(FieldExistsQuery.java:116) ~[lucene-core-9.6.0.jar:?]
	at org.apache.lucene.search.ConstantScoreQuery.rewrite(ConstantScoreQuery.java:44) ~[lucene-core-9.6.0.jar:?]
	at org.apache.lucene.search.ConstantScoreQuery.rewrite(ConstantScoreQuery.java:44) ~[lucene-core-9.6.0.jar:?]
	at org.apache.lucene.search.BooleanQuery.rewrite(BooleanQuery.java:289) ~[lucene-core-9.6.0.jar:?]
	at org.elasticsearch.common.lucene.search.function.ScriptScoreQuery.rewrite(ScriptScoreQuery.java:73) ~[elasticsearch-8.8.2.jar:?]
	at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.extract(WeightedSpanTermExtractor.java:253) ~[lucene-highlighter-9.6.0.jar:?]
	at org.elasticsearch.search.fetch.subphase.highlight.CustomQueryScorer$CustomWeightedSpanTermExtractor.extract(CustomQueryScorer.java:77) ~[elasticsearch-8.8.2.jar:?]
	at org.apache.lucene.search.highlight.WeightedSpanTermExtractor.getWeightedSpanTerms(WeightedSpanTermExtractor.java:533) ~[lucene-highlighter-9.6.0.jar:?]
	at org.apache.lucene.search.highlight.QueryScorer.initExtractor(QueryScorer.java:209) ~[lucene-highlighter-9.6.0.jar:?]
	at org.apache.lucene.search.highlight.QueryScorer.init(QueryScorer.java:178) ~[lucene-highlighter-9.6.0.jar:?]
	at org.apache.lucene.search.highlight.Highlighter.getBestTextFragments(Highlighter.java:173) ~[lucene-highlighter-9.6.0.jar:?]
	at org.elasticsearch.search.fetch.subphase.highlight.PlainHighlighter.highlight(PlainHighlighter.java:151) ~[elasticsearch-8.8.2.jar:?]
	at org.elasticsearch.search.fetch.subphase.highlight.HighlightPhase$1.process(HighlightPhase.java:69) ~[elasticsearch-8.8.2.jar:?]

```

Related to #92919, but as `ScriptScoreQuery` is an elasticsearch query we need to extend `CustomWeightedSpanTermExtractor` to be aware of it.

### Steps to Reproduce

```
POST script-score/_doc
{
  "text": "some text"
}

GET script-score/_search
{
  "query": {
    "script_score": {
      "script": {
        "source": "_score + 1"
      },
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "text": "some"
              }
            },
            {
              "exists": { "field": "text" }
            }
          ]
        }
      }
    }
  },
  "highlight": {
    "type": "plain",
    "fields": {
      "*": {}
    }
  }
}
```

Returns

```
{
  "error": {
    "root_cause": [
      {
        "type": "unsupported_operation_exception",
        "reason": "unsupported_operation_exception: null"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "script-score",
        "node": "TpI_NouPS1eIgeB4zNzGkg",
        "reason": {
          "type": "unsupported_operation_exception",
          "reason": "unsupported_operation_exception: null"
        }
      }
    ]
  },
  "status": 500
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by romseygeek**
ScriptScoreQuery is an elasticsearch query implementation that the plain
highlighter doesn't know anything about.  To highlight it correctly, we need
to add some custom handling logic in our CustomQueryScorer.

Fixes #99700

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/query/SearchExecutionContext.java [hunk 1]
```diff
@@ -110,7 +110,7 @@ public SearchExecutionContext(
         MapperService mapperService,
         MappingLookup mappingLookup,
         SimilarityService similarityService,
-        ScriptService scriptService,
+        ScriptCompiler scriptService,
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/query/SearchExecutionContext.java:113]: Note that these changes (replacing a reference to the concrete ScriptService class with one to its ScriptCompiler interface instead) make using scripts in tests a lot easier.

**Comment by romseygeek** [comment]
There are almost certainly other places where we are using a `ScriptService` when we could quite happily be using a `ScriptCompiler`, and replacing things there would probably simplify a whole bunch of tests.

**Review by javanna — APPROVED** [review]
LGTM
