### PR TITLE
[Inference API] Replace ElasticsearchTimeoutException with ElasticsearchStatusException

### LINKED ISSUE #112828: Inference request task timeout should not be 503
Timeouts on the inference service should not result in a 503. The rest suppressed logger reported this. 

Interestingly the timeout is 10s, while the default is not 30s ? 

```
"error.stack_trace": "org.elasticsearch.ElasticsearchTimeoutException: Request timed out waiting to be sent after [10s]
  at org.elasticsearch.inference@8.16.0/org.elasticsearch.xpack.inference.external.http.sender.RequestTask.lambda$getListener$2(RequestTask.java:67)
 at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.ListenerTimeouts$TimeoutableListener.run(ListenerTimeouts.java:102)
 at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:924)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
 at java.base/java.lang.Thread.run(Thread.java:1570)\n",
```

### PR DESCRIPTION
**Pull request by maxhniebergall**
... with 408 status to avoid causing 503s.

Closes https://github.com/elastic/elasticsearch/issues/112828#issuecomment-2539408805

### CODE REVIEW

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/RequestTask.java [hunk 1]
```diff
@@ -64,7 +65,10 @@ private ActionListener<InferenceServiceResults> getListener(
             threadPool.executor(UTILITY_THREAD_POOL_NAME),
             notificationListener,
             (ignored) -> notificationListener.onFailure(
-                new ElasticsearchTimeoutException(Strings.format("Request timed out waiting to be sent after [%s]", timeout))
+                new ElasticsearchStatusException(
+                    Strings.format("Request timed out waiting to be sent after [%s]", timeout),
+                    RestStatus.REQUEST_TIMEOUT
+                )
```
Comment (benwtrent) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/http/sender/RequestTask.java:71]: ❤️

**Review by benwtrent — APPROVED** [review]
:shipit:  ;)

**Review by jonathan-buttner — APPROVED** [review]

**Review by tteofili — APPROVED** [review]
