### PR TITLE
Fix ArrayIndexOutOfBoundsException when no ranges are specified in the query

### LINKED ISSUE #22881: Range aggregation with no ranges throw a NullPointerException
**Elasticsearch version**:  5.1.1

**Plugins installed**: [analysis-icu]

**JVM version**: Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111-internal/25.111-b14

**OS version**: Linux/4.8.0-34-generic/amd64

**Description of the problem including expected versus actual behavior**: 

A NullPointerException is displayed to the user when the Range aggregation is malformed:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
```

**Steps to reproduce**:

 1. Run a badly formatted query:

```json
GET /_search
{
  "aggs": {
    "foobar": {
      "range": {
        "field": "hey"
      }
    }
  }
}
```

**Provide logs (if relevant)**:

Trace:

```
[2017-01-31T10:49:11,250][WARN ][r.suppressed             ] path: /_search, params: {}
java.lang.NullPointerException: null
	at org.elasticsearch.search.aggregations.bucket.range.RangeParser.createFactory(RangeParser.java:58) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.aggregations.bucket.range.RangeParser.createFactory(RangeParser.java:39) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.aggregations.support.AbstractValuesSourceParser.parse(AbstractValuesSourceParser.java:150) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.aggregations.support.AbstractValuesSourceParser$NumericValuesSourceParser.parse(AbstractValuesSourceParser.java:48) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:156) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:80) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.builder.SearchSourceBuilder.parseXContent(SearchSourceBuilder.java:1018) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.action.search.RestSearchAction.parseSearchRequest(RestSearchAction.java:105) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.action.search.RestSearchAction.prepareRequest(RestSearchAction.java:81) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:66) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:243) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:200) [elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:113) [elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:507) [transport-netty4-5.1.1.jar:5.1.1]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:69) [transport-netty4-5.1.1.jar:5.1.1]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:66) [transport-netty4-5.1.1.jar:5.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:536) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:490) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.6.Final.jar:4.1.6.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
```

### PR DESCRIPTION
**Pull request by giorgosp**
The issue is reproduced in 5.1, 5.2, 5.3, 5.x and master branch. My fix is on master.

This commit just checks the ranges array size at the spot where the exception is raised. I am not sure if this should be fixed at a higher level in the code.

Closes #22881

### CODE REVIEW

**Comment by javanna** [comment]
Hi @giorgosp congrats on your first PR ;)

I was wondering, in the linked issue an NPE is mentioned, while in the title of this PR you mentioned an array index out of bounds exception. Are these two different bugs or the same one? Also, wouldn't it make sense to throw an error if no ranges are specified? @colings86 what do you think?

**Comment by colings86** [comment]
I agree that we should throw an exception if no ranges are specified. We could actually check for that in the RangeAggregationBuilder so we fail early and on the coordinating node in this case.

**Comment by giorgosp** [comment]
Hello guys, thanks for the feedback!

It is a NullPointerException in the 5.1 branch while in the others (5.2, 5.x, master) it is an ArrayIndexOutOfBoundsException and is thrown only if there is at least one doc indexed.

Indeed, returning an error in the response makes more sense. 

Also, I am noticing that the same error will happen to all aggregations that use `RangeAggregator`. Maybe I should raise an IllegalStateException inside `RangeAggregator`'s constructor instead of inside each one of `**Builder.innerBuild()` methods?

**Comment by javanna** [comment]
Hi @giorgosp we would prefer to fail early in the coordinating node, rather than later in each shard, hence it would be better to add validation to each builder that has this problem. Thanks!

**Comment by giorgosp** [comment]
Hi @javanna, please check the last commit (I will rebase all the commits when review is ok).

I am making the check inside the parse() method of the RangeAggregationBuilder.  But there is an issue with this approach, I cannot create an integration test because it seems that integration tests do not rely on any "parse" methods. 
Consequently, an  integration test (see https://github.com/elastic/elasticsearch/pull/23241/commits/ad57d8feb3577a64b37de28c6f3df96a3a49fe93#diff-369471927f6eb5e2ebfdf58649078d26)  will still raise the old exception.

I could manually call the builder's parse method from inside the integration test but this won't seem like an integration test anymore.

**Comment by javanna** [comment]
@colings86 do you mind having a look please?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/range/date/DateRangeAggregationBuilder.java [hunk 1]
```diff
@@ -283,7 +288,7 @@ public DateRangeAggregationBuilder addUnboundedFrom(DateTime from) {
     @Override
     protected DateRangeAggregatorFactory innerBuild(SearchContext context, ValuesSourceConfig<Numeric> config,
             AggregatorFactory<?> parent, Builder subFactoriesBuilder) throws IOException {
-        // We need to call processRanges here so they are parsed and we know whether `now` has been used before we make 
+        // We need to call processRanges here so they are parsed and we know whether `now` has been used before we make
         // the decision of whether to cache the request
         Range[] ranges = processRanges(context, config);
```
Comment (colings86) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/range/date/DateRangeAggregationBuilder.java]: Could we put the check here so that it is run for both the transport and rest APIs? When put here we should make it an `IllegalArgumentException` and we should update the other Range Aggregation Builders too.

**Review by colings86 — CHANGES_REQUESTED** [review]
Thanks for making the changes, I left a comment in the code, but also could we do this for the `IpRangeAggregationBuilder` and the `GeoDistanceAggregationBuilder` too?

It would also be good to add a test method which checks the exception is thrown when no ranges are given.

**Comment by giorgosp** [comment]
Hi @colings86, I have updated the code according to your comments. I am willing to make further changes if necessary. If it's fine, I will squash the commits and rebase the branch on master. Thanks!

**Comment by colings86** [comment]
jenkins test this

**Review by colings86 — APPROVED** [review]
LGTM. Thanks for contributing this change. I'll squash and merge this change and backport to the 5.x and 5.4 branches

**Comment by giorgosp** [comment]
Ok, thanks!
