### PR TITLE
[Test] Fix SnapshotShutdownIT

### LINKED ISSUE #140755: [CI] SnapshotShutdownIT testRemoveNodeDuringSnapshotWithOtherRunningShardSnapshots failing
**Build Scans:**
- [elasticsearch-intake #33327 / part1](https://gradle-enterprise.elastic.co/s/mpp5wlt76lppa)
- [elasticsearch-pull-request #114629 / part-1](https://gradle-enterprise.elastic.co/s/gqrhp3n7hhsu4)
- [elasticsearch-pull-request #114627 / part-1](https://gradle-enterprise.elastic.co/s/gi27wx3ukrt2y)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.SnapshotShutdownIT.testRemoveNodeDuringSnapshotWithOtherRunningShardSnapshots" -Dtests.seed=EED67C487E4F5788 -Dtests.locale=ar-LB -Dtests.timezone=America/Santarem -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.snapshots.SnapshotShutdownIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRemoveNodeDuringSnapshotWithOtherRunningShardSnapshots'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
```

**Issue Reasons:**
- [main] 3 failures in test testRemoveNodeDuringSnapshotWithOtherRunningShardSnapshots (1.2% fail rate in 243 executions)
- [main] 2 failures in step part-1 (1.2% fail rate in 169 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.2% fail rate in 165 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #140760: [CI] SnapshotShutdownIT testAbortSnapshotWhileRemovingNode failing
**Build Scans:**
- [elasticsearch-pull-request #114651 / part-1](https://gradle-enterprise.elastic.co/s/5pmqgrxnrtack)
- [elasticsearch-intake #33328 / part1](https://gradle-enterprise.elastic.co/s/werpy3wla4hp2)
- [elasticsearch-pull-request #114642 / part-1](https://gradle-enterprise.elastic.co/s/x5gf3m5yw73z2)
- [elasticsearch-pull-request #114646 / part-1](https://gradle-enterprise.elastic.co/s/2aywdhf63vp52)
- [elasticsearch-pull-request #114627 / part-1](https://gradle-enterprise.elastic.co/s/gi27wx3ukrt2y)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.SnapshotShutdownIT.testStartRemoveNodeButDoNotComplete" -Dtests.seed=DFF884C34003980E -Dtests.locale=en-ER -Dtests.timezone=Etc/Zulu -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.snapshots.SnapshotShutdownIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAbortSnapshotWhileRemovingNode'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
```

**Issue Reasons:**
- [main] 5 failures in test testAbortSnapshotWhileRemovingNode (2.0% fail rate in 254 executions)
- [main] 4 failures in step part-1 (2.3% fail rate in 177 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (2.3% fail rate in 173 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #140761: [CI] SnapshotShutdownIT testShutdownWhileSuccessInFlight failing
**Build Scans:**
- [elasticsearch-intake #33335 / part1](https://gradle-enterprise.elastic.co/s/vpq5irtpkwrbk)
- [elasticsearch-pull-request #114642 / part-1](https://gradle-enterprise.elastic.co/s/vgareah3d5ize)
- [elasticsearch-pull-request #114669 / part-1](https://gradle-enterprise.elastic.co/s/jivhgwphd47q6)
- [elasticsearch-intake #33331 / part1](https://gradle-enterprise.elastic.co/s/pnjdhbzfwxl7s)
- [elasticsearch-pull-request #114650 / part-1](https://gradle-enterprise.elastic.co/s/eajb3wkw7hz2i)
- [elasticsearch-intake #33328 / part1](https://gradle-enterprise.elastic.co/s/werpy3wla4hp2)
- [elasticsearch-pull-request #114642 / part-1](https://gradle-enterprise.elastic.co/s/x5gf3m5yw73z2)
- [elasticsearch-pull-request #114627 / part-1](https://gradle-enterprise.elastic.co/s/gi27wx3ukrt2y)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.SnapshotShutdownIT.testRestartNodeDuringSnapshot" -Dtests.seed=3CC65E71BDFC684B -Dtests.locale=ti-Ethi-ET -Dtests.timezone=Indian/Mahe -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.snapshots.SnapshotShutdownIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testShutdownWhileSuccessInFlight'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
```

**Issue Reasons:**
- [main] 8 failures in test testShutdownWhileSuccessInFlight (3.0% fail rate in 271 executions)
- [main] 5 failures in step part-1 (2.7% fail rate in 186 executions)
- [main] 3 failures in step part1 (7.3% fail rate in 41 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (2.2% fail rate in 180 executions)
- [main] 3 failures in pipeline elasticsearch-intake (7.3% fail rate in 41 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #140762: [CI] SnapshotShutdownIT testSnapshotShutdownProgressTracker failing
**Build Scans:**
- [elasticsearch-pull-request #114650 / part-1](https://gradle-enterprise.elastic.co/s/eajb3wkw7hz2i)
- [elasticsearch-pull-request #114645 / part-1](https://gradle-enterprise.elastic.co/s/lhjj3x3efqfa2)
- [elasticsearch-intake #33328 / part1](https://gradle-enterprise.elastic.co/s/werpy3wla4hp2)
- [elasticsearch-pull-request #114646 / part-1](https://gradle-enterprise.elastic.co/s/2aywdhf63vp52)
- [elasticsearch-intake #33325 / part1](https://gradle-enterprise.elastic.co/s/kf72wlpggwo7w)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.SnapshotShutdownIT.testStartRemoveNodeButDoNotComplete" -Dtests.seed=DFF884C34003980E -Dtests.locale=en-ER -Dtests.timezone=Etc/Zulu -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.snapshots.SnapshotShutdownIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSnapshotShutdownProgressTracker'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
```

**Issue Reasons:**
- [main] 5 failures in test testSnapshotShutdownProgressTracker (2.0% fail rate in 254 executions)
- [main] 3 failures in step part-1 (1.7% fail rate in 177 executions)
- [main] 2 failures in step part1 (5.3% fail rate in 38 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (1.7% fail rate in 173 executions)
- [main] 2 failures in pipeline elasticsearch-intake (5.3% fail rate in 38 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #140765: [CI] SnapshotShutdownIT testRestartNodeDuringSnapshot failing
**Build Scans:**
- [elasticsearch-intake #33332 / part1](https://gradle-enterprise.elastic.co/s/nhei7ubbtw3iy)
- [elasticsearch-pull-request #114642 / part-1](https://gradle-enterprise.elastic.co/s/vgareah3d5ize)
- [elasticsearch-pull-request #114666 / part-1](https://gradle-enterprise.elastic.co/s/ov7xlmpuumndw)
- [elasticsearch-intake #33323 / part1](https://gradle-enterprise.elastic.co/s/kcu4wz3nc6syi)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.SnapshotShutdownIT.testSnapshotShutdownProgressTracker" -Dtests.seed=910E3190F95EE1D1 -Dtests.locale=hr -Dtests.timezone=Asia/Qyzylorda -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.snapshots.SnapshotShutdownIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRestartNodeDuringSnapshot'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchTimeoutException: java.util.concurrent.TimeoutException: Timeout waiting for task.
```

**Issue Reasons:**
- [main] 4 failures in test testRestartNodeDuringSnapshot (1.5% fail rate in 262 executions)
- [main] 2 failures in step part1 (4.9% fail rate in 41 executions)
- [main] 2 failures in step part-1 (1.1% fail rate in 181 executions)
- [main] 2 failures in pipeline elasticsearch-intake (4.9% fail rate in 41 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.1% fail rate in 176 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
Clear shutdown metadata after tests so that it does not interfere with following tests. 

At beginning of each test, the test cluster is reset back to its original size. Therefore node names can be resued between tests if they manually start nodes. When a test adds shutdown metadata for its manually started node, it must be cleared at the end of the test. Otherwise, the subsequent test can start a node with the same name which is still shutting down and cannot accept shards which leads to create index timeout.  

Resolves: #140753
Resolves: #140755
Resolves: #140759
Resolves: #140760
Resolves: #140761
Resolves: #140762
Resolves: #140764
Resolves: #140765

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java [hunk 1]
```diff
@@ -765,8 +767,10 @@ public void testStatefulNodesThatDoNotContainDataDoesNotLogSnapshotShuttingDownP
                 Level.INFO,
                 "Shard snapshot completion stats since shutdown began*"
             );
-        snapshotShutdownProgressTrackerToNotRunExpectation.awaitMatched(1000);
+        mockLog.addExpectation(snapshotShutdownProgressTrackerToNotRunExpectation);
```
Comment (ywangd) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java:770]: The negative matches were not actually registered, so effectively noop. I fix it here by registering first and also calling `awaitMatched` after the nodes have been started. The same fix is applied to the other negative match as well.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java [hunk 2]
```diff
@@ -779,37 +783,45 @@ public void testStatefulNodesThatDoNotContainDataDoesNotLogSnapshotShuttingDownP
             );
 
             // Put shutdown metadata to trigger shutdown progress tracker
-            final ClusterService clusterService = internalCluster().getCurrentMasterNodeInstance(ClusterService.class);
             putShutdownForRemovalMetadata(nodeName, clusterService);
         }
+        ensureStableCluster(originalSize + nodeRoleCombinationsToTest.size());
```
Comment (ywangd) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java:788]: Wait for all the nodes to join the cluster. Otherwise the negative logging assertion can trivially pass since the nodes has not fully started yet.

**Review by joshua-adams-1 — APPROVED** [review]
LGTM! Thank you @ywangd  for doing this!
