### PR TITLE
Handle scheduler shutdown in `MasterService`

### LINKED ISSUE #105549: [CI] org.elasticsearch.cluster.service.MasterService.BatchingTaskQueue#submitTask throws unexpected EsRejectedExecutionException
Probably doesn't reproduce directly but the problem is clear from the stack trace.

**Build scan:**
https://gradle-enterprise.elastic.co/s/uqld27x6h52bo/tests/:x-pack:plugin:downsample:internalClusterTest/org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT/testDataStreamLifecycleDownsampleRollingRestart

**Reproduction line:**
```
./gradlew ':x-pack:plugin:downsample:internalClusterTest' --tests "org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT.testDataStreamLifecycleDownsampleRollingRestart" -Dtests.seed=4FFA60CD48D62773 -Dtests.locale=ar-KW -Dtests.timezone=America/Bahia -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT#testDataStreamLifecycleDownsampleRollingRestart`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testDataStreamLifecycleDownsampleRollingRestart'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.downsample.DataStreamLifecycleDownsampleDisruptionIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4d620954[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@1278403[Wrapped task = [threaded] master service timeout handler for [cluster_health (wait_for_events [LANGUID])][org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction$2@43ab3e6d] after [30s]]] on org.elasticsearch.threadpool.Scheduler$SafeScheduledThreadPoolExecutor@78f3f09c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 156] (shutdown)

  at __randomizedtesting.SeedInfo.seed([4FFA60CD48D62773:9863F77D1EDBC23D]:0)
  at org.elasticsearch.common.util.concurrent.EsRejectedExecutionHandler.newRejectedException(EsRejectedExecutionHandler.java:51)
  at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:35)
  at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
  at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340)
  at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
  at org.elasticsearch.threadpool.ThreadPool.schedule(ThreadPool.java:576)
  at org.elasticsearch.cluster.service.MasterService$BatchingTaskQueue.submitTask(MasterService.java:1525)
  at org.elasticsearch.cluster.service.MasterService.submitUnbatchedStateUpdateTask(MasterService.java:537)
  at org.elasticsearch.cluster.service.ClusterService.submitUnbatchedStateUpdateTask(ClusterService.java:229)
  at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction.submitUnbatchedTask(TransportClusterHealthAction.java:221)
  at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction.waitForEventsAndExecuteHealth(TransportClusterHealthAction.java:162)
  at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction.masterOperation(TransportClusterHealthAction.java:101)
  at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction.masterOperation(TransportClusterHealthAction.java:49)
  at org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:125)
  at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:236)
  at org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:95)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today if `ThreadPool#scheduler` is shut down while submitting a task for
execution by the `MasterService` then we directly throw the rejection
exception to the caller. By the looks of it most callers don't expect
this method to throw anything, so this commit adjusts the behaviour to
fail the task instead.

Closes #105549

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/service/MasterService.java [hunk 1]
```diff
@@ -1522,11 +1522,24 @@ public void submitTask(String source, T task, @Nullable TimeValue timeout) {
...
-                    timeout,
-                    threadPool.generic()
-                );
+                try {
+                    timeoutCancellable = threadPool.schedule(
+                        new TaskTimeoutHandler<>(timeout, source, taskHolder),
+                        timeout,
+                        threadPool.generic()
+                    );
+                } catch (Exception e) {
```
Comment (idegtiarenko) [inline server/src/main/java/org/elasticsearch/cluster/service/MasterService.java:1531]: Should it be more specific and only catch rejection?

**Review by idegtiarenko — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/cluster/service/MasterService.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/cluster/service/MasterService.java:1531]: I think it can only be a rejection, but there's no good reason to let anything else escape here. I added an assertion in 01e4c816cf3.

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java [hunk 2]
```diff
@@ -971,7 +972,17 @@ private ClusterHealthStatus ensureColor(
...
+        try {
+            clusterHealthResponse = clusterAdmin().health(healthRequest).get();
+        } catch (InterruptedException e) {
+            Thread.currentThread().interrupt();
+            logger.error("interrupted while waiting for health response", e);
+            throw new AssertionError("interrupted while waiting for health response", e);
+        } catch (ExecutionException e) {
+            logger.error("failed to get health response", e);
+            throw new AssertionError("failed to get health response", e);
+        }
```
Comment (DiannaHohensee) [inline test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:985]: Why did you need this change for your patch? Trying to connect the dots 🤔

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java [hunk 3]
```diff
@@ -2121,6 +2121,56 @@ public void onFailure(Exception e) {
         }
     }
 
+    public void testTimeoutRejectionBehaviourAtSubmission() {
+
+        final var actionCount = new AtomicInteger();
+
+        final var deterministicTaskQueue = new DeterministicTaskQueue();
+        final var threadPool = deterministicTaskQueue.getThreadPool(r -> {
+            if (r.toString().startsWith("master service timeout handler for [batched][test task]")) {
```
Comment (DiannaHohensee) [inline server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2130]: Not in this patch, but should we have something like `String AbstractRunnable#identifyTask()` that returns unique(-ish) identifiers for a `Runnable`, so we don't have to do things like `toString` matching?

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java [hunk 4]
```diff
@@ -2121,6 +2121,56 @@ public void onFailure(Exception e) {
...
+                return r;
+            }
+        });
+
+        try (var masterService = createMasterService(true, null, threadPool, new StoppableExecutorServiceWrapper(threadPool.generic()))) {
+
+            class TestTask implements ClusterStateTaskListener {
+                @Override
+                public void onFailure(Exception e) {
+                    if ((e instanceof FailedToCommitClusterStateException
```
Comment (DiannaHohensee) [inline server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2143]: "Only count errors that exactly match the failure we inject above. Any others are unexpected."

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java [hunk 5]
```diff
@@ -2121,6 +2121,56 @@ public void onFailure(Exception e) {
         }
     }
 
+    public void testTimeoutRejectionBehaviourAtSubmission() {
+
+        final var actionCount = new AtomicInteger();
+
+        final var deterministicTaskQueue = new DeterministicTaskQueue();
+        final var threadPool = deterministicTaskQueue.getThreadPool(r -> {
```
Comment (DiannaHohensee) [inline server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2129]: So this is setting up the DeterministicTaskQueue's ThreadPool to execute this code before any Runnable? Could we have a comment about what this is doing? Maybe something like,

"The MasterService wraps update tasks in TaskTimeoutHandlers. Set up the thread pool to check for TaskTimeoutHandler Runnables, and artificially inject an error, but otherwise allow anything else to run as normal."

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java [hunk 6]
```diff
@@ -2121,6 +2121,56 @@ public void onFailure(Exception e) {
...
+                actionCount.incrementAndGet();
+                throw new EsRejectedExecutionException("simulated rejection", true);
+            } else {
+                return r;
+            }
+        });
+
+        try (var masterService = createMasterService(true, null, threadPool, new StoppableExecutorServiceWrapper(threadPool.generic()))) {
+
+            class TestTask implements ClusterStateTaskListener {
```
Comment (DiannaHohensee) [inline server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2140]: A descriptive name?

TestTask => ClusterStateTaskThatCountsSimulatedErrors

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java [hunk 7]
```diff
@@ -2121,6 +2121,56 @@ public void onFailure(Exception e) {
...
+                randomFrom(Priority.values()),
+                batchExecutionContext -> fail(null, "should not execute batch")
+            );
+
+            try (var ignored = threadPool.getThreadContext().stashContext()) {
+                queue.submitTask("batched", new TestTask(), TimeValue.timeValueMillis(between(0, 100000)));
+            }
+            assertFalse(deterministicTaskQueue.hasRunnableTasks());
+            assertFalse(deterministicTaskQueue.hasDeferredTasks());
+            assertEquals(2, actionCount.get());
```
Comment (DiannaHohensee) [inline server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2170]: Where does 2 come from?

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java [hunk 8]
```diff
@@ -2121,6 +2121,56 @@ public void onFailure(Exception e) {
...
+                }
+            }
+
+            final var queue = masterService.createTaskQueue(
+                "queue",
+                randomFrom(Priority.values()),
+                batchExecutionContext -> fail(null, "should not execute batch")
+            );
+
+            try (var ignored = threadPool.getThreadContext().stashContext()) {
```
Comment (DiannaHohensee) [inline server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2165]: What is this stashing about?

**Review by DiannaHohensee — COMMENTED** [review]
Comment/name recommendations after figuring out (I think?) how the test works, and a few questions I didn't sort out :)

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 2 above)
Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:985]: Sorry should have said - the stack trace in https://github.com/elastic/elasticsearch/issues/105549 is kinda useless because it uses `actionGet()` which strips off the outer `ExecutionException` so you can't see who is treating this exception as a test failure.

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2130]: That's kinda what `toString()` is for. It's just that the automatically generated unique identifier is kinda useless.

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 4 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2143]: Is that a note-to-self or a suggested comment? :)

Comment (DiannaHohensee) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2143]: Ha, sorry: suggested comment

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 6 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2140]: Actually we can just inline this, this was more useful in the test from which I copied it. Simplest to just have the implementation right there rather than indirect via a name

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 5 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2129]: sure, is 5eb4d290cb364682b08a9154804dfbcaf4e3761e ok?

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 7 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java]: Added a little more commentary in 5eb4d290cb364682b08a9154804dfbcaf4e3761e

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 8 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java]: Oh sorry leftover from previous test case too, now gone

File: test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java (hunk 2 above)
Comment (DiannaHohensee) [reply test/framework/src/main/java/org/elasticsearch/test/ESIntegTestCase.java:985]: Ahh, tricky 😌 Thanks for explaining.

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 3 above)
Comment (DiannaHohensee) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2131]: I was thinking something that didn't involve string parsing -- toString seems geared towards log messages, not equality checks.

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 6 above)
Comment (DiannaHohensee) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java]: A good name can be very informative :) But that works, too 👍

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 5 above)
Comment (DiannaHohensee) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2129]: I think name dropping MasterService and TaskTimeoutHandler class names might make it easier to go find the code -- I had to grep using the expected `r.toString()` value below. 

But the comment gives a hint, so I'm content and will leave it up to you.

**Review by DiannaHohensee — APPROVED** [review]
Thanks for the updates!

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java:2131]: I know what you mean, I would do something more robust if this were production code for sure. On balance I think this is best for testing purposes tho - the alternative adds a little too much stuff to production just to support this test.

File: server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java (hunk 5 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/service/MasterServiceTests.java]: How about this: I extracted the method that generates the string to `org.elasticsearch.cluster.service.MasterService#getTimeoutTaskDescription`, that way you can use `Find usages` to join the dots.
