### PR TITLE
Fix testOptimizerExpressionRuleShouldNotVisitExcludedNodes

### LINKED ISSUE #127754: [CI] OptimizerRulesTests testOptimizerExpressionRuleShouldNotVisitExcludedNodes failing
**Build Scans:**
- [elasticsearch-intake #22677 / part3](https://gradle-enterprise.elastic.co/s/gswcieym4425s)
- [elasticsearch-intake #22675 / part3](https://gradle-enterprise.elastic.co/s/xpbfiobwjcf56)
- [elasticsearch-pull-request #70518 / part-3](https://gradle-enterprise.elastic.co/s/dzju3seygfwpi)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.OptimizerRulesTests.testOptimizerExpressionRuleShouldNotVisitExcludedNodes" -Dtests.seed=F7CC49322523B902 -Dtests.locale=es-EA -Dtests.timezone=America/Martinique -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.optimizer.OptimizerRulesTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testOptimizerExpressionRuleShouldNotVisitExcludedNodes),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: iterable containing [<f1+1 AS x#114592>, <f1+1>, <?f1>, <1>]
     but: item 0: was <?f1>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testOptimizerExpressionRuleShouldNotVisitExcludedNodes
- [main] 2 consecutive failures in step part3
- [main] 2 consecutive failures in pipeline elasticsearch-intake
- [main] 3 failures in test testOptimizerExpressionRuleShouldNotVisitExcludedNodes (75.0% fail rate in 4 executions)
- [main] 2 failures in step part3 (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-intake (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by idegtiarenko**
Closes: #127754

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/OptimizerRulesTests.java [hunk 1]
```diff
@@ -138,6 +138,6 @@ protected Expression rule(Expression e, LogicalOptimizerContext ctx) {
         var alias = new Alias(new Source(1, 18, "x=f1+1"), "x", add);
 
         // contains expressions only from EVAL
-        assertThat(rule.appliedTo, contains(alias, add, attribute, literal));
+        assertThat(rule.appliedTo, containsInAnyOrder(alias, add, attribute, literal));
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/OptimizerRulesTests.java:141]: This might appear as `alias, add, attribute, literal` or `attribute, literal, add, alias` depending on `TransformDirection`

**Review by alex-spies — APPROVED** [review]
