### PR TITLE
Fix error reporting for SSL resources outside of config dir

### LINKED ISSUE #63451: Fix error reporting for SSL resources outside of config dir
In #55330 we change the sequence of events on startup so that the SSL resource watcher code runs before the SSL contexts are loaded.

As a consequence some of the friendly error messages that were added in #45122 are no longer used (because the reloader fails before it gets to the key/trust config objects)

### PR DESCRIPTION
**Pull request by filipdav**
Removing error messages for missing, unreadable or blocked config files that are no longer used because the reloader fails before running the config classes.

Closes #63451

### CODE REVIEW

**Comment by filipdav** [comment]
@tvernum can you review this?

**Comment by tvernum** [comment]
This change is the opposite of what was intended by the description #63451

We want to keep those error messages, we just need to deal with the problem that they're being hidden by the failure in the reloader.

**Comment by tvernum** [comment]
Sorry @filipdav, I haven't had time to provide the guidance that would help you get the right implementation here. When I opened the issue, I wasn't expected it to be picked up by an external contributor.

The order of the resource watching matters - the reloader needs to be created before the SSL service so that updates to the SSL resources are never missed.

What we need is to find a way to perform user-friendly error handling when the SSL config reloader tries to monitor the files.
That might mean moving some logic into the `filesToMonitor` on the config classes to verify that the files are readable, or maybe we can handle it entirely within the reloader.

This is not going to be as simple as just changing 1 or 2 lines of code (if it were, I would have fixed it straight away rather than opening an issue).

**Comment by filipdav** [comment]
@tvernum thank you for the clarification. I added verification for the file readability in the reloader, take a look and tell me what you think.

**Comment by tvernum** [comment]
@filipdav When I looked into this further, it turns out it really is as simple as updating the existing exception handling.

I've pushed a change to your branch that implements what I think we need here.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloader.java [hunk 1]
```diff
@@ -94,16 +96,16 @@ private static void startWatching(Environment environment, Consumer<SSLConfigura
...
+        pathToConfigurationsMap.forEach((path, configurations) -> {
+            ChangeListener changeListener = new ChangeListener(environment, List.copyOf(configurations), reloadConsumer);
+            FileWatcher fileWatcher = new FileWatcher(path);
             fileWatcher.addListener(changeListener);
             try {
                 resourceWatcherService.add(fileWatcher, Frequency.HIGH);
-            } catch (IOException e) {
-                logger.error("failed to start watching directory [{}] for ssl configurations [{}]", entry.getKey(), sslConfigurations);
+            } catch (IOException | AccessControlException e) {
+                logger.error("failed to start watching directory [{}] for ssl configurations [{}] - {}", path, configurations, e);
```
Comment (ywangd) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloader.java:106]: I don't think it's really necessary, but corresponding error messages during SSL Context building are finer grained, e.g. different error messages are logged for different subtypes of `IOException`, security permission failure is explicitly called out.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloaderTests.java [hunk 2]
```diff
@@ -503,6 +506,27 @@ public void testPEMTrustReloadException() throws Exception {
...
+            .put("path.home", createTempDir())
+            .build();
+        Environment env = TestEnvironment.newEnvironment(settings);
+        final AtomicReference<Exception> exceptionRef = new AtomicReference<>();
+
+        final ResourceWatcherService mockResourceWatcher = Mockito.mock(ResourceWatcherService.class);
+        Mockito.when(mockResourceWatcher.add(Mockito.any(), Mockito.any())).thenThrow(new AccessControlException("access denied in test"));
+        final Collection<SSLConfiguration> configurations = SSLService.getSSLConfigurations(settings).values();
+        final SSLConfigurationReloader reloader = new SSLConfigurationReloader(env, null, mockResourceWatcher, configurations);
+        assertNotNull(reloader);
```
Comment (ywangd) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloaderTests.java:527]: Nit: isn't this redundant since the above constructor would have failed already if the object does not get created?

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloaderTests.java [hunk 3]
```diff
@@ -503,6 +506,27 @@ public void testPEMTrustReloadException() throws Exception {
...
+     */
+    public void testReadingOutsideConfigDirectoryDoesntFail() throws Exception {
+        Path tempDir = createTempDir();
+        Path clientCertPath = tempDir.resolve("testclient.crt");
+        Settings settings = baseKeystoreSettings(tempDir, null)
+            .putList("xpack.security.transport.ssl.certificate_authorities", clientCertPath.toString())
+            .put("path.home", createTempDir())
+            .build();
+        Environment env = TestEnvironment.newEnvironment(settings);
+        final AtomicReference<Exception> exceptionRef = new AtomicReference<>();
```
Comment (ywangd) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloaderTests.java:521]: I think these are no longer needed given the new change of reporting error instead of throwing.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloaderTests.java [hunk 4]
```diff
@@ -503,6 +506,27 @@ public void testPEMTrustReloadException() throws Exception {
         assertThat(sslService.sslContextHolder(config).sslContext(), sameInstance(context));
     }
 
+    /**
+     * Tests that the reloader doesn't throw an exception if a file is configured to be outside of the config/ directory.
+     * These errors are handled correctly by the
+     */
+    public void testReadingOutsideConfigDirectoryDoesntFail() throws Exception {
```
Comment (ywangd) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloaderTests.java:513]: Based on the exceptions that get caught in `startWatching`, do we need another method for testing `IOException`? I suggest we modify this method to be more generic to cover both scenarios and randomize the exception.

**Review by ywangd — APPROVED** [review]
LGTM with a few suggestions and nits.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloader.java (hunk 1 above)
Comment (tvernum) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ssl/SSLConfigurationReloader.java:106]: Yes, and those messages will still be printed.
The net effect of this PR is to catch+log the exception and then get out the way so that the more fine grained error handling can do its job.

**Comment by tvernum** [comment]
@elasticmachine test this please
