### PR TITLE
Do not fail Evaluate API when the actual and predicted fields' types differ

### LINKED ISSUE #54079: Evaluate API fails when there is type mismatch between actual and predicted fields.
If fields (`actualField`, `predictedField`) are misconfigured and it happens that their mapping types differ (e.g. `long` vs `boolean`) then Evaluate API fails with non-intuitive error message mentioning script failure (the script we are using internally to calculate the metrics).

Example failures:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "script_exception",
        "reason" : "runtime error",
        "script_stack" : [
          "java.base/java.lang.Class.cast(Class.java:3604)",
          "doc['mal_count'].value == doc['ml.label_prediction'].value",
          "                                                    ^---- HERE"
```
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "Can't parse boolean value [1337x], expected [true] or [false]"
```

### PR DESCRIPTION
**Pull request by przemekwitek**
Currently, Evaluate API fails when the user uses actual and predicted fields of different types (e.g. `long` vs `boolean`) as for some metrics (accuracy, precision) `term` aggregation tries to parse one type as another.
This PR replaces `term` aggregation with `match` + `lenient: true`. This way the Evaluate API does not fail but returns no matches (just as if the sets of actual and predicted classes were disjoint).

Additionally, I've took a chance and added a number of new test cases to `ClassificationEvaluationIT` to increase coverage in case of various actual vs predicted types combinations.

Closes https://github.com/elastic/elasticsearch/issues/54079

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/evaluation/classification/MulticlassConfusionMatrix.java [hunk 1]
```diff
@@ -142,7 +142,7 @@ public int getSize() {
         if (result.get() == null) {  // These are steps 2, 3, 4 etc.
             KeyedFilter[] keyedFiltersPredicted =
                 topActualClassNames.get().stream()
-                    .map(className -> new KeyedFilter(className, QueryBuilders.termQuery(predictedField, className)))
+                    .map(className -> new KeyedFilter(className, QueryBuilders.matchQuery(predictedField, className).lenient(true)))
```
Comment (benwtrent) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/evaluation/classification/MulticlassConfusionMatrix.java]: This will analyze the input string. Which might be ok, but it will mean if we have classNames `Foo` and `foo` we will treat them as the same.

Which, having two classes only differ by case is pathological and probably SHOULD result in error :)

**Review by benwtrent — APPROVED** [review]

**Comment by przemekwitek** [comment]
run elasticsearch-ci/packaging-sample-matrix-unix

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/evaluation/classification/MulticlassConfusionMatrix.java (hunk 1 above)
Comment (przemekwitek) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/evaluation/classification/MulticlassConfusionMatrix.java]: > This will analyze the input string. Which might be ok, but it will mean if we have classNames Foo and foo we will treat them as the same.

I added a test `testEvaluate_AllMetrics_KeywordField_CaseSensitivity` to verify that and it turns out casing is sensitive, i.e. "crocodile" does *not* match "cRoCoDiLe". This is because dependent variable can be of type `keyword` but not of type `text`.
I think comparing class labels in a case-sensitive manner is ok as long as we document it clearly. LMK if you think otherwise.

> Which, having two classes only differ by case is pathological and probably SHOULD result in error :)

Maybe or maybe not. E.g.: I could think of some scientific experiment results in which there would be class names named "a", "b", "c", "A", "B", "C" where "a" and "A" mean different things. I'm open to suggestions here as I don't have a strong opinion on that.

Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/dataframe/evaluation/classification/MulticlassConfusionMatrix.java]: WOOT! Ok, I did not think of the `keyword` mapping. Indeed, those are not analyzed. Scratch my previous concern.

**Review by benwtrent — APPROVED** [review]
