### PR TITLE
Fix annotated highlight not maching when search contains both annotation and annotated term

### LINKED ISSUE #91944: Annotated highlight not maching when search contains both annotation and annotated term
### Elasticsearch Version

v8.5.2

### Installed Plugins

mapper-annotated-text

### Java Version

_bundled_

### OS Version

Linux 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Hi,

We use the `mapper-annotated-text` plugin in production to tag named-entities and found an particularly bad behavior during highlighting.

Basically, if we have a text `aaaa [bbbb cccc](annotated) dddd`, and search for `bbbb annotated` we'll get the highlight `aaaa [bbbb](_hit_term=bbbb) cccc dddd` where we'd expect `bbbb cccc` due to `annotated` being in the query too.

On the other hand, searching for `cccc annotated` produces the expected result of `aaaa [bbbb cccc](_hit_term=annotated&annotated) dddd`.

This happens because the annotation process receives the passage matches sorted by ascending offset order, and when a match overlaps with a previously seen one, it ignores it. So in the first case, it sees `bbbb` first and when it sees `annotated` it discards it because it overlaps with `bbbb`. On the latter case, `cccc` is the one discarded since it appears later in the list of offsets.

We've prototype a fix in [this branch](https://github.com/jusbrasil/elasticsearch/commit/aef49112d8795fac3d0425e2f810f1820c9a3d5e) and would be glad to iterate on it and advance with a PR if this is considered as an issue.

### Steps to Reproduce

```
PUT example
{
  "mappings": {
    "properties": {
      "body": {
        "type": "annotated_text"
      }
    }
  }
}
POST example/_doc
{
  "body": "aaaa [bbbb cccc](annotated) dddd"
}
POST example/_search
{
  "query": {
    "match_all": {}
  },
  "highlight": {
    "type": "annotated",
    "order": "score",
    "fields": {
      "body": {
        "highlight_query": {
          "bool": {
            "must": {
              "match": {
                "body": {
                  "query": "bbbb annotated"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by thelink2012**
Fixes https://github.com/elastic/elasticsearch/issues/91944. See that issue for details on the problem. But quoting the problem from there:

> If we have a text aaaa \[bbbb cccc\](annotated) dddd, and search for bbbb annotated we'll get the highlight aaaa \[bbbb\](_hit_term=bbbb) cccc dddd where we'd expect bbbb cccc due to annotated being in the query too.
> 
> On the other hand, searching for cccc annotated produces the expected result of aaaa \[bbbb cccc\](_hit_term=annotated&annotated) dddd.
> 
> This happens because the annotation process receives the passage matches sorted by ascending offset order, and when a match overlaps with a previously seen one, it ignores it. So in the first case, it sees bbbb first and when it sees annotated it discards it because it overlaps with bbbb. On the latter case, cccc is the one discarded since it appears later in the list of offsets.

### CODE REVIEW

File: plugins/mapper-annotated-text/src/main/java/org/elasticsearch/index/mapper/annotatedtext/AnnotatedPassageFormatter.java [hunk 1]
```diff
@@ -120,11 +122,27 @@ public String toString() {
     static MarkupPassage mergeAnnotations(AnnotationToken[] annotations, Passage passage) {
         MarkupPassage markupPassage = new MarkupPassage();
 
+        final Integer[] matches = new Integer[passage.getNumMatches()];
```
Comment (romseygeek) [inline plugins/mapper-annotated-text/src/main/java/org/elasticsearch/index/mapper/annotatedtext/AnnotatedPassageFormatter.java:125]: Can this just be an `int[]`?

**Review by romseygeek — COMMENTED** [review]
Thanks @thelink2012 , this looks great.  I'll run it through CI.

**Comment by romseygeek** [comment]
@elasticmachine test this please

File: plugins/mapper-annotated-text/src/main/java/org/elasticsearch/index/mapper/annotatedtext/AnnotatedPassageFormatter.java (hunk 1 above)
Comment (thelink2012) [reply plugins/mapper-annotated-text/src/main/java/org/elasticsearch/index/mapper/annotatedtext/AnnotatedPassageFormatter.java:125]: Hey @romseygeek. Thanks for your review. It cannot be a `int[]` because `Arrays.sort` with a comparator doesn't support primitive types.

**Comment by thelink2012** [comment]
CI failed during style check. Sorry for that. I had it formatted locally but forgot to commit.

**Comment by romseygeek** [comment]
@elasticmachine test this please

**Comment by thelink2012** [comment]
@romseygeek seems like CI failed on something unrelated to this (timeout at something). How can we check this again? By running CI until it works?

**Comment by romseygeek** [comment]
@thelink2012 yes, could you merge in latest master and push to your branch?

Can you also create a file `docs/changelog/92920.yaml` with the following content:
```
pr: 92920
summary: Annotated highlighter does not match when search contains both annotation and annotated term
area: Search
type: bug
issues:
  - 91944

```

**Comment by romseygeek** [comment]
@elasticmachine test this please

**Comment by romseygeek** [comment]
That's another unrelated test failure, which should be muted now - can you merge in master again? Alternatively if you can click the 'allow edits from maintainers' button then I should be able to do it via our elasticmachine bot.

**Comment by thelink2012** [comment]
@romseygeek sure. Merged master. The allow edit checkbox is already marked. Can you confirm?

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine ok to test

**Review by romseygeek — APPROVED** [review]

**Comment by romseygeek** [comment]
Thanks for your contribution @thelink2012!
