### PR TITLE
[tests] fix sort and string processor tests around targetField

### LINKED ISSUE #25346: CI: SortProcessorTests.testAscendingSortWithTargetField fails
This test fails reliably on my local workstation as well with the configured seed, to reproduce

```
gradle clean :modules:ingest-common:test -Dtests.seed=3093A1E6D37F5E51 -Dtests.class=org.elasticsearch.ingest.common.SortProcessorTests -Dtests.method="testAscendingSortWithTargetField" -Dtests.security.manager=true -Dtests.locale=cs -Dtests.timezone=Africa/Lome
```

Link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/347/console

### PR DESCRIPTION
**Pull request by talevy**
Tests were randomly assigning `targetField` to an existing field that was an array,
causing path resolution issues. This PR fixes those tests

Closes #25346 & #25348

### CODE REVIEW

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/SortProcessorTests.java [hunk 1]
```diff
@@ -276,7 +276,7 @@ public void testSortNullValue() throws Exception {
     }
 
     public void testDescendingSortWithTargetField() throws Exception {
-        IngestDocument ingestDocument = RandomDocumentPicks.randomIngestDocument(random());
+        IngestDocument ingestDocument = RandomDocumentPicks.randomIngestDocument(random(), new HashMap<>());
```
Comment (spinscale) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/SortProcessorTests.java]: `Collections.emptyMap`?

**Review by spinscale — COMMENTED** [review]
left one minor comment, LGTM otherwise

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/SortProcessorTests.java (hunk 1 above)
Comment (talevy) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/SortProcessorTests.java]: ah yes. I didn't realize this source object was copied in the constructor. I remember this being an issue before so I avoided it. will update all
