### PR TITLE
[Data Frame] Avoid assertions on empty Optional in DF usage test

### LINKED ISSUE #40022: [CI] DataFrameFeatureSetTests.testUsage failed
The test DataFrameFeatureSetTests.testUsage failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2524/console

Reproducible locally, will disable the test on master

The repro command was:
```
./gradlew :x-pack:plugin:data-frame:unitTest \
-Dtests.seed=F4EF7A3D01C8868B \
-Dtests.class=org.elasticsearch.xpack.dataframe.DataFrameFeatureSetTests \
-Dtests.method="testUsage" \
-Dtests.security.manager=true \
-Dtests.locale=pt \
-Dtests.timezone=Africa/Bujumbura \
-Dcompiler.java=11 
-Druntime.java=8
```

### PR DESCRIPTION
**Pull request by davidkyle**
Avoid assertions on an empty Optional in DF usage test where randomisation means a reduce operation may occur on a zero lenght list resulting in an empty Optional. 

Closes #40022

### CODE REVIEW

File: x-pack/plugin/data-frame/src/test/java/org/elasticsearch/xpack/dataframe/DataFrameFeatureSetTests.java [hunk 1]
```diff
@@ -142,16 +142,19 @@ public void testUsage() throws InterruptedException, ExecutionException, IOExcep
...
-                        XContentMapValues.extractValue("stats.index_failures", usageAsMap));
-                assertEquals(toIntExact(combinedStats.getIndexTotal()), XContentMapValues.extractValue("stats.index_total", usageAsMap));
-                assertEquals(toIntExact(combinedStats.getSearchTime()),
-                        XContentMapValues.extractValue("stats.search_time_in_ms", usageAsMap));
-                assertEquals(toIntExact(combinedStats.getNumDocuments()),
-                        XContentMapValues.extractValue("stats.documents_processed", usageAsMap));
+                Optional<DataFrameIndexerTransformStats> combinedStats = transformsStateAndStats.stream().map(x -> x.getTransformStats())
+                        .reduce((l, r) -> l.merge(r));
+
+                if (combinedStats.isPresent()) {
```
Comment (hendrikmuhs) [inline x-pack/plugin/data-frame/src/test/java/org/elasticsearch/xpack/dataframe/DataFrameFeatureSetTests.java]: I think the problem of this test is on line 131, the `if` is broken, it broke because `transformConfigWithoutTasks` is empty but `transformsStateAndStats` isn't. 

I admit this isn't a master piece in test writing (I think I originally wrote it), it would be clearer and cleaner if we split this test into the empty and non-empty case. We then do not need to workaround here, which I am not sure about: it disables all asserts and tests nothing if `isPresent()` returns false, which means we have no coverage for this case.

Comment (benwtrent) [reply x-pack/plugin/data-frame/src/test/java/org/elasticsearch/xpack/dataframe/DataFrameFeatureSetTests.java]: @hendrikmuhs looking at the test we do have assertions for when `combinedStats.isPresent()`, they all occur earlier in the test for asserting the number of DFs that are given in certain states. I am not sure what `else` tests would exist in this case. 

I should have caught this in my refactor,

Comment (davidkyle) [reply x-pack/plugin/data-frame/src/test/java/org/elasticsearch/xpack/dataframe/DataFrameFeatureSetTests.java]: There are assertions on `transformConfigWithoutTasks` lines 143-144 even if `transformsStateAndStats` is empty. 

I pushed a small change so it asserts the stats have value 0 if `transformsStateAndStats` is empty

**Comment by davidkyle** [comment]
I refactored `DataFrameFeatureSetUsage.usage` to extract the logic into a separate method. That makes the testing easier as it removes the need to mock client responses. Then I ran the test 100 times and hit failures because the random task Ids were not unique so I reworked the test to prevent that happening.

**Review by benwtrent — APPROVED** [review]
👍 Integration with the usage as a whole is already done in `org.elasticsearch.xpack.dataframe.integration.DataFrameUsageIT`. So, pulling out the logic and testing it outside of using the client is cool

**Review by hendrikmuhs — APPROVED** [review]
LGTM
