### PR TITLE
Fix bug where fvh fragments could be loaded from wrong doc

### LINKED ISSUE #65533: FVH Highlighter does not work with the inner hits properly
Elasticsearch version: 7.10.0
Running in docker from image docker.elastic.co/elasticsearch/elasticsearch:7.10.0

Fvh highligher does not highlight actual content of the inner hit. It seems to alway returning highlight for the first relevant inner hit but with the highlight offsets of the current inner hit. Other highlighters ("plain" and "unified") are working correctly.

Steps:

1. Create index with the nested field:
```
curl -H 'Content-type: application/json' -XPUT 'http://localhost:9200/test' -d '{
 "mappings": {
  "properties": {
   "obj": {
    "type": "nested",
    "properties": {
     "content": {
      "type": "text",
      "norms": true,
      "term_vector": "with_positions_offsets"
     }
    }
   }
  }
 }
}'
```
2. Put a document:
```
curl -H 'Content-type: application/json' -XPOST 'http://localhost:9200/test/_doc/' -d '{
 "obj": [
  {
   "content": "hello world"
  },
  {
   "content": "world hello"
  }
 ]
}'
```

3. Run a nested search query with the highlight:
```
curl -H 'Content-type: application/json' -XPOST 'http://localhost:9200/test/_search' -d '{
 "query": {
  "bool": {
   "should": [
    {
     "nested": {
      "query": {
       "match": {
        "obj.content": {
         "query": "hello",
         "operator": "OR",
         "prefix_length": 0,
         "max_expansions": 50,
         "minimum_should_match": "1<-1%",
         "fuzzy_transpositions": true,
         "lenient": true,
         "zero_terms_query": "NONE",
         "auto_generate_synonyms_phrase_query": true,
         "boost": 1
        }
       }
      },
      "path": "obj",
      "ignore_unmapped": false,
      "score_mode": "none",
      "boost": 1,
      "inner_hits": {
       "name": "obj|116088734",
       "ignore_unmapped": false,
       "from": 0,
       "size": 10,
       "version": false,
       "seq_no_primary_term": false,
       "explain": false,
       "track_scores": false,
       "highlight": {
        "fields": {
         "obj.content": {
          "fragment_size": 350,
          "number_of_fragments": 0,
          "type": "fvh",
          "order": "score",
          "no_match_size": 0,
          "matched_fields": [
           "obj.content"
          ]
         }
        }
       }
      }
     }
    }
   ],
   "adjust_pure_negative": true,
   "boost": 1
  }
 },
 "_source": false
}'
```

Result:
```
{ - 
  "took": 5,
  "timed_out": false,
  "_shards": { - 
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": { - 
    "total": { - 
      "value": 1,
      "relation": "eq"
    },
    "max_score": 0,
    "hits": [ - 
      { - 
        "_index": "test",
        "_type": "_doc",
        "_id": "h4HGA3YBAHjK9WUfKSvs",
        "_score": 0,
        "inner_hits": { - 
          "obj|116088734": { - 
            "hits": { - 
              "total": { - 
                "value": 2,
                "relation": "eq"
              },
              "max_score": 0.18232156,
              "hits": [ - 
                { - 
                  "_index": "test",
                  "_type": "_doc",
                  "_id": "h4HGA3YBAHjK9WUfKSvs",
                  "_nested": { - 
                    "field": "obj",
                    "offset": 0
                  },
                  "_score": 0.18232156,
                  "_source": { - 
                    "content": "hello world"
                  },
                  "highlight": { - 
                    "obj.content": [ - 
                      "<em>hello</em> world"
                    ]
                  }
                },
                { - 
                  "_index": "test",
                  "_type": "_doc",
                  "_id": "h4HGA3YBAHjK9WUfKSvs",
                  "_nested": { - 
                    "field": "obj",
                    "offset": 1
                  },
                  "_score": 0.18232156,
                  "_source": { - 
                    "content": "world hello"
                  },
                  "highlight": { - 
                    "obj.content": [ - 
                      "hello <em>world</em>"
                    ]
                  }
                }
              ]
            }
          }
        }
      }
    ]
  }
}
```

Highlights are returned with the correct offsets and indents but with the wrong contents.
Should be  **world <em>hello</em>** for the second inner hit.

### PR DESCRIPTION
**Pull request by jtibshirani**
This PR fixes a regression where fvh fragments could be loaded from the wrong
document _source.

Some `FragmentsBuilder` implementations contain a `SourceLookup` to load from
_source. The lookup should be positioned to load from the current hit document.
However, since `FragmentsBuilder` are cached and shared across hits, the lookup
is never updated to load from the new documents. This means we accidentally
load _source from a different document.

The regression was introduced in #60179, which started storing `SourceLookup`
on `FragmentsBuilder`.

Fixes #65533.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/FastVectorHighlighter.java [hunk 1]
```diff
@@ -160,8 +160,13 @@ public HighlightField highlight(FieldHighlightContext fieldContext) throws IOExc
         }
         cache.fvh.setPhraseLimit(field.fieldOptions().phraseLimit());
 
-        String[] fragments;
+        // If the fragments builder requires document _source, pass it the source lookup from the hit context.
+        if (entry.fragmentsBuilder instanceof SourceBasedFragmentsBuilder) {
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/FastVectorHighlighter.java:164]: This is hacky but felt like the best way to fix this right now. `FragmentsBuilder` is an external (Lucene) interface and there's not a good way to pass in _source to its methods like `getFields`.

Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/FastVectorHighlighter.java:164]: Could we replace the cached FragmentsBuilder with a `Function<SourceLookup, FragmentsBuilder>` and then call that with the new SourceLookup for each hit?  The FragmentsBuilders themselves don't seem to do any significant processing on construction so I don't think there would be a performance penalty for rebuilding them each time.

Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/FastVectorHighlighter.java:164]: It seems like that should work! I'd like to check I understand the context. We probably have these cached entries not because fragment builders are expensive to build, but to avoid rebuilding the `FieldQuery` which looks more complex?

**Comment by jtibshirani** [comment]
Thanks @romseygeek for the suggestion, I tried out the new approach.

**Review by romseygeek — APPROVED** [review]
LGTM, thanks @jtibshirani!
