### PR TITLE
Load percolator queries before shard is marked POST_RECOVERY

### LINKED ISSUE #10722: Percolation requests can be executed before all percolator queries are loaded
The percolator can sometimes fail to match queries right after shard recovery. Version observed in: 1.5.1. 

The percolator keeps all queries in an in-memory collection (shard by shard), which it reads from the index at startup. This is done by registering a listener to the IndicesLifecycle, with the listener loads the queries when afterIndexShardPostRecovery is called. 

This seems to not block the shard to be reported as initialised, so sometimes this is not completed before the cluster returns a yellow status. Thus, if a request comes in _before_ all queries have been loaded into the in-memory structure, the response will erroneously say that there were no matches.

I've been unable to create a predictively failing test for this. This test _sometimes_ exposes the error (by not passing). For me, it fails every 5-6th time:

```
package org.elasticsearch.test.integration;

import org.elasticsearch.action.admin.cluster.health.ClusterHealthResponse;
import org.elasticsearch.action.percolate.PercolateRequestBuilder;
import org.elasticsearch.action.percolate.PercolateResponse;
import org.elasticsearch.action.percolate.PercolateSourceBuilder;
import org.elasticsearch.client.Client;
import org.elasticsearch.client.Requests;
import org.elasticsearch.common.settings.ImmutableSettings;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.percolator.PercolatorService;
import org.testng.annotations.AfterClass;
import org.testng.annotations.Test;

import java.io.IOException;
import java.util.concurrent.ExecutionException;

import static org.elasticsearch.common.xcontent.XContentFactory.jsonBuilder;
import static org.elasticsearch.index.query.QueryBuilders.matchQuery;
import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

/**
 *
 */
public class RecoveryTests extends AbstractNodesTests {
    @AfterClass
    public void closeNodes() {
        closeAllNodesAndClear();
    }

    @Test(enabled = true)
    public void testRestartNode() throws IOException, ExecutionException, InterruptedException {
        Settings extraSettings = ImmutableSettings.settingsBuilder()
                .put("index.gateway.type", "local").build();

        logger.info("--> Starting one nodes");
        startNode("node1", extraSettings);
        Client client = client("node1");

        logger.info("--> Add dummy doc");
        client.admin().indices().prepareDelete("_all").execute().actionGet();
        client.prepareIndex("test", "type", "1").setSource("field", "value").execute().actionGet();

        logger.info("--> Register query");
        client.prepareIndex("test", PercolatorService.TYPE_NAME, "1")
                .setSource(jsonBuilder()
                                .startObject()
                                .field("query", matchQuery("field", "b"))
                                .field("id", 1)
                                .field("group", "g1")
                                .field("query_hash", "hash1")
                                .endObject()
                ).setRefresh(true).execute().actionGet();
        logger.info("--> Restarting node");
        closeNode("node1");
        startNode("node1", extraSettings);
        client = client("node1");
        logger.info("Waiting for cluster health to be yellow");
        waitForYellowIndices(client);

        logger.info("--> Percolate doc with field=b");
        PercolateResponse response = new PercolateRequestBuilder(client).setIndices("test").setDocumentType("type")
                .setSource(new PercolateSourceBuilder().setDoc(PercolateSourceBuilder.docBuilder().setDoc(jsonBuilder().startObject().field("_id", "1").field("field", "b").endObject())))
                .execute().actionGet();

        assertThat(response.getCount(), is(1l));

        logger.info("--> Restarting node again (This will trigger another code-path since translog is flushed)");
        closeNode("node1");
        startNode("node1", extraSettings);
        client = client("node1");
        logger.info("Waiting for cluster health to be yellow");
        waitForYellowIndices(client);

        logger.info("--> Percolate doc with field=b");
        response = new PercolateRequestBuilder(client).setIndices("test").setDocumentType("type")
                .setSource(new PercolateSourceBuilder().setDoc(PercolateSourceBuilder.docBuilder().setDoc(jsonBuilder().startObject().field("_id", "1").field("field", "b").endObject())))
                .execute().actionGet();

        assertThat(response.getCount(), is(1l));

    }

    private void waitForYellowIndices(Client client) {
        ClusterHealthResponse health = client.admin().cluster().health(Requests.clusterHealthRequest(new String[]{}).waitForYellowStatus().waitForActiveShards(5)).actionGet();
        assertThat(health.isTimedOut(), equalTo(false));
    }
}

```

There are tests similar to this one for the percolator, which are supposed to test the same thing. From what I understand though, those are very particular about the cluster setup.. might it be that they can't catch this issue?

### PR DESCRIPTION
**Pull request by s1monw**
If we mark the shard as being in POST_RECOVERY before the percolator
is fully set up we might expose it to the user as fully searchable before
all queries are loaded. This can lead to wrong results especially in tests
when a shard is concurrently marked as STARTED.

This commit also removes unneeded abstractions on IndexShard where readoperations
should be allowed when the purpose is a write.

Closes #10722

### CODE REVIEW

**Comment by s1monw** [comment]
her is a failure related to this http://build-us-00.elastic.co/job/es_core_master_centos/5330/

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 1]
```diff
@@ -907,20 +904,9 @@ public boolean ignoreRecoveryAttempt() {
     }
 
     public void readAllowed() throws IllegalIndexShardStateException {
-        readAllowed(false);
-    }
-
-
-    private void readAllowed(boolean writeOperation) throws IllegalIndexShardStateException {
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: ++ to this simplification

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 2]
```diff
@@ -907,20 +904,9 @@ public boolean ignoreRecoveryAttempt() {
...
-        if (writeOperation) {
-            if (state != IndexShardState.STARTED && state != IndexShardState.RELOCATED && state != IndexShardState.RECOVERING && state != IndexShardState.POST_RECOVERY) {
-                throw new IllegalIndexShardStateException(shardId, state, "operations only allowed when started/relocated");
-            }
-        } else {
-            if (state != IndexShardState.STARTED && state != IndexShardState.RELOCATED) {
-                throw new IllegalIndexShardStateException(shardId, state, "operations only allowed when started/relocated");
-            }
+        if (state != IndexShardState.STARTED && state != IndexShardState.RELOCATED) {
+            throw new IllegalIndexShardStateException(shardId, state, "operations only allowed when started/relocated");
```
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: wait, this exception would be thrown when `loadQueries()` is invoked, because the state would be `RECOVERING`?

File: core/src/main/java/org/elasticsearch/action/fieldstats/TransportFieldStatsTransportAction.java [hunk 3]
```diff
@@ -133,7 +133,6 @@ protected FieldStatsShardResponse shardOperation(FieldStatsShardRequest request)
         IndexService indexServices = indicesService.indexServiceSafe(shardId.getIndex());
         MapperService mapperService = indexServices.mapperService();
         IndexShard shard = indexServices.shardSafe(shardId.id());
-        shard.readAllowed();
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/action/fieldstats/TransportFieldStatsTransportAction.java]: Why is this removed here?

**Comment by bleskes** [comment]
Looks good - left one comment.

File: core/src/main/java/org/elasticsearch/action/fieldstats/TransportFieldStatsTransportAction.java (hunk 3 above)
Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/action/fieldstats/TransportFieldStatsTransportAction.java]: I think because the readAllowed() is now part of the acquireSearcher() method.

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/fieldstats/TransportFieldStatsTransportAction.java]: yes it's called in `IndexShard#acquireSearcher()`

File: core/src/main/java/org/elasticsearch/index/shard/IndexShard.java (hunk 2 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: I worked around this by calling `indexShard().engine().acquireSearcher()` :P

Comment (martijnvg) [inline core/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: sneaky, I missed that :)

**Comment by martijnvg** [comment]
LGTM

**Comment by bleskes** [comment]
LGTM 2
