### PR TITLE
Avoid unnecessary determinization in index pattern conflict checks

### LINKED ISSUE #127972: `too_complex_to_determinize_exception` is thrown in a few cases due to the patterns in index template
### Elasticsearch Version

9.0.0 ECH

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Elastic Cloud

### Problem Description

After an upgrade to Elastic v9.0.0, a user reported that they were encountering `too_complex_to_determinize_exception` error for the index patterns in `PUT _index_template/logs-production`. 

At the moment, we've communicated a workaround: either simplify the patterns or split the patterns across 2 templates. However, we'll need a proper fix for this.

Looking at the commit history, this error is coming from the changes introduced in Lucene 10 upgrade: https://github.com/elastic/elasticsearch/pull/114741, i.e. due to `Operations.determinize(Operations.union(automata), Operations.DEFAULT_DETERMINIZE_WORK_LIMIT)` in `Regex#simpleMatchToAutomaton()`.

### Steps to Reproduce

Here's an example:

```
PUT _index_template/logs-production
{
  "index_patterns": [
                    "*haproxy-production*",
                    "*postgres-production*",
                    "*psql_slow_query-production*",
                    "*springboot-production*",
                    "*tomcat-production*",
                    "*security-security*",
                    "*alerts-monitoring*"
  ],
  "template": {
    "settings": {
      "index": {
        "lifecycle": {
          "name": "logs-production"
        },
        "codec": "best_compression",
        "query": {
          "default_field": [
            "message"
          ]
        }
      }
    }
  },
  "composed_of": [
    "logs-mappings",
    "data-streams-mappings"
  ]
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jimczi**
Starting with Lucene 10, `CharacterRunAutomaton` is no longer determinized automatically. 
In Elasticsearch 9, we adapted to this by eagerly determinizing automatons early (via `Regex#simpleMatchToAutomaton`). However, this introduced  regression: operations like index template conflict checks, which only require intersection testing, now pay the cost of determinization, an expensive step that wasn’t needed before. In some cases, especially when many wildcard patterns are involved, determinization can even fail due to state explosion.

This change removes the unnecessary determinization for index patterns conflict check, restoring the pre-9.0 behavior and allowing valid index templates with many patterns to be registered again.

closes: https://github.com/elastic/elasticsearch/issues/127972

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/regex/Regex.java [hunk 1]
```diff
@@ -113,7 +113,14 @@ public static Automaton simpleMatchToAutomaton(String... patterns) {
...
             automata.add(Operations.concatenate(prefixAutomaton));
         }
-        return Operations.determinize(Operations.union(automata), Operations.DEFAULT_DETERMINIZE_WORK_LIMIT);
+        return Operations.union(automata);
+    }
+
+    /**
+     * Return a deterministic Automaton that matches the union of the provided patterns.
+     */
+    public static Automaton simpleMatchToAutomaton(String... patterns) {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/common/regex/Regex.java:122]: small drive-by comment: should add to the javadocs when one or the other should be used?

Comment (pawankartik-elastic) [reply server/src/main/java/org/elasticsearch/common/regex/Regex.java:122]: +1, Luca. I've raised a similar question internally within the relevant discussion thread.

Comment (jimczi) [reply server/src/main/java/org/elasticsearch/common/regex/Regex.java:140]: ++, https://github.com/elastic/elasticsearch/pull/128362/commits/268dc563b09f1bd6692e5bb68ddb5085ba773b60 
I also added the variant for the single pattern case since to be complete.

**Review by pawankartik-elastic — APPROVED** [review]
LGTM overall. Leaving 2 tiny comments.

**Review by dakrone — APPROVED** [review]
LGTM, thanks for tagging us

File: server/src/test/java/org/elasticsearch/common/regex/RegexTests.java [hunk 2]
```diff
@@ -250,4 +254,14 @@ public void testThousandsAndLongPattern() throws IOException {
...
         }
     }
+
+    public void testIntersectNonDeterminizedAutomaton() {
+        String[] patterns = randomArray(20, 100, size -> new String[size], () -> "*" + randomAlphanumericOfLength(10) + "*");
+        Automaton a = Regex.simpleMatchToNonDeterminizedAutomaton(patterns);
+        Automaton b = Regex.simpleMatchToNonDeterminizedAutomaton(Arrays.copyOfRange(patterns, patterns.length / 2, patterns.length));
+        assertFalse(Operations.isEmpty(Operations.intersection(a, b)));
+        IllegalArgumentException exc = expectThrows(IllegalArgumentException.class, () -> assertMatchesAll(a, "my_test"));
+        assertThat(exc.getMessage(), containsString("deterministic"));
```
[the remark this answers is not in the document]
Comment (jimczi) [reply server/src/test/java/org/elasticsearch/common/regex/RegexTests.java:268]: https://github.com/elastic/elasticsearch/pull/128362/commits/bd1e02d6b99b290148c13aff6b02a5996019656b

File: server/src/test/java/org/elasticsearch/common/regex/RegexTests.java [hunk 3]
```diff
@@ -250,4 +254,14 @@ public void testThousandsAndLongPattern() throws IOException {
             assertTrue(predicate.test(patterns[i]));
         }
     }
+
+    public void testIntersectNonDeterminizedAutomaton() {
+        String[] patterns = randomArray(20, 100, size -> new String[size], () -> "*" + randomAlphanumericOfLength(10) + "*");
```
[the remark this answers is not in the document]
Comment (jimczi) [reply server/src/test/java/org/elasticsearch/common/regex/RegexTests.java:260]: https://github.com/elastic/elasticsearch/pull/128362/commits/bd1e02d6b99b290148c13aff6b02a5996019656b

**Comment by benwtrent** [comment]
This should be backported to 9.0.x right? Its existed ever since the lucene 10 upgrade.

@pawankartik-elastic @jimczi
