### PR TITLE
SearchRequest#allowPartialSearchResults does not handle successful retries

### LINKED ISSUE #40743: Queries using allowPartialSearchResults=false involving only successful retries fail with status 503
**Elasticsearch version** 6.3.2

**Plugins installed**: []

**JVM version**: 1.8.144

**OS version**: Linux 3.13.0-88-generic #135-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

In `AbstractSearchAsyncAction::executeNextPhase` there's the following code:
`if (allowPartialResults == false && shardFailures.get() != null )`

This code assumes that `shardFailures.get() != null` indicates shard failures.
However, since shard failures can be retried and then nulled out in `AbstractSearchAsyncAction::onShardSuccess`, it's possible that shardFailures.get() consists of only null `ShardSearchFailure`s. When that happens, `executeNextPhase` fails with "Partial shards failure".
In addition, the status code in this case is 503.

This is our query configuration:

`SearchRequest{searchType=QUERY_THEN_FETCH, indices=[index], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='_local', requestCache=null, scroll=null, maxConcurrentShardRequests=30, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=false`

**Steps to reproduce**:

**Provide logs (if relevant)**:
After a query fails (due to NPE in a custom java search script we use) with
`org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]`
and the query is retried on a different node and succeeds, the following appears in the log:

`[2019-04-02T09:30:24,986][TRACE][o.e.a.s.TransportSearchAction] [esrec11d-10001-prod-nydc1.nydc1] got first-phase result from [t7GpBRj0TUCXKaYYwiMJVA][index][1]`

`[2019-04-02T09:30:24,990][TRACE][o.e.a.s.TransportSearchAction] [esrec11d-10001-prod-nydc1.nydc1] got first-phase result from [QBZwuD5MSLyDMD56SoZpWg][index][0]`

`[2019-04-02T09:30:24,990][DEBUG][o.e.a.s.TransportSearchAction] [esrec11d-10001-prod-nydc1.nydc1] 0 shards failed for phase: [query]`

### PR DESCRIPTION
**Pull request by jimczi**
When set to false, allowPartialSearchResults option does not check if the
shard failures have been reseted to null. The atomic array, that is used to record
shard failures, is filled with a null value if a successful request on a shard happens
after a failure on a shard of another replica. In this case the atomic array is not empty
but contains only null values so this shouldn't be considered as a failure since all
shards are successful (some replicas have failed but the retries on another replica succeeded).
This change fixes this bug by checking the content of the atomic array and fails the request only
if allowPartialSearchResults is set to false and at least one shard failure is not null.

Closes #40743

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java [hunk 1]
```diff
@@ -389,12 +486,12 @@ protected void executeNext(Runnable runnable, Thread originalThread) {
...
-                    if (randomBoolean()) {
+                    //if (randomBoolean()) {
                         routing.started();
                         started.add(routing);
-                    } else {
-                        initializing.add(routing);
-                    }
+                    //} else {
+                      //  initializing.add(routing);
+                    //}
```
Comment (markharwood) [inline server/src/test/java/org/elasticsearch/action/search/SearchAsyncActionTests.java]: Comments need removing?

**Review by markharwood — COMMENTED** [review]
LGTM - test passing here. 
Just some commented-out code in the test class that looks like it needs dealing with

**Review by javanna — APPROVED** [review]
LGTM
