### PR TITLE
Fix propagation of dynamic mapping parameter when applying copy_to

### LINKED ISSUE #113049: copy_to logic fails when used to copy value from object with dynamic: "strict" to a dynamically mapped field
### Elasticsearch Version

8.16

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

x

### Problem Description

When `copy_to` values are parsed, we create a custom context via `createCopyToContext`. This context preserves the `dynamic` value from parent context which is wrong. That value is for the field that is a source of the copy, not the destination. As a result, when `copy_to` destination is a dynamically mapped field and https://github.com/elastic/elasticsearch/blob/45306a52c240ef153d2dcea8b8d36c2ab8ecc313/server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java#L533 is called, it throws an exception that is wrong.

### Steps to Reproduce

```
PUT my-index
{
  "mappings": {
    "properties": {
      "copy_source": {
        "dynamic": "strict",
        "properties": {
          "k": {
            "type": "keyword",
            "copy_to": "dest"
          }
        }
      }
    }
  }
}

POST my-index/_bulk?refresh
{ "create": {} }
{ "copy_source": { "k": "let's copy" } }

// Results in this which is wrong
"error": {
    "type": "strict_dynamic_mapping_exception",
    "reason": "[1:25] mapping set to strict, dynamic introduction of [dest] within [_doc] is not allowed"
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by lkts**
Closes https://github.com/elastic/elasticsearch/issues/113049.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java [hunk 1]
```diff
@@ -50,6 +50,13 @@ private Wrapper(ObjectMapper parent, DocumentParserContext in) {
             this.in = in;
         }
 
+        // Used to create a copy_to context.
+        // It is important to reset `dynamic` here since it is possible that we copy into a completely different object.
+        private Wrapper(RootObjectMapper root, DocumentParserContext in) {
```
Comment (lkts) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:55]: Note that call site didn't change here, this works because `createCopyToContext` is the only place that passes a root maper to `Wrapper` constructor. I think this is fragile but i don't have anything better.

**Comment by lkts** [comment]
Closes #120384.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 1 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:55]: Shall we create a factory method like `createWithRootDynamic` and use it explicitly?

**Review by kkrik-es — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java (hunk 1 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParserContext.java:55]: It's an optioin but you still need this constructor to call `super`.

**Comment by lkts** [comment]
CI failure is #121335.

**Comment by lkts** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/121357)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by tlrx** [comment]
I suspect this change needs to be backported to the `9.0` branch as well: some BWC tests that upgrade a cluster from 8.19.0 to 9.0 are now failing due to the missing required features [mapper.copy_to.dynamic_handling]. 

See #121362 or #121365 for example.

**Comment by kkrik-es** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/121386)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by kkrik-es** [comment]
> I suspect this change needs to be backported to the `9.0` branch as well: some BWC tests that upgrade a cluster from 8.19.0 to 9.0 are now failing due to the missing required features [mapper.copy_to.dynamic_handling].
> 
> See #121362 or #121365 for example.

Created the backport with auto-merge.
