### PR TITLE
Fix match_phrase_prefix on boosted fields

### LINKED ISSUE #21613: MatchPhrasePrefix does not work with fields boosted in the index mapping
When a field defines a boost directly in the mapping:

````
PUT t
{
   "mappings": {
      "t": {
         "properties": {
            "textfield": {
               "type": "text", 
               "boost": 3
            }
         }
      }
   }
}
````

... the match_phrase_prefix query does not consider the last term as prefix:

````
POST t/t
{
    "textfield" : "foo bar"
}

GET t/t/_search
{
    "query" : {
        "match_phrase_prefix": {
           "textfield": "f"
        }
    }
}
`````

The above query does not return the hit.

### PR DESCRIPTION
**Pull request by jimczi**
This change fixes the match_phrase_prefix on fields that define a boost in their mapping.

Fixes #21613

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/search/MatchQuery.java [hunk 1]
```diff
@@ -302,7 +303,10 @@ protected Query newTermQuery(Term term) {
         }
 
         public Query createPhrasePrefixQuery(String field, String queryText, int phraseSlop, int maxExpansions) {
-            final Query query = createFieldQuery(getAnalyzer(), Occur.MUST, field, queryText, true, phraseSlop);
+            Query query = createFieldQuery(getAnalyzer(), Occur.MUST, field, queryText, true, phraseSlop);
+            while (query instanceof BoostQuery) {
+                query = ((BoostQuery) query).getQuery();
+            }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/search/MatchQuery.java]: should we then apply the boost again on the new query?

File: core/src/test/java/org/elasticsearch/search/query/SearchQueryIT.java [hunk 2]
```diff
@@ -2089,4 +2089,16 @@ public void testQueryStringParserCache() throws Exception {
...
+        assertAcked(prepareCreate("test")
+            .addMapping("type1", "text", "type=text,boost=4"));
+
+        indexRandom(true,
+            client().prepareIndex("test", "type1", "1").setSource("text", "foo bar"));
+        SearchResponse searchResponse = client().prepareSearch("test")
+            .setQuery(QueryBuilders.matchPhrasePrefixQuery("text", "fo"))
+            .get();
+        assertHitCount(searchResponse, 1L);
+    }
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/search/query/SearchQueryIT.java]: would be nice to have a unit test rather than an integration test for this

**Review by jpountz — COMMENTED** [review]
I left some comments.

**Comment by jimczi** [comment]
Thanks @jpountz 
I pushed a commit that replaces the IT with a unit test and applies the field boost to the multiphraseprefix query if needed. Though it does not apply the boost if there is more than one term since the index mapping boost does not work with (multi) phrase query.

**Review by jpountz — APPROVED** [review]
LGTM!
