### PR TITLE
Link to SYSTEM_JAVA_HOME on windows

### LINKED ISSUE #40797: Investigate and fix test53JavaHomeWithSpecialCharacters failures
the test is failing during link creation / removal on windows. Need to be investigated

### PR DESCRIPTION
**Pull request by rjernst**
We don't always have java home defined in packaging tests, as we want to
use the bundled jdk most of the time. This commit fixes the java home
with special characters test to link to SYSTEM_JAVA_HOME on windows.

closes #40797

### CODE REVIEW

**Comment by rjernst** [comment]
Note I only put 8.0 on here as it looks like the backports of #39712 have not yet been merged (and should incorporate this fix once it is in).

File: qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java [hunk 1]
```diff
@@ -218,7 +218,7 @@ public void test53JavaHomeWithSpecialCharacters() throws Exception {
 
             } finally {
                 //clean up sym link
-                sh.run("cmd /c del /F /Q 'C:\\Program Files (x86)\\java' ");
+                sh.run("cmd /c rmdir 'C:\\Program Files (x86)\\java' ");
```
Comment (pgomulka) [inline qa/vagrant/src/main/java/org/elasticsearch/packaging/test/ArchiveTestCase.java]: Hopefully it will pass, but I think the problem is the path with spaces (apostrophes didn't help) . Note that del command should pass when run on windows.
If it still fails I would use fileutils.rm

**Review by pgomulka — APPROVED** [review]
Probably worthy to run windows tests from command line as they might not be include in package sample.
If the fix in cleanup works then this lgtm

**Comment by rjernst** [comment]
>  run windows tests from command line as they might not be include in package sample.

The packaging label triggers a full run of packaging tests, which include windows VMs. I will double check the CI output to ensure windows was run.
