### PR TITLE
Reduce Memory Use of Parallel Azure Blob Deletes

### LINKED ISSUE #71267: Deleting 300k stale blobs from an Azure repo leads to an OOM
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12.0

**Plugins installed**: Cloud + `repository-azure`

**JVM version** (`java -version`): Bundled

**OS version** (`uname -a` if on a Unix-like system): Cloud

**Description of the problem including expected versus actual behavior**:

We received a report of a cluster running on Azure where the master would fail with an OOME every 30 minutes. A heap dump suggests it was trying to delete some 300k stale blobs from the repository at the time.

**Steps to reproduce**:

Currently unknown how we got into this state, but once in this state it can't get out of it.

**Provide logs (if relevant)**:

See linked support case for logs/diagnostics/heap dump and other info.

### PR DESCRIPTION
**Pull request by original-brownbear**
1. Limit the number of blob deletes to execute in parallel to `100`.
2. Use flat listing when deleting a directory to require fewer listings
in between deletes and keep the code simpler. (and adjust the list request counting to also count flat listings correctly)

closes #71267

### CODE REVIEW

File: plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java [hunk 1]
```diff
@@ -216,91 +214,80 @@ public boolean blobExists(String blob) throws IOException {
         }
     }
 
+    // number of concurrent blob delete requests to use while bulk deleting
+    private static final int CONCURRENT_DELETES = 100;
```
Comment (original-brownbear) [inline plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java:218]: Admittedly a totally random choice of parallelism. But I figured we used up to 50 threads in the old SDK, this is certainly cheaper than additional threads -> lets at least double the concurrency.

Comment (DaveCTurner) [reply plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java:218]: TBH I was expecting a higher limit :) Do you have a sense of the performance impact here?

Comment (original-brownbear) [reply plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/AzureBlobStore.java:218]: >  Do you have a sense of the performance impact here?

It's pretty hard to guess with the buffering overhead from Netty sending out request etc. so I figured I'd stay on the safe side. I think it's a fair guess to assume something like 2k IO buffer overhead per request and then some extra bytes for all the state handling.

> TBH I was expecting a higher limit :) 

I didn't benchmark it but I wonder how much that will even get us in terms of throughput. This isn't a batch size, this is a concurrent requests limit. So assuming 100ms latency per request this means 1k/s and it's not a global limit so concurrent delete calls would multiply this limit.
We don't really have any benchmarking here and Azure doesn't give a target request rate for deletes but their target rate for operations on a single blob is 500/s (the rate target for deletes is probably higher than this) but I figured 10x that if we run 5 snapshot threads in parallel across all blobs is a reasonable guess?

**Review by fcofdez — APPROVED** [review]
LGTM, thanks for taking care of this 👍

**Comment by fcofdez** [comment]
I was a bit concerned about using the reactor primitives to limit the concurrency as it seems like in some parts of the SDK the reactive contract is not followed (i.e. for blob downloads even if you request just 1 byte it would bring more data) but for the uses in this PR it seems to work fine 👍.

**Comment by original-brownbear** [comment]
Thanks Francisco!

> but for the uses in this PR it seems to work fine

Yea I remembered that but it seems that the bytes flux path is different for some reason.
