### PR TITLE
Fix range query edge cases

### LINKED ISSUE #40937: [CI] RangeQueryBuilderTests fails reproducibly
It failed on CI for `7.0`, but reproduces on master
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+intake/654/console

```
./gradlew :server:unitTest -Dtests.seed=C6257F2747659030 -Dtests.class=org.elasticsearch.index.query.RangeQueryBuilderTests -Dtests.method="testToQuery" -Dtests.security.manager=true -Dtests.locale=sk -Dtests.timezone=Asia/Kolkata -Dcompiler.java=12 -Druntime.java=12

ERROR   1.74s | RangeQueryBuilderTests.testToQuery <<< FAILURES!
   > Throwable #1: java.lang.IllegalArgumentException: min value (101) is greater than max value (100)
```

### PR DESCRIPTION
**Pull request by cbuescher**
Currently we throw an error when a range querys minimum value exceeds the
maximum value due to the fact that they are neighbouring values and both
upper and lower value are excluded from the interval. Since this is a condition
that the user usually doesn't specify conciously (at least in the case of float
and double values its difficult to see which values are adjacent) we should
ignore those "wrong" intervals and create a MatchNoDocsQuery in those cases.

We should still throw errors with an actionable message if the user specifies
the query interval in a way that min value > max value. This PR adds those
checks and tests for those cases.

Closes #40937

### CODE REVIEW

**Comment by cbuescher** [comment]
@not-napoleon you showed some interest in this case, would you mind taking a look?

File: server/src/main/java/org/elasticsearch/index/mapper/RangeFieldMapper.java [hunk 1]
```diff
@@ -662,21 +678,33 @@ public Field getRangeField(String name, Range r) {
...
+                        (f, t) -> FloatRange.newIntersectsQuery(field, new float[] { f }, new float[] { t }));
+            }
+            
+            private Query createQuery(String field, Object from, Object to, boolean includeFrom, boolean includeTo,
+                    BiFunction<Float, Float, Query> querySupplier) {
+                if ((Float) from > (Float) to) {
+                    // wrong argument order, this is an error the user should fix
+                    throw new IllegalArgumentException("Range query `from` value (" + from + ") is greater than `to` value (" + to + ")");
+                }
+                Float correctedFrom = (Float) from + (includeFrom ? 0 : 1);
```
Comment (not-napoleon) [inline server/src/main/java/org/elasticsearch/index/mapper/RangeFieldMapper.java]: See below comment for doubles ranges; floats should also use `nextUp()` instead of just increasing by 1.

**Review by not-napoleon — CHANGES_REQUESTED** [review]
Left comments that need addressing.  Also, this is going to conflict with a PR I'm working on, but you should merge first and I'll fix the conflict in my branch.  This is fixing an actual bug, and I still have test cases to write.

File: server/src/main/java/org/elasticsearch/index/mapper/RangeFieldMapper.java [hunk 2]
```diff
@@ -724,21 +752,33 @@ public Field getRangeField(String name, Range r) {
...
+                        (f, t) -> DoubleRange.newIntersectsQuery(field, new double[] { f }, new double[] { t }));
+            }
+            
+            private Query createQuery(String field, Object from, Object to, boolean includeFrom, boolean includeTo,
+                    BiFunction<Double, Double, Query> querySupplier) {
+                if ((Double) from > (Double) to) {
+                    // wrong argument order, this is an error the user should fix
+                    throw new IllegalArgumentException("Range query `from` value (" + from + ") is greater than `to` value (" + to + ")");
+                }
+                Double correctedFrom = (Double) from + (includeFrom ? 0 : 1);
```
[the remark this answers is not in the document]
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/mapper/RangeFieldMapper.java]: Agreed, I had this in an earlier version of this PR, must have slipped, will update.

File: server/src/main/java/org/elasticsearch/index/mapper/RangeFieldMapper.java (hunk 1 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/mapper/RangeFieldMapper.java]: I think I'll try creating only one  createQuery function...

**Comment by cbuescher** [comment]
@not-napoleon thanks for the feedback, I changed to nextUp/Down and created a single createQuery() method for the numeric types. I left IP out since its a special kind of snowflake and probably easier to handle on its own.

**Review by not-napoleon — APPROVED** [review]

**Comment by not-napoleon** [comment]
LGTM.  

If it was me, I'd put a comment on the static `createQuery` explaining that IP is a special case and gets it's own `createQuery` function, just so someone changing it gets a warning there's a second place to look.  But that's personal preference, so feel free to not if you prefer.

**Comment by cbuescher** [comment]
>  I'd put a comment on the static `createQuery` explaining that IP is a special case

Since there are still test failures that require another re-run I might just do that ;-)

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample
