### PR TITLE
Fixes snapshot status on failed snapshots

### LINKED ISSUE #23716: failed snapshot _status returns 500
When a snapshot fails, the snapshot/_status will return a 500 error. It seems the only way to fetch the actual "FAILED" status is by listing the repository/_all. To me, the 500 exception returned when calling the snapshot/_status seems wrong.

**Elasticsearch version**: 5.2.2

**Plugins installed**: x-pack

``` json
PUT /_snapshot/my_backup
{
  "type": "fs",
  "settings": {
    "compress": true,
    "location": "repo_test"
  }
}

PUT test1

PUT /_snapshot/my_backup/snapshot_1
{
  "indices": "test1",
  "ignore_unavailable": true,
  "include_global_state": false
}

GET _snapshot/my_backup/snapshot_1/_status
` response `
{
  "snapshots": [
    {
      "snapshot": "snapshot_1",
      "repository": "my_backup",
      "uuid": "8KxZ0zSlQFyh77dqvxc3Mw",
      "state": "SUCCESS",

}]}

`make a "bad" index...   `
PUT /_cluster/settings
{
  "transient": {
    "cluster.routing.allocation.enable": "none"
  }
}

PUT test2

PUT /_snapshot/my_backup/snapshot_2
{
  "indices": "test1,test2",
  "ignore_unavailable": true,
  "include_global_state": false
}

GET _snapshot/my_backup/snapshot_2/_status
` response `
{
  "error": {
    "root_cause": [
      {
        "type": "index_shard_restore_failed_exception",
        "reason": "failed to read shard snapshot file",
        "index_uuid": "_f7dq3AMSEejQMZF4sbqYA",
        "shard": "0",
        "index": "test1"
      }
    ],
    "type": "index_shard_restore_failed_exception",
    "reason": "failed to read shard snapshot file",
    "index_uuid": "_f7dq3AMSEejQMZF4sbqYA",
    "shard": "0",
    "index": "test1",
    "caused_by": {
      "type": "no_such_file_exception",
      "reason": "/Users/jared/tmp/repo_test/indices/5H7x7fA-QsK7xqs6MdO0Bw/0/snap-2XWQ_Sd4QMCdSo1wU4VkoA.dat"
    }
  },
  "status": 500
}

GET /_snapshot/my_backup/_all?filter_path=*.snapshot,*.state
` response `
{
  "snapshots": [
    {
      "snapshot": "snapshot_1",
      "state": "SUCCESS"
    },
    {
      "snapshot": "snapshot_2",
      "state": "FAILED"
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by abeyad**
If a snapshot is taken on multiple indices, and some of them are "good"
indices that don't contain any corruption or failures, and some of them
are "bad" indices that contain missing shards or corrupted shards, and
if the snapshot request is set to partial=false (meaning don't take a
snapshot if there are any failures), then the good indices will not be
snapshotted either.  Previously, when getting the status of such a
snapshot, a 500 error would be thrown, because the snap-*.dat blob for
the shards in the good index could not be found.

This commit fixes the problem by reporting shards of good indices as
failed due to a failed snapshot, instead of throwing the
NoSuchFileException.

Closes #23716

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -577,14 +582,42 @@ private SnapshotInfo inProgressSnapshot(SnapshotsInProgress.Entry entry) {
...
             }
         }
+        for (Map.Entry<ShardId, IndexId> shard : nonFailedShards.entrySet()) {
+            final ShardId shardId = shard.getKey();
+            final IndexId indexId = shard.getValue();
+            IndexShardSnapshotStatus shardSnapshotStatus;
+            try {
+                shardSnapshotStatus = repository.getShardSnapshotStatus(
+                    snapshotInfo.snapshotId(), snapshotInfo.version(), indexId, shardId);
+            } catch (IndexShardRestoreFailedException e) {
```
Comment (dadoonet) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: I was wondering if this logic can be moved inside `repository.getShardSnapshotStatus()` instead?

**Review by dadoonet — COMMENTED** [review]
I just left a small comment but I'll let @imotov approve the PR.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -577,14 +582,42 @@ private SnapshotInfo inProgressSnapshot(SnapshotsInProgress.Entry entry) {
                         shardSnapshotStatus.updateStage(IndexShardSnapshotStatus.Stage.FAILURE);
                         shardSnapshotStatus.failure(shardFailure.reason());
                         shardStatus.put(shardId, shardSnapshotStatus);
+                        hasFailedShards = true;
                     } else {
-                        IndexShardSnapshotStatus shardSnapshotStatus =
-                            repository.getShardSnapshotStatus(snapshotInfo.snapshotId(), snapshotInfo.version(), indexId, shardId);
-                        shardStatus.put(shardId, shardSnapshotStatus);
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: So, the problem here is that these calls are always failing when the snapshot is in a FAILED state, right? So, wouldn't it it make sense to not even try to call getShardSnapshotStatus if snapshot failed by just wrapping these 3 lines into a an if statement that checks if the snapshot has a failed status and simply generate the fake shard status you are generating in line 609 below.

**Review by imotov — COMMENTED** [review]
It would work, but I think we can simplify it a bit.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 2 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: @imotov is correct, we only need to check the snapshot status here and execute the read based on it, I pushed https://github.com/elastic/elasticsearch/pull/23833/commits/45c994d98b955c834aa8533de21e54d3798199c5

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 1 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: @dadoonet the problem here is that I need to depend on the snapshot status itself now (see https://github.com/elastic/elasticsearch/pull/23833/commits/45c994d98b955c834aa8533de21e54d3798199c5) to determine if the shard status should be read, and that snapshot status is not passed in to this method.  Otherwise, it would've been a good proposition!

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 3]
```diff
@@ -578,8 +581,28 @@ private SnapshotInfo inProgressSnapshot(SnapshotsInProgress.Entry entry) {
...
+                            // were disabled and in this case, the shard snapshot will
+                            // *not* have any metadata, so attempting to read the shard
+                            // snapshot status will throw an exception.  Instead, we create
+                            // a status for the shard to indicate that the shard snapshot
+                            // could not be taken due to partial being set to false.
+                            shardSnapshotStatus = new IndexShardSnapshotStatus();
+                            shardSnapshotStatus.updateStage(IndexShardSnapshotStatus.Stage.FAILURE);
+                            String msg = "snapshot not taken because partial snapshots are not " +
+                                         "configured for this snapshot and another shard caused " +
+                                         "the snapshot to fail";
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: This will be repeated for every single good shard in the status and might hide the shards that actually caused the issue. Maybe we can say something short here like "skipped". If we want to improve readability, maybe we should improve the error message on the snapshot itself, so we don't have to repeat this for every shard.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 4]
```diff
@@ -60,6 +60,7 @@
 import org.elasticsearch.common.unit.TimeValue;
 import org.elasticsearch.index.Index;
 import org.elasticsearch.index.shard.ShardId;
+import org.elasticsearch.index.snapshots.IndexShardRestoreFailedException;
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: No longer needed

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 5]
```diff
@@ -70,6 +71,7 @@
 import org.elasticsearch.threadpool.ThreadPool;
 
 import java.io.IOException;
+import java.nio.file.NoSuchFileException;
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Same here

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 6]
```diff
@@ -578,8 +581,28 @@ private SnapshotInfo inProgressSnapshot(SnapshotsInProgress.Entry entry) {
                         shardSnapshotStatus.failure(shardFailure.reason());
                         shardStatus.put(shardId, shardSnapshotStatus);
                     } else {
-                        IndexShardSnapshotStatus shardSnapshotStatus =
-                            repository.getShardSnapshotStatus(snapshotInfo.snapshotId(), snapshotInfo.version(), indexId, shardId);
+                        IndexShardSnapshotStatus shardSnapshotStatus;
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: You might want to mark this one as final to ensure that it gets assigned.

**Review by imotov — APPROVED** [review]
Left a couple of minor comments. LGTM.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 4 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: fixed

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 5 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: fixed

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 6 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: done

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 3 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: good idea, i think we can just keep this as "skipped" for now, as that captures the essence of what happened with that shard.

**Comment by abeyad** [comment]
@imotov I pushed 01d4c7b358b5e15dc5309fe6961d07e9e5cb4083 that addresses your feedback.  Thanks for the reviews @imotov @dadoonet
