### PR TITLE
Force using the last centroid during merging

### LINKED ISSUE #111065: ArrayIndexOutOfBoundsException in TDigest library
### Elasticsearch Version

8.16.0

### Installed Plugins

_No response_

### Java Version

17.0.11

### OS Version

Darwin 23.5.0

### Problem Description

While doing some tests with TDigest library (https://github.com/elastic/elasticsearch/tree/main/libs/tdigest) and I am getting this:

```
java.lang.ArrayIndexOutOfBoundsException: Index 30 out of bounds for length 30
```

when using low compression settings. The code: 

```
TDigest td = TDigest.createMergingDigest(10);  
for(int i=0; i<1_000_000;i++) {  
    td.add(between(0, 3_600_000));  
}
```

If I use compression setting of 20, it does not happen. 

### Steps to Reproduce

Just running this code: 

```
```
TDigest td = TDigest.createMergingDigest(10);  
for(int i=0; i<1_000_000;i++) {  
    td.add(between(0, 3_600_000));  
}
```

### Logs (if relevant)

```
java.lang.ArrayIndexOutOfBoundsException: Index 30 out of bounds for length 30

	at __randomizedtesting.SeedInfo.seed([84E0D3DB44015BF7:7ABC623A61BC3D68]:0)
	at org.elasticsearch.tdigest.MergingDigest.merge(MergingDigest.java:325)
	at org.elasticsearch.tdigest.MergingDigest.mergeNewValues(MergingDigest.java:247)
	at org.elasticsearch.tdigest.MergingDigest.mergeNewValues(MergingDigest.java:237)
	at org.elasticsearch.tdigest.MergingDigest.add(MergingDigest.java:222)
	at org.elasticsearch.tdigest.TDigest.add(TDigest.java:105)
	at org.elasticsearch.search.ccs.CrossClusterSearchIT.testTDigest(CrossClusterSearchIT.java:744)	
```
(ignore the last line it's just random test to which I've attached the code to run it)

### PR DESCRIPTION
**Pull request by kkrik-es**
The MergingDigest uses pre-allocated arrays for constant memory footprint and improved performance. Points get added to an intermediate buffer that gets merged to the canonical arrays of means and weights (constituting the centroids). During merging, the values in the latter arrays get updated with the merged values. However, the current logic may try to update a value after the array bound, for values in the very low or very high percentiles. This PR fixes this.

Fixes #111065

### CODE REVIEW

File: libs/tdigest/src/test/java/org/elasticsearch/tdigest/TDigestTests.java [hunk 1]
```diff
@@ -152,7 +152,7 @@ public void testQuantile() {
         hist2.compress();
         double x1 = hist1.quantile(0.5);
         double x2 = hist2.quantile(0.5);
-        assertEquals(Dist.quantile(0.5, data), x1, 0.2);
+        assertEquals(Dist.quantile(0.5, data), x1, 0.25);
```
Comment (kkrik-es) [inline libs/tdigest/src/test/java/org/elasticsearch/tdigest/TDigestTests.java:155]: This is orthogonal, noticed it in CI: https://gradle-enterprise.elastic.co/s/36zxzfevfwrcc

Verified that it happens regardless of the change in `MergingDigest`.

**Review by not-napoleon — APPROVED** [review]

**Comment by kkrik-es** [comment]
Thanks Mark!
