### PR TITLE
Fixing rollup state tests after onFailure ordering change

### LINKED ISSUE #45770: [CI] RollupIndexerStateTests expected STARTED
This test has been failing frequently since ~20th August on 7.x and master

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(build.console-url),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:RollupIndexerStateTests),sort:!(process.time-start,desc))

The error is always `Expected <STARTED> but: was <INDEXING>` e.g. 
```
java.lang.AssertionError: 
Expected: <STARTED>
     but: was <INDEXING>
	at __randomizedtesting.SeedInfo.seed([18DC60842CC79258:4BCFCF641A707760]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.rollup.job.RollupIndexerStateTests.testSearchShardFailure(RollupIndexerStateTests.java:848)

java.lang.AssertionError: 
Expected: <STARTED>
     but: was <INDEXING>
	at __randomizedtesting.SeedInfo.seed([A3064620ADF98E4D:7B10D3C97C30BA3D]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.rollup.job.RollupIndexerStateTests.testUnknownKey(RollupIndexerStateTests.java:692)
```

2 recent failures
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-16.04&&immutable/214/console
https://gradle-enterprise.elastic.co/s/22nlguzfshaxw

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=amazon/214/console
https://gradle-enterprise.elastic.co/s/rr4ygrwt7bvoq

Does not reproduce
```
./gradlew :x-pack:plugin:rollup:test --tests "org.elasticsearch.xpack.rollup.job.RollupIndexerStateTests.testSearchShardFailure" \
  -Dtests.seed=18DC60842CC79258 \
  -Dtests.security.manager=true \
  -Dtests.locale=lt \
  -Dtests.timezone=Europe/Paris \
  -Dcompiler.java=12 \
  -Druntime.java=8


./gradlew :x-pack:plugin:rollup:test --tests "org.elasticsearch.xpack.rollup.job.RollupIndexerStateTests.testUnknownKey" \
  -Dtests.seed=A3064620ADF98E4D \
  -Dtests.security.manager=true \
  -Dtests.locale=es-MX \
  -Dtests.timezone=America/Kentucky/Monticello \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

#45757 may fix `RollupIndexerStateTests::testBulkFailure` but there are other tests in the suite failing.

### PR DESCRIPTION
**Pull request by benwtrent**
After the PR https://github.com/elastic/elasticsearch/pull/45676 `onFailure` is now called before the indexer state has transitioned out of indexing. 

To fix these tests, I added a new check to make sure that we don't mark it as failed until AFTER doSaveState is called with a `STARTED` indexer.

Sorry for missing these test changes in the earlier PR.

closes https://github.com/elastic/elasticsearch/issues/45770

### CODE REVIEW

**Comment by benwtrent** [comment]
I ran locally with this change 10k+ times and it never failed. Without this change I would get periodic failures (matching the closed issue).

File: x-pack/plugin/rollup/src/test/java/org/elasticsearch/xpack/rollup/job/RollupIndexerStateTests.java [hunk 1]
```diff
@@ -946,10 +956,11 @@ protected void doNextBulk(BulkRequest request, ActionListener<BulkResponse> next
             assertTrue(indexer.maybeTriggerAsyncJob(System.currentTimeMillis()));
             assertThat(indexer.getState(), equalTo(IndexerState.INDEXING));
             latch.countDown();
+            assertBusy(() -> assertTrue(isFinished.get()));
             ESTestCase.awaitBusy(() -> isFinished.get());
```
Comment (jakelandis) [inline x-pack/plugin/rollup/src/test/java/org/elasticsearch/xpack/rollup/job/RollupIndexerStateTests.java]: nitpick: I think this awaitBusy can be removed. If the assertBusy above passes, this will always pass (unless there is some async condition that can change back to false). If the assertBusy fails if will fail the test and this line wont execute.

Comment (benwtrent) [reply x-pack/plugin/rollup/src/test/java/org/elasticsearch/xpack/rollup/job/RollupIndexerStateTests.java]: You are correct! Let me fix it up really quick.

**Review by polyfractal — APPROVED** [review]
Changes to the flow of state LGTM :)
