### PR TITLE
[Transform] Do not log error on node restart when the transform is already failed.

### LINKED ISSUE #106168: [Transform] Inability to start a failed transform causes log spam
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

In the transform logs, we can see:
```
Failed to start task [XXX] in node operation
Unable to start transform [XXX] as it is in a failed state with failure: ...
```

If the transform is already failed then this message is just a log spam as it will be logged every time the node is restarted.

### Steps to Reproduce

Take a failed transform that is assigned to a node
Restart the node
Observe error message being logged

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by przemekwitek**
Currently, when the transform persistent task is being started by the persistent task executor and the transform is in the `FAILED` state, the error is logged. 
If the transform is already failed then this message is just a log spam as it will be logged every time the node is restarted.
This PR makes a distinction and only logs at `INFO` level if the transform persistent task is being started while the transform is already failed.

Additionally, this PR reduces code duplication in `AbstractAuditor` class.

Closes https://github.com/elastic/elasticsearch/issues/106168

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java [hunk 1]
```diff
@@ -240,9 +240,8 @@ void start(Long startingCheckpoint, ActionListener<StartTransformAction.Response
         logger.debug("[{}] start called with state [{}].", getTransformId(), getState());
         if (context.getTaskState() == TransformTaskState.FAILED) {
             listener.onFailure(
-                new ElasticsearchStatusException(
-                    TransformMessages.getMessage(CANNOT_START_FAILED_TRANSFORM, getTransformId(), context.getStateReason()),
-                    RestStatus.CONFLICT
```
Comment (prwhelan) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:245]: This wasn't even making it back to the user as a `409` right? Because it gets consumed in the `startTaskListener`?

**Review by prwhelan — APPROVED** [review]

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java (hunk 1 above)
Comment (przemekwitek) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java:245]: That's correct.
Primary reason it could not make it back to the user was that this is an asynchronous operation performed on a transform persistent task, **not** user-initiated API call.
