### PR TITLE
Preserve deployments with zero allocations during assignment planning

### LINKED ISSUE #137134: [ML] Old trained model deployment got deleted unexpectedly after a new one is added through inference API
**Version**:
9.2.0

**Step to reproduce:**
0. Update the `scale_to_zero_time` setting to 1 minutes
```
PUT /_cluster/settings
{
  "persistent": {
    "xpack.ml.trained_models.adaptive_allocations.scale_to_zero_time": "1m"
  }
}
```
1. Create an inference endpoint,
```
PUT _inference/rerank/mytest-old
{
    "service": "elasticsearch",
      "service_settings": {
        "num_threads": 1,
        "model_id": ".rerank-v1",
        "adaptive_allocations": {
          "enabled": true,
          "min_number_of_allocations": 0,
          "max_number_of_allocations": 2
        }
      }
}
```
2. After trained model deployed and started (can use `GET _ml/trained_models/_stats` to check stats), wait couple minutes until the number_of_allocations turns to 0: `"number_of_allocations": 0`
3. Create another inference endpoint,
```
PUT _inference/rerank/mytest-new
{
    "service": "elasticsearch",
      "service_settings": {
        "num_threads": 1,
        "model_id": ".rerank-v1",
        "adaptive_allocations": {
          "enabled": true,
          "min_number_of_allocations": 0,
          "max_number_of_allocations": 2
        }
      }
}
```

4. then run `GET _ml/trained_models/_stats`

the previous `mytest-old` model deployment got deleted unexpectedly.

**Note:**
it can be reproduced on 9.1.0, but not on 8.19.5

### PR DESCRIPTION
**Pull request by jan-elastic**
Fixes #137134

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlanner.java [hunk 1]
```diff
@@ -99,7 +104,8 @@ public AssignmentPlan computePlan(boolean tryAssigningAllPreviouslyAllocatedMode
 
         logger.debug(() -> "Best plan =\n" + bestPlan.prettyPrint());
         logger.debug(() -> prettyPrintOverallStats(bestPlan));
-        return bestPlan;
+
+        return bestPlan.withDeploymentsWithZeroAllocations(deploymentsWithZeroAllocations);
```
Comment (DonalEvans) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlanner.java]: Should the debug logging be for the `AssignmentPlan` that's actually returned from this method?

**Review by jonathan-buttner — COMMENTED** [review]
I did some manual testing and confirmed this works. I'll do some more testing tomorrow as well though 👍

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlanner.java (hunk 1 above)
Comment (jan-elastic) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlanner.java]: That doesn't change anything. The `prettyPrint` returns one node per line, with a list of every allocation running on that node. 

It does require some rewriting, because 
```logger.debug(() -> "Best plan =\n" + bestPlan.prettyPrint())```
doesn't work anymore (the lambda needs something effectively final), so I didn't bother.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java [hunk 2]
```diff
@@ -315,6 +314,14 @@ private Quality computeQuality() {
         return new Quality(isSatisfyingPreviousAssignments, weighedAllocationsScore, memoryScore);
     }
 
+    public AssignmentPlan withDeploymentsWithZeroAllocations(Collection<Deployment> deploymentsWithZeroAllocations) {
+        Map<Deployment, Map<Node, Integer>> newAssignments = new HashMap<>(assignments);
+        for (Deployment deployment : deploymentsWithZeroAllocations) {
+            newAssignments.put(deployment, Collections.emptyMap());
+        }
+        return new AssignmentPlan(newAssignments, remainingNodeMemory, remainingNodeCores, remainingModelAllocations);
```
Comment (valeriy42) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java]:
```suggestion
    public AssignmentPlan withDeploymentsWithZeroAllocations(Collection<Deployment> deploymentsWithZeroAllocations) {
        Map<Deployment, Map<Node, Integer>> newAssignments = new HashMap<>(assignments);
        Map<Deployment, Integer> newRemainingModelAllocations = new HashMap<>(remainingModelAllocations);
        for (Deployment deployment : deploymentsWithZeroAllocations) {
            newAssignments.put(deployment, Collections.emptyMap());
            newRemainingModelAllocations.put(deployment, 0);
        }
        return new AssignmentPlan(newAssignments, remainingNodeMemory, remainingNodeCores, newRemainingModelAllocations);
```

I would add the zero-allocation deployments to the `remainingModelAllocations` map for consistency. Right now it work fine even without this change, since `satisfiesAllocations()` handles missing deployments as if they have 0 remaining allocations, but if we rely on having all deployments in `remainingModelAllocations` elsewhere in the code, it may introduce a subtle bug.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java [hunk 3]
```diff
@@ -315,6 +314,14 @@ private Quality computeQuality() {
         return new Quality(isSatisfyingPreviousAssignments, weighedAllocationsScore, memoryScore);
     }
 
+    public AssignmentPlan withDeploymentsWithZeroAllocations(Collection<Deployment> deploymentsWithZeroAllocations) {
+        Map<Deployment, Map<Node, Integer>> newAssignments = new HashMap<>(assignments);
+        for (Deployment deployment : deploymentsWithZeroAllocations) {
+            newAssignments.put(deployment, Collections.emptyMap());
```
Comment (valeriy42) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java:335]: nit: This shouldn't happen in general, but maybe you should assert that `deployment` is not in `assignments` already to be defensive. Otherwise, it will be overwritten by an empty map.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java
Comment (valeriy42) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java:353]:
```suggestion
            for (Node n : assignments.get(m).keySet()) { // Note: zero-allocation deployments are not printed
```
nit: zero-allocation deployments will have an empty map. So they won't be pretty-printed. Maybe either comment this nuance or extend `prettyPrint()` to handle zero-allocation deployments as well.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java [hunk 4]
```diff
@@ -315,6 +314,14 @@ private Quality computeQuality() {
         return new Quality(isSatisfyingPreviousAssignments, weighedAllocationsScore, memoryScore);
     }
 
+    public AssignmentPlan withDeploymentsWithZeroAllocations(Collection<Deployment> deploymentsWithZeroAllocations) {
```
Comment (valeriy42) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java]:
```suggestion
    public AssignmentPlan withZeroAllocationDeployments(Collection<Deployment> deploymentsWithZeroAllocations) {
```

nit: very minor, maybe a shorter naming alternative.

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlannerTests.java [hunk 5]
```diff
@@ -1165,7 +1167,28 @@ public void testGivenClusterResize_ShouldRemoveAllocatedDeployments_NewMemoryFie
...
+            0,
+            new AdaptiveAllocationsSettings(true, 0, 42),
+            0,
+            0
+        );
+
+        AssignmentPlan assignmentPlan = new AssignmentPlanner(List.of(node), List.of(deployment)).computePlan();
 
+        assertThat(assignmentPlan.deployments(), contains(deployment));
+        assertThat(assignmentPlan.getRemainingNodeMemory(node.id()), equalTo(ByteSizeValue.ofGb(4).getBytes()));
```
Comment (valeriy42) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlannerTests.java:1193]:
```suggestion
        assertThat(assignmentPlan.deployments(), contains(deployment));
        assertThat(assignmentPlan.assignments(deployment), isEmpty());
        assertThat(assignmentPlan.satisfiesAllocations(deployment), is(true));
        assertThat(assignmentPlan.getRemainingNodeMemory(node.id()), equalTo(ByteSizeValue.ofGb(4).getBytes()));
```

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlannerTests.java [hunk 6]
```diff
@@ -1165,7 +1167,28 @@ public void testGivenClusterResize_ShouldRemoveAllocatedDeployments_NewMemoryFie
         assertThat(indexedBasedPlan.get("m_1"), equalTo(Map.of("n_1", 2)));
         assertThat(assignmentPlan.getRemainingNodeMemory(node1.id()), greaterThanOrEqualTo(0L));
         assertThat(assignmentPlan.getRemainingNodeCores(node1.id()), greaterThanOrEqualTo(0));
+    }
+
+    public void testDeploymentWithZeroAllocationsIsPreserved() {
```
Comment (valeriy42) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlannerTests.java]: Some more ideas for test cases to ensure we don't have more bugs:
- Multiple zero-allocation deployments mixed with non-zero deployments
- Edge case where all deployments have zero allocations
- Zero-allocation deployment that previously had allocations (maxAssignedAllocations > 0 but allocations == 0)
```java
// Deployment that previously had allocations but now has zero
Deployment deployment = new Deployment(
    "m_1", "m_1", ByteSizeValue.ofMb(500).getBytes(),
    0, // allocations = 0
    1,
    Map.of("n_1", 2), // previously had allocations on n_1
    2, // maxAssignedAllocations = 2
    new AdaptiveAllocationsSettings(true, 0, 42),
    0, 0
);
```

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java (hunk 4 above)
Comment (valeriy42) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlan.java]:
```suggestion
/**
 * Adds deployments with zero allocations to this plan. These deployments
 * are preserved in the plan but have no node assignments. This ensures
 * that deployments configured with zero allocations are not lost during
 * planning.
 * 
 * Deployments with zero allocations are filtered out during the planning
 * process (since they don't require assignment), but they need to be preserved
 * in the final plan so that deployment state is maintained correctly.
 *
 * @param deploymentsWithZeroAllocations deployments to add with empty assignments
 * @return a new plan containing the original assignments plus the zero-allocation deployments
 */
    public AssignmentPlan withDeploymentsWithZeroAllocations(Collection<Deployment> deploymentsWithZeroAllocations) {
```

**Review by valeriy42 — APPROVED** [review]
Great work on figuring out the bug! 🚀 You have my approve. ✅  I left a couple of non-essential comments and suggestions.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlanner.java (hunk 1 above)
Comment (DonalEvans) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlanner.java]: Would there be any value in modifying `prettyPrint()` to include deployments with zero allocations in the logging, or is that overkill?

Comment (jan-elastic) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/planning/AssignmentPlanner.java]: I've added it now; not sure whether it's overkill
