### PR TITLE
Limit the number of nested documents

### LINKED ISSUE #26962: Limit the number of nested documents
There is already a limit on the number of nested fields per index (#14983). However that doesn't stop anyone from adding many nested json objects to a nested field inside a single document. 

I believe we should add at least a soft limit to the number of nested Lucene documents that we index per json document. This to avoid a node going OOM when a single document contains too many nested json objects a node can handle indexing. While indexing we check the number of nested docs and if they go beyond a threshold (maybe 10000?) then we should abort and fail with an error.

Relates to #11511

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Add an index level setting `index.mapping.nested_objects.limit` to control
the number of nested json objects that can be in a single document
across all fields. Defaults to 10000.

Throw an error if the number of created nested documents exceed this
limit during the parsing of a document.

Closes #26962

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
Hi @mayya-sharipova, I did a first round of review and left a couple of comments, mostly minor. The change looks good already, can you please also add test that show that the default values work as expected (e.g. intergration tests) and maybe a rest test for a small setting (like the ones in the unit test you already have)

File: core/src/main/java/org/elasticsearch/index/mapper/ParseContext.java [hunk 1]
```diff
@@ -321,6 +325,8 @@ public InternalParseContext(@Nullable Settings indexSettings, DocumentMapperPars
             this.version = null;
             this.sourceToParse = source;
             this.dynamicMappers = new ArrayList<>();
+            this.maxAllowedNumNestedDocs = indexSettings.getAsLong(MapperService.INDEX_MAPPING_NESTED_DOCS_LIMIT_SETTING.getKey(), 10000L);
```
[the remark this answers is not in the document]
Comment (mayya-sharipova) [reply core/src/main/java/org/elasticsearch/index/mapper/ParseContext.java]: @cbuescher thanks Christoph! I agree it is strange to define the constant in two places, but so far did not find the way. I will investigate more  the way to define it a single place only.

File: core/src/main/java/org/elasticsearch/index/mapper/ParseContext.java [hunk 2]
```diff
@@ -366,6 +372,13 @@ public Document doc() {
 
         @Override
         protected void addDoc(Document doc) {
```
[the remark this answers is not in the document]
Comment (martijnvg) [reply core/src/main/java/org/elasticsearch/index/mapper/ParseContext.java]: @cbuescher Yes, this method only invoked to add nested documents. The Lucene document for the non nested parts of the document being indexed is added to the `documents` list in the constructor of this class.

**Comment by mayya-sharipova** [comment]
@cbuescher Christoph, thanks for your review. I have tried to address your comments in the 2nd commit, can you please continue/finalize the review when you have available time.
The only thing I am not sure is what you meant by "migration notest" in your comment: "maybe worth adding to the migration notest and docs as well".

File: rest-api-spec/src/main/resources/rest-api-spec/test/create/70_nested.yml [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+                  test_type:
+                      properties:
+                          nested1:
+                              type: nested
+
+---
+"Indexing a doc with No. nested objects less or equal to index.mapping.nested_objects.limit should succeed":
+  - skip:
+      version: " - 6.99.99"
+      reason:  index.mapping.nested_objects setting was introduced from this version
```
Comment (cbuescher) [inline rest-api-spec/src/main/resources/rest-api-spec/test/create/70_nested.yml]: nit: can you slightly rephrase so the version this feature was introduced is in the "reason" description (e.g. something like "the XYZ feature has been added in 7.0.0")? I think the skip "reason" is printed when running the tests and it might be useful to see the reason including the version at a glance.

File: rest-api-spec/src/main/resources/rest-api-spec/test/create/70_nested.yml [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+          id:     1
+          body:
+              "nested1" : [ { "foo": "bar" }, { "foo": "bar2" } ]
+  - match:   { _version: 1}
+
+---
+"Indexing a doc with No. nested objects more than index.mapping.nested_objects.limit should fail":
+  - skip:
+      version: " - 6.99.99"
+      reason:  index.mapping.nested_objects setting was introduced from this version
```
Comment (cbuescher) [inline rest-api-spec/src/main/resources/rest-api-spec/test/create/70_nested.yml]: same here

File: core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java [hunk 5]
```diff
@@ -524,4 +524,137 @@ public void testParentObjectMapperAreNested() throws Exception {
...
     }
 
+    public void testLimitNestedDocsDefaultSettings() throws Exception{
+        MapperService mapperService = createIndex("test1", Settings.builder().build()).mapperService();
+        String mapping = XContentFactory.jsonBuilder().startObject().startObject("type").startObject("properties")
+            .startObject("nested1").field("type", "nested").endObject()
+            .endObject().endObject().endObject().string();
+        DocumentMapper docMapper = mapperService.documentMapperParser().parse("type", new CompressedXContent(mapping));
+
+        // parsing a doc with 3 nested objects succeeds
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: I think the case where #nested_docs < limit is already covered by the later tests, could you change this to that the the document has more than the default number of nested docs (simple loop) and gets rejected? This way we can test the default value works if no explicit setting is there. I'd also check if that unit test then takes a lot more time (which I doubt, gut feeling check is okay here I think)

**Review by cbuescher — COMMENTED** [review]
@mayya-sharipova thanks a lot, this looks very close. I left one more comment about testing the default setting and two nits, scratch my previous comment about "migration notest", I didn't see they were already there.

File: core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java [hunk 6]
```diff
@@ -525,35 +525,42 @@ public void testParentObjectMapperAreNested() throws Exception {
...
+        // parsing a doc with No. nested objects > defaultMaxNoNestedDocs fails
         XContentBuilder docBuilder = XContentFactory.jsonBuilder();
         docBuilder.startObject();
         {
             docBuilder.startArray("nested1");
             {
-                docBuilder.startObject().field("field1", "11").field("field2", "21").endObject();
-                docBuilder.startObject().field("field1", "12").field("field2", "22").endObject();
-                docBuilder.startObject().field("field1", "13").field("field2", "23").endObject();
+                for(int i=0; i<=defaultMaxNoNestedDocs; i++) {
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: nit: some whitespaces around the operators etc... would be nice

File: core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java [hunk 7]
```diff
@@ -525,35 +525,42 @@ public void testParentObjectMapperAreNested() throws Exception {
...
+                    docBuilder.startObject().field("f", i).endObject();
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: I'm suprised this triggers the no. fields warnings since "f" is not the field thats defined with the "nested" type above? I would have expected this to not trigger the limit but the exception tested below seems to indicate it triggers the setting. What am I missing?

File: core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java [hunk 8]
```diff
@@ -525,35 +525,42 @@ public void testParentObjectMapperAreNested() throws Exception {
...
+                + "]. This limit can be set by changing the [" + MapperService.INDEX_MAPPING_NESTED_DOCS_LIMIT_SETTING.getKey()
+                + "] index level setting.",
+            e.getMessage()
+        );
     }
 
     public void testLimitNestedDocs() throws Exception{
         // setting limit to allow only two nested objects in the whole doc
-        long nested_docs_limit = 2L;
+        long maxNoNestedDocs = 2L;
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: just as feedback, nothing to change really, but I liked the previous variable name better ;-)

**Review by cbuescher — COMMENTED** [review]
@mayya-sharipova thanks a lot, this looks amost ready, I'm just a bit confused about the new test that checks the default setting and why it works (see line comment). Maybe you can clarify that, other than that I think this PR is ready.

File: core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java (hunk 7 above)
Comment (mayya-sharipova) [reply core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: @cbuescher Please correct me if  I  misunderstood your previous comment: "could you change this to that the the document has more than the default number of nested docs (simple loop) and gets rejected". 
This is what this new test is about.
We have a parent nested field `nested1` under which we have many json objects with a field `f`, and since the number of these json objects is more than the default number, we get an error.

File: core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java (hunk 8 above)
Comment (mayya-sharipova) [reply core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: @cbuescher thanks for the feedback, I thought in the previous variable names I did not follow Java camel case standards for variable names (was more of python style)

Comment (cbuescher) [reply core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: I see, and you are right, camel case is preferred. I probably misread the "NoNestedDocs" part of the name as "no nested docs" and that confused me for a second, but either way is fine.

File: core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java (hunk 7 above)
Comment (cbuescher) [reply core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: Thanks, I probably read the test to quickly and missed the startArray() part. You are absolutely right, this is how I expected the test. Sorry for the noise.

**Review by cbuescher — APPROVED** [review]
LGTM, thanks for bearing with me @mayya-sharipova ;-)

File: core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java (hunk 8 above)
Comment (mayya-sharipova) [reply core/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java]: @cbuescher thanks Christoph, you are right`NoNestedDocs` is confusing, I will avoid using `No` for "number of" in the future.

**Review by martijnvg — APPROVED** [review]
LGTM
