### PR TITLE
Prevent index level setting from being configured on a node level

### LINKED ISSUE #16799: Forbid settings index level settings on a node level
Today we allow to set all kinds of index level settings on the node level which is error prone and difficult to get right in a consistent manner. For instance if some analyzers are setup in a yaml config file some nodes might not have these analyzers and then index creation fails. For settings that should have node level defaults like the default codec we should add dedicated settings.

### PR DESCRIPTION
**Pull request by s1monw**
Today we allow to set all kinds of index level settings on the node level which
is error prone and difficult to get right in a consistent manner.
For instance if some analyzers are setup in a yaml config file some nodes might
not have these analyzers and then index creation fails.

Nevertheless, this change allows some selected settings to be specified on a node level
for instance:
- `index.codec` which is used in a hot/cold node architecture and it's value is really per node or per index
- `index.store.fs.fs_lock` which is also dependent on the filesystem a node uses

All other index level setting must be specified on the index level. For existing clusters the index must be closed
and all settings must be updated via the API on each of the indices.

Closes #16799

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/engine/EngineConfig.java [hunk 1]
```diff
@@ -69,20 +71,28 @@
...
-                if (Codec.availableCodecs().contains(s) == false) { // we don't error message the not officially supported ones
-                    throw new IllegalArgumentException("unknown value for [index.codec] must be one of [default, best_compression] but was: " + s);
-                }
-                return s;
-        }
-    }, Property.IndexScope);
+    public static final Setting<String> INDEX_CODEC_SETTING = new Setting<>("index.codec", "default", parseCodec("index.codec"),
+        Property.IndexScope, Property.NodeScope);
+
+    private static Function<String, String> parseCodec(String setting) {
```
Comment (nik9000) [inline core/src/main/java/org/elasticsearch/index/engine/EngineConfig.java]: Maybe just declare a static method and use a method reference for it?

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/engine/EngineConfig.java]: that is really a leftover from refactoring I will move back to waht it was

**Comment by rjernst** [comment]
LGTM
