### PR TITLE
[Rollup] Proactively resolve index patterns in RollupSearch endoint

### LINKED ISSUE #34828: Rollup search endpoint fails on wildcard index pattern
I have defined a rollup job, ran it, and the rollup index is called `jen-rollup`.

Sending a search request request with the index name (`GET jen-rollup/_rollup_search`) directly returns correct results.

But sending the request with an asterisk at the end of the index name (`GET jen-rollup*/_rollup_search`) returns no results.

Per documentation, `index` can be `Index, indices or index-pattern to execute a rollup search against. This can include both rollup and non-rollup indices.` Docs also state `Only one rollup index may be specified. If more than one are supplied an exception will be thrown`.

Given these two criteria, I would expect that since `jen-rollup*` only matches one rollup index, querying it should give the same results as querying `jen-rollup`.

Example query that returns no results with `*`, but correct results without:

```
GET jen-rollup*/_rollup_search
{
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "60m",
        "time_zone": "UTC",
        "min_doc_count": 1
      }
    }
  },
  "size": 0,
  "_source": {
    "excludes": []
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [
    {
      "field": "@timestamp",
      "format": "date_time"
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "@timestamp": {
              "gte": 1539808778039,
              "lte": 1540413578039,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "filter": [
        {
          "match_all": {}
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```

### PR DESCRIPTION
**Pull request by polyfractal**
This changes the RollupSearch endpoint to proactively resolve index patterns. 

Today, we assume any index that doesn't have a rollup cap to be a raw/live index.  But if the user specifies a wildcard pattern on a rollup index (`rollup-foo*`), this causes a problem.  We can't find an index that matches the exact string `"rollup-foo*"` so we assume it is a live index and pass it off to the regular Search endpoint.  Search resolves that to the rollup index, searches it but gets no hits because none of the names match.  The result is an empty search response that doesn't make sense to the user.

Instead, we should resolve index patterns up front in the RollupSearch endpoint.  If the index pattern(s) match more than one rollup index, an exception is thrown just like before.  But if the pattern only matches one rollup index, execution is allowed to continue.  

Regular indices continue to function as before, the only difference is that we resolve the pattern and search with a list instead of the pattern (e.g. search for `logstash-1,logstash-2,logstash-3` instead of `logstash-*`).

Also tweaks the documentation to make this clear.

Closes #34828

Kibana has requested this as blocker for 6.5.  The change is pretty minimal and should be safe I think.  I don't think it would be the end of the world if it slipped to 6.5.1 though.

### CODE REVIEW

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportRollupSearchAction.java [hunk 1]
```diff
@@ -401,9 +403,10 @@ static RollupSearchContext separateIndices(String[] indices, ImmutableOpenMap<St
         });
         assert normal.size() + rollup.size() > 0;
         if (rollup.size() > 1) {
-            throw new IllegalArgumentException("RollupSearch currently only supports searching one rollup index at a time.");
+            throw new IllegalArgumentException("RollupSearch currently only supports searching one rollup index at a time. " +
+                "Found the following rollup indices: " + rollup);
         }
-        return new RollupSearchContext(normal.toArray(new String[normal.size()]), rollup.toArray(new String[rollup.size()]), jobCaps);
+        return new RollupSearchContext(normal.toArray(new String[0]), rollup.toArray(new String[0]), jobCaps);
```
Comment (jimczi) [inline x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportRollupSearchAction.java]: This reminds me a recent email ;)

File: x-pack/plugin/src/test/resources/rest-api-spec/test/rollup/rollup_search.yml [hunk 2]
```diff
@@ -708,5 +708,86 @@ setup:
...
+      xpack.rollup.rollup_search:
+        index: "*_rollup"
+        body:
+          size: 0
+          aggs:
+            histo:
+              date_histogram:
+                field: "timestamp"
+                interval: "1h"
+                time_zone: "UTC"
```
Comment (jimczi) [inline x-pack/plugin/src/test/resources/rest-api-spec/test/rollup/rollup_search.yml]: Can you add a test with an alias that points to a rollup index ?

File: x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportRollupSearchAction.java [hunk 3]
```diff
@@ -100,8 +101,9 @@ public TransportRollupSearchAction(Settings settings, TransportService transport
 
     @Override
     protected void doExecute(Task task, SearchRequest request, ActionListener<SearchResponse> listener) {
-        RollupSearchContext rollupSearchContext = separateIndices(request.indices(),
-                clusterService.state().getMetaData().indices());
+        IndexNameExpressionResolver resolver = new IndexNameExpressionResolver(clusterService.getSettings());
+        String[] indices = resolver.concreteIndexNames(clusterService.state(), request.indicesOptions(), request.indices());
```
Comment (jimczi) [inline x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/action/TransportRollupSearchAction.java]: ++, this will also handle `alias` correctly

**Review by jimczi — APPROVED** [review]
I left a small comment regarding the tests with alias, LGTM otherwise
