### PR TITLE
Find and use non local IPv4 address while testing IP filtering

### LINKED ISSUE #40194: IPFilterTests failures in CI
```
REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=83400A086A7E1281 \
  -Dtests.class=org.elasticsearch.xpack.security.transport.filter.IPFilterTests \
  -Dtests.method="testThatProfilesAreSupported" \
  -Dtests.security.manager=true \
  -Dtests.locale=nn-NO \
  -Dtests.timezone=America/Rankin_Inlet \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:unitTest \
  -Dtests.seed=83400A086A7E1281 \
  -Dtests.class=org.elasticsearch.xpack.security.transport.filter.IPFilterTests \
  -Dtests.method="testThatProfilesAreUpdateable" \
  -Dtests.security.manager=true \
  -Dtests.locale=nn-NO \
  -Dtests.timezone=America/Rankin_Inlet \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

This has failed six times in the last six weeks, but is not reproducible

Link to build log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu-16.04&&virtual/229/console

### PR DESCRIPTION
**Pull request by bizybot**
For pattern "n:localhost" [PatternRule#isLocalhost()](https://github.com/elastic/elasticsearch/blob/d22c4b8db3267521483f92d9ed9d53e3e7f3a430/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/transport/filter/PatternRule.java#L115) matches
any local address, loopback address.

_[Note: I think for "localhost" this should not consider IP address
as a match when they are bound to network interfaces. It should just
be a loopback address check unless the intent is to match all local addresses.
This class is adopted from Netty3 and I am not sure if this is intended
behavior or if I am missing something]_

For now, I have fixed this assuming the PatternRule#isLocalhost check is
correct by avoiding the use of local address to check address denied.

Closes #40194

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/filter/IPFilterTests.java [hunk 1]
```diff
@@ -5,6 +5,8 @@
  */
 package org.elasticsearch.xpack.security.transport.filter;
 
+import com.google.common.primitives.Ints;
```
Comment (jaymode) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/filter/IPFilterTests.java]: let's not use guava

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/filter/IPFilterTests.java [hunk 2]
```diff
@@ -297,4 +305,22 @@ private void assertAddressIsDeniedForProfile(String profile, String ... inetAddr
     private void assertAddressIsDenied(String ... inetAddresses) {
         assertAddressIsDeniedForProfile("default", inetAddresses);
     }
+
+    private String randomNonLocalIPv4Address() throws SocketException, UnknownHostException {
+        String ipv4Address = null;
+        int noOfRetries = 0;
+        do {
+            noOfRetries++;
+            final InetAddress address = InetAddress.getByAddress(Ints.toByteArray(randomInt()));
```
Comment (jaymode) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/filter/IPFilterTests.java]: use `org.elasticsearch.common.Numbers#intToBytes`

**Review by jaymode — APPROVED** [review]
LGTM after removing the use of guava

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/filter/IPFilterTests.java (hunk 2 above)
Comment (bizybot) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/filter/IPFilterTests.java]: addressed this, thank you.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/filter/IPFilterTests.java (hunk 1 above)
Comment (bizybot) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/filter/IPFilterTests.java]: addressed this, thank you.
