### PR TITLE
Watcher: Fix index action simulation when indexing several documents

### LINKED ISSUE #74148: Watcher: simulating an index action after a search creates the document for real
**Elasticsearch version** (`bin/elasticsearch --version`): reported in 7.9 and reproduced with master (98943a28bef8a66014ce9a32ba37e0b8864b1d2c)

**Plugins installed**: reproduces with `./gradlew :x-pack:plugin:core run`

**JVM version** (`java -version`): Java 16

**OS version** (`uname -a` if on a Unix-like system): reproduced with
```
Linux beast 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
Simulating a watch that contains a `search` followed by an `index` action runs the action for real.

**Steps to reproduce**:

```
curl -ux_pack_rest_user:x-pack-test-password -XDELETE localhost:9200/my-index
curl -ux_pack_rest_user:x-pack-test-password -HContent-Type:application/json -XPUT localhost:9200/_watcher/watch/badguy?pretty -d'{
  "trigger": {
    "schedule": {
      "interval": "3d"
    }
  },
  "input": {
    "search": {
      "request": {
        "search_type": "query_then_fetch",
        "indices": [
          "*"
        ],
        "rest_total_hits_as_int": true,
        "body": {
          "size": 0,
          "query": {
            "match_all": {}
          }
        }
      }
    }
  },
  "condition": {
    "compare": {
      "ctx.payload.hits.total": {
        "gte": 10
      }
    }
  },
  "actions": {
    "index_payload": {
      "transform": {
        "script": {
          "source": "\ndef docs = [];\n            docs.add([\n                          \"fieldOne\": \"aaaaaaaa\"\n            ]);\n            return [\"_doc\": docs]\n            ",
          "lang": "painless"
        }
      },
      "index": {
        "index": "my-index"
      }
    }
  }
}'
curl -ux_pack_rest_user:x-pack-test-password -HContent-Type:application/json -XPOST localhost:9200/_watcher/watch/badguy/_execute?pretty -d'{
  "trigger_data" : { 
     "triggered_time" : "now",
     "scheduled_time" : "now"
  },
  "alternative_input" : { 
    "foo" : "bar"
  },
  "ignore_condition" : true, 
  "action_modes" : {
    "index_payload" : "simulate" 
  },
  "record_execution" : true 
}'

curl -ux_pack_rest_user:x-pack-test-password localhost:9200/_cat/indices
# Oh no! my-index is there!
curl -ux_pack_rest_user:x-pack-test-password localhost:9200/my-index/_search?pretty
# Oh no! The simulated doc is there!
```

### PR DESCRIPTION
**Pull request by spinscale**
When using the index action to index several documents at once,
simulation the action ended up in indexed documents because there was
not break in case the action should only be simulated.

This commits adds such an abortion condition together with a proper
simulation response.

Closes #74148 #66735

The proper fix would probably be to only have a bulk action, but this is a small and readable fix for now.

### CODE REVIEW

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/actions/index/ExecutableIndexAction.java [hunk 1]
```diff
@@ -145,6 +146,22 @@ public ExecutableIndexAction(IndexAction action, Logger logger, Client client,
             }
             bulkRequest.add(indexRequest);
         }
+
+        if (ctx.simulateAction(actionId)) {
+            try (XContentBuilder builder = jsonBuilder().startArray()) {
```
Comment (martijnvg) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/actions/index/ExecutableIndexAction.java:151]: Can `BulkItemResponse` be reused here and then serialise that to json?
This way if the format ever changes then this code doesn't need to be changed.

**Review by martijnvg — COMMENTED** [review]
Thanks, looks good Alex!
I left one question and I also wonder whether this should be back ported to the 7.x branch?

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/actions/index/ExecutableIndexAction.java (hunk 1 above)
Comment (spinscale) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/actions/index/ExecutableIndexAction.java:151]: there is no bulk item response, because the request is not sent but only simulated

**Comment by spinscale** [comment]
I think it should be ported back, but I'll leave that and merging gladly to you - not really up-to-date with existing tooling :-)

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/actions/index/ExecutableIndexAction.java (hunk 1 above)
Comment (martijnvg) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/actions/index/ExecutableIndexAction.java:151]: Right, my comment doesn't make much sense. Most of the `BulkItemResponse` instance would have dummy values (except for id and index).

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
> I think it should be ported back, but I'll leave that and merging gladly to you - not really up-to-date with existing tooling :-)

:) I will merge and backport.
