### PR TITLE
[ML] Improve file structure finder timestamp format determination

### LINKED ISSUE #35132: [ML] find_file_structure endpoint override can change field type as an unexpected side effect
Using the example file `ts.log` if you override the name of an unrelated field, the type of the field `extra_timestamp` will change from a `date` to a `keyword`

Steps to reproduce:
1. open `syslog-sample.log` in the File Data Visualizer
2. note the `extra_timestamp` field is a `date` type
3. Open the overrides flyout and in the Grok pattern text field change `ipaddress` to `ipaddress1`
4. Press apply
5. The results are reloaded and now `extra_timestamp` is a `keyword` type.

### LINKED ISSUE #35137: [ML] Slow performance of file structure finder with log message containing many dates
@grabowskit noticed that the `find_file_structure` endpoint timed out on a log file that contained messages from a Cloud allocator.

I debugged this and found that the messages that cause a particular problem for the file structure finder are those that contain many dates, for example:

```
[2018-10-05 11:05:17,526][INFO ][no.found.runner.allocation.elasticsearch.ElasticsearchDockerContainer] Creating container from [ElasticsearchDockerContainer(ElasticsearchContainerId(11111111111111111111111111111111,instance-0000000000),-,List(),{"data":{"name":"admin-console-elasticsearch"},"kind":"elasticsearch","resources":{"cpu":{"hard_limit":false,"boost":true}},"shield":{"system_key":"-","found_users":{"found-internal-constructor":{"roles":["found-internal-admin","superuser"],"username":"found-internal-constructor","password":"-","password_hash":"-","valid_until":"2023-10-05T11:05:15.879Z"},"found-internal-system":{"roles":["found-internal-constructor","superuser"],"username":"found-internal-system","password":"-","password_hash":"-","valid_until":"2060-10-05T11:05:10.624Z"},"found-internal-admin-proxy":{"roles":["found-internal-admin"],"username":"found-internal-admin-proxy","password_hash":"-","valid_until":"2060-10-05T11:05:10.546Z"},"ece-admin-cluster-indexer":{"roles":["found-internal-admin"],"username":"ece-admin-cluster-indexer","password_hash":"-"},"found-internal-monitor":{"roles":["found-internal-monitor"],"username":"found-internal-monitor","password_hash":"-","valid_until":"2060-10-05T11:05:10.701Z"},"found-local-allocator":{"password_hash":"-","roles":["found-internal-admin"]},"ec-local-beats-monitor":{"password_hash":"-","roles":["found-internal-monitor"]}}},"snapshot":{"enabled":false,"suspended":{"constructor":true}},"user_id":"root","system_owned":true,"source":{"facilitator":"bootstrap","action":"create-admin-console-backend","date":"2018-10-05T11:05:10.535Z"}},{"instance_capacity":4096,"instance_configuration_id":"data.default","allocator_filter":{"match_all":{}},"node_types":["data","master","ingest"],"elasticsearch":{"node":{"data":true,"master":true,"ingest":true},"plugins":["repository-s3","found-elasticsearch","x-pack"],"gateway_type":"local","user_settings_overrides":{},"user_bundles":[],"version":"5.6.12","confirmed_election":false,"user_settings":{"script.engine.expression.file":true,"script.engine.expression.inline":true,"script.engine.expression.stored":true,"script.engine.mustache.file":true,"script.engine.mustache.stored":true,"script.engine.painless.file":true,"script.engine.painless.inline":true,"script.engine.painless.stored":true,"script.file":false,"script.inline":false,"script.stored":false},"user_plugins":[],"seed_hosts":[]},"resources":{"quota":{"fs_multiplier":32}},"ssd":false,"plan_version":"1.0","logical_zone_name":"zone-0","start":true,"quorum_size":1,"maintenance":true,"source":{"facilitator":"constructor","action":"elasticsearch.create-instances","date":"2018-10-05T11:05:15.963Z"},"allocator_name":"10.10.10.10","allocator_id":"10.10.10.10","allocator_zone_name":"ece-zone-1"},None,None,{"forward_auth_headers":true,"shield":{"allow_anonymous":false,"esusers":{"roles":{"anonymous":{}},"users":{},"users_roles":{}}},"source":{"facilitator":"bootstrap","action":"create-admin-console-backend","date":"2018-10-05T11:05:10.535Z"}},AllocatorShieldUser(ec-local-beats-monitor,-,List(found-internal-monitor)),AllocatorShieldUser(found-local-allocator,-,List(found-internal-admin)),no.found.template.ZooKeeperResourceLocator@1f41214d,DefaultAllocatorAllocationEnvironment(438182,10.10.10.10,ece-zone-1,10.10.10.10,Map(kibana -> found/{kind}:{version}, apm -> found/{kind}:{version}, elasticsearch -> found/{kind}:{version}),Map(kibana -> 4.0, apm -> 4.0, elasticsearch -> 32.0),Map(kibana -> 5 seconds, apm -> 30000 milliseconds, elasticsearch -> 5 seconds),/usr/elastic/data/elastic/10.10.10.10/services/allocator/containers,/app/state,/app/state,state/runner-initial-containers-content.json,no.found.zookeeper.VersionCache@2b367d62,no.found.http.ActorHttpClient@3d6b7a00,no.found.runner.managers.ContainerIdsManager@1b8f1b99,no.found.runner.managers.XFSQuotaSupport@2291e278,no.found.filewatch.FileWatchService@3ad44625,no.found.template.VersionedTemplateManager@5c098005,no.found.runner.managers.ZooKeeperManager@3f390bce,no.found.runner.managers.NetworkResourcesManager@1296ac73,no.found.runner.settings.AllocatorSettings@aeb256a,Map(kibana -> 0.0, apm -> 0.0, elasticsearch -> 0.0)),no.found.featureflags.CloudFeatureManager@1af2959a)]: [{"Image":"docker.hs.coop.ch/cloud-assets/elasticsearch:5.6.12-0","Labels":{"co.elastic.cloud.allocator.id":"10.10.10.10","co.elastic.cloud.allocator.zone":"ece-zone-1","co.elastic.cloud.allocator.instance_id":"instance-0000000000","co.elastic.cloud.allocator.cluster_id":"11111111111111111111111111111111","co.elastic.cloud.allocator.user_id":"root","co.elastic.cloud.allocator.kind":"elasticsearch","co.elastic.cloud.allocator.type":"elasticsearch","co.elastic.cloud.allocator.type_version":"5.6.12"},"ExposedPorts":{"11111/tcp":{},"22222/tcp":{}},"HostConfig":{"CpuShares":11,"Memory":4294967296,"MemorySwap":4294967296,"BlkioWeight":11,"CpuPeriod":100000,"CpuQuota":4800000,"Binds":["/usr/elastic/data/elastic/10.10.10.10/services/allocator/containers/elasticsearch/11111111111111111111111111111111/instance-0000000000:/app"],"RestartPolicy":{"Name":"always"},"ExtraHosts":["containerhost:${ALLOCATOR_HOST_IP}","dockerhost:${ALLOCATOR_HOST_IP}"],"PortBindings":{"11111/tcp":[{"HostIp":"0.0.0.0","HostPort":"11111"}],"22222/tcp":[{"HostIp":"0.0.0.0","HostPort":"22222"}]},"CapAdd":["SETUID","SETGID","CHOWN","DAC_OVERRIDE"],"CapDrop":["ALL"]},"Volumes":{"/app":{}},"Env":["ELASTIC_UID=33333","ELASTIC_GID=33333"]}] {"ec_container_kind":"elasticsearch","ec_container_group":"11111111111111111111111111111111","ec_container_name":"instance-0000000000"}
```

(Some of the details in that sample have been altered to avoid disclosing real values from Cloud.)

Some temporary debug showed the following for this message:

```
[2018-10-31T16:22:20,667][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] quick rule out 0
[2018-10-31T16:22:20,667][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] done
[2018-10-31T16:22:20,667][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] quick rule out 1
[2018-10-31T16:22:20,667][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] done
[2018-10-31T16:22:20,667][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] trying [YYYY-MM-dd HH:mm:ss,SSS Z]
[2018-10-31T16:22:21,306][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] done
[2018-10-31T16:22:21,306][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] trying [YYYY-MM-dd HH:mm:ss,SSSZ]
[2018-10-31T16:22:22,021][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] done
[2018-10-31T16:22:22,021][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] trying [YYYY-MM-dd HH:mm:ss,SSSZZ]
[2018-10-31T16:22:22,727][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] done
[2018-10-31T16:22:22,727][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] trying [YYYY-MM-dd HH:mm:ss,SSS]
[2018-10-31T16:22:22,728][INFO ][o.e.x.m.f.TimestampFormatFinder] [node-0] done
```

The problems are:

1. Because there are multiple timestamps in different formats the functionality to quickly rule out some timestamp patterns doesn't work.
2. Then patterns that nearly match but not quite cause excessive backtracking and searching in the Grok pattern matcher due to the fact that a large prefix of the pattern matches in several places - around 2/3rds of a second per nearly matching pattern, just for this one message.

### PR DESCRIPTION
**Pull request by droberts195**
This change contains a major refactoring of the timestamp
format determination code used by the ML find file structure
endpoint.

Previously timestamp format determination was done separately
for each piece of text supplied to the timestamp format finder.
This had the drawback that it was not possible to distinguish
dd/MM and MM/dd in the case where both numbers were 12 or less.
In order to do this sensibly it is best to look across all the
available timestamps and see if one of the numbers is greater
than 12 in any of them.  This necessitates making the timestamp
format finder an instantiable class that can accumulate evidence
over time.

Another problem with the previous approach was that it was only
possible to override the timestamp format to one of a limited
set of timestamp formats.  There was no way out if a file to be
analysed had a timestamp that was sane yet not in the supported
set.  This is now changed to allow any timestamp format that can
be parsed by a combination of these Java date/time formats:
yy, yyyy, M, MM, MMM, MMMM, d, dd, EEE, EEEE, H, HH, h, mm, ss,
a, XX, XXX, zzz
Additionally S letter groups (fractional seconds) are supported
providing they occur after ss and separated from the ss by a dot,
comma or colon.  Spacing and punctuation is also permitted with
the exception of the question mark, newline and carriage return
characters, together with literal text enclosed in single quotes.

The full list of changes/improvements in this refactor is:

- Make TimestampFormatFinder an instantiable class
- Overrides must be specified in Java date/time format - Joda
  format is no longer accepted
- Joda timestamp formats in outputs are now derived from the
  determined or overridden Java timestamp formats, not stored
  separately
- Functionality for determining the "best" timestamp format in
  a set of lines has been moved from TextLogFileStructureFinder
  to TimestampFormatFinder, taking advantage of the fact that
  TimestampFormatFinder is now an instantiable class with state
- The functionality to quickly rule out some possible Grok
  patterns when looking for timestamp formats has been changed
  from using simple regular expressions to the much faster
  approach of using the Shift-And method of sub-string search,
  but using an "alphabet" consisting of just 1 (representing any
  digit) and 0 (representing non-digits)
- Timestamp format overrides are now much more flexible
- Timestamp format overrides that do not correspond to a built-in
  Grok pattern are mapped to a %{CUSTOM_TIMESTAMP} Grok pattern
  whose definition is included within the date processor in the
  ingest pipeline
- Grok patterns that correspond to multiple Java date/time
  patterns are now handled better - the Grok pattern is accepted
  as matching broadly, and the required set of Java date/time
  patterns is built up considering all observed samples
- As a result of the more flexible acceptance of Grok patterns,
  when looking for the "best" timestamp in a set of lines
  timestamps are considered different if they are preceded by
  a different sequence of punctuation characters (to prevent
  timestamps far into some lines being considered similar to
  timestamps near the beginning of other lines)
- Out-of-the-box Grok patterns that are considered now include
  %{DATE} and %{DATESTAMP}, which have indeterminate day/month
  ordering
- The order of day/month in formats with indeterminate day/month
  order is determined by considering all observed samples (plus
  the server locale if the observed samples still do not suggest
  an ordering)

Relates #38086
Closes #35137
Closes #35132

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java [hunk 1]
```diff
@@ -64,427 +114,1074 @@
...
-                    newPatternStr.replace(separatorPos, separatorPos + 1, ((separator == '.') ? "\\" : "") + separator);
-                    simplePattern = Pattern.compile(newPatternStr.toString());
+    /**
+     * Does the parsing the timestamp produce different results depending on the timezone of the parser?
+     * I.e., does the textual representation NOT define the timezone?
+     */
+    public boolean hasTimezoneDependentParsing() {
+        if (matchedFormats.isEmpty()) {
+            if (errorOnNoTimestamp) {
+                throw new IllegalStateException("No matched timestamp formats");
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: We should include the `why` in this exception.

**Review by benwtrent — COMMENTED** [review]
Some minor things on the first read through. 

This is a ton to grok (pun intended, in fact, I think I used this same pun on the last time a huge PR was made for the fsf...).

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java (hunk 1 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: None of these `IllegalStateException`s in the getters are user facing error messages.  They mean the programmer has made a mistake by asking for results from an object they didn't add any samples to (because if they added a sample when `errorOnNoTimestamp` is `true` then _that_ would have thrown an exception).

It's obviously confusing as it is now.  I think I should change these exceptions to `assert`s instead since they're detecting usage errors by the programmer.  The return value for when assertions are disabled can just be the `null`/empty/false/0 that gets returned when `errorOnNoTimestamp` is `false`.  If you think that sounds OK then I'll change it tomorrow, but let me know if you think of a better approach.

**Review by benwtrent — APPROVED** [review]
Will definitely need a second set of 👀 :)

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/GrokPatternCreator.java [hunk 2]
```diff
@@ -486,9 +524,17 @@ public String processCaptures(Map<String, Integer> fieldNameCountStore, Collecti
                 Map<String, String> fullMappingType = Collections.singletonMap(FileStructureUtils.MAPPING_TYPE_SETTING, mappingType);
                 if ("date".equals(mappingType)) {
                     assert values.isEmpty() == false;
-                    TimestampMatch timestampMatch = TimestampFormatFinder.findFirstFullMatch(values.iterator().next(), timeoutChecker);
-                    if (timestampMatch != null) {
-                        fullMappingType = timestampMatch.getEsDateMappingTypeWithFormat();
+                    TimestampFormatFinder timestampFormatFinder = new TimestampFormatFinder(explanation, true, true, true, timeoutChecker);
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/GrokPatternCreator.java]: This for loop all the way to calling `timestampFormatFinder.getEsDateMappingTypeWithFormat()` is repeated in `FileStructureUtils` around line `277`. I wonder if we could refactor that in a method.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java [hunk 3]
```diff
@@ -64,427 +113,1139 @@
...
+     * @param requireFullMatch        Must samples added to this object represent a timestamp in their entirety?
+     * @param errorOnNoTimestamp      Should an exception be thrown if a sample is added that does not contain a recognised timestamp?
+     * @param errorOnMultiplePatterns Should an exception be thrown if samples are uploaded that require different Grok patterns?
+     * @param timeoutChecker          Will abort the operation if its timeout is exceeded.
      */
-    public static TimestampMatch findFirstMatch(String text, TimeoutChecker timeoutChecker) {
-        return findFirstMatch(text, 0, timeoutChecker);
+    public TimestampFormatFinder(List<String> explanation, String overrideFormat, boolean requireFullMatch, boolean errorOnNoTimestamp,
+                                 boolean errorOnMultiplePatterns, TimeoutChecker timeoutChecker) {
+        this.explanation = explanation;
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: add `Objects.requireNonNull` or `@Nullable` where suitable

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java [hunk 4]
```diff
@@ -64,427 +113,1139 @@
...
+        }
+
+        // Next check for a built-in candidate that incorporates the override, and prefer this
+
+        // If the override is not a valid format then one or other of these two calls will
+        // throw, and that is how we'll report the invalid format to the user
+        Tuple<String, String> grokPatternAndRegex = overrideFormatToGrokAndRegex(overrideFormat);
+        DateTimeFormatter javaTimeFormatter = DateTimeFormatter.ofPattern(overrideFormat, Locale.ROOT);
+
+        // This timestamp is chosen to avoid the possibility of truncating zeroes
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: I'm not quite getting why 29th Feb is doing the trick. Could you elaborate?

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java [hunk 5]
```diff
@@ -64,427 +113,1139 @@
...
-        int index = ignoreCandidates;
-        String adjustedRequiredFormat = adjustRequiredFormat(requiredFormat);
-        for (CandidateTimestampFormat candidate : ORDERED_CANDIDATE_FORMATS.subList(ignoreCandidates, ORDERED_CANDIDATE_FORMATS.size())) {
-            if (adjustedRequiredFormat == null || candidate.jodaTimestampFormats.contains(adjustedRequiredFormat) ||
-                candidate.javaTimestampFormats.contains(adjustedRequiredFormat)) {
-                boolean quicklyRuledOut = false;
-                for (Integer quickRuleOutIndex : candidate.quickRuleOutIndices) {
-                    if (quickRuleoutMatches[quickRuleOutIndex] == null) {
-                        quickRuleoutMatches[quickRuleOutIndex] = QUICK_RULE_OUT_PATTERNS.get(quickRuleOutIndex).matcher(text).find();
+    private static TimestampMatch checkCandidate(CandidateTimestampFormat candidate, String text, BitSet numberPosBitSet,
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: add `@Nullable` where suitable? Especially in methods with optional arguments it helps a lot when reading.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java [hunk 6]
```diff
@@ -64,427 +113,1139 @@
...
+     * then this method does nothing.
+     */
+    public void selectBestMatch() {
+
+        if (matchedFormats.size() < 2) {
+            // Nothing to do
+            return;
+        }
+
+        int remainingMatches = matches.size();
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: This block seems a nice candidate to extract into a method that returns the weights.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java [hunk 7]
```diff
@@ -64,427 +113,1139 @@
...
+            // The highest possible weight is 1, so if the difference between the two highest weights
+            // is less than the number of lines remaining then the leader cannot possibly be overtaken
+            if (findDifferenceBetweenTwoHighestWeights(weights) > --remainingMatches) {
+                break;
+            }
+        }
+
+        timeoutChecker.check("timestamp format determination");
+
+        double highestWeight = 0.0;
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: This could be a `Tuple<Integer, Double> findHighestWeight(double[] weights)` method.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java [hunk 8]
```diff
@@ -64,427 +113,1139 @@
...
+            if (weight > highestWeight) {
+                highestWeight = weight;
+                highestWeightFormatIndex = index;
+            }
+        }
+
+        timeoutChecker.check("timestamp format determination");
+
+        // Is the selected format not already at the beginning of the list?
+        if (highestWeightFormatIndex > 0) {
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: And finally, this could be `selectHighestWeightFormat`.

The above would make the method roughly read like:

```
calcMatchWeights();
findHighestWeight();
selectHighestWeightFormat();
```

Take all these as a mere suggestion. I know at the end it's down to personal preference, but I find breaking down methods like this increase readability a lot as it prepares the reader to understand what the lower-level code is trying to achieve.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java [hunk 9]
```diff
@@ -64,427 +113,1139 @@
...
+    Boolean guessIsDayFirstFromMatches(TimestampFormat onlyConsiderFormat) {
+
+        BitSet firstIndeterminateNumbers = new BitSet();
+        BitSet secondIndeterminateNumbers = new BitSet();
+
+        for (TimestampMatch match : matches) {
+
+            if (onlyConsiderFormat == null || onlyConsiderFormat.canMergeWith(match.timestampFormat)) {
+
+                if (match.firstIndeterminateDateNumber > 0) {
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: What does the zero check represent here?

**Review by dimitris-athanasiou — COMMENTED** [review]
Left a few comments. There are some cool but complex ideas in here!

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java (hunk 4 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: Well spotted.  This is a bug.  The month, day and hour should all be less than 10 to distinguish formats that don't use leading zeroes for them.  I'll fix the comment too.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java [hunk 10]
```diff
@@ -718,7 +793,11 @@ Boolean guessIsDayFirstFromMatches(TimestampFormat onlyConsiderFormat) {
 
             if (onlyConsiderFormat == null || onlyConsiderFormat.canMergeWith(match.timestampFormat)) {
 
+                // Valid indetermine day/month numbers will be in the range 1 to 31.
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: typo: `indeterminate`; it is a confusing one to type :-)

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM Just left a typo in a comment

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java (hunk 10 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/filestructurefinder/TimestampFormatFinder.java]: Gah, I fixed the exact same typo in another place in another recent commit

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/1
