### PR TITLE
Watcher: Use joda method to get local TZ

### LINKED ISSUE #35518: Joda time unable to handle some timezones causing test failure
It appears as though joda time cannot handle certain timezones such as `SystemV/MST7MDT`, which results in test failures that reproduce locally.

Build link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/204/console

Reproduce

```
./gradlew :x-pack:plugin:watcher:test -Dtests.seed=4AA3D2B20D6E347A -Dtests.class=org.elasticsearch.xpack.watcher.trigger.schedule.tool.CronEvalToolTests -Dtests.method="testGetNextValidTimes" -Dtests.security.manager=true -Dtests.locale=hr-HR -Dtests.timezone=SystemV/MST7MDT -Dcompiler.java=11 -Druntime.java=8
```

Failure

```
Caused by: java.lang.IllegalArgumentException: The datetime zone id 'SystemV/MST7MDT' is not recognised
	at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:385)
	at org.elasticsearch.xpack.watcher.trigger.schedule.tool.CronEvalTool.<clinit>(CronEvalTool.java:34)
```

### PR DESCRIPTION
**Pull request by rjernst**
This commit switches from using java util's default timezone method to
using joda. The former can cause problems when the string representation
of the timezone is unknown to joda.

closes #35518

### CODE REVIEW

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java [hunk 1]
```diff
@@ -31,7 +30,7 @@ public static void main(String[] args) throws Exception {
     private static final DateTimeFormatter UTC_FORMATTER = DateTimeFormat.forPattern("EEE, d MMM yyyy HH:mm:ss")
         .withZone(DateTimeZone.UTC).withLocale(Locale.ROOT);
     private static final DateTimeFormatter LOCAL_FORMATTER = DateTimeFormat.forPattern("EEE, d MMM yyyy HH:mm:ss Z")
-        .withZone(DateTimeZone.forTimeZone(TimeZone.getDefault()));
+        .withZone(DateTimeZone.forTimeZone(null));
```
Comment (jakelandis) [inline x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java]: minor: I think it would be a bit more obvious to explicitly call `DateTimeZone.getDefault()` instead of `null`.
Since that is what Joda does with the `null` value.
http://joda-time.sourceforge.net/apidocs/src-html/org/joda/time/DateTimeZone.html#line.301

**Comment by jakelandis** [comment]
looks like the test failure may be related to the change

**Comment by rjernst** [comment]
The failure is odd...it does not reproduce for me. I also ran 100 iterations and I do not get any failures...

File: x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java (hunk 1 above)
Comment (jakelandis) [reply x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/trigger/schedule/tool/CronEvalTool.java]: Doh! the recommendation is forbidden API ..never mind.

**Comment by jakelandis** [comment]
LGTM

**Comment by rjernst** [comment]
Upon attempting to back port, I found the 6.x code does not have the local formatter, so I've only applied this change to master.
