### PR TITLE
Fix ThreadPoolMergeSchedulerTests testSchedulerCloseWaitsForRunningMerge

### LINKED ISSUE #125236: [CI] ThreadPoolMergeSchedulerTests testSchedulerCloseWaitsForRunningMerge failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8681 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/exihawvfuvmgo)
- [elasticsearch-periodic-platform-support #8681 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/f53geqvbc2fc2)
- [elasticsearch-pull-request #74709 / part-1](https://gradle-enterprise.elastic.co/s/pc4svbsr7hzti)
- [elasticsearch-periodic-platform-support #8681 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/q4msgun53ibww)
- [elasticsearch-periodic-platform-support #8681 / almalinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/nwnpvnn655dwk)
- [elasticsearch-periodic-platform-support #8681 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/36ikkbw4uiexu)

**Reproduction Line:**
```
gradlew ":server:test" --tests "org.elasticsearch.index.engine.ThreadPoolMergeSchedulerTests.testSchedulerCloseWaitsForRunningMerge" -Dtests.seed=A7E04417E8372109 -Dtests.locale=ur-PK -Dtests.timezone=Europe/Moscow -Druntime.java=24
```

**Applicable branches:**
9.0

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.engine.ThreadPoolMergeSchedulerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSchedulerCloseWaitsForRunningMerge),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: iterable containing [<Mock for OneMerge, hashCode: 173950959>]
     but: no item was <Mock for OneMerge, hashCode: 173950959>
```

**Issue Reasons:**
- [9.0] 6 consecutive failures in test testSchedulerCloseWaitsForRunningMerge
- [9.0] 6 failures in test testSchedulerCloseWaitsForRunningMerge (54.5% fail rate in 11 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by albertzaharovits**
Fixes https://github.com/elastic/elasticsearch/issues/125236

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerTests.java [hunk 1]
```diff
@@ -535,10 +536,10 @@ public void testSchedulerCloseWaitsForRunningMerge() throws Exception {
                         threadPoolMergeScheduler.merge(mergeSource2, randomFrom(MergeTrigger.values()));
                         // when the merge scheduler is closed it won't pull in any new merges from the merge source
                         verifyNoInteractions(mergeSource2);
+                        // assert the merge still shows up as "running"
+                        assertThat(threadPoolMergeScheduler.getRunningMergeTasks().keySet(), contains(oneMerge));
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerTests.java:540]: I wonder if we should rather just wait for the merge thread to have picked up the task - before this assert busy block? Using `CyclicBarrier` for instance. Then I think the original check here can work too - without the waiting for it using assert busy. I think that reads more clearly and is a bit stronger.

**Review by henningandersen — APPROVED** [review]
LGTM.

I'd be ok with this fix, but proposed an alternative to consider.

File: server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerTests.java (hunk 1 above)
Comment (albertzaharovits) [reply server/src/test/java/org/elasticsearch/index/engine/ThreadPoolMergeSchedulerTests.java]: Pushed [4131809](https://github.com/elastic/elasticsearch/pull/126110/commits/413180993b1b054032016010e8fa9a0c8103330a)
