### PR TITLE
Gracefully handle very large sizes on terms

### LINKED ISSUE #76492: maxSize must be >= 0 and < 2147483631; got: 2147483647"
**17.14.0** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**Linux  4.18.0-305.10.2.el8_4.x86_64 #1 SMP Mon Jul 12 04:43:18 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux** (`uname -a` if on a Unix-like system):

**Throwing error search_phase_execution_exception**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1.
 2.
 3.

**{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"illegal_argument_exception","reason":"maxSize must be >= 0 and < 2147483631; got: 2147483647"}},"status":400}**:

### PR DESCRIPTION
**Pull request by nik9000**
Folks often as for the `terms` agg to have *very* large `size`
parameters in an effort to get everything they can. But they never fill
that large size. They can't! There isn't really enough heap to return
two billion buckets.

After #74096 we try to pre-allocate an array of `size + 1` length,
regardless of how many results are returned. When folks ask for
`MAX_INT` buckets this helpfully fails off in lucene land with an error
message that fairly esoterit to someone reading it outside of
Elasticsearch.

This change handles that `MAX_INT` case by building a
`TopBucketsBuilder` designed to handle large max sizes that are rarely
filled. When you ask for 1024 or more buckets you get that one instead
and we don't preallocate the entire array for the reduction. You get the
old preallocated one when you have few buckets.

Closes #76492

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/TopBucketBuilder.java [hunk 1]
```diff
@@ -20,26 +21,47 @@
...
-            private final Comparator<DelayedBucket<? extends Bucket>> comparator = order.delayedBucketComparator();
+    public static <B extends InternalMultiBucketAggregation.InternalBucket> TopBucketBuilder<B> build(
+        int size,
+        BucketOrder order,
+        Consumer<DelayedBucket<B>> nonCompetitive
+    ) {
+        if (size < USE_BUFFERING_BUILDER) {
+            return new PriorityQueueTopBucketBuilder<>(size, order, nonCompetitive);
+        }
+        return new BufferingTopBucketBuilder<>(size, order, nonCompetitive);
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/TopBucketBuilder.java:58]: I could have made a single TopBucketBuilder which has a buffer and a queue member and flips between them but I didn't feel good making folks that set the size to something low and sensible pay the buffer tax.

File: server/src/main/java/org/elasticsearch/search/aggregations/TopBucketBuilder.java [hunk 2]
```diff
@@ -20,26 +21,47 @@
...
-public class TopBucketBuilder<B extends InternalMultiBucketAggregation.InternalBucket> {
-    private final Consumer<DelayedBucket<B>> nonCompetitive;
-    private final PriorityQueue<DelayedBucket<B>> queue;
+public abstract class TopBucketBuilder<B extends InternalMultiBucketAggregation.InternalBucket> {
+    /**
+     * The number of buckets required before we switch to the
+     * {@link BufferingTopBucketBuilder}. If we need fewer buckets we use
+     * {@link PriorityQueueTopBucketBuilder}.
+     */
+    static final int USE_BUFFERING_BUILDER = 1024;
```
Comment (imotov) [inline server/src/main/java/org/elasticsearch/search/aggregations/TopBucketBuilder.java:30]: I am really curious how you came up with this number.

**Review by imotov — APPROVED** [review]
I think this is good as a bug fix, it would be nice to discuss it further to see if we can make it a bit smarter about switching between algorithms.

File: server/src/main/java/org/elasticsearch/search/aggregations/TopBucketBuilder.java (hunk 2 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/aggregations/TopBucketBuilder.java:30]: I looked into my heart and thought "32k is fine to over allocate".  And I thought "this is much bigger than the default of 10 and in the ball park of "too many bars to have in a bar chart". But, fundamentally, it was a guess because I didn't think it was worth spending a lot of time trying to come up with the perfect number. I will add a comment about that.

**Comment by nik9000** [comment]
run elasticsearch-ci/docs

**Comment by nik9000** [comment]
run elasticsearch-ci/part-2
