### PR TITLE
Fix _terms_enum on unconfigured constant_keyword

### LINKED ISSUE #86187: _terms_enum failure on a constant keyword field
When using the terms enum API on a constant keyword field, an error is returned complaining about a non-null value.

Request:

```
POST /metrics-endpoint.policy-default/_terms_enum
{
  "field": "data_stream.type"
}
```

Response:

```
#! Your license will expire in [5] days. Contact your administrator or update your license for continued use of features
#! Your license will expire in [6] days. Contact your administrator or update your license for continued use of features
{
  "_shards" : {
    "total" : 8,
    "successful" : 4,
    "failed" : 4,
    "failures" : [
      {
        "shard" : 0,
        "index" : ".ds-metrics-endpoint.policy-default-2022.04.04-000001",
        "status" : "INTERNAL_SERVER_ERROR",
        "reason" : {
          "type" : "broadcast_shard_operation_failed_exception",
          "reason" : """java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "this.value" is null
	at org.elasticsearch.xpack.constantkeyword.mapper.ConstantKeywordFieldMapper$ConstantKeywordFieldType.getTerms(ConstantKeywordFieldMapper.java:156)
	at org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.dataNodeOperation(TransportTermsEnumAction.java:351)
	at org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.lambda$asyncNodeOperation$0(TransportTermsEnumAction.java:712)
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
""",
          "index_uuid" : "uOdQ_uBRRLeq5-OAJAwGrg",
          "shard" : "0",
          "index" : ".ds-metrics-endpoint.policy-default-2022.04.04-000001"
        }
      },
      {
        "shard" : 0,
        "index" : ".ds-metrics-endpoint.policy-default-2022.04.07-000002",
        "status" : "INTERNAL_SERVER_ERROR",
        "reason" : {
          "type" : "broadcast_shard_operation_failed_exception",
          "reason" : """java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "this.value" is null
	at org.elasticsearch.xpack.constantkeyword.mapper.ConstantKeywordFieldMapper$ConstantKeywordFieldType.getTerms(ConstantKeywordFieldMapper.java:156)
	at org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.dataNodeOperation(TransportTermsEnumAction.java:351)
	at org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.lambda$asyncNodeOperation$0(TransportTermsEnumAction.java:712)
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
""",
          "index_uuid" : "qBOOM6CXRpuK0budYXBUnQ",
          "shard" : "0",
          "index" : ".ds-metrics-endpoint.policy-default-2022.04.07-000002"
        }
      },
      {
        "shard" : 0,
        "index" : ".ds-metrics-endpoint.policy-default-2022.04.22-000007",
        "status" : "INTERNAL_SERVER_ERROR",
        "reason" : {
          "type" : "broadcast_shard_operation_failed_exception",
          "reason" : """java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "this.value" is null
	at org.elasticsearch.xpack.constantkeyword.mapper.ConstantKeywordFieldMapper$ConstantKeywordFieldType.getTerms(ConstantKeywordFieldMapper.java:156)
	at org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.dataNodeOperation(TransportTermsEnumAction.java:351)
	at org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.lambda$asyncNodeOperation$0(TransportTermsEnumAction.java:712)
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
""",
          "index_uuid" : "e8KIwULjSsSn3NGdm7tuPw",
          "shard" : "0",
          "index" : ".ds-metrics-endpoint.policy-default-2022.04.22-000007"
        }
      },
      {
        "shard" : 0,
        "index" : ".ds-metrics-endpoint.policy-default-2022.04.25-000008",
        "status" : "INTERNAL_SERVER_ERROR",
        "reason" : {
          "type" : "broadcast_shard_operation_failed_exception",
          "reason" : """java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "this.value" is null
	at org.elasticsearch.xpack.constantkeyword.mapper.ConstantKeywordFieldMapper$ConstantKeywordFieldType.getTerms(ConstantKeywordFieldMapper.java:156)
	at org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.dataNodeOperation(TransportTermsEnumAction.java:351)
	at org.elasticsearch.xpack.core.termsenum.action.TransportTermsEnumAction.lambda$asyncNodeOperation$0(TransportTermsEnumAction.java:712)
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
""",
          "index_uuid" : "bDskzrgwQbG35K389_yyKA",
          "shard" : "0",
          "index" : ".ds-metrics-endpoint.policy-default-2022.04.25-000008"
        }
      }
    ]
  },
  "terms" : [
    "metrics"
  ],
  "complete" : false
}
```

### LINKED ISSUE #86267: Terms enum API throws null pointer exception when remote shards fail
### Elasticsearch Version

8.3.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

arm64

### Problem Description

When using the `_terms_enum` API, if remote clusters return failures, but the local cluster doesn't, a null exception is thrown:

```
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"java.util.List.add(Object)\" because \"shardFailures\" is null"
      }
    ],
    "type": "null_pointer_exception",
    "reason": "Cannot invoke \"java.util.List.add(Object)\" because \"shardFailures\" is null"
  },
  "status": 500
}
```

### Steps to Reproduce

Call the _terms_enum API with a remote cluster that will return failures, e.g. because of this bug: https://github.com/elastic/elasticsearch/issues/86187

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ywelsch**
Calling _terms_enum on a constant_keyword field where the value has not been determined yet leads to a NullPointerException. We now guard against that here.

Closes #86187
Closes #86267

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/termsenum/action/TransportTermsEnumAction.java [hunk 1]
```diff
@@ -259,6 +259,9 @@ protected TermsEnumResponse mergeResponses(
                 successfulShards += rc.resp.getSuccessfulShards();
                 failedShards += rc.resp.getFailedShards();
                 for (DefaultShardOperationFailedException exc : rc.resp.getShardFailures()) {
+                    if (shardFailures == null) {
+                        shardFailures = new ArrayList<>();
```
Comment (ywelsch) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/termsenum/action/TransportTermsEnumAction.java:263]: This fixes another related bug which was observed:

```
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"java.util.List.add(Object)\" because \"shardFailures\" is null"
      }
    ],
    "type": "null_pointer_exception",
    "reason": "Cannot invoke \"java.util.List.add(Object)\" because \"shardFailures\" is null"
  },
  "status": 500
}
```

Testing this one is tricky as you need a test with a remote cluster, and you need the remote cluster to fail the terms enum on some field for some reason. I've therefore opted to fix without test.

File: x-pack/plugin/mapper-constant-keyword/src/main/java/org/elasticsearch/xpack/constantkeyword/mapper/ConstantKeywordFieldMapper.java [hunk 2]
```diff
@@ -151,11 +151,14 @@ public ValueFetcher valueFetcher(SearchExecutionContext context, String format)
...
         public TermsEnum getTerms(boolean caseInsensitive, String string, SearchExecutionContext queryShardContext, String searchAfter) {
+            if (value == null) {
+                return TermsEnum.EMPTY;
+            }
             boolean matches = caseInsensitive
                 ? value.toLowerCase(Locale.ROOT).startsWith(string.toLowerCase(Locale.ROOT))
                 : value.startsWith(string);
             if (matches == false) {
-                return null;
+                return TermsEnum.EMPTY;
```
Comment (ywelsch) [inline x-pack/plugin/mapper-constant-keyword/src/main/java/org/elasticsearch/xpack/constantkeyword/mapper/ConstantKeywordFieldMapper.java:161]: I claim that TermsEnum.EMPTY is the better response here, as null is equivalent to what we return when _terms_enum is not supported on a given field type.

Comment (cbuescher) [reply x-pack/plugin/mapper-constant-keyword/src/main/java/org/elasticsearch/xpack/constantkeyword/mapper/ConstantKeywordFieldMapper.java:161]: PS: I see one of the yaml tests already seems to test "searchAfter", am I right that this curently wouldn't result in an NPE since the value isn't really used on that code path?

**Review by cbuescher — APPROVED** [review]
LGTM; I left a few comments, feel free to adress or ignore.

File: x-pack/plugin/mapper-constant-keyword/src/main/java/org/elasticsearch/xpack/constantkeyword/mapper/ConstantKeywordFieldMapper.java [hunk 3]
```diff
@@ -151,11 +151,14 @@ public ValueFetcher valueFetcher(SearchExecutionContext context, String format)
 
         @Override
         public TermsEnum getTerms(boolean caseInsensitive, String string, SearchExecutionContext queryShardContext, String searchAfter) {
+            if (value == null) {
+                return TermsEnum.EMPTY;
```
[the remark this answers is not in the document]
Comment (ywelsch) [reply x-pack/plugin/mapper-constant-keyword/src/main/java/org/elasticsearch/xpack/constantkeyword/mapper/ConstantKeywordFieldMapper.java:155]: TermsEnum.EMPTY does not need to be special-cased, as it works just as fine as a regular TermsEnum, it just won't yield any results.

**Comment by ywelsch** [comment]
Thanks @cbuescher!
