### PR TITLE
Reindex: don't duplicate _source parameter

### LINKED ISSUE #24628: [CI] org.elasticsearch.index.reindex.remote.RemoteRequestBuildersTests testInitialSearchParamsFields fails on 5.4 due to extra search params
Seeing this failure:

```
java.lang.AssertionError: 
Expected: map containing ["fields"->"_source,_id,_parent,_routing,_ttl"]
     but: map was [<size=-1>, <fields=_source,_id,_parent,_routing,_ttl,_source>, <version=null>]
	at __randomizedtesting.SeedInfo.seed([AFFEEC0B404892D4:C8CC89B5649DFD1F]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at org.elasticsearch.index.reindex.remote.RemoteRequestBuildersTests.testInitialSearchParamsFields(RemoteRequestBuildersTests.java:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

And it reproduces for me with:

```
gradle :modules:reindex:test -Dtests.seed=FDD4FBA1D902995D -Dtests.class=org.elasticsearch.index.reindex.remote.RemoteRequestBuildersTests -Dtests.method="testInitialSearchParamsFields" -Dtests.security.manager=true -Dtests.locale=da -Dtests.timezone=Asia/Pyongyang
```

Here's a failure log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+multijob-windows-compatibility/85/console

### PR DESCRIPTION
**Pull request by nik9000**
If the request asks for the `_source` stored field then don't
duplicate it when forcing the `_source` parameter to onto the
request for reindex-from-remote from versions before 1.0.

Closes #24628

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/remote/RemoteRequestBuilders.java [hunk 1]
```diff
@@ -103,7 +103,9 @@ static String initialSearchPath(SearchRequest searchRequest) {
             searchRequest.source().storedField("_parent").storedField("_routing").storedField("_ttl");
             if (remoteVersion.before(Version.fromId(1000099))) {
                 // Versions before 1.0.0 don't support `"_source": true` so we have to ask for the _source in a funny way.
-                searchRequest.source().storedField("_source");
+                if (false == searchRequest.source().storedFields().fieldNames().contains("_source")) {
```
Comment (glefloch) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/remote/RemoteRequestBuilders.java]: Why don't you just do `if (!searchRequest.source().storedFields().fieldNames().contains("_source")) {` as contains returns a `boolean` ?

**Review by glefloch — APPROVED** [review]

File: modules/reindex/src/main/java/org/elasticsearch/index/reindex/remote/RemoteRequestBuilders.java (hunk 1 above)
Comment (nik9000) [inline modules/reindex/src/main/java/org/elasticsearch/index/reindex/remote/RemoteRequestBuilders.java]: Elasticsearch has this thing about `== false` instead of `!`. I think it has something to do with `!` being easy to miss when visually scanning the line.

**Comment by nik9000** [comment]
Thanks for reviewing @jimczi and @glefloch!
