### PR TITLE
Retry clean and create snapshot if it already exists #83694

### LINKED ISSUE #83694: Master failover during ILM snapshot creation causes ILM to enter ERROR
### Elasticsearch Version

All

### Problem Description

It's possible for ILM to attempt a double-invocation of the `create-snapshot` step due to a master fail-over during the snapshot. This causes ILM to get stuck in the `create-snapshot` ERROR step with the error that the snapshot already exists (or else is currently ongoing).

For remediation, you can either move the index back to the `cleanup-snapshot` step (**IN THE SAME PHASE**), which will delete the snapshot and start taking a new one:

```
POST _ilm/move/<your-index-here>
{
  "current_step": { 
    "phase": "cold",
    "action": "searchable_snapshot",
    "name": "ERROR"
  },
  "next_step": { 
    "phase": "cold",
    "action": "searchable_snapshot",
    "name": "cleanup-snapshot"
  }
}
```

Or, use the [delete snapshot API](https://www.elastic.co/guide/en/elasticsearch/reference/current/delete-snapshot-api.html) and simply delete the existing snapshots, since ILM keeps retrying the create-snapshot step and will recreate the snapshot with that name.

### Steps to Reproduce

It manifests in the following way:

1. Enter `create-snapshot` step
2. ILM issues the create snapshot request, which is ongoing
3. The master node fails or is shut down
4. A new master is elected
5. The new master invokes the `create-snapshot` step a second time
6. The step fails due the snapshot either already existing, or a snapshot request already ongoing

### Logs (if relevant)

You can usually diagnose this by looking to see if the master node changes between the first `create-snapshot` and subsequent `create-snapshot` invocation (ILM only executes on the master node, so the logs will come from a different node for the two invocations).

You may see logs such as:

```
[2021-09-27T18:20:22.182Z][WARN][org.elasticsearch.snapshots.SnapshotsService] [instance-0000000152] [myindex][mysnapshotname] failed to create snapshot
org.elasticsearch.snapshots.InvalidSnapshotNameException: [myrepo:mysnapshotname] Invalid snapshot name [mysnapshotname], snapshot with the same name is already in-progress
	at org.elasticsearch.snapshots.SnapshotsService.ensureSnapshotNameNotRunning(SnapshotsService.java:614) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.snapshots.SnapshotsService.access$5300(SnapshotsService.java:123) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.snapshots.SnapshotsService$2.execute(SnapshotsService.java:462) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$1.execute(BlobStoreRepository.java:480) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:691) ~[elasticsearch-7.14.2.jar:7.14.2]
```

And also:

```
org.elasticsearch.snapshots.SnapshotException: [myrepo-mysnapshotname/uuid] no longer master
```

And potentially a message about a snapshot with the same name already existing:

```
[2021-09-27T23:50:22.612Z][ERROR][org.elasticsearch.xpack.ilm.IndexLifecycleRunner] [instance-0000000152] policy [my-ilm-policy] for index [myindex] failed on step [{"phase":"cold","action":"searchable_snapshot","name":"create-snapshot"}]. Moving to ERROR step
org.elasticsearch.snapshots.InvalidSnapshotNameException: [myrepo:mysnapshotname] Invalid snapshot name [mysnapshotname], snapshot with the same name already exists
	at org.elasticsearch.snapshots.SnapshotsService.ensureSnapshotNameAvailableInRepo(SnapshotsService.java:754) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.snapshots.SnapshotsService.access$5200(SnapshotsService.java:123) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.snapshots.SnapshotsService$2.execute(SnapshotsService.java:459) ~[elasticsearch-7.14.2.jar:7.14.2]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$1.execute(BlobStoreRepository.java:480) ~[elasticsearch-7.14.2.jar:7.14.2]
```

### PR DESCRIPTION
**Pull request by gmarouli**
### Issue #83694
During a master restart or failover the step `CreateSnapshotStep` of the action `SearchableSnapshotAction` can be invoked twice. This will cause the second time to fail because the snapshot was already created, the error will set ILM in an error state and it will try the step with the same consequences, aka ILM will be stuck permanently in this loop.  See https://github.com/elastic/elasticsearch/issues/83694#issuecomment-1033139334 for more details about why is this happening.

### Approach
In this PR we are catching the exception that the `SnapshotService` is throwing and we check if the reason was that the snapshot has been previously created. In this case, we mark the creation as incomplete and we follow the existing mechanism of returning back to `CleanupSnapshotStep`. 

We consider the snapshot incomplete for simplicity. The downside is that we restart creating the snapshot every time.

Closes  #83694

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CreateSnapshotStep.java [hunk 1]
```diff
@@ -61,7 +62,17 @@ public void onResponse(Boolean complete) {
...
             @Override
             public void onFailure(Exception e) {
-                listener.onFailure(e);
+                if (snapshotAlreadyCreated(e)) {
+                    logger.warn(e.getMessage());
+                    // we treat a snapshot that was already created before this step as an incomplete snapshot. This means that the
+                    // execution will be successful from ILM's perspective and it will go to the next step, which is cleaning the incomplete
+                    // snapshot and try again. This scenario is triggered by a master restart or a failover which can result in a double
+                    // invocation of this step.
+                    onResponseResult.set(false);
```
Comment (joegallo) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CreateSnapshotStep.java:71]: What about something like `onResponse(false)` so that you reroute to the other handler rather than repeating some of the same logic? The comment here could be simpler then, too.

Comment (gmarouli) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CreateSnapshotStep.java:71]: Very good suggestion, I will adjust it.

File: server/src/main/java/org/elasticsearch/snapshots/InvalidSnapshotNameException.java [hunk 2]
```diff
@@ -18,17 +22,63 @@
...
+
+    public InvalidSnapshotNameException(final String repositoryName, final String snapshotName, Reason reason) {
+        super(repositoryName, snapshotName, "Invalid snapshot name [" + snapshotName + "], " + reason.description);
+        this.reason = reason;
     }
 
     public InvalidSnapshotNameException(StreamInput in) throws IOException {
         super(in);
+        if (in.getVersion().onOrAfter(Version.V_8_2_0)) {
+            reason = in.readOptionalEnum(Reason.class);
```
Comment (joegallo) [inline server/src/main/java/org/elasticsearch/snapshots/InvalidSnapshotNameException.java:36]: On 8.2.0 and above, will this really be optional? That is, maybe this should be `readEnum` and `writeEnum`?

File: server/src/main/java/org/elasticsearch/snapshots/InvalidSnapshotNameException.java [hunk 3]
```diff
@@ -18,17 +22,63 @@
...
+        } else {
+            reason = null;
```
Comment (joegallo) [inline server/src/main/java/org/elasticsearch/snapshots/InvalidSnapshotNameException.java:38]: What about having something like `reason = Reason.UNKNOWN` rather than `reason = null`? `UNKNOWN` could be documented as being just for backward compatibility purposes (you could even validate that it's not permitted in the non-StreamInput constructor). Then all the `@Nullable`s could drop out. (Note: I'm not even entirely sure I agree with myself on this one -- this is very much "what do you think?".)

File: server/src/main/java/org/elasticsearch/snapshots/InvalidSnapshotNameException.java (hunk 2 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/snapshots/InvalidSnapshotNameException.java:36]: That's a good point, I can't think of a good reason to make it optional, I mean when deeming a name invalid the reasons are usually straightforward.... I will change it.

File: server/src/main/java/org/elasticsearch/snapshots/InvalidSnapshotNameException.java (hunk 3 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/snapshots/InvalidSnapshotNameException.java:38]: Interesting, I was reluctant to introduce `Reason.UNKNOWN` because I thought the combination of an optional reason and null it represented better the fact that the reason is missing because of backwards compatibility.

On the other hand, I like the completeness of having `Reason.UNKNOWN` instead of null, especially if you think using a enum with a switch expression.

I am thinking of introducing this and specifying that it is because of bwc. This would limit future abuse of the value and it can be cleaned up when the backwards compatible clause is not needed anymore.

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by joegallo** [comment]
@dakrone can you take a look at this one? I'm thinking about how Enums are serialized, and I have a little bit of anxiety that we might be introducing a lot of BWC annoyances here -- e.g. like if reordering the enum constants or adding a new one becomes a potentially breaking change, etc.

That is, imagine if ES 8.6.0 introduces a new enum'ed reason for snapshotting to fail, if it's added at the end then the only problem is that prior versions wouldn't know that that constant exists (so their `readEnum` call could fail). OTOH if the new reason is added in the middle of the list, then the ordinals would all be off, etc. Or am I overthinking this?

**Comment by gmarouli** [comment]
> @dakrone can you take a look at this one? I'm thinking about how Enums are serialized, and I have a little bit of anxiety that we might be introducing a lot of BWC annoyances here -- e.g. like if reordering the enum constants or adding a new one becomes a potentially breaking change, etc.
> 
> That is, imagine if ES 8.6.0 introduces a new enum'ed reason for snapshotting to fail, if it's added at the end then the only problem is that prior versions wouldn't know that that constant exists (so their `readEnum` call could fail). OTOH if the new reason is added in the middle of the list, then the ordinals would all be off, etc. Or am I overthinking this?
> 
> edit: OTOH I see a ton of `readEnum` calls elsewhere with no particular ceremony, so either this problem is only in my head (❓) or it's everywhere (😬).

I think you are right..... I do not see how you could avoid this issue with this implementation. Changing this enum should be done in a backwards compatible way with regards to ordinals. I think no matter what we do, when changing a serialized class one needs to be careful, but if you would prefer to change this to something less annoying, I am up for that too. We could change the way it's serialized and deserialized for example to not rely on order. What do you think?

**Review by dakrone — COMMENTED** [review]
I think this looks better than an enum-based approach. I left a couple of pretty minor comments. @joegallo do you want to re-review also?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CreateSnapshotStep.java [hunk 4]
```diff
@@ -61,7 +62,14 @@ public void onResponse(Boolean complete) {
 
             @Override
             public void onFailure(Exception e) {
-                listener.onFailure(e);
+                if (e instanceof SnapshotNameAlreadyInUseException) {
+                    logger.warn(e.getMessage());
```
[the remark this answers is not in the document]
Comment (gmarouli) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CreateSnapshotStep.java:66]: Sounds good, I will change it

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotNameAlreadyInUseException.java [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+
+import java.io.IOException;
+
+/**
+ * Thrown on the attempt to create a snapshot with a name that is taken by a snapshot in progress and a snapshot that already exists.
+ */
+public class SnapshotNameAlreadyInUseException extends InvalidSnapshotNameException {
+
+    public SnapshotNameAlreadyInUseException(final String repositoryName, final String snapshotName, String desc) {
+        super(repositoryName, snapshotName, "Invalid snapshot name [" + snapshotName + "], " + desc);
```
[the remark this answers is not in the document]
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotNameAlreadyInUseException.java:21]: The description has the information about the snapshot being already in progress or existing. If this error was only triggered by ILM I would say that this distinction doesn't matter much, but since this can also be triggered by an API, I believe being more specific is better. Now the error messages are:
- `Invalid snapshot name [snapshot123], snapshot with the same name is already in-progress`
- `Invalid snapshot name [snapshot123], snapshot with the same name already exists`

What do you think?

Comment (joegallo) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotNameAlreadyInUseException.java:21]: The description gets double prefixed here since the super constructor already does the description prefixing, too. 

e.g. `Invalid snapshot name [snapshot], Invalid snapshot name [snapshot], [...]`

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CreateSnapshotStep.java [hunk 6]
```diff
@@ -61,7 +62,16 @@ public void onResponse(Boolean complete) {
 
             @Override
             public void onFailure(Exception e) {
-                listener.onFailure(e);
+                if (e instanceof SnapshotNameAlreadyInUseException) {
+                    // we treat a snapshot that was already created before this step as an incomplete snapshot. This scenario is triggered
+                    // by a master restart or a failover which can result in a double invocation of this step.
+                    logger.warn(
+                        "snapshot is already in-progress or in-use, this index will attempt to clean it up and retry snapshot creation"
```
Comment (joegallo) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CreateSnapshotStep.java:69]: Can you format in a bit more context on this log message? Maybe something like `snapshot [somesnapshotname] is already ... for index [someindexname], will attempt ...` (you could even use the new pattern matching for `instanceof` syntax)?

**Review by joegallo — CHANGES_REQUESTED** [review]
Mostly LGTM.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CreateSnapshotStep.java (hunk 6 above)
Comment (gmarouli) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/CreateSnapshotStep.java]: Done.

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by joegallo** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by joegallo — APPROVED** [review]

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@dakrone & @joegallo thank you very much for the feedback!

**Comment by dakrone** [comment]
@gmarouli what are your thoughts about potentially backporting this to 7.17 also?

**Comment by gmarouli** [comment]
> @gmarouli what are your thoughts about potentially backporting this to 7.17 also?

@dakrone I think it makes sense, it's bug fix after all, so we should backport it. I am not sure how to handle the versioning though,  in `ElasticsearchExceptionHandle` we specify the version it was introduced as `8.2.0`,  wouldn't that make it unusable in earlier versions?:
```
        SNAPSHOT_NAME_ALREADY_IN_USE_EXCEPTION(
            org.elasticsearch.snapshots.SnapshotNameAlreadyInUseException.class,
            org.elasticsearch.snapshots.SnapshotNameAlreadyInUseException::new,
            165,
            Version.V_8_2_0
        );
```

**Comment by dakrone** [comment]
@gmarouli that is a good question, and unfortunately I don't know enough about our exception serialization to know how to fix it. Let me try to figure out who knows more about it.

**Comment by andreidan** [comment]
@dakrone @gmarouli 

What was the outcome of https://github.com/elastic/elasticsearch/pull/84829#issuecomment-1095439857 ? 

Can we find a way to backport or even re-implement this in 7.17? 

@gmarouli Could we in 7.17 catch `InvalidSnapshotNameException` https://github.com/elastic/elasticsearch/commit/e03c2b0161e31f72dd848000efacab97f8c2cdbd#diff-de99cbad875eb82467666e03b94c5b9376e92ce73fa021a99ab58ea4c2bae4f6L445 and match the message - I know not pretty :) - but we can add a unit test to make sure it stays the same for this particular case in 7.17

Equally - otherwise let's introduce a custom exception in 7.17 just for this?

What do you think?
