### PR TITLE
Fail allocation of new primaries in empty cluster

### LINKED ISSUE #41073: A cluster with no data nodes or indices reports YELLOW health when an index is created.
If you start up a new cluster without any data nodes then it will report `green` health, because there are no unassigned shards. If you subsequently create an index it will report `yellow` health because there are unassigned newly-created primaries. However we never attempt to assign any shards if there are no data nodes so the health will continue to report `yellow` and will never move to `red`:

https://github.com/elastic/elasticsearch/blob/abd861bb9191a3e3edd4f92f7d5c586dfa90281d/server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java#L117-L120

I think in this case we should move the unassigned status for any new shards from `AllocationStatus.NO_ATTEMPT` to `AllocationStatus.DECIDERS_NO` before bailing out, which would result in `red` health.

### PR DESCRIPTION
**Pull request by Gaurav614**
Today if you create an index in a cluster without any data nodes then it will
report `yellow` health because it never attempts to assign any shards if there
are no data nodes, so the new shards remain at `AllocationStatus.NO_ATTEMPT`. This commit
moves the new primaries to `AllocationStatus.DECIDERS_NO` in this situation,
causing the cluster health to move to `red`.

Fixes #41073

### CODE REVIEW

**Comment by Gaurav614** [comment]
Hey! Any comments on the PR?

**Comment by DaveCTurner** [comment]
@elasticmachine update branch please

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 1]
```diff
@@ -141,6 +143,35 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
...
+     */
+    private void setAllocationStatus(RoutingAllocation allocation){
+        RoutingNodes routingNodes = allocation.routingNodes();
+        RoutingNodes.UnassignedShards unassignedShards = routingNodes.unassigned();
+        if (unassignedShards.isEmpty()) {
+            return;
+        }
+        RoutingNodes.UnassignedShards.UnassignedIterator unassignedIterator = unassignedShards.iterator();
+        while (unassignedIterator.hasNext()) {
+            ShardRouting shard = unassignedIterator.next();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: `shard` is a bit of an ambiguous name for a variable.

```suggestion
            ShardRouting shardRouting = unassignedIterator.next();
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 2]
```diff
@@ -141,6 +143,35 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
...
+            UnassignedInfo shardInfo = shard.unassignedInfo();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: `shardInfo` is a bit of an ambiguous name for a variable.

```suggestion
            UnassignedInfo unassignedInfo = shard.unassignedInfo();
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 3]
```diff
@@ -141,6 +143,35 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
...
+            if (shard.primary() && shardInfo.getLastAllocationStatus() == AllocationStatus.NO_ATTEMPT) {
+                UnassignedInfo newInfo = new UnassignedInfo(shardInfo.getReason(), shardInfo.getMessage(), shardInfo.getFailure(),
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: `newInfo` is only used in one place, may as well inline it:

```suggestion
                unassignedIterator.updateUnassigned(new UnassignedInfo(shardInfo.getReason(), shardInfo.getMessage(), shardInfo.getFailure(),
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 4]
```diff
@@ -141,6 +143,35 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
...
+    /**
+     * This method is called when there are no data nodes in the cluster.
+     *
+     * Newly created unassigned primary shards, with no prior allocation attempts
+     * are classified as yellow instead of red by cluster health.
+     * This function explicitly sets their allocation status to DECIDERS_NO, to
+     * indicate red indices with unassigned shards.
+     */
+    private void setAllocationStatus(RoutingAllocation allocation){
+        RoutingNodes routingNodes = allocation.routingNodes();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: Suggest adding `assert routingNodes.size() == 0 : routingNodes` to better document this method's preconditions.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 5]
```diff
@@ -141,6 +143,35 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
...
 
+    /**
+     * This method is called when there are no data nodes in the cluster.
+     *
+     * Newly created unassigned primary shards, with no prior allocation attempts
+     * are classified as yellow instead of red by cluster health.
+     * This function explicitly sets their allocation status to DECIDERS_NO, to
+     * indicate red indices with unassigned shards.
+     */
+    private void setAllocationStatus(RoutingAllocation allocation){
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: Suggest a more descriptive name, for example:

```suggestion
    private void failAllocationOfNewPrimaries(RoutingAllocation allocation) {
```

With this, plus the assertion below, I think the Javadoc is unnecessary and should be removed.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 6]
```diff
@@ -115,7 +116,8 @@ private void setThreshold(float threshold) {
     @Override
     public void allocate(RoutingAllocation allocation) {
         if (allocation.routingNodes().size() == 0) {
-            /* with no nodes this is pointless */
+            // If no data node then set AllocationStatus to DECIDERS_NO
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: No need for this comment if the method is better-named.

```suggestion
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 7]
```diff
@@ -141,6 +143,35 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
...
+     * Newly created unassigned primary shards, with no prior allocation attempts
+     * are classified as yellow instead of red by cluster health.
+     * This function explicitly sets their allocation status to DECIDERS_NO, to
+     * indicate red indices with unassigned shards.
+     */
+    private void setAllocationStatus(RoutingAllocation allocation){
+        RoutingNodes routingNodes = allocation.routingNodes();
+        RoutingNodes.UnassignedShards unassignedShards = routingNodes.unassigned();
+        if (unassignedShards.isEmpty()) {
+            return;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: I don't think this check is necessary?

File: server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java [hunk 8]
```diff
@@ -0,0 +1,153 @@
...
+        assertEquals(ClusterHealthStatus.RED, clusterHealthStatus);
+    }
+
+    /**
+     * The method test for scenario where we have a cluster with indices and data nodes
+     * and then all data nodes gets terminated now new index is created then
+     * all indices and cluster health should be red, but last allocation attempts of new index shards v/s
+     * old index shards should be different.
+     */
+    public void testAllocationStatusForTerminatedNodes() {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java]: Great stuff. As far as I can tell, we don't have any other tests that assert things about cluster health in an `ESAllocationTestCase`, so this is a nice addition to the test suite. Also these tests take some effort to write, so it's greatly appreciated.

I think it'd be simpler to work with a single index per test, rather than dealing with the two indices here. Also it'd be good to test yellow health as well as the red and green cases. How about the following flow instead?

- create a cluster with no data nodes, assert green health
- create an index with a random number of shards and 1 replica, assert red health
- add a data node, assert yellow health
- add another data node, assert green health
- remove a data node, assert yellow health
- remove a data node, assert red health.
- remove the index, assert green health.

File: server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java [hunk 9]
```diff
@@ -0,0 +1,153 @@
...
+        //creates one master and two data nodes
+        DiscoveryNodes.Builder nodeBuilder = DiscoveryNodes.builder().add(newNode("node_m", Collections.singleton(DiscoveryNode.Role.MASTER)))
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java]: The master node isn't really necessary here but written like this it looks like it's important to this test. If you wanted, you could reasonably add a random number (possibly zero) non-data nodes (master nodes, coordinating-only nodes, etc) to document that the non-data nodes aren't important.

File: server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java [hunk 10]
```diff
@@ -0,0 +1,153 @@
...
+                .add(newNode("node_d1", Collections.singleton(DiscoveryNode.Role.DATA)))
+                .add(newNode("node_d2", Collections.singleton(DiscoveryNode.Role.DATA)));
+        MetaData metaData = MetaData.builder()
+                .put(IndexMetaData.builder("TestIndex")
+                        .settings(settings(Version.CURRENT))
+                        .numberOfShards(2)
+                        .numberOfReplicas(0))
+                .build();
+        RoutingTable routingTable = RoutingTable.builder().addAsNew(metaData.index("TestIndex")).build();
+        ClusterState state = ClusterState.builder(new ClusterName("test_cluster"))
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java]:
```suggestion
        ClusterState state = ClusterState.builder(ClusterName.DEFAULT)
```

File: server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java [hunk 11]
```diff
@@ -0,0 +1,153 @@
...
+     * all indices and cluster health should be red, but last allocation attempts of new index shards v/s
+     * old index shards should be different.
+     */
+    public void testAllocationStatusForTerminatedNodes() {
+        //creates one master and two data nodes
+        DiscoveryNodes.Builder nodeBuilder = DiscoveryNodes.builder().add(newNode("node_m", Collections.singleton(DiscoveryNode.Role.MASTER)))
+                .add(newNode("node_d1", Collections.singleton(DiscoveryNode.Role.DATA)))
+                .add(newNode("node_d2", Collections.singleton(DiscoveryNode.Role.DATA)));
+        MetaData metaData = MetaData.builder()
+                .put(IndexMetaData.builder("TestIndex")
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java]: Elsewhere in the test suite indices normally have all-lowercase names:

```suggestion
                .put(IndexMetaData.builder("test")
```

File: server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java [hunk 12]
```diff
@@ -0,0 +1,153 @@
...
+        RoutingNodes.UnassignedShards unassignedShards = routingNodes.unassigned();
+        assertFalse(unassignedShards.isEmpty());
+        RoutingNodes.UnassignedShards.UnassignedIterator unassignedIterator = unassignedShards.iterator();
+        while (unassignedIterator.hasNext()) {
+            ShardRouting shard = unassignedIterator.next();
+            UnassignedInfo shardInfo = shard.unassignedInfo();
+            /* asserting that the TestIndex shards have different AllocationStatus than DECIDERS_NO
+               and NewTestIndex status is DECIDERS_NO */
+            if (shard.getIndexName().equals("TestIndex")) {
+                assertNotEquals(shardInfo.getLastAllocationStatus(), UnassignedInfo.AllocationStatus.DECIDERS_NO);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java]: I think we don't really need to do these assertions and it'd be better to keep this test focussed on the cluster health.

File: server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java [hunk 13]
```diff
@@ -0,0 +1,153 @@
...
+                .nodes(node)
+                .metaData(metaData)
+                .routingTable(routingTable)
+                .build();
+        MockAllocationService service = createAllocationService();
+        state = service.reroute(state, "reroute");
+        return state;
+    }
+
+    public void testClusterHealthWithNoDataNodes() {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java]: I think this test can be folded into the one below, see my other comments.

File: server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java [hunk 14]
```diff
@@ -0,0 +1,153 @@
...
+
+import static org.elasticsearch.cluster.routing.ShardRoutingState.INITIALIZING;
+import static org.elasticsearch.cluster.routing.ShardRoutingState.STARTED;
+
+/**
+ * The test case checks for the scenario when there is no data node in the cluster and only
+ * master is active. At this moment when index creation is tried, the cluster health status should
+ * change to RED
+ */
+public class NoDataNodesHealthTests extends ESAllocationTestCase {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java]: How about this name?

```suggestion
public class ClusterHealthAllocationTests extends ESAllocationTestCase {
```

File: server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java [hunk 15]
```diff
@@ -0,0 +1,153 @@
...
+                        .numberOfReplicas(0))
+                .build();
+        RoutingTable routingTable = RoutingTable.builder().addAsNew(metaData.index("TestIndex")).build();
+        ClusterState state = ClusterState.builder(new ClusterName("test_cluster"))
+                .nodes(nodeBuilder.build())
+                .metaData(metaData)
+                .routingTable(routingTable)
+                .build();
+        MockAllocationService allocationService = createAllocationService();
+        //perform allocation of TestIndex
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java]: There's no real need for these comments here, since they only reiterate what the test is doing. I prefer comments only when there's something tricky to explain.

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Thanks @Gaurav614 for taking this on. There's been a few changes in `master` that mean your branch no longer compiles, but it will be simple enough to fix it up. I have left some small suggestions, including an idea for a slightly different test that covers a few more cases in a simpler way.

**Comment by DaveCTurner** [comment]
image

Please don't force-push to PR branches. There was no harm done in this case, but force-pushing loses history and review comments.

**Comment by Gaurav614** [comment]
@DaveCTurner Thanks for reviewing the pull request. I am working on the fix to the comments.

File: server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java (hunk 8 above)
Comment (Gaurav614) [reply server/src/test/java/org/elasticsearch/cluster/health/NoDataNodesHealthTests.java]: Thanks. I think this flow will be better and I will remove below assertion and make test case focus more on only Cluster health.

**Comment by DaveCTurner** [comment]
Hi @Gaurav614, just checking if you're still working on this and if you need any help?

**Comment by Gaurav614** [comment]
> Hi @Gaurav614, just checking if you're still working on this and if you need any help?

@DaveCTurner Thanks for your helping gesture. I am working on it. And apologies for the delay, as I was out due to some personal emergency. 
Will soon raise a new revision for it. And will ping you incase need any help.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java (hunk 6 above)
Comment (Gaurav614) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: Will resolve in next revision. Please review other changes

**Comment by DaveCTurner** [comment]
Hey @Gaurav614, just checking in again. Are you still working on this PR?

**Comment by Gaurav614** [comment]
> Hey @Gaurav614, just checking in again. Are you still working on this PR?

Hey @DaveCTurner, I had pushed the new commits on 25th July. And requested for your review on it. Kindly review that.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 16]
```diff
@@ -141,6 +143,24 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
         return new ShardAllocationDecision(allocateUnassignedDecision, moveDecision);
     }
 
+    private void failedAllocationOfNewPrimaries(RoutingAllocation allocation){
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]: Minor change:

```suggestion
    private void failAllocationOfNewPrimaries(RoutingAllocation allocation) {
```

(change name to the imperative mood, and fix whitespace)

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 17]
```diff
@@ -141,6 +143,24 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
...
+        RoutingNodes routingNodes = allocation.routingNodes();
+        assert routingNodes.size() == 0 : routingNodes;
+        RoutingNodes.UnassignedShards unassignedShards = routingNodes.unassigned();
+        RoutingNodes.UnassignedShards.UnassignedIterator unassignedIterator = unassignedShards.iterator();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]:
```suggestion
        final RoutingNodes.UnassignedShards.UnassignedIterator unassignedIterator = routingNodes.unassigned().iterator();
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 18]
```diff
@@ -141,6 +143,24 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
         return new ShardAllocationDecision(allocateUnassignedDecision, moveDecision);
     }
 
+    private void failedAllocationOfNewPrimaries(RoutingAllocation allocation){
+        RoutingNodes routingNodes = allocation.routingNodes();
+        assert routingNodes.size() == 0 : routingNodes;
+        RoutingNodes.UnassignedShards unassignedShards = routingNodes.unassigned();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]:
```suggestion
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 19]
```diff
@@ -141,6 +143,24 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
...
+        RoutingNodes.UnassignedShards.UnassignedIterator unassignedIterator = unassignedShards.iterator();
+        while (unassignedIterator.hasNext()) {
+            ShardRouting shardRouting = unassignedIterator.next();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]:
```suggestion
            final ShardRouting shardRouting = unassignedIterator.next();
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 20]
```diff
@@ -141,6 +143,24 @@ public ShardAllocationDecision decideShardAllocation(final ShardRouting shard, f
...
+            UnassignedInfo unassignedInfo = shardRouting.unassignedInfo();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java]:
```suggestion
            final UnassignedInfo unassignedInfo = shardRouting.unassignedInfo();
```

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 21]
```diff
@@ -0,0 +1,102 @@
...
+import org.elasticsearch.cluster.routing.RoutingTable;
+
+import java.util.Collections;
+
+import static org.elasticsearch.cluster.routing.ShardRoutingState.*;
+
+public class ClusterHealthAllocationTests extends ESAllocationTestCase {
+    public void testClusterHealth() {
+        ClusterState clusterState = ClusterState.builder(ClusterName.DEFAULT).build();
+        clusterState = addNode(clusterState, "node_m", true);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: I think we should assert that the presence of a master doesn't really matter for this test:

```suggestion
        if (randomBoolean()) {
            clusterState = addNode(clusterState, "node_m", true);
        }
```

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 22]
```diff
@@ -0,0 +1,102 @@
...
+            .put(IndexMetaData.builder("test")
+                .settings(settings(Version.CURRENT))
+                .numberOfShards(2)
+                .numberOfReplicas(1))
+            .build();
+        RoutingTable routingTable = RoutingTable.builder().addAsNew(metaData.index("test")).build();
+        clusterState = ClusterState.builder(clusterState).metaData(metaData).routingTable(routingTable).build();
+        MockAllocationService allocation = createAllocationService();
+        clusterState = allocation.reroute(clusterState, "reroute");
+        assertTrue(clusterState.nodes().getDataNodes().size() == 0);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: Please use `assertEquals` to get more useful feedback in case of a failure:

```suggestion
        assertEquals(0, clusterState.nodes().getDataNodes().size());
```

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 23]
```diff
@@ -0,0 +1,102 @@
...
+        assertTrue(clusterState.nodes().getMasterNodes().size() == 1);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: Since the master nodes don't matter, I think we can drop this line.

```suggestion
```

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 24]
```diff
@@ -0,0 +1,102 @@
...
+        MetaData metaData = MetaData.builder()
+            .put(IndexMetaData.builder("test")
+                .settings(settings(Version.CURRENT))
+                .numberOfShards(2)
+                .numberOfReplicas(1))
+            .build();
+        RoutingTable routingTable = RoutingTable.builder().addAsNew(metaData.index("test")).build();
+        clusterState = ClusterState.builder(clusterState).metaData(metaData).routingTable(routingTable).build();
+        MockAllocationService allocation = createAllocationService();
+        clusterState = allocation.reroute(clusterState, "reroute");
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: We only really care about what happens after everything has settled down, so I suggest doing this instead of rerouting and then starting any initialising shards in a separate step:

```suggestion
        clusterState = applyStartedShardsUntilNoChange(clusterState, allocationService);
```

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 25]
```diff
@@ -0,0 +1,102 @@
...
+        assertTrue(clusterState.nodes().getDataNodes().size() == 0);
+        assertTrue(clusterState.nodes().getMasterNodes().size() == 1);
+        assertEquals(ClusterHealthStatus.RED, getClusterHealthStatus(clusterState));
+        clusterState = addNode(clusterState, "node_d1", false);
+        assertTrue(clusterState.nodes().getDataNodes().size() == 1);
+        clusterState = allocation.reroute(clusterState, "reroute");
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: As above, let's use `applyStartedShardsUntilNoChange` here instead of separate reroute/applyStartedShards steps.

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 26]
```diff
@@ -0,0 +1,102 @@
...
+        // starting primaries
+        clusterState = allocation.applyStartedShards(clusterState, clusterState.getRoutingNodes().shardsWithState(INITIALIZING));
+        assertEquals(ClusterHealthStatus.YELLOW, getClusterHealthStatus(clusterState));
+        clusterState = addNode(clusterState, "node_d2", false);
+        clusterState = allocation.reroute(clusterState, "reroute");
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: As above, let's use `applyStartedShardsUntilNoChange` here instead of separate reroute/applyStartedShards steps.

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 27]
```diff
@@ -0,0 +1,102 @@
...
+        clusterState = allocation.applyStartedShards(clusterState, clusterState.getRoutingNodes().shardsWithState(INITIALIZING));
+        assertEquals(ClusterHealthStatus.GREEN, getClusterHealthStatus(clusterState));
+        clusterState = removeNode(clusterState, "node_d1");
+        assertEquals(ClusterHealthStatus.YELLOW, getClusterHealthStatus(clusterState));
+        clusterState = removeNode(clusterState, "node_d2");
+        assertEquals(ClusterHealthStatus.RED, getClusterHealthStatus(clusterState));
+        routingTable = RoutingTable.builder(routingTable).remove("test").build();
+        metaData = MetaData.builder(clusterState.metaData()).remove("test").build();
+        clusterState = ClusterState.builder(clusterState).routingTable(routingTable).metaData(metaData).build();
+        assertTrue(clusterState.nodes().getDataNodes().size() == 0);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: As above, prefer `assertEquals` here.

```suggestion
        assertEquals(0, clusterState.nodes().getDataNodes().size());
```

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 28]
```diff
@@ -0,0 +1,102 @@
...
+            .build();
+        return clusterState;
+    }
+
+    private ClusterState removeNode(ClusterState clusterState, String nodeName) {
+        clusterState = ClusterState.builder(clusterState)
+            .nodes(DiscoveryNodes.builder(clusterState.getNodes())
+                .remove(nodeName).build())
+            .build();
+        clusterState = createAllocationService().deassociateDeadNodes(clusterState, true, "reroute");
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: I think we should pass the `allocationService` into this method rather than creating a new one here. Also there's no need to mutate `clusterState`:

```suggestion
        return allocationService.deassociateDeadNodes(clusterState, true, "reroute");
```

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 29]
```diff
@@ -0,0 +1,102 @@
...
+        assertTrue(clusterState.nodes().getDataNodes().size() == 0);
+        assertTrue(clusterState.nodes().getMasterNodes().size() == 1);
+        assertEquals(ClusterHealthStatus.GREEN, getClusterHealthStatus(clusterState));
+    }
+
+    private ClusterState addNode(ClusterState clusterState, String nodeName, boolean isMaster) {
+
+        DiscoveryNodes.Builder nodeBuilder = DiscoveryNodes.builder(clusterState.getNodes());
+        if (isMaster) {
+            nodeBuilder = nodeBuilder.add(newNode(nodeName, Collections.singleton(DiscoveryNode.Role.MASTER)));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: No need to mutate `nodeBuilder` here:

```suggestion
           nodeBuilder.add(newNode(nodeName, Collections.singleton(DiscoveryNode.Role.MASTER)));
```

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 30]
```diff
@@ -0,0 +1,102 @@
...
+        } else {
+            nodeBuilder = nodeBuilder.add(newNode(nodeName, Collections.singleton(DiscoveryNode.Role.DATA)));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: No need to mutate `nodeBuilder` here:

```suggestion
           nodeBuilder.add(newNode(nodeName, Collections.singleton(DiscoveryNode.Role.DATA)));
```

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 31]
```diff
@@ -0,0 +1,102 @@
...
+        }
+        clusterState = ClusterState.builder(clusterState)
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: No need to mutate `clusterState` here:

```suggestion
        return ClusterState.builder(clusterState).nodes(nodeBuilder).build();
```

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Thanks @Gaurav614; the last message I received on this PR indicated there'd be more changes so I was waiting for them to land before taking a look. I left some more suggestions. Could you merge the latest master too?

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java [hunk 32]
```diff
@@ -0,0 +1,102 @@
...
+import org.elasticsearch.cluster.node.DiscoveryNode;
+import org.elasticsearch.cluster.node.DiscoveryNodes;
+import org.elasticsearch.cluster.routing.RoutingTable;
+
+import java.util.Collections;
+
+import static org.elasticsearch.cluster.routing.ShardRoutingState.*;
+
+public class ClusterHealthAllocationTests extends ESAllocationTestCase {
+    public void testClusterHealth() {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: Test looks great by the way. Could you add a blank line between each conceptual "step" (i.e. after the assertion of the cluster health) to make it a bit easier to read.

File: server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java (hunk 25 above)
Comment (Gaurav614) [reply server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: Hey @DaveCTurner  I think this wont work because we need to first change shards state to `INITIALIZING` state and then `applyStartedShards`. Using only `applyStartedShardsUntilNoChange` without `reroute` wont change the shard state to `INITIALIZING`.

Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: I'm surprised by this, because `applyStartedShardsUntilNoChange` repeatedly calls `startShardsAndReroute` which calls `applyStartedShards` and then `reroute`. If there are no `INITIALIZING` shards then the first `applyStartedShards` will do nothing, but the `reroute` should make some `INITIALIZING` shards that the next `applyStartedShards` will then move to `STARTED`.

You say you _think_ this won't work. Did you try it? If so, and it didn't work, then can you share your attempt so I can investigate further?

Comment (Gaurav614) [reply server/src/test/java/org/elasticsearch/cluster/health/ClusterHealthAllocationTests.java]: Sorry @DaveCTurner I was using a previous version which didnt  `startInitializingShardsAndReroute`
have https://github.com/elastic/elasticsearch/blob/master/test/framework/src/main/java/org/elasticsearch/cluster/ESAllocationTestCase.java#L150

Let me pull it out with master . Thank you

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Review by DaveCTurner — APPROVED** [review]
LGTM. Nice work @Gaurav614, thanks for the extra iterations to get this so polished. I merged `master`, fixed a couple of whitespace issues, and triggered a CI run.

**Comment by DaveCTurner** [comment]
CI failures were apparently expected, see https://github.com/elastic/elasticsearch/pull/43284/commits/3c57592a1f2cf05f9ed5ab40140b9c01b7cdae52.

@elasticmachine test this please

**Comment by Gaurav614** [comment]
@DaveCTurner Thanks a lot man for merging the changes !!
