### PR TITLE
[Inference API] Set MockResponse body at runtime to prevent race

### LINKED ISSUE #138451: [CI] JinaAIServiceTests test_Embedding_ChunkedInfer_LateChunkingEnabled failing
**Build Scans:**
- [elasticsearch-periodic #11481 / openjdk21_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/si7m5izck4bug)
- [elasticsearch-pull-request #105417 / part-2](https://gradle-enterprise.elastic.co/s/b4qji2xtvqvmg)
- [elasticsearch-pull-request #105335 / part-2](https://gradle-enterprise.elastic.co/s/7ebw4l4k5iomm)
- [elasticsearch-pull-request #105325 / part-2](https://gradle-enterprise.elastic.co/s/wrh3siospikja)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.services.jinaai.JinaAIServiceTests.test_Embedding_ChunkedInfer_LateChunkingEnabled" -Dtests.seed=6D9206B5E037EC1C -Dtests.locale=zh-Hans-CN -Dtests.timezone=Zulu -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.services.jinaai.JinaAIServiceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test_Embedding_ChunkedInfer_LateChunkingEnabled'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [0]; expected:<0.123> but was:<0.223>
```

**Issue Reasons:**
- [main] 4 failures in test test_Embedding_ChunkedInfer_LateChunkingEnabled (1.8% fail rate in 218 executions)
- [main] 3 failures in step part-2 (2.3% fail rate in 130 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (2.4% fail rate in 125 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #140890: [CI] JinaAIServiceTests test_embeddingModel_chunkedInfer_batchesCallsWhenLateChunkingEnabled failing
**Build Scans:**
- [elasticsearch-intake #33442 / part2](https://gradle-enterprise.elastic.co/s/h5xlm3s2n2hlw)
- [elasticsearch-pull-request #114754 / part-2](https://gradle-enterprise.elastic.co/s/rixqmtoche5oc)
- [elasticsearch-pull-request #114728 / checkpart2_ipv6-tests](https://gradle-enterprise.elastic.co/s/ee7dkjucidyj6)
- [elasticsearch-pull-request #114686 / checkpart2_ipv6-tests](https://gradle-enterprise.elastic.co/s/dve6w7pfyfru2)
- [elasticsearch-pull-request #114415 / checkpart2_ipv6-tests](https://gradle-enterprise.elastic.co/s/cih7amqd3ok6a)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.services.jinaai.JinaAIServiceTests.test_embeddingModel_chunkedInfer_batchesCallsWhenLateChunkingEnabled" -Dtests.seed=9C5231F27018DA5 -Dtests.locale=es-PE -Dtests.timezone=GB -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.services.jinaai.JinaAIServiceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test_embeddingModel_chunkedInfer_batchesCallsWhenLateChunkingEnabled'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [0]; expected:<0.123> but was:<0.223>
```

**Issue Reasons:**
- [main] 5 failures in test test_embeddingModel_chunkedInfer_batchesCallsWhenLateChunkingEnabled (0.8% fail rate in 665 executions)
- [main] 3 failures in step checkpart2_ipv6-tests (75.0% fail rate in 4 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (1.0% fail rate in 392 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by DonalEvans**
This commit adds the ability to set the body of a MockResponse at runtime to allow the content of the body to be determined by the MockRequest that is supposed to generate the response. This prevents a race condition where responses were not being paired up with their intended requests due to the requests being sent in parallel.

Closes #138451
Closes #140890

### CODE REVIEW

File: x-pack/plugin/core/src/test/java/org/elasticsearch/test/http/MockWebServer.java [hunk 1]
```diff
@@ -137,6 +137,10 @@ public void start() throws IOException {
             try {
                 MockResponse response = responses.poll();
                 MockRequest request = createRequest(s);
+
+                // Update the response body based on the request if a body generator function was specified in the response
+                response.setBodyFromRequest(request);
+
```
Comment (jonathan-buttner) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/test/http/MockWebServer.java:143]: How about we also update `getStartOfBody` to call a new getter for the `bodyGenerator` to check if the function is non-null. If so we can return a new string like `body not available until request made` or something like that to make it more clear why the body is not available yet instead of just returning an empty string.

**Review by jonathan-buttner — APPROVED** [review]
Thanks for these changes. Just left a suggestion about tracing in the mock web server.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/test/http/MockWebServer.java (hunk 1 above)
Comment (DonalEvans) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/test/http/MockWebServer.java:143]: Done!
