### PR TITLE
Fix bug in circuit-breaker check for geoshape grid aggregations

### LINKED ISSUE #57847: ES crashes with OOM error when running fine-grained geotile_grid aggs on geo_shape
Elasticsearch crashes when running a fine-grained geotile_grid-agg on a geo_shape.

This seems to occur when zooming in on an area _inside_ a large shape.

e.g.
1) Index the world-countries file from EMS: https://maps.elastic.co/v7.7/index.html#file/world_countries
2) The mapping would be something like:
```
{
   "world_countries_v1":{
      "mappings":{
         "properties":{
            "coordinates":{
               "type":"geo_shape"
            },
            "iso2":{
               "type":"text",
               "fields":{
                  "keyword":{
                     "type":"keyword",
                     "ignore_above":256
                  }
               }
            },
            "iso3":{
               "type":"text",
               "fields":{
                  "keyword":{
                     "type":"keyword",
                     "ignore_above":256
                  }
               }
            },
            "name":{
               "type":"text",
               "fields":{
                  "keyword":{
                     "type":"keyword",
                     "ignore_above":256
                  }
               }
            }
         }
      }
   }
}
```

3) Issue following query
```
{
  "size": 0,
  "aggs": {
    "gridSplit": {
      "geotile_grid": {
        "bounds": {
          "top_left": [
            -117.514295,
            44.54603
          ],
          "bottom_right": [
            -91.48767500000002,
            36.42819
          ]
        },
        "field": "coordinates",
        "precision": 11
      },
      "aggs": {
        "gridCentroid": {
          "geo_centroid": {
            "field": "coordinates"
          }
        }
      }
    }
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [],
  "_source": {
    "excludes": []
  },
  "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "match_all": {}
        },
        {
          "geo_shape": {
            "coordinates": {
              "shape": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      -117.59766,
                      44.59047
                    ],
                    [
                      -117.59766,
                      36.31513
                    ],
                    [
                      -91.40625,
                      36.31513
                    ],
                    [
                      -91.40625,
                      44.59047
                    ],
                    [
                      -117.59766,
                      44.59047
                    ]
                  ]
                ]
              },
              "relation": "INTERSECTS"
            }
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```

Elasticzearch crashes with:

```
[2020-06-08T17:33:47,532][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [Thomass-MBP.attlocal.net] fatal error in thread [elasticsearch[Thomass-MBP.attlocal.net][search][T#9]], exiting
java.lang.OutOfMemoryError: Java heap space
	at org.apache.lucene.util.ArrayUtil.growExact(ArrayUtil.java:323) ~[lucene-core-8.6.0-snapshot-9d6c738ffce.jar:8.6.0-snapshot-9d6c738ffce 9d6c738ffce0c3164691f161ba8b92a615b1e062 - jenkins - 2020-05-20 09:52:47]
	at org.apache.lucene.util.ArrayUtil.grow(ArrayUtil.java:332) ~[lucene-core-8.6.0-snapshot-9d6c738ffce.jar:8.6.0-snapshot-9d6c738ffce 9d6c738ffce0c3164691f161ba8b92a615b1e062 - jenkins - 2020-05-20 09:52:47]
	at org.elasticsearch.index.fielddata.SortingNumericDocValues.resize(SortingNumericDocValues.java:62) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoShapeCellValues.resizeCell(GeoShapeCellValues.java:54) ~[?:?]
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:123) ~[?:?]
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:131) ~[?:?]
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:131) ~[?:?]
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:131) ~[?:?]
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:131) ~[?:?]
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValues(GeoTileGridTiler.java:69) ~[?:?]
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoShapeCellValues.advanceValue(GeoShapeCellValues.java:70) ~[?:?]
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoShapeCellValues.advanceExact(GeoShapeCellValues.java:34) ~[?:?]
	at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregator$1.collect(GeoGridAggregator.java:78) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:107) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:188) ~[lucene-core-8.6.0-snapshot-9d6c738ffce.jar:8.6.0-snapshot-9d6c738ffce 9d6c738ffce0c3164691f161ba8b92a615b1e062 - jenkins - 2020-05-20 09:52:47]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:242) ~[lucene-core-8.6.0-snapshot-9d6c738ffce.jar:8.6.0-snapshot-9d6c738ffce 9d6c738ffce0c3164691f161ba8b92a615b1e062 - jenkins - 2020-05-20 09:52:47]
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:229) ~[lucene-core-8.6.0-snapshot-9d6c738ffce.jar:8.6.0-snapshot-9d6c738ffce 9d6c738ffce0c3164691f161ba8b92a615b1e062 - jenkins - 2020-05-20 09:52:47]
	at org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39) ~[lucene-core-8.6.0-snapshot-9d6c738ffce.jar:8.6.0-snapshot-9d6c738ffce 9d6c738ffce0c3164691f161ba8b92a615b1e062 - jenkins - 2020-05-20 09:52:47]
	at org.elasticsearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:213) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:186) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:445) ~[lucene-core-8.6.0-snapshot-9d6c738ffce.jar:8.6.0-snapshot-9d6c738ffce 9d6c738ffce0c3164691f161ba8b92a615b1e062 - jenkins - 2020-05-20 09:52:47]
	at org.elasticsearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:348) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.search.query.QueryPhase.executeInternal(QueryPhase.java:299) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:151) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.indices.IndicesService.lambda$loadIntoContext$22(IndicesService.java:1382) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.indices.IndicesService$$Lambda$5361/0x0000000801b16840.accept(Unknown Source) ~[?:?]
	at org.elasticsearch.indices.IndicesService.lambda$cacheShardLevelResult$23(IndicesService.java:1434) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.indices.IndicesService$$Lambda$5363/0x0000000801b16040.get(Unknown Source) ~[?:?]
	at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:178) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:161) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.cache.Cache.computeIfAbsent(Cache.java:434) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
fatal error in thread [elasticsearch[Thomass-MBP.attlocal.net][search][T#9]], exiting
java.lang.OutOfMemoryError: Java heap space
	at org.apache.lucene.util.ArrayUtil.growExact(ArrayUtil.java:323)
	at org.apache.lucene.util.ArrayUtil.grow(ArrayUtil.java:332)
	at org.elasticsearch.index.fielddata.SortingNumericDocValues.resize(SortingNumericDocValues.java:62)
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoShapeCellValues.resizeCell(GeoShapeCellValues.java:54)
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:123)
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:131)
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:131)
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:131)
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValuesByRasterization(GeoTileGridTiler.java:131)
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoTileGridTiler.setValues(GeoTileGridTiler.java:69)
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoShapeCellValues.advanceValue(GeoShapeCellValues.java:70)
	at org.elasticsearch.xpack.spatial.search.aggregations.bucket.geogrid.GeoShapeCellValues.advanceExact(GeoShapeCellValues.java:34)
	at org.elasticsearch.search.aggregations.bucket.geogrid.GeoGridAggregator$1.collect(GeoGridAggregator.java:78)
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:107)
	at org.apache.lucene.search.MultiCollector$MultiLeafCollector.collect(MultiCollector.java:188)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.scoreRange(Weight.java:242)
	at org.apache.lucene.search.Weight$DefaultBulkScorer.score(Weight.java:229)
	at org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
	at org.elasticsearch.search.internal.ContextIndexSearcher.searchLeaf(ContextIndexSearcher.java:213)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:186)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:445)
	at org.elasticsearch.search.query.QueryPhase.searchWithCollector(QueryPhase.java:348)
	at org.elasticsearch.search.query.QueryPhase.executeInternal(QueryPhase.java:299)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:151)
	at org.elasticsearch.indices.IndicesService.lambda$loadIntoContext$22(IndicesService.java:1382)
	at org.elasticsearch.indices.IndicesService$$Lambda$5361/0x0000000801b16840.accept(Unknown Source)
	at org.elasticsearch.indices.IndicesService.lambda$cacheShardLevelResult$23(IndicesService.java:1434)
	at org.elasticsearch.indices.IndicesService$$Lambda$5363/0x0000000801b16040.get(Unknown Source)
	at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:178)
	at org.elasticsearch.indices.IndicesRequestCache$Loader.load(IndicesRequestCache.java:161)
```

cc @talevy @nknize

### PR DESCRIPTION
**Pull request by talevy**
There was a bug in the geoshape circuit-breaker check where the
hash values array was being allocated before its new size was
accounted for by the circuit breaker.

Fixes #57847.

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
I'm not really a big fan of guessing that the array will expand to using `oversize`. This is right now but there isn't anything that makes sure this *stays* right.

**Comment by talevy** [comment]
to reproduce OOM, download this USA Elasticsearch document:


[usa.txt](https://github.com/elastic/elasticsearch/files/4761920/usa.txt)

```
curl -X PUT "user:pass@localhost:9200/test?pretty" -H 'Content-Type: application/json' -d'
{
    "mappings" : {
        "properties" : {
            "geometry" : { "type" : "geo_shape" }
        }
    }
}
'

curl -X PUT "user:pass@localhost:9200/test/_doc/usa?pretty" -H 'Content-Type: application/json' -d'@/path/to/usa.txt'

curl -X GET "user:pass@localhost:9200/test/_search" -H 'Content-Type: application/json' -d'
{
  "size": 0,
  "aggs": {
    "gridSplit": {
      "geotile_grid": {
        "field": "geometry",
        "precision": 12
      },
      "aggs": {
        "gridCentroid": {
          "geo_centroid": {
            "field": "geometry"
          }
        }
      }
    }
  }
}
'
```

**Comment by iverase** [comment]
I agree with Nick's point, I wonder if we should add a method to `SortingNumericDocValues` that gives the amount is going to add to a resize so we can be accurate and be tight to the implementation, wdyt?

**Comment by talevy** [comment]
is the concern that that there is nothing tying the usage of `oversize` as an estimate with the actual implementation of growing the array? And that this should be coupled better with the resizing so that the two depend on one another?

Looking at SortingNumericDocValues again now, I'm surprised there is no circuit-breaking usage there since it leverages the same resizing techniques and can, similarly, run into memory pressure. I suspect this has never been a problem because of the bucket size limit?

**Comment by nik9000** [comment]
> Looking at SortingNumericDocValues again now, I'm surprised there is no circuit-breaking usage there since it leverages the same resizing techniques and can, similarly, run into memory pressure. I suspect this has never been a problem because of the bucket size limit?

I bet we just don't hit it because we don't frequently end up with very many values so the array never grows that large. I wonder if we should just pass a `LongConsumer` to the ctor for the breaker so we *always* factor it into the breaker

**Comment by iverase** [comment]
@nik9000 Note that the case for grid aggregations on geo shapes is a bit special in the sense that one value can generate potentially millions of tickets. That is not the case for other bucket aggregations where typically one doc value generates maybe a handful of buckets. (Probably the other aggregations that can generate lots of buckets are related with range field types https://github.com/elastic/elasticsearch/issues/50109)

Adding a `LongConsumer` to the constructor will touch lots of other implementations so I would like to avoid it for this PR. Maybe we can find a middle ground here and add a TODO to design a more resilient implementation?

**Comment by nik9000** [comment]
That makes sense to me! Would having a mutable `LongConsumer` that we
register be ok? It could default to noop and this agg could link it to the
breaker.

**Comment by iverase** [comment]
>Would having a mutable `LongConsumer` that we
register be ok? It could default to noop and this agg could link it to the
breaker.

+1

**Comment by iverase** [comment]
@tal @nik9000 I think we should move this PR forward to see if we can achieve 7.9?

**Comment by talevy** [comment]
👍 yes. I had planned to push this forward this week

**Review by iverase — APPROVED** [review]
lgtm

**Comment by talevy** [comment]
I re-ran [this](https://github.com/elastic/elasticsearch/pull/57962#issuecomment-642338053) using `gradle run -Drun.license_type=trial`

and this branch resulted in a circuit-breaker response

```
{"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[request] Data too large, data for [<agg [gridSplit]>] would be [430729928/410.7mb], which is larger than the limit of [322122547/307.1mb]","bytes_wanted":430729928,"bytes_limit":322122547,"durability":"TRANSIENT"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"test","node":"Alaz6WFOQJ-4qP8Rrb1Mhw","reason":{"type":"circuit_breaking_exception","reason":"[request] Data too large, data for [<agg [gridSplit]>] would be [430729928/410.7mb], which is larger than the limit of [322122547/307.1mb]","bytes_wanted":430729928,"bytes_limit":322122547,"durability":"TRANSIENT"}}]},"status":429}
```

while `master` OOMd

**Comment by talevy** [comment]
it may also not be clear, but the aggregator keeps track of these bytes added, and cleans them up upon closing of the aggregation here

https://github.com/elastic/elasticsearch/blob/dc91a3007007f16d7cd6d7045222ed545bee4f50/server/src/main/java/org/elasticsearch/search/aggregations/AggregatorBase.java#L268

File: server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java [hunk 1]
```diff
@@ -33,8 +35,13 @@
     protected long[] values;
     protected int valuesCursor;
     private final Sorter sorter;
+    private LongConsumer circuitBreakerConsumer;
 
     protected SortingNumericDocValues() {
+        this((l) -> {});
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java:41]: `l -> {}` is good enough. But this is cool too.

File: server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java [hunk 2]
```diff
@@ -51,16 +58,40 @@ protected int compare(int i, int j) {
...
+        long oldValuesSizeInBytes = values.length * Long.BYTES;
+
+        // If array is expected to grow, increment the circuit breaker
+        // to include both the additional bytes used by the grown array
+        // as well as the overhead of keeping both arrays in memory while
+        // copying.
+        if (newSize > values.length) {
+            int newValuesLength = ArrayUtil.oversize(newSize, Long.BYTES);
+            long bytesDiff = (newValuesLength - oldValuesLength) * Long.BYTES;
+            circuitBreakerConsumer.accept(bytesDiff);
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java:81]: Why not increment by the new size here and then decrement by the old size when we're done?

File: server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java [hunk 3]
```diff
@@ -51,16 +58,40 @@ protected int compare(int i, int j) {
...
      */
     protected final void resize(int newSize) {
+        int oldValuesLength = values.length;
+        long oldValuesSizeInBytes = values.length * Long.BYTES;
+
+        // If array is expected to grow, increment the circuit breaker
+        // to include both the additional bytes used by the grown array
+        // as well as the overhead of keeping both arrays in memory while
+        // copying.
+        if (newSize > values.length) {
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java:78]: I think it'd be clearer to bail early if the newSize <= values.length rather than relying on the behavior of `ArrayUtils.grow`

File: server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java [hunk 4]
```diff
@@ -51,16 +58,40 @@ protected int compare(int i, int j) {
...
+            int newValuesLength = ArrayUtil.oversize(newSize, Long.BYTES);
+            long bytesDiff = (newValuesLength - oldValuesLength) * Long.BYTES;
+            circuitBreakerConsumer.accept(bytesDiff);
+            circuitBreakerConsumer.accept(oldValuesSizeInBytes);
+        }
+
+        // resize
         count = newSize;
         values = ArrayUtil.grow(values, count);
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java:87]: I think it'd be clearer overside on our side and then call `growExact`. That way you end up with a precise value that you are growing to for tracking. And I don't have to go and read the source of `grow`, just `oversize`.

File: server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java (hunk 2 above)
Comment (talevy) [reply server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java:81]: I guess I was trying to keep consistent with the old logic, but I can see how this iterative addition can also be somewhat obtuse in this new logic.

**Comment by talevy** [comment]
thank you @nik9000. your suggestions were real great. updated!

File: server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java [hunk 5]
```diff
@@ -51,16 +58,35 @@ protected int compare(int i, int j) {
...
+        int newValuesLength = ArrayUtil.oversize(newSize, Long.BYTES);
+        circuitBreakerConsumer.accept(newValuesLength * Long.BYTES);
+
+        // resize
         count = newSize;
-        values = ArrayUtil.grow(values, count);
+        values = ArrayUtil.growExact(values, newValuesLength);
         valuesCursor = 0;
+
+        // clean up old values array
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/fielddata/SortingNumericDocValues.java:88]: s/clean up/account for freeing/?

**Review by nik9000 — APPROVED** [review]
LGTM
