### PR TITLE
Fix incorrect nullify with unmapped fields

### LINKED ISSUE #141870: ESQL: bugs in unmapped_fields="nullify" from spec tests
Relates #138888 

**Note**: this didn't yet use the code from https://github.com/elastic/elasticsearch/pull/141340. Maybe that fixes some things, although I'm sure it can't fix everything below.

The single node spec tests should all still run correctly if we prepend `SET unmapped_fields="nullify"` to every query (that doesn't already have a `SET` directive), because nullifying missing fields should only every affect queries that would otherwise fail due to referencing a missing field in the query.

I ran the single node spec tests while prepending `SET unmapped_fields="nullify"` to the query each time unless there was already a `SET directive`, by adding the following to `EsqlSpecTestCase#doTest`:
```
        if (query.startsWith("SET") == false) {
            query = "SET unmapped_fields=\"nullify\"; " + query;
        }
```

I counted 284 failures, about a third of which where just misaligned error messages due to prepending something to the query. The rest was real.

I'll add the repro line and errors that weren't expected, discarding duplicates:
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:date_nanos.Mv_min on date nanos}"

Different column type for column [nanos] (DATE_NANOS != NULL)
Expected :DATE_NANOS
Actual   :NULL
```
There were several like that above, indicating that we wrongly nullified a field that was actually present.

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:vector-l1-norm.L1NormWithLookupJoinOnJoinedField}"

úerrorúroot_causeøútype^esql_illegal_argument_exceptionreasonlUnsupported right plan for lookup join [Eval]stack_traceàorg.elasticsearch.xpack.esql.EsqlIllegalArgumentException: Unsupported right plan for lookup join [Eval]
	at org.elasticsearch.xpack.esql.planner.mapper.LocalMapper.mapBinary(LocalMapper.java:130)
	at org.elasticsearch.xpack.esql.planner.mapper.LocalMapper.map(LocalMapper.java:59)
	at org.elasticsearch.xpack.esql.planner.mapper.LocalMapper.mapUnary(LocalMapper.java:74)
	at org.elasticsearch.xpack.esql.planner.mapper.LocalMapper.map(LocalMapper.java:55)
	at org.elasticsearch.xpack.esql.planner.mapper.LocalMapper.mapUnary(LocalMapper.java:74)
	at org.elasticsearch.xpack.esql.planner.mapper.LocalMapper.map(LocalMapper.java:55)
	at org.elasticsearch.xpack.esql.planner.PlannerUtils.reductionPlan(PlannerUtils.java:154)
	at org.elasticsearch.xpack.esql.plugin.ComputeService.reductionPlan(ComputeService.java:783)
```
Saw this in multiple tests.

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:date_nanos.Date nanos not equals millis, no mv min}"

Different column name [1]
Expected :nanos
Actual   :num
```
Also multiple such cases.

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:date_trunc.EvalDateTruncQuarterlyIntervalWithGTInRange}"

line 2:3: Plan [TopN[[Order[hire_date{f}#3558,ASC,LAST]],5[INTEGER],false]] optimized incorrectly due to missing references [hire_date{f}#3558]
```
Multiple failures like this.

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:k8s-timeseries-first-over-time.First_over_time_null_values}"

line 1:133: the TS STATS command requires an @timestamp field of type date or date_nanos but it was of type [null]
```
Also multiple like this.

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:knn-function.TestKnnWithSemanticTextAndKql}"

line 2:3: [KQL] function cannot be used after WHERE
```

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:subquery.SubqueryInFromWithUnionTypesWithoutCommonTypesMultipleExplicitCasting}"

line 1:32: Column [@timestamp] has conflicting data types in subqueries: [date_nanos, null, date_nanos]
```

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:vector-cosine-similarity.CosineSimilarityWithEnrich}"

line 4:3: Unsupported type [null] for enrich matching field [id]; only [keyword, text, ip, long, integer, float, double, datetime] allowed for type [match]üstack_traceäorg.elasticsearch.xpack.esql.VerificationException: Found 1 problem
```

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:date_nanos.Mixed Nanos Millis Range Compare}"

line 3:9: first argument of [nanos > to_datenanos("2023-10-23T12:15:03.360103847")] is [null] so second argument must also be [null] but was [date_nanos]
```

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:vector-dot-product.DotProductWithLookupJoin}"

line 3:30: JOIN left field [id] of type [INTEGER] is incompatible with right field [id] of type [NULL]
```

```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlSpecIT" -Dtests.method="test {csv-spec:date_nanos.Add date nanos}"

line 3:8: EVAL does not support type [date_period] as the return data type of expression [nanos + 1 month]
```

### PR DESCRIPTION
**Pull request by idegtiarenko**
This change fixes unexpected behavior when some columns are incorrectly nullified when using `SET unmapped_fields="nullify";`

Fixes: https://github.com/elastic/elasticsearch/issues/141870

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java [hunk 1]
```diff
@@ -282,7 +279,7 @@ private static LinkedHashSet<UnresolvedAttribute> unresolvedLinkedSet(List<Unres
     public static List<UnresolvedAttribute> collectUnresolved(LogicalPlan plan) {
         List<UnresolvedAttribute> unresolved = new ArrayList<>();
         Consumer<UnresolvedAttribute> collectUnresolved = ua -> {
-            if ((ua instanceof UnresolvedPattern || ua instanceof UnresolvedTimestamp) == false) {
+            if (ua.getClass() == UnresolvedAttribute.class && ua.customMessage()) {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java]: ResolveUnmapped rule incorrectly nullifies attributes that are not resolved yet.
This attempts to only collect attributes that are intentionally marked as unresolved (eg have custom message) opposed to ones not resolved yet (with default message).

**Review by alex-spies — COMMENTED** [review]
Heya, this fixes https://github.com/elastic/elasticsearch/issues/141870, right?

Can we maybe add a test suite that runs any spec tests that don't have a `SET`ting and we add `SET unmapped_fields="nullify"` to it?

That would be a nice invariant that future tests also mustn't break this setting.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java [hunk 2]
```diff
@@ -371,6 +371,11 @@ protected final void doTest(String query) throws Throwable {
 
         addPragmas(builder);
 
+        // TODO we should implement more generic randomization for SET parameters
+        if (randomBoolean() && query.startsWith("SET") == false) {
+            query = "SET unmapped_fields=\"nullify\"; " + query;
+        }
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java]: @alex-spies just added above. 
I believe all tests should pass with it. If not, lets merge this change without randomization and followup on remaining failures separately.

Comment (idegtiarenko) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java]: This also reorders warnings:
```
Expected: Line 1:86: evaluation of [concat(host_group, \\\"/\\\", description)] failed, treating result as null. Only first 20 failures recorded.
Actual: Line 1:117: evaluation of [concat(host_group, \\\"/\\\", description)] failed, treating result as null. Only first 20 failures recorded.
```
Once more condition when this can not be applied.

Comment (alex-spies) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java]: Hmm, right.

We could either make the warning assertion more lenient in general; or we could make the warning assertions more lenient when we choose to runt he query with `SET unmapped_fields="nullify"`.

If we add a newline after the `SET unmapped_fields="nullify";`, only the line number will be unexpected while the rest of the emitted warning should stay the same.

Our [exact warning matcher](https://github.com/elastic/elasticsearch/blob/495036888003570ab799f138aaec4ed356754831/x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/AssertWarnings.java#L44-L49) takes every piece of the warning into account, but it could maybe ignore line numbers (or locations) when we run a modified version of the query?

File: x-pack/plugin/esql/qa/server/single-node/src/javaRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/EsqlSpecIT.java [hunk 3]
```diff
@@ -52,6 +52,17 @@ protected boolean supportsSourceFieldMapping() {
         return cluster.getNumNodes() == 1;
     }
 
+    @Override
+    protected String maybeRandomizeQuery(String query) {
+        // TODO we should implement more generic randomization for SET parameters
+        return randomBoolean()
+            && testCase.expectedWarnings().isEmpty() // avoid shifting warnings positions in source query
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/server/single-node/src/javaRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/EsqlSpecIT.java:60]: That works, too.

File: x-pack/plugin/esql/qa/server/single-node/src/javaRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/EsqlSpecIT.java [hunk 4]
```diff
@@ -52,6 +52,17 @@ protected boolean supportsSourceFieldMapping() {
...
+            && testCase.expectedWarningsRegex().isEmpty() // regexp might also contain line/position
+            && query.startsWith("SET") == false // avoid conflicts with provided settings
+                ? "SET unmapped_fields=\"nullify\"; " + query
+                : query;
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/server/single-node/src/javaRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/EsqlSpecIT.java:64]: Maybe this should be the default randomization, rather than the single node specific one? What do you think?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java [hunk 5]
```diff
@@ -84,15 +84,27 @@ private static LogicalPlan resolve(LogicalPlan plan, boolean load) {
...
+        Set<String> childOutputNames = new java.util.HashSet<>();
+        for (LogicalPlan child : plan.children()) {
+            for (Attribute attr : child.output()) {
+                childOutputNames.add(attr.name());
+            }
+        }
+        unresolved.removeIf(ua -> childOutputNames.contains(ua.name()));
+        if (unresolved.isEmpty()) {
+            return plan;
+        }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java:104]: This check is duplicated, see lines 88-90 above.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec [hunk 6]
```diff
@@ -12,6 +12,18 @@ null
 null
 ;
 
+keepMapped
+required_capability: date_nanos_type
+required_capability: optional_fields_nullify_tech_preview
+required_capability: optional_fields_fix_unmapped_field_detection
+
+SET unmapped_fields="nullify"; FROM date_nanos | SORT millis ASC | WHERE millis < "2000-01-01" | EVAL nanos = MV_MIN(nanos) | KEEP nanos;
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:20]: nit: formatting, in csv tests we normally put every command into a separate line.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec [hunk 7]
```diff
@@ -12,6 +12,18 @@ null
 null
 ;
 
+keepMapped
+required_capability: date_nanos_type
+required_capability: optional_fields_nullify_tech_preview
+required_capability: optional_fields_fix_unmapped_field_detection
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:18]: nit: if you require `optional_fields_fix_unmapped_field_detection`, you don't also need to require `optional_fields_nullify_tech_preview`.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec [hunk 8]
```diff
@@ -12,6 +12,18 @@ null
 null
 ;
 
+keepMapped
+required_capability: date_nanos_type
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:16]: That capability is switched on for super long now (since #117080). That's old enough that any bwc test can assume that capability is permanently switched on.

Let's remove it - this test is skipped based on the `optional_fields_fix_unmapped_field_detection` capability, anyway.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec (hunk 6 above)
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/unmapped-nullify.csv-spec:20]: nit: a small comment on the test would help, e.g. with a link to the issue that we close.
I presume this reproduces because `ResolveRefs` stops at the `WHERE millis < "2000-01-01"` and needs to pass control to `ImplicitCasting` before continuing - and in between, `ResolveUnmapped` is being run, wrongly assuming that any unresolved refs are due to missing fields that stop `ResolveRefs` from continuing.

**Review by alex-spies — APPROVED** [review]
Super nice fix, thanks @idegtiarenko ! LGTM, only minor comments. Please address at your own discretion and :shipit:, or let me know if you're out of capacity and I'll take this and foster it into main.

**Review by alex-spies — COMMENTED** [review]
Let's backport to 9.3, however. I'll add the labels, esp. the auto-backport one.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java (hunk 2 above)
Comment (alex-spies) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/EsqlSpecTestCase.java]: As discussed, let's stick with the current solution. Even tests without warnings give us plenty of coverage.

File: x-pack/plugin/esql/qa/server/single-node/src/javaRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/EsqlSpecIT.java (hunk 4 above)
Comment (alex-spies) [reply x-pack/plugin/esql/qa/server/single-node/src/javaRestTest/java/org/elasticsearch/xpack/esql/qa/single_node/EsqlSpecIT.java:64]: As discussed, this randomization only works if all nodes running the test support the required capabilities. This is generally only true for the single and multi-node tests, not the mixed cluster tests and ccq bwc tests.

Let's also randomize for our multi-node tests, though?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java (hunk 5 above)
Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java:104]: The check is not the same as collection could be modified in between.

Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/rules/ResolveUnmapped.java:104]: Fair enough :)
