### PR TITLE
TransportListTaskAction: wait for tasks to finish asynchronously

### LINKED ISSUE #89564: [CI] XPackRestIT test {p0=ml/upgrade_job_snapshot/Test existing but corrupt snapshot} failing
This looks to be reproducibly failing on our single processor node test job, and given the nature of the error message this very well be a legitimate deadlock scenario.

**Build scan:**
https://gradle-enterprise.elastic.co/s/g5rztp2kv5rq6/tests/:x-pack:plugin:yamlRestTest/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=ml%2Fupgrade_job_snapshot%2FTest%20existing%20but%20corrupt%20snapshot%7D

**Reproduction line:**
`./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=ml/upgrade_job_snapshot/Test existing but corrupt snapshot}" -Dtests.seed=BCFE2A9A03956ACA -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH -Dtests.timezone=US/Indiana-Starke -Druntime.java=17 -Dtests.configure_test_clusters_with_one_processor=true`

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.test.rest.XPackRestIT&tests.test=test%20%7Bp0%3Dml/upgrade_job_snapshot/Test%20existing%20but%20corrupt%20snapshot%7D

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:37401], URI [/_features/_reset], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"timeout_exception","reason":"Timed out waiting for completion of [Task{id=4348, type='persistent', action='xpack/ml/job/snapshot/upgrade[c]', description='job-snapshot-upgrade-upgrade-model-snapshot-1234567890', parentTask=cluster:10, startTime=1661288471981, startTimeNanos=2146045551685}]"}],"type":"failed_node_exception","reason":"Failed node [r9fh43zvSCuFWI9e5ehabQ]","node_id":"r9fh43zvSCuFWI9e5ehabQ","caused_by":{"type":"timeout_exception","reason":"Timed out waiting for completion of [Task{id=4348, type='persistent', action='xpack/ml/job/snapshot/upgrade[c]', description='job-snapshot-upgrade-upgrade-model-snapshot-1234567890', parentTask=cluster:10, startTime=1661288471981, startTimeNanos=2146045551685}]"}},"status":500}

  at __randomizedtesting.SeedInfo.seed([BCFE2A9A03956ACA:34AA1540AD690732]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:347)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:313)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
  at org.elasticsearch.xpack.core.ml.integration.MlRestTestStateCleaner.resetFeatures(MlRestTestStateCleaner.java:35)
  at org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.clearMlState(AbstractXPackRestTest.java:131)
  at org.elasticsearch.xpack.test.rest.AbstractXPackRestTest.cleanup(AbstractXPackRestTest.java:115)
  at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by arteam**
Instead of synchronously blocking a thread in the management pool, add a listener on removed tasks and calls `nodeOperation` after all matched tasks have been removed. Also add a scheduled tasks to bail out after the specified wait timeout if the tasks haven't been finished.

Fixes #89564, #90988

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java [hunk 1]
```diff
@@ -66,19 +81,61 @@ protected void taskOperation(Task actionTask, ListTasksRequest request, Task tas
...
+            AtomicBoolean nodeOperationFiredOff = new AtomicBoolean();
+            // Register the listener before we start iterating over tasks and sync it with a latch,
+            // because matched tasks can get removed whilst we are iterating over them
+            var listener = new RemovedTaskListener() {
+                @Override
+                public void onRemoved(Task task) {
+                    try {
+                        matchedTasksReady.await();
+                    } catch (InterruptedException e) {
+                        Thread.currentThread().interrupt();
```
Comment (kingherc) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java:97]: Is this aim here to bubble up the a new InterruptedException? I guess if this happens, then the timeout exception scheduled operation below will also fire up ultimately?

**Review by kingherc — COMMENTED** [review]
Looks good to me so far! Just left a couple of comments before approving, to see if a couple of questions I have (due to my inexperience with this part of the code) are already done or need further attention.

File: server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java:97]: I don't think we should be blocking here. Could we instead remember the prematurely-removed tasks captured here and process them when we're ready to do so?

**Review by DaveCTurner — DISMISSED** [review]

File: server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/TasksIT.java [hunk 2]
```diff
@@ -636,6 +637,11 @@ public void onTaskRegistered(Task task) {}
 
                     @Override
                     public void onTaskUnregistered(Task task) {}
+
+                    @Override
+                    public void subscribeForRemovedTasks(RemovedTaskListener removedTaskListener) {
+                        waitForWaitingToStart.countDown();
```
[the remark this answers is not in the document]
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/action/admin/cluster/node/tasks/TasksIT.java:643]: I believe we worked around this by always having 2 MANAGEMENT threads in https://github.com/elastic/elasticsearch/pull/90193. I think we would get sufficient coverage by reverting that change, and we should do that here.

File: server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java:97]: Something like this perhaps?

```java
ListenableActionFuture<Void> future = new ListenableActionFuture<>();
Set<Task> removedTasks = Sets.newConcurrentHashSet();
Set<Task> matchedTasks = Sets.newConcurrentHashSet();
RefCounted removalRefs = AbstractRefCounted.of(() -> {
    for (Task removedTask : removedTasks) {
        matchedTasks.remove(removedTask);
    }
    removedTasks.clear();
    if (matchedTasks.isEmpty()) {
        future.onResponse(null);
    }
});

RemovedTaskListener removedTaskListener = task -> {
    if (removalRefs.tryIncRef()) {
        removedTasks.add(task);
        removalRefs.decRef();
    } else {
        matchedTasks.remove(task);
        if (matchedTasks.isEmpty()) {
            future.onResponse(null);
        }
    }
};

taskManager.addRemovedTaskListener(removedTaskListener);
try {
    processTasks(request, task -> {
        if (task.getAction().startsWith(ListTasksAction.NAME) == false) {
            // It doesn't make sense to wait for List Tasks and it can cause an infinite loop of the task waiting
            // for itself or one of its child tasks
            matchedTasks.add(task);
        }
        operation.accept(task);
    });
} finally {
    removalRefs.decRef();
}

final ActionListener<Void> listener = ActionListener.runBefore(
    ActionListener.wrap(ignored -> nodeOperation.run(), onFailure),
    () -> taskManager.removeRemovedTaskListener(removedTaskListener)
);

if (future.isDone()) {
    listener.onResponse(null);
} else {
    future.addListener(new ThreadedActionListener<>(logger, threadPool, ThreadPool.Names.MANAGEMENT, listener, false));
    threadPool.schedule(
        () -> future.onFailure(new ElasticsearchTimeoutException("Timed out waiting for completion of tasks")),
        requireNonNullElse(request.getTimeout(), DEFAULT_WAIT_FOR_COMPLETION_TIMEOUT),
        ThreadPool.Names.SAME
    );
}
```

File: server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java [hunk 3]
```diff
@@ -66,19 +84,68 @@ protected void taskOperation(Task actionTask, ListTasksRequest request, Task tas
     }
 
     @Override
-    protected void processTasks(ListTasksRequest request, Consumer<Task> operation) {
+    protected void processTasks(ListTasksRequest request, Consumer<Task> operation, Runnable nodeOperation, Consumer<Exception> onFailure) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java:87]: We only ever run one of `nodeOperation` or `onFailure` so IMO this makes more sense as an `ActionListener<Void>`.

File: server/src/main/java/org/elasticsearch/tasks/TaskManager.java [hunk 4]
```diff
@@ -292,9 +295,20 @@ public Task unregister(Task task) {
             }
         } finally {
             tracer.stopTrace("task-" + task.getId());
+            for (RemovedTaskListener listener : removedTaskListeners) {
+                threadPool.generic().submit(() -> listener.onRemoved(task));
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/tasks/TaskManager.java:299]: Do we need to fork for every listener? I think everything the listener does is now lightweight except for completing the final listener when all tasks are removed. We should just fork at the end there instead.

File: server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java [hunk 5]
```diff
@@ -48,6 +65,7 @@ public TransportListTasksAction(ClusterService clusterService, TransportService
             TaskInfo::from,
             ThreadPool.Names.MANAGEMENT
         );
+        this.threadPool = threadPool;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java:68]: nit: both `ClusterService` and `TransportService` already contain references to the `ThreadPool`, we don't need another constructor param here.

File: server/src/main/java/org/elasticsearch/tasks/TaskManager.java [hunk 6]
```diff
@@ -292,9 +295,24 @@ public Task unregister(Task task) {
             }
         } finally {
             tracer.stopTrace("task-" + task.getId());
+            if (removedTaskListeners.size() > 0) {
+                threadPool.generic().submit(() -> {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/tasks/TaskManager.java:299]: I don't think we need any forking here...

File: server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java [hunk 7]
```diff
@@ -66,19 +84,68 @@ protected void taskOperation(Task actionTask, ListTasksRequest request, Task tas
...
+            }
+            removalRefs.decRef();
+            collectionComplete.set(true);
+
+            if (future.isDone()) {
+                // No tasks to wait, we can run nodeOperation in the management pool
+                allMatchedTasksRemovedListener.onResponse(null);
+            } else {
+                future.addListener(
+                    new ThreadedActionListener<>(logger, threadPool, ThreadPool.Names.MANAGEMENT, allMatchedTasksRemovedListener, false)
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/list/TransportListTasksAction.java:138]: ... and we are forking the final operation here.

**Review by DaveCTurner — COMMENTED** [review]
Looks good, I left just a couple more nits. I'd like someone else to review too tho.

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/part-1

File: server/src/main/java/org/elasticsearch/tasks/TaskManager.java [hunk 8]
```diff
@@ -292,9 +295,20 @@ public Task unregister(Task task) {
             }
         } finally {
             tracer.stopTrace("task-" + task.getId());
+            for (RemovedTaskListener listener : removedTaskListeners) {
+                listener.onRemoved(task);
+            }
         }
     }
 
+    public void addRemovedTaskListener(RemovedTaskListener removedTaskListener) {
```
Comment (fcofdez) [inline server/src/main/java/org/elasticsearch/tasks/TaskManager.java:304]: nit: can we rename this listener to `UnregisterTaskListener`? the removeRemoved... it's a bit confusing.

**Review by fcofdez — APPROVED** [review]
LGTM, I left a couple of naming suggestions. I wonder if we could simplify this logic by changing how the subclasses interact with the task collection, etc. But I guess that route has been considered already.

File: server/src/main/java/org/elasticsearch/tasks/TaskManager.java (hunk 8 above)
Comment (arteam) [reply server/src/main/java/org/elasticsearch/tasks/TaskManager.java:304]: Absolutely! This also was irking me for a while...
