### PR TITLE
[ML] Fix datafeed skipping first bucket after lookback when aggs are …

### LINKED ISSUE #39842: [ML] Real time datafeed skips first bucket after lookback when aggs are used
**Steps to reproduce**

1. Index documents ranging from some time before `now` to some time after `now`. You can use the python script found [here](https://gist.github.com/dimitris-athanasiou/c7cc510365620923989944460332dd98)

2. Put job:

```
PUT _ml/anomaly_detectors/test_job
{
	"analysis_config": {
		"bucket_span": "1m",
		"summary_count_field_name": "doc_count",
		"detectors": [
			{"function": "count"}
		]
	},
	"model_plot_config": {"enabled": "true"},
	"data_description": {
		"time_field": "time"
	}
}
```

3. Open job:

```
POST _ml/anomaly_detectors/test_job/_open
```

4. Put datafeed:

```
PUT _ml/datafeeds/test_datafeed
{
	"indices": "rt",
	"job_id": "test_job",
	"query_delay": "20s",
	"aggs": {
    	"buckets": {
	    	"date_histogram": {
	        "field": "time",
	        "interval": "1m",
	        "time_zone": "UTC"
    	},
        "aggs": {
            "time": {
                "max": {
        	    "field": "time"
        	}
            }
        }
    }
  }
}
```

5. Start datafeed

```
POST _ml/datafeeds/test_datafeed/_start
```

6. Wait until a few minutes pass so that  the datafeed triggers a few real-time searches

**Observed Behaviour**

Notice that there will be an empty bucket right after the lookback ended.

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
…used

The problem here was that `DatafeedJob` was updating the last end time searched
based on the `now` even though when there are aggregations, the extactor will
only search up to the floor of `now` against the histogram interval.
This commit fixes the issue by using the end time as calculated by the extractor.

It also adds an integration test that uses aggregations. This test would fail
before this fix. Unfortunately the test is slow as we need to wait for the
datafeed to work in real time.

Closes #39842

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/DatafeedWithAggsIT.java [hunk 1]
```diff
@@ -0,0 +1,139 @@
...
+
+    @After
+    public void cleanup(){
+        cleanUp();
+    }
+
+    public void testRealtime() throws Exception {
+        String dataIndex = "datafeed-with-aggs-rt-data";
+
+        // A job with a bucket_span of 1s
```
Comment (davidkyle) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/DatafeedWithAggsIT.java]: This is a good example of how quickly comments can become out of date

**Review by davidkyle — COMMENTED** [review]
Looks good my only concern is the time the realtime test takes to run. Does it have to be realtime?

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/DatafeedWithAggsIT.java (hunk 1 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/DatafeedWithAggsIT.java]: So very true!

**Comment by dimitris-athanasiou** [comment]
elasticsearch-ci/bwc

**Comment by dimitris-athanasiou** [comment]
@davidkyle Unfortunately, to test the particular bug this fixes, we need to run in real time. The original idea was to use a job with a bucket span of `1s` (as the offending comment reveals) but I run into other problems when I tried this. 

We have to make a call on adding tests like this and take the hit in execution time or leave them out. I have already spoken to @dolaru about designing real-time test cases for our qa team to run. I'm in two minds about this.

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/bwc

**Comment by droberts195** [comment]
> We have to make a call on adding tests like this and take the hit in execution time or leave them out

I agree.  It's the problem that's discussed in #37339.

For what it's worth this test isn't nearly as slow as some others we have in our integration tests in the `elasticsearch` repo.  From [this PR's `elasticsearch-ci/2`](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/9673/consoleText):

```
HEARTBEAT J0 PID(10686@elasticsearch-ci-immutable-ubuntu-1404-1552071295992367761): 2019-03-08T19:50:00, stalled for 11.7s at: DatafeedWithAggsIT.testRealtime
Suite: org.elasticsearch.xpack.ml.integration.DatafeedWithAggsIT
Completed [1/21] in 15.26s, 1 test
```

So _quite_ slow.  But the forecasting test (from the same build so exactly the same hardware) takes seven times as long:

```
HEARTBEAT J0 PID(10686@elasticsearch-ci-immutable-ubuntu-1404-1552071295992367761): 2019-03-08T19:51:58, stalled for 10.6s at: ForecastIT.testOverflowToDisk
HEARTBEAT J0 PID(10686@elasticsearch-ci-immutable-ubuntu-1404-1552071295992367761): 2019-03-08T19:52:08, stalled for 20.6s at: ForecastIT.testOverflowToDisk
HEARTBEAT J0 PID(10686@elasticsearch-ci-immutable-ubuntu-1404-1552071295992367761): 2019-03-08T19:52:18, stalled for 30.6s at: ForecastIT.testOverflowToDisk
HEARTBEAT J0 PID(10686@elasticsearch-ci-immutable-ubuntu-1404-1552071295992367761): 2019-03-08T19:52:28, stalled for 40.6s at: ForecastIT.testOverflowToDisk
HEARTBEAT J0 PID(10686@elasticsearch-ci-immutable-ubuntu-1404-1552071295992367761): 2019-03-08T19:52:38, stalled for 50.6s at: ForecastIT.testOverflowToDisk
HEARTBEAT J0 PID(10686@elasticsearch-ci-immutable-ubuntu-1404-1552071295992367761): 2019-03-08T19:52:48, stalled for 60.6s at: ForecastIT.testOverflowToDisk
HEARTBEAT J0 PID(10686@elasticsearch-ci-immutable-ubuntu-1404-1552071295992367761): 2019-03-08T19:52:58, stalled for 70.6s at: ForecastIT.testOverflowToDisk
HEARTBEAT J0 PID(10686@elasticsearch-ci-immutable-ubuntu-1404-1552071295992367761): 2019-03-08T19:53:08, stalled for 80.7s at: ForecastIT.testOverflowToDisk
Suite: org.elasticsearch.xpack.ml.integration.ForecastIT
Completed [7/21] in 105.71s, 6 tests
```

I think the two approaches for the long term could be:

1. Remove these tests from `elasticsearch` and just cover the scenarios in our QA testing.  But then the QA team really must inform us quickly if they start failing.  It also has the disadvantage that if these QA tests start failing we don't have a test that reproduces the problem integrated into the development environment for use in debugging and fixing the problem.
2. Factor them out into a separate test suite that's not run as part of all CI builds, but only under certain circumstances.  An equivalent is the `:Core/Infra/Packaging` label which causes the full set of packaging tests to be run instead of just a sample.  Theoretically CI could be changed such that only PRs labeled `:ml` have the complex ML integration tests run against them so we don't delay the whole ES team.  But this is obviously a non-trivial change that impacts the Jenkins/Github integration.

**Comment by droberts195** [comment]
6.6.2 is now "blockers only" and it's unlikely there will be a 6.6.3 unless 6.7.0 is significantly delayed.  Therefore I don't think it's worth backporting this to the 6.6 branch.

**Review by davidkyle — APPROVED** [review]
LGTM

**Review by benwtrent — APPROVED** [review]
