### PR TITLE
Fix async stop sometimes not properly collecting result

### LINKED ISSUE #121249: [CI] RemoteClusterSecurityEsqlIT testCrossClusterAsyncQueryStop failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6062 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/oqql4mv65durg)
- [elasticsearch-pull-request #53217 / checkpart4_release-tests](https://gradle-enterprise.elastic.co/s/ounrokmb3uotu)
- [elasticsearch-pull-request #53073 / checkpart4_release-tests](https://gradle-enterprise.elastic.co/s/qprvfbcfevmiq)
- [elasticsearch-pull-request #52965 / checkpart4_release-tests](https://gradle-enterprise.elastic.co/s/n6g4wyr4veads)
- [elasticsearch-pull-request #52925 / part-4](https://gradle-enterprise.elastic.co/s/tbrzjkmjzuou2)
- [elasticsearch-pull-request #52823 / checkpart4_release-tests](https://gradle-enterprise.elastic.co/s/siw2mspian3bi)
- [elasticsearch-pull-request #52785 / part-4](https://gradle-enterprise.elastic.co/s/wf2bkgwe6trpg)
- [elasticsearch-pull-request #52753 / part-4](https://gradle-enterprise.elastic.co/s/cpvxwpc7ii7qc)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:qa:multi-cluster:javaRestTest" --tests "org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityEsqlIT.testCrossClusterAsyncQueryStop" -Dtests.seed=8E517D83CCAB7558 -Dtests.locale=en-TZ -Dtests.timezone=Asia/Damascus -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityEsqlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCrossClusterAsyncQueryStop),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <false>
     but: was <true>
```

**Issue Reasons:**
- [main] 4 consecutive failures in step checkpart4_release-tests
- [main] 8 failures in test testCrossClusterAsyncQueryStop (1.0% fail rate in 802 executions)
- [main] 3 failures in step part-4 (0.8% fail rate in 364 executions)
- [main] 4 failures in step checkpart4_release-tests (100.0% fail rate in 4 executions)
- [main] 7 failures in pipeline elasticsearch-pull-request (2.0% fail rate in 355 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by smalyshev**
If the request finishes before the stop is called, but the result is not stored yet, we rely on async functionality to collect the response. I though that we are guaranteed that the data would be stored before the final handler is completed, but looks like it's not always the case. So this explicitly checks the task is finished before trying to collect.

Fixes https://github.com/elastic/elasticsearch/issues/121249

### CODE REVIEW

**Comment by dnhatn** [comment]
@smalyshev 
I think the problem is that we wrap `runAfter` to remove the async listener too early: https://github.com/elastic/elasticsearch/blob/2fbec770158c421c316a0277df02f0f454fce7a7/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlQueryAction.java#L222.  

This is because the listener does not include storing results to the index: https://github.com/elastic/elasticsearch/blob/67ee03411bad5beb7e8000f0b3fcbc8accdf96da/x-pack/plugin/esql-core/src/main/java/org/elasticsearch/xpack/esql/core/async/AsyncTaskManagementService.java#L191.  

We could avoid this issue if the `runAfter` wrap before dispatch to request to asyncTaskManagementService https://github.com/elastic/elasticsearch/blob/2fbec770158c421c316a0277df02f0f454fce7a7/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlQueryAction.java#L186). However, at that point, we don't yet have the async ID or executionInfo.

I'm a bit hesitant about this proposal in this PR because it would deduplicate the get-result logic more.

**Comment by smalyshev** [comment]
@dnhatn We don't change much logic-wise - we fetch the task ID anyway, the only change is that we'd wait for it to finish on one of the branches. As you note, if we move listener wrap earlier, we'd have to also move execution info creation and it may cause other problems?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlAsyncStopAction.java [hunk 1]
```diff
@@ -106,34 +106,37 @@ private String sessionID(AsyncExecutionId asyncId) {
...
+        }
+        Runnable getResults = () -> getResultsAction.execute(task, getAsyncResultRequest, listener);
+        exchangeService.finishSessionEarly(sessionID(asyncId), ActionListener.running(() -> {
+            if (asyncTask.addCompletionListener(() -> ActionListener.running(getResults)) == false) {
+                getResults.run();
+            }
+        }));
+    }
+
+    private EsqlQueryTask getEsqlQueryTask(AsyncExecutionId asyncId) {
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlAsyncStopAction.java:131]: Since this is related to security, can we expose and use AsyncTaskIndexService#getTaskAndCheckAuthentication instead of duplicating it here?

**Review by dnhatn — APPROVED** [review]
One ask, but LGTM. Thanks @smalyshev.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlAsyncStopAction.java (hunk 1 above)
Comment (smalyshev) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/TransportEsqlAsyncStopAction.java:131]: Oh, I didn't notice this exists. This is even better.

**Review by dnhatn — APPROVED** [review]

**Comment by smalyshev** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/122113)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/122114)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/122115)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
