### PR TITLE
[Test] Ensure latest cluster info is used in tests

### LINKED ISSUE #116870: [CI] DesiredBalanceReconcilerMetricsIT testDesiredBalanceMetrics failing
**Build Scans:**
- [elasticsearch-periodic #4879 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/4dpw5ctkzalmw)
- [elasticsearch-pull-request #41449 / part-1](https://gradle-enterprise.elastic.co/s/7esbctusasn4s)
- [elasticsearch-pull-request #41182 / part-1](https://gradle-enterprise.elastic.co/s/t2ffj5g3kwlc6)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceReconcilerMetricsIT.testDesiredBalanceMetrics" -Dtests.seed=B58F2379C103AA4 -Dtests.locale=ks-Arab-IN -Dtests.timezone=Etc/GMT+7 -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceReconcilerMetricsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testDesiredBalanceMetrics),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 3 failures in test testDesiredBalanceMetrics (1.0% fail rate in 294 executions)
- [main] 2 failures in step part-1 (2.0% fail rate in 98 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.0% fail rate in 98 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
DesiredBalanceMetrics#updateMetrics is called on reroute which is frequent but not guaranteed. It can also takes some time to complete. This PR adds an explicit reroute to ensure the latest cluster info is picked up.

Resolves: #116870

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceReconcilerMetricsIT.java [hunk 1]
```diff
@@ -68,6 +69,7 @@ public void testDesiredBalanceMetrics() {
         final var infoService = (InternalClusterInfoService) internalCluster().getCurrentMasterNodeInstance(ClusterInfoService.class);
         ClusterInfoServiceUtils.setUpdateFrequency(infoService, TimeValue.timeValueMillis(200));
         assertNotNull("info should not be null", ClusterInfoServiceUtils.refresh(infoService));
```
Comment (ywangd) [inline server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/allocator/DesiredBalanceReconcilerMetricsIT.java:71]: It seems to me that the asyncRefresh for clusterInfo can also pause which makes the `refresh` call here to get back a stale result since the newRefresh is [short-circuited](https://github.com/elastic/elasticsearch/blob/27eb01356be34742a12d207545fca7af01573e93/server/src/main/java/org/elasticsearch/cluster/InternalClusterInfoService.java#L364-L365) if there is already one running. If that does happen, it might also lead to test failure. But in practice, I was not able to make it happen, probably due to the short update interval of 200ms. So I am leaving it as is.

**Review by idegtiarenko — APPROVED** [review]

**Review by pxsalehi — APPROVED** [review]
Thanks! Let me know if this fails again, I can simplify/improve the test.
