### PR TITLE
[ML][Data Frame] fixing some data frame hlrc tests

### LINKED ISSUE #43324: DataFrameTransformIT.testGetStats failure - date formatting error on 7.x
the tests fails non reproducibly
```
REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner --tests "org.elasticsearch.client.DataFrameTransformIT.testGetStats" -Dtests.seed=20C411A7A28CEBE -Dtests.security.manager=true -Dtests.locale=fr -Dtests.timezone=Asia/Urumqi -Dcompiler.java=12 -Druntime.java=8
```
https://scans.gradle.com/s/7ewwtblzmrbtc/tests/43nmsh6ur4gh6-t7wzgf4duds5a

Assertion stacktrace
```

java.lang.AssertionError: expected:<STARTED> but was:<STOPPED>
--
at __randomizedtesting.SeedInfo.seed([20C411A7A28CEBE:953D9FEC55DC36EB]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:144)
at org.elasticsearch.client.DataFrameTransformIT.lambda$testGetStats$4(DataFrameTransformIT.java:367)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:900)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:874)
at org.elasticsearch.client.DataFrameTransformIT.testGetStats(DataFrameTransformIT.java:363)


```

From logs that looks suspicious
```
[2019-06-18T08:46:06,487][ERROR][o.e.x.m.j.p.a.w.JsonDataToProcessWriter] [node-0] Cannot parse timestamp '' as epoch value
```

```
[2019-06-18T08:47:38,826][ERROR][o.e.x.i.IndexLifecycleRunner] [node-0] policy [my_policy] for index [my_index] failed on step [{"phase":"warm","action":"shrink","name":"shrink"}]. Moving to ERROR step
--
java.lang.IllegalArgumentException: the number of target shards [3] must be less that the number of source shards [2]
at org.elasticsearch.cluster.metadata.IndexMetaData.selectShrinkShards(IndexMetaData.java:1599) ~[elasticsearch-7.3.0-SNAPSHOT.jar:7.3.0-SNAPSHOT]

[2019-06-18T08:47:38,826][ERROR][o.e.x.i.IndexLifecycleRunner] [node-0] policy [my_policy] for index [my_index] failed on step [{"phase":"warm","action":"shrink","name":"shrink"}]. Moving to ERROR step
--
java.lang.IllegalArgumentException: the number of target shards [3] must be less that the number of source shards [2]
at org.elasticsearch.cluster.metadata.IndexMetaData.selectShrinkShards(IndexMetaData.java:1599) ~[elasticsearch-7.3.0-SNAPSHOT.jar:7.3.0-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by benwtrent**
The issue with `DataFrameTransformIT#testGetStats` that we have `assertBusy` waiting on a many things that do not have a consistent end state. The task COULD transition to STARTED, but the progress is not 100%. Since we STOP on finish, the next time we assert when the progress is 100% the state would then be STOPPED. Asserting on the `STARTED` state for a transform should wait until we have continuous data frame transforms.

I also made sure that all transforms that are PUT but not deleted within the same test are added to the `transformsToClean` `ArrayList`. 

closes https://github.com/elastic/elasticsearch/issues/43324

### CODE REVIEW

File: client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameTransformIT.java [hunk 1]
```diff
@@ -186,9 +187,7 @@ public void testGetTransform() throws IOException {
         DataFrameTransformConfig transform = validDataFrameTransformConfig(id, sourceIndex, "pivot-dest");
 
         DataFrameClient client = highLevelClient().dataFrame();
-        AcknowledgedResponse ack = execute(new PutDataFrameTransformRequest(transform), client::putDataFrameTransform,
-                client::putDataFrameTransformAsync);
-        assertTrue(ack.isAcknowledged());
+        putTransform(transform);
```
Comment (dimitris-athanasiou) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameTransformIT.java]: It feels that the paradigm we've followed with ML jobs where we have a cleaner class (see `MlTestStateCleaner`) might be nice to use here too. It frees up the tests from having to worry about cleaning up and thus makes the test easier to write/read and less error prone. Of course, we can push this fix as is and refactor in a different time & PR.

Comment (davidkyle) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameTransformIT.java]: `transformsToClean` was an expedient I added when first writing the tests because I hadn't implemented GET transforms at that point and needed a way to track the DFs that had been created. It probably shouldn't have survived the rewrites but it's not such a problem. Deleting the indices between tests removes the config and there is a call to `waitForPendingTasks` in the teardown which would catch any created DFs not tracked in `transformsToClean`. So a low priority refactor.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameTransformIT.java [hunk 2]
```diff
@@ -365,15 +354,21 @@ public void testGetStats() throws Exception {
             GetDataFrameTransformStatsResponse response = execute(new GetDataFrameTransformStatsRequest(id),
                     client::getDataFrameTransformStats, client::getDataFrameTransformStatsAsync);
             DataFrameTransformStateAndStats stateAndStats = response.getTransformsStateAndStats().get(0);
-            assertEquals(IndexerState.STARTED, stateAndStats.getTransformState().getIndexerState());
```
Comment (davidkyle) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/DataFrameTransformIT.java]: Maybe use `isOneOf(STARTED, STOPPED)`

**Review by davidkyle — APPROVED** [review]
LGTM
