### PR TITLE
[Transform] Check node shutdown before fail

### LINKED ISSUE #100891: [Transform] Integrate transforms with the node shutdown API
Transforms currently do not take account of whether the node they're running on has been notified that it is shutting down.

In stateful Elasticsearch this never seemed to matter. I don't remember ever seeing a report of a failed transform that could be attributed to its node shutting down.

In stateless Elasticsearch we currently see many transform failures during rolling restarts of clusters. There are a variety of reasons, and some of the failures occur after moving to the new node rather than while running on the node that is shutting down.

Given that we haven't seen problems in current GA product, and don't want to disturb the code too much, a compromise solution to dealing with node shutdowns on transform nodes would be to say that if a transform suffers a condition that causes it to call `fail` on a node that is shutting down, instead of actually failing the transform should just mark itself locally complete so that the persistent tasks framework relocates it to a different node. If the cause of failure was something systemic to the cluster then it will fail again on the new node after redoing its most recent work. But if the cause of failure was something related to the node shutdown then the transform should pick up its work successfully on the new node, thus avoiding a spuriously failed transform.

### PR DESCRIPTION
**Pull request by prwhelan**
Transforms continue to run even when a node is shutting down. This may lead to a transform failing and putting itself into a failed state, which will prevent it from restarting when the node comes back online.

The transform will now abort rather than fail, which puts itself into a started state. When the node comes back online, or another node in the cluster starts the transform, then the transform will pick up from its last successful saved state and checkpoint.

Close #100891

--------------------------------

Testing done:

Couldn't think of a good way to write an integration test for this.  Instead I put this test code here: 
[TransformTask](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java#L425)
```java
    AtomicInteger counter = new AtomicInteger(2);
    @Override
    public void triggered(TransformScheduler.Event event) {
        if(counter.getAndDecrement() < 0) {
            fail(new IllegalStateException(), "", ActionListener.noop());
            return;
        }
```
And in TransformNode:
```java
    public Optional<Boolean> isShuttingDown() {
        var actual = clusterState.get().map(state -> {
            var localId = state.nodes().getLocalNodeId();
            if (localId != null) {
                return state.metadata().nodeShutdowns().contains(localId);
            } else {
                return null; // empty
            }
        });
        logger.error(actual);
        return Optional.of(true);
    }
```
That would call fail on a continuous transform after 3 `trigger` events, and it would print out what the cluster state said was the result before calling local abort.

I ran this on a cluster of 3 nodes with nodes 2 and 3 enabled for Transforms.  As expected, the task would cycle between es02 and es03.

I also verified that the cluster state is always updated *before* the TransformTask is created by the TransformPersistentTasksExecutor.

### CODE REVIEW

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/TransformNodeTests.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+     * When the local node is null
+     * Then return "null"
+     */
+    public void testNodeIdMissing() {
+        var nodeId = new TransformNode(Optional::empty).nodeId();
+        assertThat(nodeId, equalTo(String.valueOf((String) null)));
+    }
+
+    private Supplier<Optional<ClusterState>> clusterState(String nodeId) {
+        var clusterState = mock(ClusterState.class);
```
Comment (przemekwitek) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/TransformNodeTests.java:85]: Do we need to use mock here?
Maybe it would be possible to construct `ClusterState` object directly?
```
        ClusterState clusterState = ClusterState.builder(new ClusterName("_name"))
            .build();
```

**Review by przemekwitek — APPROVED** [review]
LGTM
