### PR TITLE
SQL: fix handling of escaped chars in JDBC connection string

### LINKED ISSUE #57927: SQL: JDBC: password attribute in connection string won't take escaped '&' or '='
If the JDBC connection string is provided the `&password=` attribute with a value containing encoded `&` or `=` characters, the parsing fails.

Ex., with `pass%3Dword`: 
```
org.elasticsearch.xpack.sql.jdbc.JdbcSQLException: Invalid parameter [password=pass=word], format needs to be key=value
	at org.elasticsearch.xpack.sql.jdbc.JdbcConfiguration.parseProperties(JdbcConfiguration.java:144)
	at org.elasticsearch.xpack.sql.jdbc.JdbcConfiguration.create(JdbcConfiguration.java:92)
	at org.elasticsearch.xpack.sql.jdbc.EsDriver.initCfg(EsDriver.java:81)
	at org.elasticsearch.xpack.sql.jdbc.EsDriver.connect(EsDriver.java:75)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
```

### PR DESCRIPTION
**Pull request by bpintea**
This PR fixes an issue emerging when the connection string URI
contains escaped characters.

The original URI is pre-parsed in order to re-assemble a new URI having
the optional elements filled in with defaults. The new URI has been
using however the unescaped query and fragment parts. So if these
contained any escaped `&` or `=` (such as in the password option value),
the unescaping would reveal them and make them later interfere with the
options parsing.

The PR changes that, so that the new URI be built from the unescaped
"raw" parts of the original URI.

Closes #57927

### CODE REVIEW

**Comment by bpintea** [comment]
@elasticmachine update branch

**Comment by bpintea** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by bpintea** [comment]
@elasticmachine update branch

**Review by costin — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcConfiguration.java [hunk 1]
```diff
@@ -208,7 +215,8 @@ public boolean indexIncludeFrozen() {
     }
 
     public static boolean canAccept(String url) {
-        return (StringUtils.hasText(url) && url.trim().startsWith(JdbcConfiguration.URL_PREFIX));
+        return (StringUtils.hasText(url) &&
```
Comment (matriv) [inline x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcConfiguration.java:218]: minor: I would trim the url and use a local var to avoid trimming it potentially twice.

**Review by matriv — APPROVED** [review]
LGTM. left a minor comment.

**Review by astefan — APPROVED** [review]
LGTM

**Review by matriv — APPROVED** [review]
LGTM. Thx for the randomization of the prefix in the tests!
