### PR TITLE
Release index commit promptly on snapshot abort

### LINKED ISSUE #95316: Pending shard snapshots prevent prompt shard shutdown
When a shard is to be snapshotted, we acquire a store ref (wrapped in an index commit) and then enqueue the shard snapshot task for execution by the repository:

https://github.com/elastic/elasticsearch/blob/b124763772748d8993911e4a7ba94b17472a9539/server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java#L369-L384

If the shard is closed while its snapshot is in the queue then it looks like we do not release the store ref promptly. Instead, we keep hold of it until it reaches the front of the queue, which could be many minutes later. During this time the shard cannot fully shut down and release the shard lock, leading to a `ShardLockObtainFailedException` being thrown on attempts to reinitialise the shard.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today we react to a shard snapshot abort when processing that shard on a
`SNAPSHOT` thread, but those threads may be busy handling tasks related
to other shards for an extended period of time which delays the release
of the resources held by the shard snapshot tasks. With this commit we
fast-track the abort handling using the machinery introduced in #96426.

Closes #95316

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/eql-correctness (succeeded but then couldn't tell H.O.M.E.R.)

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java [hunk 1]
```diff
@@ -365,31 +379,70 @@ private void snapshot(
...
+        ShardId shardId,
+        Snapshot snapshot,
+        SnapshotIndexCommit snapshotIndexCommit
+    ) {
+        return new ActionListener<>() {
+            @Override
+            public void onResponse(IndexShardSnapshotStatus.AbortStatus abortStatus) {
+                if (abortStatus == IndexShardSnapshotStatus.AbortStatus.ABORTED) {
+                    assert ThreadPool.assertCurrentThreadPool(ThreadPool.Names.GENERIC, ThreadPool.Names.SNAPSHOT);
+                    snapshotIndexCommit.onAbort();
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java:425]: It seems there could be a race condition involved around `closeException` in `SnapshotIndexCommit` in case `onAbort` and `onComplete` runs concurrently (as you pointed out, `decRef` might not have run before `onComplete` checks the `closeException`), the happens-before mentioned [here](https://github.com/elastic/elasticsearch/pull/96426/files#diff-35fe592a1471f816a2bea7eb7075fd0fa2a217cc31e8931055fd9a0cd81947efR50) is towards the `getAndSet` in `RunOnce`, where the `decRef` happens after that.

**Review by henningandersen — COMMENTED** [review]
This looks great, except the small race we identified offline.

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/snapshots/SnapshotShardsService.java:425]: :+1: yes sorry for missing this earlier. #96571 will fix this up.

**Review by henningandersen — APPROVED** [review]
LGTM.

**Review by original-brownbear — APPROVED** [review]
LGTM2 Thanks!
