### PR TITLE
[Test] Disable rare actions in RepoAnalysisFailureIT

### LINKED ISSUE #103791: [CI] RepositoryAnalysisFailureIT testFailsOnChecksumMismatch failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/r3k62nbwymnwm/tests/:x-pack:plugin:snapshot-repo-test-kit:internalClusterTest/org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalysisFailureIT/testFailsOnChecksumMismatch

**Reproduction line:**
```
./gradlew ':x-pack:plugin:snapshot-repo-test-kit:internalClusterTest' --tests "org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalysisFailureIT.testFailsOnChecksumMismatch" -Dtests.seed=F1D1273CADA87818 -Dtests.locale=ko-KR -Dtests.timezone=America/Coral_Harbour -Druntime.java=19
```

**Applicable branches:**
8.11

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalysisFailureIT#testFailsOnChecksumMismatch`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testFailsOnChecksumMismatch'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalysisFailureIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
junit.framework.AssertionFailedError: Expected exception RepositoryVerificationException but no exception was thrown

  at __randomizedtesting.SeedInfo.seed([F1D1273CADA87818:DA9BC0D1ED190491]:0)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2864)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2850)
  at org.elasticsearch.repositories.blobstore.testkit.RepositoryAnalysisFailureIT.testFailsOnChecksumMismatch(RepositoryAnalysisFailureIT.java:167)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

### PR DESCRIPTION
**Pull request by ywangd**
Rare actions are disabled to improve CI stability.

Resolves: #103791

### CODE REVIEW

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java [hunk 1]
```diff
@@ -160,16 +160,28 @@ public void testFailsOnChecksumMismatch() {
         blobStore.setDisruption(new Disruption() {
             @Override
             public byte[] onRead(byte[] actualContents, long position, long length) {
-                final byte[] disruptedContents = actualContents == null ? null : Arrays.copyOf(actualContents, actualContents.length);
-                if (actualContents != null && countDown.countDown()) {
-                    // CRC32 should always detect a single bit flip
-                    disruptedContents[Math.toIntExact(position + randomLongBetween(0, length - 1))] ^= (byte) (1 << between(0, 7));
```
Comment (ywangd) [inline x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java:166]: I did not reproduce the failure so that this is a best-effort attempt to fix. It seems plausible that in edge cases the `countDown` may not reach to 0 (hence no disruption) if there are many null `actualContents` or it happens towards the end of total read requests.

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java [hunk 2]
```diff
@@ -160,16 +160,28 @@ public void testFailsOnChecksumMismatch() {
...
+                    disruptedContents = actualContents;
                 }
                 return disruptedContents;
             }
         });
 
-        expectThrows(RepositoryVerificationException.class, () -> analyseRepository(request));
+        expectThrows(
+            RepositoryVerificationException.class,
+            "countDown has reached to zero: " + countDown.isCountedDown(),
```
Comment (idegtiarenko) [inline x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java:182]: I think it is worth moving to a dedicated assertion prior this one.

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java (hunk 1 above)
Comment (idegtiarenko) [reply x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java:166]: Why `actualContents` might be null?

Comment (ywangd) [reply x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java:166]: I just noticed it can be `null` but I am actually not sure why. I guess it might related to early read (read before write completes)? @DaveCTurner could you please help out here?

I don't think length can be `0`. Otherwise we will see assertion error from `randomLongBetween(0, length - 1)`.

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java (hunk 2 above)
Comment (ywangd) [reply x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java:182]: I thought about that. But it is not possible to assert `countDown` without excuting the analysis. But once the analysis is executed we need to check the error it throws first. So there is an order issue.

**Review by DaveCTurner — COMMENTED** [review]
This doesn't look right to me. `actualContents == null` means the blob hasn't been written yet, so we should be returning `null` in that case. Before this change we wouldn't count that as a read so should keep on trying until eventually we have done N genuine reads of written blobs. But with this change we will count every read (premature or otherwise) towards the total and may return an incomplete blob, which is a different kind of failure. Also the actual blob that is eventually written could in theory be 1 byte long too, so this wouldn't trigger a checksum mismatch.

**Comment by DaveCTurner** [comment]
That said, I've not been able to reproduce this failure locally (after 10k iterations).

**Comment by ywangd** [comment]
I think I understand where the failure comes from now. The analysis sometimes [writes and re-writes](https://github.com/elastic/elasticsearch/blob/e3009f35e91186ffbf6ccc950ec0e73b3845b7d8/x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/BlobAnalyzeAction.java#L282) a blob with different content. On the reading side, we also sometimes performs early reads which come in between the writing and re-writing. The reads can return either content and they are [both considered correct](https://github.com/elastic/elasticsearch/blob/e3009f35e91186ffbf6ccc950ec0e73b3845b7d8/x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/BlobAnalyzeAction.java#L504). The checksum can be computed against a very small range, e.g. 1 byte, of the content. With enough runs, it is possible that the disrupted content happens to match the other content (either write or re-write). 

It is a bit tricky to fix the issue. We can tighten the checksum comparison for non-early reads which should improve the robustness but it is not a complete fix. We can also track overwritten blobs in DisruptableBlobContainers and make sure the disruption on new blob content does not match the one being overwritten. But the issue can still happen when the disruption on the old blob content (the one to be overwritten) matches the future overwritting blob. I am open to ideas.

**Comment by DaveCTurner** [comment]
Ah ok that makes sense. We can avoid this by setting `request.rareActionProbability(0.0);` I think, so that we never overwrite anything.

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java [hunk 3]
```diff
@@ -154,6 +154,8 @@ public void testFailsOnChecksumMismatch() {
         final RepositoryAnalyzeAction.Request request = new RepositoryAnalyzeAction.Request("test-repo");
         request.maxBlobSize(ByteSizeValue.ofBytes(10L));
         request.abortWritePermitted(false);
```
Comment (ywangd) [inline x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java:156]: I think this is no longer needed because rare action is disabled. I left it untouched in case it might be more informational (it might be disabled for different reasons?)

**Comment by ywangd** [comment]
Thanks for the suggestion, David! It's an easy way out as long as we are OK with a bit less test coverage. I have amended the PR to align with your suggestion.

**Review by DaveCTurner — COMMENTED** [review]
Yes the slight drop in coverage is fine here, these tests are checking very specific scenarios and I didn't intend to include the overwrite case here.

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java [hunk 4]
```diff
@@ -154,6 +154,8 @@ public void testFailsOnChecksumMismatch() {
...
+        // Rare actions such as writeAndOverwrite and earlyReads can lead to CI instability
```
[the remark this answers is not in the document]
Comment (DaveCTurner) [reply x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java]: Ah not quite, the overwrite happens in the "read phase", reads that are concurrent with the overwrite do not count as early:

https://github.com/elastic/elasticsearch/blob/3031595d6a234c31abe9f7da74a86a72d30d0652/x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/BlobAnalyzeAction.java#L106-L117

[the remark this answers is not in the document]
Comment (ywangd) [reply x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java]: I could some help to understand the code. I don't quite get how Read phase starts before Overwrite. Is this the relevant code?

https://github.com/elastic/elasticsearch/blob/3031595d6a234c31abe9f7da74a86a72d30d0652/x-pack/plugin/snapshot-repo-test-kit/src/main/java/org/elasticsearch/repositories/blobstore/testkit/BlobAnalyzeAction.java#L282-L286

It seems to me that Ovewrite starts first with `writeRandomBlob` and the Read starts right before the last byte of the new content is written?

[the remark this answers is not in the document]
Comment (DaveCTurner) [reply x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java]: That sounds about right, but this isn't an early read.

[the remark this answers is not in the document]
Comment (ywangd) [reply x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java]: OK I think I understand your point now. This regular read can also possibly return the old content because the overwrite is still ongoing and may not complete before the read returns. So yeah, this read also needs the lenient checksum comparison. I have adjusted the comment accordingly.

**Review by DaveCTurner — APPROVED** [review]
LGMT

File: x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (DaveCTurner) [reply x-pack/plugin/snapshot-repo-test-kit/src/internalClusterTest/java/org/elasticsearch/repositories/blobstore/testkit/RepositoryAnalysisFailureIT.java]: Yep that's right LGTM
