### PR TITLE
[ML] adding feature_name and node size validation for tree models

### LINKED ISSUE #60759: [CI] ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty_DependentVariableIsBoolean
There are several tests from `ClassificationIT` failing (they might be correlated) - see https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+release-tests/263/ 

I've also seen quite a few failures of `ClassificationIT` over the last few months (none have been tracked though).

**Build scan**:
https://gradle-enterprise.elastic.co/s/efsbpr5sbnzwk

**Repro line**:
```./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTest' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty_DependentVariableIsBoolean" \
  -Dtests.seed=158A5379F8D00EFB \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=lt \
  -Dtests.timezone=America/Hermosillo \
  -Druntime.java=8
```

**Reproduces locally?**: No

**Applicable branches**: 7.x

**Failure history**:

**Failure excerpt**:
```
java.lang.AssertionError: Stats were: {"id":"classification_training_percent_is_50_boolean","state":"analyzing","progress":[{"phase":"reindexing","progress_percent":100},{"phase":"loading_data","progress_percent":100},{"phase":"feature_selection","progress_percent":100},{"phase":"coarse_parameter_search","progress_percent":100},{"phase":"fine_tuning_parameters","progress_percent":100},{"phase":"final_training","progress_percent":0},{"phase":"writing_results","progress_percent":0},{"phase":"inference","progress_percent":0}],"data_counts":{"training_docs_count":150,"test_docs_count":0,"skipped_docs_count":0},"memory_usage":{"timestamp":1596639663246,"peak_usage_bytes":17924,"status":"ok"},"node":{"id":"qTn19sC3Qju6ZOgwo7eDqw","name":"integTest-2","ephemeral_id":"oOFqlRycRB6L868ehr6p6w","transport_address":"127.0.0.1:34239","attributes":{"testattr":"test","ml.machine_memory":"101203308544","ml.max_open_jobs":"20","xpack.installed":"true","transform.node":"true"}},"assignment_explanation":""}
Expected: <stopped>
     but: was <analyzing>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:207)
	at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.lambda$waitUntilAnalyticsIsStopped$0(MlNativeDataFrameAnalyticsIntegTestCase.java:157)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:951)
	at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:157)
	at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.waitUntilAnalyticsIsStopped(MlNativeDataFrameAnalyticsIntegTestCase.java:153)
	at org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty(ClassificationIT.java:275)
	at org.elasticsearch.xpack.ml.integration.ClassificationIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty_DependentVariableIsBoolean(ClassificationIT.java:354)
```

### PR DESCRIPTION
**Pull request by benwtrent**
When a tree model is provided, it is possible that it is a stump.
Meaning, it only has one node with no splits
This implies that the tree has no features. In this case,
having zero feature_names is appropriate. In any other case,
this should be considered a validation failure.

This commit adds the validation if there is more than 1 node,
that the feature_names in the model are non-empty.

closes https://github.com/elastic/elasticsearch/issues/60759

### CODE REVIEW

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/inference/EnsembleInferenceModel.java [hunk 1]
```diff
@@ -142,9 +132,7 @@ private InferenceResults innerInfer(double[] features, InferenceConfig config, M
         if (preparedForInference == false) {
             throw ExceptionsHelper.serverError("model is not prepared for inference");
         }
-        LOGGER.debug("Inference called with feature names [{}]",
-            featureNames == null ? "<null>" : Strings.arrayToCommaDelimitedString(featureNames));
-        assert featureNames != null && featureNames.length > 0;
+        LOGGER.debug("Inference called with feature names [{}]", Strings.arrayToCommaDelimitedString(featureNames));
```
Comment (dimitris-athanasiou) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/inference/EnsembleInferenceModel.java:135]: Should we make this debug message take a runnable? I think it's called for each doc so it might be worth avoiding running all this if logging is not debug.

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM Just a minor logging improvement.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/inference/EnsembleInferenceModel.java (hunk 1 above)
Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/inference/EnsembleInferenceModel.java:135]: DEFINITELY! It should be a runnable.

**Comment by benwtrent** [comment]
run elasticsearch-ci/2
