### PR TITLE
ESQL: Add flags to reduce indices loaded during EsqlSpecIT

### LINKED ISSUE #120022: ESQL: Micro test optimization: Avoid loading unneeded datasets in `EsqlSpecIT` tests.
### Description

When trying to debug a single failing integration test, we can shave a few precious seconds each cycle by not loading datasets which are not used by any of the tests being run. Since we probably wish to avoid parsing the `FROM` clause, we can do this in two simple ways:
1. A new statement for the `csv-spec` DSL, signifying which datasets are needed for the current test/the entire file (for BWC, this if this is missing we will of course assume all datasets are needed).
2. A command line argument, signifying which datasets should be loaded by the test run.

### PR DESCRIPTION
**Pull request by GalLalouche**
Add a couple of flags to reduce the number of indices loaded during `EsqlSpecIT`, which speeds up things by a quite a bit when debugging a single test. This is _especially_ useful when closing the loop and letting agents fix tests, since running a single test is now faster.

These two flags were added:
1. `tests.spec_indices` Controls which indices are loaded. If not set, just load all of them (old behavior).
2. `tests.spec_enrich_policies` Specifically for `ENRICH`, these control which enrich policies are loaded. If `tests.spec_indices` is set, this defaults to none.

Resolves #120022.

### CODE REVIEW

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java [hunk 1]
```diff
@@ -390,9 +398,19 @@ public static Set<TestDataset> availableDatasetsForEs(
...
+            testDataSets.removeIf(d -> specIndices.contains(d.indexName) == false);
+        }
+
         return testDataSets;
     }
 
+    @Nullable
+    private static Set<String> parseSetProperty(String name) {
+        String prop = System.getProperty(name);
+        return (prop == null || prop.isBlank()) ? null : Set.of(prop.split(","));
```
Comment (craigtaverner) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java]: I wonder if the regex could be more generic and support optional whitespace in case people type `-Dtests.spec_indices="index1, index2"`.

**Review by craigtaverner — APPROVED** [review]
Seems useful, but I also know that there have been discussions on a more generic solution, for example a mapping of which csv-spec files rely on which indices, so we can automatically load only the indices we need for the files we're testing.

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java [hunk 2]
```diff
@@ -213,6 +213,14 @@ public class CsvTestsDataLoader {
         new TestDataset("flattened_otel_logs")
     ).collect(toMap(TestDataset::indexName, Function.identity()));
 
+    // Developer flags for faster iteration when debugging specific csv-spec tests:
+    // -Dtests.spec_indices=index1,index2 load only the specified dataset indices (enrich skipped unless spec_enrich_policies is set)
+    // -Dtests.spec_enrich_policies=p1,p2 load only the specified enrich policies (overrides the spec_indices skipping of enrich)
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:218]: This is a bit manual, but definitely could speed up debugging today.
I wonder if we could develop an automatic approach?
It would likely require parsing a query (or guessing the indices from the query some other way) before sending a query to elasticsearch.

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java [hunk 3]
```diff
@@ -479,9 +497,13 @@ private static void loadDataSets(
     }
 
     private static void loadEnrichPolicies(RestClient client) throws IOException {
-        logger.info("Loading enrich policies");
-        for (var policy : ENRICH_POLICIES.values()) {
-            loadEnrichPolicy(client, policy);
+        if (specEnrichPolicies != null || specIndices == null) {
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:501]: This toplevel condition looks confusing.
Why not rely just on an inner one?

Comment (idegtiarenko) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:501]: If I understand correctly it will not load anything if we do not specify enrich policies and specify only subset of indices (presumably to avoid errors when executing enrich policy).
Possibly worth commenting.

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java (hunk 2 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:218]: There were a couple of cases I wanted to avoid and just write a simple thing:
* Handling `*` indices.
* Multiple queries being match by the test filter itself.

They're not unsolvable, of course.

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java (hunk 3 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:501]: This is mentioned in the comment above in the flags, but I'll add an extra comment here to be extra explicit.

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java (hunk 1 above)
Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java]: Done.

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java (hunk 2 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:218]: I think that since most queries in the same csv-spec file use the same indices, we could just create a mapping of file-indices, and load those. Would be simple to implement and achieve 90% of the benefits. This is also aligned with the three most common cases:
* Run a single test (one test in one file likely loads a small set of indices specific to that file)
* Run all tests in one file (eg. views.*) loads exactly the indices it needs
* Run all spec tests (loads all indices)

Comment (GalLalouche) [reply x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/CsvTestsDataLoader.java:218]: Good idea! And it can actually use these added flags to implement that too! But I'd rather we do that in a follow-up PR. There's also the added complication of having to keep those indices up to date whenever someone adds a new test.
