### PR TITLE
ESQL: mv_expand pushes down limit and project and keep the limit after it untouched

### LINKED ISSUE #99971: ESQL: mv_expand after sort fails
### Description

`FROM employees | sort emp_no | mv_expand job_positions`

results in

```
                "type": "esql_illegal_argument_exception",
                "reason": "unknown physical plan node [OrderExec]",
```

```
[2023-09-27T18:52:46,078][INFO ][o.e.x.e.a.RestEsqlQueryAction] [runTask-0] Beginning execution of ESQL query.
Query string: [FROM employees | sort emp_no | mv_expand job_positions]
[2023-09-27T18:52:46,369][WARN ][r.suppressed             ] [runTask-0] path: /_query, params: {format=txt} org.elasticsearch.xpack.esql.EsqlIllegalArgumentException: unknown physical plan node [OrderExec]
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:214)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planMvExpand(LocalExecutionPlanner.java:561)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:189)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planLimit(LocalExecutionPlanner.java:556)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:187)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planOutput(LocalExecutionPlanner.java:275)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:209)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:155)
        at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:256)
        at org.elasticsearch.xpack.esql.plugin.ComputeService.lambda$execute$4(ComputeService.java:167)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:49)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleResponse(TransportService.java:1695)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1411)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1510)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.transport.TransportService$DirectResponseChannel$1.doRun(TransportService.java:1487)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
        at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### LINKED ISSUE #100774: ESQL: when double limiting the limit after mv_expand is not applied anymore
### Description

For `from employees | where emp_no == 10004 | limit 1 | keep emp_no, job_positions | mv_expand job_positions | limit 5` where one would expect at most 5 results (`job_positions` for `10004` has 4 values), there is only one returned, meaning the first `limit 1` is applied instead:

```
{
    "columns": [
        {
            "name": "emp_no",
            "type": "integer"
        },
        {
            "name": "job_positions",
            "type": "keyword"
        }
    ],
    "values": [
        [
            10004,
            "Head Human Resources"
        ]
    ]
}
```

### PR DESCRIPTION
**Pull request by astefan**
Allow mv_expand to push down limit and project past it.
Have the limit before mv_expand to not override the limit after it, since mv_expand is special from this point of view in the sense that it creates more rows than the original ones as defined by the `from` command.

Fixes https://github.com/elastic/elasticsearch/issues/99971
Fixes https://github.com/elastic/elasticsearch/issues/100774

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 1]
```diff
@@ -383,7 +385,8 @@ protected LogicalPlan rule(Limit limit) {
                 // check if there's a 'visible' descendant limit lower than the current one
                 // and if so, align the current limit since it adds no value
                 // this applies for cases such as | limit 1 | sort field | limit 10
-                else {
+                // but NOT for mv_expand (ie | limit 1 | mv_expand x | limit 20) where we want that last "limit" to apply on expand results
+                else if (unary instanceof MvExpand == false) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:389]: Don't combine the limits for mv_expand.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 2]
```diff
@@ -888,6 +889,50 @@ public void testCombineOrderByThroughFilter() {
...
+            | mv_expand x
+            """);
+
+        var keep = as(plan, Project.class);
+        var limit = as(keep.child(), Limit.class);
+        var mvExpand = as(limit.child(), MvExpand.class);
+        assertThat(as(mvExpand.target(), FieldAttribute.class).name(), is("first_name"));
+    }
+
+    public void testDontPushDownLimitPastMvExpand() {
```
Comment (costin) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:919]: Add as javadoc the expanded plans.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 3]
```diff
@@ -653,8 +656,22 @@ protected LogicalPlan rule(Enrich re) {
         }
     }
 
-    protected static class PushDownAndCombineOrderBy extends OptimizerRules.OptimizerRule<OrderBy> {
+    protected static class PushDownMvExpand extends OptimizerRules.OptimizerRule<MvExpand> {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:659]: What's the advantage of pushing down MvExpand? I'd argue we want the opposite as this increases the amount of data earlier in the pipeline.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:389]: this works only if the limit is right above `mv_expand` - if it's hidden by another node (keep, where, etc..) the rule won't see it.
Move the check into descendantLimit so that if mv_expand is encountered, just like with an agg, no limit is returned.

**Review by costin — CHANGES_REQUESTED** [review]
The current approach can be improved and made more reliable - see my comments.

**Review by luigidellaquila — COMMENTED** [review]
Let me add a couple of comments, because I think the situation here is a bit more convoluted:
- pushing down `mv_expand` is a very peculiar operation: `sort a, b | mv_expand c` could be rewritten as `mv_expand c | sort a, b` (they have the same semantics), but this doesn't apply to `sort a, b | mv_expand a` (if `a` is expanded before the sort, the final result will be different)
- pushing down `limit` vs `mv_expand` can still be done (and is necessary in some cases), but with a slightly different logic: `mv_expand a | limit 10` is different from `limit 10 | mv_expand a`, but is equivalent to `limit 10 | mv_expand a | limit 10`. We will need this kind of logic especially when we have `sort`, eg. for `sort a | mv_expand b | limit 10`, if we don't push down `limit`, we won't be able to build a TopN.
- if we apply the rule above (ie. push down the limit, but also maintain the original limit at the end) we have to be careful, the plan optimization could enter in an infinite loop, eg. 
  1.  `sort ... | keep ... | mv_expand a | limit 10`
  2.  `sort ... | keep ... | limit 10 | mv_expand a | limit 10`
  3.  `sort ... | limit 10 | keep ... | mv_expand a | limit 10`
  4.  `topN(10) | keep ... | mv_expand a | limit 10`
  5.  `topN(10) | keep ... | limit 10 | mv_expand a | limit 10`
  6.  `topN(10) | limit 10 | keep ... | mv_expand a | limit 10`
  and so on
- `mv_expand` is a pretty heavy command (mostly in terms of memory consumption), so having a `limit` after it could be a sub-optimal solution. It could be much better to enhance MvExpandOperator with an internal limit, like for TopN

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 1 above)
Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:389]: Good point. Haven't thought of this scenario.

**Review by luigidellaquila — COMMENTED** [review]
Thank you very much @astefan, I think we are much closer to a solution, but apparently there are still some cases that are not covered.
I managed to break the planning (`unknown physical plan node [OrderExec]`) with the following:

```
row a = 1 | sort a | mv_expand a | eval b = 100 | sort b | limit 10
```

I think the problem here is that MV_EXPAND between the two SORTs cuts out some optimization rules, so that the first sort (that is practically useless) does not get removed

**Comment by astefan** [comment]
> Thank you very much @astefan, I think we are much closer to a solution, but apparently there are still some cases that are not covered. I managed to break the planning (`unknown physical plan node [OrderExec]`) with the following:
> 
> ```
> row a = 1 | sort a | mv_expand a | eval b = 100 | sort b | limit 10
> ```
> 
> I think the problem here is that MV_EXPAND between the two SORTs cuts out some optimization rules, so that the first sort (that is practically useless) does not get removed

@luigidellaquila thank you for this scenario. I didn't think of testing such a query.
The problem with this one is that the `eval` is not pushed down past `mv_expand` and `sort a` not pushed up until it reaches `sort b`. If `mv_expand` wouldn't have been there, the two `sort`s would have been combined in a single one: `sort a, b` and eventually would have became `TopN(a, b)`.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 4]
```diff
@@ -406,6 +423,25 @@ protected LogicalPlan rule(Limit limit) {
          */
         private static Limit descendantLimit(UnaryPlan unary) {
             UnaryPlan plan = unary;
+            while (plan instanceof Aggregate == false) {
+                if (plan instanceof Limit limit) {
+                    return limit;
+                } else if (plan instanceof MvExpand) {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:429]: Why not apply the same behavior for Aggregate - stop searching for a limit once an MvExpand is found?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 5]
```diff
@@ -382,6 +383,22 @@ protected LogicalPlan rule(Limit limit) {
...
+                    // - the input of mv_expand is as small as possible before it is expanded (less rows to inflate and occupy memory)
+                    if (limitBeforeMvExpand == null) {
+                        var duplicateLimit = new Limit(limit.source(), limit.limit(), mvExpand.child());
+                        if (unary instanceof OrderBy orderBy) {
+                            return limit.replaceChild(orderBy.replaceChild(mvExpand.replaceChild(duplicateLimit)));
+                        } else {
+                            return limit.replaceChild(mvExpand.replaceChild(duplicateLimit));
+                        }
+                    }
+                }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:401]: This block needs to be simplified as the main condition is checked 2-3 times.
do a simple boolean isMvExpand = unary instanceof MvExpand, boolean orderByChild = unary instanceof OrderBy && ...
then use those later in the code.

**Review by costin — COMMENTED** [review]
Left a small round of comments - a potential problem with the current approach is looking at things top-down vs bottom-up; the later might simplify the rule.

**Comment by astefan** [comment]
I have another solution to how we handle mv_expand that is also adapted to further scenarios discovered in the meantime. But it has some bigger implications, non-ideal ones. This change is not final, but I am providing below these new points for awareness purposes and feedback.
- `from employees | sort emp_no | mv_expand job_positions | limit 5`. In this case `limit 5` should be pushed down past mv_expand until `sort emp_no` because we unnecessarily expand a lot of `job_positions` values if we only need 5 at the end. And because of https://github.com/elastic/elasticsearch/issues/99971.
- `from employees | sort emp_no | mv_expand job_positions | where job_positions like "*a*" | limit 5`. In this case we shouldn't push `limit 5` like we did for the first case because the limit happens on filtered `job_positions`. But we also need a limit for `sort emp_no`. And that limit is the "default one", the one that `Analyzer.AddImplicitLimit` rule defines.
  - the code in current form it's using the `esql.query.result_truncation_default_size` value (500) but to be entirely correct it should use the one added by the analyzer
  - the logical optimizer is now esqlconfiguration aware, which means it is parameterized and a new instance of it is created for each query. If we use the implicit limit from the analyzer, this change in the optimizer shouldn't be needed anymore.
- `from employees | mv_expand job_positions | limit 5` same argument as for the first scenario BUT differently from the first one we don't end up with an exception here because there is no `sort` that should be combined with a `limit` to form a `TopN`.

**Review by costin — APPROVED** [review]
LGTM.
The comments below can be done in a separate PR as they are mainly cosmetic and do NOT impact the 8.11 code.

The issue this ticket works on is dealing with _generators_, that is operators that create additional rows.
We only have them as a Source and thus no mechanism per se and thus makes this issue somewhat out of scope (one approach is to let the generator decide whether it can impose a limit or not internally).

My main comment is around moving the MvExpand handling from the CombineAndPushDownLimit into a separate rule - it shares little code with that rule and also complicated the logic.
Secondary, avoid making the Optimizer context aware and instead pick up the default limit from the plan (potentially through a separate path). If the limit was somehow optimized, try to incorporate that.
Again this is more of a tweak and can be done separately. On the flip side it would simplify the size of this PR.

**Comment by costin** [comment]
FTR, I've raised https://github.com/elastic/elasticsearch/pull/101248 to get away from the weird gradle compilation errors in the CI (and I was able to reproduce). I've cherry picked the changes, squashed them and rebased them on main.
I think the issue might be related to some incomplete merges (that went wrong).
