### PR TITLE
ESQL: Workaround for RLike handling of empty lang pattern

### LINKED ISSUE #128813: ESQL: AssertionError for RLIKE on # (hash)
### Description

For query `row x = "abc" | eval bool = x rlike "#"` I get

```
[ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch[runTask-0][search][T#1]], exiting java.lang.AssertionError
        at org.apache.lucene.core@10.2.1/org.apache.lucene.util.automaton.Automaton.getNumTransitions(Automaton.java:348)
        at org.apache.lucene.core@10.2.1/org.apache.lucene.util.automaton.Operations.getSingleton(Operations.java:1240)
        at org.elasticsearch.xpack.esql.core.expression.predicate.regex.AbstractStringPattern.exactMatch(AbstractStringPattern.java:35)
        at org.elasticsearch.xpack.esql.optimizer.rules.logical.ReplaceRegexMatch.rule(ReplaceRegexMatch.java:44)
        at org.elasticsearch.xpack.esql.optimizer.rules.logical.ReplaceRegexMatch.rule(ReplaceRegexMatch.java:20)
        at org.elasticsearch.xpack.esql.optimizer.rules.logical.OptimizerRules$OptimizerExpressionRule.lambda$apply$0(OptimizerRules.java:62)
```

I've tried something similar on `_search` but didn't reproduce the same behavior:

```
{"index":{"_index":"test1","_id":1}}
{"test":"abc"}
```

```
{
    "query": {
        "regexp": {
            "test.keyword": {
                "value": "#",
                "flags": "ALL"
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by bpintea**
Lucene's `org.apache.lucene.util.automaton.Operations#getSingleton` fails with an Automaton for a `REGEXP_EMPTY` `RegExp`. This adds a workaround for that, to check the type of automaton before calling into that failing method.

Closes #128813

### CODE REVIEW

**Review by astefan — APPROVED** [review]
LGTM

**Comment by bpintea** [comment]
Thanks, Andrei!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 1]
```diff
@@ -1177,11 +1177,17 @@ public enum Cap {
...
+         * Allows RLIKE to correctly handle the "empty language" flag, `#`.
+         */
+        RLIKE_WITH_EMPTY_LANGUAGE_PATTERN,
+
         /**
          * MATCH PHRASE function
          */
         MATCH_PHRASE_FUNCTION(Build.current().isSnapshot());
 
+
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]: Ugh, resolving conflicts from the browser :-/
