### PR TITLE
Switching LockObtainFailedException over to ShardLockObtainFailedException

### LINKED ISSUE #19978: Switch InternalShardLock from using LockObtainFailedException to a different exception
According to the [documentation](https://github.com/apache/lucene-solr/blob/cea8a488f0d48041abb4be0dbe29ab81f04522bf/lucene/core/src/java/org/apache/lucene/store/LockObtainFailedException.java#L22-L25) for `LockObtainFailedException`:

`This exception is thrown when the <code>write.lock</code> could not be acquired.`

We should not use this exception for the in-memory semaphore that's part of [NodeEnvironment](https://github.com/elastic/elasticsearch/blob/15c96df5b5d5b22b13a27adb4650917fc6ad1d80/core/src/main/java/org/elasticsearch/env/NodeEnvironment.java#L706-L716), we should use a different exception class.

### PR DESCRIPTION
**Pull request by dakrone**
`LockObtainFailedException` should be reserved for on-disk locks that
Lucene attempts (like `write.lock`). This switches our in-memory
semaphore locks for shards to use a different exception. Additionally,
ShardLockObtainFailedException no longer subclasses IOException, since
no IO is being done is this case.

Resolves #19978

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/IndexService.java [hunk 1]
```diff
@@ -349,9 +351,13 @@ public synchronized IndexShard createShard(ShardRouting routing) throws IOExcept
             shards = newMapBuilder(shards).put(shardId.id(), indexShard).immutableMap();
             success = true;
             return indexShard;
+        } catch (ShardLockObtainFailedException e) {
+            throw new IOException("failed to obtain in-memory shard lock", e);
         } finally {
             if (success == false) {
-                IOUtils.closeWhileHandlingException(lock);
+                if (lock != null) {
+                    IOUtils.closeWhileHandlingException(lock);
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/IndexService.java]: Believe it or not, it's fine to pass `null` to `IOUtils.closeWhileHandlingException` (it just skips them).  We do that for cases where you might have N things that need closing from a large try block, and you don't know which are `null` and which are not (depends on where the exception was thrown).

But for here I like the `null` check: less smelly.

File: core/src/main/java/org/elasticsearch/index/store/Store.java [hunk 2]
```diff
@@ -388,6 +389,8 @@ public static MetadataSnapshot readMetadataSnapshot(Path indexLocation, ShardId
             // that's fine - happens all the time no need to log
         } catch (FileNotFoundException | NoSuchFileException ex) {
             logger.info("Failed to open / find files while reading metadata snapshot");
+        } catch (ShardLockObtainFailedException ex) {
+            logger.info("{}: failed to obtain shard lock", shardId);
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/index/store/Store.java]: Should we include `ex` here?

**Comment by mikemccand** [comment]
LGTM

File: core/src/main/java/org/elasticsearch/index/IndexService.java (hunk 1 above)
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/index/IndexService.java]: That's great to know, thanks for the info!

File: core/src/main/java/org/elasticsearch/index/store/Store.java (hunk 2 above)
Comment (dakrone) [inline core/src/main/java/org/elasticsearch/index/store/Store.java]: Yes we should, great catch!

**Comment by dakrone** [comment]
Thanks for reviewing @mikemccand!
