### PR TITLE
NoSuchRemoteClusterException should not be thrown when a remote is configured

### LINKED ISSUE #107381: NoSuchRemoteClusterException is returned for both non-existent remotes and remotes with skip_unavailable=true
### Elasticsearch Version

8.14-SNAPSHOT

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin michaels-mbp.lan 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

### Problem Description

When doing cross-cluster searches (`_search` or `_async_search`), `NoSuchRemoteClusterException` is returned for both non-existent remotes and remotes with skip_unavailable=true that cannot be connected to. By contrast, remotes with skip_unavailable=false return a "connection_exception" error message when they cannot be reached.

Should we also be returning "connection exception" errors for skip_unavailable=true remotes? Should NoSuchRemoteClusterException be reserved for attempts to search clusters that are not configured?

This issue occurs for both non-secured and secured clusters. See the "Steps to Reproduce" section for details.

### Steps to Reproduce

Manual testing. Configure a cluster to connect to two remote clusters. In my case, the three clusters all run on the same local machine and the config on the primary looks like:

```
cluster:
    remote:
        remote1:
            seeds: 127.0.0.1:9301
            skip_unavailable: true
        remote2:
            seeds: 127.0.0.1:9302
            skip_unavailable: false
```

<br/>

#### Scenario 1: on a non-secured cluster, query for remote5

```
POST  remote5: */_async_search
{
   ... query not shown ...
}
```

You get a `NoSuchRemoteClusterException` (as expected)

<details><summary>Response example (toggle)</summary>

```
{
  "id": "FnFVcFctWTNxUnRDZlNzVVZFU2Q1dncaMWdWNHdULXdUaEtsUjc2UFJvTm9HZzoyNTk=",
  "is_partial": true,
  "is_running": false,
  "start_time_in_millis": 1712781379327,
  "expiration_time_in_millis": 1713213379327,
  "error": {
    "type": "status_exception",
    "reason": "error while executing search",
    "caused_by": {
      "type": "no_such_remote_cluster_exception",
      "reason": "no such remote cluster: [remote11]"
    }
  }
}
```

</details>

<br/>

#### Scenario 2: on a non-secured cluster, query for remote2 (skip_unavailable=false) when remote2 is not running/down

You get a "not connected" type exception (as expected)

<details><summary>Response example (toggle)</summary>

```
{
  "id": "FnhXUkh5dTQ5U0ppdWlVNUFTeFF4MGcaMWdWNHdULXdUaEtsUjc2UFJvTm9HZzoxNTM=",
  "is_partial": true,
  "is_running": false,
  "start_time_in_millis": 1712781752071,
  "expiration_time_in_millis": 1713213752071,
  "error": {
    "type": "status_exception",
    "reason": "error while executing search",
    "caused_by": {
      "type": "connect_transport_exception",
      "reason": "[][127.0.0.1:9302] connect_exception",
      "caused_by": {
        "type": "uncategorized_execution_exception",
        "reason": "Failed execution",
        "caused_by": {
          "type": "execution_exception",
          "reason": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9302",
          "caused_by": {
            "type": "annotated_connect_exception",
            "reason": "Connection refused: /127.0.0.1:9302",
            "caused_by": {
              "type": "connect_exception",
              "reason": "Connection refused"
            }
          }
        }
      }
    }
  }
}
```

</details>

<br/>

#### Scenario 3: on a non-secured cluster, query for remote1 (skip_unavailable=true) when remote1 is not running/down

In the search response you get a NoSuchRemoteClusterException:

```
// snippet of _cluster/details section in SearchResponse:
          "status": "skipped",
          "indices": "*",
          "timed_out": false,
          "failures": [
            {
              "shard": -1,
              "index": null,
              "reason": {
                "type": "no_such_remote_cluster_exception",
                "reason": "no such remote cluster: [remote1]"
              }
            }
          ]
```

<details><summary>Stack trace in logs when this happens (toggle)</summary>

```
[2024-04-10T16:39:21,495][WARN ][o.e.t.SniffConnectionStrategy] [node-1] fetching nodes from external cluster [remote1] failed org.elasticsearch.transport.ConnectTransportException: [][127.0.0.1:9301] connect_exception
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:1144)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener$FailureResult.complete(SubscribableListener.java:390)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:302)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:327)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.onFailure(SubscribableListener.java:246)
        at org.elasticsearch.transport.netty4@8.14.0-SNAPSHOT/org.elasticsearch.transport.netty4.Netty4Utils.lambda$addListener$2(Netty4Utils.java:178)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:322)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:338)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.common@4.1.107.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.elasticsearch.common.util.concurrent.UncategorizedExecutionException: Failed execution
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.action.support.SubscribableListener.wrapAsExecutionException(SubscribableListener.java:283)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ListenableFuture.wrapException(ListenableFuture.java:38)
        at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ListenableFuture.wrapException(ListenableFuture.java:27)
        ... 18 more
Caused by: java.util.concurrent.ExecutionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9301
        ... 21 more
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9301
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
        at io.netty.transport@4.1.107.Final/io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652)
        at io.netty.transport@4.1.107.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.common@4.1.107.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.common@4.1.107.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

</details>

<br/>

#### Secured clusters

I believe the same issue occurs on a secured cluster.

Example: in this test of [RemoteClusterSecurityFcActionAuthorizationIT](https://github.com/elastic/elasticsearch/pull/105792/files#diff-7e661242193b12735bd6cb53ce9be1edce2b8a74e5fa5b27039bdec8598e8f50R317), when the default value of skip_unavailable was changed from `false` to `true`, the search no longer throws the expected `ElasticsearchSecurityException`, but now instead throws `NoSuchRemoteClusterException`.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by quux00**
When a remote cluster has been configured by an admin, but is not connected, clusters marked with skip_unavailable=true will have `NoSuchRemoteClusterException` thrown, which is confusing. This fix changes that for one of the connection lookup pathways.

Fixes https://github.com/elastic/elasticsearch/issues/107381

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/transport/RemoteClusterService.java [hunk 1]
```diff
@@ -240,7 +240,15 @@ public boolean isSkipUnavailable(String clusterAlias) {
     }
 
     public Transport.Connection getConnection(String cluster) {
-        return getRemoteClusterConnection(cluster).getConnection();
+        try {
+            return getRemoteClusterConnection(cluster).getConnection();
+        } catch (NoSuchRemoteClusterException e) {
+            if (getRemoteClusterNames().contains(cluster)) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/transport/RemoteClusterService.java:246]: I worry that this kind of approach might see inconsistent views of the current set of remote clusters and give confusing results. Can make it so that `org.elasticsearch.transport.RemoteConnectionManager#getAnyRemoteConnection` doesn't throw a `NoSuchRemoteClusterException` instead? That's definitely incorrect, if we have a `RemoteConnectionManager` instance then the remote cluster definitely exists, and conversely that looks to be the only incorrect one.

Comment (quux00) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterService.java]: Thanks. I see why you say that now. I have changed it in the last commit(s).

**Review by DaveCTurner — APPROVED** [review]
LGTM except could we add a test for this exception behaviour, something like this:

```diff
diff --git a/server/src/test/java/org/elasticsearch/transport/RemoteConnectionManagerTests.java b/server/src/test/java/org/elasticsearch/transport/RemoteConnectionManagerTests.java
index d8ddd7c356b..667277f9ea1 100644
--- a/server/src/test/java/org/elasticsearch/transport/RemoteConnectionManagerTests.java
+++ b/server/src/test/java/org/elasticsearch/transport/RemoteConnectionManagerTests.java
@@ -101,6 +101,21 @@ public class RemoteConnectionManagerTests extends ESTestCase {
         assertThat(proxyNodes, containsInAnyOrder("node-2"));
     }

+    public void testDisconnectedException() {
+        assertEquals(
+            "Unable to connect to [remote-cluster]",
+            expectThrows(ConnectTransportException.class, remoteConnectionManager::getAnyRemoteConnection).getMessage()
+        );
+
+        assertEquals(
+            "Unable to connect to [remote-cluster]",
+            expectThrows(
+                ConnectTransportException.class,
+                () -> remoteConnectionManager.getConnection(DiscoveryNodeUtils.create("node-1", address))
+            ).getMessage()
+        );
+    }
+
     public void testResolveRemoteClusterAlias() throws ExecutionException, InterruptedException {
         DiscoveryNode remoteNode1 = DiscoveryNodeUtils.create("remote-node-1", address);
         PlainActionFuture<Void> future = new PlainActionFuture<>();
```
