### PR TITLE
Fix SAML test initialisation flakiness

### LINKED ISSUE #139067: [CI] SamlServiceProviderMetadataIT testAuthenticationWhenMetadataIsUnreliable failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11513 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/2c4nh3muc5h2c)
- [elasticsearch-periodic-platform-support #11513 / windows-2025_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/r7dt7lbnxvztq)
- [elasticsearch-periodic-platform-support #11506 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/opgybnsf3mljg)
- [elasticsearch-periodic-platform-support #11506 / windows-2025_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/k7wbbbbgccdkg)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:security:qa:saml-rest-tests:javaRestTest" --tests "org.elasticsearch.xpack.security.authc.saml.SamlServiceProviderMetadataIT.testAuthenticationWhenMetadataIsUnreliable" -Dtests.seed=4ABE243CE4233969 -Dtests.locale=ks-Deva -Dtests.timezone=America/Winnipeg -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.saml.SamlServiceProviderMetadataIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAuthenticationWhenMetadataIsUnreliable'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Expected exception ResponseException but no exception was thrown
```

**Issue Reasons:**
- [main] 2 consecutive failures in step windows-2022_checkpart4_platform-support-windows
- [main] 2 consecutive failures in step windows-2025_checkpart4_platform-support-windows
- [main] 4 failures in test testAuthenticationWhenMetadataIsUnreliable (2.8% fail rate in 144 executions)
- [main] 2 failures in step windows-2022_checkpart4_platform-support-windows (100.0% fail rate in 2 executions)
- [main] 2 failures in step windows-2025_checkpart4_platform-support-windows (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by piotrsulkowski-elastic**
Remove a short window of time, during which the metadata was available and potentially could be cached by a background thread, before the actual test method is called. The test method assumes that the metadata is not cached, hence that could have created the flakiness.

Closes #139067

### CODE REVIEW

File: x-pack/plugin/security/qa/saml-rest-tests/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/saml/SamlInResponseToIT.java [hunk 1]
```diff
@@ -30,6 +31,15 @@ public class SamlInResponseToIT extends SamlRestTestCase {
 
     private static final int REALM_NUMBER = 1;
 
+    @BeforeClass
+    public static void enableMetadata() {
```
Comment (jfreden) [inline x-pack/plugin/security/qa/saml-rest-tests/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/saml/SamlInResponseToIT.java]: Another option is to add an `initMetadata` in a `@Before` method in the base class that calls `makeMetadataAvailable` (before each test) that by default makes it available, and then override `initMetadata` in `SamlServiceProviderMetadataIT` to make it unavailable. That way we would have have the more expected available default behaviour in the base class.

**Review by jfreden — APPROVED** [review]
LGTM!

File: x-pack/plugin/security/qa/saml-rest-tests/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/saml/SamlRestTestCase.java [hunk 2]
```diff
@@ -194,6 +192,18 @@ public static void loadCertificateAuthority() throws Exception {
...
 
+    /**
+     * Make metadata available by default before each test, but make this behaviour controllable by subclasses.
+     */
+    @Before
+    public void initMetadata() {
+        enableMetadataBeforeTestIfNeeded();
+    }
+
+    protected void enableMetadataBeforeTestIfNeeded() {
```
Comment (jfreden) [inline x-pack/plugin/security/qa/saml-rest-tests/src/javaRestTest/java/org/elasticsearch/xpack/security/authc/saml/SamlRestTestCase.java]: This should probably be a `boolean isMetadataAvailable()` instead, that way you avoid the awkward empty method in the override.

**Review by jfreden — APPROVED** [review]
LGTM! Just a suggestion for readability. With that change you can remove the comments I think.

**Comment by piotrsulkowski-elastic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/146593)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/146594)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
