### PR TITLE
Flatten object mappings when subobjects is false

### LINKED ISSUE #99860: Auto-flatten mappings when `subobjects` is set to `false`
In Elastic observability, we want to set `subobjects: false` at the root level in logs, metrics, and traces data streams.

Auto-flattening documents (#88934) played a huge role in making this a backwards compatible change.

However, there's another hurdle to adoption: when subobjects are disabled, mappings need to be specified in a flattened way, where the full path is denoted as a dotted string, instead of using `properties`, which implies the `object` field type which is not supported when subobjects are disabled.

While we can change the mappings in our [integrations](https://github.com/elastic/integrations), we can't change user-defined mappings that are mixed into the integration mappings via `<integration>@custom` component templates.

Therefore, changing `subobjects` to `false` would be a breaking change that results in errors when updating integrations.

To mitigate this, we'd want to automatically flatten mappings:

When given an object mappings like this:

```yaml
mapping:
  subobjects: false
  properties:
    foo:
      properties:
        bar:
          type: keyword
```

We'll turn it into a flat mapping like this:
```yaml
mapping:
  subobjects: false
  properties:
    foo.bar:
      type: keyword
```

There will be some limitations, however. For example, this doesn't work when [mapping parameters](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html#object-params) on the object field type are used (such as `enabled` and `dynamic`). These can't simply be pushed down to the children as they also affect non-explicitly mapped children that are added via dynamic mapping. There may be something we can do in the future to support some kind of wildcard matching (such as `"foo.*" { "enabled": false }`) but this won't be part of the first iteration and we'll need to get more quantitative data on whether it is worth the development effort and added complexity.

Also, the `nested` field type is not supported with `subobjects: true`.

### LINKED ISSUE #103497: Merging mappings with `subobjects: false` can result in invalid mappings
### Elasticsearch Version

8.11

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

macOS 14.2

### Problem Description

I found a way to corrupt the mappings using `subobjects: false`. The reason is that ES is only validating that there must be no object mappers within in an object that's configured with `subobjects: false` while parsing mappings:

https://github.com/elastic/elasticsearch/blob/fb5c74475b1526302453a72677af2ec23ddbfc64/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java#L312-L320

However, it's possible to create an invalid mapping using two distinct mapping updates that are valid on their own but invalid when the mappings are merged.

This invalid mapping merge is caught in testing with this assertion that re-parses the merged mappings:

https://github.com/elastic/elasticsearch/blob/fb5c74475b1526302453a72677af2ec23ddbfc64/server/src/main/java/org/elasticsearch/index/mapper/MapperService.java#L526

Since assertions are disabled in production, it's possible to create an invalid mapping.

To fix this, we could enable the assertion in production, too. Or, maybe a better way would be to catch the error scenario earlier, during mapping merge.

In these cases, we could check if we're trying to add an `ObjectMapper` even though subobjects are disabled:

https://github.com/elastic/elasticsearch/blob/fb5c74475b1526302453a72677af2ec23ddbfc64/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java#L546-L549

### Steps to Reproduce

```
PUT test
{
  "mappings": {
    "properties": {
      "parent": {
        "type": "object",
        "subobjects": false
      }
    }
  }
}

PUT test/_mapping
{
  "properties": {
    "parent.child.grandchild": {
      "type": "keyword"
    }
  }
}
```

```
# POST test/_search 503 Service Unavailable
{
  "error": {
    "root_cause": [
      {
        "type": "no_shard_available_action_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test",
        "node": null,
        "reason": {
          "type": "no_shard_available_action_exception",
          "reason": null
        }
      }
    ]
  },
  "status": 503
}
# GET test/_mapping 200 OK
{
  "test": {
    "mappings": {
      "properties": {
        "parent": {
          "subobjects": false,
          "properties": {
            "child": {
              "properties": {
                "grandchild": {
                  "type": "keyword"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by felixbarny**
Closes #99860
Also fixes #103497

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 1]
```diff
@@ -540,25 +555,33 @@ private static Map<String, Mapper> buildMergedMappers(
...
-            Iterator<Mapper> iterator = mergeWithObject.iterator();
-            if (iterator.hasNext() == false) {
-                return Map.copyOf(existing.mappers);
+            Map<String, Mapper> mergedMappers = new HashMap<>();
+            for (Mapper existingMapper : existing.mappers.values()) {
+                if (subobjects == false && existingMapper instanceof ObjectMapper objectMapper) {
+                    objectMapper.flatten(objectMergeContext.getMapperBuilderContext()).forEach(m -> mergedMappers.put(m.simpleName(), m));
+                } else {
+                    putMergedMapper(mergedMappers, existingMapper);
+                }
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:567]: I am trying to summarize in my head why we need to auto-flatten at merge time, and not only when getting mappings. What would not work if we did not do it at merge time perhaps?

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 2]
```diff
@@ -594,6 +620,58 @@ private static ObjectMapper truncateObjectMapper(MergeReason reason, MapperMerge
...
+            );
+        }
+        if (isEnabled() == false) {
+            throw new IllegalArgumentException(
+                "cannot flatten object [" + path.pathAsText(simpleName()) + "] because the value of [enabled] is [false]"
+            );
+        }
+        if (subobjects.explicit() && subobjects()) {
+            throw new IllegalArgumentException(
+                "cannot flatten object [" + path.pathAsText(simpleName()) + "] because the value of [subobjects] is [true]"
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:670]: I wonder if these errors should be more similar to the previous error message e.g. we found an object under an object with subobjects false - we tried to auto-flatten but we couldn't because....

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 3]
```diff
@@ -627,7 +705,7 @@ void toXContent(XContentBuilder builder, Params params, ToXContent custom) throw
     protected void serializeMappers(XContentBuilder builder, Params params) throws IOException {
         // sort the mappers so we get consistent serialization format
         Mapper[] sortedMappers = mappers.values().toArray(Mapper[]::new);
-        Arrays.sort(sortedMappers, Comparator.comparing(Mapper::name));
+        Arrays.sort(sortedMappers, Comparator.comparing(Mapper::simpleName));
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:708]: I have a deja-vu seeing this change. I believe I've been here before and badly broken things this way. We no longer include the full path when sorting which makes use sort inconsistently, for instance  for foo.bar and bar and baz.bar it is not clear which one comes first?

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java [hunk 4]
```diff
@@ -1467,4 +1455,262 @@ public void testMergeUntilLimitCapacityOnlyForParent() throws IOException {
...
+                        "type" : "keyword"
+                      }
+                    }
+                  }
+                }
+              }
+            }""");
+    }
+
+    public void testExpand() throws IOException {
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java:1679]: There is nothing about subobjects false in this new test, right? Could you clarify what we are testing in the test method name?

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java [hunk 5]
```diff
@@ -1467,4 +1455,262 @@ public void testMergeUntilLimitCapacityOnlyForParent() throws IOException {
...
+        final MapperService mapperService = createMapperService(mapping(b -> {}));
+        MapperParsingException e = expectThrows(
+            MapperParsingException.class,
+            () -> mapperService.merge("_doc", List.of(mapping1, mapping2), MergeReason.INDEX_TEMPLATE)
+        );
+        assertThat(
+            e.getMessage(),
+            containsString(
+                "Failed to parse mapping: cannot flatten object [parent] because the value of [dynamic] (TRUE) is not compatible "
+                    + "with the value from its parent context (FALSE)"
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java:1632]: I commented above, I think we should try to improve the error message, or it will be very difficult to read for users.

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java [hunk 6]
```diff
@@ -1467,4 +1455,262 @@ public void testMergeUntilLimitCapacityOnlyForParent() throws IOException {
...
+    public void testAutoFlattenObjectsSubobjectsMergeConflictingMappingParameterRoot() throws IOException {
+        CompressedXContent mapping1 = new CompressedXContent("""
+            {
+              "subobjects": false,
+              "dynamic": false
+            }""");
+
+        CompressedXContent mapping2 = new CompressedXContent("""
+            {
+              "properties": {
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java:1607]: If this second mapping had `subobjects:true` at its root, what would have been the result?

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java [hunk 7]
```diff
@@ -1467,4 +1455,262 @@ public void testMergeUntilLimitCapacityOnlyForParent() throws IOException {
...
+                      "properties" : {
+                        "grandchild" : {
+                          "type" : "keyword"
+                        }
+                      }
+                    }
+                  }
+                }
+              }
+            }""");
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java:1525]: this is  good example. And what would have happened if this second mapping only disabled subobjects? would we have auto-flattened the existing child object?

File: server/src/main/java/org/elasticsearch/index/mapper/Mapper.java [hunk 8]
```diff
@@ -24,7 +24,7 @@ public abstract class Mapper implements ToXContentFragment, Iterable<Mapper> {
 
     public abstract static class Builder {
 
-        protected final String name;
+        protected String name;
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/Mapper.java:27]: this is odd. I do see why you need it though. You get a builder from the mapper, and want to build a new mapper with only the field name changed. One solution could be to introduce a new method that's specific to this scenario, but that would need to be added to every single mapper. Perhaps it could be returning the mapper directly and taking the new name as an argument.

One thing that bugs me is that the member is protected, and used directly in many places, while there is a public getter for it. It would be easier to track who uses the setter (say we introduce it) if the field was private.  Another aspect that is not great is that we make the field non final on Mapper.Builder, but in practice this is only ever needed in FieldMapper.Builder . 

I haven't come up with an appealing enough alternative but I think it would be good to rethink how we got this bit done.

**Review by javanna — COMMENTED** [review]
I did a first pass and left a bunch of comments.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 1 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:567]: Perhaps the answer is #103497 .

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 3 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:708]: I remember this has caused cryptic `MapperService#assertRefreshIsNotNeeded` failures when I made that change.

File: docs/reference/mapping/params/subobjects.asciidoc [hunk 9]
```diff
@@ -105,3 +110,70 @@ PUT my-index-000001/_doc/metric_1
...
+However, it is also possible to define these properties as sub-objects in the mappings.
+In that case, the mapping will be automatically flattened before it is stored.
+This makes it easier to re-use existing mappings without having to re-write them.
+
+Note that auto-flattening will not work when certain <<mapping-params, mapping parameters>> are set
+on object mappings that are defined under an object configured with `subobjects: false`:
+
+* The <<enabled, `enabled`>> mapping parameter must not be `false`.
+* The <<dynamic, `dynamic`>> mapping parameter must not contradict the implicit or explicit value of the parent.
+* The <<subobjects, `subobjects`>> mapping parameter mot not be set to `true` explicitly.
```
[the remark this answers is not in the document]
Comment (felixbarny) [reply docs/reference/mapping/params/subobjects.asciidoc:127]: Think of a component template (A) that was written with "traditional" object mappings in mind (subobjects is not set, the default value true is used). This PR makes it so that this component template can be used in combination with another component template (B) that sets subobjects to false. However, one limitation is that in component template A, the object mappers must not be defined with `subobjects: true`. We could also choose to just discard the subobjects mapping parameter but I chose a more conservative approach that would reject such mappings. However, the consequence is that adding subobjects: false to existing mappings may fail.

File: docs/reference/mapping/params/subobjects.asciidoc [hunk 10]
```diff
@@ -105,3 +110,70 @@ PUT my-index-000001/_doc/metric_1
...
+(as shown in the first example).
+However, it is also possible to define these properties as sub-objects in the mappings.
+In that case, the mapping will be automatically flattened before it is stored.
+This makes it easier to re-use existing mappings without having to re-write them.
+
+Note that auto-flattening will not work when certain <<mapping-params, mapping parameters>> are set
+on object mappings that are defined under an object configured with `subobjects: false`:
+
+* The <<enabled, `enabled`>> mapping parameter must not be `false`.
+* The <<dynamic, `dynamic`>> mapping parameter must not contradict the implicit or explicit value of the parent.
```
[the remark this answers is not in the document]
Comment (felixbarny) [reply docs/reference/mapping/params/subobjects.asciidoc:126]: I've added
> For example, when `dynamic` is set to `false` in the root of the mapping, object mappers that set `dynamic` to `true` can't be auto-flattened.

File: server/src/main/java/org/elasticsearch/index/mapper/Mapper.java (hunk 8 above)
Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/Mapper.java:27]: I think it's fine for a builder to have mutable state - that's what it is made for. Only when you build the actual object, you'll get an immutable instance. I like your idea of encapsulating the instance variable more. I could make it private and force using the getter instead. The setter can then also be package-private.

Fun fact, the field used to be non-final before https://github.com/elastic/elasticsearch/pull/70837

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 11]
```diff
@@ -318,7 +320,11 @@ protected static void parseProperties(
                     }
                     Mapper.Builder fieldBuilder;
                     if (objBuilder.subobjects.value() == false) {
-                        fieldBuilder = typeParser.parse(fieldName, propNode, parserContext);
+                        if (type.equals(ObjectMapper.CONTENT_TYPE)) {
+                            fieldBuilder = typeParser.parse(fieldName, propNode, parserContext);
+                        } else {
+                            fieldBuilder = typeParser.parse(fieldName, propNode, parserContext);
+                        }
```
[the remark this answers is not in the document]
Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:327]: What was I trying to do there? Probably a leftover from debugging.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 12]
```diff
@@ -390,6 +396,9 @@ private static void validateFieldName(String fieldName, IndexVersion indexCreate
         } else {
             this.mappers = Map.copyOf(mappers);
         }
+        if (subobjects.value() == false && this.mappers.values().stream().anyMatch(m -> m instanceof ObjectMapper)) {
+            throw new IllegalStateException("When subobjects is false, mappers must not contain an ObjectMapper");
+        }
```
[the remark this answers is not in the document]
Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:401]: No strong opinion here. But if it's an assertion, there's a chance that we'll construct an ObjectMapper that has sub objects even if `subobjects` is set to false. I can change it to an assertion.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 1 above)
Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:567]: It's also when two independent component templates are combined in the context of an index template. The component templates may not be written with subobjects: false in mind. But when they're imported into an index template that sets subobjects: false, the component templates need to be flattened during that merge process.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 3 above)
Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:708]: Did you break it by setting it to sort by `simpleName` or  by setting it to `name`? I don't fully remember why I made this change but something was failing for me.

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java (hunk 7 above)
Comment (felixbarny) [reply server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java:1525]: > what would have happened if this second mapping only disabled subobjects?

I don't understand. It does disable subobjects:

```json
                "parent" : {
                  "subobjects" : false,
```

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java (hunk 6 above)
Comment (felixbarny) [reply server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java:1607]: The result would be the same.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 3 above)
Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:703]: I just did a quick couple of tests and nothing seemed to break when reverting this. I'll push a revert and then see what CI thinks.

Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java]: I definitely broke it with the change you had made, from name to simpleName, because name is the full path, while simple name only the leaf name. I need to rename these, there's a TODO somewhere about clarifying what they are.

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java (hunk 7 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java:1525]: and the sub-object defined in that path (from the other mapping definition) gets removed?

File: server/src/main/java/org/elasticsearch/index/mapper/Mapper.java (hunk 8 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/Mapper.java]: I see what you mean. I just find it hard to trace why the name has to change, and it's counter intuitive that it has a name set that later has to change.

> I like your idea of encapsulating the instance variable more. I could make it private and force using the getter instead. The setter can then also be package-private.

Shall we make that change separately so we don't introduce additional changes to this PR?

File: server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java (hunk 7 above)
Comment (felixbarny) [reply server/src/test/java/org/elasticsearch/index/mapper/MapperServiceTests.java:1525]: Yes, it get's removed.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 3 above)
Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java]: Gotcha. Seems like the tests still work after reverting my changes.

File: server/src/main/java/org/elasticsearch/index/mapper/Mapper.java (hunk 8 above)
Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/Mapper.java]: Sure, here's the PR: https://github.com/elastic/elasticsearch/pull/105648

Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/Mapper.java]: > I see what you mean. I just find it hard to trace why the name has to change, and it's counter intuitive that it has a name set that later has to change.

I get what you mean. But I don't think the effort of implementing a new method in every field mapper is worth it. As this is a builder after all, I don't think it's bad practice to make it mutable. With the setter being package-protected, we also don't expose the setter to everyone.

Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/Mapper.java]: agreed, that's a good trade-off.

Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/Mapper.java]: Cool, I've merged https://github.com/elastic/elasticsearch/pull/105648 which encapsulates `Mapper.Builder#name` and then merged main into this PR.

File: docs/reference/mapping/params/subobjects.asciidoc (hunk 9 above)
[the remark this answers is not in the document]
Comment (javanna) [reply docs/reference/mapping/params/subobjects.asciidoc]: ok. I see how this makes sense applied to component templates. I got confused because in the docs there is no context around component templates, and subobjects can't normally be changed back to true once set to false, so I was wondering: that is already not valid mappings, why do we need to state that explicitly. I am still uncertain of whether we should specify it or not.

**Review by javanna — COMMENTED** [review]
a few more questions and comments, this is almost ready.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 13]
```diff
@@ -594,6 +615,58 @@ private static ObjectMapper truncateObjectMapper(MergeReason reason, MapperMerge
         }
     }
 
+    /**
+     * Returns all FieldMappers this ObjectMapper or its children hold.
+     * The name of the FieldMappers will be updated to reflect the hierarchy.
+     *
+     * @throws IllegalArgumentException if the mapper cannot be flattened
+     */
+    List<FieldMapper> flatten(MapperBuilderContext context) {
```
[the remark this answers is not in the document]
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java]: making it static makes it clear that no state of the object it is called against is affected.

[the remark this answers is not in the document]
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java]: new naming looks good, I am fine with this.

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 14]
```diff
@@ -540,25 +550,33 @@ private static Map<String, Mapper> buildMergedMappers(
...
-            Map<String, Mapper> mergedMappers = new HashMap<>(existing.mappers);
-            while (iterator.hasNext()) {
-                Mapper mergeWithMapper = iterator.next();
+            for (Mapper mergeWithMapper : mergeWithObject) {
                 Mapper mergeIntoMapper = mergedMappers.get(mergeWithMapper.simpleName());
-                Mapper merged = null;
                 if (mergeIntoMapper == null) {
-                    if (objectMergeContext.decrementFieldBudgetIfPossible(mergeWithMapper.getTotalFieldsCount())) {
-                        merged = mergeWithMapper;
+                    if (subobjects == false && mergeWithMapper instanceof ObjectMapper objectMapper) {
```
[the remark this answers is not in the document]
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:570]: Thanks for clarifying.

**Review by javanna — APPROVED** [review]
LGTM, great work.
