### PR TITLE
Unmute `FrozenSearchableSnapshotsIntegTests#testCreateAndRestorePartialSearchableSnapshot`

### LINKED ISSUE #122693: [CI] FrozenSearchableSnapshotsIntegTests testCreateAndRestorePartialSearchableSnapshot failing
**Build Scans:**
- [elasticsearch-intake #18196 / part2](https://gradle-enterprise.elastic.co/s/wythryzo24c3u)
- [elasticsearch-pull-request #56649 / part-2](https://gradle-enterprise.elastic.co/s/2mpgqw3n2up5u)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:searchable-snapshots:internalClusterTest" --tests "org.elasticsearch.xpack.searchablesnapshots.FrozenSearchableSnapshotsIntegTests.testCreateAndRestorePartialSearchableSnapshot" -Dtests.seed=939AED20A539540E -Dtests.locale=es-BZ -Dtests.timezone=Europe/Gibraltar -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.searchablesnapshots.FrozenSearchableSnapshotsIntegTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCreateAndRestorePartialSearchableSnapshot),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.
```

**Issue Reasons:**
- [main] 2 failures in test testCreateAndRestorePartialSearchableSnapshot (0.3% fail rate in 626 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by arteam**
The underlying failure `java.lang.AssertionError: Searchable snapshot directory does not support the operation [createOutput` was fixed in https://github.com/elastic/elasticsearch/pull/122006.

The automation bot was too aggressive in re-opening this issue.

Resolve #122693

### CODE REVIEW

**Comment by tlrx** [comment]
I think both failures are legit and require investigation, since they both contain https://github.com/elastic/elasticsearch/pull/122006. 

Looking at the logs I can see:
```
Caused by: java.lang.IllegalStateException: Failed to read data from cache: cache service is not started [CLOSED]
	at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.ensureLifecycleStarted(CacheService.java:251) ~[main/:?]
	at org.elasticsearch.xpack.searchablesnapshots.cache.full.CacheService.get(CacheService.java:281) ~[main/:?]
```

So I suspect the fix in #122006 is not complete and should also consider CLOSED state along with STOPPED.

**Comment by arteam** [comment]
@tlrx Let me add an extra state check :+1:

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/full/CacheService.java [hunk 1]
```diff
@@ -245,7 +245,7 @@ private void ensureLifecycleStarted() {
         final Lifecycle.State state = lifecycleState();
         assert state != Lifecycle.State.INITIALIZED : state;
         if (state != Lifecycle.State.STARTED) {
-            if (state == Lifecycle.State.STOPPED) {
+            if (state == Lifecycle.State.STOPPED || state == Lifecycle.State.CLOSED) {
                 throw new AlreadyClosedException("Failed to read data from cache: cache service is stopped");
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/cache/full/CacheService.java:249]:
```suggestion
                throw new AlreadyClosedException("Failed to read data from cache: cache service is [" + state + ']');
```

**Review by tlrx — APPROVED** [review]
LGTM, left a minor comment
