### PR TITLE
Always validate geo shapes when fetching

### LINKED ISSUE #69071: FieldExtractorIT#testGeoShapeField throws XContentParseException
**Build scan**: https://gradle-enterprise.elastic.co/s/zzdvecxascups

**Repro line**:

```
./gradlew ':x-pack:plugin:sql:qa:server:single-node:integTest' --tests "org.elasticsearch.xpack.sql.qa.single_node.FieldExtractorIT.testGeoShapeField" -Dtests.seed=FB92A77C2DBE6030 -Dtests.security.manager=true -Dtests.locale=sq -Dtests.timezone=Asia/Choibalsan -Druntime.java=11
```

**Reproduces locally?**: yes

**Applicable branches**: master, possibly 7.x once the change below is backported

**Failure history**: this recently started failing, we suspect it's related to this PR: https://github.com/elastic/elasticsearch/pull/68738

**Failure excerpt**:
```
org.elasticsearch.common.xcontent.XContentParseException: [1:31] [geojson] failed to parse field [coordinates]
org.elasticsearch.common.xcontent.ObjectParser.parseValue(ObjectParser.java:535)
org.elasticsearch.common.xcontent.ObjectParser.parseSub(ObjectParser.java:581)
org.elasticsearch.common.xcontent.ObjectParser.parse(ObjectParser.java:320)
org.elasticsearch.common.xcontent.ConstructingObjectParser.parse(ConstructingObjectParser.java:166)
org.elasticsearch.common.xcontent.ConstructingObjectParser.apply(ConstructingObjectParser.java:158)
org.elasticsearch.common.geo.GeoJson.fromXContent(GeoJson.java:72)
org.elasticsearch.common.geo.GeoJsonGeometryFormat.fromXContent(GeoJsonGeometryFormat.java:37)
org.elasticsearch.common.geo.GeoJsonGeometryFormat.fromXContent(GeoJsonGeometryFormat.java:18)
org.elasticsearch.common.geo.GeometryParser.parse(GeometryParser.java:50)
org.elasticsearch.xpack.sql.expression.literal.geo.GeoShape.parse(GeoShape.java:228)
org.elasticsearch.xpack.sql.expression.literal.geo.GeoShape.<init>(GeoShape.java:67)
org.elasticsearch.xpack.sql.execution.search.extractor.FieldHitExtractor.unwrapCustomValue(FieldHitExtractor.java:108)
```

### PR DESCRIPTION
**Pull request by romseygeek**
The ValueFetcher for `geo_shape` will shortcut the validation of its
source value if it detects that the source format and the requested
format are the same.  This worked fine when malformed values were
dealt with by checking the `_ignored` metadata, but since #68738 
we need to always validate source values at fetch time.

This commit removes this special shortcut logic, and adds tests
to check that `geo_shape` value fetchers do not return malformed
source inputs.

Fixes #69071

### CODE REVIEW

**Comment by romseygeek** [comment]
Marked as `>non-issue` because it's an unreleased bug.  More interesting is why #69071 wasn't caught by CI on #68738 in the first place.

**Comment by romseygeek** [comment]
@elasticmachine update branch

File: server/src/test/java/org/elasticsearch/index/mapper/GeoShapeFieldTypeTests.java [hunk 1]
```diff
@@ -44,4 +45,13 @@ public void testFetchSourceValue() throws IOException {
         assertEquals(List.of(jsonLineString, jsonPoint), fetchSourceValue(mapper, sourceValue, null));
         assertEquals(List.of(wktLineString, wktPoint), fetchSourceValue(mapper, sourceValue, "wkt"));
     }
+
+    public void testFetchMalformedValue() throws IOException {
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/index/mapper/GeoShapeFieldTypeTests.java:49]: Now that we don't automatically ignore values, it's become important to test malformed values at the field type level. Would you be up for adding similar tests to the other cartesian field types like (geopoint, legacy gepoint, point, and shape?)

File: server/src/main/java/org/elasticsearch/index/mapper/AbstractGeometryFieldMapper.java [hunk 2]
```diff
@@ -72,9 +72,7 @@
         /**
          * Parses the given value, then formats it according to the 'format' string.
          *
-         * By default, this method simply parses the value using {@link Parser#parse}, then formats
-         * it with {@link Parser#format}. However some {@link Parser} implementations override this
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/mapper/AbstractGeometryFieldMapper.java:76]: It's too bad that we removed this, it's nice to avoid parsing potentially very complex shapes when not necessary. I guess we can always revisit it as a performance optimization.

**Review by jtibshirani — APPROVED** [review]
This looks good to me, just had one comment about extra tests.

File: server/src/test/java/org/elasticsearch/index/mapper/GeoShapeFieldTypeTests.java (hunk 1 above)
Comment (romseygeek) [reply server/src/test/java/org/elasticsearch/index/mapper/GeoShapeFieldTypeTests.java]: I've added these extra tests, which exposed an inconsistency in how point mappers deal with malformed values - have opened https://github.com/elastic/elasticsearch/issues/69601 to follow up.

**Comment by romseygeek** [comment]
@elasticmachine update branch
