### PR TITLE
SQL: add "format" for "full" date range queries

### LINKED ISSUE #48033: SQL: multi-conditionals on date fields with NOW() don't use the format for range queries
`SELECT hire_date FROM test_emp WHERE hire_date >= NOW() - INTERVAL 200 YEARS AND hire_date < NOW() - INTERVAL 2 YEARS`

will end up returning an error:

```
"root_cause": [
            {
                "type": "parse_exception",
                "reason": "failed to parse date field [1819-10-15T04:45:20.641Z] with format [yyyy-MM-dd' 'HH:mm:ss]: [failed to parse date field [1819-10-15T04:45:20.641Z] with format [yyyy-MM-dd' 'HH:mm:ss]]"
            }
        ]
```

The error above does also  happen only when the date format of the `hire_date` field is a custom one (non-default).
The reason for the error seems to be the lack of `format` attribute (added following [this PR](https://github.com/elastic/elasticsearch/pull/45326)) on the  `range`  ES query generated for this sql query, which should enforce the `range` query to one known format - the one of `NOW()`, `CURRENT_DATE()` functions.

### PR DESCRIPTION
**Pull request by astefan**
In case of a conjunction involving the same date field, the optimizer creates a single `range` query for that field with both `from` and `to` populated. In the specific case of date literals generated by ES SQL (NOW(), TODAY(), CURRENT_TIMESTAMP() etc) we are enforcing the date format of the `range` query so that a potentially custom format for the date field is not used by default by Elasticsearch instead.

Similar logic [here](https://github.com/elastic/elasticsearch/pull/45326)

Fixes https://github.com/elastic/elasticsearch/issues/48033.

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java [hunk 1]
```diff
@@ -821,9 +823,36 @@ protected QueryTranslation asQuery(Range r, boolean onAggs) {
                 if (onAggs) {
                     aggFilter = new AggFilter(at.id().toString(), r.asScript());
                 } else {
+                    Holder<Object> lower = new Holder<>(valueOf(r.lower()));
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java]: Why use the holder? Does the closure require a final variable?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java [hunk 2]
```diff
@@ -821,9 +823,36 @@ protected QueryTranslation asQuery(Range r, boolean onAggs) {
...
+                    Holder<Object> upper = new Holder<>(valueOf(r.upper()));
+                    Holder<String> format = new Holder<>(dateFormat(r.value()));
+
+                    // for a date constant comparison, we need to use a format for the date, to make sure that the format is the same
+                    // no matter the timezone provided by the user
+                    if (format.get() == null) {
+                        DateFormatter formatter = null;
+                        if (lower.get() instanceof ZonedDateTime || upper.get() instanceof ZonedDateTime) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java]: Is there a chance to have different formats between upper and lower? I think so so it might make sense to have two formatters in case of two different formats.

**Review by costin — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java (hunk 1 above)
Comment (astefan) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java]: @costin yes.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java (hunk 2 above)
Comment (astefan) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java]: @costing, I tried to test something that has two different formats (like `WHERE date0 > CAST(NOW() - INTERVAL 150 YEARS AS DATE) AND date0 < CAST(NOW() AS DATETIME)`) but couldn't do it. If you have any ideas I can try to break this, please let me know.

Also, we need to have one format only because that's the one to be used in the `range` query. Even if the literals themselves will, in I-don't-know-what-scenario, have two different formats, the `range` query will need only one. In case the `range` query will end up having two different formats for `from` and `to` there will be a `parse_exception` error from ES side. So, in either case, `range` will work with one format only for `format`, `from` and `to` fields (all three need to match).

Comment (astefan) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java]: @costin, I tried to test something that has two different formats (like `WHERE date0 > CAST(NOW() - INTERVAL 150 YEARS AS DATE) AND date0 < CAST(NOW() AS DATETIME)`) but couldn't do it. If you have any ideas I can try to break this, please let me know.

Also, we need to have one format only because that's the one to be used in the `range` query. Even if the literals themselves will, in I-don't-know-what-scenario, have two different formats, the `range` query will need only one. In case the `range` query will end up having two different formats for `from` and `to` there will be a `parse_exception` error from ES side. So, in either case, `range` will work with one format only for `format`, `from` and `to` fields (all three need to match).

**Review by matriv — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java]: Thanks for explaining.
