### PR TITLE
[ML] Fix check on E5 model platform compatibility

### LINKED ISSUE #113577: [CI] TextEmbeddingCrudIT testPutE5Small_withPlatformAgnosticVariant failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4213 / debian-11_platform-support-unix](https://gradle-enterprise.elastic.co/s/jc4rw26debrzq)
- [elasticsearch-periodic #4220 / openjdk17_checkpart2_java-fips-matrix](https://gradle-enterprise.elastic.co/s/v27prafhdysz6)

**Reproduction Line:**
```
./gradlew ':x-pack:plugin:inference:qa:inference-service-tests:javaRestTest' --tests "org.elasticsearch.xpack.inference.TextEmbeddingCrudIT.testPutE5Small_withPlatformAgnosticVariant" -Dtests.seed=AF82615F80809A60 -Dtests.locale=ar-OM -Dtests.timezone=Mexico/General -Druntime.java=22
```

**Applicable branches:**
8.15

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testPutE5Small_withPlatformAgnosticVariant'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.inference.TextEmbeddingCrudIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [PUT], host [http://[::1]:43373], URI [_inference/text_embedding/voohhzrmgh], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"status_exception","reason":"Model importing failed due to an Exception [java.lang.IllegalArgumentException: [definition_length] must be greater than 0]"}],"type":"status_exception","reason":"Model importing failed due to an Exception [java.lang.IllegalArgumentException: [definition_length] must be greater than 0]","caused_by":{"type":"illegal_argument_exception","reason":"[definition_length] must be greater than 0"}},"status":500}
```

**Issue Reasons:**
- [8.15] 2 failures in test testPutE5Small_withPlatformAgnosticVariant (1.2% fail rate in 170 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by davidkyle**
Creating an endpoint for the built in multilingual e5 model was failing for linux optimised version due to an error in the logic that check the model variant is compatible with the cluster architecture. 

```
POST _inference/text_embedding/my-e5
{
  "service": "text_embedding",
  "service_settings": {
    "num_allocations": 1,
    "num_threads": 1,
    "model_id": ".multilingual-e5-small_linux-x86_64"
  }
}

Error parsing request config, model id does not match any models available on this platform ...
```

closes #113577 #113565

### CODE REVIEW

File: x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/TextEmbeddingCrudIT.java [hunk 1]
```diff
@@ -19,10 +19,9 @@
 
 import static org.hamcrest.Matchers.containsString;
 
-// Tests disabled in CI due to the models being too large to download. Can be enabled (commented out) for local testing
-@LuceneTestCase.AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/105198")
```
Comment (davidkyle) [inline x-pack/plugin/inference/qa/inference-service-tests/src/javaRestTest/java/org/elasticsearch/xpack/inference/TextEmbeddingCrudIT.java:23]: I unmuted the suite and muted individual tests except `testPutE5Small_withPlatformSpecificVariant()` which covers the fix.

**Review by maxhniebergall — APPROVED** [review]
LGTM, nice fix

**Comment by davidkyle** [comment]
@elasticmachine test this please
