### PR TITLE
Resolving wildcard application names without prefix query

### LINKED ISSUE #96465: search.allow_expensive_queries + wildcard application privs can fail authorization
### Elasticsearch Version

Tested against 8.6.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Ubuntu

### Problem Description

When `search.allow_expensive_queries` is set to `false` some queries may fail since they are considered expensive. Typically there is an obvious connection between the action you are performing and any errors raised due to expensive queries. For example, if you explicitly issue a [prefix query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-query.html) and  `search.allow_expensive_queries` is set to `false` there is a natural correlation between your request and the error. 

It has been found that when the following conditions are met 

* The API key or role has application level privileges
* One of the application level privileges has a trailing wildcard in the application name (i.e. `myapp*`) 
* The API key or role  is not cached 

then authentication will fail due to an error [1] related to the expensive query. This because internally the code issues a prefix query to for the application name. The end result is the API key can longer be used for authentication for any action. 

Workaround include : 
* set `search.allow_expensive_queries` is set to `true`
* remove the `*` from the application privilege name

It is also possible to set  `search.allow_expensive_queries` to  `true` make a call with the API key or user with the role so that it gets cached, then set `search.allow_expensive_queries` back to `false` . That will cause the API key or role to be cached, and it will work after that, but it can also start to fail again at what would seem a random time if ever evicted from the cache or the node gets restarted. For this reason, that work around is not suggested. 

[1] Example exception. Note - other similar exceptions can occur but they all reference `search.allow_expensive_queries` and the `.security-*` index 
```
Caused by: [.security-7/9mbNjDCNRzSzrDtj2YEeKQ] org.elasticsearch.index.query.QueryShardException: failed to create query: [prefix] queries cannot be executed when 'search.allow_expensive_queries' is set to false. For optimised prefix queries on text fields please enable [index_prefixes].
	at org.elasticsearch.index.query.SearchExecutionContext.toQuery(SearchExecutionContext.java:548)
	at org.elasticsearch.index.query.SearchExecutionContext.toQuery(SearchExecutionContext.java:531)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:1174)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:986)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:630)
	at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$2(SearchService.java:495)
	at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:50)
	at org.elasticsearch.action.ActionRunnable$2.accept(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:72)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.run(Thread.java:1589)
```

### Steps to Reproduce

```
PUT _cluster/settings
{
    "persistent": {
        "search.allow_expensive_queries": "false"
    }
}

POST _security/api_key
{
  "name": "my_api_key",
  "role_descriptors": {
    "role1": {
      "cluster": ["all"],
      "indices": [
        {
          "names": ["test"],
          "privileges": ["write"]
        }
      ],
      "applications": [
        {
          "application": "app*",
          "privileges": ["read", "write"],
          "resources": ["*"]
        }
      ]
    }
  },
  "expiration": "1d"
}

using API key just created...

POST _bulk 
{ "index" : { "_index" : "test", "_id" : "4" } }
{ "field1" : "value1" }

```

EDIT: Updated text to suggest this can happen with an API key or a custom role

### PR DESCRIPTION
**Pull request by ywangd**
For application privileges, today we use prefix query to resolve application names with trailing wildcard. However, prefix query is considered to be expensive and can be disabled if the cluster setting search.allow_expensive_queries is set to false. When that happens it breaks authorization in a surprising way.

This PR adds conditional logic to fallback to in-memory filtering for application names when expensive queries are disabled. It is not less expensive. But it avoids the surprising breakage.

Resolves: #96465

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativePrivilegeStore.java [hunk 1]
```diff
@@ -234,26 +246,43 @@ private static QueryBuilder getApplicationNameQuery(Collection<String> applicati
...
+            }
+            for (String wildcard : wildcardNames) {
+                final String prefix = wildcard.substring(0, wildcard.length() - 1);
+                boolQuery.should(QueryBuilders.prefixQuery(APPLICATION.getPreferredName(), prefix));
+            }
+            boolQuery.minimumShouldMatch(1);
+            return new Tuple<>(boolQuery, null);
+        } else {
+            logger.trace("expensive queries are not allowed, switching to filtering application names in memory");
+            return new Tuple<>(QueryBuilders.existsQuery(APPLICATION.getPreferredName()), StringMatcher.of(applications));
```
Comment (jakelandis) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativePrivilegeStore.java:265]: In the current implementation , I am pretty sure this is equivalent to a match all query since (for this doc type) that field will always exist. I think it would be more efficient to just do match all here and rely on the filter to provide all application privileges. 

However,  the in-memory post filtering (regardless of exists or match all query) is not ideal. Instead of post filtering it should be possible to configure the mappings to keep the keyword , but also add the index_prefix [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-prefixes.html) or use [edge ngrams](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenizer.html). I think if we introduce this now we can handle the limitations passively. 

For example, we could introduce index_prefix mapping and (when there is a trailing *)  if the prefix is less than 20 we always query against the index_prefix else if greater than 20 (max size for index_prefix) we fallback to the prefix query...unless expensive queries are disabled , in that case (greater than 20 with trailing * and no expensive queries) we fail with a message stating they need to make the application name shorter or enable expensive queries - that is passive since that failure condition (this bug) already exists today.  I think it would be exceptionally rare to hit the conditions to trigger the bug... so it would only be a partial fix to the bug that only fixes the bug when the application name is less than 20 characters. I think that is good enough, and the change would mostly remove the need to do expensive queries and introduce a meaningful and actionable error message.

Comment (ywangd) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativePrivilegeStore.java]: > In the current implementation , I am pretty sure this is equivalent to a match all query since (for this doc type) that field will always exist. I think it would be more efficient to just do match all here and rely on the filter to provide all application privileges.

Yes, a match-all query should do the job. This was a copy/paste from existing code without too much thinking. Now if we take one step further, we can just return null here since no further limiting query is needed since the caller already has the filter query (by doc type).

> we could introduce index_prefix mapping and (when there is a trailing *) if the prefix is less than 20 we always query against the index_prefix else if greater than 20 

This could be a good solution for a new index. But it does not help existing deployments with existing data. So I think it is not really viable here.

Comment (jakelandis) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativePrivilegeStore.java]: >  But it does not help existing deployments with existing data. So I think it is not really viable here.

Hmm... this highlights a bigger problem that we don't have a strategy for mappings updates (even passive additions) outside of a major versions bumps. Technically what i describe is possible (with inplace mapping updates + fallback queries or a new index), but without that strategy/code support I agree it is not really viable. I think we should work towards defining that strategy but that is well beyond the scope of this PR. 

> we can just return null here since no further limiting query is needed

++

**Review by jakelandis — APPROVED** [review]
LGTM (and nice job on the tests!)

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativePrivilegeStore.java (hunk 1 above)
Comment (ywangd) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/NativePrivilegeStore.java]: Thanks for the comment. I wrote my previous comment in a hurry. So please let me explain myself a bit more.

We have limited support for mappings update. It is possible to [add new fields](https://github.com/elastic/elasticsearch/pull/82700/files#diff-debc2ea327ce1c4830bf0b06da8c2175e1ea03fa42a38e765f6f456f6e2baa00) to the mappings. These new fields will have `null` values for existing documents, i.e. there is no automatic process to populate the new fields for existing documents. We also cannot update existing fields. 

For the case here, we cannot update existing `application` field because (1) it is just not updatable (2) it is a `keyword` field while `_index_prefixes` requires `text`. So we will have to add a new field which would incur rather big overhead including both indexing and querying side changes. Also because this new field will not be populated for existing documents, we need to handle it in code to conditionally query the new field, if no result (this check could be tricky on its own), then fallback. It is not impossible. But the complexity does not feel right for this particular issue. In addition, being able to use expensive queries internally is a recurring ask. So a simpler solution seems to be more suitable because once internal expensive query usage is no longer an issue we can easily remove the workaround.

> I think we should work towards defining that strategy

I agree. It would be great if we could update existing field's mapping. Or if not, at least being able to populate fields (new or existing) for existing documents. Lack of this process has been causing frictions for a while. A recent occurrence is about the API key's `type` field which is an existing field but was never used till the recent cross-cluster API key work. It is now a bit of pain to support query this field because we want to fetch API keys with both `null` and `rest` types when user asks for `rest`. You can refer to ES-5990 if interested in details.
