### PR TITLE
Make slop optional when parsing `span_near` query

### LINKED ISSUE #25642: Make slop optional in span near query
The documentation for the [span near query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-span-near-query.html) suggests that `slop` is optional. 
But if `slop` is not included, an error is returned:

```
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "span_near must include [slop]",
        "line": 18,
        "col": 5
      }
    ],
    "type": "parsing_exception",
    "reason": "span_near must include [slop]",
    "line": 18,
    "col": 5
  },
```

Lucene's `org.apache.lucene.search.spans.SpanNearQuery` defaults `slop` to 0.

It seems that either `slop` should be in fact optional (i.e. it can be omitted) or should be defaulted or the docs should be changed to make it a required value.

### PR DESCRIPTION
**Pull request by cbuescher**
The slop parameter defaults to 0 in the Lucene SpanNearQuery, so we can set it
to this default value also and don't have to require it being specified in the
query when using the Rest API. Leaving `slop` a ctro arg in the Java API as it
should normally be specified and we can keep it `final` that way.

Closes #25642

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/query/SpanNearQueryBuilder.java [hunk 1]
```diff
@@ -145,8 +147,8 @@ protected void doXContent(XContentBuilder builder, Params params) throws IOExcep
 
     public static SpanNearQueryBuilder fromXContent(XContentParser parser) throws IOException {
         float boost = AbstractQueryBuilder.DEFAULT_BOOST;
-        Integer slop = null;
-        boolean inOrder = SpanNearQueryBuilder.DEFAULT_IN_ORDER;
+        int slop = DEFAULT_SLOP;
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/SpanNearQueryBuilder.java]: given that it's an int, we wouldn't even need a specific default value but I guess you prefer it so we have an explicit constant ?

**Review by javanna — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
Shall we make it explicit in the docs that the default is now `0`?

File: core/src/main/java/org/elasticsearch/index/query/SpanNearQueryBuilder.java (hunk 1 above)
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/index/query/SpanNearQueryBuilder.java]: That was the idea, to have it explicit somewhere.

**Comment by cbuescher** [comment]
@javanna thanks for the review, I wouldn't mention the default in the docs since its usually safe to assume a value is 0 if not set.
