### PR TITLE
Factor out filling of TopDocs in SearchPhaseController

### LINKED ISSUE #19356: Build Failure: org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT.testRandomDirectoryIOExceptions
I was unable to reproduce these so far, happened twice in recent test runs:

```
gradle :core:integTest -Dtests.seed=1FFB9F0D780D57E7 -Dtests.class=org.elasticsearch.search.basic.SearchWithRandomIOExceptionsIT -Dtests.method="testRandomDirectoryIOExceptions" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=fr-CA -Dtests.timezone=Asia/Baku
```

Most of the exceptions in the log are expected, hard to spot the real cause, one of the two failures looks as if a thread is lingering around, the other one shows an uncaught exception for a set of lucene files.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/1062/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/1489/console

### LINKED ISSUE #23357: NPE in Lucene TopDocs from the SearchPhaseController
The test `org.elasticsearch.index.reindex.ReindexFailureTests testResponseOnSearchFailure` has been failing for 2 days (from Feb 23 to the day this issue was opened).  This has been failing on CI but I have not been able to reproduce it locally.  Example CI output from the failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/646/console

The issue is that `org.apache.lucene.search.TopDocs$MergeSortQueue.<init>(TopDocs.java:128)` throws a NPE, presumably because `shardHits` is null.  The stack trace shows that the calls are initialized from `SearchPhaseController:L265`.  However, the `shardTopDocs` is most certainly initialized and non-null when passed into the `TopDocs.merge` call, so its quite puzzling as to what is happening.

### PR DESCRIPTION
**Pull request by s1monw**
Previously this code was duplicated across the 3 different topdocs variants
we have. It also had no real unittest (where we tested with holes in the results)
which caused a sneaky bug where the comparison used `result.size()` vs `results.size()`
causing several NPEs downstream. This change adds a static method to fill the top docs
that is shared across all variants and adds a unittest that would have caught the issue
very quickly.

Closes #19356
Closes #23357

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java [hunk 1]
```diff
@@ -314,6 +288,21 @@ private static long optionalSum(long left, long right) {
         return scoreDocs;
     }
 
+    static <T extends TopDocs> void fillTopDocs(T[] shardTopDocs,
+                                                        List<? extends AtomicArray.Entry<? extends QuerySearchResultProvider>> results,
+                                                        Supplier<T> emptySupplier) {
+        if (results.size() != shardTopDocs.length) {
+            // TopDocs#merge can't deal with null shard TopDocs
+            final T empty = emptySupplier.get();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java]: the supplier seems to be only useful to save one object allocation, maybe getting rid of it would make things simpler?

**Review by jpountz — APPROVED** [review]
LGTM

File: core/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java (hunk 1 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java]: true! I fixed it

**Review by jpountz — APPROVED** [review]
LGTM
