### PR TITLE
SQL: Scripting support for casting functions CAST and CONVERT

### LINKED ISSUE #36061: SQL: Error in painless script generation for complex string functions
```
SELECT {fn CONVERT({fn CONCAT({fn LTRIM({fn CONVERT(emp_no, SQL_VARCHAR)})}, {fn LTRIM({fn CONVERT(languages, SQL_VARCHAR)})})}, SQL_BIGINT)} AS "TEMP"
FROM test_emp
GROUP BY 1;
```
throws:
```
Caused by: ScriptException[runtime error]; nested: NotSerializableExceptionWrapper[class_cast_exception: class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')];
	at org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:94)
	at org.elasticsearch.painless.PainlessScript$Script.execute(InternalSqlScriptUtils.concat(InternalSqlScriptUtils.ltrim(InternalSqlScriptUtils.docValue(doc,params.v0)),InternalSqlScriptUtils.ltrim(InternalSqlScriptUtils.docValue(doc,params.v1))):23)
	at org.elasticsearch.search.aggregations.support.values.ScriptLongValues.advanceExact(ScriptLongValues.java:51)
	at org.elasticsearch.search.aggregations.bucket.composite.LongValuesSource$1.collect(LongValuesSource.java:156)
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82)
	at org.elasticsearch.search.aggregations.bucket.composite.CompositeAggregator$1.collect(CompositeAggregator.java:177)
	at org.elasticsearch.search.aggregations.LeafBucketCollector.collect(LeafBucketCollector.java:82)
	at org.apache.lucene.search.MatchAllDocsQuery$1$1.score(MatchAllDocsQuery.java:62)
	at org.elasticsearch.search.internal.CancellableBulkScorer.score(CancellableBulkScorer.java:56)
	at org.apache.lucene.search.BulkScorer.score(BulkScorer.java:39)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:652)
	at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:177)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:443)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:277)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:115)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:334)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:381)
	at org.elasticsearch.search.SearchService.access$100(SearchService.java:123)
	at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:343)
```

### PR DESCRIPTION
**Pull request by astefan**
This PR fixes https://github.com/elastic/elasticsearch/issues/36061. Up until this point, there was no scripting support for CAST and CONVERT and, as such, CAST and CONVERT cannot be used in GROUP BY and ORDER BY expressions (where Painless scripting is used).

### CODE REVIEW

**Comment by astefan** [comment]
run the gradle build tests 2

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/whitelist/InternalSqlScriptUtils.java [hunk 1]
```diff
@@ -458,4 +459,15 @@ public static String substring(String s, Number start, Number length) {
     public static String ucase(String s) {
         return (String) StringOperation.UCASE.apply(s);
     }
+    
+    //
+    // Casting
+    //
+    public static Object convert(Object value, String typeName) {
+        if (value == null) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/whitelist/InternalSqlScriptUtils.java]: I think it's unnecessary, it's done internally in `convert()`

File: x-pack/plugin/sql/src/main/resources/org/elasticsearch/xpack/sql/plugin/sql_whitelist.txt [hunk 2]
```diff
@@ -130,4 +130,9 @@ class org.elasticsearch.xpack.sql.expression.function.scalar.whitelist.InternalS
   String  space(Number)
   String  substring(String, Number, Number)
   String  ucase(String)
+  
+#
+# Casting
+#
+  def convert(Object, String)
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/resources/org/elasticsearch/xpack/sql/plugin/sql_whitelist.txt]: I have a slight preference to name it `cast` which is the main name for SQL, but convert is also good.

**Review by matriv — APPROVED** [review]
LGTM! Left a couple of comments, and also can we have an integ test with the cast used also in the HAVING?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/Cast.java [hunk 3]
```diff
@@ -74,6 +78,18 @@ protected Processor makeProcessor() {
         return new CastProcessor(DataTypeConversion.conversionFor(from(), to()));
     }
 
+    @Override
+    public ScriptTemplate asScript() {
+        ScriptTemplate fieldAsScript = asScript(field());
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/Cast.java]: Since the solution is to use a slightly different script, simply override `processScript` (see its implementations for examples like `MathFunction`). This way you only need to define the string and not worry about the boiler-plate around passing the script further.

File: x-pack/plugin/sql/src/main/resources/org/elasticsearch/xpack/sql/plugin/sql_whitelist.txt (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/resources/org/elasticsearch/xpack/sql/plugin/sql_whitelist.txt]: +1 on cast for me as well.

**Review by costin — APPROVED** [review]
LGTM with the implementation moving over to `processScript` instead.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/Cast.java (hunk 3 above)
Comment (astefan) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/function/scalar/Cast.java]: With `processScript` we cannot set the dataType as parameter and we are forced to send it as String inline. Will leave it as is at the moment, as discussed.

**Comment by astefan** [comment]
@matriv when using HAVING I get the same error as the one [here](https://github.com/elastic/elasticsearch/issues/36060) (with `CAST`) and the one [here](https://github.com/elastic/elasticsearch/issues/36056) (if I use `CONVERT`). Looking into it a bit - the Painless script seems incomplete, but if I add the casting part (which is missing) the error is still there unchanged.

**Comment by matriv** [comment]
@astefan then let's go ahead and merge this and check afterwards the HAVING case.

**Comment by pcsanwald** [comment]
closes #34557
