### PR TITLE
Fix potential file leak in ES816BinaryQuantizedVectorsWriter

### LINKED ISSUE #119981: [CI] ES816HnswBinaryQuantizedVectorsFormatTests testRandomExceptions failing
**Build Scans:**
- [elasticsearch-intake #15610 / part1](https://gradle-enterprise.elastic.co/s/5yx5zwkgvytrq)
- [elasticsearch-intake #15327 / part1](https://gradle-enterprise.elastic.co/s/mruuyo4ywrvi2)

**Reproduction Line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.codec.vectors.es816.ES816HnswBinaryQuantizedVectorsFormatTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRandomExceptions),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.RuntimeException: MockDirectoryWrapper: cannot close: there are still 1 open files: {_h_ES816HnswBinaryQuantizedVectorsFormat_0.veb_temp_w.tmp=1}
```

**Issue Reasons:**
- [main] 2 failures in test testRandomExceptions (0.3% fail rate in 778 executions)
- [main] 2 failures in step part1 (1.4% fail rate in 138 executions)
- [main] 2 failures in pipeline elasticsearch-intake (1.4% fail rate in 138 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by iverase**
We are creating tmp files that might not get closed if an exception happens just after it. This PR makes sure all errors are handle properly and files are getting closed and deleted.

fixes https://github.com/elastic/elasticsearch/issues/119981

### CODE REVIEW

**Review by carlosdelest — APPROVED** [review]

File: server/src/test/java/org/elasticsearch/index/codec/vectors/es816/ES816BinaryQuantizedVectorsWriter.java [hunk 1]
```diff
@@ -513,12 +516,20 @@ private CloseableRandomVectorScorerSupplier mergeOneFieldToIndex(
...
+            final IndexOutput finalTempQuantizedVectorData = tempQuantizedVectorData;
+            final IndexOutput finalTempScoreQuantizedVectorData = tempScoreQuantizedVectorData;
+            success = true;
             return new BinarizedCloseableRandomVectorScorerSupplier(scorerSupplier, vectorValues, () -> {
-                IOUtils.close(finalBinarizedDataInput, finalBinarizedScoreDataInput);
+                IOUtils.close(
+                    finalBinarizedDataInput,
+                    finalBinarizedScoreDataInput,
+                    finalTempQuantizedVectorData,
+                    finalTempScoreQuantizedVectorData
```
Comment (benwtrent) [inline server/src/test/java/org/elasticsearch/index/codec/vectors/es816/ES816BinaryQuantizedVectorsWriter.java:527]: These are closed higher up in the function, but closing them twice is probably ok.

**Review by benwtrent — APPROVED** [review]

File: server/src/test/java/org/elasticsearch/index/codec/vectors/es816/ES816BinaryQuantizedVectorsWriter.java (hunk 1 above)
Comment (iverase) [reply server/src/test/java/org/elasticsearch/index/codec/vectors/es816/ES816BinaryQuantizedVectorsWriter.java:527]: ops, I didn't realize. Let's fix it so we don't close it twice.

**Comment by iverase** [comment]
Ok, I rework it so we don't close twice the same file.
