### PR TITLE
Fix match_only_text for keyword multi-fields with ignore_above

### LINKED ISSUE #131298: NPE on search query phase Cannot invoke "java.util.List.iterator()" because "values" is null
### Elasticsearch Version

current

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

```
Failed to execute phase [query], all shards failed; shardFailures {[or5c1cU6SdGr5z05b_4X8w][.ds-logs-kubernetes.container_logs-default-2025.07.15-000001][0]: org.elasticsearch.transport.RemoteTransportException: [es-es-search-6cf9c9cc7f-cxvmg][100.66.94.112:9300][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "values" is null
}
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:624)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.search.SearchQueryThenFetchAsyncAction.onPhaseFailure(SearchQueryThenFetchAsyncAction.java:81)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:326)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:669)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.finishOneShard(AbstractSearchAsyncAction.java:430)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:422)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:279)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:89)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:598)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1727)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1507)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1641)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1616)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:44)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:45)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.search.SearchService.lambda$wrapListenerForErrorHandling$4(SearchService.java:627)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:202)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:78)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:207)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:152)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:29)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: org.elasticsearch.ElasticsearchException$1: Cannot invoke "java.util.List.iterator()" because "values" is null
	at org.elasticsearch.server@9.2.0/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:798)
	at org.elasticsearch.server@9.2.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:324)
	... 27 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "values" is null
```

### Steps to Reproduce

Not availale

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jordan-powers**
In #129126, we stopped double-storing match_only_text fields when they are part of a multi-field, instead extracting the value when needed from the appropriate multi-field mapper.

This introduced an edge case related to ignore_above on keyword fields. If the associated multi-field mapper is a keyword mapper, and if that keyword mapper has ignore_above specified, and a document triggers the ignore_above case, then the original value will be stored in `<foo>._original` instead of `<foo>`. In this case, the match_only_text mapper needs to look at the `<foo>._original` stored field.

Resolves #131298

### CODE REVIEW

File: modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/MatchOnlyTextFieldMapper.java [hunk 1]
```diff
@@ -252,6 +254,10 @@ private IOFunction<LeafReaderContext, CheckedIntFunction<List<Object>, IOExcepti
                 String parentField = searchExecutionContext.parentPath(name());
                 var parent = searchExecutionContext.lookup().fieldType(parentField);
                 if (parent.isStored()) {
+                    if (parent instanceof KeywordFieldMapper.KeywordFieldType keywordParent
+                        && keywordParent.ignoreAbove() != Integer.MAX_VALUE) {
+                        return storedFieldFetcher(parentField, keywordParent.originalName());
+                    }
                     return storedFieldFetcher(parentField);
                 } else if (parent.hasDocValues()) {
                     var ifd = searchExecutionContext.getForField(parent, MappedFieldType.FielddataOperation.SEARCH);
```
Comment (lkts) [inline modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/MatchOnlyTextFieldMapper.java:263]: It seems like there can be a similar problem here because doc values won't include ignored values? Not sure if that matters though.

**Review by lkts — APPROVED** [review]

File: modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/MatchOnlyTextFieldMapper.java (hunk 1 above)
Comment (jordan-powers) [reply modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/MatchOnlyTextFieldMapper.java:263]: Shoot you're right. If the keyword field is `store: false, doc_values: true`, we don't error, but we completely omit the value from the match_only_text field results.

I'll work on a follow-up PR to address this.

**Review by parkertimmins — APPROVED** [review]

**Comment by jordan-powers** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/131338)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

File: modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/MatchOnlyTextFieldMapper.java [hunk 2]
```diff
@@ -252,6 +254,10 @@ private IOFunction<LeafReaderContext, CheckedIntFunction<List<Object>, IOExcepti
                 String parentField = searchExecutionContext.parentPath(name());
                 var parent = searchExecutionContext.lookup().fieldType(parentField);
                 if (parent.isStored()) {
+                    if (parent instanceof KeywordFieldMapper.KeywordFieldType keywordParent
+                        && keywordParent.ignoreAbove() != Integer.MAX_VALUE) {
```
Comment (kkrik-es) [inline modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/MatchOnlyTextFieldMapper.java:258]: This is only used when the field length exceeds the `ignore_above` settings, I think.. Lemme see if I can write a test to make this fail.

Comment (kkrik-es) [reply modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/MatchOnlyTextFieldMapper.java:258]: I see, the fetcher checks for both to play it safe.. That works.

File: modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/MatchOnlyTextFieldMapper.java [hunk 3]
```diff
@@ -312,13 +322,17 @@ private static IOFunction<LeafReaderContext, CheckedIntFunction<List<Object>, IO
...
             return context -> {
                 var leafLoader = loader.getLoader(context, null);
                 return docId -> {
                     leafLoader.advanceTo(docId);
-                    return leafLoader.storedFields().get(name);
+                    var storedFields = leafLoader.storedFields();
+                    if (names.length == 1) {
+                        return storedFields.get(names[0]);
+                    }
+                    return Arrays.stream(names).map(storedFields::get).filter(Objects::nonNull).flatMap(List::stream).toList();
```
Comment (kkrik-es) [inline modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/MatchOnlyTextFieldMapper.java:335]: Nit: streams are not very efficient, it's better to avoid them for code that runs per document.
