### PR TITLE
Fix autoexpand during node replace

### LINKED ISSUE #89527: Shutdown replace contracts auto-expand replicas
### Elasticsearch Version

7.17.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

ESS

### Problem Description

Shutdown with mode REPLACE will move all shards from the node being replaced (source) to a new node (target node).

However, it also affects auto-expand replicas. Today, it will contract the auto-expand replicas by considering them to not expand to neither the source nor the target node. This is wrong, instead the source/target pair should be considered one node.

The REPLACE indication is expected to be added prior to starting the new target node (but we should be lenient towards it appearing later). This adds a bit of complexity to how to handle auto-expand replicas. I propose to:

1. disregard a shutdown for REPLACE record when there is no corresponding target node.
2. not expand to the source node when the target node is present.

We discussed this topic during original implementation [here](https://github.com/elastic/elasticsearch/pull/76247#discussion_r695529067) as well. The problem with the current implementation is that we risk reducing the number of replicas to 0 during a shutdown for REPLACE, potentially putting data at risk.

### Steps to Reproduce

N/A

### Logs (if relevant)

```
...  updating number_of_replicas to [0] for indices [ ...
```

### PR DESCRIPTION
**Pull request by idegtiarenko**
Prior to this change NodeReplacementAllocationDecider was unconditionally
skipping both replacement source and target nodes when calculation auto-expand
replicas. This is fixed by autoexpanding to the replacement node if source node
already had shards of the index.

Closes: #89527

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java [hunk 1]
```diff
@@ -40,8 +40,8 @@ public Decision canAllocate(ShardRouting shardRouting, RoutingNode node, Routing
                 Decision.Type.YES,
                 NAME,
                 "node [%s] is replacing node [%s], and may receive shards from it",
-                shardRouting.currentNodeId(),
-                node.nodeId()
+                node.nodeId(),
+                shardRouting.currentNodeId()
```
Comment (idegtiarenko) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java:44]: The order was flipped

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDeciderTests.java [hunk 2]
```diff
@@ -63,14 +63,6 @@ public class NodeReplacementAllocationDeciderTests extends ESAllocationTestCase
...
         )
     );
-    private final AllocationService service = new AllocationService(
-        allocationDeciders,
-        new TestGatewayAllocator(),
-        new BalancedShardsAllocator(Settings.EMPTY),
-        EmptyClusterInfoService.INSTANCE,
-        EmptySnapshotsInfoService.INSTANCE,
-        TestShardRoutingRoleStrategies.DEFAULT_ROLE_ONLY
-    );
```
Comment (idegtiarenko) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDeciderTests.java:73]: This was unused test setup, removed in a separate commit to make it easier to review

**Review by henningandersen — CHANGES_REQUESTED** [review]
Thanks for working on this. I left some comments to address.

**Comment by idegtiarenko** [comment]
@elasticsearchmachine please run elasticsearch-ci/bwc

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java [hunk 3]
```diff
@@ -110,27 +110,64 @@ public Decision shouldAutoExpandToNode(IndexMetadata indexMetadata, DiscoveryNod
...
+            final String sourceNodeId = shutdown != null ? shutdown.getNodeId() : null;
+            final boolean hasShardsAllocatedOnSourceOrTarget = hasShardOnNode(indexMetadata, node.getId(), allocation)
+                || (sourceNodeId != null && hasShardOnNode(indexMetadata, sourceNodeId, allocation));
+
+            if (hasShardsAllocatedOnSourceOrTarget) {
+                return allocation.decision(
+                    Decision.YES,
+                    NAME,
+                    "node [%s] is a node replacement target for node [%s], "
+                        + "shards can auto expand to it as they were already present of the source node",
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java:122]:
```suggestion
                        + "shard can auto expand to it as it was already present on the source node",
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java [hunk 4]
```diff
@@ -110,27 +110,64 @@ public Decision shouldAutoExpandToNode(IndexMetadata indexMetadata, DiscoveryNod
...
-            return allocation.decision(
-                Decision.NO,
-                NAME,
-                "node [%s] is being replaced by [%s], shards cannot auto expand to be on it",
-                node.getId(),
-                getReplacementName(allocation, node.getId())
-            );
+            final SingleNodeShutdownMetadata shutdown = allocation.getClusterState().metadata().nodeShutdowns().get(node.getId());
+            final String replacementNodeName = shutdown != null ? shutdown.getTargetNodeName() : null;
+            final boolean hasShardThatCanNotMigrate = hasShardOnNode(indexMetadata, node.getId(), allocation)
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java:139]: I think a better name is following, the "cannot migrate" seems unimportant.

```suggestion
            final boolean hasShardOnSource = hasShardOnNode(indexMetadata, node.getId(), allocation)
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java [hunk 5]
```diff
@@ -110,27 +110,64 @@ public Decision shouldAutoExpandToNode(IndexMetadata indexMetadata, DiscoveryNod
...
+                && shutdown != null
+                && allocation.getClusterState().getNodes().findByName(shutdown.getTargetNodeName()) == null;
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java:141]: nit:
```suggestion
                && allocation.getClusterState().getNodes().findByName(replacementNodeName) == null;
```

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java [hunk 6]
```diff
@@ -110,27 +110,64 @@ public Decision shouldAutoExpandToNode(IndexMetadata indexMetadata, DiscoveryNod
...
+
+            if (hasShardThatCanNotMigrate) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java:143]: Can we add a bit of javadoc explaining the auto-expand replicas mechanism, I suggest at class level.

File: server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodes.java [hunk 7]
```diff
@@ -298,6 +298,20 @@ public DiscoveryNode findByAddress(TransportAddress address) {
         return null;
     }
 
+    /**
+     * Get a node by its name
+     *
+     * @return node identified by the given name or <code>null</code> if no such node exists
+     */
+    public DiscoveryNode findByName(String name) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodes.java:306]: The result here relies on order of the map in case of duplicates, which seems to indicate that the usefulness of sharing the method here is smal. But we are not really concerned about the node itself, only whether it exists. I think we should instead have a method `boolean hasByName(String name)`.

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java [hunk 8]
```diff
@@ -157,43 +151,103 @@ public void testCanAutoExpandToNodeThatIsNotShuttingDown() {
...
+            Decision.Type.YES,
+            "no nodes are shutting down"
+        );
+
+        // should auto-expand when shutdown/replacement is registered and no node replacement yet
+        var shutdown = createNodesShutdownMetadata(SingleNodeShutdownMetadata.Type.REPLACE, DATA_NODE.getId());
+        state = ClusterState.builder(state)
+            .metadata(Metadata.builder(state.metadata()).putCustom(NodesShutdownMetadata.TYPE, shutdown).build())
+            .build();
+        assertThatDecision(
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:187]: Can we add a verification that a shard that is not yet on the source node cannot expand to it?

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java [hunk 9]
```diff
@@ -157,43 +151,103 @@ public void testCanAutoExpandToNodeThatIsNotShuttingDown() {
...
+            decider.shouldAutoExpandToNode(indexMetadata, DATA_NODE, createRoutingAllocation(state)),
+            Decision.Type.YES,
+            "node [" + DATA_NODE.getId() + "] is preparing to be removed from the cluster, but replacement is not yet present"
+        );
+
+        // should not auto-expand when only to replacement node when joined
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:193]: I do not understand this comment, can you make it clear?

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java [hunk 10]
```diff
@@ -157,43 +151,103 @@ public void testCanAutoExpandToNodeThatIsNotShuttingDown() {
...
+        var replacementName = shutdown.get(DATA_NODE.getId()).getTargetNodeName();
+        var replacementNode = newNode(replacementName, "node-data-1", Set.of(DiscoveryNodeRole.DATA_ROLE));
+        state = ClusterState.builder(state).nodes(DiscoveryNodes.builder(state.getNodes()).add(replacementNode).build()).build();
+
+        assertThatDecision(
+            decider.shouldAutoExpandToNode(indexMetadata, DATA_NODE, createRoutingAllocation(state)),
+            Decision.Type.NO,
+            "node [" + DATA_NODE.getId() + "] is preparing to be removed from the cluster"
+        );
+        assertThatDecision(
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:203]: Can we add a verification that a shard that is not yet on the source node cannot expand to the target node?

File: x-pack/plugin/shutdown/src/internalClusterTest/java/org/elasticsearch/xpack/shutdown/NodeShutdownShardsIT.java [hunk 11]
```diff
@@ -349,37 +349,15 @@ public void testAutoExpandDuringRestart() throws Exception {
...
-                    .indices()
-                    .prepareGetSettings("myindex")
-                    .setNames("index.number_of_replicas")
-                    .get()
-                    .getSetting("myindex", "index.number_of_replicas"),
-                equalTo("1")
-            );
-        });
         ensureGreen("myindex");
+        var assertion = new BackgroundAssertion(() -> assertIndexSetting("myindex", "index.number_of_replicas", "1"));
```
Comment (henningandersen) [inline x-pack/plugin/shutdown/src/internalClusterTest/java/org/elasticsearch/xpack/shutdown/NodeShutdownShardsIT.java:353]: Can we keep the assertions between each step instead? Does not seem like this kind of 100% cpu hog validation is needed here.

File: x-pack/plugin/shutdown/src/internalClusterTest/java/org/elasticsearch/xpack/shutdown/NodeShutdownShardsIT.java [hunk 12]
```diff
@@ -391,6 +369,33 @@ public Settings onNodeStopped(String nodeName) throws Exception {
...
+
+    public void testAutoExpandDuringReplace() throws Exception {
+
+        var node1 = internalCluster().startNode();
+        var node2 = internalCluster().startNode();
+
+        createIndex("index", indexSettings(1, 0).put("index.auto_expand_replicas", "0-1").build());
+        ensureGreen("index");
+
+        var assertion = new BackgroundAssertion(() -> assertIndexSetting("index", "index.number_of_replicas", "1"));
```
Comment (henningandersen) [inline x-pack/plugin/shutdown/src/internalClusterTest/java/org/elasticsearch/xpack/shutdown/NodeShutdownShardsIT.java:383]: Can we instead just validate in between each step. Perhaps also validate that the index is green between every step.

File: x-pack/plugin/shutdown/src/internalClusterTest/java/org/elasticsearch/xpack/shutdown/NodeShutdownShardsIT.java [hunk 13]
```diff
@@ -504,7 +509,29 @@ private void assertIndexReplicaShardsAreNotAllocated(String indexName) {
...
+        }
+
+        @Override
+        public void run() {
+            while (stopped.get() == false) {
+                assertion.run();
+            }
+        }
+
+        public void verify() {
```
Comment (henningandersen) [inline x-pack/plugin/shutdown/src/internalClusterTest/java/org/elasticsearch/xpack/shutdown/NodeShutdownShardsIT.java:533]: I suppose this should be named `stop`? I think we should remove this background thread and verify explicitly the points we are interested in.

Also, when stopping a thread it is good to `join` too - to ensure it does not affect any subsequent tests - and we do not take down the cluster while the assertion is running.

**Review by henningandersen — COMMENTED** [review]
Thanks for the additional work on this. I left a number of smaller comments and test comments.

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java (hunk 10 above)
Comment (idegtiarenko) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:203]: Do you mean that shard from any other node of the cluster cannot auto-expand to the replacement target node?
I believe it can according to the `NodeShutdownAllocationDecider`

Comment (henningandersen) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:203]: The `NodeReplacementAllocationDecider` should reject this here:

https://github.com/elastic/elasticsearch/pull/96281/files#diff-6c6bb87a8918c913f92d49ba4c9dc5973f35052f062afe45706dc3a0011b324eR153

for the case where the shard is not yet present on the node.

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java (hunk 8 above)
Comment (henningandersen) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:186]: I did not find this comment addressed?

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java (hunk 10 above)
Comment (henningandersen) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:202]: I did not find this comment addressed?

**Review by henningandersen — COMMENTED** [review]
A couple of comments from last review seems unaddressed (if not, please point me to the verifications).

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java (hunk 10 above)
Comment (idegtiarenko) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:202]: This scenario:
* put a shard on the node_c
* replace node_a -> node_b
* check shard from the node_c is not auto-expanding replicas to node_a or node_b

is verified in `org.elasticsearch.cluster.routing.allocation.decider.NodeReplacementAllocationDeciderTests#testShouldNotAutoExpandReplicasDuringUnrelatedNodeReplacement`, unless I miss something

Comment (henningandersen) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:202]: Thanks for pointing me to it.

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java (hunk 8 above)
Comment (idegtiarenko) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:186]: NodeShutdownAllocationDeciderTests only prevents allocations and auto expands on the node that is about to be shut down and do not restrict allocations on the replacement node.

A scenario `shard from any node in cluster can not be auto-expanded on removing node` is tested in: `testCannotAutoExpandToRemovingNode`
A similar one for replacing node is tested in: testAutoExpandDuringNodeReplacement. Please note no ShardRouting created as both tests do not depend on the source shard location (from NodeShutdownAllocationDecider point of view).

Comment (henningandersen) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeShutdownAllocationDeciderTests.java:186]: Sorry for the confusion, I meant this for the replace decider. See [this comment](https://github.com/elastic/elasticsearch/pull/96281/files#r1219134129).

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDeciderTests.java [hunk 14]
```diff
@@ -97,117 +97,314 @@ public void testCanForceAllocate() {
...
+
+    public void testShouldNotAutoExpandReplicasDuringUnrelatedNodeReplacement() {
+
+        var indexMetadata = IndexMetadata.builder(idxName)
+            .settings(indexSettings(Version.CURRENT, 1, 0).put(SETTING_AUTO_EXPAND_REPLICAS, "0-1"))
+            .build();
+        var shardId = new ShardId(indexMetadata.getIndex(), 0);
+
+        var state = ClusterState.builder(ClusterName.DEFAULT)
+            .nodes(DiscoveryNodes.builder().add(NODE_A).add(NODE_B).add(NODE_C).build())
```
[the remark this answers is not in the document]
Comment (idegtiarenko) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDeciderTests.java:194]: Will add :+1:

however to be clear unrelated index is not going to expand to the source node regardless if replacement is present as [hasShardOnNode(indexMetadata, node.getId(), allocation)](https://github.com/idegtiarenko/elasticsearch/blob/8eb32d99dd6d43a417565a3eb5d68ce440327570/server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDecider.java#L144) going to be false in both cases.

[the remark this answers is not in the document]
Comment (henningandersen) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/NodeReplacementAllocationDeciderTests.java]: Absolutely, I think the code works just fine (otherwise I would have added a comment there too), but the branch looks untested.

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by DaveCTurner** [comment]
Added the `v7.17.13` label because this has now been backported /cc @kingherc
