### PR TITLE
Correct how meta-field is defined for pre 7.8 hits

### LINKED ISSUE #57831: MixedClusterClientYamlTestSuiteIT search.inner_hits/10_basic/Nested doc version and seqIDs} failure
**Build scan**:
https://gradle-enterprise.elastic.co/s/6v2p4uldva7yu
https://gradle-enterprise.elastic.co/s/eoao47wh52du2
https://gradle-enterprise.elastic.co/s/cjq62yrbzidu2
**Repro line**:
```
./gradlew ':qa:mixed-cluster:v7.7.2#mixedClusterTest' --tests "org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=search.inner_hits/10_basic/Nested doc version and seqIDs}" -Dtests.seed=A8957CDE2B7769A4 -Dtests.security.manager=true -Dtests.locale=it-IT -Dtests.timezone=America/Caracas -Druntime.java=15
```
**Reproduces locally?**:
Yes
**Applicable branches**:
7.x
**Failure excerpt**:
In the response stash, I don't see a field called `hits.hits.0.fields._seq_no` anywhere (the `fields` key is missing?)
```
org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=search.inner_hits/10_basic/Nested doc version and seqIDs} FAILED
    java.lang.AssertionError: Failure at [search.inner_hits/10_basic:69]: field [hits.hits.0.fields._seq_no] is null
        at __randomizedtesting.SeedInfo.seed([A8957CDE2B7769A4:20C14304858B045C]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
        at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.base/java.lang.Thread.run(Thread.java:832)

        Caused by:
        java.lang.AssertionError: field [hits.hits.0.fields._seq_no] is null
            at org.junit.Assert.fail(Assert.java:88)
            at org.junit.Assert.assertTrue(Assert.java:41)
            at org.junit.Assert.assertNotNull(Assert.java:712)
            at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:79)
            at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:398)
            ... 36 more
```

response body
```
  1> [2020-06-08T13:41:22,243][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test] Stash dump on test failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "took" : 85,
  1>       "timed_out" : false,
  1>       "_shards" : {
  1>         "total" : 1,
  1>         "successful" : 1,
  1>         "skipped" : 0,
  1>         "failed" : 0
  1>       },
  1>       "hits" : {
  1>         "total" : 1,
  1>         "max_score" : 1.0,
  1>         "hits" : [
  1>           {
  1>             "_index" : "test",
  1>             "_type" : "_doc",
  1>             "_id" : "1",
  1>             "_version" : 2,
  1>             "_score" : 1.0,
  1>             "_seq_no" : 1,
  1>             "_source" : {
  1>               "nested_field" : [
  1>                 {
  1>                   "foo" : "baz"
  1>                 }
  1>               ]
  1>             },
  1>             "inner_hits" : {
  1>               "nested_field" : {
  1>                 "hits" : {
  1>                   "total" : 1,
  1>                   "max_score" : 1.0,
  1>                   "hits" : [
  1>                     {
  1>                       "_index" : "test",
  1>                       "_type" : "_doc",
  1>                       "_id" : "1",
  1>                       "_nested" : {
  1>                         "field" : "nested_field",
  1>                         "offset" : 0
  1>                       },
  1>                       "_version" : 2,
  1>                       "_score" : 1.0,
  1>                       "_seq_no" : 1,
  1>                       "_source" : {
  1>                         "foo" : "baz"
  1>                       }
  1>                     }
  1>                   ]
  1>                 }
  1>               }
  1>             }
  1>           }
  1>         ]
  1>       }
  1>     }
  1>   }
  1> }]
```

### PR DESCRIPTION
**Pull request by mayya-sharipova**
We keep a static list of meta-fields: META_FIELDS_BEFORE_7_8
as it was before.
This is done to ensure the backwards compatability with pre 7.8 nodes.

Relates to #57771
Closes #57831

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 1]
```diff
@@ -813,11 +818,7 @@ public void close() throws IOException {
      */
     @Deprecated
     public static boolean isMetadataFieldStatic(String fieldName) {
-        if (IndicesModule.getBuiltInMetadataFields().contains(fieldName)) {
-            return true;
-        }
-        // if a node had Size Plugin installed, _size field should also be considered a meta-field
-        return fieldName.equals("_size");
+        return META_FIELDS_BEFORE_7_8.contains(fieldName);
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:821]: If I remember correctly we only use `isMetadataFieldStatic` in a few places now where we read from older nodes. Should we simply make the collection public and remove the static method? Or rename method to something like "isMetaFieldBefore7dot8" or something, just to improve readability in the locations where this it is actually used.

**Review by cbuescher — APPROVED** [review]
LGTM, I left a minor nit, feel free to ignore

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java (hunk 1 above)
Comment (mayya-sharipova) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java]: @cbuescher Thanks for the feedback! I have removed `isMetadataFieldStatic` method, and made the collection public.

File: server/src/test/java/org/elasticsearch/index/get/DocumentFieldTests.java [hunk 2]
```diff
@@ -106,7 +106,7 @@ private static DocumentField mutateDocumentField(DocumentField documentField) {
             Predicate<String> excludeMetaFieldFilter) {
         if (isMetafield) {
             String metaField = randomValueOtherThanMany(excludeMetaFieldFilter,
-                () -> randomFrom(IndicesModule.getBuiltInMetadataFields()));
+                () -> randomFrom(MapperService.META_FIELDS_BEFORE_7DOT8));
```
Comment (cbuescher) [inline server/src/test/java/org/elasticsearch/index/get/DocumentFieldTests.java:109]: Just as a last question: why is this necessary? I though the "old" collection of meta field names is only used when reading from "old" nodes? Why can't we use all built-in fields here since we're already on master?

Comment (mayya-sharipova) [reply server/src/test/java/org/elasticsearch/index/get/DocumentFieldTests.java:109]: @cbuescher I am struggling with BWC tests here, and I am not sure about the best approach.

`SearchHitsTests.testSerializationPre6_6_0` tests was failing if we use `IndicesModule.getBuiltInMetadataFields()`.

In this test we create a test SearchHit instance in 7.x and then do wire serialization to pre6_6 node and deserialization from it, and then assert that 7.x instance is equal to the deserialized instance from 6.x.  The test was failing if we use `IndicesModule.getBuiltInMetadataFields()` and include `_fied_names` as a meta-field in the created test instance.   As now during deserialization from pre 7.8 nodes we use `META_FIELDS_BEFORE_7DOT8` to decide if a field is meta-field, we put `_field_names` under document fields, which will not be equal to the original created test instance, where `_field_names` is under meta-fields.

Probably, the best approach would be to separate how we create test instances of SearchHit between pre 7.8 nodes and after 7.8 nodes.  What do you think?

Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/index/get/DocumentFieldTests.java:109]: Are those particular tests needed on 7.x anymore? As far as I understand we'd never see a pre 6.6 node in a cluster running any 7x release at this point, 6.8 should be the last supported version? Maybe we can delete the test? I wonder if this uncovers other kinds of edge cases with the change though, so I'd prefer if we can sample "meta" fields from the "true" source (IndicesModule.getBuiltInMetadataFields()) and only fix tests where we need a specific pre-7.8 behaviour if really needed.
Mabye @javanna knows if `SearchHitsTests.testSerializationPre6_6_0` can be removed since he added it way back...

Comment (javanna) [reply server/src/test/java/org/elasticsearch/index/get/DocumentFieldTests.java:109]: https://github.com/elastic/elasticsearch/pull/36555 I guess the test (actually two tests) can be removed from 7.x given that 7.x nodes will never talk to pre 6.6 nodes.

Comment (mayya-sharipova) [reply server/src/test/java/org/elasticsearch/index/get/DocumentFieldTests.java:109]: @javanna Thanks, this would simplify things

Comment (mayya-sharipova) [reply server/src/test/java/org/elasticsearch/index/get/DocumentFieldTests.java]: @cbuescher Thanks for your suggestions. I have removed *pre6_6_0 tests, and also brought back `IndicesModule.getBuiltInMetadataFields()` for defining meta-fields in test items.
