### PR TITLE
ILM: execute cached steps even if policy is updated

### LINKED ISSUE #66838: ILM can get stuck in the hot phase during attempt-rollover step if rollover is removed from the policy
**Elasticsearch version** (`bin/elasticsearch --version`): 7.10.1 on ESS

**Plugins installed**: n/a

**JVM version** (`java -version`):

```
        "vm_name" : "OpenJDK 64-Bit Server VM",
        "vm_version" : "15.0.1+9",
        "vm_vendor" : "AdoptOpenJDK"
```

**OS version** (`uname -a` if on a Unix-like system): CentOS Linux 8 (Core)

**Description of the problem including expected versus actual behavior**:

Removing the rollover action while an index is in the `check-rollover-ready` step will cause it to get stuck in the hot phase without error in ILM explain. This behavior may or may not be by design, or something ILM was not meant to do, so expected behavior could vary:

1. Allow the hot phase to complete to prevent further writes to the index and move to the next desired phase. Or,
2. Show an error in ILM explain to indicate there is a problem moving to the next step.

**Steps to reproduce**:

 1. Decrease the poll interval and up the logging.

    ```
    PUT /_cluster/settings
    {
      "persistent": {
        "indices.lifecycle.poll_interval": "1s",
        "logger.org.elasticsearch.xpack.ilm": "TRACE"
      }
    }
    ```

 1. Add an index template

    ```
    PUT /_template/devtest
    {
      "index_patterns": [
        "devtest-*"
      ],
      "settings": {
        "index": {
          "lifecycle": {
            "name": "devtest",
            "rollover_alias": "devtest"
          },
          "number_of_shards": "1",
          "number_of_replicas": "0"
        }
      }
    }
    ```

 1. Add policy version 1. Note the rollover action in the hot phase. 

    ```
    PUT /_ilm/policy/devtest
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "rollover": {
                "max_size": "50mb",
                "max_age": "2m"
              }
            }
          },
          "delete": {
            "min_age": "2m",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
    ```

1. Create the index

    ```
    PUT /devtest-000001
    {
      "aliases": {
        "devtest": {
          "is_write_index": true
        }
      }
    }
    ```

1. Let ILM perform an index rollover.

1. Create version 2 of the policy by removing the rollover action from the hot phase. The intention here is to let ILM perform index deletions per policy and prevent creation of a new index.

    ```
    PUT /_ilm/policy/devtest
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {}
          },
          "delete": {
            "min_age": "2m",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
    ```

1. Wait a few minutes and observe the last index is stuck in the rollover action of the hot phase.

    ```
    GET /devtest/_ilm/explain
    {
      "indices" : {
        "devtest-000031" : {
          "index" : "devtest-000031",
          "managed" : true,
          "policy" : "devtest",
          "lifecycle_date_millis" : 1609189822495,
          "age" : "7.12m",
          "phase" : "hot",
          "phase_time_millis" : 1609189822954,
          "action" : "rollover",
          "action_time_millis" : 1609189825089,
          "step" : "check-rollover-ready",
          "step_time_millis" : 1609189825089,
          "phase_execution" : {
            "policy" : "devtest",
            "phase_definition" : {
              "min_age" : "0ms",
              "actions" : {
                "rollover" : {
                  "max_size" : "50mb",
                  "max_age" : "2m"
                }
              }
            },
            "version" : 3,
            "modified_date_in_millis" : 1609186540697
          }
        }
      }
    }
    ```

**Provide logs (if relevant)**:

```
[es/i-0/es.log] [2020-12-28T19:40:46.669Z][TRACE][org.elasticsearch.xpack.ilm.MoveToNextStepUpdateTask] [instance-0000000000] moving [devtest-000003] to next step ({"phase":"hot","action":"rollover","name":"attempt-rollover"})
[es/i-0/es.log] [2020-12-28T19:40:46.669Z][TRACE][org.elasticsearch.xpack.ilm.PolicyStepsRegistry] [instance-0000000000] parsed steps for policy [devtest] in phase [delete], definition: [{"policy":"devtest","phase_definition":{"min_age":"2m","actions":{"delete":{"delete_searchable_snapshot":true}}},"version":2,"modified_date_in_millis":1609184409141}], steps: [[{"phase":"delete","action":"delete","name":"wait-for-shard-history-leases"} => {"phase":"delete","action":"delete","name":"cleanup-snapshot"}, {"phase":"delete","action":"delete","name":"cleanup-snapshot"} => {"phase":"delete","action":"delete","name":"delete"}, {"phase":"delete","action":"delete","name":"delete"} => {"phase":"delete","action":"complete","name":"complete"}, {"phase":"delete","action":"complete","name":"complete"} => null]]
[es/i-0/es.log] [2020-12-28T19:40:46.674Z][ERROR][org.elasticsearch.cluster.service.MasterService] [instance-0000000000] exception thrown by listener notifying of failure from [ilm-move-to-step {policy [devtest], index [devtest-000003], currentStep [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}], nextStep [{"phase":"hot","action":"rollover","name":"attempt-rollover"}]}]
org.elasticsearch.ElasticsearchException: policy [devtest] for index [devtest-000003] failed trying to move from step [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] to step [{"phase":"hot","action":"rollover","name":"attempt-rollover"}].
	at org.elasticsearch.xpack.ilm.MoveToNextStepUpdateTask.onFailure(MoveToNextStepUpdateTask.java:92) ~[?:?]
	at org.elasticsearch.cluster.service.MasterService$SafeClusterStateTaskListener.onFailure(MasterService.java:513) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService$TaskOutputs.notifyFailedTasks(MasterService.java:446) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:220) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.10.1.jar:7.10.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
	Suppressed: java.lang.IllegalArgumentException: step [{"phase":"hot","action":"rollover","name":"attempt-rollover"}] for index [devtest-000003] with policy [devtest] does not exist
		at org.elasticsearch.xpack.ilm.IndexLifecycleTransition.validateTransition(IndexLifecycleTransition.java:84) ~[?:?]
		at org.elasticsearch.xpack.ilm.IndexLifecycleTransition.moveClusterStateToStep(IndexLifecycleTransition.java:105) ~[?:?]
		at org.elasticsearch.xpack.ilm.MoveToNextStepUpdateTask.execute(MoveToNextStepUpdateTask.java:74) ~[?:?]
		at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.10.1.jar:7.10.1]
		at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.10.1.jar:7.10.1]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
		at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.IllegalArgumentException: step [{"phase":"hot","action":"rollover","name":"attempt-rollover"}] for index [devtest-000003] with policy [devtest] does not exist
	at org.elasticsearch.xpack.ilm.IndexLifecycleTransition.validateTransition(IndexLifecycleTransition.java:84) ~[?:?]
	at org.elasticsearch.xpack.ilm.IndexLifecycleTransition.moveClusterStateToStep(IndexLifecycleTransition.java:105) ~[?:?]
	at org.elasticsearch.xpack.ilm.MoveToNextStepUpdateTask.execute(MoveToNextStepUpdateTask.java:74) ~[?:?]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.10.1.jar:7.10.1]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) ~[elasticsearch-7.10.1.jar:7.10.1]
	... 10 more
```

### Use Case

The issue was discovered trying to use ILM to "dynamically" remove indices once they are no longer needed. The goal is to 1) stop creation of new indices; and 2) let ILM delete indices per the lifecycle policy.

### PR DESCRIPTION
**Pull request by andreidan**
This makes ILM honour the cached phase even when the underlying policy
is updated to not contain the cached actions.

Fixes #66838

### CODE REVIEW

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistry.java [hunk 1]
```diff
@@ -143,6 +145,15 @@ public LifecyclePolicyMetadata read(StreamInput in, String key) {
         }
     }
 
+    /**
+     * Parses the step keys from the {@code phaseDef} for the given phase.
+     * Returns null if there's a parsing error.
+     */
+    @Nullable
+    public Set<Step.StepKey> parseStepKeysFromPhase(String phaseDef, String currentPhase) {
```
Comment (andreidan) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/PolicyStepsRegistry.java:153]: Exposed this here for convenience and to reduce the number of dependencies `IndexLifecycleTransition` would need if it was to use the `PhaseCacheManagement` directly.

**Review by dakrone — APPROVED** [review]
LGTM, thanks for fixing this Andrei
