### PR TITLE
Handle empty index case in LuceneSyntheticSourceChangesSnapshot

### LINKED ISSUE #118955: [CI] SmokeTestMultiNodeClientYamlTestSuiteIT class failing
**Build Scans:**
- [elasticsearch-periodic #5464 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/i2qn3inleapc4)
- [elasticsearch-pull-request #47963 / part-1](https://gradle-enterprise.elastic.co/s/44prppr7se5xk)
- [elasticsearch-pull-request #47954 / part-1-entitlements](https://gradle-enterprise.elastic.co/s/mbun6tpvmbzmg)
- [elasticsearch-pull-request #47939 / part-1](https://gradle-enterprise.elastic.co/s/jiiwpughb7qis)
- [elasticsearch-pull-request #47924 / part-1](https://gradle-enterprise.elastic.co/s/gllxhboofpnzi)
- [elasticsearch-pull-request #47889 / part-1](https://gradle-enterprise.elastic.co/s/gzjbd32ivmesq)
- [elasticsearch-pull-request #47867 / part-1](https://gradle-enterprise.elastic.co/s/iuitggih4rtwu)
- [elasticsearch-pull-request #47656 / part-1](https://gradle-enterprise.elastic.co/s/c3vq5xlwd7vu6)
- [elasticsearch-pull-request #47572 / part-1](https://gradle-enterprise.elastic.co/s/laym4mmuisg7i)
- [elasticsearch-pull-request #47460 / part-1](https://gradle-enterprise.elastic.co/s/oaoqdxlnphmt2)

**Reproduction Line:**
```
./gradlew ":qa:smoke-test-multinode:yamlRestTest" --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT" -Dtests.method="test {yaml=indices.create/20_synthetic_source/create index with use_synthetic_source}" -Dtests.seed=EEF8314C3457C525 -Dtests.locale=bs -Dtests.timezone=Pacific/Pitcairn -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.net.SocketTimeoutException: 60.000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
```

**Issue Reasons:**
- [main] 23 failures in class org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT (4.6% fail rate in 502 executions)
- [main] 15 failures in step part-1 (6.3% fail rate in 238 executions)
- [main] 2 failures in step part1 (2.1% fail rate in 94 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (25.0% fail rate in 8 executions)
- [main] 15 failures in pipeline elasticsearch-pull-request (6.3% fail rate in 239 executions)
- [main] 2 failures in pipeline elasticsearch-intake (2.1% fail rate in 94 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by martijnvg**
In case of synthetic recovery source when the mapping is empty.

A test that reproduces failure in #118955 consistently with a potential fix.

`MapperService#updateMapping(...)` doesn't set the mapper field if a mapping has no fields, which is what is used in InternalEngine#newChangesSnapshot(...) . This happens when `newMappingMetadata` variable in `MapperService updateMapping(...)` is `null`. Causing an assertion to trip. This change adjusts that assertion to handle an empty index.

Closes #118955

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 1]
```diff
@@ -3159,17 +3159,21 @@ public Translog.Snapshot newChangesSnapshot(
...
-                    searcher,
-                    SearchBasedChangesSnapshot.DEFAULT_BATCH_SIZE,
-                    maxChunkSize,
-                    fromSeqNo,
-                    toSeqNo,
-                    requiredFullRange,
-                    accessStats,
-                    config().getIndexSettings().getIndexVersionCreated()
-                );
+                if (searcher.getIndexReader().maxDoc() == 0) {
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:3162]: Maybe add a small comment to explain why we're doing that?

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/part-1
