### PR TITLE
Fix ES:QL Driver logging for 4xx errors and cancellations

### LINKED ISSUE #138008: ES:QL Logging: Driver 4xx error should not be logged as errors
Today every driver failure that bails with `RuntimeException` will emit an error error log line: 

https://github.com/elastic/elasticsearch/blob/263c178183939f77a5667ae0867eef8c1ee91ed4/x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java#L196 

It seems that conditions other than "strictly" errors fall into this category - e.g. we are seeing `cancelled by user` as one of the messages, probably other conditions that result from user actions and parameters that are not strictly failures. 

Ideally we want to make sure that anything that corresponds to a cancelled query or any 4xx condition doesn't generate this noise - warnings or infos would probably be fine here.

### PR DESCRIPTION
**Pull request by shmuelhanoch**
# Fix ES:QL Driver logging for 4xx errors and cancellations
Reduces log noise by logging 4xx client errors (including cancellations) at DEBUG instead of WARN/ERROR.
## Problem:
Over 80% of ES:QL errors in serverless are from user cancellations, which are expected user actions, not system failures. These were logged at WARN/ERROR, creating noise.
## Solution:
TaskCancelledException is already handled separately at DEBUG level
RuntimeException with 4xx status codes (400-499) are now logged at DEBUG level
5xx server errors continue to be logged at WARN level
## Impact:
Reduces log noise from expected client actions while preserving visibility into actual system failures.

Closes  #138008

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java [hunk 1]
```diff
@@ -196,7 +198,14 @@ SubscribableListener<Void> run(TimeValue maxTime, int maxIterations, LongSupplie
                 LOGGER.debug("Cancelling running driver [{}]", shortDescription, e);
                 throw e;
             } catch (RuntimeException e) {
-                LOGGER.warn(Strings.format("Error running driver [%s]", shortDescription), e);
+                RestStatus status = ExceptionsHelper.status(e);
+                // Don't log 4xx client errors (including cancellations) as warnings/errors
+                // as they are expected user actions, not system failures
+                if (status.getStatus() >= 400 && status.getStatus() < 500) {
```
Comment (GalLalouche) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java:206]: This also removes the warnings on 429s, which could be an indication of failing to scale. @quackaplop, just to double-check, are we OK with this?

Comment (shmuelhanoch) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java:206]: I can make an exception for 429's so that there will be still logged as WARN, let's wait for the final answer if we want it or not?

Comment (quackaplop) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java:206]: This is borderline, but isn't 429  "too many requests", and the user is expected to back off and slow down to resolve this? So this error is something for the user to react to? 

The main question we need to ask ourselves- who is responsible for addressing this error? If we log it, this means us - and what would we do if we saw 429? Is it actionable? I _think_ in most cases not. So I don't know if we need to skip 429 here - the way this is written is likely right. 

But I am open to suggestions

Comment (shmuelhanoch) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/Driver.java:206]: OK, Thanks!

**Review by GalLalouche — APPROVED** [review]
