### PR TITLE
Use contains relation for geo_point intersection over geo_point field

### LINKED ISSUE #75103: [CI] GeoPointShapeQueryTests testFieldAlias failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/4luaklzcgjbiu/tests/:server:test/org.elasticsearch.search.geo.GeoPointShapeQueryTests/testFieldAlias

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.search.geo.GeoPointShapeQueryTests.testFieldAlias" -Dtests.seed=1363D0D5C6B0CD8 -Dtests.locale=bg-BG -Dtests.timezone=Etc/GMT-8 -Druntime.java=11`

**Applicable branches:**
master, 7.x

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.geo.GeoPointShapeQueryTests&tests.test=testFieldAlias

**Failure excerpt:**
```
java.lang.AssertionError: expected:<1> but was:<0>

  at __randomizedtesting.SeedInfo.seed([1363D0D5C6B0CD8:3B70AC687EDC98EC]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:645)
  at org.junit.Assert.assertEquals(Assert.java:631)
  at org.elasticsearch.search.geo.GeoPointShapeQueryTests.testFieldAlias(GeoPointShapeQueryTests.java:62)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by iverase**
For point queries and intersects, lucene does not match points that are encoded to Integer.MAX_VALUE due to the use of predicates. Use contains instead that returns the expected results. 

closes https://github.com/elastic/elasticsearch/issues/75103

### CODE REVIEW

**Comment by iverase** [comment]
part-1 failed because of #75221, unrelated flaky test

@elasticmachine run elasticsearch-ci/part-1

File: server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java [hunk 1]
```diff
@@ -260,9 +262,13 @@ public Query geoShapeQuery(Geometry shape, String fieldName, ShapeRelation relat
             if (luceneGeometries.length == 0) {
                 return new MatchNoDocsQuery();
             }
-            Query query = LatLonPoint.newGeometryQuery(fieldName, relation.getLuceneRelation(), luceneGeometries);
+            // For point queries and intersects, lucene does not match points that are encoded to Integer.MAX_VALUE. Use contains
+            // instead that returns the expected results.
+            ShapeField.QueryRelation luceneRelation = relation == ShapeRelation.INTERSECTS && shape.type() == ShapeType.POINT ?
+                    ShapeField.QueryRelation.CONTAINS : relation.getLuceneRelation();
```
Comment (imotov) [inline server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java:268]: I think in this case explicit if statement might make it much easier to comprehend. There is just too much going on with the comment and expression otherwise. WDYT?
```
final ShapeField.QueryRelation luceneRelation;
if (shape.type() == ShapeType.POINT && relation == ShapeRelation.INTERSECTS) {
  // For point queries and intersects, lucene does not match points that are encoded to Integer.MAX_VALUE. Use contains instead
  luceneRelation = ShapeField.QueryRelation.CONTAINS;
} else {
  luceneRelation = relation.getLuceneRelation();
}

**Review by imotov — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java (hunk 1 above)
Comment (iverase) [reply server/src/main/java/org/elasticsearch/index/mapper/GeoPointFieldMapper.java]: done
