### PR TITLE
[ML] Improve assertion on regression alias field test

### LINKED ISSUE #60212: RegressionIT.testAliasFields is failing
**Build scan**:
https://gradle-enterprise.elastic.co/s/vjebbutdxi44g
**Repro line**:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testAliasFields" -Dtests.seed=4C8CA3AF936CD948 -Dtests.security.manager=true -Dtests.locale=ko-KR -Dtests.timezone=Australia/Broken_Hill -Druntime.java=11
```
**Reproduces locally?**:
Yes
**Applicable branches**:
main, 7.9, 7.x
**Failure excerpt**:
```
org.elasticsearch.xpack.ml.integration.RegressionIT > testAliasFields FAILED
    java.lang.AssertionError: 
    Expected: a numeric value within <10.0> of <468.0>
         but: <478.1716820377456> differed by <0.17168203774559743> more than delta <10.0>
        at __randomizedtesting.SeedInfo.seed([4C8CA3AF936CD948:7AF2C5FC13CBA4AE]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ml.integration.RegressionIT.testAliasFields(RegressionIT.java:553)
```

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Previously the test was asserting the prediction on each document
was close 10.0 from the expected. It turned out that was not enough
as we occasionally saw the test failing by little.

Instead of relaxing that assertion, this commit changes it to
assert the mean prediction error is less than 10.0. This should
reduce the chances of the test failing significantly.

Fixes #60212

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java [hunk 1]
```diff
@@ -544,19 +543,26 @@ public void testAliasFields() throws Exception {
...
-            int featureValue = (int) destDoc.get("field_1");
-            double predictionValue = (double) resultsObject.get(predictionField);
-            assertThat(predictionValue, closeTo(2 * featureValue, 10.0));
-
             assertThat(resultsObject.containsKey(predictionField), is(true));
             assertThat(resultsObject.containsKey("is_training"), is(true));
+
+            int featureValue = (int) destDoc.get("field_1");
+            double predictionValue = (double) resultsObject.get(predictionField);
+            predictionErrorSum += Math.abs(predictionValue - 2 * featureValue);
```
Comment (przemekwitek) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java:558]: I'm wondering if we could drop the `Math.abs` here. This would of course increase the chance of the assertion in line 564 to pass but maybe it is not necessary.

**Review by przemekwitek — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java (hunk 1 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/qa/native-multi-node-tests/src/test/java/org/elasticsearch/xpack/ml/integration/RegressionIT.java:558]: We are interested in how far the prediction is from what we expect. Dropping the `abs` would mean that 2 errors that are opposite direction would cancel each other out and possibly this could hide the fact that the error is too large.
