### PR TITLE
Minor RangeAgg optimization

### LINKED ISSUE #84262: Optimize date_histogram for single-valued fields
### Description

Our most common aggregations should be optimized for single-valued fields. In general, our aggregations look like this:

```java
    @Override
    public LeafBucketCollector getLeafCollector(LeafReaderContext ctx, LeafBucketCollector sub) throws IOException {
        if (valuesSource == null) {
            return LeafBucketCollector.NO_OP_COLLECTOR;
        }
        SortedNumericDocValues values = valuesSource.longValues(ctx);
        return new LeafBucketCollectorBase(sub, values) {
            @Override
            public void collect(int doc, long owningBucketOrd) throws IOException {
                if (values.advanceExact(doc)) {
                    int valuesCount = values.docValueCount();
                    for (int i = 0; i < valuesCount; ++i) {
                        long value = values.nextValue();
                        // do something with value
                    }
                }
            }
        };
    }
```

The idea consists of optimizing for single-valued fields by unwrapping the single-valued doc-value iterator:

```java
    @Override
    public LeafBucketCollector getLeafCollector(LeafReaderContext ctx, LeafBucketCollector sub) throws IOException {
        if (valuesSource == null) {
            return LeafBucketCollector.NO_OP_COLLECTOR;
        }
        SortedNumericDocValues values = valuesSource.longValues(ctx);
        NumericDocValues singleValues = DocValues.unwrapSingleton(values); // or FieldData.unwrapSingleton for doubles
        if (singleValues != null) {
            return new LeafBucketCollectorBase(sub, values) {
                @Override
                public void collect(int doc, long owningBucketOrd) throws IOException {
                    if (singleValues.advanceExact(doc)) {
                        long value = singleValues.longValue();
                        // do something with value
                    }
                }
            };
        } else {
            return new LeafBucketCollectorBase(sub, values) {
                @Override
                public void collect(int doc, long owningBucketOrd) throws IOException {
                    if (values.advanceExact(doc)) {
                        int valuesCount = values.docValueCount();
                        for (int i = 0; i < valuesCount; ++i) {
                            long value = values.nextValue();
                            // do something with value
                        }
                    }
                }
            };
        }
    }
```

The `terms` aggregation already does this, and e.g. `min` and `max` aggregations use similar tricks that also help optimize the single-valued case. But `date_histogram`, which is one of our most common aggregations, doesn't. Let's specialize the single-value case for date histograms too?

### PR DESCRIPTION
**Pull request by tmgordeeva**
Shortcut for when we have single values in a range aggregation. This also
targets date histogram aggregations which often are converted to range
aggregations. Add profiling counts for the singleton and non-singleton
code paths.

Closes #84262

### CODE REVIEW

**Comment by nik9000** [comment]
> x Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [d6ba1d6](https://github.com/elastic/elasticsearch/commit/d6ba1d6cca7644caa76353c3835f8db2226b5eb1)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Hey CLAbot. @tmgordeeva is part of the Elastic organization. Maybe this comment will cause you to reconsider your error.

**Comment by gtback** [comment]
cla/check

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/range/RangeAggregator.java [hunk 1]
```diff
@@ -640,18 +654,33 @@ private abstract static class NumericRangeAggregator extends RangeAggregator {
...
+                    @Override
+                    public void collect(int doc, long bucket) throws IOException {
+                        if (singleton.advanceExact(doc)) {
+                            NumericRangeAggregator.this.collect(sub, doc, singleton.doubleValue(), bucket, 0);
                         }
                     }
-                }
-            };
+                };
+            } else {
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/range/RangeAggregator.java:669]: Would you kindly drop the `else` if you are returning? I'm on a semi-irrational quest to remove indentation.

**Review by nik9000 — APPROVED** [review]
