### PR TITLE
Fix YamlRestTestPluginFuncTest on Windows

### LINKED ISSUE #77060: [CI] YamlRestTestPluginFuncTest declares default dependencies failing
This seems to happen on windows, I suspect  #76554 being the cause of it

**Build scan:**
https://gradle-enterprise.elastic.co/s/eiajse5solcok/tests/:integTest/org.elasticsearch.gradle.test.YamlRestTestPluginFuncTest/declares%20default%20dependencies

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.test.YamlRestTestPluginFuncTest&tests.test=declares%20default%20dependencies

**Failure excerpt:**
```
org.spockframework.runtime.ConditionNotSatisfiedError: Condition not satisfied:

result.output.contains(""" restTestSpecs \\--- org.elasticsearch:rest-api-spec:${VersionProperties.elasticsearch} FAILED """)
|      |      |                                                                  |                 |
|      |      false                                                              |                 8.0.0-SNAPSHOT
|      |                                                                         class org.elasticsearch.gradle.VersionProperties
|       
|      > Task :dependencies
|       
|      ------------------------------------------------------------
|      Root project 'hello-world'
|      ------------------------------------------------------------
|       
|      archives - Configuration for archive artifacts. (n)
|      No dependencies
|       
|      default - Configuration for default artifacts. (n)
|      No dependencies
|       
|      es_distro_extracted_testclusters--yamlRestTest-0-8.0.0-SNAPSHOT
|      No dependencies
|       
|      es_distro_file_testclusters--yamlRestTest-0-8.0.0-SNAPSHOT
|      No dependencies
|       
|      restTestSpecs
|      \--- org.elasticsearch:rest-api-spec:8.0.0-SNAPSHOT FAILED
|       
|      yamlRestTestAnnotationProcessor - Annotation processors and their dependencies for source set 'yaml rest test'.
|      No dependencies
|       
|      yamlRestTestCompileClasspath - Compile classpath for source set 'yaml rest test'.
|      \--- org.elasticsearch.test:framework:8.0.0-SNAPSHOT FAILED
|       
|      yamlRestTestCompileOnly - Compile only dependencies for source set 'yaml rest test'. (n)
|      No dependencies
|       
|      yamlRestTestImplementation - Implementation only dependencies for source set 'yaml rest test'. (n)
|      \--- org.elasticsearch.test:framework:8.0.0-SNAPSHOT (n)
|       
|      yamlRestTestRuntimeClasspath - Runtime classpath of source set 'yaml rest test'.
|      \--- org.elasticsearch.test:framework:8.0.0-SNAPSHOT FAILED
|       
|      yamlRestTestRuntimeOnly - Runtime only dependencies for source set 'yaml rest test'. (n)
|      No dependencies
|       
|      (n) - Not resolved (configuration is not meant to be resolved)
|       
|      A web-based, searchable dependency report is available by adding the --scan option.
|       
|      BUILD SUCCESSFUL in 9s
|      1 actionable task: 1 executed
<org.gradle.testkit.runner.internal.FeatureCheckBuildResult@c585388 delegateBuildResult=org.gradle.testkit.runner.internal.DefaultBuildResult@54ed8ada outputFeatureCheck=org.gradle.testkit.runner.internal.feature.BuildResultOutputFeatureCheck@4744f86e>

  at org.elasticsearch.gradle.test.YamlRestTestPluginFuncTest.declares default dependencies(YamlRestTestPluginFuncTest.groovy:29)

```

### PR DESCRIPTION
**Pull request by breskeby**
- need to normalize output before comparison
- should fix #77060

### CODE REVIEW

File: build-tools/src/integTest/groovy/org/elasticsearch/gradle/test/YamlRestTestPluginFuncTest.groovy [hunk 1]
```diff
@@ -26,14 +26,12 @@ class YamlRestTestPluginFuncTest extends AbstractGradleFuncTest {
         def result = gradleRunner("dependencies").build()
 
         then:
-        result.output.contains("""
+        normalized(result.output).contains("""
```
Comment (pugnascotia) [inline build-tools/src/integTest/groovy/org/elasticsearch/gradle/test/YamlRestTestPluginFuncTest.groovy:29]: Should we normalize the output once and assign it to local variable? Or is that overkill?

Comment (breskeby) [reply build-tools/src/integTest/groovy/org/elasticsearch/gradle/test/YamlRestTestPluginFuncTest.groovy:29]: Actually, we could could probably do the normalization already in the runner. I don't see where non normalized output would be preferable. Will look into this. 👍
