### PR TITLE
SQL: Fix disjunctions (and `IN`) with multiple date math expressions

### LINKED ISSUE #76336: SQL: Cannot use multiple date math expression filters in disjunction
The following SQL query works as expected up to Elasticsearch 7.10.0:

```
POST _sql
{
  "query":"SELECT COUNT(*) FROM testindex WHERE (timestamp='now-1d/d' OR timestamp='now-2d/d')"
}
```

However, starting with 7.11.0 it fails with:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "ql_illegal_argument_exception",
        "reason" : "cannot cast [now-1d/d] to [datetime]: Text 'now-1d/d' could not be parsed at index 0"
      }
    ],
    "type" : "ql_illegal_argument_exception",
    "reason" : "cannot cast [now-1d/d] to [datetime]: Text 'now-1d/d' could not be parsed at index 0",
    "caused_by" : {
      "type" : "date_time_parse_exception",
      "reason" : "Text 'now-1d/d' could not be parsed at index 0"
    }
  },
  "status" : 500
}
```

The issue has most likely been introduced with https://github.com/elastic/elasticsearch/pull/65353

### PR DESCRIPTION
**Pull request by Luegg**
Resolves https://github.com/elastic/elasticsearch/issues/76336

The optimizer turns disjunctions with equality comparisons (`a = 1 OR a = 2`) against the same field into `IN` expressions (`a IN (1, 2)`). Unfortunately, `IN` handles date/time comparison differently than `Equals`: While `IN` always tries to parse string literals compared to date/time fields as date/time during the query folding, `Equals` does pass through string literals to the term query without parsing.

This PR removes this inconsistency by delegating the date/time handling logic in `In` to `Equals`. This fixes https://github.com/elastic/elasticsearch/issues/76336 and adds support for date math in `In` expressions.

The PR does not address other inconsistencies around handling of date math in SQL. E.g. date math still cannot be used to filter a derived value as in `DATE_ADD('day', 1, hire_date) = '2021-02-03||-27y/y'`

### CODE REVIEW

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 1]
```diff
@@ -316,11 +317,10 @@ private static Query translate(BinaryComparison bc, TranslatorHandler handler) {
                 return new RangeQuery(source, name, null, false, value, true, format, zoneId);
             }
             if (bc instanceof Equals || bc instanceof NullEquals || bc instanceof NotEquals) {
-                if (bc.left() instanceof FieldAttribute) {
```
Comment (Luegg) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:319]: I've replaced the `instanceof` check with the assert above. To me it was quite confusing because it looked like `bc.left()` can also be of another type. But `handler.wrapFunctionQuery` in `doTranslate` ensures that `translate` is never called with an `BinaryComparison` with a `left()` that's not a `FieldAttribute`.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java [hunk 2]
```diff
@@ -408,18 +407,6 @@ public void testSameExpressionWithoutAlias() {
         assertNotEquals(eqe.output().get(0).id(), eqe.output().get(1).id());
     }
 
-    public void testInOutOfRangeValues() {
```
Comment (Luegg) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java:411]: These two tests assert a behavior that's different between `IN` and `=`: `IN` tries to convert each value in the list to the type on the left hand side. `=` on the other hand does not perform this conversion and passes non-matching types to ES. So both `select emp_no from test_emp where emp_no in (9223372036854775807)` and `select emp_no from test_emp where emp_no < 9223372036854775807` fail, but the former with
```
{"error":{"root_cause":[{"type":"ql_illegal_argument_exception","reason":"[9223372036854775807] out of [integer] range"}],"type":"ql_illegal_argument_exception","reason":"[9223372036854775807] out of [integer] range"},"status":500}
```
and the latter with
```
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: Value [9223372036854775807] is out of range for an integer","index_uuid":"JrctQS1KTXmIqlD6_vkAQQ","index":"test_emp"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"test_emp","node":"6a6CBLYYQFa6gqsxbMkn5Q","reason":{"type":"query_shard_exception","reason":"failed to create query: Value [9223372036854775807] is out of range for an integer","index_uuid":"JrctQS1KTXmIqlD6_vkAQQ","index":"test_emp","caused_by":{"type":"illegal_argument_exception","reason":"Value [9223372036854775807] is out of range for an integer"}}}]},"status":400}
```

I now aligned the behavior such that both `IN` and `=` pass the values to ES.

Another alternative would have been to adopt the `IN` behavior and do the check in QL but I'm not sure about unintended side effects. And for some types, like date/time, we cannot do the conversion because a String might be a date math expression.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 3]
```diff
@@ -392,41 +392,31 @@ public static Query doTranslate(In in, TranslatorHandler handler) {
...
-                        q = q == null ? right : new BoolQuery(in.source(), false, q, right);
+            assert in.value() instanceof FieldAttribute;
+
+            Set<Object> terms = new LinkedHashSet<>();
+            List<Query> queries = new ArrayList<>();
+
+            for (Expression rhs : in.list()) {
+                if (DataTypes.isNull(rhs.dataType()) == false) {
+                    // delegates to BinaryComparisons translator to ensure consistent handling of date and time values
+                    Query query = BinaryComparisons.translate(new Equals(in.source(), in.value(), rhs, in.zoneId()), handler);
```
Comment (Luegg) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:403]: This is not the cheapest way to delegate to `BinaryComparisons` but every other attempt required some larger refactoring of `BinaryComparisons.translate`.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:319]: Worth adding a comment or improving the return type of doTranslate.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java:411]: Are there any new features supported by IN due to this new behavior? Such as date math?

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 4]
```diff
@@ -274,7 +273,9 @@ public static Query doTranslate(BinaryComparison bc, TranslatorHandler handler)
             return handler.wrapFunctionQuery(bc, bc.left(), () -> translate(bc, handler));
         }
 
-        private static Query translate(BinaryComparison bc, TranslatorHandler handler) {
+        static Query translate(BinaryComparison bc, TranslatorHandler handler) {
+            assert bc.left() instanceof FieldAttribute;
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:277]: `assert` is very bad since in the very unlikely case that it fails, it brings the whole JVM down.
Throw an exception instead (see `Check` utility class).

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 5]
```diff
@@ -392,41 +392,31 @@ public static Query doTranslate(In in, TranslatorHandler handler) {
...
-                        set.add(handler.convert(valueOf(e), dt));
-                    }
-                });
-
-                if (DataTypes.isDateTime(dt)) {
-                    DateFormatter formatter = DateFormatter.forPattern(DATE_FORMAT);
-
-                    q = null;
-                    for (Object o : set) {
-                        assert o instanceof ZonedDateTime : "expected a ZonedDateTime, but got: " + o.getClass().getName();
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:415]: This shouldn't have been here.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 6]
```diff
@@ -392,41 +392,31 @@ public static Query doTranslate(In in, TranslatorHandler handler) {
...
-                        // see comment in Ranges#doTranslate() as to why formatting as String is required
-                        String zdt = formatter.format((ZonedDateTime) o);
-                        RangeQuery right = new RangeQuery(
-                            in.source(), fa.exactAttribute().name(),
-                            zdt, true, zdt, true, formatter.pattern(), in.zoneId());
-                        q = q == null ? right : new BoolQuery(in.source(), false, q, right);
+            assert in.value() instanceof FieldAttribute;
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:395]: see my comment above on assert

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 7]
```diff
@@ -392,41 +392,31 @@ public static Query doTranslate(In in, TranslatorHandler handler) {
...
-                q = new ScriptQuery(in.source(), in.asScript());
             }
-            return q;
+
+            String fieldName = ((FieldAttribute) in.value()).exactAttribute().name();
+            if (terms.isEmpty() == false) {
+                queries.add(new TermsQuery(in.source(), fieldName, terms));
+            }
+
+            return queries.stream()
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:418]: I don't recall creating a `BoolQuery` by hand anywhere else - usually this is done in the optimizer not the translator which just picks it up.
Here it is being used depending on the resulting query - however that will be the case only in case of datetime field which we know in advanced.

That is my preference is to handle this breaking / rewriting of the query at a higher-level, in the plan as oppose to during the translation level which should be simple and not worry about combining things.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 8]
```diff
@@ -392,41 +392,31 @@ public static Query doTranslate(In in, TranslatorHandler handler) {
...
+                    if (query instanceof TermQuery) {
+                        terms.add(((TermQuery) query).value());
+                    } else {
+                        queries.add(query);
                     }
-                } else {
-                    q = new TermsQuery(in.source(), fa.exactAttribute().name(), set);
                 }
-            } else {
-                q = new ScriptQuery(in.source(), in.asScript());
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:427]: Is my understanding correct that the `ScriptQuery` is now created in the `BinaryComparison.translate`?

**Review by costin — COMMENTED** [review]
Can you clarify what causes the issue at the query level? Is the issue the difference between `terms`, `term` and `range` query?

It's worth considering breaking this PR in two parts if possible - one that fixes the bug, the other that adds the new functionality for IN

1.  consolidating date/math handling
+1 on moving the date time handling in only place.
If I understand the PR correctly, it delegates the IN translation to the binary comparison and then, depending on the result, acts to combine or not the results.

Since datemath is an issue only for datetime fields, the delegation should be applied only in case the left field matches that type - otherwise the `terms` query can be created directly. This avoids having to create the `term` queries only to discard them. Note that the initial optimization was motivated because of queries with a large number of values (passed as `=`) so moving them to IN reduces duplicates and creates the terms directly.

2. The side effect of support date/math in `IN` is nice. However I'm not sure if there aren't any side-effects. Considering IN with one value is the same as equals for date/time fields, the behavior looks consistent to me however I'd like a few more tests to check this (have the same query be expressed just with equals and just with IN - for one, two and multiple values).

Thoughts?

P.S. marked this as a comment since I'll be away for a few days and don't want to hold it up.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java (hunk 8 above)
Comment (Luegg) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:427]: This branch was never reached because `in.value()` is always a `FieldAttribute`. The script query is always created by `handler.wrapFunctionQuery` in `doTranslate`.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java:411]: The only difference I know about is the missing conversion to the field type. This enables date math (and using string literal dates as in `date IN ('2021-10-01')`).

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java (hunk 7 above)
Comment (Luegg) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:418]: There were some concerns I had with doing this in the optimizer:
- The fact that some field/value combination cannot benefit from the `IN` optimization seemed very execution specific to me. Guarding against this in the optimizer would mean that some execution specific knowledge (wether a comparison is executed as a term query) leaks into the optimizer.
- This by itself is not enough to make `a IN (...)` and `a = ... OR a = ...` behave consistently. To consistently support date comparisons in `IN`, the optimizer would need a rule to split up `IN` with comparisons that are not executed as term queries. This is not really an optimization though.
- To me it looks somewhat similar to what we're doing in `QueryFolder.FoldFilter`. There, we also combine expressions from multiple `Filter` plans.

I'm replacing the manual creation of the `BoolQuery` though, as we already have specialized methods in `ExpressionTranslators` for this.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java (hunk 1 above)
Comment (Luegg) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:319]: 👍 I'm extending the interface of `doTranslate` to use the type system for handling this instead of assertions.

**Comment by Luegg** [comment]
> Can you clarify what causes the issue at the query level? Is the issue the difference between `terms`, `term` and `range` query?

The issue used to be that the `InComparisons` translator tried to convert the date math string to a date/time value. This caused a date format error. So it failed before hitting ES.

> 
> It's worth considering breaking this PR in two parts if possible - one that fixes the bug, the other that adds the new functionality for IN

Usually I would agree but the two are not that easy to separate. It would be possible to just stop the optimizer from applying the `CombineDisjunctionsToIn` optimization for datetime values but I'm not sure that's the best approach because of the reasons mentioned in https://github.com/elastic/elasticsearch/pull/76424/files/8e701cd49ce1e52c9ad1546b6d1777e62e68dae8#r689391644

> 
> 1. consolidating date/math handling
>    +1 on moving the date time handling in only place.
>    If I understand the PR correctly, it delegates the IN translation to the binary comparison and then, depending on the result, acts to combine or not the results.
> 
> Since datemath is an issue only for datetime fields, the delegation should be applied only in case the left field matches that type - otherwise the `terms` query can be created directly. This avoids having to create the `term` queries only to discard them. Note that the initial optimization was motivated because of queries with a large number of values (passed as `=`) so moving them to IN reduces duplicates and creates the terms directly.

👍 I'll create the `terms` query directly if the field type is not a date/time.

> 
> 1. The side effect of support date/math in `IN` is nice. However I'm not sure if there aren't any side-effects. Considering IN with one value is the same as equals for date/time fields, the behavior looks consistent to me however I'd like a few more tests to check this (have the same query be expressed just with equals and just with IN - for one, two and multiple values).

From what I understand, `IN` used to be more restrictive than `=`. So the only side effect I'm expecting is that more queries using `IN` will be translated to an ES query and either fail in ES or succeed. I don't expect any queries that used to succeed to fail now.

> 
> Thoughts?
> 
> P.S. marked this as a comment since I'll be away for a few days and don't want to hold it up.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java:411]: > and `select emp_no from test_emp where emp_no < 9223372036854775807` fail

`<` is a BinaryComparison, but I guess for the `IN` rework I was expecting the `=` example :-)

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 9]
```diff
@@ -388,45 +372,39 @@ protected Query asQuery(In in, TranslatorHandler handler) {
...
-                // equality should always be against an exact match (which is important for strings)
-                FieldAttribute fa = (FieldAttribute) in.value();
-                DataType dt = fa.dataType();
-
-                List<Expression> list = in.list();
-                Set<Object> set = new LinkedHashSet<>(CollectionUtils.mapSize(list.size()));
-                list.forEach(e -> {
-                    // TODO: this needs to be handled inside the optimizer
-                    if (DataTypes.isNull(e.dataType()) == false) {
-                        set.add(handler.convert(valueOf(e), dt));
```
Comment (bpintea) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:406]: I guess the [removed tests](https://github.com/elastic/elasticsearch/pull/76424/files#r688298282) were "enabled" by this - now removed - conversion, but I wonder why was it needed before: just for DateTime's? I guess the rest of the types are conveniently converted by ES.

**Review by bpintea — APPROVED** [review]
LGTM, AFAI can tell.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java:411]: Good point, the `=` case also fails with a `query_shard_exception` :-)

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java (hunk 9 above)
Comment (Luegg) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:406]: I think the way the implementation worked before assumed that all values in the list have the same type. But you can also mix datetimes and strings: `foo IN ('2020-10-01T01:00', '2020-10-01T20:00'::datetime)`. So the conversion was needed to enable these mixed cases with the particular implementation.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/planner/QueryTranslator.java [hunk 10]
```diff
@@ -94,17 +94,12 @@ public static void checkInsensitiveComparison(InsensitiveBinaryComparison bc) {
                 Expressions.name(bc.right()), bc.symbol());
         }
 
-        private static Query translate(InsensitiveBinaryComparison bc, TranslatorHandler handler) {
+        private static Query translate(InsensitiveBinaryComparison bc, FieldAttribute field, TranslatorHandler handler) {
```
Comment (astefan) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/planner/QueryTranslator.java:97]: I tend not to agree with the additional FieldAttribute parameter. It bothers me that the methods receive a redundant parameter. In this case `bc.left()` is the same the `field` parametere.
[Here](https://github.com/elastic/elasticsearch/pull/76424/files#diff-385222df7bc48aa29c7282fd51bd3f3de071de85974214e19a44670750637182R238) `field` is the same as `isNull.field()`. This adds confusion: what's the point of the `field` if that same value can be extracted from the first parameter. Just to save on `if (X.field() instanceof FieldAttribute)`?

I'd like to know what others think about this. @bpintea @costin

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java (hunk 2 above)
Comment (astefan) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java:411]: If the content of `IN` values is a `string` a query like `SELECT birth_date, birth_date IN ('now-68y/y', 'now-67y/y', '1958-09-05'::datetime), gender IN ('M'), birth_date IN ('1958-09-05'::datetime) FROM test_emp WHERE birth_date IN ('now-68y/y', 'now-67y/y', '1958-09-05') ORDER BY birth_date` will return `null` for `IN ('now-68y/y')`. The condition will be valid, thus assuming it returns `true`, but the actual value is `null` in the projection.

If the projection contains `birth_date IN (....'1958-09-05'::datetime)` the value will be `true`/`false` because of the  type that's the one expected by the field. But `WHERE birth_date IN ('1958-09-05')` (not a datetime explicitly) will still be `true`. That's inconsistent imo. Yes, we get the advantage of passing datemath for `IN` but the behavior is inconsistent between the condition and the projection.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/planner/QueryTranslator.java (hunk 10 above)
Comment (bpintea) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/planner/QueryTranslator.java:97]: I remember I also looked longer at this. I'd say that if passing the extra parameter can be avoided everywhere, then it should be avoided.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java (hunk 9 above)
Comment (bpintea) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:406]: > I think the way the implementation worked before assumed that all values in the list have the same type.

Not sure about that, from these existing test: [here](https://github.com/elastic/elasticsearch/blob/a5a1c6aa9148cd98a0cf3b139619e5fe7bd85dc2/x-pack/plugin/sql/qa/server/src/main/resources/filter.csv-spec#L134) and below.

In any case, this non-DateTime "mixed values" IN would remain supported after the PR, right? That should work as the values end up as strings in the query - with no further conversions/pre-processing - passed to ES, which does then itself the conversion to the field type. But DateTimes could be different, with maybe TZ adjustment.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java:411]: I agree that this is an inconsistency that should be addressed if possible but I'm not sure it should be done in this PR. The goal here is to make sure `a IN (x, y)` and `a = x OR a = y` behave consistently and the optimizer can freely turn one into the other.

The inconsistency between the condition and the projection is a necessary consequence because this is also how equality between datetime and string behaves:

```
SELECT birth_date = 'now-68y/y' from test_emp where birth_date = 'now-68y/y'

birth_date = 'now-68y/y'
------------------------
null
null
null
...
```

I would suggest to handle this in a separate issue though as this might be quite a rabbit hole.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslator.java [hunk 11]
```diff
@@ -33,4 +34,9 @@ public static Query wrapIfNested(Query query, Expression exp) {
         }
         return query;
     }
+
+    public static FieldAttribute checkIsFieldAttribute(Expression e) {
+        Check.isTrue(e instanceof FieldAttribute, "Line {}: Expected [{}] to be FieldAttribute but was not.", e.sourceLocation(), e);
```
Comment (astefan) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslator.java:39]: The style of the error message should be consistent with the other uses of the `Check.isTrue` method in similar situations, ie `Expected a FieldAttribute but received [{}]`.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java (hunk 9 above)
Comment (astefan) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:406]: If this is an issue, it should be handled in a different PR (with a separate GH issue created).

**Review by astefan — APPROVED** [review]
LGTM. Left some minor comments.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 12]
```diff
@@ -346,11 +331,13 @@ protected Query asQuery(Range r, TranslatorHandler handler) {
...
         }
 
-        public static Query doTranslate(Range r, TranslatorHandler handler) {            
+        public static Query doTranslate(Range r, TranslatorHandler handler) {
             return handler.wrapFunctionQuery(r, r.value(), () -> translate(r, handler));
         }
 
-        private static RangeQuery translate(Range r, TranslatorHandler handler) {            
+        private static RangeQuery translate(Range r, TranslatorHandler handler) {
+            Check.isTrue(r.value() instanceof FieldAttribute, "Expected [{}] to be FieldAttribute but was not.", r.value());
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:339]: This might be a leftover. While it's probably not wrong, I'm removing it as `Ranges` does not assume `r.value()` is a FieldAttribute 👍

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java:411]: 👍 see https://github.com/elastic/elasticsearch/issues/77055

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslator.java [hunk 13]
```diff
@@ -36,7 +36,7 @@ public static Query wrapIfNested(Query query, Expression exp) {
     }
 
     public static FieldAttribute checkIsFieldAttribute(Expression e) {
-        Check.isTrue(e instanceof FieldAttribute, "Line {}: Expected [{}] to be FieldAttribute but was not.", e.sourceLocation(), e);
+        Check.isTrue(e instanceof FieldAttribute, "Expected a FieldAttributed but received [{}]", e);
```
Comment (astefan) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslator.java:39]: Typo
```suggestion
        Check.isTrue(e instanceof FieldAttribute, "Expected a FieldAttribute but received [{}]", e);
```

Comment (Luegg) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslator.java]: Thanks a lot!

**Review by costin — APPROVED** [review]
LGTM - thanks for the patience.
