### PR TITLE
Don't allow indices containing too-old segments to be opened

### LINKED ISSUE #10215: Don't allow indices containing too-old segments to be opened
Elasticsearch 2.x (Lucene 5.x) will support all Lucene 4.x segments, but not Lucene 3.x segments. We should not allow any indices with too-old segments to be opened on cluster restart.  These indices should be left in a closed state, and the reason for not opening should be logged.

If the user tries to open the index with the index-open API, they should receive an exception explaining the reason.

We will advise users of 1.x to install the migration advisory plugin #10214 before upgrading to check the age of their segments.  The upgrade path in this case will be to install Elasticsearch 1.6 and to run the upgrade API.

If users ignore this advice and go straight to 2.x, then they will be unable to open these indices.  At this point, the upgrade path will be to move these indices to a new directory, install 1.6, and use the upgrade API.  Once upgraded, they can install 2.0 and rely on the dangling indices function.

### PR DESCRIPTION
**Pull request by imotov**
When an index is introduced into the cluster via cluster upgrade, restore or as a dangled index the MetaDataIndexUpgradeService checks if this index can be upgraded to the current version. If upgrade is not possible, the newly upgraded cluster startup and restore process are aborted, the dangled index is imported as a closed index that cannot be open. This change doesn't actually checks the segment versions. Instead, it indiscriminately bans all old indices created with Elasticsearch older than v0.90. In 1.6 we will add an additional logic to upgrade API that will mark upgraded indices as "upgraded" using special setting and we will modify this process to accept such indices (see #11095).

Closes #10215

### CODE REVIEW

**Comment by rjernst** [comment]
Maybe I'm misunderstanding this, but it looks like this check is only on the ES version the index was created with, and not the lucene index?  While this will certainly block upgrades that are not possible, it would also fail indexes that were already upgraded (ie don't have any lucene 3.x segments)? As far as I understand, the created version is never modified (certainly not by merging or the upgrade api)?

**Comment by imotov** [comment]
@rjernst great observation! Sorry, I forgot to mention this in the description. I have updated the description.

File: src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexStateService.java [hunk 1]
```diff
@@ -160,7 +164,15 @@ public ClusterState execute(ClusterState currentState) {
...
                         .blocks(currentState.blocks());
                 for (String index : indicesToOpen) {
-                    mdBuilder.put(IndexMetaData.builder(currentState.metaData().index(index)).state(IndexMetaData.State.OPEN));
+                    IndexMetaData indexMetaData = IndexMetaData.builder(currentState.metaData().index(index)).state(IndexMetaData.State.OPEN).build();
+                    // The index might be closed because we couldn't import it due to old incompatible version
+                    // We need to check that this index can be upgraded to the current version
+                    try {
+                        indexMetaData = metaDataIndexUpgradeService.upgradeIndexMetaData(indexMetaData);
+                    } catch (Exception ex) {
+                        throw new IndexException(new Index(index), "unpgradable index", ex);
```
Comment (kimchy) [inline src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexStateService.java]: can we have a better message here?

**Comment by kimchy** [comment]
@imotov the code looks ok, but just so I understand how we will work in 2.0. Effectively, any version that has created version before 0.90 will require going through 1.6 for an upgrade, right?

**Comment by imotov** [comment]
@kimchy correct, if a cluster contains at least one index that was created before 0.90 such cluster will have to be upgraded to v1.6 before it can be upgraded to 2.0.

File: src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 2]
```diff
@@ -0,0 +1,134 @@
...
+    /**
+     * Elasticsearch 2.0 deprecated no longer supports indices with pre Lucene v4.0 segments. All indices
+     * that were created before Elasticsearch v0.90.0 should be upgraded using upgrade plugin before they can
+     * be open by this version of elasticsearch.
+     */
+    private IndexMetaData checkSupportedVersion(IndexMetaData indexMetaData) throws Exception {
+        if (indexMetaData.getState() == IndexMetaData.State.OPEN && isSupportedVersion(indexMetaData) == false) {
+            throw new IllegalStateException("The index [" + indexMetaData.getIndex() + "] was created before v0.90.0 and wasn't upgraded."
+                    + " This index should be open using a version before " + Version.CURRENT.minimumCompatibilityVersion()
+                    + " and upgraded using upgrade API.");
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: `upgrade API` -> `the upgrade API`

File: src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 3]
```diff
@@ -0,0 +1,134 @@
...
+        }
+        return indexMetaData;
+    }
+
+    /*
+     * Returns true if this index can be supported by the current version of elasticsearch
+     */
+    private static boolean isSupportedVersion(IndexMetaData indexMetaData) {
+        return indexMetaData.creationVersion() != null && indexMetaData.creationVersion().onOrAfter(Version.V_0_90_0_Beta1);
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: Maybe add minimumLuceneVersion() to index metadata as a placeholder for #11095? Then the impl can just be createdVersion().luceneVersion in this PR? It would just make it more clear here that the lucene version is the driving factor.

File: src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+
+/**
+ * This service is responsible for upgrading legacy index metadata to the current version
+ *
+ * Every time an existing index is introduced into cluster this service should be used
+ * to upgrade the existing index metadata to the latest version of the cluster. It typically
+ * occurs during cluster upgrade, when dangling indices are imported into the cluster or indices
+ * are restored from a repository.
+ */
+public class MetaDataIndexUpgradeService extends AbstractComponent {
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I think this name should be IndexMetaDataUpgradeService? Otherwise it sounds like there is a "metadata index".

File: src/main/java/org/elasticsearch/gateway/GatewayMetaState.java [hunk 5]
```diff
@@ -212,58 +213,27 @@ private void ensureNoPre019State() throws Exception {
     }
 
     /**
-     * Elasticsearch 2.0 deprecated custom routing hash functions. So what we do here is that for old indices, we
-     * move this old & deprecated node setting to an index setting so that we can keep things backward compatible.
+     * Elasticsearch 2.0 removed several deprecated features and removed support for Lucene 3.0. This method calls
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/gateway/GatewayMetaState.java]: `Lucene 3.0` -> `Lucene 3.x`?

File: src/main/java/org/elasticsearch/gateway/GatewayMetaState.java [hunk 6]
```diff
@@ -212,58 +213,27 @@ private void ensureNoPre019State() throws Exception {
...
+            IndexMetaData newMetaData = metaDataIndexUpgradeService.upgradeIndexMetaData(indexMetaData);
+            if (indexMetaData != newMetaData) {
+                updateIndexMetaData.add(newMetaData);
             }
         }
-        if (hasCustomPre20HashFunction || pre20UseType != null) {
-            logger.warn("Settings [{}] and [{}] are deprecated. Index settings from your old indices have been updated to record the fact that they "
-                    + "used some custom routing logic, you can now remove these settings from your `elasticsearch.yml` file", DEPRECATED_SETTING_ROUTING_HASH_FUNCTION, DEPRECATED_SETTING_ROUTING_USE_TYPE);
+        // We successfully checked all indices for backward compatibility and found no non-upgradable indices, which
+        // means the upgrade can continue. Now it's save to overwrite index metadata with the new version.
```
Comment (rjernst) [inline src/main/java/org/elasticsearch/gateway/GatewayMetaState.java]: save -> safe

File: src/test/java/org/elasticsearch/bwcompat/OldIndexBackwardsCompatibilityTests.java [hunk 7]
```diff
@@ -258,9 +273,52 @@ public void testOldIndexes() throws Exception {
...
+        logger.info("--> Testing old index " + index);
+        String indexName = loadIndex(index);
+        // force reloading dangling indices with a cluster state republish
+        client().admin().cluster().prepareReroute().get();
+        ensureClosed(indexName);
+        try {
+            client().admin().indices().prepareOpen(indexName).get();
+            fail("Shouldn't be able to open an old index");
+        } catch (IndexException ex) {
+            assertThat(ex.getMessage(), containsString("unpgradable index"));
```
Comment (rjernst) [inline src/test/java/org/elasticsearch/bwcompat/OldIndexBackwardsCompatibilityTests.java]: Can we not use hamcrest? I've been trying to eliminate it everywhere I see it...
```
assertTrue(ex.getMessage(), ex.getMessage().contains("unupgradable index");
```

Also, I agree with Shay's previous comment we should have a better exception message. And I'm not even sure unupgradeable is a word...certainly not unpgradable. :)

**Comment by rjernst** [comment]
This looks pretty good, I left a few comments.

File: src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexStateService.java (hunk 1 above)
Comment (imotov) [inline src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexStateService.java]: @kimchy I will change it to "cannot open the index due to upgrade failure" unless you have better suggestions. The reason why this index cannot be upgraded and possible remedies will be in the inner exception that will be returned as part of the response, so there is probably no reason to repeat them in this exception as well.

File: src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java (hunk 4 above)
Comment (imotov) [inline src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: I was just trying to stay consistent with MetaDataIndexAliasesService, MetaDataIndexStateService, and MetaDataIndexTemplateService.

Comment (rjernst) [inline src/main/java/org/elasticsearch/cluster/metadata/MetaDataIndexUpgradeService.java]: Ok, didn't know about those...I guess keep for consistency...

**Comment by imotov** [comment]
@kimchy, @rjernst I pushed changes addressing your comments.

**Comment by rjernst** [comment]
LGTM

**Comment by clintongormley** [comment]
> @kimchy correct, if a cluster contains at least one index that was created before 0.90 such cluster will have to be upgraded to v1.6 before it can be upgraded to 2.0.

Or the index can be closed, and have the setting updated manually, without upgrading to 1.6.  The migration plugin https://github.com/elastic/elasticsearch-migration/ checks for minimum segment version and checks for the presense of this setting.  We could add a link to instructions about how to set it without upgrading
