### PR TITLE
Fix IndexAuditTrail rolling restart on rollover edge

### LINKED ISSUE #33867: [CI] IndexAuditUpgradeIT.testAuditLogs fails
## Reproduction line
does not reproduce locally
```
 ./gradlew :x-pack:qa:rolling-upgrade:with-system-key:v6.3.1#upgradedClusterTestRunner \
  -Dtests.seed=57D936B12E792F96 \
  -Dtests.class=org.elasticsearch.upgrades.IndexAuditUpgradeIT \
  -Dtests.method="testAuditLogs" \
  -Dtests.security.manager=true \
  -Dtests.locale=bg \
  -Dtests.timezone=Pacific/Marquesas
```

## Example relevant log:
```
00:00:46    > Throwable #1: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2343, key=upgraded-node-0}, {doc_count=2175, key=node-1}, {doc_count=2106, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 	at __randomizedtesting.SeedInfo.seed([57D936B12E792F96:300A75E395A08B0D]:0)
00:00:46    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 	at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 	at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:830)
00:00:46    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:804)
00:00:46    > 	at org.elasticsearch.upgrades.IndexAuditUpgradeIT.testAuditLogs(IndexAuditUpgradeIT.java:68)
00:00:46    > 	at java.lang.Thread.run(Thread.java:748)
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+6.4+bwc-tests/x-pack/qa/rolling-upgrade/with-system-key/build/testrun/v6.3.1#upgradedClusterTestRunner/J0/temp/org.elasticsearch.upgrades.IndexAuditUpgradeIT_57D936B12E792F96-001
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46   2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=174, maxMBSortInHeap=7.47073894872366, sim=RandomSimilarity(queryNorm=true): {}, locale=bg, timezone=Pacific/Marquesas
00:00:46   2> NOTE: Linux 4.4.0-1061-aws amd64/Oracle Corporation 1.8.0_181 (64-bit)/cpus=16,threads=1,free=433534592,total=514850816
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46   2> NOTE: All tests run in this JVM: [IndexingIT, RollupIDUpgradeIT, TokenBackwardsCompatibilityIT, IndexAuditUpgradeIT]
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=1983, key=upgraded-node-0}, {doc_count=1794, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=2025, key=upgraded-node-0}, {doc_count=1841, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2175, key=node-1}, {doc_count=2141, key=upgraded-node-0}, {doc_count=1933, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46    > 	Suppressed: java.lang.AssertionError: Found node buckets [{doc_count=2431, key=node-2}, {doc_count=2212, key=upgraded-node-0}, {doc_count=2175, key=node-1}, {doc_count=2000, key=upgraded-node-1}, {doc_count=891, key=node-0}]
00:00:46    > Expected: a collection with size <6>
00:00:46    >      but: collection size was <5>
00:00:46    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.assertNumUniqueNodeNameBuckets(IndexAuditUpgradeIT.java:126)
00:00:46    > 		at org.elasticsearch.upgrades.IndexAuditUpgradeIT.lambda$testAuditLogs$0(IndexAuditUpgradeIT.java:70)
00:00:46    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:818)
00:00:46    > 		... 39 more
00:00:46 Completed [4/6] in 10.40s, 1 test, 1 failure <<< FAILURES!
```

## Frequency

It happened 8 times in August, not super frequent but seems consistent.

### PR DESCRIPTION
**Pull request by albertzaharovits**
This fixes two independent bugs , both tripping integ test failures.
They are both facilitated by the rolling nature of the audit index. Moreover, they
will both manifest only during a rolling upgrade executed while the audit index
rolls over.

The bugs:
1. While rolling upgrading, the master has the responsibility to install the new index template. Non-master new nodes (upgraded before the master) should hold off from creating new indices, because of rolling over, until the new template is installed. Because of a backwards condition, `onOrAfter`, they will fail to do that and use the index template for the old nodes with the event data of the new ones.

2. Also while rolling upgrading, non-master new nodes can wait indefinitely for a mapping update. The mapping update for the audit index is also the responsibility of the master node. However the master can fail to update the mapping for a foregoing index ( for which other new nodes might have events) and only upgrade it for the following index. Precisely on clock edge, a master with no events pipelined will only try to update the new index.

Closes #33867

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java [hunk 1]
```diff
@@ -277,7 +277,7 @@ private boolean canStart(ClusterState clusterState) {
         }
 
         if (TemplateUtils.checkTemplateExistsAndVersionMatches(INDEX_TEMPLATE_NAME, SECURITY_VERSION_STRING,
-                clusterState, logger, Version.CURRENT::onOrAfter) == false) {
+                clusterState, logger, Version.CURRENT::onOrBefore) == false) {
```
Comment (albertzaharovits) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java]: bug 1.
new nodes, with a greater version, will not be stopped to create a rolled over index using an older template.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java [hunk 2]
```diff
@@ -381,7 +390,7 @@ void updateCurrentIndexMappingsIfNecessary(ClusterState state) {
             IndexMetaData indexMetaData = indices.get(0);
             MappingMetaData docMapping = indexMetaData.mapping("doc");
             if (docMapping == null) {
-                if (indexToRemoteCluster || state.nodes().isLocalNodeElectedMaster()) {
+                if (indexToRemoteCluster || state.nodes().isLocalNodeElectedMaster() || hasStaleMessage()) {
                     putAuditIndexMappingsAndStart(index);
```
Comment (albertzaharovits) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java]: bug 2.
master will only update the next rolled over index, if there are no events (on master) for the old index. However, there could be events of new nodes for the old index, whose template will never be updated.

Comment (jaymode) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java]: I'd rather have the master issue a mapping update for the previous index or indices. What do you think?

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java (hunk 1 above)
Comment (jaymode) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java]: Hmm, maybe I am misunderstanding but I don't follow the logic.

1. template does not exist so we should not start - this makes sense
2. template exists but is onOrBefore the current version of the node. On a new node, say 6.5.1, this means that if the version in the template is <= 6.5.1 that we start. Why would we start with a older template?

Comment (albertzaharovits) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java]: I think the scenario you're describing is just the scenario for `onOrAfter`:
```
public boolean onOrAfter(Version version) {
  return version.id <= id;
}
```
In this case `id` is `6.5.1` and `version.id` is the version of the template, because the predicate is `Version.CURRENT::onOrAfter` .

As another anchor, further down in the function:
```
Version.fromString(versionString).onOrAfter(Version.CURRENT)
```
is correct, because it has the template version on the left of CURRENT.

You don't want to know for how long I had been banging my head on it....

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java (hunk 2 above)
Comment (albertzaharovits) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java]: I've been entertaining this idea too. I've chosen this alternative because the code is much simpler. In the obverse, the previous index might not exist or the rollover setting might have changed during the restart, which I think is too complex to code in an already complex mayhem. 
I think the surface for the dreaded cluster update storm is acceptable, as there is a very good chance the non-master will not be in sync during the repeated start retrials.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java (hunk 1 above)
Comment (jaymode) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/index/IndexAuditTrail.java]: Gah! This is not easy to understand. For my sanity:

Version.CURRENT on new node = 6.5.1
template version = 6.5.0

Using onOrAfter would be:
`6.5.0 <= 6.5.1` = `true`

Using onOrBefore would be:
`6.5.0 >= 6.5.1` = `false`

**Review by jaymode — APPROVED** [review]

**Comment by albertzaharovits** [comment]
If you're here because of the silly commit message I blame github for failing to keep the merge message on retrying a failed squash and merge.
