### PR TITLE
Use List instead of priority queue for stable sorting in bucket sort aggregator

### LINKED ISSUE #36322: bucket_sort aggregation misplace the first bucket
**Elasticsearch version** 6.5.1

**Plugins installed**: []

**JVM version** JVM 1.8.0_192

**OS version** Debian 8.11

**Description of the problem including expected versus actual behavior:**
* Actual behavior :
   When sorting an aggregation with a `bucket_sort` based on its `_count`, if `doc_count` are equals the item that should be in first position is the last one, other items are in the right order.
* Expected :
  Every items should be in the right order, including the first one.

**Steps to reproduce:**

1. Create a basic index :
```
curl -XPUT 'http://localhost:9200/messages' -H 'Content-Type: application/json' -d '
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas" : 0
  },
  "mappings": {
    "user": {
      "properties": {
        "rank": {
          "type": "keyword"
        }
      }
    }
  }
}'
```

2. Insert one `user` with a different `rank` each time (from `a` to `d`) :

* `user` with rank `a`
```
curl -XPUT 'http://localhost:9200/messages/user/001' -H 'Content-Type: application/json' -d '
{
  "@timestamp": "2018-12-06T01:00:00+01:00",
  "rank": "a"
}'
```

* `user` with rank `b`
```
curl -XPUT 'http://localhost:9200/messages/user/002' -H 'Content-Type: application/json' -d '
{
  "@timestamp": "2018-12-06T01:00:00+01:00",
  "rank": "b"
}'
```

* `user` with rank `c`
```
curl -XPUT 'http://localhost:9200/messages/user/003' -H 'Content-Type: application/json' -d '
{
  "@timestamp": "2018-12-06T01:00:00+01:00",
  "rank": "c"
}'
```

* `user` with rank `d`
```
curl -XPUT 'http://localhost:9200/messages/user/004' -H 'Content-Type: application/json' -d '
{
  "@timestamp": "2018-12-06T01:00:00+01:00",
  "rank": "d"
}'
```

3. Aggregate on the `rank` property and sort by `count` with a `bucket_sort` :

```
curl -XGET 'http://localhost:9200/messages/_search?pretty=true' -H 'Content-Type: application/json' -d '
    {
      "size": 0,
      "aggregations": {
        "top_by_color": {
          "composite": {
            "size": 1000,
            "sources": [
              {
                "rank": {
                  "terms": {
                    "field": "rank",
                    "missing_bucket": true,
                    "order": "asc"
                  }
                }
              }
            ]
          },
          "aggregations": {
            "top_bucket_sort": {
              "bucket_sort": {
                "sort": [
                  {
                    "_count": {
                      "order": "asc"
                    }
                  }
                ],
                "size": 1000
              }
            }
          }
        }
      }
    }'
```

Aggregation result is :
```
    {
      "took": 1,
      "timed_out": false,
      "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
      },
      "hits": {
        "total": 4,
        "max_score": 0,
        "hits": [

        ]
      },
      "aggregations": {
        "top_by_color": {
          "after_key": {
            "rank": "d"
          },
          "buckets": [
            {
              "key": {
                "rank": "b"
              },
              "doc_count": 1
            },
            {
              "key": {
                "rank": "c"
              },
              "doc_count": 1
            },
            {
              "key": {
                "rank": "d"
              },
              "doc_count": 1
            },
            {
              "key": {
                "rank": "a"
              },
              "doc_count": 1
            }
          ]
        }
      }
    }
```

We have ranks sorted has : b, c, d, **a** instead of **a**, b, c, d.

### PR DESCRIPTION
**Pull request by chatzikalymnios**
Update BucketSortPipelineAggregator to use a List and Collections.sort() for sorting instead of a priority queue. This preserves the order for equal values. Closes #36322.

### CODE REVIEW

**Review by dimitris-athanasiou — CHANGES_REQUESTED** [review]
This change introduces a bug where when there is at least one sort field specified and the `size` parameter is set, the latter is ignored. Previously, the priority queue was ensuring we apply the `size` parameter of the `bucket_sort` aggregation. Now there is nothing applying the `size` restriction. Unfortunately, `BucketSortIT` has no proper test scenario that covers this. Before discussing the code further, it would be great if we add tests that capture the above. Also, we should definitely have a new test that checks sorting is stable.

File: server/src/main/java/org/elasticsearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java [hunk 1]
```diff
@@ -95,22 +93,22 @@ public InternalAggregation reduce(InternalAggregation aggregation, ReduceContext
...
         }
 
-        int queueSize = Math.min(from + currentSize, bucketsCount);
-        PriorityQueue<ComparableBucket> ordered = new TopNPriorityQueue(queueSize);
+        List<ComparableBucket> ordered = new ArrayList<>();
         for (InternalMultiBucketAggregation.InternalBucket bucket : buckets) {
             ComparableBucket comparableBucket = new ComparableBucket(originalAgg, bucket);
-            if (comparableBucket.skip() == false) {
-                ordered.insertWithOverflow(new ComparableBucket(originalAgg, bucket));
+            if (!comparableBucket.skip()) {
```
[the remark this answers is not in the document]
Comment (chatzikalymnios) [reply server/src/main/java/org/elasticsearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java]: Got it. Thanks!

File: server/src/test/java/org/elasticsearch/search/aggregations/pipeline/BucketSortIT.java [hunk 2]
```diff
@@ -231,6 +252,29 @@ public void testSortTermsOnSubAggregation() {
         }
     }
 
+    public void testSortTermsOnSubAggregationPreservesOrderOnEquals() {
+        SearchResponse response = client().prepareSearch(INDEX)
+            .setSize(0)
+            .addAggregation(terms("foos").field(TERM_FIELD)
+                .subAggregation(bucketSort("bucketSort", Arrays.asList(new FieldSortBuilder("_key"))))
```
Comment (dimitris-athanasiou) [inline server/src/test/java/org/elasticsearch/search/aggregations/pipeline/BucketSortIT.java]: It might be nice to name the two `bucket_sort` aggs differently for readability.

File: server/src/test/java/org/elasticsearch/search/aggregations/pipeline/BucketSortIT.java [hunk 3]
```diff
@@ -231,6 +252,29 @@ public void testSortTermsOnSubAggregation() {
...
+                .subAggregation(bucketSort("bucketSort", Arrays.asList(new FieldSortBuilder("max")))))
+            .get();
+
+        assertSearchResponse(response);
+
+        Terms terms = response.getAggregations().get("foos");
+        assertThat(terms, notNullValue());
+        List<? extends Terms.Bucket> termsBuckets = terms.getBuckets();
+
+        // Since all max values are equal, we expect the order fo the first bucketSort to have been preserved
```
Comment (dimitris-athanasiou) [inline server/src/test/java/org/elasticsearch/search/aggregations/pipeline/BucketSortIT.java]: Nice idea!

File: server/src/main/java/org/elasticsearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java [hunk 4]
```diff
@@ -95,22 +93,22 @@ public InternalAggregation reduce(InternalAggregation aggregation, ReduceContext
...
         for (InternalMultiBucketAggregation.InternalBucket bucket : buckets) {
             ComparableBucket comparableBucket = new ComparableBucket(originalAgg, bucket);
             if (comparableBucket.skip() == false) {
-                ordered.insertWithOverflow(new ComparableBucket(originalAgg, bucket));
+                ordered.add(new ComparableBucket(originalAgg, bucket));
             }
         }
 
-        int resultSize = Math.max(ordered.size() - from, 0);
+        Collections.sort(ordered, Collections.reverseOrder());
```
Comment (dimitris-athanasiou) [inline server/src/main/java/org/elasticsearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java]: The fact we have to sort on reverse order seems a bit awkward here. What if we simplify? I think we can now change `ComparableBucket.compareTo` to ignore the sort order and behave like a `compareTo` promises to behave. Then in this line, we can choose to reverse order or not depending on the sort order. I think this will make it much cleaner. What do you think?

**Review by dimitris-athanasiou — COMMENTED** [review]
Thanks for adding the tests! This is looking pretty good now! I left a couple more comments regarding simplifications.

File: server/src/main/java/org/elasticsearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java (hunk 4 above)
Comment (chatzikalymnios) [reply server/src/main/java/org/elasticsearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java]: Agreed. That would make it easier to see what's happening.

Comment (chatzikalymnios) [reply server/src/main/java/org/elasticsearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java]: On second thought, we can't ignore the sort order in `ComparableBucket.compareTo` since we may be sorting buckets on multiple fields (each with a different order). Still, we can make the method return what we would normally expect from a `compareTo`. Then we won't have to sort the list in reverse and the code will make more sense overall. I will push the new version soon.

Also, the current `compareTo` (and the tests) consider `null` to be greater than any other value. Out of curiosity, is this some standard assumption, at least when it comes to Elasticsearch?

Comment (dimitris-athanasiou) [reply server/src/main/java/org/elasticsearch/search/aggregations/pipeline/BucketSortPipelineAggregator.java]: Thanks for this and sorry for the delayed response. Holidays kicked in :-) Happy new year!

Elasticsearch is handling `null` in ordinary search/sort by putting those values at the end (or the beginning when the order is descending). It also lets the user change that behaviour via the `missing` parameter. Having said that, I would argue it is overkill to support this in the context of the `bucket_sort` aggregation.

Looking more into the code, it actually looks like `ComparableBucket` could never really get any `null` values. There are 3 scenarios:

- the sort field is `_key`; keys will be non-null I believe
- `gap_policy` is `skip`; the bucket won't exist at all
- `gap_policy` is `insert_zeros`; the value of the bucket will be `0.0` and will be sorted accordingly.

So, it most probably is dead code.

**Comment by dimitris-athanasiou** [comment]
Jenkins please test this

**Comment by dimitris-athanasiou** [comment]
@elasticmachine test this please

**Comment by dimitris-athanasiou** [comment]
@chatzikalymnios Could you please rebase your PR on latest master? There were upstream changes that will cause CI to fail unless rebased.

**Comment by dimitris-athanasiou** [comment]
@elasticmachine test this please

**Comment by dimitris-athanasiou** [comment]
run default distro tests

**Comment by dimitris-athanasiou** [comment]
run gradle build tests 1

**Comment by dimitris-athanasiou** [comment]
run default distro tests

**Comment by dimitris-athanasiou** [comment]
@chatzikalymnios I'm afraid the latest rebase landed on another build which has a failing test that seems not related to this change. May I ask you to rebase one more time please? :-)

**Comment by chatzikalymnios** [comment]
@dimitris-athanasiou Sure, no worries :)

**Comment by dimitris-athanasiou** [comment]
@elasticmachine test this please

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM Thank you so much for the contribution @chatzikalymnios!

**Comment by dimitris-athanasiou** [comment]
@polyfractal Which versions do you think we should merge this in? Should we aim `6.6.0`+?

**Comment by polyfractal** [comment]
Hm, I think we probably missed the boat on 6.6, especially since this is more of an enhancement than bugfix.  Let's put it in 6.7+

Thanks @chatzikalymnios @dimitris-athanasiou!
