### PR TITLE
Handle the existence of system data streams in Get Aliases API 

### LINKED ISSUE #73218: Get Aliases API fails when a system data stream exists and security is enabled
**Elasticsearch version** (`bin/elasticsearch --version`): 7.13.0, probably all later versions

**Plugins installed**: []

**JVM version** (`java -version`): built-in

**OS version** (`uname -a` if on a Unix-like system): MacOS

**Description of the problem including expected versus actual behavior**:
When a system data stream exists and Security is enabled, the Get Alias API will always fail.

**Steps to reproduce**:

 1. Start an Elasticsearch cluster with security enabled. Perform all following steps as superuser.
 2. Create a system data stream:
```bash
curl -X POST -u elastic-admin:elastic-password "localhost:9200/.fleet-actions-results/_doc" -H 'Content-Type: application/json' -H 'X-elastic-product-origin: fleet' -d'{"@timestamp": 0}' | jq
```
 3. Attempt to use the Get Aliases API, with or without any index name, e.g. `GET _alias` or `GET _alias/auditbeat-7.13.0`.
 4. Observe the error response.

Note that the Get Alias API behaves as expected when security is not enabled.

**Provide logs (if relevant)**:
The error response:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Data stream(s) [.fleet-actions-results] use and access is reserved for system operations"
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by AthenaEryma**
This commit adjusts the behavior of the Get Aliases API to more
thoroughly prevent errors and warnings from being emitted unnecessarily
from the Get Aliases API by retrieving all indices including system ones
and only warning in the post processing of the action.

Additionally, the IndexAbstractionResolver has been updated to properly
handle system data streams when evaluating visibility.

Closes #73218
Co-authored-by: jaymode <jay@elastic.co>

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java [hunk 1]
```diff
@@ -139,6 +157,22 @@ public static boolean isIndexVisible(String expression, String index, IndicesOpt
         if (isVisible == false) {
             return false;
         }
+        if (indexAbstraction.isSystem()) {
+            // system index that backs system data stream
+            if (indexAbstraction.getParentDataStream() != null) {
+                if (indexAbstraction.getParentDataStream().isSystem() == false) {
+                    throw new IllegalStateException("system index is part of a data stream that is not a system data stream");
```
Comment (gwbrown) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java:164]: I think this is a worth candidate for promoting to an `assert` - we should never hit this case, right?

**Review by AthenaEryma — COMMENTED** [review]
I reviewed Jay's changes and this is a better fix all-around - it's slightly more code, but it's making the fix in the right place vs. piling on more hacks.

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java (hunk 1 above)
Comment (jaymode) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java:164]: it should never hit this case but I prefer this actually being detected in the wild since we don't run with assertions on normally

Comment (gwbrown) [reply server/src/main/java/org/elasticsearch/cluster/metadata/IndexAbstractionResolver.java:164]: ++, I meant along the lines of:
```java
assert false : "this means you probably wrote a bug that lets system indices be part of non data streams";
throw new IllegalStateException("system index is part of a data stream that is not a system data stream"); 
```

This shouldn't block the PR though, more maybe as a follow-up?

**Review by tvernum — APPROVED** [review]
LGTM, but given the change has moved in a direction outside of my immediate area, I may not be best placed to review it.

**Review by rjernst — APPROVED** [review]

**Review by williamrandolph — APPROVED** [review]
LGTM - I'm glad we ended up with this fix rather than just tweaking our hack. Great work, Jay and Gordon.
