### PR TITLE
Increase timeout for searchable snapshots in ILM tests

### LINKED ISSUE #137149: [CI] SearchableSnapshotActionIT testConvertingSearchableSnapshotFromFullToPartial failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11337 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/pdkmsyi3g6m2e)
- [elasticsearch-periodic-platform-support #11333 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/36u2zjuhn7754)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testResumingSearchableSnapshotFromPartialToFull" -Dtests.seed=1B768AD599FA8694 -Dtests.locale=ga -Dtests.timezone=America/Nassau -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testConvertingSearchableSnapshotFromFullToPartial'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state for index [partial-restored-myindex-ydzu] cluster state [{
  "cluster_name" : "test-cluster",
  "cluster_uuid" : "zCDoVTmvQpi7RDoJEnlhiA",
  "version" : 500,
  "state_uuid" : "gAEhH0CtQRGB0ajFnF39uA",
  "master_node" : "GARGCv3oTweseig14B3n-g",
  "blocks" : {
    "indices" : {
      "restored-myindex-ydzu" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      }
    }
  },
  "nodes" : {
    "F9aBC-nWQaqwaF5rPF9GpA" : {
      "name" : "test-cluster-3",
      "ephemeral_id" : "_NzPsBBLRCWKz8Uod3PYcA",
      "transport_address" : "127.0.0.1:62105",
      "external_id" : "test-cluster-3",
      "attributes" : {
        "testattr" : "test",
        "xpack.installed" : "true"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_wa
[truncated]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step windows-2022_checkpart5_platform-support-windows
- [main] 2 failures in test testConvertingSearchableSnapshotFromFullToPartial (2.3% fail rate in 86 executions)
- [main] 2 failures in step windows-2022_checkpart5_platform-support-windows (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #137151: [CI] SearchableSnapshotActionIT testResumingSearchableSnapshotFromPartialToFull failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11337 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/pdkmsyi3g6m2e)
- [elasticsearch-periodic-java-ea #63 / encryption-at-rest](https://gradle-enterprise.elastic.co/s/mmkpxs4aryggy)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testResumingSearchableSnapshotFromPartialToFull" -Dtests.seed=1B768AD599FA8694 -Dtests.locale=ga -Dtests.timezone=America/Nassau -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testResumingSearchableSnapshotFromPartialToFull'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state for index [partial-restored-myindex-ydzu] cluster state [{
  "cluster_name" : "test-cluster",
  "cluster_uuid" : "zCDoVTmvQpi7RDoJEnlhiA",
  "version" : 500,
  "state_uuid" : "gAEhH0CtQRGB0ajFnF39uA",
  "master_node" : "GARGCv3oTweseig14B3n-g",
  "blocks" : {
    "indices" : {
      "restored-myindex-ydzu" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      }
    }
  },
  "nodes" : {
    "F9aBC-nWQaqwaF5rPF9GpA" : {
      "name" : "test-cluster-3",
      "ephemeral_id" : "_NzPsBBLRCWKz8Uod3PYcA",
      "transport_address" : "127.0.0.1:62105",
      "external_id" : "test-cluster-3",
      "attributes" : {
        "testattr" : "test",
        "xpack.installed" : "true"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_wa
[truncated]
```

**Issue Reasons:**
- [main] 2 failures in test testResumingSearchableSnapshotFromPartialToFull (2.4% fail rate in 85 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #137153: [CI] SearchableSnapshotActionIT testDeleteActionDeletesSearchableSnapshot failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11337 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/pdkmsyi3g6m2e)
- [elasticsearch-periodic-platform-support #11333 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/36u2zjuhn7754)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testResumingSearchableSnapshotFromPartialToFull" -Dtests.seed=1B768AD599FA8694 -Dtests.locale=ga -Dtests.timezone=America/Nassau -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDeleteActionDeletesSearchableSnapshot'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state for index [partial-restored-myindex-ydzu] cluster state [{
  "cluster_name" : "test-cluster",
  "cluster_uuid" : "zCDoVTmvQpi7RDoJEnlhiA",
  "version" : 500,
  "state_uuid" : "gAEhH0CtQRGB0ajFnF39uA",
  "master_node" : "GARGCv3oTweseig14B3n-g",
  "blocks" : {
    "indices" : {
      "restored-myindex-ydzu" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      }
    }
  },
  "nodes" : {
    "F9aBC-nWQaqwaF5rPF9GpA" : {
      "name" : "test-cluster-3",
      "ephemeral_id" : "_NzPsBBLRCWKz8Uod3PYcA",
      "transport_address" : "127.0.0.1:62105",
      "external_id" : "test-cluster-3",
      "attributes" : {
        "testattr" : "test",
        "xpack.installed" : "true"
      },
      "roles" : [
        "data",
        "data_cold",
        "data_content",
        "data_frozen",
        "data_hot",
        "data_wa
[truncated]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step windows-2022_checkpart5_platform-support-windows
- [main] 2 failures in test testDeleteActionDeletesSearchableSnapshot (2.3% fail rate in 86 executions)
- [main] 2 failures in step windows-2022_checkpart5_platform-support-windows (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #137156: [CI] SearchableSnapshotActionIT testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped failing
**Build Scans:**
- [elasticsearch-periodic #11361 / encryption-at-rest](https://gradle-enterprise.elastic.co/s/oy7kfrtp7o3pi)
- [elasticsearch-periodic-platform-support #11333 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/36u2zjuhn7754)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped" -Dtests.seed=E975D8D5E6FDE415 -Dtests.locale=gsw-FR -Dtests.timezone=Asia/Manila -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state for index [restored-.ds-logs-ablommevdz-2025.10.25-000001] cluster state [{
  "cluster_name" : "test-cluster",
  "cluster_uuid" : "YoLETMF9RdOp7IBpmGstUw",
  "version" : 54,
  "state_uuid" : "bLkXvLD0RxqjU58ATX8Hzg",
  "master_node" : "fchULmQnT8OZNR5Hu2kfmA",
  "blocks" : {
    "indices" : {
      ".ds-logs-ablommevdz-2025.10.25-000001" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      },
      "fm-clone-5lax-.ds-logs-ablommevdz-2025.10.25-000001" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      }
    }
  },
  "nodes" : {
    "fchULmQnT8OZNR5Hu2kfmA" : {
      "name" : "test-cluster-1",
      "ephemeral_id" : "n0f12NjiTra1JWD9nxCAkQ",
      "transport_address" : "127.0.0.1:33789",
      "ext
[truncated]
```

**Issue Reasons:**
- [main] 2 failures in test testUpdatePolicyToAddPhasesYieldsInvalidActionsToBeSkipped (2.3% fail rate in 88 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #137166: [CI] SearchableSnapshotActionIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11340 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/7une6h7ault4u)
- [elasticsearch-periodic-platform-support #11336 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/6fts3d52gf6sq)
- [elasticsearch-periodic-platform-support #11332 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/qsjywods4f6v2)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testRestoredIndexManagedByLocalPolicySkipsIllegalActions" -Dtests.seed=41D3D0245BE5F275 -Dtests.locale=tzm -Dtests.timezone=Asia/Chongqing -Druntime.java=25
```

**Applicable branches:**
9.2

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state for index [restored-.ds-logs-dopmnkbygd-2025.10.26-000001] cluster state [{
  "cluster_name" : "test-cluster",
  "cluster_uuid" : "qXkDX57-R7ChALtnpbG4tA",
  "version" : 159,
  "state_uuid" : "5ntLWBFfTg6HC-DMkDVhMw",
  "master_node" : "5u74d2qlTmu2uKaQbNtk_g",
  "blocks" : {
    "indices" : {
      ".ds-logs-dopmnkbygd-2025.10.26-000001" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      },
      "fm-clone-gwmf-.ds-logs-dopmnkbygd-2025.10.26-000001" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      }
    }
  },
  "nodes" : {
    "Aq4Np4baTtCLjqj5XTIc0w" : {
      "name" : "test-cluster-0",
      "ephemeral_id" : "_tZcwAEFTXeVEPtn81da2Q",
      "transport_address" : "127.0.0.1:50474",
      "ex
[truncated]
```

**Issue Reasons:**
- [9.2] 3 consecutive failures in step windows-2022_checkpart5_platform-support-windows
- [9.2] 3 failures in class org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT (4.8% fail rate in 63 executions)
- [9.2] 3 failures in step windows-2022_checkpart5_platform-support-windows (100.0% fail rate in 3 executions)
- [9.2] 3 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #137167: [CI] TimeSeriesDataStreamsIT testSearchableSnapshotAction failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11341 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/3nv5myfzn2oj2)
- [elasticsearch-periodic-platform-support #11337 / windows-2022_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/pdkmsyi3g6m2e)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT.testSearchableSnapshotAction" -Dtests.seed=9EA32235A99B812B -Dtests.locale=el-GR -Dtests.timezone=Europe/Vilnius -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSearchableSnapshotAction'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state for index [restored-.ds-logs-aleejqdkaj-2025.10.26-000001] cluster state [{
  "cluster_name" : "test-cluster",
  "cluster_uuid" : "_-YaL-2lQzmFMOqdR3l4Lg",
  "version" : 220,
  "state_uuid" : "zRkQRNBJTDioPUIAk9k4Qg",
  "master_node" : "NdQ6g3ioTs-Pxjr6f9OrfQ",
  "blocks" : {
    "indices" : {
      ".ds-logs-aleejqdkaj-2025.10.26-000001" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      },
      "fm-clone-12by-.ds-logs-aleejqdkaj-2025.10.26-000001" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      }
    }
  },
  "nodes" : {
    "NdQ6g3ioTs-Pxjr6f9OrfQ" : {
      "name" : "test-cluster-3",
      "ephemeral_id" : "J0khyGYZQJeNsq_xm3ztAQ",
      "transport_address" : "127.0.0.1:57032",
      "ex
[truncated]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step windows-2022_checkpart5_platform-support-windows
- [main] 2 failures in test testSearchableSnapshotAction (4.9% fail rate in 41 executions)
- [main] 2 failures in step windows-2022_checkpart5_platform-support-windows (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nielsbauman**
As of #133954, we clone indices before performing the force-merge step in the `searchable_snapshot` action. On slow CI servers, 10 seconds for the index to go through the whole `searchable_snapshot` action isn't enough, so we bump the timeout to 20 seconds.

I looked at the logs of a few test failures, and ILM was clearly still progressing when the test timed out. I didn't identify any particular step that was taking extraordinarily long; there were always just a few steps that took a bit longer. I would love to make these tests faster rather than bumping the timeout, but the `searchable_snapshot` action is simply one of the largest ILM actions and ILM itself isn't particularly fast.

That being said, if a timeout of 20 seconds proves to be insufficient (i.e. test failures come back), I do think it's worth having a look at reducing the runtime of the tests somehow first before we increase the timeout further.

Closes #137149
Closes #137151
Closes #137152
Closes #137153
Closes #137156
Closes #137166
Closes #137167
Closes #137192

### CODE REVIEW

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/SearchableSnapshotActionIT.java [hunk 1]
```diff
@@ -459,7 +459,7 @@ public void testRestoredIndexManagedByLocalPolicySkipsIllegalActions() throws Ex
         restoreSnapshot.setJsonEntity("{\"indices\": \"" + dataStream + "\", \"include_global_state\": false}");
         assertOK(client().performRequest(restoreSnapshot));
 
-        assertThat(indexExists(searchableSnapMountedIndexName), is(true));
+        awaitIndexExists(searchableSnapMountedIndexName);
```
Comment (PeteGillinElastic) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/SearchableSnapshotActionIT.java:462]: Just checking, this one doesn't need the extended timeout?

**Review by PeteGillinElastic — APPROVED** [review]
Thanks as always.

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/SearchableSnapshotActionIT.java [hunk 2]
```diff
@@ -233,7 +233,7 @@ public void testDeleteActionDeletesSearchableSnapshot() throws Exception {
         Map<String, LifecycleAction> coldActions = Map.of(SearchableSnapshotAction.NAME, new SearchableSnapshotAction(snapshotRepo));
         Map<String, Phase> phases = new HashMap<>();
         phases.put("cold", new Phase("cold", TimeValue.ZERO, coldActions));
-        phases.put("delete", new Phase("delete", TimeValue.timeValueMillis(10000), Map.of(DeleteAction.NAME, WITH_SNAPSHOT_DELETE)));
+        phases.put("delete", new Phase("delete", TimeValue.ZERO, Map.of(DeleteAction.NAME, WITH_SNAPSHOT_DELETE)));
```
Comment (nielsbauman) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/SearchableSnapshotActionIT.java:236]: By the way, FTR, I changed this value from `10s` to `0s` because there is no point in waiting 10 seconds before we delete the searchable snapshotted index; we can just delete it immediately without compromising the flakiness or value of this test.

**Review by szybia — APPROVED** [review]

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/SearchableSnapshotActionIT.java (hunk 1 above)
Comment (nielsbauman) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/actions/SearchableSnapshotActionIT.java:462]: Nope, this is just waiting for the index to be restored after the `_restore` API from a few lines before. That should definitely not take more than 10 seconds. Thanks for checking!

**Comment by nielsbauman** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/137524)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
