### PR TITLE
Minor fixes to improve SystemIndexDescriptor

### LINKED ISSUE #112946: Creating a System Index in a mixed cluster with different mapping versions fail
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

Auto creating an internal managed system index fails in a mixed cluster where the nodes have different views of the index mapping version. In this example the `.inference` index mappings have been updated in the new version. Auto creating the index in a mixed cluster by writing to it sometimes fails with the message:

```
[auto-create index] failed - system index [.inference] requires all data and master nodes to have mappings versions at least of version [MappingsVersion[version=2, hash=1431251844]]
```

The message indicates the action is intentional but the failure does not occur every time, sometimes the index is created and other times it is not. If it is intentional to block index creation in a mixed cluster it should do so every time.

`SystemIndexMappingUpdateService` will update the mappings for the index once all nodes in the cluster have been upgraded. Given that eventually the mappings will be correct is there a reason for blocking the creation in a mixed cluster.

### Steps to Reproduce

Any mixed cluster test which create a system index through write to the index could be used. The easiest example I have uses the mixed cluster test suite in the Inference Plugin.

1. Increment `INDEX_MAPPING_VERSION` in for the inference secrets index. 

https://github.com/elastic/elasticsearch/blob/48ea474953fb365a65dd7f17741ed5d66b6fc269/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/InferenceSecretsIndex.java#L29

2. Run the mixed cluster tests with the previous version of Elasticsearch (8.16.0 in this case)
```
./gradlew :x-pack:plugin:inference:qa:mixed-cluster:v8.16.0#javaRestTest
```

The test does not fail every time but over multiple runs it does fail reproducibly. When it fails it will fail with a message like:
```
[auto-create index] failed - system index [.secrets-inference] requires all data and master nodes to have mappings versions at least of version [MappingsVersion[version=2, hash=-1434574148]]
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ldematte**
Closes https://github.com/elastic/elasticsearch/issues/112946

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java [hunk 1]
```diff
@@ -555,38 +555,19 @@ public MappingsVersion getMappingsVersion() {
...
-
-    /**
-     * Gets a standardized message when the node contains a data or master node whose version is less
-     * than that of the minimum supported version of this descriptor and its prior descriptors.
-     *
-     * @param cause the action being attempted that triggered the check. Used in the error message.
-     * @return the standardized error message
-     */
-    @Deprecated
-    public String getMinimumNodeVersionMessage(String cause) {
```
Comment (ldematte) [inline server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java:579]: Removed because unused

File: server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java [hunk 2]
```diff
@@ -555,38 +555,19 @@ public MappingsVersion getMappingsVersion() {
...
-    public String getMinimumMappingsVersionMessage(String cause) {
+    public String getMinimumMappingsVersionMessage(String cause, MappingsVersion requiredMinimumMappingVersion) {
         Objects.requireNonNull(cause);
         final MappingsVersion actualMinimumMappingsVersion = priorSystemIndexDescriptors.isEmpty()
             ? getMappingsVersion()
             : priorSystemIndexDescriptors.get(priorSystemIndexDescriptors.size() - 1).mappingsVersion;
         return Strings.format(
-            "[%s] failed - system index [%s] requires all data and master nodes to have mappings versions at least of version [%s]",
+            "[%s] failed - requested creation of system index [%s] with version [%s], which is greater than the cluster minimum index "
+                + "mapping version. Ensure that the system index descriptor for [%s] includes a prior definition for version [%s]",
```
Comment (prdoyle) [inline server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java:565]: This message text seems confusing. As a user, I'd think if the requested version is _greater_ than the minimum, that should be acceptable.

File: server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java [hunk 3]
```diff
@@ -335,7 +334,8 @@ protected SystemIndexDescriptor(
                 if (prior.primaryIndex.equals(primaryIndex) == false) {
                     throw new IllegalArgumentException("primary index must be the same");
                 }
-                if (prior.aliasName.equals(aliasName) == false) {
+                if ((prior.aliasName == null && aliasName != null)
+                    || (prior.aliasName != null && prior.aliasName.equals(aliasName) == false)) {
```
Comment (prdoyle) [inline server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java:338]: How about `Objects.equals(prior.aliasName, aliasName)`?

File: server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java (hunk 2 above)
Comment (ldematte) [reply server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java:565]: The message is really meant for developers, giving instruction on what to do.
It will read something like
"[auto-create] failed - requested creation of system index [.secrets] with version [2], which is greater than the cluster minimum index mapping version. Ensure that the system index descriptor for [.secrets] includes a prior definition for version [1]"

Maybe I can change it to 
"[auto-create] failed - requested creation of system index [.secrets] with version [2], which is greater than the   index mapping version supported by the cluster. Ensure that the system index descriptor for [.secrets] includes a prior definition for version [1]".

While it's true devs know that the cluster supports versions up to the minimum common of all versions from each node, maybe just saying "supported by the cluster" is better/clearer.

Comment (ldematte) [reply server/src/main/java/org/elasticsearch/indices/SystemIndexDescriptor.java:565]: @prdoyle Wdyt of the updated message?

**Review by prdoyle — APPROVED** [review]
LGTM
