### PR TITLE
Fix analyzer alias processing

### LINKED ISSUE #19163: ES 5 Doesn't allow registering default analyzer
**Elasticsearch version**: 5.0.0-alpha3

**JVM version**: 1.8.0_73-b02

**OS version**: CentOS Linux release 7.2.1511

**Description of the problem including expected versus actual behavior**:
I'm trying to upgrade an ES plugin from 2.3 to 5.0.0-alpha3, and a template we previously had working is now causing an issue. The template attempts to set some default analyzers for an index, but when the index is created it throws an error saying there's already an analyzer with the default name. 

Here's the template I'm using:
`{
  "order": 0, 
  "settings": {
    "index.analysis.analyzer.fairhairIndexAnalyzerv3.alias": "default",
    "index.analysis.analyzer.fairhairIndexAnalyzerv3.type": "fairhair-index-analyzer",
    "index.analysis.analyzer.fairhairTokenizingAnalyzer.type": "fairhair-tokenizing-analyzer",
    "index.analysis.analyzer.fairhairTokenizingAnalyzer.alias": "default_search"
  },
"mappings" : {
   //some mappings
},
"template" : "document.*"
}`

**Provide logs (if relevant)**:
Here's the error stack trace I get:
`elasticsearch_1  | [2016-06-28 23:40:43,871][DEBUG][action.admin.indices.create] [Iridia] [document.document-20151106] failed to create
elasticsearch_1  | java.lang.IllegalStateException: already registered analyzer with name: default
elasticsearch_1  | 	at org.elasticsearch.index.analysis.AnalysisService.<init>(AnalysisService.java:109)
elasticsearch_1  | 	at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:161)
elasticsearch_1  | 	at org.elasticsearch.index.IndexService.<init>(IndexService.java:138)
elasticsearch_1  | 	at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:328)
elasticsearch_1  | 	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:398)
elasticsearch_1  | 	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:363)
`

I've looked at the AnalysisService class constructor, and I see it does a check for analyzers with the name "default" in the passed in analyzer mappings. I believe these conditional statements fire:

`if (!analyzerProviders.containsKey("default")) {
            analyzerProviders.put("default", new StandardAnalyzerProvider(indexSettings, null, "default", Settings.Builder.EMPTY_SETTINGS));
        }
        if (!analyzerProviders.containsKey("default_search")) {
            analyzerProviders.put("default_search", analyzerProviders.get("default"));
        }
        if (!analyzerProviders.containsKey("default_search_quoted")) {
            analyzerProviders.put("default_search_quoted", analyzerProviders.get("default_search"));
        }`

So it registers the standard analyzer, but while iterating through the passed in analyzers, this check also fires:

`if (analyzers.containsKey(name)) { //Grabs the name from each entry in analyzer map
                throw new IllegalStateException("already registered analyzer with name: " + name);
            }`

I'm confused as to how both these conditions are firing. This check to see if the current map of analyzers already contains the key "name" was introduced in ES 5. 

EDIT: I know why the illegal state exception is being thrown. The Analysis Registry automatically adds the entry: "default" => StandardAnalyzer. So from what I can tell, it's actually impossible to register your own default index analyzer, since there will always be the standard analyzer. I think the check for whether a name is already in the analyzer mappings is a bug and should be removed.

### PR DESCRIPTION
**Pull request by s1monw**
In the lack of tests the analyzer.alias feature was pretty much not working
at all on current master. Issues like #19163 showed some serious problems for users
using this feature upgrading to an alpha version.
This change fixes the processing order and allows aliases to be set for
existing analyzers like `default`. This change also ensures that if `default`
is aliased the correct analyzer is used for `default_search` etc.

Closes #19163

### CODE REVIEW

**Comment by rjernst** [comment]
I know it has existed for a while, but I never knew about the feature until now. What problem does it solve? It seems to add indirection without any benefit (an alias should not be able to be changed, or it would mean an analyzer could be swapped out, which would completely break existing mappings using it).

File: core/src/test/java/org/elasticsearch/index/mapper/string/SimpleStringMappingTests.java [hunk 1]
```diff
@@ -301,6 +301,31 @@ public void testSearchAnalyzerSerialization() throws IOException {
...
+            .startObject("properties")
+            .startObject("field")
+            .field("type", "string")
+            .field("analyzer", "default")
+            .field("search_analyzer", "keyword")
+            .endObject()
+            .endObject().endObject().endObject().string();
+
+        mapper = parser.parse("type", new CompressedXContent(mapping));
+        assertEquals(mapping,  mapper.mappingSource().toString());
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/index/mapper/string/SimpleStringMappingTests.java]: we should probably have the same tests in TextFieldMapperTests?

File: core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java [hunk 2]
```diff
@@ -435,9 +435,9 @@ protected final void doXContentAnalyzers(XContentBuilder builder, boolean includ
             boolean hasDifferentSearchQuoteAnalyzer = fieldType().searchAnalyzer().name().equals(fieldType().searchQuoteAnalyzer().name()) == false;
             if (includeDefaults || hasDefaultIndexAnalyzer == false || hasDifferentSearchAnalyzer || hasDifferentSearchQuoteAnalyzer) {
                 builder.field("analyzer", fieldType().indexAnalyzer().name());
-                if (hasDifferentSearchAnalyzer || hasDifferentSearchQuoteAnalyzer) {
+                if (includeDefaults || hasDifferentSearchAnalyzer || hasDifferentSearchQuoteAnalyzer) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java]: I'm curious if that was important for the fix or if it is just for consistency?

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java]: this is just consistency - I didnt' have to fix this part since it was a bug in the AnalysisSerivice after all

File: core/src/test/java/org/elasticsearch/index/mapper/string/SimpleStringMappingTests.java (hunk 1 above)
Comment (s1monw) [inline core/src/test/java/org/elasticsearch/index/mapper/string/SimpleStringMappingTests.java]: I can add those

**Comment by s1monw** [comment]
> I know it has existed for a while, but I never knew about the feature until now. What problem does it solve? It seems to add indirection without any benefit (an alias should not be able to be changed, or it would mean an analyzer could be swapped out, which would completely break existing mappings using it).

it does - I am going to open an issue to remove it but I first need to find a good way for BWC. Until then I want it at least to work without relying on hash map iteration order

**Comment by s1monw** [comment]
@jpountz I pushed new tests

**Comment by jpountz** [comment]
LGTM

**Comment by s1monw** [comment]
test this please
