### PR TITLE
Remove Overly Strict Safety Mechnism in Shard Snapshot Logic

### LINKED ISSUE #57198: Snapshot Shard Directory in Repository Can Become Corrupted in Unlikely Corner Case
There is one very unlikely scenario in which a repository can get into a corrupt state where new snapshots cannot be taken for a certain index (**no data loss though for existing snapshots**).
The way this can happen is as follows:

1. Start to snapshot an index into a repository that does not yet contain a snapshot of an index by the same name
2. Snapshot on the data node is written fully to the repository but fails to send the network request to the master to notify the master about the fact that the snapshot worked out and then disconnects

What will happen in this scenario is that the master will write a new `index-N` blob (`RepositoryData`) that contains a the uuid for the index path in the repository but does not contain any shard generations for the shard that was just fully written.

On a subsequent snapshot, the master node will not interpret the index as newly created in the repository and will try to find the correct `index-{UUID/N}` blob for the shard in the shard directory. Since no shard generation is tracked in `RepositoryData` it assumes it will find an `index-N` blob where `N` is a number. Instead it will find the previously written but never referenced `index-{UUID}` blob from the snapshot that failed to signal completion back to master. This causes a safety mechanism to kick in and an exception is thrown:

```
java.lang.IllegalStateException: Could not find a readable index-N file in a non-empty shard snapshot directory 
```

NOTE: it is fairly unlikely to get into this state in practice (data node has to disconnect from master at just the right time during the first snapshot of a multi-shard index) and it cannot cause any data loss so the impact of this bug should be very low. It affects all versions 7.6 and newer and so far we only had a single report of it. 
The workaround is to delete all snapshot(s) that reference the so broken index in the repository to remove the broken shard directory.

### PR DESCRIPTION
**Pull request by original-brownbear**
Unfortunately, we cannot have a safety mechanism like this where we throw whenever we find unreadable
data in a shard.
This breaks in the case of an older ES version (without shard generations enabled) having failed to snapshot
a shard snapshot after writing some data to its path and having finalized it for example.
Another example of where we can't support this check is the test I added, if we snapshot an index with a name
that already exists in the repository and more shards than the existing index, fail doing that and then retry snapshotting it we will also see unexpected data in the path.

We could technically do deeper inspections on the unexpected data but I don't think it's worth it really. In the end if we are
unable to read the data here it's broken anyway. By moving to a new `index-` blob in the shard directory I don't see us ever
corrupting existing data and since we (by virtue of moving to an empty generation) won't do any incremental work on top of
potentially corrupt data we also do not risk creating broken snapshots going forward.
=> Just logging a warning in this very unlikely case is the best we can do I think (this is also what we used to do up until `7.6` anyway)

closes #57198

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 1]
```diff
@@ -2128,8 +2128,7 @@ public BlobStoreIndexShardSnapshot loadShardSnapshot(BlobContainer shardContaine
             return new Tuple<>(shardSnapshots, latest);
         } else if (blobs.stream().anyMatch(b -> b.startsWith(SNAPSHOT_PREFIX) || b.startsWith(INDEX_FILE_PREFIX)
                                                                               || b.startsWith(UPLOADED_DATA_BLOB_PREFIX))) {
-            throw new IllegalStateException(
-                "Could not find a readable index-N file in a non-empty shard snapshot directory [" + shardContainer.path() + "]");
+            logger.warn("Could not find a readable index-N file in a non-empty shard snapshot directory [" + shardContainer.path() + "]");
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java:2131]: I thought about whether this is ok or not quite a bit. I think we're not introducing any new risk qualitatively really. If we can't read what is in this directory it's broken, period.

For snapshot creation:
We can have some freak concurrency issues here if we aren't yet using shard generations and two data nodes try to write to the same path at the same time. But those we resolve either (on S3) by using the 3 minute wait or by not allowing overwrites for index-N on other types of repos. With shard generations being used, this is a non-issue anyway.
For deletions we are in the clear also, because everything runs on the master.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Yannick!
