### PR TITLE
Use zen2 with testclusters

### LINKED ISSUE #37218: Test Clusters integration test fails: time out waiting for cluster
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8,nodes=virtual&&linux/166/console

```
18:25:19       [myTestCluster][2019-01-07T16:25:15,527][INFO ][o.e.n.Node               ] [node-myTestCluster] initialized
18:25:19       [myTestCluster][2019-01-07T16:25:15,527][INFO ][o.e.n.Node               ] [node-myTestCluster] starting ...
18:25:19       [myTestCluster][2019-01-07T16:25:15,893][INFO ][o.e.t.TransportService   ] [node-myTestCluster] publish_address {127.0.0.1:40711}, bound_addresses {[::1]:46791}, {127.0.0.1:40711}
18:25:19       [myTestCluster][2019-01-07T16:25:15,937][WARN ][o.e.b.BootstrapChecks    ] [node-myTestCluster] the default discovery settings are unsuitable for production use; at least one of [discovery.zen.ping.unicast.hosts, discovery.zen.hosts_provider, cluster.initial_master_nodes] must be configured
18:25:19       [myTestCluster][2019-01-07T16:25:15,972][INFO ][o.e.c.c.ClusterBootstrapService] [node-myTestCluster] no discovery configuration found, will perform best-effort cluster bootstrapping after [3s] unless existing master is discovered
```

We will need to add the zen2 specific configuration that was done for `ClusterFormationTasks` in #36300 and #36398 to test-clusters.

### PR DESCRIPTION
**Pull request by alpar-t**
Use Zen2 by default for test-clusters. 
More detailed configuration will be added as needed.

Closes #37218

### CODE REVIEW

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 1]
```diff
@@ -342,6 +342,10 @@ private void configure() {
         if (Version.fromString(version).getMajor() >= 6) {
             config.put("cluster.routing.allocation.disk.watermark.flood_stage", "1b");
         }
+        if (Version.fromString(version).onOrAfter(Version.fromString("6.5.0"))) {
+            config.put("discovery.type", "zen2");
```
Comment (ywelsch) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: zen2 is the default. Why is this change necessary? These tests are probably already running with Zen2 unless explicitly disabled in some place

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 2]
```diff
@@ -342,6 +342,10 @@ private void configure() {
...
+            config.put("cluster.initial_master_nodes", "1");
```
Comment (ywelsch) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Unless your node is named "1", this is not a valid configuration. Please have a look at the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-discovery.html) or reach out to @DaveCTurner or me on how to configure this. Note that if your tests are running a single node in development mode, then no configuration should be necessary.

**Review by ywelsch — CHANGES_REQUESTED** [review]

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java (hunk 1 above)
Comment (DaveCTurner) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Also `zen2` is only available in ≥7.0 so `onOrAfter(6.5.0)` looks wrong.

Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: My goal was to avoid the 3s delay. Will look into it, thanks !

Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: I removed `discovery.type`, sorry was looking at an older PR.

**Comment by atorok** [comment]
@ywelsch can you take another look please.

**Review by ywelsch — APPROVED** [review]
Note that this will only make sense as long as your testclusters consist of a single node.
