### PR TITLE
[ES|QL] Simplify patterns for subfields

### LINKED ISSUE #110845: ESQL: If query lists many many many many fields then the internal field caps action will fail
### Description

This is what the error message looks like:
```
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: too_complex_to_determinize_exception: Determinizing automaton with 2254 states and 2347 transitions would require more than 10000 effort.
	at org.apache.lucene.util.automaton.Operations.determinize(Operations.java:735)
	at org.apache.lucene.util.automaton.RunAutomaton.<init>(RunAutomaton.java:72)
	at org.apache.lucene.util.automaton.CharacterRunAutomaton.<init>(CharacterRunAutomaton.java:36)
	at org.apache.lucene.util.automaton.CharacterRunAutomaton.<init>(CharacterRunAutomaton.java:23)
	at org.elasticsearch.common.regex.Regex.simpleMatcher(Regex.java:128)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$NodeTransportHandler.lambda$messageReceived$0(TransportFieldCapabilitiesAction.java:541)
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:348)
```

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves: #110845

ESQL builds subfieldNames as input to `IndexResolver`,  and `IndexResolver` calls field_caps with these field names. For example, if f1, f2, f3 are specified in the query, ESQL provides f1, f2, f3, f1.*, f2.*, f3.* to `IndexResolver`.

When the field and subfield names get complicated - it could be the field names themselves are complicated or there are too many fields, or a combination of both, Regex may throw `TooComplexToDeterminizeException` when processing `Automaton`.

This PR reduce the number of Automaton created by combining similar patterns for subfield names end with ".*".

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/regex/Regex.java [hunk 1]
```diff
@@ -48,6 +48,10 @@ public static boolean isSuffixMatchPattern(String str) {
         return str.length() > 1 && str.indexOf('*') == str.length() - 1;
     }
 
+    public static boolean isDottedWildcard(String str) {
+        return isSuffixMatchPattern(str) && str.endsWith(".*");
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/common/regex/Regex.java:52]: Could you add javadoc to this method and `isSuffixMatchPattern`. The name `isSuffixMatchPattern` doesn't scream "this matches a string followed by anything followed by more stuff.

Come to think about it, `isDottedWildcard` might be better named `isSuffixWildcard`. Or something. In my head I call these "prefix matches" so I don't use the word `suffix`. But the rest of the code does. I dunno. grumbling about names.

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java [hunk 2]
```diff
@@ -557,7 +558,12 @@ public void messageReceived(FieldCapabilitiesNodeRequest request, TransportChann
                     .stream()
                     .collect(Collectors.groupingBy(ShardId::getIndexName));
                 final FieldCapabilitiesFetcher fetcher = new FieldCapabilitiesFetcher(indicesService, request.includeEmptyFields());
-                final Predicate<String> fieldNameFilter = Regex.simpleMatcher(request.fields());
+                Predicate<String> fieldNameFilter;
+                try {
+                    fieldNameFilter = Regex.simpleMatcher(request.fields());
+                } catch (TooComplexToDeterminizeException e) {
+                    throw new IllegalArgumentException("The field names are too complex to process. " + e.getMessage());
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:565]: Could you add a yaml test to make sure this comes out as a nice 400? I'm pretty sure it does, but those tests are mostly to make sure we don't break it in nine months.

**Review by nik9000 — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/common/regex/Regex.java (hunk 1 above)
Comment (fang-xing-esql) [reply server/src/main/java/org/elasticsearch/common/regex/Regex.java:52]: > Could you add javadoc to this method and `isSuffixMatchPattern`. The name `isSuffixMatchPattern` doesn't scream "this matches a string followed by anything followed by more stuff.
> 
> Come to think about it, `isDottedWildcard` might be better named `isSuffixWildcard`. Or something. In my head I call these "prefix matches" so I don't use the word `suffix`. But the rest of the code does. I dunno. grumbling about names.

Will add javadoc for both of them. Thinking about it more, perhaps I'll just use the existing `isSuffixMatchPattern`, instead of adding `isDottedWildcard` .

File: server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java (hunk 2 above)
Comment (fang-xing-esql) [reply server/src/main/java/org/elasticsearch/action/fieldcaps/TransportFieldCapabilitiesAction.java:565]: Added a test in `RestEsqlTestCase`.

**Review by nik9000 — APPROVED** [review]
