### PR TITLE
allocation: fix up random long usage with inclusive bound

### LINKED ISSUE #139161: [CI] WriteLoadConstraintMonitorTests testHotspotCountTurnsOff failing
**Build Scans:**
- [elasticsearch-intake #32090 / part1](https://gradle-enterprise.elastic.co/s/3ia3ndoxt47hi)
- [elasticsearch-pull-request #108211 / part-1](https://gradle-enterprise.elastic.co/s/egyotpnusccuw)
- [elasticsearch-pull-request #108185 / part-1](https://gradle-enterprise.elastic.co/s/rm7us3ilcub36)
- [elasticsearch-pull-request #108085 / part-1](https://gradle-enterprise.elastic.co/s/pgir5ykmig4jo)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.cluster.routing.allocation.WriteLoadConstraintMonitorTests.testHotspotCountTurnsOff" -Dtests.seed=B7C7B4A01F47483E -Dtests.locale=kxv-Telu-IN -Dtests.timezone=Australia/LHI -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.cluster.routing.allocation.WriteLoadConstraintMonitorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testHotspotCountTurnsOff'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected:<[2, 1, 0]> but was:<[2, 1, 1]>
```

**Issue Reasons:**
- [main] 4 failures in test testHotspotCountTurnsOff (2.2% fail rate in 183 executions)
- [main] 3 failures in step part-1 (3.2% fail rate in 93 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (3.3% fail rate in 91 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by schase-es**
In the write load constraint monitor tests, the criteria for specifying a non-hotspot node generated a random queue latency between 0 and the hotspot threshold setting. In usage, the random number generation used the threshold as an inclusive bound, while it needed to be an exclusive bound. This became an issue recently, with the addition of tests that specify a certain number of hotspot nodes, and remove them individually throughout the test (testHotspotCountTurnsOff).

Fixes: #139161

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/WriteLoadConstraintMonitorTests.java [hunk 1]
```diff
@@ -660,6 +660,7 @@ private static ClusterInfo createClusterInfoWithHotSpots(
         long queueLatencyThresholdMillis,
         int highUtilizationThresholdPercent
     ) {
+        assert queueLatencyThresholdMillis > 0 : "queue latency threshold must be positive";
```
Comment (DiannaHohensee) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/WriteLoadConstraintMonitorTests.java:663]: I think with this check you've highlighted an issue with the production code :) 

If we ever set the threshold to zero, everything would be a hot-spot. So either the canRemain check must be `>latency_threshold`, or zero must be an invalid latency_threshold value.

Not something to resolve now, though. Filed https://elasticco.atlassian.net/browse/ES-13741.

**Review by DiannaHohensee — APPROVED** [review]
Looks like you shook loose a pre-existing bug :) Lgtm 👍
