### PR TITLE
[ML Data Frame] Set DF task state to stopped when stopping  

### LINKED ISSUE #42441: [ML Data Frame] Task state incorrectly reported
After the data frame is stopped the indexer state == `stopped` but the task state remains `started`

taskstate

cc @dolaru

### PR DESCRIPTION
**Pull request by davidkyle**
Set the state to stopped prior to persisting 

Closes #42441

### CODE REVIEW

File: x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformPersistentTasksExecutor.java [hunk 1]
```diff
@@ -223,18 +222,8 @@ private void startTask(DataFrameTransformTask buildTask,
                            DataFrameTransformTask.ClientDataFrameIndexerBuilder indexerBuilder,
                            Long previousCheckpoint,
                            ActionListener<StartDataFrameTransformTaskAction.Response> listener) {
-        // If we are stopped, and it is an initial run, this means we have never been started,
-        // attempt to start the task
-
         buildTask.initializeIndexer(indexerBuilder);
-        // TODO isInitialRun is false after relocation??
-        if (buildTask.getState().getTaskState().equals(DataFrameTransformTaskState.STOPPED) && buildTask.isInitialRun()) {
```
Comment (davidkyle) [inline x-pack/plugin/data-frame/src/main/java/org/elasticsearch/xpack/dataframe/transforms/DataFrameTransformPersistentTasksExecutor.java]: After the change to start the DF directly rather than waiting for the scheduler to do this check means the task would never start if state == STARTED i.e. after relocating from a failed node.

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Review by benwtrent — APPROVED** [review]
