### PR TITLE
Move nio channel initialization to event loop

### LINKED ISSUE #41071: AutoFollowIT#testCleanFollowedLeaderIndexUUIDs failures
On 7.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-darwin-compatibility/99/console

Could not reproduce locally on 7.x:
```
./gradlew :x-pack:plugin:ccr:internalClusterTest --tests "org.elasticsearch.xpack.ccr.AutoFollowIT.testCleanFollowedLeaderIndexUUIDs" \
  -Dtests.seed=CB4054056BD16251 \
  -Dtests.security.manager=true \
  -Dtests.locale=el-CY \
  -Dtests.timezone=America/Santo_Domingo \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Stacktraces:
```
java.lang.RuntimeException: failed to start nodes
	at org.elasticsearch.test.InternalTestCluster.startAndPublishNodesAndClients(InternalTestCluster.java:1672)
	at org.elasticsearch.test.InternalTestCluster.reset(InternalTestCluster.java:1214)
	at org.elasticsearch.test.InternalTestCluster.beforeTest(InternalTestCluster.java:1110)
	at org.elasticsearch.xpack.CcrIntegTestCase.startClusters(CcrIntegTestCase.java:171)
	[...]
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: failed to connect to remote clusters
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.elasticsearch.test.InternalTestCluster.startAndPublishNodesAndClients(InternalTestCluster.java:1667)
	... 39 more
Caused by: java.lang.IllegalStateException: failed to connect to remote clusters
	at org.elasticsearch.transport.RemoteClusterService.initializeRemoteClusters(RemoteClusterService.java:431)
	at org.elasticsearch.transport.TransportService.doStart(TransportService.java:241)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:61)
	at org.elasticsearch.node.Node.start(Node.java:662)
	at org.elasticsearch.test.InternalTestCluster$NodeAndClient.startNode(InternalTestCluster.java:961)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:677)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.util.concurrent.ExecutionException: ConnectTransportException[[leader1][127.0.0.1:53965] general node connection failure]; nested: IllegalStateException[handshake failed with {leader1}{C0InN5g5Q1ywlJOdPNNOwg}{nCYQ3OCCQc23dtHZNr8p9w}{127.0.0.1}{127.0.0.1:53965}{xpack.installed=true}]; nested: ReceiveTimeoutTransportException[[leader1][127.0.0.1:53965][internal:transport/handshake] request_id [4] timed out after [30001ms]];	
```

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently in the transport-nio work we connect and bind channels on the
a thread before the channel is registered with a selector. Additionally,
it is at this point that we set all the socket options. This commit
moves these operations onto the event-loop after the channel has been
registered with a selector. It attempts to set the socket options for a
non-server channel at registration time. If that fails, it will attempt
to set the options after the channel is connected. This should fix
#41071.

### CODE REVIEW

**Comment by ywelsch** [comment]
#44355 can be reverted once this is merged

File: libs/nio/src/main/java/org/elasticsearch/nio/SocketChannelContext.java [hunk 1]
```diff
@@ -288,4 +314,42 @@ protected int flushToChannel(FlushOperation flushOperation) throws IOException {
...
+            int tcpSendBufferSize = socketConfig.tcpSendBufferSize();
+            if (tcpSendBufferSize > 0) {
+                socket.setSendBufferSize(tcpSendBufferSize);
+            }
+            int tcpReceiveBufferSize = socketConfig.tcpReceiveBufferSize();
+            if (tcpReceiveBufferSize > 0) {
+                socket.setReceiveBufferSize(tcpReceiveBufferSize);
+            }
+            socketOptionsSet = true;
+        } catch (IOException e) {
```
Comment (ywelsch) [inline libs/nio/src/main/java/org/elasticsearch/nio/SocketChannelContext.java]: can you add trace logging here so that we debug possible problems with socket options being  set later?

File: libs/nio/src/test/java/org/elasticsearch/nio/ChannelContextTests.java [hunk 2]
```diff
@@ -118,11 +118,11 @@ public void closeChannel() {
         public NioSelector getSelector() {
             throw new UnsupportedOperationException("not implemented");
         }
-
```
Comment (ywelsch) [inline libs/nio/src/test/java/org/elasticsearch/nio/ChannelContextTests.java]: undo

**Review by ywelsch — APPROVED** [review]
Looks good to me. Can you have a look too @original-brownbear?

File: libs/nio/src/main/java/org/elasticsearch/nio/SocketChannelContext.java (hunk 1 above)
Comment (original-brownbear) [reply libs/nio/src/main/java/org/elasticsearch/nio/SocketChannelContext.java]: I don't think we can do that because we have no logging infra in the nio module.

**Review by original-brownbear — APPROVED** [review]
LGTM2
