### PR TITLE
Fix assertion in `SnapshotShutdownIT.testSnapshotShutdownProgressTracker()`

### LINKED ISSUE #127690: [CI] SnapshotShutdownIT testSnapshotShutdownProgressTracker failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8033 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/rgosv3g5o3kui)
- [elasticsearch-pull-request #69850 / part-1](https://gradle-enterprise.elastic.co/s/rj5gmioojphmk)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.snapshots.SnapshotShutdownIT.testSnapshotShutdownProgressTracker" -Dtests.seed=9FD834DA1359087B -Dtests.locale=xnr-IN -Dtests.timezone=Africa/Mbabane -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.snapshots.SnapshotShutdownIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSnapshotShutdownProgressTracker),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected to see SnapshotShutdownProgressTracker running number of snapshots but did not
Expected: <true>
     but: was <false>
```

**Issue Reasons:**
- [main] 2 failures in test testSnapshotShutdownProgressTracker (0.3% fail rate in 640 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by JeremyDahlgren**
Relaxes a log expectation assertion from an exact test of `numShards` running snapshots to `1-numShards`, since it
is possible for some of the shard snapshot statuses to already be in `stage=PAUSED`.

Closes #127690

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java [hunk 1]
```diff
@@ -540,12 +540,13 @@ public void testSnapshotShutdownProgressTracker() throws Exception {
         mockLog.awaitAllExpectationsMatched();
         resetMockLog();
 
+        assert 1 <= numShards && numShards <= 10;
```
Comment (DiannaHohensee) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java:543]:
```suggestion
        // At least one shard reached the MockRepository's blocking code when waitForBlock was called. However, there's no guarantee that
        // the other shards got that far before the shutdown flag was put in place, in which case the other shards may be paused instead.
        assert 1 <= numShards && numShards <= 10;
```

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java [hunk 2]
```diff
@@ -540,12 +540,13 @@ public void testSnapshotShutdownProgressTracker() throws Exception {
...
         mockLog.addExpectation(
-            new MockLog.SeenEventExpectation(
+            new MockLog.PatternSeenEventExpectation(
                 "SnapshotShutdownProgressTracker running number of snapshots",
                 SnapshotShutdownProgressTracker.class.getCanonicalName(),
                 Level.INFO,
-                "*Number shard snapshots running [" + numShards + "].*"
+                ".+Number shard snapshots running \\[" + (numShards < 10 ? "[1-" + numShards + "]" : "([1-9]|10)") + "].+"
```
Comment (DiannaHohensee) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java:549]: Can we change the `final int numShards = randomIntBetween(1, 10);` to `final int numShards = randomIntBetween(1, 9);` to simplify this? The random number range is arbitrary, so I think that would be okay.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java:543]: I'm wondering why we are asserting this because `final int numShards = randomIntBetween(1, 10);` already says it's going to be between 1 and 10?

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java:549]: ++ (or else maybe leave this as a `SeenEventExpectation` and parse out the `numShards` by overriding `innerMatch` rather than trying to do anything overly clever with a regex)

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java (hunk 1 above)
Comment (JeremyDahlgren) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotShutdownIT.java]: I added the code comment.  In the chance the thread bounds were changed it seemed clearer to enforce the restriction there instead of waiting for the seen event timeout.  I can see it doesn't add value, the assertion is removed now.

**Review by DaveCTurner — APPROVED** [review]
LGTM
