### PR TITLE
[ML] Fix ML stop datafeed ignoring close_job flag

### LINKED ISSUE #139024: [CI] DatafeedJobsIT testStopLookback_closeJobFalse failing
**Build Scans:**
- [elasticsearch-intake #31961 / part4](https://gradle-enterprise.elastic.co/s/byntood6nwfce)
- [elasticsearch-pull-request #107750 / part-4](https://gradle-enterprise.elastic.co/s/izucs7iapzpbc)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.DatafeedJobsIT.testStopLookback_closeJobFalse" -Dtests.seed=80B0B7E4A97BDE7B -Dtests.locale=en-WS -Dtests.timezone=SystemV/YST9YDT -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.integration.DatafeedJobsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testStopLookback_closeJobFalse'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected:<opened> but was:<closed>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testStopLookback_closeJobFalse
- [main] 2 failures in test testStopLookback_closeJobFalse (16.7% fail rate in 12 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by edsavage**
## Summary
Lookback-only datafeeds (`end_time` set) treated every API stop as if the job should auto-close, because `Holder.stop()` used `defaultAutoCloseJob = task.isLookbackOnly()` and the stop-datafeed transport action never forwarded the REST `close_job` parameter.

This change threads `request.closeJob()` through `DatafeedTask.stop` into `DatafeedRunner.stopDatafeed` so a stop with `close_job=false` does not call `CloseJobAction` after the datafeed stops. Natural lookback completion (e.g. `no_realtime`) still uses the existing path and unchanged default auto-close behavior.

## Testing
- `DatafeedJobsIT.testStopLookback_closeJobFalse` (50 iterations locally)
- `:x-pack:plugin:ml:spotlessJavaCheck`

Fixes #139024.

Made with [Cursor](https://cursor.com)

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedRunner.java [hunk 1]
```diff
@@ -152,11 +152,43 @@ public void onFailure(Exception e) {
...
+        TransportStartDatafeedAction.DatafeedTask task,
+        String reason,
+        TimeValue timeout,
+        Boolean autoCloseJobOverride
+    ) {
         logger.info("[{}] attempt to stop datafeed [{}] [{}]", reason, task.getDatafeedId(), task.getAllocationId());
         Holder holder = runningDatafeedsOnThisNode.remove(task.getAllocationId());
         if (holder != null) {
-            holder.stop(reason, timeout, null);
+            boolean autoCloseJob = autoCloseJobOverride != null ? autoCloseJobOverride : task.isLookbackOnly();
```
Comment (darius-vil) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedRunner.java:190]: Notice that `request.closeJob()` (https://github.com/elastic/elasticsearch/pull/145283/changes#diff-b95b221cac8877fdfcbb361c4f17f2b9de60b0716ec6362080bc508f67eb7cf1R572) reads a primitive boolean, which defaults to false.

I think it changes the behavior around stopping a lookback job slightly. Double checking that this was your intent:

BEFORE:
1. User has "lookbackOnly" datafeed running.
2. User invokes stop on it without specifying `close_job` -> the job is auto-closed as "lookbackOnly" jobs do

AFTER:
1. User has "lookbackOnly" datafeed running.
2. User invokes stop on it without specifying `close_job` -> `close_job` defaults to `false` -> a lookbackOnly job remains open

Comment (edsavage) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedRunner.java:190]: Good spot!

**Review by darius-vil — APPROVED** [review]
