### PR TITLE
Fix occasional SuggestSearchIT failure

### LINKED ISSUE #43261: Failure in org.elasticsearch.search.suggest.SuggestSearchIT.testEmptyShards
This failed on local CI for me on master 7870ae2f16f38514d0bcc93ed22031e87f69785d:

```
java.lang.AssertionError: Suggest result: {
  "suggest" : {
    "did_you_mean" : [
      {
        "text" : "tetsting sugestion",
        "offset" : 0,
        "length" : 18,
        "options" : [
          {
            "text" : "testing suggestions",
            "score" : 0.053599596
          }
        ]
      }
    ]
  }
}
Expected: <3>
     but: was <1>
	at __randomizedtesting.SeedInfo.seed([820633176B305743:96A96B78AB137AA]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertSuggestionSize(ElasticsearchAssertions.java:386)
	at org.elasticsearch.search.suggest.SuggestSearchIT.testEmptyShards(SuggestSearchIT.java:831)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

stderr:

```
REPRODUCE WITH: ./gradlew :server:integTest --tests "org.elasticsearch.search.suggest.SuggestSearchIT.testEmptyShards" -Dtests.seed=820633176B305743 -Dtests.security.manager=true -Dtests.locale=tr -Dtests.timezone=America/Atka -Dcompiler.java=12 -Druntime.java=11
NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/server/build/testrun/integTest/temp/org.elasticsearch.search.suggest.SuggestSearchIT_820633176B305743-001
NOTE: test params are: codec=Asserting(Lucene80): {_routing=PostingsFormat(name=Asserting), foo=PostingsFormat(name=Asserting), title=PostingsFormat(name=Asserting), body=PostingsFormat(name=Asserting), bigram=PostingsFormat(name=Asserting), foo.keyword=PostingsFormat(name=Asserting), field1.keyword=PostingsFormat(name=Asserting), field1=PostingsFormat(name=Asserting), _field_names=PostingsFormat(name=Asserting), name=PostingsFormat(name=Asserting), _id=PostingsFormat(name=Asserting), text=PostingsFormat(name=Asserting), text.keyword=PostingsFormat(name=Asserting), name.shingled=PostingsFormat(name=Asserting), field2=PostingsFormat(name=Asserting)}, docValues:{field1.keyword=DocValuesFormat(name=Lucene80), __soft_deletes=DocValuesFormat(name=Lucene80), _seq_no=DocValuesFormat(name=Asserting), _tombstone=DocValuesFormat(name=Lucene80), text=DocValuesFormat(name=Lucene80), text.keyword=DocValuesFormat(name=Asserting), _primary_term=DocValuesFormat(name=Lucene80), _version=DocValuesFormat(name=Asserting), foo.keyword=DocValuesFormat(name=Asserting)}, maxPointsInLeafNode=1784, maxMBSortInHeap=5.193076737714285, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@4577354a), locale=tr, timezone=America/Atka
NOTE: Linux 5.0.0-16-generic amd64/Oracle Corporation 11.0.2 (64-bit)/cpus=16,threads=1,free=468857208,total=536870912
NOTE: All tests run in this JVM: [AliasResolveRoutingIT, MetadataLoadingDuringSnapshotRestoreIT, BroadcastActionsIT, MockDiskUsagesIT, ZenDiscoveryIT, ClusterSettingsIT, UpgradeIndexSettingsIT, IndicesDocumentationIT, SingleNodeDiscoveryIT, SuggestSearchIT]
```

stdout:

```
[2019-06-16T00:22:09,857][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeAndSort] before test
[2019-06-16T00:22:09,857][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeAndSort] [SuggestSearchIT#testSizeAndSort]: setting up test
[2019-06-16T00:22:09,858][INFO ][o.e.t.InternalTestCluster] [testSizeAndSort] Setup InternalTestCluster [SUITE-CHILD_VM=[0]-CLUSTER_SEED=[7444645423189518051]-HASH=[4AE18F242CB3]-cluster] with seed [6750B191A7F2E6E3] using [3] dedicated masters, [3] (data) nodes and [0] coord only nodes (master nodes are [auto-managed])
[2019-06-16T00:22:09,873][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] using [1] data paths, mounts [[/ (/dev/nvme0n1p2)]], net usable_space [329.4gb], net total_space [467.9gb], types [ext4]
[2019-06-16T00:22:09,874][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] heap size [512mb], compressed ordinary object pointers [true]
[2019-06-16T00:22:09,879][INFO ][o.e.n.Node               ] [testSizeAndSort] node name [node_sm0], node ID [lhg4m8KfR8WgdtRCHz3YGA], cluster name [SUITE-CHILD_VM=[0]-CLUSTER_SEED=[7444645423189518051]-HASH=[4AE18F242CB3]-cluster]
[2019-06-16T00:22:09,879][INFO ][o.e.n.Node               ] [testSizeAndSort] version[8.0.0], pid[669], build[unknown/unknown/Unknown/Unknown], OS[Linux/5.0.0-16-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.2/11.0.2+9]
[2019-06-16T00:22:09,879][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM home [/usr/lib/jvm/jdk-11.0.2]
[2019-06-16T00:22:09,879][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM arguments [-Dcompiler.java=12, -Des.scripting.update.ctx_in_params=false, -Dgradle.dist.lib=/home/brownbear/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib, -Dgradle.user.home=/home/brownbear/.gradle, -Dgradle.worker.jar=/home/brownbear/.gradle/caches/5.4.1/workerMain/gradle-worker.jar, -Djava.awt.headless=true, -Djna.nosys=true, -Dorg.gradle.native=false, -Druntime.java=11, -Dtests.artifact=server, -Dtests.gradle=true, -Dtests.locale=tr, -Dtests.logger.level=WARN, -Dtests.security.manager=true, -Dtests.seed=820633176B305743, -Dtests.task=:server:integTest, -Dtests.timezone=America/Atka, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/home/brownbear/src/elasticsearch/server/build/heapdump, --illegal-access=warn, -esa, -Xms512m, -Xmx512m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=./temp, -Duser.country=US, -Duser.language=en, -Duser.variant, -ea]
[2019-06-16T00:22:09,880][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] no modules loaded
[2019-06-16T00:22:09,880][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.index.MockEngineFactoryPlugin]
[2019-06-16T00:22:09,880][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.node.NodeMocksPlugin]
[2019-06-16T00:22:09,880][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.search.suggest.SuggestSearchIT$DummyTemplatePlugin]
[2019-06-16T00:22:09,880][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$AssertActionNamePlugin]
[2019-06-16T00:22:09,880][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
[2019-06-16T00:22:09,880][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.MockHttpTransport$TestPlugin]
[2019-06-16T00:22:09,880][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.store.MockFSIndexStore$TestPlugin]
[2019-06-16T00:22:09,880][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
[2019-06-16T00:22:09,926][INFO ][o.e.d.DiscoveryModule    ] [testSizeAndSort] using discovery type [zen] and seed hosts providers [settings, file]
[2019-06-16T00:22:09,949][INFO ][o.e.n.Node               ] [testSizeAndSort] initialized
[2019-06-16T00:22:09,954][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] using [1] data paths, mounts [[/ (/dev/nvme0n1p2)]], net usable_space [329.4gb], net total_space [467.9gb], types [ext4]
[2019-06-16T00:22:09,954][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] heap size [512mb], compressed ordinary object pointers [true]
[2019-06-16T00:22:09,960][INFO ][o.e.n.Node               ] [testSizeAndSort] node name [node_sm1], node ID [KyDioTsBRo27qKBXEqjVxg], cluster name [SUITE-CHILD_VM=[0]-CLUSTER_SEED=[7444645423189518051]-HASH=[4AE18F242CB3]-cluster]
[2019-06-16T00:22:09,960][INFO ][o.e.n.Node               ] [testSizeAndSort] version[8.0.0], pid[669], build[unknown/unknown/Unknown/Unknown], OS[Linux/5.0.0-16-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.2/11.0.2+9]
[2019-06-16T00:22:09,960][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM home [/usr/lib/jvm/jdk-11.0.2]
[2019-06-16T00:22:09,960][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM arguments [-Dcompiler.java=12, -Des.scripting.update.ctx_in_params=false, -Dgradle.dist.lib=/home/brownbear/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib, -Dgradle.user.home=/home/brownbear/.gradle, -Dgradle.worker.jar=/home/brownbear/.gradle/caches/5.4.1/workerMain/gradle-worker.jar, -Djava.awt.headless=true, -Djna.nosys=true, -Dorg.gradle.native=false, -Druntime.java=11, -Dtests.artifact=server, -Dtests.gradle=true, -Dtests.locale=tr, -Dtests.logger.level=WARN, -Dtests.security.manager=true, -Dtests.seed=820633176B305743, -Dtests.task=:server:integTest, -Dtests.timezone=America/Atka, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/home/brownbear/src/elasticsearch/server/build/heapdump, --illegal-access=warn, -esa, -Xms512m, -Xmx512m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=./temp, -Duser.country=US, -Duser.language=en, -Duser.variant, -ea]
[2019-06-16T00:22:09,962][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] no modules loaded
[2019-06-16T00:22:09,962][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.index.MockEngineFactoryPlugin]
[2019-06-16T00:22:09,962][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.node.NodeMocksPlugin]
[2019-06-16T00:22:09,962][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.search.suggest.SuggestSearchIT$DummyTemplatePlugin]
[2019-06-16T00:22:09,962][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$AssertActionNamePlugin]
[2019-06-16T00:22:09,962][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
[2019-06-16T00:22:09,962][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.MockHttpTransport$TestPlugin]
[2019-06-16T00:22:09,962][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.store.MockFSIndexStore$TestPlugin]
[2019-06-16T00:22:09,963][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
[2019-06-16T00:22:10,050][INFO ][o.e.d.DiscoveryModule    ] [testSizeAndSort] using discovery type [zen] and seed hosts providers [settings, file]
[2019-06-16T00:22:10,068][INFO ][o.e.n.Node               ] [testSizeAndSort] initialized
[2019-06-16T00:22:10,094][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] using [1] data paths, mounts [[/ (/dev/nvme0n1p2)]], net usable_space [329.4gb], net total_space [467.9gb], types [ext4]
[2019-06-16T00:22:10,094][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] heap size [512mb], compressed ordinary object pointers [true]
[2019-06-16T00:22:10,100][INFO ][o.e.n.Node               ] [testSizeAndSort] node name [node_sm2], node ID [hpfnPWLrTAuF-SFDg2V4IQ], cluster name [SUITE-CHILD_VM=[0]-CLUSTER_SEED=[7444645423189518051]-HASH=[4AE18F242CB3]-cluster]
[2019-06-16T00:22:10,100][INFO ][o.e.n.Node               ] [testSizeAndSort] version[8.0.0], pid[669], build[unknown/unknown/Unknown/Unknown], OS[Linux/5.0.0-16-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.2/11.0.2+9]
[2019-06-16T00:22:10,100][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM home [/usr/lib/jvm/jdk-11.0.2]
[2019-06-16T00:22:10,100][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM arguments [-Dcompiler.java=12, -Des.scripting.update.ctx_in_params=false, -Dgradle.dist.lib=/home/brownbear/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib, -Dgradle.user.home=/home/brownbear/.gradle, -Dgradle.worker.jar=/home/brownbear/.gradle/caches/5.4.1/workerMain/gradle-worker.jar, -Djava.awt.headless=true, -Djna.nosys=true, -Dorg.gradle.native=false, -Druntime.java=11, -Dtests.artifact=server, -Dtests.gradle=true, -Dtests.locale=tr, -Dtests.logger.level=WARN, -Dtests.security.manager=true, -Dtests.seed=820633176B305743, -Dtests.task=:server:integTest, -Dtests.timezone=America/Atka, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/home/brownbear/src/elasticsearch/server/build/heapdump, --illegal-access=warn, -esa, -Xms512m, -Xmx512m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=./temp, -Duser.country=US, -Duser.language=en, -Duser.variant, -ea]
[2019-06-16T00:22:10,101][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] no modules loaded
[2019-06-16T00:22:10,101][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.index.MockEngineFactoryPlugin]
[2019-06-16T00:22:10,101][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.node.NodeMocksPlugin]
[2019-06-16T00:22:10,101][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.search.suggest.SuggestSearchIT$DummyTemplatePlugin]
[2019-06-16T00:22:10,101][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$AssertActionNamePlugin]
[2019-06-16T00:22:10,101][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
[2019-06-16T00:22:10,101][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.MockHttpTransport$TestPlugin]
[2019-06-16T00:22:10,102][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.store.MockFSIndexStore$TestPlugin]
[2019-06-16T00:22:10,102][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
[2019-06-16T00:22:10,148][INFO ][o.e.d.DiscoveryModule    ] [testSizeAndSort] using discovery type [zen] and seed hosts providers [settings, file]
[2019-06-16T00:22:10,172][INFO ][o.e.n.Node               ] [testSizeAndSort] initialized
[2019-06-16T00:22:10,191][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] using [1] data paths, mounts [[/ (/dev/nvme0n1p2)]], net usable_space [329.4gb], net total_space [467.9gb], types [ext4]
[2019-06-16T00:22:10,191][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] heap size [512mb], compressed ordinary object pointers [true]
[2019-06-16T00:22:10,195][INFO ][o.e.n.Node               ] [testSizeAndSort] node name [node_sd3], node ID [KeaMgMqNRLeBSYexn54Xwg], cluster name [SUITE-CHILD_VM=[0]-CLUSTER_SEED=[7444645423189518051]-HASH=[4AE18F242CB3]-cluster]
[2019-06-16T00:22:10,196][INFO ][o.e.n.Node               ] [testSizeAndSort] version[8.0.0], pid[669], build[unknown/unknown/Unknown/Unknown], OS[Linux/5.0.0-16-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.2/11.0.2+9]
[2019-06-16T00:22:10,196][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM home [/usr/lib/jvm/jdk-11.0.2]
[2019-06-16T00:22:10,196][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM arguments [-Dcompiler.java=12, -Des.scripting.update.ctx_in_params=false, -Dgradle.dist.lib=/home/brownbear/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib, -Dgradle.user.home=/home/brownbear/.gradle, -Dgradle.worker.jar=/home/brownbear/.gradle/caches/5.4.1/workerMain/gradle-worker.jar, -Djava.awt.headless=true, -Djna.nosys=true, -Dorg.gradle.native=false, -Druntime.java=11, -Dtests.artifact=server, -Dtests.gradle=true, -Dtests.locale=tr, -Dtests.logger.level=WARN, -Dtests.security.manager=true, -Dtests.seed=820633176B305743, -Dtests.task=:server:integTest, -Dtests.timezone=America/Atka, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/home/brownbear/src/elasticsearch/server/build/heapdump, --illegal-access=warn, -esa, -Xms512m, -Xmx512m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=./temp, -Duser.country=US, -Duser.language=en, -Duser.variant, -ea]
[2019-06-16T00:22:10,209][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] no modules loaded
[2019-06-16T00:22:10,209][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.index.MockEngineFactoryPlugin]
[2019-06-16T00:22:10,209][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.node.NodeMocksPlugin]
[2019-06-16T00:22:10,209][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.search.suggest.SuggestSearchIT$DummyTemplatePlugin]
[2019-06-16T00:22:10,209][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$AssertActionNamePlugin]
[2019-06-16T00:22:10,209][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
[2019-06-16T00:22:10,209][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.MockHttpTransport$TestPlugin]
[2019-06-16T00:22:10,209][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.store.MockFSIndexStore$TestPlugin]
[2019-06-16T00:22:10,209][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
[2019-06-16T00:22:10,263][INFO ][o.e.d.DiscoveryModule    ] [testSizeAndSort] using discovery type [zen] and seed hosts providers [settings, file]
[2019-06-16T00:22:10,293][INFO ][o.e.n.Node               ] [testSizeAndSort] initialized
[2019-06-16T00:22:10,297][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] using [1] data paths, mounts [[/ (/dev/nvme0n1p2)]], net usable_space [329.4gb], net total_space [467.9gb], types [ext4]
[2019-06-16T00:22:10,298][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] heap size [512mb], compressed ordinary object pointers [true]
[2019-06-16T00:22:10,303][INFO ][o.e.n.Node               ] [testSizeAndSort] node name [node_sd4], node ID [v0vb8-EHTdSG4MCGdUC88g], cluster name [SUITE-CHILD_VM=[0]-CLUSTER_SEED=[7444645423189518051]-HASH=[4AE18F242CB3]-cluster]
[2019-06-16T00:22:10,304][INFO ][o.e.n.Node               ] [testSizeAndSort] version[8.0.0], pid[669], build[unknown/unknown/Unknown/Unknown], OS[Linux/5.0.0-16-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.2/11.0.2+9]
[2019-06-16T00:22:10,304][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM home [/usr/lib/jvm/jdk-11.0.2]
[2019-06-16T00:22:10,304][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM arguments [-Dcompiler.java=12, -Des.scripting.update.ctx_in_params=false, -Dgradle.dist.lib=/home/brownbear/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib, -Dgradle.user.home=/home/brownbear/.gradle, -Dgradle.worker.jar=/home/brownbear/.gradle/caches/5.4.1/workerMain/gradle-worker.jar, -Djava.awt.headless=true, -Djna.nosys=true, -Dorg.gradle.native=false, -Druntime.java=11, -Dtests.artifact=server, -Dtests.gradle=true, -Dtests.locale=tr, -Dtests.logger.level=WARN, -Dtests.security.manager=true, -Dtests.seed=820633176B305743, -Dtests.task=:server:integTest, -Dtests.timezone=America/Atka, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/home/brownbear/src/elasticsearch/server/build/heapdump, --illegal-access=warn, -esa, -Xms512m, -Xmx512m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=./temp, -Duser.country=US, -Duser.language=en, -Duser.variant, -ea]
[2019-06-16T00:22:10,305][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] no modules loaded
[2019-06-16T00:22:10,305][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.index.MockEngineFactoryPlugin]
[2019-06-16T00:22:10,305][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.node.NodeMocksPlugin]
[2019-06-16T00:22:10,305][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.search.suggest.SuggestSearchIT$DummyTemplatePlugin]
[2019-06-16T00:22:10,305][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$AssertActionNamePlugin]
[2019-06-16T00:22:10,305][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
[2019-06-16T00:22:10,305][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.MockHttpTransport$TestPlugin]
[2019-06-16T00:22:10,305][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.store.MockFSIndexStore$TestPlugin]
[2019-06-16T00:22:10,305][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
[2019-06-16T00:22:10,350][INFO ][o.e.d.DiscoveryModule    ] [testSizeAndSort] using discovery type [zen] and seed hosts providers [settings, file]
[2019-06-16T00:22:10,368][INFO ][o.e.n.Node               ] [testSizeAndSort] initialized
[2019-06-16T00:22:10,381][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] using [1] data paths, mounts [[/ (/dev/nvme0n1p2)]], net usable_space [329.4gb], net total_space [467.9gb], types [ext4]
[2019-06-16T00:22:10,382][INFO ][o.e.e.NodeEnvironment    ] [testSizeAndSort] heap size [512mb], compressed ordinary object pointers [true]
[2019-06-16T00:22:10,391][INFO ][o.e.n.Node               ] [testSizeAndSort] node name [node_sd5], node ID [nPPKc3kZSFyw12vUPyEQCQ], cluster name [SUITE-CHILD_VM=[0]-CLUSTER_SEED=[7444645423189518051]-HASH=[4AE18F242CB3]-cluster]
[2019-06-16T00:22:10,392][INFO ][o.e.n.Node               ] [testSizeAndSort] version[8.0.0], pid[669], build[unknown/unknown/Unknown/Unknown], OS[Linux/5.0.0-16-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.2/11.0.2+9]
[2019-06-16T00:22:10,392][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM home [/usr/lib/jvm/jdk-11.0.2]
[2019-06-16T00:22:10,392][INFO ][o.e.n.Node               ] [testSizeAndSort] JVM arguments [-Dcompiler.java=12, -Des.scripting.update.ctx_in_params=false, -Dgradle.dist.lib=/home/brownbear/.gradle/wrapper/dists/gradle-5.4.1-all/3221gyojl5jsh0helicew7rwx/gradle-5.4.1/lib, -Dgradle.user.home=/home/brownbear/.gradle, -Dgradle.worker.jar=/home/brownbear/.gradle/caches/5.4.1/workerMain/gradle-worker.jar, -Djava.awt.headless=true, -Djna.nosys=true, -Dorg.gradle.native=false, -Druntime.java=11, -Dtests.artifact=server, -Dtests.gradle=true, -Dtests.locale=tr, -Dtests.logger.level=WARN, -Dtests.security.manager=true, -Dtests.seed=820633176B305743, -Dtests.task=:server:integTest, -Dtests.timezone=America/Atka, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/home/brownbear/src/elasticsearch/server/build/heapdump, --illegal-access=warn, -esa, -Xms512m, -Xmx512m, -Dfile.encoding=UTF-8, -Djava.io.tmpdir=./temp, -Duser.country=US, -Duser.language=en, -Duser.variant, -ea]
[2019-06-16T00:22:10,393][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] no modules loaded
[2019-06-16T00:22:10,393][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.index.MockEngineFactoryPlugin]
[2019-06-16T00:22:10,393][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.node.NodeMocksPlugin]
[2019-06-16T00:22:10,393][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.search.suggest.SuggestSearchIT$DummyTemplatePlugin]
[2019-06-16T00:22:10,393][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$AssertActionNamePlugin]
[2019-06-16T00:22:10,393][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.ESIntegTestCase$TestSeedPlugin]
[2019-06-16T00:22:10,393][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.MockHttpTransport$TestPlugin]
[2019-06-16T00:22:10,393][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.test.store.MockFSIndexStore$TestPlugin]
[2019-06-16T00:22:10,393][INFO ][o.e.p.PluginsService     ] [testSizeAndSort] loaded plugin [org.elasticsearch.transport.nio.MockNioTransportPlugin]
[2019-06-16T00:22:10,430][INFO ][o.e.d.DiscoveryModule    ] [testSizeAndSort] using discovery type [zen] and seed hosts providers [settings, file]
[2019-06-16T00:22:10,443][INFO ][o.e.n.Node               ] [testSizeAndSort] initialized
[2019-06-16T00:22:10,449][INFO ][o.e.n.Node               ] [integ_1] starting ...
[2019-06-16T00:22:10,464][INFO ][o.e.n.Node               ] [integ_2] starting ...
[2019-06-16T00:22:10,469][INFO ][o.e.n.Node               ] [integ_3] starting ...
[2019-06-16T00:22:10,517][INFO ][o.e.n.Node               ] [integ_6] starting ...
[2019-06-16T00:22:10,518][INFO ][o.e.n.Node               ] [integ_4] starting ...
[2019-06-16T00:22:10,524][INFO ][o.e.n.Node               ] [integ_5] starting ...
[2019-06-16T00:22:10,547][INFO ][o.e.t.TransportService   ] [integ_2] publish_address {127.0.0.1:42699}, bound_addresses {[::1]:42325}, {127.0.0.1:42699}
[2019-06-16T00:22:10,550][INFO ][o.e.t.TransportService   ] [integ_3] publish_address {127.0.0.1:34383}, bound_addresses {[::1]:39639}, {127.0.0.1:34383}
[2019-06-16T00:22:10,585][INFO ][o.e.t.TransportService   ] [integ_4] publish_address {127.0.0.1:45675}, bound_addresses {[::1]:37423}, {127.0.0.1:45675}
[2019-06-16T00:22:10,587][INFO ][o.e.t.TransportService   ] [integ_1] publish_address {127.0.0.1:46535}, bound_addresses {[::1]:46097}, {127.0.0.1:46535}
[2019-06-16T00:22:10,591][INFO ][o.e.t.TransportService   ] [integ_5] publish_address {127.0.0.1:45999}, bound_addresses {[::1]:44897}, {127.0.0.1:45999}
[2019-06-16T00:22:10,671][INFO ][o.e.t.TransportService   ] [integ_6] publish_address {127.0.0.1:39927}, bound_addresses {[::1]:36225}, {127.0.0.1:39927}
[2019-06-16T00:22:10,855][INFO ][o.e.c.c.Coordinator      ] [node_sm0] setting initial configuration to VotingConfiguration{{bootstrap-placeholder}-node_sm1,lhg4m8KfR8WgdtRCHz3YGA,hpfnPWLrTAuF-SFDg2V4IQ}
[2019-06-16T00:22:11,026][INFO ][o.e.c.c.JoinHelper       ] [node_sm2] failed to join {node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535} with JoinRequest{sourceNode={node_sm2}{hpfnPWLrTAuF-SFDg2V4IQ}{pskv3rsKSgiRUoQI5vIDiQ}{127.0.0.1}{127.0.0.1:34383}, optionalJoin=Optional[Join{term=1, lastAcceptedTerm=0, lastAcceptedVersion=0, sourceNode={node_sm2}{hpfnPWLrTAuF-SFDg2V4IQ}{pskv3rsKSgiRUoQI5vIDiQ}{127.0.0.1}{127.0.0.1:34383}, targetNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}]}
org.elasticsearch.transport.NodeNotConnectedException: [node_sm0][127.0.0.1:46535] Node not connected
	at org.elasticsearch.transport.ConnectionManager.getConnection(ConnectionManager.java:151) ~[main/:?]
	at org.elasticsearch.transport.TransportService.getConnection(TransportService.java:559) ~[main/:?]
	at org.elasticsearch.transport.TransportService.sendRequest(TransportService.java:531) [main/:?]
	at org.elasticsearch.cluster.coordination.JoinHelper.sendJoinRequest(JoinHelper.java:235) [main/:?]
	at org.elasticsearch.cluster.coordination.JoinHelper.lambda$new$1(JoinHelper.java:129) [main/:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [main/:?]
	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:267) [main/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:757) [main/:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2019-06-16T00:22:11,566][INFO ][o.e.c.s.MasterService    ] [node_sm0] elected-as-master ([3] nodes joined)[{node_sm1}{KyDioTsBRo27qKBXEqjVxg}{tWRjfJA0T96_A2V_q_hiig}{127.0.0.1}{127.0.0.1:42699} elect leader, {node_sm2}{hpfnPWLrTAuF-SFDg2V4IQ}{pskv3rsKSgiRUoQI5vIDiQ}{127.0.0.1}{127.0.0.1:34383} elect leader, {node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 2, version: 1, reason: master node changed {previous [], current [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}]}, added {{node_sm1}{KyDioTsBRo27qKBXEqjVxg}{tWRjfJA0T96_A2V_q_hiig}{127.0.0.1}{127.0.0.1:42699},{node_sm2}{hpfnPWLrTAuF-SFDg2V4IQ}{pskv3rsKSgiRUoQI5vIDiQ}{127.0.0.1}{127.0.0.1:34383},}
[2019-06-16T00:22:11,580][INFO ][o.e.c.c.CoordinationState] [node_sm0] cluster UUID set to [TMmmRAL2SIWw9EVY3A-a2Q]
[2019-06-16T00:22:11,581][INFO ][o.e.c.c.CoordinationState] [node_sm2] cluster UUID set to [TMmmRAL2SIWw9EVY3A-a2Q]
[2019-06-16T00:22:11,588][INFO ][o.e.c.s.ClusterApplierService] [node_sm2] master node changed {previous [], current [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}]}, added {{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535},{node_sm1}{KyDioTsBRo27qKBXEqjVxg}{tWRjfJA0T96_A2V_q_hiig}{127.0.0.1}{127.0.0.1:42699},}, term: 2, version: 1, reason: ApplyCommitRequest{term=2, version=1, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,595][INFO ][o.e.c.c.CoordinationState] [node_sm1] cluster UUID set to [TMmmRAL2SIWw9EVY3A-a2Q]
[2019-06-16T00:22:11,603][INFO ][o.e.c.s.ClusterApplierService] [node_sm1] master node changed {previous [], current [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}]}, added {{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535},{node_sm2}{hpfnPWLrTAuF-SFDg2V4IQ}{pskv3rsKSgiRUoQI5vIDiQ}{127.0.0.1}{127.0.0.1:34383},}, term: 2, version: 1, reason: ApplyCommitRequest{term=2, version=1, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,629][INFO ][o.e.n.Node               ] [integ_3] started
[2019-06-16T00:22:11,637][INFO ][o.e.n.Node               ] [integ_2] started
[2019-06-16T00:22:11,639][INFO ][o.e.c.s.ClusterApplierService] [node_sm0] master node changed {previous [], current [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}]}, added {{node_sm1}{KyDioTsBRo27qKBXEqjVxg}{tWRjfJA0T96_A2V_q_hiig}{127.0.0.1}{127.0.0.1:42699},{node_sm2}{hpfnPWLrTAuF-SFDg2V4IQ}{pskv3rsKSgiRUoQI5vIDiQ}{127.0.0.1}{127.0.0.1:34383},}, term: 2, version: 1, reason: Publication{term=2, version=1}
[2019-06-16T00:22:11,673][INFO ][o.e.n.Node               ] [integ_1] started
[2019-06-16T00:22:11,674][INFO ][o.e.c.s.MasterService    ] [node_sm0] node-join[{node_sm1}{KyDioTsBRo27qKBXEqjVxg}{tWRjfJA0T96_A2V_q_hiig}{127.0.0.1}{127.0.0.1:42699} join existing leader, {node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675} join existing leader, {node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999} join existing leader], term: 2, version: 2, reason: added {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}
[2019-06-16T00:22:11,679][INFO ][o.e.c.s.ClusterApplierService] [node_sm2] added {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 2, reason: ApplyCommitRequest{term=2, version=2, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,679][INFO ][o.e.c.s.ClusterApplierService] [node_sd4] master node changed {previous [], current [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}]}, added {{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535},{node_sm1}{KyDioTsBRo27qKBXEqjVxg}{tWRjfJA0T96_A2V_q_hiig}{127.0.0.1}{127.0.0.1:42699},{node_sm2}{hpfnPWLrTAuF-SFDg2V4IQ}{pskv3rsKSgiRUoQI5vIDiQ}{127.0.0.1}{127.0.0.1:34383},{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 2, reason: ApplyCommitRequest{term=2, version=2, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,679][INFO ][o.e.c.s.ClusterApplierService] [node_sd3] master node changed {previous [], current [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}]}, added {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535},{node_sm1}{KyDioTsBRo27qKBXEqjVxg}{tWRjfJA0T96_A2V_q_hiig}{127.0.0.1}{127.0.0.1:42699},{node_sm2}{hpfnPWLrTAuF-SFDg2V4IQ}{pskv3rsKSgiRUoQI5vIDiQ}{127.0.0.1}{127.0.0.1:34383},}, term: 2, version: 2, reason: ApplyCommitRequest{term=2, version=2, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,681][INFO ][o.e.c.s.ClusterApplierService] [node_sm1] added {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 2, reason: ApplyCommitRequest{term=2, version=2, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,723][INFO ][o.e.n.Node               ] [integ_4] started
[2019-06-16T00:22:11,741][INFO ][o.e.n.Node               ] [integ_5] started
[2019-06-16T00:22:11,741][INFO ][o.e.c.s.ClusterApplierService] [node_sm0] added {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 2, reason: Publication{term=2, version=2}
[2019-06-16T00:22:11,851][INFO ][o.e.c.s.MasterService    ] [node_sm0] node-join[{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927} join existing leader], term: 2, version: 4, reason: added {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}
[2019-06-16T00:22:11,856][INFO ][o.e.c.s.ClusterApplierService] [node_sd4] added {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}, term: 2, version: 4, reason: ApplyCommitRequest{term=2, version=4, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,856][INFO ][o.e.c.s.ClusterApplierService] [node_sd3] added {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}, term: 2, version: 4, reason: ApplyCommitRequest{term=2, version=4, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,856][INFO ][o.e.c.s.ClusterApplierService] [node_sm1] added {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}, term: 2, version: 4, reason: ApplyCommitRequest{term=2, version=4, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,856][INFO ][o.e.c.s.ClusterApplierService] [node_sd5] master node changed {previous [], current [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}]}, added {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535},{node_sm1}{KyDioTsBRo27qKBXEqjVxg}{tWRjfJA0T96_A2V_q_hiig}{127.0.0.1}{127.0.0.1:42699},{node_sm2}{hpfnPWLrTAuF-SFDg2V4IQ}{pskv3rsKSgiRUoQI5vIDiQ}{127.0.0.1}{127.0.0.1:34383},{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 4, reason: ApplyCommitRequest{term=2, version=4, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,856][INFO ][o.e.c.s.ClusterApplierService] [node_sm2] added {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}, term: 2, version: 4, reason: ApplyCommitRequest{term=2, version=4, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:11,947][INFO ][o.e.n.Node               ] [integ_6] started
[2019-06-16T00:22:11,962][INFO ][o.e.c.s.ClusterApplierService] [node_sm0] added {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}, term: 2, version: 4, reason: Publication{term=2, version=4}
[2019-06-16T00:22:12,035][INFO ][o.e.g.GatewayService     ] [node_sm0] recovered [0] indices into cluster_state
[2019-06-16T00:22:12,041][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:12,077][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeAndSort] [SuggestSearchIT#testSizeAndSort]: all set up test
[2019-06-16T00:22:12,077][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeAndSort] using custom data_path for index: [quPdRaNqQC]
[2019-06-16T00:22:12,080][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [9]/[1], mappings []
[2019-06-16T00:22:13,013][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][8]] ...]).
[2019-06-16T00:22:13,076][INFO ][o.e.c.m.MetaDataMappingService] [node_sm0] [test/22KtM0fySHiSl9bOYTCFjQ] create_mapping [type1]
[2019-06-16T00:22:15,716][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeAndSort] [SuggestSearchIT#testSizeAndSort]: cleaning up after test
[2019-06-16T00:22:15,747][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/22KtM0fySHiSl9bOYTCFjQ] deleting index
[2019-06-16T00:22:15,808][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:15,817][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:15,817][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:15,883][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] start check index
[2019-06-16T00:22:15,920][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][1] start check index
[2019-06-16T00:22:15,936][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:15,956][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] end check index
[2019-06-16T00:22:15,970][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][1] end check index
[2019-06-16T00:22:16,027][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][3] start check index
[2019-06-16T00:22:16,099][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:16,191][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:16,200][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][3] end check index
[2019-06-16T00:22:16,211][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:16,249][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][4] start check index
[2019-06-16T00:22:16,251][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][4] end check index
[2019-06-16T00:22:16,257][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:16,286][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][2] start check index
[2019-06-16T00:22:16,295][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][2] end check index
[2019-06-16T00:22:16,335][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][5] start check index
[2019-06-16T00:22:16,339][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] start check index
[2019-06-16T00:22:16,351][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][5] end check index
[2019-06-16T00:22:16,361][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] start check index
[2019-06-16T00:22:16,372][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] end check index
[2019-06-16T00:22:16,462][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] start check index
[2019-06-16T00:22:16,466][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] end check index
[2019-06-16T00:22:16,482][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] end check index
[2019-06-16T00:22:16,491][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][7] start check index
[2019-06-16T00:22:16,493][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][7] end check index
[2019-06-16T00:22:16,521][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][8] start check index
[2019-06-16T00:22:16,527][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][8] end check index
[2019-06-16T00:22:16,527][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][8] start check index
[2019-06-16T00:22:16,531][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][8] end check index
[2019-06-16T00:22:16,577][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] start check index
[2019-06-16T00:22:16,584][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] end check index
[2019-06-16T00:22:16,601][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] start check index
[2019-06-16T00:22:16,605][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] end check index
[2019-06-16T00:22:16,637][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:16,678][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeAndSort] [SuggestSearchIT#testSizeAndSort]: cleaned up after test
[2019-06-16T00:22:16,678][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeAndSort] after test
[2019-06-16T00:22:16,742][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithManyCandidates] before test
[2019-06-16T00:22:16,742][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithManyCandidates] [SuggestSearchIT#testSuggestWithManyCandidates]: setting up test
[2019-06-16T00:22:16,748][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:16,767][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithManyCandidates] [SuggestSearchIT#testSuggestWithManyCandidates]: all set up test
[2019-06-16T00:22:16,776][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[0], mappings [type1]
[2019-06-16T00:22:16,869][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
[2019-06-16T00:22:17,000][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithManyCandidates] Index [4208] docs async: [false] bulk: [true] partitions [31]
[2019-06-16T00:22:28,445][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithManyCandidates] [SuggestSearchIT#testSuggestWithManyCandidates]: cleaning up after test
[2019-06-16T00:22:28,496][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/wPuTtubGQWSvMpIxEAm2gA] deleting index
[2019-06-16T00:22:28,674][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:28,677][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:28,728][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:28,768][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithManyCandidates] [SuggestSearchIT#testSuggestWithManyCandidates]: cleaned up after test
[2019-06-16T00:22:28,768][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithManyCandidates] after test
[2019-06-16T00:22:28,813][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyShards] before test
[2019-06-16T00:22:28,813][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyShards] [SuggestSearchIT#testEmptyShards]: setting up test
[2019-06-16T00:22:28,819][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:28,842][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyShards] [SuggestSearchIT#testEmptyShards]: all set up test
[2019-06-16T00:22:28,849][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [7]/[1], mappings [type1]
[2019-06-16T00:22:29,704][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][6]] ...]).
[2019-06-16T00:22:29,798][INFO ][o.e.c.m.MetaDataMappingService] [node_sm0] [test/aBspwKH0TQuqe1yQoNOP6A] update_mapping [type1]
[2019-06-16T00:22:30,651][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyShards] [SuggestSearchIT#testEmptyShards]: cleaning up after test
[2019-06-16T00:22:30,722][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/aBspwKH0TQuqe1yQoNOP6A] deleting index
[2019-06-16T00:22:30,733][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] start check index
[2019-06-16T00:22:30,734][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][2] start check index
[2019-06-16T00:22:30,751][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:30,754][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:30,754][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] end check index
[2019-06-16T00:22:30,759][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][2] end check index
[2019-06-16T00:22:30,762][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:30,780][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:30,806][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] start check index
[2019-06-16T00:22:30,809][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] start check index
[2019-06-16T00:22:30,812][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] end check index
[2019-06-16T00:22:30,818][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] end check index
[2019-06-16T00:22:30,844][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][5] start check index
[2019-06-16T00:22:30,845][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] start check index
[2019-06-16T00:22:30,865][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][5] end check index
[2019-06-16T00:22:30,866][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] end check index
[2019-06-16T00:22:30,904][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][3] start check index
[2019-06-16T00:22:30,926][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] start check index
[2019-06-16T00:22:30,931][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] start check index
[2019-06-16T00:22:30,933][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] end check index
[2019-06-16T00:22:30,935][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] end check index
[2019-06-16T00:22:30,941][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:30,974][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][3] end check index
[2019-06-16T00:22:30,974][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:30,975][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:30,977][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:30,987][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] start check index
[2019-06-16T00:22:31,004][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] end check index
[2019-06-16T00:22:31,044][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:31,081][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyShards] [SuggestSearchIT#testEmptyShards]: cleaned up after test
[2019-06-16T00:22:31,081][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyShards] after test
[2019-06-16T00:22:31,429][INFO ][o.e.s.s.SuggestSearchIT  ] [testStopwordsOnlyPhraseSuggest] before test
[2019-06-16T00:22:31,429][INFO ][o.e.s.s.SuggestSearchIT  ] [testStopwordsOnlyPhraseSuggest] [SuggestSearchIT#testStopwordsOnlyPhraseSuggest]: setting up test
[2019-06-16T00:22:31,435][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:31,483][INFO ][o.e.s.s.SuggestSearchIT  ] [testStopwordsOnlyPhraseSuggest] [SuggestSearchIT#testStopwordsOnlyPhraseSuggest]: all set up test
[2019-06-16T00:22:31,490][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [3]/[0], mappings [typ1]
[2019-06-16T00:22:31,736][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][2], [test][1]] ...]).
[2019-06-16T00:22:31,977][INFO ][o.e.s.s.SuggestSearchIT  ] [testStopwordsOnlyPhraseSuggest] [SuggestSearchIT#testStopwordsOnlyPhraseSuggest]: cleaning up after test
[2019-06-16T00:22:32,012][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/Bur3u72eTZCzcXVqaDAKbA] deleting index
[2019-06-16T00:22:32,026][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:32,039][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:32,041][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:32,058][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:32,065][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:32,080][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:32,164][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:32,202][INFO ][o.e.s.s.SuggestSearchIT  ] [testStopwordsOnlyPhraseSuggest] [SuggestSearchIT#testStopwordsOnlyPhraseSuggest]: cleaned up after test
[2019-06-16T00:22:32,202][INFO ][o.e.s.s.SuggestSearchIT  ] [testStopwordsOnlyPhraseSuggest] after test
[2019-06-16T00:22:32,257][INFO ][o.e.s.s.SuggestSearchIT  ] [testDifferentShardSize] before test
[2019-06-16T00:22:32,257][INFO ][o.e.s.s.SuggestSearchIT  ] [testDifferentShardSize] [SuggestSearchIT#testDifferentShardSize]: setting up test
[2019-06-16T00:22:32,271][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:32,308][INFO ][o.e.s.s.SuggestSearchIT  ] [testDifferentShardSize] [SuggestSearchIT#testDifferentShardSize]: all set up test
[2019-06-16T00:22:32,311][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [4]/[1], mappings []
[2019-06-16T00:22:32,779][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][1]] ...]).
[2019-06-16T00:22:32,823][INFO ][o.e.s.s.SuggestSearchIT  ] [testDifferentShardSize] Index [3] docs async: [true] bulk: [false]
[2019-06-16T00:22:32,828][INFO ][o.e.c.m.MetaDataMappingService] [node_sm0] [test/M1EjGiUvTV-gHKu7DozPMw] create_mapping [type1]
[2019-06-16T00:22:33,123][INFO ][o.e.s.s.SuggestSearchIT  ] [testDifferentShardSize] [SuggestSearchIT#testDifferentShardSize]: cleaning up after test
[2019-06-16T00:22:33,137][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/M1EjGiUvTV-gHKu7DozPMw] deleting index
[2019-06-16T00:22:33,147][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:33,165][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:33,166][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:33,175][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][0] start check index
[2019-06-16T00:22:33,186][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:33,209][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][0] end check index
[2019-06-16T00:22:33,209][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][2] start check index
[2019-06-16T00:22:33,221][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:33,231][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] start check index
[2019-06-16T00:22:33,231][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:33,235][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][2] end check index
[2019-06-16T00:22:33,237][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] end check index
[2019-06-16T00:22:33,257][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][3] start check index
[2019-06-16T00:22:33,261][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:33,272][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][3] end check index
[2019-06-16T00:22:33,287][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:33,360][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:33,468][INFO ][o.e.s.s.SuggestSearchIT  ] [testDifferentShardSize] [SuggestSearchIT#testDifferentShardSize]: cleaned up after test
[2019-06-16T00:22:33,468][INFO ][o.e.s.s.SuggestSearchIT  ] [testDifferentShardSize] after test
[2019-06-16T00:22:33,541][INFO ][o.e.s.s.SuggestSearchIT  ] [testBasicPhraseSuggest] before test
[2019-06-16T00:22:33,541][INFO ][o.e.s.s.SuggestSearchIT  ] [testBasicPhraseSuggest] [SuggestSearchIT#testBasicPhraseSuggest]: setting up test
[2019-06-16T00:22:33,547][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:33,576][INFO ][o.e.s.s.SuggestSearchIT  ] [testBasicPhraseSuggest] [SuggestSearchIT#testBasicPhraseSuggest]: all set up test
[2019-06-16T00:22:33,582][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[0], mappings [type1]
[2019-06-16T00:22:33,851][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
[2019-06-16T00:22:34,228][INFO ][o.e.s.s.SuggestSearchIT  ] [testBasicPhraseSuggest] [SuggestSearchIT#testBasicPhraseSuggest]: cleaning up after test
[2019-06-16T00:22:34,241][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/R_xhtYRMS7GOz_Id5rv-zg] deleting index
[2019-06-16T00:22:34,289][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:34,313][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:34,350][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:34,388][INFO ][o.e.s.s.SuggestSearchIT  ] [testBasicPhraseSuggest] [SuggestSearchIT#testBasicPhraseSuggest]: cleaned up after test
[2019-06-16T00:22:34,389][INFO ][o.e.s.s.SuggestSearchIT  ] [testBasicPhraseSuggest] after test
[2019-06-16T00:22:34,425][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggestMinDocFreq] before test
[2019-06-16T00:22:34,426][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggestMinDocFreq] [SuggestSearchIT#testPhraseSuggestMinDocFreq]: setting up test
[2019-06-16T00:22:34,432][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:34,466][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggestMinDocFreq] [SuggestSearchIT#testPhraseSuggestMinDocFreq]: all set up test
[2019-06-16T00:22:34,466][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggestMinDocFreq] using custom data_path for index: [vnpsIcIkwX]
[2019-06-16T00:22:34,469][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[0], mappings [type]
[2019-06-16T00:22:34,593][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
[2019-06-16T00:22:34,612][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggestMinDocFreq] Index [4] docs async: [true] bulk: [false]
[2019-06-16T00:22:34,771][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggestMinDocFreq] [SuggestSearchIT#testPhraseSuggestMinDocFreq]: cleaning up after test
[2019-06-16T00:22:34,784][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/4QbClXjmR6WZVy-oSX_TeQ] deleting index
[2019-06-16T00:22:34,814][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:34,847][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:34,894][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:34,932][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggestMinDocFreq] [SuggestSearchIT#testPhraseSuggestMinDocFreq]: cleaned up after test
[2019-06-16T00:22:34,933][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggestMinDocFreq] after test
[2019-06-16T00:22:35,026][INFO ][o.e.s.s.SuggestSearchIT  ] [testShardFailures] before test
[2019-06-16T00:22:35,026][INFO ][o.e.s.s.SuggestSearchIT  ] [testShardFailures] [SuggestSearchIT#testShardFailures]: setting up test
[2019-06-16T00:22:35,029][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:35,060][INFO ][o.e.s.s.SuggestSearchIT  ] [testShardFailures] [SuggestSearchIT#testShardFailures]: all set up test
[2019-06-16T00:22:35,061][INFO ][o.e.s.s.SuggestSearchIT  ] [testShardFailures] using custom data_path for index: [tsTdavBILR]
[2019-06-16T00:22:35,069][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[1], mappings [type2]
[2019-06-16T00:22:35,278][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
[2019-06-16T00:22:35,313][INFO ][o.e.c.m.MetaDataMappingService] [node_sm0] [test/4t_IwRvsQMOAvZKNRtBi3w] update_mapping [type2]
[2019-06-16T00:22:35,498][INFO ][o.e.s.s.SuggestSearchIT  ] [testShardFailures] [SuggestSearchIT#testShardFailures]: cleaning up after test
[2019-06-16T00:22:35,513][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/4t_IwRvsQMOAvZKNRtBi3w] deleting index
[2019-06-16T00:22:35,540][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] start check index
[2019-06-16T00:22:35,545][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] end check index
[2019-06-16T00:22:35,549][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:35,568][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:35,598][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:35,658][INFO ][o.e.s.s.SuggestSearchIT  ] [testShardFailures] [SuggestSearchIT#testShardFailures]: cleaned up after test
[2019-06-16T00:22:35,658][INFO ][o.e.s.s.SuggestSearchIT  ] [testShardFailures] after test
[2019-06-16T00:22:35,744][INFO ][o.e.s.s.SuggestSearchIT  ] [testSearchForRarePhrase] before test
[2019-06-16T00:22:35,744][INFO ][o.e.s.s.SuggestSearchIT  ] [testSearchForRarePhrase] [SuggestSearchIT#testSearchForRarePhrase]: setting up test
[2019-06-16T00:22:35,766][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:35,822][INFO ][o.e.s.s.SuggestSearchIT  ] [testSearchForRarePhrase] [SuggestSearchIT#testSearchForRarePhrase]: all set up test
[2019-06-16T00:22:35,827][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [8]/[0], mappings [type1]
[2019-06-16T00:22:36,019][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][5], [test][3], [test][1], [test][6], [test][0], [test][2], [test][7]] ...]).
[2019-06-16T00:22:39,300][INFO ][o.e.s.s.SuggestSearchIT  ] [testSearchForRarePhrase] [SuggestSearchIT#testSearchForRarePhrase]: cleaning up after test
[2019-06-16T00:22:39,318][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/lYLBXRoPQKSbnJEdMZtZQg] deleting index
[2019-06-16T00:22:39,340][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] start check index
[2019-06-16T00:22:39,340][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:39,342][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] end check index
[2019-06-16T00:22:39,342][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:39,379][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:39,383][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:39,384][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:39,400][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] start check index
[2019-06-16T00:22:39,421][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] start check index
[2019-06-16T00:22:39,426][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] end check index
[2019-06-16T00:22:39,452][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:39,461][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] end check index
[2019-06-16T00:22:39,496][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] start check index
[2019-06-16T00:22:39,527][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] end check index
[2019-06-16T00:22:39,559][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:39,582][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:39,614][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:39,635][INFO ][o.e.s.s.SuggestSearchIT  ] [testSearchForRarePhrase] [SuggestSearchIT#testSearchForRarePhrase]: cleaned up after test
[2019-06-16T00:22:39,636][INFO ][o.e.s.s.SuggestSearchIT  ] [testSearchForRarePhrase] after test
[2019-06-16T00:22:39,737][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeParam] before test
[2019-06-16T00:22:39,737][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeParam] [SuggestSearchIT#testSizeParam]: setting up test
[2019-06-16T00:22:39,746][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:39,780][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeParam] [SuggestSearchIT#testSizeParam]: all set up test
[2019-06-16T00:22:39,785][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[0], mappings [type1]
[2019-06-16T00:22:39,901][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
[2019-06-16T00:22:40,135][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeParam] [SuggestSearchIT#testSizeParam]: cleaning up after test
[2019-06-16T00:22:40,152][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/mju10AtQR2K_FE4YkqWjmQ] deleting index
[2019-06-16T00:22:40,177][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:40,179][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:40,215][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:40,232][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeParam] [SuggestSearchIT#testSizeParam]: cleaned up after test
[2019-06-16T00:22:40,232][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeParam] after test
[2019-06-16T00:22:40,294][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithFieldAlias] before test
[2019-06-16T00:22:40,294][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithFieldAlias] [SuggestSearchIT#testSuggestWithFieldAlias]: setting up test
[2019-06-16T00:22:40,307][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:40,330][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithFieldAlias] [SuggestSearchIT#testSuggestWithFieldAlias]: all set up test
[2019-06-16T00:22:40,337][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [10]/[0], mappings [type]
[2019-06-16T00:22:40,639][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][2]] ...]).
[2019-06-16T00:22:40,669][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithFieldAlias] Index [3] docs async: [true] bulk: [false]
[2019-06-16T00:22:40,744][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithFieldAlias] [SuggestSearchIT#testSuggestWithFieldAlias]: cleaning up after test
[2019-06-16T00:22:40,770][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/stvPvp_ET3-bu1lFN4PNNw] deleting index
[2019-06-16T00:22:40,783][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] start check index
[2019-06-16T00:22:40,783][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] start check index
[2019-06-16T00:22:40,788][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] end check index
[2019-06-16T00:22:40,792][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] end check index
[2019-06-16T00:22:40,816][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:40,819][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] start check index
[2019-06-16T00:22:40,819][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:40,828][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] end check index
[2019-06-16T00:22:40,849][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:40,853][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:40,860][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:40,860][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:40,869][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] start check index
[2019-06-16T00:22:40,882][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] end check index
[2019-06-16T00:22:40,885][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][9] start check index
[2019-06-16T00:22:40,899][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][9] end check index
[2019-06-16T00:22:40,902][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][8] start check index
[2019-06-16T00:22:40,918][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:40,920][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:40,951][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][8] end check index
[2019-06-16T00:22:40,987][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:41,011][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithFieldAlias] [SuggestSearchIT#testSuggestWithFieldAlias]: cleaned up after test
[2019-06-16T00:22:41,011][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestWithFieldAlias] after test
[2019-06-16T00:22:41,101][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmpty] before test
[2019-06-16T00:22:41,101][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmpty] [SuggestSearchIT#testEmpty]: setting up test
[2019-06-16T00:22:41,107][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:41,128][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmpty] [SuggestSearchIT#testEmpty]: all set up test
[2019-06-16T00:22:41,133][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [8]/[1], mappings [type1]
[2019-06-16T00:22:41,569][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][1]] ...]).
[2019-06-16T00:22:41,789][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmpty] [SuggestSearchIT#testEmpty]: cleaning up after test
[2019-06-16T00:22:41,823][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/_jt965jNTkuH2HTSitVB4Q] deleting index
[2019-06-16T00:22:41,848][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:41,849][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:41,852][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:41,852][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][2] start check index
[2019-06-16T00:22:41,855][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:41,856][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][2] end check index
[2019-06-16T00:22:41,871][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] start check index
[2019-06-16T00:22:41,873][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:41,879][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] end check index
[2019-06-16T00:22:41,879][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][3] start check index
[2019-06-16T00:22:41,881][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:41,882][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][3] end check index
[2019-06-16T00:22:41,896][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] start check index
[2019-06-16T00:22:41,896][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] start check index
[2019-06-16T00:22:41,901][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] end check index
[2019-06-16T00:22:41,902][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] start check index
[2019-06-16T00:22:41,903][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] end check index
[2019-06-16T00:22:41,905][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] end check index
[2019-06-16T00:22:41,913][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][5] start check index
[2019-06-16T00:22:41,917][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][0] start check index
[2019-06-16T00:22:41,920][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][0] end check index
[2019-06-16T00:22:41,923][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][5] end check index
[2019-06-16T00:22:41,923][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] start check index
[2019-06-16T00:22:41,929][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] end check index
[2019-06-16T00:22:41,929][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] start check index
[2019-06-16T00:22:41,932][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] end check index
[2019-06-16T00:22:41,935][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] start check index
[2019-06-16T00:22:41,937][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:41,938][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] end check index
[2019-06-16T00:22:41,940][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:41,946][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][7] start check index
[2019-06-16T00:22:41,949][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][7] end check index
[2019-06-16T00:22:41,980][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:42,012][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmpty] [SuggestSearchIT#testEmpty]: cleaned up after test
[2019-06-16T00:22:42,012][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmpty] after test
[2019-06-16T00:22:42,138][INFO ][o.e.s.s.SuggestSearchIT  ] [testSimple] before test
[2019-06-16T00:22:42,138][INFO ][o.e.s.s.SuggestSearchIT  ] [testSimple] [SuggestSearchIT#testSimple]: setting up test
[2019-06-16T00:22:42,143][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:42,184][INFO ][o.e.s.s.SuggestSearchIT  ] [testSimple] [SuggestSearchIT#testSimple]: all set up test
[2019-06-16T00:22:42,188][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [5]/[1], mappings [type1]
[2019-06-16T00:22:42,563][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][3]] ...]).
[2019-06-16T00:22:42,838][INFO ][o.e.s.s.SuggestSearchIT  ] [testSimple] [SuggestSearchIT#testSimple]: cleaning up after test
[2019-06-16T00:22:42,852][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/U8nhIvGER3KItoeGXriwGw] deleting index
[2019-06-16T00:22:42,863][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:42,879][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:42,881][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] start check index
[2019-06-16T00:22:42,884][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] end check index
[2019-06-16T00:22:42,911][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][0] start check index
[2019-06-16T00:22:42,920][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][2] start check index
[2019-06-16T00:22:42,920][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][0] end check index
[2019-06-16T00:22:42,923][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][2] end check index
[2019-06-16T00:22:42,923][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:42,931][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] start check index
[2019-06-16T00:22:42,932][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:42,933][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] end check index
[2019-06-16T00:22:42,942][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:42,942][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][3] start check index
[2019-06-16T00:22:42,944][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][3] end check index
[2019-06-16T00:22:42,944][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:42,946][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:42,949][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:42,958][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] start check index
[2019-06-16T00:22:42,961][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] end check index
[2019-06-16T00:22:42,987][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:43,017][INFO ][o.e.s.s.SuggestSearchIT  ] [testSimple] [SuggestSearchIT#testSimple]: cleaned up after test
[2019-06-16T00:22:43,018][INFO ][o.e.s.s.SuggestSearchIT  ] [testSimple] after test
[2019-06-16T00:22:43,079][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyIndex] before test
[2019-06-16T00:22:43,079][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyIndex] [SuggestSearchIT#testEmptyIndex]: setting up test
[2019-06-16T00:22:43,084][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:43,106][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyIndex] [SuggestSearchIT#testEmptyIndex]: all set up test
[2019-06-16T00:22:43,111][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [3]/[0], mappings [type1]
[2019-06-16T00:22:43,340][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][2], [test][1]] ...]).
[2019-06-16T00:22:43,438][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyIndex] [SuggestSearchIT#testEmptyIndex]: cleaning up after test
[2019-06-16T00:22:43,462][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/otkM_AGZRiSshr4nhnmv_g] deleting index
[2019-06-16T00:22:43,478][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:43,478][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:43,480][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:43,482][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:43,487][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:43,491][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:43,539][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:43,559][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyIndex] [SuggestSearchIT#testEmptyIndex]: cleaned up after test
[2019-06-16T00:22:43,559][INFO ][o.e.s.s.SuggestSearchIT  ] [testEmptyIndex] after test
[2019-06-16T00:22:43,625][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeOneShard] before test
[2019-06-16T00:22:43,625][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeOneShard] [SuggestSearchIT#testSizeOneShard]: setting up test
[2019-06-16T00:22:43,631][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:43,654][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeOneShard] [SuggestSearchIT#testSizeOneShard]: all set up test
[2019-06-16T00:22:43,654][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeOneShard] using custom data_path for index: [cNEPIBpNEt]
[2019-06-16T00:22:43,657][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[0], mappings []
[2019-06-16T00:22:43,719][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
[2019-06-16T00:22:43,750][INFO ][o.e.c.m.MetaDataMappingService] [node_sm0] [test/KTjOlNHvSUqoNhKwSZsE_A] create_mapping [type1]
[2019-06-16T00:22:43,857][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeOneShard] [SuggestSearchIT#testSizeOneShard]: cleaning up after test
[2019-06-16T00:22:43,873][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/KTjOlNHvSUqoNhKwSZsE_A] deleting index
[2019-06-16T00:22:43,885][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:43,887][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:43,911][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:43,944][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeOneShard] [SuggestSearchIT#testSizeOneShard]: cleaned up after test
[2019-06-16T00:22:43,944][INFO ][o.e.s.s.SuggestSearchIT  ] [testSizeOneShard] after test
[2019-06-16T00:22:43,988][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestModes] before test
[2019-06-16T00:22:43,988][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestModes] [SuggestSearchIT#testSuggestModes]: setting up test
[2019-06-16T00:22:43,993][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:44,013][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestModes] [SuggestSearchIT#testSuggestModes]: all set up test
[2019-06-16T00:22:44,016][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[0], mappings [type1]
[2019-06-16T00:22:44,109][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
[2019-06-16T00:22:44,182][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestModes] [SuggestSearchIT#testSuggestModes]: cleaning up after test
[2019-06-16T00:22:44,197][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/q8eKDfaSSnSVVJiYeUk2YQ] deleting index
[2019-06-16T00:22:44,206][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:44,208][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:44,229][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:44,245][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestModes] [SuggestSearchIT#testSuggestModes]: cleaned up after test
[2019-06-16T00:22:44,245][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestModes] after test
[2019-06-16T00:22:44,284][INFO ][o.e.s.s.SuggestSearchIT  ] [testUnmappedField] before test
[2019-06-16T00:22:44,284][INFO ][o.e.s.s.SuggestSearchIT  ] [testUnmappedField] [SuggestSearchIT#testUnmappedField]: setting up test
[2019-06-16T00:22:44,291][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:44,313][INFO ][o.e.s.s.SuggestSearchIT  ] [testUnmappedField] [SuggestSearchIT#testUnmappedField]: all set up test
[2019-06-16T00:22:44,314][INFO ][o.e.s.s.SuggestSearchIT  ] [testUnmappedField] using custom data_path for index: [pCFvcrJmFU]
[2019-06-16T00:22:44,319][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [7]/[0], mappings [type1]
[2019-06-16T00:22:44,493][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][4]] ...]).
[2019-06-16T00:22:44,517][INFO ][o.e.s.s.SuggestSearchIT  ] [testUnmappedField] Index [3] docs async: [true] bulk: [false]
[2019-06-16T00:22:44,605][INFO ][o.e.s.s.SuggestSearchIT  ] [testUnmappedField] [SuggestSearchIT#testUnmappedField]: cleaning up after test
[2019-06-16T00:22:44,614][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/kJJNpU1tSgKLfcy8djuytg] deleting index
[2019-06-16T00:22:44,625][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:44,627][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:44,627][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:44,630][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:44,630][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] start check index
[2019-06-16T00:22:44,633][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] end check index
[2019-06-16T00:22:44,646][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] start check index
[2019-06-16T00:22:44,648][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:44,649][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] start check index
[2019-06-16T00:22:44,652][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] end check index
[2019-06-16T00:22:44,652][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:44,656][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] end check index
[2019-06-16T00:22:44,668][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:44,671][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:44,701][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:44,727][INFO ][o.e.s.s.SuggestSearchIT  ] [testUnmappedField] [SuggestSearchIT#testUnmappedField]: cleaned up after test
[2019-06-16T00:22:44,727][INFO ][o.e.s.s.SuggestSearchIT  ] [testUnmappedField] after test
[2019-06-16T00:22:44,800][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggesterCollate] before test
[2019-06-16T00:22:44,800][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggesterCollate] [SuggestSearchIT#testPhraseSuggesterCollate]: setting up test
[2019-06-16T00:22:44,807][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:44,846][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggesterCollate] [SuggestSearchIT#testPhraseSuggesterCollate]: all set up test
[2019-06-16T00:22:44,850][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[1], mappings [type1]
[2019-06-16T00:22:45,041][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
[2019-06-16T00:22:45,057][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggesterCollate] Index [8] docs async: [true] bulk: [false]
[2019-06-16T00:22:45,627][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggesterCollate] [SuggestSearchIT#testPhraseSuggesterCollate]: cleaning up after test
[2019-06-16T00:22:45,641][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/YKhvGRzcTWOH2QYF3OnoYg] deleting index
[2019-06-16T00:22:45,666][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] start check index
[2019-06-16T00:22:45,669][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] end check index
[2019-06-16T00:22:45,684][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:45,728][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:45,755][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:45,804][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggesterCollate] [SuggestSearchIT#testPhraseSuggesterCollate]: cleaned up after test
[2019-06-16T00:22:45,804][INFO ][o.e.s.s.SuggestSearchIT  ] [testPhraseSuggesterCollate] after test
[2019-06-16T00:22:45,957][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] before test
[2019-06-16T00:22:45,957][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] [SuggestSearchIT#testSuggestAcrossMultipleIndices]: setting up test
[2019-06-16T00:22:45,964][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:45,986][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] [SuggestSearchIT#testSuggestAcrossMultipleIndices]: all set up test
[2019-06-16T00:22:45,995][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [9]/[1], mappings [type1]
[2019-06-16T00:22:46,582][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][6], [test][5]] ...]).
[2019-06-16T00:22:46,803][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] --> run suggestions with one index
[2019-06-16T00:22:46,815][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] using custom data_path for index: [YPEfPMWmEP]
[2019-06-16T00:22:46,821][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test_1] creating index, cause [api], templates [random_index_template], shards [3]/[1], mappings [type1]
[2019-06-16T00:22:47,068][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test_1][2], [test_1][0]] ...]).
[2019-06-16T00:22:47,228][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] --> run suggestions with two indices
[2019-06-16T00:22:47,238][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test_2] creating index, cause [api], templates [random_index_template], shards [4]/[0], mappings [type1]
[2019-06-16T00:22:47,393][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test_2][2], [test_2][3], [test_2][0]] ...]).
[2019-06-16T00:22:47,539][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] --> run suggestions with three indices
[2019-06-16T00:22:47,557][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] --> run suggestions with four indices
[2019-06-16T00:22:47,566][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] [SuggestSearchIT#testSuggestAcrossMultipleIndices]: cleaning up after test
[2019-06-16T00:22:47,611][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/liwp2Dw0T020rbbSc7vZSQ] deleting index
[2019-06-16T00:22:47,611][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test_2/9xYA0cCeRD-KwUa6q5sekw] deleting index
[2019-06-16T00:22:47,611][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test_1/p3wenywLTHeiW87dEoUpvg] deleting index
[2019-06-16T00:22:47,620][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:47,620][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] start check index
[2019-06-16T00:22:47,620][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] start check index
[2019-06-16T00:22:47,623][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:47,624][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] end check index
[2019-06-16T00:22:47,628][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][0] end check index
[2019-06-16T00:22:47,630][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][2] start check index
[2019-06-16T00:22:47,633][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][2] end check index
[2019-06-16T00:22:47,634][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:47,637][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:47,640][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:47,641][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:47,642][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:47,643][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:47,645][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][3] start check index
[2019-06-16T00:22:47,647][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][3] end check index
[2019-06-16T00:22:47,650][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] start check index
[2019-06-16T00:22:47,652][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] start check index
[2019-06-16T00:22:47,653][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] end check index
[2019-06-16T00:22:47,654][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] end check index
[2019-06-16T00:22:47,660][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] start check index
[2019-06-16T00:22:47,661][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] start check index
[2019-06-16T00:22:47,662][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] end check index
[2019-06-16T00:22:47,663][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] end check index
[2019-06-16T00:22:47,664][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][5] start check index
[2019-06-16T00:22:47,667][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][5] end check index
[2019-06-16T00:22:47,672][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][8] start check index
[2019-06-16T00:22:47,672][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][7] start check index
[2019-06-16T00:22:47,674][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][8] end check index
[2019-06-16T00:22:47,676][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] start check index
[2019-06-16T00:22:47,676][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][7] end check index
[2019-06-16T00:22:47,678][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] end check index
[2019-06-16T00:22:47,685][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][8] start check index
[2019-06-16T00:22:47,685][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] start check index
[2019-06-16T00:22:47,688][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test_2][3] start check index
[2019-06-16T00:22:47,688][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][8] end check index
[2019-06-16T00:22:47,688][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] end check index
[2019-06-16T00:22:47,690][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test_2][3] end check index
[2019-06-16T00:22:47,705][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test_2][1] start check index
[2019-06-16T00:22:47,705][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test_2][2] start check index
[2019-06-16T00:22:47,707][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test_2][2] end check index
[2019-06-16T00:22:47,707][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test_2][1] end check index
[2019-06-16T00:22:47,711][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test_2][0] start check index
[2019-06-16T00:22:47,713][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test_2][0] end check index
[2019-06-16T00:22:47,718][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test_1][0] start check index
[2019-06-16T00:22:47,722][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test_1][0] end check index
[2019-06-16T00:22:47,726][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test_1][2] start check index
[2019-06-16T00:22:47,728][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test_1][2] end check index
[2019-06-16T00:22:47,736][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test_1][2] start check index
[2019-06-16T00:22:47,740][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test_1][0] start check index
[2019-06-16T00:22:47,742][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test_1][0] end check index
[2019-06-16T00:22:47,744][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test_1][1] start check index
[2019-06-16T00:22:47,749][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test_1][2] end check index
[2019-06-16T00:22:47,752][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test_1][1] end check index
[2019-06-16T00:22:47,764][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test_1][1] start check index
[2019-06-16T00:22:47,767][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test_1][1] end check index
[2019-06-16T00:22:47,815][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:47,838][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] [SuggestSearchIT#testSuggestAcrossMultipleIndices]: cleaned up after test
[2019-06-16T00:22:47,838][INFO ][o.e.s.s.SuggestSearchIT  ] [testSuggestAcrossMultipleIndices] after test
[2019-06-16T00:22:47,857][INFO ][o.e.s.s.SuggestSearchIT  ] [testWithMultipleCommands] before test
[2019-06-16T00:22:47,857][INFO ][o.e.s.s.SuggestSearchIT  ] [testWithMultipleCommands] [SuggestSearchIT#testWithMultipleCommands]: setting up test
[2019-06-16T00:22:47,863][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:47,903][INFO ][o.e.s.s.SuggestSearchIT  ] [testWithMultipleCommands] [SuggestSearchIT#testWithMultipleCommands]: all set up test
[2019-06-16T00:22:47,908][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [8]/[1], mappings [typ1]
[2019-06-16T00:22:48,277][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][7], [test][6]] ...]).
[2019-06-16T00:22:48,523][INFO ][o.e.s.s.SuggestSearchIT  ] [testWithMultipleCommands] [SuggestSearchIT#testWithMultipleCommands]: cleaning up after test
[2019-06-16T00:22:48,542][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/H16yh42yTXGhEMvOzNNqkA] deleting index
[2019-06-16T00:22:48,558][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][2] start check index
[2019-06-16T00:22:48,558][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] start check index
[2019-06-16T00:22:48,560][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] start check index
[2019-06-16T00:22:48,561][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][2] end check index
[2019-06-16T00:22:48,562][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][1] end check index
[2019-06-16T00:22:48,566][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][2] end check index
[2019-06-16T00:22:48,569][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] start check index
[2019-06-16T00:22:48,571][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][5] end check index
[2019-06-16T00:22:48,571][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][3] start check index
[2019-06-16T00:22:48,573][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] start check index
[2019-06-16T00:22:48,574][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][3] end check index
[2019-06-16T00:22:48,574][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][3] end check index
[2019-06-16T00:22:48,580][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] start check index
[2019-06-16T00:22:48,587][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] start check index
[2019-06-16T00:22:48,587][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][4] end check index
[2019-06-16T00:22:48,589][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][4] end check index
[2019-06-16T00:22:48,595][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] start check index
[2019-06-16T00:22:48,596][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][5] start check index
[2019-06-16T00:22:48,601][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][6] end check index
[2019-06-16T00:22:48,603][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][5] end check index
[2019-06-16T00:22:48,611][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] start check index
[2019-06-16T00:22:48,613][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:48,616][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:48,618][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][6] end check index
[2019-06-16T00:22:48,618][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][7] start check index
[2019-06-16T00:22:48,627][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] start check index
[2019-06-16T00:22:48,629][INFO ][o.e.t.s.M.Listener       ] [node_sd5] [test][7] end check index
[2019-06-16T00:22:48,631][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][7] end check index
[2019-06-16T00:22:48,642][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][0] start check index
[2019-06-16T00:22:48,645][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][0] end check index
[2019-06-16T00:22:48,661][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] start check index
[2019-06-16T00:22:48,668][INFO ][o.e.t.s.M.Listener       ] [node_sd3] [test][1] end check index
[2019-06-16T00:22:48,696][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:48,725][INFO ][o.e.s.s.SuggestSearchIT  ] [testWithMultipleCommands] [SuggestSearchIT#testWithMultipleCommands]: cleaned up after test
[2019-06-16T00:22:48,725][INFO ][o.e.s.s.SuggestSearchIT  ] [testWithMultipleCommands] after test
[2019-06-16T00:22:48,750][INFO ][o.e.s.s.SuggestSearchIT  ] [testPrefixLength] before test
[2019-06-16T00:22:48,750][INFO ][o.e.s.s.SuggestSearchIT  ] [testPrefixLength] [SuggestSearchIT#testPrefixLength]: setting up test
[2019-06-16T00:22:48,754][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] adding template [random_index_template] for index patterns [*]
[2019-06-16T00:22:48,786][INFO ][o.e.s.s.SuggestSearchIT  ] [testPrefixLength] [SuggestSearchIT#testPrefixLength]: all set up test
[2019-06-16T00:22:48,790][INFO ][o.e.c.m.MetaDataCreateIndexService] [node_sm0] [test] creating index, cause [api], templates [random_index_template], shards [1]/[0], mappings [type1]
[2019-06-16T00:22:48,868][INFO ][o.e.c.r.a.AllocationService] [node_sm0] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[test][0]] ...]).
[2019-06-16T00:22:48,947][INFO ][o.e.s.s.SuggestSearchIT  ] [testPrefixLength] [SuggestSearchIT#testPrefixLength]: cleaning up after test
[2019-06-16T00:22:48,964][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node_sm0] [test/aHEjRDfdTfO-J0CXZwwODA] deleting index
[2019-06-16T00:22:48,975][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] start check index
[2019-06-16T00:22:48,977][INFO ][o.e.t.s.M.Listener       ] [node_sd4] [test][0] end check index
[2019-06-16T00:22:49,007][INFO ][o.e.c.m.MetaDataIndexTemplateService] [node_sm0] removing template [random_index_template]
[2019-06-16T00:22:49,067][INFO ][o.e.s.s.SuggestSearchIT  ] [testPrefixLength] [SuggestSearchIT#testPrefixLength]: cleaned up after test
[2019-06-16T00:22:49,067][INFO ][o.e.s.s.SuggestSearchIT  ] [testPrefixLength] after test
[2019-06-16T00:22:49,068][INFO ][o.e.n.Node               ] [suite] stopping ...
[2019-06-16T00:22:49,069][INFO ][o.e.c.c.Coordinator      ] [node_sd3] master node [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}] failed, restarting discovery
org.elasticsearch.transport.NodeDisconnectedException: [node_sm0][127.0.0.1:46535][disconnected] disconnected
[2019-06-16T00:22:49,071][INFO ][o.e.c.s.MasterService    ] [node_sm0] node-left[{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675} disconnected], term: 2, version: 172, reason: removed {{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}
[2019-06-16T00:22:49,071][INFO ][o.e.n.Node               ] [suite] stopped
[2019-06-16T00:22:49,071][INFO ][o.e.n.Node               ] [suite] closing ...
[2019-06-16T00:22:49,080][INFO ][o.e.c.s.ClusterApplierService] [node_sm1] removed {{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 172, reason: ApplyCommitRequest{term=2, version=172, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:49,080][INFO ][o.e.c.s.ClusterApplierService] [node_sd5] removed {{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 172, reason: ApplyCommitRequest{term=2, version=172, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:49,080][INFO ][o.e.c.s.ClusterApplierService] [node_sd4] removed {{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 172, reason: ApplyCommitRequest{term=2, version=172, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:49,080][INFO ][o.e.c.s.ClusterApplierService] [node_sm2] removed {{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 172, reason: ApplyCommitRequest{term=2, version=172, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:49,099][INFO ][o.e.c.s.ClusterApplierService] [node_sm0] removed {{node_sd3}{KeaMgMqNRLeBSYexn54Xwg}{p9zxYSmMQrGBh-Zy4CB1bw}{127.0.0.1}{127.0.0.1:45675},}, term: 2, version: 172, reason: Publication{term=2, version=172}
[2019-06-16T00:22:49,102][INFO ][o.e.n.Node               ] [suite] closed
[2019-06-16T00:22:49,105][INFO ][o.e.n.Node               ] [suite] stopping ...
[2019-06-16T00:22:49,110][INFO ][o.e.c.c.Coordinator      ] [node_sd4] master node [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}] failed, restarting discovery
org.elasticsearch.transport.NodeDisconnectedException: [node_sm0][127.0.0.1:46535][disconnected] disconnected
[2019-06-16T00:22:49,112][INFO ][o.e.n.Node               ] [suite] stopped
[2019-06-16T00:22:49,112][INFO ][o.e.n.Node               ] [suite] closing ...
[2019-06-16T00:22:49,112][INFO ][o.e.c.s.MasterService    ] [node_sm0] node-left[{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999} disconnected], term: 2, version: 173, reason: removed {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},}
[2019-06-16T00:22:49,113][INFO ][o.e.n.Node               ] [suite] closed
[2019-06-16T00:22:49,116][INFO ][o.e.n.Node               ] [suite] stopping ...
[2019-06-16T00:22:49,117][INFO ][o.e.c.s.ClusterApplierService] [node_sm2] removed {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},}, term: 2, version: 173, reason: ApplyCommitRequest{term=2, version=173, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:49,119][INFO ][o.e.c.s.ClusterApplierService] [node_sd5] removed {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},}, term: 2, version: 173, reason: ApplyCommitRequest{term=2, version=173, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:49,119][INFO ][o.e.c.s.ClusterApplierService] [node_sm1] removed {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},}, term: 2, version: 173, reason: ApplyCommitRequest{term=2, version=173, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:49,123][INFO ][o.e.c.c.Coordinator      ] [node_sd5] master node [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}] failed, restarting discovery
org.elasticsearch.transport.NodeDisconnectedException: [node_sm0][127.0.0.1:46535][disconnected] disconnected
[2019-06-16T00:22:49,124][INFO ][o.e.c.s.ClusterApplierService] [node_sm0] removed {{node_sd4}{v0vb8-EHTdSG4MCGdUC88g}{_j0SytYmR8uZnXeH_C_C8Q}{127.0.0.1}{127.0.0.1:45999},}, term: 2, version: 173, reason: Publication{term=2, version=173}
[2019-06-16T00:22:49,128][INFO ][o.e.n.Node               ] [suite] stopped
[2019-06-16T00:22:49,128][INFO ][o.e.n.Node               ] [suite] closing ...
[2019-06-16T00:22:49,128][INFO ][o.e.c.s.MasterService    ] [node_sm0] node-left[{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927} disconnected], term: 2, version: 174, reason: removed {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}
[2019-06-16T00:22:49,131][INFO ][o.e.n.Node               ] [suite] closed
[2019-06-16T00:22:49,132][INFO ][o.e.n.Node               ] [suite] stopping ...
[2019-06-16T00:22:49,132][INFO ][o.e.c.s.ClusterApplierService] [node_sm1] removed {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}, term: 2, version: 174, reason: ApplyCommitRequest{term=2, version=174, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:49,133][INFO ][o.e.c.s.ClusterApplierService] [node_sm2] removed {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}, term: 2, version: 174, reason: ApplyCommitRequest{term=2, version=174, sourceNode={node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}}
[2019-06-16T00:22:49,140][INFO ][o.e.c.s.ClusterApplierService] [node_sm0] removed {{node_sd5}{nPPKc3kZSFyw12vUPyEQCQ}{Sw6FYmuPSv2XGSsodzf8Gg}{127.0.0.1}{127.0.0.1:39927},}, term: 2, version: 174, reason: Publication{term=2, version=174}
[2019-06-16T00:22:49,145][INFO ][o.e.c.c.Coordinator      ] [node_sm1] master node [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}] failed, restarting discovery
org.elasticsearch.transport.NodeDisconnectedException: [node_sm0][127.0.0.1:46535][disconnected] disconnected
[2019-06-16T00:22:49,145][INFO ][o.e.c.c.Coordinator      ] [node_sm2] master node [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}] failed, restarting discovery
org.elasticsearch.transport.NodeDisconnectedException: [node_sm0][127.0.0.1:46535][disconnected] disconnected
[2019-06-16T00:22:49,146][INFO ][o.e.c.s.ClusterApplierService] [node_sm1] master node changed {previous [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}], current []}, term: 2, version: 174, reason: becoming candidate: onLeaderFailure
[2019-06-16T00:22:49,147][INFO ][o.e.c.s.ClusterApplierService] [node_sm2] master node changed {previous [{node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535}], current []}, term: 2, version: 174, reason: becoming candidate: onLeaderFailure
[2019-06-16T00:22:49,148][INFO ][o.e.n.Node               ] [suite] stopped
[2019-06-16T00:22:49,148][INFO ][o.e.n.Node               ] [suite] closing ...
[2019-06-16T00:22:49,164][INFO ][o.e.n.Node               ] [suite] closed
[2019-06-16T00:22:49,165][INFO ][o.e.n.Node               ] [suite] stopping ...
[2019-06-16T00:22:49,167][WARN ][o.e.c.NodeConnectionsService] [node_sm1] failed to connect to {node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535} (tried [1] times)
org.elasticsearch.transport.ConnectTransportException: [node_sm0][127.0.0.1:46535] connect_exception
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:957) ~[main/:?]
	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$3(ActionListener.java:161) ~[main/:?]
	at org.elasticsearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:42) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at org.elasticsearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:57) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:120) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.EventHandler.handleConnect(EventHandler.java:97) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.nio.TestEventHandler.handleConnect(TestEventHandler.java:99) ~[framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.attemptConnect(NioSelector.java:405) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.setUpNewChannels(NioSelector.java:422) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.preSelect(NioSelector.java:261) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:153) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[?:?]
	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:117) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	... 8 more
[2019-06-16T00:22:49,167][WARN ][o.e.c.NodeConnectionsService] [node_sm2] failed to connect to {node_sm0}{lhg4m8KfR8WgdtRCHz3YGA}{mlGvshZLScOJIyef40DC6w}{127.0.0.1}{127.0.0.1:46535} (tried [1] times)
org.elasticsearch.transport.ConnectTransportException: [node_sm0][127.0.0.1:46535] connect_exception
	at org.elasticsearch.transport.TcpTransport$ChannelsConnectedListener.onFailure(TcpTransport.java:957) ~[main/:?]
	at org.elasticsearch.action.ActionListener.lambda$toBiConsumer$3(ActionListener.java:161) ~[main/:?]
	at org.elasticsearch.common.concurrent.CompletableContext.lambda$addListener$0(CompletableContext.java:42) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088) ~[?:?]
	at org.elasticsearch.common.concurrent.CompletableContext.completeExceptionally(CompletableContext.java:57) ~[elasticsearch-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:120) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.EventHandler.handleConnect(EventHandler.java:97) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.transport.nio.TestEventHandler.handleConnect(TestEventHandler.java:99) ~[framework-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.attemptConnect(NioSelector.java:405) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.setUpNewChannels(NioSelector.java:422) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.preSelect(NioSelector.java:261) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:153) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:129) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779) ~[?:?]
	at org.elasticsearch.nio.SocketChannelContext.connect(SocketChannelContext.java:117) ~[elasticsearch-nio-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	... 8 more
[2019-06-16T00:22:49,180][INFO ][o.e.n.Node               ] [suite] stopped
[2019-06-16T00:22:49,180][INFO ][o.e.n.Node               ] [suite] closing ...
[2019-06-16T00:22:49,188][INFO ][o.e.n.Node               ] [suite] closed
[2019-06-16T00:22:49,193][INFO ][o.e.n.Node               ] [suite] stopping ...
[2019-06-16T00:22:49,200][INFO ][o.e.n.Node               ] [suite] stopped
[2019-06-16T00:22:49,200][INFO ][o.e.n.Node               ] [suite] closing ...
[2019-06-16T00:22:49,202][INFO ][o.e.n.Node               ] [suite] closed
```

### PR DESCRIPTION
**Pull request by cbuescher**
Refreshes happening during indexing can result different segment counts and
slightly skewed term statistics, which in turn has the potential to change
suggestion output slightly. In order to prevent this, disable refresh for the
affected tests.

Closes #43261

### CODE REVIEW

**Comment by cbuescher** [comment]
@elasticmachine update branch

File: server/src/test/java/org/elasticsearch/search/suggest/SuggestSearchIT.java [hunk 1]
```diff
@@ -775,6 +775,7 @@ public void testEmptyShards() throws IOException, InterruptedException {
         assertAcked(prepareCreate("test").setSettings(Settings.builder()
                 .put(indexSettings())
                 .put(IndexSettings.MAX_SHINGLE_DIFF_SETTING.getKey(), 4)
+                .put("index.refresh_interval", -1)  // prevents occasional scoring glitches due to multi segments
```
Comment (mayya-sharipova) [inline server/src/test/java/org/elasticsearch/search/suggest/SuggestSearchIT.java]: @cbuescher I am not completely clear how multiple segments should change scoring. I thought scores should be the same regardless of number of segments.  Should we instead change the number of shards in the index to be `1`? 
But I am also in favour of completely removing the last part of this test with documents, as the test is about empty shards

**Review by mayya-sharipova — CHANGES_REQUESTED** [review]
@cbuescher thanks for the extensive investigation on this failure.  I have left some comments

File: server/src/test/java/org/elasticsearch/search/suggest/SuggestSearchIT.java (hunk 1 above)
Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/search/suggest/SuggestSearchIT.java]: Its not about scoring (as in search scoring) per se here. The way WordScorer uses the term frequencies of an index reader seems to differ depending on how many leaves it has, at least that is what Simon told me. I don't pretend to understand the subtleties here. I wouldn't like to change the random number of shards here because I think that coverage is important here, but turning of refresh is fine I think and what we seem do to in a lot of places (just grepped and found about 36 cases of this in tests).

Comment (mayya-sharipova) [reply server/src/test/java/org/elasticsearch/search/suggest/SuggestSearchIT.java]: @cbuescher Thanks for explanation.

**Review by mayya-sharipova — APPROVED** [review]

**Comment by cbuescher** [comment]
@mayya-sharipova thanks for the review, will merge.
