### PR TITLE
ES|QL: Fix pruning of Project columns in FORK branches

### LINKED ISSUE #146418: ESQL: Project optimized incorrectly due to missing attributes in subplans
### Description

```
 from countries_bbox_web 
| registered_domain x = "elastic.co" 
| user_agent y = name 
| stats  y.os.full = count(*), z = count(*) by x.subdomain 
| FORK (where NOT starts_with(x.subdomain, "v")) 
| sort y.os.full
| stats  z = count(*)
```

results in

```
                "type": "illegal_state_exception",
                "reason": "Found 1 problem\nline 5:3: Plan [Project[[y.os.full{r}#1397, y.os.full{r}#1397 AS z#1399]]] optimized incorrectly due to missing attributes in subplans: [[y.os.full{r}#1397]]",
                "stack_trace": "org.elasticsearch.ElasticsearchException$1: Found 1 problem\nline 5:3: Plan [Project[[y.os.full{r}#1397, y.os.full{r}#1397 AS z#1399]]] optimized incorrectly due to missing attributes in subplans: [[y.os.full{r}#1397]]
```

### PR DESCRIPTION
**Pull request by ioanatia**
closes https://github.com/elastic/elasticsearch/issues/146418

I messed up the pruning of columns for FORK when I removed the implicit limit, with the changes I made in `PruneColumns`.

However just changing `PruneColumns` is not enough. This only fixes queries like:

```
           from employees
                | stats x = count(*), y = count(*) by emp_no
                | FORK (where emp_no > 10000)
                | sort x
                | stats y = count(*)
```

There is another class of failures that can happen, that has less to do with removing the implicit LIMIT for FORK, but with `ProjectAwayColumns` which is a physical optimization rule.

Queries like the following will fail, even with the fix from `PruneColumns`:
```
             from employees
            | FORK ( stats z = count(*) by salary)
                   ( where emp_no > 10000)
            | stats y = count(*) 
```

That's because `PruneColumns` correctly removes all columns from FORK branches, such that the output of FORK does not contain any columns.
In `ProjectAwayColumns`, we add the `<all-columns-projected>` column just to the second branch (with WHERE), while the first one still has an empty output (because it uses aggs).
Then the query fails because the FORK branches no longer have the same output.

The fix I found is to simply skip applying `ProjectAwayColumns` to FORK branches, when the output of FORK is already empty.
I don't know if by doing this, I am missing other subtle ways queries can fail, but AFAICS all the queries I tested where FORK is pruned with an empty output seem to work.

### CODE REVIEW

**Comment by ioanatia** [comment]
putting it back in draft, I found another downstream issue with `ProjectAwayColumns`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java [hunk 1]
```diff
@@ -258,8 +258,22 @@ private static LogicalPlan pruneColumnsInFork(Fork fork, AttributeSet.Builder us
...
+                newSubPlan = subPlan.transformDown(Project.class, p -> {
+                    if (projectVisited.get()) {
+                        return p;
+                    }
+                    projectVisited.set(true);
+                    // filter projections based on fork output attributes
+                    var prunedAttrs = p.projections().stream().filter(x -> forkOutputNames.contains(x.name())).toList();
+                    p = new Project(p.source(), p.child(), prunedAttrs);
+                    // add all output attributes to used set
+                    return p;
```
Comment (carlosdelest) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java]: Nit - the comment looks wrong?

```suggestion
                    return new Project(p.source(), p.child(), prunedAttrs);
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/ProjectAwayColumns.java [hunk 2]
```diff
@@ -55,6 +55,12 @@ public PhysicalPlan apply(PhysicalPlan plan) {
             // for non-unary execution plans, we apply the rule for each child
             if (currentPlanNode instanceof MergeExec mergeExec) {
                 keepTraversing.set(FALSE);
+
+                if (mergeExec.output().isEmpty()) {
```
Comment (ioanatia) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/ProjectAwayColumns.java:59]: @fang-xing-esql this is related to some of the changes made in https://github.com/elastic/elasticsearch/pull/145164

I am not sure if by doing this I am missing any other subtle ways the query can fail.
But this seems to fix the types of queries where the output of the branches is empty, etc:

```
             from employees
            | FORK ( stats z = count(*) by salary)
                   ( where emp_no > 10000)
            | stats y = count(*) 
```
In this case, without this fix, the second branch will contain `<all-projected-fields>`, while the first one does not, which then causes the query to fail.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java [hunk 3]
```diff
@@ -258,8 +255,22 @@ private static LogicalPlan pruneColumnsInFork(Fork fork, AttributeSet.Builder us
                 var outputAttrs = localRelation.output().stream().filter(x -> forkOutputNames.contains(x.name())).toList();
                 newSubPlan = new LocalRelation(localRelation.source(), outputAttrs, localRelation.supplier());
             } else {
+                // otherwise, we first prune the projections of the top-level Project of each subplan
                 subPlan.outputSet().stream().filter(x -> forkOutputNames.contains(x.name())).forEach(usedAttrs::add);
-                newSubPlan = pruneColumns(subPlan, usedAttrs, false);
+
+                Holder<Boolean> projectVisited = new Holder<>(false);
```
Comment (ioanatia) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java:261]: I am mostly reverting the changes I made to this file when we removed the implicit limit for fork from https://github.com/elastic/elasticsearch/pull/145429

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/ProjectAwayColumns.java (hunk 2 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/ProjectAwayColumns.java:59]: Thanks for the heads up @ioanatia, I double checked the related tests added by #145164, they seem still work fine. 

This is what I see in the log for the query above, `PruneColumns` removed the output of `Project` in both branches and kept the empty `Project` node in both branches, later on `CombineProjections` removed the empty `Project` node from the first branch only. From plan consistency perspective, we should have preserved the empty `Project` from each branch in my opinion and keep the final output of the fork and its each branch consistent, but I understand the complexity there in `PruneColumns`. 

So the plan carries different branch output on to the physical plan phase, and the different branch output is seen here. It is good news skipping empty `MergeExec` here didn't cause existing tests to fail. If time allows, we should preserve the consistency between the final `Fork` output and the output of its branches, or as a follow up as soon as possible.

```
[2026-04-17T15:19:27,237][TRACE][o.e.x.e.o.L.changes      ] [runTask-0] Rule logical.PruneColumns applied with change
Limit[1000[INTEGER],false,false]                                                                                             = Limit[1000[INTEGER],false,false]
\_Aggregate[[],[COUNT(*[KEYWORD],true[BOOLEAN],PT0S[TIME_DURATION]) AS count(*)#32]]                                         = \_Aggregate[[],[COUNT(*[KEYWORD],true[BOOLEAN],PT0S[TIME_DURATION]) AS count(*)#32]]
  \_Fork[[count(*){r}#43, client.ip{r}#44, _fork{r}#45, event.duration{r}#46]]                                               !   \_Fork[[]]
    |_Project[[count(*){r}#28, client.ip{f}#34, _fork{r}#30, event.duration{r}#41]]                                          !     |_Project[[]]
    | \_Eval[[fork1[KEYWORD] AS _fork#30, null[LONG] AS event.duration#41]]                                                  !     | \_Aggregate[[client.ip{f}#34],[client.ip{f}#34 AS count(*)#34]]
    |   \_Aggregate[[client.ip{f}#34],[COUNT(*[KEYWORD],true[BOOLEAN],PT0S[TIME_DURATION]) AS count(*)#28, client.ip{f}#34]] !     |   \_EsRelation[sample_data][client.ip{f}#34, event.duration{f}#36]
    |     \_EsRelation[sample_data][client.ip{f}#34, event.duration{f}#36]                                                   !     \_Project[[]]
    \_Project[[count(*){r}#42, client.ip{f}#38, _fork{r}#31, event.duration{f}#40]]                                          !       \_Filter[event.duration{f}#40 < 1000000[INTEGER]]
      \_Eval[[fork2[KEYWORD] AS _fork#31, null[LONG] AS count(*)#42]]                                                        !         \_EsRelation[sample_data][client.ip{f}#38, event.duration{f}#40]
        \_Filter[event.duration{f}#40 < 1000000[INTEGER]]                                                                    ! 
          \_EsRelation[sample_data][client.ip{f}#38, event.duration{f}#40]                                                   ! 


[2026-04-17T15:19:27,239][TRACE][o.e.x.e.o.L.changes      ] [runTask-0] Rule logical.CombineProjections applied with change
Limit[1000[INTEGER],false,false]                                                     = Limit[1000[INTEGER],false,false]
\_Aggregate[[],[COUNT(*[KEYWORD],true[BOOLEAN],PT0S[TIME_DURATION]) AS count(*)#32]] = \_Aggregate[[],[COUNT(*[KEYWORD],true[BOOLEAN],PT0S[TIME_DURATION]) AS count(*)#32]]
  \_Fork[[]]                                                                         =   \_Fork[[]]
    |_Project[[]]                                                                    !     |_Aggregate[[client.ip{f}#34],[]]
    | \_Aggregate[[client.ip{f}#34],[client.ip{f}#34 AS count(*)#34]]                !     | \_EsRelation[sample_data][client.ip{f}#34, event.duration{f}#36]
    |   \_EsRelation[sample_data][client.ip{f}#34, event.duration{f}#36]             !     \_Project[[]]
    \_Project[[]]                                                                    !       \_Filter[event.duration{f}#40 < 1000000[INTEGER]]
      \_Filter[event.duration{f}#40 < 1000000[INTEGER]]                              !         \_EsRelation[sample_data][client.ip{f}#38, event.duration{f}#40]
        \_EsRelation[sample_data][client.ip{f}#38, event.duration{f}#40]             ! 
```

**Review by carlosdelest — APPROVED** [review]
LGTM
