### PR TITLE
Synchronize snapshot deletions on the cluster state

### LINKED ISSUE #19957: Improve resiliency of snapshot deletions
Currently, when we try to delete a snapshot, we first check to see if a snapshot or a restore is in progress, and if so, we prevent the deletion from happening.  While this takes care of most cases, the possibility of a race condition still exists here because once the deletion operation passes this initial check, it commences with deleting the snapshot files, and if in the meantime while executing the delete operation, a snapshot or restore operation is started, we don't have any way of knowing a deletion is executing and hence the snapshot or restore operation should not be permitted.  

This can lead to race conditions where we are restoring a snapshot that is under deletion, or we are taking a snapshot of an index while some of its files are being deleted by the deletion operation.  This can also lead to more subtle bugs, for example, suppose a deletion request is started, we check that there are no snapshot/restores taking place, and then proceed with deletion.  Subsequently, we issue another deletion request while the first deletion is taking place.  This can also lead to race conditions with deletion.  Furthermore, if both of these deletions are taking place, and then we initiate a snapshot or restore operation, we have no way of knowing a deletion is in process, so the snapshot/restore will commence.  The snapshot/restore will initially read the repository data, which it gets from the index generational file.  It is possible that the snapshot/restore reads the current generation value (lets call it `N`), but before reading the index file `index-N`, both of the deletes complete, which create `index-{N+1}` and `index-{N+2}`.  We only keep around the current index file and the one before it, so then `index-N` will have been deleted.  Now, when the snapshot/restore operation resumes and tries to read `index-N`, it will fail as the file is not there.

A solution would be to maintain deletions in progress in the cluster state along with snapshots in progress and restores in progress.  By using the cluster state as a point of synchronization, we can execute deletes more safely in relation to other potential operations on the repository at the same time.

### PR DESCRIPTION
**Pull request by abeyad**
Before, snapshot/restore would synchronize all operations on the cluster
state except for deleting snapshots.  This meant that only one
snapshot/restore operation would be allowed in the cluster at any given
time, except for deletions - there could be two or more snapshot
deletions running at the same time, or a deletion could be running,
unbeknowest to the rest of the cluster, and thus a snapshot or restore
would be allowed at the same time as the snapshot deletion was still in
progress.  This could cause any number of synchronization issues,
including the situation where a snapshot that was deleted could reappear
in the index-N file, even though its data was no longer present in the
repository.

This commit introduces a new custom type to the cluster state to
represent deletions in progress.  Now, another deletion cannot start if
a deletion is currently in progress.  Similarily, a snapshot or restore
cannot be started if a deletion is currently in progress.  In each case,
if attempting to run another snapshot/restore operation while a deletion
is in progress, a ConcurrentSnapshotExecutionException will be thrown.
This is the same exception thrown if trying to snapshot while another
snapshot is in progress, or restore while a snapshot is in progress.

Closes #19957

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/cluster/ClusterState.java [hunk 1]
```diff
@@ -787,7 +797,21 @@ public void writeTo(StreamOutput out) throws IOException {
             nodes.writeTo(out);
             metaData.writeTo(out);
             blocks.writeTo(out);
-            customs.writeTo(out);
+            Diff<ImmutableOpenMap<String, Custom>> customsDiff = customs;
+            if (out.getVersion().before(SnapshotDeletionsInProgress.VERSION_INTRODUCED)) {
+                customsDiff = removeSnapshotDeletionsCustomDiff(customsDiff);
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/cluster/ClusterState.java]: I think this should be handled in a generic fashion on the custom's serialization level, but it might be better to do in a follow-up PR after I merge #22336 in.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -904,6 +941,9 @@ private void removeSnapshotFromClusterState(final Snapshot snapshot, final Snaps
     private void removeSnapshotFromClusterState(final Snapshot snapshot, final SnapshotInfo snapshotInfo, final Exception failure,
                                                 @Nullable ActionListener<SnapshotInfo> listener) {
         clusterService.submitStateUpdateTask("remove snapshot metadata", new ClusterStateUpdateTask() {
+
+            private long repositoryStateId = -1L;
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: What is this doing?

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 3]
```diff
@@ -1116,6 +1180,18 @@ public static boolean isRepositoryInUse(ClusterState clusterState, String reposi
                 }
             }
         }
+        SnapshotDeletionsInProgress deletionsInProgress = clusterState.custom(SnapshotDeletionsInProgress.TYPE);
+        if (deletionsInProgress != null && deletionsInProgress.hasDeletionsInProgress()) {
+            return true;
+        }
+        RestoreInProgress restoreInProgress = clusterState.custom(RestoreInProgress.TYPE);
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: We do this check in RestoreService.isRepositoryInUse. I am not quite sure what's the reason to repeat it here.

**Review by imotov — APPROVED** [review]
In general, LGTM. I left a couple of minor comments.

File: core/src/main/java/org/elasticsearch/cluster/ClusterState.java (hunk 1 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/cluster/ClusterState.java]: Sounds good, when #22336 is in, we can go over improvements to the custom diff logic here.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 2 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: good catch, remnants from something else I was trying, I just removed it.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 3 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: you are right, I didn't notice the call to both in `RepositoriesService#ensureRepositoryNotInUse()`.  removing this.

**Comment by abeyad** [comment]
thanks for the review @imotov

**Comment by abeyad** [comment]
retest this please

**Comment by abeyad** [comment]
5.x commit: 1a6c598e6492d42fc10bc6f4cab539d96db72ed3
