### PR TITLE
Fix unresponsive network simulation

### LINKED ISSUE #42244: [CI] ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability fails
`ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos-6/428/console

The reported error is:

```
org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT > testSeqNoCASLinearizability FAILED
    java.lang.RuntimeException: java.util.concurrent.TimeoutException
        at org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability(ConcurrentSeqNoVersioningIT.java:190)

        Caused by:
        java.util.concurrent.TimeoutException
            at java.base/java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:258)
            at java.base/java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:436)
            at org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability(ConcurrentSeqNoVersioningIT.java:174)

    java.lang.AssertionError: cluster failed to form after disruption was healed
```

I managed to reproduce this twice in a row on a CentOS 7 server using:

```
./gradlew :server:integTest --tests "org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability" \
  -Dtests.seed=E8175DCFB75B80B2 \
  -Dtests.security.manager=true \
  -Dtests.locale=vun-TZ \
  -Dtests.timezone=Asia/Kashgar \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

It seems to be seed-specific as this succeeded:

```
./gradlew :server:integTest --tests "org.elasticsearch.versioning.ConcurrentSeqNoVersioningIT.testSeqNoCASLinearizability"
```

### PR DESCRIPTION
**Pull request by henningandersen**
Unresponsive network simulation would throw away requests. However, then
we no longer have any guarantees that a transport action either succeeds
or fails, which could lead to hangs (example: unclosed IndexShard
permits).

This commit changes this behavior to close any connections affected by the
unresponsive network simulation when disruption is cleared.

Closes #42244

### CODE REVIEW

**Comment by henningandersen** [comment]
Unrelated build failure, reported here: #42664 

@elasticmachine run elasticsearch-ci/1

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java [hunk 1]
```diff
@@ -102,4 +112,56 @@ public void testNetworkPartitionRemovalRestoresConnections() throws Exception {
...
+        CountDownLatch latch = new CountDownLatch(100);
+        for (int i = 0; i < 100; ++i) {
+            TransportService transportService = internalCluster().getInstance(TransportService.class);
+            TransportService target = internalCluster().getInstance(TransportService.class);
+
+            transportService.sendRequest(target.getLocalNode(), ClusterHealthAction.NAME, new ClusterHealthRequest(),
+                new TransportResponseHandler<>() {
+                @Override
+                public void handleResponse(TransportResponse response) {
+                    latch.countDown();
```
Comment (DaveCTurner) [inline test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: I like to clarify that we're not double-counting anything when using a `CountDownLatch`. How about something like this for an `AtomicBoolean responded`:

```suggestion
                    assertTrue(responded.compareAndSet(false, true));
                    latch.countDown();
```

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java [hunk 2]
```diff
@@ -102,4 +112,56 @@ public void testNetworkPartitionRemovalRestoresConnections() throws Exception {
...
+                    return ClusterHealthResponse.readResponseFrom(in);
+                }
+            });
+        }
+
+        // give a bit of time to send something under disruption.
+        latch.await(500, TimeUnit.MILLISECONDS);
+        networkDisruption.stopDisrupting();
+
+        latch.await(30, TimeUnit.SECONDS);
```
Comment (DaveCTurner) [inline test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: I think we should assert that this doesn't time out:

```suggestion
        assertTrue("all requests completed", latch.await(30, TimeUnit.SECONDS));
```

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java [hunk 3]
```diff
@@ -102,4 +112,56 @@ public void testNetworkPartitionRemovalRestoresConnections() throws Exception {
...
+        assertEquals("All requests must respond", 0, latch.getCount());
```
Comment (DaveCTurner) [inline test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: ... and then we don't need this.
```suggestion
```

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java [hunk 4]
```diff
@@ -102,4 +112,56 @@ public void testNetworkPartitionRemovalRestoresConnections() throws Exception {
...
+
+                @Override
+                public TransportResponse read(StreamInput in) throws IOException {
+                    return ClusterHealthResponse.readResponseFrom(in);
+                }
+            });
+        }
+
+        // give a bit of time to send something under disruption.
+        latch.await(500, TimeUnit.MILLISECONDS);
```
Comment (DaveCTurner) [inline test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: Is there a way we could assert that this _does_ time out?

```suggestion
        assertFalse(latch.await(500, TimeUnit.MILLISECONDS));
```

However this won't work if none the messages we send are across disrupted links. Can we try and ensure that there is always at least one disrupted message?

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java [hunk 5]
```diff
@@ -102,4 +112,56 @@ public void testNetworkPartitionRemovalRestoresConnections() throws Exception {
...
+
+        NetworkDisruption networkDisruption = new NetworkDisruption(disruptedLinks, randomFrom(new NetworkDisruption.NetworkUnresponsive(),
+            new NetworkDisruption.NetworkDisconnect(), NetworkDisruption.NetworkDelay.random(random())));
+        internalCluster().setDisruptionScheme(networkDisruption);
+
+        networkDisruption.startDisrupting();
+
+        CountDownLatch latch = new CountDownLatch(100);
+        for (int i = 0; i < 100; ++i) {
+            TransportService transportService = internalCluster().getInstance(TransportService.class);
```
Comment (DaveCTurner) [inline test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: Suggest renaming this to `source` since there's another `TransportService` in play.

**Review by DaveCTurner — COMMENTED** [review]
Looks good, but I suggested a few minor things in the tests.

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java (hunk 2 above)
Comment (henningandersen) [reply test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: I did this the other way around to ensure that a failure will include the count. In case this ever fails, it might be interesting to know if it was 1 request remaining or 100?

Let me know if you would still like me to change it into your suggestion?

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java (hunk 3 above)
Comment (henningandersen) [reply test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: See above.

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java (hunk 1 above)
Comment (henningandersen) [reply test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: Fixed in 3a4da10ac241a395ded339244b16d079aa3abf70

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java (hunk 5 above)
Comment (henningandersen) [reply test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: Fixed in f15db38043eed14308e341ac4d3ee0c3b2a76b67

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java (hunk 4 above)
Comment (henningandersen) [reply test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: The `NetworkDisconnect` disruption type notifies of failures immediately. I would like to keep that disruption type included in the test. I ended up conditionally checking that we time out only when disruption type is not `NetworkDisconnect`, see: 779b98a2a1b7e88a22b50237db122ff59a8e1ff5.

It does kind of complicate the test somewhat and I am considering if it is better without it, WDYT?

**Comment by henningandersen** [comment]
Thanks for the review, @DaveCTurner , this is ready for another round.

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java (hunk 2 above)
Comment (DaveCTurner) [reply test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: Ok, that makes sense.

File: test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java (hunk 4 above)
Comment (DaveCTurner) [reply test/framework/src/test/java/org/elasticsearch/test/disruption/NetworkDisruptionIT.java]: I see what you mean, but I do prefer it as it is now (779b98a) just in case we ever accidentally make this test vacuous.

**Review by DaveCTurner — APPROVED** [review]
LGTM
