### PR TITLE
SQL: fix NULLS FIRST/LAST for aggregations

### LINKED ISSUE #34550: SQL: Add support for NULL ordering (when grouping)
Currently, due to restrictions in the query DSL (#34221), `null` cannot be placed first or last regardless of the order as they obey the order (first if ASC, last if DESC).
This option is supported when searching without grouping though.

Once the fix lands in ES, SQL should follow suit.

### PR DESCRIPTION
**Pull request by Luegg**
Fixes https://github.com/elastic/elasticsearch/issues/34550

Uses the "missing_order" attribute introduced in https://github.com/elastic/elasticsearch/pull/76740 to address the ignored `NULLS FIRST/LAST` clauses in queries with group by.

This PR does only considers `NULLS FIRST/LAST` clauses and does not change the behavior of nulls ordering if `NULLS FIRST/LAST` is omitted. Hence, all queries without `NULLS FIRST/LAST` should still behave as before.

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java [hunk 1]
```diff
@@ -156,7 +156,7 @@ public static SearchRequest prepareRequest(Client client, SearchSourceBuilder so
             String... indices) {
         source.timeout(timeout);
 
-        SearchRequest searchRequest = new SearchRequest(SWITCH_TO_FIELDS_API_VERSION);
+        SearchRequest searchRequest = new SearchRequest(MISSING_ORDER_IN_COMPOSITE_AGGS_VERSION);
```
Comment (Luegg) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java:159]: Not sure wether this is necessary, in theory there is only a few queries that need `missing_order`, most queries would still succeed on a node without this capability.

Comment (astefan) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java:159]: I think you need to test this behavior in `SqlSearchIT`.
Why would a query succeed on a node without [this feature](https://github.com/elastic/elasticsearch/pull/76740)? Wouldn't there be an error about an unrecognized `missing_order` parameter?

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Order.java [hunk 2]
```diff
@@ -23,7 +23,11 @@
     }
 
     public enum NullsPosition {
-        FIRST, LAST;
+        FIRST, LAST,
+        /**
+         * Nulls position has not been specified by the user and an appropriate default will be used.
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Order.java:28]: What is the new/appropriate vs the previous default?

**Review by costin — COMMENTED** [review]
LGTM however I'd like a bit more testing on the bwc side.
Can you clarify, if no order is being specified what is going to be the behavior and how that differs from specifying the order?

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Order.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Order.java:28]: I've extended the comment and point to https://github.com/elastic/elasticsearch/issues/77068 now. The default is not particularly meaningful but it stays compatible with the legacy behavior.

**Comment by Luegg** [comment]
@astefan @costin I've added some BWC tests and also tested it on the 7.x branch already. Please have another look.

**Review by astefan — APPROVED** [review]
LGTM.
It bothers me a bit that we don't choose a default behavior in case the user doesn't specify a null ordering (nulls first/last), but also I'm ok with the chosen behavior as well.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Order.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Order.java:28]: Thanks. Let's put this on the discussion list for 8.x and whether it is worth reviewing the default so it's consistent across different contexts with minimal (if any) performance penalty.

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+        StringBuilder bulk = new StringBuilder();
+        for (String doc : Arrays.asList("{\"int\":1,\"kw\":\"foo\"}", "{\"int\":2,\"kw\":\"bar\"}", "{\"kw\":\"bar\"}")) {
+            bulk.append("{\"index\":{}\n").append(doc).append("\n");
+        }
+        indexDocs.setJsonEntity(bulk.toString());
+        client().performRequest(indexDocs);
+
+        Request query = new Request("GET", "_sql");
+        query.setJsonEntity("{\"query\":\"SELECT int FROM test GROUP BY 1 ORDER BY 1 NULLS LAST\"}");
+        Response queryResponse = queryClient.performRequest(query);
```
Comment (costin) [inline x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java:117]: It would be nice to externalize these strings some how; once upgrading to Java11 declaring these strings should be less messy.

**Review by costin — APPROVED** [review]
LGTM. Glad to see this finally resolved.

**Comment by Luegg** [comment]
> LGTM.
> It bothers me a bit that we don't choose a default behavior in case the user doesn't specify a null ordering (nulls first/last), but also I'm ok with the chosen behavior as well.

Same for me, but we can address it in subsequent PRs. I've also opened https://github.com/elastic/elasticsearch/issues/77068 to discuss and track the inconsistencies of null orders.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/execution/search/QlSourceBuilder.java [hunk 4]
```diff
@@ -23,6 +23,7 @@
  */
 public class QlSourceBuilder {
     public static final Version SWITCH_TO_FIELDS_API_VERSION = Version.V_7_10_0;
+    public static final Version MISSING_ORDER_IN_COMPOSITE_AGGS_VERSION = Version.V_7_16_0;
```
Comment (bpintea) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/execution/search/QlSourceBuilder.java:26]: This name makes sense now in this PR, but I'd prolly find it a bit confusing later. Imo it'd help a comment or something like `INTRODUCING_` prefix. Just a minor suggestion.

**Review by bpintea — APPROVED** [review]
Lgtm.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/execution/search/QlSourceBuilder.java (hunk 4 above)
Comment (Luegg) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/execution/search/QlSourceBuilder.java:26]: makes sense, I'll add the `INTRODUCING_` prefix 👍
