### PR TITLE
Fix roles parsing in client nodes sniffer

### LINKED ISSUE #52864: ElasticsearchNodesSniffer complains about  "unknown role [ml]"
We have an API server using version 7.5.1 of the elasticsearch-rest-high-level-client and elasticsearch-rest-client-sniffer Java libraries, which matches the version of ES used on our cluster. It is working fine, but our application log ends up filled with messages saying
`WARN o.e.c.s.ElasticsearchNodesSniffer - unknown role [ml] on node <name>`

I asked about this on the official Elastic forum and was told by David Turner
(an Elastic Team Member) that this behavior is a bug and I should file it here. Specifically, he says "The ElasticsearchNodesSniffer only knows about the three core roles... IOW it was not updated when node roles became pluggable", and points to the code here:

https://github.com/elastic/elasticsearch/blob/bbbdf949a9d63dbc795ce8dd7dbd529d5f40b98b/client/sniffer/src/main/java/org/elasticsearch/client/sniff/ElasticsearchNodesSniffer.java#L209-L222

### PR DESCRIPTION
**Pull request by jasontedor**
We mades roles pluggable, but never updated the client to account for this. This means that when speaking to a modern cluster, application logs are spammed with warning messages around unrecognized roles. This commit addresses this by accounting for the fact that roles can extend beyond master/data/ingest now.

Closes #52864

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine update branch

File: client/rest/src/main/java/org/elasticsearch/client/Node.java [hunk 1]
```diff
@@ -175,42 +176,35 @@ public int hashCode() {
...
+        public Roles(final Set<String> roles) {
+            this.roles = new TreeSet<>(roles);
         }
 
         /**
          * Teturns whether or not the node <strong>could</strong> be elected master.
          */
         public boolean isMasterEligible() {
-            return masterEligible;
+            return roles.contains("master");
```
Comment (dakrone) [inline client/rest/src/main/java/org/elasticsearch/client/Node.java]: Out of curiosity, should we make these constants since they're hardcoded as strings all over the place? (in separate work, not this PR)

**Review by dakrone — APPROVED** [review]
LGTM, left one question regarding optional future work, but nothing this PR depends on.
