### PR TITLE
Fix KQL case-sensitivity for keyword fields in ES|QL

### LINKED ISSUE #135772: [ES|QL] KQL defaults to case-insensitive matching on keyword fields (inconsistent with docs & Kibana behavior)
### Elasticsearch Version

>=8.17

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

There is an inconsistency between how KQL queries behave in Kibana vs. ES|QL/Elasticsearch’s implementation.

In Kibana, KQL queries on keyword fields are case-sensitive (as per documentation).
In Elasticsearch KQL implementation (used by the ES|QL kql() function), the default is incorrectly set to case-insensitive.

This discrepancy is confusing for users and inconsistent with the [documented](https://www.elastic.co/docs/explore-analyze/query-filter/languages/kql#_filter_for_documents_that_match_a_value) behavior of KQL:

> When querying keyword, numeric, date, or boolean fields, the value must be an exact match, including punctuation and case. However, when querying text fields, Elasticsearch analyzes the value provided The KQL query implementation in Elasticsearch has the wrong default making it case insensitive

### Steps to Reproduce

Put some docs

```
PUT test/_doc/1
{
  "user": "Student01"
}

PUT test/_doc/2
{
  "user": "student01"
}
```

**Run in Kibana Discover:**

```
user: "student01"
```

→ Returns only the lowercase match.

**Run in ES|QL:**

```
FROM test | WHERE kql(user: "student01")
```

→ Returns both "student01" and "Student01".

**Expected Behavior:**

KQL should respect its documented semantics: keyword fields require exact match (case-sensitive).

**Actual Behavior:**

ES|QL’s KQL function is case-insensitive on keyword fields.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by afoucret**
This pull request addresses an inconsistency in the KQL implementation used by ES|QL, where queries on keyword fields were incorrectly case-insensitive by default. This behavior contradicted the KQL documentation and the behavior of KQL in Kibana, which both specify exact, case-sensitive matching for keyword fields.

The change adjusts the KQL parsing context to ensure that matching on keyword fields is case-sensitive, aligning the ES|QL implementation with the expected standard.

Fixes #135772

### CODE REVIEW

File: x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/query/KqlQueryBuilderTests.java [hunk 1]
```diff
@@ -170,7 +170,7 @@ public void testCaseInsensitiveWildcardQuery() throws IOException {
         for (boolean caseInsensitive : List.of(true, false)) {
             KqlQueryBuilder kqlQuery = new KqlQueryBuilder(KEYWORD_FIELD_NAME + ": foo*");
             // Check case case_insensitive is true by default
```
Comment (carlosdelest) [inline x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/query/KqlQueryBuilderTests.java:172]:
```suggestion
            // Check case case_insensitive is false by default
```

File: x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/query/KqlQueryBuilderTests.java [hunk 2]
```diff
@@ -190,7 +190,7 @@ public void testCaseInsensitiveTermQuery() throws IOException {
         for (boolean caseInsensitive : List.of(true, false)) {
             KqlQueryBuilder kqlQuery = new KqlQueryBuilder(KEYWORD_FIELD_NAME + ": foo");
             // Check case case_insensitive is true by default
```
Comment (carlosdelest) [inline x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/query/KqlQueryBuilderTests.java:192]:
```suggestion
            // Check case case_insensitive is false by default
```

File: x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/query/KqlQueryBuilderTests.java (hunk 1 above)
Comment (carlosdelest) [inline x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/query/KqlQueryBuilderTests.java:172]:
```suggestion
            // Check case case_insensitive is false by default
```

File: x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/query/KqlQueryBuilderTests.java (hunk 2 above)
Comment (carlosdelest) [inline x-pack/plugin/kql/src/test/java/org/elasticsearch/xpack/kql/query/KqlQueryBuilderTests.java:192]:
```suggestion
            // Check case case_insensitive is false by default
```

**Review by carlosdelest — APPROVED** [review]
LGTM!

**Comment by swg0101** [comment]
Despite this being an inconsistent behavior, we actually have been exploiting this behavior in ES|QL to do case-insensitive searches on keywords where we ordinarily would have to resort to other hacks, like doing a regex DSL with case-insensitive set to true, or doing a to_lower()/upper() in ES|QL. That being said, those functions are much slower than the KQL() function.

It may be wise for there to be a toggle on this so users can choose the behavior they want to see. There has also been a long standing ticket asking for a similar behavior, like this: https://github.com/elastic/kibana/issues/55378

**Comment by afoucret** [comment]
@swg0101 got your point. 

I think:
- the default behavior should be consistent
- we should expose the feature as an option of the KQL function

I opened an issue that describe exactly this: #135823.

**Comment by swg0101** [comment]
That sounds great. Perhaps the result can be slightly more user-friendly, especially if there are no other variables that would need to be passed. Perhaps naming the function KQLi/kqli with and passing the `case_insensitive: true` parameter would be easier?

Just like using the DSL like this would be cumbersome:
```
{
  "kql": {
    "query": "user.name: student01",
    "case_insensitive": true
  }
}
```

Perhaps adding a toggle in Classic Discover would make it more friendly, although it got closed as not planned under: https://github.com/elastic/kibana/issues/55378. Also, out of scope of this ticket... :)

**Comment by afoucret** [comment]
@swg0101 There are probably some improvements that can be done in the UX but I am very reluctant to introduce new functions for things that can accessible through an optional parameter.

My plan for KQL function is to expose the `case_insensitive` but also to introduce other params that are supported by the query DSL:
- `default field`: list of field to use when no field is specified
- `timezone`: the timezone to use for date / time queries

Last but mot least, our plan with the KQL query is to allow users to migrate to ES|QL more easily. We do not want to add new features to the KQL language and would prefer that people rewrite their queries using native ES|QL syntax / functions. 
If there are gaps, it would be better that we fix it in ES|QL directly instead of calling KQL to the rescue and call a query language inside a query language.  My gut feeling is that we won't add new features to KQL once the above named params are implemented.

**Comment by swg0101** [comment]
That makes sense. I am guessing that as long as autocomplete works well, then it probably wouldn't be that much of a problem.
To your point about migrating from KQL --> ES|QL, I think the top few things that drag me back into KQL are as follows:

1. Native ES|QL is still relatively weak when dealing with array values. For example, seeing if a particular field, like `related.ip` contains a value, regardless if it's in a scalar form or a multivalue (array) form. KQL couldn't care less about what type the field is in, and works like a "generic contains" match, versus ES|QL being much more literal in its matching (e.g., `==` vs `:` in KQL). This specific limitation also makes matching IPs difficult, such as something like `related.ip: 192.168.0.0/16`, where `related.ip` could contain either one IP or multiple IPs, depending on the document(s) being searched.

2. The absolute imposition of a strict limit with no pagination support, as described in https://github.com/elastic/elasticsearch/issues/100000.

3. I am guessing this very discussion about case insensitivity would be one as well, as `==` is strictly case sensitive, and there is no option to change this on the fly without falling back to `KQL()`.
