### PR TITLE
Second parsing pass tracks array scopes properly

### LINKED ISSUE #114563: [CI] LogsDbVersusLogsDbReindexedIntoStandardModeChallengeRestIT testTermsQuery failing
**Build Scans:**
- [elasticsearch-intake #10996 / part1](https://gradle-enterprise.elastic.co/s/4m27fwuhdno6c)
- [elasticsearch-pull-request #35110 / part-1](https://gradle-enterprise.elastic.co/s/43wqaw26fgyji)
- [elasticsearch-periodic-platform-support #4312 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/ojwhtg5pab74c)
- [elasticsearch-periodic #4338 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/sx3pekvazozx2)
- [elasticsearch-periodic-platform-support #4312 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/hyyl6emmqprii)
- [elasticsearch-pull-request #35058 / part-1](https://gradle-enterprise.elastic.co/s/47jeizdnao2ys)
- [elasticsearch-pull-request #35047 / part-1](https://gradle-enterprise.elastic.co/s/d6ssgn3v63zfc)
- [elasticsearch-pull-request #35042 / part-1](https://gradle-enterprise.elastic.co/s/wxoz5g6qvam3w)
- [elasticsearch-pull-request #35032 / part-1](https://gradle-enterprise.elastic.co/s/oj3vccvf2vdna)
- [elasticsearch-intake #10798 / part1](https://gradle-enterprise.elastic.co/s/rxlrre43mlifc)

**Reproduction Line:**
```
./gradlew ":modules:data-streams:javaRestTest" --tests "org.elasticsearch.datastreams.logsdb.qa.LogsDbVersusLogsDbReindexedIntoStandardModeChallengeRestIT.testTermsQuery" -Dtests.seed=D6A971D4983BFEDE -Dtests.locale=nds-DE -Dtests.timezone=US/Pacific -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testTermsQuery'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.datastreams.logsdb.qa.LogsDbVersusLogsDbReindexedIntoStandardModeChallengeRestIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:42139], URI [/_reindex?refresh=true], status line [HTTP/1.1 400 Bad Request]
{"took":2164,"timed_out":false,"total":180,"updated":0,"created":179,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[{"index":".ds-standard-apache-reindexed-contender-2024.10.11-000001","id":"91","cause":{"type":"illegal_argument_exception","reason":"mapper [fueh.ZX.A] cannot be changed from type [long] to [float]"},"status":400,"failure_store":"not_enabled"}]}
```

**Issue Reasons:**
- [main] 23 failures in test testTermsQuery (2.4% fail rate in 972 executions)
- [main] 3 failures in step part1 (2.1% fail rate in 146 executions)
- [main] 8 failures in step part-1 (1.7% fail rate in 461 executions)
- [main] 2 failures in step rhel-7_platform-support-unix (16.7% fail rate in 12 executions)
- [main] 2 failures in step oraclelinux-7_platform-support-unix (15.4% fail rate in 13 executions)
- [main] 3 failures in pipeline elasticsearch-intake (2.1% fail rate in 146 executions)
- [main] 4 failures in pipeline elasticsearch-periodic-platform-support (28.6% fail rate in 14 executions)
- [main] 8 failures in pipeline elasticsearch-pull-request (1.8% fail rate in 455 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by kkrik-es**
In the second doc parsing pass, the end of an array scope is not properly tracked. If there's a field of interest within an array and a field with the same name outside the array in the parent object, the second pass may erroneously pick the field outside the array as well, due to the current path not getting updated to remove the array suffix.

To fix this, we track the type of each scope and remove the path component for it when the correspond scope end type is parsed (END_OBJECT for objects, END_ARRAY for arrays).

Fixes #114563

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 1]
```diff
@@ -218,11 +219,16 @@ private static List<IgnoredSourceFieldMapper.NameValue> parseDocForMissingValues
...
                     }
                     fieldName = null;
                 } else if (currentToken == XContentParser.Token.END_OBJECT || currentToken == XContentParser.Token.END_ARRAY) {
-                    if (currentToken == XContentParser.Token.END_OBJECT && path.isEmpty() == false) {
+                    // Remove the path, if the scope type matches the one when the path was added.
+                    if (isObjectInPath.isEmpty() == false
+                        && (isObjectInPath.getLast() && currentToken == XContentParser.Token.END_OBJECT
+                            || isObjectInPath.getLast() == false && currentToken == XContentParser.Token.END_ARRAY)) {
                         path.removeLast();
+                        isObjectInPath.removeLast();
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:231]: Double checking, so in case of array and `isObjectInPath.getLast() == false` then we remove and if in case of object and `isObjectInPath.getLast() == true` we remove as well. So we should never end up in case we forget to remove an element?

**Review by martijnvg — APPROVED** [review]
LGTM. I left 2 questions.

**Review by lkts — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 1 above)
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:231]: Correct, the idea is that, if the name is an array of objects, we won't remove it when we remove an object.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 2]
```diff
@@ -237,7 +243,6 @@ private static List<IgnoredSourceFieldMapper.NameValue> parseDocForMissingValues
             if (leaf != null) {
                 parser.nextToken();  // Advance the parser to the value to be read.
                 result.add(leaf.cloneWithValue(context.encodeFlattenedToken()));
-                parser.nextToken();  // Skip the token ending the value.
```
[the remark this answers is not in the document]
Comment (kkrik-es) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:240]: This was added before to avoid removing paths for simple arrays of leaf values. It was the wrong fix, and not needed any more.

**Comment by kkrik-es** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/114646)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
