### PR TITLE
SQL: Disallow queries with inner LIMIT that cannot be executed in ES

### LINKED ISSUE #75830: SQL: LIMIT in subquery with outer WHERE or ORDER BY gives wrong result
The query `select * from (select * from test_emp order by emp_no limit 3) s where gender = 'F'` yields three results:

```
       birth_date       |    emp_no     |  first_name   |    gender     |       hire_date        |   languages   |   last_name   |      name       |    salary
------------------------+---------------+---------------+---------------+------------------------+---------------+---------------+-----------------+---------------
1964-06-02T00:00:00.000Z|10002          |Bezalel        |F              |1985-11-21T00:00:00.000Z|5              |Simmel         |Bezalel Simmel   |56371
1953-04-20T00:00:00.000Z|10006          |Anneke         |F              |1989-06-02T00:00:00.000Z|3              |Preusig        |Anneke Preusig   |60335
1957-05-23T00:00:00.000Z|10007          |Tzvetan        |F              |1989-02-10T00:00:00.000Z|4              |Zielinski      |Tzvetan Zielinski|74572
```

Expected behavior is that LIMIT is applied before WHERE and the result only contains the records with `gender = 'F'` out of the first three rows of the table (with the test dataset only one record):

```
       birth_date       |    emp_no     |  first_name   |    gender     |       hire_date        |   languages   |   last_name   |      name       |    salary
------------------------+---------------+---------------+---------------+------------------------+---------------+---------------+-----------------+---------------
1964-06-02T00:00:00.000Z|10002          |Bezalel        |F              |1985-11-21T00:00:00.000Z|5              |Simmel         |Bezalel Simmel   |56371
```

The problem is that we assume that the LIMIT and FILTER operations commute which is not the case.

The same issue occurs with ORDER BY: `select * from (select * from test_emp limit 3) s order by gender` yields

```
       birth_date       |    emp_no     |  first_name   |    gender     |       hire_date        |   languages   |   last_name   |      name       |    salary
------------------------+---------------+---------------+---------------+------------------------+---------------+---------------+-----------------+---------------
1964-06-02T00:00:00.000Z|10002          |Bezalel        |F              |1985-11-21T00:00:00.000Z|5              |Simmel         |Bezalel Simmel   |56371
1953-04-20T00:00:00.000Z|10006          |Anneke         |F              |1989-06-02T00:00:00.000Z|3              |Preusig        |Anneke Preusig   |60335
1957-05-23T00:00:00.000Z|10007          |Tzvetan        |F              |1989-02-10T00:00:00.000Z|4              |Zielinski      |Tzvetan Zielinski|74572
```

Thus, the ORDER BY is applied first and then the LIMIT, instead of the other way around. Expected result is:

```
       birth_date       |    emp_no     |  first_name   |    gender     |       hire_date        |   languages   |   last_name   |     name      |    salary
------------------------+---------------+---------------+---------------+------------------------+---------------+---------------+---------------+---------------
1964-06-02T00:00:00.000Z|10002          |Bezalel        |F              |1985-11-21T00:00:00.000Z|5              |Simmel         |Bezalel Simmel |56371
1953-09-02T00:00:00.000Z|10001          |Georgi         |M              |1986-06-26T00:00:00.000Z|2              |Facello        |Georgi Facello |57305
1959-12-03T00:00:00.000Z|10003          |Parto          |M              |1986-08-28T00:00:00.000Z|4              |Bamford        |Parto Bamford  |61805
```

### PR DESCRIPTION
**Pull request by Luegg**
Resolves https://github.com/elastic/elasticsearch/issues/75830

This PR only disallows subqueries with `LIMIT` if they cannot be translated into an semantically equivalent ES query. Thus, queries like `SELECT languages FROM (SELECT * FROM test_emp LIMIT 10)` that can be flattened correctly are still valid. Compared to disallowing all subqueries with `LIMIT`, this will only break queries that might return wrong results.

Additionally, this change also uncovered an issue with `TOP`. Because `TOP` is part of the `querySpecification` syntax, the `LogicalPlanBuilder` creates it as a child of `OrderBy` nodes. Thus, the query `SELECT TOP 10 * FROM test_emp ORDER BY salary` used to produce the logical plan
```
\ OrderBy
 \ Limit
  \ EsRelation[test_emp]
```
the semnatically correct plan would be 
```
\ Limit
 \ OrderBy
  \ EsRelation[test_emp]
```
This also had the effect that some queries with both `TOP` and `LIMIT` were not rejected by the parser.

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/LogicalPlanBuilder.java [hunk 1]
```diff
@@ -119,6 +124,21 @@ public LogicalPlan visitQueryNoWith(QueryNoWithContext ctx) {
         return plan;
     }
 
+    private LogicalPlan pullUpTopClauseFromQuerySpecification(LogicalPlan plan) {
+        if (plan instanceof UnaryPlan) {
+            UnaryPlan unary = (UnaryPlan) plan;
+            if (unary.child() instanceof Limit) {
+                Limit limit = (Limit) unary.child();
+
+                return limit.replaceChildrenSameSize(Arrays.asList(
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/LogicalPlanBuilder.java:133]: nit: `Collections#singletonList()` might work too.

File: x-pack/plugin/sql/qa/server/src/main/resources/select.sql-spec [hunk 2]
```diff
@@ -153,14 +153,10 @@ selectOrderByOrderByOrderByLimit
 SELECT * FROM (SELECT * FROM (SELECT * FROM test_emp ORDER BY emp_no DESC) ORDER BY emp_no ASC) ORDER BY emp_no DESC LIMIT 5;
 selectOrderByOrderByOrderByLimitLimit
 SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM test_emp ORDER BY emp_no DESC) ORDER BY emp_no ASC) ORDER BY emp_no DESC LIMIT 12) LIMIT 6;
-selectOrderByLimitSameOrderBy
-SELECT * FROM (SELECT * FROM (SELECT * FROM test_emp LIMIT 10) ORDER BY emp_no) ORDER BY emp_no LIMIT 5;
```
Comment (bpintea) [inline x-pack/plugin/sql/qa/server/src/main/resources/select.sql-spec:157]: Wondering if this (type of) sequence of sub-selects couldn't be flattened safely. The outer ones don't change the ordering and out of multiple limitations, the smallest value could be determined (there's already code doing this comparison, IIRC?).

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/Verifier.java [hunk 3]
```diff
@@ -59,20 +63,19 @@
...
     private static void checkForNonCollapsableSubselects(PhysicalPlan plan, List<Failure> failures) {
-        Holder<Boolean> hasLimit = new Holder<>(Boolean.FALSE);
-        Holder<List<Order>> orderBy = new Holder<>();
-        plan.forEachUp(p -> {
-            if (hasLimit.get() == false && p instanceof LimitExec) {
-                hasLimit.set(Boolean.TRUE);
-                return;
-            }
-            if (p instanceof OrderExec) {
-                if (hasLimit.get() && orderBy.get() != null && ((OrderExec) p).order().equals(orderBy.get()) == false) {
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/Verifier.java:70]: Related to the removed query comment: can't we keep this "pass-through" check? I.e. chaining multiple orderings if they aren't combined with other clauses?

File: x-pack/plugin/sql/qa/server/src/main/resources/select.sql-spec (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/resources/select.sql-spec:157]: I think this particular query cannot be flattened as well because it also first limits and then sorts.

But I think you're right that there is a special case where the outer ORDER BY is redundant and could be eliminated as in `SELECT * FROM (SELECT * FROM test_emp ORDER BY emp_no LIMIT 10) ORDER BY emp_no`. This query should be equivalent to `SELECT * FROM (SELECT * FROM test_emp ORDER BY emp_no LIMIT 10)` which can safely be flattened.

I think the same principle applies for redundant filters as well: `SELECT * FROM (SELECT * FROM test_emp WHERE emp_no > 10 LIMIT 10) WHERE emp_no > 10`. And maybe also `GROUP BY`s.

I have the feeling this would best be implemented as an additional optimization though. A rule that eliminates redundant WHERE and ORDER BY.

Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/resources/select.sql-spec:157]: I just noticed that in this particular case, the query could even be flattened because the order is not specified in the inner query. This would be a somewhat surprising behavior but probably aligned with SQL's "unordered bag of tuples" semantics.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/Verifier.java [hunk 4]
```diff
@@ -59,20 +63,19 @@
...
-                    failures.add(fail(p, "Cannot use ORDER BY on top of a subquery with ORDER BY and LIMIT"));
-                } else {
-                    orderBy.set(((OrderExec) p).order());
-                }
+        // use a comparator to ensure deterministic order of the error messages
+        Set<LimitExec> limits = new TreeSet<>(Comparator.comparing(l -> l.source().text()));
+
+        plan.forEachDown(p -> {
+            if (p instanceof OrderExec || p instanceof FilterExec || p instanceof PivotExec || p instanceof AggregateExec) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/Verifier.java:70]: No need to do double iteration - the main forEach already traverses the tree so for each matching node doing another p.forEachDown is unnecessary.
Further more I don't think it's useful to the user to see all the instances where the same type of error occurs since a query with ORDER BY and a WHERE clause will report the error twice (once per entity).

I favor the initial approach since it's O(n) - traverse the tree once. (this could be optimized by ending the traversal on the first error however it's a rare enough case that we can ignore it).

**Review by costin — COMMENTED** [review]
Left some comments on improving the complexity of the validation rule and the top parser.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/Verifier.java (hunk 4 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/Verifier.java:70]: 👍 for the single iteration.

Also reporting only one error shouldn't make too much of a difference but I was more thinking about the cases where there is more than one offending `Limit` as in `SELECT * FROM (SELECT * FROM (SELECT * FROM test_emp LIMIT 10) LIMIT 20) WHERE languages > 5`. Since this seems to be a rather far-fetched case, the simpler one-error implementation should be fine.

**Comment by Luegg** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by Luegg** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by Luegg** [comment]
@costin and @bpintea I've addressed your comments and had a look at what Bogdan mentioned about queries with redundant sort orders (`SELECT * FROM (SELECT * FROM test_emp ORDER BY emp_no LIMIT 10) ORDER BY emp_no`). In theory, we could allow such queries but I'm not sure it's worth it.

The last commit is an attempt to allow these queries and also to address https://github.com/elastic/elasticsearch/issues/76013 . Basically, it introduces a `PushDownAndCombineOrderBy` that folds multiple order bys if possible. The same logic could probably also be implemented in the `QueryFolder` but to me it looked more like an optimization.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 5]
```diff
@@ -165,6 +167,9 @@ public LogicalPlan optimize(LogicalPlan verified) {
                 new PushDownAndCombineFilters()
         );
 
+        Batch pushDownOrderBy = new Batch("Push Down Order By",
+            new PushDownAndCombineOrderBy());
```
Comment (Luegg) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:171]: Needs to run isolated from `PushDownAndCombineFilters` in order to avoid interfering push downs.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java [hunk 6]
```diff
@@ -701,6 +701,10 @@ protected PhysicalPlan rule(OrderExec plan) {
                 EsQueryExec exec = (EsQueryExec) plan.child();
                 QueryContainer qContainer = exec.queryContainer();
 
+                if (qContainer.sort().isEmpty() == false) {
+                    throw new SqlIllegalArgumentException("QueryContainer already defines sort order");
```
Comment (Luegg) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java:705]: I think we should be defensive here because the naive approach to just prepend additional sort orders leads to https://github.com/elastic/elasticsearch/issues/76013 .

Alternatively, `FoldOrderBy` (and `Verifier`) could take over the responsibility to merge `OrderBy`s from `PushDownAndCombineOrderBy`.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java [hunk 7]
```diff
@@ -1255,6 +1260,58 @@ private boolean foldable(Expression e) {
...
+                    if (combinedOrder.equals(innerOrderBy.order())) {
+                        return child.replaceChildrenSameSize(Collections.singletonList(innerOrderBy));
+                    }
+                }
+            }
+
+            return plan;
+        }
+
+        private List<Order> combineOrders(List<Order> parentOrders, List<Order> childOrders) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java:1302]: It's not clear to me how this method combines orders?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/LogicalPlanBuilder.java [hunk 8]
```diff
@@ -102,10 +101,15 @@ public LogicalPlan visitQueryNoWith(QueryNoWithContext ctx) {
...
             List<OrderByContext> orders = ctx.orderBy();
             OrderByContext endContext = orders.get(orders.size() - 1);
-            plan = new OrderBy(source(ctx.ORDER(), endContext), plan, visitList(ctx.orderBy(), Order.class));
-
-            // Limit from TOP clauses must be the parent of the OrderBy clause
-            plan = pullUpTopClauseFromQuerySpecification(plan);
+            Source source = source(ctx.ORDER(), endContext);
+            List<Order> order = visitList(ctx.orderBy(), Order.class);
+
+            if (plan instanceof Limit) {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/parser/LogicalPlanBuilder.java:107]: 👍

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java (hunk 6 above)
Comment (costin) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java:705]: > Alternatively, FoldOrderBy (and Verifier) could take over the responsibility to merge OrderBys from PushDownAndCombineOrderBy.

I like this better.

**Review by costin — APPROVED** [review]
> The last commit is an attempt to allow these queries and also to address #76013 .

Please address that through a different PR (and +1 at enhancing FoldOrderBy instead of a separate rule) to keep things clean.
Otherwise LGTM.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java (hunk 5 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java]: I think the optimizer would never converge to a stable plan in some cases as `OrderBy` and `Filter` would alternately be pushed down.

**Comment by Luegg** [comment]
I've reverted the last commit and will try to address https://github.com/elastic/elasticsearch/issues/76013 in a separate PR. This means that we will have a temporary regression as will no longer support queries with redundant sorts (e.g. `SELECT * FROM (SELECT * FROM test_emp ORDER BY emp_no LIMIT 10) ORDER BY emp_no`). Since it seems to be quite a special case, I would say that's justifiable.
