### PR TITLE
Fixes snapshot deletion handling on in-progress snapshot failure

### LINKED ISSUE #23663: SharedClusterSnapshotRestoreIT times out
See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/2158

Reproduction line (which fails to reproduce the issue):
```
gradle :core:integTest -Dtests.seed=1DA1BF57E52F287A -Dtests.class=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=UTC
```

### PR DESCRIPTION
**Pull request by abeyad**
This commit fixes an issue manifested in the
SharedClusterSnapshotRestoreIT#testGetSnapshotsRequest where a delete
request on a snapshot encounters an in-progress snapshot, so it first
tries to abort the snapshot.  During the aborting process, an exception
is thrown which is handled by the snapshot listener's onSnapshotFailure
method.  This method retries the delete snapshot request, only to
encounter that the snapshot is missing, throwing an exception.  It is
possible that the snapshot failure resulted in the snapshot never having
been written to the repository, and hence, there is nothing to delete.
This commit handles the SnapshotMissingException by logging it and
notifying the listener of the missing snapshot.

Closes #23663

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -1150,11 +1150,24 @@ public void onSnapshotCompletion(Snapshot completedSnapshot, SnapshotInfo snapsh
...
+                                        deleteSnapshot(failedSnapshot.getRepository(),
+                                                       failedSnapshot.getSnapshotId().getName(),
+                                                       listener,
+                                                       true);
+                                    } catch (SnapshotMissingException smex) {
+                                        logger.info((Supplier<?>) () -> new ParameterizedMessage(
+                                            "Tried deleting in-progress snapshot [{}], but it " +
+                                            "could not be found after failing to abort.",
+                                            smex.getSnapshotName()), e);
+                                        listener.onFailure(new SnapshotException(snapshot,
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Maybe pass `smex` as the cause for this one?

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 2]
```diff
@@ -1150,11 +1150,24 @@ public void onSnapshotCompletion(Snapshot completedSnapshot, SnapshotInfo snapsh
...
-                                threadPool.executor(ThreadPool.Names.SNAPSHOT).execute(() ->
-                                    deleteSnapshot(failedSnapshot.getRepository(), failedSnapshot.getSnapshotId().getName(), listener, true)
-                                );
+                                threadPool.executor(ThreadPool.Names.SNAPSHOT).execute(() -> {
+                                    try {
+                                        deleteSnapshot(failedSnapshot.getRepository(),
+                                                       failedSnapshot.getSnapshotId().getName(),
+                                                       listener,
+                                                       true);
+                                    } catch (SnapshotMissingException smex) {
```
Comment (imotov) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Should we catch other exceptions here?

**Review by imotov — APPROVED** [review]
left a couple of comment, otherwise - LGTM

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 2 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Good point - I think we should catch a generic `SnapshotException` here, because one other possible uncaught exception would be a generic `SnapshotException` if the snapshot is incompatible.  I will make this change.

Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: However, this would've been caught before by the deleteSnapshot, so there is really no other exception that should be uncaught on the listener.

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java (hunk 1 above)
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: Good call

**Comment by abeyad** [comment]
thanks for the review @imotov
