### PR TITLE
Re-enable spec tests in mixed cluster

### LINKED ISSUE #103765: ReplaceDuplicateAggWithEval break BWC between 8.11 and 8.12+
Queries with duplicated aggregations don't work in a mixed cluster between 8.11 and 8.12+. This is can reproduced as follow:

1. Set up a mixed cluster with two nodes: one 8.11.x node and one 8.12+ node
2. Index data into the new node only
3. Run this query against the old node
	```
	from employees | stats m = median(salary_change), p50 = percentile(salary_change, 50)
	```
4. ESQL failed with this exception:

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.xpack.esql.planner.Layout$ChannelAndType.channel()" because "input" is null
    at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planProject(LocalExecutionPlanner.java:536)
    at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:199)
    at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planExchangeSink(LocalExecutionPlanner.java:325)
    at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:229)
    at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:170)
    at org.elasticsearch.xpack.esql.plugin.ComputeService.runCompute(ComputeService.java:404)
    at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestHandler.lambda$messageReceived$5(ComputeService.java:588)
    at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:169)
    at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:274)
    at org.elasticsearch.xpack.esql.plugin.ComputeService.lambda$acquireSearchContexts$21(ComputeService.java:454)
    at org.elasticsearch.index.shard.IndexShard.ensureShardSearchActive(IndexShard.java:3967)
    at org.elasticsearch.xpack.esql.plugin.ComputeService.acquireSearchContexts(ComputeService.java:452)
    at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestHandler.messageReceived(ComputeService.java:581)
    at org.elasticsearch.xpack.esql.plugin.ComputeService$DataNodeRequestHandler.messageReceived(ComputeService.java:572)
    at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
    at org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:288)
    at org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:301)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.lang.Thread.run(Thread.java:1583)
```

The issue went unnoticed due to a bug in the mixed-cluster QA module (see #103758). Although I haven't investigated the details, I believe the introduction of `ReplaceDuplicateAggWithEval` in #100642 is causing the disparity between these versions. I think we should disable this rule in both 8.12 and 8.13, and reintroduce it later.

### PR DESCRIPTION
**Pull request by dnhatn**
This pull request re-enables ESQL spec tests in a mixed cluster by implementing these changes:

- Skipping spec tests with repeated aggregations in a mixed cluster between versions 8.11 and 8.12+ due to the impact of the ReplaceDuplicateAggWithEval rule.

- Avoiding access to the block factory in the InMapper constructor to prevent AssertionError when the driver context is ThrowingContextDriver.

Closes #103765

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/evaluator/predicate/operator/comparison/InMapper.java [hunk 1]
```diff
@@ -40,10 +41,10 @@ public ExpressionEvaluator.Factory map(In in, Layout layout) {
             ExpressionEvaluator.Factory eqEvaluator = ((ExpressionMapper) EQUALS).map(eq, layout);
             listEvaluators.add(eqEvaluator);
         });
-        return dvrCtx -> new InExpressionEvaluator(dvrCtx.blockFactory(), listEvaluators.stream().map(fac -> fac.get(dvrCtx)).toList());
+        return dvrCtx -> new InExpressionEvaluator(dvrCtx, listEvaluators.stream().map(fac -> fac.get(dvrCtx)).toList());
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/evaluator/predicate/operator/comparison/InMapper.java:44]: `drvCtx.blockFactory()` where the driverContext is ThrowingDriverContext can bring down Elasticsearch nodes. This can happen during the rolling upgrade from 8.11 to 8.12+ (see #103830).

**Review by costin — APPROVED** [review]
LGTM
Might be useful to link the GH ticket in the CSV spec as well.

**Comment by dnhatn** [comment]
Thanks, Costin. I pushed https://github.com/elastic/elasticsearch/issues/103765.
