### PR TITLE
Bulk api: fail deletes when routing is required but not specified

### LINKED ISSUE #16645: SimpleRoutingIT.testRequiredRoutingMapping fails because a doc remains undeleted
http://build-us-00.elastic.co/job/es_core_master_metal/12355/

```
elastic/elasticsearch
master

SUMMARY

Please direct your attention to the attached stacktraces associated with some or all of these tests:

org.elasticsearch.routing.SimpleRoutingIT testRequiredRoutingMapping
FAILED: 1
ERROR: 0
SKIPPED: 80
TOTAL: 5644

BUILD INFO

Build	20160212182431-BE4C2D89
Log	https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/406/console
Duration	12m 33s (753008ms)
Started	2016-02-12T18:24:32.000Z
Ended	2016-02-12T18:37:05.008Z
Exit Code	1
Host	slave-3740eaed (up 43 days)
OS	Ubuntu 15.04, Linux 3.19.0-42-generic
Specs	4 CPUs, 15.67GB RAM
java.version	1.8.0_45-internal
java.vm.name	OpenJDK 64-Bit Server VM
java.vm.version	25.45-b02
java.runtime.version	1.8.0_45-internal-b14
java.home	/usr/lib/jvm/java-8-openjdk-amd64
```

Failure replicates for me.

Due to https://github.com/elastic/elasticsearch/pull/10136, when a _routing is defined in the mapping, "Broadcast Deletes" are no longer allowed.  The `testRequiredRoutingMapping` test was updated in the single-delete case so that `isExists(), equalTo(true)` each time through the loop, since the document should not be deleted.

However, it looks like the Bulk Delete case wasn't changed, so the test is still trying to verify that the bulk delete "broadcasted" despite no _routing being specified:

```java
for (int i = 0; i < 5; i++) {
    try {
        client().prepareGet(indexOrAlias(), "type1", "1").execute().actionGet().isExists();
        fail();
    } catch (RoutingMissingException e) {
        assertThat(e.status(), equalTo(RestStatus.BAD_REQUEST));
        assertThat(e.getMessage(), equalTo("routing is required for [test]/[type1]/[1]"));
    }
    assertThat(
      client().prepareGet(indexOrAlias(), "type1", "1")
        .setRouting("0")
        .execute()
        .actionGet()
        .isExists(),
      equalTo(false));  // <-- Here
}
```

I assumed this was just a test problem, so I updated it to match the single-delete case (`isExists(), equalTo(true))`.  But that begins to fail under other seeds:

```
gradle :core:integTest -Dtests.seed=42425D480F1F72E8 -Dtests.class=org.elasticsearch.routing.SimpleRoutingIT -Dtests.method="testRequiredRoutingMapping" -Dtests.locale=es-CL -Dtests.timezone=AET
```

So either:

1. The test was correct, Bulk broadcast deletes without _routing are allowed, and the document isn't being deleted for some reason

2. Or the test is incorrect, bulk broadcast deletes *shouldn't* be allowed, but they are working anyway under certain conditions.

/cc @javanna any thoughts?

### PR DESCRIPTION
**Pull request by javanna**
As part of #10136 we removed the transport action for broadcast deletes in case routing is required but not specified. Bulk api worked differently though and kept on doing the broadcast delete internally in that case. This commit makes sure that delete items are marked as failed in such cases. Also the check has been moved up in the code together with the existing check for the update api, and we now make sure that the exception is the same as the one thrown for single document apis (delete/update).

Note that the failure for the update api contained the wrong optype (the type of the document rather than "update"), that's been fixed too and tested.

Closes #16645

### CODE REVIEW

**Comment by javanna** [comment]
@s1monw  can you have a look please?

File: core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 1]
```diff
@@ -214,32 +213,49 @@ private void executeBulk(final BulkRequest bulkRequest, final long startTime, fi
         MetaData metaData = clusterState.metaData();
         for (int i = 0; i < bulkRequest.requests.size(); i++) {
             ActionRequest request = bulkRequest.requests.get(i);
-            if (request instanceof DocumentRequest) {
-                DocumentRequest req = (DocumentRequest) request;
-
-                if (addFailureIfIndexIsUnavailable(req, bulkRequest, responses, i, concreteIndices, metaData)) {
-                    continue;
+            if (request == null) {
+                continue;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: this looks scary, whin can it happen?

File: core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 2]
```diff
@@ -214,32 +213,49 @@ private void executeBulk(final BulkRequest bulkRequest, final long startTime, fi
...
+                try {
+                    TransportUpdateAction.resolveAndValidateRouting(metaData, concreteIndex, (UpdateRequest)request);
+                } catch(RoutingMissingException e) {
+                    BulkItemResponse.Failure failure = new BulkItemResponse.Failure(concreteIndex, documentRequest.type(), documentRequest.id(), e);
+                    BulkItemResponse bulkItemResponse = new BulkItemResponse(i, "update", failure);
+                    responses.set(i, bulkItemResponse);
+                    // make sure the request gets never processed again
+                    bulkRequest.requests.set(i, null);
                 }
             }
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: should we do `else throw new AssertionError();`?

File: core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java (hunk 1 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: oh I see, because we set the request to null in case of validation issues. Can you leave a comment about this?

Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: it does happen, I only made it explicit and scary, before we were relying on the instanceof check to return false, which happened only when we set the request to false. I can add a comment, sure!

File: core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java (hunk 2 above)
Comment (javanna) [inline core/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java]: why not, sounds good to me, will do

**Comment by jpountz** [comment]
LGTM
