### PR TITLE
Analyze API to return 400 for wrong custom analyzer

### LINKED ISSUE #121443: When calling the _analyze API, it should be a 4xx when dictionary files are missing
### Elasticsearch Version

_any_

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

When calling the `_analyze` API, its possible to explore using it to see how things work with various dictionary files. However ,if a dictionary file is completely missing, this API throws a 5xx. For all analyzers that depend on user provided dictionaries, we should return a 4xx not a 5xx.

Example: when using `hunspell` it should be a 4xx if the dictionary is missing as that needs to be provided by the admin of the cluster.

### Steps to Reproduce

```
GET /_analyze
{
  "tokenizer": "standard",
  "filter": {"type": "hunspell", "locale": "en_US"},
  "text": "the knife foxes jumping quickly over knives"
}
```

### Logs (if relevant)

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "failed to load hunspell dictionary for locale: en_US"
      }
    ],
    "type": "illegal_state_exception",
    "reason": "failed to load hunspell dictionary for locale: en_US",
    "caused_by": {
      "type": "exception",
      "reason": "Could not find hunspell dictionary [en_US]"
    }
  },
  "status": 500
}
```

Full error:

```
org.elasticsearch.transport.RemoteTransportException: [es-es-search-5b7c555d59-xtvz7][100.66.132.194:9300][indices:admin/analyze[s]]\nCaused by: java.lang.IllegalStateException: failed to load hunspell dictionary for locale: en_US\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.indices.analysis.HunspellService.lambda$new$0(HunspellService.java:102)\n\tat java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1713)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.indices.analysis.HunspellService.getDictionary(HunspellService.java:119)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.index.analysis.HunspellTokenFilterFactory.<init>(HunspellTokenFilterFactory.java:34)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.indices.analysis.AnalysisModule.lambda$setupTokenFilters$0(AnalysisModule.java:163)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.plugins.AnalysisPlugin$1.get(AnalysisPlugin.java:128)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.index.analysis.AnalysisRegistry.getComponentFactory(AnalysisRegistry.java:132)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.index.analysis.AnalysisRegistry.buildCustomAnalyzer(AnalysisRegistry.java:267)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.buildCustomAnalyzer(TransportAnalyzeAction.java:218)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:143)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:129)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:66)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.action.support.single.shard.TransportSingleShardAction.lambda$asyncShardOperation$0(TransportSingleShardAction.java:113)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:79)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:76)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1575)\nCaused by: org.elasticsearch.ElasticsearchException: Could not find hunspell dictionary [en_US]\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.indices.analysis.HunspellService.loadDictionary(HunspellService.java:168)\n\tat org.elasticsearch.server@9.0.0/org.elasticsearch.indices.analysis.HunspellService.lambda$new$0(HunspellService.java:100)\n\t... 20 more\n
```

### PR DESCRIPTION
**Pull request by mayya-sharipova**
If a custom analyzer provided in _analyze API
can not be built, return 400 instead of the current
500. This most probably means that the user's provided analyzer specifications are wrong.

Closes #121443

### CODE REVIEW

**Review by john-wagster — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/action/admin/indices/analyze/TransportAnalyzeAction.java [hunk 1]
```diff
@@ -65,6 +66,8 @@
  */
 public class TransportAnalyzeAction extends TransportSingleShardAction<AnalyzeAction.Request, AnalyzeAction.Response> {
 
+    public static final NodeFeature WRONG_CUSTOM_ANALYZER_RETURN_400 = new NodeFeature("wrong_custom_analyzer_return_400");
```
Comment (john-wagster) [inline server/src/main/java/org/elasticsearch/action/admin/indices/analyze/TransportAnalyzeAction.java:69]: more for curiosity does this need to be a nodefeature or can it be a test feature.  it's unfortunate stuff like this has to be enumerated.

Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/action/admin/indices/analyze/TransportAnalyzeAction.java:69]: Could you simply make this a capability on the REST API side? That is much simpler and then you don't need all these feature things.

**Comment by mayya-sharipova** [comment]
@john-wagster @benwtrent Thank you for the feedback. I've modified the PR to use capabilties instead of feature.

**Review by benwtrent — APPROVED** [review]
:shipit:

**Review by john-wagster — APPROVED** [review]
