### PR TITLE
Fix NPE on plugin sync

### LINKED ISSUE #114818: NPE while restarting ES in docker
### Elasticsearch Version

Version: 8.15.2, Build: docker/98adf7bf6bb69b66ab95b761c9e5aadb0bb059a3/2024-09-19T10:06:03.564235954Z, JVM: 22.0.1

### Installed Plugins

analysis-icu

### Java Version

_bundled_

### OS Version

Linux vm-debian 6.1.0-26-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.112-1 (2024-09-30) x86_64 GNU/Linux

### Problem Description

I am running an ES in docker with plugins installed by `elasticsearch-plugins.yml`.
The first run was working well.
When I restart the container, it'll throw a NullPointerException and stop.

### Steps to Reproduce

1. Prepare `elasticsearch-plugins.yml`
```
plugins:
  - id: analysis-icu
```
2. Create a container
```
docker create docker.elastic.co/elasticsearch/elasticsearch:8.15.2
```
3. Copy configuration
```
docker cp elasticsearch-plugins.yml xxx:/usr/share/elasticsearch/config/elasticsearch-plugins.yml
```
4. Run initially （It's working properly)
```
docker start xxx
```
5. Restart (It's throwing NPE)
```
docker restart xxx
```

### Logs (if relevant)

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:220)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1709)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:702)
	at org.elasticsearch.plugins.cli.SyncPluginsAction.lambda$getPluginsToUpgrade$2(SyncPluginsAction.java:210)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.elasticsearch.plugins.cli.SyncPluginsAction.getPluginsToUpgrade(SyncPluginsAction.java:209)
	at org.elasticsearch.plugins.cli.SyncPluginsAction.getPluginChanges(SyncPluginsAction.java:133)
	at org.elasticsearch.plugins.cli.SyncPluginsAction.execute(SyncPluginsAction.java:101)
	at org.elasticsearch.plugins.cli.SyncPluginsCliProvider$1.execute(SyncPluginsCliProvider.java:49)
	at org.elasticsearch.server.cli.ServerCli.syncPlugins(ServerCli.java:206)
	at org.elasticsearch.server.cli.ServerCli.execute(ServerCli.java:98)
	at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:94)
	at org.elasticsearch.cli.Command.main(Command.java:51)
	at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64)
```

### PR DESCRIPTION
**Pull request by ldematte**
Reproducing https://github.com/elastic/elasticsearch/issues/114818, I noticed the problem presents itself when we have a `null` location in the plugin cache (`.elasticsearch-plugins.yml.cache`).
Following the steps from https://github.com/elastic/elasticsearch/issues/114818, the file contains:
```
{
  "plugins": [
    {
      "id": "analysis-icu",
      "location": null
    }
  ],
  "proxy": null
}
```
From the javadoc of `InstallablePlugin`, the `null` location is ok:
```
location    the location from which to fetch the plugin, e.g. a URL or Maven
            coordinates. Can be null for official plugins.
```

But when we use its content to look for plugins to upgrade, we use Collectors.toMap, which does _not_ accept null values.
I changed the Collectors.toMap to a simple foreach, and added a test with `null` location to verify it works (it used to fail before the change).

It is not clear to me how this was un-noticed before - shouldn't this always fail?
Or maybe adding an official plugins to `elasticsearch-plugins.yml` is not "supported" (and we should fail in a different place?)

Closes https://github.com/elastic/elasticsearch/issues/114818

### CODE REVIEW

**Review by pugnascotia — APPROVED** [review]
Nice catch, I'm surprised this problem has lurked for so long. I guess this feature doesn't see much use? But listing official plugins in the config should absolutely be supported.

File: distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/SyncPluginsAction.java [hunk 1]
```diff
@@ -207,9 +208,10 @@ private List<InstallablePlugin> getPluginsToUpgrade(
         Optional<PluginsConfig> cachedPluginsConfig,
         List<PluginDescriptor> existingPlugins
     ) {
-        final Map<String, String> cachedPluginIdToLocation = cachedPluginsConfig.map(
-            config -> config.getPlugins().stream().collect(Collectors.toMap(InstallablePlugin::getId, InstallablePlugin::getLocation))
-        ).orElse(Map.of());
+        final Map<String, String> cachedPluginIdToLocation = new HashMap<>();
+        cachedPluginsConfig.ifPresent(
+            config -> config.getPlugins().forEach(p -> cachedPluginIdToLocation.put(p.getId(), p.getLocation()))
```
Comment (rjernst) [inline distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/SyncPluginsAction.java:213]: Could this be `cachedPluginIdToLocation.putAll(config.getPlugins())`?

**Review by rjernst — APPROVED** [review]
LGTM, one suggesiton

File: distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/SyncPluginsAction.java (hunk 1 above)
Comment (ldematte) [reply distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/SyncPluginsAction.java:213]: config.getPlugins() returns a List, while putAll accepts a Map.
I can use the basic `collect` like
```
config.getPlugins().stream().collect(HashMap::new, (m,v)->m.put(v.getId(), v.getLocation()), HashMap::putAll) 
```
And keep it closer to the original code, but using `forEach` and `put` seemed simpler (and probably more efficient).
Wdyt?

**Comment by ldematte** [comment]
@elasticmachine update branch

File: distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/SyncPluginsAction.java (hunk 1 above)
Comment (rjernst) [reply distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/SyncPluginsAction.java]: What you have is fine then. I was hoping to avoid such nested lambdas.
