### PR TITLE
Prevent concurrent rollover race conditions 

### LINKED ISSUE #67836: Remove concurrent modification check in rollover action
The concurrent modification check does a "soft" rollover prior to the real rollover, comparing that result to the final "hard" rollover to make sure no other rollovers have happened in the meantime.

However, now that rollovers are completed in a single cluster state update, we don't need this compare-and-set check, as it only means we introduce our own race condition (that throws an exception when it races).

This does mean, however, that concurrent rollovers will result in rolling over twice (which is closer in line with what is intended since rollover was invoked twice).

### PR DESCRIPTION
**Pull request by dakrone**
We recently rewrote the `TransportRolloverAction` code to encapsulate the rollover into a single
cluster state. This is great, but we can do a bit better when there are concurrent rollover requests
that occur, specifically, we should meet both of the following criteria:

- Multiple concurrent unconditional rollovers should generate multiple rollovers without any concurrent
modification exceptions.
- Multiple concurrent rollovers with conditions should roll over exactly once, assuming the
condition is met only once

This commit changes the `TransportRolloverAction` code to reach these goals. It does it by treating
the cluster state submittion as a pseudo-"synchronized" block. This means that we calculate the
source, destination, and conditions met *prior* to performing the cluster state update. If the
conditions are met, we invoke a cluster state update. Inside the cluster state update (serialized,
so essentially inside our "synchronized" block) we recalculate the source, destination, and
contitions met, and only proceed with the rollover if the conditions on met.

As a byproduct of this, it also fixes issues where rollover could happen but the response returned
incorrect information such as conditions that weren't actually met or an incorrect
source/destination index.

I've also tried to document (with comments) the thought process and how this code works for future
generations.

This also adds a test with multiple threads all trying to invoke a rollover that ensures that only a
single rollover happens in the case conditions are specified.

Resolves #67836
Resloves #64921

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/rollover/RolloverIT.java [hunk 1]
```diff
@@ -562,4 +568,66 @@ public void testRolloverWithHiddenAliasesAndImplicitWriteIndex() {
         assertThat(oldIndex.getRolloverInfos().get(aliasName).getTime(),
             is(both(greaterThanOrEqualTo(beforeTime)).and(lessThanOrEqualTo(client().threadPool().absoluteTimeInMillis() + 1000L))));
     }
+
+    /**
+     * Tests that multiple threads all racing to rollover based on a condition trigger one and only one rollover
+     */
+    public void testMultiThreadedRollover() throws Exception {
+        final String aliasName = "alias";
```
Comment (andreidan) [inline server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/rollover/RolloverIT.java:576]: shall we add a similar test for data stream rollover?

File: server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java [hunk 2]
```diff
@@ -85,85 +84,138 @@ protected ClusterBlockException checkBlock(RolloverRequest request, ClusterState
...
+                            // Regenerate the rollover names, as a rollover could have happened
+                            // in between the pre-check and the cluster state update
+                            final MetadataRolloverService.NameResolution rolloverNames =
+                                rolloverService.resolveRolloverNames(currentState, rolloverRequest.getRolloverTarget(),
+                                    rolloverRequest.getNewIndexName(), rolloverRequest.getCreateIndexRequest());
+                            final String sourceIndexName = rolloverNames.sourceName;
+
+                            // Re-evaluate the conditions, now with our final source index name
+                            final Map<String, Boolean> postConditionResults = evaluateConditions(rolloverRequest.getConditions().values(),
+                                metadata.index(sourceIndexName), statsResponse);
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java:153]: I'm a bit worried about the semantics of the `Multiple concurrent rollovers with conditions should roll over exactly once, assuming the condition is met only once` invariant. Namely about the `assuming the condition is met only once` bit. I think a concurrent rollover will always be rejected. 

Let's assume the conditions would be met even if there was a concurrent rollover (there was a rollover and a  document indexed when the condition was `max_docs: 1` so by the time we got to re-evaluate the conditions as part of the "rollover cluster state change" the alias/ds target is indeed ready to rollover again). 
But we are evaluating against the old `statsResponse`. The rollover will never meet the condition as the stats don't contain the now latest index - the `sourceIndex` is now generation `000002` (as the concurrent rollover created this index) but we grabbed the stats when this index didn't exist (the latest generation was `000001` in the beginning). 

I believe we should redefine the invariant here (and the implementation should we decide to change it).

**Review by andreidan — CHANGES_REQUESTED** [review]
Thanks for working on this @dakrone. 

I've manually tested this a bit. I think one of the advertised invariants is not upheld. I've left a comment about that and a few other minor suggestions.

File: server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java (hunk 2 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java:153]: Thinking about this some more, I think it's rather unlikely for very fast consecutive rollovers to be what the users want, so I'd say if we detect the source name changed (ie. the target was already rolled over) we should not do anything (ie. ` return currentState`). The client listener will have the option to retry themselves as the API will reflect that rollover didn't happen.
What do you think?

Comment (dakrone) [reply server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java:153]: I agree, I glossed over the fact that the stats are only generated once per rollover (rather than invoked twice), but it is possible for the retrieval of stats to be separate from the evaluation of those conditions within the cluster state update thread. I think this is a reasonable compromise.

Comment (dakrone) [reply server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java:153]: > I think it's rather unlikely for very fast consecutive rollovers to be what the users want, so I'd say if we detect the source name changed (ie. the target was already rolled over) we should not do anything (ie. return currentState).

I think I'd prefer to err on the side of the behavior being consistent with regard to the number of requests, for example, N unconditional rollover requests should roll over N times. I think we (ES) shouldn't make judgements about "oh there are too many rollovers within an amount of time so I'm not going to do the subsequent ones", especially since it's possible for the rollover to be delayed (in extreme cases, it could be a while between the actual rollovers even if they are initiated at the same time)

**Comment by dakrone** [comment]
@andreidan thanks for the comments, I think I addressed everything, lemme know if not!

**Comment by dakrone** [comment]
@elasticmachine update branch

**Review by andreidan — APPROVED** [review]
LGTM, this is great! thanks for fixing and iterating on this Lee
