### PR TITLE
[Entitlements] Add missing entitlements for trust store

### LINKED ISSUE #122546: [CI] ApmAgentSettingsIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6518 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/44z2tnnrk64e2)
- [elasticsearch-periodic-platform-support #6518 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/bl7jaxmwsca54)
- [elasticsearch-pull-request #58405 / part-1-fips](https://gradle-enterprise.elastic.co/s/ld4pzz3ute2ig)
- [elasticsearch-pull-request #58398 / part-1-fips](https://gradle-enterprise.elastic.co/s/b37ncucz3vg4y)
- [elasticsearch-pull-request #58395 / part-1-fips](https://gradle-enterprise.elastic.co/s/qnkkat4jqwjfk)
- [elasticsearch-pull-request #58229 / part-1-fips](https://gradle-enterprise.elastic.co/s/4dt2u7wgfawzq)
- [elasticsearch-periodic-platform-support #6497 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/3tco7k6j67kui)
- [elasticsearch-periodic-platform-support #6497 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/s3fs3xlzkorew)
- [elasticsearch-pull-request #58115 / part-1-fips](https://gradle-enterprise.elastic.co/s/qiyxegse37iga)
- [elasticsearch-pull-request #58110 / part-1-fips](https://gradle-enterprise.elastic.co/s/63bga27ekrv7a)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.telemetry.apm.ApmAgentSettingsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.telemetry.apm.ApmAgentSettingsIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in class org.elasticsearch.telemetry.apm.ApmAgentSettingsIT
- [8.x] 3 consecutive failures in step part-1-fips
- [8.x] 24 failures in class org.elasticsearch.telemetry.apm.ApmAgentSettingsIT (5.9% fail rate in 410 executions)
- [8.x] 4 failures in step windows-2019_checkpart1_platform-support-windows (66.7% fail rate in 6 executions)
- [8.x] 4 failures in step windows-2022_checkpart1_platform-support-windows (66.7% fail rate in 6 executions)
- [8.x] 15 failures in step part-1-fips (78.9% fail rate in 19 executions)
- [8.x] 4 failures in pipeline elasticsearch-periodic-platform-support (40.0% fail rate in 10 executions)
- [8.x] 15 failures in pipeline elasticsearch-pull-request (31.3% fail rate in 48 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122566: [CI] EntitlementsDeniedIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6511 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/y7ihmvuhmrm4e)
- [elasticsearch-periodic-platform-support #6511 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/u2tglv75hmsf4)
- [elasticsearch-pull-request #58246 / part-1-fips](https://gradle-enterprise.elastic.co/s/nhqblaqej6n76)
- [elasticsearch-pull-request #57909 / part-1-fips](https://gradle-enterprise.elastic.co/s/xlkewzrtt4eba)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsDeniedIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsDeniedIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in class org.elasticsearch.entitlement.qa.EntitlementsDeniedIT
- [8.x] 2 consecutive failures in step part-1-fips
- [8.x] 4 failures in class org.elasticsearch.entitlement.qa.EntitlementsDeniedIT (2.0% fail rate in 201 executions)
- [8.x] 2 failures in step part-1-fips (100.0% fail rate in 2 executions)
- [8.x] 2 failures in pipeline elasticsearch-pull-request (10.5% fail rate in 19 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122568: [CI] EntitlementsAllowedNonModularIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6511 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/y7ihmvuhmrm4e)
- [elasticsearch-periodic-platform-support #6511 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/u2tglv75hmsf4)
- [elasticsearch-pull-request #58246 / part-1-fips](https://gradle-enterprise.elastic.co/s/nhqblaqej6n76)
- [elasticsearch-pull-request #57909 / part-1-fips](https://gradle-enterprise.elastic.co/s/xlkewzrtt4eba)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsAllowedNonModularIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsAllowedNonModularIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in class org.elasticsearch.entitlement.qa.EntitlementsAllowedNonModularIT
- [8.x] 2 consecutive failures in step part-1-fips
- [8.x] 4 failures in class org.elasticsearch.entitlement.qa.EntitlementsAllowedNonModularIT (2.0% fail rate in 201 executions)
- [8.x] 2 failures in step part-1-fips (100.0% fail rate in 2 executions)
- [8.x] 2 failures in pipeline elasticsearch-pull-request (10.5% fail rate in 19 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122569: [CI] EntitlementsDeniedNonModularIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6511 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/y7ihmvuhmrm4e)
- [elasticsearch-periodic-platform-support #6511 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/u2tglv75hmsf4)
- [elasticsearch-pull-request #58246 / part-1-fips](https://gradle-enterprise.elastic.co/s/nhqblaqej6n76)
- [elasticsearch-pull-request #57909 / part-1-fips](https://gradle-enterprise.elastic.co/s/xlkewzrtt4eba)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsDeniedNonModularIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsDeniedNonModularIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in class org.elasticsearch.entitlement.qa.EntitlementsDeniedNonModularIT
- [8.x] 2 consecutive failures in step part-1-fips
- [8.x] 4 failures in class org.elasticsearch.entitlement.qa.EntitlementsDeniedNonModularIT (2.0% fail rate in 201 executions)
- [8.x] 2 failures in step part-1-fips (100.0% fail rate in 2 executions)
- [8.x] 2 failures in pipeline elasticsearch-pull-request (10.5% fail rate in 19 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #122680: [CI] EntitlementsAllowedIT class failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6511 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/y7ihmvuhmrm4e)
- [elasticsearch-periodic-platform-support #6511 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/u2tglv75hmsf4)
- [elasticsearch-pull-request #58246 / part-1-fips](https://gradle-enterprise.elastic.co/s/nhqblaqej6n76)
- [elasticsearch-pull-request #57909 / part-1-fips](https://gradle-enterprise.elastic.co/s/xlkewzrtt4eba)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsAllowedIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.entitlement.qa.EntitlementsAllowedIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in class org.elasticsearch.entitlement.qa.EntitlementsAllowedIT
- [8.x] 2 consecutive failures in step part-1-fips
- [8.x] 4 failures in class org.elasticsearch.entitlement.qa.EntitlementsAllowedIT (2.0% fail rate in 201 executions)
- [8.x] 2 failures in step part-1-fips (100.0% fail rate in 2 executions)
- [8.x] 2 failures in pipeline elasticsearch-pull-request (10.5% fail rate in 19 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mosche**
Add missing entitlements for trust store if running in fips mode.

Fixes #122546, fixes #122569, fixes #122568, fixes #122680, fixes #122566

### CODE REVIEW

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/initialization/EntitlementInitialization.java [hunk 1]
```diff
@@ -204,6 +205,12 @@ private static PolicyManager createPolicyManager() {
                         new LoadNativeLibrariesEntitlement(),
                         new FilesEntitlement(List.of(FileData.ofRelativePath(Path.of(""), FilesEntitlement.BaseDir.DATA, READ_WRITE)))
                     )
+                ),
+                new Scope(
```
Comment (rjernst) [inline libs/entitlement/src/main/java/org/elasticsearch/entitlement/initialization/EntitlementInitialization.java:209]: Could we only add this if the trust store property is present? Then we don't need to handle an empty list of files.

**Review by rjernst — COMMENTED** [review]
LGTM

File: libs/entitlement/src/main/java/org/elasticsearch/entitlement/initialization/EntitlementInitialization.java (hunk 1 above)
Comment (mosche) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/initialization/EntitlementInitialization.java]: Initially did it this way to minimize the risk of conflicts, but changed to add the scope conditionally 👍

Comment (ldematte) [reply libs/entitlement/src/main/java/org/elasticsearch/entitlement/initialization/EntitlementInitialization.java]: There will be conflicts anyway, this class is getting hammered :)

**Review by ldematte — APPROVED** [review]
LGTM
