### PR TITLE
Fix Infinite Loops in ExceptionsHelper#unwrap

### LINKED ISSUE #42340: ExceptionsHelper might enter infinite loops or fail with a stack overflow
Cycles in exceptions' causes or suppressions can trigger bugs, try to run eg. the following tests:

```java
    public void testSuppressedCycle() {
        RuntimeException e1 = new RuntimeException();
        RuntimeException e2 = new RuntimeException();
        e1.addSuppressed(e2);
        e2.addSuppressed(e1);
        ExceptionsHelper.unwrapCorruption(e1);
    }

    public void testCauseCycle() {
        RuntimeException e1 = new RuntimeException();
        RuntimeException e2 = new RuntimeException(e1);
        e1.initCause(e2);
        ExceptionsHelper.unwrapCorruption(e1);
    }
```

The first one fails with a `StackOverflowError` and the second one enters an infinite loop. It occurred to me while giving another look at #41889 but this is a pre-existing issue.

cc @original-brownbear

### PR DESCRIPTION
**Pull request by original-brownbear**
* Keep track of all seen exceptions and break out on loops
* Closes #42340

### CODE REVIEW

**Review by ywelsch — CHANGES_REQUESTED** [review]
This implements similar but slightly different logic than `maybeError`.
Can we do it one way and even reuse code?

**Comment by original-brownbear** [comment]
@ywelsch sure done in 832db83 :) Reused the existing approach, I think it's good enough to go 1024 (right?) steps and it's safer without the recursion.

**Review by jpountz — CHANGES_REQUESTED** [review]
Maybe I'm being over cautious, but I'd like to collect exceptions that have been seen so far better than using a counter. The reason is that with the counter approach, given that we look at suppressed exceptions before causes, if there is a cycle in suppressed exceptions then we will never look at the causes.

Maybe we also need to improve naming in this class, we have one `unwrap` method that only looks at causes and another one that looks at both causes and suppressed exceptions, this got me a bit confused while reviewing.

**Comment by original-brownbear** [comment]
@jpountz thanks for spotting that. I added a test for the case you mentioned, removed the step limit, put the set of all visited Exceptions back into action and removed the recursion -> let me know what you think :)
Didn't do any renaming though, not sure we want to mix renaming (that also affect other code) with the changes here?

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

File: server/src/main/java/org/elasticsearch/ExceptionsHelper.java [hunk 1]
```diff
@@ -246,33 +244,22 @@ public static boolean reThrowIfNotNull(@Nullable Throwable e) {
...
-     *
-     * @param cause the root throwable
-     * @return an optional error if one is found suppressed or a root cause in the tree rooted at the specified throwable
-     */
-    public static Optional<Error> maybeError(final Throwable cause, final Logger logger) {
-        // early terminate if the cause is already an error
-        if (cause instanceof Error) {
-            return Optional.of((Error) cause);
+    @SuppressWarnings("unchecked")
+    private static <T extends Throwable> Optional<T> unwrap(Throwable cause, Predicate<Throwable> predicate) {
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/ExceptionsHelper.java]: when I mentioned naming, I was thinking that this one could e.g. be called something like `unwrapCausesAndSuppressed` (ugly, maybe you can think of something better :) ), which shouldn't be an issue since it's both new and private?

**Review by jpountz — APPROVED** [review]
LGTM

File: server/src/main/java/org/elasticsearch/ExceptionsHelper.java (hunk 1 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/ExceptionsHelper.java]: Ah that makes sense :) I couldn't think of anything better though 850d507

**Comment by original-brownbear** [comment]
@jpountz thanks!
@ywelsch you're good with this one as well?

**Review by ywelsch — APPROVED** [review]
LGTM
