### PR TITLE
Sometimes delegate to SourceLoader in ValueSourceReaderOperator for required stored fields

### LINKED ISSUE #115076: [CI] AnnotatedTextFieldMapperTests testBlockLoaderFromRowStrideReaderWithSyntheticSource failing
**Build Scans:**
- [elasticsearch-intake #11444 / part1](https://gradle-enterprise.elastic.co/s/5p5ywgk6jzc44)
- [elasticsearch-pull-request #37107 / part-1](https://gradle-enterprise.elastic.co/s/573gq2kl4xz4m)
- [elasticsearch-intake #11441 / part1](https://gradle-enterprise.elastic.co/s/nzmefsttbxung)

**Reproduction Line:**
```
./gradlew ":plugins:mapper-annotated-text:test" --tests "org.elasticsearch.index.mapper.annotatedtext.AnnotatedTextFieldMapperTests.testBlockLoaderFromColumnReaderWithSyntheticSource" -Dtests.seed=C4C2E205B3F04149 -Dtests.locale=as-IN -Dtests.timezone=Japan -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testBlockLoaderFromRowStrideReaderWithSyntheticSource'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.index.mapper.annotatedtext.AnnotatedTextFieldMapperTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: expected null, but was:<BlockSourceReader.Bytes[Norms]>
```

**Issue Reasons:**
- [main] 3 failures in test testBlockLoaderFromRowStrideReaderWithSyntheticSource (1.4% fail rate in 220 executions)
- [main] 2 failures in step part1 (6.5% fail rate in 31 executions)
- [main] 2 failures in pipeline elasticsearch-intake (6.5% fail rate in 31 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by martijnvg**
If source is required by a block loader then the `StoredFieldsSpec` that gets populated should be enhanced by `SourceLoader#requiredStoredFields(...)` in `ValuesSourceReaderOperator`. Otherwise in case of synthetic source many stored fields aren't loaded, which causes only a subset of _source to be synthesized.  For example when unmapped fields exist or field values that exceed configured ignore above will not appear is _source.

This happens when field types fallback to a block loader implementation that uses _source. The required field values are then extracted from the source once loaded.  

This change also reverts the production code changes introduced via #114903. That change only ensured that `_ignored_source` field was added to the required list of stored fields. In reality more fields could be required. This change is better fix, since it handles also other cases and the `SourceLoader` implementation indicates which stored fields are needed.

Closes #115076, #115074, #115073 and #115066

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 1]
```diff
@@ -1025,7 +1025,14 @@ protected String delegatingTo() {
             }
             SourceValueFetcher fetcher = SourceValueFetcher.toString(blContext.sourcePaths(name()));
             var sourceMode = blContext.indexSettings().getIndexMappingSourceMode();
-            return new BlockSourceReader.BytesRefsBlockLoader(fetcher, blockReaderDisiLookup(blContext), sourceMode);
+            if (sourceMode == SourceFieldMapper.Mode.SYNTHETIC && syntheticSourceDelegate().ignoreAbove() != Integer.MAX_VALUE) {
+                // Can't just read the original field, because only when ignore_above threshold is exceeded,
+                // then this stored fields gets added. In other cases this field does not exist. But we do need to include the field name:
+                String originalName = syntheticSourceDelegate().name() + "._original";
```
Comment (lkts) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:1031]: Can we encapsulate this logic inside `KeywordFieldMapper` somehow similar to how `syntheticSourceDelegate()` works? It would eliminate this kind of problem.

File: x-pack/plugin/logsdb/src/yamlRestTest/resources/rest-api-spec/test/50_esql_synthetic_source_disabled_fields.yml [hunk 2]
```diff
@@ -303,3 +303,113 @@ teardown:
...
+  - match: {columns.8.type: "integer"}
+
+  - match: {values.0.0: "2024-02-12T10:31:00.000Z"}
+  - match: {values.0.1: "yoda"}
+  - match: {values.0.2: "bar"}
+  - match: {values.0.3: "PUT"}
+  - match: {values.0.4: false}
+  - match: {values.0.5: "POINT (-74.006 40.7128)"}
+  - match: {values.0.6: "Do. Or do not. There is no try."}
+#  - match: {values.0.7: "Do. Or do not. There is no try."}
```
Comment (lkts) [inline x-pack/plugin/logsdb/src/yamlRestTest/resources/rest-api-spec/test/50_esql_synthetic_source_disabled_fields.yml:399]: Why is this commented?

Comment (martijnvg) [reply x-pack/plugin/logsdb/src/yamlRestTest/resources/rest-api-spec/test/50_esql_synthetic_source_disabled_fields.yml:399]: Whoops and I think this may need some extra work.

**Comment by dnhatn** [comment]
It seems that the BlockReader for a text field with stored=false and no subfields does not return values. Should we address this issue in this PR as well?

**Comment by martijnvg** [comment]
> It seems that the BlockReader for a text field with stored=false and no subfields does not return values. Should we address this issue in this PR as well?

Yes, this is a separate issue. The `TextFieldMapper#parseCreateField(...)` ignores that value when a text field isn't stored or doesn't have a suitable keyword subfield. I think the value should be added to ignored source if that is the case. This should be addressed on a follow up. This is also an issue for get and search apis.

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 3]
```diff
@@ -1007,20 +1007,8 @@ protected String delegatingTo() {
             if (isStored()) {
                 return new BlockStoredFieldsReader.BytesFromStringsBlockLoader(name());
             }
-            if (isSyntheticSource && syntheticSourceDelegate == null) {
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:1010]: In this case the value of text fields is captured in ignored source.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java [hunk 4]
```diff
@@ -241,6 +241,12 @@ private void loadFromSingleLeaf(Block[] blocks, int shard, int segment, BlockLoa
                 }
             }
 
+            SourceLoader sourceLoader = null;
+            if (storedFieldsSpec.requiresSource()) {
+                sourceLoader = shardContexts.get(shard).newSourceLoader.get();
+                storedFieldsSpec = storedFieldsSpec.merge(new StoredFieldsSpec(true, true, sourceLoader.requiredStoredFields()));
```
Comment (dnhatn) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:247]: The second parameter, `requiresMetadata`, should be false.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java [hunk 5]
```diff
@@ -381,9 +387,14 @@ private void fieldsMoved(LeafReaderContext ctx, int shard) throws IOException {
                 FieldWork field = fields[f];
                 rowStride[f] = field.rowStride(ctx);
                 storedFieldsSpec = storedFieldsSpec.merge(field.loader.rowStrideStoredFieldSpec());
+                SourceLoader sourceLoader = null;
```
Comment (dnhatn) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:390]: I think the code from here to the end of the loop can be moved outside and executed once.

```java
            if (false == storedFieldsSpec.equals(StoredFieldsSpec.NO_REQUIREMENTS)) {
                trackStoredFields(storedFieldsSpec, false);
                SourceLoader sourceLoader = null;
                if (storedFieldsSpec.requiresSource()) {
                    sourceLoader = shardContexts.get(shard).newSourceLoader.get();
                    storedFieldsSpec = storedFieldsSpec.merge(new StoredFieldsSpec(true, false, sourceLoader.requiredStoredFields()));
                }
                storedFields = new BlockLoaderStoredFieldsFromLeafLoader(
                    StoredFieldLoader.fromSpec(storedFieldsSpec).getLoader(ctx, null),
                    sourceLoader != null ? sourceLoader.leaf(ctx.reader(), null) : null
                );
            }
```

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java [hunk 6]
```diff
@@ -381,9 +387,14 @@ private void fieldsMoved(LeafReaderContext ctx, int shard) throws IOException {
...
+                if (storedFieldsSpec.requiresSource()) {
+                    sourceLoader = shardContexts.get(shard).newSourceLoader.get();
+                    storedFieldsSpec = storedFieldsSpec.merge(new StoredFieldsSpec(true, true, sourceLoader.requiredStoredFields()));
```
Comment (dnhatn) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:393]: The second parameter, requiresMetadata, should be false.

**Review by dnhatn — COMMENTED** [review]
I have two comments, but this approach looks better.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java (hunk 4 above)
Comment (martijnvg) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:247]: Maybe it should be sourced from `storedFieldsSpec` variable (which is always initialized and gets updates by block loaders)? It could be that a block loader required metadata?

Comment (martijnvg) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java]: This is what I meant: e2c77e11120e284c374490846671423507c91b16

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java (hunk 5 above)
Comment (martijnvg) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java]: good catch: 455ecd03a692119e10f244022f5c1d8f8559ae90

File: test/framework/src/main/java/org/elasticsearch/index/mapper/MapperTestCase.java [hunk 7]
```diff
@@ -1362,9 +1364,19 @@ public FieldNamesFieldMapper.FieldNamesFieldType fieldNames() {
...
-        SyntheticSourceExample example = syntheticSourceSupport(false, columnReader).example(5);
+        var syntheticSourceSupport = syntheticSourceSupport(false, columnReader);
+        SyntheticSourceExample example = syntheticSourceSupport.example(5);
+        if (syntheticSource && columnReader == false) {
+            // The synthetic source testing support can't always handle now the difference between stored and synthetic source mode.
+            // In case of ignore above, the ignored values are always appended after the valid values
+            // (both if field has doc values or stored field). While stored source just reads original values (from _source) and there
+            // is no notion of values that are ignored.
+            // TODO: fix this by improving block loader support: https://github.com/elastic/elasticsearch/issues/115257
+            assumeTrue("inconsistent synthetic source testing support with ignore above", syntheticSourceSupport.ignoreAbove() == false);
```
Comment (martijnvg) [inline test/framework/src/main/java/org/elasticsearch/index/mapper/MapperTestCase.java:1375]: I'm not too happy about this. Altering the synthetic source example so that the right expected result is produced caused other test failures when stored source is used. The fact that `SyntheticSourceExample` is used for both stored and synthetic source doesn't seem right. I think the right fix is to improve the block loader testing by replacing synthetic source support by something else, like is hinted in#115257.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java (hunk 4 above)
Comment (dnhatn) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java]: Yes, that works too. However, I prefer passing `false` for both the first and second arguments, as it yields the same spec since they are XORed in the `merge` method. I think it's clearer to indicate that we are appending `required stored fields` from the source loader to the spec. But I'm okay with your approach as well - just a minor nit.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @martijnvg

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java [hunk 8]
```diff
@@ -241,6 +241,14 @@ private void loadFromSingleLeaf(Block[] blocks, int shard, int segment, BlockLoa
                 }
             }
 
+            SourceLoader sourceLoader = null;
+            if (storedFieldsSpec.requiresSource()) {
+                sourceLoader = shardContexts.get(shard).newSourceLoader.get();
+                storedFieldsSpec = storedFieldsSpec.merge(
+                    new StoredFieldsSpec(true, storedFieldsSpec.requiresMetadata(), sourceLoader.requiredStoredFields())
+                );
+            }
```
Comment (kkrik-es) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:250]: This seems duplicated? I wonder if we can add a helper function `getSourceLoaderLeaf` to encapsulate this logic, along with getting the leaf.

**Review by lkts — COMMENTED** [review]
I have to admit i don't really understand what's going on. Based on tests LGTM.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java (hunk 8 above)
Comment (martijnvg) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/ValuesSourceReaderOperator.java:250]: It is duplicated, but if this is turned into a helper method it isn't necessarily getting cleaner. It would need to return a source loader and stored field spec, which means a tuple or something like that needs to be used, which makes using the helper method verbose.
