### PR TITLE
Automatically set the collection mode to breadth_first in the terms aggregation when the cardinality of the field is unknown or greater than the requested size.

### LINKED ISSUE #9825: Define good heuristics to use `collect_mode: breadth_first`
`breadth_first` does not work when sub aggregations require scores, which is why we never use it by default today. However, we recently added the ability to know whether an aggregator requires scores or not (for now it just assumes that if a script is used then scripts are needed but we can improve it in the future, for instance I think we could have the information with lucene-expressions at least).

This means that we could now use `breadth_first` by default, we just need to figure out a good heuristic of when this is going to make the terms agg faster and/or more memory-efficient.

### PR DESCRIPTION
**Pull request by jimczi**
For fields with big cardinality this can save a lot of memory and speed up the overall aggregations.
For instance with an index of 100,000 documents and two fields (f1 and f2) with a cardinality of 10,000, the following query:

```
"aggs": {
  "f1": {
    "terms": {
       "field": "f1"
    },
    "aggs": {
       "f2": {
          "terms": {
            "field": "f2
         }
      }
    }
  }
}
```

... takes 100ms to finish with the depth_first mode and 10ms with breadth_first. 

For fields with small cardinality the breadth_first mode can use more memory than the depth_first.
This PR does not handle this case yet.

closes #9825

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java [hunk 1]
```diff
@@ -150,14 +150,24 @@ protected Aggregator doCreateInternal(ValuesSource valuesSource, Aggregator pare
                     }
                 }
             }
+            SubAggCollectionMode cm = collectMode;
+            if (cm == null) {
+                cm = SubAggCollectionMode.DEPTH_FIRST;
+                if (factories != AggregatorFactories.EMPTY) {
+                    int expectedSize = Math.max(bucketCountThresholds.getRequiredSize(),
+                        bucketCountThresholds.getShardSize());
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java]: I think getShardSize would always we >= getRequiredSize?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java [hunk 2]
```diff
@@ -167,26 +177,57 @@ protected Aggregator doCreateInternal(ValuesSource valuesSource, Aggregator pare
...
+    static SubAggCollectionMode subAggCollectionMode(int expectedSize, long maxOrd) {
+        if (expectedSize == Integer.MAX_VALUE) {
+            // return all buckets
+            return SubAggCollectionMode.DEPTH_FIRST;
+        }
+        if (maxOrd == -1 || maxOrd > expectedSize) {
+            // use breadth_first if the cardinality is bigger than the expected size or unknown (-1)
+            return SubAggCollectionMode.BREADTH_FIRST;
+        }
+        if (maxOrd > expectedSize) {
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java]: we will never run this block since the condition is already covered in the previous if statement?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java [hunk 3]
```diff
@@ -167,26 +177,57 @@ protected Aggregator doCreateInternal(ValuesSource valuesSource, Aggregator pare
...
+            double r = expectedSize / maxOrd;
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java]: I think we need to cast expectedSize to double, otherwise it runs the integer division first and only then casts to a double?

File: docs/reference/aggregations/bucket/terms-aggregation.asciidoc [hunk 4]
```diff
@@ -617,7 +621,7 @@ mode as opposed to the default `depth_first` mode:
              "terms" : {
                  "field" : "actors",
                  "size" : 10,
-                 "collect_mode" : "breadth_first"
+                 "collect_mode" : "breadth_first|depth_first"
```
Comment (jpountz) [inline docs/reference/aggregations/bucket/terms-aggregation.asciidoc]: I think we should keep it a working example, so intead of putting `breadth_first|depth_first`, maybe we can add an annotation that says that it also accepts `depth_first`?

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java (hunk 2 above)
Comment (jimferenczi) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java]: Bad commit, sorry. My first intention was to use breadth_first only if maxOrd is ten times bigger than expectedSize and I forgot to remove the statement. I think that maxOrd > expectedSize is enough.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java (hunk 3 above)
Comment (jimferenczi) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java]: I'll remove this part.

File: docs/reference/aggregations/bucket/terms-aggregation.asciidoc (hunk 4 above)
Comment (jimferenczi) [inline docs/reference/aggregations/bucket/terms-aggregation.asciidoc]: Sure, will do.

File: core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java (hunk 1 above)
Comment (jimferenczi) [inline core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorFactory.java]: Right, I pushed a fix.

**Comment by jpountz** [comment]
LGTM. The heuristic is simple, I like it.

As a follow-up, we might want to change the heuristic for the default shard size (BucketUtils.suggestShardSideQueueSize). Currently it is very aggressive (`size * min(10, num_shards)`), which would probably cause `breadth_first` to be used quite often in practice with this change? For instance Solr is doing `size*1.5+10`, which looks more reasonable to me?

**Comment by jpountz** [comment]
Sorry I was thinking backwards, this aggressivity actually favors *depth first*. Yet I think there is still an argument that by making the default shard size less aggressive, we could save memory since there would be more opportunities to use breadth_first (while still having good accuracy for zipfian distributions).

**Comment by rayward** [comment]
Any chance of this getting backported to 2.x?

**Comment by atealxt** [comment]
I get this PR from search engine. The word `smaller` should be `bigger` in the PR title, isn't it? It made me confused.

**Comment by jpountz** [comment]
@atealxt Agreed, I renamed.
