### PR TITLE
Don’t ack if unable to remove failing replica

### LINKED ISSUE #39467: FollowerFailOverIT.testFailOverOnFollower fails on CI
The test `FollowerFailOverIT.testFailOverOnFollower` failed today on 7.0: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+internalClusterTest/1446

It does not reproduce locally with:
```
 ./gradlew :x-pack:plugin:ccr:internalClusterTest \
  -Dtests.seed=D87CDC85B26F55B8 \
  -Dtests.class=org.elasticsearch.xpack.ccr.FollowerFailOverIT \
  -Dtests.method="testFailOverOnFollower" \
  -Dtests.security.manager=true \
  -Dtests.locale=id-ID \
  -Dtests.timezone=Africa/Ndjamena \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

It is maybe related to #35403 or #38633 but I haven't found the same exact errors so I'm opening a new issue.

The log shows some timeout issues with the `GlobalCheckpointListeners`:
```
14:23:04   1> [2019-02-27T15:20:06,932][TRACE][o.e.i.s.IndexShard       ] [leader1] [leader_test_failover][0] global checkpoint listener timed out
14:23:04   1> java.util.concurrent.TimeoutException: 10ms
14:23:04   1> 	at org.elasticsearch.index.shard.GlobalCheckpointListeners.lambda$add$3(GlobalCheckpointListeners.java:141) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
14:23:04   1> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_202]
14:23:04   1> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_202]
14:23:04   1> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_202]
14:23:04   1> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_202]
14:23:04   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
14:23:04   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
```

And some mismatched documents:
```
14:23:54    > 		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
14:23:54    > 		at org.elasticsearch.xpack.CcrIntegTestCase.lambda$assertIndexFullyReplicatedToFollower$4(CcrIntegTestCase.java:505)
14:23:54    > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:856)
14:23:54    > 		... 39 more
14:23:54    > 	Suppressed: java.lang.AssertionError: mismatched documents [{0=[DocIdSeqNoAndTerm{id='133 seqNo=135 primaryTerm=1}, DocIdSeqNoAndTerm{id='132 seqNo=134 primaryTerm=1}, DocIdSeqNoAndTerm{id='131 seqNo=133 primaryTerm=1}]}]
```

I tried to isolate the relevant test log:
[consoleText.txt](https://github.com/elastic/elasticsearch/files/2911173/consoleText.txt)

### PR DESCRIPTION
**Pull request by dnhatn**
Today when a replicated write operation fails to execute on a replica, the primary will reach out to the master to fail that replica (and mark it stale). We then won't ack that request until the master removes the failing replica; otherwise, we will lose the acked operation if the failed replica is still in the in-sync set. However, if a node with the primary is shutting down, we might ack such request even though we are unable to send a shard-failure request to the master. This happens because we ignore NodeClosedException which is triggered when the ClusterService is being closed.

Closes #39467

/cc @bleskes @martijnvg @jasontedor

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/discovery/ClusterDisruptionIT.java [hunk 1]
```diff
@@ -436,4 +442,54 @@ public void testIndicesDeleted() throws Exception {
         assertFalse(client().admin().indices().prepareExists(idxName).get().isExists());
     }
 
+    public void testRestartPrimaryNodeWhileIndexing() throws Exception {
```
Comment (dnhatn) [inline server/src/test/java/org/elasticsearch/discovery/ClusterDisruptionIT.java]: I will combine this newly added test to `testAckedIndexing` in a follow-up.

File: server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java [hunk 2]
```diff
@@ -204,13 +202,18 @@ public String toString() {
...
-        finishAsFailed(new RetryOnPrimaryException(primary.routingEntry().shardId(), primaryFail, demotionFailure));
+    private void onNoLongerPrimary(Exception failure) {
+        final String message;
+        if (failure instanceof ShardStateAction.NoLongerPrimaryShardException) {
+            // we are no longer the primary, fail ourselves and start over
+            message = String.format(Locale.ROOT, "primary shard [%s] was demoted while failing replica shard", primary.routingEntry());
+            primary.failShard(message, failure);
+        } else {
+            // these can occur if the node is shutting down and are okay any other exception here is not expected and merits investigation.
+            assert failure instanceof NodeClosedException || failure instanceof TransportException : failure;
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: @bleskes mentioned that the TransportException here should be coming from https://github.com/elastic/elasticsearch/blob/022726011ce1d9e4748fd39293a3aeae6954b3ac/server/src/main/java/org/elasticsearch/transport/TransportService.java#L645-L649

We should verify this here with an assertion and (I think in a follow-up) look into throwing a more appropriate exception in TransportService. Possible options are `AlreadyClosedException` or a custom subclass of `TransportException`.

File: server/src/test/java/org/elasticsearch/discovery/ClusterDisruptionIT.java (hunk 1 above)
Comment (ywelsch) [reply server/src/test/java/org/elasticsearch/discovery/ClusterDisruptionIT.java]: was this test able to expose the bug without the fix?

File: server/src/test/java/org/elasticsearch/discovery/ClusterDisruptionIT.java [hunk 3]
```diff
@@ -436,4 +442,54 @@ public void testIndicesDeleted() throws Exception {
...
+            });
+            threads[i].start();
+        }
+        ensureGreen(index);
+        assertBusy(() -> assertThat(docID.get(), greaterThanOrEqualTo(100)));
+        ClusterState clusterState = internalCluster().clusterService().state();
+        for (ShardRouting shardRouting : clusterState.routingTable().allShards(index)) {
+            if (shardRouting.primary()) {
+                String nodeName = clusterState.nodes().get(shardRouting.currentNodeId()).getName();
+                internalCluster().restartNode(nodeName, new InternalTestCluster.RestartCallback());
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/discovery/ClusterDisruptionIT.java]: perhaps just restart a random node instead of explicitly the one with the primary?

**Review by ywelsch — CHANGES_REQUESTED** [review]

File: server/src/test/java/org/elasticsearch/discovery/ClusterDisruptionIT.java (hunk 3 above)
Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/discovery/ClusterDisruptionIT.java]: Yep, I pushed https://github.com/elastic/elasticsearch/pull/39584/commits/ab65f4b14ae8af85708e8b4340fd72599546f803

File: server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java (hunk 2 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: I pushed https://github.com/elastic/elasticsearch/pull/39584/commits/6afb094f04d21f2f30c601a4beea9fa25de06c6c.

**Comment by dnhatn** [comment]
@ywelsch Thanks for looking. It's ready again.

File: server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java [hunk 4]
```diff
@@ -204,13 +203,23 @@ public String toString() {
...
-            primary.routingEntry());
-        // we are no longer the primary, fail ourselves and start over
-        primary.failShard(primaryFail, demotionFailure);
-        finishAsFailed(new RetryOnPrimaryException(primary.routingEntry().shardId(), primaryFail, demotionFailure));
+    private void onNoLongerPrimary(Exception failure) {
+        final boolean nodeIsClosing = failure instanceof NodeClosedException ||
+            (failure instanceof TransportException && "TransportService is closed stopped can't send request".equals(failure.getMessage()));
+        final String message;
+        if (nodeIsClosing) {
+            message = String.format(Locale.ROOT, "primary node [%s] is shutting down while failing replica shard", primary.routingEntry());
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: perhaps change to "node with primary [%s] is shutting ..."

Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: add a comment here as well that it's not necessary to fail shard as the node is shutting down anyway

**Review by ywelsch — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java (hunk 4 above)
Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: Pushed https://github.com/elastic/elasticsearch/pull/39584/commits/6b56fbcee0171e995a01ac7f1ba288963be44d41.

Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/support/replication/ReplicationOperation.java]: Added https://github.com/elastic/elasticsearch/pull/39584/commits/6b56fbcee0171e995a01ac7f1ba288963be44d41

**Comment by dnhatn** [comment]
@ywelsch Thanks!

**Comment by dnhatn** [comment]
@jpountz I have backported this to 6.6.2 in https://github.com/elastic/elasticsearch/commit/799491fb8c9dd41bdcdfbe5333c213eaeebb180a.

**Comment by dnhatn** [comment]
@jpountz @ywelsch I have reverted this change in 6.6.2 for we need to adjust the way we check if the node with primary is shutting down. It's fine if this does not make 6.6.2 (I've removed the label).

**Comment by jpountz** [comment]
Thanks for letting me know!
