### PR TITLE
[ES|QL]Allow AUTO_BUCKET to accept references created by EVAL as input to from and to

### LINKED ISSUE #104634: [ES|QL] Allow AUTO_BUCKET to accept variables as the third and fourth input parameters
### Description

This is a follow up issue to #102756.

Currently, AUTO_BUCKET can accept Strings as the third and fourth input parameters. After #102756, it allows DateTime. This is to allow variables defined in EVAL as its third and fourth input parameters.

Here is an example:
If the literal values are assigned to variables, and these variables are assigned as input parameter to the AUTO_BUCKET function, it failed.
curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{
  "query": "FROM sample_data | EVAL bucket_start = \"1985-07-09T00:00:00.000Z\" | EVAL bucket_end = \"2023-01-17T00:00:00Z\"  | EVAL bucket = AUTO_BUCKET (@timestamp, 24, bucket_start, bucket_end) "
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "verification_exception",
        "reason" : "Found 1 problem\nline 1:127: third argument of [AUTO_BUCKET (@timestamp, 24, bucket_start, bucket_end)] must be a constant, received [bucket_start]"
      }
    ],
    "type" : "verification_exception",
    "reason" : "Found 1 problem\nline 1:127: third argument of [AUTO_BUCKET (@timestamp, 24, bucket_start, bucket_end)] must be a constant, received [bucket_start]"
  },
  "status" : 400
}

However if the literal values are coded inside the AUTO_BUCKET function, it works fine.

curl -u elastic:password -X POST 'localhost:9200/_query?format=txt&pretty' -H 'Content-Type: application/json' '-d
{
  "query": "FROM sample_data | EVAL bucket = AUTO_BUCKET (@timestamp, 24, \"2023-01-17T00:00:00Z\", \"2024-01-17T00:00:00Z\")"
}
'
       @timestamp       |   client.ip   |event.duration |       message       |         bucket         
------------------------+---------------+---------------+---------------------+------------------------
2023-10-23T12:15:03.360Z|172.21.2.162   |3450233        |Connected to 10.1.0.3|2023-10-01T00:00:00.000Z
2023-10-23T12:27:28.948Z|172.21.2.113   |2764889        |Connected to 10.1.0.2|2023-10-01T00:00:00.000Z
2023-10-23T13:33:34.937Z|172.21.0.5     |1232382        |Disconnected         |2023-10-01T00:00:00.000Z
2023-10-23T13:51:54.732Z|172.21.3.15    |725448         |Connection error     |2023-10-01T00:00:00.000Z
2023-10-23T13:52:55.015Z|172.21.3.15    |8268153        |Connection error     |2023-10-01T00:00:00.000Z
2023-10-23T13:53:55.832Z|172.21.3.15    |5033755        |Connection error     |2023-10-01T00:00:00.000Z
2023-10-23T13:55:01.543Z|172.21.3.15    |1756467        |Connected to 10.1.0.1|2023-10-01T00:00:00.000Z

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves: #104634 

When a reference, created by EVAL, is provided to AUTO_BUCKET as input to from and to, to specify a time range, analyzer's verifier fails because a reference is not foldable, it is not a literal value.  However, PropagateEvalFoldables rule in logical plan optimizer is able to propagate the literal values into AUTO_BUCKET, and the inputs to AUTO_BUCKET will become foldable in the optimized plan the transformation, and the statement can be executed successfully and correctly.

Checking foldable at analyzer's verifier is too early for this case, and it can be deferred after all of the EVAL fodables are propagated, at the end of logical plan optimizer.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 1]
```diff
@@ -1384,4 +1389,32 @@ protected LogicalPlan rule(Aggregate aggregate) {
...
+    /**
+     * Verify that a {@link LogicalPlan} can be executed.
+     *
+     * @param plan The logical plan to be verified
+     * @return a collection of verification failures; empty if and only if the plan is valid
+     *
+     * The following verifications on an optimized logical plan are supported:
+     * 1. EVAL with AUTO_BUCKET expression, its from and to should be foldable
+     */
+    LogicalPlan verify(LogicalPlan plan) throws VerificationException {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1402]: bikeshed:
```suggestion
    LogicalPlan verifyOptimized(LogicalPlan plan) throws VerificationException {
```
Also, we could move this into the Verifier and call it from `EsqlSession.optimizedPlan` to make sure that all verification code (and related stuff) is in one place - but keeping it here is probably fine for now, too.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java [hunk 2]
```diff
@@ -191,4 +193,16 @@ public String toString() {
...
+        return verifyOptimizedPlan;
+    }
+
+    public void setVerifyOptimizedPlan() {
+        verifyOptimizedPlan = true;
+    }
+
+    public TypeResolution verifyOptimizedPlan() {
+        return TypeResolution.TYPE_RESOLVED;
+    }
```
Comment (alex-spies) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java:207]: nit:
```suggestion
    /**
     * Some expressions need additional verifications that can only be performed after optimization.
    */
    public TypeResolution verifyAfterOptimization() {
        return TypeResolution.TYPE_RESOLVED;
    }
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 3]
```diff
@@ -1384,4 +1389,32 @@ protected LogicalPlan rule(Aggregate aggregate) {
...
+        Collection<Failure> failures = new LinkedHashSet<>();
+        plan.forEachUp(p -> {
+            if (p instanceof Eval) {
+                p.forEachExpression(e -> {
+                    if (e.getVerifyOptimizedPlan()) {
+                        Expression.TypeResolution resolution = e.verifyOptimizedPlan();
+                        if (resolution.unresolved()) failures.add(fail(e, resolution.message()));
+                    }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1410]: I don't think `e.getVerifyOptimizedPlan` (and its setter counterpart) are needed; this should do the same:

```suggestion
                    Expression.TypeResolution resolution = e.verifyOptimizedPlan();
                    if (resolution.unresolved()) failures.add(fail(e, resolution.message()));
```
(Per default, `e.verifyOptimizedPlan` already returns `TypeResolution.TYPE_RESOLVED`.)

**Review by alex-spies — COMMENTED** [review]
Thanks @fang-xing-esql !

This runs into a tricky situation as our current query planning does not account for verifications that need to be done after optimization.

I agree that adding a post-optimization check to the expressions is likely necessary; since this requires refactoring our expressions, I think this needs @costin 's input.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec [hunk 4]
```diff
@@ -326,6 +326,18 @@ COUNT(*):long            | bucket:date
 1                        | 1999-01-01T00:00:00.000Z
 ;
 
+autoBucketYearInAggRefs
+FROM employees
+| WHERE hire_date >= "1999-01-01T00:00:00Z"
+| EVAL bucket_start =  "1999-01-01T00:00:00Z"
+| EVAL bucket_end = NOW()
+| EVAL bucket = AUTO_BUCKET(hire_date, 5, bucket_start, bucket_end)
```
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec:334]: Ergh, of course the `VerifierTests` only do pre-optimization verification - so we'd need to extend them a little, I'm afraid.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/math/AutoBucket.java [hunk 5]
```diff
@@ -199,21 +199,12 @@ private TypeResolution resolveType(BiFunction<Expression, TypeResolutions.ParamO
...
-        if (resolution.unresolved()) {
-            return resolution;
-        }
-
-        resolution = checkThirdAndForth.apply(to, FOURTH);
-        if (resolution.unresolved()) {
-            return resolution;
-        }
-        return isFoldable(to, sourceText(), FOURTH);
+        return checkThirdAndForth.apply(to, FOURTH);
```
[the remark this answers is not in the document]
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/math/AutoBucket.java:206]: This will be included in the next commit.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec (hunk 4 above)
[the remark this answers is not in the document]
Comment (fang-xing-esql) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec]: Thank you for the suggestion! A couple of verification tests are included in the LogicalPlanOptimizerTests.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java [hunk 6]
```diff
@@ -69,6 +69,8 @@ public String toString() {
     private Expression lazyCanonical = null;
     private AttributeSet lazyReferences = null;
 
+    private boolean verifyOptimizedPlan = false;
```
[the remark this answers is not in the document]
Comment (fang-xing-esql) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java]: The changes to this class are reverted from the last commit, after discussing with @costin , we'd like to reduce the scope of this PR to auto_bucket only, and don't want to change this class as you suggested.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java (hunk 2 above)
Comment (fang-xing-esql) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/Expression.java]: The changes to this class are reverted in the last commit.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 3 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java]: After reverting the changes to Expression.java in the last commit, this piece of code is outdated.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/math/AutoBucket.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/math/AutoBucket.java:206]: Super low priority, though - and since it's cosmetic, include this at your own discretion :)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 7]
```diff
@@ -1384,4 +1392,34 @@ protected LogicalPlan rule(Aggregate aggregate) {
             return plan;
         }
     }
+
+    /**
+     * Verify that a {@link LogicalPlan} can be executed.
+     *
+     * @param plan The logical plan to be verified.
+     * @return a collection of verification failures; empty if and only if the plan is valid.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1400]: This shouldn't be @return; I'd just mention this throws a VerificationException.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 8]
```diff
@@ -1384,4 +1392,34 @@ protected LogicalPlan rule(Aggregate aggregate) {
...
+     *
+     * The following verifications on an optimized logical plan are supported, it can be extended to other situations:
+     * 1. AUTO_BUCKET expression's from and to should be foldable.
+     */
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1404]: I'd remove this paragraph - this can already be seen in the code.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1405]: (Moving this to the Verifier is very matter of taste - this location is also fine IMO.)

**Review by alex-spies — COMMENTED** [review]
In general looks good and I agree with the scope-down; it makes our optimizer a bit "weird" in that it also does some verification, but we can refactor this later if need be.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 1 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java]: Changed the name, I'll leave it here for now, as the Verifier we have is under analysis, if the optimized plan needs more verifications, we can have it in a dedicated place.

**Comment by fang-xing-esql** [comment]
> In general looks good and I agree with the scope-down; it makes our optimizer a bit "weird" in that it also does some verification, but we can refactor this later if need be.

Thank you for reviewing! All of the comments are addressed in the last commit.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 9]
```diff
@@ -1384,4 +1392,31 @@ protected LogicalPlan rule(Aggregate aggregate) {
             return plan;
         }
     }
+
+    /**
+     * Verify that a {@link LogicalPlan} can be executed.
+     *
+     * @param plan The logical plan to be verified.
+     * @throws VerificationException if and only if the plan is valid.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:1400]: Typo: should be "invalid".

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec [hunk 10]
```diff
@@ -326,6 +326,32 @@ COUNT(*):long            | bucket:date
...
+COUNT(*):long            | bucket:date
+1                        | 1999-01-01T00:00:00.000Z
+;
+
+autoBucketYearInAggConstRefsRename#[skip:-8.12.99, reason:date type is supported in 8.13]
+FROM employees
+| WHERE hire_date >= "1999-01-01T00:00:00Z"
+| EVAL bucket_start =  "1999-01-01T00:00:00Z"
+| EVAL bucket_end = NOW()
+| RENAME bucket_end as be, bucket_start as bs
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec:347]: ++ to the additional test case.

**Review by alex-spies — APPROVED** [review]
LGTM!

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec [hunk 11]
```diff
@@ -326,6 +326,32 @@ COUNT(*):long            | bucket:date
...
+| sort bucket;
+
+COUNT(*):long            | bucket:date
+1                        | 1999-01-01T00:00:00.000Z
+;
+
+autoBucketYearInAggConstRefsRename#[skip:-8.12.99, reason:date type is supported in 8.13]
+FROM employees
+| WHERE hire_date >= "1999-01-01T00:00:00Z"
+| EVAL bucket_start =  "1999-01-01T00:00:00Z"
```
Comment (costin) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec:345]: Please add another test that assembles the string through concat function.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java [hunk 12]
```diff
@@ -91,7 +99,7 @@ public LogicalPlanOptimizer(LogicalOptimizerContext optimizerContext) {
     }
 
     public LogicalPlan optimize(LogicalPlan verified) {
-        return verified.optimized() ? verified : execute(verified);
+        return verified.optimized() ? verifyOptimized(verified) : verifyOptimized(execute(verified));
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java:102]: `return verifyOptimized(verified.optimized() ? verified : execute(verified))`

**Review by costin — APPROVED** [review]
LGTM. Pinging kibana in case the new exception package change affects them.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec (hunk 11 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec]: Added a couple of more tests here.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec (hunk 10 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/date.csv-spec:374]: Added a couple of more tests here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 9 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java]: Thanks for catching it!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java (hunk 12 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java]: Done.

**Comment by fang-xing-esql** [comment]
> LGTM. Pinging kibana in case the new exception package change affects them.

Thank you for reviewing! The comments are addressed in the last commit.
