### PR TITLE
EQL: Fix translation of bool fields

### LINKED ISSUE #63693: EQL: bool field inside where clauses causes the query to fail
Performing a query against a boolean field ends up with an exception:

```
GET .ds-logs-endpoint.events.process-*/_eql/search
{
  "size": 1,
  "query": "process where process.code_signature.trusted == true"
}
# verification_exception (Unknown Column)
​
GET auditbeat-*/_eql/search
{
  "size": 1,
  "query": "process where process.code_signature.trusted == true"
}
# "type" : "ql_illegal_argument_exception",
# "reason" : "Don't know how to translate FieldAttribute process.code_signature.trusted{f}#2112886"
​
GET auditbeat-*/_eql/search
{
  "size": 0,
  "query": "process where process.code_signature.trusted == true"
}

```

The issue seems to be related in handling bool fields inside the where clause.

### PR DESCRIPTION
**Pull request by costin**
This commit fixes two issues in dealing with bool fields in EQL:
- avoid simplifications of field == true expressions
- adding comparison to clauses on fields missing logic (where bool)

Fix #63693

### CODE REVIEW

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java [hunk 1]
```diff
@@ -99,7 +104,34 @@ public LogicalPlan optimize(LogicalPlan verified) {
...
+
+    private static class AddMissingEquals extends OptimizerRule<Filter> {
+
+        @Override
+        protected LogicalPlan rule(Filter filter) {
+            // check the condition itself
+            Expression condition = replaceRawBoolFieldWithEquals(filter.condition());
+            // otherwise look for binary logic
+            if (condition == filter.condition()) {
+                condition = condition.transformUp(b ->
```
Comment (matriv) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java:118]: Shouldn't this be enough? why do we need to check the top level separately?

**Review by matriv — APPROVED** [review]
LGTM, left a question though.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java:118]: for cases such as `where bool` which have no other expression specified.

Comment (matriv) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java:118]: I meant, that the transformUp would also catch this case, no?

File: x-pack/plugin/eql/src/test/resources/queryfolder_tests.txt [hunk 2]
```diff
@@ -145,6 +145,49 @@ process where endsWith(user_name, "c")
...
+process where bool
+;
+{"bool":{"must":[
+{"term":{"bool":{"value":true,
+;
+
+fieldNoEqualsInExpression
+process where length(file_name) > 0 and bool
+;
+{"bool":{"must":[
```
Comment (astefan) [inline x-pack/plugin/eql/src/test/resources/queryfolder_tests.txt:158]: Can you add more from the actual query DSL. The fact that there is a `bool` `must` and a `term` with `true` doesn't mean the actual query is entirely correct, more like how we do it with SQL (where the entire query is checked for correctness). For `term` at least, there is the new parameter that Mark H. added that makes it case insensitive or not.

**Review by astefan — APPROVED** [review]
LGTM, but I would like to see the tests match a more complete query dsl. Left a comment about this.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/optimizer/Optimizer.java:118]: No because it filters on `BinaryLogic`.

File: x-pack/plugin/eql/src/test/resources/queryfolder_tests.txt (hunk 2 above)
Comment (costin) [reply x-pack/plugin/eql/src/test/resources/queryfolder_tests.txt:158]: I'm not a fan of comprehensive query tests since any optimization or change breaks the test. For example the bool must is separate since the term comparison gets applied on process as well.
The aim of this test is to check that the bool field is compared not to what. So checking the parameter for case insensitivity (which btw, does appear only if it gets set) goes beyond the scope tested here.
