### PR TITLE
Fix SearchExecutionContextTests.testFielddataLookupSomtimesLoop

### LINKED ISSUE #136766: [CI] SearchExecutionContextTests testFielddataLookupSometimesLoop failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11247 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/576txycivy2ii)
- [elasticsearch-periodic-platform-support #11207 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/yjypsbyu54wzy)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.index.query.SearchExecutionContextTests.testFielddataLookupSometimesLoop" -Dtests.seed=8126445C5EB564A5 -Dtests.locale=bs-BA -Dtests.timezone=Pacific/Rarotonga -Druntime.java=25
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.index.query.SearchExecutionContextTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testFielddataLookupSometimesLoop'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.IllegalArgumentException: Cyclic dependency detected while resolving runtime fields: 1 -> 2 -> 3 -> 4 -> 4
```

**Issue Reasons:**
- [8.19] 2 failures in test testFielddataLookupSometimesLoop (0.9% fail rate in 227 executions)
- [8.19] 2 failures in pipeline elasticsearch-periodic-platform-support (25.0% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by chrisparrinello**
Closes #136766. 

The test creates a cycle in runtime fields that is broken if the doc with `docId == 0`'s field `4` is accessed. The first part of the test attempts to only fetch the document with `indexed_field` `first` which should not fail because the runtime fields would not have a loop since `first` should have `docId == 0`. The second part fetches all of the documents which should fail since all of the documents are fetched and the runtime fields are calculated. 

The random seed used in the failing test results in the document with `first` actually getting a `docId` of 1 causing the test to fail. Since we can't depend on `docId` to break the cycle in the runtime fields, changes were made to be able to use `indexed_field == "first"` to break the cycle in the first part of the test.

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/query/SearchExecutionContextTests.java [hunk 1]
```diff
@@ -223,18 +222,27 @@ public void testFielddataLookupTerminatesInLoop() {
...
-            // simulate a runtime field cycle in the second doc: 1: doc['2'] 2: doc['3'] 3: doc['4'] 4: doc['4']
+        // create this field so we can use it to make sure we're escaping the loop on only the "first" document
+        var concreteField = new KeywordFieldMapper.KeywordFieldType("indexed_field", true, true, Collections.emptyMap());
+
+        // simulate a runtime field cycle in the second doc: 1: doc['2'] 2: doc['3'] 3: doc['4'] 4: doc['4']
+        var runtimeFields = List.of(
             runtimeField("1", leafLookup -> leafLookup.doc().get("2").get(0).toString()),
             runtimeField("2", leafLookup -> leafLookup.doc().get("3").get(0).toString()),
             runtimeField("3", leafLookup -> leafLookup.doc().get("4").get(0).toString()),
             runtimeField("4", (leafLookup, docId) -> {
```
Comment (benchaplin) [inline server/src/test/java/org/elasticsearch/index/query/SearchExecutionContextTests.java]: Can we remove docId?

File: server/src/test/java/org/elasticsearch/index/query/SearchExecutionContextTests.java [hunk 2]
```diff
@@ -776,8 +784,8 @@ private static List<String> collect(String field, SearchExecutionContext searchE
     private static List<String> collect(String field, SearchExecutionContext searchExecutionContext, Query query) throws IOException {
         List<String> result = new ArrayList<>();
         try (Directory directory = newDirectory(); RandomIndexWriter indexWriter = new RandomIndexWriter(random(), directory)) {
-            indexWriter.addDocument(List.of(new StringField("indexed_field", "first", Field.Store.NO)));
-            indexWriter.addDocument(List.of(new StringField("indexed_field", "second", Field.Store.NO)));
+            indexWriter.addDocument(List.of(new KeywordField("indexed_field", "first", Field.Store.YES)));
```
Comment (benchaplin) [inline server/src/test/java/org/elasticsearch/index/query/SearchExecutionContextTests.java:787]: You sure this doesn't mess with other tests that use this method? I would run `@Repeat` on the suite to be sure.

**Review by benchaplin — APPROVED** [review]
Nice find!

File: server/src/test/java/org/elasticsearch/index/query/SearchExecutionContextTests.java (hunk 1 above)
Comment (chrisparrinello) [reply server/src/test/java/org/elasticsearch/index/query/SearchExecutionContextTests.java]: Yes. Will do.

File: server/src/test/java/org/elasticsearch/index/query/SearchExecutionContextTests.java (hunk 2 above)
Comment (chrisparrinello) [reply server/src/test/java/org/elasticsearch/index/query/SearchExecutionContextTests.java:787]: I'm running it now. 10k iterations pass without problems. I'm going to push it until I run OOM.

Comment (chrisparrinello) [reply server/src/test/java/org/elasticsearch/index/query/SearchExecutionContextTests.java:787]: At about 15k I start getting OOM and Heap errors which I can't reproduce on the seeds if I run them standalone so I think this is good to go.

**Comment by seanzatzdev** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/157692)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
