### PR TITLE
Try to Optimize error handling after lazy rollovers #108838

### LINKED ISSUE #108838: Optimize error handling after lazy rollovers
Currently, we're looping over all the requests in the bulk request for _each_ failed lazy rollover ([here](https://github.com/elastic/elasticsearch/blob/a2008bd190ec05db4cbd6e3cafd7d5850add647f/server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java#L481), and once https://github.com/elastic/elasticsearch/pull/108108 is merged, we'll do it in `BulkOperation` too). While this is probably around O(n) in practice, it's technically O(n^2), if each document was destined to a different failure store and each rollover failed.

A better alternative would be to collect all the failed rollovers and traverse the documents one time.

### PR DESCRIPTION
**Pull request by Kushal-Dalasaniya**
Hi, I am trying to Optimize error handling after lazy rollovers and resolve #108838 issue

### CODE REVIEW

**Comment by nielsbauman** [comment]
buildkite test this

**Review by nielsbauman — CHANGES_REQUESTED** [review]
Hi @Kushal-Dalasaniya, thank you for taking the time to open a PR with Elasticsearch! I left some comments on your approach. Could you take a look at those?

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 1]
```diff
@@ -394,24 +397,25 @@ public void onResponse(RolloverResponse result) {
 
                 @Override
                 public void onFailure(Exception e) {
-                    failRequestsWhenPrerequisiteActionFailed(dataStream, bulkRequest, responses, e);
```
[the remark this answers is not in the document]
Comment (Kushal-Dalasaniya) [reply server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java:397]: Hi @nielsbauman,

Thank you for pointing that out. In your suggested solution, we set exceptions in the BulkRequest for indices. However, since we have separate sets for dataStreamsToBeRolledOver and failureStoresToBeRolledOver, I believe the issue you mentioned may not be present in the current code.

That said, I could be mistaken, and if so, I'd appreciate your guidance on the changes I need to make.

**Comment by Kushal-Dalasaniya** [comment]
Hi @nielsbauman,

Thank you for the suggestion. I've implemented your recommended changes. Please take a look when you have a chance.

**Comment by nielsbauman** [comment]
Hi @Kushal-Dalasaniya, thanks for iterating on this. I just pushed some changes to make the code align more with what I had in mind. I'll ask someone else on my team to review as well.

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 2]
```diff
@@ -342,29 +342,36 @@ protected void createMissingIndicesAndIndexData(
...
         // Optimizing when there are no prerequisite actions
         if (indicesToAutoCreate.isEmpty() && dataStreamsToBeRolledOver.isEmpty() && failureStoresToBeRolledOver.isEmpty()) {
-            executeBulk(task, bulkRequest, startTimeNanos, listener, executor, responses, Map.of());
+            executeBulk(task, bulkRequest, startTimeNanos, listener, executor, responses);
             return;
         }
-        final Map<String, IndexNotFoundException> indicesThatCannotBeCreated = new HashMap<>();
+        Map<String, Exception> indicesExceptions = new ConcurrentHashMap<>();
+        Map<String, Exception> dataStreamExceptions = new ConcurrentHashMap<>();
+        Map<String, Exception> failureStoreExceptions = new ConcurrentHashMap<>();
```
Comment (nielsbauman) [inline server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java:350]: To avoid the scenario where there are two requests in a `BulkRequest` where one goes to a data stream that is marked for rollover and another goes to that data stream's failure store that is marked for rollover, and both rollovers fail, we have two separate maps. If we'd have one map, one of those failed rollovers would overwrite the other in the map (because the key (i.e. data stream name) would be the same).

**Review by jbaiera — APPROVED** [review]
LGTM! Left a small nit but otherwise looks good to go

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 3]
```diff
@@ -431,26 +439,52 @@ public void onResponse(RolloverResponse result) {
...
+                    exception = dataStreamExceptions.get(request.index());
+                }
+            }
+            if (exception == null) {
+                continue;
+            }
+            var failureStoreStatus = request instanceof IndexRequest ir && ir.isWriteToFailureStore()
+                ? IndexDocFailureStoreStatus.FAILED
+                : IndexDocFailureStoreStatus.NOT_APPLICABLE_OR_UNKNOWN;
+            var failure = new BulkItemResponse.Failure(request.index(), request.id(), exception, failureStoreStatus);
```
Comment (nielsbauman) [inline server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java:485]: @jbaiera I copied this from
https://github.com/elastic/elasticsearch/blob/f7ba89bcb1f7f059542dcccd83c01d06ed613dfa/server/src/main/java/org/elasticsearch/action/bulk/BulkOperation.java#L765-L768
(as per https://github.com/elastic/elasticsearch/pull/112816)
Can you quickly re-check these changes with that merged PR in mind? I think everything is ok, but would like you to have a quick check to be sure.

File: server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java [hunk 4]
```diff
@@ -431,26 +439,52 @@ public void onResponse(RolloverResponse result) {
...
+            responses.set(i, BulkItemResponse.failure(i, request.opType(), failure));
+            bulkRequest.requests.set(i, null);
```
Comment (nielsbauman) [inline server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java:487]: @jbaiera Secondly, I realized we don't track APM metrics when we run into a failure here. I think we'll want to add that, right? If you agree, I'll open an issue so we can do it in a separate PR.

Comment (jbaiera) [reply server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java:487]: If we've never tracked the failures here before then yeah, lets open a new issue for that.

**Review by jbaiera — APPROVED** [review]

**Comment by nielsbauman** [comment]
@elasticmachine update branch

**Comment by nielsbauman** [comment]
buildkite test this

**Review by nielsbauman — APPROVED** [review]

**Comment by nielsbauman** [comment]
Hi @Kushal-Dalasaniya, would you maybe be so kind as to go to the Github Actions page of your fork (https://github.com/Kushal-Dalasaniya/elasticsearch/actions) and manually disable all actions there? I'm getting daily emails that they're failing but I'm not allowed to disable them on your repo. They don't need to run on forks, so we're going to update them to only run on our main repo, but for the time being it would be great if you could disable them on your fork :). Much appreciated!
