### PR TITLE
[ML][Inference] Adds validations for model PUT

### LINKED ISSUE #51354: [ML] Inference PUT: 500 returned when `trained_model.ensemble.trained_models`  is an empty array
Spotted in 7.6.0

When creating a new trained model, if `trained_model.ensemble.trained_models`  is an empty array, ES responds with a `500`:

**Request:**
```
PUT _ml/inference/foo
{
  "input": {
    "field_names": "fieldy_mc_fieldname"
  },
  "definition": {
    "trained_model": {
      "ensemble": {
        "feature_names": [],
        "trained_models": []
      }
    }
  }
}
```

**Response:**
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "no_such_element_exception",
        "reason" : "No value present"
      }
    ],
    "type" : "no_such_element_exception",
    "reason" : "No value present"
  },
  "status" : 500
}
```

**ES log output:**
[es_log_output.log](https://github.com/elastic/elasticsearch/files/4103563/es_log_output.log)

**Expected behavior:** 
Return a `400` and a meaningful error message that explains what went wrong while parsing the trained model configuration.

### PR DESCRIPTION
**Pull request by benwtrent**
Adds validations making sure that

* `input.field_names` is not empty
* `ensemble.trained_models` is not empty
* `tree.feature_names` is not empty

closes https://github.com/elastic/elasticsearch/issues/51354

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/ensemble/Ensemble.java [hunk 1]
```diff
@@ -250,6 +250,10 @@ public int hashCode() {
 
     @Override
     public void validate() {
+        if (this.models.isEmpty()) {
+            throw ExceptionsHelper.badRequestException("[trained_models] must not be empty");
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/ensemble/Ensemble.java]: Would it make sense to use `TRAINED_MODELS.getPreferredName()` here rather than literal?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/tree/Tree.java [hunk 2]
```diff
@@ -253,6 +253,9 @@ public static Builder builder() {
 
     @Override
     public void validate() {
+        if (featureNames.isEmpty()) {
+            throw ExceptionsHelper.badRequestException("[feature_names] must not be empty for tree model");
```
Comment (przemekwitek) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/inference/trainedmodel/tree/Tree.java]: Would it make sense to use `FEATURE_NAMES.getPreferredName()` here rather than literal?

**Review by przemekwitek — APPROVED** [review]
LGTM
