### PR TITLE
SQL: Fix issue with aliased subqueries and GROUP BY

### LINKED ISSUE #69263: SQL: fail to aggregate within aliased subquery
The following two queries work as expected:
* `SELECT * FROM (SELECT author FROM library GROUP BY author)` and 
* `SELECT * FROM (SELECT author FROM library) AS subquery`.

However, when aliasing the subquery with agg,
* `SELECT * FROM (SELECT author FROM library GROUP BY author) AS subquery`, 
 
the following exception triggers:

```
org.elasticsearch.xpack.sql.SqlIllegalArgumentException: Cannot find group [author]
	at org.elasticsearch.xpack.sql.util.Check.notNull(Check.java:37)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.fold(QueryFolder.java:604)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:414)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:226)
	at org.elasticsearch.xpack.ql.tree.Node.lambda$transformUp$11(Node.java:198)
	at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:192)
	at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:198)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:877)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:873)
	at org.elasticsearch.xpack.ql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:83)
	at org.elasticsearch.xpack.ql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:159)
	at org.elasticsearch.xpack.ql.rule.RuleExecutor.execute(RuleExecutor.java:131)
	at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:112)
	at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:39)
	at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:29)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:161)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:157)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:145)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117)
	at org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$4(IndexResolver.java:299)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:117)
	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:100)
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:170)
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:164)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:165)
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:167)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$0(TransportFieldCapabilitiesAction.java:78)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:93)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:87)
	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:100)
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:170)
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:164)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:165)
	at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:167)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesIndexAction$AsyncShardsAction$1.handleResponse(TransportFieldCapabilitiesIndexAction.java:283)
	at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesIndexAction$AsyncShardsAction$1.handleResponse(TransportFieldCapabilitiesIndexAction.java:273)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1165)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1243)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1223)
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:41)
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:32)
	at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:16)
	at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47)
	at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:728)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)


```

### PR DESCRIPTION
**Pull request by matriv**
Previously, when a subquery was used with an alias in combination with
a nested GROUP BY, the collapsing of the nested queries into a flattened
`Aggregate` query, lead to wrong attribute qualifier on the external
projection, which was still referencing the removed subquery. e.g.:

For the following query:
```
SELECT languages FROM (
    SELECT languages FROM test_emp GROUP BY languages
) AS subquery
```
The `languages` of the top level SELECT, was qualified with `subquery`
which was removed during the flattening optimisation leading to
Exception of not being able to resolve the referenced group:
`test_emp.languages`.

Fix this behaviour by introducing a new rule which precedes the
`PruneSubqueryAliases` rules and updates the `qualifier` for the
`FieldAttributes`.

Fixes: #69263

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 1]
```diff
@@ -1216,7 +1217,36 @@ private Expression implicitCast(Expression e) {
...
+            if (plan.child() instanceof SubQueryAlias) {
+                SubQueryAlias a = (SubQueryAlias) plan.child();
+                return plan.transformExpressionsDown(FieldAttribute.class, f -> {
+                   if (f.qualifier() != null && f.qualifier().equals(a.alias())) {
+                       // Find the underlying concrete relation (EsIndex) and its name as the new qualifier
+                       String newQualifier = null;
+                       List<LogicalPlan> children = a.collectFirstChildren(p -> p instanceof EsRelation);
+                       if (children.isEmpty() == false) {
+                           newQualifier = ((EsRelation) children.get(0)).index().name();
+                       }
```
Comment (bpintea) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:1233]: Shouldn't an `else` just return `f` here? Otherwise it seems to strip the qualifier.
Not sure if it can happen (maybe when ref'ing an `UnresolvedRelation`?), but might be safer.

**Comment by costin** [comment]
Since this occurs only with `GROUP BY` I think adding the subquery name as a qualifier alias might work better.
That is allow `subquery.a` to resolve to `test_emp.a` by resolving `subquery` to `test_emp`. 
The subquery qualifier is correct - removing/replacing is one option however the downside is that needs to occur across attributes; remembering the aliasing preserves the original tree and the overall relationship since this seems to impact only grouping.

However if it probes tricky, I'm fine with the current approach since after the attributes have been resolved, there's no need to keep the qualifiers around...
I'd like also a couple of tests with aliased subfields in the named subqueries.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:1232]: Yep, makes sense, It shouldn't happened, but I fixed it to return f instead of stripping completely the qualifier which could hide some other issue in the future.

**Comment by matriv** [comment]
@costin Thx! I've already tried to manipulate the Aliases so that the resolution would be done with the existing code but failed. I'll try spending some more time on it, since this approach is "cleaner" than my current one.

**Review by bpintea — APPROVED** [review]
lgtm, but I guess you'll update it.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java [hunk 2]
```diff
@@ -1216,7 +1217,33 @@ private Expression implicitCast(Expression e) {
...
+    public static class ReplaceSubQueryAliases extends AnalyzerRule<UnaryPlan> {
+
+        @Override
+        protected LogicalPlan rule(UnaryPlan plan) {
+            if (plan.child() instanceof SubQueryAlias) {
+                SubQueryAlias a = (SubQueryAlias) plan.child();
+                return plan.transformExpressionsDown(FieldAttribute.class, f -> {
+                   if (f.qualifier() != null && f.qualifier().equals(a.alias())) {
+                       // Find the underlying concrete relation (EsIndex) and its name as the new qualifier
+                       List<LogicalPlan> children = a.collectFirstChildren(p -> p instanceof EsRelation);
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:1229]: Wondering if you have any better ideas for getting only the first child, and not first children out of which to extract the first. Not a biggie, though.

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 2 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:1229]: Those methods are generic since they reside on the `Node` superclass. Creating a `collectFirstChild` method on `UnaryPlan` that just returns `children.get(0)` doesn't make much of an improvement imho.

**Comment by matriv** [comment]
@costin I tried a bit more to somehow add aliases so that the FieldAttributes resolves to the underlying index name but couldn't achieve it. I think this needs some bigger refactoring, and we anyway need to "look ahead" and see that the current plan's child is a `SubqueryAlias` which is what we already do in this PR's approach.

I'd say to move fwd with this solution, what do you think?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java (hunk 2 above)
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Analyzer.java:1229]: I think the search should be for `Relation` alone.

**Review by costin — APPROVED** [review]
@matriv thanks - fine by me.
Could you please add some tests for inline queries that use subqueries without `FROM`:
```
SELECT int FROM (    
	SELECT int FROM (        
		SELECT 1 AS int) 
	AS subq1) 
AS subq2;
```
