### PR TITLE
Fix Local Translog Recovery not Updating Safe Commit in Edge Case

### LINKED ISSUE #57010: ReplicaShardAllocatorIT#testFullClusterRestartPerformNoopRecovery failed
**Build scan**: https://gradle-enterprise.elastic.co/s/hdysqr5ca43ae

**Repro line**:

` ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.gateway.ReplicaShardAllocatorIT.testFullClusterRestartPerformNoopRecovery" -Dtests.seed=4D289CA066996995 -Dtests.security.manager=true -Dtests.locale=en-MT -Dtests.timezone=Asia/Harbin -Dcompiler.java=14 -Druntime.java=11`

**Reproduces locally?**:

YES! Not every time tho, but definitely at least once.

**Applicable branches**:

`master`

**Failure history**:

Looks  very rare, only two failures (both PR builds) in the last 90 days:

https://build-stats.elastic.co/goto/7bfc8e670dbde7b97b0f42eb0d485748

**Failure excerpt**:

```

org.elasticsearch.gateway.ReplicaShardAllocatorIT > testFullClusterRestartPerformNoopRecovery FAILED |  
-- | --
  | java.lang.AssertionError: |  
  | Expected: an empty collection |  
  | but: <[file (name [_0.si], reused [false], length [372], recovered [372]), file (name [_3.si], reused [false], length [372], recovered [372]), file (name [_1.cfe], reused [false], length [426], recovered [426]), file (name [_1.si], reused [false], length [372], recovered [372]), file (name [_2.si], reused [false], length [372], recovered [372]), file (name [_0.cfs], reused [false], length [9459], recovered [9459]), file (name [_5.cfs], reused [false], length [2707], recovered [2707]), file (name [_2.cfs], reused [false], length [2811], recovered [2811]), file (name [_4.cfe], reused [false], length [426], recovered [426]), file (name [_3.cfe], reused [false], length [426], recovered [426]), file (name [segments_4], reused [false], length [769], recovered [769]), file (name [_1.cfs], reused [false], length [6760], recovered [6760]), file (name [_0.cfe], reused [false], length [426], recovered [426]), file (name [_2.cfe], reused [false], length [426], recovered [426]), file (name [_3.cfs], reused [false], length [3457], recovered [3457]), file (name [_5.cfe], reused [false], length [426], recovered [426]), file (name [_4.cfs], reused [false], length [2694], recovered [2694]), file (name [_4.si], reused [false], length [372], recovered [372]), file (name [_5.si], reused [false], length [372], recovered [372])]> |  
  | at __randomizedtesting.SeedInfo.seed([4D289CA066996995:A48B015963175D36]:0) |  
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  | at org.junit.Assert.assertThat(Assert.java:956) |  
  | at org.junit.Assert.assertThat(Assert.java:923) |  
  | at org.elasticsearch.gateway.ReplicaShardAllocatorIT.assertNoOpRecoveries(ReplicaShardAllocatorIT.java:378) |  
  | at org.elasticsearch.gateway.ReplicaShardAllocatorIT.testFullClusterRestartPerformNoopRecovery(ReplicaShardAllocatorIT.java:234) |  
  | REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.gateway.ReplicaShardAllocatorIT.testFullClusterRestartPerformNoopRecovery" -Dtests.seed=4D289CA066996995 -Dtests.security.manager=true -Dtests.locale=en-MT -Dtests.timezone=Asia/Harbin -Dcompiler.java=14 -Druntime.java=11 |  
  |  

```

### PR DESCRIPTION
**Pull request by original-brownbear**
In case the local checkpoint in the latest commit is less
than the last processed local checkpoint we would recover
0 ops and hence not commit again.
This would lead to the logic in `IndexShard#recoverLocallyUpToGlobalCheckpoint`
not seeing the latest local checkpoint when it reload the safe commit from the store
and thus cause inefficient recoveries because the recoveries would work from a
lower than possible local checkpoint.

Closes #57010

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 1]
```diff
@@ -485,11 +486,11 @@ private void recoverFromTranslogInternal(TranslogRecoveryRunner translogRecovery
         // note: if opsRecovered == 0 and we have older translogs it means they are corrupted or 0 length.
         assert pendingTranslogRecovery.get() : "translogRecovery is not pending but should be";
         pendingTranslogRecovery.set(false); // we are good - now we can commit
+        logger.trace(() -> new ParameterizedMessage(
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:489]: Adjusted this because it's called more often now and `translog.currentFileGeneration()` actually does lock and create a `ReleaseableLock` instance

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 2]
```diff
@@ -485,11 +486,11 @@ private void recoverFromTranslogInternal(TranslogRecoveryRunner translogRecovery
...
+                "flushing post recovery from translog: ops recovered [{}], current translog generation [{}]",
+                opsRecovered, translog.currentFileGeneration()));
+        flush(false, true);
         if (opsRecovered > 0) {
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:493]: I kept this condition around the external refresh triggered here. Not sure if that optimization is necessary now to be honest, but removing it breaks a large number of unit tests that would now see two refreshes instead of one (since the flush also refreshes)

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java [hunk 3]
```diff
@@ -1021,8 +1021,8 @@ private void finish() {
                     assertNull(onFailure.get());
                     assertThat(getTranslog(indexShard).getGeneration().translogFileGeneration,
                         // if rollback happens we roll translog twice: one when we flush a commit before opening a read-only engine
-                        // and one after replaying translog (upto the global checkpoint); otherwise we roll translog once.
-                        either(equalTo(translogGen + 1)).or(equalTo(translogGen + 2)));
+                        // and two or three times after replaying translog (upto the global checkpoint); otherwise we roll translog once.
```
Comment (original-brownbear) [inline server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:1024]: We discussed this on AoN, we're now potentially rolling the translog redundantly one additional time during flush.

Comment (ywelsch) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:1024]: I looked at this, and think we can remove the redundant rollover with the following:

```
diff --cc server/src/main/java/org/elasticsearch/index/translog/Translog.java
index 0a8e38816fa,0a8e38816fa..60375d5b485
--- a/server/src/main/java/org/elasticsearch/index/translog/Translog.java
+++ b/server/src/main/java/org/elasticsearch/index/translog/Translog.java
@@@ -1615,13 -1615,13 +1615,17 @@@ public class Translog extends AbstractI
      }
  
      /**
--     * Roll the current translog generation into a new generation. This does not commit the
++     * Roll the current translog generation into a new generation if it's not empty. This does not commit the
       * translog.
       *
       * @throws IOException if an I/O exception occurred during any file operations
       */
      public void rollGeneration() throws IOException {
          syncBeforeRollGeneration();
++        // no need to roll over when it's empty
++        if (current.totalOperations() == 0) {
++            return;
++        }
          try (Releasable ignored = writeLock.acquire()) {
              ensureOpen();
              try {
```

The reason we have the rollover in the first place is to make sue we no longer need to hold on to certain ops, or that we do not mix ops from different terms in the same generation. For  an empty translog, neither is necessary.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 4]
```diff
@@ -1654,10 +1655,12 @@ public void flush(boolean force, boolean waitIfOngoing) throws EngineException {
...
             try {
                 // Only flush if (1) Lucene has uncommitted docs, or (2) forced by caller, or (3) the
-                // newly created commit points to a different translog generation (can free translog)
+                // newly created commit points to a different translog generation (can free translog),
+                // or (4) the processed local checkpoint is ahead of the local checkpoint tracked in the safe commit
                 boolean hasUncommittedChanges = indexWriter.hasUncommittedChanges();
                 boolean shouldPeriodicallyFlush = shouldPeriodicallyFlush();
-                if (hasUncommittedChanges || force || shouldPeriodicallyFlush) {
+                if (hasUncommittedChanges || force || shouldPeriodicallyFlush
+                        || getProcessedLocalCheckpoint() > getPersistedLocalCheckpoint()) {
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:1663]: This is very subtle, as the persisted local checkpoint is driven mainly by Translog fsyncing (even though both local checkpoints are initialized from what's in the safe commit), i.e. getPersistedLocalCheckpoint() means the local checkpoint last persisted by the translog, not Lucene. I'm inclined to instead use `lastCommittedSegmentInfos.getUserData()...` here and look at the actually last Lucene-persisted local checkpoint.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 5]
```diff
@@ -1654,10 +1655,12 @@ public void flush(boolean force, boolean waitIfOngoing) throws EngineException {
             }
             try {
                 // Only flush if (1) Lucene has uncommitted docs, or (2) forced by caller, or (3) the
-                // newly created commit points to a different translog generation (can free translog)
+                // newly created commit points to a different translog generation (can free translog),
+                // or (4) the processed local checkpoint is ahead of the local checkpoint tracked in the safe commit
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:1659]: It's unclear what the safe commit is in the case of calling this method. Instead I would say something along the lines of:
// or (4) the local checkpoint information in the last commit is stale, which slows down future recoveries.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 2 above)
Comment (ywelsch) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:493]: The refresh in the flush method is an internal refresh, not an external one. I don't think that the external refresh is actually necessary (we do the relevant refresh in IndexShard.postRecovery, which is called before moving the shard to started). What happens if you just remove the refresh call here?

**Review by ywelsch — CHANGES_REQUESTED** [review]
I've left some comments. Thanks for picking this up, Armin.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:493]: It breaks a few tests that relied on the external refresh when recovering from translog, but it's a manageable number. I'll adjust those and run a few iterations of tests to make sure I didn't miss a spot.

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java (hunk 3 above)
Comment (original-brownbear) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java]: This works fine I think. The only adjustment I had to make is to also check if the primary term is still in sync with the current writer in addition to the operations.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java (hunk 4 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: ++ moved to reading it from the `lastCommittedSegmentInfos`

**Comment by original-brownbear** [comment]
Thanks Yannick, all points addressed I think :)

**Review by ywelsch — APPROVED** [review]
LGTM. I would like for @dnhatn to have a look here too.

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 6]
```diff
@@ -485,13 +486,10 @@ private void recoverFromTranslogInternal(TranslogRecoveryRunner translogRecovery
...
-            logger.trace("flushing post recovery from translog: ops recovered [{}], current translog generation [{}]",
-                opsRecovered, translog.currentFileGeneration());
-            commitIndexWriter(indexWriter, translog);
-            refreshLastCommittedSegmentInfos();
-            refresh("translog_recovery");
-        }
+        logger.trace(() -> new ParameterizedMessage(
+                "flushing post recovery from translog: ops recovered [{}], current translog generation [{}]",
+                opsRecovered, translog.currentFileGeneration()));
+        flush(false, true);
```
Comment (dnhatn) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java:492]: I am a bit concerned about the [locking order](https://github.com/elastic/elasticsearch/pull/57350/files#diff-0a8902003e3ef16c5ca38aa269765578R1635) in`flush` (readLock -> flushLock) and `recoverFromTranslog` (flushLock -> readLock). I think we can remove the `flushLock` in `recoverFromTranslog` as it's safe to flush during recovery.

**Review by dnhatn — COMMENTED** [review]
Changes look good. I left a comment.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks Armin. Can you also remove this [stale comment](https://github.com/elastic/elasticsearch/blob/b483246868c107ed8e2218c562571d54b97c470c/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L1637-L1641)?

**Comment by original-brownbear** [comment]
Thanks Nhat + Yannick!

> Can you also remove this stale comment?

Sure removed it :)
