### PR TITLE
Reapply "Add an option to return early from an allocate call" 

### LINKED ISSUE #135150: [CI] RollingUpgradeSearchableSnapshotIndexCompatibilityIT testSearchableSnapshotUpgrade {p0=[9.2.0, 9.2.0, 9.2.0]} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10733 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/nof5sl46epd46)
- [elasticsearch-pull-request #93593 / part-6](https://gradle-enterprise.elastic.co/s/dnlghtb2xip3i)
- [elasticsearch-periodic-platform-support #10697 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/nc3g53kja3eg4)

**Reproduction Line:**
```
./gradlew ":qa:lucene-index-compatibility:javaRestTest" --tests "org.elasticsearch.lucene.RollingUpgradeSearchableSnapshotIndexCompatibilityIT" -Dtests.method="testSearchableSnapshotUpgrade {p0=[9.2.0, 9.2.0, 9.2.0]}" -Dtests.seed=C632D9CFC4DB11ED -Dtests.locale=el-POLYTON -Dtests.timezone=US/Hawaii -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.lucene.RollingUpgradeSearchableSnapshotIndexCompatibilityIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSearchableSnapshotUpgrade%20%7Bp0%3D%5B9.2.0%2C%209.2.0%2C%209.2.0%5D%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.RuntimeException: An error occurred while checking cluster 'test-cluster' status.
```

**Issue Reasons:**
- [main] 3 failures in test testSearchableSnapshotUpgrade {p0=[9.2.0, 9.2.0, 9.2.0]} (0.9% fail rate in 347 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (28.6% fail rate in 7 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135151: [CI] RollingUpgradeSearchableSnapshotIndexCompatibilityIT testMountSearchableSnapshot {p0=[9.2.0, 9.2.0, 9.2.0]} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10733 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/nof5sl46epd46)
- [elasticsearch-pull-request #93593 / part-6](https://gradle-enterprise.elastic.co/s/dnlghtb2xip3i)
- [elasticsearch-periodic-platform-support #10697 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/nc3g53kja3eg4)

**Reproduction Line:**
```
./gradlew ":qa:lucene-index-compatibility:javaRestTest" --tests "org.elasticsearch.lucene.RollingUpgradeSearchableSnapshotIndexCompatibilityIT" -Dtests.method="testSearchableSnapshotUpgrade {p0=[9.2.0, 9.2.0, 9.2.0]}" -Dtests.seed=C632D9CFC4DB11ED -Dtests.locale=el-POLYTON -Dtests.timezone=US/Hawaii -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.lucene.RollingUpgradeSearchableSnapshotIndexCompatibilityIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMountSearchableSnapshot%20%7Bp0%3D%5B9.2.0%2C%209.2.0%2C%209.2.0%5D%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.RuntimeException: An error occurred while checking cluster 'test-cluster' status.
```

**Issue Reasons:**
- [main] 3 failures in test testMountSearchableSnapshot {p0=[9.2.0, 9.2.0, 9.2.0]} (0.9% fail rate in 347 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (28.6% fail rate in 7 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135194: [CI] QueryableBuiltInRolesUpgradeIT testBuiltInRolesSyncedOnClusterUpgrade failing
**Build Scans:**
- [elasticsearch-intake #28833 / 9.2.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/epen5ajlogtbo)
- [elasticsearch-intake #28737 / 9.2.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ascmlxgdys35u)
- [elasticsearch-pull-request #93604 / 9.0.8_part_2_bwc-snapshots](https://gradle-enterprise.elastic.co/s/oykwezw5spj7s)

**Reproduction Line:**
```
./gradlew ":x-pack:qa:rolling-upgrade:v9.2.0#upgradedClusterTest" -Dtests.class="org.elasticsearch.upgrades.QueryableBuiltInRolesUpgradeIT" -Dtests.method="testBuiltInRolesSyncedOnClusterUpgrade" -Dtests.seed=EF0385DDF1CEE2FC -Dtests.bwc=true -Dtests.locale=xnr -Dtests.timezone=Pacific/Johnston -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.QueryableBuiltInRolesUpgradeIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testBuiltInRolesSyncedOnClusterUpgrade'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:35913], URI [/_cluster/health?wait_for_nodes=3], status line [HTTP/1.1 408 Request Timeout]
{"cluster_name":"v9.2.0","status":"red","timed_out":true,"number_of_nodes":2,"number_of_data_nodes":2,"active_primary_shards":179,"active_shards":352,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":4,"unassigned_primary_shards":3,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":98.87640449438202}
```

**Issue Reasons:**
- [main] 2 consecutive failures in step 9.2.0_bwc-snapshots
- [main] 3 failures in test testBuiltInRolesSyncedOnClusterUpgrade (0.4% fail rate in 687 executions)
- [main] 2 failures in step 9.2.0_bwc-snapshots (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-intake (3.2% fail rate in 63 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135406: [CI] DataStreamsUpgradeIT testDataStreamValidationDoesNotBreakUpgrade failing
**Build Scans:**
- [elasticsearch-intake #29026 / 9.2.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/3eeakildzuq6u)
- [elasticsearch-intake #29018 / 9.0.8_bwc-snapshots](https://gradle-enterprise.elastic.co/s/4twuqshdvjiss)

**Reproduction Line:**
```
./gradlew ":x-pack:qa:rolling-upgrade:v9.2.0#upgradedClusterTest" -Dtests.class="org.elasticsearch.upgrades.DataStreamsUpgradeIT" -Dtests.method="testDataStreamValidationDoesNotBreakUpgrade" -Dtests.seed=F70ECBC8A5C1BD21 -Dtests.bwc=true -Dtests.locale=en-US -Dtests.timezone=Etc/GMT+11 -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.DataStreamsUpgradeIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDataStreamValidationDoesNotBreakUpgrade'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state for index [logs-barbaz] cluster state [{
  "cluster_name" : "v9.2.0",
  "cluster_uuid" : "gyhgkq5gTN-_JMIMXgD7Xw",
  "version" : 1778,
  "state_uuid" : "nCxM-IPnSt-lLUVd0Yuvzw",
  "master_node" : "r5tvncrmRnGnH-KpVpAnbA",
  "blocks" : {
    "indices" : {
      "mounted_index_shared_cache" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      },
      "mounted_index_full_copy" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      },
      "index_first_reindex_test_data_stream-01" : {
        "4" : {
          "description" : "index closed",
          "retryable" : false,
          "levels" : [
            "read",
            "write"
          ]
        }
      },
      ".ds-reindex_test_data_stream-202
[truncated]
```

**Issue Reasons:**
- [main] 2 failures in test testDataStreamValidationDoesNotBreakUpgrade (0.2% fail rate in 1000 executions)
- [main] 2 failures in pipeline elasticsearch-intake (9.1% fail rate in 22 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135407: [CI] IndexingIT testIndexing failing
**Build Scans:**
- [elasticsearch-intake #29026 / 9.2.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/3eeakildzuq6u)
- [elasticsearch-intake #29018 / 9.0.8_bwc-snapshots](https://gradle-enterprise.elastic.co/s/4twuqshdvjiss)

**Reproduction Line:**
```
./gradlew ":x-pack:qa:rolling-upgrade:v9.2.0#upgradedClusterTest" -Dtests.class="org.elasticsearch.upgrades.IndexingIT" -Dtests.method="testIndexing" -Dtests.seed=F70ECBC8A5C1BD21 -Dtests.bwc=true -Dtests.locale=ti -Dtests.timezone=Asia/Oral -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.IndexingIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testIndexing'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state for index [test_index,index_with_replicas,empty_index] cluster state [{
  "cluster_name" : "v9.2.0",
  "cluster_uuid" : "gyhgkq5gTN-_JMIMXgD7Xw",
  "version" : 1778,
  "state_uuid" : "nCxM-IPnSt-lLUVd0Yuvzw",
  "master_node" : "r5tvncrmRnGnH-KpVpAnbA",
  "blocks" : {
    "indices" : {
      "mounted_index_shared_cache" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      },
      "mounted_index_full_copy" : {
        "8" : {
          "description" : "index write (api)",
          "retryable" : false,
          "levels" : [
            "write"
          ]
        }
      },
      "index_first_reindex_test_data_stream-01" : {
        "4" : {
          "description" : "index closed",
          "retryable" : false,
          "levels" : [
            "read",
            "write"
          ]
        }
      },
      ".
[truncated]
```

**Issue Reasons:**
- [main] 2 failures in test testIndexing (0.2% fail rate in 1000 executions)
- [main] 2 failures in pipeline elasticsearch-intake (9.1% fail rate in 22 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135474: [CI] SearchableSnapshotsRollingUpgradeIT testBlobStoreCacheWithFullCopyInMixedVersions failing
**Build Scans:**
- [elasticsearch-intake #29085 / 9.2.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/q3agdjs5c6u4k)
- [elasticsearch-pull-request #94917 / 9.2.0_part_2_bwc-snapshots](https://gradle-enterprise.elastic.co/s/hhhfsea4rhfdw)

**Reproduction Line:**
```
./gradlew ":x-pack:qa:rolling-upgrade:v9.2.0#twoThirdsUpgradedTest" -Dtests.class="org.elasticsearch.upgrades.SearchableSnapshotsRollingUpgradeIT" -Dtests.method="testBlobStoreCacheWithPartialCopyInMixedVersions" -Dtests.seed=4389970EFAEA39C8 -Dtests.bwc=true -Dtests.locale=is -Dtests.timezone=US/Michigan -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.SearchableSnapshotsRollingUpgradeIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testBlobStoreCacheWithFullCopyInMixedVersions'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:38023], URI [/_cluster/health?wait_for_nodes=3], status line [HTTP/1.1 408 Request Timeout]
{"cluster_name":"v9.2.0","status":"yellow","timed_out":true,"number_of_nodes":2,"number_of_data_nodes":2,"active_primary_shards":176,"active_shards":292,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":55,"unassigned_primary_shards":0,"delayed_unassigned_shards":55,"number_of_pending_tasks":1,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":84.14985590778097}
```

**Issue Reasons:**
- [main] 2 failures in test testBlobStoreCacheWithFullCopyInMixedVersions (0.2% fail rate in 1000 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
This PR reapply #134786 with a bug fix which previously caused many test failures. 

Resolves: #135406
Resolves: #135407 
Resolves: #135150 
Resolves: #135151 
Resolves: #135194 
Resolves: #135248 
Resolves: #135249 
Resolves: #135408 
Resolves: #135473 
Resolves: #135474

The following is the original commit message
Instead of running simulation all the way to balance or no possible movement, this PR adds an option to finish early based on the number of relocating shards. Note this early return mechanism is enabled only when desired balance is in use, i.e. it affects simulation only.

Resolves: ES-12862

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java [hunk 1]
```diff
@@ -630,6 +699,18 @@ private void balanceByWeights(NodeSorter sorter) {
...
+                                // ES-12955: Check routingNodes.getRelocatingShardCount() > 0 in case the first relocation is a THROTTLE.
+                                // This should rarely happen since in most cases, we don't throttle unless there is an existing relocation.
+                                // But it can happen in production for frozen indices when the cache is still being prepared. It can also
+                                // happen in tests because we have decider like RandomAllocationDecider that can randomly return THROTTLE
+                                // when there is no existing relocation.
+                                shardBalanced = true;
+                            }
+                            if (completeEarlyOnShardAssignmentChange && shardBalanced) {
+                                return true;
+                            }
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java:713]: This is the fix. See also 70b99deb0fd49cf8ff8c8635fe7c1928e2fd59fe for its commit.

There were two issues:
1. The main one is the we should only flag `shardBalanced` to `true` when there is shard movement on the cluster instead of just on the model node.
2. The second issue is that in production, we can actually have balance being throttled without any prior shard movement due to [HasFrozenCacheAllocationDecider](https://github.com/elastic/elasticsearch/blob/3f56dbc80ae4625895e659de5b420b12f751cf89/x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/xpack/searchablesnapshots/allocation/decider/HasFrozenCacheAllocationDecider.java#L86). I updated the comment to reflect it.

**Comment by ywangd** [comment]
Test failure not related, but reproducible on `main`. I raised https://github.com/elastic/elasticsearch/issues/135590

**Review by nicktindall — COMMENTED** [review]
LGTM, tricky one to catch

**Review by nicktindall — APPROVED** [review]
