### PR TITLE
Make range queries round up upper bounds again.

### LINKED ISSUE #20579: Query_String query inclusive date range is not "inclusive"
**Elasticsearch version**: 2.4.0

**Plugins installed**: []

**JVM version**: Java HotSpot 64-bit Server VM (build 25.65-b01, mixed mode)

**OS version**:  Windows 7 SP 1

**Description of the problem including expected versus actual behavior**:

When searching date field using query_string query and providing timestamp like:

[2016-09-13 TO 2016-09-20] the entry with timestamp field being 2016-09-20T08 is not matched - same with curly brackets i.e. {2016-09-13 TO 2016-09-20} 
[2016-09-13 TO 2016-09-20T09]  works (but [2016-09-13 TO 2016-09-20T08] not)

I have just migrated from 1.7.5 to 2.4.0 and in 1.7.5 above query was returning correct, in my understanding, results.

**Steps to reproduce**:
 1. Perform search using query_string query for inclusive date range [yyyy-mm-dd TO yyyy-mm-dd] and provide date with day but without hour

### PR DESCRIPTION
**Pull request by jpountz**
Elasticsearch 1.x used to implicitly round up upper bounds of queries when they
were inclusive so that eg. `[2016-09-18 TO 2016-09-20]` would actually run
`[2016-09-18T00:00:00.000Z TO 2016-09-20T23:59:59.999Z]` and include dates like
`2016-09-20T15:32:44`. This behaviour was lost in the cleanups of #8889.

Closes #20579

### CODE REVIEW

**Comment by jpountz** [comment]
@rjernst would you mind having a look?

**Comment by rjernst** [comment]
Hrm, I don't see this as the feature being "lost", but fixed. You can see how a user would have the exact opposite reaction when documents *outside* of the datetime range they passed were returned. The date math change you reference cleaned this up, so that if you want a user wants to include an entire day, they should use `2016-09-20/d`

**Comment by jpountz** [comment]
I need to think more about it but I'm not sure it is crazy to assume that all time values on the boundary should be included when the date is specified without time and the boundary is inclusive, and excluded if the boundary is exclusive (eg. `{2016-09-18 TO 2016-09-20}`). Rounding explicitly works but it's also less user-friendly (and the syntax needs to be `2016-09-20||/d` I think).

**Comment by clintongormley** [comment]
I agree with @jpountz - as a user i'd expect an inclusive upper bound specified as `2016-09-20` to include up to midnight

**Comment by clintongormley** [comment]
Discussed in FixItFriday - agreed that we should do this as it corresponds with the user's intention

**Comment by jpountz** [comment]
Could someone please have a look?

File: core/src/test/java/org/elasticsearch/common/joda/DateMathParserTests.java [hunk 1]
```diff
@@ -77,8 +77,8 @@ public void testBasicDates() {
     }
 
     public void testRoundingDoesNotAffectExactDate() {
-        assertDateMathEquals("2014-11-12T22:55:00Z", "2014-11-12T22:55:00Z", 0, true, null);
-        assertDateMathEquals("2014-11-12T22:55:00Z", "2014-11-12T22:55:00Z", 0, false, null);
+        assertDateMathEquals("2014-11-12T22:55:00.000Z", "2014-11-12T22:55:00.000Z", 0, true, null);
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/common/joda/DateMathParserTests.java]: nite: can we use some other time zone than UTC in these tests?

File: core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java [hunk 2]
```diff
@@ -63,13 +63,10 @@ public long parse(String text, Callable<Long> now, boolean roundUp, DateTimeZone
         } else {
             int index = text.indexOf("||");
             if (index == -1) {
-                return parseDateTime(text, timeZone);
+                return parseDateTime(text, timeZone, roundUp);
             }
-            time = parseDateTime(text.substring(0, index), timeZone);
+            time = parseDateTime(text.substring(0, index), timeZone, false);
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java]: I found it weird that we ignore the incoming round up parameter here. Are you sure it's correct?

File: core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java [hunk 3]
```diff
@@ -190,15 +187,29 @@ private long parseMath(String mathString, long time, boolean roundUp, DateTimeZo
...
         if (timeZone != null) {
             parser = parser.withZone(timeZone);
         }
         try {
-            return parser.parseMillis(value);
+            MutableDateTime date;
+            // We use 01/01/1970 as a base date so that things keep working with date
+            // fields that are filled with times without dates
+            if (roundUp) {
+                date = new MutableDateTime(1970, 1, 1, 23, 59, 59, 999, DateTimeZone.UTC);
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java]: are we sure we shouldn't use the incoming timeZone parameter here?

**Review by bleskes — COMMENTED** [review]
Left some questions...

File: core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java (hunk 2 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java]: It is not ignored. What happens is that the date is rounded explicitly using the `||` notation. Eg. `2010-03-19 09:45:02||/d` which tells Elasticsearch to parse the date and round it with a daily interval. So first we parse the date without taking care of rounding (the line that you are commenting) and then we are applying the rounding 2 lines below in the `parseMath` method.

File: core/src/test/java/org/elasticsearch/common/joda/DateMathParserTests.java (hunk 1 above)
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/common/joda/DateMathParserTests.java]: will do

File: core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java (hunk 3 above)
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java]: Yes. There is a test for it already in `testImplicitRounding`. And I added a new one for the case that the timezone is not passed as an argument but set directly in the format.

**Comment by jpountz** [comment]
Thanks @bleskes. I pushed another commit.

File: core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java (hunk 2 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java]: OK. thx.

File: core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java (hunk 3 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java]: This is totally funky and the parsing code is crazy, but I verified it works with weirder timezones.

```
        assertDateMathEquals("2014-11-18", "2014-11-18T00:00:00-09:30", 0, false, DateTimeZone.forID("Pacific/Marquesas"));
        assertDateMathEquals("2014-11-18", "2014-11-18T23:59:59.999-09:30", 0, true, DateTimeZone.forID("Pacific/Marquesas"));
```

**Review by bleskes — APPROVED** [review]
LGTM. This is nit, but I think the roundUp name in [1] is confusing as it is only used if no time is supplied. Maybe rename it to `roundUpIfNoTime`?  java docs will be great too :)

[1] `public long parse(String text, Callable<Long> now, boolean roundUp, DateTimeZone timeZone)`
