### PR TITLE
[7.17] Fix Netty4TransportMultiPortIntegrationIT#testThatTransportClientCanConnect

### LINKED ISSUE #107757: [CI] Netty4TransportMultiPortIntegrationIT testThatTransportClientCanConnect failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/v6se3blyyh6v2/tests/:modules:transport-netty4:internalClusterTest/org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT/testThatTransportClientCanConnect

**Reproduction line:**
```
gradlew ':modules:transport-netty4:internalClusterTest' --tests "org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT.testThatTransportClientCanConnect" -Dtests.seed=A5E27C5B18060E9F -Dtests.locale=nl-BE -Dtests.timezone=Asia/Vientiane -Druntime.java=21
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT#testThatTransportClientCanConnect`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testThatTransportClientCanConnect'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{f-v3UV12SYWla3BIo12EeA}{127.0.0.1}{127.0.0.1:61286}, {#transport#-2}{juoGzxwLTweew8g3wXnCzg}{127.0.0.1}{127.0.0.1:61287}, {#transport#-3}{m1gisPg2S26TKYjsSRHI2A}{127.0.0.1}{127.0.0.1:61288}, {#transport#-4}{TDY5gBIdQxCscnHHqiY15g}{127.0.0.1}{127.0.0.1:61289}, {#transport#-5}{LNi_27isSBuUT1UxPouwIQ}{127.0.0.1}{127.0.0.1:61290}, {#transport#-6}{bMEuJtv2TP6C1WGhJD_IwA}{127.0.0.1}{127.0.0.1:61291}, {#transport#-7}{uOtQrsVpQsm8711GqQMEAA}{127.0.0.1}{127.0.0.1:61292}, {#transport#-8}{xOmxGiV7Q8a2UrI8EmNM1g}{127.0.0.1}{127.0.0.1:61293}, {#transport#-9}{RLXZkE52R3S9V-O2X0iHCQ}{127.0.0.1}{127.0.0.1:61294}, {#transport#-10}{BMj7VMBeR1OFhdg12cdSgg}{127.0.0.1}{127.0.0.1:61295}, {#transport#-11}{mDB8pMl3Si6QgJCfyI3dQQ}{127.0.0.1}{127.0.0.1:61296}]

  at __randomizedtesting.SeedInfo.seed([A5E27C5B18060E9F:414823E21D85F6E5]:0)
  at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:250)
  at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:51)
  at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:464)
  at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:407)
  at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:392)
  at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:699)
  at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:34)
  at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:41)
  at org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT.testThatTransportClientCanConnect(Netty4TransportMultiPortIntegrationIT.java:78)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by arteam**
#103894 increased the range of available client ports on Windows for a node, but didn't update the range of ports that the transport client test iterates through in trying to connect to the node. 

Both test failures reported in #107757 happened on Windows machines.

See #103894

Resolves #107757

### CODE REVIEW

**Review by idegtiarenko — APPROVED** [review]

File: modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java [hunk 1]
```diff
@@ -72,7 +72,7 @@ public void testThatTransportClientCanConnect() throws Exception {
             .build();
         // we have to test all the ports that the data node might be bound to
         try (TransportClient transportClient = new MockTransportClient(settings, Arrays.asList(Netty4Plugin.class))) {
-            for (int i = 0; i <= 10; i++) {
+            for (int i = 0; i <= NUMBER_OF_CLIENT_PORTS; i++) {
```
Comment (pxsalehi) [inline modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java:75]: I'm not that familiar with these parts, by I wonder why does this resolve the test failure? My understanding is that this only extends the list that the client can pick from. Adding some 300 ports there seems a bit odd to me. Are the `NoNodeAvailableException` in the failures caused by the port issue on Windows?

Comment (arteam) [reply modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/transport/netty4/Netty4TransportMultiPortIntegrationIT.java:75]: It extends the list of ports we need to try to connect to. Windows blocks a lot of port ranges for some reason.

**Review by pxsalehi — APPROVED** [review]

**Comment by arteam** [comment]
Thank you both!
