### PR TITLE
Make docker tests more reliable

### LINKED ISSUE #66656: [CI] DockerTests test085EnvironmentVariablesAreRespectedUnderDockerExec failing on Fedora 32
This docker test seems to fail on occasion specifically on Fedora 32:

https://gradle-enterprise.elastic.co/s/zjf65ovw657li/tests/:qa:os:destructiveDistroTest.default-docker_ubi/org.elasticsearch.packaging.test.DockerTests/test085EnvironmentVariablesAreRespectedUnderDockerExec#1

```
org.elasticsearch.packaging.test.DockerTests > test010Install FAILED
    java.lang.RuntimeException: Command was not successful: [bash -c docker exec --user elasticsearch:root --tty 2e1612134c884d03d13f7a711a416b26db7e2d0c5643c19aa9a998305f313fe1 stat --format="%U %G %A" /usr/share/elasticsearch/config/elasticsearch.keystore]
       result: exitCode = [1] stdout = [stat: cannot stat '/usr/share/elasticsearch/config/elasticsearch.keystore': No such file or directory] stderr = []
        at __randomizedtesting.SeedInfo.seed([528C4E8802F598B8:76D3EE1B6058C7E0]:0)
        at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:158)
        at org.elasticsearch.packaging.util.Shell.run(Shell.java:84)
        at org.elasticsearch.packaging.util.Docker.assertPermissionsAndOwnership(Docker.java:372)
        at org.elasticsearch.packaging.util.Docker.verifyOssInstallation(Docker.java:426)
        at org.elasticsearch.packaging.util.Docker.verifyContainerInstallation(Docker.java:408)
        at org.elasticsearch.packaging.test.DockerTests.test010Install(DockerTests.java:114)
```

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #66656.

Current, `Docker#verifyOssInstallation(...)` checks the permissions of
`elasticsearch.keystore`, however this often causes problems when a test
forgets to wait for ES and the keystore doesn't exist yet.

Instead, add a test specifically to check `elasticsearch.keystore` and
remove the check from `verifyOssInstallation()`.

### CODE REVIEW

File: buildSrc/src/main/java/org/elasticsearch/gradle/docker/DockerSupportService.java [hunk 1]
```diff
@@ -311,7 +311,7 @@ private Result runCommand(String... args) {
          * <ul>
          *     <li>Installed</li>
          *     <li>Executable</li>
-         *     <li>Is at least version compatibile with minimum version</li>
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/docker/DockerSupportService.java:314]: I think "compatibile" is the right word when describing Docker.

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java [hunk 2]
```diff
@@ -97,9 +98,7 @@ public void teardownTest() {
     /**
      * Checks that the Docker image can be run, and that it passes various checks.
      */
-    public void test010Install() throws Exception {
-        // Wait for the container to come up, because we assert the state of some files that Elasticsearch creates on startup.
-        waitForElasticsearch(installation);
```
Comment (mark-vieira) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java:102]: Are there no other files that get laid down on startup? It's just the keystore?

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java [hunk 3]
```diff
@@ -146,6 +145,15 @@ public void test041AmazonCaCertsAreInTheKeystore() {
         assertTrue("Expected Amazon trusted cert in cacerts", matches);
     }
 
+    /**
+     * Check that when the keystore is created on startup, it is created with the correct permissions.
+     */
+    public void test042KeystorePermissionsAreCorrect() throws Exception {
+        waitForElasticsearch(installation);
```
Comment (mark-vieira) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java:152]: The failures seem to indicate that `waitForElasticseach()` doesn't seem to be robust enough. Do we have theories on why that method would return, but the keystore file would _not_ be there? Wouldn't we expect this test to occasionally fail still?

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 2 above)
Comment (pugnascotia) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java:102]: Besides log files, it's just the keystore AFAIK.

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 3 above)
Comment (pugnascotia) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java:152]: I'm not sure that `waitForElasticseach()` is the problem. The original problem in #66656 was due to to the test running a CLI tool without waiting for ES to start up and create the keystore, which in this case the tool needed.

I removed the keystore from the `verifyOssInstallation()` because most tests don't care about it, and have a test fail because it didn't wait for a file to be created that the test doesn't care about is just...silly.

Comment (mark-vieira) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java:152]: Sure, I guess my point being that the new test you added is still susceptible to the same underlying cause of those other failures, unless I'm missing something. Indeed I agree we don't need superfluous assertions in those other tests, so if nothing else this should fail _less_ often. We'll keep an eye on it.

**Review by mark-vieira — APPROVED** [review]

File: qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java (hunk 3 above)
Comment (pugnascotia) [reply qa/os/src/test/java/org/elasticsearch/packaging/test/DockerTests.java:152]: Basically this - if the new test is failing often, at least I have somewhere more specific to start investigating.

**Comment by pugnascotia** [comment]
Backported to `7.x` in abc645424bb
