### PR TITLE
Give another chance for the shards to become available.

### LINKED ISSUE #93633: [CI] SingleNodeTests testThatLoadingWithNonExistingIndexWorks failing
Related to https://github.com/elastic/elasticsearch/issues/54096 but with different error.

**Build scan:**
https://gradle-enterprise.elastic.co/s/alacszij2iusu/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests/testThatLoadingWithNonExistingIndexWorks

**Reproduction line:**
```
gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests.testThatLoadingWithNonExistingIndexWorks" -Dtests.seed=BBAB816FDB200A43 -Dtests.locale=ga-IE -Dtests.timezone=Asia/Tehran -Druntime.java=19
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests&tests.test=testThatLoadingWithNonExistingIndexWorks

**Failure excerpt:**
```
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed

  at __randomizedtesting.SeedInfo.seed([BBAB816FDB200A43:697B0E71D50E75BF]:0)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:728)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:418)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:760)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:512)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.performPhaseOnShard(AbstractSearchAsyncAction.java:326)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.run(AbstractSearchAsyncAction.java:262)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.executePhase(AbstractSearchAsyncAction.java:469)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.start(AbstractSearchAsyncAction.java:217)
  at org.elasticsearch.action.search.TransportSearchAction.executeSearch(TransportSearchAction.java:1041)
  at org.elasticsearch.action.search.TransportSearchAction.executeLocalSearch(TransportSearchAction.java:769)
  at org.elasticsearch.action.search.TransportSearchAction.lambda$executeRequest$6(TransportSearchAction.java:390)
  at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:167)
  at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:112)
  at org.elasticsearch.index.query.Rewriteable.rewriteAndFetch(Rewriteable.java:77)
  at org.elasticsearch.action.search.TransportSearchAction.executeRequest(TransportSearchAction.java:478)
  at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:277)
  at org.elasticsearch.action.search.TransportSearchAction.doExecute(TransportSearchAction.java:103)
  at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:86)
  at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:61)
  at org.elasticsearch.tasks.TaskManager.registerAndExecute(TaskManager.java:203)
  at org.elasticsearch.client.internal.node.NodeClient.executeLocally(NodeClient.java:112)
  at org.elasticsearch.client.internal.node.NodeClient.doExecute(NodeClient.java:90)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:380)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:366)
  at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:34)
  at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:41)
  at org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests.lambda$testThatLoadingWithNonExistingIndexWorks$0(SingleNodeTests.java:64)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1136)
  at org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests.testThatLoadingWithNonExistingIndexWorks(SingleNodeTests.java:62)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

  Caused by: org.elasticsearch.action.NoShardAvailableActionException: (No message provided)


```

### PR DESCRIPTION
**Pull request by gmarouli**
`[CI] SingleNodeTests testThatLoadingWithNonExistingIndexWorks` keeps failing with the error `org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed`.

In a previous attempt to fix this (https://github.com/elastic/elasticsearch/pull/93710) we saw that introducing, we saw that waiting for the refresh to finish would decrease the chance of failure.

We believe that the flakiness is due to the shards not being ready yet, for this reason we propose the following:
- Assert on the response of the refresh request.
- Log any errors if there were failed shards.
- Assert all shards were successfully refreshed.

Because we cannot reproduce this and test the fix, our goals with this PR are:

- If the shards are not ready, we use the `assertBusy` mechanism to try again, and
- We log the reasons the shards failed hoping to get more insights if this was not a timing issue.

Most recent failure: https://gradle-enterprise.elastic.co/s/jwk4izpftydec/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests/testThatLoadingWithNonExistingIndexWorks?top-execution=1

Closes: https://github.com/elastic/elasticsearch/issues/93633

### CODE REVIEW

**Review by HiDAl — APPROVED** [review]

File: x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java [hunk 1]
```diff
@@ -60,7 +63,12 @@ public void testThatLoadingWithNonExistingIndexWorks() throws Exception {
         assertThat(putWatchResponse.isCreated(), is(true));
 
         assertBusy(() -> {
-            indicesAdmin().prepareRefresh(".watcher-history*").get();
+            RefreshResponse refreshResponse = indicesAdmin().prepareRefresh(".watcher-history*").get();
+            assertThat(refreshResponse.getStatus(), equalTo(RestStatus.OK));
+            if (refreshResponse.getShardFailures().length > 0) {
+                logger.warn(refreshResponse.getShardFailures());
+            }
+            assertThat(refreshResponse.getSuccessfulShards(), equalTo(refreshResponse.getTotalShards()));
```
Comment (andreidan) [inline x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java:71]: Hm, looking at the failure, it'd seem that the actual search request failed with an exception:
```
SearchResponse searchResponse = client().prepareSearch(".watcher-history*").setSize(0).get();
``` 

```
at org.elasticsearch.xpack.watcher.test.integration.SingleNodeTests.lambda$testThatLoadingWithNonExistingIndexWorks$0(SingleNodeTests.java:64) |  
```

Also, note that the `assertBusy` only retries on `AssertionErrors`. It'll fail like all the other assertions on exceptions.

I don't think this will give us more information, the way it is now. 

I think we'd need to include the refresh/search calls into `assert...` methods (`assertAcked` ? ) so they throw `AssertionError` if we'd like to retry in case of an error.
Or maybe wait for the data stream to exist first? 
e.g. something along the lines of
```
  assertBusy(() -> assertTrue(dataStreamExists("watcher-history-16")));
```

Comment (gmarouli) [reply x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java:71]: > Also, note that the assertBusy only retries on AssertionErrors. It'll fail like all the other assertions on exceptions.

Indeed, that's why I introduced assertion that the refresh succeeded on all shards. My assumption here is, that if a refresh succeeds then the shards are available so the search should succeed too. Do you think that assumption is wrong?

> Or maybe wait for the data stream to exist first?

I do like this idea because it's more explicit than checking the result of the refresh.

Comment (andreidan) [reply x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java:71]: >Indeed, that's why I introduced assertion that the refresh succeeded on all shards. My assumption here is, that if a refresh succeeds then the shards are available so the search should succeed too. Do you think that assumption is wrong?

I think this is what happened in the test run. 
Refresh succeeded and the (next) search call failed, if I'm reading the failure stack trace correctly.

Comment (gmarouli) [reply x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java:71]: But if the shards are not available how can the refresh succeed and by succeed I mean in the response report that all shards have been successfully refreshed?

Comment (andreidan) [reply x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java:71]: refresh on missing targets reports `0` in the successful report
e.g. 
```
{
  "_shards": {
    "total": 0,
    "successful": 0,
    "failed": 0
  }
}
```

This wouldn't have caused an exception before this PR either.

When searching over a shard without a node in the routing ( https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/search/SearchShardIterator.java#L111 ) we do fail https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/search/AbstractSearchAsyncAction.java#L327

IMO it's highly likely we would only need to wait for the `watch-history*` index to be `GREEN` before searching it

Comment (gmarouli) [reply x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/SingleNodeTests.java:71]: Ah thank you for this clarification! I will change it right away.
