### PR TITLE
[Transform] Do not log warning when triggering an `ABORTING` transform

### LINKED ISSUE #105233: [Transform] Log spam for transform in `ABORTING` state
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

When transform scheduler is trying to trigger a transform that is already in `ABORTING` state, the transform is **not** triggered but warnings are logged in an excessive number.

Note: This issue does **not** cover the reason for why the transform is in `ABORTING` state for such a long time that these warnings are noticeable.

### Steps to Reproduce

I reproduced it using a unit test:
1. Create a transform persistent task
2. Initialize the task with indexer in `ABORTING` state
3. Trigger the task by calling `TransformTask.triggered(Event)` method

Observe the warning being logged.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by przemekwitek**
When transform scheduler is trying to trigger a transform which indexer is already in `ABORTING` state, the transform is not triggered but warnings are logged in an excessive number.

This PR prevents the warnings from being logged by exiting early if the indexer is in `ABORTING` state.
Additionally, this PR adds a bunch of unit tests for `initializeIndexer` and `triggered` methods.

Closes https://github.com/elastic/elasticsearch/issues/105233

### CODE REVIEW

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformTaskTests.java [hunk 1]
```diff
@@ -523,6 +528,85 @@ public void testDeriveBasicCheckpointingInfoWithIndexer() {
...
+        assertThat(e.getMessage(), containsString("The object cannot be set twice!"));
+    }
+
+    public void testTriggeredIsNoOpWhenTransformIdMismatch() {
+        var transformId = randomAlphaOfLengthBetween(1, 10);
+        var transformTask = createTransformTask(
+            TransformConfigTests.randomTransformConfigWithoutHeaders(transformId),
+            MockTransformAuditor.createMockAuditor()
+        );
+        transformTask.triggered(new TransformScheduler.Event("not-" + transformId, randomNonNegativeLong(), randomNonNegativeLong()));
```
Comment (prwhelan) [inline x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformTaskTests.java:550]: If we wanted to verify this returns without calling the indexer, we could do something like:
```java
var indexer = mock(ClientTransformIndexerBuilder.class);
transformTask.initializeIndexer(indexer);
transformTask.triggered(new TransformScheduler.Event("not-" + transformId, randomNonNegativeLong(), randomNonNegativeLong()));
verifyNoInteractions(indexer);
```

**Review by prwhelan — APPROVED** [review]
LGTM

File: x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformTaskTests.java (hunk 1 above)
Comment (przemekwitek) [reply x-pack/plugin/transform/src/test/java/org/elasticsearch/xpack/transform/transforms/TransformTaskTests.java:552]: Great idea!

Done.

**Comment by przemekwitek** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.12|[](https://github.com/elastic/elasticsearch/pull/105307)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
