### PR TITLE
ML: Add reason field in JobTaskState

### LINKED ISSUE #34431: [ML] Store failure reason in ML job task status
At present if an ML job fails then its persistent task is not deleted, but remains in the cluster state with a status of `failed`.  However, to find the reason why it failed you currently need to look in the log file of the node that was running the persistent task at the time when it failed.  This almost invariably involves multiple back-and-forth cycles when working on support cases.

It would be relatively easy to store the `getMessage()` of the exception that caused the job to fail in the job task status for ML job persistent tasks.  This would be helpful in the case where the logs for the node the job was running on are not initially available.  In some cases it may prevent the need to ask for those logs at all.

The only problem with making this change is BWC of the job task status.  If it is strictly parsed in 6.0 or above then 6.7 needs to be changed to leniently ignore unknown fields from the job task status and the new exception field can only be added in 7.0.

### PR DESCRIPTION
**Pull request by benwtrent**
Adds a `reason` field to `JobTaskState`. 

This is so while the task stays in cluster state, the cause for a `failed` state can be gleaned outside of just the logs. 

closes https://github.com/elastic/elasticsearch/issues/34431

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java [hunk 1]
```diff
@@ -473,18 +473,18 @@ protected void doRun() {
...
                                     }
                                 }
                             });
                         }, e1 -> {
                             logger.warn("Failed to gather information required to open job [" + jobId + "]", e1);
-                            setJobState(jobTask, JobState.FAILED, e2 -> closeHandler.accept(e1, true));
+                            setJobState(jobTask, JobState.FAILED, e1.getMessage(), e2 -> closeHandler.accept(e1, true));
                         });
-                    },
+                   },
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java]: nit: a space was accidentally removed here

**Review by droberts195 — APPROVED** [review]
LGTM

I just noticed a couple of places where a space seems to have been deleted unnecessarily
