### PR TITLE
Do not enable doc-partitioning for count

### LINKED ISSUE #134512: [CI] CanMatchIT testAliasFilters failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10547 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/w2nyw5ztw66dg)
- [elasticsearch-pull-request #90883 / part-3](https://gradle-enterprise.elastic.co/s/q4bdwee5uwq4k)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.plugin.CanMatchIT.testAliasFilters" -Dtests.seed=AD1A4AA1D217B8E -Dtests.locale=fy -Dtests.timezone=Etc/Zulu -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.plugin.CanMatchIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAliasFilters'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <[3]>
     but: was <[2]>
```

**Issue Reasons:**
- [main] 2 failures in test testAliasFilters (0.6% fail rate in 315 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
We can't use `Weight#count` with doc-partitioning because if the query gets cached mid-way, the count becomes incorrect. Over-counting occurs when some parts are counted doc-by-doc while the first part is counted entirely via the cached shortcut. Under-counting occurs when the first part is not cached but later parts are, causing those parts to be skipped. To make doc-partitioning work properly for count, we would need coordination between threads.

This change also restores the default partitioning to SEGMENT, which accidentally changed to SHARD.

Closes #134512

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/query/LuceneCountOperator.java [hunk 1]
```diff
@@ -251,4 +249,19 @@ public void collect(int doc) {
...
+    /**
+     * We can't use Weight.count() with doc-partitioning because if the query gets cached mid-way, the count becomes incorrect.
+     * Over-counting occurs when some parts are counted doc-by-doc while the first part is counted entirely via the cached shortcut.
+     * Under-counting occurs when the first part is not cached but later parts are, causing those parts to be skipped.
+     * To make doc-partitioning work properly for count, we would need coordination between threads.
+     */
+    static LuceneSliceQueue.PartitioningStrategy partitioningStrategyForCount(Query q) {
+        final Query unwrapped = LuceneSourceOperator.Factory.unwrapQuery(q);
+        return switch (unwrapped) {
+            case MatchAllDocsQuery unused -> LuceneSliceQueue.PartitioningStrategy.SHARD;
```
Comment (romseygeek) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/query/LuceneCountOperator.java:262]: Nit: do we need the `unused` token here?

**Review by romseygeek — APPROVED** [review]
LGTM.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/query/LuceneCountOperator.java (hunk 1 above)
Comment (dnhatn) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/lucene/query/LuceneCountOperator.java:262]: yes, we need it for switch.

**Comment by dnhatn** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/149236)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/149237)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
