### PR TITLE
Fix ChangePointOperatorTests.testSimpleFinishClose

### LINKED ISSUE #122234: OperatorTestCase testSimpleFinishClose failing
### CI Link

https://gradle-enterprise.elastic.co/s/rmnrjeqrdn2oa/tests/task/:x-pack:plugin:esql:compute:test/details/org.elasticsearch.compute.operator.ChangePointOperatorTests/testSimpleFinishClose?expanded-stacktrace=WyIwIl0&top-execution=1

### Repro line

./gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.operator.ChangePointOperatorTests.testSimpleFinishClose" -Dtests.seed=9E6073984183ECB2 -Dtests.locale=sat-Olck -Dtests.timezone=Asia/Urumqi -Druntime.java=23	

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.buildOutcome=failure&search.timeZoneId=Europe%2FBerlin&tests.container=org.elasticsearch.compute.operator.ChangePointOperatorTests&tests.test=testSimpleFinishClose

### Failure excerpt

I discovered this failure on my pr branch, however I was able to reproduce it on main as well.

When running with `-Dtests.iters` it fails ~1-2 times per 1k runs

### PR DESCRIPTION
**Pull request by jan-elastic**
Fixes https://github.com/elastic/elasticsearch/issues/122234

### CODE REVIEW

File: x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java [hunk 1]
```diff
@@ -241,16 +241,16 @@ protected final void assertSimple(DriverContext context, int size) {
      * Tests that finish then close without calling {@link Operator#getOutput} to
      * retrieve a potential last page, releases all memory.
      */
-    public void testSimpleFinishClose() throws Exception {
+    public void testSimpleFinishClose() {
         DriverContext driverContext = driverContext();
         List<Page> input = CannedSourceOperator.collectPages(simpleInput(driverContext.blockFactory(), 1));
-        assert input.size() == 1 : "Expected single page, got: " + input;
```
Comment (jan-elastic) [inline x-pack/plugin/esql/compute/test/src/main/java/org/elasticsearch/compute/test/OperatorTestCase.java:247]: ChangePoint needs at least 22 values (this is enforced in `simpleInput` by clamping the `size`). For input larger than 1, the number of pages may also exceeds 1 (they have random sizes).

**Review by alex-spies — APPROVED** [review]
