### PR TITLE
Check for default.path.data included in path.data

### LINKED ISSUE #24283: Wrong checking of #23981 bug
**Elasticsearch version**: 5.3.1
**JVM version**:  openjdk-1.8.0.131-2.b11.el7_3
**OS version**: CentOS 7.3.1611 (Core)

**Description of the problem including expected versus actual behavior**:
I had just updated from 5.3.0 to 5.3.1 and then the node didn't like to start up. The logs indicates that there were indexes in the default folder where they should not be. However, this is exactly the folder in which always I have had my indexes!

I think that the mechanism to control a potential misconfiguration after the fix of the bug #23981 in 5.3.1 is wrongly implemented when you have the default data folder explicitly defined in the configuration file.

I had the following lines in my configuration file:

```
    path:
        data: /var/lib/elasticsearch
        logs: /var/log/elasticsearch
```

I was using the default data folder but anyway configuring it explicitly (since it is configurable by other means; ansible-stuff ...). 

In order to raise the Elasticsearch service I have had to comment the path.data line and then it works fine:

```
    path:
#        data: /var/lib/elasticsearch
         logs: /var/log/elasticsearch
```

I think the problem is that the new code was checking if the data folder was being settled up and then check if the default data folder contains indexes, but ... what about if the default data folder is also a valid data folder included in the configuration?

Thanks!

**Steps to reproduce**:
 1. Update to 5.3.1 from 5.3.0 having the default data folder configured explicitly
 2. Try to start the elastic search service

**Provide logs (if relevant)**:
[2017-04-24T11:45:12,480][INFO ][o.e.n.Node               ] [automation] initializing ...
[2017-04-24T11:45:12,557][INFO ][o.e.e.NodeEnvironment    ] [automation] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/mapper/vg_data-lv_elastic)]], net usable_space [39gb], net total_space [58.9gb], spins? [possibly], types [ext4]
[2017-04-24T11:45:12,557][INFO ][o.e.e.NodeEnvironment    ] [automation] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-04-24T11:45:13,691][ERROR][o.e.n.Node               ] [automation] detected index data in default.path.data [/var/lib/elasticsearch/nodes/0/indices] where there should not be any

### PR DESCRIPTION
**Pull request by jasontedor**
If the user explicitly configured path.data to include default.path.data, then we should not fail the node if we find indices in default.path.data. This commit addresses this.

Closes #24283

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

File: core/src/main/java/org/elasticsearch/node/Node.java [hunk 1]
```diff
@@ -523,15 +523,26 @@ static void checkForIndexDataInDefaultPathData(
...
-            if (Files.exists(nodeDirectory) == false) {
+            final Path defaultNodeDirectory = NodeEnvironment.resolveNodePath(getPath(defaultPathData), nodeEnv.getNodeLockId());
+            if (Files.exists(defaultNodeDirectory) == false) {
                 continue;
             }
-            final NodeEnvironment.NodePath nodePath = new NodeEnvironment.NodePath(nodeDirectory);
+
+            boolean includedInPathData = false;
+            for (final NodeEnvironment.NodePath dataPath : nodeEnv.nodePaths()) {
+                includedInPathData |= Files.isSameFile(dataPath.path, defaultNodeDirectory);
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/node/Node.java]: maybe move the loop in a method then we can return early and don't need a label / boolean var in the outer loop

**Review by s1monw — APPROVED** [review]
left a suggestion but LGTM otherwise

File: core/src/main/java/org/elasticsearch/node/Node.java (hunk 1 above)
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/node/Node.java]: I pushed 7d5331765f0a4e2dbf035b53aff414428ed5b363.

It is incredibly fortunate that you asked for this. As a result of asking for this, I made the necessary change and tried to run `gradle :core:test -Dtests.class=org.elasticsearch.node.NodeTests -Dtests.iters=128` from the command-line to ensure that the change did not break anything. This failed, Gradle told me that no tests were executed. It turns out that `org.elasticsearch.node.NodeTests` was sitting in the test framework in src/main/java, so these tests were not executing. It appears the class has been like this since July of last year. Fortunately, nothing is broken. I moved this test class to the appropriate location in core.

**Comment by jasontedor** [comment]
Thanks @nik9000 and @s1monw.

**Comment by nik9000** [comment]
> It turns out that org.elasticsearch.node.NodeTests was sitting in the test framework in src/main/java, so these tests were not executing.

😨

**Comment by nik9000** [comment]
I'll look at changing the gradle task that we have for naming conventions to detect that one....

**Comment by jasontedor** [comment]
> I'll look at changing the gradle task that we have for naming conventions to detect that one....

Good call @nik9000, thanks for picking this up.
