### PR TITLE
[ES|QL] Make numberOfChannels consistent with layout map by removing duplicated ChannelSet

### LINKED ISSUE #121754: ES|QL: NullPointerException planning EVAL
With csv-spec test dataset

```
from clientips,* 
| dissect street "%{height_range} %{MNyXV}" 
| rename env AS kxpCK, pod AS etUHW, language_code AS city.country.continent.planet.galaxy
| rename city.country.continent.planet.name as message 
| lookup join message_types_lookup on message
| rename languages.int as language_code 
| lookup join languages_lookup on language_code
| rename language_code as language_code 
| lookup join languages_lookup on language_code 
| sort decade DESC NULLS FIRST, year ASC NULLS FIRST, country.keyword ASC, num ASC NULLS LAST, network.bytes_in ASC, author.keyword ASC, languages.byte DESC NULLS LAST, type ASC NULLS LAST, zip_code NULLS FIRST, height_range, number ASC, language_code ASC NULLS LAST, host_group NULLS LAST, MNyXV ASC NULLS FIRST, kxpCK ASC, language.id ASC, languages.long DESC NULLS FIRST, host.name ASC, city.country.continent.name ASC NULLS FIRST, author DESC NULLS LAST, ip0, event_duration ASC NULLS LAST, scalerank ASC, ip1 DESC, client.ip NULLS FIRST, message NULLS FIRST, city.country.name ASC NULLS FIRST, version ASC NULLS FIRST, airport ASC NULLS FIRST, language.code ASC NULLS LAST, language.name.keyword NULLS FIRST, city.name DESC NULLS LAST, city.country.continent.planet.galaxy NULLS FIRST, publisher ASC NULLS FIRST, abbrev DESC NULLS FIRST, card ASC, salary_change.keyword NULLS FIRST, lk ASC NULLS FIRST	
```

TODO: simplify the query, it's extreme because it's randomly generated

```
{
    "error": {
        "root_cause": [
            {
                "type": "null_pointer_exception",
                "reason": "Cannot read field \"nameIds\" because \"set\" is null"
            }
        ],
        "type": "null_pointer_exception",
        "reason": "Cannot read field \"nameIds\" because \"set\" is null"
    },
    "status": 500
}
```

```
ESQL request failed with status [INTERNAL_SERVER_ERROR]: java.lang.NullPointerException: Cannot read field "nameIds" because "set" is null
        at org.elasticsearch.xpack.esql.planner.Layout$Builder.build(Layout.java:111)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planEval(LocalExecutionPlanner.java:412)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:211)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planProject(LocalExecutionPlanner.java:640)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:217)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planLookupJoin(LocalExecutionPlanner.java:562)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:243)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planEval(LocalExecutionPlanner.java:406)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:211)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planProject(LocalExecutionPlanner.java:640)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:217)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.planLookupJoin(LocalExecutionPlanner.java:562)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:243)
```

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves: https://github.com/elastic/elasticsearch/issues/121754

This is another option to solve this bug, if duplicated `ChannelSet` are expected to be added to the layout or it is not avoidable.

This NullPointerException happens in Layout.Builder.build(), when there is null ChannelSet in Layout.Builder.channels.

A null ChannelSet could be added in Layout.Builder.channels by Layout.inverse(), if the numberOfChannels > the # of items in the layout map. `

When there are multiple batches of data node executions with lookup join and sort in the query, LocalExecutionPlanner.planEval could potentially append duplicated ChannelSet - duplicated NameId and data type, to the list of ChannelSet in Layout.Builder, which causes numberOfChannels > the # of items in the layout map when build() is called and a DefaultLayout is created.

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM

**Comment by costin** [comment]
Look more self contained than #125636

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 1]
```diff
@@ -927,7 +927,12 @@ public enum Cap {
         /**
          * Index component selector syntax (my-data-stream-name::failures)
          */
-        INDEX_COMPONENT_SELECTORS(DataStream.isFailureStoreFeatureFlagEnabled());
+        INDEX_COMPONENT_SELECTORS(DataStream.isFailureStoreFeatureFlagEnabled()),
+
+        /**
+         * Create null alias with new id in ReplaceMissingFieldWithNull when there is lookup join with multiple batches.
+         */
+        REPLACE_MISSING_FIELD_WITH_NULL_NEW_ALIAS_ID_FOR_JOIN_AND_MULTIPLE_BATCHES;
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java:935]: Maybe the name should reflect the current fix more clearly.

**Review by alex-spies — APPROVED** [review]
I think we can merge this, but should immediately work on a long-term fix.

Attribute ids should not have duplicates in layouts to begin with. The layout should reflect what pages passed through the corresponding operators actually look like - discarding a duplicate attribute means we act as if the block was just not there and this can lead to wrong blocks being passed to operators.

**Comment by alex-spies** [comment]
When we merge this, let's make sure this gets backported as generously as https://github.com/elastic/elasticsearch/pull/125462 was planned to.

**Comment by fang-xing-esql** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/125715)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/125720)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/125721)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
