### PR TITLE
[ES|QL] add tests for stats by constant

### LINKED ISSUE #105383: [ES|QL] Throwing on STATS BY constant statement
### Elasticsearch Version

8.13.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

The following error:

```
verification_exception\n\tRoot causes:\n\t\tverification_exception: Found 1 problem\nline 1:42: expected an aggregate function but found [1]
```

is thrown by the following query:

```
from a_index | stats avg(numberField) by 1
```

I think the problem is double:
* I would expect to error in the first place as user
* The error message is wrong: expected an aggregate function at `by` level?

### Steps to Reproduce

See above.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves #105383

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -5520,6 +5520,43 @@ public void testMvSortInvalidOrder() {
...
+
+        var project = as(plan, Project.class);
+        var eval = as(project.child(), Eval.class);
+        var limit = as(eval.child(), Limit.class);
+        var agg = as(limit.child(), Aggregate.class);
+
+        assertThat(agg.aggregates(), hasSize(3));
+        assertThat(agg.groupings(), hasSize(1));
+        var ref = as(agg.groupings().get(0), ReferenceAttribute.class);
+        assertEquals("0", ref.name());
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:5541]: IMHO I'm not sure we're testing the right thing here.

I _guess_ what's happening is that our optimizer creates an `EVAL` in front of the `STATS` that evaluates the `0`. That's why we see're seeing a reference attribute here.

But that's not what _needs_ to happen. In fact, since the group is foldable, we could optimize away the `by` clause entirely, and, more cheaply, add an `EVAL` after the `STATS` that just appends the `0` to every row.

In that sense, asserting that we have a reference attribute `0` here might be overconstraining.

**Review by alex-spies — COMMENTED** [review]
Heya, thanks @fang-xing-esql !

I think csv tests would be more useful, so we demonstrate that the correct output is computed.

Personally, I'd like to csv test the queries you added - but without the `keep` at the end, so we see what we do with the constant column. Additionally, we could add a test that will catch any weirdness when propagating foldables in the future, i.e.
```
            from test
            | stats m = max(salary), a = avg(salary) by 0

            from test
            | stats c = count(languages)
            | stats a = count(*) by c

// and, additionally, to catch foldable propagation bugs:
            from test
            | eval x = 0
            | stats m = max(salary), a = avg(salary) by x
```

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java (hunk 1 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:5541]: > IMHO I'm not sure we're testing the right thing here.
> 
> I _guess_ what's happening is that our optimizer creates an `EVAL` in front of the `STATS` that evaluates the `0`. That's why we see're seeing a reference attribute here.
> 
> But that's not what _needs_ to happen. In fact, since the group is foldable, we could optimize away the `by` clause entirely, and, more cheaply, add an `EVAL` after the `STATS` that just appends the `0` to every row.
> 
> In that sense, asserting that we have a reference attribute `0` here might be overconstraining.

Thanks for reviewing @alex-spies ! Let me move the tests to CsvTests, I tried to avoid adding a new EsqlCapability just for adding new tests, but perhaps that's the right thing to do.

**Review by alex-spies — APPROVED** [review]
Thanks @fang-xing-esql , LGTM.

It's unfortunate that retrofitting tests needs a new capability, but it's fine IMHO.

Personally, I'd slightly prefer removing the new test in the `LogicalPlanOptimizerTests` since this may be brittle/overconstraining in case we do more optimizations in the future and the exact plan changes; but this PR is a good addition either way so feel free to keep it :)

**Comment by fang-xing-esql** [comment]
> Thanks @fang-xing-esql , LGTM.
> 
> It's unfortunate that retrofitting tests needs a new capability, but it's fine IMHO.
> 
> Personally, I'd slightly prefer removing the new test in the `LogicalPlanOptimizerTests` since this may be brittle/overconstraining in case we do more optimizations in the future and the exact plan changes; but this PR is a good addition either way so feel free to keep it :)

Thank you for reviewing @alex-spies ! I'll remove the new tests from LogicalPlanOptimizerTests, add them in CsvTests only.
