### PR TITLE
Initialize document subset bit set cache used for DLS

### LINKED ISSUE #45147: [bug] failed to collect data, xpack monitoring busted on 7.3.0
**Elasticsearch/JVM version** (`bin/elasticsearch --version`):
flavor: docker image
Version: 7.3.0, Build: default/docker/de777fa/2019-07-24T18:30:11.767338Z, JVM: 12.0.1

**OS version** (`uname -a` if on a Unix-like system):
Linux ******** 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
* rolling upgrade cluster of cluster from 7.2.0 to 7.3.0
* monitoring stops working

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. upgrade cluster from 7.2.0 to 7.3.0
 2. open kibana's monitoring tab
 3. --> cannot find any monitoring data.

**Weirdness**: indexes .monitoring* seem to be filled, but nothing apears on monitoring tab.

**Provide logs (if relevant)**:
```
{"type": "server", "timestamp": "2019-08-02T14:53:19,325+0000", "level": "ERROR", "component": "o.e.x.m.c.c.ClusterStatsCollector", "cluster.name": "elastic-cluster", "node.name": "ccccccccc", "cluster.uuid": "cccccc", "node.id": "ccccc",  "message": "collector [cluster_stats] failed to collect data" , 
"stacktrace": ["java.lang.NullPointerException: null",
"at org.elasticsearch.xpack.security.authz.store.CompositeRolesStore.usageStats(CompositeRolesStore.java:439) ~[?:?]",
"at org.elasticsearch.xpack.security.SecurityFeatureSet.usage(SecurityFeatureSet.java:133) ~[?:?]",
"at org.elasticsearch.xpack.core.action.TransportXPackUsageAction.lambda$masterOperation$0(TransportXPackUsageAction.java:70) ~[?:?]",
"at org.elasticsearch.xpack.core.common.IteratingActionListener.onResponse(IteratingActionListener.java:117) ~[?:?]",
"at org.elasticsearch.xpack.core.action.TransportXPackUsageAction$2.onResponse(TransportXPackUsageAction.java:75) ~[?:?]",
"at org.elasticsearch.xpack.core.action.TransportXPackUsageAction$2.onResponse(TransportXPackUsageAction.java:70) ~[?:?]",
"at org.elasticsearch.xpack.flattened.FlattenedFeatureSet.usage(FlattenedFeatureSet.java:52) ~[?:?]",
"at org.elasticsearch.xpack.core.action.TransportXPackUsageAction.lambda$masterOperation$0(TransportXPackUsageAction.java:70) ~[?:?]",
"at org.elasticsearch.xpack.core.common.IteratingActionListener.run(IteratingActionListener.java:102) ~[?:?]",
"at org.elasticsearch.xpack.core.action.TransportXPackUsageAction.masterOperation(TransportXPackUsageAction.java:93) ~[?:?]",
"at org.elasticsearch.xpack.core.action.TransportXPackUsageAction.masterOperation(TransportXPackUsageAction.java:31) ~[?:?]",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:127) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.doRun(TransportMasterNodeAction.java:200) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:758) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.3.0.jar:7.3.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]",
"at java.lang.Thread.run(Thread.java:835) [?:?]"] }

```

### PR DESCRIPTION
**Pull request by bizybot**
This commit initializes `DocumentSubsetBitsetCache` even if DLS
is disabled. Previously it would throw null pointer when querying
usage stats if we explicitly disabled DLS as there would be no instance of `DocumentSubsetBitsetCache` to query. It is okay to initialize 
`DocumentSubsetBitsetCache` which will be empty as the license enforcement
would prevent usage of DLS feature and it will not fail when accessing usage stats.

Closes #45147

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java [hunk 1]
```diff
@@ -106,17 +106,17 @@ public CompositeRolesStore(Settings settings, FileRolesStore fileRolesStore, Nat
                                ReservedRolesStore reservedRolesStore, NativePrivilegeStore privilegeStore,
                                List<BiConsumer<Set<String>, ActionListener<RoleRetrievalResult>>> rolesProviders,
                                ThreadContext threadContext, XPackLicenseState licenseState, FieldPermissionsCache fieldPermissionsCache,
-                               ApiKeyService apiKeyService, @Nullable DocumentSubsetBitsetCache dlsBitsetCache,
+                               ApiKeyService apiKeyService, DocumentSubsetBitsetCache dlsBitsetCache,
                                Consumer<Collection<RoleDescriptor>> effectiveRoleDescriptorsConsumer) {
-        this.fileRolesStore = fileRolesStore;
-        this.dlsBitsetCache = dlsBitsetCache;
+        this.fileRolesStore = Objects.requireNonNull(fileRolesStore);
+        this.dlsBitsetCache = Objects.requireNonNull(dlsBitsetCache);
```
Comment (jkakavas) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/store/CompositeRolesStore.java]: Can't make a comment in that line, but we can now remove the null check in line 418
``` java
        if (dlsBitsetCache != null) {
            dlsBitsetCache.clear("role store invalidation");
        }
```

**Review by jkakavas — APPROVED** [review]
LGTM with a minor suggestion

**Comment by jasontedor** [comment]
@bizybot I think this can be backported to 7.4 too?
