### PR TITLE
Fix default value for some settings when filtered

### LINKED ISSUE #136333: ignore_dynamic_beyond_limit has variable default value, conflicting values when queried
### Elasticsearch Version

8.19

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

eck

### Problem Description

[This document](https://www.elastic.co/docs/reference/elasticsearch/index-settings/mapping-limit) states that the default value of `index.mapping.total_fields.ignore_dynamic_beyond_limit` is false, but under some conditions, like using logsdb data stream type, the [default value will be true](https://www.elastic.co/docs/manage-data/data-store/data-streams/logs-data-stream#logs-db-ignore-limit). It would be clearer if the first document also outlined that under some normal conditions, other than a user explicitly setting a non-default value, a different default will be set.

Additionally, when querying this default setting for a logdb datastream, under some conditions it will return true and others it will return false. The actual behavior appears to be true. See repro steps for details.

### Steps to Reproduce

Create a logsdb data stream and leave `ignore_dynamic_beyond_limit` unset.

Query the default setting for `ignore_dynamic_beyond_limit` via `GET /<stream>/_settings/index.mapping.total_fields.ignore_dynamic_beyond_limit?include_defaults=true`. For all indexes in the stream it will return that the default value is false, but it should return true. 

Query all default settings via `GET /<stream>/_settings?include_defaults=true`. For all indexes in the stream it will return that the default value is true.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jordan-powers**
Some settings (such as `index.mapping.total_fields.ignore_dynamic_beyond_limit`) rely on the value of other settings to determine their default value.

When retrieving a setting value or default, the api allows the user to specify a filter, and the returned settings object will be filtered to only include the relevant setting. 

However, we are currently applying this filter to the settings object that we pass to the defaults providers. This means that the other setting(s) which determines the default value for the dependent setting might be hidden by the filter, and so an incorrect default will be returned.

This PR fixes that logic so that the unfiltered set of all set settings is passed into the default values provider.

Fixes #136333

### CODE REVIEW

**Comment by mosche** [comment]
Thanks @jordan-powers!
Would you mind adding an internalClusterTest case for this? 🙏

File: server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsIT.java [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked;
+import static org.hamcrest.Matchers.equalTo;
+
+@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.SUITE)
+public class GetSettingsIT extends ESIntegTestCase {
+    public void testGetDefaultValueWhenDependentOnOtherSettings() {
+        final String indexName = "test-index-1";
+
+        String[][] expectedSettings = {
```
Comment (mosche) [inline server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsIT.java]: Thanks for adding the test!
Though, a nit on that. Could you assert that the filtered response contains nothing else than the filtered key.
That should be fairly easy if making `expectedSettings` a `Settings` object. That way lists are also properly supported.

```Java
Settings expectedSettings = Settings.builder()
    .put("index.mapping.source.mode", "SYNTHETIC")
    ...
    .build();

...

for (String key : expectedSettings.keySet()) {
   ...

    Map<String, Settings> expectedResponse = Map.of(indexName, expectedSettings.filter(key::equals));
    assertThat(
        filteredResponse,
        Matchers.either(LambdaMatchers.transformedMatch(GetSettingsResponse::getIndexToSettings, equalTo(expectedResponse)))
            .or(LambdaMatchers.transformedMatch(GetSettingsResponse::getIndexToDefaultSettings, equalTo(expectedResponse)))
    );
}
```

File: server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsIT.java [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+            { "index.use_time_series_doc_values_format", "true" },
+            { "index.mapping.ignore_above", "8191" },
+            { "index.sort.field", "[@timestamp]" },
+            { "index.sort.order", "[desc]" },
+            { "index.sort.mode", "[max]" },
+            { "index.sort.missing", "[_last]" } };
+
+        assertAcked(prepareCreate(indexName).setSettings(Settings.builder().put("index.mode", "logsdb")).get());
+        for (String[] expectedSetting : expectedSettings) {
+            GetSettingsResponse unfilteredResponse = indicesAdmin().getSettings(
```
Comment (mosche) [inline server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsIT.java]: nit, this could move out of the loop

File: server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsIT.java (hunk 1 above)
Comment (mosche) [reply server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsIT.java]: I'm also wondering how stable these settings will be for index mode`logsdb`. 
If there are settings that are more likely to change, we should better not check them here as that would lead to a rather unexpected place for test failures.

**Review by mosche — APPROVED** [review]
Thanks again for the fix!
I just pointed out some minor nits on the new test case, looking good otherwise :)

File: server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsIT.java (hunk 1 above)
Comment (jordan-powers) [reply server/src/internalClusterTest/java/org/elasticsearch/action/admin/indices/settings/get/GetSettingsIT.java]: I believe these settings should be fairly stable, so it'd be ok to check them here.
