### PR TITLE
Expose http.type setting, and collapse al(most all) modules relating to transport/http

### LINKED ISSUE #14148: How to switch default HttpServerTransport?
Hi, I´m migrating a plugin from 1.5 to 2.0, it switch default NettyHttpServerTransport to add some sort of securiity, but I confused, since 40f119d85a4eaa39d0a6e594e46f70de725557f0 it seems to me that "http.type" parm doesn´t work (see HttpServerTransport.java)

I´m right? Is there any other way to do that? How is supossed I can call setHttpServerTransport?

### PR DESCRIPTION
**Pull request by rjernst**
This change adds back the http.type setting. It also cleans up all the
transport related guice code to be consolidated within the
NetworkModule (as transport and http related stuff is what and how ES
exposes over the network). The setter methods previously used by some
plugins to override eg the TransportService or HttpServerTransport are
removed, and those plugins should now register a custom implementation
of the class with a name and set that using the appropriate config
setting. Note that I think ActionModule should also be moved into here,
to sit along side the rest actions, but I left that for a followup.

closes #14148

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java [hunk 1]
```diff
@@ -19,21 +19,362 @@
...
+            catHandlers.registerExtension(clazz.asSubclass(AbstractCatAction.class));
+        } else {
+            restHandlers.registerExtension(clazz);
+        }
     }
 
     @Override
     protected void configure() {
         bind(NetworkService.class).toInstance(networkService);
+        bind(NamedWriteableRegistry.class).asEagerSingleton();
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: why do we bind this?

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java [hunk 2]
```diff
@@ -19,21 +19,362 @@
...
+
+        transportServiceTypes.bindType(binder(), settings, TRANSPORT_SERVICE_TYPE_KEY, NETTY_TRANSPORT);
+        String defaultTransport = DiscoveryNode.localNode(settings) ? LOCAL_TRANSPORT : NETTY_TRANSPORT;
+        transportTypes.bindType(binder(), settings, TRANSPORT_TYPE_KEY, defaultTransport);
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: can we add logging to what transport is active.. We used to have :

```
logger.info("Using [{}] as http transport, overridden by [{}]", httpServerTransportClass.getName(), source)
```

The source will be hard to do, so I'm fine with dropping it.

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java [hunk 3]
```diff
@@ -19,21 +19,362 @@
...
+    // TODO: we need another name than "http transport"....so confusing with transportClient...
+    public void registerHttpTransport(String name, Class<? extends HttpServerTransport> clazz) {
+        if (transportClient) {
+            throw new IllegalArgumentException("Cannot register http transport " + clazz.getName() + " for transport client");
+        }
+        httpTransportTypes.registerExtension(name, clazz);
+    }
+
+    /** Adds an additional rest action. */
+    // TODO: change this further to eliminate the middle man, ie RestController, and just register method and path here
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: how about preparing the scene and have two methods - registerRestHandler and registerCatHandler? the latter can accept things that extend AbstractCatAction and the first can assert the parameter doesn't inherit from AbstractCatAction and throw the right exception.

File: core/src/test/java/org/elasticsearch/transport/TransportModuleTests.java [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+import org.elasticsearch.Version;
+import org.elasticsearch.common.inject.Inject;
+import org.elasticsearch.common.inject.ModuleTestCase;
+import org.elasticsearch.common.io.stream.NamedWriteableRegistry;
+import org.elasticsearch.common.settings.Settings;
+import org.elasticsearch.test.transport.AssertingLocalTransport;
+import org.elasticsearch.threadpool.ThreadPool;
+
+/** Unit tests for module registering custom transport and transport service */
+public class TransportModuleTests extends ModuleTestCase {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/transport/TransportModuleTests.java]: Intelijj seems to think this is not used...

**Comment by bleskes** [comment]
This is awesome. Left some minor suggestions

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java (hunk 1 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: Because it was bound before in TransportModule.

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java (hunk 3 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: Why would separating them help? It seems more complicated to me. When eliminating RestController, cat actions would still need to have a method and path. The *only* reason this is handled separately right now is so the RestCatAction can iterate over all of them, so it can build "documentation" for what cat actions are available.

File: core/src/test/java/org/elasticsearch/transport/TransportModuleTests.java (hunk 4 above)
Comment (rjernst) [inline core/src/test/java/org/elasticsearch/transport/TransportModuleTests.java]: Oops, removed.

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java (hunk 2 above)
Comment (rjernst) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: That was only when the setter was used before, not a named value. I'm not sure it is really useful, as the user set this in their settings (eg transport.type).  If we really want it, we could do it at debug level, and within ExtensionPoint.SelectedType, but I will leave that as a follow up if you think it is important.

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java (hunk 3 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: ok, sure. I thought you liked the separation. This works for me.

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java (hunk 1 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: oh, I see. It felt like a utility class but it's officially a bless thing. Thanks for pointing it out.

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java (hunk 2 above)
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: I think it's important to know that the transport system is replaced and that the settings have effect. This also has security implications, as plugins can add settings. I think this should stay an info log like it was. Adding something similar to the SelectedType is good but over there debug is the right call indeed - it may be used for many things.

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java [hunk 5]
```diff
@@ -19,21 +19,362 @@
...
+    public static final String TRANSPORT_TYPE_KEY = "transport.type";
+    public static final String TRANSPORT_SERVICE_TYPE_KEY = "transport.service.type";
+
+    public static final String LOCAL_TRANSPORT = "local";
+    public static final String NETTY_TRANSPORT = "netty";
+
+    public static final String HTTP_TYPE_KEY = "http.type";
+    public static final String HTTP_ENABLED = "http.enabled";
+
+    private static final List<Class<? extends RestHandler>> builtinRestHandlers = Arrays.asList(
```
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: cool stuff - I'd kill for these not being .class instances but I think this must be a followup :)

**Comment by s1monw** [comment]
LGTM - awesome

File: core/src/main/java/org/elasticsearch/common/network/NetworkModule.java (hunk 2 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: we can open a new issue to add debug logging to SelectedType but this is really arbitrary here. I don't think this should be info - we have enough info going on and if we reset it we see it in the settings, no need to X different ways to get some information

Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: > we can open a new issue to add debug logging to SelectedType

Agreed. I think it's a good one, but just to be cleared - it's not what I requested.

> but this is really arbitrary here

To me this is a case by case call of what to log on what level. To me changing a transport layer is something that's worth logging under info.

>  we have enough info going on and if we reset it we see it in the settings, no need to X different ways to get some information

It's a valid point that now it's visible in the settings and it's great. Logs are different and some people look at them (at least I did) to see things started up properly.

All of that said I don't under stand why we're discussing this to death. To *me* it would be nice to have this in the log. I'm sure other would as well. It's a low risk, one line change. Unless anyone is strongly against it, I don't understand what prevents us from just taking the feedback and a request for a minor trivial change. The amount of discussion - unless I miss a critical point - is not proportional to what I ask.

Comment (rjernst) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: > It's a low risk, one line change.

It's an arbitrary change, and it adds to noise. We already have tons of stuff in logs. Would you do this just when it is overriden (ie not the default)? Or at all times? What about if they explicitly select netty in their settings? Anything but the first is not a one line change. It woudln't be complicated either, but I don't think we should just willy nilly log things all over, and like said before, I don't think this is useful.

Comment (bleskes) [inline core/src/main/java/org/elasticsearch/common/network/NetworkModule.java]: > Would you do this just when it is overriden (ie not the default)? Or at all times? What about if they explicitly select netty in their settings? Anything but the first is not a one line change.

Yep. Log all the time.

> I don't think we should just willy nilly log things
> I don't think this is useful.

It saddens me that this takes so much effort and discussion.  It is also sad that there is no constructive discussion but rather these yes/no statements. As I said, I find it useful, for the reasons I mentioned. That should be enough for this kind of change. I'm signing out of this now. I don't think it's constructive anymore.
