### PR TITLE
FIx async search tests - do not warn on the presence of .async-search

### LINKED ISSUE #117099: [CI] DocsClientYamlTestSuiteIT test {yaml=reference/esql/esql-across-clusters/line_197} failing
**Build Scans:**
- [elasticsearch-intake #13107 / part1](https://gradle-enterprise.elastic.co/s/mdqjz45dhlfuy)
- [elasticsearch-pull-request #41685 / part-1](https://gradle-enterprise.elastic.co/s/tcr2jmjrsshlk)
- [elasticsearch-pull-request #41424 / part-1](https://gradle-enterprise.elastic.co/s/tf7ugickrvxkk)

**Reproduction Line:**
```
./gradlew ":docs:yamlRestTest" --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/esql/esql-across-clusters/line_197}" -Dtests.seed=A0B22570DB8DDFD8 -Dtests.locale=kab -Dtests.timezone=America/North_Dakota/Beulah -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Byaml%3Dreference%2Fesql%2Fesql-across-clusters%2Fline_197%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.WarningFailureException: method [DELETE], host [http://127.0.0.1:39033], URI [*,-.ds-ilm-history-*,-.ds-.slm-history-*,-.ds-.watcher-history-*?expand_wildcards=open%2Cclosed%2Chidden], status line [HTTP/1.1 200 OK]
Warnings: [this request accesses system indices: [.async-search], but in a future major version, direct access to system indices will be prevented by default]
{"acknowledged":true}
```

**Issue Reasons:**
- [main] 3 failures in test test {yaml=reference/esql/esql-across-clusters/line_197} (0.3% fail rate in 903 executions)
- [main] 2 failures in step part-1 (0.6% fail rate in 344 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (0.6% fail rate in 359 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by smalyshev**
`.async-search` can sometimes appear if async request is slow, and there's no point for the test cleanup to complain about it. 

Fixes https://github.com/elastic/elasticsearch/issues/117099

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -1143,6 +1144,30 @@ protected static void wipeAllIndices(boolean preserveSecurityIndices) throws IOE
         }
     }
 
+    // Make warnings handler that ignores the .async-search warning since .async-search may randomly appear when async requests are slow
```
Comment (bpintea) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1147]:
```suggestion
    // Make warnings handler ignore the .async-search warning since .async-search may randomly appear when async requests are slow
```

**Review by bpintea — APPROVED** [review]

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 1 above)
Comment (original-brownbear) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1147]: Shouldn't we wait for those async requests then maybe? Is the index randomly popping up because we have those complete in the background somehow?

Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1147]: I think we should do both things. We should cancel any outstanding async requests and wait for them to die. I think folks have mostly been doing that in "after" clauses, but I feel like that's something we'd traditionally handle in the teardown code here.

But if the async-search index exists after the test we should trash it so we don't leak any async results from one test to another.

**Comment by smalyshev** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/117372)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java (hunk 1 above)
Comment (smalyshev) [reply test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:1147]: I've made https://github.com/elastic/elasticsearch/issues/117376 so we don't lose track of this concern.
