### PR TITLE
ES|QL: fix EsqlQueryResponseTests.testEqualsAndHashcode

### LINKED ISSUE #113754: [CI] EsqlQueryResponseTests testEqualsAndHashcode failing
**Build Scans:**
- [elasticsearch-periodic #4242 / release-tests](https://gradle-enterprise.elastic.co/s/d6nq2ejtvpcf4)
- [elasticsearch-periodic #4222 / release-tests](https://gradle-enterprise.elastic.co/s/uhviiicmtmqom)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.action.EsqlQueryResponseTests.testEqualsAndHashcode" -Dtests.seed=93DE470BEC9C4D8D -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=su-ID -Dtests.timezone=CAT -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testEqualsAndHashcode'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.action.EsqlQueryResponseTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Issue Reasons:**
- [main] 2 failures in test testEqualsAndHashcode (1.2% fail rate in 170 executions)
- [main] 2 failures in step release-tests (33.3% fail rate in 6 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (33.3% fail rate in 6 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes: #113754

For a specific seed, the test tried to mutate a page made of all UNSUPPORTED columns, leading to an infinite loop (unsupported values are always null)

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/action/EsqlQueryResponseTests.java [hunk 1]
```diff
@@ -236,7 +236,7 @@ private Page randomPage(List<ColumnInfoImpl> columns) {
     protected EsqlQueryResponse mutateInstance(EsqlQueryResponse instance) {
         boolean allNull = true;
         for (ColumnInfoImpl info : instance.columns()) {
-            if (info.type() != DataType.NULL) {
+            if (info.type() != DataType.NULL && info.type() != DataType.UNSUPPORTED) {
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/action/EsqlQueryResponseTests.java:239]: Might be worth adding a comment here that for UNSUPPORTED the `null` value is used throughout the test suite, thus the check here.

**Review by astefan — APPROVED** [review]
LGTM
