### PR TITLE
Fix FileAccessTreeTests#testDuplicateExclusivePaths to work on windows

### LINKED ISSUE #124437: [CI] FileAccessTreeTests testDuplicateExclusivePaths failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #6880 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/hhp3xgpvoasca)
- [elasticsearch-pull-request #61507 / part-1-windows](https://gradle-enterprise.elastic.co/s/4q4czwvupzhym)
- [elasticsearch-pull-request #61507 / part-1-windows](https://gradle-enterprise.elastic.co/s/x33nxvbkoencm)
- [elasticsearch-pull-request #60887 / part-1](https://gradle-enterprise.elastic.co/s/3jak327pkckkw)
- [elasticsearch-pull-request #60527 / part-1-windows](https://gradle-enterprise.elastic.co/s/avv3zkk36qujs)

**Reproduction Line:**
```
gradlew ":libs:entitlement:test" --tests "org.elasticsearch.entitlement.runtime.policy.FileAccessTreeTests.testDuplicateExclusivePaths" -Dtests.seed=3449CDA387F2CFFA -Dtests.locale=mer-Latn-KE -Dtests.timezone=America/Santo_Domingo -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.entitlement.runtime.policy.FileAccessTreeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testDuplicateExclusivePaths),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: "Path [/a/b] is already exclusive to [component1][module1], cannot add exclusive access for [component2][module1]"
     but: was "Path [C:\\a\\b] is already exclusive to [component1][module1], cannot add exclusive access for [component2][module1]"
```

**Issue Reasons:**
- [main] 2 consecutive failures in step part-1-windows
- [main] 5 failures in test testDuplicateExclusivePaths (0.6% fail rate in 820 executions)
- [main] 3 failures in step part-1-windows (60.0% fail rate in 5 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.9% fail rate in 334 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ldematte**
Fix PolicyManagerTests#testFilesEntitlementsWithExclusive

Fixes https://github.com/elastic/elasticsearch/issues/124437

### CODE REVIEW

**Comment by prdoyle** [comment]
This change seems super subtle. I can't see a difference in the behaviour; how does this fix the tests?

File: libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/PolicyManagerTests.java [hunk 1]
```diff
@@ -447,7 +447,9 @@ public void testDuplicateEntitlements() {
     public void testFilesEntitlementsWithExclusive() {
         var baseTestPath = Path.of("/base").toAbsolutePath();
         var testPath1 = Path.of("/base/test").toAbsolutePath();
+        var testPath1String = testPath1.toString();
```
Comment (prdoyle) [inline libs/entitlement/src/test/java/org/elasticsearch/entitlement/runtime/policy/PolicyManagerTests.java:450]: I thought these `toString` calls are not needed if the `Strings.format` call is using `%s`?

**Comment by ldematte** [comment]
> This change seems super subtle. I can't see a difference in the behaviour; how does this fix the tests?

By forcing the same string

Failure was:

expected "Path [/a/b] ..." found "Path [C:\a\b] ... " on windows.

**Comment by ldematte** [comment]
Actually you are right, the second one is a red herring, it was not the same issue and it's fixed by Ryan's PR. I'll remove it.

**Review by prdoyle — APPROVED** [review]

**Comment by ldematte** [comment]
Backports need https://github.com/elastic/elasticsearch/pull/123676
