### PR TITLE
Use SearchStats instead of field.isAggregatable in data node planning

### LINKED ISSUE #115737: Lucene pushdown does not work when doc-values are disabled
Since ES|QL makes use of field-caps and only considers `isAggregatable` during Lucene pushdown, turning off doc-values disables Lucene pushdown. For spatial types, this is incorrect. The physical planning decision for Lucene pushdown is made during local planning on the data node, at which point `SearchStats` are known, and both `isIndexed` and `hasDocValues` are separately knowable. The Lucene pushdown should happen for `isIndexed` and not consider `hasDocValues` at all.

### PR DESCRIPTION
**Pull request by craigtaverner**
Since ES|QL makes use of field-caps and only considers `isAggregatable` during Lucene pushdown, turning off doc-values disables Lucene pushdown. This is incorrect. The physical planning decision for Lucene pushdown is made during local planning on the data node, at which point `SearchStats` are known, and both `isIndexed` and `hasDocValues` are separately knowable. The Lucene pushdown should happen for `isIndexed` and not consider `hasDocValues` at all.

This PR adds hasDocValues to SearchStats and the uses isIndexed and hasDocValue separately during local physical planning on the data nodes. This immediately cleared up one issue for spatial data, which could not push down a lucene query when doc-values was disabled.

Summary of what `isAggregatable` means for different implementations of `MappedFieldType`:
* Default implementation of `isAggregatable` in `MappedFieldType` is `hasDocValues`, and does not consider `isIndexed`
* All classes that extend `AbstractScriptFieldType` (eg. `LongScriptFieldType`) hard coded `isAggregatable` to `true`. This presumably means Lucene is happy to mimic having doc-values
* `TestFieldType`, and classes that extend it, return the value of `fielddata`, so consider the field aggregatable if there is field-data.
* `AggregateDoubleMetricFieldType` and `ConstantFieldType` hard coded to `true`
* `DenseVectorFieldType` hard coded to `false`
* `IdFieldType` return the value of `fieldDataEnabled.getAsBoolean()`

In no case is `isIndexed` used for `isAggregatable`. However, for our Lucene pushdown of filters, `isIndexed` would make a lot more sense. But for pushdown of TopN, `hasDocValues` makes more sense.

Summarising the results of the various options for the various field types, where `?` means configrable:

| Class | isAggregatable | isIndexed | isStored | hasDocValues |
| --- | --- | --- | --- | --- |
| AbstractScriptFieldType                 | true  | false | false | false |
| AggregateDoubleMetricFieldType | true  | true  | false | false |
| DenseVectorFieldType                    | false | ?       | false | !indexed |
| IdFieldType                                      | fieldData | true | true | false |
| TsidExtractingIdField                       | false | true | true | false |
| TextFieldType                                   | fieldData | ? | ? | false |
| ? (the rest)                                        | hasDocValues | ? | ? | ? |

It has also been observed that we cannot push filters to source without checking `hasDocValues` when we use the `SingleValueQuery`. So this leads to three groups of conditions:

| Category | require `indexed` | require `docValues` |
| --- | --- | --- |
| Filters(single-value) | true | true |
| Filters(multi-value) | true | false |
| TopN | true | true |

And for all cases we will also consider `isAggregatable` as a disjunction to cover the script field types, leading to two possible combinations:

* `fa.isAggregatable() || searchStats.isIndexed(fa.name()) && searchStats.hasDocValues(fa.name())`
* `fa.isAggregatable() || searchStats.isIndexed(fa.name())`

Fixes #115737

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java [hunk 1]
```diff
@@ -252,6 +254,26 @@ public boolean isIndexed(String field) {
...
+            stat.hasDocValues = false;
+            if (exists(field)) {
+                boolean hasDocValues = true;
+                for (SearchExecutionContext context : contexts) {
+                    if (context.isFieldMapped(field)) {
+                        if (context.getFieldType(field).hasDocValues() == false) {
+                            hasDocValues = false;
+                            break;
+                        }
+                    }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java:269]: Since exists() doesn't return the information fully, since it's the same code underneath, how about copying its implementation inside docValues and performing the hasDocValues() check as well - so there's only one SearchExecutionContext loop and the same context is called twice?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java [hunk 2]
```diff
@@ -51,6 +51,7 @@ private static class FieldStat {
         private Boolean singleValue;
         private Boolean hasIdenticalDelegate;
         private Boolean indexed;
+        private Boolean hasDocValues;
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java:54]: looks like the naming convention is to have no has prefix so `docValues`

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushTopNToSource.java [hunk 3]
```diff
@@ -60,7 +62,9 @@
 public class PushTopNToSource extends PhysicalOptimizerRules.ParameterizedOptimizerRule<TopNExec, LocalPhysicalOptimizerContext> {
     @Override
     protected PhysicalPlan rule(TopNExec topNExec, LocalPhysicalOptimizerContext ctx) {
-        Pushable pushable = evaluatePushable(topNExec, x -> LucenePushDownUtils.hasIdenticalDelegate(x, ctx.searchStats()));
+        Predicate<FieldAttribute> hasIdenticalDelegate = (fa) -> LucenePushDownUtils.hasIdenticalDelegate(fa, ctx.searchStats());
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushTopNToSource.java:65]: would be useful to rename this method to something more meaningful such as `hasExactFallback`.

**Review by costin — COMMENTED** [review]
👍 
It's a good direction and having this information locally is good.
Please state FTR, what turns on/off isAggregateable in field_caps as there might be other cases where this information is not useful.

Secondly, please look at the impact of removing isAggregatable from EsField.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java (hunk 1 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java:269]: I agree. This pattern of doing the loop for each parameter exists for a few pre-existing methods, so I kept it that way, but probably it would be better to instead capture them all in one go. I think no-one cared before because this check is not in performance critical runtime code, but in some planning code. By merging loops we would primarily share the `isFIeldMapped` and `getFieldType` calls on the `SearchExecutionContext`. All the rest if different between loops.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java (hunk 2 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java:54]: Or add `is` and `has` prefixes to the rest... (which might conform better to the naming contexts elsewhere).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushTopNToSource.java (hunk 3 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/PushTopNToSource.java:65]: While this method pre-dates my work (was added almost a year ago), I agree that the name is not entirely clear, and my last commit also changed slightly what is checked deeper down too. However, the name `hasExactFallback` is also insufficient (and to my ears sounds synonymous with what we already have). We check if the TEXT field-type has a surrogate and then make several checks on the nature of that surrogate. Any name that fully captures what is checked will be unreasonably long, which is why I kept the original name coded before.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java (hunk 1 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchStats.java]: OK. I separated the FieldStat into two groups, things that are simple config settings, like `exists`, `indexed`, `hasDocValues` and `hasIdenticalDelegate`, and other things that might take longer to retrieve. The first set are in a record created in a single pass loop (as you suggested). The rest are accessed on demand. I also made refactoring less flaky by not having all test versions extend the production version. I also deleted the entire unused methods for getting `min` and `max`, and think we should only add those back if (hopefully when) we use them.

File: x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java [hunk 4]
```diff
@@ -245,10 +263,76 @@ public byte[] max(String field, DataType dataType) {
...
+            return isConfigationSet(Config.INDEXED, field);
+        }
+
+        @Override
+        public boolean hasDocValues(String field) {
+            return isConfigationSet(Config.DOC_VALUES, field);
+        }
+
+        @Override
+        public boolean hasIdenticalDelegate(String field) {
```
Comment (costin) [inline x-pack/plugin/esql/qa/testFixtures/src/main/java/org/elasticsearch/xpack/esql/EsqlTestUtils.java:329]: Since PR does renaming, I propose to change this to something more clearer such as "hasFallbackSubfield" / "hasExactSubfield" or something similar.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+    /**
+     * For TEXT fields, we need to check if the field has an identical delegate.
+     */
+    boolean hasIdenticalDelegate(FieldAttribute attr);
+
+    /**
+     * For pushing down TopN and for pushing down filters with SingleValueQuery,
+     * we need to check if the field is indexed and has doc values.
+     */
+    boolean isIndexedAndDocValues(FieldAttribute attr);
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:39]: isIndexedAndHasDocValues? :)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+ *         and this requires knowing if the field is indexed and has doc-values.</li>
+ *     <li>A filter using a spatial function will allow multi-valued fields and we only need to know if the field is indexed,
+ *         and do not need doc values.</li>
+ *     <li>A TopN will be pushed down if the field is indexed and has doc values.</li>
+ *     <li>Filters with TEXT fields can only be pushed down if the TEXT field has a nested KEYWORD field,
+ *         referred to here as IdenticalDelegate. This that this is related to normal ES|QL predicates,
+ *         not the full-text search provided by the MATCH and QSTR functions, which are pushed down separately.</li>
+ * </ol>
+ */
+public interface LucenePushdownPredicates {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:29]: Do we still need the default implementation ? I wonder how out of sync it will become with respect to SearchStats.

Separately there's a lot in this class - it defines both an interface, its implementations and acts as a factory so I suggest decomposing it:
1. have FieldAttribute in the name since all methods resolve around that - e.g. LucenePushDown, LuceneFieldInfo,  etc...
2. Move the two implementation into a Xs class such as LucenePushDowns, LuceneFieldInfos,  (like we do for DataType and DataTypes) :  LucenePushDowns.DEFAULT or LucenePushDowns.from(SearchStats)

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+     * The reason we don't just rely entirely on <code>isAggregatable</code> is because this is often false for normal fields, and could
+     * also differ from node to node, and we can physically plan each node separately, allowing Lucene pushdown on the nodes that
+     * support it, and relying on the compute engine for the nodes that do not.
+     */
+    default boolean isPushableFieldAttribute(Expression exp) {
+        if (exp instanceof FieldAttribute fa && fa.getExactInfo().hasExact() && isIndexedAndDocValues(fa)) {
+            return (fa.dataType() != DataType.TEXT && fa.dataType() != DataType.SEMANTIC_TEXT) || hasIdenticalDelegate(fa);
+        }
+        return false;
+    }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:60]: This method  can be moved in the LucenePushdownS (or whatever name you decide).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchContextStats.java [hunk 8]
```diff
@@ -0,0 +1,357 @@
...
+                        throw new EsqlIllegalArgumentException("Don't know how to compare with previous min");
+                    }
+                }
+                return true;
+            }, true);
+            stat.min = min[0];
+        }
+        // return stat.min;
+        return null;
+    }
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchContextStats.java:193]: Could Ignacio help finalize these two methods (min and max)?
The min and max come handy with range queries (e.g. `WHERE x < 10`  gets folded to false if x min is 10+).

**Review by costin — APPROVED** [review]
Left some minor comments otherwise LGTM

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java (hunk 5 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:39]: Done.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java (hunk 6 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/local/LucenePushdownPredicates.java:29]: The recent work on MATCH has removed one of the three usages of the DEFAULT implementation. One other is test-only so could be refactored away, but the remaining use persists. It is in the `ComputeEngine.startComputeOnDataNodes` method, which creates a filter on `@timestamp` based on the current plan before we even know the separate data nodes, or individual SearchExecutionContexts to be used for creating the `SearchStats`. I'm maintaining the exact same behaviour here (ie. I did not want to change anything here, other than naming), although perhaps we would want to revisit this later. If so, we should do that in another PR.

(The above mentioned test-only usage is in `FilterTests`, but if we got rid of the ComputeEngine usage, we could mock SearchStats in FilterTests to get around that usage too, again a task for another PR if we desire it).

Regarding splitting the file into multiple files, I actually prefer the current approach because it is a simple interface with two simple implementations, and I think it is much easier to reason about with all three in the same file (which remains a very small file).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchContextStats.java (hunk 8 above)
Comment (craigtaverner) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/stats/SearchContextStats.java:193]: The `min` and `max` methods were coded in the original `SearchStats`, but as yet have never been used. I actually favour removing them, and only adding them back when they get used. A feature to fold `WHERE x < 10` to `false` on a per-shard or per collections of shards basis is certainly a nice feature, and I will discuss this with Ignacio.
