### PR TITLE
Lift the restrictions that uppercase is not allowed in Setting Name.

### LINKED ISSUE #43835: [DOCS] Clarify keystore format in breaking changes 7.0
Reading [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#watcher-notifications-account-settings) it is clear we have to use keystore.

It would be good to add clarification regarding keystore format. 

Before 7.0 we could have setting in elasticsearch.yml
```xpack.notification.pagerduty.account.TEST.service_api_key```

In 7.0 we will need 
```xpack.notification.pagerduty.account.TEST.secure_service_api_key```

However this format is not valid when adding to keystore (bin/elasticsearch-keystore add xpack.notification.pagerduty.account.TEST.secure_service_api_key) we get:
```ERROR: Setting name [xpack.notification.pagerduty.account.TEST.secure_service_api_key] does not match the allowed setting name pattern [[a-z0-9_\-.]+]```

In this case account format in elasticsearch.yml will have to change as well.

### PR DESCRIPTION
**Pull request by FreshOrangeXC**
Closes #43835

### CODE REVIEW

**Comment by tvernum** [comment]
The lowercase requirement was intentionally added in https://github.com/elastic/elasticsearch/pull/27626, but at the time the keystore was implemented using a PKCS#12 keystore, which is no longer the case. 

There's the potential to relax that requirement now that the keystore uses a custom storage format with UTF strings.
@rjernst thoughts?

**Comment by rjernst** [comment]
@tvernum You are correct this was a limitation from the time when we used PKCS#12.

@FreshOrangeXC Could you please update the test for this limitation in `KeyStoreWrapperTests.testIllegalSettingName()`? We can just change it to use a special character instead of upper case.

Also note this is not actually a format change, just a relaxing of restrictions on the tool itself.

**Comment by FreshOrangeXC** [comment]
@rjernst Ok, I will do it.

File: distribution/tools/keystore-cli/src/test/java/org/elasticsearch/common/settings/AddStringKeyStoreCommandTests.java [hunk 1]
```diff
@@ -176,16 +176,6 @@ public void testMissingSettingName() throws Exception {
         assertThat(e.getMessage(), containsString("The setting name can not be null"));
     }
 
-    public void testUpperCaseInName() throws Exception {
```
Comment (rjernst) [inline distribution/tools/keystore-cli/src/test/java/org/elasticsearch/common/settings/AddStringKeyStoreCommandTests.java]: We shoudl keep this test, but rename it and use a special character instead of uppercase.

**Review by rjernst — CHANGES_REQUESTED** [review]

**Review by FreshOrangeXC — COMMENTED** [review]
How to use the RandomizedTest class create a random special character? Or I just use a specific special character "@" like this commit?

**Comment by rjernst** [comment]
@elasticmachine ok to test

**Comment by FreshOrangeXC** [comment]
Oh, It seems test failed but I don't know why.

**Comment by rjernst** [comment]
I think the branch needs to be synced with master.

@elasticmachine update branch

**Comment by rjernst** [comment]
@elasticmachine update branch

**Comment by FreshOrangeXC** [comment]
@elasticmachine update branch

**Comment by rjernst** [comment]
There are a few build failures that need to be addressed. Another test has illegal setting name checking: `org.elasticsearch.common.settings.SettingsTests.testSecureSettingIllegalName`. Also, there are some checkstyle failures (line lengths and unused imports). Running `./gradlew :server:precommit :server:test` should allow you to reproduce the failures locally.

**Comment by FreshOrangeXC** [comment]
I got it. I will solve it.

**Comment by FreshOrangeXC** [comment]
@elasticmachine update branch

**Comment by FreshOrangeXC** [comment]
@elasticmachine update branch

**Comment by FreshOrangeXC** [comment]
@elasticmachine updata branch

**Comment by FreshOrangeXC** [comment]
@elasticmachine update branch

**Comment by FreshOrangeXC** [comment]
@rjernst Test passed.

**Comment by rjernst** [comment]
@elasticmachine update branch

**Comment by rjernst** [comment]
Thanks for the contribution @FreshOrangeXC!

**Comment by FreshOrangeXC** [comment]
It is my pleasure to contribute to the open source.
