### PR TITLE
Fix NPE in EnrichLookupService on mixed clusters with <8.14 versions

### LINKED ISSUE #116529: [CI] EsqlClientYamlIT test {p0=esql/61_enrich_ip/IP strings} failing
**Build Scans:**
- [elasticsearch-periodic #4786 / 8.13.4_bwc](https://gradle-enterprise.elastic.co/s/oyorwichebtf4)
- [elasticsearch-pull-request #40468 / 8.13.4_bwc](https://gradle-enterprise.elastic.co/s/4nadaxpo6lh4a)
- [elasticsearch-pull-request #40468 / 8.12.2_bwc](https://gradle-enterprise.elastic.co/s/mvribf3qhi3ve)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:mixed-cluster:v8.13.4#yamlRestTest" -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT" -Dtests.method="test {p0=esql/61_enrich_ip/IP strings}" -Dtests.seed=428BBA97DEF79736 -Dtests.bwc=true -Dtests.locale=csw-Cans-CA -Dtests.timezone=US/Pacific -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Desql%2F61_enrich_ip%2FIP%20strings%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [esql/61_enrich_ip:112]: expected [2xx] status code but api [esql.query] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"null_pointer_exception","reason":"Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\" because \"inputDataType\" is null","stack_trace":"org.elasticsearch.ElasticsearchException$1: Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\" because \"inputDataType\" is null\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:701)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:629)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.RestResponse.build(RestResponse.java:184)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:143)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:114)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:55)\n\tat org.elasticsearch.xpack.esql.action.EsqlResponseListener.lambda$wrapWithLogging$1(EsqlResponseListener.java:173)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:179)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.action.RestCancellableNodeClient$1.onFailure(RestCancellableNodeClient.java:96)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:324)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:214)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:317)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:324)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\tat org.elasticsearch.xpack.esql.plugin.ComputeService.lambda$execute$1(ComputeService.java:147)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:186)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:191)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:317)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:324)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:324)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.RefCountingListener.finish(RefCountingListener.java:127)\n\tat org.elasticsearch.base@8.13.4/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)\n\tat org.elasticsearch.base@8.13.4/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)\n\tat org.elasticsearch.base@8.13.4/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:151)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.RefCountingListener$1.onResponse(RefCountingListener.java:146)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:269)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:314)\n\tat org.elasticsearch.xpack.esql.plugin.ComputeService.lambda$startComputeOnDataNodes$13(ComputeService.java:298)\n\tat org.elasticsearch.base@8.13.4/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:118)\n\tat org.elasticsearch.base@8.13.4/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:70)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:112)\n\tat org.elasticsearch.base@8.13.4/org.elasticsearch.core.Releasables$4.close(Releasables.java:159)\n\tat org.elasticsearch.base@8.13.4/org.elasticsearch.core.Releasables.close(Releasables.java:34)\n\tat org.elasticsearch.base@8.13.4/org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:56)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:49)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:280)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:324)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:53)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1751)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1475)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1609)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.transport.TransportService$DirectResponseChannel$2.doRun(TransportService.java:1589)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.lang.NullPointerException: Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\" because \"inputDataType\" is null\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService.termQueryList(AbstractLookupService.java:185)\n\tat org.elasticsearch.xpack.esql.enrich.EnrichLookupService.queryList(EnrichLookupService.java:82)\n\tat org.elasticsearch.xpack.esql.enrich.EnrichLookupService.queryList(EnrichLookupService.java:42)\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService.doLookup(AbstractLookupService.java:328)\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService$TransportHandler.messageReceived(AbstractLookupService.java:433)\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService$TransportHandler.messageReceived(AbstractLookupService.java:428)\n\tat org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:76)\n\tat org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:289)\n\tat org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:302)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.lang.Thread.run(Thread.java:1575)\n"}],"type":"null_pointer_exception","reason":"Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\" because \"inputDataType\" is null","stack_trace":"java.lang.NullPointerException: Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\" because \"inputDataType\" is null\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService.termQueryList(AbstractLookupService.java:185)\n\tat org.elasticsearch.xpack.esql.enrich.EnrichLookupService.queryList(EnrichLookupService.java:82)\n\tat org.elasticsearch.xpack.esql.enrich.EnrichLookupService.queryList(EnrichLookupService.java:42)\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService.doLookup(AbstractLookupService.java:328)\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService$TransportHandler.messageReceived(AbstractLookupService.java:433)\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService$TransportHandler.messageReceived(AbstractLookupService.java:428)\n\tat org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:76)\n\tat org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:289)\n\tat org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:302)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)\n\tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.lang.Thread.run(Thread.java:1575)\n"},"status":500}]
```

**Issue Reasons:**
- [8.x] 3 failures in test test {p0=esql/61_enrich_ip/IP strings} (2.5% fail rate in 120 executions)
- [8.x] 2 failures in step 8.13.4_bwc (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #116544: [CI] EsqlClientYamlIT test {p0=esql/62_extra_enrich/Enrich fields includes match field} failing
**Build Scans:**
- [elasticsearch-periodic #4826 / 8.13.4_bwc](https://gradle-enterprise.elastic.co/s/sumvvkidtw4bk)
- [elasticsearch-periodic #4826 / 8.12.2_bwc](https://gradle-enterprise.elastic.co/s/asndltdj2kxmg)
- [elasticsearch-periodic #4821 / 8.12.2_bwc](https://gradle-enterprise.elastic.co/s/p3z2c2psoefns)
- [elasticsearch-periodic #4811 / 8.13.4_bwc](https://gradle-enterprise.elastic.co/s/rv5j5u4sfajwq)
- [elasticsearch-periodic #4801 / 8.12.2_bwc](https://gradle-enterprise.elastic.co/s/dgurabpgehvdk)
- [elasticsearch-periodic #4786 / 8.13.4_bwc](https://gradle-enterprise.elastic.co/s/oyorwichebtf4)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:mixed-cluster:v8.13.4#yamlRestTest" -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT" -Dtests.method="test {p0=esql/62_extra_enrich/Enrich fields includes match field}" -Dtests.seed=7DB169E6BCEC13AD -Dtests.bwc=true -Dtests.locale=chr -Dtests.timezone=SystemV/PST8 -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Desql%2F62_extra_enrich%2FEnrich%20fields%20includes%20match%20field%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [esql/62_extra_enrich:57]: expected [2xx] status code but api [esql.query] returned [500 Internal Server Error] [---
error:
  root_cause:
  - type: "null_pointer_exception"
    reason: "Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\"\
      \ because \"inputDataType\" is null"
    stack_trace: "org.elasticsearch.ElasticsearchException$1: Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\"\
      \ because \"inputDataType\" is null\n\tat org.elasticsearch.server@8.13.4/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:701)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:629)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.RestResponse.build(RestResponse.java:184)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:143)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:114)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.action.RestActionListener.onFailure(RestActionListener.java:55)\n\
      \tat org.elasticsearch.xpack.esql.action.EsqlResponseListener.lambda$wrapWithLogging$1(EsqlResponseListener.java:173)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:179)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.rest.action.RestCancellableNodeClient$1.onFailure(RestCancellableNodeClient.java:96)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:324)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:214)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:317)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:324)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\
      \tat org.elasticsearch.xpack.esql.plugin.ComputeService.lambda$execute$1(ComputeService.java:147)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:186)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:191)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onFailure(ActionListenerImplementations.java:317)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:324)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:31)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onFailure(ActionListenerImplementations.java:278)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$3.onFailure(ActionListener.java:324)\n\
      \tat org.elasticsearch.compute.operator.DriverRunner$1.done(DriverRunner.java:82)\n\
      \tat org.elasticsearch.compute.operator.DriverRunner$1.onFailure(DriverRunner.java:73)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.SubscribableListener$FailureResult.complete(SubscribableListener.java:378)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:290)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:189)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:165)\n\
      \tat org.elasticsearch.compute.operator.Driver.abort(Driver.java:183)\n\tat\
      \ org.elasticsearch.compute.operator.DriverTaskRunner$1.lambda$start$0(DriverTaskRunner.java:60)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:62)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.action.ActionListener$2.onFailure(ActionListener.java:179)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.transport.TransportResponseHandler$1.handleException(TransportResponseHandler.java:63)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1751)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1475)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1609)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.transport.TransportService$DirectResponseChannel$2.doRun(TransportService.java:1589)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)\n\
      \tat org.elasticsearch.server@8.13.4/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)\n\
      \tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\
      \tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\
      \tat java.base/java.lang.Thread.run(Thread.java:1583)\nCaused by: java.lang.NullPointerException:\
      \ Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\"\
      \ because \"inputDataType\" is null\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService.termQueryList(AbstractLookupService.java:185)\n\
      \tat org.elasticsearch.xpack.esql.enrich.EnrichLookupService.queryList(EnrichLookupService.java:82)\n\
      \tat org.elasticsearch.xpack.esql.enrich.EnrichLookupService.queryList(EnrichLookupService.java:42)\n\
      \tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService.doLookup(AbstractLookupService.java:328)\n\
      \tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService$TransportHandler.messageReceived(AbstractLookupService.java:433)\n\
      \tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService$TransportHandler.messageReceived(AbstractLookupService.java:428)\n\
      \tat org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:76)\n\
      \tat org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:289)\n\
      \tat org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:302)\n\
      \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\
      \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\
      \tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)\n\
      \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\
      \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\
      \tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\
      \tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\
      \tat java.lang.Thread.run(Thread.java:1575)\n"
  type: "null_pointer_exception"
  reason: "Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\"\
    \ because \"inputDataType\" is null"
  stack_trace: "java.lang.NullPointerException: Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.ordinal()\"\
    \ because \"inputDataType\" is null\n\tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService.termQueryList(AbstractLookupService.java:185)\n\
    \tat org.elasticsearch.xpack.esql.enrich.EnrichLookupService.queryList(EnrichLookupService.java:82)\n\
    \tat org.elasticsearch.xpack.esql.enrich.EnrichLookupService.queryList(EnrichLookupService.java:42)\n\
    \tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService.doLookup(AbstractLookupService.java:328)\n\
    \tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService$TransportHandler.messageReceived(AbstractLookupService.java:433)\n\
    \tat org.elasticsearch.xpack.esql.enrich.AbstractLookupService$TransportHandler.messageReceived(AbstractLookupService.java:428)\n\
    \tat org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:76)\n\
    \tat org.elasticsearch.transport.InboundHandler.doHandleRequest(InboundHandler.java:289)\n\
    \tat org.elasticsearch.transport.InboundHandler$1.doRun(InboundHandler.java:302)\n\
    \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\
    \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\
    \tat org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)\n\
    \tat org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)\n\
    \tat org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)\n\
    \tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\
    \tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\
    \tat java.lang.Thread.run(Thread.java:1575)\n"
status: 500
]
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in test test {p0=esql/62_extra_enrich/Enrich fields includes match field}
- [8.x] 6 failures in test test {p0=esql/62_extra_enrich/Enrich fields includes match field} (3.2% fail rate in 190 executions)
- [8.x] 3 failures in step 8.13.4_bwc (30.0% fail rate in 10 executions)
- [8.x] 3 failures in step 8.12.2_bwc (30.0% fail rate in 10 executions)
- [8.x] 5 failures in pipeline elasticsearch-periodic (55.6% fail rate in 9 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/116529
Fixes https://github.com/elastic/elasticsearch/issues/116544

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java [hunk 1]
```diff
@@ -127,9 +127,9 @@ static TransportRequest readFrom(StreamInput in, BlockFactory blockFactory) thro
             TaskId parentTaskId = TaskId.readFromStream(in);
             String sessionId = in.readString();
             ShardId shardId = new ShardId(in);
-            DataType inputDataType = DataType.fromTypeName(
-                (in.getTransportVersion().onOrAfter(TransportVersions.V_8_14_0)) ? in.readString() : "unknown"
-            );
+            DataType inputDataType = (in.getTransportVersion().onOrAfter(TransportVersions.V_8_14_0))
+                ? DataType.fromTypeName(in.readString())
+                : null;
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java:132]: This returned a null before (`DataType.fromTypeName("unknown") == null`), I'm just making it obvious

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/AbstractLookupService.java [hunk 2]
```diff
@@ -185,7 +186,7 @@ protected static QueryList termQueryList(
         return switch (inputDataType) {
             case IP -> QueryList.ipTermQueryList(field, searchExecutionContext, (BytesRefBlock) block);
             case DATETIME -> QueryList.dateTermQueryList(field, searchExecutionContext, (LongBlock) block);
-            default -> QueryList.rawTermQueryList(field, searchExecutionContext, block);
+            case null, default -> QueryList.rawTermQueryList(field, searchExecutionContext, block);
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/AbstractLookupService.java:189]: `default` doesn't include nulls for enums (As enums call `v.ordinal()` in switches), and it throws unless an explicit null case is added.
Another interesting thing, is that the `case null, default` syntax is the only way to combine null or default cases!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/AbstractLookupService.java [hunk 3]
```diff
@@ -459,6 +460,7 @@ abstract static class Request {
     abstract static class TransportRequest extends org.elasticsearch.transport.TransportRequest implements IndicesRequest {
         final String sessionId;
         final ShardId shardId;
+        @Nullable
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/AbstractLookupService.java:463]: Could you add a javadoc to this one saying it's null for versions before <WHATEVER VERSION IT IS>?

**Review by nik9000 — APPROVED** [review]
Thanks!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/AbstractLookupService.java (hunk 3 above)
Comment (ivancea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/AbstractLookupService.java:466]: Done

**Review by nik9000 — APPROVED** [review]

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/AbstractLookupService.java (hunk 3 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/AbstractLookupService.java:466]: Ah! `&lt;`. I thought that might be a problem.....
