### PR TITLE
Fix rare serialization failure in SuggestTests

### LINKED ISSUE #95607: [CI] SuggestTests testSerialization failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/fjxuohetdjmqq/tests/:server:test/org.elasticsearch.search.suggest.SuggestTests/testSerialization

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.search.suggest.SuggestTests.testSerialization" -Dtests.seed=7C2E1080054FE574 -Dtests.locale=mk -Dtests.timezone=Chile/EasterIsland -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.search.suggest.SuggestTests&tests.test=testSerialization

**Failure excerpt:**
```
java.lang.IllegalArgumentException: cannot serialize [rank] to version [8060299]

  at __randomizedtesting.SeedInfo.seed([7C2E1080054FE574:28F671C8221DD8E8]:0)
  at org.elasticsearch.search.SearchHit.writeTo(SearchHit.java:248)
  at org.elasticsearch.search.suggest.completion.CompletionSuggestion$Entry$Option.writeTo(CompletionSuggestion.java:408)
  at org.elasticsearch.common.io.stream.StreamOutput.lambda$writeCollection$33(StreamOutput.java:1026)
  at org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1045)
  at org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1026)
  at org.elasticsearch.search.suggest.Suggest$Suggestion$Entry.writeTo(Suggest.java:545)
  at org.elasticsearch.common.io.stream.StreamOutput.lambda$writeCollection$33(StreamOutput.java:1026)
  at org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1045)
  at org.elasticsearch.common.io.stream.StreamOutput.writeCollection(StreamOutput.java:1026)
  at org.elasticsearch.common.io.stream.StreamOutput.writeList(StreamOutput.java:1033)
  at org.elasticsearch.search.suggest.Suggest$Suggestion.writeTo(Suggest.java:320)
  at org.elasticsearch.search.suggest.completion.CompletionSuggestion.writeTo(CompletionSuggestion.java:84)
  at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteable(StreamOutput.java:976)
  at org.elasticsearch.common.io.stream.StreamOutput.writeNamedWriteableList(StreamOutput.java:1098)
  at org.elasticsearch.search.suggest.Suggest.writeTo(Suggest.java:115)
  at org.elasticsearch.search.suggest.SuggestTests.testSerialization(SuggestTests.java:255)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by cbuescher**
SuggestTests uses a fairly recursive way to create its test item. Those can end up with an CompletionSuggestion.Entry.Option that have a "rank" field set to something other than the bwc default of -1. The test still tries to test the serialization roundtrip to a random transport version down to TransportVersions.MINIMUM_COMPATIBLE which is currently at V_7_17_0, but the rank field serialization fails for anything below V_8_8_0. In reality however, suggester options shouldn't contain search hits with a set rank field, so simples way to avoid it is checking the randomly created test item for those cases and correct them before running the test.

Closes #95607

### CODE REVIEW

**Comment by cbuescher** [comment]
After having looked at https://github.com/elastic/elasticsearch/blob/92cea2797e811680e05151c8805e16c003db84d4/server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java#L385 I'm not entirely sure anymore we can never have a "rank" field in a completion suggester option search hit. But it would be rather strange. @jdconrad do you know if you can mix RRF and suggestions? If so that would probably be something to forbid in a follow up.

**Comment by cbuescher** [comment]
Seed that currently triggers the failure in SuggestTests#testSerialization directly has changed to "7CB74B835EA72E4B", if you want to try repro without this change.

File: server/src/test/java/org/elasticsearch/search/suggest/SuggestTests.java [hunk 1]
```diff
@@ -248,6 +247,22 @@ public void testSerialization() throws IOException {
         );
 
         final Suggest suggest = createTestItem();
+        // if bwc version is below V_8_8_0 we need to make sure potential
+        // search hits in CompletionSuggestion$Entry$Option don't have "rank" set
+        // TODO remove this once MINIMUM_COMPATIBLE > V_8_8_0
+        if (bwcVersion.before(TransportVersions.V_8_8_0)) {
```
Comment (romseygeek) [inline server/src/test/java/org/elasticsearch/search/suggest/SuggestTests.java:253]: Does it make sense to change this TODO into an assertion, so that when we upgrade it will fail CI and prompt whoever is doing it to remove the block?

**Comment by jdconrad** [comment]
@cbuescher Suggest should be disallowed when using rank.

**Comment by cbuescher** [comment]
> @cbuescher Suggest should be disallowed when using rank.

@jdconrad thats what I thought, and that's more or less what this change does, it makes sure we don't have the "rank" property set in the randomized completion suggest entry. I will remove the TODO so its clear that this is not a workaround but the expectation. Its much work to integrate this into the randomization itself because its quite nested, so I hope you find it okay to do it here after the fact.

**Review by jdconrad — APPROVED** [review]
