### PR TITLE
Include last-committed data in publication

### LINKED ISSUE #90158: [CI] CoordinatorTests testUnhealthyLeaderIsReplaced failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/j4xfvozocqmng/tests/:server:test/org.elasticsearch.cluster.coordination.CoordinatorTests/testUnhealthyLeaderIsReplaced

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.CoordinatorTests.testUnhealthyLeaderIsReplaced" -Dtests.seed=3E136AAE5154F966 -Dtests.locale=ro -Dtests.timezone=Asia/Aqtau -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.cluster.coordination.CoordinatorTests&tests.test=testUnhealthyLeaderIsReplaced

**Failure excerpt:**
```
java.lang.AssertionError: leaders
Expected: not an empty collection
     but: was <[]>

  at __randomizedtesting.SeedInfo.seed([3E136AAE5154F966:80597ABFDE528E40]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.getAnyLeader(AbstractCoordinatorTestCase.java:791)
  at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:563)
  at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:548)
  at org.elasticsearch.cluster.coordination.CoordinatorTests.testUnhealthyLeaderIsReplaced(CoordinatorTests.java:640)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
The cluster coordination consistency layer relies on a couple of fields within `Metadata` which record the last _committed_ values on each node. In contrast, the rest of the cluster state can only be changed at _accept_ time.

In the past we would copy these fields over from the master on every publication, but since #90101 we don't copy anything at all if the `Metadata` is unchanged on the master. However, the master computes the diff against the last _committed_ state whereas the receiving nodes apply the diff to the last _accepted_ state, and this means if the master sends a no-op `Metadata` diff then the receiving node will revert its last-committed values to the ones included in the state it last accepted.

With this commit we include the last-committed values alongside the cluster state diff so that they are always copied properly.

Closes #90158

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Alternative to https://github.com/elastic/elasticsearch/pull/92258 that doesn't involve changing the safety algorithm. Not as bad as I thought it would be.

Repeating here: I think this bug is more of a liveness concern than a safety one: it means that an election may incorrectly wait to collect votes from the previous configuration as well as the current one.

**Comment by DaveCTurner** [comment]
We should backport this to 8.6, but I'm unsure if it'll land in 8.6.0 or 8.6.1. It's not serious enough to call it a blocker for 8.6.0 IMO. However the 8.6.1 version constant doesn't exist yet so I am going to have to set the BwC version to 8.6.0 while backporting, and then we will have to adjust this when bumping versions after the 8.6.0 release.

cc @henningandersen who may have a different opinion about calling this a blocker for 8.6.0.
cc @kingherc who I believe will be doing the 8.6.0 version bump.

File: server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java [hunk 1]
```diff
@@ -556,27 +556,18 @@ public interface PersistedState extends Closeable {
...
-                && lastAcceptedState.metadata().clusterUUIDCommitted() == false) {
-                if (metadataBuilder == null) {
-                    metadataBuilder = Metadata.builder(lastAcceptedState.metadata());
-                }
-                metadataBuilder.clusterUUIDCommitted(true);
+            final var lastAcceptedState = getLastAcceptedState();
+            final var hasClusterUuid = lastAcceptedState.metadata().clusterUUID().equals(Metadata.UNKNOWN_CLUSTER_UUID) == false;
+            assert hasClusterUuid : "received cluster state with empty cluster uuid: " + lastAcceptedState;
+
+            if (hasClusterUuid && lastAcceptedState.metadata().clusterUUIDCommitted() == false) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java:563]: Feels odd to protect the logging by something we assert on above?

```suggestion
            if (lastAcceptedState.metadata().clusterUUIDCommitted() == false) {
```

File: server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java [hunk 2]
```diff
@@ -556,27 +556,18 @@ public interface PersistedState extends Closeable {
...
                 logger.info("cluster UUID set to [{}]", lastAcceptedState.metadata().clusterUUID());
             }
-            if (metadataBuilder != null) {
-                setLastAcceptedState(ClusterState.builder(lastAcceptedState).metadata(metadataBuilder).build());
+
+            final var adjustedMetadata = lastAcceptedState.metadata()
+                .withLastCommittedValues(hasClusterUuid, lastAcceptedState.getLastAcceptedConfiguration());
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java:568]: Should we pass in `hasClusterUuid || lastAcceptedState.metadata().clusterUUIDCommitted()` here? I mean, we are outside assertions already, so could also pass in true. But assuming assertions have some case we are trying to protect against, passing in the original committed value seems safer and also in line with original code.

File: server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java [hunk 3]
```diff
@@ -556,27 +556,18 @@ public interface PersistedState extends Closeable {
          * marked as committed.
          */
         default void markLastAcceptedStateAsCommitted() {
-            final ClusterState lastAcceptedState = getLastAcceptedState();
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java:559]: I think the code is cleaner, but I failed to spot the important difference, is it just the logging you wanted out of this?

**Review by henningandersen — COMMENTED** [review]
Left a few comments, probably to be considered questions.

File: server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java:563]: Ehh I just kept the same logic as before but I don't think I've ever seen this assertion trip. I'd be ok to drop it.

File: server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java [hunk 4]
```diff
@@ -86,6 +86,8 @@ public class PublicationTransportHandler {
         TransportRequestOptions.Type.STATE
     );
 
+    public static final Version INCLUDES_LAST_COMMITTED_DATA_VERSION = Version.V_8_7_0;
```
Comment (kingherc) [inline server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java:89]: @DaveCTurner should this be 8.6.0 since it's intended to be backported?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java:89]: I'll adjust that while backporting. If I set this to 8.6.0 now then the BwC test suite would fail on this PR, but it's important for those tests to pass because they tell us whether there are any other more subtle BwC problems here.

File: server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java (hunk 3 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationState.java]: Thanks. In that case, let us revert this and move this to a follow-up, where we can also assume that assertions are held (i.e., use `true` instead of `hasClusterUuid` later in the code).

**Comment by DaveCTurner** [comment]
I reverted the tidy-up to `CoordinationState` in 768a864599c0815b9ff23565ca84e2a61bac3c29 because it's not necessary for the backport. I'll follow-up with that change in a separate PR

File: server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTransportHandlerTests.java [hunk 5]
```diff
@@ -330,4 +338,160 @@ public void writeTo(StreamOutput out) throws IOException {
...
+                otherNode,
+                new PublishRequest(clusterState1),
+                ActionListener.wrap(() -> assertTrue(completed.compareAndSet(false, true)))
+            );
+            assertTrue(completed.getAndSet(false));
+            var receivedState = receivedStateRef.getAndSet(null);
+            assertEquals(clusterState1.stateUUID(), receivedState.stateUUID());
+            assertEquals(otherNode, receivedState.nodes().getLocalNode());
+            assertTrue(receivedState.metadata().clusterUUIDCommitted());
+            assertEquals(VotingConfiguration.of(localNode), receivedState.getLastCommittedConfiguration());
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTransportHandlerTests.java:489]: Can we add something like:

```
assertSame(receivedState.nodes(), firstReceivedState.nodes());
```
where `firstReceivedState` is the `receivedState` from the `context0` invocation above? It is mostly a test validation, i.e., that we do send a diff in this case (which AFAICS, we will).

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTransportHandlerTests.java (hunk 5 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/cluster/coordination/PublicationTransportHandlerTests.java]: Yep, and we can see that from the receiving node's `PublishClusterStateStats` too. See b910c87aaed.

File: server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java (hunk 4 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/cluster/coordination/PublicationTransportHandler.java:89]: Joining the dots here:

- I opened a PR at https://github.com/elastic/elasticsearch/pull/92277 which backports this to 8.6 with a fixed BwC version, and waited for it to pass CI.
- I merged 296eacd1a3b2c41275dddafc3469f60d309d7344 which disables the BwC tests in `main`.
- I merged the backport PR.
- I opened another PR at https://github.com/elastic/elasticsearch/pull/92280 to fix up the BwC version in `main` and reinstate the BwC tests, which will be merged once it passes CI.
