### PR TITLE
ES|QL: fix ENRICH validation for use of wildcards

### LINKED ISSUE #121740: ESQL: ENRICH throws 500 when wildcard is used in the WITH clause
This should throw a ValidationException with a 400 status code.

Reproducer on main:
```
$ curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_enrich/policy/my-policy" -XPUT -d'
{
  "match": {
    "indices": "enrich_index",
    "match_field": "match_field",
    "enrich_fields": ["enrich_field"]
  }
}
'

$ curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_enrich/policy/my-policy/_execute?wait_for_completion=true" -XPUT

$ curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/_query?format=txt&error_trace" -d '
{
  "query": "row x = \"foo\" | enrich my-policy with x = *"
}'

{"error":{"root_cause":[{"type":"unresolved_exception","reason":"Invalid call to name on an unresolved object ?*"}],"type":"unresolved_exception","reason":"Invalid call to name on an unresolved object ?*"},"status":500}
```

The stack trace also shows that we end up calling `UnresolvedNamedExpression.name` (which throws `UnresolvedException`, which is a server-side exception resulting in 500):

```
org.elasticsearch.xpack.esql.core.capabilities.UnresolvedException: Invalid call to name on an unresolved object ?* at 
org.elasticsearch.xpack.esql.core.expression.UnresolvedNamedExpression.name(UnresolvedNamedExpression.java:29) at 
org.elasticsearch.xpack.esql.core.expression.Expressions.name(Expressions.java:132) at 
org.elasticsearch.xpack.esql.analysis.Analyzer$ResolveEnrich.calculateEnrichFields(Analyzer.java:357) at 
org.elasticsearch.xpack.esql.analysis.Analyzer$ResolveEnrich.rule(Analyzer.java:314) at 
org.elasticsearch.xpack.esql.analysis.Analyzer$ResolveEnrich.rule(Analyzer.java:299) at 
org.elasticsearch.xpack.esql.analysis.AnalyzerRules$ParameterizedAnalyzerRule.lambda$apply$0(AnalyzerRules.java:49) at 
org.elasticsearch.xpack.esql.core.tree.Node.lambda$transformUp$11(Node.java:199) at 
org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:193) at 
org.elasticsearch.xpack.esql.core.tree.Node.lambda$transformUp$10(Node.java:191) at 
org.elasticsearch.xpack.esql.core.tree.Node.transformChildren(Node.java:212) at 
org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:191) at 
org.elasticsearch.xpack.esql.core.tree.Node.transformUp(Node.java:199) at 
org.elasticsearch.xpack.esql.analysis.AnalyzerRules$ParameterizedAnalyzerRule.apply(AnalyzerRules.java:49) at 
org.elasticsearch.xpack.esql.analysis.AnalyzerRules$ParameterizedAnalyzerRule.apply(AnalyzerRules.java:41) at 
org.elasticsearch.xpack.esql.rule.ParameterizedRuleExecutor.lambda$transform$0(ParameterizedRuleExecutor.java:29) at 
org.elasticsearch.xpack.esql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:92) at 
org.elasticsearch.xpack.esql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:171) at 
org.elasticsearch.xpack.esql.rule.RuleExecutor.execute(RuleExecutor.java:140) at 
org.elasticsearch.xpack.esql.analysis.Analyzer.analyze(Analyzer.java:183) at 
org.elasticsearch.xpack.esql.session.EsqlSession.lambda$analyzedPlan$7(EsqlSession.java:305) at 
org.elasticsearch.xpack.esql.session.EsqlSession.analyzeAndMaybeRetry(EsqlSession.java:512) at 
org.elasticsearch.xpack.esql.session.EsqlSession.lambda$analyzedPlan$16(EsqlSession.java:350) at 
org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(Acti
onListenerImplementations.java:247) at 
...
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes: https://github.com/elastic/elasticsearch/issues/121740

Fix validation of ENRICH with usage of (unsupported) wildcards in field names, eg.

```
... | enrich my-policy with x = * 
```

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/ExpressionBuilder.java [hunk 1]
```diff
@@ -795,9 +795,9 @@ public NamedExpression visitEnrichWithClause(EsqlBaseParser.EnrichWithClauseCont
 
     private NamedExpression enrichFieldName(EsqlBaseParser.QualifiedNamePatternContext ctx) {
         return visitQualifiedNamePattern(ctx, ne -> {
-            if (ne instanceof UnresolvedNamePattern up) {
+            if (ne instanceof UnresolvedNamePattern || ne instanceof UnresolvedStar) {
                 var src = ne.source();
-                throw new ParsingException(src, "Using wildcards [*] in ENRICH WITH projections is not allowed [{}]", up.pattern());
+                throw new ParsingException(src, "Using wildcards [*] in ENRICH WITH projections is not allowed [{}]", src.text());
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/ExpressionBuilder.java:800]:
```suggestion
                throw new ParsingException(src, "Using wildcards [*] in ENRICH WITH projections is not allowed, found [{}]", src.text());
```

**Review by astefan — APPROVED** [review]
LGTM. Left one minor styling comment.

**Review by idegtiarenko — APPROVED** [review]

**Comment by luigidellaquila** [comment]
Thanks folks!
