### PR TITLE
SQL: Fix issue with date range queries and timezone

### LINKED ISSUE #56049: SQL: range queries on dates do not pass along the timezone
When dealing with a time interval, the user timezone is not set on the [range](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html) (meaning `gt`, `lt`, etc..) query which can lead to problems when dealing with relative intervals (such as 1d).

### PR DESCRIPTION
**Pull request by matriv**
Previously, the timezone parameter was not passed to the RangeQuery
and as a results queries that use the ES date math notation (now,
now-1d, now/d, now/h, now+2h, etc.) were using the UTC timezone and
not the one passed through the "timezone"/"time_zone" JDBC/REST params.
As a consequence, the date math defined dates were always considered in
UTC and possibly led to incorrect results for queries like:
```
SELECT * FROM t WHERE date BETWEEN now-1d/d AND now/d
```

Fixes: #56049

### CODE REVIEW

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/planner/QueryFolder.java [hunk 1]
```diff
@@ -53,7 +53,7 @@ protected PhysicalPlan rule(FilterExec plan) {
                 EsQueryExec exec = (EsQueryExec) plan.child();
                 QueryContainer qContainer = exec.queryContainer();
 
-                Query query = ExpressionTranslators.toQuery(plan.condition());
+                Query query = ExpressionTranslators.toQuery(plan.condition(), qContainer.zoneId());
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/planner/QueryFolder.java:56]: I think it's too disruptive to pass the `zoneId` to all translations as the vast majority of the nodes will simply ignore it.
It also forces one to think of an expression in terms of a timezone which is incorrect.
Only some expressions have a zoneId so that information should be localized instead of being passed at a higher level.
In this case, the zoneId should be on the comparison operator (either inferred based on the arguments or extracted from the configuration) and the translator should only extract it from there.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 2]
```diff
@@ -249,17 +251,21 @@ private static Query translate(BinaryComparison bc, TranslatorHandler handler) {
                 isDateLiteralComparison = true;
             }
 
+            ZoneId zoneId = null;
+            if (bc.left().dataType() == DATETIME) {
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:255]: A handler could contain the default zoneId however since these are created statically, there's no way to pass that through during construction time.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/querydsl/query/RangeQuery.java [hunk 3]
```diff
@@ -20,20 +21,30 @@
...
 
-    public RangeQuery(Source source, String field, Object lower, boolean includeLower, Object upper, boolean includeUpper) {
-        this(source, field, lower, includeLower, upper, includeUpper, null);
+    public RangeQuery(Source source, String field, Object lower, boolean includeLower, Object upper, boolean includeUpper, ZoneId zoneId) {
+        this(source, field, lower, includeLower, upper, includeUpper, null, zoneId);
     }
 
-    public RangeQuery(Source source, String field, Object lower, boolean includeLower, Object upper,
-            boolean includeUpper, String format) {
+    public RangeQuery(
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/querydsl/query/RangeQuery.java:30]: Ughhh - a good example of how formatting penalizes clarity. Rename `source` into `s` or `includeLower` into `iLower`, etc... and boom, now everything fits into one line.

**Review by costin — CHANGES_REQUESTED** [review]
Thanks for picking this one up. I don't think the current approach works - first off, the user timezone doesn't seem to be used (it always defaults to UTC).
Second, the timezone should not be passed around - it's an implementation leak.
So either `TranslatorHandler` should become parameterized (which is tricky due to its static nature and general usability) or the `zoneId` should be extracted either inside the translator, based on the existing configuration (again hard to parameterized since it's unclear where it is called from) or extracted from the argument itself, the expression that is about to be translated.
This requires some changes in the way operators are created since the timezone would have to be injected into them - that is all comparisons should be timezone aware _if_ at least one argument is dateTime specific otherwise that information can be ignored all together.

**Comment by matriv** [comment]
> Thanks for picking this one up. I don't think the current approach works - first off, the user timezone doesn't seem to be used (it always defaults to UTC).
> Second, the timezone should not be passed around - it's an implementation leak.
> So either `TranslatorHandler` should become parameterized (which is tricky due to its static nature and general usability) or the `zoneId` should be extracted either inside the translator, based on the existing configuration (again hard to parameterized since it's unclear where it is called from) or extracted from the argument itself, the expression that is about to be translated.
> This requires some changes in the way operators are created since the timezone would have to be injected into them - that is all comparisons should be timezone aware _if_ at least one argument is dateTime specific otherwise that information can be ignored all together.

The timezone is passed correctly for SQL: https://github.com/elastic/elasticsearch/pull/56115/files#diff-913993cd17dbceac1fa55d21b31c61deR83
It's for EQL that the QueryContainer has always UTC. (Check QueryTranslatorTests).

On the other hand, I agree that injecting the timezone to the comparison operators seems a much better approach, since it's closer to the context and we don't have to pass it around for all translations.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/CIDRMatch.java [hunk 4]
```diff
@@ -105,7 +106,7 @@ public ScalarFunction makeSubstitute() {
         ScalarFunction func = null;
 
         for (Expression address : addresses) {
-            final Equals eq = new Equals(source(), field, address);
+            final Equals eq = new Equals(source(), field, address, UTC);
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/CIDRMatch.java:109]: For Equals without timezone I think it's best to create a constructor that doesn't require the tz , have the tz as null and potentially validate that it's not being used.
The tz should not be used in this case so forcing its user to specify one is just going to lead to problems.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/ExpressionBuilder.java [hunk 5]
```diff
@@ -118,17 +124,17 @@ public Expression visitComparison(ComparisonContext ctx) {
 
         switch (op.getSymbol().getType()) {
             case EqlBaseParser.EQ:
-                return new Equals(source, left, right);
+                return new Equals(source, left, right, params.zoneId());
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/ExpressionBuilder.java:127]: Similar to source, just extract the params.zoneId into a variable an use that instead - less verbose and makes potential refactoring easier in the future.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java [hunk 6]
```diff
@@ -56,7 +55,7 @@ public LogicalPlan visitEventQuery(EqlBaseParser.EventQueryContext ctx) {
             Literal eventValue = new Literal(eventSource, eventName, DataTypes.KEYWORD);
 
             UnresolvedAttribute eventField = new UnresolvedAttribute(eventSource, params.fieldEventCategory());
-            Expression eventMatch = new Equals(eventSource, eventField, eventValue);
+            Expression eventMatch = new Equals(eventSource, eventField, eventValue, params.zoneId());
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/parser/LogicalPlanBuilder.java:58]: 👍

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plugin/TransportEqlSearchAction.java [hunk 7]
```diff
@@ -64,7 +64,7 @@ public static void operation(PlanExecutor planExecutor, EqlSearchTask task, EqlS
         boolean includeFrozen = request.indicesOptions().ignoreThrottled() == false;
         String clientId = null;
 
-        ParserParams params = new ParserParams()
+        ParserParams params = new ParserParams(zoneId)
```
Comment (costin) [inline x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/plugin/TransportEqlSearchAction.java:67]: 👍

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/predicate/Range.java [hunk 8]
```diff
@@ -35,28 +36,30 @@
 
     private final Expression value, lower, upper;
     private final boolean includeLower, includeUpper;
+    private final ZoneId zoneId;
 
-    public Range(Source source, Expression value, Expression lower, boolean includeLower, Expression upper, boolean includeUpper) {
-        super(source, asList(value, lower, upper));
+    public Range(Source src, Expression value, Expression lower, boolean inclLower, Expression upper, boolean inclUpper, ZoneId zoneId) {
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/expression/predicate/Range.java:41]: :)

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 9]
```diff
@@ -249,17 +251,21 @@ private static Query translate(BinaryComparison bc, TranslatorHandler handler) {
...
+                zoneId = bc.zoneId();
```
Comment (costin) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:256]: What would be the downside of always getting the zoneId and passing it to the range query ?

File: x-pack/plugin/ql/src/test/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRulesTests.java [hunk 10]
```diff
@@ -44,12 +44,21 @@
...
+import static org.elasticsearch.xpack.ql.TestUtils.greaterThanOrEqualOf;
+import static org.elasticsearch.xpack.ql.TestUtils.lessThanOf;
+import static org.elasticsearch.xpack.ql.TestUtils.lessThanOrEqualOf;
+import static org.elasticsearch.xpack.ql.TestUtils.notEqualsOf;
+import static org.elasticsearch.xpack.ql.TestUtils.nullEqualsOf;
 import static org.elasticsearch.xpack.ql.TestUtils.of;
+import static org.elasticsearch.xpack.ql.TestUtils.rangeOf;
 import static org.elasticsearch.xpack.ql.expression.Literal.FALSE;
 import static org.elasticsearch.xpack.ql.expression.Literal.NULL;
 import static org.elasticsearch.xpack.ql.expression.Literal.TRUE;
```
Comment (costin) [inline x-pack/plugin/ql/src/test/java/org/elasticsearch/xpack/ql/optimizer/OptimizerRulesTests.java:64]: 👍

**Review by costin — APPROVED** [review]
Left some style comments but otherwise looks good to me.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java (hunk 9 above)
Comment (matriv) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java:256]: I don't see a "downside" other than possible confusion when one sees the translated query.
the timezone is only used for processing ES date math expressions.

File: x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/CIDRMatch.java (hunk 4 above)
Comment (matriv) [reply x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/expression/function/scalar/string/CIDRMatch.java]: Could you explain a bit more about this validation that you mention? Validation for the CIDRMatch function or for the Equals?

**Review by astefan — APPROVED** [review]
LGTM
