### PR TITLE
Address when scores can be very large in osq score test

### LINKED ISSUE #128485: [CI] ES91OSQVectorScorerTests testScore failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8430 / almalinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/wptsypsqmufo6)
- [elasticsearch-periodic-platform-support #8346 / ubuntu-2404-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/ran65ipm3l5yy)

**Reproduction Line:**
```
./gradlew ":libs:simdvec:test" --tests "org.elasticsearch.simdvec.internal.vectorization.ES91OSQVectorScorerTests.testScore" -Dtests.seed=DC73C000DF433DC7 -Dtests.locale=ksf-Latn-CM -Dtests.timezone=Japan -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.simdvec.internal.vectorization.ES91OSQVectorScorerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testScore),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: defaultScores: 1.726524E9 bulkScores: 1.7265239E9
Expected: a value less than <65>
     but: <128> was greater than <65>
```

**Issue Reasons:**
- [main] 2 failures in test testScore (0.3% fail rate in 688 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (13.3% fail rate in 15 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by benwtrent**
Using a static `diff` or epsilon just doesn't work for this test as the scores can be very large, but relatively close. 

Maybe there is a simpler way, but my mind wasn't wanting to "math" very much. 

For example, the seed that this previously failed on had scores like `1.726524E9` and `1.7265239E9`, which, given their size, are really close together (within 128). But a static epsilon wouldn't capture that.

closes: https://github.com/elastic/elasticsearch/issues/128485

### CODE REVIEW

File: libs/simdvec/src/test/java/org/elasticsearch/simdvec/internal/vectorization/ES91OSQVectorScorerTests.java [hunk 1]
```diff
@@ -107,12 +107,21 @@ public void testScore() throws Exception {
...
-                                int diff = (int) (scores1[j] - scores2[j]);
-                                assertThat("defaultScores: " + scores1[j] + " bulkScores: " + scores2[j], Math.abs(diff), lessThan(9));
+                            if (scores1[j] == scores2[j]) {
+                                continue;
+                            }
+                            if (scores1[j] > (maxDims * Byte.MAX_VALUE)) {
+                                float diff = scores1[j] - scores2[j];
+                                assertThat(
+                                    "defaultScores: " + scores1[j] + " bulkScores: " + scores2[j],
+                                    diff / scores1[j],
```
Comment (john-wagster) [inline libs/simdvec/src/test/java/org/elasticsearch/simdvec/internal/vectorization/ES91OSQVectorScorerTests.java:135]: does this not need an Math.abs so as to be Math.abs(diff) / scores1[j]?

Comment (benwtrent) [reply libs/simdvec/src/test/java/org/elasticsearch/simdvec/internal/vectorization/ES91OSQVectorScorerTests.java:135]: you are right!

**Review by john-wagster — APPROVED** [review]
lgtm

**Review by tteofili — APPROVED** [review]
LGTM
