### PR TITLE
Configure TMP for test nodes on Windows

### LINKED ISSUE #39904: Integration tests fail on Windows
The latest master cannot run integration tests on windows due to:
```
Exception in thread "main" java.nio.file.AccessDeniedException: C:\Windows\elasticsearch
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(WindowsFileSystemProvider.java:504)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.elasticsearch.tools.launchers.TempDirectory.main(TempDirectory.java:52)
```

It looks like the temporary folder is not set which causes the default/system folder (`C:\Windows`) to be used instead which obviously fails.

From try-outs it looks commit 465343f12a54111709ca7c7cd776edcaba1e0c2b introduced this change in behavior.

### PR DESCRIPTION
**Pull request by alpar-t**
On windows TMP dir default to C:\Windows and startup fails with a permission error.
The reason we don't see this more is that typically windows has TMP defined in users environment, but with `newenvironment: true` this is not passed along. 

Closes #39904.

### CODE REVIEW

**Comment by rjernst** [comment]
The new environment is necessary; otherwise we pass through JAVA_HOME and always use that, even when we want to use the bundled jdk. I think we can solve this by passing through whatever env vars windows needs?

**Comment by atorok** [comment]
Thanks @rjernst I was too quick on that one. I added `TMP` now, which required an additional fix since it happened to be a path with spaces.

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy [hunk 1]
```diff
@@ -690,6 +690,13 @@ class ClusterFormationTasks {
                     env(key: 'JAVA_HOME', value: project.runtimeJavaHome)
                 }
                 node.args.each { arg(value: it) }
+                if (Os.isFamily(Os.FAMILY_WINDOWS)) {
+                    // Having no TMP on Windows defaults to C:\Windows and permission errors
+                    // Since we configure ant to run with a new  environment above, we need to set this to a dir we have access to
+                    File tmpDir = new File(node.baseDir, "tmp")
+                    tmpDir.mkdirs()
+                    env(key: "TMP", value: tmpDir.absolutePath)
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy]: shouldn't we just pass through TMP? this would match the previous behavior where the environment was inherited

**Review by rjernst — APPROVED** [review]
LGTM, one optional suggestion
