### PR TITLE
Reuse JoinTaskExecutor

### LINKED ISSUE #85249: Investigate possible election retry loop
I observed a 7.12 cluster that was struggling to complete an election, with at least one node holding over a million `elected-as-master` tasks in its pending task queue. I suspect there were two such nodes because they were just constantly winning elections and then failing because of the next election and so on...

It's currently unclear exactly how we got into this state, but it doesn't seem completely impossible if something else causes a bunch of spurious elections somehow. Perhaps a partial network partition is involved?

In any case I believe we can and should take steps to avoid processing stale `elected-as-master` tasks.

### PR DESCRIPTION
**Pull request by idegtiarenko**
Currently, we are not reusing the JoinTaskExecutor that could result in
a long-running processing of outdated join or election requests. This
change keeps the executor permanently and drops all but latest requests.

Closes: #85249

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/coordination/JoinTask.java [hunk 1]
```diff
@@ -13,24 +13,18 @@
...
+    public static JoinTask singleNode(DiscoveryNode node, String reason, ActionListener<Void> listener, long term) {
+        return new JoinTask(List.of(new NodeJoinTask(node, reason, listener)), false, term);
     }
 
-    public static JoinTask completingElection(Stream<NodeJoinTask> nodeJoinTaskStream) {
-        return new JoinTask(nodeJoinTaskStream.toList(), true);
-    }
-
-    public JoinTask(List<NodeJoinTask> nodeJoinTasks, boolean isBecomingMaster) {
-        this.nodeJoinTasks = Collections.unmodifiableList(nodeJoinTasks);
```
Comment (idegtiarenko) [inline server/src/main/java/org/elasticsearch/cluster/coordination/JoinTask.java:32]: No need to wrap as every static factory creates an immutable list already

File: server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java [hunk 2]
```diff
@@ -41,19 +41,22 @@
...
 
     @Override
     public ClusterState execute(ClusterState currentState, List<TaskContext<JoinTask>> joinTaskContexts) throws Exception {
         // The current state that MasterService uses might have been updated by a (different) master in a higher term already. If so, stop
         // processing the current cluster state update, there's no point in continuing to compute it as it will later be rejected by
         // Coordinator#publish anyhow.
+        assert joinTaskContexts.isEmpty() == false : "Expected to have non empty join tasks list";
+
+        var term = joinTaskContexts.stream().mapToLong(t -> t.getTask().term()).max().getAsLong();
+        joinTaskContexts = joinTaskContexts.stream().filter(t -> t.getTask().term() == term).toList();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java:58]: We need to complete every context, but this would not complete the stale ones. Think that means we're missing a unit test that submits tasks with a mix of terms - ideally use something like `ClusterStateTaskExecutorUtils.executeHandlingResults` which verifies that all contexts are completed.

Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java:58]: I converted this to draft as I wanted to see the complete list of failures. Currently they are:
* CoordinatorTests » testDoesNotElectNonMasterNode
* CoordinatorTests » testNodeCannotJoinIfJoinValidationFailsOnJoiningNode
* CoordinatorTests » testJoiningNodeReceivesFullState
* CoordinatorTests » testDoesNotPerformElectionWhenRestartingFollower
* VotingOnlyNodeCoordinatorTests » testRepeatableTests
* VotingOnlyNodeCoordinatorTests » testDoesNotElectVotingOnlyMasterNode

I also still have not added new test to `JoinTaskExecutorTests`.

Comment (idegtiarenko) [reply server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java]: Updated to throw `JoinTaskOutdatedException` and added the unit test for it. I believe I still need to add it to `ElasticsearchExceptionHandle`

File: server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskOutdatedException.java [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+import org.elasticsearch.ElasticsearchException;
+import org.elasticsearch.common.io.stream.StreamInput;
+
+import java.io.IOException;
+
+/**
+ * Is thrown when a join requests arrives with outdated term
+ */
+public class JoinTaskOutdatedException extends ElasticsearchException {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskOutdatedException.java:19]: I think we can just use `NotMasterException`, no need for a new exception like this.

**Review by DaveCTurner — COMMENTED** [review]
Looks good, just one comment.

File: server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java [hunk 4]
```diff
@@ -41,19 +41,28 @@
...
         // The current state that MasterService uses might have been updated by a (different) master in a higher term already. If so, stop
         // processing the current cluster state update, there's no point in continuing to compute it as it will later be rejected by
         // Coordinator#publish anyhow.
+        assert joinTaskContexts.isEmpty() == false : "Expected to have non empty join tasks list";
+
+        var term = joinTaskContexts.stream().mapToLong(t -> t.getTask().term()).max().getAsLong();
+
+        var split = joinTaskContexts.stream().collect(Collectors.partitioningBy(t -> t.getTask().term() == term));
+        for (TaskContext<JoinTask> outdated : split.get(false)) {
+            outdated.onFailure(new NotMasterException("Join task term [" + term + "] is outdated"));
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java:61]: This message suggests that `term` is stale, but `term` is actually the latest term, it's `outdated.getTask().term()` that is stale. Could we include both numbers in the message?

File: server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java [hunk 5]
```diff
@@ -41,19 +41,28 @@
...
+        }
+
+        joinTaskContexts = split.get(true);// process up-to-date tasks
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/cluster/coordination/JoinTaskExecutor.java:64]: Nit: I'm not convinced this comment makes things any clearer. Are you sure it's useful?

```suggestion
        joinTaskContexts = split.get(true);
```

**Review by DaveCTurner — COMMENTED** [review]
Looks good, just one change needed to the exception message and another nit.

**Review by DaveCTurner — APPROVED** [review]
LGTM
