### PR TITLE
Skip Rollover step if next index already exists

### LINKED ISSUE #34465: [ILM] Rollover action errors after restart
4 node cluster with 1 hot, 2 warm and 1 cold node

1. Create a policy:
```
PUT _ilm/my_lifecycle3
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_age": "30s"
          }
        }
      },
      "warm": {
        "actions": {
          "forcemerge": {
            "max_num_segments": 1
          },
          "allocate": {
            "number_of_replicas": 1,
            "include": {
              "box_type": "warm"
            },
            "exclude": {},
            "require": {}
          }
        }
      },
      "cold": {
        "minimum_age": "1m",
        "actions": {
          "allocate": {
            "number_of_replicas": 0,
            "include": {
              "box_type": "cold"
            },
            "exclude": {},
            "require": {}
          }
        }
      },
      "delete": {
        "minimum_age": "2m",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}
```

2. Create an index template:
```
PUT _template/my_template
{
  "index_patterns": ["test-*"],
  "settings": {
    "number_of_shards": 2,
    "number_of_replicas": 0,
    "index.lifecycle.name": "my_lifecycle3",
    "index.lifecycle.rollover_alias": "test-alias",
    "index.routing.allocation.include.box_type": "hot"
  }
}
```

3.  create the first index:
```
PUT test-000001
{
  "aliases": {
    "test-alias":{
      "is_write_index": true
    }
  }
}
```

4. Check the index is on the `attempt_rollover` step using the explain api:
```
GET test-*/_ilm/explain?human
```

5. Shutdown all nodes

6. Restart all nodes

7. Wait for the 2nd index to appear using the explain API:
```
GET test-*/_ilm/explain?human
```

8. Observe that the first index is in the ERROR state with a response something like the following
```
{
  "indices": {
    "test-000001": {
      "index": "test-000001",
      "managed": true,
      "policy": "my_lifecycle3",
      "skip": false,
      "lifecycle_date": "2018-10-15T14:49:32.281Z",
      "phase": "hot",
      "phase_time": "2018-10-15T14:49:32.531Z",
      "action": "rollover",
      "action_time": "2018-10-15T14:49:32.531Z",
      "step": "ERROR",
      "step_time": "2018-10-15T14:50:18.632Z",
      "failed_step": "attempt_rollover",
      "step_info": {
        "type": "resource_already_exists_exception",
        "reason": "index [test-000002/cRr06akcS4mJXfZniAFfGQ] already exists",
        "index_uuid": "cRr06akcS4mJXfZniAFfGQ",
        "index": "test-000002"
      },
      "phase_execution": {
        "policy": "my_lifecycle3",
        "phase_definition": {
          "minimum_age": "0ms",
          "actions": {
            "rollover": {
              "max_age": "30s"
            }
          }
        },
        "version": 1,
        "modified_date": "2018-10-15T14:49:24.641Z",
        "modified_date_in_millis": 1539614964641
      }
    },
    "test-000002": {
      "index": "test-000002",
      "managed": true,
      "policy": "my_lifecycle3",
      "skip": false,
      "lifecycle_date": "2018-10-15T14:50:17.338Z",
      "phase": "new",
      "phase_time": "2018-10-15T14:50:18.725Z",
      "action": "complete",
      "action_time": "2018-10-15T14:50:18.384Z",
      "step": "complete",
      "step_time": "2018-10-15T14:50:18.384Z"
    }
  }
}
```

It seems like in this scenario the rollover step might be getting run twice?

### PR DESCRIPTION
**Pull request by AthenaEryma**
If the Rollover step would fail due to the next index in sequence
already existing, just skip to the next step instead of going to the
Error step.

This prevents spurious `ResourceAlreadyExistsException`s created by
simultaneous RolloverStep executions from causing ILM to error out
unnecessarily.

Resolves #34465 - I tested this fix manually against a setup that otherwise
reliably reproduced that issue for a few hours, and did not encounter any 
failures due to an unnecessary `ResourceAlreadyExistsException`.

However, I'm still somewhat concerned that the error message a user encounters
if they really do have a problem with the index existing isn't clear - see the test case
I added (`testRolloverAlreadyExists`) to see what I mean.  We could change that
message to be clearer in this case, but that may cause the error to be less clear if
the `RolloverInfo` is `null` via some other way.  Any thoughts?

### CODE REVIEW

File: x-pack/plugin/ilm/qa/multi-node/src/test/java/org/elasticsearch/xpack/indexlifecycle/TimeSeriesLifecycleActionsIT.java [hunk 1]
```diff
@@ -192,6 +193,38 @@ public void testRolloverAction() throws Exception {
...
+
+        // index another doc to trigger the policy
+        index(client(), originalIndex, "_id", "foo", "bar");
+
+        assertBusy(() -> {
+            logger.info(originalIndex + ": " + getStepKeyForIndex(originalIndex));
+            logger.info(secondIndex + ": " + getStepKeyForIndex(secondIndex));
+            assertThat(getStepKeyForIndex(originalIndex), equalTo(new StepKey("hot", RolloverAction.NAME, ErrorStep.NAME)));
+            assertThat(getFailedStepForIndex(originalIndex), equalTo("update-rollover-lifecycle-date"));
+            assertThat(getReasonForIndex(originalIndex), equalTo("index [" + originalIndex + "] has not rolled over yet"));
```
Comment (colings86) [inline x-pack/plugin/ilm/qa/multi-node/src/test/java/org/elasticsearch/xpack/indexlifecycle/TimeSeriesLifecycleActionsIT.java]: I agree that this error message is confusing. Just to check I understand correctly. The problem with the second index is actually that it doesn't have the rollover alias setting set and doesn't have any rollover info?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/RolloverStep.java [hunk 2]
```diff
@@ -63,7 +68,16 @@ public void evaluateCondition(IndexMetaData indexMetaData, Listener listener) {
             rolloverRequest.addMaxIndexDocsCondition(maxDocs);
         }
         getClient().admin().indices().rolloverIndex(rolloverRequest,
-                ActionListener.wrap(response -> listener.onResponse(response.isRolledOver(), new EmptyInfo()), listener::onFailure));
+            ActionListener.wrap(response -> listener.onResponse(response.isRolledOver(), new EmptyInfo()), exception -> {
+                if (exception instanceof ResourceAlreadyExistsException) {
+                    // This can happen sometimes when this step is executed multiple times
+                    logger.debug("index [{}] cannot roll over because the next index already exists, skipping to next step",
```
[the remark this answers is not in the document]
Comment (dakrone) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/RolloverStep.java]: Can you add logging of the exception on TRACE level (so that in the future if this ever occurs for a different reason we still have access to the full stacktrace):

```java
if (logger.isTraceEnabled()) {
    logger.debug(() -> new ParameterizedMessage("{} index cannot roll over ...", indexMetaData.getIndex()), exception);
} else {
    logger.debug("{} index cannot roll over ...", indexMetaData.getIndex());
}
```

File: x-pack/plugin/ilm/qa/multi-node/src/test/java/org/elasticsearch/xpack/indexlifecycle/TimeSeriesLifecycleActionsIT.java (hunk 1 above)
Comment (gwbrown) [reply x-pack/plugin/ilm/qa/multi-node/src/test/java/org/elasticsearch/xpack/indexlifecycle/TimeSeriesLifecycleActionsIT.java]: Here's an example: If you have `test-000001` and manually create `test-000002` before rollover fires (and don't do anything else), then `test-000001` will end up in the error state with this message because `test-000001` has not been rolled over, and therefore doesn't have any attached `RolloverInfo`.  `test-000001` is still the target of the alias and still has the rollover alias setting.

If `test-000002` had been manually created and the alias had been manually switched to point to `test-000002`, `attempt_rollover` would fail due to https://github.com/elastic/elasticsearch/pull/35065

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/RolloverStep.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (gwbrown) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/RolloverStep.java]: Done and done.

File: x-pack/plugin/ilm/qa/multi-node/src/test/java/org/elasticsearch/xpack/indexlifecycle/TimeSeriesLifecycleActionsIT.java (hunk 1 above)
Comment (colings86) [reply x-pack/plugin/ilm/qa/multi-node/src/test/java/org/elasticsearch/xpack/indexlifecycle/TimeSeriesLifecycleActionsIT.java]: I think we should just change the message in this step to say something like:
```
No rollover info found for index [INDEX_NAME]. Either the index has not yet rolled over or a subsequent index was created outside of Index Lifecycle Management. 
```

**Comment by gwbrown** [comment]
CI failure seems unrelated and does not reproduce locally.

@elasticmachine test this please

**Comment by gwbrown** [comment]
Whoops, just realized I got mixed up and this didn't actually get any official approvals from reviewers - my bad.  Let me know if there were more changes you wanted me to make.
