### PR TITLE
Term Query: Be more strict during parsing

### LINKED ISSUE #12184: Term filter parser too lenient
The term filter parser does allow specifying more than one field without barfing and throwing an exception, resulting in a last one wins scenario.

Sample to reproduce

```
GET /foo/bar/_search
{
  "query": {
    "filtered": {
      "query": {
        "match_all": {}
      },
      "filter": {
        "term": {
          "field2": "bar",
          "field1": "foo"
        }
      }
    }
  }
}
```

This should throw an exception, once `field2` has been found and is tried to be overwritten.

### PR DESCRIPTION
**Pull request by spinscale**
The term query parser was too lenient during parsing and allowed to specify
more than one field, even though this expected to filter only for a single field.

This commit returns an exception if a query has been specified more than once.

Closes #12184

### CODE REVIEW

**Comment by colings86** [comment]
LGTM

File: core/src/main/java/org/elasticsearch/index/query/TermQueryParser.java [hunk 1]
```diff
@@ -63,6 +63,9 @@ public Query parse(QueryParseContext parseContext) throws IOException, QueryPars
                 // skip
             } else if (token == XContentParser.Token.START_OBJECT) {
                 // also support a format of "term" : {"field_name" : { ... }}
+                if (fieldName != null) {
+                    throw new QueryParsingException(parseContext, "[term] query does not support different field names, use [terms] query");
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/TermQueryParser.java]: I would modify the error message here, one cannot use the terms query instead against multiple fields, you should rather combine multiple term queries in a bool query I think

File: core/src/main/java/org/elasticsearch/index/query/TermQueryParser.java [hunk 2]
```diff
@@ -87,6 +90,9 @@ public Query parse(QueryParseContext parseContext) throws IOException, QueryPars
                 } else if ("boost".equals(currentFieldName)) {
                     boost = parser.floatValue();
                 } else {
+                    if (fieldName != null) {
+                        throw new QueryParsingException(parseContext, "[term] query does not support different field names, use [terms] query");
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/TermQueryParser.java]: same comment about the error message above

**Comment by javanna** [comment]
LGTM besides a minor comment

File: core/src/main/java/org/elasticsearch/index/query/TermQueryParser.java (hunk 1 above)
Comment (spinscale) [inline core/src/main/java/org/elasticsearch/index/query/TermQueryParser.java]: valid. fixed
