### PR TITLE
[ML] Feed errors starting the PyTorch process back to caller

### LINKED ISSUE #73769: Persistent task timeout for PyTorchModelIT.testEvaluate
**Build scan**:
https://gradle-enterprise.elastic.co/s/3fhraorgrz462
**Repro line**:
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluate" -Dtests.seed=7A6300C6BF1BC1F5 -Dtests.locale=da-DK -Dtests.timezone=Indian/Comoro -Druntime.java=11
**Reproduces locally?**:
No, its a timeout so happens periodicaly
**Applicable branches**:
Master
**Failure history**:
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:b646ed00-7efc-11e8-bf69-63c8ef516157,key:build.branch,negate:!f,params:(query:master,type:phrase),type:phrase,value:master),query:(match:(build.branch:(query:master,type:phrase))))),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:PyTorchModelIT),sort:!(process.time-start,desc))
**Failure excerpt**:
```
org.elasticsearch.xpack.ml.integration.PyTorchModelIT > testEvaluate FAILED
    org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:34482], URI [/_ml/trained_models/simple_model_to_evaluate/deployment/_start], status line [HTTP/1.1 500 Internal Server Error]
    {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Timed out when waiting for persistent task after 20s"}],"type":"illegal_state_exception","reason":"Timed out when waiting for persistent task after 20s"},"status":500}
        at __randomizedtesting.SeedInfo.seed([7A6300C6BF1BC1F5:50CE5F1A6354D1AE]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:330)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.startDeployment(PyTorchModelIT.java:172)
        at org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluate(PyTorchModelIT.java:91)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.ml.integration.PyTorchModelIT.testEvaluate" -Dtests.seed=7A6300C6BF1BC1F5 -Dtests.locale=da-DK -Dtests.timezone=Indian/Comoro -Druntime.java=11
```

Either the test needs more time for waiting for the persistent task, or there is some internal race condition where the listener is not alerted on a deployment start

### PR DESCRIPTION
**Pull request by davidkyle**
There are number of things that can go wrong launching the pytorch native process and loading a model. Most errors are due to mis-configuration and are easily resolved if a user can see the error message in the response of the `_start` deployment API call rather than buried in the log. 

Using the persistent tasks framework the process for this is:
1. The master node receives the `_start` request allocates the task and updates the clusterstate
2. The `_start` request waits for a change in status of the persistent task 
3. Some other node notices the new task and starts executing the task
4. The native process is launched and model loaded
5. If successful the p. task status is set to `STARTED`
    - The `_start` request on the master node notices the new status and returns success
6. If an error occurs the p. task status is set to `FAILED` and a failure reason added to the p. task state
    - The `_start` request on the master node notices the `FAILED` state and extracts the failure reason
    - The p. task is now removed from the clusterstate
    - The `_start` request returns an error with the failure reason

This is slightly different to AD jobs where the AutoDetectProcessManager first sets the job state to `FAILED` with a reason which is noticed by the `_open` request then AutoDetectProcessManager removes the p. task. Here is p. task is removed in the transport handler I found the flow of this code easier to follow. 

This change also fixes a test failure in PyTorchModelIT by adding an index refresh so the task configuration document is detected. 

Closes #73769

Non issue as this is iterating on a feature in un released code

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java [hunk 1]
```diff
@@ -117,16 +120,17 @@ private void doStartDeployment(TrainedModelDeploymentTask task) {
                 processContext.startProcess();
                 processContext.loadModel(modelLoadedListener);
             },
-            e -> failTask(task, e)
+            e -> failTask(task,
+                String.format(Locale.ROOT, "[%s] search for task config failed with error [%s]", task.getModelId(), e))
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/deployment/DeploymentManager.java:124]: I think it would be useful to log the trace here and above. I am not sure if the trace is included in the `Exception#toString` method.

**Review by benwtrent — APPROVED** [review]

**Comment by davidkyle** [comment]
run elasticsearch-ci/part-2

**Comment by davidkyle** [comment]
run elasticsearch-ci/part-2

**Comment by davidkyle** [comment]
run elasticsearch-ci/part-2

**Review by benwtrent — APPROVED** [review]

**Comment by davidkyle** [comment]
run elasticsearch-ci/part-2

I am trying to get the tests to run on CentOS 8 where they have been failing due to elastic/ml-cpp#1933. I've had SUSE and Ubuntu so far fingers crossed for this time

**Comment by davidkyle** [comment]
run elasticsearch-ci/part-2
