### PR TITLE
Await all pending activity in testConnectAndDisconnect

### LINKED ISSUE #40030: [CI] NodeConnectionsServiceTests. testConnectAndDisconnect & testOnlyBlocksOnConnectionsToNewNodes failed
Multiple jobs failed for NodeConnectionsServiceTests#testConnectAndDisconnect & NodeConnectionsServiceTests#testOnlyBlocksOnConnectionsToNewNodes tests.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/445/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu8,nodes=immutable&&linux&&docker/72/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=java11,nodes=immutable&&linux&&docker/72/console

Tried to reproduce locally but it did not with following command:
```
./gradlew :server:unitTest \
  -Dtests.seed=8231EE33CCE16B45 \
  -Dtests.class=org.elasticsearch.cluster.NodeConnectionsServiceTests \
  -Dtests.method="testConnectAndDisconnect" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" \
  -Dtests.locale=pt-BR \
  -Dtests.timezone=Pacific/Pohnpei \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

```
./gradlew :server:unitTest \
  -Dtests.seed=8231EE33CCE16B45 \
  -Dtests.class=org.elasticsearch.cluster.NodeConnectionsServiceTests \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/UTC \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by DaveCTurner**
It looks like this test can finish while there are still asynchronous
connection attempts in flight, causing test failures as reported in #40030.
This change ensures that the test waits for everything to settle down before
the end of the test.

NB I was unable to reproduce this failure, although it's affected quite a
number of CI runs. This is my best guess.

This also unmutes `testOnlyBlocksOnConnectionsToNewNodes`: the only failures of
_this_ test that I could see were related to earlier failures.

Closes #40030

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/NodeConnectionsServiceTests.java [hunk 1]
```diff
@@ -106,46 +105,55 @@ public void testConnectAndDisconnect() throws Exception {
...
+                        assertConnectedExactlyToNodes(nodes);
+                    } else {
+                        assertBusy(() -> assertConnectedExactlyToNodes(nodes));
+                    }
                 }
             }
+        } finally {
+            assertTrue(stopReconnecting.compareAndSet(false, true));
+            reconnectionThread.join();
+            ensureConnections(service);
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/cluster/NodeConnectionsServiceTests.java]: I would prefer to put ensureConnections outside the finally block to ensure that if the test fails, we see the original error rather than potentially an error from ensureConnections.

**Review by henningandersen — APPROVED** [review]
LGTM.

I added one small comment.

**Comment by DaveCTurner** [comment]
Relates https://github.com/elastic/elasticsearch/pull/39629
