### PR TITLE
SQL: Fix milliseconds handling in intervals

### LINKED ISSUE #41635: SQL: incorrect fractional value in duration expression
The following query:
```
POST /_xpack/sql
{
  "query": "SELECT INTERVAL '0.23' SECOND"
}
```
will yield the following result:
```
{"columns":[{"name":"INTERVAL '0.23' SECOND","type":"interval_second"}],"rows":[["PT0.023S"]]}
```
which contains the incorrect fractional digits value `.023` instead of expected `.230`/`.23`.

The [protocol tests](https://raw.githubusercontent.com/elastic/elasticsearch/master/x-pack/plugin/sql/qa/src/main/java/org/elasticsearch/xpack/sql/qa/SqlProtocolTestCase.java) also accommodate this error and should be corrected.

### PR DESCRIPTION
**Pull request by bpintea**
This PR fixes:
- the parsing of milliseconds in intervals: everything past the `.` used to be converted as-is to milliseconds, with no normalisation of the unit; thus, a value of `.23` ended up as 23 millis in the interval, instead of 230.
- the printing of a trailing .0, in case the interval lacks the fractional part;
- tests generating a random millisecond value used to simply print it in the string about to be evaluated without a necessary front-filling of `0`[s], where the amount was below 100/10.

(The combination of first and last issues above, plus statistical "luck" made the incorrect handling pass the tests.)

Closes #41635.

### CODE REVIEW

**Review by costin — APPROVED** [review]
Nice catch. The `.0` was bothersome in the `INTERVAL`s - we didn't support millis yet they got displayed.

File: x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/StringUtils.java [hunk 1]
```diff
@@ -129,8 +129,14 @@ public static String toString(Object value) {
             sb.append(":");
             durationInSec = durationInSec % SECONDS_PER_MINUTE;
             sb.append(indent(durationInSec));
-            sb.append(".");
-            sb.append(TimeUnit.NANOSECONDS.toMillis(d.getNano()));
+            long millis = TimeUnit.NANOSECONDS.toMillis(d.getNano());
+            if (millis > 0) {
+                sb.append(".");
+                while (millis % 10 == 0) {
```
Comment (matriv) [inline x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/proto/StringUtils.java]: Same here.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/DateUtils.java [hunk 2]
```diff
@@ -136,8 +136,14 @@ public static String toString(Object value) {
             sb.append(":");
             durationInSec = durationInSec % SECONDS_PER_MINUTE;
             sb.append(indent(durationInSec));
-            sb.append(".");
-            sb.append(TimeUnit.NANOSECONDS.toMillis(d.getNano()));
+            long millis = TimeUnit.NANOSECONDS.toMillis(d.getNano());
+            if (millis > 0) {
+                sb.append(".");
+                while (millis % 10 == 0) {
```
Comment (matriv) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/DateUtils.java]: Alternatively you could just iterate on the string millis from end->start and remove all zeroes.
Don't know if performance wise makes sense...

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/literal/interval/Intervals.java [hunk 3]
```diff
@@ -341,6 +341,10 @@ TemporalAmount parse(Source source, String string) {
                                             + ": negative value [{}] not allowed (negate the entire interval instead)",
                                     v);
                         }
+                        if (units.get(unitIndex) == TimeUnit.MILLISECOND && number.length() < 3) {
+                            // normalize the number past DOT to millis
+                            v *= number.length() < 2 ? 100 : 10;
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/literal/interval/Intervals.java]: Same concept here, you could avoid the multiplication by creating a string with right zero padding and then read is as number.

**Review by matriv — APPROVED** [review]
LGTM. Left some comments which are just suggestions, maybe your approach is better :-)

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/DateUtils.java (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/util/DateUtils.java]: I've also fluttered a bit between the two approaches. I went with this approach since generally arithmetic operations should be faster. But anyways, micro-optimisations.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/literal/interval/Intervals.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/literal/interval/Intervals.java]: This might be changed later if we ever bring the nanos to intervals and a multiplication might be more succinct. But yes, also here debatable.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by polyfractal** [comment]
Should this be targeting `v7.6.1` instead of `v7.6.0`?  E.g. we're well into feature freeze for 7.6 and this doesn't look critical?

(Commenting because I'm curating release notes and this one caught my eye being still open)

**Comment by bpintea** [comment]
> E.g. we're well into feature freeze for 7.6 and this doesn't look critical?

Sure, can wait for the next patch, not critical.

**Comment by bpintea** [comment]
> polyfractal added v7.6.0 and removed v7.6.1 labels 3 days ago

@polyfractal I didn't merge this into 7.6 yet (as per the conversation above), so it won't be in 7.6.1. Will do that as soon as 7.6.1 is released. Sorry for the confusion.

**Comment by polyfractal** [comment]
Sorry, this was my fault :)  The release script just automatically re-labels things, and I forgot to go look through them to see if any were incorrectly re-labeled.  I'll reset the label and set a backport-pending on it

Apologies for the hassle!
