### PR TITLE
Fix synthetic source for empty nested objects

### LINKED ISSUE #111811: Synthetic source construction fails for empty nested objects
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

xx

### Problem Description

Synthetic source construction fails for empty nested objects.

### Steps to Reproduce

```
PUT /my_index
{
  "mappings": {
    "_source": { "mode": "synthetic" },
    "properties": {
      "obj": {
        "type": "nested",
        "properties": {
          "k": {
              "type": "keyword"
          }
        }
      }
    }
  }
}

PUT my_index/_doc/1
{
  "obj": [{"k": "key1"}, {"k": null}]
}
```

```
GET /my_index/_doc/1
```

```
    "statusCode": 500,
    "body": {
        "error": {
            "root_cause": [
                {
                    "type": "json_generation_exception",
                    "reason": "Can not start an object, expecting field name (context: Object)"
                }
            ],
            "type": "json_generation_exception",
            "reason": "Can not start an object, expecting field name (context: Object)",
            "suppressed": [
                {
                    "type": "illegal_state_exception",
                    "reason": "Failed to close the XContentBuilder",
                    "caused_by": {
                        "type": "i_o_exception",
                        "reason": "Unclosed object or array found"
                    }
                }
            ]
        },
        "status": 500
    },
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by lkts**
Closes #111811.

### CODE REVIEW

**Comment by lkts** [comment]
I think this is a good candidate for a backport to 8.15 too.

**Review by martijnvg — APPROVED** [review]
LGTM

**Review by dnhatn — APPROVED** [review]
LGTM2. Thanks Sasha!

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 1]
```diff
@@ -843,12 +843,10 @@ public void write(XContentBuilder b) throws IOException {
                 return;
             }
 
-            if (isFragment == false) {
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:846]: `isFragment` is not needed, then?

File: server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java [hunk 2]
```diff
@@ -463,17 +463,14 @@ public boolean hasValue() {
...
                 leafStoredFieldLoader.advanceTo(children.get(0));
                 leafSourceLoader.write(leafStoredFieldLoader, children.get(0), b);
-                b.endObject();
             } else {
                 b.startArray(leafName());
                 for (int childId : children) {
-                    b.startObject();
                     leafStoredFieldLoader.advanceTo(childId);
                     leafSourceLoader.write(leafStoredFieldLoader, childId, b);
-                    b.endObject();
```
Comment (kkrik-es) [inline server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java:476]: These changes here and above are somewhat surprising.. Is the idea that nested objects will be adding their own `start/endObject` tags, so we don't need to do it at the nested object level?

**Comment by kkrik-es** [comment]
We probably need to port this to 8.15 too.

File: server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java [hunk 3]
```diff
@@ -1737,6 +1737,30 @@ public void testSyntheticNestedWithIncludeInRoot() throws IOException {
...
+            b.startArray("path");
+            {
+                b.startObject().field("foo", "A").endObject();
+                b.startObject().nullField("foo").endObject();
+            }
+            b.endArray();
+        });
+        assertEquals("""
+            {"path":[{"foo":"A"},{}]}""", syntheticSource);
+    }
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java:1762]: We should also test with a single child like:
```
 {
            var syntheticSource = syntheticSource(documentMapper, b -> {
                b.startArray("path");
                {
                    b.startObject().nullField("foo").endObject();
                }
                b.endArray();
            });
            assertEquals("""
                    {"path":{}}""", syntheticSource);
        }
```

Should we also have the same tests with object (instead of nested) mappers?

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java (hunk 1 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:846]: It's still needed to not always start an object with a field name. For nested we need to be in control since we make a distinction between single and multi-children.

**Review by jimczi — COMMENTED** [review]
Good catch @lkts , I left a comment regarding the tests.

File: server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java (hunk 2 above)
Comment (lkts) [reply server/src/main/java/org/elasticsearch/index/mapper/NestedObjectMapper.java:476]: Yes, `leafSourceLoader` is responsible for these tags now.

File: server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java (hunk 3 above)
Comment (lkts) [reply server/src/test/java/org/elasticsearch/index/mapper/NestedObjectMapperTests.java:1762]: We test both objects and nested with this configuration using our integration tests (that's how i found this).

**Comment by lkts** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/111982)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
