### PR TITLE
Reject multiple methods in `percentiles` aggregation

### LINKED ISSUE #26095: Percentiles aggregation allows multiple methods
**Elasticsearch version** (`bin/elasticsearch --version`): git revision 82fa531ab4 (HEAD revision as of now) but this behavior can be reproduced also with Elasticsearch 5.x.

**Description of the problem including expected versus actual behavior**:

The percentiles aggregation allows to use the `t-digest` or `HDR` histogram approaches. Although they should be mutually exclusive, it is possible for users to define options for both approaches which is confusing because only the second approach is applied. 

**Steps to reproduce**:

1. Insert a document into an empty index:

```
POST /my_index/doc
{
    "load_time": 20
}
```

2. Run the following aggregation from the docs but specify `tdigest` and `hdr` options:

```
GET /_search
{
   "aggs": {
      "load_time_outlier": {
         "percentiles": {
            "field": "load_time",
            "percents": [99],
            "tdigest": {
               "compression": 200
            },
            "hdr": {
               "number_of_significant_value_digits": 3
            }
         }
      }
   }
}
```

* **Actual outcome**: It produces results.
* **Expected outcome**: Specifying options for both `tdigest` and `hdr` should be considered invalid and Elasticseach should throw an Exception.

### PR DESCRIPTION
**Pull request by cbuescher**
Currently the `percentiles` aggregation allows specifying both possible methods
in the query DSL, but only the later one is used. This changes it to rejecting
such requests with an error. Setting the method multiple times via the java API
still works (and the last one wins).

Closes #26095

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java [hunk 1]
```diff
@@ -293,4 +313,29 @@ protected int innerHashCode() {
     public String getType() {
         return NAME;
     }
+
+    /**
+     * Private specialization of this builder that should only be used by the parser, this enables us to
+     * overwrite {@link #method()} to check that it is not called twice when parsing xContent and throw
+     * an error while the Java API should allow this
+     */
+    private static class InternalBuilder extends PercentilesAggregationBuilder {
```
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java]: In a first wip of ths PR I was doing the checks if the setter was called multiple times in the original builder, but that felt akward since it would also affect the java api and would mean the PercentilesAggregationBuilder would somehow need that call counter somewhere. Attempts to use ConstructingObjectParser to check that methods was specified only once also were not promosing, so I went with this internal temporary object for the parser output for now as it felt least invasive.

File: core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java [hunk 2]
```diff
@@ -103,7 +104,26 @@
...
+        InternalBuilder internal = PARSER.parse(parser, new InternalBuilder(aggregationName), null);
+        // we need to return a PercentilesAggregationBuilder for equality checks to work
+        PercentilesAggregationBuilder returnedAgg = new PercentilesAggregationBuilder(internal.name);
+        setIfNotNull(returnedAgg::valueType, internal.valueType());
+        setIfNotNull(returnedAgg::format, internal.format());
+        setIfNotNull(returnedAgg::missing, internal.missing());
+        setIfNotNull(returnedAgg::field, internal.field());
+        setIfNotNull(returnedAgg::script, internal.script());
+        setIfNotNull(returnedAgg::method, internal.method());
+        setIfNotNull(returnedAgg::percentiles, internal.percentiles());
```
Comment (polyfractal) [inline core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java]: Should we also check for empty arrays too?   Or maybe down in the `percentiles()` method?

**Comment by polyfractal** [comment]
LGTM.  The requirement to keep java builder behavior unchanged seems to complicate life a bit, but the solution seems reasonable to me :)

File: core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java (hunk 2 above)
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java]: Sure, I will add something along those lines.
