### PR TITLE
Fix open/close race in ConnectionManagerTests

### LINKED ISSUE #49903: [CI] ConnectionManagerTests.testConcurrentConnectsAndDisconnects timed out
`ConnectionManagerTests.testConcurrentConnectsAndDisconnects` hit the 20 minute test timeout in a couple of builds on the 7.5 branch.

* https://gradle-enterprise.elastic.co/s/367rox57bzflk
* https://gradle-enterprise.elastic.co/s/levbg6qu3y5my

The repro commands are:

```
./gradlew ':server:test' --tests "org.elasticsearch.transport.ConnectionManagerTests.testConcurrentConnectsAndDisconnects" \
  -Dtests.seed=9A5390B666099003 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksh-DE \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

and:

```
./gradlew ':server:test' --tests "org.elasticsearch.transport.ConnectionManagerTests.testConcurrentConnectsAndDisconnects" \
  -Dtests.seed=E8171F27A4EF04C1 \
  -Dtests.security.manager=true \
  -Dtests.locale=en \
  -Dtests.timezone=America/Argentina/La_Rioja \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

Neither reproduces locally.

The error that causes this is:

```
WARNING: Uncaught exception in thread: Thread[elasticsearch[ConnectionManagerTests][generic][T#4],5,TGRP-ConnectionManagerTests]
java.lang.AssertionError: Expected node to be connected
	at __randomizedtesting.SeedInfo.seed([E8171F27A4EF04C1]:0)
	at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$10(ConnectionManagerTests.java:171)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
	at org.elasticsearch.common.util.concurrent.ListenableFuture$1.doRun(ListenableFuture.java:112)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$DirectExecutorService.execute(EsExecutors.java:225)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:106)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.lambda$done$0(ListenableFuture.java:98)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.done(ListenableFuture.java:98)
	at org.elasticsearch.common.util.concurrent.BaseFuture.set(BaseFuture.java:144)
	at org.elasticsearch.common.util.concurrent.ListenableFuture.onResponse(ListenableFuture.java:127)
	at org.elasticsearch.transport.ConnectionManager.lambda$connectToNode$1(ConnectionManager.java:165)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63)
	at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$7(ConnectionManagerTests.java:148)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:703)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Then the fact that the node is not connected makes the code hang for 20 minutes and trigger the test timeout.

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently we reuse the same test connection for all connection attempts
in the testConcurrentConnectsAndDisconnects test. This means that if the
connection fails due to a pre-existing connection, the connection will
be closed impacting the state of all connection attempts. This commit
fixes the test, by returning a unique connection for each attempt.

Fixes #49903.

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java [hunk 1]
```diff
@@ -124,11 +124,10 @@ public void onNodeDisconnected(DiscoveryNode node, Transport.Connection connecti
         assertEquals(1, nodeDisconnectedCount.get());
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/49903")
     public void testConcurrentConnectsAndDisconnects() throws BrokenBarrierException, InterruptedException {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java]: Should we rename this to just `testConcurrentConnects`? It doesn't obviously do any disconnecting.

File: server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java [hunk 2]
```diff
@@ -124,11 +124,10 @@ public void onNodeDisconnected(DiscoveryNode node, Transport.Connection connecti
...
         DiscoveryNode node = new DiscoveryNode("", new TransportAddress(InetAddress.getLoopbackAddress(), 0), Version.CURRENT);
-        Transport.Connection connection = new TestConnect(node);
         doAnswer(invocationOnMock -> {
+            Transport.Connection connection = new TestConnect(node);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java]: Could we keep track of all of these connections and assert that all but one of them has been closed when the dust has settled?

File: server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java [hunk 3]
```diff
@@ -124,11 +124,10 @@ public void onNodeDisconnected(DiscoveryNode node, Transport.Connection connecti
...
             ActionListener<Transport.Connection> listener = (ActionListener<Transport.Connection>) invocationOnMock.getArguments()[2];
             if (rarely()) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java]: I think it would be good to have these three branches chosen with more equal probabilities (and similarly for the connection validator lambda). As it is, we only complete both listeners on the same thread one in every 10,000 runs I think.

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Looks good, I left a few small extra requests.

File: server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java [hunk 4]
```diff
@@ -198,6 +207,16 @@ public void testConcurrentConnectsAndDisconnects() throws BrokenBarrierException
         });
 
         assertEquals(10, nodeConnectedCount.get() + nodeFailureCount.get());
+
+        // Only a single connection attempt should be open.
+        long size = connections.stream().filter(c -> !c.isClosed()).count();
+        assertEquals(1, size);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java]: Sorry, I misled you, this can be zero if all 10 connection attempts fail.

File: server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java [hunk 5]
```diff
@@ -198,6 +207,16 @@ public void testConcurrentConnectsAndDisconnects() throws BrokenBarrierException
         });
 
         assertEquals(10, nodeConnectedCount.get() + nodeFailureCount.get());
+
+        // Only a single connection attempt should be open.
+        long size = connections.stream().filter(c -> !c.isClosed()).count();
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/transport/ConnectionManagerTests.java]: `== false` ☠️

**Review by DaveCTurner — COMMENTED** [review]
Test failure looks relevant - see comment. Also could you even out the probabilities of the branches in the `ConnectionValidator` too?

**Review by DaveCTurner — APPROVED** [review]
LGTM thanks for the extra iterations TIm
