### PR TITLE
Testclusters: implement support to install plugins

### LINKED ISSUE #37889: TestClustersPluginIT fails with connection errors
I haven't been able to reproduce the failures locally. This looks similar to #37218, but the failure mode seems different.

Just today, I've seen this test suite fail in CI ~10 times. The test seems to fail on master as well as 6.x.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1195

Relevant excerpt from the logs:
```
 Caused by: java.lang.IllegalStateException: Connection attempt to node{::myTestCluster} failed
    	at org.elasticsearch.gradle.testclusters.ElasticsearchNode.lambda$waitForUri$2(ElasticsearchNode.java:163)
    	at org.elasticsearch.gradle.testclusters.ElasticsearchNode.lambda$waitForAllConditions$7(ElasticsearchNode.java:414)
    	... 74 more
    	Suppressed: java.lang.IllegalStateException: Connection attempt to node{::myTestCluster} failed
    		at org.elasticsearch.gradle.testclusters.ElasticsearchNode.lambda$waitForUri$2(ElasticsearchNode.java:163)
    		at org.elasticsearch.gradle.testclusters.ElasticsearchNode.lambda$waitForAllConditions$7(ElasticsearchNode.java:414)
    		at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
    		at org.elasticsearch.gradle.testclusters.ElasticsearchNode.waitForAllConditions(ElasticsearchNode.java:401)
    		at org.elasticsearch.gradle.testclusters.ElasticsearchNode.getHttpSocketURI(ElasticsearchNode.java:229)
    		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
    		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
    		at org.codehaus.groovy.runtime.metaclass.MethodMetaProperty$GetBeanMethodMetaProperty.getProperty(MethodMetaProperty.java:76)
    		at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:63)
    		at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
    		at build_2kot767fmb696rtvvmg8tn437$_run_closure1$_closure11$_closure16.doCall(/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+intake/buildSrc/src/testKit/testclusters/build.gradle:34)
    		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    		at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
    		at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
    		at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
    		at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
    		at groovy.lang.Closure.call(Closure.java:411)
    		at groovy.lang.Closure.call(Closure.java:427)
    		at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:647)
    		at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:620)
    		at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:284)
    		at 
```

### PR DESCRIPTION
**Pull request by alpar-t**
This change extends the DSL and implements calling the commands to install plugins.
The plugin install dir is not configurable, for this reason we have to sync the working dir. 
This fixes some other issues for which the plugin was muted and thus closes #37889. 
Since the test was muted, some changes around distribution name are also required,
so there are some change in this PR that don't relate directly, but I didn't want to add new functionality without enabling the test.

### CODE REVIEW

File: buildSrc/src/main/java/org/elasticsearch/gradle/Distribution.java [hunk 1]
```diff
@@ -20,23 +20,66 @@
...
+        }
+    }
+
+    private enum OS {
+        WINDOWS,
+        MAC,
+        LINUX
+    }
+
+    private OS getOS() {
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/Distribution.java]: This is common functionality that tends to get reimplemented a lot. We rely on the Gradle internal `OperatingSystem` class a bunch of other places for this. We should either 1) just continue to use that type since it's so pervasive or 2) provide a replacement and use it consistently across `buildSrc`. We can do this as a separate PR.

File: buildSrc/src/main/java/org/elasticsearch/gradle/Distribution.java [hunk 2]
```diff
@@ -20,23 +20,66 @@
...
         return fileName;
     }
 
     public String getFileExtension() {
-        return fileExtension;
+        if (this.equals(INTEG_TEST)) {
+            return "zip";
+        } else {
+            switch (getOS()) {
+                case LINUX:
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/Distribution.java]: Personally, I always like to add an explicit comment whenever there is a purposeful fall-through in a `switch` expression, just so future folks know it wasn't a mistake.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 3]
```diff
@@ -166,12 +183,20 @@ private void waitForUri(String description, String uri) {
         });
     }
 
+    /**
+     * Returns a stream of lines in the generated logs similar to Files.lines
+     *
+     * @return stream of log lines
+     */
+    public Stream<String> logLines() throws IOException {
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Is this intended for users of the plugin to do something with the log output in their build scripts?

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 4]
```diff
@@ -183,34 +208,69 @@ synchronized void start() {
...
+        );
+
+        startElasticsearchProcess();
+    }
+
+    private void runElaticsearchBinScript(String tool, String... args) {
+        services.loggedExec(spec -> {
+            spec.setEnvironment(getESEnvironment());
+            spec.workingDir(workingDir);
+            if (OperatingSystem.current().isWindows()) {
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: As mentioned above, here's an example of relying on Gradle's implementation of OS detection. We should probably come to an agreement on how to standardize this.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 5]
```diff
@@ -183,34 +208,69 @@ synchronized void start() {
...
+        });
     }
 
-    private void startElasticsearchProcess(Path distroArtifact) {
-        logger.info("Running `bin/elasticsearch` in `{}` for {}", workingDir, this);
+    private Map<String, String> getESEnvironment() {
+        Map<String, String> environment= new HashMap<>();
+        environment.put("JAVA_HOME", getJavaHome().getAbsolutePath());
+        environment.put("ES_PATH_CONF", configFile.getParent().toString());
+        environment.put("ES_JAVA_OPTS", "-Xms512m -Xmx512m");
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: This seems like something that makes sense to be exposed as a config option rather than be hard-coded.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 6]
```diff
@@ -346,6 +409,7 @@ private void configure()  {
             config.put("cluster.initial_master_nodes", "[" + nodeName + "]");
         }
         try {
+            Files.delete(configFile);
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: I've seen a number of instances of us creating big strings in memory. `LoggedExec` is another, more problematic instance of this. Individually, these are not big issues but we need to be careful about this stuff as the build becomes more complex, and we rely more on the daemon, memory pressure will become an issue. We should try and keep this in mind and prefer streaming this stuff when possible.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/TestClustersPlugin.java [hunk 7]
```diff
@@ -120,10 +105,18 @@ public void apply(Project project) {
                 sync.from((Callable<List<FileTree>>) () ->
                     helperConfiguration.getFiles()
                         .stream()
-                        .map(project::zipTree)
+                        .map(file -> {
+                          if (file.getName().endsWith(".zip")) {
+                              return project.zipTree(file);
+                          } else if (file.getName().endsWith("tar.gz")) {
+                              return project.tarTree(project.getResources().gzip(file));
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/TestClustersPlugin.java]: We can actually just call `tarTree` directly here as it will interpret `.tar.gz` as a compressed file automatically.

> Unless custom implementation of resources is passed, the tar tree attempts to guess the compression based on the file extension.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/TestClustersPlugin.java [hunk 8]
```diff
@@ -302,9 +295,11 @@ private static void autoConfigureClusterDependencies(
         project.afterEvaluate(ip -> container.forEach(esNode -> {
             // declare dependencies against artifacts needed by cluster formation.
             String dependency = String.format(
-                "org.elasticsearch.distribution.zip:%s:%s@zip",
-                esNode.getDistribution().getFileName(),
-                esNode.getVersion()
+                "unused:%s:%s:%s@%s",
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/TestClustersPlugin.java]: What is "unused"?

File: buildSrc/src/main/java/org/elasticsearch/GradleServicesAdapter.java [hunk 9]
```diff
@@ -70,4 +72,8 @@ public FileTree zipTree(File zipPath) {
     public FileCollection fileTree(File dir) {
         return project.fileTree(dir);
     }
+
+    public void loggedExec(Action<ExecSpec> action) {
+        LoggedExec.exec(project, action);
```
[the remark this answers is not in the document]
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/GradleServicesAdapter.java]: The intent was to eliminate uses of LoggedExec as a task and keeps the methods only.
I agree there's opportunity for cleanup and improvement here, but wouldn't want to do it in this PR.

File: buildSrc/src/main/java/org/elasticsearch/gradle/Distribution.java (hunk 1 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/Distribution.java]: I agree, we could move this in it's own class as needed, I just wanted to avoid relying on Gradle classes here.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java (hunk 3 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Yes, right now it's used by a test to verify the plugin is indeed loaded.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java (hunk 4 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Good catch, i  missed this one. I'll move the  OS detection out to it's own class and replace it here

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java (hunk 5 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: There are lots of things that fall into this category.
The reason it's not a config option is that I would like  to find the use-cases that need to change these and figure out the best DSL to do so at that time. 
We will likely not do this, but just for the sake of example, we could expose something like this using templates of "small", "medium" "large" instead of direct configuration if we feel users don't care about details.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/TestClustersPlugin.java (hunk 8 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/TestClustersPlugin.java]: the group name, not used right now since the repo is a flat dir. 
Of course this will only work in tests right now, but I plan to deal with this as a follow up as I prepare changes to use testclusters with rest integ test task.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java [hunk 10]
```diff
@@ -311,16 +371,19 @@ private void waitForProcessToExit(ProcessHandle processHandle) {
...
-            Files.createDirectories(configFile.getParent());
-            Files.createDirectories(confPathRepo);
-            Files.createDirectories(confPathData);
-            Files.createDirectories(confPathLogs);
-        } catch (IOException e) {
-            throw new UncheckedIOException(e);
-        }
+    private void createWorkingDir(Path distroExtractDir) throws IOException {
+        services.sync(spec -> {
+            spec.from(distroExtractDir.toFile());
```
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: In ClusterFormationTasks, we always have a fresh directory we extract into. This isn't great for build performance, but it means we don't have any possiblity of old stuff being used. From a reproducibility perspective, I think we should wipe the data/logs/temp dirs here?

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java (hunk 6 above)
Comment (rjernst) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Why do we need to delete the config file when it is written below this?

Comment (rjernst) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: LoggedExec is a special case. We could redirect output to files, but most of the exec calls are tiny invocations, so the I/O overhead to disk is much more than writing into the heap. But I agree here we should consider writing the file through a stream instead of building up in a String.

**Review by rjernst — COMMENTED** [review]
Looks pretty good, a few comments

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java (hunk 10 above)
Comment (mark-vieira) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: FYI, `sync()` does exactly this. In contrast to `copy()` a sync first deletes the target folder before performing the copy.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java (hunk 6 above)
Comment (mark-vieira) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: Agreed. If it hasn't been problematic yet it may just not be an issue. We still have a situation where a bad execution could potentially create a load of output that blows out the heap. We could pretty simply put some safeguards here to ensure the output doesn't exceed some configured threshold and truncate if it does. Separate discussion 😄

File: buildSrc/src/main/java/org/elasticsearch/gradle/Distribution.java (hunk 2 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/Distribution.java]: I ended up removing this switch statement.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/TestClustersPlugin.java (hunk 7 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/TestClustersPlugin.java]: done

File: buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java (hunk 6 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java]: I removed it, it's an oversight.

**Comment by atorok** [comment]
@mark-vieira @rjernst ready for another review

**Review by mark-vieira — APPROVED** [review]
