### PR TITLE
SQL: Fix issues with format=txt when paging through result sets and in mixed node environments

### LINKED ISSUE #83581: SQL: REST queries with format=txt fail during rolling upgrade
### Elasticsearch Version

8.2.0-SNAPSHOT

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

OSX

### Problem Description

While there are some restrictions with SQL during rolling upgrades, simple queries (without scrolling) are expected to yield results during rolling upgrades. This is currently not the case for REST queries with `?format=txt` if the upgrade spans across a version that is used as the `minCompatibleShardNode` version in search requests. In this case, the request fails. E.g. during an upgrade from 7.17.1 to 8.2.0, a request to the 8.2 node with `/_sql?format=txt` fails with:

```
{
  "error": {
    "root_cause": [
      {
        "type": "sql_illegal_argument_exception",
        "reason": "Unsupported cursor version [7.17.1], expected [8.2.0]"
  },
  "status": 500
}
```

The problem is a combination of the query being redirected from the 8.2 node to 7.17 and `TextFormatterCursor` trying to deserialize the cursor in the response on the 8.2 node.

### Steps to Reproduce

1. Create a two node cluster with ES 7.17.1
2. Create any index
3. Upgrade one node to 8.2.0-SNAPSHOT
4. Run any REST SQL query that returns a scroll cursor with `/_sql?format=txt` against the 8.2 node

### Logs (if relevant)

_No response_

### LINKED ISSUE #83788: SQL: Rest scroll requests with format=txt fail if last page is not empty and does not include a scroll cursor
### Elasticsearch Version

8.2.0-SNAPSHOT (but also affects 7.x releases)

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

The problem only happens with a cursor that
- produces the last page of the result set
- and the last page is non-empty

Currently, this mostly (only?) happens with queries returning a `ListCursor` but #83381 might also make search hit queries susceptible to this issue.

### Steps to Reproduce

1. Issue an SQL query that produces a `ListCursor` (e.g. `show tables`) and fetches more than half of the total records: `http post "localhost:9201/_sql?format=txt" query="show tables" fetch_size=50`
2. Use the returned cursor to fetch the remaining records: `http post "localhost:9201/_sql?format=txt" cursor="<cursor>" fetch_size=50`

Expected behavior: Remaining records are returned.

Observed behavior: Request fails with
```
{
    "error": {
        "reason": "Cannot find text formatter - this is likely a bug",
        "root_cause": [
            {
                "reason": "Cannot find text formatter - this is likely a bug",
                "type": "sql_illegal_argument_exception"
            }
        ],
        "type": "sql_illegal_argument_exception"
    },
    "status": 500
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by Luegg**
Resolves #83581
Resolves #83788

SQL REST requests using `format=txt` stand out from the other formats because the cursor needs to carry the formatter state from the initial request to subsequent scroll requests. The state is needed to be able to format the subsequent pages with column widths that match the widths in the first page.

Currently, this is solved by wrapping cursor objects together with the formatter state in `TextFormatterCursor`. Hence, a query might return a `ListCursor` and `TextFormat.PLAIN_TEXT` adds the necessary state when formatting the output. This approach is handy because a `TextFormatterCursor` is a `Cursor` and delegates calls to the wrapped cursor. Unfortunately, it also has some downsides that have been revealed when looking into #83581 and #83788:

- MediaType formatting is a concern of the REST layer of the plugin that does not have access to the serialization logic usually accessible through the `NamedWriteablesRegistry`. Because the formatting required to (de)serialize the cursors for the wrapping, this meant that the `Cursor` deserialization could only use a subset of `NamedWriteable`s specific to Cursors (namely the ones returned by `Cursors.getNamedWriteables`). This subset of writeables is not enough to deserialize `CompositeAggCursor` which lead to the surprising design that `CompositeAggCursor` has a `nextQuery` member consisting of the serialized `SearchSourceBuilder` whose deserialization is suspended until the call to `Cursor.nextPage`.
- `TextFormat.PLAIN_TEXT` had to deserialize the complete cursor to do it's work, not just the information relevant to the formatter. Because of the `min_compatible_version` redirects that occur during rolling upgrades, it can happen though that an upgraded node needs to deserialize a cursor from a redirected SQL query written by an older node. Because we do not offer any form of bwc for cursors, this causes an error and leads to #83581.

In this PR, I propose to change the design such that the REST layer can add state to the cursor strings without having to read or write instances of `Cursor`. This allows to address the issues described above and also made fixing #83788 very straightforward.

Attaching state to the cursor is achieved by extending the format of encoded cursors. Previously, an base64 encoded SQL cursor had the following wire format `<version><zoneId><cursor>`. Now, there are two different cursor types:

* `<version><zoneId><CursorType.NO_STATE><cursor>` for most cases
* `<version><ZoneOffset.UTC><CursorType.WITH_STATE><formatterState><base64encodedCursor>` for txt format cursors. Note, `<ZoneOffset.UTC>` could be any zone id because consumers will use the one encoded in `<base64encodedCursor>`.

This serialization format ensures that every version of ES can read and check the cursor version and produce an according error in case of a mismatch.

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/RestCursorState.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+import org.elasticsearch.xpack.sql.common.io.SqlStreamInput;
+import org.elasticsearch.xpack.sql.common.io.SqlStreamOutput;
+
+import java.io.IOException;
+import java.time.ZoneOffset;
+import java.util.List;
+
+import static org.elasticsearch.core.Tuple.tuple;
+
+public record RestCursorState(BasicFormatter formatter) implements Writeable {
```
Comment (Luegg) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/RestCursorState.java:28]: Not sure wether this class is a bit of an overkill right now but I added it for additional clarity and to organize the state related code in one place. Also, it could act as an extension point in the future in case we have to add additional state for other formatters. Alternatively, we could just pass `BasicFormatter` everywhere.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/FormatterState.java [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+package org.elasticsearch.xpack.sql.plugin;
+
+import org.elasticsearch.common.io.stream.StreamInput;
+import org.elasticsearch.common.io.stream.StreamOutput;
+import org.elasticsearch.common.io.stream.Writeable;
+import org.elasticsearch.xpack.sql.action.BasicFormatter;
+
+import java.io.IOException;
+
+public record FormatterState(BasicFormatter formatter) implements Writeable {
```
Comment (Luegg) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/FormatterState.java:17]: Not sure wether this class is a bit of an overkill right now but I added it for additional clarity to avoid passing `BasicFormatter` everywhere. Also, it could act as an extension point in the future in case we have to add additional state for other formatters.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/PlanExecutor.java [hunk 3]
```diff
@@ -120,7 +120,7 @@ public void nextPage(SqlConfiguration cfg, Cursor cursor, ActionListener<Page> l
      * `nextPage` for internal callers (not from the APIs) without metrics reporting.
      */
     public void nextPageInternal(SqlConfiguration cfg, Cursor cursor, ActionListener<Page> listener) {
-        cursor.nextPage(cfg, client, writableRegistry, listener);
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/PlanExecutor.java:123]: 👍

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlPlugin.java [hunk 4]
```diff
@@ -158,4 +159,9 @@ protected XPackLicenseState getLicenseState() {
             infoAction
         );
     }
+
+    @Override
+    public List<NamedWriteableRegistry.Entry> getNamedWriteables() {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlPlugin.java:164]: What's the advantage of sharing the cursors writables since in most of the code, the StreamInput is wrapped?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlClearCursorAction.java [hunk 5]
```diff
@@ -47,7 +47,7 @@ public static void operation(
         SqlClearCursorRequest request,
         ActionListener<SqlClearCursorResponse> listener
     ) {
-        Cursor cursor = Cursors.decodeFromStringWithZone(request.getCursor()).v1();
+        Cursor cursor = Cursors.decodeFromStringWithZone(request.getCursor(), planExecutor.writeableRegistry()).v1();
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlClearCursorAction.java:50]: Is there a case where the Cursors would not all use the same internal writeableRegistry regardless of the user request?
That is, why isn't it a constant and has to be passed in as a parameter?

**Review by costin — COMMENTED** [review]
I _think_ I understand what this PR tries to fix (thanks also to our offine discussion); a first round of comments:
1. The cursor type enum can be replaced with a writeOptional/boolean which is the pattern used elsewhere in StreamInput. This makes the intent clearer since it indicates that there's a state prefix or there isn't to be consumed by the actual cursor and also removes the need of another named registry. There's a discussion here on why that needs to be specified outside the cursor and why isn't the cursor itself handle this but that will become clearer in time hopefully.
2. I'm not clear why the writeable registry is parameterized - 👍 that we don't pass it to the cursor methods however, it is now being passed to Cursors; why is that?
3. the FormatterState interface is just a maker which extends NamedWriteable; an alternative is ask a lambda as a parameter instead (such a Consumer<StreamOutput> or similar) or add said method to the Formatter class and thus asking the argument to handle its serialization if needed.

**Comment by Luegg** [comment]
> 1. The cursor type enum can be replaced with a writeOptional/boolean which is the pattern used elsewhere in StreamInput. This makes the intent clearer since it indicates that there's a state prefix or there isn't to be consumed by the actual cursor and also removes the need of another named registry. There's a discussion here on why that needs to be specified outside the cursor and why isn't the cursor itself handle this but that will become clearer in time hopefully.

👍 makes sense, using `writeOptional` is a lot leaner.

> 2. I'm not clear why the writeable registry is parameterized - 👍 that we don't pass it to the cursor methods however, it is now being passed to Cursors; why is that?

`Cursors.decodeFromStringWithZone` needs the registry to be able to decode any payload. E.g. `CompositeAggCursor` contains a `SearchSourceBuilder` that can only be read with the global `NamedWriteableRegistry`.

> 3. the FormatterState interface is just a maker which extends NamedWriteable; an alternative is ask a lambda as a parameter instead (such a Consumer or similar) or add said method to the Formatter class and thus asking the argument to handle its serialization if needed.

I also need the marker interface to be able to register the state as a `NamedWriteable`. Alternatively, we could also do without `FormatterState` for now and pass `BasicFormatter` everywhere. I slightly prefer the interface because it makes the intent clearer.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlPlugin.java (hunk 4 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/SqlPlugin.java:164]: Not quite sure what you mean by `since in most of the code, the StreamInput is wrapped` but it became necessary because there is no way atm to combine two `NamedWriteableRegistry`. But `SqlStreamInput` needs to be able to decode both instances of `Cursor` and `SearchSourceBuilder` (in `CompositeAggCursor`) of which the later is only available through the global registry.

I think there are not really any major downsides though. Since the `NamedWriteableRegistry` uses fully qualified class names for the writeable "categories", there shouldn't be any visible effect for the other plugins.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlClearCursorAction.java (hunk 5 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TransportSqlClearCursorAction.java:50]: It's mostly because of `SearchSourceBuilder` (in `CompositeAggCursor`)

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java [hunk 6]
```diff
@@ -197,4 +198,36 @@ private void assertCursorNotCompatibleAcrossVersions(Version version1, RestClien
...
+    }
+
+    public void testFormatTxtQueryWithCursor(RestClient client) throws IOException {
+        // see https://github.com/elastic/elasticsearch/issues/83581
+        index("{\"foo\":1}", "{\"foo\":2}");
+
+        Request query = new Request("POST", "_sql");
+        XContentBuilder json = XContentFactory.jsonBuilder()
+            .startObject()
+            .field("query", "select foo from test order by foo")
```
Comment (astefan) [inline x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java:216]: Are there any tests covering `GROUP BY` and pagination with txt format? If not, please add one.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/RestSqlQueryAction.java [hunk 7]
```diff
@@ -49,6 +49,7 @@ protected RestChannelConsumer prepareRequest(RestRequest request, NodeClient cli
 
         return channel -> {
             RestCancellableNodeClient cancellableClient = new RestCancellableNodeClient(client, request.getHttpChannel());
+
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/RestSqlQueryAction.java:52]: Unnecessary empty line.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/FormatterState.java [hunk 8]
```diff
@@ -0,0 +1,21 @@
...
+ */
+
+package org.elasticsearch.xpack.sql.plugin;
+
+import org.elasticsearch.common.io.stream.NamedWriteable;
+import org.elasticsearch.common.io.stream.NamedWriteableRegistry;
+
+import java.util.List;
+
+public interface FormatterState extends NamedWriteable {
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/FormatterState.java:15]: Why this new interface? You can add directly the formatterstate to `Cursors` list of writeables.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/BasicFormatter.java [hunk 9]
```diff
@@ -4,11 +4,12 @@
  * 2.0; you may not use this file except in compliance with the Elastic License
  * 2.0.
  */
-package org.elasticsearch.xpack.sql.action;
+package org.elasticsearch.xpack.sql.plugin;
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/BasicFormatter.java:7]: Why?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TextFormat.java [hunk 10]
```diff
@@ -48,43 +46,21 @@
...
-                    response.cursor(Cursors.encodeToString(new TextFormatterCursor(cursor, formatter), zoneId));
-                }
-                // format with header
-                return formatter.formatWithHeader(response.columns(), response.rows());
-            } else if (formatter != null) { // should be initialized (wrapped by the cursor)
-                // format without header
-                return formatter.formatWithoutHeader(response.rows());
-            } else if (response.hasId()) {
-                // an async request has no results yet
-                return StringUtils.EMPTY;
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TextFormat.java:81]: Why hasn't this one been kept?

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/CursorTests.java [hunk 11]
```diff
@@ -99,7 +60,73 @@ public void testVersionHandling() {
...
+        Tuple<Cursor, ZoneId> decoded = decodeFromStringWithZone(withState, WRITEABLE_REGISTRY);
+        assertEquals(cursor, decoded.v1());
+        assertNull(decoded.v2());
+        assertNull(Cursors.decodeState(withState));
+    }
+
+    public void testAttachingStateToCursorFromOtherVersion() {
+        Cursor cursor = randomSearchHitCursor();
+        ZoneId zone = randomZone();
+        String encoded = encodeToString(cursor, Version.V_7_17_1, zone);
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/CursorTests.java:115]: Is there anything in particular with Version.V_7_17_1 or there can be any version?

**Review by astefan — COMMENTED** [review]
Left some comments.

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java [hunk 12]
```diff
@@ -1438,6 +1438,43 @@ public void testCompressCursor() throws IOException {
...
+
+    public void testNonEmptyLastPageTsv() throws IOException {
+        testNonEmptyLastPage("text/tab-separated-values");
+    }
+
+    private void testNonEmptyLastPage(String format) throws IOException {
+        // see https://github.com/elastic/elasticsearch/issues/83788
+        int size = 10;
+        // ensure that second page is neither empty nor full
+        int pageSize = size / 2 + 1;
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java:1457]: I don't see why it shouldn't be computed but `size` can be randomized indeed. Will update the test accordingly.

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java [hunk 13]
```diff
@@ -197,4 +198,36 @@ private void assertCursorNotCompatibleAcrossVersions(Version version1, RestClien
...
 
+    public void testFormatTxtQueryWithCursorOnNewNode() throws IOException {
+        testFormatTxtQueryWithCursor(newNodesClient);
+    }
+
+    public void testFormatTxtQueryWithCursorOnOldNode() throws IOException {
+        testFormatTxtQueryWithCursor(oldNodesClient);
+    }
+
+    public void testFormatTxtQueryWithCursor(RestClient client) throws IOException {
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java:209]: It's a very specific test to cover the bug described in https://github.com/elastic/elasticsearch/issues/83581. I'll try to find a more telling test name though and have more specific assertions.

[the remark this answers is not in the document]
Comment (astefan) [reply x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java:209]: You can mention the bug url in a comment in code. Any reason why you don't ask for the second page of results as well?

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java (hunk 6 above)
Comment (Luegg) [reply x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java:216]: the nature of the query doesn't really matter for this test but I'll make this explicit with a `randomFrom(...)`

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TextFormat.java [hunk 14]
```diff
@@ -48,43 +46,21 @@
...
+        Tuple<String, FormatterState> format(RestRequest request, FormatterState state, SqlQueryResponse response) {
+            if (state instanceof BasicFormatter basicFormatter) {
+                // scroll response
+                return tuple(basicFormatter.formatWithoutHeader(response.rows()), state);
+            } else if (response.columns() != null) {
+                // initial response
+                BasicFormatter formatter = new BasicFormatter(response.columns(), response.rows(), TEXT);
+
+                return tuple(formatter.formatWithHeader(response.columns(), response.rows()), formatter);
+            } else if (CollectionUtils.isEmpty(response.rows())) {
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TextFormat.java:58]: There is at least one case where `response.rows()` can be `null` (async results).

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/CursorTests.java (hunk 11 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/CursorTests.java:115]: nope, I think it can be any version < current. But we do not have a `randomVersion` yet.

Comment (astefan) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/CursorTests.java:115]: I think we have a variant of randomVersion: `VersionUtils.randomVersionBetween`

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TextFormat.java (hunk 10 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/TextFormat.java:81]: I'll try to revert the original logic to avoid regressions in the async API.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/CursorTests.java (hunk 11 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/CursorTests.java:115]: Turns out I didn't search hard enough: There is `VersionUtils.randomVersion`

**Review by Wow123419 — COMMENTED** [review]
Fake

File: x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/qa/mixed-node/src/test/java/org/elasticsearch/xpack/sql/qa/mixed_node/SqlCompatIT.java:209]: It's right on the next line :) But I guess I'll move it into a doc comment for improved visibility.

The second page is not really of concern for this particular bug. The initial query request used to fail during a rolling upgrade, not the scroll request.

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/CursorTests.java (hunk 11 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/plugin/CursorTests.java:115]: argh, GH should have live reload for comments ;)

**Review by Wow123419 — APPROVED** [review]

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/BasicFormatter.java (hunk 9 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plugin/BasicFormatter.java:7]: I had to move it out of the `sql-action` project to make it extend `FormatterState`. While this won't be necessary anymore, I think it still makes sense to keep it out of `sql-action`. I guess at some point there was another project using it but that doesn't seem to be the case anymore. The CLI depends directly on `SimpleFormatter` so that also can't be the reason.

File: x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java [hunk 15]
```diff
@@ -1438,6 +1444,126 @@ public void testCompressCursor() throws IOException {
         assertThat(resp.get("cursor").toString().length(), lessThan(5000));
     }
 
+    public void testFetchAllPagesSearchHitCursorTxt() throws IOException {
```
Comment (Luegg) [inline x-pack/plugin/sql/qa/server/src/main/java/org/elasticsearch/xpack/sql/qa/rest/RestSqlTestCase.java:1447]: @astefan I've extended the IT a bit to ensure that we cover all combinations of (cursorType, format) together with random sizes and page sizes. Altogether it should cover all scenarios including "all records in first page", "full last page", "empty last page" etc.

**Comment by costin** [comment]
The PR tries to address multiple items which are minor, however it makes it difficult for reviewers to follow since the code is spread across multiple methods/packages.
+1 on rolling the changes on async, extending testing and minimizing the overall size (and potentially following up with other PRs).

**Review by astefan — APPROVED** [review]
LGTM

**Review by costin — APPROVED** [review]
LGTM

**Comment by Luegg** [comment]
Backport to 8.1 turns out to be trickier than expected because changeset heavily overlaps with #83381
