### PR TITLE
Fixing bug with bedrock client caching

### LINKED ISSUE #117916: Inference API returning Unable to execute HTTP request: event executor terminated
### Elasticsearch Version

serverless

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

serverless

### Problem Description

Getting error

```
{
  "error": {
    "root_cause": [
      {
        "type": "exception",
        "reason": "Amazon Bedrock converse call failed"
      }
    ],
    "type": "exception",
    "reason": "Failed to send request from inference entity id [bedrock_cohere-cmd-r-plus_completion]",
    "caused_by": {
      "type": "exception",
      "reason": "org.elasticsearch.ElasticsearchException: Amazon Bedrock converse call failed",
      "caused_by": {
        "type": "exception",
        "reason": "Amazon Bedrock converse call failed",
        "caused_by": {
          "type": "sdk_client_exception",
          "reason": "Unable to execute HTTP request: event executor terminated",
          "caused_by": {
            "type": "rejected_execution_exception",
            "reason": "event executor terminated"
          }
        }
      }
    }
  },
  "status": 500
}
```

### Steps to Reproduce

```
## Using Bedrock Service - Cohere Command R+ model
PUT _inference/completion/bedrock_cohere-cmd-r-plus_completion
{
    "service": "amazonbedrock",
    "service_settings": {
        "access_key": "${bedrock_access_key}",
        "secret_key": "${bedrock_secret_key}",
        "region": "us-east-1",
        "provider": "cohere",
        "model": "cohere.command-r-plus-v1:0"
    }
}

## Test inference api - streaming
POST _inference/completion/bedrock_cohere-cmd-r-plus_completion/
{
  "input": "How many male malard ducks fit in an american football field?"
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ymao1**
Resolves https://github.com/elastic/elasticsearch/issues/117916

## Summary

1. Fixes an order of operations bug with flushing the client cache and retrieving the client. Previously, we look in the cache for a client and return it, regardless of whether it is expired or not, and then we flush the cache of expired clients. This was causing the `event executor terminated` error. This PR changes the order so that we flush the cache of expired clients first and then we try to retrieve the client (creating a new one if the expired one was flushed).

2. Updates the expiration date of the client if the client is used. This allows an actively used client to continue being cached. Previously, the client would be flushed every 5 minutes regardless of whether it's in use or not. If this is not the desired behavior, I can revert this change.

### CODE REVIEW

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/amazonbedrock/AmazonBedrockInferenceClientCache.java [hunk 1]
```diff
@@ -35,20 +35,26 @@ public AmazonBedrockInferenceClientCache(BiFunction<AmazonBedrockModel, TimeValu
...
         final Integer modelHash = AmazonBedrockInferenceClient.getModelKeysAndRegionHashcode(model, timeout);
         cacheLock.readLock().lock();
         try {
-            return clientsCache.computeIfAbsent(modelHash, hashKey -> {
-                final AmazonBedrockBaseClient builtClient = creator.apply(model, timeout);
-                builtClient.setClock(clock);
-                builtClient.resetExpiration();
-                return builtClient;
+            return clientsCache.compute(modelHash, (hashKey, client) -> {
+                if (client == null) {
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/amazonbedrock/AmazonBedrockInferenceClientCache.java:47]: nit: I think we could collapse this to something like:

```
AmazonBedrockBaseClient clientToUse = client;
if (clientToUse == null) {
  clientToUse = creator.apply(model, timeout);
}

clientToUse.setClock(clock);
clientToUse.resetExpiration();
return clientToUse;
```

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/amazonbedrock/AmazonBedrockInferenceClientCache.java [hunk 2]
```diff
@@ -35,20 +35,26 @@ public AmazonBedrockInferenceClientCache(BiFunction<AmazonBedrockModel, TimeValu
...
+                    final AmazonBedrockBaseClient builtClient = creator.apply(model, timeout);
+                    builtClient.setClock(clock);
+                    builtClient.resetExpiration();
+                    return builtClient;
+                } else {
+                    // for testing
+                    client.setClock(clock);
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/amazonbedrock/AmazonBedrockInferenceClientCache.java:54]: nit: This is completely unrelated to your PR but I wonder if we could refactor the client class' creator function to take the clock as a parameter so we can avoid the `setClock()` class here 🤔

**Review by jonathan-buttner — APPROVED** [review]

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/amazonbedrock/AmazonBedrockInferenceClientCache.java (hunk 2 above)
Comment (ymao1) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/amazonbedrock/AmazonBedrockInferenceClientCache.java]: I did not tackle this comment in this PR but I left a code comment. Would you like me to open an issue?
