### PR TITLE
SQL: Fix rearranging columns in PIVOT queries

### LINKED ISSUE #80952: SQL: Cannot reorder columns in PIVOT query
Given a query like `SELECT a, b, birth_date FROM (SELECT * FROM test_emp PIVOT (SUM(salary) FOR languages IN (1 as a, 2 as b)) LIMIT 10)` the response is 

```
           a            |       b       |  birth_date   
------------------------+---------------+---------------
null                    |56415          |null           
null                    |34341          |null           
null                    |39728          |null           
1952-04-19T00:00:00.000Z|66174          |null           
1953-01-07T00:00:00.000Z|null           |52044          
1953-01-23T00:00:00.000Z|73717          |null           
1953-09-02T00:00:00.000Z|null           |57305          
1953-09-19T00:00:00.000Z|null           |44307          
1954-06-19T00:00:00.000Z|null           |56760          
```

Expected response would be to have the first column with the dates last.

Note, the bug also applies if you don't select any of the pivoted columns as in `SELECT emp_no, birth_date FROM (SELECT * FROM test_emp PIVOT (SUM(salary) FOR languages IN (1 as a, 2 as b)) LIMIT 10)` and also when not using a subquery as in `SELECT a, birth_date, emp_no FROM test_emp PIVOT (SUM(salary) FOR languages IN (1 as a, 2 as b)) LIMIT 10`.

### PR DESCRIPTION
**Pull request by Luegg**
Resolves #80952 and also fixes arbitrary rearrangements of pivoted columns (dropping, duplicating and reordering).

The bug was caused because fields reordering in `ProjectExec` wrapping `PivotExec` have been ignored. As a result the field mask (from `QueryContainer.columnMask()`) is created wrongly because the attributes in `EsQueryExec.output()` have a different order in `EsQueryExec.output()` as in `QueryContainer.fields()`.

### CODE REVIEW

**Comment by Luegg** [comment]
@elasticmachine run elasticsearch-ci/eql-correctness

**Comment by Luegg** [comment]
@elasticmachine run elasticsearch-ci/eql-correctness

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java [hunk 1]
```diff
@@ -143,9 +143,17 @@ protected PhysicalPlan rule(ProjectExec project) {
                 AttributeMap.Builder<Expression> aliases = AttributeMap.<Expression>builder().putAll(queryC.aliases());
                 AttributeMap.Builder<Pipe> processors = AttributeMap.<Pipe>builder().putAll(queryC.scalarFunctions());
 
+                // recreate the query container's fields such that they appear in order of the projection and with non-projected fields
+                // last. This is mostly needed for PIVOT queries where we have to fold projections on aggregations because they cannot be
+                // optimized away. Most (all) other queries usually prune nested projections in earlier steps.
+                List<QueryContainer.FieldInfo> fields = new ArrayList<>(queryC.fields().size());
+                List<QueryContainer.FieldInfo> nonProjectedFields = new ArrayList<>(queryC.fields());
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java:150]: I find `nonProjected` confusing as it might imply a field that was not specified in the projection (maybe because of an implicit declaration) - it's better to describe what it does as oppose to what it does NOT do.
How about `extraFields`,  `hiddenFields`  or `infraFields` and update the comment re: non-projected fields.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java [hunk 2]
```diff
@@ -155,13 +163,27 @@ protected PhysicalPlan rule(ProjectExec project) {
...
+                            attributeId = ((NamedExpression) e).toAttribute().id();
+                        }
                     }
+
+                    final NameId finalAttributeId = attributeId;
+
+                    queryC.fields().stream().filter(f -> f.attribute().id().equals(finalAttributeId)).findFirst().ifPresent(f -> {
+                        fields.add(f);
+                        nonProjectedFields.remove(f);
+                    });
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java:177]: This looks better though a regular for/loop without the stream boilerplate code:

```java
for (field : queryC.fields()) {
  if (f.attribute().id.equals(attributeId)) {
       fields.add(f);
       nonProjectedFields.remove(f);
  }
}
```

This can be improved by moving the equality check in `FieldInfo`, say : `FieldInfo.match(Attribute)`

**Review by costin — COMMENTED** [review]
Thanks for the quick turnaround.
Why is the order in `EsQueryExec.output()` different than that of the `QueryContainer`.
Since lists are used everywhere the order of the PIVOT should be preserved - what ends up affecting it?

As far as I can tell, the field order is still being carried over however it's the extra fields that are affecting the mask - how come they end up in front of the other fields and are not being ignored?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java (hunk 2 above)
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryFolder.java]: Yeah, the boilerplate around streams is pretty ugly indeed. Converting it to a loop...

**Comment by Luegg** [comment]
> Thanks for the quick turnaround. Why is the order in `EsQueryExec.output()` different than that of the `QueryContainer`. Since lists are used everywhere the order of the PIVOT should be preserved - what ends up affecting it?
> 
> As far as I can tell, the field order is still being carried over however it's the extra fields that are affecting the mask - how come they end up in front of the other fields and are not being ignored?

The problem unfolds in FoldProject when creating the new `EsQueryExec`. In https://github.com/elastic/elasticsearch/pull/81032/files#diff-86d40bd19662dc9b28da1d6a85443b36386ad920924edefe9c6e8637b19e75e8L164 you see that the fields of the old query container are passed into the newly created one. But in https://github.com/elastic/elasticsearch/pull/81032/files#diff-86d40bd19662dc9b28da1d6a85443b36386ad920924edefe9c6e8637b19e75e8L174 the output for the new query exec is taken from the `ProjectExec`. Now if the project swaps the output, it's no longer aligned with fields.

**Review by astefan — APPROVED** [review]
LGTM. Left one question.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/GlobalCountRef.java [hunk 3]
```diff
@@ -15,6 +15,8 @@
 public final class GlobalCountRef extends AggRef {
     public static final GlobalCountRef INSTANCE = new GlobalCountRef();
 
+    private GlobalCountRef() {}
```
[the remark this answers is not in the document]
Comment (Luegg) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/GlobalCountRef.java:18]: Just to make the class adhere to the general singleton pattern. This way it's obvious that there is only this one instance of the class and you only have to trace the usage of `INSTANCE` when looking for all instances of the class. See for example `EmptyCursor`.

**Review by bpintea — APPROVED** [review]
LGTM

**Review by costin — APPROVED** [review]
Thanks for the explanation. LGTM
