### PR TITLE
Fix IndexSortUpgradeIT test

### LINKED ISSUE #128861: [CI] IndexSortUpgradeIT testIndexSortForNumericTypes {upgradedNodes=3} failing
**Build Scans:**
- [elasticsearch-intake #23590 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/2qgz2g2dyndnc)
- [elasticsearch-pull-request #73758 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/w72x3aw2oygaq)
- [elasticsearch-pull-request #73751 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/4omwefrw6gtkc)
- [elasticsearch-pull-request #73749 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/oajzunnycskme)
- [elasticsearch-intake #23587 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/al53msp3kuhyg)
- [elasticsearch-pull-request #73748 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ickaj3g6e276y)
- [elasticsearch-pull-request #73747 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/n2l6dbljkfhre)
- [elasticsearch-pull-request #73746 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/cuaodzrrplsyg)
- [elasticsearch-intake #23585 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ykusvoezoqnxo)
- [elasticsearch-pull-request #73745 / 8.19.0_bwc-snapshots](https://gradle-enterprise.elastic.co/s/ky75iawfd7yru)

**Reproduction Line:**
```
./gradlew ":qa:rolling-upgrade:v8.19.0#bwcTest" -Dtests.class="org.elasticsearch.upgrades.IndexSortUpgradeIT" -Dtests.method="testIndexSortForNumericTypes {upgradedNodes=2}" -Dtests.seed=A725F62ED38F8BC8 -Dtests.bwc=true -Dtests.locale=kab-Latn-DZ -Dtests.timezone=America/Manaus -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.upgrades.IndexSortUpgradeIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testIndexSortForNumericTypes%20%7BupgradedNodes%3D3%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.RuntimeException: An error occurred while checking cluster 'test-cluster' status.
```

**Issue Reasons:**
- [main] 14 consecutive failures in step 8.19.0_bwc-snapshots
- [main] 14 failures in test testIndexSortForNumericTypes {upgradedNodes=3} (3.5% fail rate in 403 executions)
- [main] 14 failures in step 8.19.0_bwc-snapshots (11.0% fail rate in 127 executions)
- [main] 4 failures in pipeline elasticsearch-intake (12.1% fail rate in 33 executions)
- [main] 10 failures in pipeline elasticsearch-pull-request (10.3% fail rate in 97 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Relates to PR #127968

Closes #128861, #128862, #128863

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java [hunk 1]
```diff
@@ -144,12 +146,18 @@ public SortField sortField(
         boolean reverse
     ) {
         SortField sortField = sortField(missingValue, sortMode, nested, reverse);
-        if (indexCreatedVersion.onOrAfter(IndexVersions.INDEX_INT_SORT_INT_TYPE) || getNumericType().sortFieldType != SortField.Type.INT) {
+        // we introduced INT sort type in 8.19 and from 9.1
+        if (getNumericType().sortFieldType != SortField.Type.INT
+            || indexCreatedVersion.onOrAfter(IndexVersions.INDEX_INT_SORT_INT_TYPE)
+            || indexCreatedVersion.between(IndexVersions.INDEX_INT_SORT_INT_TYPE_8_19, UPGRADE_TO_LUCENE_10_0_0)) {
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java:152]: ❤️ yes! OK, I understand why this was failing on 8.19 now. Excellent.

File: server/src/main/java/org/elasticsearch/index/IndexVersions.java [hunk 2]
```diff
@@ -141,6 +141,7 @@ private static Version parseUnchecked(String version) {
     public static final IndexVersion RESCORE_PARAMS_ALLOW_ZERO_TO_QUANTIZED_VECTORS_BACKPORT_8_X = def(8_529_0_00, Version.LUCENE_9_12_1);
     public static final IndexVersion DEFAULT_OVERSAMPLE_VALUE_FOR_BBQ_BACKPORT_8_X = def(8_530_0_00, Version.LUCENE_9_12_1);
     public static final IndexVersion SEMANTIC_TEXT_DEFAULTS_TO_BBQ_BACKPORT_8_X = def(8_531_0_00, Version.LUCENE_9_12_1);
+    public static final IndexVersion INDEX_INT_SORT_INT_TYPE_8_19 = def(8_532_0_00, Version.LUCENE_9_12_1);
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/index/IndexVersions.java:144]: Verified that the 8.19 branch is using:
```
    public static final IndexVersion INDEX_INT_SORT_INT_TYPE_8_19 = def(8_532_0_00, Version.LUCENE_9_12_1);
```
So, the versions all line up. 👍

**Review by benwtrent — APPROVED** [review]
