### PR TITLE
Expose underlying processor to blame for thrown exception within CompoundProcessor

### LINKED ISSUE #17823: Ingest failure metadata fields refer to compound processor
The compound processor is used internally in ingest when handling failures. As I understand though it should be an internal concept that users don't know about. If you define a processor that fails, which has an `on_failure` block defined, which fails again, and the pipeline has its own `on_failure`, the metadata about the failure itself will be referring to the compound processor rather than the one that really failed.

```
GET _ingest/pipeline/_simulate
{
  "pipeline" : {
    "processors" : [
      {
        "convert" : {
          "field": "doesnotexist",
          "type" : "integer",
          "on_failure" : [
            {
              "fail" : {
                "message" : "custom error message"
              }    
            }
          ]
        }
      }
    ],
    "on_failure" : [
      {
        "set" : {
          "field" : "failure",
          "value" : {
            "message" : "{{_ingest.on_failure_message}}",
            "processor" : "{{_ingest.on_failure_processor_type}}",
            "tag" : "{{_ingest.on_failure_processor_tag}}"
          }
        }
      }
    ]
  },
  "docs" : [
    {
      "_source" : {
        "message" : "test"
      }
    }
  ]
}
```

```
{
  "docs": [
    {
      "doc": {
        "_type": "_type",
        "_index": "_index",
        "_id": "_id",
        "_source": {
          "message": "test",
          "failure": {
            "tag": "CompoundProcessor-null-null",
            "message": "custom error message",
            "processor": "compound"
          }
        },
        "_ingest": {
          "timestamp": "2016-04-18T13:20:28.981+0000"
        }
      }
    }
  ]
}
```

The `tag` and the `processor` that goes in the document as part of the failure object are a bit off, they should be coming from the fail processor, which caused the failure. That information gets lost with the double wrapping.

Here is also a failing unit test to add to `CompoundProcessorTests` that reproduces the problem:

```
public void testFail() throws Exception {
        TestProcessor firstProcessor = new TestProcessor("id1", "first", ingestDocument -> {throw new RuntimeException("error");});
        FailProcessor failProcessor = new FailProcessor("tag_fail", new TestTemplateService.MockTemplate("custom error message"));
        TestProcessor secondProcessor = new TestProcessor("id2", "second", ingestDocument -> {
            Map<String, String> ingestMetadata = ingestDocument.getIngestMetadata();
            assertThat(ingestMetadata.size(), equalTo(3));
            assertThat(ingestMetadata.get(CompoundProcessor.ON_FAILURE_MESSAGE_FIELD), equalTo("custom error message"));
            assertThat(ingestMetadata.get(CompoundProcessor.ON_FAILURE_PROCESSOR_TYPE_FIELD), equalTo("fail"));
            assertThat(ingestMetadata.get(CompoundProcessor.ON_FAILURE_PROCESSOR_TAG_FIELD), equalTo("tag_fail"));
        });

        CompoundProcessor failCompoundProcessor = new CompoundProcessor(Collections.singletonList(firstProcessor),
                Collections.singletonList(failProcessor));

        CompoundProcessor compoundProcessor = new CompoundProcessor(Collections.singletonList(failCompoundProcessor),
                Collections.singletonList(secondProcessor));
        compoundProcessor.execute(ingestDocument);

        assertThat(firstProcessor.getInvokedCounter(), equalTo(1));
        assertThat(secondProcessor.getInvokedCounter(), equalTo(1));
}
```

### PR DESCRIPTION
**Pull request by talevy**
Fixes #17823

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/ingest/processor/TrackingResultProcessorTests.java [hunk 1]
```diff
@@ -121,8 +121,8 @@ public void testActualCompoundProcessorWithOnFailure() throws Exception {
 
         metadata = resultList.get(3).getIngestDocument().getIngestMetadata();
         assertThat(metadata.get(ON_FAILURE_MESSAGE_FIELD), equalTo("fail"));
-        assertThat(metadata.get(ON_FAILURE_PROCESSOR_TYPE_FIELD), equalTo("compound"));
-        assertThat(metadata.get(ON_FAILURE_PROCESSOR_TAG_FIELD), equalTo("CompoundProcessor-fail-success-success-fail"));
```
Comment (talevy) [inline core/src/test/java/org/elasticsearch/ingest/processor/TrackingResultProcessorTests.java]: This test originally exposed the bug, and let it pass. no more!

File: core/src/main/java/org/elasticsearch/ingest/core/CompoundProcessor.java [hunk 2]
```diff
@@ -93,29 +93,40 @@ public void execute(IngestDocument ingestDocument) throws Exception {
...
-    void executeOnFailure(IngestDocument ingestDocument, Exception cause, String failedProcessorType, String failedProcessorTag) throws Exception {
+    void executeOnFailure(IngestDocument ingestDocument, Throwable cause, Processor failedProcessor) throws Exception {
         try {
-            putFailureMetadata(ingestDocument, cause, failedProcessorType, failedProcessorTag);
+            putFailureMetadata(ingestDocument, cause, failedProcessor.getType(), failedProcessor.getTag());
             for (Processor processor : onFailureProcessors) {
-                processor.execute(ingestDocument);
+                try {
+                    processor.execute(ingestDocument);
+                } catch (Exception e) {
```
Comment (talevy) [inline core/src/main/java/org/elasticsearch/ingest/core/CompoundProcessor.java]: actually, this needs to handle `CompoundProcessorException` separately as well

File: core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java [hunk 3]
```diff
@@ -117,4 +111,68 @@ public void testSingleProcessorWithNestedFailures() throws Exception {
         assertThat(processorToFail.getInvokedCounter(), equalTo(1));
         assertThat(lastProcessor.getInvokedCounter(), equalTo(1));
     }
+
+    public void testCompoundProcessorExceptionFailWithoutOnFailure() throws Exception {
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java]: I'm not sure this method name is right. Maybe I just don't know this code that well though.

Comment (nik9000) [inline core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java]: Yup. I just don't know it well enough. Disregard.

File: core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java [hunk 4]
```diff
@@ -117,4 +111,68 @@ public void testSingleProcessorWithNestedFailures() throws Exception {
...
+        assertThat(firstProcessor.getInvokedCounter(), equalTo(1));
+        assertThat(secondProcessor.getInvokedCounter(), equalTo(1));
+    }
+
+    public void testCompoundProcessorExceptionFail() throws Exception {
+        TestProcessor firstProcessor = new TestProcessor("id1", "first", ingestDocument -> {throw new RuntimeException("error");});
+        TestProcessor failProcessor = new TestProcessor("tag_fail", "fail", ingestDocument -> {throw new RuntimeException("custom error message");});
+        TestProcessor secondProcessor = new TestProcessor("id3", "second", ingestDocument -> {
+            Map<String, String> ingestMetadata = ingestDocument.getIngestMetadata();
+            assertThat(ingestMetadata.size(), equalTo(3));
```
Comment (nik9000) [inline core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java]: I like `hasSize` better for this because it gives a nicer error message on failure.

**Comment by nik9000** [comment]
LGTM though maybe @javanna should have a look?

File: core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java (hunk 3 above)
Comment (talevy) [inline core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java]: haha, I don't blame you. I had a really awkward time trying to name all of these subtly different scenarios

File: core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java (hunk 4 above)
Comment (talevy) [inline core/src/test/java/org/elasticsearch/ingest/core/CompoundProcessorTests.java]: noted. will update

**Comment by talevy** [comment]
thanks for the review @nik9000, I'll give @javanna or @martijnvg a little bit of time to check this out as well.

It was one of these problems that arose from refactoring, and this solution was kind of lost in the changes (seemed more difficult at the time).

**Comment by martijnvg** [comment]
LGTM

File: core/src/main/java/org/elasticsearch/ingest/core/Pipeline.java [hunk 5]
```diff
@@ -51,7 +51,11 @@ public Pipeline(String id, String description, CompoundProcessor compoundProcess
      * Modifies the data of a document to be indexed based on the processor this pipeline holds
      */
     public void execute(IngestDocument ingestDocument) throws Exception {
-        compoundProcessor.execute(ingestDocument);
+        try {
+            compoundProcessor.execute(ingestDocument);
+        } catch (CompoundProcessorException e) {
+            throw new IllegalArgumentException(e.getMessage());
```
Comment (talevy) [inline core/src/main/java/org/elasticsearch/ingest/core/Pipeline.java]: This was updated so that we do not expose `CompoundProcessorException` outside of the Ingest Pipeline.

**Comment by talevy** [comment]
@nik9000 @martijnvg thank you for the reviews. Originally, I was missing an integration test that actually caught a big flaw in my original `CompoundProcessorException` design.

In the latest push, I wrap all CompoundProcessor related exceptions in an ElasticsearchException which relays the processor information in its headers.

let me know what you think!

**Comment by martijnvg** [comment]
LGTM 👍
