### PR TITLE
[ML] Add .ml-anomalies and .ml-annotations to the DotPrefixValidator exceptions

### LINKED ISSUE #133138: [CI] TextEmbeddingQueryIT testModelWithPrefixStrings failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #10123 / ubuntu-2404-aarch64_checkpart4_platform-support-arm](https://gradle-enterprise.elastic.co/s/glq37ffhvo2ie)
- [elasticsearch-pull-request #86229 / part-4](https://gradle-enterprise.elastic.co/s/l4gyjf6dlxkl6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.TextEmbeddingQueryIT.testModelWithPrefixStrings" -Dtests.seed=284E28E858E61E7E -Dtests.locale=twq -Dtests.timezone=America/Ensenada -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ml.integration.TextEmbeddingQueryIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testModelWithPrefixStrings'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:35171], URI [_cluster/settings], status line [HTTP/1.1 200 OK]
Warnings: [Index [.ml-annotations-000001] name begins with a dot (.), which is deprecated, and will not be allowed in a future Elasticsearch version.]
{"acknowledged":true,"persistent":{"logger":{"org":{"elasticsearch":{"xpack":{"ml":{"inference":{"pytorch":"DEBUG","assignment":"DEBUG","deployment":"DEBUG"},"action":"DEBUG","process":{"logging":"DEBUG"}}}}}}},"transient":{}}
```

**Issue Reasons:**
- [main] 2 failures in test testModelWithPrefixStrings (0.4% fail rate in 522 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by davidkyle**
Several REST tests have failed due to this warning heading in the response to `PUT _cluster/settings` 

```
Warnings: [Index [.ml-annotations-000001] name begins with a dot (.), which is deprecated, and will not be allowed in a future Elasticsearch version.]
```

The fix here is to add the internal `.ml` indices to the list of exceptions. As to why `PUT _cluster/settings` could return a warning about a deprecated index name? Cluster state updates are batched, the update settings request has been batched with a create index request and the warning has leaked out into this response. 

Closes #133138, #129035, #132703, #128417 https://github.com/elastic/elasticsearch/issues/135162, https://github.com/elastic/elasticsearch/issues/135159, https://github.com/elastic/elasticsearch/issues/135135

### CODE REVIEW

File: modules/dot-prefix-validation/src/test/java/org/elasticsearch/validation/DotPrefixValidatorTests.java [hunk 1]
```diff
@@ -124,13 +133,24 @@ public String actionName() {
             return "";
         }
 
+        void validateIndices(@Nullable Set<String> indices) {
+            super.validateIndices(indices);
+            if (assertNoWarnings) {
+                assertWarnings();
```
Comment (davidkyle) [inline modules/dot-prefix-validation/src/test/java/org/elasticsearch/validation/DotPrefixValidatorTests.java:141]: Asserts that no warnings were created in the thread context

**Review by prwhelan — APPROVED** [review]

**Review by DonalEvans — APPROVED** [review]

File: server/src/main/resources/transport/upper_bounds/9.2.csv [hunk 2]
```diff
@@ -1 +1 @@
-inference_api_openai_embeddings_headers,9169000
+inference_api_openai_embeddings_headers,9169000
```
Comment (davidkyle) [inline server/src/main/resources/transport/upper_bounds/9.2.csv]:
```suggestion
inference_api_openai_embeddings_headers,9169000

```

**Comment by davidkyle** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/135677)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/135678)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
