### PR TITLE
Core: Pick inner most parse exception as root cause

### LINKED ISSUE #30261: Causes of XContentParseException should be included in search for root_cause
Following #29373 parse exceptions are now `XContentParseException` rather than `ParsingException`.  This has a major effect on the determination of the `root_cause` of an exception that is found during parsing due to the definition of `root_cause`.

The `root_cause` is determined by starting at the outermost exception and recursing through the causes until an exception is found that is _not_ an `ElasticsearchException`.  Then:

* If the outermost exception was not an `ElasticsearchException` then it is the `root_cause`
* Otherwise the most deeply nested `ElasticsearchException` is the `root_cause`

`ParsingException` extends `ElasticsearchException` whereas `XContentParseException` does not.

This means that if a validation error occurs during parsing then following #29373 the most general parsing exception is reported as the root cause.  Prior to #29373 the most specific parsing exception, i.e. most likely the one detailing the validation error, was considered the `root_cause`.

As a concrete example, this is a validation error after #29373:

```
{
    "error": {
        "root_cause": [{
            "type": "x_content_parse_exception",
            "reason": "[1:144] [job_details] failed to parse field [analysis_limits]"
        }],
        "type": "x_content_parse_exception",
        "reason": "[1:144] [job_details] failed to parse field [analysis_limits]",
        "caused_by": {
            "type": "x_content_parse_exception",
            "reason": "Failed to build [analysis_limits] after last required field arrived",
            "caused_by": {
                "type": "status_exception",
                "reason": "categorization_examples_limit cannot be less than 0. Value = -1"
            }
        }
    },
    "status": 400
}
```

And this is the equivalent error before #29373:

```
{
  "error": {
    "root_cause": [
      {
        "type": "status_exception",
        "reason": "categorization_examples_limit cannot be less than 0. Value = -1"
      }
    ],
    "type": "parsing_exception",
    "reason": "[job_details] failed to parse field [analysis_limits]",
    "line": 11,
    "col": 3,
    "caused_by": {
      "type": "parsing_exception",
      "reason": "Failed to build [analysis_limits] after last required field arrived",
      "caused_by": {
        "type": "status_exception",
        "reason": "categorization_examples_limit cannot be less than 0. Value = -1"
      }
    }
  },
  "status": 400
}
```

If all you have to go on is the `root_cause` then `[1:144] [job_details] failed to parse field [analysis_limits]` is nowhere near as useful as `categorization_examples_limit cannot be less than 0. Value = -1`.  The red error bars that Kibana shows when an error occurs only show the `root_cause`, so Kibana users suffer from this.

I think the solution that will keep the `root_cause` functionality as it was previously would be to consider both `ElasticsearchException` and `XContentParseException` when recursing through causes.

### PR DESCRIPTION
**Pull request by nik9000**
Just like `ElasticsearchException`, the inner most
`XContentParseException` tends to contain the root cause of the
exception and show be show to the user in the `root_cause` field.

The effectively undoes most of the changes that #29373 made to the
`root_cause` for parsing exceptions. The `type` field still changes from
`parse_exception` to `x_content_parse_exception`, but this seems like a
fairly safe change.

`ElasticsearchWrapperException` *looks* tempting to implement this but
the behavior isn't quite right. `ElasticsearchWrapperExceptions` are
entirely unwrapped until the cause no longer
`implements ElasticsearchWrapperException` but `XContentParseException`
should be unwrapped until its cause is no longer an
`XContentParseException` but no further. In other words,
`ElasticsearchWrapperException` are unwrapped one step too far.

Closes #30261

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/ElasticsearchException.java [hunk 1]
```diff
@@ -635,8 +636,25 @@ public static ElasticsearchException failureFromXContent(XContentParser parser)
     public static ElasticsearchException[] guessRootCauses(Throwable t) {
         Throwable ex = ExceptionsHelper.unwrapCause(t);
         if (ex instanceof ElasticsearchException) {
+            // ElasticsearchException knows how to guess its own root cause
             return ((ElasticsearchException) ex).guessRootCauses();
         }
+        if (ex instanceof XContentParseException) {
+            /*
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/ElasticsearchException.java]: I feel like if we get *another* exception like this one we should try to build something a little more generic and less "heuristics that make the exception look good". But `XContentParseException isn't really the same thing as `ElasticsearchException`. It is similar, but different enough that I don't think I could boil out the generic bits without this getting wonky.

File: server/src/main/java/org/elasticsearch/ElasticsearchWrapperException.java [hunk 2]
```diff
@@ -19,7 +19,11 @@
 
 package org.elasticsearch;
 
+/**
+ * An exception that is meant to be "unwrapped" when sent back to the user
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/ElasticsearchWrapperException.java]: This one turned out not to be useful but I researched it so I figured I'd add the javadocs.

File: server/src/test/java/org/elasticsearch/ElasticsearchExceptionTests.java [hunk 3]
```diff
@@ -124,13 +126,13 @@ public void testGuessRootCause() {
             } else {
                 rootCauses = ElasticsearchException.guessRootCauses(randomBoolean() ? new RemoteTransportException("remoteboom", ex) : ex);
             }
-            assertEquals(ElasticsearchException.getExceptionName(rootCauses[0]), "parsing_exception");
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/ElasticsearchExceptionTests.java]: These were all backwards....

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
Thanks for reviewing @dakrone! I've merged and I'll backport now!
