### PR TITLE
[Tests] Handle escape char correctly in wildcard patterns

### LINKED ISSUE #69837: StringMatcherTests.testUnicodeWildcard test failure
There is a reproducible test failure for the `testUnicodeWildcard` test in security.

Fails on: master/v8.0

reproduce with:

```
./gradlew ':x-pack:plugin:core:test' --tests "org.elasticsearch.xpack.core.security.support.StringMatcherTests.testUnicodeWildcard" -Dtests.seed=CA428535A844FAB5 -Dtests.security.manager=true -Dtests.locale=de-CH -Dtests.timezone=Pacific/Chuuk -Druntime.java=11
```

Exception:

```
org.elasticsearch.xpack.core.security.support.StringMatcherTests > testUnicodeWildcard FAILED
    java.lang.AssertionError: Matcher [o\a*] failed to match [o\a෣එඒ඿෍ඪa] but should
        at __randomizedtesting.SeedInfo.seed([CA428535A844FAB5:4987B18C23E0F50F]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.elasticsearch.xpack.core.security.support.StringMatcherTests.assertMatch(StringMatcherTests.java:141)
        at org.elasticsearch.xpack.core.security.support.StringMatcherTests.testUnicodeWildcard(StringMatcherTests.java:52)
```

### PR DESCRIPTION
**Pull request by ywangd**
Escape char is handled specially while building automaton. It should also be handled when buidling the target text for matching.

Resolves: #69837

### CODE REVIEW

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/support/StringMatcherTests.java [hunk 1]
```diff
@@ -26,10 +26,11 @@ public void testEmptySet() throws Exception {
     public void testSingleWildcard() throws Exception {
         final String prefix = randomAlphaOfLengthBetween(3, 5);
         final StringMatcher matcher = StringMatcher.of(prefix + "*");
+        final String normalisedPrefix = prefix.replace("\\", "");
```
Comment (tvernum) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/support/StringMatcherTests.java:29]: `prefix` cannot contain a `\`, it's alphabetic only.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/support/StringMatcherTests.java [hunk 2]
```diff
@@ -48,10 +49,11 @@ public void testUnicodeWildcard() throws Exception {
         final String prefix = randomValueOtherThanMany(StringMatcherTests::hasHighSurrogate,
             () -> randomRealisticUnicodeOfLengthBetween(3, 5));
         final StringMatcher matcher = StringMatcher.of(prefix + "*");
+        final String normalisedPrefix = prefix.replace("\\", "");
```
Comment (tvernum) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/support/StringMatcherTests.java:52]: I would just push this up into the `otherThanMany` check.
 
```
randomValueOtherThanMany(StringMatcherTests::hasHighSurrogateOrBackslash
```

Comment (ywangd) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/support/StringMatcherTests.java]: Updated as suggested. 
PS: I think we do need some tests for the behaviour of the escape char. This is not the right place for it. Maybe when fixing #69851.

**Review by tvernum — APPROVED** [review]
