### PR TITLE
Remove usages of `DataStream#getDefaultBackingIndexName`

### LINKED ISSUE #123376: Remove test usages of `DataStream#getDefaultBackingIndexName`
We've already seen [several test failures](https://github.com/elastic/elasticsearch/issues?q=sort%3Aupdated-desc+is%3Aissue+state%3Aclosed+getDefaultBackingIndexName) that were caused by (integration) test usages of `DataStream#getDefaultBackingIndexName`. The danger is that when a test runs around midnight, the test cluster might create a data stream backing index using day `X` and the test that calls `getDefaultBackingIndexName` uses day `X + 1` because it executed a few milliseconds later. That causes the test to look for a backing index that will never exist.

The solution is straightforward: retrieve the list of backing indices from the data stream and extract the backing index name from that list.

**Integration tests**
- [x] `elasticsearch.modules.data-streams.internalClusterTest`  (19 usages found) https://github.com/elastic/elasticsearch/pull/127384
- [x] `elasticsearch.x-pack.plugin.ilm.internalClusterTest`  (2 usages found) https://github.com/elastic/elasticsearch/pull/124319
- [x] `elasticsearch.x-pack.plugin.ilm.qa.multi-node.javaRestTest`  (10 usages found) https://github.com/elastic/elasticsearch/pull/124319
- [x] `elasticsearch.x-pack.plugin.logsdb.javaRestTest`  (3 usages found) https://github.com/elastic/elasticsearch/pull/127384
- [x] `elasticsearch.x-pack.plugin.logsdb.qa.with-basic.javaRestTest` https://github.com/elastic/elasticsearch/pull/127384
- [x] `elasticsearch.x-pack.plugin.ccr.javaRestTest` (3 usages found) https://github.com/elastic/elasticsearch/pull/127693

**Unit tests**
Unit tests do not fail that often because they are much faster, but it would be good to check that this method is not used multiple times in a unit test or it is replaced by [the `getDefaultBackingIndexName` that uses the provided timestamp](https://github.com/elastic/elasticsearch/blob/737ab623937376a1e038290dd4497909af49cb94/server/src/main/java/org/elasticsearch/cluster/metadata/DataStream.java#L1131) 

- [ ] `elasticsearch.modules.data-streams.test`  (50 usages found)
- [ ] `elasticsearch.server.test`  (106 usages found)
- [ ] `elasticsearch.x-pack.plugin.ccr.qa.multi-cluster.test`  (3 usages found)
- [ ] `elasticsearch.x-pack.plugin.ccr.test`  (19 usages found)
- [ ] ` elasticsearch.x-pack.plugin.core.test`  (3 usages found)
- [ ] `elasticsearch.x-pack.plugin.logsdb.test`  (18 usages found)
- [ ] `elasticsearch.x-pack.plugin.ml.test`  (1 usage found)
- [ ] `elasticsearch.x-pack.plugin.security.test`  (8 usages found)

Not all the usages above are incorrect. But this can be used to track the progress.

### PR DESCRIPTION
**Pull request by nielsbauman**
These usages had the potential of causing test failures when a data stream was created before midnight and the backing index name generation ran the next day - which would be millisecconds apart. To avoid these failures, we update the tests to be robust to these time differences.

Resolves #123376

### CODE REVIEW

File: modules/data-streams/src/test/java/org/elasticsearch/datastreams/MetadataDataStreamRolloverServiceTests.java [hunk 1]
```diff
@@ -65,7 +65,7 @@ public void testRolloverClusterStateForDataStream() throws Exception {
         final DataStream dataStream = DataStream.builder(
             dataStreamName,
             List.of(new Index(DataStream.getDefaultBackingIndexName(dataStreamName, 1, now.toEpochMilli()), "uuid"))
-        ).setIndexMode(IndexMode.TIME_SERIES).build();
+        ).setIndexMode(IndexMode.TIME_SERIES).setTimeProvider(now::toEpochMilli).build();
```
Comment (lukewhiting) [inline modules/data-streams/src/test/java/org/elasticsearch/datastreams/MetadataDataStreamRolloverServiceTests.java:68]: Bit of a nitpick not specifically about this PR but I'm interested in why we went for this TimeProvider pattern Vs using the [Clock](https://docs.oracle.com/javase/8/docs/api/java/time/Clock.html) interface?

**Review by lukewhiting — APPROVED** [review]
One question more than comment but otherwise looks good 👍🏻

File: modules/data-streams/src/test/java/org/elasticsearch/datastreams/MetadataDataStreamRolloverServiceTests.java (hunk 1 above)
Comment (nielsbauman) [reply modules/data-streams/src/test/java/org/elasticsearch/datastreams/MetadataDataStreamRolloverServiceTests.java:68]: I'm afraid I have no idea... This time provider predates my time at Elastic
