### PR TITLE
ESQL: Don't duplicate Limit on left InlineJoin

### LINKED ISSUE #133235: ESQL: INLINESTATS wrongly applies the after-LIMIT command to the right hand side agg
### Description

`FROM employees | INLINESTATS a = avg(salary) | LIMIT 1 | KEEP a`

results in:

```
       a       
---------------
57305.0        
```

while

`FROM employees | STATS a = avg(salary) | LIMIT 1 | KEEP a`

results in:

```
       a       
---------------
48248.55       
```

This is likely because the `limit` is wrongly pushed down:

`FROM employees | INLINESTATS a = avg(salary) | LIMIT 1 | KEEP a, emp_no, salary`
results in 
```
       a       |    emp_no     |    salary     
---------------+---------------+---------------
57305.0        |10001          |57305          
```

### PR DESCRIPTION
**Pull request by bpintea**
...as this reduces the data the (inline) aggs run on, which is wrong.

Closes #133235

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java [hunk 1]
```diff
@@ -64,7 +65,7 @@ public LogicalPlan rule(Limit limit, LogicalOptimizerContext ctx) {
                     }
                 }
             }
-        } else if (limit.child() instanceof Join join && join.config().type() == JoinTypes.LEFT) {
+        } else if (limit.child() instanceof Join join && join.config().type() == JoinTypes.LEFT && join instanceof InlineJoin == false) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java:68]: ++.

Maybe let's add a comment that we _want_ to also apply this to InlineJoin, but that requires that the stub relation corresponds to a node somewhere _inside_ the left branch, rather than the whole left branch. Or we need to get rid of the stub relation then and replace it by a copy of the left branch (with updated name ids, most likely, but that's a detail).

Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PushDownAndCombineLimits.java:68]: A one line comment here would help, imho.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec [hunk 2]
```diff
@@ -51,8 +51,35 @@ emp_no:integer | languages:integer | max_lang:integer | gender:keyword
          10014 |                 5 | 5                | null
 ;
 
+maxOfIntByKeywordLimit1Aggd
+required_capability: inlinestats_v11
+
+FROM employees
+| KEEP emp_no, languages, gender
+| INLINESTATS max_lang = MAX(languages) BY gender
+| LIMIT 1
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec:62]: Limit 1 is non-deterministic and this might fail on multi-node tests like for serverless, no?

Maybe `LIMIT 3 | SORT gender` (-> F, M, null) as this would still surface the bug?

**Review by alex-spies — APPROVED** [review]
LGTM, thanks @bpintea !

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec (hunk 2 above)
Comment (bpintea) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/inlinestats.csv-spec:62]: The first (`emp_no`-sorted) value has a `language` value of `2`. If the LIMIT (of `1`) is pushed down, that would yield a `max_lang` of `2`. Ideally we'd have a `| SORT emp_no` before INLINESTATS, but that doesn't current work.
In any case, even if the data is shuffled, all records should have the same `max_lang` (`5`).
I've left a comment on the test.

**Comment by bpintea** [comment]
Thanks Alex, Andrei.
