### PR TITLE
Fix get-license test failure by ensure cluster is ready

### LINKED ISSUE #59157: [CI] yaml=reference/licensing/get-license/line_47 failure
**Build scan**:

https://gradle-enterprise.elastic.co/s/iqhh2uk2ya54o

**Repro line**:

```
./gradlew ':docs:integTestRunner' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/licensing/get-license/line_47}" \
  -Dtests.seed=26E92C07695BE133 \
  -Dtests.security.manager=true \
  -Dtests.locale=es-HN \
  -Dtests.timezone=Australia/Broken_Hill \
  -Druntime.java=8

```

**Reproduces locally?**:

No

**Failure history**:

Seems to happen irregularly over the last 60 days, haven't checked earlier.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:%22licensing%2Fget-license%22),sort:!(process.time-start,desc))

**Failure excerpt**:

```
org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT > test {yaml=reference/licensing/get-license/line_47} FAILED
    java.lang.AssertionError: Failure at [reference/licensing/get-license:11]: expected [2xx] status code but api [raw[method=GET path=_license]] returned [404 Not Found] [{ }
    ]
        at __randomizedtesting.SeedInfo.seed([26E92C07695BE133:AEBD13DDC7A78CCB]:0)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
        at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
        at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
        at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
        at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        java.lang.AssertionError: expected [2xx] status code but api [raw[method=GET path=_license]] returned [404 Not Found] [{ }
        ]
            at org.junit.Assert.fail(Assert.java:88)
            at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:297)
            at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:398)
```

### LINKED ISSUE #60468: [CI] EnableSecurityOnBasicLicenseIT.testSecuritySetup failure
**Build scan**: https://gradle-enterprise.elastic.co/s/ususuu432yrsu

**Repro line**:

```
./gradlew ':x-pack:plugin:security:qa:basic-enable-security:integTestRunner' --tests "org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT.testSecuritySetup" -Dtests.seed=EB6BC4DAFFD9A916 -Dtests.security.manager=true -Dtests.locale=be-BY -Dtests.timezone=America/Araguaina -Druntime.java=8
```

**Reproduces locally?**: No

**Failure history**:

It's been failing once in a while in the past 6 months.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testSecuritySetup),sort:!(process.time-start,desc))

**Failure excerpt**:

```
org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT > testSecuritySetup FAILED
    org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:43207], URI [/_license], status line [HTTP/1.1 404 Not Found]
    { }
        at __randomizedtesting.SeedInfo.seed([EB6BC4DAFFD9A916:960DB491A93081CF]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
        at org.elasticsearch.test.rest.ESRestTestCase.getAsMap(ESRestTestCase.java:1222)
        at org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT.checkBasicLicenseType(EnableSecurityOnBasicLicenseIT.java:101)
        at org.elasticsearch.xpack.security.EnableSecurityOnBasicLicenseIT.testSecuritySetup(EnableSecurityOnBasicLicenseIT.java:68)
```

### LINKED ISSUE #60519: SecurityWithBasicLicenseIT.testWithBasicLicense failed
**Build scan**:
https://gradle-enterprise.elastic.co/s/fr4mt4blht7u4

**Repro line**:
`./gradlew ':x-pack:plugin:security:qa:security-basic:integTestRunner' --tests "org.elasticsearch.xpack.security.SecurityWithBasicLicenseIT.testWithBasicLicense" -Dtests.seed=8896CF1F5831ADCC -Dtests.security.manager=true -Dtests.locale=be -Dtests.timezone=Asia/Manila -Druntime.java=11`

**Reproduces locally?**: No.

**Applicable branches**: master

**Failure history**:
https://build-stats.elastic.co/goto/bf6148253b0eb65ed4ae64112b8a4ce7

**Failure excerpt**:
```

org.elasticsearch.xpack.security.SecurityWithBasicLicenseIT > testWithBasicLicense FAILED |  
-- | --
  | org.elasticsearch.client.ResponseException: method [GET], host [http://[::1]:36021], URI [/_license], status line [HTTP/1.1 404 Not Found] |  
  | { } |  
  | at __randomizedtesting.SeedInfo.seed([8896CF1F5831ADCC:9E1C8AAED47D5688]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:302) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) |  
  | at org.elasticsearch.test.rest.ESRestTestCase.getAsMap(ESRestTestCase.java:1185) |  
  | at org.elasticsearch.xpack.security.SecurityWithBasicLicenseIT.checkLicenseType(SecurityWithBasicLicenseIT.java:81) |  
  | at org.elasticsearch.xpack.security.SecurityWithBasicLicenseIT.testWithBasicLicense(SecurityWithBasicLicenseIT.java:31)

```

Fails mostly on master but failed a few times also in 7.x branches.

### PR DESCRIPTION
**Pull request by ywangd**
When a new cluster starts, the HTTP layer become ready to accept incoming requests while the basic license is still being generated in the background. When a get license request comes in before the license is ready, it can get `404` error. This PR fixes it by either: ensure the cluster is ready before issue the license request or wrap the license request in assertBusy.

Resolves: #59157
Resolves: #60468
Resolves: #60519

### CODE REVIEW

File: docs/src/test/java/org/elasticsearch/smoketest/DocsClientYamlTestSuiteIT.java [hunk 1]
```diff
@@ -175,6 +175,11 @@ protected boolean isCcrTest() {
         return testName != null && testName.contains("/ccr/");
     }
 
+    protected boolean isGetLicenseTest() {
+        String testName = getTestName();
+        return testName != null && (testName.contains("/get-license/") || testName.contains("\\get-license\\"));
```
Comment (tvernum) [inline docs/src/test/java/org/elasticsearch/smoketest/DocsClientYamlTestSuiteIT.java:180]: Why does this need to support `\\` but ccr doesn't?

**Review by tvernum — APPROVED** [review]

File: docs/src/test/java/org/elasticsearch/smoketest/DocsClientYamlTestSuiteIT.java (hunk 1 above)
Comment (ywangd) [reply docs/src/test/java/org/elasticsearch/smoketest/DocsClientYamlTestSuiteIT.java:180]: My guess is that ccr tests do not run on Windows? There are other similar methods in this file, e.g. `isMachineLearningTest`, `isTransformTest` and they all check for the backslash'd variant. The CI does have machine learning specific jobs so I think they are justified. 

For license check, I decided to add it because we do have multijob-windows-compatibility jobs. I am not completely sure that these jobs run the license check. But it's easy to add so I just did it.
