### PR TITLE
Fix bug where moving_avg prediction keys are appended to previous prediction

### LINKED ISSUE #11454: predicting two moving averages in the same aggregation produces incorrect keys for predicted buckets
In the example request below we have a date histogram with buckets for each month between 01 Jan 2001 (inclusive) and 01 Jan 2005 (not inclusive). In each bucket (month) we calculate the minimum distance, the derivative of that minimum (the speed) and then do a moving average of the distance and the moving average of the speed. Both moving averages predict the next 12 months of values.

The first moving average to execute (lets say the distance moving average) works fine and produces buckets for Jan 2005 to Dec 2005 (inclusive) as expected. The problem is that when the second moving average runs (the speed moving average), it appends its predictions onto the end of the buckets and predict for Jan 2006 to Dec 2006 (inclusive). This is because we assume predictions should always append buckets on the end of the histogram, rather than predicting for buckets starting at the next bucket after the last value for whatever metric we are predicting.

Example request:

```json
{
  "query": {
    "range": {
      "date": {
        "gte": "2001-01-01",
        "lt": "2005-01-01"
      }
    }
  },
  "size": 0,
  "aggs": {
    "histo": {
      "date_histogram": {
        "field": "date",
        "interval": "month"
      },
      "aggs": {
            "dist": {
              "min": {
                "field": "distance"
              }
        },
        "speed": {
          "derivative": {
            "buckets_path": "distance"
          }
        },
        "speed-mov-avg": {
          "moving_avg": {
            "buckets_path": "speed",
            "predict": 12,
            "model" : "holt",
            "settings" : {
                "alpha" : 0.5,
                "beta": 0.5
            }
          }
        },
        "dist-mov-avg": {
          "moving_avg": {
            "buckets_path": "distance",
            "predict": 12,
            "model" : "holt",
            "settings" : {
                "alpha" : 0.5,
                "beta": 0.5
            }
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by polyfractal**
Flow is now:
1. Iterate over buckets, generating movavg values if possible
2. If predictions are requested, a hashmap of keys is maintained for lookup later
3. Track the last valid key (e.g. last key that had data)
4. When a prediction is needed, we check in the map to see if the key is present.
   1. If the key is present, we create a new bucket with the old aggs + new prediction and overwrite the existing bucket
   2. If the key was not found, we simply generate a brand new bucket with the prediction
5. Predictions are now appended to the end of the "valid data", rather than the end of the requested range.  This makes more sense anyway, and works nicely with the gap policies.

The map is needed to avoid doing constant binary searches over the list of buckets.  We may need to add an `execution_mode` that allows a bin-search in the future, in case the user is executing massive moving avgs and would prefer to trade CPU for memory.

The solution feels a little janky...happy to entertain a different solution.  If this looks reasonable, I'll work up some more test cases (movavgs with different predictions, 3+ movavgs, etc)

Fixes #11454

### CODE REVIEW

**Comment by colings86** [comment]
@polyfractal given that we know the keys are always in the correct order in the list, can we not just store the position of the last bucket which had a value? Then when we predict we just start at that position and iterate through the remaining buckets predicting values until we run out of existing buckets and have to start creating new ones.

**Comment by polyfractal** [comment]
@colings86 Updated, cleaner now :)

File: src/main/java/org/elasticsearch/search/aggregations/pipeline/movavg/MovAvgPipelineAggregator.java [hunk 1]
```diff
@@ -158,13 +157,35 @@ public InternalAggregation reduce(InternalAggregation aggregation, ReduceContext
 
             double[] predictions = model.predict(values, predict);
             for (int i = 0; i < predictions.length; i++) {
```
Comment (colings86) [inline src/main/java/org/elasticsearch/search/aggregations/pipeline/movavg/MovAvgPipelineAggregator.java]: why not start `i` from 1 and have the end condition as `i <= predictions.length`? You seem to always use `i+1` anyway?

Comment (polyfractal) [inline src/main/java/org/elasticsearch/search/aggregations/pipeline/movavg/MovAvgPipelineAggregator.java]: No particularly compelling reason, just how I was thinking about it at the time.  E.g. the first prediction is one ahead of the last valid bucket, second prediction is two ahead, etc.

Can switch it if you think it is cleaner.  Will need to change `predictions[i]` to `predictions[i - 1]` to compensate.

Comment (colings86) [inline src/main/java/org/elasticsearch/search/aggregations/pipeline/movavg/MovAvgPipelineAggregator.java]: Had missed that `predictions[i]`. Think in that case it's better as is.

**Comment by colings86** [comment]
LGTM
