### PR TITLE
Fix and unmute `CrossClusterEsqlRCS1UnavailableRemotesIT` tests

### LINKED ISSUE #118350: [CI] CrossClusterEsqlRCS1UnavailableRemotesIT testEsqlRcs1UnavailableRemoteScenarios failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #5292 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/iml7kd2mdcniu)
- [elasticsearch-pull-request #44776 / part-4](https://gradle-enterprise.elastic.co/s/rfsy5d3rxee4w)
- [elasticsearch-pull-request #44706 / part-4](https://gradle-enterprise.elastic.co/s/a2a6mie2kngju)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:security:qa:multi-cluster:javaRestTest" --tests "org.elasticsearch.xpack.remotecluster.CrossClusterEsqlRCS1UnavailableRemotesIT.testEsqlRcs1UnavailableRemoteScenarios" -Dtests.seed=A423397337C6646C -Dtests.locale=en-GD -Dtests.timezone=Atlantic/Cape_Verde -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.remotecluster.CrossClusterEsqlRCS1UnavailableRemotesIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEsqlRcs1UnavailableRemoteScenarios),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a string containing "connect_transport_exception"
     but: was "method [POST], host [http://[::1]:50649], URI [_query], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"node_disconnected_exception","reason":"[][[::1]:50919][indices:data/read/esql/resolve_fields] disconnected"}],"type":"node_disconnected_exception","reason":"[][[::1]:50919][indices:data/read/esql/resolve_fields] disconnected"},"status":500}"
```

**Issue Reasons:**
- [main] 3 failures in test testEsqlRcs1UnavailableRemoteScenarios (0.4% fail rate in 851 executions)
- [main] 2 failures in step part-4 (0.6% fail rate in 341 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (0.6% fail rate in 340 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by pawankartik-elastic**
Fixes #118350.

Solution inline with https://github.com/elastic/elasticsearch/pull/119977.

### CODE REVIEW

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/CrossClusterEsqlRCS1UnavailableRemotesIT.java [hunk 1]
```diff
@@ -177,7 +178,10 @@ private void remoteClusterShutdownWithSkipUnavailableFalse() throws Exception {
             // A simple query that targets our remote cluster.
             String query = "FROM *,my_remote_cluster:* | LIMIT 10";
             ResponseException ex = expectThrows(ResponseException.class, () -> client().performRequest(esqlRequest(query)));
-            assertThat(ex.getMessage(), containsString("connect_transport_exception"));
+            assertThat(
+                ex.getMessage(),
+                anyOf(containsString("connect_transport_exception"), containsString("node_disconnected_exception"))
```
Comment (quux00) [inline x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/CrossClusterEsqlRCS1UnavailableRemotesIT.java:183]: This should also have the third variant added we saw in the enrich tests.

Comment (pawankartik-elastic) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/CrossClusterEsqlRCS1UnavailableRemotesIT.java]: Pushed a commit to fix this.

**Comment by quux00** [comment]
Let's add `auto-backport` to the labels and `v8.18.0` after you get the original test backported.

**Comment by quux00** [comment]
Did this ever get backported to 8.18?

**Comment by pawankartik-elastic** [comment]
It's a separate PR here: https://github.com/elastic/elasticsearch/pull/120802. I believe we can merge these 2 independent of each other without relying on the backport tool?

**Review by quux00 — APPROVED** [review]
LGTM
