### PR TITLE
Using ObjectParser in UpdateRequest

### LINKED ISSUE #28740: _update API should check the syntax in case of scripted updates
**Elasticsearch version** (`bin/elasticsearch --version`): 6.1.2

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**:

The `_update` API doesn't seem to reject a command that is wrong. Actually, this example comes from [The Definitive Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html) (which I know it's WIP), but still the ES API should reply back with an error for such a command:

```
POST /website/blog/1/_update
{
  "script": "ctx.op = ctx._source.views == params.count ? 'delete' : 'none'",
  "params": {
    "count": 1
  }
}
```

This returns:

```
{
  "_index": "website",
  "_type": "blog",
  "_id": "1",
  "_version": 2,
  "result": "noop",
  "_shards": {
    "total": 0,
    "successful": 0,
    "failed": 0
  }
}
```

Debugging this with `Debug.explain(params)` shows that there is no `params` registered. Which, in fact, is fine since the syntax is incorrect: there shouldn't be any `params` definitions at the root level, but inside `script` itself. The correct syntax should be:

```
POST /website/blog/1/_update
{
  "script": {
    "source": "ctx.op = ctx._source.views == params.count ? 'delete' : 'none'",
    "params": {
      "count": 1
    }
  }
}
```

### PR DESCRIPTION
**Pull request by liketic**
Reject unknown field and switch ```fromXContent``` to ```ObjectParser```. 

Closes #28740

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
Could you add a unit test with the example that you hit in addition to the one you already have?

File: server/src/main/java/org/elasticsearch/action/update/UpdateRequest.java [hunk 1]
```diff
@@ -55,6 +57,58 @@
...
+            (parser, context) -> {
+                XContentParser.Token token = parser.currentToken();
+                List<Object> fields = null;
+                if (token == XContentParser.Token.START_ARRAY) {
+                    fields = parser.list();
+                } else if (token.isValue()) {
+                    fields = Collections.singletonList(parser.text());
+                }
+                return fields;
+            }, FIELDS_FIELD, ObjectParser.ValueType.STRING_ARRAY);
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/action/update/UpdateRequest.java]: I *think* you can use `PARSER.declareStringArray(UpdateRequest::fields, FIELDS_FIELD)`. It doens't reject non-array things but I think that is fine. Another choice would be to simply pitch this. It has been deprecated for a year and a half (since 1764ec56b38) and we are only going to merge this to the master branch anyway so it is going to be released during a major version so we can make breaking changes like dropping a deprecated field.

**Review by nik9000 — CHANGES_REQUESTED** [review]
I left a minor thing. Otherwise I think this looks great!

Do you mind dropping `_fields`? I believe you'd need to add a breaking changes note somewhere in the docs starting at `migrate_7_0.asciidoc`. Maybe in a new `crud.asciidoc` file. Are you ok with making that change as part of this?

**Comment by liketic** [comment]
@nik9000 Thank you so much! I updated the PR and hope that's what we need. And added a note in migration/api , not sure if that's appropriate.  And another problem is I don't know how to avoid the failure when executing task ```:qa:mixed-cluster:v6.3.0-SNAPSHOT#mixedClusterTestRunner```, because I removed ```fields = in.readOptionalStringArray();``` from ```UpdateRequest.readFrom``` which caused a bwc issue. Thanks for your help!

File: server/src/test/java/org/elasticsearch/update/UpdateIT.java [hunk 2]
```diff
@@ -225,7 +225,7 @@ public void testUpsertDoc() throws Exception {
         UpdateResponse updateResponse = client().prepareUpdate(indexOrAlias(), "type1", "1")
                 .setDoc(XContentFactory.jsonBuilder().startObject().field("bar", "baz").endObject())
                 .setDocAsUpsert(true)
-                .setFields("_source")
+                .setFetchSource(true)
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/update/UpdateIT.java]: Hmmm. I *think* this is true by default. Can you check what happens if you drop the `.setFetchSource(true)` part?

File: server/src/test/java/org/elasticsearch/update/UpdateIT.java [hunk 3]
```diff
@@ -293,12 +293,8 @@ public void testUpdate() throws Exception {
         ensureGreen();
 
         Script fieldIncScript = new Script(ScriptType.INLINE, UPDATE_SCRIPTS, FIELD_INC_SCRIPT, Collections.singletonMap("field", "field"));
-        try {
-            client().prepareUpdate(indexOrAlias(), "type1", "1").setScript(fieldIncScript).execute().actionGet();
-            fail();
-        } catch (DocumentMissingException e) {
-            // all is well
-        }
+        expectThrows(DocumentMissingException.class,
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/update/UpdateIT.java]: :heart:

Comment (nik9000) [reply server/src/test/java/org/elasticsearch/update/UpdateIT.java]: Usually I do
```
Exception e = expectThrows(DocumentMissingException.class, () ->
    the thing);
assertEquals("whatever", e.getMessage());
```

Just to make sure it was the *right* exception. In this case there is only one kind of message for `DocumentMissingException` so it is probably safe to do what you are doing, but it still might be nice anyway.

**Review by nik9000 — CHANGES_REQUESTED** [review]
I left a few suggestions and one small thing.

I think you can fix the failing mixed cluster version test with something like:
You can use something like this:
```
    - skip:
        version: " - 6.99.99"
        reason:  fields dropped in 7.0
```

**Comment by nik9000** [comment]
And thanks so much for doing this!

@jimczi, I believe you deprecated `fields` in updates. Are you ok with removing for 7.0 like I've suggested here? I just realized I might want to confirm with you.

**Comment by jimczi** [comment]
+1 to remove `fields. Thanks @liketic @nik9000 !

File: server/src/test/java/org/elasticsearch/update/UpdateIT.java (hunk 2 above)
Comment (liketic) [reply server/src/test/java/org/elasticsearch/update/UpdateIT.java]: By default the field ```fetchSource``` is null in the class UpdateRequest:
```
    private FetchSourceContext fetchSourceContext;
```. 
If we drop this, we'll get a AssertionError.

Comment (nik9000) [reply server/src/test/java/org/elasticsearch/update/UpdateIT.java]: I see it. I was tired when I was reading it. You are right to do what you did.

File: server/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java [hunk 4]
```diff
@@ -375,21 +370,11 @@ public BulkRequest add(BytesReference data, @Nullable String defaultIndex, @Null
...
                                 fetchSourceContext = FetchSourceContext.fromXContent(parser);
                             } else {
                                 throw new IllegalArgumentException("Action/metadata line [" + line + "] contains an unknown parameter [" + currentFieldName + "]");
                             }
-                        } else if (token == XContentParser.Token.START_ARRAY) {
-                            if (FIELDS.match(currentFieldName, parser.getDeprecationHandler())) {
-                                DEPRECATION_LOGGER.deprecated("Deprecated field [fields] used, expected [_source] instead");
-                                List<Object> values = parser.list();
-                                fields = values.toArray(new String[values.size()]);
-                            } else {
```
[the remark this answers is not in the document]
Comment (liketic) [reply server/src/main/java/org/elasticsearch/action/bulk/BulkRequest.java]: Thanks! I put the ```throw``` back and add a test.

**Comment by liketic** [comment]
Thanks @nik9000 , I pushed 2024751c8be2fb6a649fce616e746778565ff7b6

File: server/src/main/java/org/elasticsearch/action/update/UpdateRequest.java [hunk 5]
```diff
@@ -800,7 +772,6 @@ public void readFrom(StreamInput in) throws IOException {
             doc = new IndexRequest();
             doc.readFrom(in);
         }
-        fields = in.readOptionalStringArray();
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/action/update/UpdateRequest.java]: So removing this line is going to cause problems in mixed clusters. Elasticsearch versions before 7.0.0 will continue to send this array. You have to read it and decide what to do with it. Something like:
```
        if (false == in.getVersion().onOrAfter(Version.V_7_0_0_alpha1)) {
            String[] fields = in.readOptionalStringArray();
            if (fields != null) {
                throw new IllegalArgumentException("[fields] is no longer supported");
            }
        }
```

is probably fine to be honest.

File: server/src/main/java/org/elasticsearch/action/update/UpdateRequest.java [hunk 6]
```diff
@@ -838,7 +809,6 @@ public void writeTo(StreamOutput out) throws IOException {
             doc.id(id);
             doc.writeTo(out);
         }
-        out.writeOptionalStringArray(fields);
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/action/update/UpdateRequest.java]: You'll want to do something like:
```
if (false == out.getVersion().onOrAfter(Version.V_7_0_0_alpha_1) {
  out.writeOptionalStringArray(null);
}
```

That way 6.x can parse the request. We know there aren't any `fields` anyway because we couldn't have parsed them.

File: docs/reference/migration/migrate_7_0/api.asciidoc [hunk 7]
```diff
@@ -22,3 +22,6 @@ The following parameters starting with underscore have been removed:
 Instead of these removed parameters, use their non camel case equivalents without
 starting underscore, e.g. use `version_type` instead of `_version_type` or `versionType`.
 
+
+==== The parameter `fields` deprecated in 6.x has been removed from Bulk request 
+and Update request.
```
Comment (nik9000) [inline docs/reference/migration/migrate_7_0/api.asciidoc]: Can you also add a note about the change you update request?

I'm not *sure* this is the right file for them but you may as well put them here for now and we'll move them if we decide there is a better spot.

**Review by nik9000 — CHANGES_REQUESTED** [review]
So I'm genuinely sorry I suggested dropping the `fields` parameter in this PR. It has made it *much* larger than your original contribution. Thanks so much for following through with this.

I left a few things. I believe you should remove your "skip"s in the rest tests. I didn't understand what you meant by the REST tests failing when I told you about the skip. It is an option, but not the right one in this case.

We need to make sure that update requests work in a mixed version cluster and those tests were telling you that they were not. I left some line comments on the line that I'm fairly sure need to be changed to fix the tests.

Again, thanks for all of your work on this. I think this is super close!

**Comment by liketic** [comment]
Thanks @nik9000 That's much better!  I pushed fae79081c531e0829f1597096380a0fce4e039ba

**Review by nik9000 — APPROVED** [review]
This looks good to me! I'll merge it when I get clean builds on the intake jobs.

**Comment by nik9000** [comment]
Or maybe there are conflicts. Nuts!

If you are around @liketic, can you merge master into this branch and resolve the conflicts? I can do it if you'd prefer.

**Comment by liketic** [comment]
Thanks @nik9000 , the conflict was resolved.

**Comment by nik9000** [comment]
> Thanks @nik9000 , the conflict was resolved.

:heart:

**Review by nik9000 — APPROVED** [review]
@elasticmachine, test this please

**Comment by nik9000** [comment]
Damn, wrong power words!

@elasticmachine, run all tests!

**Comment by nik9000** [comment]
That did it.

**Comment by nik9000** [comment]
The PR build failed but it looks like that is because this needs master merged into it again. I've done so locally and am re-running the build locally.

**Comment by nik9000** [comment]
OK! I got a passing build locally. I'll merge this when the intake build is green.

**Comment by nik9000** [comment]
Merged to master! Finally! Thanks @liketic! Thanks for sticking with it! I've learned my lesson. Next time I won't ask about dropping a deprecated thing when converting to ObjectParser. That more than doubled the complexity of this. But thanks for finishing it out!

For posterity: I rewrote the commit message but accidentally didn't rewrite the subject line. Oops.
