### PR TITLE
Drain responses on completion for TransportNodesAction

### LINKED ISSUE #128852: `ConcurrentModificationException` in `TransportClusterStatsAction`
### Elasticsearch Version

9.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

---

### Problem Description

This error occurs:
```
        java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1096)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1050)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.admin.cluster.stats.VersionStats.of(VersionStats.java:53)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.admin.cluster.stats.TransportClusterStatsAction.lambda$newResponseAsync$0(TransportClusterStatsAction.java:209)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:105)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:401)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:321)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:217)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.SubscribableListener.addListener(SubscribableListener.java:175)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.SubscribableListener.lambda$andThenApply$2(SubscribableListener.java:535)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.ActionListener.run(ActionListener.java:465)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.SubscribableListener.newForked(SubscribableListener.java:133)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.SubscribableListener.andThenApply(SubscribableListener.java:535)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.admin.cluster.stats.TransportClusterStatsAction.newResponseAsync(TransportClusterStatsAction.java:186)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.admin.cluster.stats.TransportClusterStatsAction.newResponseAsync(TransportClusterStatsAction.java:82)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.nodes.TransportNodesAction$1.lambda$onCompletion$4(TransportNodesAction.java:167)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.nodes.TransportNodesAction.lambda$doExecute$0(TransportNodesAction.java:179)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:40)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
```

### Steps to Reproduce

unclear

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by ywangd**
This PR ensures the node responses are copied and drained exclusively in onCompletion so that they do not get concurrently modified by cancellation.

Resolves: #128852

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java [hunk 1]
```diff
@@ -163,8 +163,13 @@ protected void onItemFailure(DiscoveryNode discoveryNode, Exception e) {
             protected CheckedConsumer<ActionListener<NodesResponse>, Exception> onCompletion() {
                 // ref releases all happen-before here so no need to be synchronized
                 return l -> {
-                    try (var ignored = Releasables.wrap(Iterators.map(responses.iterator(), r -> r::decRef))) {
-                        newResponseAsync(task, request, actionContext, responses, exceptions, l);
+                    final List<NodeResponse> completedResponses;
+                    synchronized (responses) {
+                        completedResponses = List.copyOf(responses);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: I'd rather we didn't add another full-list copy on the happy path just to deal with the rare possibility of concurrent cancellation. Instead, let's use an `AtomicBoolean` to make sure that we only do (at most) one of this call to `newResponseAsync` or the drain-and-close in the cancellation handler.

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: Sure I pushed 4adb4a60731e26057ad9f1bf26b4d9c7e43b7c98

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java [hunk 2]
```diff
@@ -163,8 +167,12 @@ protected void onItemFailure(DiscoveryNode discoveryNode, Exception e) {
...
                 // ref releases all happen-before here so no need to be synchronized
                 return l -> {
-                    try (var ignored = Releasables.wrap(Iterators.map(responses.iterator(), r -> r::decRef))) {
-                        newResponseAsync(task, request, actionContext, responses, exceptions, l);
+                    if (responsesHandled.compareAndSet(false, true)) {
+                        try (var ignored = Releasables.wrap(Iterators.map(responses.iterator(), r -> r::decRef))) {
+                            newResponseAsync(task, request, actionContext, responses, exceptions, l);
+                        }
+                    } else {
+                        newResponseAsync(task, request, actionContext, List.of(), exceptions, l);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: Hmm actually that raises a different concern. The exceptions correspond to the node-level responses, but it could be that the task was cancelled after we received the last response. If that happens, we may drain and close all the node-level responses and then send back an empty, but apparently-successful, response here right?

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: Yes. I was going to comment on this. It's an existing behaviour. I was wondering whether we should change it in a different PR or should we bundle it in this one?

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java [hunk 3]
```diff
@@ -163,8 +167,12 @@ protected void onItemFailure(DiscoveryNode discoveryNode, Exception e) {
             protected CheckedConsumer<ActionListener<NodesResponse>, Exception> onCompletion() {
                 // ref releases all happen-before here so no need to be synchronized
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: nit: this comment should now be under the `if (responsesHandled` branch

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: I'd be inclined to fix it here, I think it's simple enough and fits naturally into the test you've already written.

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java (hunk 3 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: Yeah see f990e43c4f03ed01f052b28736e7518df7b9253d

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java (hunk 2 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: > fits naturally into the test you've already written

Sorry, I take that back, we don't go down that branch in the new test. But we probably should cover this branch too, and if we do that then I expect it's not hard to assert that we get an exceptional response.

File: server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java [hunk 4]
```diff
@@ -316,6 +318,62 @@ protected Object createActionContext(Task task, TestNodesRequest request) {
...
+                Task task,
+                TestNodesRequest request,
+                Void unused,
+                List<TestNodeResponse> testNodeResponses,
+                List<FailedNodeException> failures,
+                ActionListener<TestNodesResponse> listener
+            ) {
+                final var waited = new AtomicBoolean();
+                for (var response : testNodeResponses) {
+                    if (waited.compareAndSet(false, true)) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java]: This is kind of a convoluted way to wait on a nonempty list. There's no concurrency here so the `compareAndSet` is a bit of a sledgehammer. Can we just check `testNodeResponses.isEmpty()`?

Comment (ywangd) [reply server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java]: This is to wait for only the first response. You are right there is no need for AtomicBoolean. I changed it to a primitive boolean variable.

File: server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java [hunk 5]
```diff
@@ -316,6 +317,67 @@ protected Object createActionContext(Task task, TestNodesRequest request) {
...
+                ActionListener<TestNodesResponse> listener
+            ) {
+                boolean waited = false;
+                for (var response : testNodeResponses) {
+                    if (waited == false) {
+                        waited = true;
+                        safeAwait(barrier);
+                        safeAwait(barrier);
+                    }
+                }
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java]: Can we not just do this?

```suggestion
                if (testNodeResponses.isEmpty() == false) {
                    safeAwait(barrier);
                    safeAwait(barrier);
                }
```

Indeed can we not assert that `testNodeResponses` is nonempty in this test?

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java [hunk 6]
```diff
@@ -161,10 +166,18 @@ protected void onItemFailure(DiscoveryNode discoveryNode, Exception e) {
...
+                        // ref releases all happen-before here so no need to be synchronized
+                        try (var ignored = Releasables.wrap(Iterators.map(responses.iterator(), r -> r::decRef))) {
+                            newResponseAsync(task, request, actionContext, responses, exceptions, l);
+                        }
+                    } else {
+                        logger.debug("task cancelled after all responses were collected");
+                        assert task instanceof CancellableTask : "expect CancellableTask, but got: " + task;
+                        final var cancellableTask = (CancellableTask) task;
+                        assert cancellableTask.isCancelled();
+                        throw new TaskCancelledException("task cancelled [" + cancellableTask.getReasonCancelled() + "]");
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: `getReasonCancelled` is racy according to its Javadocs: "May also be null if the task was just cancelled since we don't set the reason and the cancellation flag atomically." You need to use `notifyIfCancelled` to get the right behaviour here.

Comment (ywangd) [inline server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: This change is to address the edge case commented [here](https://github.com/elastic/elasticsearch/pull/130303#discussion_r2174359775). But I struggle to write a test for it. Essentially we need the cancel to comes in after all node responses are collected but before the `AtomicBoolean responsesHandled` is checked. One option is to extract the creation of `CancellableFanOut` into its own protected method plus wrapping the returned value with a delgating `CancellableFanOut`. But this requires making the 4 protected methods in `CancellableFanOut` package private. I am a bit suspicous on whether this is the right path to go down. I am open to suggestions.

File: server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java (hunk 5 above)
Comment (ywangd) [reply server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java]: The for-loop is to reproduce the `ConcurrentModificationException` reported in https://github.com/elastic/elasticsearch/issues/128852. The test always passes without it.

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java (hunk 6 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: Thanks. Pushed 3d072614922a25bf738610c7116134f0d7051dfd. Please let me know if it has used the right listener.

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java (hunk 2 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: I added the fix, but having difficulty to write a test for it. See also https://github.com/elastic/elasticsearch/pull/130303#discussion_r2174459325

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java (hunk 6 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: I'd be content with a test which concurrently completes the action and cancels it, and asserts that we always either get an exception or we get a successful response. I expect such a test would find the bug here pretty reliably.

Comment (ywangd) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: Cool I added such a test, see fb71e89b6a100010df9e7bc9f6699fbb9b9fe76e

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java [hunk 7]
```diff
@@ -161,10 +167,18 @@ protected void onItemFailure(DiscoveryNode discoveryNode, Exception e) {
...
+                        // ref releases all happen-before here so no need to be synchronized
+                        try (var ignored = Releasables.wrap(Iterators.map(responses.iterator(), r -> r::decRef))) {
+                            newResponseAsync(task, request, actionContext, responses, exceptions, l);
+                        }
+                    } else {
+                        logger.debug("task cancelled after all responses were collected");
+                        assert task instanceof CancellableTask : "expect CancellableTask, but got: " + task;
+                        final var cancellableTask = (CancellableTask) task;
+                        assert cancellableTask.isCancelled();
+                        cancellableTask.notifyIfCancelled(finalListener);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: I think we should complete `l` here, not the `finalListener`.

File: server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java (hunk 5 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java]: I see, could you add a comment to that effect or else this'll get "tidied up"

File: server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java (hunk 7 above)
Comment (ywangd) [reply server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java]: Ah right. I was in a rush to finish up and missed the obvious 🤦 pushed db76ef879f1c4cab4badf7f48972c002f273d9ad

File: server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java (hunk 5 above)
Comment (ywangd) [reply server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java]: Comment added in fdf0b22c461e99aab0ef548a17cf8bc6eba2af66

File: server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java [hunk 8]
```diff
@@ -316,6 +321,137 @@ protected Object createActionContext(Task task, TestNodesRequest request) {
...
+            safeAwait(raceBarrier);
+            TaskCancelHelper.cancel(cancellableTask, "simulated");
+        });
+        completeThread.start();
+        cancelThread.start();
+        safeAwait(raceBarrier);
+
+        try {
+            final var testNodesResponse = future.actionGet(SAFE_AWAIT_TIMEOUT);
+            assertFalse(cancellableTask.isCancelled());
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java]: I don't think this'll hold in general, we could cancel the task after the completion has already passed the point of no return and then the task's cancellation flag will be set even though it completed successfully.

Comment (ywangd) [reply server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java]: Yeah good point, Thanks. I removed that in b38783d8bfa1299dc719b42c4511077ed76d4fed which also contains a few other tweaks.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch
