### PR TITLE
Fix race in testSeqNoPrunedOnLeaderAfterFollowerCatchesUp

### LINKED ISSUE #147133: [CI] CcrSeqNoPruningIT testSeqNoPrunedOnLeaderAfterFollowerCatchesUp failing
**Build Scans:**
- [elasticsearch-intake #38146 / part2](https://gradle-enterprise.elastic.co/s/mih5cc7ukznx4)
- [elasticsearch-pull-request #138593 / part-2](https://gradle-enterprise.elastic.co/s/v475u3fjmt25k)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ccr:internalClusterTest" --tests "org.elasticsearch.xpack.ccr.CcrSeqNoPruningIT.testSeqNoPrunedOnLeaderAfterFollowerCatchesUp" -Dtests.seed=A2764AE2F7F78A3B -Dtests.locale=mi -Dtests.timezone=Etc/GMT-13 -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ccr.CcrSeqNoPruningIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSeqNoPrunedOnLeaderAfterFollowerCatchesUp'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: [wbtxkrnz][0] _seq_no doc values should be empty
Expected: <2147483647>
     but: was <0>
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testSeqNoPrunedOnLeaderAfterFollowerCatchesUp
- [main] 1 consecutive failures in step part2
- [main] 1 consecutive failures in pipeline elasticsearch-intake
- [main] 2 failures in test testSeqNoPrunedOnLeaderAfterFollowerCatchesUp (0.3% fail rate in 708 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by inespot**
See investigation: https://github.com/elastic/elasticsearch/issues/147133#issuecomment-4315265709.

During a force merge, `PruningMergePolicy` calls `SoftDeletesPolicy.getMinRetainedSeqNo()` once per input segment. That method is synchronized and can return the `minRetainedSeqNo` from cache only (without updating it) when a retention lock is held. 
When the test reaches the merge, the cached `minRetainedSeqNo` can still be value `0`. Indeed, during the first flush, `getMinRetainedSeqNo()` is called with `localCheckpointOfSafeCommit = -1`, giving `minSeqNoToRetain = Math.min(minSeqNoForQueryingChanges, 1 + (-1)) = 0`
The second flush is a no-op (no new uncommitted changes?) and does not call `getMinRetainedSeqNo()`.

The CCR lease renewal task briefly holds a retention lock every 100ms, and if it coincides with at least the first segment's call, the retention query consequently uses `seq_no >= 0`, and pruning is then skipped for that segment.

The fix calls `assertMinRetainedSeqNoAdvanced` before the force merge, which retries `IndexShard.getMinRetainedSeqNo()` until it returns maxSeqNo + 1, so all subsequent merge calls read the correct minimum from cache.

Reproed by adding a slight delay on retention lock acquiring/releasing (see https://github.com/elastic/elasticsearch/pull/147484/changes/6d5a6c1d383a7e57315bc0b8aab7906e520879e9): https://gradle-enterprise.elastic.co/s/ihlq67q3drgnq

Also reproed on VM without the sleep delay, with commit pointing to: https://github.com/elastic/elasticsearch/commit/62e82b48e1c05ba6855070f020da42d488f430f5 (to get the additional logs): https://gradle-enterprise.elastic.co/s/xbdmnevyndarg

Closes: https://github.com/elastic/elasticsearch/issues/147133

### CODE REVIEW

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/CcrSeqNoPruningIT.java [hunk 1]
```diff
@@ -110,7 +111,7 @@ public void testSeqNoPrunedOnLeaderAfterFollowerCatchesUp() throws Exception {
         final long maxSeqNo = getMaxSeqNo(leaderClient(), leaderIndex);
         assertRetentionLeasesAdvanced(leaderClient(), leaderIndex, maxSeqNo + 1);
         persistGlobalCheckpointOnPrimaryShards(getLeaderCluster(), leaderIndex);
-        flush(leaderClient(), leaderIndex);
```
Comment (inespot) [inline x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/CcrSeqNoPruningIT.java:113]: This looks redundant with the flush on line 93? No new uncommitted docs in between. Let me know if I'm missing something though.

Comment (michalborek) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/CcrSeqNoPruningIT.java:113]: Just for my understanding, if we called `force flush` here, would there still be a case this being a no-op?

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java [hunk 2]
```diff
@@ -179,6 +179,38 @@ private static int doAssertShardsSeqNoDocValuesCount(IndicesService indicesServi
...
+     * @param cluster          the cluster containing the index
+     * @param indexName        the index to check
+     * @param expectedSeqNo    the expected minimum retained sequence number
+     */
+    public static void assertMinRetainedSeqNoAdvanced(InternalTestCluster cluster, String indexName, long expectedSeqNo) throws Exception {
+        assertBusy(() -> {
+            for (var indicesService : cluster.getDataNodeInstances(IndicesService.class)) {
+                for (var indexService : indicesService) {
+                    if (indexService.index().getName().equals(indexName)) {
+                        for (var indexShard : indexService) {
```
Comment (michalborek) [inline test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:199]: maybe we could extract this into "forEveryShard(cluster, indexName, lambda)" helper method (or similar), might be easier to read

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/CcrSeqNoPruningIT.java (hunk 1 above)
Comment (inespot) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/CcrSeqNoPruningIT.java:113]: Nop, it would not be a no-op. It would then pass this check: https://github.com/elastic/elasticsearch/blob/40cafb1f3b3699d11f4329c3bd9c6bb88c9da11a/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L2608-L2613
call `InternalEngine.commitIndexWriter`, which will then call `writer.commit()` with a lambda a call to `softDeletesPolicy.getMinRetainedSeqNo()`. But it's still subject to the same race: if the CCR renewal holds the retention lock during that call as well then we could end up with the same failure

File: test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java (hunk 2 above)
Comment (inespot) [reply test/framework/src/main/java/org/elasticsearch/index/seqno/SequenceNumbersTestUtils.java:199]: Agree! Although maybe worth doing this cleanup in a FLUP PR, considering this should also be applicable to other function in this class, `TSDBSyntheticIdsIT` and `SeqNoPruningIT`

**Comment by inespot** [comment]
I have also been running this test in a loop on a VM today with the same load conditions used to repro the failure and the proposed fix, no failure so far (see [test history](https://gradle-enterprise.elastic.co/scans/tests?search.startTimeMax=1777413599999&search.startTimeMin=1777240800000&search.timeZoneId=Europe%2FParis&tests.container=org.elasticsearch.xpack.ccr.CcrSeqNoPruningIT&tests.test=testSeqNoPrunedOnLeaderAfterFollowerCatchesUp&tests.unstableOnly=false)). Planning on waiting until we reach at least 1000+ green builds before merging.

File: x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/CcrSeqNoPruningIT.java (hunk 1 above)
Comment (tlrx) [reply x-pack/plugin/ccr/src/internalClusterTest/java/org/elasticsearch/xpack/ccr/CcrSeqNoPruningIT.java:113]: Yes, that's redundant indeed 🤔 

I think I added it to ensure that `SoftDeletesPolicy#localCheckpointOfSafeCommit` got updated as it's also part of the function that computes the minSeqNoToRetain. But obvisouly without `force=true` it can be a noop.

If the test passed several hundreds executions without it then it's best to remove it.

Thanks!

**Review by tlrx — APPROVED** [review]
LGTM
