### PR TITLE
Fix random failures in SearchResponseMerger#testMergeSearchHits

### LINKED ISSUE #40214: SearchResponseMergerTests#testMergeSearchHits fails reproducibly
Ran into this on an unrelated PR, but seems to fail reliably on master:

```
./gradlew :server:unitTest -Dtests.seed=C0023449F2A58809 -Dtests.class=org.elasticsearch.action.search.SearchResponseMergerTests -Dtests.method="testMergeSearchHits" -Dtests.security.manager=true -Dtests.locale=da -Dtests.timezone=America/Fort_Wayne -Dcompiler.java=11 -Druntime.java=8
```

```
FAILURE 0.41s | SearchResponseMergerTests.testMergeSearchHits <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: actual array was null
   >    at __randomizedtesting.SeedInfo.seed([C0023449F2A58809:9016D5FC5DC6CF26]:0)
   >    at org.elasticsearch.action.search.SearchResponseMergerTests.testMergeSearchHits(SearchResponseMergerTests.java:515)
   >    at java.lang.Thread.run(Thread.java:748)
```
Will followup with a mute.

### PR DESCRIPTION
**Pull request by jimczi**
This commit fixes the expectation in the test when the search hits are empty.

Closes #40214

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/search/SearchResponseMergerTests.java [hunk 1]
```diff
@@ -513,8 +512,11 @@ public void testMergeSearchHits() throws InterruptedException {
         assertNull(searchResponse.getScrollId());
 
         SearchHits searchHits = searchResponse.getHits();
-        assertArrayEquals(sortFields, searchHits.getSortFields());
-        assertEquals(collapseField, searchHits.getCollapseField());
+        // the sort fields and the collapse field are not returned when hits are empty
+        if (searchHits.getHits().length > 0) {
+            assertArrayEquals(sortFields, searchHits.getSortFields());
+            assertEquals(collapseField, searchHits.getCollapseField());
+        }
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/action/search/SearchResponseMergerTests.java]: nit: shall we assert that they are null otherwise?

**Review by javanna — APPROVED** [review]
left a tiny comment, LGTM

**Comment by jimczi** [comment]
@elasticmachine run elasticsearch-ci/1
