### PR TITLE
Robust error handling for enrollment calls

### LINKED ISSUE #79810: [CI] EnrollmentProcessTests test10AutoFormCluster failing
Test seems to fail somewhat frequently

**Build scan:**
https://gradle-enterprise.elastic.co/s/lbprapwe6bi56/tests/:qa:os:destructiveDistroTest.default-linux-archive/org.elasticsearch.packaging.test.EnrollmentProcessTests/test10AutoFormCluster

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.EnrollmentProcessTests&tests.test=test10AutoFormCluster

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c sudo -E -u elasticsearch "/tmp/elasticsearch-node2/bin/elasticsearch-enroll-node" --enrollment-token eyJ2ZXIiOiI4LjAuMCIsImFkciI6WyIxNzIuMTcuMC4xOjkyMDAiLCIxMC4yMjQuMy40Njo5MjAwIl0sImZnciI6IjcxZmEyNDhkZDIwZjJjZTI5YWYyYjA2YzMzZmUwMGIxMzQ3ZmM5YzI2M2YzNmIzMTEyMDk1YTk2YTdmY2JlODAiLCJrZXkiOiJEaDVOdkh3QkZfRFZsNDZkc2Q5QjpXRjFJaWJjdFNxcVpIckZ3aVlzMFNnIn0=]
   result: exitCode = [1] stdout = [] stderr = [Exception in thread "main" javax.net.ssl.SSLHandshakeException: No subject alternative names matching IP address 172.17.0.1 found
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142)
	at org.elasticsearch.xpack.core.common.socket.SocketAccess.lambda$doPrivileged$0(SocketAccess.java:43)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.elasticsearch.xpack.core.common.socket.SocketAccess.doPrivileged(SocketAccess.java:42)
	at org.elasticsearch.xpack.core.security.CommandLineHttpClient.execute(CommandLineHttpClient.java:164)
	at org.elasticsearch.xpack.core.security.CommandLineHttpClient.execute(CommandLineHttpClient.java:125)
	at org.elasticsearch.xpack.security.cli.EnrollNodeToCluster.execute(EnrollNodeToCluster.java:202)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:114)
	at org.elasticsearch.cli.Command.main(Command.java:79)
	at org.elasticsearch.xpack.security.cli.EnrollNodeToCluster.main(EnrollNodeToCluster.java:108)
Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 172.17.0.1 found
	at java.base/sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:165)
	at java.base/sun.security.util.HostnameChecker.match(HostnameChecker.java:101)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:452)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:426)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1475)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1442)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	... 24 more]

  at __randomizedtesting.SeedInfo.seed([4154C633C8488898:2C736EC85B2BC262]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:152)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:187)
  at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:170)
  at org.elasticsearch.packaging.test.EnrollmentProcessTests.test10AutoFormCluster(EnrollmentProcessTests.java:51)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by jkakavas**
When enrolling into an existing cluster, nodes will make a
request over HTTPS to a node of the existing cluster in order to
retrieve necessary information. We use
CommandLineHttpClient#execute which can throw an exception and we
need to catch them both for offering a better error message to the
users but also so that we can potentially try all the available
addresses we know from the enrollment token

Resolves: #79810

### CODE REVIEW

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java [hunk 1]
```diff
@@ -284,26 +284,30 @@ protected void execute(Terminal terminal, OptionSet options, Environment env) th
...
+                    enrollResponse = client.execute(
+                        "GET",
+                        enrollNodeUrl,
+                        new SecureString(enrollmentToken.getApiKey().toCharArray()),
+                        () -> null,
+                        CommandLineHttpClient::responseBuilder
+                    );
+                    if (enrollResponse.getHttpStatus() == 200) {
+                        break;
+                    }
```
Comment (albertzaharovits) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:298]: The call can fail in two different ways: on the connection or on the HTTP level.

The connection one is to be expected, but the HTTP one is not. Hence I think that a non-200 from the the `node enroll token` endpoint should result in an enrollment failure.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java [hunk 2]
```diff
@@ -284,26 +284,30 @@ protected void execute(Terminal terminal, OptionSet options, Environment env) th
...
+                } catch (Exception e) {
+                    terminal.errorPrint(Terminal.Verbosity.NORMAL, "Unable to communicate with the initial node on " + enrollNodeUrl);
```
Comment (albertzaharovits) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:300]: I would suggest we debug log the exception stacktrace; for example, the exception can also be certificate verification exception, or a connection timeout.

Also it is not always connecting with the "initial node". It is connecting with the node that generated the enrollment token.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java (hunk 1 above)
Comment (jkakavas) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:298]: >  but the HTTP one is not. Hence I think that a non-200 from the the node enroll token endpoint should result in an enrollment failure.

The enrollment token can contain multiple HTTP addresses for the existing nodes in the cluster. Presumably, each existing node can answer to the enrollment request. Why should a temporary failure in one node ( returning 5xx ) prevent the new node from enrolling, when it can still try and get the enrollment information from another node ?

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java (hunk 2 above)
Comment (jkakavas) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:300]: Makes sense, will adjust!

File: qa/os/src/test/java/org/elasticsearch/packaging/test/EnrollmentProcessTests.java [hunk 3]
```diff
@@ -27,7 +26,6 @@
 import static org.hamcrest.Matchers.is;
 import static org.junit.Assume.assumeTrue;
 
-@AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/79810")
 public class EnrollmentProcessTests extends PackagingTestCase {
```
Comment (albertzaharovits) [inline qa/os/src/test/java/org/elasticsearch/packaging/test/EnrollmentProcessTests.java:29]: I would suggest a test (or two) where the second node tries a "wrong" enrollment token, and then tries an enrollment token with some obviously wrong addresses first in th list, before finally succeding.

Only add if you believe it ads value (When testing manually, initially I wasn't sure if I could try again with another enrollment token on the same instalation).

**Review by albertzaharovits — APPROVED** [review]
I had a couple of suggestions. Address at your convenience.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java (hunk 1 above)
Comment (jkakavas) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:298]: Nevermind me, I forgot we changed this. We call `/_nodes/_local/http` when creating the enrollment token so the IP addresses we get are all for the same node.

Comment (jkakavas) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:298]: >  Hence I think that a non-200 from the the node enroll token endpoint should result in an enrollment failure.

It would still result to an enrollment failure _unless_ it was something temporary and there is another bound address for that node so when we retry talking to that address, the node responds successfully. Do you think it's worth exiting on non 200 immediately every time ?

Comment (albertzaharovits) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:298]: The enrollment token only contains the addresses of the node that generated it.

If the endpoint returns 400/500 I'm OK to retry that call, in the hope that it is a temporary failure, but I would say this is not necesary.

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java (hunk 2 above)
Comment (jkakavas) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:300]: printing the stacktrace on the terminal is tricky , would `terminal.errorPrint(Terminal.Verbosity.NORMAL, "Unable to communicate with the node on " + enrollNodeUrl + ". Error was " + e.getMessage());` suffice ?

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java (hunk 1 above)
Comment (jkakavas) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:298]: > The enrollment token only contains the addresses of the node that generated it.

yes, I figured out after writing the comment :) 

> If the endpoint returns 400/500 I'm OK to retry that call, in the hope that it is a temporary failure, but I would say this is not necesary.

No strong opinions, I'll adjust
