### PR TITLE
Fix AutoFollowIT Failures from Transport Thread Assertion

### LINKED ISSUE #67106: AutoFollowIT#testCleanFollowedLeaderIndexUUIDs failure
**Build scan**:
https://gradle-enterprise.elastic.co/s/wchepwmxp4rn6/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.AutoFollowIT/testCleanFollowedLeaderIndexUUIDs?expanded-stacktrace=WyIwIl0#1
**Repro line**:
```
./gradlew ':x-pack:plugin:ccr:internalClusterTest' --tests "org.elasticsearch.xpack.ccr.AutoFollowIT.testCleanFollowedLeaderIndexUUIDs" -Dtests.seed=C1F2474A919348E8 -Dtests.security.manager=true -Dtests.locale=et-EE -Dtests.timezone=America/Indiana/Marengo
```
**Reproduces locally?**:
No
**Applicable branches**:
`7.x`, `master`
**Failure history**:
It failed twice according to build scans
```
https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Madrid&tests.container=org.elasticsearch.xpack.ccr.AutoFollowIT&tests.sortField=FAILED&tests.test=testCleanFollowedLeaderIndexUUIDs&tests.unstableOnly=true
```
But only once according to `build-stats`
```
https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testCleanFollowedLeaderIndexUUIDs),sort:!(process.time-start,desc))
```
**Failure excerpt**:
```
org.elasticsearch.discovery.MasterNotDiscoveredException: (No message provided)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
We have to execute the `onFailure` callback on the generic pool as well,
not just the `onResponse`, since it blocks on a transport request so I refactored the listener accordingly.

closes #67106

### CODE REVIEW

File: x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/repository/CcrRepository.java [hunk 1]
```diff
@@ -556,21 +556,38 @@ protected FileChunk nextChunkRequest(StoreFileMetadata md) {
...
+                                        }
+                                    });
+                                }
+
+                                @Override
+                                public void onFailure(Exception e) {
+                                    threadPool.generic().execute(() -> {
+                                        try {
+                                            listener.onFailure(e);
+                                        } catch (Exception ex) {
```
Comment (original-brownbear) [inline x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/repository/CcrRepository.java:583]: This whole thing is kind of verbose but since we need to fork-off after incrementing the ref there wasn't a nice way of doing this via `ThreadedActionListener` and this recreates the old behavior of that class pretty much exactly and with a more meaningful log message.
(we definitely have to catch here, the callback does blocking transport requests that will fail at some rate)

Comment (original-brownbear) [reply x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/repository/CcrRepository.java:583]: This was originally broken here: https://github.com/elastic/elasticsearch/pull/65921/files#diff-99f9df7f4e940afb7f2885ff7fddebe882f88345db74519a06744b019afab8b7R559

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Tanguy!
