### PR TITLE
ESQL: Avoid unintended attribute removal

### LINKED ISSUE #127468: ES|QL: Grok only supports KEYWORD or TEXT values, found expression [type] type [INTEGER]
With CSV dataset

```
from multivalue_points,h*,messa* 
| eval  `card` = true, PbehoQUqKSF = "VLGjhcgNkQiEVyCLo", DsxMWtGL = true, qSxTIvUorMim = true, `location` = 8593178066470220111, type = -446161601, FSkGQkgmS = false 
| eval  PbehoQUqKSF = 753987034, HLNMQfQj = true, `within` = true, `id` = "JDKKkYwhhh", lk = null, aecuvjTkgZza = 510616700, aDAMpuVtNX = null, qCopgNZPt = "AjhJUtZefqKdJYH", BxHHlFoA = "isBrmhKLc"
| rename message as message 
| lookup join message_types_lookup on message 
| sort PbehoQUqKSF DESC, ip1 DESC NULLS LAST 
| limit 5845 
| drop `subset`, ip*, `card`, `within`, host.v*, description, `aecuvjTkgZza`, host.version, `ip0`, height_range, DsxMWtGL, host_group, `aDAMpuVtNX`, PbehoQUqKSF, `intersects`, `host.os`, aDAMpuVtNX, *ight_range, HLNMQfQj, `FSkGQkgmS`, BxHHlFoA, card 
| grok type "%{WORD:GknCxQFo}" 
| eval  `location` = null, ZjWUUvGusyyz = null, HeeKIpzgh = false, `id` = 4325287503714500302, host = false, `lk` = null, HvTQdOqFajpH = false, fKNlsYoT = true, `location` = -1158449473, `qCopgNZPt` = 1219986202615280617 
| drop HeeKIpzg*, `ZjWUUvGusyyz`, `message`, `type`, `lk` 
| grok GknCxQFo "%{WORD:location} %{WORD:HvTQdOqFajpH}" 
| drop HvTQdOqFajpH, `location`, centroid 
| mv_expand GknCxQFo 
| limit 410 
| limit 3815 
| rename `id` AS `GknCxQFo` 
| grok host.name "%{WORD:oGQQZHxQHj} %{WORD:qCopgNZPt} %{WORD:vHKOmmocPcTO}" 
| stats  BkQXJRMeAM = min(GknCxQFo) 
| keep `BkQXJRMeAM`
```

```
verification_exceptionreason
Found 1 problem |
line 1:787: Grok only supports KEYWORD or TEXT values, found expression [type] type [INTEGER]
```

### PR DESCRIPTION
**Pull request by kanoshiou**
Because we aim to minimize the number of attributes required from `field_caps` at pre-analysis time, a removal check helps eliminate fields defined by users (such as `eval`). However, commands like `lookup join` and `enrich` can introduce fields with the same names as user-defined fields. To accommodate this, we ensure that aliases are not removed from the attributes list when a subsequent `JOIN` occurs.

For the query:
```
from message_types 
| eval type = 1 
| lookup join message_types_lookup on message 
| drop  message 
| grok type "%{WORD:b}" 
| stats x = max(b) 
| keep x
```

The plan `grok type "%{WORD:b}` passes the removal check and initiates alias removal down the tree. However, the removal process should halt at `lookup join` due to the reason mentioned above. The issue arises because the original code allows progression to `eval type = 1`, which inadvertently removes the `type` field. As a result, the field `type` ends up being of type `integer` defined by `eval type = 1`, rather than preserving the `keyword` type field `type` obtained from `message_types_lookup`.

Closes #127468

### CODE REVIEW

**Comment by astefan** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
I'm really confused. I can get a result of `4325287503714500000` when I run the query on my local machine, but the test says it should be `4325287503714500302`. It seems the test result is right, I will update the branch.

**Review by astefan — CHANGES_REQUESTED** [review]
@kanoshiou I really appreciate you provided this PR and you tried to understand where the fix needs to go.

Unfortunately, this is a trivial fix that doesn't quite catch the true reason for the initial failure.

The essence of the failure is the fact that `lookup join` can override the `type` user-provided field with its own `type` field. The `type` from `eval` is of type `integer` while the `type` that comes from the `lookup join` is of type `keyword`. Because the list of field names didn't contain `type` the Analyzer couldn't learn about that `type` that exists in `message_types_lookup` and the only thing it knew about its type is that it comes from `eval`.

`lookup join` (like `enrich` and maybe `inlinestats`) are special in the sense that they add some columns to the result, so some of the rules we have in `EsqlSession.fieldNames` need to be adjusted to account for these special characteristics. Because `lookup join` can add a field of the same name as `type` coming from an `eval` **before** the said lookup join command, we have [a special check in `fieldNames` that forbids the removal of those `Alias`es](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java#L660-L674).

Your proposed solution does this:
- places the input references of grok in a new variable, instead of the `referenceBuilder` that was used before
- the special check above for lookup join is not applied to `referenceBuilder` for `grok` because the input reference is not there anymore
- you add to `referenceBuilder` the content of the grok-special variable

This is a bypass of the `lookup join` special removal check.

Instead, let the `grok` references in `referenceBuilder` where they are and don't let the special `lookup join` check remove it. The issue is with the `lookup join` check, not with `grok`, so adjust that one. I have the feeling that check is applicable in other cases, only that we didn't catch those yet.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java [hunk 1]
```diff
@@ -1341,6 +1341,18 @@ public void testDissectOverwriteName() {
         assertThat(fieldNames, equalTo(Set.of("emp_no", "emp_no.*", "first_name", "first_name.*")));
     }
 
+    public void testAvoidGrokAttributesRemoval() {
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:1344]: This one will need the lookup capability. Search for that one in tests here in this class and add it to this test as well.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/dissect.csv-spec [hunk 2]
```diff
@@ -331,3 +331,19 @@ ROW a="b c d x"| DISSECT a "%{b} %{} %{d} %{}";
...
+| lookup join message_types_lookup on message 
+| drop message 
+| dissect type "%{b}" 
+| stats x = max(b) 
+| keep x
+;
+
+x:keyword
+Success
+;
```
Comment (astefan) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/dissect.csv-spec:349]: Add one more tests here, please. It's slightly more convoluted and uses multiple lookup join commands:

```
FROM sample_data, employees
| EVAL client_ip = client_ip::keyword
| RENAME languages AS language_code
| LOOKUP JOIN clientips_lookup ON client_ip
| EVAL type = 1::keyword
| EVAL type = 2
| LOOKUP JOIN message_types_lookup ON message
| LOOKUP JOIN languages_lookup ON language_code
| DISSECT type "%{type_as_text}"
| KEEP message
| WHERE message IS NOT NULL
| SORT message DESC
| LIMIT 1
```

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java [hunk 3]
```diff
@@ -1341,6 +1341,18 @@ public void testDissectOverwriteName() {
         assertThat(fieldNames, equalTo(Set.of("emp_no", "emp_no.*", "first_name", "first_name.*")));
     }
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/session/IndexResolverFieldNamesTests.java:1343]: Here add, also, the test that I mentioned for dissect.csv-spec:

```
FROM sample_data, employees
| EVAL client_ip = client_ip::keyword
| RENAME languages AS language_code
| LOOKUP JOIN clientips_lookup ON client_ip
| EVAL type = 1::keyword
| EVAL type = 2
| LOOKUP JOIN message_types_lookup ON message
| LOOKUP JOIN languages_lookup ON language_code
| DISSECT type "%{type_as_text}"
| KEEP message
| WHERE message IS NOT NULL
| SORT message DESC
| LIMIT 1
```

**Comment by astefan** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
Thank you for your review and suggestions, @astefan!

I believe the statement `p.anyMatch(c -> couldOverrideAliases(c))` will always return true since there must be an `UnresolvedRelation` at the end. If we disregard the `UnresolvedRelation` case, I believe your code essentially avoids alias removal whenever there is a `lookup join` or `enrich` operation in the tree. However, this contradicts the original intent of minimizing the number of attributes required from `field_caps` at pre-analysis time.

**Comment by astefan** [comment]
buildkite test this

**Comment by astefan** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
@astefan The original code goes down each expression to remove aliases when the current plan passes the removal check. However, we cannot determine whether the aliases were defined before `lookup join`. 

To address this, my solution is:
- Go down each plan instead of each expression
- Check whether the plan can override aliases
  - If it can, stop removing further aliases
  - If it cannot, remove aliases and proceed to the next plan

I believe this solution is well-optimized and should prevent any future issues caused by alias removal check, since no more aliases before `lookup join` can execute this removal logic.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java [hunk 4]
```diff
@@ -667,13 +667,22 @@ static PreAnalysisResult fieldNames(LogicalPlan parsed, Set<String> enrichPolicy
...
                 AttributeSet planRefs = p.references();
                 Set<String> fieldNames = planRefs.names();
-                p.forEachExpressionDown(Alias.class, alias -> {
-                    // do not remove the UnresolvedAttribute that has the same name as its alias, ie "rename id AS id"
-                    // or the UnresolvedAttributes that are used in Functions that have aliases "STATS id = MAX(id)"
-                    if (fieldNames.contains(alias.name())) {
-                        return;
+                canRemoveAliases[1] = true;
+                // go down each plan and remove aliases until we meet a plan that can override aliases
+                p.forEachDown(c -> {
```
[the remark this answers is not in the document]
Comment (kanoshiou) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/EsqlSession.java:672]: I'm happy to make the change, please give me a moment.

**Comment by kanoshiou** [comment]
Thank you for your review @astefan! Your suggestion has been applied in [ee9de1c](https://github.com/elastic/elasticsearch/pull/127563/commits/ee9de1c6197dd15b953083430b00c704e634289c).

**Review by astefan — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
@kanoshiou please, look into the conflicts. Most likely, they are coming from the freshly merged PR.

**Comment by kanoshiou** [comment]
@astefan conflicts resolved.

**Comment by astefan** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
Thank you @astefan!
