### PR TITLE
Retry batch-delete items in GCS

### LINKED ISSUE #138364: [CI] GCSRepositoryAnalysisRestIT testRepositoryAnalysis failing
**Build Scans:**
- [elasticsearch-periodic #11531 / third-party_gcs](https://gradle-enterprise.elastic.co/s/epfewketa2grm)
- [elasticsearch-periodic #11514 / third-party_gcs](https://gradle-enterprise.elastic.co/s/dbk33xra4qbm2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:snapshot-repo-test-kit:qa:gcs:javaRestTest" --tests "org.elasticsearch.repositories.blobstore.testkit.analyze.GCSRepositoryAnalysisRestIT.testRepositoryAnalysis" -Dtests.seed=4BCB53930B668105 -Dtests.locale=en-US -Dtests.timezone=Africa/Nairobi -Druntime.java=25
```

**Applicable branches:**
9.2

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.blobstore.testkit.analyze.GCSRepositoryAnalysisRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRepositoryAnalysis'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:41629], URI [/_snapshot/repository/_analyze?blob_count=10&seed=-3385924099031504602&max_blob_size=1mb&timeout=120s&concurrency=4], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[repository] Elasticsearch observed the storage system underneath this repository behaved incorrectly which indicates it is not suitable for use with Elasticsearch snapshots. See [https://www.elastic.co/docs/api/doc/elasticsearch/v9/operation/operation-snapshot-repository-analyze?version=9.2] for further information. Elasticsearch attempted to remove the data it wrote at [temp-analysis-l0fR2l3HS92L6XpH4kA4gg] but may have left some behind. If so, please now remove this data manually."}],"type":"repository_verification_exception","reason":"[repository] Elasticsearch observed the storage system underneath this repository behaved incorrectly which indicates i
[truncated]
```

**Issue Reasons:**
- [9.2] 2 failures in test testRepositoryAnalysis (1.7% fail rate in 119 executions)
- [9.2] 2 failures in step third-party_gcs (40.0% fail rate in 5 executions)
- [9.2] 2 failures in pipeline elasticsearch-periodic (40.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mhl-b**
Add retry logic for batch-delete items in GCS blob store. Algorithm
maximizes the size of every batch by merging retryable items from the
previous batch and new items. When batch results have failed items, we
first retry only a single item using the SDK client's retry strategy
(exponential-backoff). Retrying a single item should provide enough
time to back-off from throttling or temporary GCS failures. Once a
single item successfully retries, we proceed with the next batch,
combining the remaining failures and new items.

Roughly this:
- create batch of 100 new items
- submit batch
- receive 100 results, with 10 retryable failures
- retry 1 failure using non-batched delete using SDK retry strategy
- (loop) create batch from 9 remaining failures and 91 new items

Also extend test fixture to randomly fail individual items in batch.

fix https://github.com/elastic/elasticsearch/issues/138364

### CODE REVIEW

**Comment by mhl-b** [comment]
@DaveCTurner, @joshua-adams-1
 Using draft to align on the approach how to retry bulk items.

**Comment by mhl-b** [comment]
@nicktindall, I didn't have chance to review GCS retry refactoring PR. But want to verify that we still keep retry strategy for non stream calls.

**Comment by nicktindall** [comment]
> @nicktindall, I didn't have chance to review GCS retry refactoring PR. But want to verify that we still keep retry strategy for non stream calls.

Yes, only get blob should be affected by my changes

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java [hunk 1]
```diff
@@ -763,6 +672,91 @@ OptionalBytesReference compareAndExchangeRegister(
         }
     }
 
+    private static boolean isRetryErrCode(int code) {
+        return switch (code) {
+            case 408 | 429 | 500 | 502 | 503 | 504 -> true;
```
Comment (joshua-adams-1) [inline modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: 1. Can we replace these raw values with `HttpURLConnection` like [here](https://github.com/elastic/elasticsearch/blob/f9575563459aa257c1e0cfc24ce933d40a75e90a/x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/esnative/tool/SetupPasswordToolTests.java#L279)
2. Is it worth explaining why we can retry on this?

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java [hunk 2]
```diff
@@ -763,6 +672,91 @@ OptionalBytesReference compareAndExchangeRegister(
...
+                }
+            }
+            batchResults.clear();
+
+            // using GCS client's retry logic to delete single item,
+            // once single item can go through we can retry batch again
+            if (failedItems.isEmpty() == false) {
+                final var retryBlobId = failedItems.getLast().blobId;
+                try {
+                    client().deleteBlob(retryBlobId);
```
Comment (joshua-adams-1) [inline modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: Two questions:
1. I assume this blocks?
2. Does `storage.delete(blobId);` use an exponential back off retry strategy?

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java [hunk 3]
```diff
@@ -763,6 +672,91 @@ OptionalBytesReference compareAndExchangeRegister(
...
+                    // remaining items go the next bulk
+                    failedItems.removeLast();
+                } catch (StorageException e) {
+                    throw new IOException(
```
Comment (joshua-adams-1) [inline modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java:793]: Can we also log the other elements in `failedItems`? Otherwise they would fail quietly

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java [hunk 4]
```diff
@@ -763,6 +672,91 @@ OptionalBytesReference compareAndExchangeRegister(
...
+            }
+            batchResults.clear();
+
+            // using GCS client's retry logic to delete single item,
+            // once single item can go through we can retry batch again
+            if (failedItems.isEmpty() == false) {
+                final var retryBlobId = failedItems.getLast().blobId;
+                try {
+                    client().deleteBlob(retryBlobId);
+                    // remaining items go the next bulk
```
Comment (joshua-adams-1) [inline modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]:
```suggestion
                    // remaining items go into the next bulk
```

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java [hunk 5]
```diff
@@ -763,6 +672,91 @@ OptionalBytesReference compareAndExchangeRegister(
...
+            batch.submit();
+            for (var deleteResult : batchResults) {
+                try {
+                    final var ignored = deleteResult.result.get();
+                } catch (StorageException e) {
+                    final var errCode = e.getCode();
+                    if (isRetryErrCode(errCode)) {
+                        failedItems.add(new DeleteFailure(deleteResult.blobId, e.getCode()));
+                    } else {
+                        throw new IOException("Failed to process bulk delete, non-retryable error for blobId=" + deleteResult.blobId, e);
```
Comment (joshua-adams-1) [inline modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: General question: If we fail to delete N blobs, are these subsequently cleaned up?

**Review by joshua-adams-1 — COMMENTED** [review]
After reading https://github.com/elastic/elasticsearch/issues/138364 this looks good to me. I'm happy to approve once the CI issues are resolved. Could we also add unit tests for the `deleteBlobs` function?

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java (hunk 1 above)
Comment (DaveCTurner) [reply modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: I'd rather we used the names in `org.elasticsearch.rest.RestStatus` but yes names >> numbers here, and if there's any docs about why we should retry these codes then it'd be great to link them in a comment.

**Review by DaveCTurner — COMMENTED** [review]
Looks sensible to me, but needs supporting changes in `GoogleCloudStorageHttpHandler` to exercise the retries properly.

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java (hunk 1 above)
Comment (mhl-b) [reply modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: Done https://github.com/elastic/elasticsearch/pull/138951/changes#diff-56e89befa62de07551e01d35a1c0d3018ac0b49d6476af5c7bd38fd81f56181bR703-R709

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java (hunk 2 above)
Comment (mhl-b) [reply modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: Yes and yes

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java (hunk 3 above)
Comment (mhl-b) [reply modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java:793]: Added list of failed items and their status codes. https://github.com/elastic/elasticsearch/pull/138951/changes#diff-56e89befa62de07551e01d35a1c0d3018ac0b49d6476af5c7bd38fd81f56181bR780

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java (hunk 5 above)
Comment (mhl-b) [reply modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: I think so, there is a cleanup of dangling blobs occasionally. But don't know exactly.

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java [hunk 6]
```diff
@@ -767,6 +700,99 @@ OptionalBytesReference compareAndExchangeRegister(
...
+            }
+            for (var deleteResult : batchResults) {
+                try {
+                    deleteResult.result.get();
+                } catch (StorageException e) {
+                    final var errCode = e.getCode();
+                    if (isRetryErrCode(errCode)) {
+                        batchFailures.add(new DeleteFailure(deleteResult.blobId, e.getCode()));
+                    } else {
+                        throw new IOException("Failed to process batch delete, non-retryable error for blobId=" + deleteResult.blobId, e);
```
Comment (nicktindall) [inline modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: Is it worth accumulating all (within some limit, or summarised sensibly) of the failures in the current batch? Or are we happy to assume if they're there, they'll most likely be for the same reason?

File: test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java [hunk 7]
```diff
@@ -264,6 +285,98 @@ private void writeBlobVersionAsJson(HttpExchange exchange, MockGcsBlobStore.Blob
...
+            final var errorObj = """
+                {
+                  "error" : {
+                    "code": $code
+                  }
+                }
+                """.replace("$code", Integer.toString(itemStatus.getStatus()));
+            responseText
+                // SDK client will try to parse error as JSON despite these headers. Adding them for HTTP spec consistency.
+                .append("content-type: application/json")
```
Comment (nicktindall) [inline test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java]: > SDK client will try to parse error as JSON despite these headers. Adding them for HTTP spec consistency.

Do you mean the SDK will parse the response as JSON even without these headers? despite makes it sound like the content type indicates it's something other than JSON

**Review by nicktindall — APPROVED** [review]
LGTM

File: test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java (hunk 7 above)
Comment (mhl-b) [reply test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java]: > Do you mean the SDK will parse the response as JSON even without these headers?

Yes, as far as I can trace GCS code there is no check for the content type, it goes straight to JSON parsing. Having these headers does not hurt, if GCS at some point decides to be strict on part headers this code will continue to work.

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java (hunk 6 above)
Comment (mhl-b) [reply modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java]: Sure, I will collect all errors, they already sit in memory.

File: test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java (hunk 7 above)
Comment (mhl-b) [reply test/fixtures/gcs-fixture/src/main/java/fixture/gcs/GoogleCloudStorageHttpHandler.java]: I removed this comment line to avoid confusion. There is nothing to worry about.

**Comment by mhl-b** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/141066)|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/141067)|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/141068)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
