### PR TITLE
[ML] Do not fail DFA task when it's stopped whilst reindexing

### LINKED ISSUE #55068: Timeout in RunDataFrameAnalyticsIT#testOutlierDetectionStopAndRestart with ml integration tests
A number of failures have arisen lately ([since Apr 4 2020 on master](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-2y,mode:quick,to:now))&_a=(columns:!(branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%22org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT%22%20AND%20test:%22testOutlierDetectionStopAndRestart%22%20AND%20branch:master'),sort:!(time,desc)))):

oraclelinux-7: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux-7&&immutable/685/console / https://gradle-enterprise.elastic.co/s/vy7fun2blav4w

centos-8: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos-8&&immutable/685/console / https://gradle-enterprise.elastic.co/s/z2lub544emry6

All of them seem to be failing due to the suite timing out (after `20m`):

```
org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT > testOutlierDetectionStopAndRestart FAILED |  
  | java.lang.Exception: Test abandoned because suite timeout was reached. |  
  | at __randomizedtesting.SeedInfo.seed([591EC3B588EE3AFB]:0) |  
  | REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionStopAndRestart" -Dtests.seed=591EC3B588EE3AFB -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=Europe/Moscow -Dcompiler.java=14 |
```

Reproduction line:

`/gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testOutlierDetectionStopAndRestart" -Dtests.seed=591EC3B588EE3AFB -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=Europe/Moscow -Dcompiler.java=14`

I couldn't reproduce it locally.

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Adding to #55659, we missed another way we could set the task to
failed due to task cancellation. CI revealed that we might also
get a `SearchPhaseExecutionException` whose cause is a
`TaskCancelledException`. That exception is not wrapped so
unwrapping it will not return the underlying `TaskCancelledException`.
Thus to be complete in catching this, we also need to check the
error's cause.

Closes #55068

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DataFrameAnalyticsManager.java [hunk 1]
```diff
@@ -294,6 +294,10 @@ private void reindexDataframeAndStartAnalysis(DataFrameAnalyticsTask task, DataF
                 new GetIndexRequest().indices(config.getDest().getIndex()), destIndexListener);
     }
 
+    private boolean isTaskCancelledException(Exception error) {
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DataFrameAnalyticsManager.java:297]: static

**Review by przemekwitek — APPROVED** [review]
LGTM with one small comment

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DataFrameAnalyticsManager.java [hunk 2]
```diff
@@ -294,6 +294,10 @@ private void reindexDataframeAndStartAnalysis(DataFrameAnalyticsTask task, DataF
...
+        return ExceptionsHelper.unwrapCause(error) instanceof TaskCancelledException || error.getCause() instanceof TaskCancelledException;
```
Comment (droberts195) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DataFrameAnalyticsManager.java:298]: I wonder if it's also worth unwrapping the cause?

```suggestion
        return ExceptionsHelper.unwrapCause(error) instanceof TaskCancelledException || ExceptionsHelper.unwrapCause(error.getCause()) instanceof TaskCancelledException;
```

Whether this is worth it or not depending on whether the nested exception could be a remote transport exception, or whether only the outermost exception can be.  If you don't know the answer it's probably better to add the extra unwrap call.

Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/DataFrameAnalyticsManager.java:298]: Good point. I'll do that.
