### PR TITLE
Fix block checks when no indices are specified

### LINKED ISSUE #8105: Indices exists returns false during recovery
I have a problem with the embedded Java client (for testing) after moving our [our Java integration library](https://github.com/molindo/esi4j) from 1.0 to 1.4.0.Beta. We use the Java client embedded. 

During application restart, we check if an index exists and create or update it. Now we have the problem, that [indices exists](http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.4/indices-exists.html) returns false, causing [create index](http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.4/indices-create-index.html) to fail.

I tried IRC for a solution but @karmi thought it's supposedly a bug.

(test case to follow)

### PR DESCRIPTION
**Pull request by ywelsch**
Global cluster blocks were not checked if an empty set of indices were passed as argument to the block checking method.

Closes #8105

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/action/admin/indices/exists/ExistsIndexBlocksIT.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+@ClusterScope(scope = ESIntegTestCase.Scope.TEST, numDataNodes = 0, numClientNodes = 0, transportClientRatio = 0.0)
+public class ExistsIndexBlocksIT extends ESIntegTestCase {
+
+    public void testIndexExistsWithBlocksInPlace() throws IOException {
+        Settings settings = Settings.builder().put(GatewayService.RECOVER_AFTER_NODES_SETTING.getKey(), 99).build();
+        String node = internalCluster().startNode(settings);
+
+        assertThrows(client(node).admin().indices().prepareExists("test").setMasterNodeTimeout(TimeValue.timeValueSeconds(0)),
+            MasterNotDiscoveredException.class);
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/admin/indices/exists/ExistsIndexBlocksIT.java]: why does this throw a master no discovered? we should have master, but our state is not recovered.. I think more is going on here.

Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/action/admin/indices/exists/ExistsIndexBlocksIT.java]: MasterNotDiscoveredException is what we throw when we time out. The ClusterBlockException is wrapped by the MasterNotDiscoveredException (which is what we throw when we have retryable block)

Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/admin/indices/exists/ExistsIndexBlocksIT.java]: hmm. I think we should throw the original failure? like we do in other places?

Comment (ywelsch) [inline core/src/test/java/org/elasticsearch/action/admin/indices/exists/ExistsIndexBlocksIT.java]: sure, that's another change though (another PR).

Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/admin/indices/exists/ExistsIndexBlocksIT.java]: fair enough

**Comment by bleskes** [comment]
change LGTM, but I think we should testing on a different level. We should have unit tests on ClusterBlocks

File: core/src/test/java/org/elasticsearch/action/admin/indices/exists/ExistsIndexBlocksIT.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+import org.elasticsearch.test.ESIntegTestCase;
+import org.elasticsearch.test.ESIntegTestCase.ClusterScope;
+import org.elasticsearch.test.InternalTestCluster;
+
+import java.io.IOException;
+
+import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertThrows;
+
+@ClusterScope(scope = ESIntegTestCase.Scope.TEST, numDataNodes = 0, numClientNodes = 0, transportClientRatio = 0.0)
+public class ExistsIndexBlocksIT extends ESIntegTestCase {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/action/admin/indices/exists/ExistsIndexBlocksIT.java]: can this IndicesExistsIT ? will be easier to find because it's the name of the action

**Comment by ywelsch** [comment]
@bleskes thanks for the review. I've added a unit test.

**Comment by bleskes** [comment]
LGTM. Thx @ywelsch
