### PR TITLE
Validate settings specified in index templates at template creation time

### LINKED ISSUE #12865: Template allows creation of index with 0 primary shards
If you create a template with `number_of_shards` set to 0, then it accepts it and the eventual index fails. Attempted in ES 1.7.1. (If you try to do this directly with the index, then it will appropriately block the attempt.)

```http
# Create the template
PUT /_template/test_shards
{
  "template": "test_shards*",
  "settings": {
    "number_of_shards" : 0
  }
}

# Create the index
PUT /test_shards
```

Once created, the cluster is in a red state because no primaries are allocated, which is kind of odd on its own because no primaries are missing.

```http
DELETE /test_shards
```

When trying to delete the index, an exception is logged:

```
[2015-08-13 18:49:11,042][WARN ][cluster.action.index     ] [WallE] [test_shards]failed to ack index store deleted for index
java.lang.IllegalArgumentException: settings must contain a non-null > 0 number of shards
    at org.elasticsearch.env.NodeEnvironment.lockAllForIndex(NodeEnvironment.java:445)
    at org.elasticsearch.indices.IndicesService.processPendingDeletes(IndicesService.java:733)
    at org.elasticsearch.cluster.action.index.NodeIndexDeletedAction.lockIndexAndAck(NodeIndexDeletedAction.java:125)
    at org.elasticsearch.cluster.action.index.NodeIndexDeletedAction.access$500(NodeIndexDeletedAction.java:49)
    at org.elasticsearch.cluster.action.index.NodeIndexDeletedAction$1.doRun(NodeIndexDeletedAction.java:94)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

However, after an usually long delay, it eventually responds with success. Looking on disk, the index's directory still exists, but it is appropriately empty.

### Workaround

You can fix the issue by updating the template to fix the issue, creating the index, and then deleting it. (You can also just specify the `number_of_shards` directly at index time to override them template, but fixing the template is the appropriate fix if you run into this issue!)

```http
# Recreate the index
PUT /test_shards
{
  "settings" : {
    "number_of_shards" : 1
  }
}

# Clean it up
DELETE /test_shards
```

This will appropriately cleanup the directory.

### PR DESCRIPTION
**Pull request by jasontedor**
Previously settings specified in index templates were not validated upon
template creation. Creating an index from an index template with invalid
settings could lead to cluster stability issues because creation of such
indexes would bypass index settings validation.

This commit adds validation of settings specified in index templates at
template creation time. This works by routing the index template
settings through the index settings validation mechanism.

Closes #12865

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/action/admin/indices/template/put/MetaDataIndexTemplateServiceTests.java [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+import org.elasticsearch.indices.InvalidIndexTemplateException;
+import org.elasticsearch.test.ESIntegTestCase;
+import org.elasticsearch.test.ESTestCase;
+import org.junit.Test;
+
+import java.io.IOException;
+import java.util.List;
+import java.util.Map;
+
+@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST)
```
Comment (dakrone) [inline core/src/test/java/org/elasticsearch/action/admin/indices/template/put/MetaDataIndexTemplateServiceTests.java]: I don't think we really need scope for this test since it's a unit test?

**Comment by dakrone** [comment]
Generally this looks good to me, but I wonder if we should move towards the validation style that the `*Request` classes use, where they create an `ActionRequestValidationException` and use `validationException = addValidationError("<message>", validationException)` multiple times to collect multiple validations at once?

File: core/src/test/java/org/elasticsearch/action/admin/indices/template/put/MetaDataIndexTemplateServiceTests.java (hunk 1 above)
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/action/admin/indices/template/put/MetaDataIndexTemplateServiceTests.java]: Oh, yeah, that's just left over because my initial implementation of the test was as an integration test and I didn't remove it when I rewrote it as a unit test.

**Comment by jasontedor** [comment]
@dakrone Completely agree, I but will address that in a [separate issue](https://github.com/elastic/elasticsearch/issues/12900).
