### PR TITLE
Security: fix dynamic mapping updates with aliases

### LINKED ISSUE #30597: Authorization failure when indexing document with new mappings to alias.
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4

**Description of the problem including expected versus actual behavior**:

If a user is allowed to write to an alias, but not its concrete index, then indexing a document with new mappings can produce the following authorization exception:
 ```
 {
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "action [indices:admin/mapping/put] is unauthorized for user [test_user]"
      }
    ],
    "type" : "security_exception",
    "reason" : "action [indices:admin/mapping/put] is unauthorized for user [test_user]"
  },
  "status" : 403
}
```

This behavior is confusing, because `write` permissions should allow for both indexing and updating mappings, and the user can successfully make a put mapping request directly.

Note that if the user is also given `write` privileges to the underlying index, then attempting to index the document succeeds. This fact suggests that the implicit `mappings` call during indexing is maybe being validated against the concrete index, instead of the alias.

Related to https://github.com/elastic/elasticsearch/issues/29874.

**Steps to reproduce**:

Gist: https://gist.github.com/jtibshirani/ff8ebcd235dc8be36ecd84543b29525d

### PR DESCRIPTION
**Pull request by jaymode**
This commit fixes an issue with dynamic mapping updates when an index
operation is performed against an alias and when the user only has
permissions to the alias. Dynamic mapping updates resolve the concrete
index early to prevent issues so the information about the alias that
the triggering operation was being executed against is lost. When
security is enabled and a user only has privileges to the alias, this
dynamic mapping update would be rejected as it is executing against the
concrete index and not the alias. In order to handle this situation,
the security code needs to look at the concrete index and the
authorized indices of the user; if the concrete index is not authorized
the code will attempt to find an alias that the user has permissions to
update the mappings of.

Closes #30597

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java [hunk 1]
```diff
@@ -213,7 +217,48 @@ ResolvedIndices resolveIndicesAndAliases(IndicesRequest indicesRequest, MetaData
...
+        final String concreteIndexName = request.getConcreteIndex().getName();
+        final List<String> authorizedIndicesList = authorizedIndices.get();
+
+        // validate that the concrete index exists, otherwise there is no remapping that we could do
+        final AliasOrIndex aliasOrIndex = metaData.getAliasAndIndexLookup().get(concreteIndexName);
+        final String resolvedAliasOrIndex;
+        if (aliasOrIndex == null) {
+            resolvedAliasOrIndex = concreteIndexName;
+        } else if (aliasOrIndex.isAlias()) {
+            throw new IllegalStateException("concrete index should never be an alias!");
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/IndicesAndAliasesResolver.java]: Can we provide more details in this message (e.g. the name of the index/alias)

**Review by tvernum — APPROVED** [review]
LGTM
