### PR TITLE
Bind on localhost only when no site addresses

### LINKED ISSUE #80923: Elasticsearch fails to start when not connected to local network
With security enabled by default, we changed our default to bind to both `_local` and `_site_` when we go through with the security autoconfiguration setup. It makes sense to do so as elasticsearch has authentication and TLS on the HTTP layer enabled and we wanted to allow maximum connectivity as kibana or other clients could run on different hosts. 

The issue with setting `http.host: ["_local_", "_site_"]` is that when there is no site-local address (i.e. host is disconnected from local networks ), elasticsearch would fail to start with a message similar to 
```
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:br-72896d75edab (br-72896d75edab), name:docker0 (docker0), name:br-9a09ce2f5f7e (br-9a09ce2f5f7e), name:br-b6a5fb9fac6d (br-b6a5fb9fac6d), name:br-c11a9a002c33 (br-c11a9a002c33), name:br-eb3168295388 (br-eb3168295388), name:br-f9dd975f4e4d (br-f9dd975f4e4d)]
```

### PR DESCRIPTION
**Pull request by jkakavas**
This changes the auto-configuration behavior to bind only to
localhost (_local_) and no site-local (_site_) addresses when
we can't discover any site-local addresses in the interfaces we
know of.

Resolves: #80923

### CODE REVIEW

File: x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java [hunk 1]
```diff
@@ -688,6 +690,14 @@ protected void execute(Terminal terminal, OptionSet options, Environment env) th
         Files.deleteIfExists(keystoreBackupPath);
     }
 
+    protected String httpHostSettingValue(InetAddress[] allAddresses) {
```
Comment (jkakavas) [inline x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:693]: There are no tests added but: 

- I don't think we can control the interfaces used in our packaging tests so that we can end up with only local addresses
- A unit test for `AutoConfigureNode#httpHostSettingValue` would basically be a unit test for `InetAddress#isSiteLocalAddress`

Comment (albertzaharovits) [reply x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java:693]: I think this is the best we can do, as you say.
The `NetworkService` doesn't have a public static method to resolve bind addresses of different types, for good reasons, I'm sure.

When we write to the node configuration we rely on the node to interpret the settings in a certain way, and we can't always use the node code that does that, neither we can always test the interaction.

**Review by albertzaharovits — APPROVED** [review]
