### PR TITLE
[Tests] Make testEngineGCDeletesSetting deterministic

### LINKED ISSUE #38874: UpdateSettingsIT#testEngineGCDeletesSetting failure
test failing:

```
org.elasticsearch.indices.settings.UpdateSettingsIT testEngineGCDeletesSetting
```

#38254 introduced a new `VersionConflictEngineException` assertion that seems 
to be dependent on cache invalidation timed by `Thread.sleep`.

exception:

```
java.lang.AssertionError: expected a class org.elasticsearch.index.engine.VersionConflictEngineException exception to be thrown

	at __randomizedtesting.SeedInfo.seed([103812063D7BAB96:96D53E0C3D9BE721]:0)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertThrows(ElasticsearchAssertions.java:596)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertThrows(ElasticsearchAssertions.java:543)
	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertThrows(ElasticsearchAssertions.java:520)
	at org.elasticsearch.indices.settings.UpdateSettingsIT.testEngineGCDeletesSetting(UpdateSettingsIT.java:452)
```

was tough to get a stacktrace, but looks to fail in `InternalEngine#planIndexingAsPrimary`

with the exception:

```[type][1]: version conflict, required seqNo [3], primary term [1]. but no document was found```

ci link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+internalClusterTest/472/console

reproduce:

```
./gradlew :server:integTest \
  -Dtests.seed=EAF25E026AF61CCF \
  -Dtests.class=org.elasticsearch.indices.settings.UpdateSettingsIT \
  -Dtests.method="testEngineGCDeletesSetting" \
  -Dtests.security.manager=true \
  -Dtests.locale=is-IS \
  -Dtests.timezone=Australia/Canberra \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

This is easy to reproduce if one removes the `Thread.sleep(300)`. Which means that
cache hadn't changed in the CI run in time for the assertion.

### PR DESCRIPTION
**Pull request by matriv**
`InternalEngine.resolveDocVersion()` uses `relativeTimeInMillis()` from
`ThreadPool` so it needs, the cached time to be advanced. Add a check
to ensure that and decrease the `thread_pool.estimated_time_interval`
to 1msec to prevent long running times for the test.

Fixes: #38874

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java [hunk 1]
```diff
@@ -126,6 +128,16 @@ public void onIndexModule(IndexModule indexModule) {
         }
     }
 
+    /**
+     * Needed by {@link UpdateSettingsIT#testEngineGCDeletesSetting()}
+     */
+    @Override
+    protected Settings nodeSettings(int nodeOrdinal) {
+        return Settings.builder().put(super.nodeSettings(nodeOrdinal))
+            .put("thread_pool.estimated_time_interval", TimeValue.timeValueMillis(1))
```
Comment (jasontedor) [inline server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: This effectively makes this thread busy spin for this entire test suite. On a machine with a low core count or that is otherwise busy (think how we fork tests across JVMs) it might be too much?

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java [hunk 2]
```diff
@@ -435,23 +447,31 @@ public void testOpenCloseUpdateSettings() throws Exception {
...
+        for (ThreadPool tPool : internalCluster().getInstances(ThreadPool.class)) {
+            long time1 = tPool.relativeTimeInMillis();
+            long time2 = tPool.relativeTimeInMillis();
+            while (time1 == time2) {
+                time2 = tPool.relativeTimeInMillis();
+            }
+        }
+
         // delete is should not be in cache
         assertThrows(client().prepareIndex("test", "type", "1").setSource("f", 3).setIfSeqNo(seqNo).setIfPrimaryTerm(primaryTerm),
```
Comment (jasontedor) [inline server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: Wouldn’t it be enough to assert busy and remove the sleep?

**Review by jasontedor — COMMENTED** [review]
Thanks for diving into this. I left some questions.

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java (hunk 1 above)
Comment (matriv) [reply server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: We can increase it a bit I guess. The reason of changing the setting here, is to avoid adding a public test-only method to force update of cached time, to avoid waiting too much in the while loop.

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java (hunk 2 above)
Comment (matriv) [reply server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: I guess so, this solution just makes more visible of what's happening and less "brute force".

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java (hunk 1 above)
Comment (bleskes) [reply server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: Maybe we can change the logic of the cache - if this is 0, it disables caching.

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java (hunk 2 above)
Comment (bleskes) [reply server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: The goal of the test is to make sure that once time moves the delete is forgotten. If we busy spin on the indexing request (instead of on time - which is what I think Jason refers to with sleep), we will have different semantics as some indexing ops may succeed, changing the dynamics of the test (it now will check that a CASed index operation fails if it's base is an index op, rather than a delete op).

Comment (matriv) [reply server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: ah, yeah. Didn't even think that the assertBusy would potentially execute the prepareIndex request multiple times.

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java (hunk 1 above)
Comment (matriv) [reply server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: @bleskes Something like this: https://github.com/elastic/elasticsearch/pull/38942/commits/7fed99ae0f5f0ba1bda80246718e8f060e3f2e6e ?

File: server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java [hunk 3]
```diff
@@ -550,22 +550,39 @@ public String toString() {
...
          * Return the current time used for relative calculations. This is
          * {@link System#nanoTime()} truncated to milliseconds.
+         * <p>
+         * If {@link ThreadPool#ESTIMATED_TIME_INTERVAL_SETTING} is set to 0
+         * then the cache is disabled and the method calls {@link System#nanoTime()}
+         * whenever called. Typically used for testing.
          */
         long relativeTimeInMillis() {
-            return relativeMillis;
+            if (running) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: I'd slightly prefer

```suggestion
            if (0 < interval) {
```

since this is what the Javadoc says.

File: server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java [hunk 4]
```diff
@@ -550,22 +550,39 @@ public String toString() {
...
          * Return the current epoch time, used to find absolute time. This is
          * a cached version of {@link System#currentTimeMillis()}.
+         * <p>
+         * If {@link ThreadPool#ESTIMATED_TIME_INTERVAL_SETTING} is set to 0
+         * then the cache is disabled and the method calls {@link System#currentTimeMillis()}
+         * whenever called. Typically used for testing.
          */
         long absoluteTimeInMillis() {
-            return absoluteMillis;
+            if (running) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: Similarly, I'd prefer
```suggestion
            if (0 < interval) {
```

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java [hunk 5]
```diff
@@ -435,23 +446,31 @@ public void testOpenCloseUpdateSettings() throws Exception {
...
 
         response = client().prepareDelete("test", "type", "1").get();
         seqNo = response.getSeqNo();
-        Thread.sleep(300); // wait for cache time to change TODO: this needs to be solved better. To be discussed.
+
+        // Make sure the time has advanced for InternalEngine#resolveDocVersion()
+        for (ThreadPool tPool : internalCluster().getInstances(ThreadPool.class)) {
+            long time1 = tPool.relativeTimeInMillis();
+            long time2 = tPool.relativeTimeInMillis();
+            while (time1 == time2) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: I think I'd have written this loop as the following, since there's no need for it to be a tight loop:

    assertBusy(() -> assertThat(tPool.relativeTimeInMillis(), greaterThan(time1)));

It is, admittedly, somewhat of a question of taste.

**Review by DaveCTurner — COMMENTED** [review]
I left some suggestions, but this looks generally good to me.

File: server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java (hunk 3 above)
Comment (matriv) [reply server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: I chose to use the boolean `running` (properly set in the constructor) to avoid the comparison on every call, and it's used in the same way to avoid having a "running" thread that updates those values.

**Comment by matriv** [comment]
@jasontedor @bleskes @DaveCTurner Thank you for the feedback! Please check again.

File: server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: I don't clearly understand why avoiding the comparison is a good thing. Is it a performance question? Are you sure that a comparison between a constant and a `final` field is worse than a second `volatile` read?

Comment (matriv) [reply server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: My thinking was yes the performance, but didn't think about the volatile.
But also to have the logic that when `interval == 0` -> `running = false` so that we avoid having a running thread and we have a common check in all 3 places (the methods and the `run()`).

If you think that the interval check is better, I'll happily change. And if we do that, should the code in the run() change like: `while(running && 0 < interval)` ?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: Yep, sounds like a good idea, thanks.

**Review by DaveCTurner — APPROVED** [review]
LGTM, thanks @matriv

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java (hunk 2 above)
Comment (jasontedor) [reply server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: @bleskes Sorry to be unclear. I meant busy spin waiting for the cached time to advance. So instead of sleeping for it to happen, assert that it has happened, busily since it happens in the background.

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java [hunk 6]
```diff
@@ -435,23 +447,28 @@ public void testOpenCloseUpdateSettings() throws Exception {
...
         client().prepareIndex("test", "type", "1").setSource("f", 2).setIfSeqNo(seqNo).setIfPrimaryTerm(primaryTerm).get();
-        client().admin().indices().prepareUpdateSettings("test").setSettings(Settings.builder().put("index.gc_deletes", 0)).get();
+        assertAcked(client().admin().indices().prepareUpdateSettings("test").setSettings(Settings.builder().put("index.gc_deletes", 0)));
 
         response = client().prepareDelete("test", "type", "1").get();
         seqNo = response.getSeqNo();
-        Thread.sleep(300); // wait for cache time to change TODO: this needs to be solved better. To be discussed.
+
+        // Make sure the time has advanced for InternalEngine#resolveDocVersion()
+        for (ThreadPool tPool : internalCluster().getInstances(ThreadPool.class)) {
```
Comment (jasontedor) [inline server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: Can we please use names consistent with the style in the codebase? For example, this would be `threadPool`.

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java [hunk 7]
```diff
@@ -435,23 +447,28 @@ public void testOpenCloseUpdateSettings() throws Exception {
...
+            long time1 = tPool.relativeTimeInMillis();
```
Comment (jasontedor) [inline server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: Can we use a clearer name than `time1`?

**Review by jasontedor — CHANGES_REQUESTED** [review]
I left some comments.

File: server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java (hunk 2 above)
Comment (matriv) [reply server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java]: @jasontedor You mean this: https://github.com/elastic/elasticsearch/pull/38942/commits/9e8c5310cc8149f0233e480df86910ee963012b7#diff-2f68a8c77a0935a6ec75d0cc4878e86aR466 
as also proposed by @DaveCTurner ?

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by matriv** [comment]
@jasontedor please check again

File: server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java [hunk 8]
```diff
@@ -555,22 +555,36 @@ public String toString() {
         /**
          * Return the current time used for relative calculations. This is
          * {@link System#nanoTime()} truncated to milliseconds.
+         * <p>
+         * If {@link ThreadPool#ESTIMATED_TIME_INTERVAL_SETTING} is set to 0
```
Comment (jasontedor) [inline server/src/main/java/org/elasticsearch/threadpool/ThreadPool.java]: Should we make `ThreadPool#ESTIMATED_TIME_INTERVAL_SETTING` a setting that has `0` as an inclusive lower bound? I am fine with that in a follow up.

**Review by jasontedor — APPROVED** [review]
LGTM.
