### PR TITLE
Speed up terms agg when not force merged

### LINKED ISSUE #71086: [CI] "string profiler via global ordinals native implementation" fails
Build scan: https://gradle-enterprise.elastic.co/s/r2uhjr2wsn6cy

```
 ./gradlew ':qa:smoke-test-multinode:integTest' --tests "org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT" \
-Dtests.method="test {yaml=search.aggregation/20_terms/string profiler via global ordinals native implementation}" \
-Dtests.seed=247343C29CF5B2F2 \
-Dtests.security.manager=true \
-Dtests.locale=fi-FI \
-Dtests.timezone=Asia/Damascus 
```

```
2> java.lang.AssertionError: Failure at [search.aggregation/20_terms:860]: profile.shards.0.aggregations.0.children.0.debug.segments_with_multi_valued_ords didn't match expected value:
    profile.shards.0.aggregations.0.children.0.debug.segments_with_multi_valued_ords: expected Integer [0] but was Integer [1]
```

### PR DESCRIPTION
**Pull request by nik9000**
This speeds up the `terms` aggregation when it can't take the fancy
`filters` path, there is more than one segment, and any of those
segments have only a single value for the field. These three things are
super common.

Here are the performance change numbers:
```
|        50th percentile latency | date-histo-string-terms-via-global-ords | 3414.02 | 2632.01 | -782.015 | ms |
|        90th percentile latency | date-histo-string-terms-via-global-ords | 3470.91 | 2756.88 | -714.031 | ms |
|       100th percentile latency | date-histo-string-terms-via-global-ords | 3620.89 | 2875.79 | -745.102 | ms |
|   50th percentile service time | date-histo-string-terms-via-global-ords | 3410.15 | 2628.87 | -781.275 | ms |
|   90th percentile service time | date-histo-string-terms-via-global-ords | 3467.36 | 2752.43 | -714.933 | ms |   20%!!!!
|  100th percentile service time | date-histo-string-terms-via-global-ords | 3617.71 | 2871.63 | -746.083 | ms |
```

This works by hooking global ordinals into `DocValues.unwrapSingleton`.
Without this you could unwrap singletons *if* the segment's ordinals
aligned exactly with the global ordinals. If they didn't we'd return an
doc values iterator that you can't unwrap. Even if the segment ordinals
were singletons.

That speeds up the terms aggregator because we have a fast path we can
take if we have singletons. It was previously only working if we had a
single segment. Or if the segment's ordinals lined up exactly. Which,
for low cardinality fields is fairly common. So they might not benefit
from this quite as much as high cardinality fields.

Closes #71086

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/fielddata/ordinals/GlobalOrdinalsIndexFieldData.java [hunk 1]
```diff
@@ -219,6 +221,25 @@ public SortedSetDocValues getOrdinalsValues() {
...
+                     * returns `int` instead of `long`
+                     */
+                    if (ordinalMap.getValueCount() < Integer.MAX_VALUE) {
+                        SortedDocValues singleton = DocValues.unwrapSingleton(values);
+                        if (singleton != null) {
+                            return DocValues.singleton(
+                                new SingletonGlobalOrdinalMapping(ordinalMap, singleton, atomicLookups, context.ord)
+                            );
+                        }
+                    }
```
Comment (imotov) [inline server/src/main/java/org/elasticsearch/index/fielddata/ordinals/GlobalOrdinalsIndexFieldData.java:242]: This feels a bit brittle. Basically, SingletonGlobalOrdinalMapping seems to be a very specialized class that can only function if its constructor parameters satisfy these very specific criteria that are neither documented nor enforced in the class itself. I wonder if we could make this less brittle if we made SingletonGlobalOrdinalMapping constructor private and moved the logic and comment above into a factory method that would return null in case the conditions are not satisfied.

**Review by imotov — COMMENTED** [review]
Looks reasonable to me in general, but I think @not-napoleon should review it as well since he is much more familiar with this code.

File: server/src/main/java/org/elasticsearch/index/fielddata/ordinals/GlobalOrdinalsIndexFieldData.java (hunk 1 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/index/fielddata/ordinals/GlobalOrdinalsIndexFieldData.java:242]: Yeah. The second test - that you can unwrap - is encoded in the ctor's signature. But the first bit - the value count - that totally should be guarded like you say.

File: server/src/main/java/org/elasticsearch/index/fielddata/ordinals/SingletonGlobalOrdinalMapping.java [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+class SingletonGlobalOrdinalMapping extends SortedDocValues {
+    private final SortedDocValues values;
+    private final OrdinalMap ordinalMap;
+    private final LongValues mapping;
+    private final TermsEnum[] lookups;
+
+    SingletonGlobalOrdinalMapping(OrdinalMap ordinalMap, SortedDocValues values, TermsEnum[] lookups, int segmentIndex) {
+        this.values = values;
+        this.lookups = lookups;
+        this.ordinalMap = ordinalMap;
```
Comment (not-napoleon) [inline server/src/main/java/org/elasticsearch/index/fielddata/ordinals/SingletonGlobalOrdinalMapping.java:31]: I agree with Igor.  At a minimum we should throw here if `ordinalMap.getValueCount() >= MAX_INT`.  I think it's okay if we require callers to pre-check it rather than building a factory method (although a factory method would also be fine), but we shouldn't allow the construction of invalid objects.

File: server/src/test/java/org/elasticsearch/index/fielddata/AbstractStringFieldDataTestCase.java [hunk 3]
```diff
@@ -445,6 +447,35 @@ public void testNestedSorting(MultiValueMode sortMode) throws IOException {
...
     }
 
+    public void testSingleValuedGlobalOrdinals() throws Exception {
+        Document d = new Document();
+        addField(d, "_id", "1");
+        addField(d, "value", "2");
+        writer.addDocument(d);
+
+        d = new Document();
+        addField(d, "_id", "1");
```
Comment (not-napoleon) [inline server/src/test/java/org/elasticsearch/index/fielddata/AbstractStringFieldDataTestCase.java:457]: Should the `_id` value here be 2? or are you intentionally duplicating IDs?

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorTests.java [hunk 4]
```diff
@@ -1377,6 +1382,56 @@ public void testSortingWithNestedAggregations() throws IOException {
...
+        NumberFieldType nFt = new NumberFieldType("n", NumberFieldMapper.NumberType.LONG);
+        KeywordFieldType strFt = new KeywordFieldType("str", true, true, Collections.emptyMap());
+        AggregationBuilder builder = new TermsAggregationBuilder("n").field("n")
+            .subAggregation(new TermsAggregationBuilder("str").field("str"));
+        try (Directory directory = newDirectory()) {
+            RandomIndexWriter iw = new RandomIndexWriter(
+                random(),
+                directory,
+                // Attempt to disable merging.
+                LuceneTestCase.newIndexWriterConfig(random(), new StandardAnalyzer()).setMergePolicy(NoMergePolicy.INSTANCE)
```
Comment (not-napoleon) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorTests.java:1395]: This is handy.  I wouldn't mind a method in `AggregatorTestCase` to get a non-merging(ish) index writer.

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorTests.java [hunk 5]
```diff
@@ -1377,6 +1382,56 @@ public void testSortingWithNestedAggregations() throws IOException {
         }
     }
 
+    public void testManySegmentsStillSingleton() throws IOException {
```
Comment (not-napoleon) [inline server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorTests.java:1385]: I'm a little unhappy that this test doesn't run through `AggregatorTestCase.testCase`, or at least use `AggregatorTestCase.searchAndReduce`.   I think that's because you want to assert on the debug info which we don't currently make easy.  If that's correct, I don't think we need to address it here, but I would like to leave a todo and maybe a ticket.

**Review by not-napoleon — APPROVED** [review]
LGTM overall.  Would like that constructor guard before merging.

File: server/src/test/java/org/elasticsearch/index/fielddata/AbstractStringFieldDataTestCase.java (hunk 3 above)
Comment (nik9000) [reply server/src/test/java/org/elasticsearch/index/fielddata/AbstractStringFieldDataTestCase.java:457]: It should be 2, yeah.

File: server/src/main/java/org/elasticsearch/index/fielddata/ordinals/SingletonGlobalOrdinalMapping.java (hunk 2 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/index/fielddata/ordinals/SingletonGlobalOrdinalMapping.java:58]: Done!

File: server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorTests.java (hunk 5 above)
Comment (nik9000) [reply server/src/test/java/org/elasticsearch/search/aggregations/bucket/terms/TermsAggregatorTests.java:1387]: Done!

**Comment by nik9000** [comment]
@imotov do you want to have another look at this one?

**Review by imotov — APPROVED** [review]
LGTM. Thanks!

**Comment by nik9000** [comment]
Thanks for all the reviews!
