### PR TITLE
FetchFieldsPhase needs to use local docid, not global

### LINKED ISSUE #90881: [CI] SizeMappingIT testGetWithFields failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/efva2osgphkle/tests/:plugins:mapper-size:internalClusterTest/org.elasticsearch.index.mapper.size.SizeMappingIT/testGetWithFields

**Reproduction line:**
`./gradlew ':plugins:mapper-size:internalClusterTest' --tests "org.elasticsearch.index.mapper.size.SizeMappingIT.testGetWithFields" -Dtests.seed=FA954CBDA791C93D -Dtests.locale=en-GB -Dtests.timezone=Canada/Saskatchewan -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.mapper.size.SizeMappingIT&tests.test=testGetWithFields

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([FA954CBDA791C93D]:0)

```

### PR DESCRIPTION
**Pull request by romseygeek**
This commit passes the correct docid to value fetchers, and adds a new test
to exercise the behaviour explicitly and guard against regressions.

Fixes #90881

### CODE REVIEW

**Comment by romseygeek** [comment]
Marked as `>non-issue` as this is as an unreleased bug

File: server/src/test/java/org/elasticsearch/search/fetch/subphase/FetchFieldsPhaseTests.java [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+        MappedFieldType fieldType = mock(MappedFieldType.class);
+        when(fieldType.valueFetcher(any(), any())).thenReturn(
+            new DocValueFetcher(DocValueFormat.RAW, new SortedNumericIndexFieldData("field", IndexNumericFieldData.NumericType.LONG, null))
+        );
+        when(sec.getFieldType(any())).thenReturn(fieldType);
+        when(sec.getMatchingFieldNames(any())).thenReturn(Set.of("field"));
+        when(sec.nestedLookup()).thenReturn(NestedLookup.EMPTY);
+        FetchContext fetchContext = mock(FetchContext.class);
+        when(fetchContext.fetchFieldsContext()).thenReturn(ffc);
+        when(fetchContext.getSearchExecutionContext()).thenReturn(sec);
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/search/fetch/subphase/FetchFieldsPhaseTests.java:70]: Would it be a lot of work to try and do without mocking? MapperServiceTestCase has a utility method to create a search execution context but it requires a mapper service instance. Wondering if it may be worth changing.

**Review by javanna — APPROVED** [review]
Small comment on testing, LGTM though

File: server/src/test/java/org/elasticsearch/search/fetch/subphase/FetchFieldsPhaseTests.java (hunk 1 above)
Comment (romseygeek) [reply server/src/test/java/org/elasticsearch/search/fetch/subphase/FetchFieldsPhaseTests.java:70]: We need a special MappedFieldType that returns a DocValueFetcher, and we don't have any core mappers that use DocValueFetcher. So somewhat counter-intuitively, not using mocks here ends up with much more ceremony because we need to register plugins and create special Mappers and TypeParsers, etc.

I would love to extract some interfaces from SearchExecutionContext though.  Loads of places that take it only need the 'return all matching field types' functionality, and it's a very heavy object to construct for tests.
