### PR TITLE
Avoid dropping aggregate groupings in local plans

### LINKED ISSUE #128054: [ES|QL] ClassCastException in PercentileDoubleGroupingAggregatorFunction
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

The following error was observed:

```
java.lang.ClassCastException: class org.elasticsearch.compute.data.LongVectorBlock cannot be cast to class org.elasticsearch.compute.data.BytesRefBlock (org.elasticsearch.compute.data.LongVectorBlock and org.elasticsearch.compute.data.BytesRefBlock are in unnamed module of loader java.net.URLClassLoader @1174676f)
	at org.elasticsearch.compute.aggregation.PercentileDoubleGroupingAggregatorFunction.addIntermediateInput(PercentileDoubleGroupingAggregatorFunction.java:173)
	at org.elasticsearch.compute.aggregation.GroupingAggregator$1.add(GroupingAggregator.java:50)
	at org.elasticsearch.compute.operator.HashAggregationOperator$1AddInput.add(HashAggregationOperator.java:165)
	at org.elasticsearch.compute.aggregation.blockhash.BytesRef3BlockHash.addVectors(BytesRef3BlockHash.java:95)
	at org.elasticsearch.compute.aggregation.blockhash.BytesRef3BlockHash.add(BytesRef3BlockHash.java:75)
	at org.elasticsearch.compute.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:193)
	at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:276)
	at org.elasticsearch.compute.operator.Driver.run(Driver.java:184)
	at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:403)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.compute.operator.DriverScheduler$1.doRun(DriverScheduler.java:57)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
```

There are mentions of similar error in #100047 so i suspect a malformed query.

### Steps to Reproduce

N/A

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by dnhatn**
The local plan optimizer should not change the layout, as it has already been agreed upon. However, [CombineProjections](https://github.com/elastic/elasticsearch/blob/9626fe54ebe38a6142a0b65816febded7e881423/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java#L171-L175) can violate this when some grouping elements refer to the same attribute. This occurs when [ReplaceFieldWithConstantOrNull](https://github.com/elastic/elasticsearch/blob/21fe40a9b5e73ca953e93971089116a535ab903c/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/ReplaceFieldWithConstantOrNull.java#L102) replaces missing fields with the same reference for a given data type.

I see several ways to address this issue:

1. Skip CombineProjections in the local plan. This optimization is useful in the global plan, but likely unnecessary in the local plan, especially since we now need to retain the same number of aggregates and groupings.

2. Update [RuleUtils#aliasedNulls ](https://github.com/elastic/elasticsearch/blob/21fe40a9b5e73ca953e93971089116a535ab903c/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/RuleUtils.java#L64)to generate an eval for each missing field separately, rather than one per data type.

This change adopts option 2 as it is simpler and more robust. However, either option is fine, and I am open to other suggestions.

Closes #128054
Closes #129811

### CODE REVIEW

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java [hunk 1]
```diff
@@ -1680,6 +1680,36 @@ public void testQueryOnEmptyDataIndex() {
         }
     }
 
+    public void testGroupingStatsOnMissingFields() {
+        assertAcked(client().admin().indices().prepareCreate("test_missing_fields").setMapping("data", "type=long"));
```
Comment (astefan) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java]: I think here you meant `missing_field_index`, right?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java [hunk 2]
```diff
@@ -925,21 +925,12 @@ public void testMissingFieldsDoNotGetExtracted() {
...
-        var nullAlias = Alias.unwrap(projections.get(8));
-        assertThat(Expressions.name(nullAlias), is("first_name"));
-        // salary --> emp_no
-        nullAlias = Alias.unwrap(projections.get(10));
-        assertThat(Expressions.name(nullAlias), is("emp_no"));
-        // check field extraction is skipped and that evaled fields are not extracted anymore
         var field = as(project.child(), FieldExtractExec.class);
         var fields = field.attributesToExtract();
         assertThat(Expressions.names(fields), contains("_meta_field", "gender", "hire_date", "job", "job.raw", "languages", "long_noidx"));
+        var eval = as(field.child(), EvalExec.class);
```
Comment (astefan) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java]: Could you also, please, change the "Expects" part of this method at the top? It's a thing with the optimizer tests that, at least for me, is very useful when looking at a test.

**Review by astefan — COMMENTED** [review]
Had a first look at it, but I need more time to understand it.
It seems to be doing what the comment in RuleUtils.aliasedNulls is suggesting, which is good.

When I tested this I really had to use `"max_concurrent_shards_per_node":1` (as you have it in your IT test). Why is this bit needed, if you can shed some light?

**Comment by bpintea** [comment]
Nice find of the cause!

> This change adopts option 2 as it is simpler and more robust.

I think skipping `CombineProjections` in `LocalLogicalPlanOptimizer` should be (1) even simpler (basically, similar to [this line](https://github.com/elastic/elasticsearch/blob/80667d0c8a80c88e900cac6f2006f0471ee6f234/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java#L70)) and likely needed anyways, as indeed, the rule (1) shouldn't normally apply locally, but (2) could also change the layout (as it happened).

So IMO we should at a minimum apply 1. Then, the `NULL` aliasing should make a difference with many locally missing fields, so even it has some fragility, I'd opt to keep it (at least until we substitute with something else).

**Comment by alex-spies** [comment]
Hey, nice find @dnhatn !

> Update [RuleUtils#aliasedNulls ](https://github.com/elastic/elasticsearch/blob/21fe40a9b5e73ca953e93971089116a535ab903c/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/RuleUtils.java#L64)to generate an eval for each missing field separately, rather than one per data type.

I believe this is a good quick fix.

> I think skipping CombineProjections in LocalLogicalPlanOptimizer should be (1) even simpler (basically, similar to [this line](https://github.com/elastic/elasticsearch/blob/80667d0c8a80c88e900cac6f2006f0471ee6f234/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java#L70)) and likely needed anyways, as indeed, the rule (1) shouldn't normally apply locally, but (2) could also change the layout (as it happened)

I wouldn't disable this locally altogether. There are very valid reasons to combine projections on the local node; for one, `ProjectAwayColumns` introduces a projection that's only present on local nodes; also, `ReplaceFieldWithConstantOrNull` introduces a projection only locally; combining those makes sense and simplifies our plans.

I think the crux is that on a local node `Aggregate` can actually mean "this will be the initial aggregate that corresponds to an intermediate/final aggregate downstream and thus mustn't have its output changed".

Thus, I think a more robust approach would be to mark such `Aggregate`s and avoid the deduplication of the groupings [here](https://github.com/elastic/elasticsearch/blob/9626fe54ebe38a6142a0b65816febded7e881423/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java#L171-L175) for any aggregates marked in such a way.

I know this requires a new transport version, but we could add a `fixedOutput` field to `Aggregate` and check it in `CombineProjections`.

**Comment by bpintea** [comment]
> I wouldn't disable this locally altogether. There are very valid reasons to combine projections on the local node; for one, `ProjectAwayColumns` introduces a projection that's only present on local nodes; also, `ReplaceFieldWithConstantOrNull` introduces a projection only locally; combining those makes sense and simplifies our plans.

I think `ProjectAwayColumns` should matter later, as a physical rule, but the projections that `ReplaceFieldWithConstantOrNull` produces should be combined, you're right! 

> Thus, I think a more robust approach would be to mark such Aggregates and avoid the deduplication of the groupings [here](https://github.com/elastic/elasticsearch/blob/9626fe54ebe38a6142a0b65816febded7e881423/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java#L171-L175) for any aggregates marked in such a way.

`CombineProjections` would need to become aware of a special `Aggregate` flavour, then, plus have a rule to mark these instances (coming/going from/in a fragment). An alternative might be to just make `CombineProjections` location-aware (coordinator vs. local) and based on this discriminator just use a list, rather then a set, when building the output of the agg in `#combineUpperGroupingsAndLowerProjections`? That shouldn't require transport changes.

**Comment by alex-spies** [comment]
> I think ProjectAwayColumns should matter later, as a physical rule,

It adds a logical projection into the fragment [here](https://github.com/elastic/elasticsearch/blob/62a542242f5783b6ed6c4d7e327486438813b3aa/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/physical/ProjectAwayColumns.java#L93). Currently, this top projection gets normally combined with anything that rules like `ReplaceFieldWithConstantOrNull` add.

> An alternative might be to just make CombineProjections location-aware (coordinator vs. local) and based on this discriminator just use a list, rather then a set, when building the output of the agg in #combineUpperGroupingsAndLowerProjections? That shouldn't require transport changes.

Oh, right - I thought this wasn't an option because there may be other aggs in the local plan, but of course there can be at most one aggregate :facepalm: . So, a local flavor of `CombineProjections` would do the trick!

**Comment by bpintea** [comment]
Laterally, I was also wondering if we couldn't do a verification of the outputs before and after local replanning.

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java (hunk 1 above)
Comment (dnhatn) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java]: Yes, good catch, fixed in https://github.com/elastic/elasticsearch/pull/129370/commits/13a30b09c1bc12ce340a14f97773e588a48aa462. Thanks!

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java (hunk 2 above)
Comment (dnhatn) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalPhysicalPlanOptimizerTests.java]: I've taken a different approach, so we no longer need to adjust this test.

**Comment by dnhatn** [comment]
> When I tested this I really had to use "max_concurrent_shards_per_node":1 (as you have it in your IT test). Why is this bit needed, if you can shed some light?

@astefan To reproduce this bug, we need to set up more than one index where at least one pair of fields with the same type is missing from one of the indices. At query execution time, we also need to ensure that the query targets only shards from the index that lacks these fields. This setup will cause `ReplaceFieldWithConstantOrNull` to replace the missing fields with a single null eval, duplicate it via projection, and then `CombineProjects` will drop the duplicate, leading to a mismatched layout. Here, we set `max_concurrent_shards_per_node` to 1 to make sure we don't target shards from both indices at the same time, which effectively disables the `ReplaceFieldWithConstantOrNull` rule if the fields exist in any index.

**Comment by dnhatn** [comment]
@astefan @bpintea @alex-spies Thank you for your review. I thought about it more. I agree that the right fix is to introduce a local variant of the CombineProjections rule to ensure we don't change the layout (I took this approach before https://github.com/elastic/elasticsearch/pull/129370/commits/d172ff3acda68d4bedf131a8a49c5f4425a6ac30). I've updated this in https://github.com/elastic/elasticsearch/pull/129370/commits/edfb33e06a8253794dd7e7d22d16bd99bcddf54a. I also tried to add a check to ensure that the local (logical/physical) optimizer doesn't change the output of a plan; however, we need to do more work to adjust the test infra to allow this. I prefer to address this later so we can get this fix in sooner and reduce the noise in serverless.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java [hunk 3]
```diff
@@ -58,8 +59,8 @@ protected List<Batch<LogicalPlan>> batches() {
 
     @SuppressWarnings("unchecked")
     private static Batch<LogicalPlan> localOperators() {
-        var operators = operators();
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizer.java:61]: nit: this is a second mechanism for supplying local versions of rules; below is the original one, which looks for e.g. `PropagateEmptyRelation` and replaces it by `LocalPropagateEmptyRelation`.

It'd be nicer to have just one such mechanism, but it's not the end of the world.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java [hunk 4]
```diff
@@ -54,33 +57,32 @@ protected LogicalPlan rule(UnaryPlan plan) {
                 // project can be fully removed
                 if (newAggs != null) {
                     var newGroups = replacePrunedAliasesUsedInGroupBy(a.groupings(), aggs, newAggs);
-                    plan = a.with(newGroups, newAggs);
+                    if (local == false || newGroups.size() == a.groupings().size()) {
+                        plan = a.with(newGroups, newAggs);
+                    }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java]: Why is the new condition required? Does this have anything to do with how `TS` works/will work? I just tried reverting the change in these lines and the new tests still passed fine.

In general, if we have a projection downstream from an agg, the top projection dictates the output and we should be able to do whatever with the agg below as long as the overall output remains that of the projection.

The only exception is if the agg is the local counterpart of a final agg on the coordinator; but then there shouldn't be a project downstream from it. (If we have this situation, it's a bug, at least for regular `STATS`.)

Unless having additional nodes downstream from the agg in a local plan can happen somehow with `TS`; but then I don't understand why we need to keep the number of groupings constant.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java [hunk 5]
```diff
@@ -54,33 +57,32 @@ protected LogicalPlan rule(UnaryPlan plan) {
...
                 }
             }
             return plan;
         }
 
         // Agg with underlying Project (group by on sub-queries)
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java]: nit & pre-existing, but can we remove this comment? It's misleading.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java [hunk 6]
```diff
@@ -54,33 +57,32 @@ protected LogicalPlan rule(UnaryPlan plan) {
...
+                    throw new EsqlIllegalArgumentException("Expected an Attribute, got {}", grouping);
                 }
-                plan = a.with(
-                    p.child(),
-                    combineUpperGroupingsAndLowerProjections(groupingAttrs, p.projections()),
-                    combineProjections(a.aggregates(), p.projections())
-                );
+            }
+            List<Expression> newGroupings = combineUpperGroupingsAndLowerProjections(groupingAttrs, p.projections());
+            if (local == false || newGroupings.size() == a.groupings().size()) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java]: This is correct as we skip this optimization if it would change the number of groupings.

However, I think it would be better to make a small adjustment to `combineUppgerGroupingsAndLowerProjections` to use a list of new groupings instead of a set in local plans (as @bpintea suggested), so we still combine the agg with the project but just don't de-duplicate the groupings. 

This approach could fail if we somehow expect distinct attribute ids in the physical step, but we should try.

Reason: In cases where we have a huge projection (happens with ReplaceFieldWithConstantOrNull!) but only really need 1 or 2 attributes, leaving the projection in place means we'll introduce a ton of field extractions, namely `O(n)` in the number of fields that the `EsRelation` has.

You can see this clearly when you inspect the optimized local plan in the local optimizer test you added:
```
    \_Aggregate[[first_name{f}#7, last_name{f}#10],[SUM(salary{f}#11,true[BOOLEAN]) AS $$SUM$AVG(salary)$0#17, COUNT(salary{f}#
11,true[BOOLEAN]) AS $$COUNT$AVG(salary)$1#18, first_name{f}#7, last_name{f}#10]]
      \_Project[[_meta_field{f}#12, emp_no{f}#6, first_name{r}#7, gender{f}#8, hire_date{f}#13, job{f}#14, job.raw{f}#15, lang
uages{f}#9, first_name{r}#7 AS last_name#10, long_noidx{f}#16, salary{f}#11]]
        \_Eval[[null[KEYWORD] AS first_name#7]]
          \_EsRelation[test][_meta_field{f}#12, emp_no{f}#6, first_name{f}#7, ge..]
```

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java [hunk 7]
```diff
@@ -1679,6 +1679,39 @@ public void testQueryOnEmptyDataIndex() {
         }
     }
 
+    public void testGroupingStatsOnMissingFields() {
+        assertAcked(client().admin().indices().prepareCreate("missing_field_index").setMapping("data", "type=long"));
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java:1683]: This test could use some comments to explain why we set it up in this specific way.

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java [hunk 8]
```diff
@@ -1679,6 +1679,39 @@ public void testQueryOnEmptyDataIndex() {
...
+        long oneValue = between(1, 1000);
+        indexDoc("missing_field_index", "1", "data", oneValue);
+        refresh("missing_field_index");
+        QueryPragmas pragmas = randomPragmas();
+        pragmas = new QueryPragmas(
+            Settings.builder().put(pragmas.getSettings()).put(QueryPragmas.MAX_CONCURRENT_SHARDS_PER_NODE.getKey(), 1).build()
+        );
+        EsqlQueryRequest request = new EsqlQueryRequest();
+        request.query("FROM missing_field_index,test | STATS s = sum(data) BY color, tag | SORT color");
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java:1692]: I guess the point is to force a situation where both `color` and `tag` are missing? And because they have the same type, `ReplaceFieldWithConstantOrNull` will add just 1 eval expression like `null[KEYWORD] AS color#7` and `CombineProjections` would try to slim down the groupings to just `BY null`, right?

**Review by alex-spies — COMMENTED** [review]
I think this improves the situation by avoiding an error in the response, but there is a potential performance problem that remains. See my comments below.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java (hunk 6 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/CombineProjections.java]: I tried following this approach but it's also incomplete.

It breaks 2 invariants:
- AggregateExec having a duplicate name id in its output, this triggers the PlanConsistencyChecker. But even disabling it still causes trouble, because
- when building the layout for such an AggregateExec, we mustn't have duplicate name ids - and we really shouldn't attempt to side-step this.

My conclusion: the correct fix requires leaving an aliasing projection or eval upstream from the Aggregate that just maintains the original grouping attributes.

~~I'll work on it right now.~~ Pushed an alternative solution.

**Comment by alex-spies** [comment]
@dnhatn , I pushed an alternative solution that, I hope, is closest to the original workings of CombineProjections while still preserving the agg output.

If you also think this is better, I think I need eyes from @bpintea and/or @astefan on it + a liiiittle bit more test coverage, and we should be good to go.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java [hunk 9]
```diff
@@ -744,6 +744,14 @@ public void testUnionTypesInferNonNullAggConstraint() {
         assertEquals("integer_long_field", unionTypeField.fieldName().string());
     }
 
+    public void testGroupingByMissingFields() {
+        var plan = plan("FROM test | STATS AVG(salary) BY first_name, last_name ");
+        var testStats = statsForMissingField("first_name", "last_name");
+        var localPlan = localPlan(plan, testStats);
+        Aggregate aggregate = (Aggregate) localPlan.collectFirstChildren(p -> p instanceof Aggregate).getFirst();
+        assertThat(aggregate.groupings(), hasSize(2));
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java:759]: I'd expand the test a little to assert the rest of the plan.

With the alternative solution I pushed, there should be an `Eval` upstream taking care of creating a new attribute for the duplication that otherwise happens when the groupings would get optimized away.

**Review by astefan — APPROVED** [review]
LGTM. The code looks good to me, maybe  a bit more unit tests (not sure exactly what) that show the different "context" (coordinator/data node) of CombineProjections in "action", like LogicalPlan optimizer tests on both coordinator and data node branches.

**Comment by dnhatn** [comment]
Thanks friends for reviews and feedback!

**Comment by dnhatn** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/130053)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/130055)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/130060)|
|✅|8.17|[](https://github.com/elastic/elasticsearch/pull/130128)|

**Comment by alex-spies** [comment]
@dnhatn , I realized that 8.17 might also be affected - the optimization of missing fields changed with https://github.com/elastic/elasticsearch/pull/126187 (which triggered the bug in CombineProjections to surface on main).

Should we backport one more time, to 8.17?

**Comment by dnhatn** [comment]
> Should we backport one more time, to 8.17?

++ I opened https://github.com/elastic/elasticsearch/pull/130128. Thanks Alex!
