### PR TITLE
Report GREEN status when FileSettingsService is stopped

### LINKED ISSUE #117591: [CI] FileSettingsServiceTests testStopWorksInMiddleOfProcessing failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #5044 / sles-15_platform-support-unix](https://gradle-enterprise.elastic.co/s/a6nctirglnxxs)
- [elasticsearch-pull-request #43083 / part-1](https://gradle-enterprise.elastic.co/s/jqoke2n4vll7q)
- [elasticsearch-pull-request #42612 / part-1](https://gradle-enterprise.elastic.co/s/p65rwt56y2ig2)
- [elasticsearch-pull-request #42568 / part-1](https://gradle-enterprise.elastic.co/s/iqyjqbiyngji2)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.reservedstate.service.FileSettingsServiceTests.testStopWorksInMiddleOfProcessing" -Dtests.seed=8B345834FF0F6BFA -Dtests.locale=fr -Dtests.timezone=Pacific/Gambier -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
No observed failures in 1081 runs.

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.reservedstate.service.FileSettingsServiceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testStopWorksInMiddleOfProcessing),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
fileSettingsHealthIndicatorService.changeOccurred();
Wanted 1 time:
-> at org.elasticsearch.reservedstate.service.FileSettingsServiceTests.testStopWorksInMiddleOfProcessing(FileSettingsServiceTests.java:401)
But was 2 times:
-> at org.elasticsearch.reservedstate.service.FileSettingsService.processFileOnServiceStart(FileSettingsService.java:160)
-> at org.elasticsearch.reservedstate.service.FileSettingsService.processFileChanges(FileSettingsService.java:149)


```

**Issue Reasons:**
- [main] 4 failures in test testStopWorksInMiddleOfProcessing (0.4% fail rate in 959 executions)
- [main] 3 failures in step part-1 (0.7% fail rate in 401 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.8% fail rate in 398 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by prdoyle**
When the `FileSettingsService` is inactive, its health indicator should report `GREEN` because it is successfully doing nothing.

Fixes #117591.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java [hunk 1]
```diff
@@ -225,21 +236,33 @@ public static class FileSettingsHealthIndicatorService implements HealthIndicato
...
-        private final AtomicLong failureStreak = new AtomicLong(0);
-        private final AtomicReference<String> mostRecentFailure = new AtomicReference<>();
+        private boolean isActive = false;
+        private long changeCount = 0;
+        private long failureStreak = 0;
+        private String mostRecentFailure = null;
 
-        public void changeOccurred() {
-            changeCount.incrementAndGet();
+        public synchronized void startOccurred() {
```
Comment (prdoyle) [inline server/src/main/java/org/elasticsearch/reservedstate/service/FileSettingsService.java:244]: I got tired of worrying about mixing and matching the states of these fields when they're changed independently. Now they're all just protected by `synchronized`.

**Review by JVerwolf — APPROVED** [review]
LGTM
