### PR TITLE
ESQL: Lookup join drop unused columns on lookup index

### LINKED ISSUE #118778: LOOKUP JOIN fails with cryptic error when we DROP the fields looked up
A query that uses KEEP (or DROP) to drop the fields that are looked up will fail with a runtime error during LOOKUP.

```
ROW left = "left", client_ip = "172.21.0.5", right = "right"
| LOOKUP JOIN clientips_lookup ON client_ip
| KEEP left, client_ip, right
```

Failed with:

```
path: /_query, params: {format=txt, error_trace=true}, status: 500 java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at org.elasticsearch.compute.operator.lookup.MergePositionsOperator.<init>(MergePositionsOperator.java:76)
        at org.elasticsearch.xpack.esql.enrich.AbstractLookupService.doLookup(AbstractLookupService.java:329)
...
```

The problem is that the `LOOKUP JOIN` should return the `env` field, and dropping it causes the error, since all fields left after the `KEEP` actually come from the left index.

The current behaviour differs between `main` and the latest code in https://github.com/elastic/elasticsearch/pull/118429.

* `main` uses fieldcaps `*` for lookup indices, and so will resolve to lookup `env` even if it is later dropped by the `KEEP`. This is wrong, since we do a lot of work which we then drop
* `https://github.com/elastic/elasticsearch/pull/118429` instead does fieldcaps on what it sees the query as needing, which does not include any fields on the right. But instead of generating a validation error or erasing the LOOKUP JOIN entirely, it passes the _lookup no fields_ down to the runtime, and that chokes with the cryptic error.

Both are incorrect.

Choices of behaviour:

* Throw a validation error for LOOKUP JOIN that has output only from the left index.
* Rewrite away LOOKUP JOIN if the JOIN does not actually achieve anything.
* Allow LOOKUP JOIN on no output fields, but return as many rows as match the join key, but return no extra columns

This last option appears to be favoured as we move in the direction of returning increased cardinality instead of multivalue results. See https://github.com/elastic/elasticsearch/issues/118781

### PR DESCRIPTION
**Pull request by ivancea**
Closes https://github.com/elastic/elasticsearch/issues/118778

Unignore/Update some tests when dropping the lookup columns, and update PruneColumns rule to prune the columns even if only 1 remains

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java [hunk 1]
```diff
@@ -104,12 +104,10 @@ public LogicalPlan apply(LogicalPlan plan) {
...
                     // Normally, pruning EsRelation has no effect because InsertFieldExtraction only extracts the required fields, anyway.
-                    // The field extraction for LOOKUP JOIN works differently, however - we extract all fields (other than the join key)
-                    // that the EsRelation has.
+                    // However, InsertFieldExtraction can't be currently used in LOOKUP JOIN right index,
+                    // it works differently as we extract all fields (other than the join key) that the EsRelation has.
                     var remaining = removeUnused(esRelation.output(), used);
-                    // TODO: LookupFromIndexOperator cannot handle 0 lookup fields, yet. That means 1 field in total (key field + lookup).
-                    // https://github.com/elastic/elasticsearch/issues/118778
-                    if (remaining != null && remaining.size() > 1) {
+                    if (remaining != null) {
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java:110]: :+1:

**Review by nik9000 — APPROVED** [review]
LGTM. @alex-spies probably should also look.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1]: Minor suggestion: as a sort of a weird edge case, it's interesting how we optimize in case of shadowing in addition to explicit projection. (In the past, these two cases _could_ behave differently, in fact!)

An easy way to get this would be to have 2 identical lookups in a row:

```
              FROM test
            | EVAL language_code = languages
            | LOOKUP JOIN languages_lookup ON language_code
            | LOOKUP JOIN languages_lookup ON language_code
            // Specifically no KEEP or DROP at the end
```
The first lookup join shouldn't add any columns at all, while the second one should add all of them.

**Review by alex-spies — APPROVED** [review]
LGTM. Thanks @ivancea ! Only a minor test suggestion from my side.

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 2]
```diff
@@ -6220,6 +6220,76 @@ public void testLookupJoinPushDownDisabledForDisjunctionBetweenLeftAndRightField
...
+
+        var join = as(project.child(), Join.class);
+        var joinRightRelation = as(join.right(), EsRelation.class);
+
+        assertThat(joinRightRelation.output().size(), equalTo(1));
+        assertThat(joinRightRelation.output().get(0).name(), equalTo("language_code"));
+    }
+
+    /**
+     * Same as {@link #testLookupJoinKeepNonLookupFields}, but with drop.
```
[the remark this answers is not in the document]
Comment (ivancea) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java]: Done!

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java
Comment (ivancea) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1]: Added that test. FWIW it worked fine with and without KEEP

**Review by alex-spies — APPROVED** [review]
Great, thanks for the additional tests @ivancea !
