### PR TITLE
Fix use of time zone in date_histogram rewrite

### LINKED ISSUE #31392: Date field mapping "epoch_millis" errors on date aggregations with timezones other than UTC
As demonstrated in https://github.com/elastic/kibana/issues/19858, having a date field with `"format": "epoch_millis"` can cause
errors when running date histogram aggregations with a time zone other than UTC. I think this problem was introduced as a side effect of https://github.com/elastic/elasticsearch/pull/30534. While throwing an error for parsing time values with `"format": "epoch_millis"` and timezones other than UTC looks like the intented behaviour (see https://github.com/elastic/elasticsearch/issues/22621), it should be able to overwrite this by specifying `format` in the aggregation. This however doesn't seem to work currently on 6.x.

### PR DESCRIPTION
**Pull request by cbuescher**
Currently, DateHistogramAggregationBuilder#rewriteTimeZone uses the aggregation
date math parser and time zone to check whether all values in a read have the
same timezone to speed up computation. However, the upper and lower bounds to
check are retrieved as longs in epoch time, so they don't need to get parsed
using a time zone or a parser other than "epoch_millis". This PR changes this
behaviour that was causing problems when the field type mapping was specifying
only "epoch_millis" as a format but a different time zone than UTC was used.

Closes #31392

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java [hunk 1]
```diff
@@ -406,11 +409,10 @@ DateTimeZone rewriteTimeZone(QueryShardContext context) throws IOException {
                     // rounding rounds down, so 'nextTransition' is a good upper bound
                     final long high = nextTransition;
 
-                    final DocValueFormat format = ft.docValueFormat(null, null);
-                    final Object formattedLow = format.format(low);
-                    final Object formattedHigh = format.format(high);
+                    final Object formattedLow = DocValueFormat.RAW.format(low);
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java]: Since the field is a date, it's a bit confusing to use the RAW format imo, maybe use a `new DocValueFormat.Date(epoch_millis, DateTimeZone.UTC)` instead?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java [hunk 2]
```diff
@@ -70,6 +72,7 @@
 public class DateHistogramAggregationBuilder extends ValuesSourceAggregationBuilder<ValuesSource.Numeric, DateHistogramAggregationBuilder>
         implements MultiBucketAggregationBuilder {
     public static final String NAME = "date_histogram";
+    private static DateMathParser DEFAULT_DATE_PARSER = new DateMathParser(DateFieldMapper.DEFAULT_DATE_TIME_FORMATTER);
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java]: Should we use the epoch_millis parser specifically rather than a parser that understands epoch millis among other formats?

**Review by jpountz — CHANGES_REQUESTED** [review]
Wow, this was more sneaky than I expected.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java (hunk 1 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java]: I was even thinking about just boxing the long to a Long because there really isn't much more to it in this case. Would that work?

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java (hunk 2 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java]: I thought I did that, might have not pushed it though because I think it was a late addition. Will do.

File: server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java (hunk 1 above)
Comment (jpountz) [reply server/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java]: It relies on the assumption that we store millis internally, but I think that's fine. :+1:

**Comment by cbuescher** [comment]
@jpountz I pushed an update with the changes you requested

**Review by jpountz — APPROVED** [review]
LGTM!

**Comment by jpountz** [comment]
@cbuescher Should we use the `non-issue` label rather than `bug` given that this bug is not released?

**Comment by cbuescher** [comment]
@jpountz makes sense in terms of release notes I think
