### PR TITLE
Don't disable tasks based on the plugin

### LINKED ISSUE #36041: Build: :x-pack:test:smb-fixture:licenseHeaders Fails on 6.x
This task fails regularly on 6.x. intake currently: 

> Task :x-pack:test:smb-fixture:licenseHeaders FAILED

I haven't found more info on the cause of it yet in the logs but just want to file this to track it.

### PR DESCRIPTION
**Pull request by alpar-t**
Some times the test fixtures plugin did not correctly disable tasks
from the build plugin as it should.
The plugin manager and tasks both use domain name collections so
the previus conde should have worked.
I did not have trime to track it down, but suspect there's some race
condition in Gradle causing this. The plugin manager is still incubating.
Since the tasks are on the cp even if the plugin is not applyed, we
don't really  need to involve the plugin at all.

Closes #36041

### CODE REVIEW

File: buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java [hunk 1]
```diff
@@ -113,7 +111,10 @@ private void setSystemProperty(Task task, String name, Object value) {
     }
 
     private void disableTaskByType(TaskContainer tasks, Class<? extends Task> type) {
-        tasks.withType(type, task -> task.setEnabled(false));
+        tasks.withType(type, task -> {
+            task.getLogger().info("test fixtures: Disabling tasks of type {}", type);
```
Comment (jasontedor) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java]: Maybe log this only at the debug level?

**Review by jasontedor — APPROVED** [review]
I left one comment, no need for another round.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java (hunk 1 above)
Comment (nik9000) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java]: +1

**Review by nik9000 — APPROVED** [review]

File: buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java [hunk 2]
```diff
@@ -45,21 +46,18 @@ public void apply(Project project) {
...
-
         if (project.file(DOCKER_COMPOSE_YML).exists()) {
+            // convenience boilerplate with build plugin
+            // Can't reference tasks that are implemented in Groovy, use reflection  instead
+            disableTaskByType(tasks, getTaskClass("org.elasticsearch.gradle.precommit.LicenseHeadersTask"));
+            disableTaskByType(tasks, getTaskClass("com.carrotsearch.gradle.junit4.RandomizedTestingTask"));
+            disableTaskByType(tasks, ThirdPartyAuditTask.class);
+            disableTaskByType(tasks, JarHellTask.class);
+
+            if(dockerComposeSupported(project) == false) {
```
Comment (jasontedor) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java]: Nit: add a space between `if` and `(`

File: buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java [hunk 3]
```diff
@@ -71,16 +69,17 @@ public void apply(Project project) {
...
-                // Can't reference tasks that are implemented in Groovy, use reflection  instead
-                disableTaskByType(tasks, getTaskClass("org.elasticsearch.gradle.precommit.LicenseHeadersTask"));
-                disableTaskByType(tasks, getTaskClass("com.carrotsearch.gradle.junit4.RandomizedTestingTask"));
-                disableTaskByType(tasks, ThirdPartyAuditTask.class);
-                disableTaskByType(tasks, JarHellTask.class);
-            });
         } else {
+            if (dockerComposeSupported(project) == false) {
+                project.getLogger().warn(
+                    "Tests require docker-compose at /usr/local/bin/docker-compose or /usr/bin/docker-compose " +
```
Comment (jasontedor) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java]: Add the project name to the log message?

File: buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java [hunk 4]
```diff
@@ -101,6 +100,15 @@ public void apply(Project project) {
         }
     }
 
+    @Input
+    public boolean dockerComposeSupported(Project project) {
+        // Don't look for docker-compose on the PATH yet that would pick up on Windows as well
```
Comment (jasontedor) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java]: Maybe be more explicit and if (Windows) return false else return docker-compose exists?

**Review by jasontedor — COMMENTED** [review]
I left a few suggestions.

File: buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java [hunk 5]
```diff
@@ -45,21 +46,18 @@ public void apply(Project project) {
             "testFixtures", TestFixtureExtension.class, project
         );
 
-        // Don't look for docker-compose on the PATH yet that would pick up on Windows as well
```
Comment (nik9000) [inline buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java]: I see. We can't bail here because we won't do the disabling that we need. Got it!

**Review by nik9000 — APPROVED** [review]

File: buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java (hunk 4 above)
Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java]: It's technically possible to support windows, it's just a matter of testing. 
I think being specific about the OS would make it seem like it's impossible to support.

Comment (jasontedor) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java]: I don't agree, it would mean it's not supported for now. You've done that, just indirectly.

Comment (atorok) [reply buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java]: ok, I'll add this to #36037
