### PR TITLE
Fix snapshot double finalization

### LINKED ISSUE #101028: [CI] SnapshotStressTestsIT testRandomActivities failing
This NPE issue is different from #99477 and #99516

### CI Link

https://gradle-enterprise.elastic.co/s/v7icocftg32uc/tests/task/:server:internalClusterTest/details/org.elasticsearch.snapshots.SnapshotStressTestsIT/testRandomActivities%20%7Bseed=%5B32DA52B8E1546052:7737AEA21D8C5249%5D%7D?top-execution=1

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SnapshotStressTestsIT.testRandomActivities {seed=[32DA52B8E1546052:7737AEA21D8C5249]}" -Dtests.seed=32DA52B8E1546052 -Dtests.locale=cs -Dtests.timezone=America/El_Salvador -Druntime.java=21

### Does it reproduce?

No

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.snapshots.SnapshotStressTestsIT&tests.test=testRandomActivities%20%7Bseed%3D%5B32DA52B8E1546052:7737AEA21D8C5249%5D%7D

### Failure excerpt

```
WARNING: Uncaught exception in thread: Thread[#108,elasticsearch[node_s0][masterService#updateTask][T#1],5,TGRP-SnapshotStressTestsIT]
java.lang.AssertionError: java.lang.AssertionError: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.SnapshotsInProgress$Entry.failure()" because "entry" is null
	at __randomizedtesting.SeedInfo.seed([32DA52B8E1546052]:0)
	at org.elasticsearch.snapshots.SnapshotsService.finalizeSnapshotEntry(SnapshotsService.java:1447)
	at org.elasticsearch.snapshots.SnapshotsService.runNextQueuedOperation(SnapshotsService.java:1535)
	at org.elasticsearch.snapshots.SnapshotsService.lambda$finalizeSnapshotEntry$28(SnapshotsService.java:1428)
	at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:177)
	at org.elasticsearch.repositories.FinalizeSnapshotContext.onResponse(FinalizeSnapshotContext.java:116)
	at org.elasticsearch.repositories.FinalizeSnapshotContext.onResponse(FinalizeSnapshotContext.java:28)
	at org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onResponse(ActionListenerImplementations.java:182)
	at org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:310)
	at org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:230)
	at org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:259)
	at org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:173)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.lambda$finalizeSnapshot$19(BlobStoreRepository.java:1684)
	at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236)
	at org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:310)
	at org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:230)
	at org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:259)
	at org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:173)
	at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$9.clusterStateProcessed(BlobStoreRepository.java:2690)
	at org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.lambda$execute$0(MasterService.java:552)
	at org.elasticsearch.cluster.service.MasterService$ExecutionResult.onPublishSuccess(MasterService.java:927)
	at org.elasticsearch.cluster.service.MasterService$4.onResponse(MasterService.java:374)
	at org.elasticsearch.cluster.service.MasterService$4.onResponse(MasterService.java:369)
	at org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:260)
	at org.elasticsearch.action.ActionListener$4.onResponse(ActionListener.java:330)
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32)
	at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:50)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.AssertionError: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.SnapshotsInProgress$Entry.failure()" because "entry" is null
	... 32 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.SnapshotsInProgress$Entry.failure()" because "entry" is null
	at org.elasticsearch.snapshots.SnapshotsService.finalizeSnapshotEntry(SnapshotsService.java:1311)
	... 31 more

```

### PR DESCRIPTION
**Pull request by ywangd**
When a snapshot is completed as a SnapshotsInProgress entry in cluster state and also queued for next operations, it can lead to double finalization of the snapshot if the entry in cluster state is processed first. This PR fixes it by only start finalization if it is *not* already in endingSnapshots.

The PR also adds a specific test case for the double finalization issue (manifested as NPE).

Resolves: #101028

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 1]
```diff
@@ -1280,7 +1284,11 @@ public void onFailure(Exception e) {
                     }
                 });
             } else {
-                finalizeSnapshotEntry(snapshot, metadata, repositoryData);
+                if (newFinalization) {
+                    finalizeSnapshotEntry(snapshot, metadata, repositoryData);
+                } else {
+                    runNextQueuedOperation(repositoryData, repoName, false);
+                }
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java:1291]: Happy to discuss whether this is the right fix. It seems safe to me. But I am also running this change in a loop to see if there is undesirable side effect.

**Review by DaveCTurner — COMMENTED** [review]
Makes sense to me.

Could we add this assertion now?

```diff
diff --git a/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java b/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
index 2ad9b21bcb8..30167a894e0 100644
--- a/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
+++ b/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java
@@ -1312,6 +1312,7 @@ public class SnapshotsService extends AbstractLifecycleComponent implements Clus

     private void finalizeSnapshotEntry(Snapshot snapshot, Metadata metadata, RepositoryData repositoryData) {
         assert currentlyFinalizing.contains(snapshot.getRepository());
+        assert repositoryOperations.assertNotQueued(snapshot);
         try {
             SnapshotsInProgress.Entry entry = SnapshotsInProgress.get(clusterService.state()).snapshot(snapshot);
             final String failure = entry.failure();
```

Also did it not work to reproduce this with the test suite introduced in https://github.com/elastic/elasticsearch/pull/101312?

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotsServiceNpeIT.java [hunk 2]
```diff
@@ -0,0 +1,279 @@
...
+            logger.info("--> start deleting snapshot snap-1 ");
+            startDeleteSnapshot(repoName, "snap-1");
+        }).start();
+        assertBusy(() -> assertThat(barrier.getNumberWaiting(), equalTo(1)));
+        future.actionGet();
+        logger.info("--> repository blocked at listing root blobs");
+
+        // 3 - Stop data node so that index-2, index-3 become unassigned
+        internalCluster().stopNode(dataNodeName);
+        ensureColor(ClusterHealthStatus.RED, TimeValue.timeValueSeconds(30), false, "index-2", "index-3");
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotsServiceNpeIT.java:104]: I think `ensureColor(RED)` is confusing, this ensures that the health of these indices is _at least_ RED, which is always true. If you're wanting to wait for the data node to be removed then I think `validateClusterFormed()` or `ensureStableCluster()` would be best.

Comment (ywangd) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/SnapshotsServiceNpeIT.java]: Indeed this assertion is not really needed. I replaced it with `internalCluster().validateClusterFormed()`. Thanks!

**Comment by ywangd** [comment]
Added `assert repositoryOperations.assertNotQueued(snapshot);`

> did it not work to reproduce this with the test suite introduced in https://github.com/elastic/elasticsearch/pull/101312?

It might. I did not try. I can use this as a study case when I get back to work on #101312.

**Comment by ywangd** [comment]
Failure is unrelated. I raised #101500

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-2
