### PR TITLE
Always fail engine if delete operation fails

### LINKED ISSUE #33256: Should we fail engine immediately after a delete fails?
This is a spin-off of https://github.com/elastic/elasticsearch/pull/33217#issuecomment-416980172.

Today when a delete operation on a primary fails, we won't immediately fails that shard but "replace" that delete by a NoOp. While this approach sounds correct, its benefit is questionable. What can we recover after a delete fails? If nothing, should we just fail a shard immediately?

Let's revisit this approach.

### PR DESCRIPTION
**Pull request by dnhatn**
Unlike index operations which can fail at the document level to analyzing errors, delete operations should never fail at the document level whether soft-deletes is enabled or not. With this change, we will always fail the engine if we fail to apply a delete operation to Lucene. 

Closes #33256

### CODE REVIEW

**Comment by dnhatn** [comment]
test this please

File: server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java [hunk 1]
```diff
@@ -1394,13 +1384,8 @@ private DeleteResult deleteInLucene(Delete delete, DeletionStrategy plan) throws
...
                 plan.versionOfDeletion, getPrimaryTerm(), delete.seqNo(), plan.currentlyDeleted == false);
         } catch (Exception ex) {
-            if (indexWriter.getTragicException() == null) {
-                // there is no tragic event and such it must be a document level failure
-                return new DeleteResult(
-                        ex, plan.versionOfDeletion, delete.primaryTerm(), delete.seqNo(), plan.currentlyDeleted == false);
-            } else {
-                throw ex;
-            }
+            assert indexWriter.getTragicException() != null : "delete operation should never fail at document level";
```
Comment (s1monw) [inline server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java]: can we do this like this:

```Java

if (indexWriter.getTragicException() == null) {
  throw new AssertionError("delete operation should never fail at document level", ex);
}
```
we otherwise loose the original exception and then we are in trouble :)

**Review by s1monw — APPROVED** [review]
left one comment

**Comment by dnhatn** [comment]
Thanks @s1monw!
