### PR TITLE
Reroute after cluster recovery

### LINKED ISSUE #82456: Persistent Settings Takes Effect After RecoverStateUpdateTask's Reroute
RecoverStateUpdateTask execute Reroute before persistent settings takes effect, this may cause the logic about `AllocationService#reroute`  execute in an unexpected way.
`    class RecoverStateUpdateTask extends ClusterStateUpdateTask {

        @Override
        public ClusterState execute(final ClusterState currentState) {
            if (currentState.blocks().hasGlobalBlock(STATE_NOT_RECOVERED_BLOCK) == false) {
                logger.debug("cluster is already recovered");
                return currentState;
            }

            final ClusterState newState = Function.<ClusterState>identity()
                .andThen(ClusterStateUpdaters::updateRoutingTable)
                .andThen(ClusterStateUpdaters::removeStateNotRecoveredBlock)
                .apply(currentState);

            return allocationService.reroute(newState, "state recovered");
        }
       ....
`
The place where the persistent settings is applied in master is after clusterstate publish .

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today when starting the cluster we open the routing table and reroute in
a single cluster state update, which means that this reroute runs before
any cluster settings have been applied. This doesn't make much
difference today since the initial reroute just triggers async shard
fetching so there are no settings which affect it, but it's still
surprising and would result in a bug if such a setting were introduced.
With this commit we trigger the first reroute in a follow-up cluster
state update instead so that any persistent settings are sure to be
applied.

Closes #82456

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/GatewayServiceIT.java [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+
+        @Override
+        public Map<String, ExistingShardsAllocator> getExistingShardsAllocators() {
+            return Map.of(ALLOCATOR_NAME, new ExistingShardsAllocator() {
+                @Override
+                public void beforeAllocation(RoutingAllocation allocation) {
+                    if (settingApplied.get() == false) {
+                        fail("boom");
+                    }
+                    assertTrue(settingApplied.get());
```
Comment (idegtiarenko) [inline server/src/internalClusterTest/java/org/elasticsearch/gateway/GatewayServiceIT.java:67]: I believe if statement and following assertion are doing exactly the same check.
I would suggest to only keep one and add a message describing the failure

**Review by idegtiarenko — APPROVED** [review]

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/GatewayServiceIT.java (hunk 1 above)
Comment (DaveCTurner) [reply server/src/internalClusterTest/java/org/elasticsearch/gateway/GatewayServiceIT.java:64]: Ah whoops that was just so I had somewhere to hang a breakpoint. Fixed in 0ae1e299a32.

File: server/src/main/java/org/elasticsearch/gateway/GatewayService.java [hunk 2]
```diff
@@ -220,20 +221,22 @@ public ClusterState execute(final ClusterState currentState) {
...
-            return allocationService.reroute(newState, "state recovered");
         }
 
         @Override
         public void clusterStateProcessed(final ClusterState oldState, final ClusterState newState) {
             logger.info("recovered [{}] indices into cluster_state", newState.metadata().indices().size());
             // reset flag even though state recovery completed, to ensure that if we subsequently become leader again based on a
             // not-recovered state, that we again do another state recovery.
-            resetRecoveredFlags();
+            if (oldState != newState) {
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/gateway/GatewayService.java:235]: I am a bit hesitant to this. I think that if the states are identical, we no longer have the block either. And we *should* only submit the task if we have not recovered yet and only once through the booleans in this class.

I wonder if we should just assert that they are different instead? And then always call reroute since that seems most defensive anyway.

I may have missed the situation making this necessary though, hope you can educate me then.

File: server/src/main/java/org/elasticsearch/cluster/routing/BatchedRerouteService.java [hunk 3]
```diff
@@ -105,7 +107,10 @@ public ClusterState execute(ClusterState currentState) {
                             pendingRerouteListeners = null;
                         }
                     }
-                    if (currentListenersArePending) {
+                    if (currentState.blocks().hasGlobalBlock(STATE_NOT_RECOVERED_BLOCK)) {
+                        logger.trace("skipping reroute prior to state recovery [{}]", reason);
+                        return currentState;
```
Comment (henningandersen) [inline server/src/main/java/org/elasticsearch/cluster/routing/BatchedRerouteService.java:112]: I think we are changing the contract slightly here in that a reroute may now result in the listener being invoked with a cluster-state that was not rerouted. Most of those listeners just do logging. One exception is the `DiskThresholdMonitor` which seems unproblematic wrt. this. But it still seems like a possibly confusing semantics for future users of the listener callback from the reroute service.

I am not sure I would prefer to defer invoking the listener until the block is removed, but I wonder what your thoughts are on this. I think it at least requires an explanation in the javadoc for the `RerouteService` method.

**Review by henningandersen — COMMENTED** [review]
Thanks David, this is a great find. I have a couple of comments otherwise looking good.

File: server/src/main/java/org/elasticsearch/cluster/routing/BatchedRerouteService.java (hunk 3 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/cluster/routing/BatchedRerouteService.java]: Thanks, I now better understand your thinking here. I wonder if we should (not necessarily in this PR) add an assert to cluster state building that it cannot have a non-empty routing table with a `STATE_NOT_RECOVERED_BLOCK` block?

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/cluster/routing/BatchedRerouteService.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/cluster/routing/BatchedRerouteService.java]: Sure, I think https://github.com/elastic/elasticsearch/pull/83133 should do the trick, let's see what CI says.
