### PR TITLE
Handle not preferred in replica shards allocator

### LINKED ISSUE #142424: [CI] IndexStatsIT testFieldDataStats failing
**Build Scans:**
- [elasticsearch-intake #34583 / part1](https://gradle-enterprise.elastic.co/s/o5dn7zkaiwzoi)
- [elasticsearch-pull-request #120704 / part-1](https://gradle-enterprise.elastic.co/s/gvr4tlv4u2eki)
- [elasticsearch-intake #34353 / part1](https://gradle-enterprise.elastic.co/s/qucxico45vxq4)
- [elasticsearch-pull-request #119409 / part-1](https://gradle-enterprise.elastic.co/s/ane2vp6suhcai)
- [elasticsearch-periodic-platform-support #11826 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/7yenr5u3iyjh6)
- [elasticsearch-pull-request #119280 / checkpart1_gpu-tests](https://gradle-enterprise.elastic.co/s/ttm5nkln4iqv4)
- [elasticsearch-periodic #11848 / encryption-at-rest](https://gradle-enterprise.elastic.co/s/pjf7d6lchma42)
- [elasticsearch-pull-request #119088 / part-1](https://gradle-enterprise.elastic.co/s/si5i46mdjunes)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.indices.stats.IndexStatsIT.testFieldDataStats" -Dtests.seed=4422F58253CEA387 -Dtests.locale=ln -Dtests.timezone=Africa/Kampala -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.indices.stats.IndexStatsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testFieldDataStats'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: timed out waiting for green state
```

**Issue Reasons:**
- [main] 8 failures in test testFieldDataStats (1.4% fail rate in 570 executions)
- [main] 2 failures in step part1 (2.0% fail rate in 99 executions)
- [main] 3 failures in step part-1 (0.8% fail rate in 353 executions)
- [main] 2 failures in pipeline elasticsearch-intake (2.0% fail rate in 98 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (1.1% fail rate in 351 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
Now that `canAllocate` can return `NOT_PREFERRED` for unassigned shards, we need to handle this correctly in the replica shards allocator.

Note that neither the write load or index balance deciders are turned on for stateful ES deployments, but we do run the write load decider in CI, so it's possible this causes issues in tests (as we think we might have seen).

In any case we must prepare for a world where stateful ES has deciders that return `NOT_PREFERRED`.

Assisted by Cursor

Fixes #142424

### CODE REVIEW

**Comment by nicktindall** [comment]
> Actually there may be corresponding work to do in the primary shards allocator

There is some similar, but orthogonal work in `PrimaryShardAllocator`, I did that [here](#142669). The current state is not broken, but just treats `NOT_PREFERRED` as `YES`.

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java [hunk 1]
```diff
@@ -57,9 +68,16 @@
 @ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST, numDataNodes = 0)
 public class ReplicaShardAllocatorIT extends ESIntegTestCase {
 
+    private static final Set<String> NOT_PREFERRED_NODES = Collections.newSetFromMap(new ConcurrentHashMap<>());
```
Comment (mhl-b) [inline server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java:71]: nit: why static?

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java [hunk 2]
```diff
@@ -410,6 +428,72 @@ public void testPeerRecoveryForClosedIndices() throws Exception {
         assertNoOpRecoveries(indexName);
     }
 
+    /**
+     * Verify that when a node with a shard copy returns NOT_PREFERRED from allocation deciders,
+     * the replica is still allocated there and can perform a no-op recovery.
+     */
+    public void testNoopRecoveryOnNotPreferredNode() throws Exception {
+        String indexName = "test";
```
Comment (mhl-b) [inline server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java]: nit: randomIndexName

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java [hunk 3]
```diff
@@ -410,6 +428,72 @@ public void testPeerRecoveryForClosedIndices() throws Exception {
...
+        ensureActivePeerRecoveryRetentionLeasesAdvanced(indexName);
+
+        // Disable allocation, then stop the replica so the shard becomes unassigned without immediately reallocating
+        updateClusterSettings(
+            Settings.builder().put(CLUSTER_ROUTING_ALLOCATION_ENABLE_SETTING.getKey(), EnableAllocationDecider.Allocation.PRIMARIES)
+        );
+        internalCluster().stopNode(nodeWithReplica);
+
+        // Start a node with the old replica's data and mark it as NOT_PREFERRED
+        nodeWithReplica = internalCluster().startDataOnlyNode(nodeWithReplicaSettings);
```
Comment (mhl-b) [inline server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java:465]: Can you explain a bit more please this part. My understanding that we start another another node on the same data path, while previous node is still running. Why it needs same data path settings?

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java (hunk 1 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java:71]: Really just to avoid needing to get the plugin instance and fiddle with it that way, you only specify the plugins via the list of classes, so you get no opportunity to keep a reference to a non-static instance? Maybe I've missed something, but it's the approach I've used [elsewhere](https://github.com/elastic/elasticsearch/blob/70f0da72400c07d453ca03a9ae4df11a811d173c/server/src/internalClusterTest/java/org/elasticsearch/cluster/routing/allocation/allocator/AbstractAllocationDecisionTestCase.java#L49-L62) as well.

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java (hunk 3 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java:465]: The reason is the that this logic lives in the `ReplicaShardsAllocator`, which is called by the `GatewayShardsAllocator` which is an `ExistingShardsAllocator`.

```java
/**
 * Searches for, and allocates, shards for which there is an existing on-disk copy somewhere in the cluster. The default implementation is
 * {@link GatewayAllocator}, but plugins can supply their own implementations too.
 */
public interface ExistingShardsAllocator {
```

So for this logic to be exercised we need to be looking for a node that has the shard contents on disk already.

Also as I understand it `internalCluster().stopNode(nodeWithReplica);` will block until the node is stopped, so we shouldn't be running two nodes concurrently looking at the same data path.

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java (hunk 2 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java]: Fixed in c58bf45bc9b270cbb01b23a5668e8e484fc37e43

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java (hunk 1 above)
Comment (mhl-b) [reply server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java:71]: Something like this. More complex :(

Add accessible map to the plugin.

https://github.com/elastic/elasticsearch/blob/937f80c0fcf9af2f68b51bb6b7c1405e523a3ad6/modules/transport-netty4/src/internalClusterTest/java/org/elasticsearch/http/netty4/Netty4IncrementalRequestHandlingIT.java#L883-L918

And access in the test:
```
 var handlersByOpaqueId = internalCluster().getInstance(HandlersByOpaqueId.class, nodeName);
```

File: server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java (hunk 3 above)
Comment (mhl-b) [reply server/src/internalClusterTest/java/org/elasticsearch/gateway/ReplicaShardAllocatorIT.java:465]: I've been looking for stopNode but couldn't find it, it was right in front me all the time @_@. Thanks!

**Review by mhl-b — APPROVED** [review]
LGTM
