### PR TITLE
[Transform] improve error handling of script errors

### LINKED ISSUE #48467: [Transform] search failures due to script or mapping errors are not handled
If a transform task fails in the search phase due to a mapping conflict or a scripting error the error is handled as a temporary search problem, search is re-tried (10 times) and eventually the task is put into `FAILED` state with reason: "task encountered more than 10 failures; latest failure: Partial shards failure", audit only contains "Partial shards failure".

The real issue can only be found in the logs, e.g.

```
Caused by: org.elasticsearch.ElasticsearchException$1: Fielddata is disabled on text fields by default. Set fielddata=true on [...] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
```

or 
```
org.elasticsearch.script.ScriptException: runtime error
...
Caused by: java.lang.IllegalArgumentException: No field found for [field_b] in mapping
```

## Solution

We need to unwrap search failures and check for inner problems:

 - do not retry if it turns out to be a irrecoverable error (like we do for other errors like this)
 - message the real error as reason in `_stats` and as audit message

### Case 1
 - create 2 indexes with 2 fields, use keyword fields: 
    - `field_a`, `field_b`
    - `field_a`, `field_c`
 - create a transform group by `field_a` with a scripted metric agg that accesses `field_b` without a guard:

```
      "scripted_metric": {
          "init_script": "state.b = new String()",
          "map_script": "state.b = doc['field_b']",
          "combine_script": "return state.b",
          "reduce_script": "return states"
        }
```
The transform should fail with a `ScriptException`

### Case 2
 - create 2 indexes with 2 fields, map `field_a` for the 2nd index to `text`: 
    - `field_a`, `field_b`
    - `field_a`, `field_b`
 - create a transform, group by `field_a`

The transform should fail with an `ElasticsearchException: Fielddata is disabled on text fields by default.`

/CC @tsg

### PR DESCRIPTION
**Pull request by hendrikmuhs**
improve error handling for script errors, treating it as irrecoverable errors which puts the task
immediately into failed state, also improves the error extraction to properly report the script error.

fixes #48467

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/packaging-sample-matrix

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/SearchExceptionRootCauseFinder.java [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+ */
+public final class SearchExceptionRootCauseFinder {
+
+    /**
+     * Unwrap the Exceptionstack and return the most likely cause.
+     *
+     * @param e raw Exception
+     * @return unwrapped elasticsearch exception
+     */
+    public static ElasticsearchException getRootCauseElasticsearchException(Exception e) {
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/SearchExceptionRootCauseFinder.java]: Why didn't you put this in the transforms ExceptionHelper class?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/SearchExceptionRootCauseFinder.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+
+                if (unwrappedShardFailure instanceof ElasticsearchException) {
+                    return (ElasticsearchException) unwrappedShardFailure;
+                }
+            }
+        } else if (unwrappedThrowable instanceof ElasticsearchException) {
+            return (ElasticsearchException) unwrappedThrowable;
+        }
+
+        return null;
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/SearchExceptionRootCauseFinder.java]: I think returning `null` here will confuse other users of this class and may cause bugs. 

This method should return `Exception` and then the caller can do their `instanceof` checks to verify (which is being done anyways).

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java [hunk 3]
```diff
@@ -468,25 +468,32 @@ protected void onAbort() {
...
+            handleCircuitBreakingException((CircuitBreakingException) unwrappedException);
+        } else if (unwrappedException instanceof ScriptException) {
+            handleScriptException((ScriptException) unwrappedException);
+            // irrecoverable error without special handling
+        } else if (unwrappedException instanceof IndexNotFoundException
+            || unwrappedException instanceof AggregationResultUtils.AggregationExtractionException
+            || unwrappedException instanceof TransformConfigReloadingException) {
+            failIndexer("task encountered irrecoverable failure: " + e.getMessage());
+        } else if (context.getAndIncrementFailureCount() > context.getNumFailureRetries()) {
+            String failure = unwrappedException != null ? unwrappedException.getDetailedMessage() : e.getMessage();
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformIndexer.java]: I think it would be beneficial to add a `getDetailedMessage` method to the transforms ExceptionsHelper class. It could do a `if(exception instanceof ElasticsearchException)` and then cast and return the detailed message. And `exception.getMessage` otherwise.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/SearchExceptionRootCauseFinder.java (hunk 1 above)
Comment (hendrikmuhs) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/utils/SearchExceptionRootCauseFinder.java]: ExceptionHelper is used to validate input parameters, so it serves a different purpose. In the long run this generic class should move into core. 

The root cause finder has a different purpose and probably can not be generalized.

**Comment by hendrikmuhs** [comment]
Thanks @benwtrent for the review! Good points, I addressed your remarks and pushed an update.

**Review by benwtrent — APPROVED** [review]

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc 
run elasticsearch-ci/default-distro

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/packaging-sample-matrix

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/packaging-sample-matrix
