### PR TITLE
ESQL: Retain aggregate when grouping 

### LINKED ISSUE #126026: ES|QL: columns not projected away despite KEEP
```
row foo = 10 
| stats field_1 = max(foo), this = count(*), field_2 = max(foo) by foo  
| rename this AS field_2 
| keep field_1, field_2  
| eval field_2 = 1, field_1 = 1
```

```
      foo      |    field_1    |    field_2    
---------------+---------------+---------------
10             |1              |1              

```

`foo` shouldn't be there.

Interestingly, if you try to use the wrong column, the query will fail:

```
row foo = 10 
| stats field_1 = max(foo), this = count(*), field_2 = max(foo) by foo  
| rename this AS field_2 
| keep field_1, field_2  
| eval field_2 = 1, field_1 = 1, bar = foo
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "verification_exception",
                "reason": "Found 1 problem\nline 1:176: Unknown column [foo]"
            }
        ],
        "type": "verification_exception",
        "reason": "Found 1 problem\nline 1:176: Unknown column [foo]"
    },
    "status": 400
}
```

### PR DESCRIPTION
**Pull request by kanoshiou**
This PR resolves #126026.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java [hunk 1]
```diff
@@ -84,7 +86,8 @@ public LogicalPlan apply(LogicalPlan plan) {
                                 );
                             } else {
                                 // Aggs cannot produce pages with 0 columns, so retain one grouping.
-                                remaining = List.of(Expressions.attribute(aggregate.groupings().get(0)));
+                                Attribute attribute = Expressions.attribute(aggregate.groupings().getFirst());
+                                remaining = aggregate.aggregates().stream().map(v -> new Alias(v.source(), v.name(), attribute)).toList();
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java:90]: Is there a specific reason why we are creating a list the same size as the original one?
Couldn't it just be

```
NamedExpression firstAggregate = aggregate.aggregates().getFirst();
remaining = List.of(new Alias(firstAggregate.source(), firstAggregate.name(), attribute));
```

It won't make a big difference at execution time, but a high number of attributes makes a difference at planning time

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec [hunk 2]
```diff
@@ -636,4 +636,55 @@ row foo = "Bar" | where foo rlike "(?i)Ba.*"
 foo:keyword
 ;
 
+evalAfterAvgGroupingUsingSameName
```
Comment (luigidellaquila) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec:639]: Please also add the query from the [original issue](https://github.com/elastic/elasticsearch/issues/126026)

**Review by luigidellaquila — COMMENTED** [review]
Thanks @kanoshiou, I had a first look a the PR and I added a couple of comments

**Comment by luigidellaquila** [comment]
buildkite test this

**Comment by luigidellaquila** [comment]
Apparently the CI is not happy, `LogicalPlanOptimizerTests.testEmptyProjectInStatWithGroupAndEval` needs to be fixed.

Also, probably we should preserve the NameID of the Alias, something like

```
remaining = List.of(new Alias(firstAggregate.source(), firstAggregate.name(), attribute, firstAggregate.id()));
```

It won't make a huge difference probably, as that alias is not further referenced in the plan, but at least we avoid to create a new NameID

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java (hunk 1 above)
Comment (kanoshiou) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java:90]: You are right, I did't think that far.

**Comment by kanoshiou** [comment]
Thank you for reviewing @luigidellaquila! Fix is on the way😊.

**Comment by luigidellaquila** [comment]
buildkite test this

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks @kanoshiou!
It will only need a merge with `main` to resolve conflicts

**Comment by luigidellaquila** [comment]
buildkite test this

**Comment by kanoshiou** [comment]
This is weird. I have iterated the test over 100 times and can't reproduce it.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec [hunk 3]
```diff
@@ -673,3 +673,68 @@ ROW foo = [10, 11, 12]
 max:integer
 13
 ;
+
+evalAfterAvgGroupingUsingSameName
+required_capability: retain_aggregate_when_grouping
+from employees
+| stats avg = avg(salary) by gender 
+| keep avg 
+| eval avg = 12
```
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec:682]: nitpicky suggestion: the added tests 1. keep one or several aggregates and then 2. override them. We could also add tests that keep groupings in step 1, and consider aliased groupings for good measure.

E.g.
```
from employees
| stats avg(salary) by g = gender
| keep g
| eval g = 12
```

**Review by alex-spies — APPROVED** [review]
Thanks @kanoshiou , very nice fix!

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec (hunk 3 above)
Comment (kanoshiou) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec:682]: Thank you for the helpful suggestion. I hadn’t considered keeping the aliased groupings, but I’ll update those tests.

**Comment by luigidellaquila** [comment]
buildkite test this

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec (hunk 3 above)
Comment (alex-spies) [reply x-pack/plugin/esql/qa/testFixtures/src/main/resources/eval.csv-spec]: Thanks @kanoshiou ! I think a test case that doesn't keep any of the aggregates would be nice, too, like the one I suggested above - but this PR is already in a very good spot and can happily be merged as-is (once the small test regression is fixed that @luigidellaquila mentioned).

**Comment by kanoshiou** [comment]
> wrong column name in the result, `avg` vs `max`

oops🥺
I don't why my test command unexpectedly skipped the tests requiring a capability, but now it has been fixed.

**Comment by luigidellaquila** [comment]
buildkite test this

**Review by luigidellaquila — APPROVED** [review]
Thanks @kanoshiou, LGTM

I'm merging it now

**Comment by luigidellaquila** [comment]
This will need a manual backport to 8.x branch.
I'm doing it now

**Comment by luigidellaquila** [comment]
https://github.com/elastic/elasticsearch/pull/127253
