### PR TITLE
Fixing expectations in DataLifecycleServiceIT when there is a single node

### LINKED ISSUE #96070: [CI] DataLifecycleServiceIT testErrorRecordingOnRollover failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/njctqv4g2k7ly/tests/:modules:dlm:internalClusterTest/org.elasticsearch.dlm.DataLifecycleServiceIT/testErrorRecordingOnRollover

**Reproduction line:**
```
gradlew ':modules:dlm:internalClusterTest' --tests "org.elasticsearch.dlm.DataLifecycleServiceIT.testErrorRecordingOnRollover" -Dtests.seed=7A0C4AB39ECCF42F -Dtests.locale=fr-FR -Dtests.timezone=Universal -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.dlm.DataLifecycleServiceIT&tests.test=testErrorRecordingOnRollover

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: null
     but: was "{\"type\":\"exception\",\"reason\":\"Force merge request only had 1 successful shards out of a total of 2\"}"

  at __randomizedtesting.SeedInfo.seed([7A0C4AB39ECCF42F:EF340B4E82C2DA79]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.dlm.DataLifecycleServiceIT.lambda$testErrorRecordingOnRollover$11(DataLifecycleServiceIT.java:453)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1158)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1131)
  at org.elasticsearch.dlm.DataLifecycleServiceIT.testErrorRecordingOnRollover(DataLifecycleServiceIT.java:435)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by masseyke**
If an integration test brings up a 1-node cluster, and if DLM runs forcemerge, then forcemerge will report an error. This PR updates 2 DataLifecycleServiceIT tests to account for that, similar to #96047.
Closes #96070

### CODE REVIEW

File: modules/dlm/src/internalClusterTest/java/org/elasticsearch/dlm/DataLifecycleServiceIT.java [hunk 1]
```diff
@@ -452,7 +451,16 @@ public void testErrorRecordingOnRollover() throws Exception {
...
 
             for (DataLifecycleService lifecycleService : lifecycleServices) {
-                assertThat(lifecycleService.getErrorStore().getError(previousWriteInddex), nullValue());
+                if (internalCluster().numDataNodes() > 1) {
+                    assertThat(lifecycleService.getErrorStore().getError(previousWriteInddex), nullValue());
+                } else {
+                    if (lifecycleService.getErrorStore().getError(previousWriteInddex) != null) {
+                        assertThat(
+                            lifecycleService.getErrorStore().getError(previousWriteInddex),
+                            containsString("Force merge request only had 1 successful shards out of a total of 2")
```
Comment (gmarouli) [inline modules/dlm/src/internalClusterTest/java/org/elasticsearch/dlm/DataLifecycleServiceIT.java:460]: So, this test is a called `testErrorRecordingOnRollover` and it is checking how rollover related errors are recorded and cleared up, right?

If my above hypothesis is correct, I have to admit that this last part confuses me a bit. If I understand correctly the issue here is that if the cluster has a single node then the replica shard is unassigned and the force merge fails right?

What if, we use `auto_expand_replicas: 0-1` or something like that to ensure there will be no other errors. My concern is that this logic isn't related to this test and it will only confuse future maintainers.

What do you think?

File: modules/dlm/src/internalClusterTest/java/org/elasticsearch/dlm/DataLifecycleServiceIT.java [hunk 2]
```diff
@@ -533,7 +541,16 @@ public void testErrorRecordingOnRetention() throws Exception {
                 // error stores don't contain anything for the first generation index anymore
                 Iterable<DataLifecycleService> lifecycleServices = internalCluster().getInstances(DataLifecycleService.class);
                 for (DataLifecycleService lifecycleService : lifecycleServices) {
-                    assertThat(lifecycleService.getErrorStore().getError(firstGenerationIndex), nullValue());
+                    if (internalCluster().numDataNodes() > 1) {
```
Comment (gmarouli) [inline modules/dlm/src/internalClusterTest/java/org/elasticsearch/dlm/DataLifecycleServiceIT.java:544]: Same here.

**Review by gmarouli — COMMENTED** [review]
Nice catch @masseyke , I didn't think of this complication either. I have my concerns about handling the error like this, I would like to see if we could prevent that. Let me know what you think about the proposal in the comments, or let's think together what else we can do.

File: modules/dlm/src/internalClusterTest/java/org/elasticsearch/dlm/DataLifecycleServiceIT.java (hunk 1 above)
Comment (masseyke) [reply modules/dlm/src/internalClusterTest/java/org/elasticsearch/dlm/DataLifecycleServiceIT.java]: Yeah I had originally thought about changing it to use a minimum cluster size of 2 to avoid this problem. But that seemed to be too much of an impact on the test. Using `auto_expand_replicas` seems like a good balance. I'll switch to that.

**Review by gmarouli — APPROVED** [review]
LGTM, minor comment I would add a comment that explain why we changed this setting, to avoid surprising future developers :p .

Thanks @masseyke
