### PR TITLE
ESQL: TopNOperator, release Row on failure

### LINKED ISSUE #130215: [CI] TopNOperatorTests testSimpleWithCranky failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #9007 / windows-2022_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/bmdlrqksqaogg)
- [elasticsearch-pull-request #77881 / part-3](https://gradle-enterprise.elastic.co/s/4p5epkhnyl3hs)
- [elasticsearch-pull-request #77862 / part-3](https://gradle-enterprise.elastic.co/s/sboh7almreqr4)
- [elasticsearch-periodic #8978 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/ylusud4k4jv34)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:esql:compute:test" --tests "org.elasticsearch.compute.operator.topn.TopNOperatorTests.testSimpleWithCranky" -Dtests.seed=1F19B8C6301BB745 -Dtests.locale=hy -Dtests.timezone=Indian/Cocos -Druntime.java=24
```

**Applicable branches:**
9.1

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.compute.operator.topn.TopNOperatorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testSimpleWithCranky),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Expected no used bytes for driver, found: 200
```

**Issue Reasons:**
- [9.1] 4 failures in test testSimpleWithCranky (6.1% fail rate in 66 executions)
- [9.1] 2 failures in step part-3 (14.3% fail rate in 14 executions)
- [9.1] 2 failures in pipeline elasticsearch-pull-request (15.4% fail rate in 13 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by GalLalouche**
Resolves #130215, #130222, #130270.

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/topn/TopNOperator.java [hunk 1]
```diff
@@ -469,51 +469,50 @@ private Iterator<Page> toPages() {
                     p = 0;
                 }
 
-                Row row = list.get(i);
```
Comment (GalLalouche) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/topn/TopNOperator.java:472]: This line was basically moved to the `try-with-resource` clause. Everything else is indentation.

**Review by alex-spies — APPROVED** [review]

**Review by idegtiarenko — APPROVED** [review]

**Review by ivancea — APPROVED** [review]
