### PR TITLE
Fix logger when you can not create an azure storage client

### LINKED ISSUE #20633: Azure repository creation Issue in Elasticsearch 2.4.0
Hi All,

I want to take snapshot and restore using azure repository in Linux, I have configured these below setting in yml,

```
##################### Azure cloud plugin for repository ######################

cloud:
  azure:
    storage:
      account: "https://XXX.blob.core.windows.net/"
      key: "..."
```

with the above setting, service is started, but i am m getting below error when creating repository in Elasticsearch 2.4.0,

    PUT snapshot/mybackup
    {
    "type": "azure"
    }

Error msg:-

```json
{
   "error": {
      "root_cause": [
         {
            "type": "repository_exception",
            "reason": "[elasticsearch-snapshots] Can not find an azure client for account [null]"
         }
      ],
      "type": "repository_exception",
      "reason": "[elasticsearch-snapshots] Can not find an azure client for account [null]"
   },
   "status": 500
}
```

When I looked into the ES logs I could see cloud storage account not getting created at the start of elasticsearch

```
2016-09-22 07:30:23,221][INFO ][http                     ] [mue2rhegrdd002_RD_NDX_MASTER] publish_address {10.247.0.4:9200}, bound_addresses {10.247.0.4:9200}
[2016-09-22 07:30:23,221][INFO ][node                     ] [mue2rhegrdd002_RD_NDX_MASTER] started
[2016-09-22 07:30:23,258][INFO ][cluster.service          ] [mue2rhegrdd002_RD_NDX_MASTER] new_master {mue2rhegrdd002_RD_NDX_MASTER}{-mRr-uLKQkyEJwfqLLI_2Q}{10.247.0.4}{10.247.0.4:9300}{data=false, max_local_storage_nodes=1, master=true}, added {{mue2rhegrdd001_RD_NDX_DATA}{O-JSVOlMQXCuwb5nf5XheQ}{10.247.0.5}{10.247.0.5:9260}{max_local_storage_nodes=1, master=false},{mue2rhegrdd001_RD_NDX_MASTER}{DMAPO7O6QEuXmcsP6aGuAQ}{10.247.0.5}{10.247.0.5:9300}{data=false, max_local_storage_nodes=1, master=true},}, reason: zen-disco-join(elected_as_master, [1] joins received)
**[2016-09-22 07:30:24,576][ERROR][cloud.azure.storage      ] [mue2rhegrdd002_RD_NDX_MASTER] can not create azure storage client: Primary and secondary location URIs in a StorageUri must point to the same resource.**
[2016-09-22 07:30:24,589][INFO ][watcher                  ] [mue2rhegrdd002_RD_NDX_MASTER] starting watch service...
[2016-09-22 07:30:24,590][INFO ][watcher                  ] [mue2rhegrdd002_RD_NDX_MASTER] watch service has started
[2016-09-22 07:30:24,631][INFO ][license.plugin.core      ] [mue2rhegrdd002_RD_NDX_MASTER] license [cf8a2152-4f41-4739-8459-4137cac8105b] - valid
[2016-09-22 07:30:25,489][INFO ][gateway                  ] [mue2rhegrdd002_RD_NDX_MASTER] recovered [20] indices into cluster_state
[2016-09-22 07:30:26,021][INFO ][http                     ] [mue2rhegrdd002_RD_NDX_DATA] publish_address {10.247.0.4:9240}, bound_addresses {10.247.0.4:9240}
[2016-09-22 07:30:26,021][INFO ][node                     ] [mue2rhegrdd002_RD_NDX_DATA] started
[2016-09-22 07:30:26,622][INFO ][cluster.service          ] [mue2rhegrdd002_RD_NDX_MASTER] added {{mue2rhegrdd002_RD_NDX_DATA}{eE1n1iLMQom6VEgYfBwJ9g}{10.247.0.4}{10.247.0.4:9260}{max_local_storage_nodes=1, master=false},}, reason: zen-disco-join(join from node[{mue2rhegrdd002_RD_NDX_DATA}{eE1n1iLMQom6VEgYfBwJ9g}{10.247.0.4}{10.247.0.4:9260}{max_local_storage_nodes=1, master=false}])
[2016-09-22 07:30:26,678][INFO ][cluster.service          ] [mue2rhegrdd002_RD_NDX_DATA] detected_master {mue2rhegrdd002_RD_NDX_MASTER}{-mRr-uLKQkyEJwfqLLI_2Q}{10.247.0.4}{10.247.0.4:9300}{data=false, max_local_storage_nodes=1, master=true}, added {{mue2rhegrdd001_RD_NDX_DATA}{O-JSVOlMQXCuwb5nf5XheQ}{10.247.0.5}{10.247.0.5:9260}{max_local_storage_nodes=1, master=false},{mue2rhegrdd001_RD_NDX_MASTER}{DMAPO7O6QEuXmcsP6aGuAQ}{10.247.0.5}{10.247.0.5:9300}{data=false, max_local_storage_nodes=1, master=true},{mue2rhegrdd002_RD_NDX_MASTER}{-mRr-uLKQkyEJwfqLLI_2Q}{10.247.0.4}{10.247.0.4:9300}{data=false, max_local_storage_nodes=1, master=true},}, reason: zen-disco-receive(from master [{mue2rhegrdd002_RD_NDX_MASTER}{-mRr-uLKQkyEJwfqLLI_2Q}{10.247.0.4}{10.247.0.4:9300}{data=false, max_local_storage_nodes=1, master=true}])
**[2016-09-22 07:30:26,711][ERROR][cloud.azure.storage      ] [mue2rhegrdd002_RD_NDX_DATA] can not create azure storage client: Primary and secondary location URIs in a StorageUri must point to the same resource.**
[2016-09-22 07:30:26,764][INFO ][license.plugin.core      ] [mue2rhegrdd002_RD_NDX_DATA] license [cf8a2152-4f41-4739-8459-4137cac8105b] - valid
```

Please let me know your suggestions to resolve this.

Thanks,
Ganeshbabu R

### PR DESCRIPTION
**Pull request by dadoonet**
We were swallowing the original exception when creating a client with bad credentials.
So even in `TRACE` log level, nothing useful were coming out of it.
With this commit, it now prints:

```
[2016-09-27 15:54:13,118][ERROR][cloud.azure.storage      ] [node_s0] can not create azure storage client: Storage Key is not a valid base64 encoded string.
```

Closes #20633.

This PR applies to 2.4 branch. When accepted, I'll also apply it to master / 5.x branch (and 5.0? cc @clintongormley)

### CODE REVIEW

File: plugins/cloud-azure/src/test/java/org/elasticsearch/cloud/azure/AbstractAzureRepositoryServiceTestCase.java [hunk 1]
```diff
@@ -38,22 +38,7 @@
 
 public abstract class AbstractAzureRepositoryServiceTestCase extends AbstractAzureTestCase {
```
Comment (dadoonet) [inline plugins/cloud-azure/src/test/java/org/elasticsearch/cloud/azure/AbstractAzureRepositoryServiceTestCase.java]: Well. Actually this test class is totally broken. Probably for months. May be we should better get rid of it entirely or fix that in another PR.

**Comment by gmoskovicz** [comment]
Nice!

File: plugins/cloud-azure/src/test/java/org/elasticsearch/cloud/azure/AbstractAzureRepositoryServiceTestCase.java (hunk 1 above)
Comment (dadoonet) [inline plugins/cloud-azure/src/test/java/org/elasticsearch/cloud/azure/AbstractAzureRepositoryServiceTestCase.java]: So I checked in master branch and we are in a pretty good shape. We have 2 choices here:

* Remove the tests in 2.4 branch
* Keep them (but as they are not ran by default it's harmless IMO)

I'll go for the later, which means status quo on 2.4 branch if no one objects.

**Review by pickypg — APPROVED** [review]
