### PR TITLE
Implement rounding optimization for fixed offset timezones

### LINKED ISSUE #45702: Slow date_histogram after upgrading to 7.3.0
**Elasticsearch version** (`bin/elasticsearch --version`):
`Version: 7.3.0, Build: default/rpm/de777fa/2019-07-24T18:30:11.767338Z, JVM: 12.0.1`

**Plugins installed**: []
`repository-s3`

**JVM version** (`java -version`):
JVM shipped with Elasticsearch (rpm)

**OS version** (`uname -a` if on a Unix-like system):
`Linux es-hot-03.aegaeon-it.com 4.9.120-xxxx-std-ipv6-64 #327490 SMP Thu Aug 16 10:11:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
We noticed a severe degradation of `date_histogram` performance after upgrading from Elasticsearch `6.8.2` to the latest `7.3.0`.

The table below shows the execution time of the same query on the same cluster before and after the upgrade. The first execution happens after caches are cleared as follows:
- ES caches are cleared with `POST _cache/clear`
- Filesystem caches are invalidated by doing a _cat_ of all files found in `/var/lib/elasticsearch` do `/dev/null` (that's the best we found...)

Timings are as follows:
```
ES Version   Timings (ms)
------------------------------------
6.8.2        10388,  5797,  7319
7.3.0        21553, 15138, 14833
```

As you notice `7.3.0` is at **least twice slower** than `6.8.2`.

The dataset is made of about `650m` documents spread evenly between 15 indexes. Indexes have 3 shards each and no replica. The cluster is made of three nodes, each with 7Gb RAM (of each 4Gb is allocated to the heap) and 2 vCPUs at 3.1Ghz. There is no activity on the cluster besides this test query.

The query targets only half of the documents (using a _date_range_) and builds a `date_histogram` with buckets of `3h`. This query is actually what KIbana's Discover panel will do...

```
{
  "size": 500,
  "sort": [
    {
      "@timestamp": {
        "order": "desc",
        "unmapped_type": "boolean"
      }
    }
  ],
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "3h",
        "time_zone": "Europe/Berlin",
        "min_doc_count": 1
      }
    }
  },
  "docvalue_fields": [
    {
      "field": "@timestamp",
      "format": "date_time"
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "@timestamp": {
              "format": "strict_date_optional_time",
              "gte": "2019-01-09T00:00:00.000Z",
              "lte": "2019-01-15T00:00:00.000Z"
            }
          }
        }
      ]
    }
  }
}
```

We are very surprised by this drop of performance...
Did we forgot to change some configurations parameters when doing the upgrade or is it a regression in ES itself ?

### PR DESCRIPTION
**Pull request by csoulios**
Fixes #45702 with date_histogram aggregation when using `fixed_interval`. 

Implement code change discussed at:
https://github.com/elastic/elasticsearch/issues/45702#issuecomment-530775309

Optimization has been implemented for both fixed and calendar intervals

### CODE REVIEW

**Review by spinscale — CHANGES_REQUESTED** [review]
As I am unsure about the performance implications, maybe resurrecting the `RoundingBenchmark` for testing from the 7.x branch makes sense here (or just test on the 7.x branch then port)

**Review by jimczi — CHANGES_REQUESTED** [review]
Thanks @csoulios , the changes look good, I left some comments

File: server/src/main/java/org/elasticsearch/common/Rounding.java [hunk 1]
```diff
@@ -455,6 +454,15 @@ public byte id() {
 
         @Override
         public long round(final long utcMillis) {
+            // This works as long as the tz offset doesn't change. It is worth getting this case out of the way first,
+            // as the calculations for fixing things near to offset changes are a little expensive and unnecessary
+            // in the common case of working with fixed offset timezones (such as UTC).
+            if (timeZone.getRules().isFixedOffset() == true) {
```
[the remark this answers is not in the document]
Comment (csoulios) [reply server/src/main/java/org/elasticsearch/common/Rounding.java]: Moved this to constructor as discussed. Benchmark results improved by ~12%.

See results below (right column is the newer revision):

```|                                       50th percentile latency | query-agg-date_histogram |     2892.92 |     2539.31 | -353.609 |     ms |
|                                       90th percentile latency | query-agg-date_histogram |     3086.98 |     2762.28 | -324.694 |     ms |
|                                      100th percentile latency | query-agg-date_histogram |     3182.51 |     2865.38 | -317.137 |     ms |
|                                  50th percentile service time | query-agg-date_histogram |     2885.19 |     2532.11 | -353.078 |     ms |
|                                  90th percentile service time | query-agg-date_histogram |     3078.69 |     2755.39 | -323.297 |     ms |
|                                 100th percentile service time | query-agg-date_histogram |     3174.46 |     2857.74 | -316.713 |     ms |```

**Comment by csoulios** [comment]
I ran ES Rally benchmark (https://github.com/csoulios/date_histogram-benchmark) for the following scenarios (on my laptop): 
* ES 6..8.0, UTC tz
* ES 8.x (with fix), UTC tz
* ES 8.x (with fix), -01:00 tz
* ES 8.x (with fix), Europe/Berlin tz

All produced similar results:
```
|-------------------------------+--------------------------+-------------+-----------+--------------+---------------------|
| Metric                        | Task                     | 6.8.0 (UTC) | 8.x (UTC) | 8.x (-01:00) | 8.x (Europe/Berlin) |
|-------------------------------+--------------------------+-------------+-----------+--------------+---------------------|
|      50th percentile latency | query-agg-date_histogram |      2570.75 |   2539.31 |      2687.07 |             2583.18 |  
|      90th percentile latency | query-agg-date_histogram |      2666.16 |   2762.28 |      2764.50 |             2674.80 |
|     100th percentile latency | query-agg-date_histogram |      2780.84 |   2865.38 |      2786.68 |             2898.41 | 
|-------------------------------+--------------------------+-------------+-----------+--------------+---------------------|
```

**Review by jimczi — APPROVED** [review]
LGTM, thanks @csoulios

File: server/src/main/java/org/elasticsearch/common/Rounding.java [hunk 2]
```diff
@@ -218,17 +218,20 @@ public Rounding build() {
...
 
         static final byte ID = 1;
+        static final long TZ_OFFSET_NON_FIXED = -1;
 
         private final DateTimeUnit unit;
         private final ZoneId timeZone;
         private final boolean unitRoundsToMidnight;
-        private final boolean isUtcTimeZone;
+        /** For fixed offset timezones, this is the offset in milliseconds, otherwise TZ_OFFSET_NON_FIXED */
+        private final long fixedOffset;
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/Rounding.java]: ignoreable nit: maybe name this fixedOffsetMs or something to indicate its contents

File: server/src/main/java/org/elasticsearch/common/Rounding.java [hunk 3]
```diff
@@ -218,17 +218,20 @@ public Rounding build() {
     static class TimeUnitRounding extends Rounding {
 
         static final byte ID = 1;
+        static final long TZ_OFFSET_NON_FIXED = -1;
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/Rounding.java]: comment nit: maybe include a small comment what `-1` indicates, and why this can never be -1 in a regular offset

File: server/src/main/java/org/elasticsearch/common/Rounding.java [hunk 4]
```diff
@@ -432,20 +436,25 @@ public String toString() {
         }
 
         static final byte ID = 2;
+        static final long TZ_OFFSET_NON_FIXED = -1;
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/Rounding.java]: minor nit: would one instance of this be enough?

File: server/src/main/java/org/elasticsearch/common/Rounding.java (hunk 3 above)
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/common/Rounding.java]: minor nit: can be private?

**Review by spinscale — APPROVED** [review]
left a few minor nits, feel free to ignore them

LGTM otherwise, thanks for fixing!

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro
