### PR TITLE
Fix tests in `TimeSeriesDataStreamsIT`

### LINKED ISSUE #126746: [CI] TimeSeriesDataStreamsIT testShrinkActionInPolicyWithoutHotPhase failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #7630 / ubuntu-2404-aarch64_checkpart5_platform-support-arm](https://gradle-enterprise.elastic.co/s/qkzprgjx7pl66)
- [elasticsearch-pull-request #67642 / part-5](https://gradle-enterprise.elastic.co/s/thnws5yvse5lm)
- [elasticsearch-pull-request #66748 / part-5](https://gradle-enterprise.elastic.co/s/e4vsfn7bc3sq6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT.testShrinkActionInPolicyWithoutHotPhase" -Dtests.seed=E09DE1E27786974F -Dtests.locale=pl -Dtests.timezone=NZ -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testShrinkActionInPolicyWithoutHotPhase),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [GET], host [http://127.0.0.1:33149], URI [shrink-stkv-.ds-logs-dakdrclfzi-2025.04.12-000001/_ilm/explain?only_errors=false&only_managed=false], status line [HTTP/1.1 404 Not Found]
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [shrink-stkv-.ds-logs-dakdrclfzi-2025.04.12-000001]","resource.type":"index_or_alias","resource.id":"shrink-stkv-.ds-logs-dakdrclfzi-2025.04.12-000001","index_uuid":"_na_","index":"shrink-stkv-.ds-logs-dakdrclfzi-2025.04.12-000001"}],"type":"index_not_found_exception","reason":"no such index [shrink-stkv-.ds-logs-dakdrclfzi-2025.04.12-000001]","resource.type":"index_or_alias","resource.id":"shrink-stkv-.ds-logs-dakdrclfzi-2025.04.12-000001","index_uuid":"_na_","index":"shrink-stkv-.ds-logs-dakdrclfzi-2025.04.12-000001"},"status":404}
```

**Issue Reasons:**
- [main] 3 failures in test testShrinkActionInPolicyWithoutHotPhase (0.3% fail rate in 889 executions)
- [main] 2 failures in step part-5 (0.5% fail rate in 418 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (0.5% fail rate in 417 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nielsbauman**
These tests had the potential to fail when subsequent requests would hit different nodes with different versions of the cluster state.

Only one of these tests failed already, but we fix the other ones proactively to avoid future failures.

Fixes #126746

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -2043,13 +2043,35 @@ protected Map<String, Object> getIndexMappingAsMap(String index) throws IOExcept
         return (Map<String, Object>) ((Map<String, Object>) indexMapping.get(index)).get("mappings");
     }
 
+    @SuppressWarnings("unchecked")
```
Comment (PeteGillinElastic) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java:2046]: Nit: I know it's nerdy of me, and this isn't production code, but I was always taught to suppress warnings at the narrowing possible scope, which I think on this case is just on the `indices` variable declaration.

If you can't be bothered making this change, I understand.

**Review by PeteGillinElastic — APPROVED** [review]
I think this makes sense. One nit — strictly optional. Thanks.

**Comment by nielsbauman** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/127015)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
