### PR TITLE
allocation: move shutdown explain to bulk/function shard variant

### LINKED ISSUE #140467: TransportGetShutdownStatusAction performance is O(N^2) over the number of shards
I have been looking at a production cluster with ~140,000 shards and noticed that multiple threads were at 100% in TransportGetShutdownStatusAction. I think that it's due to looping over all shards in an N^2 loop. Here's an example stack trace from a call to _nodes/hot_threads:

```
   100.3% [cpu=100.3%, other=0.0%] (501.6ms out of 500ms) cpu usage by thread 'elasticsearch[es-es-index-5cdbdd5db-xlgnq][management][T#6]'
     2/10 snapshots sharing following 43 elements
       java.base@25.0.1/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1080)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.buildModelFromAssigned(BalancedShardsAllocator.java:1249)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator$Balancer.<init>(BalancedShardsAllocator.java:332)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator.explainShardAllocation(BalancedShardsAllocator.java:253)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.cluster.routing.allocation.allocator.DesiredBalanceShardsAllocator.explainShardAllocation(DesiredBalanceShardsAllocator.java:259)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.cluster.routing.allocation.AllocationService.explainShardAllocation(AllocationService.java:798)
       org.elasticsearch.shutdown@9.4.0/org.elasticsearch.xpack.shutdown.TransportGetShutdownStatusAction.lambda$shardMigrationStatus$6(TransportGetShutdownStatusAction.java:285)
       org.elasticsearch.shutdown@9.4.0/org.elasticsearch.xpack.shutdown.TransportGetShutdownStatusAction$$Lambda/0x0000000088d1f430.apply(Unknown Source)
       java.base@25.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
       java.base@25.0.1/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:577)
       java.base@25.0.1/java.util.Iterator.forEachRemaining(Iterator.java:133)
       java.base@25.0.1/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
       java.base@25.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
       java.base@25.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
       java.base@25.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:635)
       java.base@25.0.1/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:291)
       java.base@25.0.1/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:652)
       java.base@25.0.1/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:658)
       java.base@25.0.1/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:663)
       org.elasticsearch.shutdown@9.4.0/org.elasticsearch.xpack.shutdown.TransportGetShutdownStatusAction.shardMigrationStatus(TransportGetShutdownStatusAction.java:294)
       org.elasticsearch.shutdown@9.4.0/org.elasticsearch.xpack.shutdown.TransportGetShutdownStatusAction.lambda$masterOperation$1(TransportGetShutdownStatusAction.java:146)
       org.elasticsearch.shutdown@9.4.0/org.elasticsearch.xpack.shutdown.TransportGetShutdownStatusAction$$Lambda/0x0000000088d1e8a0.apply(Unknown Source)
       java.base@25.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
       java.base@25.0.1/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:197)
       java.base@25.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:214)
       java.base@25.0.1/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
       java.base@25.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
       java.base@25.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
       java.base@25.0.1/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
       java.base@25.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
       java.base@25.0.1/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:723)
       org.elasticsearch.shutdown@9.4.0/org.elasticsearch.xpack.shutdown.TransportGetShutdownStatusAction.masterOperation(TransportGetShutdownStatusAction.java:162)
       org.elasticsearch.shutdown@9.4.0/org.elasticsearch.xpack.shutdown.TransportGetShutdownStatusAction.masterOperation(TransportGetShutdownStatusAction.java:60)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:113)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:229)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$$Lambda/0x0000000088ce8000.accept(Unknown Source)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1113)
       app/org.elasticsearch.server@9.4.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
       java.base@25.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
       java.base@25.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
       java.base@25.0.1/java.lang.Thread.runWith(Thread.java:1487)
       java.base@25.0.1/java.lang.Thread.run(Thread.java:1474)
```
It looks like we loop through all started shards in `TransportGetShutdownStatusAction::shardMigrationStatus`, and then for each of those we construct a `BalancedShardsAllocator$Balancer` object, and its constructor loops over all shards in `BalancedShardsAllocator::buildModelFromAssigned`.

### PR DESCRIPTION
**Pull request by schase-es**
GetShutdownStatusAction calls into AllocationService.explainShardAllocation for each shard. Down in the BalancedShardsAllocator, this creates a new Balancer object, which constructs a map of ModelNodes with weights needed for sorting the cluster and making allocation decisions. This map operation is intensive, and is order(nodes) in length. Because this is called for every shard on a node shutting down, this is order(shards * nodes). This adds a bulk explainShardsAllocation API, which returns a function that reuses a Balancer internally.

Fixes: #140467, ES-13973

### CODE REVIEW

**Comment by schase-es** [comment]
This is an alternative to https://github.com/elastic/elasticsearch/pull/142443, which allows the kind of flexibility and future changes @DaveCTurner mentioned here: https://github.com/elastic/elasticsearch/issues/140467#issuecomment-3755349013

(I'm not sure async is the right name for it, but also unsure what to call it.)

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocator.java [hunk 1]
```diff
@@ -81,4 +83,16 @@ default RoutingExplanations execute(RoutingAllocation allocation, AllocationComm
...
+     * Bulk explain over a bunch of shards
+     */
+    default Function<ShardRouting, ShardAllocationDecision> explainShardAllocationAsync(final RoutingAllocation allocation) {
+        return new Function<ShardRouting, ShardAllocationDecision>() {
+            @Override
+            public ShardAllocationDecision apply(ShardRouting shardRouting) {
+                return explainShardAllocation(shardRouting, allocation);
+            }
+        };
+    }
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocator.java:101]: A few comments:
1. Can we expand the javadocs a bit more to include why such a method is needed when we already have the method for single shard? 
2. The default implementation basically degenerates to a loop over the single shard version. That does not seem to be helpful since the very goal of this method is to avoid a simple implementation like that. IIUC, this default implementation is here so that subclasses used in tests do not have to change. In that case, I'd prefer we throw UnsupportedOperationException in the default implementation.
3. Instead of `explainShardAllocationAsync`, what about something like `createExplainShardAllocationFunc`. I am not a fan of calling it `Async` since it really is not.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java [hunk 2]
```diff
@@ -799,6 +799,11 @@ public ShardAllocationDecision explainShardAllocation(ShardRouting shardRouting,
         }
     }
 
+    public Function<ShardRouting, ShardAllocationDecision> explainAssignedShardAllocationAsync(RoutingAllocation allocation) {
+        assert allocation.debugDecision();
+        return shardsAllocator.explainShardAllocationAsync(allocation);
```
Comment (ywangd) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java]: Since this should only be applied to assigned shards, I think we want to wrap the function

```suggestion
        final var func = shardsAllocator.explainShardAllocationAsync(allocation)
        if (Assertions.ENABLED) {
            return shard -> {
                assert shard.unassigned() == false;
                return func.apply(shard);
            };
        } else {
            return func;
        }     
```

**Review by ywangd — COMMENTED** [review]
I like this version better than #142443 which concerns me with its list allocations.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocator.java (hunk 1 above)
Comment (schase-es) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/ShardsAllocator.java:101]: Good idea -- all set

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java (hunk 2 above)
Comment (schase-es) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java]: Ah, I haven't seen the explicit Assertions.ENABLED check before -- this makes this more efficient for production use. Thanks!

**Comment by schase-es** [comment]
I like this version too, though it took a while to come up with.

I've closed out the other one. Please let me know if there is any testing you'd like to see.

File: docs/changelog/142620.yaml [hunk 3]
```diff
@@ -0,0 +1,6 @@
+area: Allocation
+issues:
+ - 140467
+pr: 142620
+summary: "Allocation: move shutdown explain to bulk/async shard API"
+type: bug
```
Comment (ywangd) [inline docs/changelog/142620.yaml]: 1. I don't think it's really a bug. I'd be OK with it being a `>non-issue` since it is not really visible to user and currently most just for serverless impact. But I am also OK with `>enhancement` if you prefer.
2. If we don't want to label it as `>non-issue`, can we remove `async` from the summary? Also can we make it clear that this is an internal optimization. The API seems to suggest it's accessible to end users which is not the case.

File: x-pack/plugin/shutdown/src/main/java/org/elasticsearch/xpack/shutdown/TransportGetShutdownStatusAction.java [hunk 4]
```diff
@@ -278,11 +279,14 @@ static ShutdownShardMigrationStatus shardMigrationStatus(
         }
 
         // Get all shard explanations
+        final Function<ShardRouting, ShardAllocationDecision> allocationExplainFunction = allocationService
+            .explainAssignedShardAllocationFunction(allocation);
```
Comment (ywangd) [inline x-pack/plugin/shutdown/src/main/java/org/elasticsearch/xpack/shutdown/TransportGetShutdownStatusAction.java]: If we are really keen, we could make this function creation lazy in case there is no started shard on this node to explain. The polling interval is `30s` in serverless. So it runs every 30 seconds. When the node has no started shard to explain, it is likely about to complete shutdown. So it probably does not matter if we eagerly create the func unnecessarily a few times.

**Review by ywangd — APPROVED** [review]
LGTM 

A few comments that I'd appreciate if you could address them. Thanks!
