### PR TITLE
Retry after all S3 get failures that made progress

### LINKED ISSUE #87243: Increase tenacity of S3RetryingInputStream
The `S3RetryingInputStream` hides cases where S3 closes a connection partway through downloading a blob. By default it retries 3 times before failing the download. However, the number of failures tends to increase on larger blobs and often 3 failures is not enough to complete a multi-GB download if S3 is suffering from a cluster of failures as sometimes happens. Typically we make 10s-to-100s of MBs of progress between each failure even in this state.

I think we should increase the tenacity of `S3RetryingInputStream` when downloading larger blobs. For instance, we could not count a partial download towards the retry limit if it makes significant progress before failing.

### PR DESCRIPTION
**Pull request by DaveCTurner**
S3 sometimes enters a state where blob downloads repeatedly fail but
with nontrivial progress between failures. Often each attempt yields 10s
or 100s of MBs of data. Today we abort a download after three (by
default) such failures, but this may not be enough to completely
retrieve a large blob during one of these flaky patches.

With this commit we start to avoid counting download attempts that
retrieved at least 1% of the configured `buffer_size` (typically 1MB)
towards the maximum number of retries.

Closes #87243

### CODE REVIEW

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RetryingInputStream.java [hunk 1]
```diff
@@ -160,31 +162,31 @@ private void ensureOpen() {
...
-                blobKey,
-                start + currentOffset,
-                attempt,
-                maxAttempts
-            ),
-            e
+        final Supplier<String> messageSupplier = () -> format(
+            """
+                failed reading [%s/%s] at offset [%s]; this was attempt [%s] to read this blob which yielded [%s] bytes; in total \
+                [%s] of the attempts to read this blob have made meaningful progress; the maximum number of attempts is [%s]""",
```
Comment (kingherc) [inline modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RetryingInputStream.java:175]: This log line will be a bit weird because it will say something like:

> this was attempt 103; in total 100 of the attempts made meaningful progress; the maximum number of attempts is 3.

Feels a bit weird that 103 >> 3. Maybe to make it more clear you could say at the end "the maximum number of attempts **(without meaningful progress)** is 3".

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java [hunk 2]
```diff
@@ -439,6 +443,82 @@ public void testWriteLargeBlobStreaming() throws Exception {
...
+        final int meaningfulProgressBytes = Math.max(1, bufferSizeBytes / 100);
+
+        final byte[] bytes = randomBlobContent();
+
+        @SuppressForbidden(reason = "use a http server")
+        class FlakyReadHandler implements HttpHandler {
+            private int failuresWithoutProgress;
+
+            @Override
+            public void handle(HttpExchange exchange) throws IOException {
```
Comment (kingherc) [inline modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java:462]: So here basically you first exhaust the "meaningless" failures, and then have a series of failures with meaningful progress that should not finally throw an exception and the blob should be successfully read (either in its entirety or partly).

**Review by kingherc — APPROVED** [review]
LGTM. Left one optional comment.

Of course please do not count my sole review for now -- it's my first review. Thanks for adding me!

File: modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RetryingInputStream.java (hunk 1 above)
Comment (DaveCTurner) [reply modules/repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3RetryingInputStream.java:175]: :+1: good point

File: modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java (hunk 2 above)
Comment (DaveCTurner) [reply modules/repository-s3/src/test/java/org/elasticsearch/repositories/s3/S3BlobContainerRetriesTests.java:462]: Yep, pretty much, although note that `sendIncompleteContent` will sometimes send a meaningful amount of data too.

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/bwc - failure tracked at https://github.com/elastic/elasticsearch/issues/87959

**Review by tlrx — APPROVED** [review]
LGTM
