### PR TITLE
[Transform] fixing naming in HLRC and _cat to match API content

### LINKED ISSUE #53946: [Transform] Field naming is inconsistent between _stats, HLRC and _cat
As #53776 shows the naming of some fields is inconsistent between the ouput of `_stats`, the HLRC getters in code and what `_cat/transform` returns.

The problem seems to originate from HLRC inheriting the getters from the shared code IndexerStats object. However, we renamed some fields which in the server code is benign.

- fix naming in HLRC so its consistent with field naming of xcontent
- use consistent naming of fields in `_cat/transform`
- (optional) have consistent getters/setters in the server code (optional, because its non-public, however it's good to have it consistent)

(This is non-breaking if we keep the old getters/setters and only add new ones)

### PR DESCRIPTION
**Pull request by benwtrent**
Fixing the naming of the HLRC values to match the ToXContent field names (i.e. the field names returned from an API call). 

Also fixes the names in the _cat API as well.

closes https://github.com/elastic/elasticsearch/issues/53946

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by hendrikmuhs** [comment]
FYI @lcawl

File: client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java [hunk 1]
```diff
@@ -29,11 +28,24 @@
...
     static ParseField EXPONENTIAL_AVG_CHECKPOINT_DURATION_MS = new ParseField("exponential_avg_checkpoint_duration_ms");
     static ParseField EXPONENTIAL_AVG_DOCUMENTS_INDEXED = new ParseField("exponential_avg_documents_indexed");
     static ParseField EXPONENTIAL_AVG_DOCUMENTS_PROCESSED = new ParseField("exponential_avg_documents_processed");
+    static ParseField PAGES_PROCESSED = new ParseField("pages_processed");
+    static ParseField DOCUMENTS_PROCESSED = new ParseField("documents_processed");
+    static ParseField DOCUMENTS_INDEXED = new ParseField("documents_indexed");
+    static ParseField TRIGGER_COUNT = new ParseField("trigger_count");
+    static ParseField INDEX_TIME_IN_MS = new ParseField("index_time_in_ms");
+    static ParseField SEARCH_TIME_IN_MS = new ParseField("search_time_in_ms");
+    static ParseField PROCESSING_TIME_IN_MS = new ParseField("processing_time_in_ms");
```
Comment (lcawl) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java]: > processing_time_in_ms

Does this mean we need to add this property to the stats object in https://www.elastic.co/guide/en/elasticsearch/reference/master/get-transform-stats.html ?

File: client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java [hunk 2]
```diff
@@ -29,11 +28,24 @@
...
+    static ParseField INDEX_TOTAL = new ParseField("index_total");
+    static ParseField SEARCH_TOTAL = new ParseField("search_total");
+    static ParseField PROCESSING_TOTAL = new ParseField("processing_total");
```
Comment (lcawl) [inline client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java]: > processing_total

This also doesn't appear in https://www.elastic.co/guide/en/elasticsearch/reference/master/get-transform-stats.html
Should it?

File: client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java (hunk 1 above)
Comment (hendrikmuhs) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java]: Sorry, that's my fault. In #53770 I added `processing_time_in_ms` and `processing_total`.

File: client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java (hunk 2 above)
Comment (benwtrent) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java]: i think it should be in stats. I am not 100% sure it should be in the `_cat` API though. Right now processing times are so small that they are pretty insignificant.

**Comment by benwtrent** [comment]
@elasticmachine update branch

File: client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java (hunk 1 above)
Comment (lcawl) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java]: Thanks, I've created https://github.com/elastic/elasticsearch/pull/54368 to add those.

File: client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java (hunk 2 above)
Comment (lcawl) [reply client/rest-high-level/src/main/java/org/elasticsearch/client/transform/transforms/TransformIndexerStats.java]: Likewise this will be fixed in https://github.com/elastic/elasticsearch/pull/54368

**Review by lcawl — APPROVED** [review]
Documentation LGTM
Preview: http://elasticsearch_54300.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/cat-transforms.html
