### PR TITLE
[ESQL] Fix first/last functions when used with timeseries

### LINKED ISSUE #142284: [ES|QL] PromQL without index and TS * | STATS ... fail
### Elasticsearch Version

9.4

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 24.6.0

### Problem Description

I am testing promQL and TS at kibana and I see a strange behavior

This query succeeds

```
PROMQL  index = kibana_sample_data_logstsdb step = "5m" col0 = (avg(rate(bytes_counter[5m])) by (geo.dest) )
```

While this fails

```
PROMQL step = "5m" col0 = (avg(rate(bytes_counter[5m])) by (geo.dest) )
```

The index is optional so it should work as the above but for all timeseries indices. The error is 

```
illegal_state_exception - Found 1 problem
line 1:28: Plan [TimeSeriesAggregate[[_tsid{m}#30085, step{r}#29944],[RATE(bytes_counter{r}#30040,true[BOOLEAN],PT5M[TIME_DURATION],@timestamp{r}#30
036) AS RATE_$1#30086, step{r}#29944 AS step#29944, VALUES(geo.dest{r}#30048,true[BOOLEAN],PT0S[TIME_DURATION]) AS geo.dest#30048],
BUCKET(@timestamp{r}#30036,PT5M[TIME_DURATION]),@timestamp{r}#30036]] optimized incorrectly due to missing references [_tsid{m}#30085]
```

We discussed it with Felix and he told me to also test the 

```
TS * | STATS count(bytes) by geo.dest
```

This fails too with the same error

### Steps to Reproduce

Try to run a PromQL query without giving the index

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by sidosera**
A recent alert uncovered crashes in TS queries with errors like:

```text
Plan [Aggregate[[pack_attributes.session.id_$1{r}#5067],[LAST(DEFAULTTIMESERIESAGGREGATEFUNCTION_$1{r}#5065,true[BOOLEAN],PT0S[TIME_DURATION],@timestamp{f}#4994) AS final_session_cost#4801]]] optimized incorrectly due to missing references [@timestamp{f}#4994]
```

Root cause: 

This happens when  LAST(field, sortBy) or FIRST(field, sortBy) is used with with TS queries. Time series aggregates are performed in two stages: first by _tsid and bucket (if provided) and then by whatever aggregate function supply. The first phase leaves bare sortBy (e.g. `@timestamp`), so the second phase ends up referencing an attribute not produced by the first phase.

Fix: 

Wrap the sortBy argument of LAST/FIRST with MAX/MIN. Both are `TimeSeriesAggregateFunction` subclasses, and existing translation pipeline handles them naturally during the split, with no extra handling.

Issue: https://github.com/elastic/elasticsearch/issues/144411

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java [hunk 1]
```diff
@@ -68,6 +94,18 @@ private static Expression addDefaultInnerAggs(Expression expression, Expression
...
+                // For Last/First, also wrap the sort parameter so it gets handled by the two-phase split
+                // in TranslateTimeSeriesAggregate (sort is typically @timestamp which must be passed through).
+                case Last last -> {
+                    Expression newField = addDefaultInnerAggs(last.field(), timestamp, changed);
+                    Expression newSort = wrapSortField(last.sort(), changed, MaxOverTime::new);
+                    yield last.replaceChildren(List.of(newField, last.filter(), last.window(), newSort));
+                }
+                case First first -> {
+                    Expression newField = addDefaultInnerAggs(first.field(), timestamp, changed);
+                    Expression newSort = wrapSortField(first.sort(), changed, MinOverTime::new);
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java]: `addDefaultInnerAggs` wraps the value field with DefaultTimeSeriesAggregateFunction (which delegates to LastOverTime) and `wrapSortField` wraps the sort field with `MinOverTime/MaxOverTime`. These are independent aggregations in phase 1, so they can pick values from different documents within the same _tsid.

For example, with `FIRST(cpu, @timestamp)` and a single _tsid:

```
_tsid=A:  t1 -> cpu=10, t2 ->cpu=99
Phase 1:  LastOverTime(cpu)=99, Min(@timestamp)=t1
Phase 2:  FIRST(99, t1) -> should be (10, t1) instead
```

The same thing can happen with LAST when the sort field is not `@timestamp`, since LastOverTime is always keyed on `@timestamp` while Max(sort) operates on a different field - though this is less common.

Would it make sense to check whether the sort field is `@timestamp`? If so, convert to LastOverTime/FirstOverTime (so value and sort stay correlated). For cases where the sort field is not `@timestamp`, wrap both the value and sort fields with FirstOverTime (for FIRST) or LastOverTime (for LAST) so they pick from the same document in phase 1. WDYT?

**Review by dnhatn — COMMENTED** [review]
I left a comment. Thanks for the investigation @sidosera

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java (hunk 1 above)
Comment (sidosera) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java]: Good catch, Nhat. Fixed.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java [hunk 2]
```diff
@@ -67,6 +83,27 @@ private static Expression addDefaultInnerAggs(Expression expression, Expression
...
                 case TimeSeriesAggregateFunction ts -> ts;
+                // Last/First have a sort parameter that must also be wrapped so TranslateTimeSeriesAggregate
+                // handles it during the two-phase split. Field and sort use correlated over-time functions
+                // to ensure they pick from the same document within a _tsid group.
+                case Last last when last.sort() instanceof TimeSeriesAggregateFunction == false -> wrapSortedAgg(
+                    last,
+                    last.sort(),
+                    timestamp,
+                    changed,
+                    new DefaultTimeSeriesAggregateFunction(last.field(), timestamp),
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/InsertDefaultInnerTimeSeriesAggregate.java:94]: nit: maybe create LastOverTime directly here instead.

File: server/src/main/java/org/elasticsearch/common/PentaFunction.java [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+ * or more contributor license agreements. Licensed under the "Elastic License
+ * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
+ * Public License v 1"; you may not use this file except in compliance with, at
+ * your election, the "Elastic License 2.0", the "GNU Affero General Public
+ * License v3.0 only", or the "Server Side Public License, v 1".
+ */
+
+package org.elasticsearch.common;
+
+public interface PentaFunction<T, U, V, W, X, R> {
```
Comment (dnhatn) [inline server/src/main/java/org/elasticsearch/common/PentaFunction.java:12]: nit: Should we add `@FunctionalInterface` here?

**Review by dnhatn — APPROVED** [review]
LGTM, thanks for iterating on this @sidosera.
