### PR TITLE
[Test] Fix CRUDDocumentationIT

### LINKED ISSUE #28446: [CI] CRUDDocumentationIT.testUpdate fails on 5.6
Link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-unix-compatibility/os=sles/629/console

```
./gradlew :client:rest-high-level:integTestRunner -Dtests.seed=DD79E663948D17FD -Dtests.class=org.elasticsearch.client.documentation.CRUDDocumentationIT -Dtests.method="testUpdate" -Dtests.security.manager=true -Dtests.locale=ar-BH -Dtests.timezone=Indian/Antananarivo
```

```
17:32:09    > Throwable #1: [posts/4LhljGVTQZ6AWgrE2bR3nw][[posts][3]] ElasticsearchStatusException[Elasticsearch exception [type=version_conflict_engine_exception, reason=[doc][1]: version conflict, current version [9] is different than the one provided [8]]]
17:32:09    > 	at __randomizedtesting.SeedInfo.seed([DD79E663948D17FD:6B6FA369F249FF2B]:0)
17:32:09    > 	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
17:32:09    > 	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:526)
17:32:09    > 	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:502)
17:32:09    > 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:409)
17:32:09    > 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:382)
17:32:09    > 	at org.elasticsearch.client.RestHighLevelClient.update(RestHighLevelClient.java:285)
17:32:09    > 	at org.elasticsearch.client.documentation.CRUDDocumentationIT.testUpdate(CRUDDocumentationIT.java:444)
```

### PR DESCRIPTION
**Pull request by tlrx**
Similarly to other documentation tests in the high level client, the
asynchronous operation like update, index or delete can make the test
fail if it sneak in between the middle of another operation.

This commit moves the async doc tests to be the last ones executed and
adds await busy loops to ensure that the asynchronous operations are
correctly terminated.

closes #28446

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
I expect `assertBusy` will produce better error messages one failure. Also, I don't think you had to move these to the last ones, right? I don't mind either way, but just for my own sanity, can you confirm that or correct me?

**Review by javanna — APPROVED** [review]
LGTM I would do assertBusy too, I am curious about the answers to Nik's questions too.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java [hunk 1]
```diff
@@ -240,9 +225,34 @@ public void onFailure(Exception e) {
...
+            });
+            // end::index-execute-async
+
+            assertTrue(awaitBusy(() -> {
+                try {
+                    return client.exists(new GetRequest("posts", "doc", "async"));
+                } catch (IOException e) {
+                    return false;
+                }
+            }));
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: what happens if we don't wait for this one?

Comment (javanna) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: I was also thinking, given that this is a recurring problem and we don't want to have latches to show in our docs, shall we make this more clear doing something through a listener that blocks (without showing in the snippets what the listener really does)?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java [hunk 2]
```diff
@@ -497,9 +493,34 @@ public void onFailure(Exception e) {
...
+            });
+            // end::update-execute-async
+
+            assertTrue(awaitBusy(() -> {
+                try {
+                    return client.exists(new GetRequest("posts", "doc", "async"));
+                } catch (IOException e) {
+                    return false;
+                }
+            }));
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: once you have changed the id of the update, it won't sneak in anymore and cause version conflict, so I think it doesn't necessarily needs to be moved down? But maybe it's good like you did. Maybe we don't even need to wait for it at this point?

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java [hunk 3]
```diff
@@ -601,6 +608,34 @@ public void onFailure(Exception e) {
...
+            });
+            // end::delete-execute-async
+
+            assertTrue(awaitBusy(() -> {
+                try {
+                    return client.exists(new GetRequest("posts", "doc", "async")) == false;
+                } catch (IOException e) {
+                    return false;
+                }
+            }));
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: same comment as above, once we change the id, do we need to still wait for it?

**Comment by tlrx** [comment]
Thanks for the reviews @nik9000 and @javanna.

> Also, I don't think you had to move these to the last ones, right?

This is not a requirement of course but some tests use the same document (like /posts/doc/1) and update or index it multiple times. Since I changed the async operations to use a different doc I moved them down so that it does not interleave with other request executions as I found this more readable.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java (hunk 2 above)
Comment (tlrx) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: That was for readability, as some test use the same document to index or update multiple times. But I can move them back if you prefer.

> Maybe we don't even need to wait for it at this point?

We need to wait  for any writing operation, but we can relax this for read operations.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java (hunk 1 above)
Comment (tlrx) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: > what happens if we don't wait for this one?

After each test method, the `ESRestTestCase.cleanUpCluster()` is executed. As you know this method deletes the cluster indices, waits for the pending cluster states tasks to finish and logs a message if there is still inflight requests. 

By not waiting for the async request to respond, it's possible that an index got re created because the index (or update) operation is processed after the indices have been deleted and s recreates the index and breaks following tests. 

I'm pretty sure I saw this error, but sadly I can't find a test execution log that clearly shows this behavior. In any way I think it's better to wait for the completion of any write operation that could recreate an index for the reason I mentioned.

Comment (javanna) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: makes sense, thanks for explaining.

Comment (javanna) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: what do you think about the listener idea above?

Comment (tlrx) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: I'd prefer to have a blocking listener than assertBusy loops but I guess we'll have to declare a simple listener just for the doc purpose like:

```
//tag::listener
ActionListener<IndexResponse> listener = new ActionListener<IndexResponse>() {
                @Override
                public void onResponse(IndexResponse indexResponse) {
                    // <1>
                }

                @Override
                public void onFailure(Exception e) {
                    // <2>
                }
            };
//end::listener
```

Then, out of documented snippet replace the listener by a blocking one:

```
// Replace the listener by a blocking one
final CountDownLatch latch = new CountDownLatch(1);
listener = new ActionListener<IndexResponse> {
.. use latch in on response/onfailure methods here
}
```

And finally show the async execution snippet using the listener reference:
```
// tag::index-execute-async
client.indexAsync(request, listener);
//end::async
```

Is that what you have in mind?

Comment (javanna) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: yea this sounds good to me.

Comment (tlrx) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: This will have an impact on documentation (2 code snippets instead of one), should we align all documentation for async execution to be like this? I think so.

Comment (javanna) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: yes I would adapt the docs, let me know if you prefer me to take this over given that it's becoming a bigger task.

Comment (tlrx) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: I can do it. Do you prefer a follow up PR or be part of this one?

Comment (javanna) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/CRUDDocumentationIT.java]: I don't mind either way
