### PR TITLE
Prevent writing to closed channel if translog is already closed

### LINKED ISSUE #14866: Bulk items fail due to TranslogException via ClosedChannelException
We recently made the jump to start testing ES 2.0 against our codebase, which was pretty straightforward with only a couple of changes on the Query DSL.

However, once we put this into our test environment, we see constant streams of this (please note I have removed sensitive information, such as source, index and type):

```
[2015-11-19 18:21:10,865][DEBUG][action.bulk              ] [La Nuit] [pem:2015:47][5] failed to execute bulk item (index) index {[my-index][my-type][3279b5669abaf1458583678b37bbf2a2], source[{"my-source":true}]}
[my-index][[my-index][5]] TranslogException[Failed to write operation [Index{id='3279b5669abaf1458583678b37bbf2a2', type='my-type'}]]; nested: ClosedChannelException;
	at org.elasticsearch.index.translog.Translog.add(Translog.java:497)
	at org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:532)
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:447)
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:556)
	at org.elasticsearch.index.engine.Engine$Index.execute(Engine.java:815)
	at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1073)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:338)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:131)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:199)
	at org.elasticsearch.common.io.Channels.writeToChannel(Channels.java:206)
	at org.elasticsearch.index.translog.BufferingTranslogWriter.flush(BufferingTranslogWriter.java:75)
	at org.elasticsearch.index.translog.BufferingTranslogWriter.add(BufferingTranslogWriter.java:62)
	at org.elasticsearch.index.translog.Translog.add(Translog.java:489)
	... 13 more
```

This is a pretty constant thing, and there seems to be nothing around about what might cause it. All of our ES settings are pretty much the defaults, and we haven't (deliberately) changed anything between versions. 

Is there some change in ES 2.0 which might explain the above, such as maybe tweaking default thread counts for bulk (etc)? If so, where would I start looking to resolve this exception?

If I had to guess at the rate of failure, I'd say that `> 50%` of bulk items receive this error. 

I'm not sure if this is related, but this is also showing up inside the logs; perhaps something regarding indexing is badly configured?

```
[2015-11-19 18:21:48,456][WARN ][indices.memory           ] [La Nuit] failed to set shard [my-index][4] index buffer to [309.3mb]
```

### PR DESCRIPTION
**Pull request by s1monw**
We handle AlreadyClosedExceptions gracefully wherever IndexShard / Engine
is used. In some cases, instead of throwing the appropriate exception we
bubble up ChannelClosedException instead which causes shard failures etc.
Today, it seems like that this can only happen if the engine is closed without
acquireing the lock which means that the shard has failed already so the impact is really
just a confusing log message. Yet, this change enforces throwing the right exception
if the translog is already closed.

Closes #14866

### CODE REVIEW

**Comment by mikemccand** [comment]
LGTM

File: core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java [hunk 1]
```diff
@@ -46,6 +46,7 @@ public BufferingTranslogWriter(ShardId shardId, long generation, ChannelReferenc
 
     @Override
     public Translog.Location add(BytesReference data) throws IOException {
+        ensureOpen();
```
Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: should this be under lock?

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: well - we have the parent one under lock. I am tempted to remove the one here altogether or just keep them

Comment (bleskes) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: you mean removing the ensure open? +1 on that.  Sadly I see the same out of lock pattern in the Translog class as well:

```
        ensureOpen();
        ImmutableTranslogReader toClose = null;
        try (ReleasableLock lock = writeLock.acquire()) {
```

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/index/translog/BufferingTranslogWriter.java]: this is not too much of a deal here but I can move these into the write lock block. On those methods it's really just best effort anyway. The add method has it in the right place. 

> you mean removing the ensure open? +1 on that.

I can't remove it completely I think but it's confusing and need to be used consistently. I wanna do that in a different PR since I wanna backport this one to a release branch

**Comment by s1monw** [comment]
@bleskes I reviewed all the code again and moved ensureOpen calls under lock where necessary / possible

**Comment by bleskes** [comment]
awesome. Thanks @s1monw .

**Comment by bleskes** [comment]
i.e., LGTM^2

**Comment by s1monw** [comment]
I backported this to 2.0.2, 2.1.1, and 2.2
