### PR TITLE
Active shards message corrected for search shards

### LINKED ISSUE #101896: Misleading error message for search shard unavailablity in stateless
The following error message emitted from org.elasticsearch.action.support.replication.ReplicationOperation is misleading:

```
Not enough active copies to meet shard count of [1] (have 1, needed 1)
```

full context:
```
org.elasticsearch.transport.RemoteTransportException: [es-es-index-58f985f8f-pgls6][10.2.12.197:9300][indices:data/write/bulk[s][p]]
Caused by: org.elasticsearch.action.UnavailableShardsException: [.security-7][0] Not enough active copies to meet shard count of [1] (have 1, needed 1). Timeout: [1m], request: [BulkShardRequest [[.security-7][0]] containing [index {[.security][myrole], source[{"enabled":true,"roles":["myrole"],"rules":{"all":[{"field":{"realm.name":"myrealm"}},{"field":{"username":"me"}}]},"metadata":{},"doc_type":"role-mapping"}]}] and a refresh]
```

The message appears to be due to the calculation for wait_for_active_shards only counts search shards, but the message is constructed by counting all shards. In stateless this message can mean that the search shard is not available.

### PR DESCRIPTION
**Pull request by kingherc**
Note that the broader topic of waiting for active shards in the context of stateless is handled in ES-7302. This only fixes the message returned to mention the search shards (that the logic considers when calculating the boolean to return).

For example, if no search shard is active, the message was previously returning "(have 1, need 1)" because it was considering the primary shard. However it is now corrected to say "have 0" since the logic considers only search shards.

Fixes #101896

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/support/ActiveShardCount.java [hunk 1]
```diff
@@ -164,19 +165,23 @@ public boolean enoughShardsActive(final ClusterState clusterState, final String.
     }
 
     /**
-     * Returns true iff the active shard count in the shard routing table is enough
-     * to meet the required shard count represented by this instance.
+     * Returns a tuple where the first value is true iff the active shard count in the shard routing table is enough
+     * to meet the required shard count represented by this instance, and the second value is the active shard count.
      */
-    public boolean enoughShardsActive(final IndexShardRoutingTable shardRoutingTable) {
+    public Tuple<Boolean, Integer> enoughShardsActive(final IndexShardRoutingTable shardRoutingTable) {
```
Comment (idegtiarenko) [inline server/src/main/java/org/elasticsearch/action/support/ActiveShardCount.java:171]: Since this is a public method, should it return a record? Not sure about naming though. `EnoughShards`?

**Review by idegtiarenko — APPROVED** [review]
Overall :+1: with one suggestion

File: server/src/main/java/org/elasticsearch/action/support/ActiveShardCount.java (hunk 1 above)
Comment (kingherc) [reply server/src/main/java/org/elasticsearch/action/support/ActiveShardCount.java]: Thanks @idegtiarenko ! Sure, made a record.

File: server/src/main/java/org/elasticsearch/action/support/ActiveShardCount.java [hunk 2]
```diff
@@ -164,19 +164,30 @@ public boolean enoughShardsActive(final ClusterState clusterState, final String.
...
         } else if (value == 1) {
-            return shardRoutingTable.hasSearchShards() ? shardRoutingTable.getActiveSearchShardCount() >= 1 : activeShardCount >= 1;
+            if (shardRoutingTable.hasSearchShards()) {
+                return new EnoughShards(shardRoutingTable.getActiveSearchShardCount() >= 1, shardRoutingTable.getActiveSearchShardCount());
+            } else {
+                return new EnoughShards(activeShardCount >= 1, activeShardCount);
+            }
         } else {
-            return shardRoutingTable.getActiveSearchShardCount() >= value;
+            return new EnoughShards(shardRoutingTable.getActiveSearchShardCount() >= value, shardRoutingTable.getActiveSearchShardCount());
```
Comment (tlrx) [inline server/src/main/java/org/elasticsearch/action/support/ActiveShardCount.java:190]: nit: to help with readability, maybe use local variables for activeShardCount and enoughShards and then instanciate he EnoughShard record when returning at the end of the method?

File: server/src/test/java/org/elasticsearch/action/support/replication/ReplicationOperationTests.java [hunk 3]
```diff
@@ -439,10 +440,15 @@ public void testWaitForActiveShards() throws Exception {
         final int unassignedReplicas = randomInt(2);
         final int totalShards = 1 + assignedReplicas + unassignedReplicas;
         final int activeShardCount = randomIntBetween(0, totalShards);
+        final boolean stateless = randomBoolean();
```
Comment (tlrx) [inline server/src/test/java/org/elasticsearch/action/support/replication/ReplicationOperationTests.java:443]:
```suggestion
        final boolean hasUnpromotableShards = randomBoolean();
```

File: server/src/test/java/org/elasticsearch/action/support/replication/ReplicationOperationTests.java [hunk 4]
```diff
@@ -439,10 +440,15 @@ public void testWaitForActiveShards() throws Exception {
...
         Request request = new Request(shardId).waitForActiveShards(
             activeShardCount == totalShards ? ActiveShardCount.ALL : ActiveShardCount.from(activeShardCount)
         );
-        final boolean passesActiveShardCheck = activeShardCount <= assignedReplicas + 1;
+        // In the case of stateless, only the search/replica assigned shards are calculated as active shards. But in other cases, or when
```
Comment (tlrx) [inline server/src/test/java/org/elasticsearch/action/support/replication/ReplicationOperationTests.java:447]: Maybe not mention stateless, but instead "unpromotable" (which has a meaning in core)

**Review by tlrx — APPROVED** [review]
LGTM, I left some minor comments
