### PR TITLE
Throw exception if unrecognized parameter in bulk action/metadata line

### LINKED ISSUE #10977: Throw exception if unrecognised params present in bulk request
If additional elements (like `_source`) are present in the metadata line of the bulk request body, some arguments get ignored. This is an example where `_id` gets ignored (works fine without the `_source` there):

    curl -XGET 'http://localhost:9200/?pretty'
    #[200] (0.002s)
    #{
    #  "cluster_name": "elasticsearch",
    #  "name": "Xemnu the Titan",
    #  "status": 200,
    #  "tagline": "You Know, for Search",
    #  "version": {
    #    "build_hash": "53bf0729d5cab01181e98d2de34c73a97fa2b1f8",
    #    "build_snapshot": true,
    #    "build_timestamp": "2015-05-05T10:11:47Z",
    #    "lucene_version": "4.10.4",
    #    "number": "1.6.0"
    #  }
    #}
    curl -XPUT 'http://localhost:9200/test?pretty' -d ''
    #[200] (0.095s)
    #{
    #  "acknowledged": true
    #}
    curl -XPOST 'http://localhost:9200/test/_bulk?pretty&refresh=true' -d '{"index": {"_index": "test", "_type": "doc", "_source": {"hello": "world"}, "_id": 0}}
    {"idx": 0}
    '
    #[200] (0.089s)
    #{
    #  "errors": false,
    #  "items": [
    #    {
    #      "create": {
    #        "_id": "AU0jlPM2pgX4WOPmtASc",
    #        "_index": "test",
    #        "_type": "doc",
    #        "_version": 1,
    #        "status": 201
    #      }
    #    }
    #  ],
    #  "took": 85
    #}

### PR DESCRIPTION
**Pull request by tlrx**
It now throws an exception when an action/metadataline of a bulk request contains an unknown parameter or object like:

``` json
{"index": {"_index": "test", "_type": "doc", "_id": 1, "_foo": "bar"}}
```

``` json
{"index": {"_index": "test", "_type": "doc", "_id": 2, "_unkown": ["foo", "bar"]}}
```

Closes #10977

### CODE REVIEW

File: src/main/java/org/elasticsearch/action/bulk/BulkRequest.java [hunk 1]
```diff
@@ -285,41 +287,48 @@ public BulkRequest add(BytesReference data, @Nullable String defaultIndex, @Null
...
-                        } else if ("_routing".equals(currentFieldName) || "routing".equals(currentFieldName)) {
-                            routing = parser.text();
-                        } else if ("_parent".equals(currentFieldName) || "parent".equals(currentFieldName)) {
-                            parent = parser.text();
-                        } else if ("_timestamp".equals(currentFieldName) || "timestamp".equals(currentFieldName)) {
-                            timestamp = parser.text();
-                        } else if ("_ttl".equals(currentFieldName) || "ttl".equals(currentFieldName)) {
-                            if (parser.currentToken() == XContentParser.Token.VALUE_STRING) {
-                                ttl = TimeValue.parseTimeValue(parser.text(), null).millis();
+                if (token == XContentParser.Token.START_OBJECT) {
```
Comment (bleskes) [inline src/main/java/org/elasticsearch/action/bulk/BulkRequest.java]: I think we want an else + exception for this if?

File: src/main/java/org/elasticsearch/action/bulk/BulkRequest.java [hunk 2]
```diff
@@ -285,41 +287,48 @@ public BulkRequest add(BytesReference data, @Nullable String defaultIndex, @Null
...
-                        } else if ("op_type".equals(currentFieldName) || "opType".equals(currentFieldName)) {
-                            opType = parser.text();
-                        } else if ("_version".equals(currentFieldName) || "version".equals(currentFieldName)) {
-                            version = parser.longValue();
-                        } else if ("_version_type".equals(currentFieldName) || "_versionType".equals(currentFieldName) || "version_type".equals(currentFieldName) || "versionType".equals(currentFieldName)) {
-                            versionType = VersionType.fromString(parser.text());
-                        } else if ("_retry_on_conflict".equals(currentFieldName) || "_retryOnConflict".equals(currentFieldName)) {
-                            retryOnConflict = parser.intValue();
+                        } else {
+                            throw new IllegalArgumentException("Action/metadata line [" + line + "] has a wrong format");
```
Comment (bleskes) [inline src/main/java/org/elasticsearch/action/bulk/BulkRequest.java]: can we add some more info about what expected found and the field name? maybe "expected a simple value for field '..' but found a [TYPE]"..

**Comment by bleskes** [comment]
awesome - extra bonus points for the line indication. Left some minor comments.

**Comment by tlrx** [comment]
@bleskes thanks for your review! I updated the code following your comments.

**Comment by bleskes** [comment]
LGTM

**Comment by s1monw** [comment]
this is likely breaking logstash see https://github.com/elastic/elasticsearch/issues/11458
