### PR TITLE
Fixing potential OOME in HistoryIntegrationTest.testThatHistoryIsTruncated()

### LINKED ISSUE #111530: [CI] HistoryIntegrationTests testThatHistoryIsTruncated failing
**Build Scans:**
- [elasticsearch-periodic #3638 / openjdk17_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/mepobu27omwoi)
- [elasticsearch-periodic #3638 / openjdk17_checkpart2_java-fips-matrix](https://gradle-enterprise.elastic.co/s/ovptnlfyd2olw)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:watcher:internalClusterTest" --tests "org.elasticsearch.xpack.watcher.test.integration.HistoryIntegrationTests.testThatHistoryIsTruncated" -Dtests.seed=1D682FCE9A4850 -Dtests.locale=sl-SI -Dtests.timezone=Asia/Tokyo -Druntime.java=17
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testThatHistoryIsTruncated'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.watcher.test.integration.HistoryIntegrationTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Issue Reasons:**
- [main] 2 failures in test testThatHistoryIsTruncated (20.0% fail rate in 10 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by masseyke**
HistoryIntegrationTest.testThatHistoryIsTruncated() sometimes results in an OutOfMemoryError. This happens when the cluster is started with multiple nodes and the test is using a 512 MB heap. The 20 MB watch gets stored as byte arrays several times, and it winds up being just enough to push us over the top.
This change uses a lower configured value for `xpack.watcher.max.history.record.size` in the test instead (which is good, because it also showed that that setting was not exposed in the plugin).
Closes #111530

### CODE REVIEW

File: x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/HistoryIntegrationTests.java [hunk 1]
```diff
@@ -261,13 +271,13 @@ public void testThatHistoryIsTruncated() throws Exception {
         }
         {
             /*
-             * The input for this watch is 20 MB, much bigger than the 10 MB default of HistoryStore's MAX_HISTORY_SIZE_SETTING. So we
+             * The input for this watch is 500 MB, much bigger than the configured 100 KB of HistoryStore's MAX_HISTORY_SIZE_SETTING. So we
```
Comment (jbaiera) [inline x-pack/plugin/watcher/src/internalClusterTest/java/org/elasticsearch/xpack/watcher/test/integration/HistoryIntegrationTests.java:274]: Typo
```suggestion
             * The input for this watch is 500 KB, much bigger than the configured 100 KB of HistoryStore's MAX_HISTORY_SIZE_SETTING. So we
```

**Review by jbaiera — APPROVED** [review]
LGTM
