### PR TITLE
[ML] Handle data frame analytics state spreading over multiple docs

### LINKED ISSUE #52476: [ML] Data Frame Analytics could fail to read stored state
The native code has a static limit on the size of documents it will write back to the process handler. 

https://github.com/elastic/ml-cpp/blob/6750684c0d10116f06afeac7735938c21d661287/lib/api/CSingleStreamDataAdder.cc#L15

There is a chance that regression or classification state documents exceed this limit. 

If the documents exceed this limit, the analytics process does not read in each one. Instead it assumes the state fit within one document. 

Data frame analytics should be able to read in numerous documents when restoring previous state.

It appears as if writing the state works fine. I tested with a much smaller `MAX_DOCUMENT_SIZE` and saw multiple state documents written with the appropriate doc names.

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
When state persistence was first implemented for data frame analytics
we had the assumption that state would always fit in a single document.
However this is not the case any more.

This commit adds handling of state that spreads over multiple documents.

Closes #52476

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java [hunk 1]
```diff
@@ -242,17 +241,46 @@ private void deleteState(ParentTaskAssigningClient parentTaskClient,
...
             parentTaskClient,
             AnomalyDetectorsIndex.jobStateIndexPattern(),
-            QueryBuilders.idsQuery().addIds(ids.toArray(String[]::new)),
+            query,
             timeout,
-            listener
+            ActionListener.wrap(
+                response -> {
+                    if (response.getDeleted() > 0) {
+                        deleteModelState(parentTaskClient, config, timeout, docNum + 1, listener);
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java:277]: Is this recursion needed? Would it be possible to delete all the `#1`, `#2`, etc. in one `deleteByQuery` request?
I know we don't know the number of state docs in advance, but maybe we could apply some id pattern?

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java [hunk 2]
```diff
@@ -242,17 +241,46 @@ private void deleteState(ParentTaskAssigningClient parentTaskClient,
                              DataFrameAnalyticsConfig config,
                              TimeValue timeout,
                              ActionListener<BulkByScrollResponse> listener) {
-        List<String> ids = new ArrayList<>();
-        ids.add(StoredProgress.documentId(config.getId()));
-        if (config.getAnalysis().persistsState()) {
-            ids.add(config.getAnalysis().getStateDocId(config.getId()));
+        ActionListener<Boolean> deleteModelStateListener = ActionListener.wrap(
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java:244]: Does `UnusedStateRemover` class need to be changed too?

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/NativeAnalyticsProcess.java [hunk 3]
```diff
@@ -56,10 +59,23 @@ public AnalyticsProcessConfig getConfig() {
...
-            StateToProcessWriterHelper.writeStateToStream(state, restoreStream);
+            int docNum = 0;
+            while (true) {
+                if (isProcessKilled()) {
+                    return;
+                }
+
+                SearchResponse stateResponse = client.prepareSearch(AnomalyDetectorsIndex.jobStateIndexPattern())
+                    .setSize(1)
+                    .setQuery(QueryBuilders.idsQuery().addIds(stateDocIdPrefix + ++docNum)).get();
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/NativeAnalyticsProcess.java:73]: This comment is somewhat related to the one about using recursion. Could we fetch all the state docs at once using some pattern-matched query?
If not, and if 
we expect  many state docs to exist, we could try to fetch them in batches (by adding ids `#1`, `#2`, ..., `#10` to one ids query) to reduce the number of queries.
Please disregard the above if we expect the number of docs to be small so there is no need for premature optimization.

Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/NativeAnalyticsProcess.java:73]: > Could we fetch all the state docs at once using some pattern-matched query?

We deliberately fetch one at a time because if there is more than one then all but the last will be quite big (~16MB in size).  The reason why we split the state over multiple documents is to avoid using all the JVM heap with a massive model state that we have to hold in memory in its entirety.

There should probably be a comment to say we are deliberately only bringing one document into memory at a time because they are big.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java (hunk 1 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java:277]: Unfortunately can't have a pattern query for ids.

Note, however, this is not a real recursion. As the client call is async, each `deleteModelState` call completes immediately. We then make the new call when we get a response from the client.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/NativeAnalyticsProcess.java (hunk 3 above)
Comment (przemekwitek) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/NativeAnalyticsProcess.java:73]: > The reason why we split the state over multiple documents is to avoid using all the JVM heap with a massive model state that we have to hold in memory in its entirety.

Great, thanks for explaining that!

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java (hunk 2 above)
Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportDeleteDataFrameAnalyticsAction.java:244]: No because the corresponding job id extractors (see `Classification.extractJobIdFromStateDoc` and `Regression.extractJobIdFromStateDoc`) successfully extract the job id regardless of the document number that follows the infix.

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/packaging-sample-windows

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/packaging-sample-windows

**Review by droberts195 — APPROVED** [review]
LGTM
