### PR TITLE
Fixes SemanticTextFieldMapperTests.testMinimalIsInvalidInRoutingPath

### LINKED ISSUE #146824: [CI] SemanticTextFieldMapperTests testMinimalIsInvalidInRoutingPath {p0=true p1=BASIC} failing
**Build Scans:**
- [elasticsearch-intake #37886 / part5](https://gradle-enterprise.elastic.co/s/hwrtgqagzye4e)
- [elasticsearch-pull-request #138487 / part-5](https://gradle-enterprise.elastic.co/s/hxpnvdxydspry)
- [elasticsearch-pull-request #138487 / part-5](https://gradle-enterprise.elastic.co/s/mecao6hnvdtxu)
- [elasticsearch-intake #37881 / part5](https://gradle-enterprise.elastic.co/s/soj3kdx4otmwm)
- [elasticsearch-pull-request #138478 / part-5](https://gradle-enterprise.elastic.co/s/i2wlfniwq6hu4)
- [elasticsearch-pull-request #138478 / part-5](https://gradle-enterprise.elastic.co/s/tyckadc2qamwi)
- [elasticsearch-pull-request #138450 / part-5](https://gradle-enterprise.elastic.co/s/6wgsoiuslpay4)
- [elasticsearch-pull-request #138450 / part-5](https://gradle-enterprise.elastic.co/s/yjufkqpn52dhy)
- [elasticsearch-pull-request #138440 / part-5](https://gradle-enterprise.elastic.co/s/2c6onxtux566k)
- [elasticsearch-pull-request #138440 / part-5](https://gradle-enterprise.elastic.co/s/dz37wp4quymo6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.mapper.SemanticTextFieldMapperTests.testMinimalIsInvalidInRoutingPath {p0=true p1=BASIC}" -Dtests.seed=857F97DA21A5017A -Dtests.locale=ar-SY -Dtests.timezone=Etc/GMT+1 -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.mapper.SemanticTextFieldMapperTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMinimalIsInvalidInRoutingPath%20%7Bp0%3Dtrue%20p1%3DBASIC%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: "All fields that match routing_path must be configured with [time_series_dimension: true] or flattened fields with a list of dimensions in [time_series_dimensions] and without the [script] parameter. [field] was not a dimension."
     but: was "cannot have nested fields when index sort is activated"
```

**Issue Reasons:**
- [main] 1 consecutive failures in step part5
- [main] 1 consecutive failures in pipeline elasticsearch-intake
- [main] 23 failures in test testMinimalIsInvalidInRoutingPath {p0=true p1=BASIC} (12.6% fail rate in 182 executions)
- [main] 16 failures in step part-5 (16.0% fail rate in 100 executions)
- [main] 4 failures in step part5 (11.1% fail rate in 36 executions)
- [main] 2 failures in step part-5-arm (66.7% fail rate in 3 executions)
- [main] 10 failures in pipeline elasticsearch-pull-request (10.9% fail rate in 92 executions)
- [main] 4 failures in pipeline elasticsearch-intake (11.1% fail rate in 36 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #146825: [CI] SemanticTextFieldMapperTests testMinimalIsInvalidInRoutingPath {p0=true p1=ENTERPRISE} failing
**Build Scans:**
- [elasticsearch-intake #37886 / part5](https://gradle-enterprise.elastic.co/s/hwrtgqagzye4e)
- [elasticsearch-pull-request #138487 / part-5](https://gradle-enterprise.elastic.co/s/hxpnvdxydspry)
- [elasticsearch-pull-request #138487 / part-5](https://gradle-enterprise.elastic.co/s/mecao6hnvdtxu)
- [elasticsearch-intake #37881 / part5](https://gradle-enterprise.elastic.co/s/soj3kdx4otmwm)
- [elasticsearch-pull-request #138478 / part-5](https://gradle-enterprise.elastic.co/s/i2wlfniwq6hu4)
- [elasticsearch-pull-request #138478 / part-5](https://gradle-enterprise.elastic.co/s/tyckadc2qamwi)
- [elasticsearch-pull-request #138450 / part-5](https://gradle-enterprise.elastic.co/s/6wgsoiuslpay4)
- [elasticsearch-pull-request #138450 / part-5](https://gradle-enterprise.elastic.co/s/yjufkqpn52dhy)
- [elasticsearch-pull-request #138440 / part-5](https://gradle-enterprise.elastic.co/s/2c6onxtux566k)
- [elasticsearch-pull-request #138440 / part-5](https://gradle-enterprise.elastic.co/s/dz37wp4quymo6)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.mapper.SemanticTextFieldMapperTests.testMinimalIsInvalidInRoutingPath {p0=true p1=BASIC}" -Dtests.seed=857F97DA21A5017A -Dtests.locale=ar-SY -Dtests.timezone=Etc/GMT+1 -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.mapper.SemanticTextFieldMapperTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMinimalIsInvalidInRoutingPath%20%7Bp0%3Dtrue%20p1%3DENTERPRISE%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: "All fields that match routing_path must be configured with [time_series_dimension: true] or flattened fields with a list of dimensions in [time_series_dimensions] and without the [script] parameter. [field] was not a dimension."
     but: was "cannot have nested fields when index sort is activated"
```

**Issue Reasons:**
- [main] 1 consecutive failures in step part5
- [main] 1 consecutive failures in pipeline elasticsearch-intake
- [main] 23 failures in test testMinimalIsInvalidInRoutingPath {p0=true p1=ENTERPRISE} (12.6% fail rate in 182 executions)
- [main] 16 failures in step part-5 (16.0% fail rate in 100 executions)
- [main] 4 failures in step part5 (11.1% fail rate in 36 executions)
- [main] 2 failures in step part-5-arm (66.7% fail rate in 3 executions)
- [main] 10 failures in pipeline elasticsearch-pull-request (10.9% fail rate in 92 executions)
- [main] 4 failures in pipeline elasticsearch-intake (11.1% fail rate in 36 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by carlosdelest**
Closes #146824
Closes #146825

SemanticTextFieldMapperTests.testMinimalIsInvalidInRoutingPath always check the latest version of indices. 

SemanticTextFieldMapperTests also checks indices created with the legacy format, which do not have the same error message than the new format. Legacy format stores inference results in nested objects, which are incompatible with
 the index sort required by time_series mode, so validation fails before the routing_path check.

### CODE REVIEW

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapperTests.java [hunk 1]
```diff
@@ -231,6 +231,12 @@ protected Supplier<ModelRegistry> getModelRegistry() {
         });
     }
 
+    protected String minimalIsInvalidRoutingPathErrorMessage(Mapper mapper) {
```
Comment (Mikep86) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapperTests.java:235]: Nit: `@Override` annotation

**Review by Mikep86 — APPROVED** [review]
