### PR TITLE
Automatically flatten objects when subobjects:false

### LINKED ISSUE #88934: Automatically flatten objects when `subobjects: false`
Currently, when an object is mapped with `subobjects: false`, trying to ingest a document that has nested objects leads to a mapping exception.

In a couple of occasions, we've been talking about that it would be convenient if Elasticsearch could automatically flatten the fields instead of the client having to know about the `subobjects` setting. This would make `subobjects: false` more of a drop-in replacement that allows for a much easier adoption, without changes in the client.

Note that the `_source` should ideally stay untouched, just the stored fields should be flattened automatically.

Some related issues
* https://github.com/elastic/apm/issues/347
* https://github.com/elastic/elasticsearch/issues/88777
* https://github.com/elastic/package-spec/issues/349

### PR DESCRIPTION
**Pull request by piergm**
While ingesting documents that contain nested object and the
mapping property `subobjects` is set to `false` instead of throwing
a mapping exception and dropping the document(s), we map only 
leaf field(s) with their full path as their name.

This has being done by avoiding dynamically mapping of the 
intermediate objects and retaining `dottedFieldName` while parsing.

After this change with the following root level mapping:
`{
  "subobjects" : false,
  "properties" : {
  } 
}
`
the ingest both of the following documents will result in the same
mapped fields (`time.min` and `time.max`) instead of having the 
second rejected:
1) `{
	"time.min": 1,
	"time.max": 2
}`
2) `{
	"time": {
		"max": 1,
		"max": 2
	}
}`

Subtasks:
- Skip dynamically mapping objects when parsing a document and an 
object is encountered
- Fields capable of parsing objects natively, such as geo_point, will now 
be dynamically mapped exclusively through dynamic templates.
- Provide parsed objects to field mappers only when they are supported

closes #88934

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 1]
```diff
@@ -421,16 +421,18 @@ private static void parseObject(final DocumentParserContext context, String curr
...
-                    context.path().setWithinLeafObject(true);
-                }
-            }
             parseObjectOrField(context, objectMapper);
-            context.path().setWithinLeafObject(false);
             context.path().remove();
         } else {
-            parseObjectDynamic(context, currentFieldName);
+            DynamicTemplate dynamicTemplate = context.findDynamicTemplate(currentFieldName, DynamicTemplate.XContentFieldType.OBJECT);
+            if (context.parent().subobjects() || dynamicTemplate != null) {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:428]: This is to only apply dynamic templates to objects, but skip creating the  object if there is no matching template when subobjects is false? 

I think I would adapt the conditional to that, and only do something special if subobjects is false. Is it needed to look up a dynamic template externally if subobjects is true? In that case you can call parseObjectDynamic directly?

I also wonder if a cleaner solution would be to add an argument to parseObjectDynamic to control whether it should only apply the template. This will probably make it a bigger change which may warrant pulling it into a separate PR.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 2]
```diff
@@ -421,16 +421,18 @@ private static void parseObject(final DocumentParserContext context, String curr
         Mapper objectMapper = context.getMapper(currentFieldName);
         if (objectMapper != null) {
             context.path().add(currentFieldName);
-            if (objectMapper instanceof ObjectMapper objMapper) {
-                if (objMapper.subobjects() == false) {
-                    context.path().setWithinLeafObject(true);
-                }
-            }
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:428]: I would expect this to break things, as it effectively ignores the subobjects setting at each object level (it can be set within any object)

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 3]
```diff
@@ -451,28 +453,7 @@ private static void parseObjectDynamic(DocumentParserContext context, String cur
...
-                    throw new DocumentParsingException(
-                        context.parser().getTokenLocation(),
-                        "Tried to add subobject ["
-                            + dynamicObjectMapper.simpleName()
-                            + "] to object ["
-                            + context.parent().name()
-                            + "] which does not support subobjects"
-                    );
-                }
-            }
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:475]: can you expand on removing these?

File: server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java [hunk 4]
```diff
@@ -2574,6 +2578,375 @@ public void testDeeplyNestedDocument() throws Exception {
...
+            """));
+
+        assertNotNull(parsedDocument.rootDoc().getField("location"));
+        RootObjectMapper root = parsedDocument.dynamicMappingsUpdate().getRoot();
+        assertEquals(1, root.mappers.size());
+        Mapper geoPointFieldMapper = root.getMapper("location");
+        assertNotNull(geoPointFieldMapper);
+        assertTrue(geoPointFieldMapper instanceof GeoPointFieldMapper);
+        assertNotNull(parsedDocument.dynamicMappingsUpdate());
+    }
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java:2948]: I think it may be good to add tests that index multiple docs with different way to specify the same fields (flat or not flat). That is because dynamic mappings rely on order and it may happen that we end up only testing the happy path.

File: server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java [hunk 5]
```diff
@@ -2574,6 +2578,375 @@ public void testDeeplyNestedDocument() throws Exception {
...
+        }));
+        ParsedDocument parsedDocument = mapper.parse(source("""
+            {
+              "metrics": {
+                "service.time" : {
+                  "min" : 1
+                }
+              }
+            }
+            """));
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java:2830]: Does this test run? I remember the problem here being that we would provide the inner object to be parsed by the long `service.time` field, which would not work. That is because service.time is mapped, but not as an object. I am not completely following how you worked around that, I am also quite fuzzy on this because it's been a while since I worked on this issue.

**Comment by felixbarny** [comment]
I'm really excited that this is happening. Thanks for working on it ❤️

File: server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java [hunk 6]
```diff
@@ -153,7 +153,6 @@ protected final Map<String, Mapper> buildMappers(MapperBuilderContext mapperBuil
             Map<String, Mapper> mappers = new HashMap<>();
             for (Mapper.Builder builder : mappersBuilders) {
                 Mapper mapper = builder.build(mapperBuilderContext);
-                assert mapper instanceof ObjectMapper == false || subobjects.value() : "unexpected object while subobjects are disabled";
```
[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java:156]: Actually wasn't necessary, I added it back. Thanks for the feedback!

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 3 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:475]: Actually wasn't necessary, I added it back! Was needed in a previous implementation I tired and newbiely forgot to add it back... I'll be more careful next times

File: server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java (hunk 4 above)
Comment (piergm) [reply server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java:2948]: Added!

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 2 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:428]: After further investigation it indeed breaks things. It added a bug that is making the test `testSubobjectsFalseDocsWithInnerObjectMappedAsNonObject ` from the comment quoted below to pass because during the parsing of the document it retains `time` instead of `service.time` as the field name, therefore failing on retrieving the correct mapper. I'm adding the check back and I'll work on making the test pass!
> Does this test run? I remember the problem here being that we would provide the inner object to be parsed by the long `service.time` field, which would not work. That is because service.time is mapped, but not as an object. I am not completely following how you worked around that, I am also quite fuzzy on this because it's been a while since I worked on this issue.

File: server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java (hunk 5 above)
Comment (piergm) [reply server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java:2830]: It did run because of a bug discovered thanks to your comment above. 
Ref:
> I would expect this to break things, as it effectively ignores the subobjects setting at each object level (it can be set within any object)

Comment (javanna) [reply server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java:2830]: Got it. This is the third problem we discussed. When you do have an object in the document, and the field is mapped but not as an object, there are cases in which you do need to provide the object as-is to the mapper for parsing (e.g. geo_point) and the majority of the cases in which you can just throw an error (e.g. because long does not support parsing objects). We are covered for the error situation, that happens already, but we need to cover the geo_point scenario, and we don't have a systematic way to say: "does the mapper support parsing objects?". We should avoid instanceof checks and rather introduce a way to discriminate between mappers that can and cannot parse objects natively.

Comment (piergm) [reply server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java:2830]: So, if I understood correctly, when `subobject: false` we want to be able to provide the entire object as-is to the mapper for parsing if either:

1. There is a dynamic template for such field or 
2. There is a mapped field of any type that can natively parse objects.

While in the case of this particular test, where there is a mapped field but the type cannot parse objects, we just want an exception.

Did I understood correctly or am I missing something?

Comment (javanna) [reply server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java]: Sounds accurate!

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 1 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:434]: hey @piergm thought about this comment?

File: server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java [hunk 7]
```diff
@@ -2574,6 +2578,475 @@ public void testDeeplyNestedDocument() throws Exception {
...
+            {
+              "metrics": {
+                "service.time" : {
+                  "min" : 1
+                }
+              }
+            }
+            """)));
+        String expectedErrorMessage = "[5:5] failed to parse field [metrics.service.time] of type [long] in document with id '1'. "
+            + "Preview of field's value: '{min=1}'";
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java:2867]: Sorry about the confusion: this should not throw an error. it should be possible to map service.time as long, or have a previous document with service time as a long, as well as provide service.time as an object with a subfield. The service.time object should be ignored when it comes to mappings, because subobjects is set to false and only the sub-field should be mapped.

**Review by javanna — CHANGES_REQUESTED** [review]
Did another , more in-depth round, and left some comments

File: server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java (hunk 5 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java]: I tripped on the following sentence:

> While in the case of this particular test, where there is a mapped field but the type cannot parse objects, we just want an exception.

Not, we want to parse its sub-fields and ignore their object container. That is one of the challenges of this change. Sorry about the confusion.

Comment (piergm) [reply server/src/test/java/org/elasticsearch/index/mapper/DocumentParserTests.java]: Got it! Thanks for clarifying. 👍

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 8]
```diff
@@ -430,7 +430,15 @@ private static void parseObject(final DocumentParserContext context, String curr
...
             context.path().remove();
         } else {
-            parseObjectDynamic(context, currentFieldName);
+            DynamicTemplate dynamicTemplate = context.findDynamicTemplate(currentFieldName, DynamicTemplate.XContentFieldType.OBJECT);
+            if (context.parent().subobjects() || dynamicTemplate != null) {
+                parseObjectDynamic(context, currentFieldName);
+            } else {
+                context.parser().nextToken(); // Skipping Object-start
+                context.path().addDottedFieldName(currentFieldName);
+                innerParseObject(context);
```
[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:439]: Thanks for pointing this out, my reasoning here is that at this stage in parsing we are not sure if the object we are parsing contains properties, other nested objects or both therefore we rely on the innerParseObject switch-case to kind-of-recursively unpack objects and parse values. This, together with the fact that we add the dottedFileName before the call and remove it right after, works seamlessly with this logic. 
Basically I am using dottedFieldName as a stack by pushing to it field names while we encounter nested objects and popping from it when we finish parsing any of the nested objects.

After further inspection I think that we can call `parseObjectOrNested` instead of `innerParseObject` after adjusting the context by adding the dottedFieldName. This will maintain the same logic I implemented (since inside `parseObjectOrNested` we call `innerParseObject`) but the `parseObjectOrNested` method will handle all the checks and skip the object start that I was doing manually here.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 1 above)
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:434]: I do agree on just doing 

> something special if subobjects is false  
I wanted to avoid to much nesting and by adding the or clause did prevent this but on the other and as you pointed out we are looking up dynamic templates even if subobject is set to false. I'll correct this.
----
But I am not so sure that:

> a cleaner solution would be to add an argument to parseObjectDynamic to control whether it should only apply the template.

I'll try it out but does not resonate well with me.
----
I am indeed bypassing the dynamic behaviour here. Is not what we wanted in the first case? I'll add further tests to cover the case of dynamic false/runtime and subobject false.
----
> For reference: within parseObjectDynamic, we already handle dynamic:runtime, and that is very similar to what we need to do for subobjects false, as runtime mappings effectively don't have objects, and are flattened using their full path name as their field name.

Good point. I wander if there is a latent bug due to this that I solved by introducing dottedFieldNames

File: server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java [hunk 9]
```diff
@@ -27,18 +31,37 @@ public ContentPath() {
...
 
-    private void expand() {
+    private void expandPath() {
         String[] newPath = new String[path.length + 10];
         System.arraycopy(path, 0, newPath, 0, path.length);
         path = newPath;
     }
 
-    public void remove() {
-        path[index--] = null;
```
Comment (piergm) [inline server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java:41]: This was a wrong behaviour, index has the next available index to write path to. In fact to add a path we did `path[index++] = name;` so we write at index position and increment it later. Doing `path[index--] = null;` would set to null the next available index position (that is already null) and later subtract 1 from index. This was masked by the fact that when retrieving a path we loop up until `i < index`, therefore masking the fact that there could have being 'removed' but not null path existing at `index`.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java [hunk 10]
```diff
@@ -417,6 +417,10 @@ protected void doXContentBody(XContentBuilder builder, Params params) throws IOE
 
     protected abstract String contentType();
 
+    protected boolean canParseObjects() {
+        return false;
```
Comment (piergm) [inline server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java:421]: **Note for reviewers:**
By reading public docs the only Fields that can parse objects are Percolator and AbstractGeometry (that covers geo_point, geo_shape, point, shape). Am I missing other Fields?

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 11]
```diff
@@ -415,6 +426,10 @@ static void parseObjectOrField(DocumentParserContext context, Mapper mapper) thr
         }
     }
 
+    private static boolean canToBeFlatten(DocumentParserContext context) {
```
Comment (piergm) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:429]: I decided to extract this method to make the if-elif-else just above much easier to read.

**Review by piergm — COMMENTED** [review]
Left few notes for reviewers.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java (hunk 10 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java:421]: There's more: I would look at the mappers that override `FieldMapper#parse(DocumentParserContext context)` as opposed to `parseCreateField`. Those are the ones that support complex formats, and out of those you'd need to double check which ones support objects (e.g. does the parsing code handle objects?)

File: server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java (hunk 9 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java:41]: could you extract this fix out of this PR and add a test for it? I am not clear on whether it causes actual issues, and if the fix is needed to make your changes work. Still, I think it would be worthwhile to pull it out of this PR.

**Review by javanna — COMMENTED** [review]
left some comments, this looks headed in the right direction. Thanks for all the tests.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 12]
```diff
@@ -415,6 +426,10 @@ static void parseObjectOrField(DocumentParserContext context, Mapper mapper) thr
...
+        return context.parser().currentToken() == XContentParser.Token.START_OBJECT && context.parent().subobjects() == false;
```
[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:430]: Yes, there are cases where the token is not `START_OBJECT`. It's a little bit tricky but it's given away by the fact that the method name is `parseObjectOrField`.
A case is where we use the `parseDynamicValue` method, in that case the token is never `START_OBJECT` and we are using `DynamicFieldsBuilder` that internally calls `DocumentParser::parseObjectOrField`.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 13]
```diff
@@ -453,7 +468,18 @@ private static void parseObject(final DocumentParserContext context, String curr
             context.path().setWithinLeafObject(false);
             context.path().remove();
         } else {
-            parseObjectDynamic(context, currentFieldName);
+            if (context.parent().subobjects()) {
+                parseObjectDynamic(context, currentFieldName);
+            } else {
+                DynamicTemplate dynamicTemplate = context.findDynamicTemplate(currentFieldName, DynamicTemplate.XContentFieldType.OBJECT);
```
[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:474]: I agree with you and I added a check to lookup dynamic templates only if dynamic:true

File: server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java (hunk 9 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java:41]: is that a pre-requisite for this change or a separate one? Can this PR go in without it?

File: server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java [hunk 14]
```diff
@@ -58,6 +81,15 @@ public String pathAsText(String name) {
         return sb.toString();
     }
 
+    public String dottedFieldName(String name) {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/ContentPath.java:84]: Could we add javadocs to explain what this method does and how it should be used? Same for the other public methods you are adding: addDottedFieldname / removeDottedFieldName

File: server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java [hunk 15]
```diff
@@ -161,6 +161,17 @@ public boolean parsesArrayValue() {
         return false;
     }
 
+    /**
+     * Whether this mapper can handle an object value during document parsing. If true,
+     * when an object is encountered during parsing, the document parser will pass the
+     * whole object to the mapper. If false, the object name becomes part of the dotted
+     * field name of each internal value when subobjects property is set to false,
+     * otherwise it gets mapped to an ObjectMapper.
+     */
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java:170]: One aspect that is not entirely clear to me reading this comment is: do we need to consult this method when subobjects is set to true? The comment would make me think so, but the only reason why we need the method is for subobjects false / auto - flattening? 

I would think that when subobjects is true, there are two situations:
1) there is a field mapped that corresponds to the object we are parsing, which we provide to the mapper, no matter if it supports objects or not. It it does not, parsing will throw error
2) there is no field mapped for the object we are parsing, in which case we will create a new object mapper dynamically (assuming dynamic:true)

Does it add any value to consult this method when subobjects is true?

We could clarify, unless I got this wrong, that we call this method only when subobjects is false, and we use it to discriminate between field mappers that should be provided with the object to be parsed (situation 1. above), and field mappers that need to continue parsing and map nothing (situation 2. above, no object mapper created).

File: server/src/main/java/org/elasticsearch/index/mapper/vectors/SparseVectorFieldMapper.java [hunk 16]
```diff
@@ -114,6 +114,11 @@ public SparseVectorFieldType fieldType() {
         return (SparseVectorFieldType) super.fieldType();
     }
 
+    @Override
+    protected boolean parsesObject() {
+        return true;
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/vectors/SparseVectorFieldMapper.java:119]: this mapper has been removed, effectively, looking at the javadocs above. I am thinking that we don't need to update it as we no longer support parsing this type of fields

File: server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java [hunk 17]
```diff
@@ -161,6 +161,17 @@ public boolean parsesArrayValue() {
...
+    protected boolean parsesObject() {
+        return false;
+    }
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java:173]: I double checked the mapper that you overrode this method for and it looks good, great work on figuring that out.

File: server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java (hunk 15 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java:170]: Could we also rename the method to supportsParsingObject ?

File: server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java (hunk 17 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/FieldMapper.java:173]: It would be good to spend some time thinking how to test correctness for this value, and to make sure it does not go out of sync. We have `MapperTestCase` as a base class for all mappers tests, where we can add a new test method that all the subclasses will run. One idea would be to add a method that verifies that if the mapper supports parsing objects, it won't throw error when provided one (could be tricky because of the structure required, but perhaps we can leverage the existing `getSampleValueForDocument` which every test class already defines to provide valid values to be parsed. Also, we could verify (maybe easier) that when a mapper does not support parsing objects, it will throw an error when provided one (for which you can just try to parse a plain object and verify that parsing fails). 

Because this becomes possibly more involving, it would not be a bad idea to extract adding this method alone together with its related tests to a separate PR, even if the method is not yet used.

**Review by javanna — COMMENTED** [review]
I have done another round, I'd open a separate PR also for the support around parsing objects and corresponding tests. I ahve yet to go through the DocumentParser changes one more time, but this gives you something to work on in the meantime.

**Comment by piergm** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by romseygeek** [comment]
I wonder if it's possible to make these changes without touching ContentPath, which is getting considerably more complicated here.  I think we can keep all our changes within `DocumentParser#parseObjectDynamic`, and do something like: if we have a dynamically created object mapper here but subobjects are disallowed, then throw said object mapper away and instead create a new DocumentParserContext with a wrapped XContentParser that prepends the current field name to any of its immediate children, and pass this to `parseObjectOrField`.  I think this would also simplify the handling of the dynamic runtime case: where we currently create a fake object mapper for the context to use, we instead modify the xcontentparser to include the extra field level when it reports field names but stick with the same ObjectMapper parent.

Have a look at XContentSubParser to get an idea of how this might be implemented - keep track of the nesting level, and if we're at level 1 when `currentName()` is called, return the delegate name with the extra field name prepended, otherwise just delegate.

**Review by romseygeek — COMMENTED** [review]
This looks great, thanks @piergm - I left a couple of nits and have one question.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 18]
```diff
@@ -396,7 +396,15 @@ static void parseObjectOrField(DocumentParserContext context, Mapper mapper) thr
             context = context.createChildContext(objectMapper);
             parseObjectOrNested(context);
         } else if (mapper instanceof FieldMapper fieldMapper) {
-            fieldMapper.parse(context);
+            if (canToBeFlatten(context, fieldMapper)) {
```
[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:399]: We hit branch when there is a MappedField that does not support parsing objects and we are trying to parse an object. In this case:
> we want to parse its sub-fields and ignore their object container. https://github.com/elastic/elasticsearch/pull/97972#discussion_r1283044555

One of the tests that cover this case is `testSubobjectsFalseDocsWithMultipleInnerObjectMappedAsNonObject` where we have a mapping for `metrics.service.time` as LongField but we receive an object instead eg. `"current" : { "min" : 1, "max" : 10}`

File: libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java [hunk 19]
```diff
@@ -475,6 +475,37 @@ public void testSubParserObject() throws IOException {
...
+        assertEquals(XContentParser.Token.START_OBJECT, parser.nextToken());
+        XContentParser subParser = new FlatteringXContentParser(parser, parser.currentName());
+        assertEquals(XContentParser.Token.FIELD_NAME, subParser.nextToken());
+        assertEquals("parent.child1", subParser.currentName());
+        assertEquals(XContentParser.Token.VALUE_NUMBER, subParser.nextToken());
+        assertEquals(XContentParser.Token.FIELD_NAME, subParser.nextToken());
+        String secondChildName = subParser.currentName();
+        assertEquals("parent.child2", secondChildName);
+        assertEquals(XContentParser.Token.START_OBJECT, subParser.nextToken());
+        XContentParser subSubParser = new FlatteringXContentParser(subParser, secondChildName);
```
[the remark this answers is not in the document]
Comment (piergm) [reply libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java:502]: I agree on the `child3` test and I added it, but I think re-wrapping is necessary since `FlatteringXContentParser::currentName` handles only immediate child, therefore in the case you mentioned we'd get just `grandchild` as currentName plus in the code we'd re-wrap in case we encounter an object.

File: libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteringXContentParser.java [hunk 20]
```diff
@@ -0,0 +1,47 @@
...
+
+package org.elasticsearch.xcontent;
+
+import java.io.IOException;
+
+/**
+ * A subclass of XContentSubParser that provides the functionality to flatten
+ * the field names by prefixing them with the provided parent name.
+ */
+public class FlatteringXContentParser extends XContentSubParser {
```
[the remark this answers is not in the document]
Comment (piergm) [reply libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteringXContentParser.java]: Done!

File: libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (piergm) [reply libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java]: > Rather than rewrapping here, can we test that we get `grandchild` as the next field name?
Sorry I read the comment wrongly. Now we check that we get `grandchild` as the next field name

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 18 above)
[the remark this answers is not in the document]
Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:399]: Gotcha.  Can we rename `canToBeFlatten` to `shouldFlattenObject`

[the remark this answers is not in the document]
Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java]: Done!

**Review by romseygeek — APPROVED** [review]
LGTM, thanks for all the iterations!

File: libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java [hunk 21]
```diff
@@ -475,6 +475,41 @@ public void testSubParserObject() throws IOException {
...
+        XContentParser subParser = new FlatteningXContentParser(parser, parser.currentName());
+        assertEquals(XContentParser.Token.FIELD_NAME, subParser.nextToken());
+        assertEquals("parent.child1", subParser.currentName());
+        assertEquals(XContentParser.Token.VALUE_NUMBER, subParser.nextToken());
+        assertEquals(XContentParser.Token.FIELD_NAME, subParser.nextToken());
+        String secondChildName = subParser.currentName();
+        assertEquals("parent.child2", secondChildName);
+        assertEquals(XContentParser.Token.START_OBJECT, subParser.nextToken());
+        assertEquals(XContentParser.Token.FIELD_NAME, subParser.nextToken());
+        assertEquals("grandChild", subParser.currentName());
```
Comment (javanna) [inline libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java:504]: can you help me understand why we need to prepend the path only if level is 1? shouldn't this be also `parent.child2.grandChild` ?

File: libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java [hunk 22]
```diff
@@ -0,0 +1,47 @@
...
+    /**
+     * Retrieves the name of the current field being parsed. If the current parsing level is 1,
+     * the returned field name will be constructed by prepending the parent name to the
+     * delegate's currentFieldName, otherwise just delegate.
+     *
+     * @return The current field name, potentially modified by prepending the parent name as a prefix.
+     * @throws IOException If an I/O error occurs during parsing.
+     */
+    @Override
+    public String currentName() throws IOException {
```
Comment (javanna) [inline libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java:41]: I find it a bit surprising that the only method that needs to be overridden here is `currentName`. If we are flattening docs, shouldn't nextToken get adjusted too in some ways? I find this a little hard to follow.

File: libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java [hunk 23]
```diff
@@ -0,0 +1,47 @@
...
+
+package org.elasticsearch.xcontent;
+
+import java.io.IOException;
+
+/**
+ * A subclass of XContentSubParser that provides the functionality to flatten
+ * the field names by prefixing them with the provided parent name.
+ */
+public class FlatteningXContentParser extends XContentSubParser {
```
Comment (javanna) [inline libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java:17]: Sorry for chiming in late, I'd like to better understand how the additional complexity in `ContentPath` around tracking the full path is replaced with this custom parser. In a previous experience with `DotExpandingXContentParser`, we have seen that having a custom parser can have quite a few side effects that are difficult to predict (do we forward all the right methods? is the parser only used how we think it is?),  because the parser exposes a pretty generic interface that is used in many different ways and we are customizing it for a very specific scenario.

While additional methods to `ContentPath` increase its surface, I find that they make the contract easier to reason about and easier to track as well. While I agree that `ContentPath` is not a fantastic abstraction and needs some love, I am not sure that adding a new parser addresses that fairly, in that it introduces all kinds of unknowns, at least in my opinion.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 24]
```diff
@@ -486,15 +499,16 @@ private static void parseObjectDynamic(DocumentParserContext context, String cur
...
-                    );
+                    // We have an ObjectMapper but subobjects are disallowed
+                    // therefore we create a new DocumentParserContext that
+                    // prepends currentFieldName to any immediate children.
+                    parseObjectOrNested(context.createFlattenContext(currentFieldName));
+                    return;
                 }
+
+            }
+            if (context.dynamic() != ObjectMapper.Dynamic.RUNTIME) {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:510]: nit: for readability, should this have been if dynamic == Dynamic.TRUE ? Otherwise you have to look above to see that we can only have either RUNTIME or TRUE at this point.

File: libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java (hunk 22 above)
Comment (romseygeek) [reply libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java:41]: Because we need to distinguish between deeply nested leaf fields, and dynamically created mappers that accept an object, we only flatten a single level at a time.  We don't need to adjust anything apart from the lowest-level name, because once we move into a new object we will either pass it to a mapper to parse, or wrap it again.

File: libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java (hunk 21 above)
Comment (piergm) [reply libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java:504]: Every time that we have a dynamically created object mapper and subobjects:false we create a new context with a FlatteningXContentParser. This is explicit when we create `subParser` for field `parent` and is not done (for tests purpouses) for the field `child2`. In the normal code execution since 'child2' is a dynamically created object mapper itself we would have created a sub-subParser passing as parent name `subParser.currentName()` that is `parent.child2` as was done in [this test](https://github.com/elastic/elasticsearch/pull/97972#discussion_r1304248220) and therefore the current name here would have being `parent.child2.grandChild`.
Is for this reason that we only "care" about immediate child, since grandchildren are handled recursively. Otherwise we would have created somewhat of a clone of ContentPath.

File: libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java (hunk 22 above)
Comment (piergm) [reply libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java:41]: Here we are using the logic of `XContentSubParser` that I extend. There is keeping track of the current nested level.

File: libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java (hunk 23 above)
Comment (romseygeek) [reply libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java:17]: > because the parser exposes a pretty generic interface that is used in many different ways and we are customizing it for a very specific scenario.

That's a fair point - maybe we should make this a private class within DocumentParserContext?

My reason for preferring it this way is that is makes it much simpler to read the DocumentParser code, which is already fairly gnarly.  It also opens the way to further simplifications - I played around a bit with rewriting the Dynamic.RUNTIME logic to use this and it mostly just works, although we'd need to revisit how we handle fields that contain spaces.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java (hunk 24 above)
Comment (felixbarny) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:510]: After https://github.com/elastic/elasticsearch/pull/96235 is merged, this case should also cover `Dynamic.UNTIL_LIMIT`, which it currently does.

Comment (javanna) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:510]: I'd still prefer to be explicit, rather than assuming that any other value than RUNTIME should get the dynamic behaviour. Still it's not a super huge deal, but I think it'd improve readability

Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:510]: > I assume this came from refactoring out context.addDynamicMapper(dynamicObjectMapper)

Yes this was the case, but I totally agree with @javanna on the readability aspect.

File: libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java (hunk 23 above)
Comment (javanna) [reply libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java:17]: I agree that DocumentParser could be simplified, greatly. But I think that this type of changes just end up moving the complexity elsewhere and possibly cause collateral issues that are difficult to predict. I am being conservative, I know, that's because I've been bitten with DotExpandingXContentParser before.

File: libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java (hunk 21 above)
Comment (javanna) [reply libs/x-content/src/test/java/org/elasticsearch/xcontent/XContentParserTests.java:504]: Got it, thanks for your patient explanation ;)

File: libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java (hunk 22 above)
Comment (romseygeek) [reply libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java:41]: We still expect nextToken to be called, but it delegates to the XContentSubParser implementation (which keeps track of levels, etc).  But yes, +1 to making the parser private.

Comment (piergm) [reply libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java:41]: I agree on the private parser, but as @romseygeek said we must not throw when nextToken is called, we expect to call the parent's class nextToken.

Comment (javanna) [reply libs/x-content/src/main/java/org/elasticsearch/xcontent/FlatteningXContentParser.java:41]: sounds good, thanks.Let's also see if there's other assumptions we are making that could be enforced directly in the parser to prevent it from being misused. Maybe nothing to do, not exactly sure.

File: server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java [hunk 25]
```diff
@@ -486,15 +499,16 @@ private static void parseObjectDynamic(DocumentParserContext context, String cur
                     );
                 }
                 if (dynamicObjectMapper instanceof ObjectMapper) {
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:501]: Question: here we don't know how the object mapper was created dynamically. In most cases this comes from the usual dynamic mappings (intermediate objects created automatically), but are there cases in which an object may be the result of applying a dynamic template?

The main purpose of this conditional is that we do want to apply dynamic templates that e.g. create ip fields out of objects from docs, and we know implicitly that these can only come from dynamic template because we have no default dynamic mapping for ip fields (or any field that supports parsing objects natively for that matter). I think though that we are also making the assumption that objects are only the result of the default dynamic mappings, while they could be the result of applying a dynamic template. I am not entirely sure what this would cause: such objects could have a different dynamic or enabled property which we are ignoring. I am thinking we may want to consider throwing exception if we get an object mapper as a result of applying a dynamic template. Ideally, we would apply only the dynamic template here so we don't have to guess what happened. 

Does this make sense?

Comment (piergm) [reply server/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java:501]: I tested this out and you are correct there could be the case in which an object may be result of applying dynamic templates. 
I do agree on the solution of throwing an exception in this case. 
I'll create a PR with all the suggested improvements. 
Thanks for the review!
