### PR TITLE
Make Searchable Snapshot's CacheFile Lock less

### LINKED ISSUE #63586: [CI] Failure in SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot
This failed both on 7.x and `master`.

Given enough iterations (I'm able to reproduce this locally):

```

REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:internalClusterTest' --tests "org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot" -Dtests.seed=15BC13A4BD1F1DBF -Dtests.security.manager=true -Dtests.locale=ga-IE -Dtests.timezone=Africa/Monrovia -Druntime.java=11
```

relatively reliably fails with:

```
java.lang.AssertionError: Expected no direct read for _1_6.fnm of shard [khpgkyjndq][3], node[Ey_vMbkqSiOr6XnG0FovcQ], [P], s[STARTED], a[id=wolGObVwS0eqfqJGMi_rRg]
Expected: <0L>
     but: was <1L>
	at __randomizedtesting.SeedInfo.seed([15BC13A4BD1F1DBF:9FDF64DF2E884C0C]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.assertSearchableSnapshotStats(SearchableSnapshotsIntegTests.java:810)
	at org.elasticsearch.xpack.searchablesnapshots.SearchableSnapshotsIntegTests.testCreateAndRestoreSearchableSnapshot(SearchableSnapshotsIntegTests.java:262)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda
```

as it did in https://gradle-enterprise.elastic.co/s/4vrinfmyhhgyo

### PR DESCRIPTION
**Pull request by original-brownbear**
Replacing the mechanism for eviction and listener references via a read-write lock by
a reference counting implementation.
This fixes a bug that caused test failure #63586 in which concurrently trying to acquire or release
an eviction listener while doing a file operation would sometimes lead to throwing an exception
since the `tryLock` call on the read lock would fail in this case.
Also this removes the possibility of blocking cluster state updates as a result of them waiting
on the write-lock which might take a long time if a slow read operation executes concurrently.

Closes #63586

NOTE: I ran almost 10k iterations of all searchable snapshot integ tests over this one without failure, this change also visibly speeds up tests.

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 1]
```diff
@@ -42,37 +40,60 @@
...
     private final Path file;
 
-    private volatile Set<EvictionListener> listeners;
-    private volatile boolean evicted;
+    private final Set<EvictionListener> listeners = new HashSet<>();
+
+    /**
+     * A reference counted holder for the current channel to the physical file backing this cache file instance.
+     */
+    private static final class FileChannelReference extends AbstractRefCounted {
```
Comment (original-brownbear) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:68]: By moving access to the file channel to a ref-counted basis and giving the channel its own life-cycle, we can remove all need for locking when dealing with file closing and opening.
Background operations running for index inputs that get closed concurrently are tied to a specific instance of this reference and will simply fail once all references to the channel have been released.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 2]
```diff
@@ -113,22 +117,20 @@ public boolean acquire(final EvictionListener listener) throws IOException {
...
             try {
-                ensureOpen();
-                final Set<EvictionListener> newListeners = new HashSet<>(listeners);
-                final boolean added = newListeners.add(listener);
-                assert added : "listener already exists " + listener;
-                maybeOpenFileChannel(newListeners);
-                listeners = Collections.unmodifiableSet(newListeners);
+                synchronized (listeners) {
+                    ensureOpen();
+                    final boolean added = listeners.add(listener);
```
Comment (original-brownbear) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:123]: There's no need for a `volatile` and immutable set of listeners here. We never accessed the listeners outside of the lock so we can simply mutate them in place.
I made this clearer now by using the `listeners` set as the mutex for all operations that apply to the set and the channel opening/closing that is a result of the set size.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 3]
```diff
@@ -140,96 +142,63 @@ public boolean release(final EvictionListener listener) {
...
-            evictionLock.lock();
-            try {
-                if (evicted == false) {
-                    evicted = true;
-                    evictionListeners.addAll(listeners);
-                    refCounter.decRef();
-                }
-            } finally {
-                evictionLock.unlock();
+        if (evicted.compareAndSet(false, true)) {
```
Comment (original-brownbear) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:180]: I found this a lot cleaner and easier to reason about than checking the value of this boolean twice with tricky locking and the cost of the atomic reference relative to the `volatile` boolean should be trivial.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CachedBlobContainerIndexInput.java [hunk 4]
```diff
@@ -498,34 +496,19 @@ public void prefetchPart(final int part) throws IOException {
                     // We do not actually read anything, but we want to wait for the write to complete before proceeding.
                     // noinspection UnnecessaryLocalVariable
                     final Tuple<Long, Long> rangeToRead = rangeToWrite;
-
-                    try (Releasable ignored = cacheFile.fileLock()) {
```
Comment (original-brownbear) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CachedBlobContainerIndexInput.java:502]: This lock seems pointless to me and was causing trouble. If an eviction of the current file is concurrently started, all that happened here was that we would block that eviction when as far as I can tell we should simply fail the cache population as it's just wasted effort anyway as soon as the eviction hits?

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CachedBlobContainerIndexInput.java [hunk 5]
```diff
@@ -164,193 +164,191 @@ protected void readInternal(ByteBuffer b) throws IOException {
 
         try {
             final CacheFile cacheFile = getCacheFileSafe();
-            try (Releasable ignored = cacheFile.fileLock()) {
```
Comment (original-brownbear) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CachedBlobContainerIndexInput.java:167]: Same argument as in the other spot where I removed use of this method, what's the point of locking here when all we do is make the cache file be used after eviction has already been started, meaning all the writes going into it are wasted anyway?

**Comment by original-brownbear** [comment]
@tlrx I think this is good for review now. I simplified it a little more and added some more comments. The test failure is not related to this PR but some dep download thing we currently see in master as well. Hope this makes sense :)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CachedBlobContainerIndexInput.java (hunk 5 above)
Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CachedBlobContainerIndexInput.java:167]: The point was to keep the file around in order to be able to process any concurrent read operation (if any) that would have required a gap to be filled. But there was no reason to prevent other listeners to be acquired nor an eviction to kick in. Your change improves all of that.

**Review by tlrx — APPROVED** [review]
LGTM - This is nice work @original-brownbear! I can't find any situations where this change could cause an issue. It simplifies the code while reducing the blocking situations to the minimum and that will also help when file are accessed within the cluster state applier thread.

Still, I'd like a second pair of eyes on this before it got merged in.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 6]
```diff
@@ -306,21 +276,18 @@ private void ensureOpen() {
                     @Override
                     protected void doRun() {
                         for (SparseFileTracker.Gap gap : gaps) {
+                            ensureOpen();
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:279]: My bad, this was a leftover from a previous attempt to fix the implementation that used locking. Will remove :)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 7]
```diff
@@ -42,37 +40,60 @@
...
+
+    /**
+     * A reference counted holder for the current channel to the physical file backing this cache file instance.
+     */
+    private static final class FileChannelReference extends AbstractRefCounted {
+
+        private final FileChannel fileChannel;
+
+        FileChannelReference(Path file) throws IOException {
+            super("FileChannel");
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java]: done

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 1 above)
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:74]: Sure done :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 (dep download issue ...)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 8]
```diff
@@ -140,96 +149,63 @@ public boolean release(final EvictionListener listener) {
...
-                maybeCloseFileChannel(newListeners);
-                listeners = Collections.unmodifiableSet(newListeners);
-                success = true;
-            } finally {
-                if (success) {
-                    refCounter.decRef();
+                if (listeners.isEmpty()) {
+                    // nobody is using this file so we close the channel
+                    channelRef.decRef();
+                    channelRef = null;
```
Comment (henningandersen) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:162]: Add `assert channelRef.recCount() == 0`?

**Review by henningandersen — COMMENTED** [review]
I did an initial read-through but need a bit more time to do an in-depth review.

I wonder if it was possible to write a test that provokes the issue of #63586 with higher certainty?

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 8 above)
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:162]: We can't assert that. We could still be using that specific channel in a background operation. This fact is to some degree at the heart of what motivated this PR: we don't want to lock here and wait for all the background fetchers/warmers etc. to be done with the file so we don't have to block and instead have the last of them to finish its work close it.

**Comment by original-brownbear** [comment]
> I wonder if it was possible to write a test that provokes the issue of #63586 with higher certainty?

I suppose technically we could construct the scenario that lead to this issue by some tricky blocking of repository reads at just the right points. But I'm not sure we want that:
1. That would be a significant effort and would only be a relevant special case in the old code, not in the new code this PR introduces.
2. We can probably make it much more likely to shake out this kind of issue and others similar to it by just more aggressively testing concurrent search + relocate which is the actual thing that caused trouble here but I'm not sure how far we want to go here. It's always a trade-off between making the tests slower and increasing the chance of catching things I guess and I'd have a hard time at guessing better parameters for parallelism etc. than what we're currently working with.

**Comment by henningandersen** [comment]
Yeah, it is tricky. I was thinking that we could have a test of just `CacheFile`, calling `acquire`, `release`, `startEviction`, `populateAndRead` in multiple threads (in legal ways), with some level of blocking in the `reader` and `writer` passed to `populateAndRead`.

**Comment by original-brownbear** [comment]
@henningandersen I think I found a way of getting reasonable coverage without too much effort :) I pushed 3c3756af25d where I used the deterministic thread pool to simulate a number of possible permutations of adding and releasing a listener while concurrently evicting the file. This actually tracked down a real-world bug (that was obvious in hindsight but would only show on Windows ... or using `WindowsFS` as in this case:)) that is fixed in the same commit.
I could potentially extend that test a little to use more eviction listeners for example if you want (not sure how much that actually changes, it covers most possible logical scenarios as far as I can tell) and maybe that's all the coverage we need?

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 8 above)
Comment (henningandersen) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:169]: Thanks, I wonder if we should then just change the comment a few lines up to not say "close" (or just remove the comment), at least that is what confused me.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 9]
```diff
@@ -140,96 +156,63 @@ public boolean release(final EvictionListener listener) {
...
-                    evictionListeners.addAll(listeners);
-                    refCounter.decRef();
-                }
-            } finally {
-                evictionLock.unlock();
+        if (evicted.compareAndSet(false, true)) {
+            final Set<EvictionListener> evictionListeners;
+            synchronized (listeners) {
+                evictionListeners = new HashSet<>(listeners);
+                refCounter.decRef();
```
Comment (henningandersen) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:198]: nit: I think this can go outside the synchronized block? Not that I have a case where it makes a difference though...

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 10]
```diff
@@ -113,22 +131,20 @@ public boolean acquire(final EvictionListener listener) throws IOException {
         ensureOpen();
         boolean success = false;
         if (refCounter.tryIncRef()) {
```
Comment (henningandersen) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:133]: This seems unchanged, but I find it slightly odd to have both the option of returning false from this method as well as throwing `AlreadyClosedException` when this `CacheFile` is being evicted. Am I missing something here?

File: x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/index/store/cache/CacheFileTests.java [hunk 11]
```diff
@@ -124,9 +130,40 @@ public void testDeleteOnCloseAfterLastRelease() throws Exception {
...
+
+        final TestEvictionListener evictionListener = new TestEvictionListener();
+        assertTrue(cacheFile.acquire(evictionListener));
+        final long length = cacheFile.getLength();
+        final DeterministicTaskQueue deterministicTaskQueue = new DeterministicTaskQueue(
+            builder().put(NODE_NAME_SETTING.getKey(), getTestName()).build(),
+            random()
+        );
+        final ThreadPool threadPool = deterministicTaskQueue.getThreadPool();
+        final CompletableFuture<Integer> readFuture = cacheFile.populateAndRead(
```
Comment (henningandersen) [inline x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/index/store/cache/CacheFileTests.java:145]: Can we also (sometimes, randomly) call readIfAvailableOrPending?

**Review by henningandersen — COMMENTED** [review]
Thanks for adding the test. This change looks great. I have a number of smaller comments only.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 12]
```diff
@@ -244,7 +227,7 @@ public String toString() {
             + ", length="
             + tracker.getLength()
             + ", channel="
-            + (channel != null ? "yes" : "no")
+            + (channelRef != null ? "yes" : "no")
             + ", listeners="
             + listeners.size()
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:232]: I think that's fine, it's a `volatile` field so it's not going to be totally out of whack and the behavior is the same we had so far? Not great maybe but even if we sync on `listeners` I think we won't get a completely consistent view of things as we have no lock over all the fields used here (the `evicted` can still change async) so maybe it's not worth it? (my main contention with adding locking is that it would mess with debugging in potentially by introducing a new barrier depending on log settings)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 13]
```diff
@@ -374,6 +356,27 @@ public void onFailure(Exception e) {
...
+     * @return file channel reference
+     */
+    private FileChannelReference getFileChannelReference(CompletableFuture<Integer> future) {
+        final FileChannelReference reference;
+        synchronized (listeners) {
+            ensureOpen();
+            reference = channelRef;
+            assert reference.refCount() > 0 : "impossible to run into a fully released channel reference under the listeners mutex";
+            reference.incRef();
+            future.handle((res, t) -> {
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:372]: > I wonder if it was more intuitive to "just" ensure we decRef the FileChannelReference appropriately in the two call-sites?

Yea it's quite annoying to code this up (just adds a lot of random code) actually but let's do it for correctness :)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 9 above)
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:198]: Right :) ... always good to not do some potentially long running file delete under a lock I guess :)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 14]
```diff
@@ -374,6 +356,27 @@ public void onFailure(Exception e) {
...
+     *
+     * @param future completable future to complete after the read operation finished
+     * @return file channel reference
+     */
+    private FileChannelReference getFileChannelReference(CompletableFuture<Integer> future) {
+        final FileChannelReference reference;
+        synchronized (listeners) {
+            ensureOpen();
+            reference = channelRef;
+            assert reference.refCount() > 0 : "impossible to run into a fully released channel reference under the listeners mutex";
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:370]: ++

File: x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/index/store/cache/CacheFileTests.java (hunk 11 above)
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/index/store/cache/CacheFileTests.java:145]: sure thing adding it :)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 10 above)
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:133]: Yea I'm not sure about this either. I think we should just always throw here, since the only way we could conceivably return `false` is if we evict between `ensureOpen()` and trying to increment the ref counter (which is close to impossible).
Maybe change that in a follow-up though, could simplify this and also the `release` method which always returns `true` currently as well and can be simplified to a `void`.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java]: Refactored this in d5eb341a775 now to manually release the ref instead of using the future. Let me know what you think. I was able to keep it reasonably dry and clean I hope :)

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 10 above)
Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:136]: Yes, I think this is a left over when the IndexInput tried to re-acquire a cache file if it failed to add itself as a listener. I guess we were just returning `false` at that time in case of eviction.

Anyway, I'm +1 on throwing.

**Comment by original-brownbear** [comment]
Thanks for the review @henningandersen I think I addressed all your comments now :) (also ran a few thousand iterations of the tests with the latest changes to releasing the file reference and it still seems to run fine.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 15]
```diff
@@ -307,20 +289,16 @@ private void ensureOpen() {
...
-                                        throw new AlreadyClosedException("Cache file channel has been released and closed");
-                                    }
-                                    writer.fillCacheRange(channel, gap.start(), gap.end(), gap::onProgress);
-                                    gap.onCompletion();
+                                    writer.fillCacheRange(reference.fileChannel, gap.start(), gap.end(), gap::onProgress);
                                 } finally {
-                                    readLock.unlock();
+                                    reference.decRef();
                                 }
+                                gap.onCompletion();
```
Comment (tlrx) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:301]: Looking at this again I think that `gap.onCompletion();` should be executed within the try/finally block, before the reference is decremented, as completing the gap might trigger the execution of some listeners.

Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:301]: I think we have this covered by the fact that we increment the reference by one anyway in `getFileChannelReference` so unless we are in some broken state where the overall listener got failed async (maybe that's impossible even?) the ref counting here is actually redundant.
I actually added the ref counting in `getFileChannelReference` to cover this exact spot so we're not without a reference when completing the listener. (I suppose we could do away with the incrementing in `getFileChannelReference` and decrementing after if we made this change, but it seemed easier to reason about the way it currently is but maybe that's just me?)

Comment (tlrx) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:301]: Yes, sorry, I've been puzzled a minute by the decRef following by the gap's completion instead of the other way around... sorry for the noise you can ignore my comment.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (henningandersen) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:235]: I believe `listeners` is no longer `volatile` with this PR? So could in theory be unboundedly wrong.

Also in theory, HashSet implementation could evolve in ways that make this fail in bad ways when concurrently modifying the listeners set (though hard to imagine it would ever do so).

File: x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/index/store/cache/CacheFileTests.java [hunk 16]
```diff
@@ -124,9 +130,47 @@ public void testDeleteOnCloseAfterLastRelease() throws Exception {
...
+        assertTrue(cacheFile.acquire(evictionListener));
+        final long length = cacheFile.getLength();
+        final DeterministicTaskQueue deterministicTaskQueue = new DeterministicTaskQueue(
+            builder().put(NODE_NAME_SETTING.getKey(), getTestName()).build(),
+            random()
+        );
+        final ThreadPool threadPool = deterministicTaskQueue.getThreadPool();
+        final Future<Integer> readFuture;
+        if (randomBoolean()) {
+            readFuture = cacheFile.readIfAvailableOrPending(Tuple.tuple(0L, length), channel -> Math.toIntExact(length));
```
Comment (henningandersen) [inline x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/index/store/cache/CacheFileTests.java:147]: It would be nice in this case to randomly first invoke populateAndRead too - in order to get into the more interesting part of `readIfAvailableOrPending` involving the listener callback.

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 17]
```diff
@@ -307,20 +289,16 @@ private void ensureOpen() {
                     protected void doRun() {
                         for (SparseFileTracker.Gap gap : gaps) {
                             try {
-                                ensureOpen();
-                                if (readLock.tryLock() == false) {
-                                    throw new AlreadyClosedException("Cache file channel is being evicted, writing attempt cancelled");
+                                if (reference.tryIncRef() == false) {
+                                    throw new AlreadyClosedException("Cache file channel has been released and closed");
```
Comment (henningandersen) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:293]: Related to your discussion below I believe we could add:
```
assert false : "expected a non-closed channel reference"
```

**Review by henningandersen — APPROVED** [review]
LGTM, thanks @original-brownbear

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:235]: Urgh you're right I totally forgot that `listeners` isn't `volatile` any longer. I'll just `synchronize` this method on `listeners` for now as we do in all other spots where we touch `listeners`, it's just the only consistent way of doing things with the way it's implemented now IMO. It's probably not too necessary to do anything more complicated just for debugging purposes?

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java [hunk 18]
```diff
@@ -349,31 +327,72 @@ public void onFailure(Exception e) {
...
+            future.complete(read);
+        }, future::completeExceptionally), releasable::close);
+    }
+
+    /**
+     * Get the reference to the currently open file channel for this cache file for a read operation
+     *
+     * @return file channel reference
+     */
+    private FileChannelReference getFileChannelReference() {
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:383]: ++

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java (hunk 17 above)
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/index/store/cache/CacheFile.java:293]: Yea that seems like a safe thing to try :) thanks!

File: x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/index/store/cache/CacheFileTests.java (hunk 16 above)
Comment (original-brownbear) [reply x-pack/plugin/searchable-snapshots/src/test/java/org/elasticsearch/index/store/cache/CacheFileTests.java:147]: ++

**Comment by original-brownbear** [comment]
Thanks Henning + Tanguy!

**Comment by tlrx** [comment]
Thanks to you!
