### PR TITLE
Fix inefficient (worst case exponential) loading of snapshot repository

### LINKED ISSUE #24509: GET /_snapshot/[repo]/_all slow/inefficient
**Elasticsearch version**: 5.2.0 - master
**Plugins installed**: repository-s3
**JVM version**: 1.8.0_92
**OS version** : Darwin [..] 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
**Description of the problem including expected versus actual behavior**:

Listing a read-only 2.4.1 S3 snapshot repository with about 100 snapshots takes 10s on ES 5.1.2 and 5m41s on ES 5.2.0 and 5.3.1.

I noticed that the AWS S3 client is making a lot of requests:
```
cat es-5.1.2.log | grep "Sending request: GET /elasticsearch/green" | wc 
185
cat es-5.3.1.log | grep "Sending request: GET /elasticsearch/green" | wc 
9485
cat es-5.3.1.log | grep "Sending request: GET /elasticsearch/green/snap-month_201703_20170331_100020.dat" | wc
94
```
Listing a 5.3.1 S3 snapshot repository with about 100 snapshots takes 17s and with a fix of the problem 3s.
On 6.0.0-alpha1-SNAPSHOT (master) with about 100 snapshots takes 13s and with a fix of the problem 3s.

**Steps to reproduce**:

Tested on 5.3.1 and master
 1.  create 100 snapshots
 2. GET /_snapshot/[repo]/_all, measure time

**Analysis**:

The problem has been introduced with [commit 714e74888acbe6e8443413a295c0c78cd3bd1c4e](https://github.com/elastic/elasticsearch/commit/714e74888acbe6e8443413a295c0c78cd3bd1c4e):
In order to handle incompatible snapshots gracefully `getRepositoryData()`  is called for each `snapshotId`, which is especially problematic for a list operation. `getRepositoryData()` will load the `snapshotIndexBlob` and the `incompatibleSnapshotsBlob` each time. (17s instead of 3s) 

For a legacy and read-only repository, getRepositoryData() will load each snapshot on every call in order to upgrade the data, which leads to exponential cost. (5m41s instead of 10s)

[(problematic call to getRepository)](https://github.com/elastic/elasticsearch/commit/714e74888acbe6e8443413a295c0c78cd3bd1c4e#diff-d5e40e0acdb86da4b9d02a16848fa927R582)

### PR DESCRIPTION
**Pull request by joachimdraeger**
Ensure that getRepositoryData() is only called once during a list snapshots operation. Fixes #24509.

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/repositories/Repository.java [hunk 1]
```diff
@@ -72,6 +72,15 @@
     /**
      * Reads snapshot description from repository.
      *
+     * @param repositoryData repository data
+     * @param snapshotId  snapshot id
+     * @return information about snapshot
+     */
+    SnapshotInfo getSnapshotInfo(RepositoryData repositoryData, SnapshotId snapshotId);
```
Comment (joachimdraeger) [inline core/src/main/java/org/elasticsearch/repositories/Repository.java]: I appreciate that requiring to pass RepositoryData on getSnapshotInfo might not be the cleanest solution regarding Repository's API.

**Comment by abeyad** [comment]
@joachimdraeger thank you for this contribution, and great catch!  Indeed this would help solve the performance issues introduced by `incompatible-snapshots`.  However, as you stated, I don't think we want to alter the `Repository` interface to take the `RepositoryData`.  Rather, I would propose a different solution: in `TransportGetSnapshotsAction`, we have already retrieved the `RepositoryData`, so we can pass the incompatible snapshots list from that `RepositoryData` instance into `SnapshotsService#snapshots`.  The `SnapshotsServce#snapshots` method can return a `SnapshotInfo.incompatible` instance, instead of relying on `BlobStoreRepository#getSnapshotInfo` to do so.

Let me know if you have the time to do this, or if you prefer I take it on.  We would want to get this in for 5.4.1 and 5.5.0.

Thanks again!

Regarding your question of running `gradle check`, what exactly was failing?

**Review by abeyad — CHANGES_REQUESTED** [review]
I left feedback on a different approach

**Comment by joachimdraeger** [comment]
@abeyad thanks for your feedback. I see that the incompatible SnapshotInfo is only used for the list. In get and restore incompatible is determined twice at the moment: directly and in getSnapshotInfo. 

I think it would be nicer in general if the source of truth would be  getSnapshotInfo with the INCOMPATIBLE state in all cases. However, that would require a much bigger refactoring.

For now I agree that removing the check from 'getSnapshotInfo' and letting 'SnapshotsService#snapshots' check for incompatible snapshots itself seems to be the most viable solution.

I'm happy to give it a go on Monday.

**Comment by abeyad** [comment]
Thank you @joachimdraeger, don't hesitate to ping me on Monday if I can help in any way.

**Comment by joachimdraeger** [comment]
@abeyad I re-implemented the fix as discussed. I tested the incompatible snapshots listing manually and the performance improvement.

File: core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 2]
```diff
@@ -490,11 +490,6 @@ public MetaData getSnapshotMetaData(SnapshotInfo snapshot, List<IndexId> indices
 
     @Override
     public SnapshotInfo getSnapshotInfo(final SnapshotId snapshotId) {
-        if (getRepositoryData().getIncompatibleSnapshotIds().contains(snapshotId)) {
-            // an incompatible snapshot - cannot read its snapshot metadata file, just return
-            // a SnapshotInfo indicating its incompatible
-            return SnapshotInfo.incompatible(snapshotId);
-        }
```
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Since `getSnapshotInfoInternal` (just below) is only used by `getSnapshotInfo`, we can move the code in `getSnapshotInfoInternal` directly into `getSnapshotInfo` and get rid of `getSnaphotInfoInternal`

File: core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java [hunk 3]
```diff
@@ -196,6 +206,7 @@ public SnapshotInfo snapshot(final String repositoryName, final SnapshotId snaps
         return Collections.unmodifiableList(snapshotList);
     }
 
+
```
Comment (abeyad) [inline core/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java]: remove extra new line

**Review by abeyad — CHANGES_REQUESTED** [review]
I left a couple small comments.  Once fixed, we can get this merged.

**Review by abeyad — APPROVED** [review]
LGTM, I will run the tests locally as well and merge.  Thank you for working on this @joachimdraeger!

**Comment by abeyad** [comment]
@elasticmachine test this please

**Comment by abeyad** [comment]
5.x commit: 690250ecfbff2b352b22b8627b08fb59c7dcf7a5
5.4 commit: 21da532493807c566507e01b6665fa089c08ab6f

**Comment by abeyad** [comment]
@joachimdraeger the PR has been merged - thanks again!

**Comment by talevy** [comment]
@abeyad are you sure this change was made properly into `5.x`?

I am seeing that there is a rogue reference to the `getSnapshotInfoInternal` method:

https://github.com/elastic/elasticsearch/blob/5.x/core/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L369

seems to be the only call to it... but the method definition is deleted.

**Comment by abeyad** [comment]
@talevy I pushed ccee1b03c7f6537f50552763930dbada47e17f1c and 6a0e070c1b4bb3a5dc6b412279bd081579d083e6 to fix the issue on 5.x
