### PR TITLE
Increase timeout for FrozenExistenceDeciderIT#testZeroToOne

### LINKED ISSUE #89082: [CI] FrozenExistenceDeciderIT testZeroToOne failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/qsjtxzak77j4q/tests/:x-pack:plugin:autoscaling:internalClusterTest/org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT/testZeroToOne

**Reproduction line:**
`./gradlew ':x-pack:plugin:autoscaling:internalClusterTest' --tests "org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT.testZeroToOne" -Dtests.seed=BB772B619A4692B0 -Dtests.locale=sq-AL -Dtests.timezone=Asia/Hong_Kong -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT&tests.test=testZeroToOne

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: ["partial-index"] 
     but: item 0: was "index"

  at __randomizedtesting.SeedInfo.seed([BB772B619A4692B0:CA2385809CADCC93]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT.lambda$testZeroToOne$2(FrozenExistenceDeciderIT.java:131)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1104)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1077)
  at org.elasticsearch.xpack.autoscaling.existence.FrozenExistenceDeciderIT.testZeroToOne(FrozenExistenceDeciderIT.java:129)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by arteam**
We increased the timeout from 10s to 30s in #90108 it was not enough, There were 5 failures over the 8100 latest builds.
I suspect we do need 30 seconds to allow for ILM to finish.

Fixes #89082

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by arteam** [comment]
@elasticmachine update branch

File: x-pack/plugin/autoscaling/src/internalClusterTest/java/org/elasticsearch/xpack/autoscaling/existence/FrozenExistenceDeciderIT.java [hunk 1]
```diff
@@ -131,7 +131,7 @@ public void testZeroToOne() throws Exception {
             String[] indices = indices();
             assertThat(indices, arrayContaining(PARTIAL_INDEX_NAME));
             assertThat(indices, not(arrayContaining(INDEX_NAME)));
```
Comment (idegtiarenko) [inline x-pack/plugin/autoscaling/src/internalClusterTest/java/org/elasticsearch/xpack/autoscaling/existence/FrozenExistenceDeciderIT.java:133]: Currently this is failing with:
```
java.lang.AssertionError: 	
Expected: ["partial-index"] 	
     but: item 0: was "index"	
```

It would be great to know if it is not created `partial-index` yet or both indices exists at the same time (this is an odd situation).

I wish we have assertj here so that it would report entire array in case of failure.
I have tried `assertThat(indices, allOf(arrayContaining(PARTIAL_INDEX_NAME), not(arrayContaining(INDEX_NAME))));` but its error output is also not clear

**Comment by idegtiarenko** [comment]
According to the logs there is 33s gap between creating partial index and deleting the original one:
```
[2022-11-21T05:02:51,850][INFO ][o.e.c.r.a.AllocationService] [node_t0] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[partial-index][0]]])." previous.health="YELLOW" reason="shards started [[partial-index][0]]"
[2022-11-21T05:03:24,523][INFO ][o.e.s.SnapshotsService   ] [node_t0] deleting snapshots [old-version-snapshot-*] from repository [lePQAUoKPt]
[2022-11-21T05:03:24,532][INFO ][o.e.a.a.c.r.c.TransportCleanupRepositoryAction] [node_t0] Running cleanup operations on repository [lePQAUoKPt][1]
[2022-11-21T05:03:24,557][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"wait-for-index-color"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"copy-execution-state"}] in policy [policy]
[2022-11-21T05:03:24,560][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"copy-execution-state"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"copy-settings"}] in policy [policy]
[2022-11-21T05:03:24,563][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"copy-settings"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"branch-on-datastream-check"}] in policy [policy]
[2022-11-21T05:03:24,564][INFO ][o.e.x.i.IndexLifecycleTransition] [node_t0] moving index [index] from [{"phase":"frozen","action":"searchable_snapshot","name":"branch-on-datastream-check"}] to [{"phase":"frozen","action":"searchable_snapshot","name":"swap-aliases"}] in policy [policy]
[2022-11-21T05:03:24,673][INFO ][o.e.c.m.MetadataDeleteIndexService] [node_t0] [index/UAsQv5HbQuiaRS6eucx12A] deleting index
```

It is still interesting to know what was taking so long, however I believe this is a good justification to prolong the timeout

**Review by idegtiarenko — APPROVED** [review]
