### PR TITLE
SQL: Fix incorrect message for aliases

### LINKED ISSUE #31611: SQL XPack complaining about same index behind an alias with having different mappings.
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0, Build: default/deb/424e937/2018-06-11T23:38:03.357887Z, JVM: 1.8.0_171

**Plugins installed**: []
**JVM version** (`java -version`):"1.8.0_171

**OS version** (`uname -a` if on a Unix-like system): 4.4.0-128-generic

I am attempting to issue a select statement against a alias and receiving a message about the same index having a different mapping.

Query:  `{ "query": "SELECT * FROM news_current", "fetch_size": 5 }`

Response:  `{
    "error": {
        "root_cause": [
            {
                "type": "verification_exception",
                "reason": "Found 1 problem(s)\nline 1:15: [news_current] points to indices [news-20180614] and [news-20180614] which have different mappings. When using multiple indices, the mappings must be identical."
            }
        ],
        "type": "verification_exception",
        "reason": "Found 1 problem(s)\nline 1:15: [news_current] points to indices [news-20180614] and [news-20180614] which have different mappings. When using multiple indices, the mappings must be identical."
    },
    "status": 400
}`

### LINKED ISSUE #31784: SQL: querying an alias having different mappings indices generates an incorrect error message
For an alias defined as 

```
$ curl -XGET "localhost:9200/_alias/test_alias?pretty"
{
  "test_emp_copy" : {
    "aliases" : {
      "test_alias" : { }
    }
  },
  "library" : {
    "aliases" : {
      "test_alias" : { }
    }
  },
  "test_emp" : {
    "aliases" : {
      "test_alias" : { }
    }
  }
}
```

the error message received is:

```
sql> select * from test_alias;
Bad request [Found 1 problem(s)
line 1:15: [test_alias] points to indices [library] and [library] which have different mappings. When using multiple indices, the mappings must be identical.]
```

(twice the `library` index mentioned instead of `library` and another index from the alias)
Those three indices mappings are like this:
* `test_emp_copy` and `test_emp` are identical
* `library` is completely different from the other two

### PR DESCRIPTION
**Pull request by costin**
Fix the naming in the verification message thrown for aliases over
multiple indices with different mappings.

Closes #31611 
Closes #31784

### CODE REVIEW

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolverTests.java [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+        EsIndex esIndex = resolution.get();
+
+        assertEquals(wildcard, esIndex.name());
+        assertEquals(sameMapping, esIndex.mapping());
+    }
+
+    @Test
+    public void testMergeDifferentMapping() throws Exception {
+        Map<String, EsField> oneMapping = TypesTests.loadMapping("mapping-basic.json", true);
+        Map<String, EsField> sameMapping = TypesTests.loadMapping("mapping-basic.json", true);
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolverTests.java]: Can you add one more test for two mappings that are logically the same (same field types, same field names) but the `json`s themselves are different (different fields order for example)?

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolverTests.java [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+
+        assertNotSame(oneMapping, sameMapping);
+        assertEquals(oneMapping, sameMapping);
+        assertNotEquals(oneMapping, differentMapping);
+
+        String wildcard = "*";
+        IndexResolution resolution = IndexResolver.merge(
+                Arrays.asList(IndexResolution.valid(new EsIndex("a", oneMapping)),
+                        IndexResolution.valid(new EsIndex("b", sameMapping)),
+                        IndexResolution.valid(new EsIndex("diff", differentMapping))),
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolverTests.java]: Worth putting the different mapping as first in the List? `(EsIndex("diff"...), EsIndex("same"..), EsIndex("one"))`

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolverTests.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolverTests.java]: ES mapping are always returned in order (which is important since the underlying `Map`s depend on it). Hence why the `loadMapping` has the `true` parameter otherwise the order is intentionally randomized (which causes the map equality to fail).

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolverTests.java (hunk 2 above)
Comment (costin) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/analysis/index/IndexResolverTests.java]: The order is somewhat important for this test since the comparison is done between the first entry and the rest.
The order above tests that a and b pass and that a and diff fail - there are two comparisons applied.
Putting diff first will cause only one comparison since and and b are not compared.
A minor detail that was done on purpose.

**Review by astefan — APPROVED** [review]

**Review by nik9000 — APPROVED** [review]
So long as @astefan likes it I'm happy.

**Comment by costin** [comment]
Thanks for reviewing folks!
