### PR TITLE
[CI] ShardSearchPhaseAPMMetricsTests testUniformCanMatchMetricAttributesWhenPlentyOfDocumentsInIndex failed

### LINKED ISSUE #140589: [CI] ShardSearchPhaseAPMMetricsTests testUniformCanMatchMetricAttributesWhenPlentyOfDocumentsInIndex failed
### CI Link

https://gradle-enterprise.elastic.co/s/giw7sna4jxtsk/console-log?anchor=6712&page=7

### Repro line

`./gradlew ":server:test" --tests "org.elasticsearch.search.TelemetryMetrics.ShardSearchPhaseAPMMetricsTests.testUniformCanMatchMetricAttributesWhenPlentyOfDocumentsInIndex" -Dtests.seed=2DD8D2A8DFF468CB -Dtests.locale=nnh -Dtests.timezone=Asia/Gaza -Druntime.java=25`

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

    java.lang.AssertionError: 
    Expected: a collection with size <5>
         but: collection size was <4>
        at __randomizedtesting.SeedInfo.seed([2DD8D2A8DFF468CB:98FDA0E4F8F74388]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2867)
        at org.elasticsearch.search.TelemetryMetrics.ShardSearchPhaseAPMMetricsTests.testUniformCanMatchMetricAttributesWhenPlentyOfDocumentsInIndex(ShardSearchPhaseAPMMetricsTests.java:450)

### PR DESCRIPTION
**Pull request by chrisparrinello**
Closes #140589 and #140603 

The underlying issue is that when gathering the search request attributes for the can-match APM metrics, we only do that for the first shard. The test is assuming that the search request attributes have all of the attributes including `time_range_filter_from`. If the first search shard request is on an empty shard, we don't drill down into the query to determine if this is a time range query so the `time_range_filter_from` will be missing from the search request attributes for all metrics for all of the shards. 

To fix this and ensure we're gathering as much search request attributes as possible for all search queries, we check each shard search request to see if there is a time request attribute in case it is missing in the cached search request attributes we've already parse from the first shard search request and then add it to the search request attributes.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/search/SearchRequestAttributesExtractor.java [hunk 1]
```diff
@@ -184,13 +184,13 @@ private static final class QueryMetadataBuilder {
...
     }
 
-    static final String TARGET_ATTRIBUTE = "target";
-    static final String SORT_ATTRIBUTE = "sort";
-    static final String QUERY_TYPE_ATTRIBUTE = "query_type";
-    static final String PIT_SCROLL_ATTRIBUTE = "pit_scroll";
-    static final String KNN_ATTRIBUTE = "knn";
-    static final String TIME_RANGE_FILTER_FIELD_ATTRIBUTE = "time_range_filter_field";
-    static final String TIME_RANGE_FILTER_FROM_ATTRIBUTE = "time_range_filter_from";
+    public static final String TARGET_ATTRIBUTE = "target";
```
Comment (spinscale) [inline server/src/main/java/org/elasticsearch/action/search/SearchRequestAttributesExtractor.java:187]: these could stay package private?

**Review by spinscale — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/action/search/SearchRequestAttributesExtractor.java (hunk 1 above)
Comment (chrisparrinello) [reply server/src/main/java/org/elasticsearch/action/search/SearchRequestAttributesExtractor.java:187]: Actually I think I have an incomplete change here. I wanted to reuse `TIME_RANGE_FILTER_FROM_ATTRIBUTE` instead of the literal string in `SearchService` so I made that constant public and decided to just make them all public. 

I'd like to definitely make `TIME_RANGE_FILTER_FROM_ATTRIBUTE` public and reuse that in `SearchService`. Should I keep the others still package private?

File: muted-tests.yml [hunk 2]
```diff
@@ -285,9 +285,9 @@ tests:
 - class: org.elasticsearch.packaging.test.DockerTests
   method: test130JavaHasCorrectOwnership
   issue: https://github.com/elastic/elasticsearch/issues/131369
-- class: org.elasticsearch.search.TelemetryMetrics.ShardSearchPhaseAPMMetricsTests
-  method: testUniformCanMatchMetricAttributesWhenPlentyOfDocumentsInIndex
-  issue: https://github.com/elastic/elasticsearch/issues/140603
+- class: org.elasticsearch.packaging.test.DockerTests
+  method: test072RunEsAsDifferentUserAndGroup
+  issue: https://github.com/elastic/elasticsearch/issues/140127
```
Comment (jozala) [inline muted-tests.yml:290]: Hi @chrisparrinello,
Was this muted tests added here on purpose or it is conflict resolution mistake?
I'm looking through the DockerTests failures and the issue #140127 is closed but the mute is still here.
If it is a mistake I could take care of that as part of the work I'm doing around DockerTests.

**Comment by chrisparrinello** [comment]
@jozala This is a mistake. I think I had a bad merge from main that accidentally added it. Please feel free to remove that muted test. Thanks!
