### PR TITLE
Correctly determine defaults of settings which depend on other settings

### LINKED ISSUE #47890: GET index/_settings?include_defaults returns the wrong default value for settings with default values dependent on other settings
The Get Index Settings API returns the wrong default for `index.soft_deletes.enabled` in the 7.x series.

This is because the default is computed based on the version the index was created in:
https://github.com/elastic/elasticsearch/blob/24882140b0e808a0973beb303350b47ae447b8bf/server/src/main/java/org/elasticsearch/index/IndexSettings.java#L233-L235

But the version is not included in the Settings object passed to the default calculation function when called by the Get Index Settings API with the `include_defaults` flag.  It looks like the Settings object passed to calculate the defaults in this circumstance is always empty, so any setting whose defaults depend on another setting is likely to be wrong as well.

---

Update:

This definitely impacts other settings, as can be seen in https://github.com/elastic/elasticsearch/issues/51194 where an incorrect default value of `index.merge.scheduler.max_merge_count` is returned from `GET index/settings?include_defaults` because its default value depends on the value of `index.merge.scheduler.max_thread_count`.

### PR DESCRIPTION
**Pull request by AthenaEryma**
This commit adjusts the behavior when calculating the diff between two
`AbstractScopedSettings` objects, so that the default values of settings
whose default values depend on the values of other settings are
correctly calculated. Previously, when calculating the diff, the default
value of a depended setting would be calculated based on the default
value of the setting(s) it depends on, rather than the current value of
those settings.

Fixes https://github.com/elastic/elasticsearch/issues/47890

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/common/settings/Setting.java [hunk 1]
```diff
@@ -486,7 +486,11 @@ private T get(Settings settings, boolean validate) {
      * @param defaultSettings the default settings object to diff against
      */
     public void diff(Settings.Builder builder, Settings source, Settings defaultSettings) {
-        if (exists(source) == false) {
+        if (exists(source) == false && exists(defaultSettings) == false) {
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/common/settings/Setting.java:489]: I think this might read better if the outer "doesn't exist in source" stays the same and then have two inner conditions for "if (exists in defaults) X else Y"

**Review by rjernst — APPROVED** [review]
LGTM, one suggestion
