### PR TITLE
Fix multi-node parsing in voting config exclusions REST API

### LINKED ISSUE #41587: Voting config exclusions API: node_name is not parsed as a comma-separated list
**Elasticsearch version** (`bin/elasticsearch --version`): >=7

**Description of the problem including expected versus actual behavior**: In the voting config exclusions API the `node_name` parameter is converted into an array of 1 element and not processed as a comma-separated list of individual filters as expected.

See line 52 here:
https://github.com/elastic/elasticsearch/blob/1038f23510e81b0edffb12d0dfd6a13179682bce/server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestAddVotingConfigExclusionAction.java#L50-L54

**Steps to reproduce**:
1. setup a 3 master nodes cluster
2. Try to add at least 2 master nodes to the voting exclusions list, e.g. do a `POST` on `http://es:9200/_cluster/voting_config_exclusions/node-1,node-2`

**Provide logs (if relevant)**:

> 400 Bad Request: add voting config exclusions request for [node-1,node-2] matched no master-eligible nodes"

### PR DESCRIPTION
**Pull request by barkbay**
Fix #41587 
This PR split the `node_name` parameter before it is processed by `resolveNodes`

### CODE REVIEW

**Comment by not-napoleon** [comment]
@barkbay I added the 7.1.0 label on the assumption that you intend to backport this.  If you end up not backporting for some reason, please remove that label.

**Review by ywelsch — COMMENTED** [review]
Good catch, and thank you for the PR. Can you also add the following test to Zen2RestApiIT?

```
public void testRemoveTwoNodesAtOnce() throws Exception {
    internalCluster().setBootstrapMasterNodeIndex(2);
    List<String> nodes = internalCluster().startNodes(3);
    ensureStableCluster(3);
    RestClient restClient = getRestClient();
    Response response = restClient.performRequest(new Request("POST", "/_cluster/voting_config_exclusions/" +
        nodes.get(2) + "," + nodes.get(0)));
    assertThat(response.getStatusLine().getStatusCode(), is(200));
    assertThat(response.getEntity().getContentLength(), is(0L));
    internalCluster().stopRandomNode(InternalTestCluster.nameFilter(nodes.get(0)));
    internalCluster().stopRandomNode(InternalTestCluster.nameFilter(nodes.get(2)));
    ensureStableCluster(1);
}
```

File: server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestAddVotingConfigExclusionAction.java [hunk 1]
```diff
@@ -47,15 +47,18 @@ public String getName() {
...
     protected RestChannelConsumer prepareRequest(final RestRequest request, final NodeClient client) throws IOException {
-        String nodeName = request.param("node_name");
-        AddVotingConfigExclusionsRequest votingConfigExclusionsRequest = new AddVotingConfigExclusionsRequest(
-            new String[]{nodeName},
-            TimeValue.parseTimeValue(request.param("timeout"), DEFAULT_TIMEOUT, getClass().getSimpleName() + ".timeout")
-        );
         return channel -> client.execute(
             AddVotingConfigExclusionsAction.INSTANCE,
-            votingConfigExclusionsRequest,
+            resolveVotingConfigExclusionsRequest(request),
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/rest/action/admin/cluster/RestAddVotingConfigExclusionAction.java]: Tests on the PR are failing because this is no lazy-resolved. Please move the request creation back to the prepareRequest method. Thank you.

**Comment by ywelsch** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Review by ywelsch — APPROVED** [review]
LGTM. The packaging test failures are unrelated to this PR.
