### PR TITLE
Fix inner hits + aggregations concurrency bug

### LINKED ISSUE #122419: IllegalStateException during search: "Error retrieving path ..."
Got a stack trace from a suppressed REST error on Serverless (anonymized). Looks like it could be originating from [here](https://github.com/elastic/elasticsearch/blob/2c846e735192d12cdb6fb85c5e711fc49a9cd6bd/server/src/main/java/org/elasticsearch/search/SearchHit.java#L1062) in `SearchHit.java`, although the stack trace doesn't really show this.

```
Failed to execute phase [query], all shards failed; shardFailures {[pZ7he6e-S6adoEWgKemdyA][some_index][0]: org.elasticsearch.transport.RemoteTransportException: [es-es-search-...][...][indices:data/read/search[phase/query]]
  Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
  Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: Fetch Failed [Error running fetch phase for doc [3197]]
  Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: Fetch Failed [Error running fetch phase for doc [3194]]
  Caused by: java.lang.IllegalStateException: Error retrieving path some_path
  }{[pZ7he6e-S6adoEWgKemdyA][some_index][1]: org.elasticsearch.transport.RemoteTransportException: [es-es-search-...][...][indices:data/read/search[phas
  e/query]]
  Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
  Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: Fetch Failed [Error running fetch phase for doc [6231]]
  Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: Fetch Failed [Error running fetch phase for doc [6228]]
  Caused by: java.lang.IllegalStateException: Error retrieving path some_path
  }{[pZ7he6e-S6adoEWgKemdyA][some_index][2]: org.elasticsearch.transport.RemoteTransportException: [es-es-search-...][...][indices:data/read/search[phase/query]]
  Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Query Failed [Failed to execute main query]
  Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: Fetch Failed [Error running fetch phase for doc [6615]]
  Caused by: org.elasticsearch.search.fetch.FetchPhaseExecutionException: Fetch Failed [Error running fetch phase for doc [6612]]    
  Caused by: java.lang.IllegalStateException: Error retrieving path some_path
  }

 │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:693)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:360)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:738)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:454)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:312)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:64)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations.safeOnFailure(ActionListenerImplementations.java:75)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.DelegatingActionListener.onFailure(DelegatingActionListener.java:32)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:54)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:593)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1776)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1509)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1643)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1618)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:44)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:45)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.search.SearchService.lambda$maybeWrapListenerForStackTrace$1(SearchService.java:540)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.acceptException(ActionListenerImplementations.java:188)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations.safeAcceptException(ActionListenerImplementations.java:64)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionListenerImplementations$DelegatingResponseActionListener.onFailure(ActionListenerImplementations.java:193)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:152)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:29)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:34)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
  │ at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  │ at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  │ at java.base/java.lang.Thread.run(Thread.java:1575)
  Caused by: org.elasticsearch.ElasticsearchException$1: Error retrieving path  some_path
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:725)
  │ at org.elasticsearch.server@9.0.0/org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:358)
  │ ... 26 more
  Caused by: java.lang.IllegalStateException: Error retrieving path some_path
```

### PR DESCRIPTION
**Pull request by benchaplin**
Resolves https://github.com/elastic/elasticsearch/issues/122419.

There's a concurrency bug that occurs when doing aggregations on inner hits. It can result in one of three exceptions:
- `java.lang.IllegalStateException: Error retrieving path`
- `java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.preloadedStoredFieldValues" is null`
- `java.lang.AssertionError: invalid decRef call: already closed`

The underlying issue is that `InnerHitSubContext` is not thread safe, yet instances are shared across leaf slice search threads during an aggregation. Specifically, the race condition occurs when `InnerHitSubContext.rootId` & `InnerHitSubContext.rootSource` fields are set and accessed concurrently by multiple threads.

The tests I've added to `TopHitsIT` reproduce the issue. If you paste those tests into main and run them a few times you should see one of the exceptions.

I've solved this by forking the `InnerHitSubContext` instances, similar to what was done here https://github.com/elastic/elasticsearch/pull/106990. `SearchExecutionContext` is at times accessed from `InnerHitSubContext`, so I also had to make sure the forked `SearchExecutionContext` was used in those cases.

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/metrics/TopHitsIT.java [hunk 1]
```diff
@@ -983,6 +987,67 @@ public void testTopHitsInNested() throws Exception {
...
+            assertTrue(source0.containsKey("reviewers"));
+
+            assertThat(innerHits.getAt(1).getId(), equalTo("1"));
+            assertThat(innerHits.getAt(1).getNestedIdentity().getField().string(), equalTo("comments"));
+            assertThat(innerHits.getAt(1).getNestedIdentity().getOffset(), equalTo(1));
+            Map<String, Object> source1 = innerHits.getAt(1).getSourceAsMap();
+            assertTrue(source1.containsKey("message"));
+            assertTrue(source1.containsKey("reviewers"));
+        });
+    }
```
Comment (javanna) [inline server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/metrics/TopHitsIT.java:1049]: this is a great reproducer! Should we have one for the parent child sub context too? Sounds like that may be affected by the same bug?

Comment (benchaplin) [reply server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/metrics/TopHitsIT.java:1049]: Good call! I had tunnel vision on the nested case. You're right - the bug also affects join field inner hits. I've added a test that reproduces the error in main.

**Review by javanna — APPROVED** [review]
LGTM great work

**Comment by javanna** [comment]
Hey @benchaplin I think it makes sense to backport this fix to 9.0 as well. Thoughts?

**Comment by benchaplin** [comment]
> Hey @benchaplin I think it makes sense to backport this fix to 9.0 as well. Thoughts?

Ah, agreed. Thanks for catching this, I got a little mixed up with versions.
