### PR TITLE
ConnectTransportException returns retryable BAD_GATEWAY

### LINKED ISSUE #118320: Change ConnectTransportException response code to 502
According to [RFC 9110 § 15.6.3](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6.3), the `502 Bad Gateway` response code is appropriate whenever:

> the server, while acting as a gateway or proxy, received an invalid response from an inbound server it accessed while attempting to fulfill the request.

These days we consider the ES REST to be acting as a gateway to the cluster (or clusters) being accessed, so that seems like a more appropriate code to use when returning a `ConnectTransportException` than today’s 500. More practically, our clients generally retry on a 502, but not on a 500, and retrying on a `ConnectTransportException` seems like the right thing to do.

Relates ES-10214

### PR DESCRIPTION
**Pull request by DiannaHohensee**
I took a spin through the code with `new ConnectTransportException`, and saw this [error case](https://github.com/elastic/elasticsearch/blob/1bad1cf6b2256f594361059a8090d2707aa54001/server/src/main/java/org/elasticsearch/transport/ProxyConnectionStrategy.java#L195). That one doesn't seem like it should be a retryable error 🤔 Is this status code change safe, or maybe we should change [that](https://github.com/elastic/elasticsearch/blob/1bad1cf6b2256f594361059a8090d2707aa54001/server/src/main/java/org/elasticsearch/transport/ProxyConnectionStrategy.java#L195) code to a different exception type?

Related ES-10214
Closes #118320

### CODE REVIEW

**Comment by mhl-b** [comment]
I think [that](https://github.com/elastic/elasticsearch/blob/1bad1cf6b2256f594361059a8090d2707aa54001/server/src/main/java/org/elasticsearch/transport/ProxyConnectionStrategy.java#L195) should be IllegalStateException, because we already have remote connection to another cluster.

Why it needs REST status attached? Do we send it back to the REST handler and client?

**Comment by DiannaHohensee** [comment]
Thanks for taking a look and confirming it seems strange, @mhl-b. I'll take a closer look at Proxy* -- I'm not familiar with it, atm.

I forgot to reference the ticket, but this relates to ES-10214 -- I just updated my description to include it. I don't myself know how the HTTP error code propagates back to the caller, but other folks believe that it does. I would think it could reasonably end up in a stack trace of 'caused by' errors, if not directly.

**Comment by DiannaHohensee** [comment]
Hmm. I think IllegalStateException would indicate ES has done something wrong. Whereas ES looks like it's throwing the ConnectTransportException when the information from the user doesn't match up with reality: like setting an address to a cluster and a cluster name, and then ES verifies that the connected to cluster's name matches, and it doesn't. I think we need a "user gave us a bad parameter" non-retryable exception?

There is [some more code](https://github.com/elastic/elasticsearch/blob/1bad1cf6b2256f594361059a8090d2707aa54001/server/src/main/java/org/elasticsearch/discovery/HandshakingTransportAddressConnector.java#L146-L171) throwing the ConnectTransportException, and I think the idea is that we connected successfully to some server, but the type of server is not what ES expected to find.

**Comment by DiannaHohensee** [comment]
After reviewing the `ConnectTransportException` uses, I think we need a new exception type, something like `InvalidRemoteNodeException`, to replace the `ConnectTransportException` use cases where the node connection is successful but the node type is unexpected. It doesn't seem like those error cases should be retryable.

@DaveCTurner for thoughts.

**Comment by DaveCTurner** [comment]
My reading of the HTTP spec is that we are indeed acting as a [gateway](https://www.rfc-editor.org/rfc/rfc9110.html#section-3.7-6) in this situation:

> A "gateway" (a.k.a. "reverse proxy") is an intermediary that acts as an origin server for the outbound connection but translates received requests and forwards them inbound to another server or servers [...] A gateway communicates with inbound servers using any protocol that it desires [...]

Moreover, if the remote node turns out to belong to a cluster with an unexpected name then `502 Bad Gateway` is a [valid response code](https://www.rfc-editor.org/rfc/rfc9110.html#name-502-bad-gateway):

> The 502 (Bad Gateway) status code indicates that the server, while acting as a gateway or proxy, received an invalid response from an inbound server it accessed while attempting to fulfill the request.

There's other ways that a bad in-cluster config might lead to a `ConnectTransportException` or a subclass, and indeed I can think of ways that this specific failure might go away on a retry. In any case, the effect on client retries is not really relevant here, at least not as much as following the HTTP spec. The whole notion of triggering client behaviour based solely on the HTTP response code is fundamentally doomed anyway, there's just too many different outcomes to map onto the very limited options available to us in the HTTP spec.

It's definitely not a client-side failure so we have to return some kind of 5xx error, and 502 seems more appropriate than 500. If clients choose to retry on all 502s then 🤷 that's not wrong I guess.

**Comment by mhl-b** [comment]
Would be nice to have an integ or yaml/rest test to show rest status propagation. I dont think status is very important, 500 or 502, since we [model REST over HTTP](https://martinfowler.com/articles/richardsonMaturityModel.html) and there is no strict requirement to confine to error codes, as David said there are not enough of them. So client still need to unwrap HTTP response to make any decision, including retry.

File: server/src/main/java/org/elasticsearch/transport/ConnectTransportException.java [hunk 1]
```diff
@@ -41,6 +42,16 @@ public ConnectTransportException(StreamInput in) throws IOException {
         }
     }
 
+    /**
+     * The ES REST API is a gateway to a single or multiple clusters. If there is an error connecting to other servers, then we should
+     * return a retryable 502 BAD_GATEWAY error, instead of the parent class' non-retryable 500 INTERNAL_SERVER_ERROR response code.
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/transport/ConnectTransportException.java:47]: Wording nit: there is no absolute concept of "retryable" for HTTP status codes. Clients generally have some heuristics about whether to retry on a failure, and 502s tend to be retried, but this is ultimately up to the client to decide.

```suggestion
      * The ES REST API is a gateway to a single or multiple clusters. If there is an error connecting to other servers, then we should
      * return a 502 BAD_GATEWAY status code instead of the parent class' 500 INTERNAL_SERVER_ERROR. Clients tend to retry on a 502 but not
      * on a 500, and retrying may help on a connection error.
```

**Review by DaveCTurner — APPROVED** [review]
LGTM except a couple of nits

**Comment by pawankartik-elastic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/119146)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
