### PR TITLE
By pass cancellation when closing sinks

### LINKED ISSUE #117253: [CI] EsqlNodeFailureIT testFailureLoadingFields failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #5155 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/gc4j6xtfeuris)
- [elasticsearch-periodic #5171 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/jgcqc66ekg64c)
- [elasticsearch-periodic #5165 / encryption-at-rest](https://gradle-enterprise.elastic.co/s/225bfxdmkaotm)
- [elasticsearch-periodic-platform-support #5125 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/xwnrs63eezkbo)
- [elasticsearch-periodic-platform-support #5107 / ubuntu-1804_platform-support-unix](https://gradle-enterprise.elastic.co/s/oxjovjjkeb7by)
- [elasticsearch-periodic-platform-support #5065 / amazonlinux-2_platform-support-aws](https://gradle-enterprise.elastic.co/s/7icob7mmh2cvc)
- [elasticsearch-periodic-platform-support #5053 / sles-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/hesqbfucjqrd2)
- [elasticsearch-periodic-platform-support #5029 / sles-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/f2yg3ll4wtqza)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.EsqlNodeFailureIT.testFailureLoadingFields" -Dtests.seed=32FCAC4806BB4D55 -Dtests.locale=en-SZ -Dtests.timezone=US/Samoa -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.EsqlNodeFailureIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testFailureLoadingFields),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Leftover exchanges ExchangeService{sinks=[ppb3SW3jTJKWyDpCoYnFjw:393/1]} on node node_s1
```

**Issue Reasons:**
- [8.x] 8 failures in test testFailureLoadingFields (1.1% fail rate in 748 executions)
- [8.x] 2 failures in step sles-12_platform-support-unix (11.8% fail rate in 17 executions)
- [8.x] 6 failures in pipeline elasticsearch-periodic-platform-support (27.3% fail rate in 22 executions)
- [8.x] 2 failures in pipeline elasticsearch-periodic (9.1% fail rate in 22 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
> **java.lang.AssertionError: Leftover exchanges ExchangeService{sinks=[veZSyrPATq2Sg83dtgK3Jg:700/3]} on node node_s4**

I looked into the test failure described in https://github.com/elastic/elasticsearch/issues/117253. The reason we don't clean up the exchange sink quickly is that, once a failure occurs, we cancel the request along with all its child requests. These exchange sinks will be cleaned up only after they become inactive, which by default takes 5 minutes. 

We could override the `esql.exchange.sink_inactive_interval` setting in the test to remove these exchange sinks faster. However, I think we should allow exchange requests that close exchange sinks to bypass cancellation, enabling quicker resource cleanup than the default inactive interval.

Closes #117253

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/exchange/ExchangeRequest.java [hunk 1]
```diff
@@ -40,6 +40,17 @@ public void writeTo(StreamOutput out) throws IOException {
         out.writeBoolean(sourcesFinished);
     }
 
+    @Override
+    public TaskId getParentTask() {
+        // Exchange requests with `sourcesFinished=true` complete the remote sink and return without blocking.
+        // Masking the parent task allows these requests to bypass task cancellation, ensuring cleanup of the remote sink.
+        // TODO: Maybe add a separate action/request for closing exchange sinks?
```
Comment (smalyshev) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/exchange/ExchangeRequest.java:47]: I wonder indeed if we shouldn't drop `sourcesFinished` and instead have ExchangeCloseRequest or something?

**Review by smalyshev — APPROVED** [review]

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/exchange/ExchangeService.java [hunk 2]
```diff
@@ -361,6 +353,15 @@ private void doFetchPageAsync(boolean allSourcesFinished, ActionListener<Exchang
                 }, responseExecutor)
             );
         }
+
+        @Override
+        public void close(ActionListener<Void> listener) {
+            if (finished.compareAndSet(false, true)) {
+                doFetchPageAsync(true, listener.delegateFailure((l, unused) -> l.onResponse(null)));
```
Comment (smalyshev) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/exchange/ExchangeService.java:360]: what happens here if the remote goes away or is slow? Does the whole request wait for the closing request to complete, and will it fail if it fails?

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/exchange/ExchangeRequest.java (hunk 1 above)
Comment (dnhatn) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/exchange/ExchangeRequest.java:47]: Yes, my plan is to remove sourcesFinished and replace it with ExchangeCloseRequest.

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/exchange/ExchangeService.java (hunk 2 above)
Comment (dnhatn) [reply x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/exchange/ExchangeService.java:360]: The entire request must wait for the closing. The (implicit) rule for the task is that once it is completed, its child tasks should also be completed, and its resources should be cleaned up unless that's not possible. Here, we only perform the actual `closing()` when encountering exceptions; in other cases, the remote sink should finish on its own.

**Comment by dnhatn** [comment]
Thanks @smalyshev!
