### PR TITLE
ESQL: Fix CASE when conditions are multivalued

### LINKED ISSUE #112359: ESQL: CASE bugs with multivalued conditions
### Description

I've been looking at case and found:
```
curl -uelastic:password -HContent-Type:application/json -XPOST localhost:9200/_query?pretty -d'{
    "query": "ROW a = [true, false] | EVAL c = CASE(MV_SLICE(a, 0, 2), \"foo\", \"bar\")"
}'


curl -uelastic:password -HContent-Type:application/json -XPOST localhost:9200/_query?pretty -d'{
    "query": "ROW a = [true, false] | EVAL c = CASE(a, \"foo\", \"bar\")"
}'


curl -uelastic:password -HContent-Type:application/json -XDELETE localhost:9200/test
curl -uelastic:password -HContent-Type:application/json -XPUT localhost:9200/test/_doc/1?refresh -d'{"a": [true, true]}'

curl -uelastic:password -HContent-Type:application/json -XPOST localhost:9200/_query?pretty -d'{
    "query": "FROM test | EVAL c = CASE(a, \"foo\", \"bar\")"
}'
```

These three produce incorrect output - the first two fail with class cast exceptions. The second produces `foo` instead of `bar` and a warning. This is because the implementation for CASE is from long before we had proper multivalue field handling.

### PR DESCRIPTION
**Pull request by nik9000**
When CASE hits a multivalued field it was previously either crashing on fold or evaluating it to the first value. Since booleans are loaded in sorted order from lucene that *usually* means `false`. This changes the behavior to line up with the rest of ESQL - now multivalued fields are treated as `false` with a warning.

You might say "hey wait! multivalued fields usually become `null`, not `false`!". Yes, dear reader, you are right. Very right. But! `CASE`'s contract is to immediatly convert its values into `true` or `false` using the standard boolean tri-valued logic. So `null` just become `false` immediately. This is how PostgreSQL, MySQL, and SQLite behave:
```
> SELECT CASE WHEN null THEN 1 ELSE 2 END;
2
```

They turn that `null` into a false. And we're right there with them. Except, of course, that we're turning `[false, false]` and the like into `null` first. See!? It's consitent. Consistently confusing, but sane at least.

The warning message just says "treating multivalued field as false" rather than explaining all of that.

This also fixes up a few of CASE's docs which I noticed were kind of busted while working on CASE. I think the docs generation is having a lot of trouble with CASE so I've manually hacked the right thing into place, but we should figure out a better solution eventually.

Closes #112359

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/Warnings.java [hunk 1]
```diff
@@ -34,28 +34,39 @@ public void registerException(Exception exception) {
     /**
      * Create a new warnings object based on the given mode
      * @param warningsMode The warnings collection strategy to use
-     * @param source used to indicate where in the query the warning occured
+     * @param source used to indicate where in the query the warning occurred
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/Warnings.java:37]: I've given us a little more flexibility, specifically so I can tell folks that multivalues in CASE default to `false`. If it's confusing why we do that read the PR description. Er, well, it's still confusing a bit. But that tries to explain it.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 2]
```diff
@@ -56,9 +62,12 @@ record Condition(Expression condition, Expression value) {}
         returnType = {
             "boolean",
             "cartesian_point",
+            "cartesian_shape",
             "date",
+            "date_nanos",
             "double",
             "geo_point",
+            "geo_shape",
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:70]: These were missing and easy enough to add while I was here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 3]
```diff
@@ -215,25 +224,19 @@ public boolean foldable() {
...
-    @Override
-    public Object fold() {
-        for (Condition condition : conditions) {
-            Boolean b = (Boolean) condition.condition.fold();
-            if (b != null && b) {
-                return condition.value.fold();
-            }
-        }
-        return elseValue.fold();
-    }
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:235]: We can let the superclass handle it.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 4]
```diff
@@ -303,40 +304,58 @@ public ExpressionEvaluator get(DriverContext context) {
...
             @Override
             public String toString() {
-                return "CaseEvaluator[resultType="
-                    + resultType
-                    + ", conditions="
-                    + conditionsFactories
-                    + ", elseVal="
-                    + elseValueFactory
-                    + ']';
+                return "CaseEvaluator[conditions=" + conditionsFactories + ", elseVal=" + elseValueFactory + ']';
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:315]: This was just making testing harder and doesn't really provide any debug value.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 5]
```diff
@@ -365,6 +385,12 @@ public Block eval(Page page) {
                                 if (b.isNull(0)) {
                                     continue;
                                 }
+                                if (b.getValueCount(0) > 1) {
+                                    condition.conditionWarnings.registerException(
+                                        new IllegalArgumentException("CASE expects a single-valued boolean")
+                                    );
+                                    continue;
+                                }
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:401]: Here's the core of the fix! It's fun how it's like 5 lines of fix, 200 testing, 200 ceremony to plumb the fix properly, and another 200 of docs updates.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java [hunk 6]
```diff
@@ -707,7 +705,7 @@ public static void testFunctionInfo() {
         );
 
         List<Set<String>> typesFromSignature = new ArrayList<>();
-        Set<String> returnFromSignature = new HashSet<>();
+        Set<String> returnFromSignature = new TreeSet<>();
```
Comment (nik9000) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java:708]: Makes comparing the errors easier because they are in alphabetical order....

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/RailRoadDiagram.java [hunk 7]
```diff
@@ -49,18 +49,28 @@ static String functionSignature(FunctionDefinition definition) throws IOExceptio
...
-                expressions.add(new Repetition(new Sequence(new Syntax(","), new Literal(arg.substring(0, arg.length() - 3))), 0, null));
-            } else {
-                if (first) {
-                    first = false;
+
+        if (definition.name().equals("case")) {
+            // CASE is so weird let's just hack this together manually
+            Sequence seq = new Sequence(new Literal("condition"), new Syntax(","), new Literal("trueValue"));
+            expressions.add(new Repetition(seq, 1, null));
+            expressions.add(new Repetition(new Literal("elseValue"), 0, 1));
```
Comment (nik9000) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/RailRoadDiagram.java:57]: I think CASE is the only function that has this funny signature. It's actually pretty helpful to see the railroad diagram for CASE too!

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java [hunk 8]
```diff
@@ -36,166 +36,117 @@ public CaseTests(@Name("TestCase") Supplier<TestCaseSupplier.TestCase> testCaseS
...
+            DataType.INTEGER,
+            DataType.LONG,
+            DataType.UNSIGNED_LONG,
+            DataType.IP,
+            DataType.VERSION,
+            DataType.CARTESIAN_POINT,
+            DataType.GEO_POINT,
+            DataType.CARTESIAN_SHAPE,
+            DataType.GEO_SHAPE
+        )) {
```
Comment (nik9000) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java:56]: Previously these were all written by hand, but we know a lot more about how to write these now.

File: x-pack/plugin/esql/qa/testFixtures/src/main/resources/conditional.csv-spec
Comment (alex-spies) [inline x-pack/plugin/esql/qa/testFixtures/src/main/resources/conditional.csv-spec:1]: Nice tests!
- I'd add one with `ROW foo = CASE([true, true], ...` just to make it obvious that `CASE` doesn't have implicit `ANY` or `ALL` logic.
- Should we add `ROW a = [true, false] | EVAL c = CASE(MV_SLICE(a, 0, 2), "foo", "bar")` as well? This one failed differently from others, so I guess it exercised a different code path? A test case with an mv expression inside `CASE` is probably a good idea, anyway. Or, similarly but more realistically, using a conversion function like `ROW a = ["true", "false"] | EVAL c = CASE(a::boolean, "foo", "bar")`
- If we want to be supremely paranoid, we could also check the interaction with multivalued union types, e.g. `FROM idx* | EVAL x = CASE(field::boolean, 1, 2)`; I'd only do that if we expect weird interactions with block loading, though, which probably is not the case.

**Review by alex-spies — COMMENTED** [review]
I'll have a second go at this tomorrow; I agree with the proposed semantics of `CASE` when presented with multi-valued booleans.

@luigidellaquila: I think `CASE` is something where users would profit from keywords like `ANY` and `ALL`. I think it's reasonable to have a multi-valued field and wanting to express something like `CASE (ANY multivalued_field, 1, 0)` or `CASE(ALL multivalued_field, 1, 0)`; without the warning that this PR adds, it could _look_ like `CASE` already does it, so it's good we are being explicit about it in the warning.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 9]
```diff
@@ -261,6 +267,11 @@ public Expression partiallyFold() {
                 continue;
             }
             modified = true;
+            Object o = condition.condition.fold();
+            if (o instanceof List) {
+                // multivalued field folds to null which folds to false
+                continue;
+            }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:274]: Maybe we should use a helper method (or two) on `Condition` to tell us whether the condition is always true/false? That could be reused in `Case.foldable` and would avoid the foldability logic to drift apart.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 10]
```diff
@@ -303,40 +312,58 @@ public ExpressionEvaluator get(DriverContext context) {
...
+                /*
+                 * We treat failures as null just like any other failure.
+                 * It's just that we then *immediately* convert it to
+                 * true or false using the tri-valued boolean logic stuff.
+                 * And that makes it into false. This is, *exactly* what
+                 * happens in PostgreSQL and MySQL and SQLite:
+                 * > SELECT CASE WHEN null THEN 1 ELSE 2 END;
+                 * 2
+                 * Rather than go into depth about this in the warning message,
+                 * we just say "false".
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:335]: CC @costin and @astefan : Nik is nicely making the MV semantics for CASE consistent.

Just FYI because we could also choose to define `CASE([true, true], ... ) == null` similarly to functions, which applied to multivalues just become `null`. I think Nik's approach is more useful, because making `CASE` on multivalues always return `null` would probably also imply that `CASE(true, a, [true, true], b)` should return `null`, even though it doesn't matter that the second condition is multivalued.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java [hunk 11]
```diff
@@ -828,6 +826,28 @@ public static void renderDocs() throws IOException {
         FunctionDefinition definition = definition(name);
         if (definition != null) {
             EsqlFunctionRegistry.FunctionDescription description = EsqlFunctionRegistry.description(definition);
+            if (name.equals("case")) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java:829]: nit: Should we use a constant for `case` here and in `RailRoadDiagram.java`? Maybe also in the function registry?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseExtraTests.java [hunk 12]
```diff
@@ -72,6 +72,19 @@ public void testPartialFoldDropsFirstFalse() {
         );
     }
 
+    public void testPartialFoldMv() {
+        Case c = new Case(
+            Source.synthetic("case"),
+            new Literal(Source.EMPTY, List.of(true, true), DataType.BOOLEAN),
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseExtraTests.java:78]: - Maybe let's randomize the booleans and the number of MVs?
- Maybe let's also consider cases with multiple multivalued conditions, not just one?
- Also maybe let's add cases where `partiallyFold` can fully fold, and returns the same as `fold`?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java [hunk 13]
```diff
@@ -36,166 +36,117 @@ public CaseTests(@Name("TestCase") Supplier<TestCaseSupplier.TestCase> testCaseS
...
+            suppliers.add(threeArgCase(true, true, type, List.of()));
+            suppliers.add(threeArgCase(false, false, type, List.of()));
+            suppliers.add(threeArgCase(null, false, type, List.of()));
+            suppliers.add(
+                threeArgCase(
+                    List.of(true, true),
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java:62]: nit: Let's randomize?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java:1]: A bit out of scope, but: shouldn't we also at least test the 4 and 5 parameter cases?

**Review by alex-spies — APPROVED** [review]
Thanks Nik, this is great. I think there's a bug in `Case.foldable` which we should fix before merging, otherwise my remarks are rather minor (suggesting more tests, as is becoming tradition :D ).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java (hunk 10 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:335]: > . I think Nik's approach is more useful
It's also the same approach as PostgreSQL.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java
Comment (nik9000) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java:1]: Yeah. We get those tests from the `Extra` tests right now. Not great.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java (hunk 13 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseTests.java:62]: ++

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseExtraTests.java (hunk 12 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseExtraTests.java:78]: The first two I'm doing now. The last one I'll have a think about. I think I'd like to make a method to test partiallFold inside `CaseTests` so it can use the test cases.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 14]
```diff
@@ -215,23 +224,20 @@ public boolean foldable() {
...
             }
-            Boolean b = (Boolean) condition.condition.fold();
-            if (b != null && b) {
+            Object o = condition.condition.fold();
+            if (o instanceof List) {
+                /*
+                 * multivalued fields fold to null which folds to false.
+                 * So they *are* foldable if the value is foldable.
+                 */
                 return condition.value.foldable();
```
[the remark this answers is not in the document]
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:233]: Can the list be empty? if so, is that the same as false?

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java (hunk 10 above)
Comment (costin) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:335]: I don't think Case makes the equivalence of null == false rather it checks if the condition is true.
That is  `SELECT CASE WHEN null THEN 1 ELSE 2 END` returns 2 because the condition `null` is not true. 
It's a subtle difference but it means `CASE(true, a, [true, true], b)` should return a because the condition is `true` so the else branch is not even evaluated.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 15]
```diff
@@ -215,23 +224,20 @@ public boolean foldable() {
             if (condition.condition.foldable() == false) {
                 return false;
             }
-            Boolean b = (Boolean) condition.condition.fold();
-            if (b != null && b) {
+            Object o = condition.condition.fold();
+            if (o instanceof List) {
```
Comment (costin) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:228]: I would rewrite this to `Boolean.TRUE.equals(b)` - takes care of nulls, list and other values.

**Review by costin — APPROVED** [review]
I might be overlooking some implementation details however I would focus on defining the contract of Case as the condition having to be a single-value true; anything else (multi value, false, null, etc...) would cause the else branch to be evaluated which would repeat the above process.
There's a question on whether we should give a warning when checking for true - which we could add (better be safe than sorry) however to your point, this is not about null == false rather about the value not being true.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java (hunk 14 above)
[the remark this answers is not in the document]
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:233]: I don't think lists occur unless they have at least 2 elements.

I think the intention is to treat any multivalue the same as false, which I think is correct, but the implementation in these lines is a bug.

More interestingly, there could be lists with 1 element which is `true`. I'd say that's a bug because that should simply be a boolean literal, but I'm not sure we never create such literals, either.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseExtraTests.java (hunk 12 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/CaseExtraTests.java:78]: I've added a bunch of cases.

**Review by nik9000 — COMMENTED** [review]
@alex-spies wanted to have another look at this one with all the new tests.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java (hunk 11 above)
Comment (nik9000) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/AbstractFunctionTestCase.java:835]: Meh.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 16]
```diff
@@ -224,18 +227,13 @@ public boolean foldable() {
             if (condition.condition.foldable() == false) {
                 return false;
             }
-            Object o = condition.condition.fold();
-            if (o instanceof List) {
+            if (Boolean.TRUE.equals(condition.condition.fold())) {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:230]: ++

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java [hunk 17]
```diff
@@ -224,18 +227,13 @@ public boolean foldable() {
...
                 /*
                  * multivalued fields fold to null which folds to false.
                  * So they *are* foldable if the value is foldable.
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/conditional/Case.java:233]: I think the comment here means the converse.
```suggestion
                 * So they *are* foldable if remaining list of conditions is foldable.
```
Same in line 271.

**Review by alex-spies — APPROVED** [review]
Hey Nik, don't wait for another review from me! I was just curious about the added testing that you showed me the other day, but you had my thumbs-up already before that :)
