### PR TITLE
ESQL: Fix equals hashCode for functions

### LINKED ISSUE #104393: ESQL: missing equals and hashCode for some functions
Some functions are missing correct implementations for `equals` and `hashCode`. This applies at least to
- ~~[DateDiff](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateDiff.java)~~ **Update:** This one is actually fine.
- [DateExtract](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateExtract.java) and other `ConfigurationFunctions` (we could just implement this for `ConfigurationFunction` in this case).

Other functions may need to be checked as well.

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/104393.

For any descendants of `EsqlConfigurationFunction`, the `hashCode` and `equals` methods did not take the actual configuration into account. It is important that they do, since functions like `NOW` provide different results depending on the configuration; in particular, the actual `now` datetime is contained in the `EsqlConfiguration`.

Also, clean redundant implementations of `hashCode` and `equals` in other functions, whenever the inherited methods could just be used.
I went over all inheritors of `EsqlScalarFunction` for this.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/UnaryScalarFunction.java [hunk 1]
```diff
@@ -47,18 +46,4 @@ public final Expression field() {
     public DataType dataType() {
         return field.dataType();
     }
-
-    @Override
-    public final int hashCode() {
-        return Objects.hash(field);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/UnaryScalarFunction.java:53]: The implementation in `Function` also hashes the class name, likely causing fewer collisions.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/UnaryScalarFunction.java [hunk 2]
```diff
@@ -47,18 +46,4 @@ public final Expression field() {
...
-    }
-
-    @Override
-    public final boolean equals(Object obj) {
-        if (obj == null || obj.getClass() != getClass()) {
-            return false;
-        }
-        UnaryScalarFunction other = (UnaryScalarFunction) obj;
-        return Objects.equals(other.field, field);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/UnaryScalarFunction.java:62]: Redundant, the implementation in `Function` already checks equality based on the children (all of the expressions).

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/math/RationalUnaryPredicate.java [hunk 3]
```diff
@@ -1,36 +0,0 @@
...
-
-import org.elasticsearch.xpack.esql.expression.function.scalar.UnaryScalarFunction;
-import org.elasticsearch.xpack.ql.expression.Expression;
-import org.elasticsearch.xpack.ql.tree.Source;
-import org.elasticsearch.xpack.ql.type.DataType;
-import org.elasticsearch.xpack.ql.type.DataTypes;
-
-import static org.elasticsearch.xpack.ql.expression.TypeResolutions.isType;
-
-public abstract class RationalUnaryPredicate extends UnaryScalarFunction {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/math/RationalUnaryPredicate.java:18]: This was unused altogether.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/CsvTests.java [hunk 4]
```diff
@@ -455,7 +455,7 @@ private static void opportunisticallyAssertPlanSerialization(PhysicalPlan... pla
                 }
             } while (tmp.children().isEmpty() == false && (tmp = tmp.children().get(0)) != null);
 
-            SerializationTestUtils.assertSerialization(plan);
+            SerializationTestUtils.assertSerialization(plan, configuration);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/CsvTests.java:458]: The config was _always_ important for serialization and subsequent deserialization to produce equal results; now our csv tests actually catch this: without using the correct `EsqlConfiguration`, differences are being detected in e.g. `date_format` (and rightly so).

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/AbstractConfigurationFunctionTestCase.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+import org.elasticsearch.xpack.esql.session.EsqlConfiguration;
+import org.elasticsearch.xpack.ql.expression.Expression;
+import org.elasticsearch.xpack.ql.tree.Source;
+import org.elasticsearch.xpack.ql.util.StringUtils;
+
+import java.util.List;
+
+import static org.elasticsearch.xpack.esql.SerializationTestUtils.assertSerialization;
+
+public abstract class AbstractConfigurationFunctionTestCase extends AbstractFunctionTestCase {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/AbstractConfigurationFunctionTestCase.java:24]: @not-napoleon maybe we should (separately to this PR) add test cases for functions that rely on the `EsqlConfig`. E.g. `NOW` actually derives its value from the config, which maybe could use a nice randomized test.

Comment (not-napoleon) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/AbstractConfigurationFunctionTestCase.java:24]: That's a good point.  Let's get a ticket open for that, so we don't forget.  for `NOW` at least, it might make sense for it to not use `AbstractFunctionTestCase` at all, since it doesn't really have any parameters we need to randomize, null, type check, etc.

**Review by astefan — APPROVED** [review]
LGTM 👍

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/AbstractConfigurationFunctionTestCase.java (hunk 5 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/expression/function/scalar/AbstractConfigurationFunctionTestCase.java:24]: Here we go: https://github.com/elastic/elasticsearch/issues/107997
