### PR TITLE
Fix leftover exchange in ManyShardsIT

### LINKED ISSUE #112406: [CI] ManyShardsIT testRejection failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4969 / ubuntu-1804_platform-support-unix](https://gradle-enterprise.elastic.co/s/v7wt54jrge5bk)
- [elasticsearch-periodic-platform-support #4969 / rhel-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/tvfmzom67o4g4)
- [elasticsearch-periodic-platform-support #4956 / rhel-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/hx4iw4hbrghy6)
- [elasticsearch-periodic-platform-support #4917 / oraclelinux-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/cq5vd645btz2k)
- [elasticsearch-periodic-platform-support #4917 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/7h6flqtbttdng)
- [elasticsearch-periodic-platform-support #4912 / rocky-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/3l72rlxudvv7e)
- [elasticsearch-periodic #4932 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/2ufvfjk3g7rb4)
- [elasticsearch-periodic-platform-support #4897 / rhel-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/xtngntjlhf6mc)
- [elasticsearch-periodic-platform-support #4887 / almalinux-8-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/uqo3qnhjh5gio)

**Reproduction Line:**
```
./gradlew ':x-pack:plugin:esql:internalClusterTest' --tests "org.elasticsearch.xpack.esql.action.ManyShardsIT.testRejection" -Dtests.seed=26D51210A7272351 -Dtests.locale=sr-Latn-RS -Dtests.timezone=Asia/Irkutsk -Druntime.java=22
```

**Applicable branches:**
8.15

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.ManyShardsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRejection),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Leftover exchanges ExchangeService{sinks=[M6axhOYHQBqTPJ2FDslNUA:1343]} on node node_s1
```

**Issue Reasons:**
- [8.15] 9 failures in test testRejection (1.8% fail rate in 488 executions)
- [8.15] 6 failures in pipeline elasticsearch-periodic-platform-support (37.5% fail rate in 16 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #112418: [CI] ManyShardsIT testLimitConcurrentShards failing
**Build Scans:**
- [elasticsearch-periodic #4932 / single-processor-node-tests](https://gradle-enterprise.elastic.co/s/2ufvfjk3g7rb4)
- [elasticsearch-periodic-platform-support #4887 / almalinux-8-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/uqo3qnhjh5gio)
- [elasticsearch-periodic-platform-support #4842 / almalinux-8-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/zb32v6a3yszva)

**Reproduction Line:**
```
./gradlew ':x-pack:plugin:esql:internalClusterTest' --tests "org.elasticsearch.xpack.esql.action.ManyShardsIT.testRejection" -Dtests.seed=DFF7E1E07DD36FD4 -Dtests.configure_test_clusters_with_one_processor=true -Dtests.locale=de-BE -Dtests.timezone=Africa/Juba -Druntime.java=22
```

**Applicable branches:**
8.15

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.ManyShardsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testLimitConcurrentShards),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Leftover exchanges ExchangeService{sinks=[IybrvFhSTFGeqtzCfW4AWA:1075]} on node node_s1
```

**Issue Reasons:**
- [8.15] 3 failures in test testLimitConcurrentShards (0.7% fail rate in 422 executions)
- [8.15] 2 failures in step almalinux-8-aarch64_checkpart3_platform-support-arm (14.3% fail rate in 14 executions)
- [8.15] 2 failures in pipeline elasticsearch-periodic-platform-support (14.3% fail rate in 14 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #112424: [CI] ManyShardsIT testConcurrentQueries failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4837 / oraclelinux-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/o6nxlzn3zqtry)
- [elasticsearch-periodic-platform-support #4827 / ubuntu-2004_platform-support-unix](https://gradle-enterprise.elastic.co/s/ehimkavn2sf2g)
- [elasticsearch-periodic-platform-support #4804 / oraclelinux-7_platform-support-unix](https://gradle-enterprise.elastic.co/s/aeeddt3drx5cq)

**Reproduction Line:**
```
./gradlew ':x-pack:plugin:esql:internalClusterTest' --tests "org.elasticsearch.xpack.esql.action.ManyShardsIT.testRejection" -Dtests.seed=5A24321944C32423 -Dtests.locale=nus -Dtests.timezone=America/Indiana/Vincennes -Druntime.java=22
```

**Applicable branches:**
8.15

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.ManyShardsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testConcurrentQueries),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Leftover exchanges ExchangeService{sinks=[bH0PBiWGQ_SCC4Ahkoh8GQ:726]} on node node_s0
```

**Issue Reasons:**
- [8.15] 3 failures in test testConcurrentQueries (1.5% fail rate in 195 executions)
- [8.15] 2 failures in step oraclelinux-7_platform-support-unix (28.6% fail rate in 7 executions)
- [8.15] 3 failures in pipeline elasticsearch-periodic-platform-support (42.9% fail rate in 7 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
In the `ManyShardsIT#testRejection` test, we intercept exchange requests and fail them with EsRejectedExecutionException, verifying that we return a 400 response instead of a 500.

The issue with the current test is that if a data-node request never arrives because the whole request was canceled after the exchange request failed—the leftover exchange sink remains until it times out, which defaults to 5 minutes. This change adjusts the test to use a single data node and ensures exchange requests are only failed after the data-node request has arrived.

Closes #112406
Closes #112418
Closes #112424

### CODE REVIEW

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/ManyShardsIT.java [hunk 1]
```diff
@@ -113,32 +129,54 @@ public void testConcurrentQueries() throws Exception {
...
-        }
+        DiscoveryNode dataNode = randomFrom(internalCluster().clusterService().state().nodes().getDataNodes().values());
+        String indexName = "single-node-index";
+        client().admin()
+            .indices()
+            .prepareCreate(indexName)
+            .setSettings(
+                Settings.builder()
+                    .put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, 0)
+                    .put("index.routing.allocation.require._name", dataNode.getName())
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/ManyShardsIT.java:140]: This makes it so that only a single data node is responsible for the index, right? Rather than all data nodes, as before?

I wonder if that changes the test case meaningfully. Maybe it'd be interesting to also test that all is well if a random number (>0) of nodes respond with a rejection, while some nodes send the expected result, instead.

**Review by alex-spies — APPROVED** [review]
I'm not super familiar with this neck of the ESQL woods, but this LGTM.

My understanding is that this only fixes what happens on the data nodes, which are not under test in the test case. So this change should be fine.

**Comment by alex-spies** [comment]
Also, thanks @dnhatn for taking care of this!

**Comment by dnhatn** [comment]
Thanks Alex!
