### PR TITLE
[TestFix] ExplainLifecycleIT testStepInfoPreservedOnAutoRetry failing

### LINKED ISSUE #114220: [CI] ExplainLifecycleIT testStepInfoPreservedOnAutoRetry failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4300 / windows-2019_checkpart5_platform-support-windows](https://gradle-enterprise.elastic.co/s/6bytzpvkaj234)
- [elasticsearch-pull-request #34683 / part-5](https://gradle-enterprise.elastic.co/s/mfjovvtti45ni)
- [elasticsearch-pull-request #34640 / part-5-arm](https://gradle-enterprise.elastic.co/s/6ciyzpr44gpmi)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:ilm:qa:multi-node:javaRestTest" --tests "org.elasticsearch.xpack.ilm.ExplainLifecycleIT.testStepInfoPreservedOnAutoRetry" -Dtests.seed=15616B811AA8CEDA -Dtests.locale=sd-Deva -Dtests.timezone=Etc/GMT+3 -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testStepInfoPreservedOnAutoRetry'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.ilm.ExplainLifecycleIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: not null
     but: was null
```

**Issue Reasons:**
- [main] 3 failures in test testStepInfoPreservedOnAutoRetry (1.0% fail rate in 291 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (2.6% fail rate in 77 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by lukewhiting**
Fix for [ES#114220 - [CI] ExplainLifecycleIT testStepInfoPreservedOnAutoRetry failing](https://github.com/elastic/elasticsearch/issues/114220)

After running unstable test for 500+ iterations using random parameters from failing runs, I was unable to reproduce the failure but suspect it's possibly due to a timeout being too short in the busy CI runs.

For now, I have unmuted the test, extended the timeout of the `assertBusy` that checks for the ILM run retries and added additional logging to print out the last response in the event the `assertBusy` times out to assist in future debugging if the extended timeout does not fix the issue.

### CODE REVIEW

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java [hunk 1]
```diff
@@ -305,16 +307,23 @@ public void testStepInfoPreservedOnAutoRetry() throws Exception {
...
+                assertThat((int) explainIndex.get("failed_step_retry_count"), greaterThan(0));
+                assertThat(
+                    explainIndex.get("previous_step_info").toString(),
+                    containsString("rollover_alias [" + aliasName + "] does not point to index [" + indexName + "]")
+                );
+            }, 30, TimeUnit.SECONDS);
+        } catch (AssertionError e) {
+            logger.error("Assertion failed with response: {}", explainIndexRef.get());
+            throw e;
+        }
```
Comment (dakrone) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:326]: If you didn't want to catch the AssertionError (we generally try never to catch any Error classes, only Exceptions), it may be better to put a logging statement at `info` level inside of the `assertBusy()`, which would log the output each time (and show up in the logs if it fails again). Then you wouldn't need the `AtomicReference` either.

**Review by dakrone — APPROVED** [review]
LGTM, I left one comment

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java (hunk 1 above)
Comment (lukewhiting) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:326]: That is how I initially implemented it however it really did pollute the logs and looked a bit confusing as it logged out during each attempt at the assertBusy.

I also thought about adding it as a message param to each assertion however those aren't lazy evaluated like a log message param so it was adding to the execution time to do the map.toString for each assertion when it was 99% of the time not actually used.

In the end I decided to optimized for execution time (I'm always conscious time == money in the cloud CI environment) and conciseness but happy to go for logging it out each time if you feel strongly about not catching errors :-)

Comment (dakrone) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:326]: I think it'd be nice to avoid the error catching if possible, so I would advocate for adding the message param to the assertions you think are most likely to fail (`assertBusy`'s back-off gets longer and longer, so I don't think it'd be too bad). Then it's only returned if the entire thing fails.

Comment (lukewhiting) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java]: Switched to using a message param on the assertions and saving the message to a var so it's only computed once per run

**Comment by lukewhiting** [comment]
Seems the dice roll was in our favour an the IT in question actually failed on the latest CI run, despite the longer timeout so I could take a look at the full state of things: https://gradle-enterprise.elastic.co/s/lituf73fyko2o/console-log/task/:x-pack:plugin:ilm:qa:multi-node:javaRestTest?anchor=57&page=1

**Comment by lukewhiting** [comment]
buildkite test this

**Comment by dakrone** [comment]
> I have pushed a new commit that adds addition logic to explicitly prevent the previous step info getting nulled out if the state update is a step auto retry or a move to an error state.

I think this is useful, it means that we wouldn't remove the step index until we move forward, which I think more closely matches the original request.
