### PR TITLE
Skip Shrink when numberOfShards not changed

### LINKED ISSUE #33275: Allow ILM's Shrink Action to progress successfully on indices with 1 shard
When a user specifies the shrink action and the index it is supposed to shrink already has only 1 shard, this error crops up:

        "failed_step": "shrink",
        "phase": "warm",
        "action_time": "1535643967009",
        "rollover_alias": "thing-alias",
        "phase_time": "1535643367314",
        "step_info": "{\"type\":\"illegal_argument_exception\",\"reason\":\"can't shrink an index with only one shard\"}",

ILM should just noop this (or shrink should).

### PR DESCRIPTION
**Pull request by talevy**
Previously, ShrinkAction would fail if
it was executed on an index that had
the same number of shards as the target
shrunken number.

This PR introduced a new BranchingStep that
is used inside of ShrinkAction to branch which
step to move to next, depending on the
shard values. So no shrink will occur if the
shard count is unchanged.

Fixes #33275.

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/BranchingStep.java [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+import org.apache.logging.log4j.Logger;
+import org.apache.lucene.util.SetOnce;
+import org.elasticsearch.cluster.ClusterState;
+import org.elasticsearch.cluster.metadata.IndexMetaData;
+import org.elasticsearch.index.Index;
+
+import java.util.Objects;
+import java.util.function.BiPredicate;
+
+public class BranchingStep extends ClusterStateActionStep {
```
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/BranchingStep.java]: Can you add javadocs please?

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java [hunk 2]
```diff
@@ -102,8 +101,14 @@ public ClusterState execute(final ClusterState currentState) throws IOException
                     } else {
                         state = IndexLifecycleRunner.moveClusterStateToNextStep(index, state, currentStep.getKey(),
                             currentStep.getNextStepKey(), nowSupplier, false);
+                        // set here to make sure that the clusterProcessed knows to execute the
+                        // correct step if it an async action
+                        nextStepKey = currentStep.getNextStepKey();
```
Comment (dakrone) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java]: Can you move this to line 99 (before the `null` check) and then use the var so that we don't call `getNextStepKey()` three times, I want to avoid any situation in the future where subsequent calls could garner a different result.

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java [hunk 3]
```diff
@@ -86,12 +86,11 @@ public ClusterState execute(final ClusterState currentState) throws IOException
...
-                nextStepKey = currentStep.getNextStepKey();
                 if (currentStep instanceof ClusterStateActionStep) {
                     // cluster state action step so do the action and
                     // move the cluster state to the next step
-                    logger.trace("[{}] performing cluster state action ({}) [{}], next: [{}]",
-                        index.getName(), currentStep.getClass().getSimpleName(), currentStep.getKey(), currentStep.getNextStepKey());
+                    logger.trace("[{}] performing cluster state action ({}) [{}]",
+                        index.getName(), currentStep.getClass().getSimpleName(), currentStep.getKey());
                     try {
                         state = ((ClusterStateActionStep) currentStep).performAction(index, state);
```
Comment (dakrone) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java]: In the future perhaps we will want to return `Tuple<ClusterState, Step.SteyKey>` from this. The disconnect in terms of the ordering of how things have to be called feels a little weird to me, I'd prefer it to be completely functional.

What do you think?

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java [hunk 4]
```diff
@@ -86,12 +86,11 @@ public ClusterState execute(final ClusterState currentState) throws IOException
             // either get to a step that isn't a cluster state step or a
             // cluster state wait step returns not completed
             while (currentStep instanceof ClusterStateActionStep || currentStep instanceof ClusterStateWaitStep) {
-                nextStepKey = currentStep.getNextStepKey();
                 if (currentStep instanceof ClusterStateActionStep) {
                     // cluster state action step so do the action and
                     // move the cluster state to the next step
-                    logger.trace("[{}] performing cluster state action ({}) [{}], next: [{}]",
-                        index.getName(), currentStep.getClass().getSimpleName(), currentStep.getKey(), currentStep.getNextStepKey());
+                    logger.trace("[{}] performing cluster state action ({}) [{}]",
```
Comment (dakrone) [inline x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java]: Maybe since we're losing the trace logging for where we're going to move to on the next step, we can add it below before we call `moveClusterStateToNextStep`?

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/BranchingStep.java [hunk 5]
```diff
@@ -0,0 +1,109 @@
...
+     * next step to run, otherwise nextStepKeyOnFalse is.
+     *
+     * throws {@link UnsupportedOperationException} if performAction was not called yet
+     *
+     * @return next step to execute
+     */
+   @Override
+   public final StepKey getNextStepKey() {
+        if (predicateValue.get() == null) {
+            throw new UnsupportedOperationException("Cannot call getNextStepKey before performAction");
```
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/BranchingStep.java]: I think this should be `IllegalStateException`, because we've reached a state where we want the next step before the action has been performed

**Review by dakrone — CHANGES_REQUESTED** [review]
I left some comments, I still feel a little uneasy about the brittleness of this, but we can improve it in the future too.

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java (hunk 2 above)
Comment (talevy) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java]: yes

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java (hunk 3 above)
Comment (talevy) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java]: I think that would be a reasonable direction to go, yes.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/BranchingStep.java (hunk 1 above)
Comment (talevy) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/BranchingStep.java]: yup. I ended up pushing the docs down to the constructor, but I'll add some more description up here as well

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java (hunk 4 above)
Comment (talevy) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/indexlifecycle/ExecuteStepsUpdateTask.java]: ++

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/BranchingStep.java (hunk 5 above)
Comment (talevy) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/BranchingStep.java]: ++ much better

**Comment by talevy** [comment]
> I left some comments, I still feel a little uneasy about the brittleness of this, but we can improve it in the future too.

thanks for the review Lee!

I, too, feel uneasy about the brittleness of this. Should we have a path forward in place for 
fixing this tech-debt in following releases before accepting to merge this?

**Comment by jakelandis** [comment]
> Should we have a path forward in place for fixing this tech-debt in following releases before accepting to merge this?

@talevy - Can you log a refactoring issue with some thoughts on why this is brittle and a potential way to address ? I am putting together a list of the next round changes for ILM and this will likely be on that list.

**Review by dakrone — APPROVED** [review]
LGTM assuming CI is happy; I agree with @jakelandis for next steps on the brittleness. Open an issue and link this one, we can prioritize the tech debt for the next release.

**Comment by talevy** [comment]
opened https://github.com/elastic/elasticsearch/issues/38047 as a reference for future discussion

**Comment by talevy** [comment]
run elasticsearch-ci/1
