### PR TITLE
Consume `full_id` request parameter early

### LINKED ISSUE #21266: full_id parameter unrecognized at /_cat/nodes in 5.0
**Elasticsearch version**: `Version: 5.0.0, Build: 253032b/2016-10-26T05:11:34.737Z, JVM: 1.8.0_111`

**Plugins installed**: []

**JVM version**:

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**OS version**:

* Ubuntu 16.04.1
* `Linux elastic 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
In previous versions of elasticsearch, the `_cat/nodes` api accepted the parameter `full_id` to show the full node ID instead of an abbreviated version. It appears that this parameter is no longer accepted in `5.0`, and now returns a `400` response with an error:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "request [/_cat/nodes] contains unrecognized parameter: [full_id]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "request [/_cat/nodes] contains unrecognized parameter: [full_id]"
  },
  "status": 400
}
```

I'm not very familiar with the codebase, but according to [these lines](https://github.com/elastic/elasticsearch/blob/5.0/core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java#L217-L236), this parameter should still exist, correct?

This causes [elasticbeat](https://github.com/radoondas/elasticbeat/blob/master/beater/nodes.go#L18) to be unable to collect stats on individual nodes and significantly impairs its effectiveness.

**Steps to reproduce**:
 1. Install and start an Elasticsearch `5.0` node
 2. `GET _cat/nodes?full_id=true`

**Provide logs (if relevant)**:
> No log lines emitted in elasticsearch logs.

### PR DESCRIPTION
**Pull request by s1monw**
Since we now validate all consumed request parameter, users can't specify
`_cat/nodes?full_id=true|false` anymore since this parameter is consumed late.
This commit adds a test for this parameter and consumes it before request is processed.

Closes #21266

### CODE REVIEW

**Comment by s1monw** [comment]
@nik9000 @jasontedor can you take a look

File: core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java [hunk 1]
```diff
@@ -85,7 +85,7 @@ public RestChannelConsumer doCatRequest(final RestRequest request, final NodeCli
         clusterStateRequest.clear().nodes(true);
         clusterStateRequest.local(request.paramAsBoolean("local", clusterStateRequest.local()));
         clusterStateRequest.masterNodeTimeout(request.paramAsTime("master_timeout", clusterStateRequest.masterNodeTimeout()));
-
+        final boolean fullId = request.paramAsBoolean("full_id", false);
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java]: This is one way to do it, but I'm wondering why you opted to do it this way instead of using the infrastructure that exists for handling response parameters? Namely, override `AbstractCatAction#responseParams` (being sure to include the response params from super).

**Review by jasontedor — COMMENTED** [review]
I left a question.

File: core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java (hunk 1 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java]: because that is the most obvious way to do this. I like when thinks are obvious especially when you look where this is consumed you don't need to look for it, it's right where I'd expect it.

Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java]: This isn't where I would expect it to be consumed since it affects the output only, not the request handling.

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java]: that's a fair statement. I think if you put it anywhere else it's a bug. when you have request params then consume them in the request method.

Comment (s1monw) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java]: even further I think `AbstractCatAction#responseParams` is pretty obscure and I think we  should remove it if we can. It's just yet antother place we need to maintain and look for params. I don't know if we really need it

**Comment by s1monw** [comment]
I will push this soon unless anybody objects

**Comment by jasontedor** [comment]
> I will push this soon unless anybody objects

@s1monw I don't understand why this PR was merged, I think we were in the middle of a discussion (I'm sorry, I was sleeping when you posted this comment)?

**Comment by s1monw** [comment]
> @s1monw I don't understand why this PR was merged, I think we were in the middle of a discussion (I'm sorry, I was sleeping when you posted this comment)?

I want to give this CI cycles and there was no objection to the code as you said it's _This is one way to do it_

**Comment by jasontedor** [comment]
> I want to give this CI cycles 

You can do this by asking the PR CI to test it again.

> and there was no objection to the code as you said it's This is one way to do it

You do not have an LGTM, I was trying to have a dialogue with you.

File: core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java (hunk 1 above)
Comment (s1monw) [inline core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java]: yeah that's fine - it's an exception and that is why you likely added this. In this case we have no exception and doing it without hiding this parameter in some special method was possible. I strongly encourage people to do it this way. I don't think this falls under _taste_ we can't hide stuff just because we have an abstraction

**Comment by s1monw** [comment]
> You do not have an LGTM, I was trying to have a dialogue with you.

I know, we have the dialog but it's unrelated to this change it's a taste question. I really don't think this should wait much longer for such a question so I took the change and asked other to object which is a fair game. Nothing personal here you can still object and I back it out but not for a taste question there must be a technical reason.

**Comment by s1monw** [comment]
> You can do this by asking the PR CI to test it again.

thank you I know how our system works
