### PR TITLE
Change year max digits for strict_date_optional_time and date_optional_time

### LINKED ISSUE #52396: Arithmetic_exception(long overflow) when using rangeQuery
Hi,

My index mapping is something like:
{
  "properties": {
    "datetime": {
      "type": "date"
    }
  }
}

I am querying the following search query (post):

{
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "dateTime": {
              "from": -316800000,
              "to": 345354353,
              "include_lower": true,
              "include_upper": true,
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
}

and then i receive  ArithmeticException: long overflow. It seems like the formatter ([strict_date_optional_time||epoch_millis]) is paring the long to a wrong year and then get this error.
This didn't happen on ES 7.3.0.. we are now using 7.5.2, and it also happens on 7.6.0
When i am adding "format":"epoch_millis" to the query, it works without this exception.

Please advice.
Thanks,
Shirley.

Caused by: java.lang.ArithmeticException: long overflow
        at java.lang.Math.multiplyExact(Math.java:892) ~[?:1.8.0_201-1-ojdkbuild]
        at java.time.Instant.toEpochMilli(Instant.java:1237) ~[?:1.8.0_201-1-ojdkbuild]
        at org.elasticsearch.index.mapper.DateFieldMapper$Resolution$1.convert(DateFieldMapper.java:83) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.parseToLong(DateFieldMapper.java:409) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.mapper.DateFieldMapper$DateFieldType.isFieldWithinQuery(DateFieldMapper.java:422) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.query.RangeQueryBuilder.getRelation(RangeQueryBuilder.java:447) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.query.RangeQueryBuilder.doRewrite(RangeQueryBuilder.java:464) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:265) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.query.BoolQueryBuilder.rewriteClauses(BoolQueryBuilder.java:458) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.query.BoolQueryBuilder.doRewrite(BoolQueryBuilder.java:425) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.query.AbstractQueryBuilder.rewrite(AbstractQueryBuilder.java:265) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.builder.SearchSourceBuilder.rewrite(SearchSourceBuilder.java:962) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.builder.SearchSourceBuilder.rewrite(SearchSourceBuilder.java:82) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:68) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:51) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.internal.ShardSearchRequest$RequestRewritable.rewrite(ShardSearchRequest.java:333) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.internal.ShardSearchRequest$RequestRewritable.rewrite(ShardSearchRequest.java:323) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.index.query.Rewriteable.rewrite(Rewriteable.java:68) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:639) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.SearchService.createSearchContext(SearchService.java:617) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:580) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:545) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:348) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.search.SearchService.lambda$executeQueryPhase$1(SearchService.java:340) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.action.ActionListener.lambda$map$2(ActionListener.java:146) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58) ~[elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.5.2.jar:7.5.2]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.2.jar:7.5.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201-1-ojdkbuild]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201-1-ojdkbuild]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201-1-ojdkbuild]
[2020-02-16T16:21:57,411][DEBUG][o.e.a.s.TransportSearchAction] [IL105580WIN] [test][0], node[Dbq1AHCtSy-UbRY6AgxKCQ], [P], s[STARTED], a[id=jIBJqNtSTZ2Zq8XIn10eHA]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={"query":{"bool":{"filter":[{"range":{"dateTime":{"from":-316800000,"to":345354353,"include_lower":true,"include_upper":true,"boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}}}}]

### LINKED ISSUE #72191: ES 7 changes which dates `date_optional_time` can successfully parse
**Elasticsearch version** (`bin/elasticsearch --version`):
```
Version: 7.12.0, Build: default/tar/78722783c38caa25a70982b5b042074cde5d3b3a/2021-03-18T06:17:15.410153305Z, JVM: 15.0.1
```

**Plugins installed**: []

**JVM version** (`java -version`):

```
jdk.app/Contents/Home/bin/java --version
openjdk 15.0.1 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system):

```
Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```

**Description of the problem including expected versus actual behavior**:

The values that the `date_optional_time` format can successfully parse have changed in ElasticSearch 7.
It seems to be related to dates where the year includes more than 5 digits.

I understand that ES7 includes a migration from Joda time formatters to Java time formatters and there are some expected breaking changes - as documented in the [Java time migration guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/migrate-to-java-time.html#java-time-migration-impacted-features).

This change in behaviour could be deliberate, but it's not clear from the documentation that this migration affects the `date_optional_time` built-in format. From the docs:

> The switch to java time only impacts custom `date` and `date_nanos` formats.

**Steps to reproduce**:

1. Create an index with a `date` field using the `date_optional_time` format:

```
curl -X PUT "localhost:9200/my-index-000001?pretty" -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "properties": {
      "date": {
        "type":   "date",
        "format": "date_optional_time"
      }
    }
  }
}
'
```

2. Attempt to create a new document with a value which was valid in ES6.8 (or an index created in ES6.8)

```
curl -X PUT "localhost:9200/my-index-000001/_create/1?pretty" -H 'Content-Type: application/json' -d'
{
  "date": "123456-01-02T12:34:56"
}
'
```

Error response:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "failed to parse field [date] of type [date] in document with id '1'. Preview of field's value: '123456-01-02T12:34:56'"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse field [date] of type [date] in document with id '1'. Preview of field's value: '123456-01-02T12:34:56'",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "failed to parse date field [123456-01-02T12:34:56] with format [date_optional_time]",
      "caused_by" : {
        "type" : "date_time_parse_exception",
        "reason" : "Text '123456-01-02T12:34:56' could not be parsed, unparsed text found at index 5"
      }
    }
  },
  "status" : 400
}
```

Example of this working successfully in ES6.8:
```
curl -X PUT "localhost:9200/my-index-000001?pretty" -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "_doc": {
        "properties": {
            "date": {
                "type":   "date",
                "format": "date_optional_time"
            }
        }
    }
  }
}
'
```

```
curl -X PUT "localhost:9200/my-index-000001/_doc/1?pretty" -H 'Content-Type: application/json' -d'
{
  "date": "123456-01-02T12:34:56"
}
'
```

Response:

```
{
  "_index" : "my-index-000001",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}
```

### PR DESCRIPTION
**Pull request by pgomulka**
We changed the default joda behaviour in `strict_date_optional_time` to
max 4 digits in a year. Java.time implementation should behave the same way.
At the same time `date_optional_time` should have 9digits for year part.

closes #52396
closes https://github.com/elastic/elasticsearch/issues/72191

### CODE REVIEW

**Comment by pgomulka** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java [hunk 1]
```diff
@@ -57,8 +57,21 @@
...
+        .appendLiteral('-')
+        .appendValue(DAY_OF_MONTH, 2, 2, SignStyle.NOT_NEGATIVE)
+        .optionalEnd()
+        .optionalEnd()
+        .toFormatter(Locale.ROOT)
+        .withResolverStyle(ResolverStyle.STRICT);
+
     private static final DateTimeFormatter STRICT_YEAR_MONTH_DAY_FORMATTER = new DateTimeFormatterBuilder()
-        .appendValue(ChronoField.YEAR, 4, 10, SignStyle.EXCEEDS_PAD)
+        .appendValue(ChronoField.YEAR, 4, 4, SignStyle.EXCEEDS_PAD)
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/common/time/DateFormatters.java:74]: Isn't this a breaking change? And it then limits the ability to use dates in the future (yes past 9999)? Is the expectation then that dates in the distant future must use epoch seconds or millis?

**Review by rjernst — COMMENTED** [review]
This seems like a breaking change at this point? I'm not necessarily opposed to it, it seems unlikely anyone was relying on it. I just want to confirm this will break anyone that is sending ISO dates in the distant future.

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java [hunk 2]
```diff
@@ -1040,7 +1053,7 @@
     /////////////////////////////////////////
 
     private static final DateTimeFormatter DATE_FORMATTER = new DateTimeFormatterBuilder()
-        .appendValue(ChronoField.YEAR, 1, 5, SignStyle.NORMAL)
+        .appendValue(ChronoField.YEAR, 1, 9, SignStyle.NORMAL)
```
Comment (pgomulka) [inline server/src/main/java/org/elasticsearch/common/time/DateFormatters.java:1056]: the "date_optional_time" fix for https://github.com/elastic/elasticsearch/issues/72191

File: server/src/main/java/org/elasticsearch/common/time/DateFormatters.java (hunk 1 above)
Comment (pgomulka) [reply server/src/main/java/org/elasticsearch/common/time/DateFormatters.java:74]: we have accidentally changed  the max length of year in strict_date_optional_time in 7.0.
If we do not consider this accidental change a bug, then agree it would be a breaking change. 
This change - limiting the length from 10 to 4 - might help parsing epoch millis with length between 4 and 10. At the moment the "date":1234567890 would be considered a year.
I think most of the time users are actually using the dates around our time, not so much in the future. So your suggestion that they should use epoch seconds/millis (or custom format) for such a dates makes sense to me.

**Review by rjernst — APPROVED** [review]
Alright, the argument makes sense to me. LGTM.
