### PR TITLE
[ESQL] Fix misleading error for missing external files

### LINKED ISSUE #146715: [ESQL] EXTERNAL with unreadable local file reports misleading "not a Parquet file" error
### Description

When `EXTERNAL "file://…"` targets a local parquet path that cannot be read (non-existent, wrong permissions, or outside `path.repo`), the resulting error is misleading: it claims the file is not valid Parquet, when the real cause is that the file could not be opened at all.

### Reproducer

Start a snapshot build with the external-datasource feature enabled (default) and run:

```
EXTERNAL "file:///tmp/does-not-exist.parquet"
| STATS c = COUNT(*)
```

### Expected

A clear error such as:

```
Failed to resolve external source [file:///tmp/does-not-exist.parquet]: file does not exist (or is not readable)
```

### Actual

```
Failed to resolve external source [file:///tmp/does-not-exist.parquet]: Failed to resolve metadata for [file:///tmp/does-not-exist.parquet]
…
Caused by: java.io.IOException: Could not read [file:///tmp/does-not-exist.parquet] as a Parquet file:
  ParquetStorageObjectAdapter@… is not a Parquet file (length is too low: 0)
    at org.elasticsearch.xpack.esql.datasource.parquet.ParquetFormatReader.newInvalidParquetFileException(ParquetFormatReader.java:169)
    at org.elasticsearch.xpack.esql.datasource.parquet.ParquetFormatReader.openParquetFile(ParquetFormatReader.java:160)
    at org.elasticsearch.xpack.esql.datasource.parquet.ParquetFormatReader.metadata(ParquetFormatReader.java:177)
    at org.elasticsearch.xpack.esql.datasources.FileSourceFactory.resolveMetadata(FileSourceFactory.java:110)
    at org.elasticsearch.xpack.esql.datasources.ExternalSourceResolver.resolveSingleSource(ExternalSourceResolver.java:501)
    …
```

The user has to read the root cause ("length is too low: 0") and guess that it means "file unreadable", when it literally reads as "you gave me a corrupt parquet file".

### Likely cause

`LocalStorageObject.length()` appears to return `0` instead of raising when the underlying file is missing or access is denied. The parquet reader then hits its minimum-size sanity check (valid Parquet files have at least the 4-byte "PAR1" magic + footer) and throws "length is too low: 0" — surfacing a **format** diagnostic for an **access/existence** problem.

### Suggested fix

- In `LocalStorageProvider` / `LocalStorageObject`, validate that the underlying `Path` exists and is readable **before** any metadata operation; throw a dedicated `java.nio.file.NoSuchFileException` or `AccessDeniedException` with a helpful message (including which directories are in `path.repo` when that is the constraint).
- Keep the parquet-format "length is too low" check as a secondary guard for genuinely-truncated files, not the primary error path for missing ones.

### Environment

- Elasticsearch 9.5.0-SNAPSHOT, self-built from `main`
- macOS 14.8.5 / aarch64
- Modules present: `esql-datasource-http`, `esql-datasource-parquet`, `esql-datasource-compression-libs`

### PR DESCRIPTION
**Pull request by costin**
StorageObject.length() silently returned 0 for non-existent files/objects,
causing the Parquet reader to report "not a Parquet file (length is too low: 0)"
instead of a clear missing-file error.

Fix `LocalStorageObject` and `HttpStorageObject` to throw from `length()` and
`lastModified()` when the underlying file/object does not exist, matching the
pattern already used by S3, Azure, and GCS providers. Add an `exists()` pre-check
in `FileSourceFactory.resolveMetadata()` for a clear user-facing diagnostic before
format-specific code runs.

The `exists()` pre-check does not add extra network calls — all providers use lazy
`fetchMetadata()` that caches all fields in a single call; subsequent `length()`
from the Parquet adapter hits the cache.

Closes #146715

Developed with AI-assisted tooling

### CODE REVIEW

File: x-pack/plugin/esql-datasource-http/src/main/java/org/elasticsearch/xpack/esql/datasource/http/local/LocalStorageObject.java [hunk 1]
```diff
@@ -137,6 +135,12 @@ public StoragePath path() {
...
 
+    private void checkFileExists() throws NoSuchFileException {
+        if (Files.exists(filePath) == false) {
+            throw new NoSuchFileException(filePath.toString());
+        }
+    }
+
     private void fetchMetadata() throws IOException {
         if (Files.exists(filePath)) {
             cachedExists = true;
```
Comment (bpintea) [inline x-pack/plugin/esql-datasource-http/src/main/java/org/elasticsearch/xpack/esql/datasource/http/local/LocalStorageObject.java]: Nit: not changed in current patch, but to stay consistent with introducing changes, should this be `Boolean.TRUE`? (throughout the file).

File: x-pack/plugin/esql-datasource-http/src/main/java/org/elasticsearch/xpack/esql/datasource/http/HttpStorageObject.java
Comment (bpintea) [inline x-pack/plugin/esql-datasource-http/src/main/java/org/elasticsearch/xpack/esql/datasource/http/HttpStorageObject.java:1]: Should we have tests for these too?

**Review by bpintea — APPROVED** [review]
Lgtm. Do we do the same with S3?

File: x-pack/plugin/esql-datasource-http/src/main/java/org/elasticsearch/xpack/esql/datasource/http/local/LocalStorageObject.java (hunk 1 above)
Comment (costin) [reply x-pack/plugin/esql-datasource-http/src/main/java/org/elasticsearch/xpack/esql/datasource/http/local/LocalStorageObject.java]: Done — switched to `Boolean.TRUE` / `Boolean.FALSE` throughout `fetchMetadata()`.

File: x-pack/plugin/esql-datasource-http/src/main/java/org/elasticsearch/xpack/esql/datasource/http/HttpStorageObject.java
Comment (costin) [reply x-pack/plugin/esql-datasource-http/src/main/java/org/elasticsearch/xpack/esql/datasource/http/HttpStorageObject.java:1]: Added three tests: `testLengthOnNotFoundThrows`, `testLastModifiedOnNotFoundThrows`, `testExistsOnNotFoundReturnsFalse` — using a mocked HttpClient that returns 404.

**Comment by costin** [comment]
> Do we do the same with S3?

S3, Azure, and GCS already guard `length()` with `if (cachedExists != null && cachedExists == false) throw IOException("Object not found: ...")` — so they don't have this bug. Only `LocalStorageObject` and `HttpStorageObject` were missing the guard.
