### PR TITLE
Fix concurrency bug in AbstractStringScriptFieldAutomatonQuery

### LINKED ISSUE #105911: Data race condition in automaton queries
### Elasticsearch Version

8.12.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

archlinux 6.7.8

### Problem Description

First described in the post https://discuss.elastic.co/t/data-race-condition-in-automaton-queries/353937?u=yfful there seems to be a data race condition when evaluating automaton queries like `regexp`. In a local unit test involving a runtime field and a regexp query, I have experienced search inconsistencies with the result count. 

### Steps to Reproduce

The query shown below uses the script `parity` which returns `even` or `odd` depending on the value of another numeric field. It returns sometimes an unexpected number of hits. 

```json
{
  "query": {
    "regexp": {
      "outer_parity": {
        "value": "e.e."
      }
    }
  },
  "runtime_mappings": {
    "outer_parity": {
      "type": "keyword",
      "script": {
        "lang": "painless",
        "source": "parity"
      }
    }
  }
}
```

I believe that following this [change](https://github.com/elastic/elasticsearch/pull/101230) that enabled parallelization by default, the queries extending `AbstractStringScriptFieldAutomatonQuery` have a data race condition. If I understand that change correctly, then the code below can be called concurrently:

https://github.com/elastic/elasticsearch/blob/f0e43173eac4549ed78375b991ebd61c0cc13d2e/server/src/main/java/org/elasticsearch/search/runtime/AbstractScriptFieldQuery.java#L71-L77

Therefore, the `BytesRefBuilder` scratch below is shared by all threads that execute a search on different segments, which would lead to the race condition I am seeing. With the query shared above, the `scratch` variable would contain `even` for example, although the `values` list passed in argument contains only `odd`. The race condition would explain this inconsistency.

https://github.com/elastic/elasticsearch/blob/f0e43173eac4549ed78375b991ebd61c0cc13d2e/server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java#L20

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by javanna**
Back when we introduced queries against runtime fields, Elasticsearch did not support
inter-segment concurrency yet. At the time, it was fine to assume that segments will be
searched sequentially. AbstractStringScriptFieldAutomatonQuery used to have a BytesRefBuilder
instance shared across the segments, which gets re-initialized when each segment starts its work.
This is no longer possible with inter-segment concurrency.

Closes https://github.com/elastic/elasticsearch/issues/105911

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java [hunk 1]
```diff
@@ -17,7 +17,7 @@
 import java.util.List;
 
 public abstract class AbstractStringScriptFieldAutomatonQuery extends AbstractStringScriptFieldQuery {
-    private final BytesRefBuilder scratch = new BytesRefBuilder();
+    private final ThreadLocal<BytesRefBuilder> bytesRefBuilderThreadLocal = ThreadLocal.withInitial(BytesRefBuilder::new);
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java:20]: @nik9000 pinging you because you wrote this in the first place. How important is it to have a pre-initialized BytesRefBuilder as opposed to creating one within matches every time? I went for the ThreadLocal initially, but I think that it's probably overkill. Do you have opinions?

Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java:20]: Thinking out loud: before we would create a single scratch, shared across all segments. With the thread local, we would create one per thread executing a certain query: there's a max number of threads we use for a single search, despite the number of slices may be high. Without the threadlocal, we would create a new instance for each segment.

Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java:20]: I think it's pretty important not to allocate every time. I just fixed someone on the ESQL side that is shaped kind of similar and it went from ~25 nanos per run to ~12 nanos per run. 

If we have segment-level concurrency we could make the scratch when we make a `Scorer`.

Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java:20]: > If we have segment-level concurrency we could make the scratch when we make a Scorer.

How would that work? The scorer is made per segment anyways?  Each thread that runs matches needs to have a different instance of the scratch, it cannot be shared, unless we want to synchronize its access, which does not seem like a good idea. That is what the thread local does: give each thread a different instance.

Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java:20]: Yeah, Scorers are always made per segment. If we're running per-segment concurrency that's probably fine.

Comment (nik9000) [reply server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java:20]: > One scratch per segment or one per thread does not make a huge difference.

Yeah! I really like avoiding the ThreadLocal because those are hard for me to read.

Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java]: yea I tend to agree. I extended the script context, that gets created per segment, to include the scratch instance. This should do it.

Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/runtime/AbstractStringScriptFieldAutomatonQuery.java]: err, that does not work, and reminds me once again never to mess with painless script contexts :)

File: server/src/test/java/org/elasticsearch/search/runtime/StringScriptFieldFuzzyQueryTests.java [hunk 2]
```diff
@@ -68,18 +75,42 @@ protected StringScriptFieldFuzzyQuery mutate(StringScriptFieldFuzzyQuery orig) {
...
-        assertTrue(query.matches(List.of("foa")));
-        assertTrue(query.matches(List.of("faa")));
-        assertFalse(query.matches(List.of("faaa")));
+        assertTrue(query.matches(List.of("foo"), scratch));
+        assertTrue(query.matches(List.of("foa"), scratch));
+        assertTrue(query.matches(List.of("faa"), scratch));
+        assertFalse(query.matches(List.of("faaa"), scratch));
+    }
+
+    public void testConcurrentMatches() {
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/search/runtime/StringScriptFieldFuzzyQueryTests.java:93]: These concurrency test are kind of artificial now that they rely on the different matches method... we could rely on integration tests perhaps instead.

Comment (nik9000) [reply server/src/test/java/org/elasticsearch/search/runtime/StringScriptFieldFuzzyQueryTests.java:93]: If you built a `Scorer` or something that could work. That's kind of integration-y. You'd need to make a lucene index, but sometimes that's life.

**Review by nik9000 — APPROVED** [review]

File: server/src/test/java/org/elasticsearch/search/runtime/StringScriptFieldFuzzyQueryTests.java (hunk 2 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/search/runtime/StringScriptFieldFuzzyQueryTests.java]: Yep, I later realized that we already have coverage for all of this in our script field type tests. Only, those did not leverage concurrency as we never ended up running them against multiple segments. I have added an addDocument method to the base class that more aggressively flushes, this is ok as we are only ever adding a few documents. The random flush within RandomIndexWriter needs a minimum number of 10 docs which is never reached in these tests.
With this adjustment, I was able to reproduce the problem and ensure that it is now fixed.

File: test/framework/src/main/java/org/elasticsearch/index/mapper/AbstractScriptFieldTypeTestCase.java [hunk 3]
```diff
@@ -64,6 +65,13 @@ public abstract class AbstractScriptFieldTypeTestCase extends MapperServiceTestC
 
     protected abstract String typeName();
 
+    protected static <T extends IndexableField> void addDocument(RandomIndexWriter iw, Iterable<T> indexableFields) throws IOException {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/index/mapper/AbstractScriptFieldTypeTestCase.java:68]: Could you stick a javadoc on this so a reader can mouse over the method and get a quick sense of what it does?

**Review by nik9000 — APPROVED** [review]

File: test/framework/src/main/java/org/elasticsearch/index/mapper/AbstractScriptFieldTypeTestCase.java (hunk 3 above)
Comment (javanna) [reply test/framework/src/main/java/org/elasticsearch/index/mapper/AbstractScriptFieldTypeTestCase.java:73]: good idea

Comment (nik9000) [reply test/framework/src/main/java/org/elasticsearch/index/mapper/AbstractScriptFieldTypeTestCase.java:73]: I'm full of good ideas. And bad ones.
