### PR TITLE
Prefer new test cluster framework for new FIPS setting

### LINKED ISSUE #104234: [CI] BWC tests failing on 7.17 clusters when FIPS is enabled
We're getting [failures](https://gradle-enterprise.elastic.co/s/tpwsnlis6x5l2/console-log?page=4#L3427) in BWC tests when FIPS is enabled because we are applying some incompatible configuration to the BWC cluster.

```
» [2024-01-10T21:13:36,451][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.17.17-0] uncaught exception in thread [main]
»  org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [xpack.security.fips_mode.required_providers] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
»  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:173) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
```

### PR DESCRIPTION
**Pull request by jakelandis**
https://github.com/elastic/elasticsearch/pull/103483 introduced a new setting for FIPS only. 
Due to the way FIPS is configured with the elder gradle test cluster framework this setting
was getting applied to elder clusters in BWC tests that did not have the settting causing test failures. 

The new test framework has better semantics for version specific configuration. 
This commit updates applies the new setting via the new framework with a 
version specific condition. 

Adding this setting to the test clusters is a simple way to
test the setting (which will cause errors if the required providers are not found in the cluster). 
The pseudo test does not care which framework is used for configuration. 
Also, using the new framework allows to remove some hacky configuration previously needed
to handle some elder test cluster configuration that used elder versions. 

Fixes: https://github.com/elastic/elasticsearch/issues/104234

### CODE REVIEW

File: test/test-clusters/src/main/java/org/elasticsearch/test/cluster/local/FipsEnabledClusterConfigProvider.java [hunk 1]
```diff
@@ -33,7 +38,14 @@ public void apply(LocalClusterSpecBuilder<?> builder) {
                 .setting("xpack.security.fips_mode.enabled", "true")
                 .setting("xpack.license.self_generated.type", "trial")
                 .setting("xpack.security.authc.password_hashing.algorithm", "pbkdf2_stretch")
-                .keystorePassword("keystore-password");
+                .keystorePassword("keystore-password")
+                .settings(node -> {
```
Comment (mark-vieira) [inline test/test-clusters/src/main/java/org/elasticsearch/test/cluster/local/FipsEnabledClusterConfigProvider.java:42]: FWIW, there is a `setting()` method that accepts a predicate specifically for this purpose. This could be simplified to:

```java
.setting("xpack.security.fips_mode.required_providers", () -> "[BCFIPS, BCJSSE]", n -> n.getVersion().onOrAfter("8.13.0"));
```

**Review by mark-vieira — APPROVED** [review]
One minor comment, otherwise LGTM.

Just to confirm, we are good with the fact that we're only testing this setting when using the new framework? Of course, overtime this should be basically _all_ tests as we continue to migrate suites.

File: test/test-clusters/src/main/java/org/elasticsearch/test/cluster/local/FipsEnabledClusterConfigProvider.java (hunk 1 above)
Comment (jakelandis) [reply test/test-clusters/src/main/java/org/elasticsearch/test/cluster/local/FipsEnabledClusterConfigProvider.java]: thanks .. i missed that originally but [switched](https://github.com/elastic/elasticsearch/pull/104287/commits/8562f277ddcc539e78cb88abd69f6171059f9db2) over to use that api instead.

**Comment by jakelandis** [comment]
> Just to confirm, we are good with the fact that we're only testing this setting when using the new framework? Of course, overtime this should be basically all tests as we continue to migrate suites

Yes. I really only need it to run on 1 FIPS enabled cluster to test that it works in a real cluster, which cluster/test does not matter.
