### PR TITLE
Error if installed plugin is inside plugins folder

### LINKED ISSUE #27401: Provide more actionable error message when installing an offline plugin in the plugins directory
Today if you try to install a plugin from a distribution that sits inside the plugins directory, you get a non-actionable error message:

```
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [x-pack-5.6.3.zip]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:334)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:545)
	at org.elasticsearch.plugins.InstallPluginCommand.verify(InstallPluginCommand.java:527)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:570)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:218)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:202)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

This is deliberate, we do not want anything in the plugins directory that is not a plugin, but we could provide a more actionable error message here. This behavior will be documented clearly after #27400 so this is low-priority.

### PR DESCRIPTION
**Pull request by mamazzol**
If a non directory file is in the plugins folder during installation, there will be a non descriptive error during findBundle, as it assumes everything is a directory. This new preemptive check adds a descriptive error message to avoid this scenario.

Also, for consistency and to not use a deprecated URL constructor, in the download method we now use URI.

Closes #27401

### CODE REVIEW

File: distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/InstallPluginAction.java [hunk 1]
```diff
@@ -329,10 +330,31 @@ private Path download(InstallablePlugin plugin, Path tmpDir) throws Exception {
...
+            return;
+        }
+        URI uri = new URI(pluginLocation);
+        if ("file".equalsIgnoreCase(uri.getScheme())) {
+            Path pluginRealPath = Paths.get(uri).toRealPath();
+            Path pluginsDirectory = env.pluginsDir().toRealPath();
+            if (pluginRealPath.startsWith(pluginsDirectory)) {
+                throw new UserException(
+                    ExitCodes.USAGE,
+                    "plugin location [" + pluginLocation + "] is inside the plugins directory [" + pluginsDirectory + "]"
```
Comment (mark-vieira) [inline distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/InstallPluginAction.java]: Error messages should make it clear what the user is trying to do is wrong. I'd rephrase this to something like "Installation of plugin bundles located in the plugins directory is not permitted.".

File: distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java [hunk 2]
```diff
@@ -586,11 +586,24 @@ public void testSpaceInUrl() throws Exception {
         assertPlugin("fake", pluginDir, env.v2());
     }
 
+    public void testInstallFromInsidePluginsDirectory() throws Exception {
```
Comment (mark-vieira) [inline distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java]: nit: If we are testing a failure scenario, I like to make that clear in the test name. In this case I'd name this something like `testCannnotInstallFromInsidePluginsDirectory`.

**Comment by mark-vieira** [comment]
FWIW, is there a reason this isn't allowed? Did we consider simply removing this limitation?

**Comment by rjernst** [comment]
> is there a reason this isn't allowed?

We want to maintain control of what is in the plugins directory. Otherwise we would have to have leniency that could hide an error (eg broken plugin installation, looks like the plugin is there but it's not complete, etc)

**Comment by mamazzol** [comment]
> FWIW, is there a reason this isn't allowed? Did we consider simply removing this limitation?

At the moment it's stopped by the "bug/feature" present [here](https://github.com/elastic/elasticsearch/blob/0e945127edcf45110358be4ec0cfc1462486a553/server/src/main/java/org/elasticsearch/plugins/PluginsUtils.java#L236-L237).

`findPluginDirs` will interpret everything in the plugins directory as another directory, so when the `readPluginBundle` tries to read properties file from the zip, it fails. This acts as a block for unrecognised things in the plugins directory and the user will get a message like "random-uuid has no properties file".

Perhaps `findPluginDirs` could validate the retrieved folders in some way and throw otherwise? Or are we happy with the existing behaviour?

**Comment by mark-vieira** [comment]
> Perhaps `findPluginDirs` could validate the retrieved folders in some way and throw otherwise? Or are we happy with the existing behaviour?

Sounds like we want to keep the existing behavior of preventing folks from installing plugins located inside the plugins dir.

**Review by mark-vieira — APPROVED** [review]

**Comment by mamazzol** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/137507)|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/137508)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/137509)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
