### PR TITLE
Fix NPE when having double nested field with knn query

### LINKED ISSUE #141830: NullPointerException with a knn search query over a nested byte  vector
### Elasticsearch Version

9.3.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux fedora 6.18.7-200.fc43.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jan 23 16:42:34 UTC 2026 x86_64 GNU/Linux

### Problem Description

Executing a nested k-NN query with byte vectors results in a nullpointer exception. 

### Steps to Reproduce

1. Create an index with the following structure:
```http
PUT http://localhost:32770/test-knn-byte-000001
Content-Type: application/json

{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "nested": {
        "type": "nested",
        "dynamic": "strict",
        "properties": {
          "nested": {
            "type": "nested",
            "dynamic": "strict",
            "properties": {
              "byte_vector": {
                "type": "dense_vector",
                "element_type": "byte",
                "dims": 4,
                "index": true,
                "similarity": "cosine",
                "index_options": {
                  "type": "hnsw",
                  "m": 16,
                  "ef_construction": 100
                }
              }
            }
          }
        }
      }
    }
  }
}
```
2. Add some documents:
```http
POST http://localhost:32770/test-knn-byte-000001/_doc/1
Content-Type: application/json

{ }
```
3. Try to run a search query:
```http
{
  "query": {
    "bool": {
      "must": {
        "nested": {
          "path": "nested",
          "query": {
            "nested": {
              "path": "nested.nested",
              "query": {
                "knn": {
                  "field": "nested.nested.byte_vector",
                  "num_candidates": 1,
                  "query_vector": [
                    0,
                    1,
                    2,
                    3
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Results in `HTTP/1.1 500 Internal Server Error`:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"org.apache.lucene.search.KnnCollector.visitedCount()\" because \"this.collector\" is null"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test-knn-byte-000001",
        "node": "vko6mansRpKzClaUwQQ-cg",
        "reason": {
          "type": "null_pointer_exception",
          "reason": "Cannot invoke \"org.apache.lucene.search.KnnCollector.visitedCount()\" because \"this.collector\" is null"
        }
      }
    ],
    "caused_by": {
      "type": "null_pointer_exception",
      "reason": "Cannot invoke \"org.apache.lucene.search.KnnCollector.visitedCount()\" because \"this.collector\" is null",
      "caused_by": {
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"org.apache.lucene.search.KnnCollector.visitedCount()\" because \"this.collector\" is null"
      }
    }
  },
  "status": 500
}
```

Used to work fine in all previous versions. (additional info -- there seems to be no issue with float vectors)

Elasticsearch is started from the official docker image.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by iverase**
In this case the DiversifyingNearestChildrenKnnCollectorManager can produce null collectors which if they are wrapped by the PatienceCollectorManager can produce this NPEs. The fix in this PR is to not wrap the collectors if they are null.  They are probably more elegant solutions but they need to be done upstream in lucene.

Fixes https://github.com/elastic/elasticsearch/issues/141830

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/vectors/PatienceCollectorManager.java [hunk 1]
```diff
@@ -39,17 +39,24 @@ static KnnCollectorManager wrap(KnnCollectorManager knnCollectorManager) {
...
-            return new AdaptiveHnswQueueSaturationCollector(knnCollectorManager.newOptimisticCollector(visitLimit, searchStrategy, ctx, k));
-        } else {
-            return null;
+            KnnCollector collector = knnCollectorManager.newOptimisticCollector(visitLimit, searchStrategy, ctx, k);
+            if (collector != null) {
+                return new AdaptiveHnswQueueSaturationCollector(collector);
+            }
         }
+        return null;
+
```
Comment (benwtrent) [inline server/src/main/java/org/elasticsearch/search/vectors/PatienceCollectorManager.java]:
```suggestion
```

**Review by benwtrent — APPROVED** [review]
This is a good patch. We will want to adjust the API all the way down I think like you said in Apache Lucene.

**Comment by iverase** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.4|[](https://github.com/elastic/elasticsearch/pull/147091)|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/147092)|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/147093)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
