### PR TITLE
Filter out empty top docs results before merging

### LINKED ISSUE #126118: [CI] GeoDistanceIT testDistanceSortingWithUnmappedField failing
**Build Scans:**
- [elasticsearch-intake #21186 / part1](https://gradle-enterprise.elastic.co/s/3yrt27fxcfgro)
- [elasticsearch-pull-request #65474 / part-1](https://gradle-enterprise.elastic.co/s/ez7ejhofes5ks)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.search.sort.GeoDistanceIT.testDistanceSortingWithUnmappedField" -Dtests.seed=579B109C4F710F23 -Dtests.locale=vai-Vaii -Dtests.timezone=Africa/Lagos -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.sort.GeoDistanceIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testDistanceSortingWithUnmappedField),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.action.search.SearchPhaseExecutionException: 
```

**Issue Reasons:**
- [main] 2 failures in test testDistanceSortingWithUnmappedField (0.4% fail rate in 450 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by javanna**
`Lucene.EMPTY_TOP_DOCS` to identify empty to docs results. These were previously null results, but did not need to be send over transport as incremental reduction was performed only on the data node.

Now it can happen that the coord node received a merge result with empty top docs, which has nothing interesting for merging, but that can lead to an exception because the type of the empty array does not match the type of other shards results, for instance if the query was sorted by field. To resolve this, we filter out empty top docs results before merging.

Closes #126118

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java [hunk 1]
```diff
@@ -150,11 +150,11 @@ static TopDocs mergeTopDocs(List<TopDocs> results, int topN, int from) {
             return topDocs;
         } else if (topDocs instanceof TopFieldGroups firstTopDocs) {
             final Sort sort = new Sort(firstTopDocs.fields);
-            final TopFieldGroups[] shardTopDocs = results.toArray(new TopFieldGroups[0]);
+            final TopFieldGroups[] shardTopDocs = results.stream().filter(td -> td != Lucene.EMPTY_TOP_DOCS).toArray(TopFieldGroups[]::new);
             mergedTopDocs = TopFieldGroups.merge(sort, from, topN, shardTopDocs, false);
         } else if (topDocs instanceof TopFieldDocs firstTopDocs) {
             final Sort sort = checkSameSortTypes(results, firstTopDocs.fields);
-            final TopFieldDocs[] shardTopDocs = results.toArray(new TopFieldDocs[0]);
+            final TopFieldDocs[] shardTopDocs = results.stream().filter((td -> td != Lucene.EMPTY_TOP_DOCS)).toArray(TopFieldDocs[]::new);
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:157]: I feel a bit uneasy that this was almost inadvertently raised by a geo distance related integration test. This seems to indicate that we lack some proper unit testing of the merging logic.

**Review by drempapis — APPROVED** [review]
LGTM, that's clean and concise

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java (hunk 1 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:157]: ++ indeed, we should have caught this deterministically for sure

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java [hunk 2]
```diff
@@ -150,11 +150,11 @@ static TopDocs mergeTopDocs(List<TopDocs> results, int topN, int from) {
             return topDocs;
         } else if (topDocs instanceof TopFieldGroups firstTopDocs) {
             final Sort sort = new Sort(firstTopDocs.fields);
-            final TopFieldGroups[] shardTopDocs = results.toArray(new TopFieldGroups[0]);
+            final TopFieldGroups[] shardTopDocs = results.stream().filter(td -> td != Lucene.EMPTY_TOP_DOCS).toArray(TopFieldGroups[]::new);
```
Comment (original-brownbear) [inline server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:153]: It's obviously hard to justify this here in isolation, but shall we stay away from that stream magic a little? It really adds a lot of unexpected warmup overhead and is generally somewhat unpredictable.
That said, this looks like code we could optimize/design away mostly anyway, not important now :)

**Review by original-brownbear — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java (hunk 1 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:157]: shall we track this in a follow-up issue, to add the missing unit tests for the merging of incremental results?

File: server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java (hunk 2 above)
Comment (javanna) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:153]: I am not sure what you'd prefer here, a loop? What do you mean with optimize/design away? I tried different approaches and this is the only one that worked, sadly. Curious to know how we could do things differently to not require this filtering.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:153]: I think a loop would be cheaper, but actually we should just filter this stuff out right off the bat in the `QueryPhaseResultConsumer` for one and also exploit our knowledge of the array type there directly and not type check here (this need not be clever, we simply know this once we have the first result).
Now that I look at this again, I'm sorry :) I think this only looks the way it does now because I was lazy when it came to the serialization of partial merge results.

But that said, I also had a kinda cool optimization in mind here. Merging top docs is super cheap actually. We could do it on literally every result and then only register search contexts with the search service if a shard's hits are needed as well as releasing those that go out of the top-hits window directly. That would save the needless complicated logic that deals with this when sending the partial result now and saves heap and such :)

Comment (javanna) [reply server/src/main/java/org/elasticsearch/action/search/SearchPhaseController.java:153]: I tried fixing the problem at the root, and serializing things differently, but I did not get very far. In short, in https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/search/QueryPhaseResultConsumer.java#L361 we have a `null` topDocsList, and I was not sure how we can determine what type that actually was. I will merge this as a remediation for the test failure. If there's a better way to fix this with a more extensive change, let's make it as a follow-up.

**Comment by javanna** [comment]
@original-brownbear this needs to be backported once batched execution is backported.
