### PR TITLE
ES|QL: Fix CSV tests for MMR

### LINKED ISSUE #142438: [CI] CsvTests test {csv-spec:mmr.MMR with query vector variable} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11854 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/eknbwbid7ntgy)
- [elasticsearch-periodic-platform-support #11854 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/pyme7zcl5uljg)
- [elasticsearch-periodic-platform-support #11854 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/3iat7mjkiutcq)
- [elasticsearch-periodic-platform-support #11854 / rocky-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/7i4kip2km4sci)
- [elasticsearch-periodic-platform-support #11854 / windows-2022_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/eabyvnlx5qema)
- [elasticsearch-intake #34598 / part3](https://gradle-enterprise.elastic.co/s/vcbqb6x5xztnq)
- [elasticsearch-periodic-platform-support #11854 / windows-2022_checkpart3_platform-support-windows](https://gradle-enterprise.elastic.co/s/lixfi5jorqh2e)
- [elasticsearch-periodic-platform-support #11854 / ubuntu-2404-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/igqzek2mwgbpa)
- [elasticsearch-periodic-platform-support #11854 / ubuntu-2404-aarch64_checkpart3_platform-support-arm](https://gradle-enterprise.elastic.co/s/i5narkngylkyi)
- [elasticsearch-periodic #11877 / openjdk21_checkpart3_java-matrix](https://gradle-enterprise.elastic.co/s/fsvue5nrydzyk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.CsvTests" -Dtests.method="test {csv-spec:mmr.MMR with query vector variable}" -Dtests.seed=16C31AEA6247964D -Dtests.locale=hsb -Dtests.timezone=Asia/Rangoon -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.CsvTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Bcsv-spec%3Ammr.MMR%20with%20query%20vector%20variable%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Issue Reasons:**
- [main] 2 consecutive failures in step ubuntu-2204_platform-support-unix
- [main] 2 consecutive failures in step rocky-9_platform-support-unix
- [main] 2 consecutive failures in step windows-2022_checkpart3_platform-support-windows
- [main] 2 consecutive failures in step ubuntu-2404-aarch64_checkpart3_platform-support-arm
- [main] 20 failures in test test {csv-spec:mmr.MMR with query vector variable} (36.4% fail rate in 55 executions)
- [main] 2 failures in step ubuntu-2204_platform-support-unix (100.0% fail rate in 2 executions)
- [main] 6 failures in step part-3 (37.5% fail rate in 16 executions)
- [main] 2 failures in step rocky-9_platform-support-unix (100.0% fail rate in 2 executions)
- [main] 2 failures in step windows-2022_checkpart3_platform-support-windows (100.0% fail rate in 2 executions)
- [main] 5 failures in step part3 (50.0% fail rate in 10 executions)
- [main] 2 failures in step ubuntu-2404-aarch64_checkpart3_platform-support-arm (100.0% fail rate in 2 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (37.5% fail rate in 16 executions)
- [main] 5 failures in pipeline elasticsearch-intake (50.0% fail rate in 10 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ioanatia**
closes #142438 #142441 #142444 #142445 #142446 #142447 #142448

the CSV tests can generate multiple input pages, in the `MMROperator` because we never increased `pageCounter` we ended up filtering the same positions on every page.
this either meant outputting more rows than we need or running into `ArrayIndexOutOfBoundsException`.

we still have the operator tests that are failing - I need to look into those to see if all pages are actually properly released.

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/MMROperator.java [hunk 1]
```diff
@@ -139,9 +139,6 @@ private void createOutputPages() {
         // gather our documents and their vectors
         List<PagePositionDocVector> docsAndVectors = gatherAllDocsAndVectors();
 
-        // set our doc ranks and final mappings for diversification
-        docsAndVectors.sort(Comparator.comparing(PagePositionDocVector::doc));
```
Comment (ioanatia) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/MMROperator.java:143]: this is not needed - and might actually give wrong results
what we get from `gatherAllDocsAndVectors` should already be sorted correctly, because it relies on the order of the input pages.

**Review by pmpailis — APPROVED** [review]
