### PR TITLE
Avoid using bundled jdk on unsupported platforms

### LINKED ISSUE #62635: CI: packaging fails due to missing files
A number of Cli tests are failing due to incorrect permissions or missing files.

**Build scan**:
PluginCliTests in 7.x: 
https://gradle-enterprise.elastic.co/s/foei5rgng7qw2
SqlClitests/ArchiveTests  in 7.x:
https://gradle-enterprise.elastic.co/s/a7nujb7rluyju

**Repro line**:

**Reproduces locally?**:
Not applicable

**Applicable branches**:
7.x so far.

**Failure history**:

**Failure excerpt**:

PluginCliTests
```
15:34:49 org.elasticsearch.packaging.test.PluginCliTests > test10Install FAILED
15:34:49     java.lang.AssertionError: 
15:34:49     Expected: "file/directory: "<File> with owner "root" with group "elasticsearch" with posix permissions [<OWNER_READ>,<OWNER_WRITE>,<GROUP_READ>,<GROUP_WRITE>]
15:34:49          but: path </etc/elasticsearch/elasticsearch.keystore>Does not exist
```
SqlCliTests
```
15:36:05 
15:36:05 org.elasticsearch.packaging.test.SqlCliTests > test010Install FAILED
15:36:05     java.lang.AssertionError: 
15:36:05     Expected: "file/directory: "<File> with owner "root" with group "elasticsearch" with posix permissions [<OWNER_READ>,<OWNER_WRITE>,<GROUP_READ>,<GROUP_WRITE>]
15:36:05          but: path </etc/elasticsearch/elasticsearch.keystore>Does not exist
```

this might be related to a GLIBC issue seen in some of the error logs:

```
java.lang.RuntimeException: Command was not successful: [bash -c sudo -E -u elasticsearch "/tmp/elasticsearch/bin/elasticsearch-plugin" list]
15:34:37        result: exitCode = [1] stdout = [] stderr = [/tmp/elasticsearch/jdk/bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/elasticsearch/jdk/bin/../lib/libjli.so)]
15:34:37         at __randomizedtesting.SeedInfo.seed([C45E3BC5D833FE24:D00AD72D3E2EBD96]:0)
15:34:37         at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:158)
15:34:37         at org.elasticsearch.packaging.util.Shell.run(Shell.java:84)
15:34:37         at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:185)
15:34:37         at org.elasticsearch.packaging.util.Installation$Executable.run(Installation.java:168)
15:34:37         at org.elasticsearch.packaging.test.ArchiveTests.test20PluginsListWithNoPlugins(ArchiveTests.java:69)
```

### PR DESCRIPTION
**Pull request by rjernst**
We use the bundled jdk for unit, integ and packaging tests. Since
upgrading to jdk 15, centos-6 and oracle enterprise linux 6 have failed
due to versions of glibc no longer supported by the jdk. This commit
adds detection of the old glibc versions to gradle, and utilizes that
when deciding which jdk to use for tests.

relates #62709
closes #62635

### CODE REVIEW

File: buildSrc/src/main/java/org/elasticsearch/gradle/info/GlobalBuildInfoPlugin.java [hunk 1]
```diff
@@ -276,6 +278,28 @@ private static String findJavaHome(String version) {
         return versionedJavaHome;
     }
 
+    private static boolean findIfBundledJdkSupported(Project project) {
+        if (Os.isFamily(Os.FAMILY_UNIX) == false || Os.isFamily(Os.FAMILY_MAC)) {
```
Comment (mark-vieira) [inline buildSrc/src/main/java/org/elasticsearch/gradle/info/GlobalBuildInfoPlugin.java:282]: We should cache this result in a static variable so we don't have to shell out on every build invocation. This is considered safe because a) we're just storing a static reference to a `boolean` so leaks aren't an issue and b) this is _very_ unlikely to change between build invocations on the same machine.

We do the same for `findDefaultParallel()` so let's follow that pattern.

**Review by mark-vieira — CHANGES_REQUESTED** [review]
One comment about determining glibc compatibility. Also, we need to address test cluster runtime java. By default we use the bundled JDK for things like BWC testing. We'll need to augment that when running on these incompatible systems. See [here](https://github.com/elastic/elasticsearch/blob/ccb3e2228b5e110d5f3fd49394dd26eea248b540/buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java#L705).

**Comment by rjernst** [comment]
@mark-vieira I made the suggested change. Can you take another look?

**Comment by mark-vieira** [comment]
Did you look into [my comment](https://github.com/elastic/elasticsearch/pull/62793#pullrequestreview-494889551)? What happens when we run BWC tests? As I understand it that would be using the bundled JDK as well an we'll have to account for that.

**Comment by rjernst** [comment]
Oops, sorry I missed that. I've address it now.

**Review by mark-vieira — APPROVED** [review]
Changes look good. 👍
