### PR TITLE
[ML] Ensure phase progress may only increase

### LINKED ISSUE #56282: RegressionIt.testWithOnlyTrainingRowsAndTrainingPercentIsFifty failures
Two failures today with 
```
org.elasticsearch.xpack.ml.integration.RegressionIT > testWithOnlyTrainingRowsAndTrainingPercentIsFifty FAILED
    java.lang.AssertionError: progress is complete: [{"phase":"reindexing","progress_percent":100}, {"phase":"loading_data","progress_percent":100}, {"phase":"feature_selection","progress_percent":1}, {"phase":"coarse_parameter_search","progress_percent":100}, {"phase":"fine_tuning_parameters","progress_percent":100}, {"phase":"final_training","progress_percent":100}, {"phase":"writing_results","progress_percent":100}]
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([5682D617C3B794D:B94D34F14C44ACB8]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgressComplete(MlNativeDataFrameAnalyticsIntegTestCase.java:211)
        at org.elasticsearch.xpack.ml.integration.RegressionIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty(RegressionIT.java:219)
REPRODUCE WITH: gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RegressionIT.testWithOnlyTrainingRowsAndTrainingPercentIsFifty" -Dtests.seed=5682D617C3B794D -Dtests.security.manager=true -Dtests.locale=ru -Dtests.timezone=Asia/Baku -Dcompiler.java=14 -Druntime.java=11
```

example: https://gradle-enterprise.elastic.co/s/vbdxaoi5nsyyo

I will mute this test.

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Due to multi-threading it is possible that phase progress
updates written from the c++ process arrive reordered.
We can address this by ensuring that progress may only increase.

Closes #56282

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/dataframe/stats/ProgressTrackerTests.java [hunk 1]
```diff
@@ -79,4 +79,15 @@ public void testUpdatePhase_GivenUnknownPhase() {
         assertThat(phases.stream().map(PhaseProgress::getPhase).collect(Collectors.toList()),
             contains("reindexing", "loading_data", "foo", "writing_results"));
     }
+
+    public void testUpdatePhase_GivenLowerValueThanCurrentProgress() {
+        ProgressTracker progressTracker = ProgressTracker.fromZeroes(Collections.singletonList("foo"));
+        progressTracker.updateReindexingProgress(10);
+
+        progressTracker.updateReindexingProgress(11);
+        assertThat(progressTracker.getReindexingProgressPercent(), equalTo(11));
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/dataframe/stats/ProgressTrackerTests.java:88]: Could you also add the same assertion after line 90?
That would make the test stronger.

Comment (dimitris-athanasiou) [reply x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/dataframe/stats/ProgressTrackerTests.java:88]: Ah! That's what it meant to be. Thanks for spotting!

**Review by przemekwitek — APPROVED** [review]
LGTM
