### PR TITLE
fix and unmute SamlRedirectTests

### LINKED ISSUE #139389: [CI] SamlRedirectTests testRedirectUrlWithRelayStateAndSigning failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11542 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/tkmwidhr5blyq)
- [elasticsearch-periodic-platform-support #11542 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/ipc4d4m4fln2u)
- [elasticsearch-pull-request #109352 / part-4-fips-140-3](https://gradle-enterprise.elastic.co/s/yiunp4jlnrrvo)
- [elasticsearch-pull-request #109060 / part-4-fips-140-3](https://gradle-enterprise.elastic.co/s/vhtsqgk24xsui)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.security.authc.saml.SamlRedirectTests.testRedirectUrlWithRelayStateAndSigning" -Dtests.seed=F957694543D6C00A -Dtests.locale=es-AR -Dtests.timezone=Indian/Maldives -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.saml.SamlRedirectTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRedirectUrlWithRelayStateAndSigning'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a string starting with "https://idp.test/saml/logout?SAMLRequest=nZFBa4QwFIT%2FSnh3Naa2ax%2FqsiAFYdtDu91DLyVo2AY0cX2x9Oc36gpLCz30mAwz3wwv2351LftUA2lrcohDDkyZ2jbanHJ4PTwEKWyLjGTXih739mRH96zOoyLHvNMQLlIO42DQStKERnaK0NX4snvcowg59oN1trYtsNIbtZFupn041xNGkW760HkhmrKidoYAq8oc3nUTi5vk9m6T3vsfolFVhpw0LgfB4zTgcRAnByEw2SDnIef8DdhxnePZcCmPs3m4Lv13Z0mkhqknFL96ZtF15kp48hlV%2BS%2FCJAbL0sBP5StgiSwuzx8HKL4B&RelayState=hello&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature="
     but: was "https://idp.test/saml/logout?SAMLRequest=nZHBaoNAEIZfZZm7um5tYwY1FKQgpD20aQ69lEWXdEF3rTOWPH5RI4QWeuhx%2BJn%2F%2B4bJdueuFV9mIOtdDnEoQRhX%2B8a6Uw6vh4cghV2Rke5a1ePen%2FzIz%2BZzNMTi3LWOcIlyGAeHXpMldLozhFzjy%2F3jHlUosR88%2B9q3IEpDbJ3mmfbB3BNGkW36kA1xNHVF7QwBUZU5vNsmVjfJ7d0m3YKoiEZTOWLtOAcl4zSQcRAnB6Uw2aCUoZTyDcRxPUeFEi7yOC8P19J%2FO2siM0yeUPzyzKLrzpXwpDtTlf8iTGGwXBps0q1cAUtlcRl%2FPKD4Bg%3D%3D&RelayState=hello&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxm
[truncated]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step rhel-10_platform-support-unix
- [main] 4 failures in test testRedirectUrlWithRelayStateAndSigning (1.4% fail rate in 296 executions)
- [main] 2 failures in step rhel-10_platform-support-unix (100.0% fail rate in 2 executions)
- [main] 2 failures in step part-4-fips-140-3 (50.0% fail rate in 4 executions)
- [main] 2 failures in pipeline elasticsearch-pull-request (1.0% fail rate in 195 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139390: [CI] SamlRedirectTests testRedirectUrlWithoutRelayStateOrSigning failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11542 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/tkmwidhr5blyq)
- [elasticsearch-periodic-platform-support #11542 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/ipc4d4m4fln2u)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.security.authc.saml.SamlRedirectTests.testRedirectUrlWithRelayStateAndSigning" -Dtests.seed=F957694543D6C00A -Dtests.locale=es-AR -Dtests.timezone=Indian/Maldives -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.saml.SamlRedirectTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRedirectUrlWithoutRelayStateOrSigning'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a string starting with "https://idp.test/saml/logout?SAMLRequest=nZFBa4QwFIT%2FSnh3Naa2ax%2FqsiAFYdtDu91DLyVo2AY0cX2x9Oc36gpLCz30mAwz3wwv2351LftUA2lrcohDDkyZ2jbanHJ4PTwEKWyLjGTXih739mRH96zOoyLHvNMQLlIO42DQStKERnaK0NX4snvcowg59oN1trYtsNIbtZFupn041xNGkW760HkhmrKidoYAq8oc3nUTi5vk9m6T3vsfolFVhpw0LgfB4zTgcRAnByEw2SDnIef8DdhxnePZcCmPs3m4Lv13Z0mkhqknFL96ZtF15kp48hlV%2BS%2FCJAbL0sBP5StgiSwuzx8HKL4B&RelayState=hello&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature="
     but: was "https://idp.test/saml/logout?SAMLRequest=nZHBaoNAEIZfZZm7um5tYwY1FKQgpD20aQ69lEWXdEF3rTOWPH5RI4QWeuhx%2BJn%2F%2B4bJdueuFV9mIOtdDnEoQRhX%2B8a6Uw6vh4cghV2Rke5a1ePen%2FzIz%2BZzNMTi3LWOcIlyGAeHXpMldLozhFzjy%2F3jHlUosR88%2B9q3IEpDbJ3mmfbB3BNGkW36kA1xNHVF7QwBUZU5vNsmVjfJ7d0m3YKoiEZTOWLtOAcl4zSQcRAnB6Uw2aCUoZTyDcRxPUeFEi7yOC8P19J%2FO2siM0yeUPzyzKLrzpXwpDtTlf8iTGGwXBps0q1cAUtlcRl%2FPKD4Bg%3D%3D&RelayState=hello&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxm
[truncated]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step rhel-10_platform-support-unix
- [main] 2 failures in test testRedirectUrlWithoutRelayStateOrSigning (0.7% fail rate in 296 executions)
- [main] 2 failures in step rhel-10_platform-support-unix (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139391: [CI] SamlRedirectTests testRedirectUrlWithTrailingQuestionMark failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11542 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/tkmwidhr5blyq)
- [elasticsearch-periodic-platform-support #11542 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/ipc4d4m4fln2u)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.security.authc.saml.SamlRedirectTests.testRedirectUrlWithRelayStateAndSigning" -Dtests.seed=F957694543D6C00A -Dtests.locale=es-AR -Dtests.timezone=Indian/Maldives -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.saml.SamlRedirectTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRedirectUrlWithTrailingQuestionMark'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: a string starting with "https://idp.test/saml/logout?SAMLRequest=nZFBa4QwFIT%2FSnh3Naa2ax%2FqsiAFYdtDu91DLyVo2AY0cX2x9Oc36gpLCz30mAwz3wwv2351LftUA2lrcohDDkyZ2jbanHJ4PTwEKWyLjGTXih739mRH96zOoyLHvNMQLlIO42DQStKERnaK0NX4snvcowg59oN1trYtsNIbtZFupn041xNGkW760HkhmrKidoYAq8oc3nUTi5vk9m6T3vsfolFVhpw0LgfB4zTgcRAnByEw2SDnIef8DdhxnePZcCmPs3m4Lv13Z0mkhqknFL96ZtF15kp48hlV%2BS%2FCJAbL0sBP5StgiSwuzx8HKL4B&RelayState=hello&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature="
     but: was "https://idp.test/saml/logout?SAMLRequest=nZHBaoNAEIZfZZm7um5tYwY1FKQgpD20aQ69lEWXdEF3rTOWPH5RI4QWeuhx%2BJn%2F%2B4bJdueuFV9mIOtdDnEoQRhX%2B8a6Uw6vh4cghV2Rke5a1ePen%2FzIz%2BZzNMTi3LWOcIlyGAeHXpMldLozhFzjy%2F3jHlUosR88%2B9q3IEpDbJ3mmfbB3BNGkW36kA1xNHVF7QwBUZU5vNsmVjfJ7d0m3YKoiEZTOWLtOAcl4zSQcRAnB6Uw2aCUoZTyDcRxPUeFEi7yOC8P19J%2FO2siM0yeUPzyzKLrzpXwpDtTlf8iTGGwXBps0q1cAUtlcRl%2FPKD4Bg%3D%3D&RelayState=hello&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxm
[truncated]
```

**Issue Reasons:**
- [main] 2 consecutive failures in step rhel-10_platform-support-unix
- [main] 2 failures in test testRedirectUrlWithTrailingQuestionMark (0.7% fail rate in 296 executions)
- [main] 2 failures in step rhel-10_platform-support-unix (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139392: [CI] SamlRedirectTests testRedirectUrlWithExistingParameters failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11563 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/faoa7mzevrg2c)
- [elasticsearch-periodic-platform-support #11563 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/6z3pckxur35qe)
- [elasticsearch-periodic-platform-support #11559 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/w6gtcrxygwlwq)
- [elasticsearch-periodic-platform-support #11559 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/3fuw4y7w6swqk)
- [elasticsearch-periodic-platform-support #11555 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/chojtqgkoglmy)
- [elasticsearch-periodic-platform-support #11555 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/btfvxpcphjl7i)
- [elasticsearch-periodic-platform-support #11551 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/zrrdz2gfrtkea)
- [elasticsearch-periodic-platform-support #11551 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/4t72o3vzaktxe)
- [elasticsearch-periodic-platform-support #11547 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/dmfs327smse4w)
- [elasticsearch-periodic-platform-support #11547 / rhel-10_platform-support-unix](https://gradle-enterprise.elastic.co/s/bufsq3m357ewg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:test" --tests "org.elasticsearch.xpack.security.authc.saml.SamlRedirectTests.testRedirectUrlWithoutRelayStateOrSigning" -Dtests.seed=B4B095E1231EF773 -Dtests.locale=vun-TZ -Dtests.timezone=ART -Druntime.java=25
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.security.authc.saml.SamlRedirectTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testRedirectUrlWithExistingParameters'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: "https://idp.test/saml/logout?SAMLRequest=nZFBa4QwFIT%2FSnh3Naa2ax%2FqsiAFYdtDu91DLyVo2AY0cX2x9Oc36gpLCz30mAwz3wwv2351LftUA2lrcohDDkyZ2jbanHJ4PTwEKWyLjGTXih739mRH96zOoyLHvNMQLlIO42DQStKERnaK0NX4snvcowg59oN1trYtsNIbtZFupn041xNGkW760HkhmrKidoYAq8oc3nUTi5vk9m6T3vsfolFVhpw0LgfB4zTgcRAnByEw2SDnIef8DdhxnePZcCmPs3m4Lv13Z0mkhqknFL96ZtF15kp48hlV%2BS%2FCJAbL0sBP5StgiSwuzx8HKL4B"
     but: was "https://idp.test/saml/logout?SAMLRequest=nZHBaoNAEIZfZZm7um5tYwY1FKQgpD20aQ69lEWXdEF3rTOWPH5RI4QWeuhx%2BJn%2F%2B4bJdueuFV9mIOtdDnEoQRhX%2B8a6Uw6vh4cghV2Rke5a1ePen%2FzIz%2BZzNMTi3LWOcIlyGAeHXpMldLozhFzjy%2F3jHlUosR88%2B9q3IEpDbJ3mmfbB3BNGkW36kA1xNHVF7QwBUZU5vNsmVjfJ7d0m3YKoiEZTOWLtOAcl4zSQcRAnB6Uw2aCUoZTyDcRxPUeFEi7yOC8P19J%2FO2siM0yeUPzyzKLrzpXwpDtTlf8iTGGwXBps0q1cAUtlcRl%2FPKD4Bg%3D%3D"
```

**Issue Reasons:**
- [8.19] 10 consecutive failures in step rhel-10_platform-support-unix
- [8.19] 10 failures in test testRedirectUrlWithExistingParameters (5.7% fail rate in 175 executions)
- [8.19] 10 failures in step rhel-10_platform-support-unix (100.0% fail rate in 10 executions)
- [8.19] 5 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by piotrsulkowski-elastic**
SamlRedirectTests are comparing request values, which are compressed with zlib deflate. This function is not guaranteed to always be deterministic and can change when zlib version is updated. That is exactly what happened. For that reason, instead of relying on hardcoded result of compression, the test is not comparing uncompressed values.

Resolves https://github.com/elastic/elasticsearch/issues/139389
Resolves https://github.com/elastic/elasticsearch/issues/139390
Resolves https://github.com/elastic/elasticsearch/issues/139391
Resolves https://github.com/elastic/elasticsearch/issues/139392

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java [hunk 1]
```diff
@@ -64,53 +72,99 @@ public void testRedirectUrlWithRelayStateAndSigning() throws Exception {
...
+        inflater.setInput(decodedBytes);
+        byte[] result = new byte[decodedBytes.length * 10];
+        try {
+            int resultLength = inflater.inflate(result);
+            inflater.end();
+            return new String(result, 0, resultLength, StandardCharsets.UTF_8);
+        } catch (DataFormatException e) {
+            throw new RuntimeException("Failed to decompress SAML request", e);
+        }
+    }
```
Comment (slobodanadamovic) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java]: It could be simplified to avoid dealing with output byte array.
```suggestion
    private static String decompressAndBase64Decode(String compressedBase64) {
        byte[] compressed = Base64.getDecoder().decode(compressedBase64);
        Inflater inflater = new Inflater(true);
        try (InflaterInputStream in = new InflaterInputStream(new ByteArrayInputStream(compressed), inflater)) {
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);

        } catch (IOException e) {
            throw new UncheckedIOException("Failed to decompress input: " + compressedBase64, e);
        }
    }
```

Comment (piotrsulkowski-elastic) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java]: nice! Fixed

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java [hunk 2]
```diff
@@ -45,15 +54,17 @@ public class SamlRedirectTests extends SamlTestCase {
...
+        assertRedirectUrl(
             url,
-            equalTo(
-                LOGOUT_URL
-                    + "?SAMLRequest=nZFBa4QwFIT%2FSnh3Naa2ax%2FqsiAFYdtDu91DLyVo2AY0cX2x9Oc36gpLCz30mAwz3"
-                    + "wwv2351LftUA2lrcohDDkyZ2jbanHJ4PTwEKWyLjGTXih739mRH96zOoyLHvNMQLlIO42DQStKERnaK0NX4snvcowg59oN1trYtsNIbtZFupn04"
-                    + "1xNGkW760HkhmrKidoYAq8oc3nUTi5vk9m6T3vsfolFVhpw0LgfB4zTgcRAnByEw2SDnIef8DdhxnePZcCmPs3m4Lv13Z0mkhqknFL96ZtF15kp"
-                    + "48hlV%2BS%2FCJAbL0sBP5StgiSwuzx8HKL4B"
-            )
+            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
```
Comment (slobodanadamovic) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java]: It would increase readability if you use triple double-quoted strings. That way you avoid all escaping here.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java [hunk 3]
```diff
@@ -64,53 +75,95 @@ public void testRedirectUrlWithRelayStateAndSigning() throws Exception {
...
+                + "ID=\"_id123456789\" IssueInstant=\"2018-01-14T22:47:00.000Z\" Version=\"2.0\">"
+                + "<saml2:Issuer xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\">https://idp.test/</saml2:Issuer>"
+                + "<saml2:NameID xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\">name-123456-7890</saml2:NameID>"
+                + "</saml2p:LogoutRequest>",
+            emptyMap(),
+            false
         );
     }
 
+    private void assertRedirectUrl(
```
Comment (slobodanadamovic) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java]: What do you think about refactoring `assertRedirectUrl` to extract actual URL parameter parsing into its own method? Then simply assert that parameters and their values match the expected ones?

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java (hunk 2 above)
Comment (slobodanadamovic) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java]: pushed https://github.com/elastic/elasticsearch/pull/139459/commits/8fcbc06590fc2fb95241a71c216bdd481539be69

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java (hunk 3 above)
Comment (slobodanadamovic) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/saml/SamlRedirectTests.java]: pushed https://github.com/elastic/elasticsearch/pull/139459/commits/2c3a19424528f5296b9917327bafa69dadc656e7

**Review by n1v0lg — APPROVED** [review]

**Comment by n1v0lg** [comment]
Approved provided CI failures are unrelated! Thanks for working on this 👍

**Comment by slobodanadamovic** [comment]
> Approved provided CI failures are unrelated! Thanks for working on this 👍

Looks unrelated:

```
Error response from daemon: Get "https://registry-1.docker.io/v2/": received unexpected HTTP status: 500 Internal Server Error
```

**Comment by slobodanadamovic** [comment]
## backports 
| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/139726)|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/139727)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/139728)|

**Comment by slobodanadamovic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/139731)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
