### PR TITLE
Check field data type before casting when applying geo distance sort

### LINKED ISSUE #129500: java.lang.ClassCastException: class org.elasticsearch.index.fielddata.plain.SortedDoublesIndexFieldData cannot be cast to class org.elasticsearch.index.fielddata.IndexGeoPointFieldData
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

*

### Problem Description

```
java.lang.ClassCastException: class org.elasticsearch.index.fielddata.plain.SortedDoublesIndexFieldData cannot be cast to class org.elasticsearch.index.fielddata.IndexGeoPointFieldData (org.elasticsearch.index.fielddata.plain.SortedDoublesIndexFieldData and org.elasticsearch.index.fielddata.IndexGeoPointFieldData are in module org.elasticsearch.server@9.1.0 of loader 'app')
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.sort.GeoDistanceSortBuilder.fieldData(GeoDistanceSortBuilder.java:602)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.sort.GeoDistanceSortBuilder.build(GeoDistanceSortBuilder.java:508)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:161)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:153)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.SearchService.parseSource(SearchService.java:1574)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.SearchService.createContext(SearchService.java:1335)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:869)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.search.SearchService.lambda$executeQueryPhase$7(SearchService.java:710)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:79)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:76)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:101)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1044)
	at org.elasticsearch.server@9.1.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
```

### Steps to Reproduce

Found this in suppressed REST errors.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by javanna**
If a user tries to apply geo distance sorting to a field of the wrong type, they'll get a 500 error that causes shard failures, because the field data impl gets casted to the expected type without first checking that the field type is the one expected. This commit addresses that by returning a 400 error instead.

Closes #129500

### CODE REVIEW

**Review by andreidan — APPROVED** [review]
LGTM, thanks for fixing this Luca

File: server/src/main/java/org/elasticsearch/search/sort/GeoDistanceSortBuilder.java [hunk 1]
```diff
@@ -599,7 +599,13 @@ private IndexGeoPointFieldData fieldData(SearchExecutionContext context) {
                 throw new IllegalArgumentException("failed to find mapper for [" + fieldName + "] for geo distance based sort");
             }
         }
-        return context.getForField(fieldType, MappedFieldType.FielddataOperation.SEARCH);
+        IndexFieldData<?> indexFieldData = context.getForField(fieldType, MappedFieldType.FielddataOperation.SEARCH);
+        if (indexFieldData instanceof IndexGeoPointFieldData) {
```
Comment (drempapis) [inline server/src/main/java/org/elasticsearch/search/sort/GeoDistanceSortBuilder.java:603]: Is it worth checking indexFieldData for nullity here? If it is null, should we return a proper exception?

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/search/sort/GeoDistanceSortBuilder.java:603]: `instanceOf` does the check already here (i.e. `null instanceOf Any` is `false`)

Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/sort/GeoDistanceSortBuilder.java:603]: I am not sure how to reproduce that scenario. it is a possible bug in a field type impl perhaps. Yet the case is already covered by the current code. It will throw the exception that I added for null values too.

Comment (drempapis) [reply server/src/main/java/org/elasticsearch/search/sort/GeoDistanceSortBuilder.java:603]: That's correct. My primary focus was on ensuring that an appropriate message exception is returned in that scenario. Catching for nullity, we could return something like
```
 throw new IllegalArgumentException(
            "No index field data found for field [" + fieldName + "] of type [" + fieldType.typeName() + "]"
        );
```
