### PR TITLE
Warn on slow signature verification

### LINKED ISSUE #80480: elasticsearch-plugin install hang without any reason (no high cpu, nothing)
**Elasticsearch version** (`bin/elasticsearch --version`): `Version: 7.13.2, Build: default/deb/4d960a0733be83dd2543ca018aa4ddc42e956800/2021-06-10T21:01:55.251515791Z, JVM: 16`

**Plugins installed**: []

**JVM version** (`java -version`): `openjdk 16 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)`

**OS version** (`uname -a` if on a Unix-like system): `Linux lk-elastic-data-6 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**: 

Context, I would like to add 3 nodes to an existing cluster, **all of the 3 servers** are fresh install of debian10, and all of them get the same behavior

**Steps to reproduce**:

 1. Install any plugin
 `/usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-kuromoji`
 2. Hang for a long period without any reason

For repository-gcs it hang for 10-15min before asking y/N
```-> Installing repository-gcs
-> Downloading repository-gcs from elastic
[=================================================] 100%
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission setFactory
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]
```

Additionnal information, installing with file:///path/plugin.zip works without hanging, and the plugin install do not respect os proxy I was trying to follow if it was an http request that hang.

**Provide logs (if relevant)**:

2 jstack

https://gist.github.com/PMickael/293f0bc431926fe95f7fe15332d72145
https://gist.github.com/PMickael/0f05418a32b9999f04d274d407af1533

### PR DESCRIPTION
**Pull request by grcevski**
Plugin downloads can sometimes take unexpectedly
long because of slow random number generation on certain
operating system versions, e.g. Debian based OS
distros with kernels older than 5.6. This PR adds
a warning message for users explaining why plugin
installation from remote URLs is taking unexpectedly long.

Closes #80480

### CODE REVIEW

**Comment by grcevski** [comment]
@elasticmachine run elasticsearch-ci/part1

**Comment by grcevski** [comment]
@elasticmachine run elasticsearch-ci/part-1

File: distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/InstallPluginAction.java [hunk 1]
```diff
@@ -667,20 +670,47 @@ void verifySignature(final Path zip, final String urlString) throws IOException,
...
-                signature.update(buffer, 0, read);
-            }
+            computeSignatureForDownloadedPlugin(fin, ain, signature);
 
             // finally we verify the signature of the downloaded plugin zip matches the expected signature
             if (signature.verify() == false) {
                 throw new IllegalStateException("signature verification for [" + urlString + "] failed");
             }
+        } finally {
+            timer.cancel();
```
Comment (rjernst) [inline distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/InstallPluginAction.java:696]: Why not have this timer be local to computeSignatureForDownload?

File: distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java [hunk 2]
```diff
@@ -404,6 +408,60 @@ public void testSomethingWorks() throws Exception {
...
+            this::signature
+        );
+
+        final InstallPluginAction spied = spy(action);
+
+        // make the slow verification acceptable delay artificially low for testing
+        doReturn(100L).when(spied).acceptableSignatureVerificationDelay();
+
+        doAnswer(i -> {
+            Thread.sleep(200); // sleep 100ms more than acceptable delay
```
Comment (rjernst) [inline distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java:434]: Can we just block here indefinitely? I'm concerned for flakiness if this completes within the same slice, and the wrong thread unblocks first, that this could appear "ok" and cause the test to fail.

File: distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java [hunk 3]
```diff
@@ -404,6 +408,60 @@ public void testSomethingWorks() throws Exception {
...
+            return null;
+        }).when(spied).computeSignatureForDownloadedPlugin(any(InputStream.class), any(InputStream.class), any(PGPSignature.class));
+
+        // NullPointerException expected because we are mocking the signature verification
+        expectThrows(NullPointerException.class, () -> installPlugin(new PluginDescriptor("analysis-icu", null), env.v1(), spied));
```
Comment (rjernst) [inline distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java:439]: That seems like a very generic exception to depend on, which could mask another problem (an actual NPE). Why would we not expect the install to succeed in this case? Can't we mock it in such a way that it works?

**Review by rjernst — COMMENTED** [review]
I left a couple suggestions

**Review by DaveCTurner — COMMENTED** [review]
Some suggestions about the message.

File: distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/InstallPluginAction.java [hunk 4]
```diff
@@ -667,20 +670,47 @@ void verifySignature(final Path zip, final String urlString) throws IOException,
...
+            timer.schedule(new TimerTask() {
+                @Override
+                public void run() {
+                    terminal.println(
+                        "Downloaded plugin signature verification is taking too long. "
+                            + "This is typically caused by environmental issues on your system related to speed "
+                            + "of random number generation. If you are running on a Linux based system, your "
+                            + "random number generation might be configured to use"
+                            + "/dev/random which blocks until sufficient entropy is achieved on the system. Consider switching to "
+                            + "/dev/urandom instead for faster random number generation."
```
[the remark this answers is not in the document]
Comment (grcevski) [reply distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/InstallPluginAction.java:682]: Both suggestions sound good to me. I like the approach of checking for windows and adding the bit on /dev/random.

File: distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/InstallPluginAction.java (hunk 1 above)
Comment (grcevski) [reply distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/cli/InstallPluginAction.java:696]: The main reason I split it this way is to be able to mock computeSignatureForDownload, but I really like your suggestion, there's no reason to pollute the mainline of that code with the timer block. I'll extract into a method that signifies that we are wrapping with a timer.

File: distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java (hunk 2 above)
Comment (grcevski) [reply distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java:434]: Good point!

File: distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java (hunk 3 above)
Comment (grcevski) [reply distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java:439]: Yeah valid point, I think I can make this work. Right now my mock method for computeSignatureForDownload is simply a sleep call, so the verification doesn't happen and a later call fails with NPE. But I can do the work of the original method too after the sleep and then it will succeed just fine.

File: distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java [hunk 5]
```diff
@@ -404,6 +410,67 @@ public void testSomethingWorks() throws Exception {
...
+
+        // Make sure we don't see any slow error messages when the signature verification is fast
+        doCallRealMethod().when(spied)
+            .computeSignatureForDownloadedPlugin(any(InputStream.class), any(InputStream.class), any(PGPSignature.class));
+
+        int terminalLen = terminal.getOutput().length();
+
+        installPlugin(new PluginDescriptor("analysis-icu", null), env.v1(), spied);
+        assertThat(
+            terminal.getOutput().substring(terminalLen),
```
Comment (rjernst) [inline distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java:469]: Isn't this the same as just using `getOutput()` since terminalLen is the len of `getOutput()`?

**Review by rjernst — APPROVED** [review]
LGTM

File: distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java (hunk 5 above)
Comment (grcevski) [reply distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java:469]: The new call of installPlugin will cause more messages to come out, so it will advance the length of the output from the length I capture in terminalLen. I'm  trying to cut out the previous install output which shows the error, and compare what the successful install produced in the output.

Comment (rjernst) [reply distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java:469]: MockTerminal has a `reset()` method to serve this purpose.

Comment (grcevski) [reply distribution/tools/plugin-cli/src/test/java/org/elasticsearch/plugins/cli/InstallPluginActionTests.java:469]: Ah I didn't know, I'll use that instead, thanks!
