### PR TITLE
[ML] Allow datafeed start with remote indices despite local index pat…

### LINKED ISSUE #81013: [ML] Datafeed fails to start when using CCS and multi-index wildcards and data only exists in remote cluster
Seen in `8.0.0-SNAPSHOT`, likely occurs in earlier versions.

Datafeed fails to start when using CCS and multi-index wildcards and data only exists in remote cluster 

**Steps to reproduce**

1. Configure 2 clusters for CCS. Remote cluster should contain data. Local cluster should not.
2. Configure datafeed to use `remote:index1-*, remote:index2-*, index1-*, index2-*` with options `{"expand_wildcards":["open"],"ignore_unavailable":true,"allow_no_indices":true,"ignore_throttled":true}`
3. Start datafeed

The following error occurs:

`No node found to start datafeed [datafeed-job1], allocation explanation [cannot start datafeed [datafeed-job1] because index [index1-*,index2-*] does not exist, is closed, or is still initializing.]`

If trying to reproduce without using CCS, the datafeed would successfully start as long as either `index1-*` or `index2-*` existed. 

If neither `index1-*` or `index2-*` existed, there is an error `cannot retrieve field [timestamp] because it has no mappings`

Without using wildcards, then I would expect different behaviour, and depending on index options.

Internal edge test clusters are using this CCS pattern and there is no data in the local cluster.

**Expected behaviour**

- As long as data exists in at least one of those indexes (either remote or local), the datafeed should start.
- Errors should be meaningful.
- Where possible, we should follow how this is handled in `_search`

**Workaround**

Either 

1. Update the datafeed to exclude the indices which do not exist, or
2. Create empty index in local cluster with mappings for the fields used in the detection config

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
…tern not matching

When a datafeed is assigned we check that there are indices with fully assigned shards.
However, in the scenario where the datafeed has a mix of local and remote index patterns,
when the local index patterns do not match any index, results to failure to assign
the datafeed.

This should not be the behaviour. As the datafeed also has remote indices we should allow
starting the datafeed. This commit fixes this by skipping the check that local index patterns
produce matching indices when there are remote indices too.

Closes #81013

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedNodeSelector.java [hunk 1]
```diff
@@ -168,6 +168,7 @@ private AssignmentFailure checkAssignment() {
 
     @Nullable
     private AssignmentFailure verifyIndicesActive() {
+        boolean hasRemoteIndices = datafeedIndices.stream().filter(RemoteClusterLicenseChecker::isRemoteIndex).findAny().isPresent();
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedNodeSelector.java:171]:
```suggestion
        boolean hasRemoteIndices = datafeedIndices.stream().anyMatch(RemoteClusterLicenseChecker::isRemoteIndex);
```

**Review by davidkyle — APPROVED** [review]
LGTM
