### PR TITLE
_all: Stop NPE querying _all when it doesn't exist

### LINKED ISSUE #12439: NPE when querying `_all` field with no fields
DELETE my_index

    POST my_index/my_type/1
    {}
    
    GET my_index/_search
    {
      "query": {
        "match": {
          "_all": "foo"
        }
      }
    }

Returns an NPE with the following stack trace:

    Failed to execute [org.elasticsearch.action.search.SearchRequest@402fa749]
    RemoteTransportException[[Havok][inet[/127.0.0.1:9300]][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ElasticsearchException; nested: NullPointerException;
    Caused by: QueryPhaseExecutionException[Query Failed [Failed to execute main query]]; nested: ElasticsearchException; nested: NullPointerException;
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:157)
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:334)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:346)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:340)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:722)
    Caused by: ElasticsearchException; nested: NullPointerException;
        at org.elasticsearch.ExceptionsHelper.convertToElastic(ExceptionsHelper.java:57)
        at org.elasticsearch.search.internal.ContextIndexSearcher.createNormalizedWeight(ContextIndexSearcher.java:133)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:485)
        at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:173)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:694)
        at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:410)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:439)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:151)
        ... 9 more
    Caused by: java.lang.NullPointerException
        at org.elasticsearch.common.lucene.all.AllTermQuery.rewrite(AllTermQuery.java:130)
        at org.apache.lucene.search.IndexSearcher.rewrite(IndexSearcher.java:786)
        at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:833)
        at org.elasticsearch.search.internal.ContextIndexSearcher.createNormalizedWeight(ContextIndexSearcher.java:130)
        ... 15 more

### PR DESCRIPTION
**Pull request by nik9000**
This can happen in two ways:
1. The _all field is disabled.
2. There are documents in the index, the _all field is enabled, but there are
no fields in any of the documents.

In both of these cases we now rewrite the query to a MatchNoDocsQuery which
should be safe because there isn't anything to match.

Closes #12439

### CODE REVIEW

**Comment by jasontedor** [comment]
LGTM!

**Comment by metadave** [comment]
LGTM

**Comment by dakrone** [comment]
LGTM

**Comment by nik9000** [comment]
Ok - three LGTM means I'll merge this in the morning.

File: core/src/main/java/org/elasticsearch/common/lucene/all/AllTermQuery.java [hunk 1]
```diff
@@ -124,14 +125,21 @@ public boolean equals(Object obj) {
...
+            if (terms != null) {
+                fieldExists = true;
+                if (terms.hasPayloads()) {
+                    hasPayloads = true;
+                    break;
+                }
             }
         }
+        if (fieldExists == false) {
+            return new MatchNoDocsQuery();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/lucene/all/AllTermQuery.java]: Can you propagate the boost to this query? If this query is enclosed in a BooleanQuery, it could have an impact on the normalization factor.

Comment (nik9000) [inline core/src/main/java/org/elasticsearch/common/lucene/all/AllTermQuery.java]: Sure, yeah. Makes sense. Do you think its worth adding a test for that?

Comment (jpountz) [inline core/src/main/java/org/elasticsearch/common/lucene/all/AllTermQuery.java]: no

**Comment by nik9000** [comment]
@jpountz done

**Comment by jpountz** [comment]
LGTM
