### PR TITLE
[bugfix] Ensures that we're keeping up with cluster settings in HealthMetadataService

### LINKED ISSUE #96219: max_shards_in_cluster is not properly calculated from max_shards_per_node
### Elasticsearch Version

8.6.0, 8.7.0, 8.8.0, 8.9.0

### Installed Plugins

ESS default

### Java Version

ESS default

### OS Version

ESS default

### Problem Description

Our clusters hit continuously the following error on ESS

It is related to the number of shards per cluster `max_shards_in_cluster` that is calculated based on `max_shards_per_node` but is not correctly calculated, our value for `max_shards_per_node` is 10000. We have 10 data nodes, so we have configured more than 7000 shards per cluster for sure. No matter the value you put on `max_shards_per_node`, we cannot have more than 7000 shards in our clusters.

image

```
      "shards_capacity" : {
        "status" : "Red",
        "symptom" : "Cluster is close to reaching the configured maximum number of shards for data nodes.",
        "details" : {
          "data" : {
            "max_shards_in_cluster" : 7000,
            "current_used_shards" : 9023
```

```
{
  "status": "green",
  "number_of_nodes": 10,
  "unassigned_shards": 0,
  "number_of_pending_tasks": 2,
  "number_of_in_flight_fetch": 0,
  "timed_out": false,
  "active_primary_shards": 5185,
  "task_max_waiting_in_queue_millis": 600,
  "cluster_name": "0000000000000000000000000",
  "relocating_shards": 0,
  "active_shards_percent_as_number": 100,
  "active_shards": 9753,
  "initializing_shards": 0,
  "number_of_data_nodes": 7,
  "delayed_unassigned_shards": 0
}
```

Probably related to https://github.com/elastic/elasticsearch/issues/91119

### Steps to Reproduce

* Deploy a cluster with Elastic Stack 8.7.0
* Create more than 7000 shards
* Change the value of `max_shards_per_node` to 5000
* Wait until the error appears again

### Logs (if relevant)

_No response_

### LINKED ISSUE #96919: org.elasticsearch.health.node.DiskHealthIndicatorServiceIT.testRed failed on main
### CI Link

https://gradle-enterprise.elastic.co/s/g5lnen3vqybaa

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.health.node.DiskHealthIndicatorServiceIT.testRed" \   -Dtests.seed=BFEB6603081AAC8A \   -Dtests.locale=lv \   -Dtests.timezone=America/Cancun \   -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

10:13:46 REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.health.node.DiskHealthIndicatorServiceIT.testRed" -Dtests.seed=BFEB6603081AAC8A -Dtests.locale=lv -Dtests.timezone=America/Cancun -Druntime.java=20
10:13:46 
10:13:46 org.elasticsearch.health.node.DiskHealthIndicatorServiceIT > testRed FAILED
10:13:46     java.lang.AssertionError: 
10:13:46     Expected: <RED>
10:13:46          but: was <GREEN>
10:13:46         at __randomizedtesting.SeedInfo.seed([BFEB6603081AAC8A:955469E053FFD5D6]:0)
10:13:46         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
10:13:46         at org.junit.Assert.assertThat(Assert.java:956)
10:13:46         at org.junit.Assert.assertThat(Assert.java:923)
10:13:46         at org.elasticsearch.health.node.DiskHealthIndicatorServiceIT.testRed(DiskHealthIndicatorServiceIT.java:62)

### PR DESCRIPTION
**Pull request by HiDAl**
Refactor the code to ensure that the `HealthMetadataService` keeps up with the settings changes all the time (not only when the cluster is non-blocked) and post the changes to the `ClusterState` once the cluster is stable.

Before we were discarding changes to some settings in case the cluster was not stable (e.g..: not all nodes in the same version), this provoked that if a user changed a setting, once a new master was elected, the internal `HealthMetadata` object was reset to the default values, do not respecting new settings values. 

With this change, we hold an in-memory representation of the `HealthMetadata` within `HealthMetadataService` which is always up-to-date with the latest user settings and we publish to the ClusterState only when is viable to publish.

Fixes #96219 
Fixes #96919 
Reverts #96843

### CODE REVIEW

**Comment by HiDAl** [comment]
I'm not sure about the `v8.8.2` label, but the pr #96843 made it to 8.8.2, so I guess we should backport it to that version. WDYT?

**Comment by gmarouli** [comment]
> I'm not sure about the `v8.8.2` label, but the pr #96843 made it to 8.8.2, so I guess we should backport it to that version. WDYT?

Hi Pablo, we only add bug fixes on the current (`8.10`) and the previous minor version (`8.9`), so I think the label `v8.8.2` is not necessary.

**Comment by HiDAl** [comment]
> > I'm not sure about the `v8.8.2` label, but the pr #96843 made it to 8.8.2, so I guess we should backport it to that version. WDYT?
> 
> Hi Pablo, we only add bug fixes on the current (`8.10`) and the previous minor version (`8.9`), so I think the label `v8.8.2` is not necessary.

Thanks Mary, removed the label :)

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 1]
```diff
@@ -124,39 +130,34 @@ private void enable(boolean enabled) {
...
             clusterService.removeListener(clusterStateListener);
-            readyToPublish = false;
+            readyToPublishAsMaster = false;
         }
     }
 
     private void updateOnClusterStateChange(ClusterChangedEvent event) {
         final boolean wasMaster = event.previousState().nodes().isLocalNodeElectedMaster();
         isMaster = event.localNodeMaster();
         if (isMaster && wasMaster == false) {
```
Comment (gmarouli) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:140]: Wait, this can't be right.... When we have `isMaster == false` then this `if` statement will be `true` and it will try to publish, right?

Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:140]: if `isMaster == false` then it will short-circuit and fall to the following `else-if`, where the condition will be true, making `readyToPublish = false` . I don't think I fully followed your question

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:140]: Disclaimer, I did write it, but now reading it.... it doesn't make sense :p

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:140]: ignore..... I added parentheses in my mind

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 2]
```diff
@@ -53,25 +54,29 @@ public class HealthMetadataService {
...
 
     // Signifies that a node has been elected as master, but it was not able yet to publish its health metadata for
-    // other reasons for example not all nodes of the cluster are 8.4.0 or newer
-    private volatile boolean readyToPublish = false;
+    // other reasons for example not all nodes of the cluster are 8.5.0 or newer
+    private volatile boolean readyToPublishAsMaster = false;
     // Allows us to know if this node is the elected master without checking the cluster state, effectively protecting
     // us from checking the cluster state before the cluster state is initialized
     private volatile boolean isMaster = false;
+    private volatile HealthMetadata previousHealthMetadata;
```
Comment (gmarouli) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:62]: I am wondering if we should keep the `previousHealthMetadata` in memory or we should better retrieve it from the cluster state each time. I am concerned there might be rare scenarios that we an update is lost and the "previous" would diverge from what is currently on cluster state which I believe is the "true" previous... What do you think?

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 3]
```diff
@@ -53,25 +54,29 @@ public class HealthMetadataService {
...
+    private volatile HealthMetadata healthMetadata;
```
Comment (gmarouli) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:63]: I find this name a bit misleading. When I first read this I thought this variable will contain the health metadata currently shared in the cluster state, and the previous the last value before this. However, after some more reading I think that these variable represent the health metadata that would be stored in the cluster if this node was the master. Right?

That got me thinking, with rollover we retrieve the current values from the cluster settings every time. If I am not mistaken our problem here is when a master is freshly elected or the cluster is ublocked how to get the correct settings. Could we maybe use something like this: `clusterSettings.get(BLAH_SETTING)` at that moment? This was we would have so much less booking to do. Right? I am not 100% sure this would work, but it feels like it should. Maybe the settings in isolation are not a good option, but the combo with cluster settings maybe is.

**Review by gmarouli — CHANGES_REQUESTED** [review]
Hm, that's a tough and tricky problem.... Tracking changes etc is quite tough to reason about.

I would suggest that we write a test that captures this use case deterministically, if possible. Start a cluster, keep the block, change a setting, unblock it and then see what happens.

Then I am curious if we can fix it without keeping in memory the health data but by trying to retrieve them from the settings.

What do you think?

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java (hunk 3 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:63]: Discussed offline that reading directly from the cluster settings is not the way to do this :). Thanks for the explanation @HiDAl .

So, let's rethink this:

- Maybe we can name the `healthMetadata` differently, like `localHealthSettings` or `localHealthMetadata` and explain in an one line comment why they are there.
- I like that we always listen to the cluster setting updates and update these variable no matter, if there is a block, or if this is enabled or not. Otherwise, we will miss updates.
-  I am wondering if these listeners could choose to trigger a request to update the `healthMetadata` in the cluster state if all the conditions hold, what do you think?
- When we become a master and we are ready to publish we publish the new health metadata.
- Maybe we can remove the check if health metadata has changed altogether, the cluster state task already does that, if I am not mistaken, right? Then we only trigger an update if we just became the master. What do you think?

I am trying to reduce the state in memory and the paths that lead to update.

Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:63]: > Maybe we can name the healthMetadata differently, like localHealthSettings or localHealthMetadata and explain in an one line comment why they are there.

++ 

> I like that we always listen to the cluster setting updates and update these variable no matter, if there is a block, or if this is enabled or not. Otherwise, we will miss updates.
++
> I am wondering if these listeners could choose to trigger a request to update the healthMetadata in the cluster state if all the conditions hold, what do you think?

Not sure if I correctly understood this: From my perspective, they are already doing this, but transitively: trigger the change, update the in-memory stuff, a cluster state is triggered, we post the up-to-date health metadata. right?

> When we become a master and we are ready to publish we publish the new health metadata.

yes

> Maybe we can remove the check if health metadata has changed altogether, the cluster state task already does that, if I am not mistaken, right? Then we only trigger an update if we just became the master. What do you think?

I though about this, but wasn't sure. Let me think a bit more about it.

Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:63]: yes, you're right, it's safe to have only 1 object in memory and let the `UpsertHealthMetadataTask.execute` do the magic of checking whether it should update or not the `ClusterState`.

Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java]: pushed :) thanks for your comment. Now it's easier to understand

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 4]
```diff
@@ -53,25 +54,31 @@ public class HealthMetadataService {
...
-    // other reasons for example not all nodes of the cluster are 8.4.0 or newer
-    private volatile boolean readyToPublish = false;
+    // other reasons for example not all nodes of the cluster are 8.5.0 or newer
+    private volatile boolean readyToPublishAsMaster = false;
     // Allows us to know if this node is the elected master without checking the cluster state, effectively protecting
     // us from checking the cluster state before the cluster state is initialized
     private volatile boolean isMaster = false;
+    // we hold an in-memory representation of the healthMetadata which will be updated by the settings updaters. This way, we can
+    // get the initial values (reading default values from `Settings`) and then, potentially, user changed values (they'll be received
+    // through the settings updater). Later, we always post the latest in-memory HealthMetadata to the ClusterState to maintain an
```
Comment (gmarouli) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:64]:
```suggestion
    // through the settings updater). Later and if this node is the master, we will always post the latest in-memory HealthMetadata to the ClusterState to maintain an
```

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 5]
```diff
@@ -124,39 +132,32 @@ private void enable(boolean enabled) {
...
-
-    private void updateOnSettingsUpdated(UpsertHealthMetadataTask task) {
-        // We do not use the cluster state to check if this is the master node because the cluster state might not have been initialized
-        if (isMaster && enabled) {
-            ClusterState clusterState = clusterService.state();
-            if (clusterState.nodesIfRecovered().getMinNodeVersion().onOrAfter(Version.V_8_5_0)) {
-                taskQueue.submitTask("health-metadata-update", task, null);
+                readyToPublishAsMaster = false;
+            } else if (isMaster && event.state().blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK) == false) {
+                taskQueue.submitTask("health-metadata-update", () -> this.localHealthMetadata, null);
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:154]: If I understand this code correctly we will submit one cluster state update with the local health metadata for ... every cluster state that this master node receives (even if the local health metadata has not changed since we last published it). I believe we shouldn't send more cluster state updates than needed here to not add more things for the master node to process (note that after it receives the cluster state update request here, it will drop the request as there isn't anything to update) 

I wonder if we should take a step back here and sketch how we think this health metadata upsert functionality should work theoretically (and then translate it into code) - we haven't really had this use case before in Elasticsearch (reacting to a cluster setting by publishing a cluster state update, and doing an initialise operation on master failover).

For e.g. I think we shouldn't do anything if `event.state().blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK)` is `true`

I think we can already write down a few guiding invariants e.g. 

1. The first line in `updateOnClusterStateChange` should be:

```
if (event.state().blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK) ) {
  return;
}
```
(we shouldn't make decisions and act on a partially recovered cluster state - the cluster settings updates will be received by the settings listeners and they'll update the local state)

2. we should only publish the local health metadata only if it has changed from what we published before 
3. the cluster state update we publish on master failover should not override a setting update

**Review by andreidan — COMMENTED** [review]
Thanks for looking into this Pablo

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java (hunk 5 above)
Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:154]: > 1. The first line in updateOnClusterStateChange should be:
if (event.state().blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK) ) {
  return;
}
(we shouldn't make decisions and act on a partially recovered cluster state - the cluster settings updates will be received by the settings listeners and they'll update the local state)

100% agree

> 2. we should only publish the local health metadata only if it has changed from what we published before

I agree but I don't know how to do it without having a `previousHealthMetadata` object, as a baseline to check against. In previous commits, I did that but changed it by @gmarouli's recommendation. Mary, what do you think of this? Any other idea of maintaining only 1 object in memory? or maybe a flag indicating that _something_ has changed? 

> 3. the cluster state update we publish on master failover should not override a setting update

We're doing this with the current code, as long as each node properly reacts to setting changes.

Thinking a bit more, I think we've no tests checking a setting update in the cluster. will check and write a test for that.

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:154]: >I agree but I don't know how to do it without having a previousHealthMetadata object

Could we compare it with whatever's already in the cluster state? ( note that we wouldn't want to reset the settings _back_ to the default values - the defaults might be different to what's in the cluster state however, by the time the cluster state is fully recovered we should've received the latest cluster settings ) 

e.g.
```
if (localHealth.equals(clusterState.custom(HealthMetadata.TYPE) == false) {
  // our local is different than what's in the cluster state 
  // fire cluster state update
}
```

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 6]
```diff
@@ -169,28 +173,32 @@ public static List<NamedWriteableRegistry.Entry> getNamedWriteables() {
...
             logger.log(
                 MasterService.isPublishFailureException(e) ? Level.DEBUG : Level.WARN,
                 () -> "failure during health metadata update",
                 e
             );
         }
 
-        ClusterState execute(ClusterState currentState) {
+        default ClusterState execute(ClusterState currentState) {
+            if (currentState.blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK)) {
```
Comment (HiDAl) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:188]: we cannot add this check in the first line of `updateOnClusterStateChange` because it'll block the logic to mark this node as master. We could add this check right after line 146, but I preferred to put it here because it's the moment before publishing potential clusterstate changes, and it's shared among all the task received (`resetHealthMetadata` and updates). _Not sure whether it's the right place, though_. I can guess we can still add load to the master node because we're enqueuing tasks, but I don't know the internals to be fully sure.

Comment (andreidan) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:188]: > it'll block the logic to mark this node as master

That's correct. But in this case we would just assume we are not the master in the meantime, and not do any health related things. I think that's ok isn't it? 

I think it's ok (preferable even) to **not** decide we are the master until the cluster state is fully recovered.

Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java]: nevermind, my guess was correct

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 7]
```diff
@@ -53,25 +54,31 @@ public class HealthMetadataService {
     private volatile boolean enabled;
 
     // Signifies that a node has been elected as master, but it was not able yet to publish its health metadata for
-    // other reasons for example not all nodes of the cluster are 8.4.0 or newer
-    private volatile boolean readyToPublish = false;
+    // other reasons for example not all nodes of the cluster are 8.5.0 or newer
+    private volatile boolean readyToPublishAsMaster = false;
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:58]: Looking at where this is used, I think we can get rid of this flag (I'll suggest below how `updateOnClusterStateChange` could look like so it's not used anymore)

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 8]
```diff
@@ -124,39 +132,40 @@ private void enable(boolean enabled) {
...
-    private void updateOnSettingsUpdated(UpsertHealthMetadataTask task) {
-        // We do not use the cluster state to check if this is the master node because the cluster state might not have been initialized
-        if (isMaster && enabled) {
-            ClusterState clusterState = clusterService.state();
-            if (clusterState.nodesIfRecovered().getMinNodeVersion().onOrAfter(Version.V_8_5_0)) {
-                taskQueue.submitTask("health-metadata-update", task, null);
+                readyToPublishAsMaster = false;
+            } else if (isMaster) {
+                var currentStoredHealthMetadata = HealthMetadata.getFromClusterState(event.state());
+                if (currentStoredHealthMetadata != null && this.localHealthMetadata.equals(currentStoredHealthMetadata) == false) {
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:160]: I don't want to bike shed too much here, thanks for iterating on this so far ❤️ 

I'm wondering here if we can simplify the logic here quite a bit (for e.g. it's a bit confusing to me that we have this condition here `if (currentStoredHealthMetadata != null` - as the `currentStoredHealthMetadata` could indeed be null - however, the `null` case it's handled on the previous branch of the if statement where we reset the health stuff)

What if we don't differentiate between a `reset` health metadata case and a regular `upsert` health metadata case (due to settings change) ? 
Also what if we drop the `readyToPublishAsMaster` flag? (it _seems_ that it just guards against the whole cluster being upgraded, however we have a designated `if` check for that - unless I'm missing something I think we could drop this flag altogether)

For e.g. this `updateOnClusterStateChange` method could look like so:

```
    private void updateOnClusterStateChange(ClusterChangedEvent event) {
        // Avoid scheduling updates to the taskQueue in case the cluster is recovering.
        if (event.state().blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK)) {
            return;
        }
        final boolean prevIsMaster = this.isMaster;
        if (prevIsMaster != event.localNodeMaster()) {
            this.isMaster = event.localNodeMaster();
        }

        if (this.isMaster) {
            // Wait until every node in the cluster is upgraded to 8.5.0 or later
            if (event.state().nodesIfRecovered().getMinNodeVersion().onOrAfter(Version.V_8_5_0)) {
                var currentStoredHealthMetadata = HealthMetadata.getFromClusterState(event.state());
                if (currentStoredHealthMetadata == null || this.localHealthMetadata.equals(currentStoredHealthMetadata) == false) {
                    logger.info("updating health to {}", this.localHealthMetadata);
                    taskQueue.submitTask("health-metadata-update", () -> this.localHealthMetadata, null);
                }
            }
        }
    }
```

What do you think?

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 9]
```diff
@@ -124,39 +132,40 @@ private void enable(boolean enabled) {
...
+                    taskQueue.submitTask("health-metadata-update", () -> this.localHealthMetadata, null);
+                }
             }
         }
     }
 
     private void resetHealthMetadata(String source) {
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:167]: This is a very shallow method we could remove

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java [hunk 10]
```diff
@@ -177,31 +147,27 @@ public void testWatermarkSettingUpdate() throws Exception {
...
-                        percentageMode
-                            ? updatedFloodStageMaxHeadroom
-                            : CLUSTER_ROUTING_ALLOCATION_DISK_FLOOD_STAGE_MAX_HEADROOM_SETTING.getDefault(EMPTY)
-                    )
-                );
+            // Force a master fail-over but, since the settings were manually changed, we should return the manually set values
+            internalCluster.stopNode(electedMaster);
+            ensureStableCluster(numberOfNodes - 1);
+
+            assertBusy(() -> {
```
Comment (andreidan) [inline server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:164]: Shall we add another case after this where we do a full cluster restart? 

e.g. 

```
+            // restart the whole cluster
+            internalCluster.fullRestart();
+            ensureStableCluster(internalCluster.numDataAndMasterNodes());
+            String electedMasterAfterRestart = internalCluster.getMasterName();
+            assertBusy(() -> {
+                var healthMetadata = HealthMetadata.getFromClusterState(internalCluster.clusterService(electedMasterAfterRestart).state());
                var diskMetadata = healthMetadata.getDiskMetadata();
                assertThat(diskMetadata.describeHighWatermark(), equalTo(updatedHighWatermark));
                assertThat(diskMetadata.highMaxHeadroom(), equalTo(updatedHighMaxHeadroom));
                assertThat(diskMetadata.describeFloodStageWatermark(), equalTo(updatedFloodStageWatermark));
                assertThat(diskMetadata.floodStageMaxHeadroom(), equalTo(updatedFloodStageMaxHeadroom));
...
```

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java [hunk 11]
```diff
@@ -177,31 +147,27 @@ public void testWatermarkSettingUpdate() throws Exception {
...
+                var healthMetadata = HealthMetadata.getFromClusterState(internalCluster.clusterService().state());
```
Comment (andreidan) [inline server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:165]:
```suggestion
                var healthMetadata = HealthMetadata.getFromClusterState(internalCluster.clusterService(internalCluster.getMasterName()).state());
```

Comment (andreidan) [reply server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:165]: Let's avoid potential flakiness by always reading the state from the master node

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java [hunk 12]
```diff
@@ -90,18 +80,7 @@ public void testEachMasterPublishesTheirThresholds() throws Exception {
...
-                    equalTo(
-                        percentageMode
-                            ? maxHeadroomByNode.get(electedMaster)
-                            : CLUSTER_ROUTING_ALLOCATION_HIGH_DISK_MAX_HEADROOM_SETTING.getDefault(EMPTY)
-                    )
-                );
+                assertThat(diskMetadata.highMaxHeadroom(), equalTo(maxHeadroomByNode.get(electedMaster)));
 
                 var shardLimitsMetadata = healthMetadata.getShardLimitsMetadata();
                 assertEquals(shardLimitsMetadata, shardLimitsPerNode.get(electedMaster));
```
Comment (andreidan) [inline server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:86]: Shall we add another test case here where we restart the whole cluster?

e.g.
``` // restart the whole cluster
+            internalCluster.fullRestart();
+            ensureStableCluster(internalCluster.numDataAndMasterNodes());
+            String electedMasterAfterRestart = internalCluster.getMasterName();
+            {
+                var healthMetadata = HealthMetadata.getFromClusterState(internalCluster.clusterService(electedMasterAfterRestart).state());
+                var diskMetadata = healthMetadata.getDiskMetadata();
+                assertThat(diskMetadata.describeHighWatermark(), equalTo(watermarkByNode.get(electedMasterAfterRestart)));
+                assertThat(diskMetadata.highMaxHeadroom(), equalTo(maxHeadroomByNode.get(electedMasterAfterRestart)));
+
+                var shardLimitsMetadata = healthMetadata.getShardLimitsMetadata();
+                assertEquals(shardLimitsMetadata, shardLimitsPerNode.get(electedMasterAfterRestart));
+            }
```

**Review by andreidan — COMMENTED** [review]
Thanks for iterating on this Pablo.

Apologies for another round of comments 🙈 Hopefully they make sense and simplify this even further

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java (hunk 8 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:160]: I've tested this locally and pushed a branch here in case it's helpful? https://github.com/andreidan/elasticsearch/tree/simplify-healthmetadataservice

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java (hunk 5 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java]: I completely agree to compare with the health metadata that is in the cluster state. 

I see my initial suggestion suggestion was not clear. I thought we can skip the comparison if we would only publish the health metadata when we witness a new master or a setting update. Not as a reaction to every cluster update.

But the code looks simpler the way you approached it, so if we compare the local view of health metadata with what we retrieve from the cluster state, we should be fine.

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java (hunk 8 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:160]: Indeed, since we check the health metadata from the cluster state we do not need the flag.

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 13]
```diff
@@ -124,39 +132,32 @@ private void enable(boolean enabled) {
...
-    }
-
-    private void updateOnSettingsUpdated(UpsertHealthMetadataTask task) {
-        // We do not use the cluster state to check if this is the master node because the cluster state might not have been initialized
-        if (isMaster && enabled) {
-            ClusterState clusterState = clusterService.state();
-            if (clusterState.nodesIfRecovered().getMinNodeVersion().onOrAfter(Version.V_8_5_0)) {
-                taskQueue.submitTask("health-metadata-update", task, null);
+                readyToPublishAsMaster = false;
+            } else if (isMaster && event.state().blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK) == false) {
```
[the remark this answers is not in the document]
Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java]: I think you reviewed an old version :P

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 14]
```diff
@@ -124,39 +132,32 @@ private void enable(boolean enabled) {
...
         if (event.state().nodesIfRecovered().getMinNodeVersion().onOrAfter(Version.V_8_5_0)) {
-            if (readyToPublish) {
+            if (readyToPublishAsMaster) {
                 resetHealthMetadata("health-metadata-update-master-election");
-                readyToPublish = false;
-            }
-        }
-    }
-
-    private void updateOnSettingsUpdated(UpsertHealthMetadataTask task) {
```
[the remark this answers is not in the document]
Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:148]: yes, it does trigger a clusterChange.

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java (hunk 8 above)
Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:160]: damn, I didn't read you comment about the branch and wrote all this code by my own 🤦🏽

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 15]
```diff
@@ -102,63 +106,43 @@ private void registerListeners() {
...
-        clusterService.getClusterSettings().addSettingsUpdateConsumer(ENABLED_SETTING, this::enable);
     }
 
-    private void enable(boolean enabled) {
+    private void updateOnHealthNodeEnabledChange(boolean enabled) {
         this.enabled = enabled;
         if (this.enabled) {
             clusterService.addListener(clusterStateListener);
-            resetHealthMetadata("health-node-enabled");
+            taskQueue.submitTask("health-node-enabled", () -> this.localHealthMetadata, null);
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:126]: Shall we also wrap this call in 
```
           if (this.localHealthMetadata.equals(HealthMetadata.getFromClusterState(clusterService.state())) == false) {
              ...           
           }
```
?

File: server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java [hunk 16]
```diff
@@ -90,22 +80,25 @@ public void testEachMasterPublishesTheirThresholds() throws Exception {
...
+            String electedMasterAfterRestart = internalCluster.getMasterName();
+            {
+                var healthMetadata = HealthMetadata.getFromClusterState(internalCluster.clusterService().state());
+                var diskMetadata = healthMetadata.getDiskMetadata();
+                assertThat(diskMetadata.describeHighWatermark(), equalTo(watermarkByNode.get(electedMasterAfterRestart)));
+                assertThat(diskMetadata.highMaxHeadroom(), equalTo(maxHeadroomByNode.get(electedMasterAfterRestart)));
+
+                var shardLimitsMetadata = healthMetadata.getShardLimitsMetadata();
+                assertEquals(shardLimitsMetadata, shardLimitsPerNode.get(electedMasterAfterRestart));
+            }
```
Comment (andreidan) [inline server/src/internalClusterTest/java/org/elasticsearch/health/HealthMetadataServiceIT.java:101]: ❤️

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 17]
```diff
@@ -52,26 +53,26 @@ public class HealthMetadataService {
     private final MasterServiceTaskQueue<UpsertHealthMetadataTask> taskQueue;
     private volatile boolean enabled;
 
-    // Signifies that a node has been elected as master, but it was not able yet to publish its health metadata for
-    // other reasons for example not all nodes of the cluster are 8.4.0 or newer
-    private volatile boolean readyToPublish = false;
-    // Allows us to know if this node is the elected master without checking the cluster state, effectively protecting
-    // us from checking the cluster state before the cluster state is initialized
-    private volatile boolean isMaster = false;
```
[the remark this answers is not in the document]
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:60]: Ah sweet, great shout ! 

edit: mmmmaybe we still need this? :( See the next comment

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java (hunk 15 above)
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:126]: Talking of `isMaster` - do we have a small bug here were this would submit a cluster state change even if this particular node is not the master? 🤔 
I reckon we should also check here if we are the master node before sending this update? (in which case we probably still need the `isMaster` dance)

What do you think?

**Review by andreidan — APPROVED** [review]
Thanks for iterating on this Pablo. 

I think this is nearly there - I had one more question around the need for `isMaster` but after that this is ready 🚀 

Great work !

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java (hunk 15 above)
Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:126]: you're right, `isMaster` was transitively check through `readyToPublish`, good catch

Comment (HiDAl) [reply server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java]: done

File: server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java [hunk 18]
```diff
@@ -102,61 +109,49 @@ private void registerListeners() {
...
+    private void updateOnClusterStateChange(ClusterChangedEvent event) {
+        // Avoid scheduling updates to the taskQueue in case the cluster is recovering.
+        if (event.state().blocks().hasGlobalBlock(GatewayService.STATE_NOT_RECOVERED_BLOCK)) {
+            return;
         }
-    }
 
-    private void resetHealthMetadata(String source) {
-        taskQueue.submitTask(source, new InsertHealthMetadata(clusterService.getClusterSettings()), null);
+        isMaster = event.localNodeMaster();
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/health/metadata/HealthMetadataService.java:149]: This will always perform a volatile write. 

Shall we avoid it ? (note that volatile reads are much cheaper - equivalent to a memory load - than a volatile write )

```suggestion
     final boolean prevIsMaster = this.isMaster;
     if (prevIsMaster != event.localNodeMaster()) {
        this.isMaster = event.localNodeMaster(); 
      }
```

**Comment by HiDAl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by gmarouli — APPROVED** [review]
Thank you for working on this @HiDAl ! LGTM, it feels much more robust now!! 🚀
