### PR TITLE
ESQL: Refactor HeapAttackIT

### LINKED ISSUE #135122: [CI] HeapAttackIT testLookupExplosionBigString failing
**Build Scans:**
- [elasticsearch-intake #28760 / part1](https://gradle-enterprise.elastic.co/s/mbta5dh5lwwxq)
- [elasticsearch-intake #28756 / part1](https://gradle-enterprise.elastic.co/s/6oycjfhq5skzk)
- [elasticsearch-intake #28751 / part1](https://gradle-enterprise.elastic.co/s/eynmkmgwd54pm)

**Reproduction Line:**
```
./gradlew ":test:external-modules:test-esql-heap-attack:javaRestTest" --tests "org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.testLookupExplosionBigString" -Dtests.seed=4F7998AF45B554CE -Dtests.locale=luy-Latn-KE -Dtests.timezone=Asia/Sakhalin -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testLookupExplosionBigString'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:36083], URI [/_query?error_trace=], status line [HTTP/1.1 429 Too Many Requests]
Warnings: [No limit defined, adding default limit of [1000]]
{"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[request] Data too large, data for [serialize lookup join response] would be [530618896/506mb], which is larger than the limit of [322122547/307.1mb]; for more information, see https://www.elastic.co/docs/troubleshoot/elasticsearch/circuit-breaker-errors?version=master","bytes_wanted":530618896,"bytes_limit":322122547,"durability":"TRANSIENT","stack_trace":"org.elasticsearch.common.breaker.CircuitBreakingException: [request] Data too large, data for [serialize lookup join response] would be [530618896/506mb], which is larger than the limit of [322122547/307.1mb]; for more information, see https://www.elastic.co/docs/troubleshoot/elasticsearch/circuit-breaker-errors?version=master\n\tat org.elasticsea
[truncated]
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testLookupExplosionBigString
- [main] 3 consecutive failures in step part1
- [main] 3 consecutive failures in pipeline elasticsearch-intake
- [main] 3 failures in test testLookupExplosionBigString (1.3% fail rate in 225 executions)
- [main] 3 failures in step part1 (9.1% fail rate in 33 executions)
- [main] 3 failures in pipeline elasticsearch-intake (9.1% fail rate in 33 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #135585: [CI] HeapAttackIT testAggTooManyMvLongs failing
**Build Scans:**
- [elasticsearch-periodic #10875 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/jki37ndgx76le)
- [elasticsearch-pull-request #95335 / part-1](https://gradle-enterprise.elastic.co/s/p2qdhqoybjnok)

**Reproduction Line:**
```
./gradlew ":test:external-modules:test-esql-heap-attack:javaRestTest" --tests "org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT.testAggTooManyMvLongs" -Dtests.seed=84C50A58F5401452 -Dtests.jvm.argline="-Des.concurrent_search=true" -Dtests.locale=or-Orya-IN -Dtests.timezone=SystemV/EST5 -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.heap_attack.HeapAttackIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAggTooManyMvLongs'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Issue Reasons:**
- [main] 2 failures in test testAggTooManyMvLongs (2.4% fail rate in 82 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by julian-elastic**
As we keep adding more and more test cases to HeapAttackIT, it takes longer and longer. The timeout is also getting increased, and right now the time out is set to 40 minutes. It seems occasionally we still hit it though. I don't think it is sustainable to keep increasing the timeout. I think it is time to split the test into a few smaller tests. 

With this change we:
- Refactor `HeapAttackIT.java` by moving the 10+ Lookup Join related test and 3 Enrich test cases to `HeapAttackLookupJoinIT.java`. 
- Add `HeapAttackTestCase.java` and moved the common methods used by `HeapAttackIT.java` and `HeapAttackLookupJoinIT.java` there. 
- Unmute testAggTooManyMvLongs and testLookupExplosionBigString

Closes https://github.com/elastic/elasticsearch/issues/135585
Closes https://github.com/elastic/elasticsearch/issues/135122

### CODE REVIEW

File: test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackBaseIT.java [hunk 1]
```diff
@@ -0,0 +1,324 @@
...
+import static org.elasticsearch.common.Strings.hasText;
+import static org.elasticsearch.test.MapMatcher.assertMap;
+import static org.elasticsearch.test.MapMatcher.matchesMap;
+import static org.hamcrest.Matchers.equalTo;
+import static org.hamcrest.Matchers.greaterThanOrEqualTo;
+
+/**
+ * Base class for heap attack tests. Contains common infrastructure and helper methods.
+ */
+public abstract class HeapAttackBaseIT extends ESRestTestCase {
```
Comment (dnhatn) [inline test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackBaseIT.java]: Maybe call it `HeapAttackTestCase` instead?

**Review by dnhatn — APPROVED** [review]
Should we also move the enrich tests together with the lookup tests? LGTM, thanks @julian-elastic

File: test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackBaseIT.java (hunk 1 above)
Comment (nik9000) [reply test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackBaseIT.java]: Yeah, we tend to call these `TestCase`

Comment (julian-elastic) [reply test/external-modules/esql-heap-attack/src/javaRestTest/java/org/elasticsearch/xpack/esql/heap_attack/HeapAttackBaseIT.java]: OK, renamed
