### PR TITLE
Fix range query on date fields for number inputs

### LINKED ISSUE #63680: range query on dates can see small numbers of millis as a year
If you write a date range query with numeric parameters we *can* interpret them as a year. Check it out:

```
curl -XDELETE -uelastic:password localhost:9200/test
curl -XPOST -HContent-Type:application/json -uelastic:password localhost:9200/test/_doc?refresh -d'{"d": "1970-01-01T00:00:01.010Z"}'
curl -XPOST -HContent-Type:application/json -uelastic:password localhost:9200/test/_doc?refresh -d'{"d": "1967-01-01T00:00:00.000Z"}'
curl -XPOST -HContent-Type:application/json -uelastic:password localhost:9200/test/_search?pretty -d'{
  "query": {
    "range": {
      "d": {
        "gt": 1000
      }
    }
  }
}'
```

The `1000` gets turned into a String internally and then we parse it as the year 1000.

### PR DESCRIPTION
**Pull request by cbuescher**
Currently, if you write a date range query with numeric 'to' or 'from' bounds,
they can be interpreted as years if no format is provided. We use
"strict_date_optional_time||epoch_millis" in this case that can interpret inputs
like 1000 as the year 1000 for example. We should change this to always
interpret and parse numbers in this case with the second option "epoch_millis"
if no other formatter was provided.

Closes #63680

### CODE REVIEW

**Comment by cbuescher** [comment]
This is a potential fix, as @nik9000 mentioned on the issue we should discuss if we want this kind of change and, if so, should it be considered a breaking change in 8.0 or a bugfix. I tend to see this as a bug fix since the current behaviour is really trappy and very likely not expected by the user.

File: server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java [hunk 1]
```diff
@@ -349,9 +350,17 @@ public Query rangeQuery(Object lowerTerm, Object upperTerm, boolean includeLower
                 throw new IllegalArgumentException("Field [" + name() + "] of type [" + typeName() +
                         "] does not support DISJOINT ranges");
             }
-            DateMathParser parser = forcedDateParser == null
-                    ? dateMathParser
-                    : forcedDateParser;
+            DateMathParser parser;
+            if (forcedDateParser == null) {
+                if (lowerTerm instanceof Integer || upperTerm instanceof Integer) {
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java:355]: I think `Number` is better here. That, or `Long` and `Integer`. Its kind of plain luck that the range of numbers that cause the bug are small and so parsed as an `Integer` instead of a `Long` or whatever. But tests and stuff could still end up with a `Long`.

File: server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java [hunk 2]
```diff
@@ -349,9 +350,17 @@ public Query rangeQuery(Object lowerTerm, Object upperTerm, boolean includeLower
...
+                    // force epoch_millis
+                    parser = EPOCH_MILLIS_PARSER;
```
Comment (nik9000) [inline server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java:357]: Should we just cast them to a number and call `longValue` on them? It feels like a shame to `toString` them and then parse them if we know they are numbers.

File: server/src/test/java/org/elasticsearch/index/query/IdsQueryBuilderTests.java [hunk 3]
```diff
@@ -109,4 +111,18 @@ public void testMustRewrite() throws IOException {
                 () -> queryBuilder.toQuery(context));
         assertEquals("Rewrite first", e.getMessage());
     }
+
+    public void testFoo() {
```
Comment (nik9000) [inline server/src/test/java/org/elasticsearch/index/query/IdsQueryBuilderTests.java:115]: Leftover I think.

File: server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java [hunk 4]
```diff
@@ -372,25 +381,37 @@ public static Query dateRangeQuery(
...
             return handleNow(context, nowSupplier -> {
                 long l, u;
+                DateMathParser parser = forcedDateParser == null ? fallbackParser : forcedDateParser;
                 if (lowerTerm == null) {
                     l = Long.MIN_VALUE;
                 } else {
-                    l = parseToLong(lowerTerm, !includeLower, timeZone, parser, nowSupplier, resolution);
+                    if (lowerTerm instanceof Number && forcedDateParser == null) {
+                        // force epoch_millis
+                        l = resolution.convert(Instant.ofEpochMilli(((Number) lowerTerm).longValue()));
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java:398]: I think we need "resolution.convert" here to this gets kind of ugly. I personally prefer the earlier variant where we just have a "toString" detour but keep the rest of the code as-is.

**Comment by cbuescher** [comment]
@nik9000 thanks for the review, I added another iteration but personally prefered the earlier variant. let me know what you think. Maybe I missed some simpler option?

File: server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java (hunk 4 above)
Comment (nik9000) [reply server/src/main/java/org/elasticsearch/index/mapper/DateFieldMapper.java:398]: Yeah. I think you are right. If this were super performance sensitive code I'd argue more, but building queries typically isn't. I think going back is probably the right thing.

File: rest-api-spec/src/main/resources/rest-api-spec/test/field_caps/30_filter.yml [hunk 5]
```diff
@@ -81,7 +81,7 @@ setup:
       field_caps:
         index: test-*
         fields: "*"
-        body: { index_filter: { range: { timestamp: { gte: 2010 }}}}
+        body: { index_filter: { range: { timestamp: { gte: "2010" }}}}
```
Comment (cbuescher) [inline rest-api-spec/src/main/resources/rest-api-spec/test/field_caps/30_filter.yml:84]: Interestingly we weren't very precise about this in our own tests.

**Comment by nik9000** [comment]
This happens when you submit a doc too!

**Comment by cbuescher** [comment]
@nik9000 just going through open PRs atm, do you think this needs changes or additions? Or just another round of discussion maybe?

**Review by nik9000 — APPROVED** [review]
LGTM. Should we add something to the breaking changes list?

**Comment by cbuescher** [comment]
@nik9000 thanks for the review, I added a blip to the docs and an entry in the breaking changes list. Can you take another short quick look to see if what I added there makes sense to you?

**Review by nik9000 — APPROVED** [review]
LGTM! I think 8.0.0-alpha1.asciidoc could also use a line for this.
