### PR TITLE
Remove BlobContainer Tests against Mocks

### LINKED ISSUE #30424: Run ESBlobStoreContainerTestCase tests against real blob store implementations
ESBlobStoreContainerTestCase is an abstract class in test:framework that checks properties that all blob store implementation have to satisfy, for example that writing to a blob that already exists fails.

We currently run these tests only against mock implementations, not the actual services. Running against the actual services would validate that the blob store implementations are compliant to the BlobContainer interface.

### PR DESCRIPTION
**Pull request by original-brownbear**
Removing all these weird mocks as asked for by #30424.
All these tests are now part of real repository ITs and otherwise left unchanged if they had
independent tests that didn't call the `createBlobStore` method previously.
The HDFS tests also get added coverage as a side-effect because they did not have an implementationof the abstract repository ITs.

This will allow us to more easily test different SDK versions because we don't have to support the complex blob store mocks removed here.

Closes #30424

### CODE REVIEW

File: plugins/repository-hdfs/src/test/java/org/elasticsearch/repositories/hdfs/HdfsBlobStoreRepositoryTests.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+public class HdfsBlobStoreRepositoryTests extends ESBlobStoreRepositoryIntegTestCase {
+
+    @Override
+    protected String repositoryType() {
+        return "hdfs";
+    }
+
+    @Override
+    protected Settings repositorySettings() {
+        assumeFalse("https://github.com/elastic/elasticsearch/issues/31498", HdfsRepositoryTests.isJava11());
```
Comment (tlrx) [inline plugins/repository-hdfs/src/test/java/org/elasticsearch/repositories/hdfs/HdfsBlobStoreRepositoryTests.java]: :+1:

**Review by tlrx — APPROVED** [review]
LGTM! This is a long overdue work, thanks Armin!  Also, nice stats :)

**Comment by original-brownbear** [comment]
Thanks Tanguy! :)
