### PR TITLE
Don't serialize endpoint metadata in semantic text mappings

### LINKED ISSUE #144969: EndpointMetadata is serialized in an index mapping
### Elasticsearch Version

serverless

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

When the first document is stored in an index that leverages a semantic_text field, information is retrieved from the inference API and persisted in the index mapping. This includes fields like the `dimensions`, `task_type`.

Currently the endpoint metadata is persisted in the index mapping. The metadata isn't used by the semantic text field after an inference id is chosen and the information may confuse the user. It can also be out of date with what the inference API exposes through its REST GET API.

We should filter out the endpoint metadata so it isn't stored in the index mappings.

### Steps to Reproduce

1. Create an index

```
PUT my-index
{
    "mappings": {
        "properties": {
            "my_field": {
                "type": "semantic_text",
                "inference_id": ".google-gemini-embedding-001"
            }
        }
    }
}
```

2. Ingest a document
```
POST my-index/_doc/1
{
    "my_field": "hello"
}
```

3. The metadata field will show up in the index mapping:

```
{
  "my-index": {
    "aliases": {},
    "mappings": {
      "properties": {
        "my_field": {
          "type": "semantic_text",
          "inference_id": ".google-gemini-embedding-001",
          "model_settings": {
            "service": "elastic",
            "task_type": "text_embedding",
            "dimensions": 3072,
            "similarity": "cosine",
            "element_type": "float",
            "metadata": {
              "heuristics": {
                "properties": [
                  "multilingual"
                ],
                "status": "ga",
                "release_date": "2025-07-14"
              },
              "internal": {
                "fingerprint": "fb3e18481f118e3d3883669be08b9637ac235f8efd2b4f4ec2035b1478878bbd",
                "version": 1
              },
              "display": {
                "name": "Google Gemini Embedding v1",
                "model_creator": "Google"
              }
            }
          }
        }
      }
    },
    "settings": {}
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by Mikep86**
In #141393, `MinimalServiceSettings` was updated to add endpoint metadata. This change introduced a bug (see https://github.com/elastic/elasticsearch/issues/144969) where endpoint metadata is serialized in `semantic_text` index mappings. Endpoint metadata is only necessary when selecting the default inference service to use; once the inference service is selected it is no longer useful and can be discarded.

This PR fixes that by implementing filtered XContent for `MinimalServiceSettings` that excludes endpoint metadata. An alternative approach considered was to make a new class, `MappingServiceSettings`, that models all params in `MinimalServiceSettings` except for endpoint metadata. We did not choose to go with that for a couple reasons:

- Due to this bug, there are some users out there with `semantic_text` index mappings on disk with endpoint metadata. We need to know how to parse those or the mappings will be invalid, breaking Elasticsearch. See `testMappingWithEndpointMetadata` for a test validating this case with the chosen approach.
- There are places where we rely on the `semantic_text` model settings being `MinimalServiceSettings`, such as when [updating the inference ID](https://github.com/Mikep86/elasticsearch/blob/c7bdd6fc0e69470b7ea04029a49cf236ee2f5202/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapper.java#L418-L431). Using a new class like `MappingServiceSettings` breaks this logic, and would require more significant changes to resolve.

Nothing precludes us from refactoring at a later time to introduce a new class like `MappingServiceSettings`. This PR aims to fix the bug with the fewest and simplest changes possible so that it can be resolved quickly and without side-effects.

Fixes https://github.com/elastic/elasticsearch/issues/144969

### CODE REVIEW

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextField.java [hunk 1]
```diff
@@ -157,7 +157,7 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
         }
         builder.startObject(INFERENCE_FIELD);
         builder.field(INFERENCE_ID_FIELD, inference.inferenceId);
-        builder.field(MODEL_SETTINGS_FIELD, inference.modelSettings);
+        builder.field(MODEL_SETTINGS_FIELD, inference.modelSettings != null ? inference.modelSettings.getFilteredXContentObject() : null);
```
Comment (DonalEvans) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextField.java:160]: Just a thought, would it be a good idea to mark nullable fields on `InferenceResult` as `@Nullable` in the class declaration and add a null check for those fields that should never be null?

File: server/src/main/java/org/elasticsearch/inference/MinimalServiceSettings.java [hunk 2]
```diff
@@ -204,7 +204,7 @@ public boolean supportsVersion(TransportVersion version) {
 
     @Override
     public ToXContentObject getFilteredXContentObject() {
-        return this::toXContent;
+        return (b, p) -> toXContent(b, p, false);
```
Comment (jonathan-buttner) [inline server/src/main/java/org/elasticsearch/inference/MinimalServiceSettings.java:207]: Ideally in the future we can remove `MinimalServiceSettings` from implementing `ServiceSettings`. Maybe when we get around to doing that we can rename the method then. The other option we have is to leverage the `Params` instead which I think is the typical way to handle this.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextField.java (hunk 1 above)
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextField.java:160]: nit: How about we mark `modelSettings` as `@Nullable` in the record declaration:

```
    public record InferenceResult(
        String inferenceId,
        @Nullable MinimalServiceSettings modelSettings,
        ChunkingSettings chunkingSettings,
        Map<String, List<Chunk>> chunks
    ) {}
```

It took me a minute to figure out that it could be null based on the parsing logic.

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapper.java [hunk 3]
```diff
@@ -329,7 +329,11 @@ public Builder(
                 () -> null,
                 (n, c, o) -> SemanticTextField.parseModelSettingsFromMap(o),
                 mapper -> ((SemanticTextFieldType) mapper.fieldType()).modelSettings,
-                XContentBuilder::field,
+                (b, n, v) -> {
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapper.java:332]: If we wanted to use `Params` here instead, I think we'd do something like this:

```
(b, n, v) -> {
  if (v != null) {
    b.field(MODEL_SETTINGS_FIELD, v, new ToXContent.MapParams(Map.of("exclude_metadata", "true")));
  }
}
```

**Review by jonathan-buttner — APPROVED** [review]

File: x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextField.java (hunk 1 above)
Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextField.java:160]: I can mark the relevant fields as nullable, but I think any other changes should be done in a separate PR to keep the scope of this limited to the bug fix

Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextField.java:160]: Done in a03fd2d2

Comment (Mikep86) [reply x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextField.java:160]: Done in
