### PR TITLE
Fixes cluster state-based role mappings not recovered from disk

### LINKED ISSUE #93048: [CI] FileSettingsRoleMappingsRestartIT testReservedStatePersistsOnRestart failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/qnpqqjfzuqd62/tests/:x-pack:plugin:security:internalClusterTest/org.elasticsearch.xpack.security.FileSettingsRoleMappingsRestartIT/testReservedStatePersistsOnRestart

**Reproduction line:**
```
./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.security.FileSettingsRoleMappingsRestartIT.testReservedStatePersistsOnRestart" -Dtests.seed=96EB3AA6266BA299 -Dtests.locale=ga-IE -Dtests.timezone=Indian/Antananarivo -Druntime.java=19
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.FileSettingsRoleMappingsRestartIT&tests.test=testReservedStatePersistsOnRestart

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([96EB3AA6266BA299:28E4EB140ABA240A]:0)
  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.elasticsearch.xpack.security.FileSettingsRoleMappingsRestartIT.testReservedStatePersistsOnRestart(FileSettingsRoleMappingsRestartIT.java:120)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

### PR DESCRIPTION
**Pull request by albertzaharovits**
Cluster state role mappings need to be recovered from disk CS
(when master nodes are restarted), because the CS metadata
that says if the role mappings are up to date (it actually tells
if all file settings are up to date) is itself recovered from disk.
In case that the metadata is recovered, but the role mappings
themselves are not, the role mappings from the file will not
be present in the CS and will also not be copied from the
settings file.

Fixes: https://github.com/elastic/elasticsearch/issues/93048

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/FileSettingsServiceIT.java [hunk 1]
```diff
@@ -8,6 +8,7 @@
```
Comment (albertzaharovits) [inline server/src/internalClusterTest/java/org/elasticsearch/reservedstate/service/FileSettingsServiceIT.java:8]: changes in this file are just to expose some methods to reuse in another test

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackClientPlugin.java [hunk 2]
```diff
@@ -376,10 +376,16 @@ public List<NamedXContentRegistry.Entry> getNamedXContent() {
...
+            // security
             new NamedXContentRegistry.Entry(
                 PersistentTaskParams.class,
                 new ParseField(SecurityMigrationTaskParams.TASK_NAME),
                 SecurityMigrationTaskParams::fromXContent
+            ),
+            new NamedXContentRegistry.Entry(
+                Metadata.Custom.class,
+                new ParseField(RoleMappingMetadata.TYPE),
+                RoleMappingMetadata::fromXContent
```
Comment (albertzaharovits) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackClientPlugin.java:388]: This is the essential part of this PR.

File: x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/FileSettingsRoleMappingsRestartIT.java [hunk 3]
```diff
@@ -8,33 +8,26 @@
 package org.elasticsearch.xpack.security;
 
 import org.elasticsearch.action.admin.cluster.state.ClusterStateRequest;
-import org.elasticsearch.cluster.ClusterChangedEvent;
```
Comment (albertzaharovits) [inline x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/security/FileSettingsRoleMappingsRestartIT.java:11]: This is the IT that exercises that role mappings are recovered from disk CS.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleMappingMetadata.java [hunk 4]
```diff
@@ -71,9 +95,24 @@ public static NamedDiff<Metadata.Custom> readDiffFrom(StreamInput streamInput) t
 
     @Override
     public Iterator<? extends ToXContent> toXContentChunked(ToXContent.Params params) {
+        // role mappings are serialized without their names
         return Iterators.concat(ChunkedToXContentHelper.startArray(TYPE), roleMappings.iterator(), ChunkedToXContentHelper.endArray());
     }
 
+    @Override
+    public XContentBuilder toXContent(XContentBuilder builder, Params params) throws IOException {
+        return ChunkedToXContent.wrapAsToXContent(this).toXContent(builder, params);
```
Comment (jakelandis) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleMappingMetadata.java:104]: can you help me understand this change ? I am mostly concerned if this will change the format that is persisted to cluster state in any way. I suspect we want to avoid 2 variants of persisted state.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleMappingMetadata.java [hunk 5]
```diff
@@ -16,22 +16,46 @@
...
+        TYPE,
+        // serialization tests rely on the order of the ExpressionRoleMapping
+        args -> new RoleMappingMetadata(new LinkedHashSet<>((List<ExpressionRoleMapping>) args[0]))
+    );
+
+    static {
+        PARSER.declareObjectArray(
+            constructorArg(),
+            // role mapping names are lost when the role mapping metadata is serialized
+            (p, c) -> ExpressionRoleMapping.parse("name_not_available_after_deserialization", p),
```
Comment (jakelandis) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleMappingMetadata.java:54]: This further tightly couples the payload of our REST API to the payload of cluster state, despite the workflow being disjoint. I think this is fine for now, but it does present some long term concern w.r.t. these objects and the tight coupling of their serialization. The mismatch between persisted state across multiple versions of ES vs. transient state in a REST API yields different expectations and want to protect against good nature changes in the REST API breaking cluster state and vice-versa. Given the impact of getting this wrong at some future point, can you follow up with something that decouples these two ? Perhaps an adaptor pattern, where today it is an identity adaption (e.g. no differences) but is explicit and tests that changes to one will not influence the other.

**Review by jakelandis — COMMENTED** [review]
looking good ... (reviewing tests now)

**Review by jakelandis — APPROVED** [review]
LGTM assuming https://github.com/elastic/elasticsearch/pull/109167/files#r1619371128 does not introduce a new variant of persistent meta data in cluster state.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleMappingMetadata.java (hunk 4 above)
Comment (albertzaharovits) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleMappingMetadata.java]: Thanks for raising this! It's actually **not** required, and I've removed it.
I needed it only for tests, i.e. because `RoleMappingMetadataXContentSerializationTests` extended `AbstractXContentSerializingTestCase`. But I then found out about `AbstractChunkedSerializingTestCase` so now `RoleMappingMetadata` doesn't need to implement anything new (`ToXContent`).

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleMappingMetadata.java (hunk 5 above)
Comment (albertzaharovits) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/RoleMappingMetadata.java:52]: You're right to point out that this is an issue. I'll follow-up with an implementation of "`ExpressionRoleMapping` in the CS" separate from "`ExpressionRoleMapping` in request payload".

**Comment by albertzaharovits** [comment]
I really appreciate the lighting review on this one Jake!

**Comment by albertzaharovits** [comment]
@gwbrown I rushed with merging this one given its potential impact. I'm open to discuss if you have comments on the approach.

**Comment by gwbrown** [comment]
👍🏼 100% behind merging with just Jake's review, I don't have any comments beyond what he left.
