### PR TITLE
Resolve date math expressions before looking up index metadata

### LINKED ISSUE #75047: Final pipeline not executed for indexing requests which include date math expressions
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12.0, 7.13.2, possibly others

**Description of the problem including expected versus actual behavior**:

This is similar to #69727 except that in this case, the final pipeline is set directly on an existing index rather than in a template.

**Steps to reproduce**:

```
PUT _ingest/pipeline/my-final-pipeline
{
  "description": "create event.source",
  "processors": [
    {
      "set": {
        "field": "user.name",
        "value": "my-user-name",
        "ignore_failure": false
      }
    }
  ]
}

# Create an index which the final_pipeline is my-final-pipeline
# PUT /<my-index-{now/d}>
PUT /%3Cmy-index-%7Bnow%2Fd%7D%3E
{
  "settings": {
    "index.final_pipeline": "my-final-pipeline"
  }
}

# Index a document using the date math expression in the URL:
POST %3Cmy-index-%7Bnow%2Fd%7D%3E/_doc/1
{
  "foo": "bar"
}

# observe that user.name field is not set by the final pipeline
```

### PR DESCRIPTION
**Pull request by danhermann**
This is somewhat similar to #69727 except that in this case, the final pipeline is set directly on an existing index rather than in a template. The root cause of the issue was looking for the ingest pipelines on index metadata before resolving any date math expressions in the index name.

Fixes https://github.com/elastic/elasticsearch/issues/75047

### CODE REVIEW

**Comment by danhermann** [comment]
@dakrone, would you mind looking at this one as you reviewed the similar fix in https://github.com/elastic/elasticsearch/pull/71433?

File: server/src/test/java/org/elasticsearch/ingest/IngestServiceTests.java [hunk 1]
```diff
@@ -1376,6 +1377,23 @@ public void testResolveFinalPipeline() {
...
+        final DateFormatter dateFormatter = DateFormatter.forPattern("uuuu.MM.dd");
+        IndexMetadata.Builder builder = IndexMetadata.builder("idx-" + dateFormatter.formatMillis(System.currentTimeMillis()))
+            .settings(settings(Version.CURRENT).put(IndexSettings.FINAL_PIPELINE.getKey(), "final-pipeline"))
+            .numberOfShards(1)
+            .numberOfReplicas(0);
+        Metadata metadata = Metadata.builder().put(builder).build();
+
+        // index name matches with IDM:
+        IndexRequest indexRequest = new IndexRequest("<idx-{now/d}>");
+        boolean result = IngestService.resolvePipelines(indexRequest, indexRequest, metadata);
```
Comment (dakrone) [inline server/src/test/java/org/elasticsearch/ingest/IngestServiceTests.java:1390]: I believe this will very rarely fail when the first call to `System.currentTimeMillis()` on line 1382 is called on one day, then this is called on the next day (across the day delineation I mean).

Is it worth adding a parameter that allows overriding the time used when resolving for this test? (I only say since we've had failures related to this with data streams and dates in index names)

Comment (danhermann) [reply server/src/test/java/org/elasticsearch/ingest/IngestServiceTests.java]: Yep, worth it. Added in https://github.com/elastic/elasticsearch/pull/75314/commits/b934eb4159d120f4a09ce96c8387aa9dcf204750

**Review by dakrone — APPROVED** [review]
LGTM, thanks Dan!

**Comment by danhermann** [comment]
Thanks, @dakrone!
