### PR TITLE
Compatability mode for forbidden APIs for Java 12

### LINKED ISSUE #37007: Forbidden APIs check fails - missing bundled signatures for java 12
Failure repros locally for me against master with:
```./gradlew client:test:forbiddenApisMain -Dcompiler.java=11 -Druntime.java=12```

Links to failing builds:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=virtual&&linux/144/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=openjdk12,nodes=virtual&&linux/144/console

Prior work:
We encountered this issue before with Java 11, see https://github.com/elastic/elasticsearch/issues/33082 . In that case, we were still using a forked version of the ForbiddenApis check, and the fix (found at #33116) looks like it would have also prevented this issue.  Some time after that, however, we went back to using the mainline plugin, see PR here #33809 and discussion here #33759

### PR DESCRIPTION
**Pull request by alpar-t**
Limit the maximum `targetVersion` we set `forbiddenApis` to. No support for Java 12 yet.
Closes #37007.

### CODE REVIEW

File: buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/PrecommitTasks.groovy [hunk 1]
```diff
@@ -123,8 +123,14 @@ class PrecommitTasks {
         project.tasks.withType(CheckForbiddenApis) {
             dependsOn(buildResources)
             targetCompatibility = project.runtimeJavaVersion >= JavaVersion.VERSION_1_9 ?
-                    project.runtimeJavaVersion.getMajorVersion() :
-                    project.runtimeJavaVersion
+                    project.runtimeJavaVersion.getMajorVersion() : project.runtimeJavaVersion
+            if (project.runtimeJavaVersion > JavaVersion.VERSION_11) {
+                doLast {
+                    println "Forbidden APIs does not support java version past 11. Will use the signatures from 11 for " +
```
Comment (rjernst) [inline buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/PrecommitTasks.groovy]: Why a bare print statement? Seems this should at least be a warning log. But what can a dev do about it? Maybe nothing should be printed and an issue created and linked here to remove once forbidden apis supports Java 12.

Comment (atorok) [reply buildSrc/src/main/groovy/org/elasticsearch/gradle/precommit/PrecommitTasks.groovy]: I agree, i converted it to info so it leaves a trace in CI. 
An issue isn't actionable either unless  we implement the support in forbidden APIs ourselves.

**Review by not-napoleon — APPROVED** [review]
LGTM

**Review by rjernst — APPROVED** [review]
LGTM
