### PR TITLE
Fix GoogleCloudStorageBlobStoreRepositoryTests#testMultipleSnapshotAndRollback

### LINKED ISSUE #139556: [CI] GoogleCloudStorageBlobStoreRepositoryTests testMultipleSnapshotAndRollback failing
**Build Scans:**
- [elasticsearch-intake #32377 / part1](https://gradle-enterprise.elastic.co/s/tser23mqq4skw)
- [elasticsearch-periodic-platform-support #11550 / debian-13_platform-support-unix](https://gradle-enterprise.elastic.co/s/fpwksjs7iijxw)
- [elasticsearch-pull-request #109712 / part-1](https://gradle-enterprise.elastic.co/s/4bruaqvoc3ml6)

**Reproduction Line:**
```
./gradlew ":modules:repository-gcs:internalClusterTest" --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStoreRepositoryTests.testMultipleSnapshotAndRollback" -Dtests.seed=8D2DCF04D643D138 -Dtests.locale=en-MO -Dtests.timezone=Europe/London -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStoreRepositoryTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMultipleSnapshotAndRollback'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.repositories.RepositoryVerificationException: [jblimsjm] [[-6pw8ypcSVybaAFVMXon2g, 'org.elasticsearch.transport.RemoteTransportException: [node_s5][127.0.0.1:30824][internal:admin/repository/verify]']]
```

**Issue Reasons:**
- [main] 3 failures in test testMultipleSnapshotAndRollback (0.8% fail rate in 359 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139665: [CI] GoogleCloudStorageBlobStoreRepositoryTests testReadNonExistingPath failing
**Build Scans:**
- [elasticsearch-intake #32463 / part1](https://gradle-enterprise.elastic.co/s/j2afgctoi5a7y)
- [elasticsearch-periodic-platform-support #11562 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/rb66y55uqtu4i)
- [elasticsearch-periodic #11589 / openjdk21_checkpart1_java-fips-matrix](https://gradle-enterprise.elastic.co/s/2tzi63rsvbnbk)
- [elasticsearch-pull-request #110003 / part-1](https://gradle-enterprise.elastic.co/s/uphnamuhbxyai)
- [elasticsearch-periodic-platform-support #11546 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/ox255mppsi3mk)
- [elasticsearch-periodic-platform-support #11546 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/zemes67rtp7ny)
- [elasticsearch-intake #32274 / part1](https://gradle-enterprise.elastic.co/s/6olqrqdeh5uzu)
- [elasticsearch-pull-request #109533 / checkpart1_gpu-tests](https://gradle-enterprise.elastic.co/s/n6yebqvqe44yo)
- [elasticsearch-pull-request #109529 / part-1](https://gradle-enterprise.elastic.co/s/s2dqjuise2rtu)
- [elasticsearch-pull-request #109524 / checkpart1_release-tests](https://gradle-enterprise.elastic.co/s/w6i4keb4kot44)

**Reproduction Line:**
```
./gradlew ":modules:repository-gcs:internalClusterTest" --tests "org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStoreRepositoryTests.testReadNonExistingPath" -Dtests.seed=477593DA50535A12 -Dtests.locale=es-US -Dtests.timezone=America/Scoresbysund -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStoreRepositoryTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testReadNonExistingPath'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.repositories.RepositoryVerificationException: [uutauan] [[gsT0a54zTpiGC5_8nlqaEg, 'org.elasticsearch.transport.RemoteTransportException: [node_s2][127.0.0.1:29205][internal:admin/repository/verify]']]
```

**Issue Reasons:**
- [main] 10 failures in test testReadNonExistingPath (1.9% fail rate in 534 executions)
- [main] 2 failures in step part1 (1.9% fail rate in 106 executions)
- [main] 2 failures in step part-1 (0.7% fail rate in 303 executions)
- [main] 2 failures in step oraclelinux-8_platform-support-unix (40.0% fail rate in 5 executions)
- [main] 2 failures in pipeline elasticsearch-intake (1.9% fail rate in 106 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (1.3% fail rate in 303 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
The reason for this test failure is that the `GoogleCloudStorageBlobStoreRepositoryTests.GoogleErroneousHttpHandler#requestUniqueId` implementation returns IDs that are not unique between nodes. This can cause the fault injection to exceed the maximum retries and fail the test. 

The reason it only showed up since the change is this test moved from using time-limited retries (unlimited by number) to using limited-by-number retries.

## Example interleaving:

(imagine client max retries is 3, mock server fails requests twice before allowing them to proceed)

|source node | request | result |
|-------------|--------|-------|
|`node1`| `GET /download/storage/v1/b/bucket/o/tests-xxx/master.dat` | blocked first time |
|`node1`| `GET /download/storage/v1/b/bucket/o/tests-xxx/master.dat` | blocked second time |
|`node2`| `GET /download/storage/v1/b/bucket/o/tests-xxx/master.dat` | allow through because third block |
|`node1`| `GET /download/storage/v1/b/bucket/o/tests-xxx/master.dat` | blocked first time (third for `node1`) |
|`node1`| `GET /download/storage/v1/b/bucket/o/tests-xxx/master.dat` | blocked second time (fourth for `node1`, client fails due to retries exceeded) |

The PR adds a client-id header which we can include in the request unique ID to disambiguate between clients.

Closes: #139556
Closes: #139646
Closes: #139665

### CODE REVIEW

File: modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java [hunk 1]
```diff
@@ -356,13 +375,19 @@ protected String requestUniqueId(HttpExchange exchange) {
...
 
+            String clientId = exchange.getRequestHeaders().getFirst(CLIENT_ID_HEADER);
+            if (clientId == null) {
+                if (exchange.getRequestURI().toString().startsWith("/batch/") == false) {
+                    logger.warn(
+                        "Missing {} on non-batch request, this may cause issues with fault injection: {}",
+                        CLIENT_ID_HEADER,
+                        exchange.getRequestURI()
+                    );
+                }
```
Comment (nicktindall) [inline modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java:389]: `/batch/` requests don't include the custom header, but they also aren't failed by this thing so that's OK

**Review by ywangd — APPROVED** [review]
LGTM

File: modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java [hunk 2]
```diff
@@ -356,13 +377,20 @@ protected String requestUniqueId(HttpExchange exchange) {
                 return idempotencyToken;
             }
```
Comment (mhl-b) [inline modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java:378]: Hm, I thought IDEMPOTENCY_TOKEN should address this problem, isn't it?

Comment (nicktindall) [reply modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java:378]: It doesn't appear to be populated for these requests (debugger indicates its not there). These are GET requests so perhaps idempotency is implied?

Comment (mhl-b) [reply modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java:378]: Right these GET request without idempotency token. In short it comes from 

https://github.com/elastic/elasticsearch/blob/c0e1c56a69b41a160a4235e309bd6666eed23f68/modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageRetryingInputStream.java#L71

```
final var meteredGet = client.meteredObjectsGet(purpose, blobId.getBucket(), blobId.getName());
-> storageRpc.objects().get(bucket, blob)
```

This returns an `Storage.Objects.Get` that does not perform retries and GCS client skips all retrying logic including idempotency key. I'm not sure why we should abandon default's client retry logic.

I think we should change 
```
FROM storage.objects().get(bucket, blob) -> Storage.Objects.Get

TO storage.reader(blobId) -> com.google.cloud.ReadChannel
```

A reader does use default retry logic and populates idempotency. It's a bigger change, but I think a right one.

Comment (mhl-b) [reply modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java:378]: Hm, there is a story about reader being bad, neither small or large chunks are acceptable for us due to internal buffering. https://github.com/elastic/elasticsearch/pull/55506

Considering all above CLIENT_ID is good choice :)

**Review by mhl-b — APPROVED** [review]
LGTM

File: modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java (hunk 2 above)
Comment (mhl-b) [reply modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java:378]: I'm not 100% positive, but my quick test showed using reader with 0-chunk-size does not do any buffering. The reader would have inner type of `com.google.cloud.storage.ApiaryUnbufferedReadableByteChannel` that does what we do in retrying stream, keep track of how many bytes were read and retry from there.

I think this is what we want.

Comment (nicktindall) [reply modules/repository-gcs/src/internalClusterTest/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStoreRepositoryTests.java:378]: Azure and GCS both provide this behaviour out of the box, but the `RetryingInputStream` has lots of logic specific to our use-case
- Retry indefinitely for indexing ops
- Retry never for repo analysis ops
- Don't count failures where we made meaningful progress

That was the reason I factored that logic out for re-use (the original ticket was about Azure not being tenacious enough in its retries). It also gives us a place to put more such common logic that might be ES-specific.

I will merge this as-is but happy to reconsider what we want from each layer going forward. I'll create a ticket to follow up.

**Comment by nicktindall** [comment]
@elasticmachine run elasticsearch-ci/elasticsearch-serverless-es-pr-check

**Comment by nicktindall** [comment]
@elasticsearchmachine test this please

**Comment by mhl-b** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/141689)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
