### PR TITLE
Fix FLS for frozen tier

### LINKED ISSUE #82044: Document Field Level Security on Frozen Tier not working correctly
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16.2 (running inside Elastic Cloud)

**Plugins installed**: []

**JVM version** (`java -version`): n/a (Elastic Cloud)

**OS version** (`uname -a` if on a Unix-like system): n/a (Elastic Cloud)

**Description of the problem including expected versus actual behavior**:

I seem to be running into an issue where Field Level Security throws a null exception when operating on frozen indices.

I have a simple ILM policy for my index that moves data from Hot to Frozen after 12 hours. Within that data set, I would like to grant access to all fields except for a few specific ones that I would like to remain internal only.

If I create a new user and grant them a custom role with field level security (allowing and denying specific fields), that user cannot search for anything beyond my hot data tier without getting the following exception back
```
"reason": "unsupported_operation_exception: null"
```
Within the data access role, If I disable `Grant access to specific fields`, the user can see and return results from the frozen tier.

I will note that in my current environment, this role also is using a `Grant read privileges to specific documents` templated query, however that does not seem to have an impact on this issue. I have tried to produce a working example below that does not involve that privilege.

**Steps to reproduce**:

1. Create a simple ILM policy that rolls data out of a hot index and into a frozen index

2. Index data into your ILM managed index so that you have both hot data AND frozen data within your cluster. If my ILM index alias was called `pulse`, my underlying indices are `pulse-0001`, `pulse-0002`, etc and the frozen indices look like `partial-pulse-0001`, `partial-pulse-0002`... etc

3. Create a new role that grants read access to you your desired indices, like below (I am using Kibana):

Screen Shot 2021-12-22 at 1 24 46 PM

4. Create a new user, and assign them typical access to a kibana space and grant them the data role from step 3

5. In a new private browser, log in as your new user and validate they have access to your frozen tier data and hot tier data, by viewing the Discover panel and looking at a timerange that spans hot and frozen tiers. (24 hrs in my case, see below as an example)

Screen Shot 2021-12-22 at 1 29 14 PM

6. Go back to the role you created as an admin, and check the box `Grant access to specific fields`. Deny a field in your data (see below as an example)

Screen Shot 2021-12-22 at 1 30 29 PM

7. Back as your new user, refresh the page to see shard exceptions being thrown for all your frozen indices (even though my time range is still set to 24 hours, I get exceptions for my entire frozen tier)

Screen Shot 2021-12-22 at 1 31 46 PM

Note in the screenshot above that my data is cut off arbitrarily, right near my frozen tier rollover line from my ILM policy

8. Investigate the exception further and you get the following

image

9. Clicking the tab for "Request" shows very normal request, and the "Response" tab looks like below:

Screen Shot 2021-12-22 at 1 35 18 PM

10. From the command line, I can search the cluster easily if I use a simple count search on a hot tier index

```
curl https://user:pass@my-cluster.es.us-east-1.aws.found.io:9243/pulse-000252/_count
# returns
{"count":<real number here>,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0}}
```

But if I try to do an operation on the whole alias that includes frozen shards, I get shard exceptions.
```
curl https://user:pass@my-cluster.es.us-east-1.aws.found.io:9243/pulse/_count
# returns 
{"count":<partial number here>,"_shards":{"total":248,"successful":14,"skipped":0,"failed":234,"failures":[{"shard":0,"index":"partial-pulse-000015","node":"XCRMYhdLR3KHuHxm74vlCg","reason":{"type":"unsupported_operation_exception","reason":"unsupported_operation_exception: null"}},{"shard":0,"index":"partial-pulse-000016","node":"9SNaA5L9TCqZ8l0BA39c1Q","reason":{"type":"unsupported_operation_exception","reason":"unsupported_operation_exception: null"}},{"shard":0,"index":"partial-pulse-000017","node":"XCRMYhdLR3KHuHxm74vlCg","reason":{"type":"unsupported_operation_exception","reason":"unsupported_operation_exception: null"}},.....
```

11. For sanity you can go back to your role configuration and uncheck "Grant access to specific fields" and run that _count command again:

```
curl https://user:pass@my-cluster.es.us-east-1.aws.found.io:9243/pulse/_count
{"count":<real number here>,"_shards":{"total":248,"successful":248,"skipped":0,"failed":0}}
```
and it works.

I have also tried combing through the built in [roles](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/built-in-roles.html) for Elastic, as well as the built in [index priviledges](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/security-privileges.html#privileges-list-indices) to see if there was anything related to the frozen tier specifically that causes this behavior, without much luck.

**Provide logs (if relevant)**:

I have tried to comb the logs inside of Elastic Cloud but the UI does not seem to be surfacing this exception where I can find it.

### PR DESCRIPTION
**Pull request by ywelsch**
Field level security was interacting in bad ways with the can-match phase on frozen tier shards (interaction between `FieldSubsetReader` and `RewriteCachingDirectoryReader`). This made can-match phase fail, which in the normal case would result in extra load on the frozen tier, and in the extreme case (in interaction with https://github.com/elastic/elasticsearch/pull/51708) made searches fail.

This is a bug that was indirectly introduced by #78988.

Closes #82044

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/FieldSubsetReader.java [hunk 1]
```diff
@@ -432,7 +432,18 @@ private Terms wrapTerms(Terms terms, String field) throws IOException {
...
             // so we hide terms for fields we filter out.
-            return fieldNamesFilterTerms;
+            if (fieldNamesFilterTerms == null) {
+                synchronized (this) {
+                    if (fieldNamesFilterTerms == null) {
+                        assert Transports.assertNotTransportThread("resolving filter terms");
+                        final Terms fieldNameTerms = super.terms(FieldNamesFieldMapper.NAME);
+                        this.fieldNamesFilterTerms = Optional.ofNullable(
+                            fieldNameTerms == null ? null : new FieldNamesTerms(fieldNameTerms)
+                        );
```
Comment (jpountz) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/FieldSubsetReader.java:442]: nit: it feels a bit weird to use `Optional.ofNullable` when you need to check for null already anyway, what about something like that instead?

```java
this.fieldNamesFilterTerms = fieldNameTerms == null ? Optional.empty() : Optional.of(new FieldNamesTerms(fieldNameTerms));
```

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/FieldSubsetReader.java [hunk 2]
```diff
@@ -432,7 +432,18 @@ private Terms wrapTerms(Terms terms, String field) throws IOException {
             // for the _field_names field, fields for the document
             // are encoded as postings, where term is the field.
             // so we hide terms for fields we filter out.
-            return fieldNamesFilterTerms;
+            if (fieldNamesFilterTerms == null) {
+                synchronized (this) {
+                    if (fieldNamesFilterTerms == null) {
```
Comment (jpountz) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/FieldSubsetReader.java:437]: can you leave a comment that explains why this is computed lazily?

**Review by jpountz — APPROVED** [review]

**Comment by ywelsch** [comment]
Thanks @jpountz!
