### PR TITLE
Test-fix testAcceptsMismatchedServerlessBuildHash #121869

### LINKED ISSUE #121869: [CI] TransportServiceHandshakeTests testAcceptsMismatchedServerlessBuildHash failing
**Build Scans:**
- [elasticsearch-periodic #6363 / openjdk24_entitlements_false_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/3x67fjphaqj7e)
- [elasticsearch-periodic #6363 / openjdk24_entitlements_true_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/dkmat7ic6bdeg)
- [elasticsearch-periodic #6356 / openjdk24_entitlements_false_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/wdtlmqehrmlcc)
- [elasticsearch-periodic #6356 / openjdk24_entitlements_true_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/c2oxofyeec2d6)
- [elasticsearch-periodic #6349 / openjdk24_entitlements_false_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/xul5abn7kjs5u)
- [elasticsearch-periodic #6342 / openjdk24_entitlements_false_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/rxkejmm4ahrik)
- [elasticsearch-periodic #6335 / openjdk24_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/u7jdlle3fkqv4)
- [elasticsearch-periodic #6328 / openjdk24_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/cuf4qx4k7enc2)
- [elasticsearch-periodic #6321 / openjdk24_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/ugdu5yhetykuu)
- [elasticsearch-periodic #6314 / openjdk24_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/onqxomtzadmuu)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.transport.TransportServiceHandshakeTests.testAcceptsMismatchedServerlessBuildHash" -Dtests.seed=32B2A08BD592F0A8 -Dtests.jvm.argline="-Des.entitlements.enabled=false" -Dtests.locale=ast-ES -Dtests.timezone=BET -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.transport.TransportServiceHandshakeTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testAcceptsMismatchedServerlessBuildHash),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [main] 18 consecutive failures in test testAcceptsMismatchedServerlessBuildHash
- [main] 4 consecutive failures in step openjdk24_entitlements_false_checkpart1_java-matrix
- [main] 2 consecutive failures in step openjdk24_entitlements_true_checkpart1_java-matrix
- [main] 12 consecutive failures in step openjdk24_checkpart1_java-matrix
- [main] 16 consecutive failures in pipeline elasticsearch-periodic
- [main] 18 failures in test testAcceptsMismatchedServerlessBuildHash (100.0% fail rate in 18 executions)
- [main] 4 failures in step openjdk24_entitlements_false_checkpart1_java-matrix (100.0% fail rate in 4 executions)
- [main] 2 failures in step openjdk24_entitlements_true_checkpart1_java-matrix (100.0% fail rate in 2 executions)
- [main] 12 failures in step openjdk24_checkpart1_java-matrix (100.0% fail rate in 12 executions)
- [main] 16 failures in pipeline elasticsearch-periodic (100.0% fail rate in 16 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mhl-b**
Fixes #121869

`testAcceptsMismatchedServerlessBuildHash` uses wrong system property name `"es.serverless"` but should be `"es.serverless_transport"`.

### CODE REVIEW

**Comment by mhl-b** [comment]
Hey @thecoop, I'm wondering why system property is different, am I missing something. It was like this for 1.5 years.

**Comment by thecoop** [comment]
This might be something @DaveCTurner has been modifying...

**Comment by mhl-b** [comment]
I see. I dont see "es.serverless" property in the code base, probably a mistake. This should be a valid fix.

File: server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java [hunk 1]
```diff
@@ -377,7 +377,8 @@ public void testRejectsMismatchedBuildHash() {
     public void testAcceptsMismatchedServerlessBuildHash() {
         assumeTrue("Current build needs to be a snapshot", Build.current().isSnapshot());
         assumeTrue("Security manager needs to be disabled", System.getSecurityManager() == null);
-        System.setProperty("es.serverless", Boolean.TRUE.toString());   // security manager blocks this
+        System.setProperty(TransportService.SERVERLESS_TRANSPORT_SYSTEM_PROPERTY, Boolean.TRUE.toString());   // security manager blocks
```
Comment (DiannaHohensee) [inline server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java:380]: Does the test reliably fail before this change? You mentioned [reproducing](https://github.com/elastic/elasticsearch/issues/121869#issuecomment-2652600927) it, but I wasn't sure of the frequency.

I'm wondering why this didn't fail in the first place when it was added. Maybe we could bundle the try-block logic into a method, and exercise it once with `System.setProperty(TransportService.SERVERLESS_TRANSPORT_SYSTEM_PROPERTY, Boolean.TRUE.toString());` set to true (succeeds) and then a second time set to false (should throw)?

**Review by DiannaHohensee — COMMENTED** [review]
This makes sense to me, but I had a concern about the reliability of the test before the change (see [comment](https://github.com/elastic/elasticsearch/pull/122332#discussion_r1953435204)).

File: server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java (hunk 1 above)
Comment (mhl-b) [reply server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java:380]: > Does the test reliably fail before this change?

yes, test fails every time with

```
./gradlew ":server:test" --tests "org.elasticsearch.transport.TransportServiceHandshakeTests.testAcceptsMismatchedServerlessBuildHash" -Dtests.seed=8278A46E39005C96 -Dtests.jvm.argline="-Des.entitlements.enabled=" -Dtests.locale=en-001 -Dtests.timezone=US/Pacific -Druntime.java=24
```

I believe test suppose to test this flag by going through debugger.

https://github.com/elastic/elasticsearch/blob/c27bc086770b12a71c335e5537318f54cce53a65/server/src/main/java/org/elasticsearch/transport/TransportService.java#L694-L698

But it set with "es.serverless_transport".

Comment (mhl-b) [reply server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java:380]: > Maybe we could bundle the try-block

Do you mean put System.setProperty inside try-catch? I dont think System.setProperty throws here. Also if it throws entire test case will not run.

Comment (DiannaHohensee) [reply server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java:380]: Okay, then it reliably fixes the test 👍  Thanks.

Optionally I'd suggest making the test more robust by also proving the test setup would normally throw, and then verifying that it does not throw with the serverless Property set -- e.g. put the try-block code in a method and call it twice, with and without the Property setting. But that's a test improvement, not a test fix, so I don't feel strongly about it.

**Review by DiannaHohensee — APPROVED** [review]
LGTM

File: server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java (hunk 1 above)
Comment (ywangd) [reply server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java:380]: I was curious why it started to fail now since all related changes have been around more than 1 year. It turns out the reason is that the test was never executed because of the following line

https://github.com/elastic/elasticsearch/blob/3c18ea6e4454c5977c20eb853e41fb8d80edf8dc/server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java#L379

SecurityManager is removed in JDK 24. Hence it started to fail now with JDK24 while it is skipped when running with all prior JDK versions.

Comment (ywangd) [reply server/src/test/java/org/elasticsearch/transport/TransportServiceHandshakeTests.java:380]: Yeah I think it definitely has ran since https://github.com/elastic/elasticsearch/pull/95754

**Comment by mosche** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/123476)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/123477)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/123478)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
