### PR TITLE
[ML] Audit job open failures and stop any corresponding datafeed

### LINKED ISSUE #48934: [ML] Datafeed assignment should cancel datafeeds with failed jobs
Currently if an ML job fails then we expect the datafeed to stop when it tries to send data to that job and receives an exception response.  However, this may not happen for a while after the job has failed, as the datafeed only sends data to it periodically.

If the node that the datafeed is running on is removed from the cluster while the job is in the `failed` state then there is a problem: the datafeed node assignment will refuse to assign it while its job is failed.  This leads to a datafeed that is in limbo, unable to be assigned to a new node and (due to #48931) unable to be force-stopped.

It would make more sense if the datafeed node assignment cancelled datafeeds whose jobs were in states where the datafeed would not work after reassignment, such as `closing` or `failed`.

There may be subtlety here, as the same node assignment code is used to generate error messages for the start_datafeed endpoint.  So we may need to find a way of telling the node assignment code whether it's being called on an initial assignment or a reassignment, and having it work slightly differently in the two cases:

1. For an initial assignment return an error message if the datafeed's job is in an unacceptable state
2. For a reassignment log an error and cancel the datafeed task if the datafeed's job is in an unacceptable state

### LINKED ISSUE #80621: [ML] anomaly detection Job failed without reason audit message when model snapshot is too old
Steps to reproduce (easier to do this from a cloud env)
- Deploy a 7.8.1 cluster and start a real-time anomaly detection job,
- Then create a 8.0 cluster by restoring that 7.8.1 cluster snapshot,
- after 8.0 cluster successfully was created, login to check the AD job status:

AD job failed on UI, and there is no failed reason being thrown, neither in job message. (At the time of 11:56 on the below screenshot)

Screen Shot 2021-11-10 at 9 50 03 AM

After stop datafeed and force-close job (at the time of 16:01 on above screen), restarting job gave the root cause of job failure, which was caused by old model snapshot:
```
{
  "error": {
    "root_cause": [
      {
        "type": "exception",
        "reason": "[response_code_rates] job snapshot [1636472812] has min version before [7.0.0], please revert to a newer model snapshot or reset the job"
      }
    ],
    "type": "exception",
    "reason": "[response_code_rates] job snapshot [1636472812] has min version before [7.0.0], please revert to a newer model snapshot or reset the job"
  },
  "status": 500
}
```
 
Expected behaviour:
Good failure message on UI and job messages

### PR DESCRIPTION
**Pull request by droberts195**
The anomaly detection code contained an assumption dating back
to 2016 that if a job failed then its datafeed would notice and
stop itself. That works if the job fails on a node after it has
successfully started up. But it doesn't work if the job fails
during the startup sequence. If the job is being started for the
first time then the datafeed won't be running, so there's no
problem, but if the job fails when it's being reassigned to a
new node then it breaks down, because the datafeed is started
but not assigned to any node at that instant. This leads to the
situation where a datafeed is started but its job is not opened,
which is supposed to be impossible.

This PR addresses this by making the job force-stop its own
datafeed if it fails during its startup sequence and the datafeed
is started.

Fixes #48934

Additionally, auditing of job failures during the startup
sequence is moved so that it happens for all failure scenarios
instead of just one.

Fixes #80621

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java [hunk 1]
```diff
@@ -404,13 +404,7 @@ public void writeUpdateProcessMessage(JobTask jobTask, UpdateParams updateParams
...
         ActionListener<QueryPage<ScheduledEvent>> eventsListener = ActionListener.wrap(events -> {
             updateProcessMessage.setScheduledEvents(events == null ? null : events.results());
-            communicator.writeUpdateProcessMessage(updateProcessMessage.build(), (aVoid, e) -> {
-                if (e == null) {
-                    handler.accept(null);
-                } else {
-                    handler.accept(e);
-                }
-            });
+            communicator.writeUpdateProcessMessage(updateProcessMessage.build(), (aVoid, e) -> handler.accept(e));
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/AutodetectProcessManager.java:407]: lulz, accept null if null

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/task/OpenJobPersistentTasksExecutor.java [hunk 2]
```diff
@@ -319,45 +320,78 @@ private void runJob(JobTask jobTask, JobState jobState, OpenJobAction.JobParams
...
+        jobTask.updatePersistentTaskState(failedState, ActionListener.wrap(r -> {
+            logger.debug(() -> new ParameterizedMessage("[{}] updated task state to failed", jobTask.getJobId()));
+            stopAssociatedDatafeedForFailedJob(jobTask.getJobId());
+        }, e -> {
+            logger.error(
+                new ParameterizedMessage("[{}] error while setting task state to failed; marking task as failed", jobTask.getJobId()),
+                e
+            );
+            jobTask.markAsFailed(e);
+        }));
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/task/OpenJobPersistentTasksExecutor.java:338]: We are blowing away the task here with `jobTask.markAsFailed(e);`

So, does it make sense to also `stopAssociatedDatafeedForFailedJob(jobTask.getJobId());` when we failed to set the job to failed?

Otherwise, we have a datafeed task around but the job task is gone.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/task/OpenJobPersistentTasksExecutor.java [hunk 3]
```diff
@@ -319,45 +320,78 @@ private void runJob(JobTask jobTask, JobState jobState, OpenJobAction.JobParams
...
+                            logger.error(
+                                new ParameterizedMessage(
+                                    "[{}] failed to stop associated datafeed [{}] after job failure",
+                                    jobId,
+                                    runningDatafeedId
+                                ),
+                                e
+                            );
+                        }
+                    }
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/task/OpenJobPersistentTasksExecutor.java:367]: What do you think of auditing a failure to stop? 

`TransportStopDatafeedAction` already audits on stop success. I am just wondering if we should alert the user of a weird state.

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/task/OpenJobPersistentTasksExecutor.java (hunk 2 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/task/OpenJobPersistentTasksExecutor.java:338]: Yes, sure, I'll add `stopAssociatedDatafeedForFailedJob` here too.

I am not sure if it will make any difference in practice though, because the only likely reason for failing to update the persistent task status is if the node is shutting down, and if that's happening then stopping the associated datafeed will also fail.

**Review by benwtrent — APPROVED** [review]
