### PR TITLE
Fix false circular view reference with shared wildcards

### LINKED ISSUE #146097: ES|QL: False-positive circular view reference when composing a subquery-based view with a simple view that shares a wildcard index pattern
**Elasticsearch version:** 9.4.0-SNAPSHOT (build hash `6cd0eb0de52ae19cec37ee49400d69d6b6b37dcd`, build date 2026-04-10)

**Describe the bug:** When a view defined with subqueries (e.g., `FROM (FROM app-events-* ...), (FROM auth-events-* ...)`) is composed with a simple view that queries one of the same wildcard patterns (e.g., `FROM auth-events-*`), querying the composed view produces a false-positive "circular view reference" error. The circular reference detection appears to walk into the subquery branches and treat a shared wildcard index pattern as a view dependency.

**Steps to reproduce:**

```
// Setup: two indices with distinct patterns
PUT app-events-001/_doc/1
{ "msg": "app error", "level": "error" }

PUT auth-events-001/_doc/1
{ "msg": "login failed", "level": "warn" }

// view_x: subqueries touching both patterns
PUT _query/view/view_x
{ "query": "FROM (FROM app-events-* | KEEP msg, level), (FROM auth-events-* | KEEP msg, level)" }

// view_y: simple view on one of the same patterns
PUT _query/view/view_y
{ "query": "FROM auth-events-* | KEEP msg, level" }

// Compose both views
PUT _query/view/view_xy
{ "query": "FROM view_x, view_y" }

// Query the composed view
POST _query
{ "query": "FROM view_xy" }
```

All view creation calls succeed. The error occurs when you **query** the composed view:

```json
{
  "error": {
    "type": "verification_exception",
    "reason": "circular view reference 'view_y': view_xy -> view_x -> view_y"
  },
  "status": 400
}
```

`view_x` does not reference `view_y` in any way -- they are completely independent. The detection incorrectly interprets the shared wildcard pattern (`auth-events-*`) as a view dependency.

**Control test:** When the simple view uses a non-overlapping pattern (e.g., `FROM other-events-*`), the circular reference error does NOT occur. Instead, the correct error is returned: "Nested subqueries are not supported" -- confirming the false positive is specifically triggered by wildcard pattern overlap.

**Expected behavior:** The query should either succeed or return the "Nested subqueries are not supported" error (which is the actual limitation). It should not report a circular view reference where none exists.

**Impact:** Any view that uses subqueries with wildcard patterns cannot be composed with another view that happens to touch one of the same wildcard patterns. This blocks composing independent investigation angles (e.g., multi-source error triage + auth-focused security view) that naturally touch overlapping data sources.

### LINKED ISSUE #146118: ES|QL Views false circular reference error on shared index pattern
Circular reference detection is conservative — if View A and View B both query the same underlying index pattern (e.g., svc-auth-*), composing them in a nested view triggers a "circular view reference" error even though there's no actual cycle.

Example:

```
PUT _query/view/error_triage
{
"query": """
FROM (
FROM svc-gateway-*
| WHERE http.response.status_code >= 500
| EVAL service = "gateway",
error_detail = CONCAT("HTTP ", http.response.status_code::string)
| KEEP @timestamp, service, error_detail, source.ip
),
(
FROM svc-payments-*
| WHERE transaction.status IN ("failed", "timeout")
| EVAL service = "payments",
error_detail = transaction.status
| KEEP @timestamp, service, error_detail, source.ip
),
(
FROM svc-auth-*
| WHERE event.action == "login" AND event.outcome == "failure"
| EVAL service = "auth",
error_detail = CONCAT(event.action, " ", event.outcome)
| KEEP @timestamp, service, error_detail, source.ip
)
"""
}
```

```
PUT _query/view/suspicious_ips
{
"query": """
FROM svc-auth-*
| WHERE event.action == "login" AND event.outcome == "failure"
| STATS attempts = COUNT(*),
first_seen = FIRST(@timestamp, @timestamp),
last_seen  = LAST(@timestamp, @timestamp)
BY source.ip
| WHERE attempts > 3
"""
}
```

then if you

```
PUT _query/view/incident_dashboard
{
"query": """
FROM error_triage, suspicious_ips
"""
}
```

and then query `FROM incident_dashboard`, you get an error

```
{
"error": {
"type": "verification_exception",
"reason": "circular view reference 'suspicious_ips': incident_dashboard -> error_triage -> suspicious_ips"
},
"status": 400
}
```

### PR DESCRIPTION
**Pull request by craigtaverner**
Fixes #146097. When a subquery-based view (e.g., `FROM (FROM app-events-* ...), (FROM auth-events-* ...)`) is composed with a simple view that shares a wildcard index pattern (e.g., `FROM auth-events-*`), querying the composed view incorrectly throws a "circular view reference" error.                                                                                                                                                                                             

The root cause is that `Node.transformDown()` always recurses into the children of a transformed node. After `replaceViewsUnresolvedRelation` resolves views and returns a fully-resolved plan, `transformDown` re-visits the children, causing wildcards inside resolved view subqueries to be re-resolved. This produces:

1. **False circular reference errors** — sibling view names accumulate in the shared `seenViews` set, so a wildcard matching a sibling view's name appears circular
2. **Deeply nested duplicate plans** — re-resolution creates new `ViewUnionAll` nodes recursively up to the max view depth

The fix tracks resolved plan nodes in an identity set. When `transformDown` later visits those nodes during its child recursion, they are recognized as already-resolved and skipped. The unnecessary `seenViews.add(view.name())` that polluted the shared seen set with sibling view names is also removed.

In addition ViewUnionAll flattening has been enhanced to also flatten included subqueries, so it becomes possible to have views that contain subqueries without generating a `Nested subqueries are not supported` error, as long as the subqueries inside the view are the top-most plan node (ie. no following commands after the subqueries inside the view).

## Test plan

  - [x] New: `testFalseCircularReferenceFromSharedWildcardPattern_Issue146097` — exact reproduction from #146097
  - [x] New: `testFalseCircularReferenceWithSharedWildcardInSubqueries` — two views sharing a wildcard pattern composed in a parent view (view names don't match wildcards)
  - [x] New: `testFalseCircularReferenceWhenWildcardMatchesSiblingViewName` — wildcard in a subquery matches a sibling view's name (with self-exclusion)
  - [x] New: `testGenuineSelfReferenceViaWildcardInComposedView` — genuine circular self-reference via wildcard is still correctly detected
  - [x] Enhance view flattening phase to include directly nested subqueries and fork
  - [x] Update tests to verify that subquery flattening works
  - [x] All 101 `InMemoryViewServiceTests` pass                                                                                                                                                                                                     
  - [x] Verified new tests fail without the fix    
  - [x] Verify CsvIT tests still pass      

Assisted by Claude

Fixes #146097
Fixes #146118

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/view/ViewResolver.java [hunk 1]
```diff
@@ -180,6 +207,14 @@ private void replaceViews(
         }, listener);
     }
 
+    /**
+     * Marks a plan and all its descendants as already resolved, so the outer transformDown
+     * traversal will skip them and not re-process their view references.
+     */
+    private static void markResolved(LogicalPlan plan, Set<LogicalPlan> resolvedPlans) {
+        plan.forEachDown(resolvedPlans::add);
+    }
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/view/ViewResolver.java]: NIT: seems this could be inlined

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/view/ViewResolver.java (hunk 1 above)
Comment (jfreden) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/view/ViewResolver.java]: +1

**Review by jfreden — APPROVED** [review]
LGTM!
