### PR TITLE
Fix SearchHit ref-count leak in chunked fetch coordinator path

### LINKED ISSUE #147634: [CI] TransportFetchPhaseCoordinationActionTests testDoExecuteWithHeaders failing
**Build Scans:**
- [elasticsearch-intake #38513 / part1](https://gradle-enterprise.elastic.co/s/hl3krgfk6cyee)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.search.fetch.chunk.TransportFetchPhaseCoordinationActionTests.testDoExecuteWithHeaders" -Dtests.seed=2710BEA33B64147 -Dtests.locale=ff-Latn-GN -Dtests.timezone=America/St_Vincent -Druntime.java=26
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.search.fetch.chunk.TransportFetchPhaseCoordinationActionTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testDoExecuteWithHeaders'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an empty collection
     but: <[LEAK: resource was not cleaned up before it was garbage-collected.
Recent access records: 
#1:
	in [elasticsearch[testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming][generic][T#1]][testDoExecuteReleasesRegistrationWhenDataNodeFailsAfterChunkStreaming]
	org.elasticsearch.search.fetch.chunk.FetchPhaseResponseChunk.close(FetchPhaseResponseChunk.java:206)
	org.elasticsearch.core.Releasables.close(Releasables.java:39)
	org.elasticsearch.core.Releasables.closeExpectNoException(Releasables.java:72)
	org.elasticsearch.action.ActionListenerImplementations$2.run(ActionListenerImplementations.java:51)
	org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:314)
	org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:438)
	org.elasticsearch.search.fetch.chunk.TransportFetchPhaseResponseChunkAction.lambda$processChunk$2(Transp
[truncated]
```

**Issue Reasons:**
- [main] 1 consecutive failures in test testDoExecuteWithHeaders
- [main] 1 consecutive failures in step part1
- [main] 1 consecutive failures in pipeline elasticsearch-intake

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by drempapis**
Fixes a `SearchHit` ref-count leak on the coordinator's chunked-fetch path, detected by the leak tracker.

`FetchPhaseResponseStream.writeChunk` and `FetchPhaseResponseChunk.close` shared ownership of each hit (chunk + queue, with an `incRef` in `writeChunk`), which left a refcount imbalance on partial-failure paths.

This change moves to single-ownership: hits are transferred per-hit from the chunk to the stream's queue via the new `FetchPhaseResponseChunk.consumeHits`, and `writeChunk` drops the explicit `incRef`. Queued hits are released by `closeInternal()` or handed onward by `buildFinalResult` as before.

This became visible after [#147155](https://github.com/elastic/elasticsearch/pull/147155), which made `SearchHit.readFrom` always pool `_source` and wrap the hit in `LeakTracker.wrap(new SimpleRefCounted())`

Closes #147634 #147622 #147693

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java [hunk 1]
```diff
@@ -141,24 +141,51 @@ public long getBytesLength() {
...
+    /* Visibility for tests */
+    SearchHit[] getHits() throws IOException {
+        ensureDeserialized();
         return deserializedHits != null ? deserializedHits : new SearchHit[0];
     }
 
-    public int[] getHitPositions() {
+    /* Visibility for tests */
+    int[] getHitPositions() {
         return hitPositions;
```
Comment (eranweiss-elastic) [inline server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java:185]: I think this better call `ensureDeserialized`, like `getHits`

File: server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java [hunk 2]
```diff
@@ -141,24 +141,51 @@ public long getBytesLength() {
...
-            try (StreamInput in = createStreamInput()) {
-                for (int i = 0; i < hitCount; i++) {
-                    hitPositions[i] = in.readVInt();
-                    deserializedHits[i] = SearchHit.readFrom(in);
-                }
+    /**
+     * Iterates the hits in this chunk, invoking {@code consumer} with each hit and its position.
+     * */
+    public void consumeHits(HitConsumer consumer) throws IOException {
+        ensureDeserialized();
```
Comment (eranweiss-elastic) [inline server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java:154]: Can this method be called from multiple threads? Does it need concurrency protection?

File: server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java
Comment (eranweiss-elastic) [inline server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java]: I would add here `deserializedHits[i] = null;`, to be consistent with `consumeHits`. Also, can it be called from a different thread from `consumeHits`? Do they need some kind of concurrency protection?

**Review by eranweiss-elastic — COMMENTED** [review]
Looks good overall. I'm not sure about concurrency - are there protections from other parts of the chunked mechanism?

File: server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java (hunk 1 above)
Comment (drempapis) [reply server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java:185]: Done, the `getHitPositions()` now calls `ensureDeserialized()` before returning, mirroring `getHits()`

File: server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java (hunk 2 above)
Comment (drempapis) [reply server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java:154]: Each `FetchPhaseResponseChunk` is single-owner. The transport handler builds a fresh instance, calls consumeHits once via `responseStream.writeChunk`, and closes it; it doesn't escape to other threads. I added a class-level thread-safety note to document this.

File: server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java
Comment (drempapis) [reply server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java]: Refactored both `consumeHits` and `close` to share a `drainDeserializedHits` helper, so the per-slot null is now applied consistently in both paths. Single-owner per chunk; no concurrency protection is needed.

File: server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java (hunk 2 above)
Comment (eranweiss-elastic) [reply server/src/main/java/org/elasticsearch/search/fetch/chunk/FetchPhaseResponseChunk.java:154]: Thanks!

**Review by eranweiss-elastic — APPROVED** [review]
LGTM.
