### PR TITLE
Correct service time parameter in ARS formula

### LINKED ISSUE #65838: ARS implementation inverts the priority of servicetime
**Elasticsearch version** (`bin/elasticsearch --version`): commit c3ab6f71c873551ebef333c655b348023a497d9b

**Plugins installed**: []

**JVM version** (`java -version`):
```
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.2+10, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Darwin Roberts-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
```

**Description of the problem including expected versus actual behavior**:

The implementation of the [C3 algorithm](https://www.usenix.org/system/files/conference/nsdi15/nsdi15-paper-suresh.pdf) uses 1/serviceTime in place of serviceTime.

i.e.
https://github.com/elastic/elasticsearch/blob/fd3d7e336822ed9966cec2be9a4c2d95b438117b/server/src/main/java/org/elasticsearch/node/ResponseCollectorService.java#L176
should be
```
double muBarS = FACTOR / serviceTime;
```

The confusion derives from the fact that the paper in question uses the notation mu_s to denote the **service rate**, which is the inverse of the service-time.

This results in incorrect choices of the fastest node. 

**Steps to reproduce**:

For example, if you apply this change to tests:
```
diff --git a/server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java b/server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java
index c05d0a551fe..f2bf47e49b2 100644
--- a/server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java
+++ b/server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java
@@ -571,8 +571,8 @@ public class OperationRoutingTests extends ESTestCase{
         assertThat(searchedShards.size(), equalTo(3));
 
         // Now let's start adding node metrics, since that will affect which node is chosen
-        collector.addNodeStatistics("node_0", 2, TimeValue.timeValueMillis(200).nanos(), TimeValue.timeValueMillis(150).nanos());
-        collector.addNodeStatistics("node_1", 1, TimeValue.timeValueMillis(100).nanos(), TimeValue.timeValueMillis(50).nanos());
+        collector.addNodeStatistics("node_0", 1, TimeValue.timeValueMillis(200).nanos(), TimeValue.timeValueMillis(150).nanos());
+        collector.addNodeStatistics("node_1", 1, TimeValue.timeValueMillis(200).nanos(), TimeValue.timeValueMillis(50).nanos());
         collector.addNodeStatistics("node_2", 1, TimeValue.timeValueMillis(200).nanos(), TimeValue.timeValueMillis(200).nanos());
         outstandingRequests.put("node_0", 1L);
         outstandingRequests.put("node_1", 1L);
```
You can see that with the same number of queued requests and the same client response time for each node, the algorithm should choose the node with the lowest service time (i.e. node 1), however the test fails because the current implementation chooses node_2 (the slowest).

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by jtibshirani**
The adaptive replica selection algorithm implements the [C3 algorithm](https://www.usenix.org/system/files/conference/nsdi15/nsdi15-paper-suresh.pdf)
for ranking nodes. The formula defines service time as a quantity `1/muBarS`.
Our implementation accidentally plugs in service time for `muBarS` instead of
`1/muBarS`. This commit corrects the formula and adds invariant tests to
confirm it behaves as expected.

This change also fixes a bug in how we adjust node statistics. To ensure that
nodes with high ranks occasionally get selected, every time we select a
'winner' node, we average its stats with the node's stats and add it to the
moving average. For service time, we were accidentally overwriting the whole
moving average with the new stats, which caused the ranks to adjust too
quickly. This issue has a much bigger impact now that the formula correctly
incorporates service time, and is important to fix so the behavior remains
reasonable.

Fixes #65838.

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java [hunk 1]
```diff
@@ -523,13 +523,11 @@ public void testAdaptiveReplicaSelection() throws Exception {
                 new ClusterSettings(Settings.EMPTY, ClusterSettings.BUILT_IN_CLUSTER_SETTINGS));
         opRouting.setUseAdaptiveReplicaSelection(true);
         List<ShardRouting> searchedShards = new ArrayList<>(numShards);
-        Set<String> selectedNodes = new HashSet<>(numShards);
         TestThreadPool threadPool = new TestThreadPool("testThatOnlyNodesSupportNodeIds");
         ClusterService clusterService = ClusterServiceUtils.createClusterService(threadPool);
         ResponseCollectorService collector = new ResponseCollectorService(clusterService);
-        Map<String, Long> outstandingRequests = new HashMap<>();
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java:530]: Some notes on these tests:
* I had to make the checks more lenient in order to get the test to pass. I tracked down the surprising behavior to `IndexShardRoutingTable#adjustStats`, which gives a big boost to slow nodes in terms of ranking. I plan to open a follow-up issue proposing more tests and a potential fix.
* Every time we select a 'winner' node, we update the outstanding requests map to increment the value by 1. It only affects the local copy, and does not update global statistics. While this has a purpose in the ARS logic, it is not the right behavior for this test.
* The `selectedNodes` map was unused.

Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java:530]: Some notes on these tests:
* I had to make the checks more lenient in order to get the test to pass. I tracked down the surprising behavior to `IndexShardRoutingTable#adjustStats`, which gives a big boost to slow nodes in terms of ranking. I plan to open a follow-up issue proposing more tests and a potential fix.
* Every time we select a 'winner' node, we update the outstanding requests map to increment the value by 1. It only affects the local copy, and does not update global statistics. While this has a purpose in the ARS logic, it is not the right behavior for this test. So we no longer share `outstandingRequests` across searches.

**Comment by jtibshirani** [comment]
As [mentioned in the issue](https://github.com/elastic/elasticsearch/issues/65838#issuecomment-791801275), for moderate queue sizes the existing behavior roughly ranks based on response time. So in many cases we may not see a real difference with this change. However (based on my understanding of the formula) there are possible improvements:
* The ranking could be more responsive, since we now better incorporate non-local information about each node's service time and queue size
* When nodes have larger queue sizes, we'll always make the right selection, whereas before we might pick a node with worse service time

Note that I have not run large scale end-to-end tests to assess the impact.

File: server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java (hunk 1 above)
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java:530]: Some notes:
* I had to make loosen the checks before the test would pass. I tracked down the surprising behavior to `IndexShardRoutingTable#adjustStats`, which can give a big boost to slower nodes in the ranking. I plan to open a follow-up issue proposing more tests and a potential fix.
* When a 'winner' node is selected, we update the local 'outstanding requests' map to increment its value by 1. This only affects the local copy, it doesn't update global statistics. While this has a purpose in the ARS logic, it doesn't make sense in the context of these tests. So I removed the shared `outstandingRequests` map.

File: server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java [hunk 2]
```diff
@@ -523,13 +523,11 @@ public void testAdaptiveReplicaSelection() throws Exception {
                 new ClusterSettings(Settings.EMPTY, ClusterSettings.BUILT_IN_CLUSTER_SETTINGS));
         opRouting.setUseAdaptiveReplicaSelection(true);
         List<ShardRouting> searchedShards = new ArrayList<>(numShards);
-        Set<String> selectedNodes = new HashSet<>(numShards);
-        TestThreadPool threadPool = new TestThreadPool("testThatOnlyNodesSupportNodeIds");
+        TestThreadPool threadPool = new TestThreadPool("test");
         ClusterService clusterService = ClusterServiceUtils.createClusterService(threadPool);
         ResponseCollectorService collector = new ResponseCollectorService(clusterService);
-        Map<String, Long> outstandingRequests = new HashMap<>();
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/cluster/routing/OperationRoutingTests.java:530]: When a 'winner' node is selected, we update the local 'outstanding requests' map to increment its value by 1. This only affects the local copy, it doesn't update global statistics. While this has a purpose in the ARS logic, it doesn't make sense in the context of this test. So I removed the shared `outstandingRequests` map here, and added another test that explicitly checks this behavior.

File: server/src/main/java/org/elasticsearch/cluster/routing/IndexShardRoutingTable.java [hunk 3]
```diff
@@ -309,7 +310,12 @@ private static void adjustStats(final ResponseCollectorService collector,
                     final ResponseCollectorService.ComputedNodeStats stats = maybeStats.get();
                     final int updatedQueue = (minStats.queueSize + stats.queueSize) / 2;
                     final long updatedResponse = (long) (minStats.responseTime + stats.responseTime) / 2;
-                    final long updatedService = (long) (minStats.serviceTime + stats.serviceTime) / 2;
+
+                    ExponentiallyWeightedMovingAverage avgServiceTime = new ExponentiallyWeightedMovingAverage(
+                        ResponseCollectorService.ALPHA, stats.serviceTime);
+                    avgServiceTime.addValue((minStats.serviceTime + stats.serviceTime) / 2);
+                    final long updatedService = (long) avgServiceTime.getAverage();
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/cluster/routing/IndexShardRoutingTable.java:317]: As discussed offline, the "adjustment" seems odd. We should think about updating the node statistics explicitly. That's not in the scope of this PR but that would be a good follow up as discussed offline.

**Review by jimczi — APPROVED** [review]
Great catch @jtibshirani ! The formula looks much better now ;).

**Comment by jtibshirani** [comment]
Thanks @jimczi for the review! I also tagged @henningandersen for a review to get input from the distributed area.

**Review by henningandersen — COMMENTED** [review]
Thanks for looking into this. I have a question, probably just me needing this clarification.

Also, I wonder if we could add an integration test to validate that the overall mechanism works as we expect it (for instance, doing two searches in a row, we would want to see it hit two different nodes (I think)).

File: server/src/main/java/org/elasticsearch/node/ResponseCollectorService.java [hunk 4]
```diff
@@ -161,12 +164,12 @@ private double innerRank(long outstandingRequests) {
...
-            // EWMA of service time
-            double muBarS = serviceTime / FACTOR;
+            // EWMA of service time. We match the paper's notation, which
+            // defines service time as the inverse of service rate (muBarS).
+            double muBarSInverse = serviceTime / FACTOR;
 
             // The final formula
-            double rank = rS - (1.0 / muBarS) + (Math.pow(qHatS, queueAdjustmentFactor) / muBarS);
-            return rank;
+            return rS - muBarSInverse + Math.pow(qHatS, queueAdjustmentFactor) * muBarSInverse;
```
[the remark this answers is not in the document]
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/node/ResponseCollectorService.java:172]: I also found this surprising and don't understand the reasoning. I am guessing it is meant as a loose approximation to the number of clients, since by default every node can serve as a coordinating node.

I can see a couple options. We could avoid making changes to `clientNum` in this PR to keep it well-scoped, while recognizing that it may give too much weight to the queue size factor. Or we could always set `clientNum` to 1 for now, which can underestimate the queue size, but is simpler and makes the calculation more predictable.

In any case, I will make sure we track this through an issue or other means.

**Comment by jtibshirani** [comment]
> I wonder if we could add an integration test to validate that the overall mechanism works as we expect it

I added `SearchReplicaSelectionIT` with some basic checks on end-to-end behavior.

File: server/src/main/java/org/elasticsearch/node/ResponseCollectorService.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/node/ResponseCollectorService.java:172]: My worry is primarily that if we split changes here, we end up with some customers seeing multiple changes to the behavior over releases.

On the other hand, my intuition on this matter is not really strong enough that I think it is a show-stopper to merge this first and then deal with the other part later. It seems likely enough that `clientNum` will stabilize around a similar number over time for "client" nodes in the cluster. It might be too high (or low) though and building up the `numClients` could take time after restarts.

The dedicated role for coordinating nodes might come in handy here.

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/main/java/org/elasticsearch/node/ResponseCollectorService.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/node/ResponseCollectorService.java:172]: This change identified a few aspects of ARS that could use improvement (including the 'stats adjustment` @jimczi mentioned above). So there will likely be more changes even apart from `clientNum`. To me it seems okay to introduce fixes/ improvements incrementally instead of assembling a single large update to the algorithm.
