### PR TITLE
Skip certain metric assertions on Windows

### LINKED ISSUE #144282: [CI] MetricsApmIT testApmIntegration {withOTel=false} failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11978 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/4yrgzedi43s7c)
- [elasticsearch-periodic-platform-support #11978 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/fr2h7tiguo2qi)
- [elasticsearch-pull-request #128476 / part-1-arm](https://gradle-enterprise.elastic.co/s/5pni5jlxjgn3k)
- [elasticsearch-pull-request #128457 / part-1-arm](https://gradle-enterprise.elastic.co/s/ueisdiizobcj6)
- [elasticsearch-pull-request #128417 / part-1-windows](https://gradle-enterprise.elastic.co/s/kkp7nc4kujudo)
- [elasticsearch-pull-request #128043 / part-1-arm](https://gradle-enterprise.elastic.co/s/eo4t472awooek)
- [elasticsearch-pull-request #127585 / part-1-arm](https://gradle-enterprise.elastic.co/s/end4gufpnns5i)
- [elasticsearch-pull-request #127478 / part-1-arm](https://gradle-enterprise.elastic.co/s/vwo5cnxqs7sym)
- [elasticsearch-pull-request #127478 / part-1-arm](https://gradle-enterprise.elastic.co/s/sv2xt5hzowqug)

**Reproduction Line:**
```
./gradlew ":test:external-modules:test-apm-integration:javaRestTest" --tests "org.elasticsearch.test.apmintegration.MetricsApmIT.testApmIntegration {withOTel=false}" -Dtests.seed=53AC9435DCC33624 -Dtests.locale=fi-FI -Dtests.timezone=America/Argentina/Rio_Gallegos -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.test.apmintegration.MetricsApmIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testApmIntegration%20%7BwithOTel%3Dfalse%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Timeout when waiting for assertions to complete. Remaining assertions to match: es.test.async_long_counter.total,es.test.long_gauge.current,es.test.double_gauge.current,es.test.double_counter.total,es.test.long_counter.total,es.test.async_double_counter.total,es.test.long_histogram.histogram,es.test.double_histogram.histogram
```

**Issue Reasons:**
- [main] 2 consecutive failures in step almalinux-8-aarch64_checkpart1_platform-support-arm
- [main] 2 consecutive failures in step part-1-arm
- [main] 9 failures in test testApmIntegration {withOTel=false} (1.5% fail rate in 618 executions)
- [main] 2 failures in step almalinux-8-aarch64_checkpart1_platform-support-arm (33.3% fail rate in 6 executions)
- [main] 6 failures in step part-1-arm (85.7% fail rate in 7 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (1.7% fail rate in 343 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #145152: [CI] SystemMetricsTests testOTelMetricsRegisteredWhenEnabled failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #12030 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/mqkx2jbfow53q)
- [elasticsearch-periodic-platform-support #12030 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/k7aidfxs7coza)
- [elasticsearch-periodic-java-ea #220 / checkpart1_windows-2025](https://gradle-enterprise.elastic.co/s/m7wjmo53bd7te)
- [elasticsearch-periodic-platform-support #12026 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/7jmk76bu4l2u6)
- [elasticsearch-periodic-platform-support #12026 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/w4ihzlvlrfnli)
- [elasticsearch-periodic-platform-support #12026 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/otzgbwtntcq22)
- [elasticsearch-periodic-java-ea #219 / checkpart1_windows-2025](https://gradle-enterprise.elastic.co/s/t2banxmnqpirq)
- [elasticsearch-periodic-platform-support #12022 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/cf524odi3xsla)
- [elasticsearch-periodic-platform-support #12022 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/wcxid5dt3dre4)
- [elasticsearch-periodic-platform-support #12022 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/qpryah5e56tvw)

**Reproduction Line:**
```
gradlew ":server:test" --tests "org.elasticsearch.monitor.metrics.SystemMetricsTests.testOTelMetricsNotRegisteredWhenNotEnabled" -Dtests.seed=AB4789F768538328 -Dtests.locale=fr-CG -Dtests.timezone=America/North_Dakota/New_Salem -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.monitor.metrics.SystemMetricsTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testOTelMetricsRegisteredWhenEnabled'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: jvm.fd.used should always be registered
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testOTelMetricsRegisteredWhenEnabled
- [main] 6 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [main] 4 consecutive failures in step checkpart1_windows-2025
- [main] 6 consecutive failures in step windows-2025_checkpart1_platform-support-windows
- [main] 16 failures in test testOTelMetricsRegisteredWhenEnabled (2.1% fail rate in 780 executions)
- [main] 6 failures in step windows-2022_checkpart1_platform-support-windows (100.0% fail rate in 6 executions)
- [main] 4 failures in step checkpart1_windows-2025 (100.0% fail rate in 4 executions)
- [main] 6 failures in step windows-2025_checkpart1_platform-support-windows (100.0% fail rate in 6 executions)
- [main] 4 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 4 executions)
- [main] 3 failures in pipeline elasticsearch-periodic-java-ea (100.0% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by mamazzol**
Make sure we don't check for metrics that are not enabled on Windows.

Closes: #144166 
Closes: #144167 
Closes: #144282   
Closes: #144976
Closes: #145152

### CODE REVIEW

File: test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java [hunk 1]
```diff
@@ -74,6 +75,33 @@ public static Iterable<Object[]> parameters() throws Exception {
...
         .build();
 
+    @ClassRule
+    // Custom test rule which manually orders test fixtures. A RuleChain won't work here due to the specific order we require, which is:
+    // 1. Start the mock APM server
+    // 2. Start ES cluster
+    // 3. Run the test
+    // 4. Stop the mock APM server
+    // 5. Stop ES cluster
+    public static TestRule rule = (base, description) -> {
```
Comment (mark-vieira) [inline test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java]: Should we refactor this into a `TestRule` we can reuse in both places?

File: test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java [hunk 2]
```diff
@@ -212,6 +240,12 @@ public void testJvmMetrics() throws Exception {
             )
         );
 
+        if (Constants.WINDOWS) {
+            // JVM file descriptor metrics are not emitted on Windows.
+            valueAssertions.remove("jvm.fd.used");
+            valueAssertions.remove("jvm.fd.max");
```
Comment (prdoyle) [inline test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java]: This might fix #144976.

File: test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/AbstractMetricsIT.java [hunk 3]
```diff
@@ -179,6 +180,12 @@ public void testJvmMetrics() throws Exception {
             )
         );
 
+        if (Constants.WINDOWS) {
```
Comment (prdoyle) [inline test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/AbstractMetricsIT.java:183]: Why does this check for Windows, while the other one checks `ProcessProbe`? I would have expected both of them to check the same thing.

**Review by prdoyle — APPROVED** [review]
One question, but I'll just approve because this is a pretty low-consequence PR since it's only fixing tests.
