### PR TITLE
[ML] Ensure queued AbstractRunnables are notified when executor stops

### LINKED ISSUE #134651: [ML] Reindex hangs when deployment forcefully shuts down
### Elasticsearch Version

latest

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

ECH

### Problem Description

While reindexing data using a semantic text field in the destination index, the reindex task can hang when a deployment is stopped upon assignment rebalancing.

### Steps to Reproduce

1. Create an ECH cluster with 2 ML nodes (2 zones) 8 GB nodes
2. Upload the marco data set or use the example data shipped with Kibana
3. Create an index `test-data` from the test data
4. Create an inference endpoint for elser
```
PUT _inference/sparse_embedding/test
{
  "service": "elasticsearch",
  "service_settings": {
    "model_id": ".elser_model_2_linux-x86_64",
    "num_threads": 1,
    "num_allocations": 2,
    "adaptive_allocations": {
      "enabled": false
    }
  }
}
```

This will force one allocation to be on each node.

We can ensure this has happened by checking the node stats: `GET _ml/trained_models/_stats`. We should see one allocation on each node.

5. Create the destination index

```
PUT dest-index
{
  "mappings": {
    "properties": {
      "column2": {
        "type": "text",
        "copy_to": "infer_field"
      },
      "infer_field": {
        "type": "semantic_text",
        "inference_id": "test"
      }
    }
  }
}
``` 

6. Perform a reindex from `test-data` to `dest-index`

```
POST _reindex?wait_for_completion=false
{
  "source": {
    "index": "test-data",
    "size": 1000
  },
  "dest": {
    "index": "dest-index"
  },
  "max_docs": 2000
}
```

Make sure to save the task id for reference later

7. Force the deployment on one of the nodes to stop by reducing the allocation count

```
PUT _inference/sparse_embedding/test/_update
{
  "service_settings": {
    "model_id": ".elser_model_2_linux-x86_64",
    "num_threads": 1,
    "num_allocations": 1
  }
}
```

This should cause the deployment to stop on one of the nodes but remain on the other one.

8. Observe that the inference counts are still increasing on the deployment that still exists

Poll `GET _ml/trained_models/_stats` a few times and ensure the `inference_stats.inference_count` is still increasing.

9. Note that the reindex task does not complete

Once it stops increasing, the reindex task should complete with failures but it when we retrieve the task it will show that it is not completed.

It'll likely show something like this

```
{
  "completed": false,
  "task": {
    "node": "nrA_ZbXYQCWyggxOpCoKUA",
    "id": 3167795,
    "type": "transport",
    "action": "indices:data/write/reindex",
    "status": {
      "total": 2000,
      "updated": 0,
      "created": 0,
      "deleted": 0,
      "batches": 1,
      "version_conflicts": 0,
      "noops": 0,
      "retries": {
        "bulk": 0,
        "search": 0
      },
      "throttled_millis": 0,
      "requests_per_second": -1,
      "throttled_until_millis": 0
    },
    "description": "reindex from [test-data] to [dest-index]",
    "start_time_in_millis": 1757692996623,
    "running_time_in_nanos": 2927073854341,
    "cancellable": true,
    "cancelled": false,
    "headers": {
      "trace.id": "464fbe4a5ac684bdd31f2e2df0e246b5"
    }
  }
}
```

In addition to this, there won't be any documents in the destination index.

### Logs (if relevant)

There should be logs like this showing that some requests were skipped because the deployment was forcefully shutdown

```
[instance-0000000003] [test] clearing [52] requests pending results
[instance-0000000003] [inference process] notifying [35] queued requests that have not been processed before shutdown
```

### PR DESCRIPTION
**Pull request by DonalEvans**
AbstractProcessWorkerExecutorService.notifyQueueRunnables() was making an incorrect assumption that all AbstractRunnables that were submitted for execution would be queued as AbstractRunnables. However, PriorityProcessWorkerExecutorService wraps AbstractRunnables in OrderedRunnable before queueing them, and since OrderedRunnable is not an AbstractRunnable, these were skipped when notifyQueueRunnables() drained the queue, leading to potential hangs.

- Refactor notifyQueueRunnables() to allow PriorityProcessWorkerExecutorService to notify the AbstractRunnable contained within queued OrderedRunnables
- Ensure that notifyQueueRunnables() is called and the executor marked as shut down if an exception is thrown from start()
- Add unit tests

Closes #134651

### CODE REVIEW

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/AbstractProcessWorkerExecutorService.java [hunk 1]
```diff
@@ -155,20 +156,22 @@ public synchronized void notifyQueueRunnables() {
...
+
+    protected static void notifyAbstractRunnable(Exception ex, String msg, AbstractRunnable ar) {
+        if (ex != null) {
+            ar.onFailure(ex);
+        } else {
+            ar.onRejection(new EsRejectedExecutionException(msg, true));
+        }
+    }
+
+    protected abstract void notifyIfAbstractRunnable(T runnable, Exception ex, String msg);
```
Comment (jonathan-buttner) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/AbstractProcessWorkerExecutorService.java]: What do you think about having `AbstractProcessWorkerExecutorService` contain the logic for `notifyIfAbstractRunnable` and relying on an abstract method like `getAsAbstractRunnable` which either returns the `AbstractRunnable` or `null`. That way child classes don't need to call back into the parent to do the notification, they would only return the abstract runnable if it was one.

Something like:

```
    protected abstract AbstractRunnable getAsAbstractRunnable(T runnable);

    private void notifyIfAbstractRunnable(T runnable, Exception ex, String msg) {
        var abstractRunnable = getAsAbstractRunnable(runnable);
        if (abstractRunnable != null) {
            notifyAbstractRunnable(ex, msg, abstractRunnable);
        }
    }
```

Then `PriorityProcessWorkerExecutorService` would have something like:

```
    @Override
    protected AbstractRunnable getAsAbstractRunnable(OrderedRunnable orderedRunnable, Exception ex, String msg) {
        // The runnable contained within OrderedRunnable is always an AbstractRunnable, so no need to check the type
        return orderedRunnable.runnable();
    }
```

**Review by jonathan-buttner — COMMENTED** [review]
Great work, left one suggestion

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/AbstractProcessWorkerExecutorService.java (hunk 1 above)
Comment (DonalEvans) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/AbstractProcessWorkerExecutorService.java]: Good idea, this is better

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/pytorch/PriorityProcessWorkerExecutorService.java [hunk 2]
```diff
@@ -35,7 +36,7 @@ public enum RequestPriority {
      * A Runnable sorted first by RequestPriority then a tie breaker which in
      * most cases will be the insertion order
      */
-    public record OrderedRunnable(RequestPriority priority, long tieBreaker, Runnable runnable)
+    protected record OrderedRunnable(RequestPriority priority, long tieBreaker, AbstractRunnable runnable)
```
Comment (davidkyle) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/pytorch/PriorityProcessWorkerExecutorService.java]: Another option is make `OrderedRunnable` extend `AbstractRunnable` and implement the required methods as calling the `runnable` parameter

Comment (DonalEvans) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/pytorch/PriorityProcessWorkerExecutorService.java]: This solution adds more code than the original one, but I think it might be better, since it simplifies the logic for determining what we need to notify.

**Review by jonathan-buttner — APPROVED** [review]

**Comment by DonalEvans** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/136125)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/136126)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/136127)|
|✅|8.18|[](https://github.com/elastic/elasticsearch/pull/136128)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
