### PR TITLE
[ML] Return status 400 for grok_pattern errors in find_structure

### LINKED ISSUE #68132: [Find structure API] Using an invalid regex in grok_pattern returns a 500
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12.0

**Description of the problem including expected versus actual behavior**:
When an invalid regular expression is used in the `grok_pattern` query parameter of a POST request to the find structure API, the response status code is `500`. The response status code should've been `400` along with a human-readable message.

Example response body for `POST _text_structure/find_structure?grok_pattern=[`:
  ```
{
  "error" : {
    "root_cause" : [ {
      "type" : "syntax_exception",
      "reason" : "premature end of char-class"
    } ],
    "type" : "syntax_exception",
    "reason" : "premature end of char-class",
    "suppressed" : [ {
      "type" : "exception",
      "reason" : "Explanation so far:\n[Using character encoding [UTF-8], which matched the input with [100%] confidence]\n[Deciding sample is text]\n[Most likely timestamp format is [yyyy-MM-dd HH:mm:ss.SSSSSS]]\n"
    } ]
  },
  "status" : 500
}
  ```

**Steps to reproduce**:
 1. `POST _text_structure/find_structure?grok_pattern=[` with a valid payload
 2. Notice that the response status code is `500`.

### PR DESCRIPTION
**Pull request by droberts195**
The _text_structure/find_structure endpoint should return a
400 error if an invalid grok_pattern override is supplied.
Previously this was happening in the case of high-level
errors, like named patterns that didn't exist, but in the
case of low-level errors in the regex structure 500 errors
were being returned. This change rectifies the mistake, so
that now both high-level and low-level errors in grok_pattern
overrides return status 400.

Fixes #68132

### CODE REVIEW

File: x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/GrokPatternCreator.java [hunk 1]
```diff
@@ -822,8 +822,11 @@ public boolean matchesAll(Collection<String> sampleMessages, TimeoutChecker time
             TimeoutChecker timeoutChecker
         ) {
 
-            explanation.add("A full message Grok pattern [" + grokPattern.substring(2, grokPattern.length() - 1) + "] looks appropriate");
-
+            if (grokPattern.startsWith("%{") && grokPattern.endsWith("}")) {
```
Comment (benwtrent) [inline x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/GrokPatternCreator.java:825]: is it ever the case that this pattern contains regex with it as well as grok captures?

Comment (droberts195) [reply x-pack/plugin/text-structure/src/main/java/org/elasticsearch/xpack/textstructure/structurefinder/GrokPatternCreator.java:825]: Only if it's supplied by the end user, and in that case this explanation doesn't make sense.  This explanation was originally added on the assumption it would relate to one of the "full line" matches on lines 54-68 of this file.  Later on the same class was used to apply arbitrary stuff the user might have supplied, but in that case they know that's the only Grok pattern that will be considered.

**Review by benwtrent — APPROVED** [review]
