### PR TITLE
SQL: Fix QlIllegalArgumentException with non-foldable date range queries

### LINKED ISSUE #137365: SQL: QlIllegalArgumentException due to failed folding: Cannot determine value for DATE_ADD('days', -30, field)
Happened as suppressed rest error on Serverless. (Internal issue: ES-13375)

```
"org.elasticsearch.xpack.ql.QlIllegalArgumentException: Cannot determine value for DATE_ADD('days', -30, field)
	at org.elasticsearch.xpack.ql.planner.ExpressionTranslators.valueOf(ExpressionTranslators.java:119)
	at org.elasticsearch.xpack.ql.planner.ExpressionTranslators$Ranges.translate(ExpressionTranslators.java:371)
	at org.elasticsearch.xpack.ql.planner.ExpressionTranslators$Ranges.lambda$doTranslate$0(ExpressionTranslators.java:367)
	at org.elasticsearch.xpack.ql.planner.TranslatorHandler.wrapFunctionQuery(TranslatorHandler.java:30)
	at org.elasticsearch.xpack.ql.planner.ExpressionTranslators$Ranges.doTranslate(ExpressionTranslators.java:367)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator$Ranges.asQuery(QueryTranslator.java:465)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator$Ranges.asQuery(QueryTranslator.java:450)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator$SqlExpressionTranslator.translate(QueryTranslator.java:495)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator.toQuery(QueryTranslator.java:147)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator$BinaryLogic.asQuery(QueryTranslator.java:314)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator$BinaryLogic.asQuery(QueryTranslator.java:305)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator$SqlExpressionTranslator.translate(QueryTranslator.java:495)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator.toQuery(QueryTranslator.java:147)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator$BinaryLogic.asQuery(QueryTranslator.java:317)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator$BinaryLogic.asQuery(QueryTranslator.java:305)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator$SqlExpressionTranslator.translate(QueryTranslator.java:495)
	at org.elasticsearch.xpack.sql.planner.QueryTranslator.toQuery(QueryTranslator.java:147)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldFilter.rule(QueryFolder.java:209)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldFilter.rule(QueryFolder.java:203)
	at org.elasticsearch.xpack.ql.tree.Node.lambda$transformUp$11(Node.java:198)
	at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:192)
	at org.elasticsearch.xpack.ql.tree.Node.lambda$transformUp$10(Node.java:190)
	at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:211)
	at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:190)
	at org.elasticsearch.xpack.ql.tree.Node.lambda$transformUp$10(Node.java:190)
	at org.elasticsearch.xpack.ql.tree.Node.transformChildren(Node.java:211)
	at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:190)
	at org.elasticsearch.xpack.ql.tree.Node.transformUp(Node.java:198)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:930)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:926)
	at org.elasticsearch.xpack.ql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:88)
	at org.elasticsearch.xpack.ql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:167)
	at org.elasticsearch.xpack.ql.rule.RuleExecutor.execute(RuleExecutor.java:136)
	at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:115)
	at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:39)
	at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:29)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:186)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:182)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:169)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.xpack.ql.index.IndexResolver.lambda$resolveAsMergedMapping$7(IndexResolver.java:401)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:261)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:228)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:222)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:350)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:33)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:111)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:373)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.mergeIndexResponses(TransportFieldCapabilitiesAction.java:368)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecuteForked$6(TransportFieldCapabilitiesAction.java:238)
	at org.elasticsearch.base@9.3.0/org.elasticsearch.core.AbstractRefCounted$1.closeInternal(AbstractRefCounted.java:125)
	at org.elasticsearch.base@9.3.0/org.elasticsearch.core.AbstractRefCounted.decRef(AbstractRefCounted.java:77)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.support.RefCountingRunnable.close(RefCountingRunnable.java:113)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.RunOnce.run(RunOnce.java:41)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.fieldcaps.RequestDispatcher.innerExecute(RequestDispatcher.java:177)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.fieldcaps.RequestDispatcher$1.doRun(RequestDispatcher.java:146)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:328)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:324)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.AbstractThrottledTaskRunner$1.doRun(AbstractThrottledTaskRunner.java:136)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:35)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1076)
	at org.elasticsearch.server@9.3.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
	at java.base/java.lang.Thread.run(Thread.java:1474)
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixing a NullPointerException due to the attempt to fold a range expression that is not foldable.
We'll translate it into a Painless script instead
Developed using AI-assisted tooling

Fixes: https://github.com/elastic/elasticsearch/issues/137365

### CODE REVIEW

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java [hunk 1]
```diff
@@ -364,7 +364,12 @@ protected Query asQuery(Range r, TranslatorHandler handler) {
         }
 
         public static Query doTranslate(Range r, TranslatorHandler handler) {
-            return handler.wrapFunctionQuery(r, r.value(), () -> translate(r, handler));
+            // Check if bounds are foldable for native RangeQuery
+            if (r.lower().foldable() && r.upper().foldable()) {
+                return handler.wrapFunctionQuery(r, r.value(), () -> translate(r, handler));
+            }
+            // Fall back to script query for non-foldable bounds (e.g., DATE_ADD with field reference)
+            return new ScriptQuery(r.source(), r.asScript());
```
Comment (astefan) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java]: Here don't you need to also call `wrapIfNested`?
Ie 
```
Query q = new ScriptQuery(r.source(), r.asScript());
  return wrapIfNested(q, r.value());
```

**Review by astefan — COMMENTED** [review]
Apart from my one comment related to the change, I would advise checking EQL code as well (since this code change is in common shared code between EQL and SQL) to see if/how this is affecting it. If necessary add tests for EQL as well. Thank you

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java]: Thanks for checking @astefan 

> I would advise checking EQL code as well

EQL is more restrictive than SQL, the optimizer can create `Range` objects, but only starting from expressions like `field >= expression`, and the right hand side expression is always checked and required to be foldable (if it's not, you'll get a `Comparisons against fields are not (currently) supported`). 

> Here don't you need to also call wrapIfNested?

That's a good point, let me check and add it.

Comment (luigidellaquila) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/planner/ExpressionTranslators.java]: I added `wrapIfNested` for correctness, but I think there is no practical way to make it happen in production. The verifier prevents functions from using nested fields, see https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java#L848, so I couldn't reproduce the original problem with a nested field.

**Review by astefan — APPROVED** [review]
LGTM
