### PR TITLE
Teach the build about betas and rcs

### LINKED ISSUE #26017: [CI] Vagrant centos packaging tests fail reliably
This seed reproduces it locally for me

```
gradle clean :qa:vagrant:vagrantCentos6#packagingTest -Dtests.seed=26CF6DE57E3F0087
```

Error message looks similar to https://github.com/elastic/elasticsearch/issues/25295 - but that might not be the true underlying issue I assume

### PR DESCRIPTION
**Pull request by nik9000**
The build was ignoring suffixes like "beta1" and "rc1" on the version numbers which was causing the backwards compatibility packaging tests to fail because they expected to be upgrading from 6.0.0 even though they were actually upgrading from 6.0.0-beta1. This adds the suffixes to the information that the build scrapes from Version.java. It then uses those suffixes when it resolves artifacts build from the bwc branch and for testing.

Closes #26017

### CODE REVIEW

**Comment by nik9000** [comment]
I'm still running through the test suite for this but it fixes the packaging tests and seems fine on the regular test suite. I'd also like to run the `gradle bwcTest` build before merging this, but I figure it'd be good to get some feedback on the approach.

**Comment by nik9000** [comment]
This is failing in the mixed cluster tests with:
```
  2> REPRODUCE WITH: gradle :qa:mixed-cluster:v6.1.0-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=6B1C9F49AFC53C45 -Dtests.class=org.elasticsearch.backwards.IndexingIT -Dtests.meth
od="testIndexVersionPropagation" -Dtests.security.manager=true -Dtests.jvms=12 -Dtests.locale=es -Dtests.timezone=America/Danmarkshavn
ERROR   1.47s | IndexingIT.testIndexVersionPropagation <<< FAILURES!
   > Throwable #1: org.elasticsearch.client.ResponseException: DELETE http://[::1]:41849*: HTTP/1.1 400 Bad Request
   > {"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[node-3][127.0.0.1:43495][indices:admin/delete]"}],"type":"illegal_argument_exception","reason":"Cannot 
delete indices that are being snapshotted: [[index1/UsojX7mgT_K23SvdPdlavA], [index2/jRZeN7MnTHuFxnKiGAM7mw]]. Try again after snapshot finishes or cancel the currently running sna
pshot."},"status":400}
```


I'm not sure  what is up with that but I don't see CI failing so it must be this change, somehow.

**Comment by nik9000** [comment]
After merging from master everything looks like it works now.

File: test/framework/src/test/java/org/elasticsearch/test/VersionUtilsTests.java [hunk 1]
```diff
@@ -195,7 +199,12 @@ public void testGradleVersionsMatchVersionUtils() {
                 /* Gradle skips the current version because being backwards compatible
                  * with yourself is implied. Java lists the version because it is useful. */
                 .filter(v -> v != Version.CURRENT)
-                .map(v -> v.major + "." + v.minor + "." + v.revision)
+                /* Note that gradle does *not* skip alphas, betas, or rcs here even
+                 * though we don't have backwards compatibility for alphas, betas,
```
Comment (rjernst) [inline test/framework/src/test/java/org/elasticsearch/test/VersionUtilsTests.java]: I thought we agreed to only have the last beta/rc in the wire/bwc test in the special case of a new major release like we have now. So we should not have betas/rcs here in most cases. Also, gradle still does not ever have alphas, that would not be matched by the regex for Version.java.

Comment (nik9000) [inline test/framework/src/test/java/org/elasticsearch/test/VersionUtilsTests.java]: I believe only the last beta/rc in a branch is unreleased so I think we're good there. I mean, it is technically possible for the release branch and the stable branch to have a beta but I don't think we'll do that so I'm not sure it is worth filtering it out.

I'm not sure why we don't have alphas in the Version.groovy. I mean, I know the regex doesn't match them, I just don't know why we treat them differently then betas. Either way, I can remove the word alpha here and make the filter just allow betas and rcs if you like.

I haven't changed the way gradle scrapes the versions. Did you want me to do that as part of this PR? We talked about wanting that "only the last beta/rc" behavior but I was under the impression we'd already implemented it. When I went to make this change it looks like we haven't and the reason our list lines up now is because we only pick up alphas.

Comment (rjernst) [inline test/framework/src/test/java/org/elasticsearch/test/VersionUtilsTests.java]: > I'm not sure why we don't have alphas in the Version.groovy. I mean, I know the regex doesn't match them, I just don't know why we treat them differently then betas

Because alphas are only cut from master, so there is never a case where we need to worry about bwc with an alpha. Only once we branch for a major release will we have betas/rcs.

Comment (rjernst) [inline test/framework/src/test/java/org/elasticsearch/test/VersionUtilsTests.java]: > We talked about wanting that "only the last beta/rc" behavior but I was under the impression we'd already implemented it

You are right, I think I already did this. I forgot.

File: build.gradle [hunk 2]
```diff
@@ -64,10 +64,10 @@ configure(subprojects.findAll { it.projectDir.toPath().startsWith(rootPath) }) {
 
 /* Introspect all versions of ES that may be tested agains for backwards
  * compatibility. It is *super* important that this logic is the same as the
- * logic in VersionUtils.java, modulo alphas, betas, and rcs which are ignored
```
Comment (nik9000) [inline build.gradle]: This was out of date.

File: build.gradle [hunk 3]
```diff
@@ -84,11 +84,16 @@ for (String line : versionLines) {
     int major = Integer.parseInt(match.group(1))
     int minor = Integer.parseInt(match.group(2))
     int bugfix = Integer.parseInt(match.group(3))
-    Version foundVersion = new Version(major, minor, bugfix, false)
+    String suffix = (match.group(4) ?: '').replace('_', '-')
+    Version foundVersion = new Version(major, minor, bugfix, suffix, false)
     if (currentVersion != foundVersion
-        && (major == prevMajor || major == currentVersion.major)
-        && (versions.isEmpty() || versions.last() != foundVersion)) {
-      versions.add(foundVersion)
```
Comment (nik9000) [inline build.gradle]: This was keeping `beta-1` when it should have been keeping `beta-2`.

**Review by nik9000 — COMMENTED** [review]
@rjernst I pushed an update. I believe this matches up with the logic we've talked about. I made it so gradle wouldn't keep alphas and updated some comments and tests around it keeping betas.

The tests found that gradle was keeping `6.0.0-beta1` instead of `6.0.0-beta2` and I believe I've fixed that was well.

File: build.gradle [hunk 4]
```diff
@@ -84,11 +84,16 @@ for (String line : versionLines) {
...
+        && (major == prevMajor || major == currentVersion.major)) {
+      if (versions.isEmpty() || versions.last() != foundVersion) {
+        versions.add(foundVersion)
+      } else {
+        // Replace the earlier betas with later ones
+        versions.set(versions.size() - 1, foundVersion)
```
Comment (rjernst) [inline build.gradle]: Can you assert/error here if foundVersion and/or the previous version.last() is not a beta/rc?

**Review by rjernst — APPROVED** [review]
Looks good, thanks @nik9000

File: build.gradle (hunk 4 above)
Comment (nik9000) [inline build.gradle]: :+1:

**Comment by nik9000** [comment]
I've merged this to master but I don't believe I can merge it to 6.x or 6.0 because that'd cause all kinds of "fun" problems.

**Comment by nik9000** [comment]
This change works in master because master only needs to test against 6.0.0-beta2 and 6.1.0, both of which are unreleased. On the other hand, cleanly backporting this to 6.x would have it testing against all the released 5.x versions and **three** unreleased versions: 5.5.2, 5.6.0, and 6.0.0-beta2. The build doesn't support testing against three unreleased versions, only 2.
