### PR TITLE
[Test] Add match for new error message from zulu jdk

### LINKED ISSUE #72122: [CI] SSLDriverTests testHandshakeFailureBecauseProtocolMismatch failing
Only reproduces on Zulu jvms. Reproduced for me locally with Zulu 11.0.11.

**Build scan:**
https://gradle-enterprise.elastic.co/s/ctngyizquooci/tests/:x-pack:plugin:security:test/org.elasticsearch.xpack.security.transport.nio.SSLDriverTests/testHandshakeFailureBecauseProtocolMismatch

**Reproduction line:**
`./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.transport.nio.SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch" -Dtests.seed=98E8EE60436E9816 -Dtests.locale=mt-MT -Dtests.timezone=Australia/Lindeman -Druntime.java=11`

**Applicable branches:**
master, 7.x, 7.13

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.security.transport.nio.SSLDriverTests&tests.test=testHandshakeFailureBecauseProtocolMismatch

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: (is "The client supported protocol versions [TLSv1.1] are not accepted by server preferences [TLS12]" or is "Client requested protocol TLSv1.1 not enabled or not supported")
     but: was "No appropriate protocol (protocol is disabled or cipher suites are inappropriate)"

  at __randomizedtesting.SeedInfo.seed([98E8EE60436E9816:47DBCF1979E59BE]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.xpack.security.transport.nio.SSLDriverTests.testHandshakeFailureBecauseProtocolMismatch(SSLDriverTests.java:195)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:829)

```

### PR DESCRIPTION
**Pull request by ywangd**
Azul backported [JDK-8196584](https://bugs.openjdk.java.net/browse/JDK-8196584) to Zulu JDK 8+. This changed the error message for TLSv1.1. This PR adds a new match for the new error message for specifically Zulu JDK.

Resolves: #72122

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/nio/SSLDriverTests.java [hunk 1]
```diff
@@ -191,8 +196,17 @@ public void testHandshakeFailureBecauseProtocolMismatch() throws Exception {
...
+                serverDriver.getSSLEngine().closeInbound();
+                serverDriver.getSSLEngine().closeOutbound();
+                serverDriver.close();;
+                assertTrue(serverDriver.isClosed());
+                clientDriver.close();
+                assertTrue(clientDriver.isClosed());
+            } else {
+                failedCloseAlert(serverDriver, clientDriver, Arrays.asList("Received fatal alert: protocol_version",
+                    "Received fatal alert: handshake_failure"));
+            }
```
Comment (ywangd) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/nio/SSLDriverTests.java:209]: The test fails without these changes. But honestly I am half guessing here. The latest zulu update seems to get into a weird state in that the driver is not closed but it does not have any buffer to flush either. So it would error out if we simply call `failedCloseAlert`. The test actually passes if I just comment out this block entirely for zulu, but I decide to mimic the behaviour of `failedCloseAlert` as much as possible, ie. closing down both server and client SSL drivers. 
@tbrooks8 in case there is more to it.

**Review by jkakavas — APPROVED** [review]
LGTM , let's merge this unless @tbrooks8 has any objections regarding the closing behavior

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/nio/SSLDriverTests.java [hunk 2]
```diff
@@ -178,7 +179,11 @@ public void testHandshakeFailureBecauseProtocolMismatch() throws Exception {
         } else {
             serverProtocols = new String[]{"TLSv1.2"};
             clientProtocols = new String[]{"TLSv1.1"};
-            expectedMessage = "The client supported protocol versions [TLSv1.1] are not accepted by server preferences [TLS12]";
+            if (inZuluJvm) {
+                expectedMessage = "No appropriate protocol (protocol is disabled or cipher suites are inappropriate)";
+            } else {
+                expectedMessage = "The client supported protocol versions [TLSv1.1] are not accepted by server preferences [TLS12]";
+            }
```
Comment (tvernum) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/nio/SSLDriverTests.java:186]: I don't think we should be worrying about checking the vendor for these sorts of fixes.

Why do we care about which message appears on which JVMs? Aren't both acceptable on all JDKs?

I'd prefer that, where possible, these sort of fixes end up with assertions that effectively say "any of these message are acceptable, the exact message might vary by JVM vendor/version"

Comment (ywangd) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/transport/nio/SSLDriverTests.java:186]: Indeed, I noticed this same test in 7.x branch uses `anyOf` when backporting. I thought about whether I should add this new error message to it. But didn't do so because it's already done this way in the `master` branch. I'll keep this in mind and change it to use `anyOf` if it fails again in future.
