### PR TITLE
[Tests] Fix alias names in PutIndexTemplateRequestTests

### LINKED ISSUE #30911: [CI] PutIndexTemplateRequestTests.testFromXContent fails reproducibly
I saw at least two instances today:

On 6.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/80/console

This reproduces on 6.x for me:
```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=4077509E4F46A969 \
  -Dtests.class=org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequestTests \
  -Dtests.method="testFromXContent" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-CC \
  -Dtests.timezone=US/Pacific-New
```

```
10:35:30    > Throwable #1: java.lang.AssertionError: 
10:35:30    > Expected: <[org.elasticsearch.action.admin.indices.alias.Alias@df79bfbc, org.elasticsearch.action.admin.indices.alias.Alias@6d4376, org.elasticsearch.action.admin.indices.alias.Alias@d8ddcb43]>
10:35:30    >      but: was <[org.elasticsearch.action.admin.indices.alias.Alias@6d4376, org.elasticsearch.action.admin.indices.alias.Alias@d9ea79d7, org.elasticsearch.action.admin.indices.alias.Alias@d8ddcb43]>
10:35:30    > 	at __randomizedtesting.SeedInfo.seed([4077509E4F46A969:611F6586C6E149B3]:0)
10:35:30    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
10:35:30    > 	at org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequestTests.assertEqualInstances(PutIndexTemplateRequestTests.java:189)
10:35:30    > 	at org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequestTests.assertEqualInstances(PutIndexTemplateRequestTests.java:48)
```

### PR DESCRIPTION
**Pull request by cbuescher**
The randomized alias names can contain unicode controll charactes that don't
survive an xContent rendering and parsing roundtrip when using the YAML xContent
type. This fix filters the randomized unicode string for control characters to
avoid this particular problem.

Closes #30911

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/admin/indices/alias/Alias.java [hunk 1]
```diff
@@ -248,6 +249,11 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
         return builder;
     }
 
+    @Override
+    public String toString() {
```
Comment (cbuescher) [inline server/src/main/java/org/elasticsearch/action/admin/indices/alias/Alias.java]: I added this because during debugging #30911 I found it really useful to have a readable toString() output for the Alias class.

Comment (dnhatn) [reply server/src/main/java/org/elasticsearch/action/admin/indices/alias/Alias.java]: +1

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @cbuescher

**Comment by cbuescher** [comment]
test this please
