### PR TITLE
Don't detect PlainActionFuture deadlock on concurrent complete

### LINKED ISSUE #110181: [CI] AsyncBulkByScrollActionTests testScrollResponseBatchingBehavior failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/h7gdqkimbf4tg/tests/:modules:reindex:test/org.elasticsearch.reindex.AsyncBulkByScrollActionTests/testScrollResponseBatchingBehavior

**Reproduction line:**
```
./gradlew ':modules:reindex:test' --tests "org.elasticsearch.reindex.AsyncBulkByScrollActionTests.testScrollResponseBatchingBehavior" -Dtests.seed=5638EFEF212A5042 -Dtests.locale=nl-BE -Dtests.timezone=America/Atka -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.reindex.AsyncBulkByScrollActionTests#testScrollResponseBatchingBehavior`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testScrollResponseBatchingBehavior'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.reindex.AsyncBulkByScrollActionTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: cannot complete future on thread Thread[#70,elasticsearch[testScrollResponseBatchingBehavior][generic][T#7],5,TGRP-AsyncBulkByScrollActionTests] with waiter on thread Thread[#69,elasticsearch[testScrollResponseBatchingBehavior][generic][T#6],5,TGRP-AsyncBulkByScrollActionTests], could deadlock if pool was full
	at java.base/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:410)
	at java.base/java.util.concurrent.LinkedTransferQueue$DualNode.await(LinkedTransferQueue.java:452)
	at java.base/java.util.concurrent.LinkedTransferQueue.xfer(LinkedTransferQueue.java:613)
	at java.base/java.util.concurrent.LinkedTransferQueue.poll(LinkedTransferQueue.java:1268)
	at java.base/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1069)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)

  at __randomizedtesting.SeedInfo.seed([5638EFEF212A5042]:0)
  at org.elasticsearch.action.support.PlainActionFuture.assertCompleteAllowed(PlainActionFuture.java:416)
  at org.elasticsearch.action.support.PlainActionFuture.onFailure(PlainActionFuture.java:42)
  at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.lambda$finishHim$3(AbstractAsyncBulkByScrollAction.java:598)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
  at org.elasticsearch.index.reindex.ClientScrollableHitSource.cleanup(ClientScrollableHitSource.java:127)
  at org.elasticsearch.index.reindex.ScrollableHitSource.lambda$close$2(ScrollableHitSource.java:115)
  at org.elasticsearch.index.reindex.ClientScrollableHitSource$2.onResponse(ClientScrollableHitSource.java:114)
  at org.elasticsearch.index.reindex.ClientScrollableHitSource$2.onResponse(ClientScrollableHitSource.java:110)
  at org.elasticsearch.reindex.AsyncBulkByScrollActionTests$MyMockClient.doExecute(AsyncBulkByScrollActionTests.java:1092)
  at org.elasticsearch.client.internal.support.AbstractClient.execute(AbstractClient.java:138)
  at org.elasticsearch.client.internal.support.AbstractClient.clearScroll(AbstractClient.java:363)
  at org.elasticsearch.index.reindex.ClientScrollableHitSource.clearScroll(ClientScrollableHitSource.java:110)
  at org.elasticsearch.index.reindex.ScrollableHitSource.close(ScrollableHitSource.java:115)
  at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.finishHim(AbstractAsyncBulkByScrollAction.java:588)
  at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction.finishHim(AbstractAsyncBulkByScrollAction.java:576)
  at org.elasticsearch.reindex.AbstractAsyncBulkByScrollAction$1.onFailure(AbstractAsyncBulkByScrollAction.java:373)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:967)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28)
  at org.elasticsearch.common.util.concurrent.RunOnce.run(RunOnce.java:40)
  at org.elasticsearch.index.reindex.WorkerBulkByScrollTaskState$DelayedPrepareBulkRequest.lambda$new$0(WorkerBulkByScrollTaskState.java:254)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:917)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1570)

```

### LINKED ISSUE #110360: PlainActionFuture#assertCompleteAllowed false positives on concurrent resolve
### Elasticsearch Version

8.14

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

macos

### Problem Description

PlainActionFuture detects dangerous usage patterns where threads from the same pool are simultaneously resolving and waiting on the future. This is to prevent tests that deadlock and is only switched on when assertions are enabled.

This deadlock detection can falsely fire when threads from the same pool are simultaneously resolving a future.

The sequence of events is as follows:

1. T1 calls `PlainActionFuture.Sync.complete` with a value or exception, it successfully performs `compareAndSet(RUNNING, COMPLETING)` and proceeds to set the value/exception.
2. T2 calls `PlainActionFuture.Sync.complete` with a value or exception, if fails to perform `compareAndSet(RUNNING, COMPLETING)` while state is `COMPLETING`. It calls `awaitShared` to wait for T1 to finish.
3. T3 from the same pool as T2 attempts to complete the future, it throws in `assertCompleteAllowed` because there is a thread from the same pool (T2) waiting on the result.

This is a false-positive because T2 will definitely complete.

Note that T1 can be the same as T3 if completing the future in a loop or the thread gets recycled.

### Steps to Reproduce

This has resulted in at least one [test flake](https://github.com/elastic/elasticsearch/issues/110181)

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by nicktindall**
Closes #110360
Closes #110181 

I don't love the test for this, but it does reproduce the issue reliably. Any suggestions for making it less verbose are appreciated.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/support/PlainActionFuture.java [hunk 1]
```diff
@@ -379,7 +379,11 @@ private boolean complete(@Nullable V v, @Nullable Exception e, int finalState) {
             } else if (getState() == COMPLETING) {
                 // If some other thread is currently completing the future, block until
                 // they are done so we can guarantee completion.
-                acquireShared(-1);
+                // Don't use acquire here, to prevent false-positive deadlock detection
+                // when multiple threads from the same pool are completing the future
+                while (isDone() == false) {
+                    Thread.onSpinWait();
+                }
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/action/support/PlainActionFuture.java:386]: I imagine we stay in this state extremely briefly as we're just waiting on two assignments, surely busy wait is OK here?

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 2]
```diff
@@ -142,6 +150,66 @@ public void testCancelException() {
...
+        public void run() {
+            try {
+                startBarrier.countDown();
+                safeAwait(startBarrier);
+                while (running.get()) {
+                    if (number == 0) {
+                        future.set(new PlainActionFuture<>());
+                    }
+                    future.get().onResponse(null);
+                }
```
Comment (nicktindall) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:202]: The issue only manifests in the moment the future is first resolved, this test reproduces fairly quickly when we do the above.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 3]
```diff
@@ -142,6 +150,62 @@ public void testCancelException() {
...
+            final AtomicBoolean running = new AtomicBoolean(true);
+            final CountDownLatch startBarrier = new CountDownLatch(threads + 1);
+            final CompletionService<?> cs = new ExecutorCompletionService<>(tp.generic());
+            final List<Future<?>> futures = new ArrayList<>();
+            for (int i = 0; i < threads; i++) {
+                futures.add(cs.submit(new FutureCompleter(i, startBarrier, futureReference, running), null));
+            }
+            startBarrier.countDown();
+            safeAwait(startBarrier);
+            cs.poll(250, TimeUnit.MILLISECONDS);
```
Comment (nicktindall) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:167]: This test will unfortunately run the full 250 in the happy case, on my desktop it seemed to fail around the 80ms mark fairly reliably before the fix.

File: server/src/main/java/org/elasticsearch/action/support/PlainActionFuture.java (hunk 1 above)
Comment (nicktindall) [reply server/src/main/java/org/elasticsearch/action/support/PlainActionFuture.java:386]: We could also use some other synchronisation mechanism here to wait/notify (that didn't add the waiter to the waiters for the `Sync`), but that might be overkill?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/action/support/PlainActionFuture.java:386]: Seems ok to me; possibly this is even more efficient, not that efficiency particularly matters in these cases.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:167]: I'd rather a test which fails _sometimes_ but always runs quickly, because we run this so often in CI that it'll catch the bug pretty soon anyway.

Comment (nicktindall) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: Cool, I reduced to 20ms which is still surprisingly reliable.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 4]
```diff
@@ -142,6 +150,62 @@ public void testCancelException() {
         assertPropagatesInterrupt(() -> future.actionGet(10, TimeUnit.SECONDS));
     }
 
+    public void testAssertCompleteAllowedAllowsConcurrentCompletes() throws InterruptedException {
+        assumeTrue("Assertions need to be enabled for assertCompleteAllowed to be invoked", Assertions.ENABLED);
+        try (TestThreadPool tp = new TestThreadPool(getTestName())) {
+            final AtomicReference<PlainActionFuture<?>> futureReference = new AtomicReference<>(new PlainActionFuture<>());
+            final int threads = 4;
+            final AtomicBoolean running = new AtomicBoolean(true);
+            final CountDownLatch startBarrier = new CountDownLatch(threads + 1);
```
Comment (ywangd) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:159]: Nit: can we call this `startLatch` instead of `startBarrier`. The name got me for a bit.

**Review by ywangd — APPROVED** [review]
LGTM

Nice catch! TIL!

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: I'm wondering why we need such a complicated test to reproduce this. Something like this seems to work too:

```diff
diff --git a/server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java b/server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java
index 2ca914eb23c..68c706c7f3c 100644
--- a/server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java
+++ b/server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java
@@ -14,6 +14,8 @@ import org.elasticsearch.common.util.concurrent.UncategorizedExecutionException;
 import org.elasticsearch.core.Assertions;
 import org.elasticsearch.core.TimeValue;
 import org.elasticsearch.test.ESTestCase;
+import org.elasticsearch.threadpool.TestThreadPool;
+import org.elasticsearch.threadpool.ThreadPool;
 import org.elasticsearch.transport.RemoteTransportException;

 import java.util.concurrent.CancellationException;
@@ -180,4 +182,19 @@ public class PlainActionFutureTests extends ESTestCase {
             }
         };
     }
+
+    public void testConcurrentCompletion() {
+        try (var threadPool = new TestThreadPool(getTestName())) {
+            final var future = new PlainActionFuture<>();
+            final var threadCount = threadPool.info(ThreadPool.Names.GENERIC).getMax();
+            final var barrier = new CyclicBarrier(threadCount);
+            for (int taskIndex = 0; taskIndex < threadCount; taskIndex++) {
+                threadPool.generic().execute(() -> {
+                    safeAwait(barrier);
+                    future.onResponse(null);
+                });
+            }
+            assertNull(safeGet(future));
+        }
+    }
 }
```

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
I think we should try and simplify the test

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: slightly nicer:

```diff
diff --git a/server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java b/server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java
index 2ca914eb23c..4893dfc91e8 100644
--- a/server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java
+++ b/server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java
@@ -9,11 +9,14 @@
 package org.elasticsearch.action.support;

 import org.elasticsearch.ElasticsearchException;
+import org.elasticsearch.action.ActionRunnable;
 import org.elasticsearch.common.util.concurrent.FutureUtils;
 import org.elasticsearch.common.util.concurrent.UncategorizedExecutionException;
 import org.elasticsearch.core.Assertions;
 import org.elasticsearch.core.TimeValue;
 import org.elasticsearch.test.ESTestCase;
+import org.elasticsearch.threadpool.TestThreadPool;
+import org.elasticsearch.threadpool.ThreadPool;
 import org.elasticsearch.transport.RemoteTransportException;

 import java.util.concurrent.CancellationException;
@@ -180,4 +183,18 @@ public class PlainActionFutureTests extends ESTestCase {
             }
         };
     }
+
+    public void testConcurrentCompletion() {
+        try (var threadPool = new TestThreadPool(getTestName())) {
+            final var future = new PlainActionFuture<>();
+            final var executorName = randomFrom(ThreadPool.Names.GENERIC, ThreadPool.Names.MANAGEMENT);
+            final var threadCount = threadPool.info(executorName).getMax();
+            final var executor = threadPool.executor(executorName);
+            final var barrier = new CyclicBarrier(threadCount);
+            for (int i = 0; i < threadCount; i++) {
+                executor.execute(ActionRunnable.run(future, () -> safeAwait(barrier)));
+            }
+            assertNull(safeGet(future));
+        }
+    }
 }
```

Comment (nicktindall) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: That doesn't seem to trigger it on my machine (It's been running for >5000 times without a failure so far). I will try and inline the logic so we don't need the inner class. I'm sure it can be made simpler.

Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: Weird, it fails pretty reliably for me. Although 5k iterations isn't very many.

Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: Try running with `-Dtests.iters=1000 -Dtests.failfast=true`, no need to wait for seconds+ for Gradle to start up on each iteration.

Comment (nicktindall) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: I'm not sure what the difference is, but I can't get it to fail. This M3 MacBook seems to eat race conditions for breakfast (I also had trouble reproducing [this one](https://github.com/elastic/elasticsearch/issues/109866)).

I ran for 800,000 iterations which took ~48 minutes and produced zero failures where the latest iteration of my longer test fails almost immediately. While I accept that CI Is probably going to yield these failures more reliably, I think it's probably best if we have a test that reproduces on typical dev hardware.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 5]
```diff
@@ -142,6 +147,37 @@ public void testCancelException() {
...
+            }
+            // continually create new futures to complete
+            safeAwait(startBarrier);
+            long endTime = System.currentTimeMillis() + 20;
+            while (System.currentTimeMillis() < endTime) {
+                futureReference.set(new PlainActionFuture<>());
+                safeSleep(1);
+            }
+            running.set(false);
+            futures.forEach(ESTestCase::safeGet);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:177]: No real need to wait on these futures, uncaught exceptions will fail the test anyway and shutting down the threadpool will `join()` all the threads.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java (hunk 3 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: > I think it's probably best if we have a test that reproduces on typical dev hardware.

Hmm I think this is the wrong way round - if "typical dev hardware" isn't able to reproduce genuine race conditions that happen in CI/production then I don't think we should work around that by making one specific test more complex. I'd recommend using a GCP machine for long-running repro attempts rather than your laptop since it'll be closer to real production infra.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 6]
```diff
@@ -142,6 +147,37 @@ public void testCancelException() {
...
+                    safeAwait(startBarrier);
+                    while (running.get()) {
+                        futureReference.get().onResponse(null);
+                    }
+                }, null));
+            }
+            // continually create new futures to complete
+            safeAwait(startBarrier);
+            long endTime = System.currentTimeMillis() + 20;
+            while (System.currentTimeMillis() < endTime) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:172]: Maybe just loop 20 times rather than hammering on `System.currentTimeMillis()`?

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 7]
```diff
@@ -142,6 +147,37 @@ public void testCancelException() {
...
+    public void testAssertCompleteAllowedAllowsConcurrentCompletesFromSamePool() {
+        assumeTrue("Assertions need to be enabled for assertCompleteAllowed to be invoked", Assertions.ENABLED);
+        final AtomicReference<PlainActionFuture<?>> futureReference = new AtomicReference<>(new PlainActionFuture<>());
+        final var executorName = randomFrom(ThreadPool.Names.GENERIC, ThreadPool.Names.MANAGEMENT);
+        final var threadCount = 4;
+        final var running = new AtomicBoolean(true);
+        final var startBarrier = new CyclicBarrier(threadCount + 1);
+        final var futures = new ArrayList<Future<?>>();
+        try (TestThreadPool threadPool = new TestThreadPool(getTestName())) {
+            assert threadPool.info(executorName).getMax() >= threadCount : "Not enough threads in pool";
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:159]: Why not use all the threads available? More than 4 normally, but even if the pool is smaller than 4 sometimes it's still a valid test.

Comment (nicktindall) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:159]: It blows the test time out to 300ms+ on my machine because of the additional synchronisation. 4 threads takes < 100ms but still reliably reproduces the issue.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java (hunk 3 above)
Comment (nicktindall) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: I think my version of the test is about as slender as it can be now (thanks for the feedback), but I'm OK with replacing it with the much shorter test if you'd prefer.
I'm satisfied that the issue was there and the change fixes it, and it sounds like that test will fail in CI if we regress, so I'm happy to go with consensus on the cost/benefit of the additional complexity.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java (hunk 7 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:156]: Ok let's use `Math.min(threadPool.info(executorName).getMax(), 4)` rather than failing the test if the threadpool is smaller than 4, and add a comment about why.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 8]
```diff
@@ -142,6 +145,34 @@ public void testCancelException() {
...
+        final AtomicReference<PlainActionFuture<?>> futureReference = new AtomicReference<>(new PlainActionFuture<>());
+        final var executorName = randomFrom(ThreadPool.Names.GENERIC, ThreadPool.Names.MANAGEMENT);
+        final var threadCount = 4;
+        final var running = new AtomicBoolean(true);
+        final var startBarrier = new CyclicBarrier(threadCount + 1);
+        try (TestThreadPool threadPool = new TestThreadPool(getTestName())) {
+            assert threadPool.info(executorName).getMax() >= threadCount : "Not enough threads in pool";
+            // N threads competing to complete the futures
+            for (int i = 0; i < threadCount; i++) {
+                threadPool.executor(executorName).submit(() -> {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:159]: We can just use `execute()` now that we don't care about the result - no need to wrap the task in a `RunnableFuture`.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 9]
```diff
@@ -142,6 +145,34 @@ public void testCancelException() {
...
+                    safeAwait(startBarrier);
+                    while (running.get()) {
+                        futureReference.get().onResponse(null);
+                    }
+                }, null);
+            }
+            // create new futures to complete
+            safeAwait(startBarrier);
+            for (int i = 0; i < 20; i++) {
+                futureReference.set(new PlainActionFuture<>());
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:169]: Would it help to wait on the future to be completed too?

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 10]
```diff
@@ -142,6 +145,34 @@ public void testCancelException() {
...
+            // N threads competing to complete the futures
+            for (int i = 0; i < threadCount; i++) {
+                threadPool.executor(executorName).submit(() -> {
+                    safeAwait(startBarrier);
+                    while (running.get()) {
+                        futureReference.get().onResponse(null);
+                    }
+                }, null);
+            }
+            // create new futures to complete
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:166]: Could you expand this comment to describe why we're creating multiple futures, recording the investigations you've done in this area?

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java [hunk 11]
```diff
@@ -142,6 +145,34 @@ public void testCancelException() {
         assertPropagatesInterrupt(() -> future.actionGet(10, TimeUnit.SECONDS));
     }
 
+    public void testAssertCompleteAllowedAllowsConcurrentCompletesFromSamePool() {
+        assumeTrue("Assertions need to be enabled for assertCompleteAllowed to be invoked", Assertions.ENABLED);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:149]: Is this assumption necessary any more?

**Review by DaveCTurner — COMMENTED** [review]
Ok I think the test is simple enough now for my tastes, although IMO it deserves a few more comments explaining why it's not any simpler.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java (hunk 11 above)
Comment (nicktindall) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:149]: Yes, because
```java
@Override
    public void onFailure(Exception e) {
        assert assertCompleteAllowed();  // <----- only tested when assertions enabled
        ...
```

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java (hunk 9 above)
Comment (nicktindall) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:169]: I actually don't think so, I tried replacing the sleep with a wait and that made the test unreliable. I measured, and on my machine each thread completed that loop about 800,000 times in the ~20ms so I feel waiting on the future (in addition to the sleep) is at best redundant and at worst interfering with the behaviour under test.

File: server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java (hunk 11 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java:149]: Sure, but the test is still valid either way AFAICT. I mean most tests make stronger checks if assertions are enabled, but that doesn't mean we should suppress them all like this.

Comment (nicktindall) [reply server/src/test/java/org/elasticsearch/action/support/PlainActionFutureTests.java]: Yes, fair. I guess I was over-fitting the test to the issue that was fixed (rather than implementing a generic "can complete futures concurrently"). Have removed.

**Review by DaveCTurner — APPROVED** [review]
LGTM thanks for the extra iterations Nick
