### PR TITLE
Make testSortAndPaginateWithInProgress test stable

### LINKED ISSUE #79779: [CI] RestGetSnapshotsIT testSortAndPaginateWithInProgress failing
This has been particularly flaky over the last 4 days, https://gradle-enterprise.elastic.co/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Athens&tests.container=org.elasticsearch.http.snapshots.RestGetSnapshotsIT&tests.sortField=FAILED&tests.test=testSortAndPaginateWithInProgress&tests.unstableOnly=true

**Build scan:**
https://gradle-enterprise.elastic.co/s/j6rh73in4gaqi/tests/:qa:smoke-test-http:integTest/org.elasticsearch.http.snapshots.RestGetSnapshotsIT/testSortAndPaginateWithInProgress

**Reproduction line:**
`./gradlew ':qa:smoke-test-http:integTest' --tests "org.elasticsearch.http.snapshots.RestGetSnapshotsIT.testSortAndPaginateWithInProgress" -Dtests.seed=7213D5EE803D5CAB -Dtests.locale=es-GT -Dtests.timezone=Africa/Accra -Druntime.java=11`

**Applicable branches:**
master, 7.16

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.http.snapshots.RestGetSnapshotsIT&tests.test=testSortAndPaginateWithInProgress

**Failure excerpt:**
```
java.lang.AssertionError: expected:<[SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-0/sDjyOJX2T6iU413ObgP0vQ, state=SUCCESS, reason='null', indices=[], startTime=1635229854789, endTime=1635229854798, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-1/-V1xYn8BSo2wfPpb0NMJHg, state=SUCCESS, reason='null', indices=[], startTime=1635229854799, endTime=1635229854977, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-2/ZN4gRmQ_RYGD_bncyxtt0g, state=SUCCESS, reason='null', indices=[], startTime=1635229854807, endTime=1635229855058, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-3/1V7dbEZTRViX6Xm6gpFPpw, state=SUCCESS, reason='null', indices=[], startTime=1635229854815, endTime=1635229855195, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-4/lTg7HDpoQu6Mjj5oezP-5A, state=SUCCESS, reason='null', indices=[], startTime=1635229854825, endTime=1635229855266, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-5/h6NqkmHdSeyh39M5RDnDAg, state=SUCCESS, reason='null', indices=[], startTime=1635229854834, endTime=1635229855336, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-6/ujKA23-5RlKYnsuR4voX-g, state=SUCCESS, reason='null', indices=[], startTime=1635229854844, endTime=1635229855406, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-7/RHoKZTc7RFqAWjPtVd7wuw, state=SUCCESS, reason='null', indices=[], startTime=1635229854853, endTime=1635229855475, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-8/c92IKJWrTTKErIjYIdpYDA, state=SUCCESS, reason='null', indices=[], startTime=1635229854862, endTime=1635229855554, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-9/_YPz1Pb4R2GFA3MAfmPlOA, state=SUCCESS, reason='null', indices=[], startTime=1635229854869, endTime=1635229855625, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-10/ci7dlrL4QhSRts6C9T0W-A, state=SUCCESS, reason='null', indices=[], startTime=1635229854877, endTime=1635229855698, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-11/T8FYr2TuQOua6LA8ixbs1A, state=SUCCESS, reason='null', indices=[], startTime=1635229854886, endTime=1635229855774, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-0/IN6wQLGIRhy1zYwuu-yQAQ, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856046, endTime=1635229856184, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-1/uax8pIsKQPy8faEh70tJCQ, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856073, endTime=1635229856275, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-2/nk49YuzDQtGzoGnK4J9DAg, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856084, endTime=1635229856370, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-3/-001QUBSQqiaOSG-OgsrAA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856096, endTime=1635229856464, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-4/AGpAmNKsShqJjmHuQ5ejsA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856106, endTime=1635229856548, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-5/WP1Lxs8eRsiFk0RNcr0imA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856118, endTime=1635229856635, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-6/j3IqqtHkTmmX6g2hJDDhxg, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856127, endTime=1635229856706, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-7/Nxjbp5-VQCemmpCrUbAI4Q, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856137, endTime=1635229856787, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-8/iI6h0Db3TwSKxzj9Q9QdFw, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856145, endTime=1635229856868, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-9/4TJbSrfTTy-sKoE5dEyJig, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856156, endTime=1635229856960, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-10/KFTwDVyYRFCx3urqyGd79Q, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856166, endTime=1635229857023, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-0/J_xiB2MJSzasDHffrckpHw, state=IN_PROGRESS, reason='null', indices=[test-index-1, test-index-2], startTime=1635229857294, endTime=0, totalShards=2, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}]> but was:<[SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-0/sDjyOJX2T6iU413ObgP0vQ, state=SUCCESS, reason='null', indices=[], startTime=1635229854789, endTime=1635229854798, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-1/-V1xYn8BSo2wfPpb0NMJHg, state=SUCCESS, reason='null', indices=[], startTime=1635229854799, endTime=1635229854977, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-2/ZN4gRmQ_RYGD_bncyxtt0g, state=SUCCESS, reason='null', indices=[], startTime=1635229854807, endTime=1635229855058, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-3/1V7dbEZTRViX6Xm6gpFPpw, state=SUCCESS, reason='null', indices=[], startTime=1635229854815, endTime=1635229855195, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-4/lTg7HDpoQu6Mjj5oezP-5A, state=SUCCESS, reason='null', indices=[], startTime=1635229854825, endTime=1635229855266, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-5/h6NqkmHdSeyh39M5RDnDAg, state=SUCCESS, reason='null', indices=[], startTime=1635229854834, endTime=1635229855336, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-6/ujKA23-5RlKYnsuR4voX-g, state=SUCCESS, reason='null', indices=[], startTime=1635229854844, endTime=1635229855406, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-7/RHoKZTc7RFqAWjPtVd7wuw, state=SUCCESS, reason='null', indices=[], startTime=1635229854853, endTime=1635229855475, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-8/c92IKJWrTTKErIjYIdpYDA, state=SUCCESS, reason='null', indices=[], startTime=1635229854862, endTime=1635229855554, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-9/_YPz1Pb4R2GFA3MAfmPlOA, state=SUCCESS, reason='null', indices=[], startTime=1635229854869, endTime=1635229855625, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-10/ci7dlrL4QhSRts6C9T0W-A, state=SUCCESS, reason='null', indices=[], startTime=1635229854877, endTime=1635229855698, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-r-6bpp__t_-ssrh7_____w-11/T8FYr2TuQOua6LA8ixbs1A, state=SUCCESS, reason='null', indices=[], startTime=1635229854886, endTime=1635229855774, totalShards=0, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-0/IN6wQLGIRhy1zYwuu-yQAQ, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856046, endTime=1635229856184, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-1/uax8pIsKQPy8faEh70tJCQ, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856073, endTime=1635229856275, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-2/nk49YuzDQtGzoGnK4J9DAg, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856084, endTime=1635229856370, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-3/-001QUBSQqiaOSG-OgsrAA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856096, endTime=1635229856464, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-4/AGpAmNKsShqJjmHuQ5ejsA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856106, endTime=1635229856548, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-5/WP1Lxs8eRsiFk0RNcr0imA, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856118, endTime=1635229856635, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-6/j3IqqtHkTmmX6g2hJDDhxg, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856127, endTime=1635229856706, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-7/Nxjbp5-VQCemmpCrUbAI4Q, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856137, endTime=1635229856787, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-8/iI6h0Db3TwSKxzj9Q9QdFw, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856145, endTime=1635229856868, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-9/4TJbSrfTTy-sKoE5dEyJig, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856156, endTime=1635229856960, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-erz9faaaqacfvjbq_____w-10/KFTwDVyYRFCx3urqyGd79Q, state=SUCCESS, reason='null', indices=[test-index-1], startTime=1635229856166, endTime=1635229857023, totalShards=1, successfulShards=1, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}, SnapshotInfo{snapshot=test-repo:snap-0/J_xiB2MJSzasDHffrckpHw, state=IN_PROGRESS, reason='null', indices=[test-index-1, test-index-2], startTime=1635229857294, endTime=0, totalShards=2, successfulShards=0, includeGlobalState=true, version=8.0.0, shardFailures=[], featureStates=[], indexSnapshotDetails={}}]>

  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.failNotEquals(Assert.java:834)
  at org.junit.Assert.assertEquals(Assert.java:118)
  at org.junit.Assert.assertEquals(Assert.java:144)
  at org.elasticsearch.http.snapshots.RestGetSnapshotsIT.assertStablePagination(RestGetSnapshotsIT.java:340)
  at org.elasticsearch.http.snapshots.RestGetSnapshotsIT.testSortAndPaginateWithInProgress(RestGetSnapshotsIT.java:179)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by arteam**
Start asserting snapshots in progress only in case when they reach
a stable state (the first index has finished, the second has been
blocked).

Fixes #79779
Relates #78507

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine 
run elasticsearch-ci/packaging-tests-windows-sample
run elasticsearch-ci/part-1

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/eql-correctness

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/eql-correctness

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/eql-correctness

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java [hunk 1]
```diff
@@ -176,7 +182,14 @@ public void testSortAndPaginateWithInProgress() throws Exception {
             inProgressSnapshots.add(AbstractSnapshotIntegTestCase.startFullSnapshot(logger, repoName, snapshotName, false));
         }
         AbstractSnapshotIntegTestCase.awaitNumberOfSnapshotsInProgress(logger, inProgressCount);
-
+        AbstractSnapshotIntegTestCase.awaitClusterState(
```
Comment (henningandersen) [inline qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:185]: Can you add a comment here on why we need to wait for this instead.

Also, in the PR description, you mention that this makes the sorting stable, can you elaborate on why that is as well?

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java [hunk 2]
```diff
@@ -46,10 +47,16 @@
 // TODO: dry up duplication across this suite and org.elasticsearch.snapshots.GetSnapshotsIT more
 public class RestGetSnapshotsIT extends AbstractSnapshotRestTestCase {
 
+    private static final Settings LARGE_SNAPSHOT_POOL_SETTINGS = Settings.builder()
+        .put("thread_pool.snapshot.core", 5)
+        .put("thread_pool.snapshot.max", 5)
```
Comment (henningandersen) [inline qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:52]: Can you add a comment on why this need to be raised?

Also, I think 2 would be enough, 1 to be blocked for `test-index-2` and one to ensure `test-index-1` completes?

**Review by henningandersen — COMMENTED** [review]
Left a couple of comments to ensure I understand the change correctly.

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 1 above)
Comment (arteam) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:185]: It's copied from https://github.com/elastic/elasticsearch/blob/master/test/framework/src/main/java/org/elasticsearch/snapshots/AbstractSnapshotIntegTestCase.java#L103.

The approach is used in other snapshots tests too, e.g. https://github.com/elastic/elasticsearch/blob/master/server/src/internalClusterTest/java/org/elasticsearch/snapshots/GetSnapshotsIT.java#L42

I can also copy the comment from there
```
Large snapshot pool settings to set up nodes for tests involving multiple repositories that need to have enough
threads so that blocking some threads on one repository doesn't block other repositories from doing work
```

The large pool makes sure that all the shards for `test-index-2` get blocked without blocking `test-index-1`. So we can just wait until `test-index-1` shards have been successfully snapshotted. After that the snapshot in progress reaches a stable state and we can check that the pagination works.

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java [hunk 3]
```diff
@@ -176,7 +177,14 @@ public void testSortAndPaginateWithInProgress() throws Exception {
             inProgressSnapshots.add(AbstractSnapshotIntegTestCase.startFullSnapshot(logger, repoName, snapshotName, false));
         }
         AbstractSnapshotIntegTestCase.awaitNumberOfSnapshotsInProgress(logger, inProgressCount);
-
+        AbstractSnapshotIntegTestCase.awaitClusterState(
+            logger,
+            state -> state.custom(SnapshotsInProgress.TYPE, SnapshotsInProgress.EMPTY)
+                .asStream()
+                .flatMap(s -> s.shards().stream())
+                .filter(e -> e.getKey().getIndexName().equals("test-index-1"))
```
Comment (original-brownbear) [inline qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:185]: `filter` and `allMatch` can be collapsed into just `allMatch`

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 1 above)
Comment (original-brownbear) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:180]: I'm not sure this is correct yet. We only wait for `test-index-1` to complete now, but how does that guarantee that `test-index-2` is actually blocked? I suppose in practice the timing works out that way, but it would be nice to have a cleaner and actually deterministic solution here as I can see this still failing albeit at a lower rate than before.

**Review by original-brownbear — CHANGES_REQUESTED** [review]
I don't think this is enough unfortunately, see inline comment.

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 3 above)
Comment (arteam) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:185]: Yeah, I can do 

```
e -> e.getKey().getIndexName().equals("test-index-1") == false
                        && e.getValue().state() == SnapshotsInProgress.ShardState.SUCCESS
```

like in `GetSnapshotsIT`

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 1 above)
Comment (arteam) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java]: @original-brownbear :+1: I've added a check on `test-index-2` to make sure that it's blocked on first shard in the `INIT` state with the rest being `QUEUED`

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 3 above)
Comment (arteam) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java]: Done!

**Comment by arteam** [comment]
@elasticmachine update branch

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 2 above)
Comment (henningandersen) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java]: I think you missed this comment?

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java [hunk 4]
```diff
@@ -50,6 +52,7 @@
     protected Settings nodeSettings(int nodeOrdinal, Settings otherSettings) {
         return Settings.builder()
             .put(super.nodeSettings(nodeOrdinal, otherSettings))
+            .put(LARGE_SNAPSHOT_POOL_SETTINGS)
```
Comment (henningandersen) [inline qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:55]: I'd prefer to just use a local settings object (class or inline) with the specific needs of this test (which I believe is 2?).

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java [hunk 5]
```diff
@@ -176,7 +178,24 @@ public void testSortAndPaginateWithInProgress() throws Exception {
...
+                        || e.getValue().state() == SnapshotsInProgress.ShardState.SUCCESS
+                );
+            List<SnapshotsInProgress.ShardState> secondIndexStates = state.custom(SnapshotsInProgress.TYPE, SnapshotsInProgress.EMPTY)
+                .asStream()
+                .flatMap(s -> s.shards().stream())
+                .filter(e -> e.getKey().getIndexName().equals("test-index-2"))
+                .map(e -> e.getValue().state())
+                .collect(Collectors.toList());
+            boolean secondIndexIsBlocked = secondIndexStates.stream().filter(e -> e == SnapshotsInProgress.ShardState.INIT).count() == 1
+                && secondIndexStates.stream().filter(e -> e == SnapshotsInProgress.ShardState.QUEUED == false).count() == 1;
```
Comment (henningandersen) [inline qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:196]: I think we should instead check that the number of queued states is `inProgressCount - 1`? That would be a bit clearer I think.

Perhaps we could use `Collectors.groupingBy` to group by status and check that we have 1 INIT, `inProgressCount - 1` QUEUED and nothing else?

**Review by henningandersen — COMMENTED** [review]
A couple of smaller points, otherwise this looks fine.

**Comment by arteam** [comment]
@elasticmachine update branch

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 2 above)
Comment (arteam) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java]: Sorry, I indeed missed it! I've moved `LARGE_SNAPSHOT_POOL_SETTINGS` to `RestGetSnapshotsIT`. I believe 2 is insufficient, the test hangs with 2 threads, but works with 3.

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 4 above)
Comment (arteam) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:55]: I've moved LARGE_SNAPSHOT_POOL_SETTINGS to RestGetSnapshotsIT. I believe 2 is insufficient, the test hangs with 2 threads, but works with 3.

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java [hunk 6]
```diff
@@ -176,7 +187,23 @@ public void testSortAndPaginateWithInProgress() throws Exception {
...
-
+        AbstractSnapshotIntegTestCase.awaitClusterState(logger, state -> {
+            boolean firstIndexSuccessfullySnapshot = state.custom(SnapshotsInProgress.TYPE, SnapshotsInProgress.EMPTY)
+                .asStream()
+                .flatMap(s -> s.shards().stream())
+                .allMatch(
+                    e -> e.getKey().getIndexName().equals("test-index-1") == false
+                        || e.getValue().state() == SnapshotsInProgress.ShardState.SUCCESS
+                );
+            boolean secondIndexIsBlocked = state.custom(SnapshotsInProgress.TYPE, SnapshotsInProgress.EMPTY)
```
Comment (original-brownbear) [inline qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:198]: We shouldn't need this second check. If we make sure that all snapshots for index-1 are successful, then that should be the end state of things. The state of snapshots for the second index should be initialized to exactly what we're asserting here right away I think?

**Review by original-brownbear — COMMENTED** [review]
I think the CS wait check can be simplified some more, other than that looks alright.

**Comment by arteam** [comment]
@elasticmachine update branch

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 6 above)
Comment (arteam) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:198]: https://github.com/elastic/elasticsearch/pull/80530#discussion_r758346965

@original-brownbear That was the original implementation (with only the `test-index-1` check) and you suggested to add an addition check for the second index :smiley:

Comment (arteam) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:198]: I don't have a strong feeling towards this one way or another (the test passes on 100 iterations both with `secondIndexIsBlocked` check and without it).

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/eql-correctness

**Comment by arteam** [comment]
@elasticmachine update

File: qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java (hunk 6 above)
Comment (original-brownbear) [reply qa/smoke-test-http/src/test/java/org/elasticsearch/http/snapshots/RestGetSnapshotsIT.java:198]: Right, now I remember :) Sorry about that.

**Review by original-brownbear — APPROVED** [review]
LGTM, sorry for the delay here

**Comment by arteam** [comment]
Thanks @original-brownbear!
