### PR TITLE
Fix request processing scheduling

### LINKED ISSUE #127168: [CI] DataNodeRequestSenderTests testRetryOnlyMovedShards failing
**Build Scans:**
- [elasticsearch-intake #22167 / part3](https://gradle-enterprise.elastic.co/s/b6cooz3t5auei)
- [elasticsearch-intake #22154 / part3](https://gradle-enterprise.elastic.co/s/vuzq2a7uelums)
- [elasticsearch-pull-request #68269 / part-3](https://gradle-enterprise.elastic.co/s/x4x5if72u4lqk)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.plugin.DataNodeRequestSenderTests.testRetryOnlyMovedShards" -Dtests.seed=954153CA6297C084 -Dtests.locale=nl-SR -Dtests.timezone=EET -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.plugin.DataNodeRequestSenderTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRetryOnlyMovedShards),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: safeGet: listener was completed exceptionally
```

**Issue Reasons:**
- [main] 3 failures in test testRetryOnlyMovedShards (7.7% fail rate in 39 executions)
- [main] 2 failures in step part3 (16.7% fail rate in 12 executions)
- [main] 2 failures in pipeline elasticsearch-intake (16.7% fail rate in 12 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by idegtiarenko**
This change fix concurrency around handling moved shards.

The test was failing as the shard failures were visible before retry was processed. In order to fix it the error handling is updated to:
* schedule retries before recording shard failures
* block request sending as soon as moved shard is detected (before the sending was locked only when we accumulated the list of shards and started resolving their new location).

Closes: #127168

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 1]
```diff
@@ -265,9 +265,8 @@ void onAfter(DriverCompletionInfo info) {
                     concurrentRequests.release();
                 }
 
-                if (pendingRetries.isEmpty() == false && remainingUnavailableShardResolutionAttempts.decrementAndGet() >= 0) {
+                if (sendingLock.isHeldByCurrentThread()) {
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:268]: I think `isHeldByCurrentThread` should be used for assertions or debugging purposes, not in production code.

Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:268]: Agree. let me find a way to replace it.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java [hunk 2]
```diff
@@ -322,7 +321,13 @@ private void maybeScheduleRetry(ShardId shardId, boolean receivedData, Exception
                 if (receivedData == false
                     && targetShards.getShard(shardId).remainingNodes.isEmpty()
                     && unwrapFailure(shardId, e) instanceof NoShardAvailableActionException) {
-                    pendingRetries.add(shardId);
+                    if (pendingRetries == null && remainingUnavailableShardResolutionAttempts.decrementAndGet() >= 0) {
+                        pendingRetries = new HashSet<>();
+                        sendingLock.lock();
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:326]: I am concerned that we are scattering sendingLock#lock and sendingLock#unlock in two different places. Can we  keep them close?

Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:326]: I am not following. They are in the same inner listener, guarding the same structure.

Comment (dnhatn) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:326]: @idegtiarenko Sorry, I should have provided more detail. My concern is that we acquire the sending lock in `maybeScheduleRetry` and release it in `onAfter`, which is linked to the status of `pendingRetries`. While the implementation is technically correct, I think we should stick to the simplest lock pattern unless there is a strong reason to do otherwise:

```
lock/tryLock
try {
  ...
} finally {
  unlock
}
```

I think we can follow this lock pattern in the DataNodeRequestSender class.

Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java:326]: This sounds a lot like the original implementation (within `onAfter`) that was not correct.
Do you see a way how to implement this suggestion while still locking conditionally (only if shard movement is detected) and blocking concurrent requests while it is detected that new shard location resolution is required?

Comment (idegtiarenko) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeRequestSender.java]: As discussed yesterday, I moved retry scheduling to `trySendingRequestsForPendingShards` in https://github.com/elastic/elasticsearch/pull/127464/commits/8a0dcc6a08aa84c2d91923786a4b73c2f20bd9fd

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @idegtiarenko
