### PR TITLE
Larger offset when calculating the next histogram bucket to avoid col…

### LINKED ISSUE #139382: [CI] DownsampleIT testAggregateMethod failing
**Build Scans:**
- [elasticsearch-intake #32242 / part2](https://gradle-enterprise.elastic.co/s/w672exmkwmrs4)
- [elasticsearch-pull-request #109257 / part-2](https://gradle-enterprise.elastic.co/s/fpgm2naysjtl2)
- [elasticsearch-pull-request #108346 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/dhq4sjszarpzq)
- [elasticsearch-pull-request #108275 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/krebgobd45xos)
- [elasticsearch-pull-request #108263 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/yvq7kfzxxn3my)
- [elasticsearch-pull-request #108244 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/wiro5rajtbbjg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:downsample:internalClusterTest" --tests "org.elasticsearch.xpack.downsample.DownsampleIT.testAggregateMethod" -Dtests.seed=DA6CF6555B348C1 -Dtests.locale=agq -Dtests.timezone=America/Thunder_Bay -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.downsample.DownsampleIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAggregateMethod'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.ElasticsearchException: downsample task [downsample-downsample-5m-.ds-metrics-foo-2025.12.11-000001-0-5m] failed
```

**Issue Reasons:**
- [main] 6 failures in test testAggregateMethod (0.7% fail rate in 907 executions)
- [main] 4 failures in step checkpart2_release-tests (40.0% fail rate in 10 executions)
- [main] 5 failures in pipeline elasticsearch-pull-request (0.9% fail rate in 588 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by gmarouli**
We generate legacy histograms in `DownsampleIT` and we used to small of a delta when generating the histogram values which caused them to collide. We ensure that the delta between the buckets is more than 1.0 fix that.

Fixes  #139382

### CODE REVIEW

File: x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/DownsampleIT.java [hunk 1]
```diff
@@ -646,7 +646,7 @@ private static double[] randomHistogramValues(int size) {
         final double[] array = new double[size];
         double minHistogramValue = randomDoubleBetween(0.0, 0.1, true);
         for (int i = 0; i < array.length; i++) {
-            array[i] = minHistogramValue += randomDoubleBetween(0.0, 0.5, true);
+            array[i] = minHistogramValue += randomDoubleBetween(1.0, 10.0, true);
```
Comment (kkrik-es) [inline x-pack/plugin/downsample/src/internalClusterTest/java/org/elasticsearch/xpack/downsample/DownsampleIT.java]: 0.1 - 10.0?

**Review by kkrik-es — APPROVED** [review]

**Comment by gmarouli** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/139737)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
