### PR TITLE
Don't omit empty arrays when filtering _source

### LINKED ISSUE #23796: source filtering on nested properties no longer returning empty[] when no nested documents.
**Elasticsearch version**: 5.2.2

**Plugins installed**: none

**JVM version**: 1.8.0_111

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:
Just ungraded from 5.0.1 and now hitting this issue.
When a document contains no nested documents in its array property and we use source filtering to exclude any nested document property, the result is missing the entire nested documents empty array property.

**Steps to reproduce**:
 1. Create document with nested document array property
 ```
{
  "mydocument": {
    "properties": {
      "mynesteddocuments": {
        "type": "nested"
      }
    }
  }
}
```
 2. Add couple of documents, 1 of which should have empty array of nesteddocuments
```
{
  "strprop": "document string property",
  "boolprop": true,
  "intprop": 54321,
  "mynesteddocuments": []
}
```
 3. Search for the documents with source filtering to exclude say the "intprop" property.
```
{
  "_source": {
    "excludes": [
      "mynesteddocuments.intprop"
    ]
  },
  "query": {
    "match_all": {}
  }
}
```
  4. For documents with nesteddocuments it correctly excludes the "intprop" but for the documents with empty nested documents array... this property is completely missing.
Previously it always returned an empty [] which we relied on in code and it would be painful to have to introduce checks for nulls now.

Believe it may be somewhat related to #22557 and #22593

### PR DESCRIPTION
**Pull request by javanna**
When using source filtering exclusions, empty arrays are not preserved in documents, and no empty arrays are returned if arrays are empty after applying exclusions. What I find surprising is that we have special treatment to make sure that we preserve empty objects, but the behaviour for arrays is different.

```
PUT /test/_doc/1
{
  "field" : "value",
  "array": [],
  "object" : {}
}

PUT /test/_doc/2
{
  "field" : "value",
  "array": [{ "exclude": "bar"}],
  "object": { "exclude": "bar" }
}

PUT /test/_doc/3
{
  "field" : "value",
  "array": [{ "exclude": "bar"}, {"include" : "bar"}],
  "object": { "exclude": "bar", "include" : "bar" }
}

POST /test/_search?pretty
{
  "_source": {
    "excludes": [
      "array.exclude", "object.exclude"
    ]
  }
}

"hits" : [
      {
        "_index" : "test",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "field" : "value",
          "object" : { }
        }
      },
      {
        "_index" : "test",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "field" : "value",
          "object" : { }
        }
      },
      {
        "_index" : "test",
        "_id" : "3",
        "_score" : 1.0,
        "_source" : {
          "field" : "value",
          "array" : [
            {
              "include" : "bar"
            }
          ],
          "object" : {
            "include" : "bar"
          }
        }
      }
]
```

It looks like this regression was introduced by #22593, shortly after we refactored source filtering to use automata (#20736).

Note that this affects what the search API returns when using source exclusions, as well as what gets indexed when using source exclusions for the `_source` field.

Closes #23796

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

I am in favor of backporting the fix to 7.x. What do you think @jpountz @jtibshirani ?

**Comment by jpountz** [comment]
+1 to backport, this looks like a bugfix to me, not an enhancement.

**Comment by javanna** [comment]
run elasticsearch-ci/2

**Comment by javanna** [comment]
would we consider backporting to 7.8 / 7.7 ?

File: server/src/test/java/org/elasticsearch/common/xcontent/support/AbstractFilteringTestCase.java [hunk 1]
```diff
@@ -484,70 +484,70 @@ public void testSimpleArrayOfObjectsInclusive() throws Exception {
         testFilter(expected, SAMPLE, singleton("authors.*name"), emptySet());
     }
 
-    public void testSimpleArrayOfObjectsExclusive() throws Exception {
-        final Builder expected = builder -> builder.startObject()
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/common/xcontent/support/AbstractFilteringTestCase.java:488]: I have not changed anything in the json, only made it a protected static member.

File: server/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java [hunk 2]
```diff
@@ -479,6 +482,79 @@ public void testSharedPrefixes() {
         assertEquals(Collections.singletonMap("foobaz", 3), XContentMapValues.filter(map, new String[0], new String[] {"foobar"}));
     }
 
+    @Override
+    public void testSimpleArrayOfObjectsExclusive() throws Exception {
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java:486]: I guess our map-based filtering will now behave differently than direct xContent filtering. This seems okay to me, since I think it already diverged -- map-based filtering preserves empty objects, whereas xContent filtering doesn't?

**Review by jtibshirani — APPROVED** [review]
Looks good to me too. I also think we should backport, as it was a regression (albeit a long-standing one).

File: server/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java (hunk 2 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/common/xcontent/support/XContentMapValuesTests.java:486]: yes, preserving empty objects was until now the main difference between the two way of filtering, and with this change we also preserve empty arrays.

**Comment by jtibshirani** [comment]
> would we consider backporting to 7.8 / 7.7 ?

To me we should skip backporting to 7.7, since it's already been released. It's very possible users will have to adapt their code (especially if they've implemented a workaround), and it seems best to avoid this in a patch release.

**Comment by somdevmehta** [comment]
While this seems to be fixed in version 7.9.0. I am wondering if there is a similar change planned for **inclusions** as well.
Consider the following scenario.


`POST /test/_doc/1
{
  "field" : "value",
  "array": [],
  "object" : {}
}

POST /test/_doc/2
{
  "field" : "value",
  "array": [{ "exclude": "bar"}],
  "object": { "exclude": "bar" }
}

POST /test/_doc/3
{
  "field" : "value",
  "array": [{ "exclude": "bar"}, {"include" : "bar"}],
  "object": { "exclude": "bar", "include" : "bar" }
}

POST /test/_search?pretty
{
	"_source": {"includes": ["name","object.include","array.include"] }
}

{
  "hits": [
    {
      "_index": "test",
      "_type": "_doc",
      "_id": "82HEBnQBxtHMu64O7lFB",
      "_score": 1,
      "_source": {}
    },
    {
      "_index": "test",
      "_type": "_doc",
      "_id": "9GHFBnQBxtHMu64OElFU",
      "_score": 1,
      "_source": {}
    },
    {
      "_index": "test",
      "_type": "_doc",
      "_id": "9WHFBnQBxtHMu64ONFGE",
      "_score": 1,
      "_source": {
        "array": [
          {
            "include": "bar"
          }
        ],
        "object": {
          "include": "bar"
        }
      }
    }
  ]
}
`
Shouldn't the first 2 results include empty Arrays/Objects as well ? Not including them creates a bigger problem for nested scenario as shown below,

`
PUT /test1
{
  "mappings": {
    "properties": {
      "product": { "type": "text" },
      "Users": {
        "type": "nested",
        "properties": {
          "name": { "type": "text" },
          "Address": {
            "type": "nested",
            "properties": {
              "country": { "type": "text" }
            }
          }
        }
      }
    }
  }
}

POST /test1/_doc/1
{
  "product": "Laptop",
  "Users": [
    { "name": "user1", "Address": [{ "country": "country1" }] },
    { "name": "user2", "Address": [] },
    { "name": "user3", "Address": [{ "country": "country2" }] },
    { "name": "user4", "Address": [{ "country": "country3" }] }
  ]
}

POST /test1/_doc/_search
{
  "query": {
    "nested": {
      "path": "Users.Address",
      "inner_hits":{},
      "query": {
		"match" :{ "Users.Address.country": "country2"}
      }
    }
  },
  "_source": ["Users.Address.country"]
}

"hits": {
        "total": {
            "value": 1,
            "relation": "eq"
        },
        "max_score": 0.9808291,
        "hits": [
            {
                "_index": "test1",
                "_type": "_doc",
                "_id": "1",
                "_score": 0.9808291,
                "_source": {
                    "Users": [
                        {
                            "Address": [
                                {
                                    "country": "country1"
                                }
                            ]
                        },
                        {
                            "Address": [
                                {
                                    "country": "country2"
                                }
                            ]
                        },
                        {
                            "Address": [
                                {
                                    "country": "country3"
                                }
                            ]
                        }
                    ]
                },
                "inner_hits": {
                    "Users.Address": {
                        "hits": {
                            "total": {
                                "value": 1,
                                "relation": "eq"
                            },
                            "max_score": 0.9808291,
                            "hits": [
                                {
                                    "_index": "test1",
                                    "_type": "_doc",
                                    "_id": "1",
                                    "_nested": {
                                        "field": "Users",
                                        "offset": 2,
                                        "_nested": {
                                            "field": "Address",
                                            "offset": 0
                                        }
                                    },
                                    "_score": 0.9808291,
                                    "_source": {
                                        "country": "country2"
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        ]
    }
`
In above response Innher_hits is giving  Users[2].Address[0] as a match for condition country= "country2". However, in the _source object Users[2] appears at index 1 of Users Array. This creates reliability concerns for offset attribute. For elastic-search versions prior to 5.X, we used to get empty [] if no nested attribute was found and offsets could be reliably used to pull data for m_source object.
