### PR TITLE
[Test] Fix MigrationDocumentationIT.testClusterHealth

### LINKED ISSUE #27754: [CI] MigrationDocumentationIT#testClusterHealth failed
This test has been failed recently but I could not reproduce it locally.

```
 gradle :client:rest-high-level:integTestRunner \
  -Dtests.seed=A72A1EF88C187DAB \
  -Dtests.class=org.elasticsearch.client.documentation.MigrationDocumentationIT \
  -Dtests.method="testClusterHealth" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:+AggressiveOpts" \
  -Dtests.locale=fr \
  -Dtests.timezone=Europe/Isle_of_Man
```

Some instances:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/526/console

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/406/console

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/525/console

Log: [testClusterHealth.txt](https://github.com/elastic/elasticsearch/files/1548097/testClusterHealth.txt)

### PR DESCRIPTION
**Pull request by tlrx**
Closes #27754

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine retest this please

**Review by dnhatn — APPROVED** [review]
LGTM. @javanna Would you mind taking an extra look? Thank you.

**Comment by tlrx** [comment]
Thanks @dnhatn ! Since it causes an annoying test failure and the changes are quite light I just merged it. We can improve or adapt later if @javanna has some comments.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/MigrationDocumentationIT.java [hunk 1]
```diff
@@ -155,6 +151,14 @@ public void onFailure(Exception e) {
                 }
             });
             //end::migration-request-async-execution
+            assertBusy(() -> assertFalse(client.exists(new GetRequest("index", "doc", "id"))));
```
Comment (javanna) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/MigrationDocumentationIT.java]: was this another problem? I wonder why this assertBusy is needed.

Comment (tlrx) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/MigrationDocumentationIT.java]: Yes, previously the last code snippet was an async deletion and the test sometimes fails (or warn a thread leak) because of ongoing operation when shutting down the cluster. 

I swapped the async and syn deletion operation so that the async is executed first, and this assertBusy is here to wait for the async operation to finish. A CountDownLatch would have been better but since this is a documentation code snippet I didn't want the latch to appear in doc so I did it this way.

Comment (javanna) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/MigrationDocumentationIT.java]: I understand, that makes sense. Maybe add a tiny comment on why the assertBusy is there (the wait could be elsewhere but that would also appear in the docs snippet which is not good)
