### PR TITLE
Get repository metadata from the cluster state doesn't throw an exception if a repo is missing

### LINKED ISSUE #92849: SLM retention fails if there are multiple policies using different repositories and one respository does not exist
### Elasticsearch Version

7.x and 8.x

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

All

### Problem Description

We retrieve all snapshots for all repositories at once, however, if we fail to retrieve them, we consider the SLM task as failed entirely, even though we might have been able to get snapshots individually. We should probably do a pre-check for the repository existence in the cluster state and then filter any missing repositories out when we retrieve snapshots for SLM retention execution.

### Steps to Reproduce

Run ES with `./gradlew run -Dtests.es.path.repo=/tmp`, then:

```
PUT /_cluster/settings
{
  "transient": {
    "logger.org.elasticsearch.xpack.slm":"TRACE"
  }
}

PUT /_snapshot/repo
{
  "type": "fs",
  "settings": {
    "location": "/tmp/foo"
  }
}

PUT /_snapshot/missing
{
  "type": "fs",
  "settings": {
    "location": "/tmp/foo2"
  }
}

PUT /_slm/policy/daily-snapshots
{
  "schedule": "0 30 1 * * ?",
  "name": "<daily-snap-{now/d}>",
  "repository": "repo",
  "config": {
    "ignore_unavailable": false,
    "include_global_state": false
  },
  "retention": {
    "expire_after": "1s"
  }
}

PUT /_slm/policy/daily-snapshots2
{
  "schedule": "0 30 1 * * ?",
  "name": "<daily-snap-{now/d}>",
  "repository": "missing",
  "config": {
    "ignore_unavailable": false,
    "include_global_state": false
  },
  "retention": {
    "expire_after": "1s"
  }
}

DELETE /_snapshot/missing

GET /_slm/policy

PUT /_slm/policy/daily-snapshots/_execute

POST /_slm/_execute_retention
```

### Logs (if relevant)

The failure in the logs will look like:

```
[2023-01-11T13:47:27,594][INFO ][o.e.x.s.a.TransportExecuteSnapshotRetentionAction] [runTask-0] manually triggering SLM snapshot retention
[2023-01-11T13:47:27,595][INFO ][o.e.x.s.SnapshotRetentionTask] [runTask-0] starting SLM retention snapshot cleanup task
[2023-01-11T13:47:27,596][TRACE][o.e.x.s.SnapshotRetentionTask] [runTask-0] policies with retention enabled: [daily-snapshots, daily-snapshots2]
[2023-01-11T13:47:27,596][TRACE][o.e.x.s.SnapshotRetentionTask] [runTask-0] fetching snapshots from repositories: [repo, missing]
[2023-01-11T13:47:27,599][DEBUG][o.e.x.s.SnapshotRetentionTask] [runTask-0] unable to retrieve snapshots for [[repo, missing]] repositories org.elasticsearch.repositories.RepositoryMissingException: [missing] missing
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.repositories.get.TransportGetRepositoriesAction.getRepositories(TransportGetRepositoriesAction.java:105)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:116)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:67)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:124)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:235)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:72)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:958)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[2023-01-11T13:47:27,603][ERROR][o.e.x.s.SnapshotRetentionTask] [runTask-0] error during snapshot retention task org.elasticsearch.repositories.RepositoryMissingException: [missing] missing
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.repositories.get.TransportGetRepositoriesAction.getRepositories(TransportGetRepositoriesAction.java:105)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:116)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:67)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.support.master.TransportMasterNodeAction.executeMasterOperation(TransportMasterNodeAction.java:124)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.lambda$doStart$3(TransportMasterNodeAction.java:235)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.action.ActionRunnable$3.doRun(ActionRunnable.java:72)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:958)
	at org.elasticsearch.server@8.7.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by gmarouli**
### Expected situation
When retrieving snapshots by giving the names of multiple repositories, if a repository is missing we would like to retrieve the snapshots of the repositories that were found and report the other repositories as failures.

### The bug
The bug was witnessed during the execution of SLM policies of which one referred to a missing repository. See #92849.

### How we fixed it
In this PR we propose to change the function of `org.elasticsearch.action.admin.cluster.repositories.get.TransportGetRepositoriesAction#getRepositories` to return the found repositories and the missing ones instead of throwing an exception when it encounters a missing repository.

Based on this change we adjusted the logic in the following places:
- The `GetRepositoriesAction` now mentions in the exception all the missing repositories. For example:
```
{
  "error": {
    "root_cause": [
      {
        "type": "repository_missing_exception",
        "reason": "[missing_1, missing_2] missing"
      }
    ],
    "type": "repository_missing_exception",
    "reason": "[missing_1, missing_2] missing"
  },
  "status": 404
}
```
Instead of only one.
- The `SnapshotRetentionTask` will now receive the snapshots from the repositories that can be retrieved and it will log in the debug level the missing repos.

Fixes: #92849

### CODE REVIEW

**Comment by gmarouli** [comment]
@elasticmachine elasticsearch-ci/part-1

**Comment by dakrone** [comment]
Since this is currently mainly touching the snapshots side of things, I think someone on the distributed team should take a look (they own snapshots). I do think though that we should be defensive on the SLM side and elide the missing repos from the fetching action, we can use the same check we use in `SnapshotLifecycleService.validateRepositoryExists`. What do you think Mary?

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
I see your point. For me it's not that clear which one is best. I think it depends how we define `TransportGetRepositoriesAction#getRepositories`. I see (at least) two options:

A] Redefine it to `TransportGetRepositoriesAction#getRepositoriesMetadata`, then it would make sense to return the metadata and the repositories it wasn't able to retrieve and let the caller decide how to act with that information. The benefits of this path, I think is that we are able to give to the caller a more complete response. For example, now we can inform the user exactly which repositories do not exist instead of reporting only the first one. As an API user I do appreciate when I get all the info so I can fix my request in one go, that's the benefit of this approach I think.

B] The `TransportGetRepositoriesAction#getRepositories` expects that all the repositories must exist and if any of them doesn't it throws an exception, just like it works now. Then I completely agree, we can use `SnapshotLifecycleService.validateRepositoryExists` to filter out the non existing paths and only fetch those. It's a simpler change with a shorter scope.

I think it depends on how we want to define the scope of `TransportGetRepositoriesAction#getRepositories`. @elastic/es-distributed do you think there is value in implementing `A` or should do I just revert `TransportGetRepositoriesAction#getRepositories` and filter the repos in SLM side?

**Comment by DaveCTurner** [comment]
I think option A (as implemented here) is the right approach. When we extended the get-snapshots action to work across repositories we designed it to report failures on a repository-by-repository basis. "Does not exist" is just another per-repository failure, but it's one that was missed in the implementation because it happens much earlier in the process than the other kinds of failure.

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/GetSnapshotsIT.java [hunk 1]
```diff
@@ -578,6 +581,26 @@ public void testSortAfter() throws Exception {
         assertThat(paginatedResponse2.totalCount(), is(3));
     }
 
+    public void testRetrievingSnapshotsWhenRepositoryIsMissing() throws Exception {
+        final String repoName = "test-repo";
+        final Path repoPath = randomRepoPath();
+        createRepository(repoName, "fs", repoPath);
+        final String missingRepoName = "missing";
+        createRepository(missingRepoName, "fs");
```
Comment (DaveCTurner) [inline server/src/internalClusterTest/java/org/elasticsearch/snapshots/GetSnapshotsIT.java:589]: Do we need to even create this repo only to delete it later? I would expect the test to work without that.

**Review by DaveCTurner — APPROVED** [review]
LGTM (one nit)

File: server/src/internalClusterTest/java/org/elasticsearch/snapshots/GetSnapshotsIT.java (hunk 1 above)
Comment (gmarouli) [reply server/src/internalClusterTest/java/org/elasticsearch/snapshots/GetSnapshotsIT.java:589]: Not really, I had the SLM issue reproduction path in mind, which is not necessary here :). I will clean it up.

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@dakrone Given that the `TransportGetRepositoriesAction#getRepositories` is returning a complete response with the repository metadata of the found repos and the missing repos. Do you agree that we can keep SLM as it is? I think it's not unreasonable to expect `getRepositories` to do the filtering of the existing and non existing repos. It feels a bit of double work to have SLM check that first and the request them.

**Comment by dakrone** [comment]
Thanks for following up on this Mary, I'm happy to leave this on the snapshot side. As something so we don't hit the bug again (perhaps in a different place), could you add an integration test that has two SLM policies, where the repository for one of the policies doesn't exist, and then run retention and ensure that snapshots are deleted from the repository that does exist? I don't mind if we want to add it either here or in a subsequent PR (up to you).

**Comment by gmarouli** [comment]
Theoretically, it should be an easy test to write (famous last words). If that is indeed the case I would prefer to wrap it up here ;). I will give it a try.

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java [hunk 2]
```diff
@@ -591,6 +591,96 @@ public void testSLMXpackUsage() throws Exception {
...
+        // Run retention every second
+        ClusterUpdateSettingsRequest req = new ClusterUpdateSettingsRequest();
+        req.persistentSettings(Settings.builder().put(LifecycleSettings.SLM_RETENTION_SCHEDULE, "*/1 * * * * ?"));
+        try (XContentBuilder builder = jsonBuilder()) {
+            req.toXContent(builder, ToXContent.EMPTY_PARAMS);
+            Request r = new Request("PUT", "/_cluster/settings");
+            r.setJsonEntity(Strings.toString(builder));
+            Response updateSettingsResp = client().performRequest(r);
+            assertAcked(updateSettingsResp);
+        }
```
Comment (dakrone) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java:657]: Rather than run retention every second, you could manually invoke the retention (we have the execute retention API)

**Review by dakrone — APPROVED** [review]
LGTM, I left one really minor comment, thanks for adding the test Mary!

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java (hunk 2 above)
Comment (gmarouli) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/slm/SnapshotLifecycleRestIT.java:657]: I was doubting about this, but in second thought it will be better and more efficient. I will change it :)

**Comment by gmarouli** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.6|[](https://github.com/elastic/elasticsearch/pull/93105)|
|❌|7.17|Conflict resolution was aborted by the user|

### Manual backport
To create the backport manually run:
```
backport --pr 92914
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by gmarouli** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.6|[](https://github.com/elastic/elasticsearch/pull/93106)|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/93108)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)
