### PR TITLE
Query parsers to throw exception when multiple field names are provided

### LINKED ISSUE #19547: Multiple fields provided to queries return results for the last one only
**Elasticsearch version**: 2.3.4

**JVM version**: 1.8

**OS version**: OSX 10.11

**Description of the problem including expected versus actual behavior**:

There is a possibility to provide multiple fields to queries like so:

```json
{
  "query": {
    "range": {
      "age": {
        "gte": 30,
        "lte": 40
      },
      "price": {
        "gte": 10,
        "lte": 30
      }
    }
  }
}
```

Here I provide two fields to a single query and elasticsearch provides legitimate results for such a query. However, the results returned always only include hits from the last field request, that is, if I were to execute the query given above, I would only get results from the `price` field. Moreover I could not find any mentions of such behaviour in the official docs. 
Analogous behaviour was observed with `prefix`, `regexp`, `geo_distance` queries and more.
Logically this should either provide the hits for both provided fields or not work at all.

### PR DESCRIPTION
**Pull request by javanna**
Most of our queries support a single field name, the field that gets queried. That is the key of the object which contains the query options. For such queries, in case multiple fields are presented, in most of the cases the query goes through and either the last or the first field only will be read and queried.

This PR changes the behaviour of all those parsers to throw exception in case multiple field names are provided.

Closes #19547

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/index/query/CommonTermsQueryBuilder.java [hunk 1]
```diff
@@ -280,78 +277,79 @@ protected void doXContent(XContentBuilder builder, Params params) throws IOExcep
...
-                throw new ParsingException(parser.getTokenLocation(),
-                        "[common] query parsed in simplified form, with direct field name, but included more options than just " +
-                                "the field name, possibly use its 'options' form, with 'query' element?");
+            } else {
+                fieldName = parser.currentName();
+                text = parser.objectText();
             }
         }
 
-        if (text == null) {
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/CommonTermsQueryBuilder.java]: I removed this of checks at the end of parsing as they are not needed. The query builder throws error anyways as we validate its input and we also test that in our tests.

File: core/src/main/java/org/elasticsearch/index/query/FuzzyQueryBuilder.java [hunk 2]
```diff
@@ -258,63 +258,60 @@ protected void doXContent(XContentBuilder builder, Params params) throws IOExcep
 
     public static Optional<FuzzyQueryBuilder> fromXContent(QueryParseContext parseContext) throws IOException {
         XContentParser parser = parseContext.parser();
-
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/FuzzyQueryBuilder.java]: this type of change is mechanical and the same for some of the parsers that didn't loop till the END_OBJECT. That would cause the query to not be completely read in case multiple fields are presented. That would be caught by the new check I am introducing in QueryParseContext#parseInnerQueryBuilder, but I think it is better to change the way we parse those queries to exhaust their own object at all times.

File: core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java [hunk 3]
```diff
@@ -115,10 +115,11 @@ public QueryBuilder parseTopLevelQueryBuilder() {
         @SuppressWarnings("unchecked")
         Optional<QueryBuilder> result = (Optional<QueryBuilder>) indicesQueriesRegistry.lookup(queryName, parseFieldMatcher,
                 parser.getTokenLocation()).fromXContent(this);
-        if (parser.currentToken() == XContentParser.Token.END_OBJECT) {
-            // if we are at END_OBJECT, move to the next one...
-            parser.nextToken();
+        if (parser.currentToken() != XContentParser.Token.END_OBJECT) {
+            throw new ParsingException(parser.getTokenLocation(),
+                    "[" + queryName + "] malformed query, expected [END_OBJECT] but found [" + parser.currentToken() + "]");
```
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java]: this new check is just best effort, but should help finding out when parsers don't properly exhaust their own object. I don't think the previous leniency was needed.

File: core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java [hunk 4]
```diff
@@ -115,10 +115,11 @@ public QueryBuilder parseTopLevelQueryBuilder() {
...
         }
+        parser.nextToken();
```
Comment (jpountz) [inline core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java]: should we check the return value?

File: core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryBuilderTests.java [hunk 5]
```diff
@@ -173,4 +190,24 @@ public void testCommonTermsQuery4() throws IOException {
...
+                "    }\n" +
+                "  }\n" +
+                "}";
+
+        try {
+            parseQuery(json);
+            fail("parseQuery should have failed");
+        } catch(ParsingException e) {
+            assertEquals("[common] query doesn't support multiple fields, found [message1] and [message2]", e.getMessage());
+        }
```
Comment (jpountz) [inline core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryBuilderTests.java]: I tend to like expectThrows better for doing this.

**Comment by jpountz** [comment]
I left some comments, this looks great!

File: core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryBuilderTests.java (hunk 5 above)
Comment (javanna) [inline core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryBuilderTests.java]: yea that is what most people do, but I really like checking the error message too, which I don't think is possible with expectThrows is it?

File: core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java (hunk 4 above)
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java]: I am not sure we can make assumption about what it is. what could it be? another start object, end object...not sure what else...

File: core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryBuilderTests.java (hunk 5 above)
Comment (tlrx) [inline core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryBuilderTests.java]: Exception e = expectThrows(Exception.class, () -> doSomething());
assertEquals(e.getMessage(), containsString("bla"));

Comment (javanna) [inline core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryBuilderTests.java]: oh... now I feel silly :) thanks @tlrx  !!!

File: core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java (hunk 4 above)
Comment (tlrx) [inline core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java]: Yes, I'm not sure either if we can make any assumption here

File: core/src/main/java/org/elasticsearch/index/query/MatchQueryBuilder.java [hunk 6]
```diff
@@ -533,80 +527,84 @@ public String getWriteableName() {
...
+            if (token == XContentParser.Token.FIELD_NAME) {
+                currentFieldName = parser.currentName();
+            } else if (parseContext.isDeprecatedSetting(currentFieldName)) {
+                // skip
+            } else if (token == XContentParser.Token.START_OBJECT) {
+                if (fieldName != null) {
+                    throw new ParsingException(parser.getTokenLocation(), "[match] query doesn't support multiple fields, found ["
+                            + fieldName + "] and [" + currentFieldName + "]");
+                }
+                fieldName = currentFieldName;
```
Comment (tlrx) [inline core/src/main/java/org/elasticsearch/index/query/MatchQueryBuilder.java]: Match query is tricky because it can be written as:
```
{
  "match" : 
    "message1" : {
       "query" : "this is a test"
   }
}
```

but also:
```
{
  "match" : 
    "message1" : "this is a test"
}
```

and in case of multiple fields we just catch the first form, not the second which is very used too.

File: core/src/main/java/org/elasticsearch/index/query/MatchPhrasePrefixQueryBuilder.java [hunk 7]
```diff
@@ -192,62 +192,55 @@ protected int doHashCode() {
...
+            if (token == XContentParser.Token.FIELD_NAME) {
+                currentFieldName = parser.currentName();
+            } else if (parseContext.isDeprecatedSetting(currentFieldName)) {
+                // skip
+            } else if (token == XContentParser.Token.START_OBJECT) {
+                if (fieldName != null) {
+                    throw new ParsingException(parser.getTokenLocation(), "[match_phrase_prefix] query doesn't support multiple " +
+                            "fields, found [" + fieldName + "] and [" + currentFieldName + "]");
+                }
+                fieldName = currentFieldName;
```
Comment (tlrx) [inline core/src/main/java/org/elasticsearch/index/query/MatchPhrasePrefixQueryBuilder.java]: Same comment as for `match`

**Comment by tlrx** [comment]
It's a nice change, thanks for doing that. I left comments concerning the queries that can be written differently like `match*` queries. I don't know if we can handle every format here but that would be great.

File: core/src/main/java/org/elasticsearch/index/query/MatchQueryBuilder.java (hunk 6 above)
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/MatchQueryBuilder.java]: many queries actually have a short syntax like the match one. I'm afraid what you bring up is a problem that's common to them all. I will dig.

Comment (tlrx) [inline core/src/main/java/org/elasticsearch/index/query/MatchQueryBuilder.java]: Yes, I know, sorry for that :(

File: core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryBuilderTests.java (hunk 5 above)
Comment (javanna) [inline core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryBuilderTests.java]: I pushed a commit that introduces using expectThrows wherever possible in our query tests. That way I will remember it for the next time as I had to introduce a kagillion  of those... also PR stats got much better :)

File: core/src/main/java/org/elasticsearch/index/query/MatchQueryBuilder.java (hunk 6 above)
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/MatchQueryBuilder.java]: I suspect that this situation is already at least partially caught by making QueryParseContext#parseInnerQueryBuilder stricter as in checking what is the current token  after the query gets parsed. I have ideas on how to test it too but I'd prefer to do this in a followup PR if you don' mind. We already test these short syntaxes but we never inject bogus objects in them like we do with the "standard" json output, we can totally introduce that for more coverage.

Comment (tlrx) [inline core/src/main/java/org/elasticsearch/index/query/MatchQueryBuilder.java]: Sure.

> We already test these short syntaxes but we never inject bogus objects in them like we do with the "standard" json output, we can totally introduce that for more coverage.

Since query builders now implements ToXContent I think we could introduce bogus object using a XContentBuilder that randomly duplicates fields. Just an idea.

File: core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java (hunk 4 above)
Comment (javanna) [inline core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java]: back on this, I think I am sure now we can make assumption that this must be an end_object. I opened #20528 .

Comment (tlrx) [inline core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java]: Thanks for the heads up - I agree too.
