### PR TITLE
Fix default value of ignore_unavailable for snapshot REST API (#25359)

### LINKED ISSUE #25359: snapshot succeeds with missing index defined
**Elasticsearch version**: 5.4.1

**Plugins installed**: x-pack

**JVM version**:
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**OS version**:
16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
Creating a snapshot where one of the indices does not exist should result in a failed snapshot unless you have `ignore_unavailable` set to true. Rather, the snapshot succeeds and there is no indication of the missing index.

``` json
PUT /_snapshot/my_backup
{
  "type": "fs",
  "settings": {
    "compress": true,
    "location": "/Users/jared/tmp/blah"
  }
}

POST exists/test/1
{"hello": true}

PUT /_snapshot/my_backup/snapshot_1
{"indices":"exists,missing"}

GET /_snapshot/my_backup/snapshot_1/_status

# return
{
  "snapshots": [
    {
      "snapshot": "snapshot_1",
      "repository": "my_backup",
      "uuid": "Zp8WS3YdST-c65Ku_r9sVA",
      "state": "SUCCESS",
      "shards_stats": {
        "initializing": 0,
        "started": 0,
        "finalizing": 0,
        "done": 5,
        "failed": 0,
        "total": 5
      },
      "stats": {
        "number_of_files": 8,
        "processed_files": 8,
        "total_size_in_bytes": 3203,
        "processed_size_in_bytes": 3203,
        "start_time_in_millis": 1498150300101,
        "time_in_millis": 36
      },
      "indices": {
        "exists": {
          "shards_stats": {
            "initializing": 0,
            "started": 0,
            "finalizing": 0,
            "done": 5,
            "failed": 0,
            "total": 5
          },
          "stats": {
            "number_of_files": 8,
            "processed_files": 8,
            "total_size_in_bytes": 3203,
            "processed_size_in_bytes": 3203,
            "start_time_in_millis": 1498150300101,
            "time_in_millis": 36
          },
          "shards": {
            ... 
          }
        }
      }
    }
  ]
}

### PR DESCRIPTION
**Pull request by liketic**
The default value for `ignore_unavailable` did not match what was documented when using the REST APIs for snapshot creation and restore.  This PR sets the default value of `ignore_unavailable` to `false`, [the way it is documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) and ensures it's the same when using either REST API or transport client.

Closes #25359

### CODE REVIEW

**Comment by liketic** [comment]
@abeyad Could you please review this? Thanks in advance.

**Comment by dnhatn** [comment]
@elasticmachine please test this.

**Comment by liketic** [comment]
@dnhatn I rebased and get test passed. Please test again.

**Comment by tvernum** [comment]
@elasticmachine ok to test

File: core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java [hunk 1]
```diff
@@ -402,7 +403,7 @@ public CreateSnapshotRequest source(Map<String, Object> source) {
                 includeGlobalState = nodeBooleanValue(entry.getValue(), "include_global_state");
             }
         }
-        indicesOptions(IndicesOptions.fromMap((Map<String, Object>) source, IndicesOptions.lenientExpandOpen()));
+        indicesOptions(IndicesOptions.fromMap(source, IndicesOptions.strictExpandOpen()));
```
Comment (ywelsch) [inline core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/create/CreateSnapshotRequest.java]: I think this should be fixed by falling back to `indicesOptions` instead (which is equal to `IndicesOptions.strictExpandOpen()` by default)

**Review by ywelsch — CHANGES_REQUESTED** [review]
Indeed, the REST API is not aligned with the defaults of the transport client. I have made a suggestion that makes sure they're always aligned. Can you also fix RestoreSnapshotRequest?

**Comment by liketic** [comment]
@ywelsch Thanks for reviewing this. I pushed 9c657d7fb08eddd8e58e8cf4239b99f2c7c1b4d0

**Comment by ywelsch** [comment]
Thanks for the quick update. Can you also add a REST test in `rest-api-spec/test/snapshot.create/10_basic.yml` that checks that creating a snapshot with an unavailable index name fails? (i.e. that the defaults match what's in the documentation). Note that this will require adding a skip section (for tests in mixed clusters with older versions):

```
  - skip:
      version: " - 6.99.99"
```

For now, you can specify "-6.99.99", I will take care about changing it once we decide on backporting this PR.

Finally can you update the PR title and description? Thanks a lot!

**Comment by liketic** [comment]
@ywelsch Thanks. I updated the REST test. Hope it makes sense.

**Comment by ywelsch** [comment]
@elasticmachine retest this please

**Review by ywelsch — APPROVED** [review]
Thanks again @liketic. I took the liberty of editing the PR description and will merge this soon.
