### PR TITLE
Extend nextDoc to delegate to the wrapped doc-value iterator for date_nanos

### LINKED ISSUE #39107: date_histogram aggregation fails for date_nanos and noon utc timezone
When trying to apply a date_histogram aggregation with a timezone which isn't utc (tested with `Europe/Berlin`) on a `date_nanos` field, elasticsearch responds with a `unsupported_operation_exception`.

Tested version: 7.0 snapshot

Steps to reproduce:
1. Create an index like described in the docs: https://www.elastic.co/guide/en/elasticsearch/reference/7.0/date_nanos.html
2. Execute the following query:
```
GET my_index/_search
{
  "version": true,
  "size": 500,
  "sort": [{ "date": { "order": "desc", "unmapped_type": "boolean" } }],
  "_source": { "excludes": [] },
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "date",
        "interval": "30s",
        "time_zone": "Europe/Berlin",
        "min_doc_count": 1
      }
    }
  },
  "docvalue_fields": [{ "field": "date", "format": "date_time" }],
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "date": { "gte": 1050572204889, "lte": 1550573104889, "format": "epoch_millis" }
          }
        }
      ]
    }
  },
  "timeout": "30000ms"
}
```
expected response: status code 200 and hits in the payload
actual response:
```
{
  "error": {
    "root_cause": [
      {
        "type": "unsupported_operation_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "my_index",
        "node": "mTfaCthlT8uvuCLbfUtPCQ",
        "reason": {
          "type": "unsupported_operation_exception",
          "reason": null
        }
      }
    ],
    "caused_by": {
      "type": "unsupported_operation_exception",
      "reason": null,
      "caused_by": {
        "type": "unsupported_operation_exception",
        "reason": null
      }
    }
  },
  "status": 500
}
```

The same query with `"time_zone": "UTC",` works correctly.

### PR DESCRIPTION
**Pull request by iverase**
The type `date_nanos` does not direct doc-value iterators and it needs to extend `next_doc` in order to delegate the call to the wrapped iterator.

closes #39107

### CODE REVIEW

**Review by jpountz — COMMENTED** [review]
Thanks Ignacio. In addition to the integration test, can you add a unit test that the iterator supports `nextDoc()` in `DateFieldTypeTests`?

File: server/src/test/java/org/elasticsearch/index/mapper/DateFieldTypeTests.java [hunk 1]
```diff
@@ -214,4 +220,36 @@ public void testRangeQuery() throws IOException {
...
+        // Create an index with some docValues
+        Directory dir = newDirectory();
+        IndexWriter w = new IndexWriter(dir, new IndexWriterConfig(null));
+        Document doc = new Document();
+        NumericDocValuesField docValuesField = new NumericDocValuesField("my_date", 1444608000000L);
+        doc.add(docValuesField);
+        w.addDocument(doc);
+        docValuesField.setLongValue(1459641600000L);
+        w.addDocument(doc);
+        w.flush();
```
Comment (jpountz) [inline server/src/test/java/org/elasticsearch/index/mapper/DateFieldTypeTests.java]: no need to flush, `DirectoryReader.open` takes care of writing NRT segments for data that only lives in the IW buffers

File: server/src/test/java/org/elasticsearch/index/mapper/DateFieldTypeTests.java [hunk 2]
```diff
@@ -214,4 +220,36 @@ public void testRangeQuery() throws IOException {
...
+        // Create the doc values reader
+        Settings indexSettings = Settings.builder().put(IndexMetaData.SETTING_VERSION_CREATED, Version.CURRENT)
+            .put(IndexMetaData.SETTING_NUMBER_OF_SHARDS, 1).put(IndexMetaData.SETTING_NUMBER_OF_REPLICAS, 1).build();
+        QueryShardContext context = new QueryShardContext(0,
+            new IndexSettings(IndexMetaData.builder("foo").settings(indexSettings).build(), indexSettings),
+            null, null, null, null, null, xContentRegistry(), writableRegistry(), null, null, () -> nowInMillis, null);
```
Comment (jpountz) [inline server/src/test/java/org/elasticsearch/index/mapper/DateFieldTypeTests.java]: we don't need this object, do we?

**Review by jpountz — APPROVED** [review]
Some minor comments, LGTM. Thanks @iverase !

**Review by jpountz — APPROVED** [review]
