### PR TITLE
Fix concurrent search and index delete

### LINKED ISSUE #28053: [CI] ReindexFailureTests testAbortOnVersionConflict, testFailuresCauseAbortDefault, testResponseOnSearchFailure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=centos/479/console

[build-479-ReindexFailureTests.txt](https://github.com/elastic/elasticsearch/files/1598563/build-479-ReindexFailureTests.txt)

```
ERROR   51.4s J3 | ReindexFailureTests.testResponseOnSearchFailure <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: an empty iterable
   > dices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd1][127.0.0.1:43434][indices:data/write/index]]; nested: RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd1][127.0.0.1:43434][indices:data/write/index]]; nested: RemoteTransportException[[node_sd3][127.0.0.1:35162][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd1][127.0.0.1:43434][indices:data/write/index]]; nested: RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<RemoteTransportException[[node_sd2][127.0.0.1:35287][indices:data/write/bulk[s]]]; nested: IndexNotFoundException[no such index];>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<RemoteTransportException[[node_sd1][127.0.0.1:43434][indices:data/write/index]]; nested: IndexNotFoundException[no such index];>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFounption[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>,<[source/sj2mv1B6SP6OUxseTSjeOQ] IndexNotFoundException[no such index]>]
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1451)
   >    at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1369)
   >    at org.elasticsearch.test.ESIntegTestCase.indexRandom(ESIntegTestCase.java:1353)
   >    at org.elasticsearch.index.reindex.ReindexFailureTests.indexDocs(ReindexFailureTests.java:128)
   >    at org.elasticsearch.index.reindex.ReindexFailureTests.testResponseOnSearchFailure(ReindexFailureTests.java:100)
   >    at java.lang.Thread.run(Thread.java:748)Throwable #2: java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
   >    at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:51)
   >    at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$4(ESTestCase.java:421)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:731)
   >    at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:705)
   >    at org.elasticsearch.test.ESTestCase.ensureAllSearchContextsReleased(ESTestCase.java:421)
   >    at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2072)
   >    at java.lang.Thread.run(Thread.java:748)
   >    Suppressed: java.lang.AssertionError: There are still [1] in-flight contexts. The first one's creation site is listed as the cause of this exception.
   >            at org.elasticsearch.search.MockSearchService.assertNoInFlightContext(MockSearchService.java:51)
   >            at org.elasticsearch.test.ESTestCase.lambda$ensureAllSearchContextsReleased$4(ESTestCase.java:421)
   >            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:719)
   >            ... 37 more
```

```
gradle :modules:reindex:test \
  -Dtests.seed=401B0C5B3206920F \
  -Dtests.class=org.elasticsearch.index.reindex.ReindexFailureTests \
  -Dtests.method="testAbortOnVersionConflict" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn \
  -Dtests.timezone=America/Cuiaba
```

### PR DESCRIPTION
**Pull request by henningandersen**
Changed order of listener invocation so that we notify before
registering search context and notify after unregistering same.

This ensures that count up/down like what we do in ShardSearchStats
works. Otherwise, we risk notifying onFreeScrollContext before notifying
onNewScrollContext (same for onFreeContext/onNewContext, but we
currently have no assertions failing in those).

Closes #28053

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 1]
```diff
@@ -550,12 +551,19 @@ final SearchContext createAndPutContext(ShardSearchRequest request) throws IOExc
         SearchContext context = createContext(request);
         boolean success = false;
         try {
-            putContext(context);
             if (request.scroll() != null) {
                 openScrollContexts.incrementAndGet();
                 context.indexShard().getSearchOperationListener().onNewScrollContext(context);
             }
             context.indexShard().getSearchOperationListener().onNewContext(context);
+            putContext(context);
```
Comment (s1monw) [inline server/src/main/java/org/elasticsearch/search/SearchService.java]: I don't understand why you moved the `putContext(context)`

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 2]
```diff
@@ -550,12 +551,19 @@ final SearchContext createAndPutContext(ShardSearchRequest request) throws IOExc
...
+            // ensure that if index is deleted concurrently, we free the context immediately, either here or in afterIndexRemoved
+            try {
+                indicesService.indexServiceSafe(request.shardId().getIndex());
+            } catch (IndexNotFoundException e) {
```
Comment (s1monw) [inline server/src/main/java/org/elasticsearch/search/SearchService.java]: I don't think you need the catch clause here - we free [below](https://github.com/elastic/elasticsearch/pull/42621/files#diff-a42a639093633662ea658bec29044a4cR571)

**Review by s1monw — COMMENTED** [review]
I am not following what the issue is here and why we don't clean it up correctly today? Can you show me what fails here in what situation. Sorry for being slow...

**Comment by henningandersen** [comment]
Thanks for reviewing, @s1monw . The problem we were facing is that `onFreeScrollContext` could be called prior to `onNewScrollContext` for a specific `SearchContext`. This in turn makes `totalStats.scrollCurrent` in `ShardSearchStats` go negative, tripping the assertion in `ShardSearchStats.onFreeScrollContext`. Intuitively, it also seems unexpected for a `SearchOperationListener` to be exposed to this order.

The wrong order of invocation could occur in following scenario:
1. Someone does a search and a SearchContext is created and put into `SearchService.activeContexts` (but listeners not invoked yet).
2. The index is deleted and `SearchService.afterIndexRemoved` is called, which frees all `activeContexts`, thus invoking the listeners too.
3. Now the original thread resumes and invokes 'onNewContext/onNewScrollContext`.

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 1 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: By registering the search context in `activeContexts` after having invoked `onNewContext/onNewScrollContext`, we guarantee that for a specific `SearchContext`, the call to `onNewXXX` happens before the matching call the `onFreeXXX`.

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 2 above)
Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: How did I miss that, thanks! Fixed in 8edda7b36f7009f6d01d44fabe97e94153d7d06e

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 1 above)
Comment (s1monw) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: I see I didn't think about `SearchService.afterIndexRemoved`.  my issue here is that we have to call  `onFreeXXX` but if one of the `onNewContext /onNewScrollContext` fails we don't register and fail? I think we need extra protection for this?

File: server/src/main/java/org/elasticsearch/search/SearchService.java (hunk 2 above)
Comment (s1monw) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: but is this necessary or can we just rearrange the registration?

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 3]
```diff
@@ -548,19 +548,35 @@ final SearchContext createAndPutContext(ShardSearchRequest request) throws IOExc
         }
 
         SearchContext context = createContext(request);
+        onNewContext(context);
         boolean success = false;
         try {
             putContext(context);
-            if (request.scroll() != null) {
+            // ensure that if index is deleted concurrently, we free the context immediately, either here or in freeAllContextForIndex
+            indicesService.indexServiceSafe(request.shardId().getIndex());
```
Comment (s1monw) [inline server/src/main/java/org/elasticsearch/search/SearchService.java]: I am still not sure why we do this here. Why can't we just let the search go and fail whenever?

Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: It might be overkill... The way I understand the code, the primary purpose of `afterIndexRemoved` is to ensure that we free memory and file system resources as quickly as possible when an index is deleted/closed. Here we try to ensure the same happens also during a race condition. Without this, we theoretically risk holding on to memory/file system resources for a while after the index is deleted/closed. With this, we should free such resources as soon as the index is deleted (and any current search phases have run to completion).

I guess there is a trade-off in that doing this double validation has a small cost and the likelihood of seeing the race condition is very small. I can certainly remove this double validation if you think?

Comment (s1monw) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: I think we should remove the double validation. But the fix you added in this PR is crucial!

Comment (henningandersen) [reply server/src/main/java/org/elasticsearch/search/SearchService.java]: Thanks @s1monw , I have removed the double validation, please have another look at your convenience.

File: server/src/main/java/org/elasticsearch/search/SearchService.java [hunk 4]
```diff
@@ -648,18 +664,22 @@ private void freeAllContextForIndex(Index index) {
...
-                    context.indexShard().getSearchOperationListener().onFreeScrollContext(context);
-                }
+                onFreeContext(context);
                 return true;
             }
             return false;
         }
     }
 
+    private void onFreeContext(SearchContext context) {
```
Comment (s1monw) [inline server/src/main/java/org/elasticsearch/search/SearchService.java]: can you add an assertion here that ensures that we removed the context. I think it's trappy that we have an this method and we need to make sure that we never call if if we haven't removed the context. The special case is fina

**Review by s1monw — APPROVED** [review]
LGTM left one comment

**Comment by henningandersen** [comment]
Backported to 7.x, 7.2.
Backport to 6.8 pending.
