### PR TITLE
Workaround for JDK bug with total mem on Debian8

### LINKED ISSUE #66629: OsProbeTests.testOsStats and memory-related YAML test failures on Debian 8
Other associated failures from what appears to be the same root cause of misreported memory by the OS, all on Debian 8 runners:
- `ClientYamlTestSuiteIT test {p0=cluster.stats/10_basic/cluster stats test}`
- `ClientYamlTestSuiteIT test {p0=cluster.stats/10_basic/get cluster stats returns cluster_uuid at the top level}`
- `DocsClientYamlTestSuiteIT test {yaml=reference/ml/anomaly-detection/apis/get-ml-info/line_41}`

**Build scan**: https://gradle-enterprise.elastic.co/s/z3bger2wnj62m

**Repro line**: `./gradlew ':server:test' --tests "org.elasticsearch.monitor.os.OsProbeTests.testOsStats" -Dtests.seed=A4A541649A2C4A2C -Dtests.security.manager=true -Dtests.locale=es-PY -Dtests.timezone=Asia/Anadyr -Druntime.java=8`

**Reproduces locally?**: No (on MacOS, don't have a local Debian box)

**Applicable branches**: `7.x`, `7.11`, `7.10`, `6.8`

**Failure history**: [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(branch,message),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'test:testOsStats'),sort:!(time,desc))), first recent failure at `2020-12-17T04:22:14.082Z` on `7.11`
**Failure excerpt**:
```
java.lang.AssertionError: 	
Expected: a value greater than <0L>	
     but: <0L> was equal to <0L>	
	at __randomizedtesting.SeedInfo.seed([A4A541649A2C4A2C:2FAF436319C6E61C]:0)	
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)	
	at org.junit.Assert.assertThat(Assert.java:956)	
	at org.junit.Assert.assertThat(Assert.java:923)	
	at org.elasticsearch.monitor.os.OsProbeTests.testOsStats(OsProbeTests.java:123)	
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
	at java.lang.reflect.Method.invoke(Method.java:498)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)	
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)	
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)	
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)	
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)	
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)	
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)	
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)	
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by danhermann**
Reads total system memory from `/proc/meminfo` on Debian8 systems if the JDK reports `0` total memory. See https://github.com/elastic/elasticsearch/issues/66885#issuecomment-757888941 for more background.

Fixes #66629.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/monitor/os/OsProbe.java [hunk 1]
```diff
@@ -641,6 +646,56 @@ private String getPrettyName() throws IOException {
         }
     }
 
+    /**
+     * Returns the lines from /proc/meminfo as a workaround for JDK bugs that prevent retrieval of total system memory
+     * on some Linux variants such as Debian8.
+     */
+    @SuppressForbidden(reason = "access /proc/meminfo")
+    List<String> readProcMeminfo() throws IOException {
```
Comment (danhermann) [inline server/src/main/java/org/elasticsearch/monitor/os/OsProbe.java:654]: I'm not thrilled by everything that happens here, but by default, the value is cached so that this method shouldn't be called more than once per second and probably less frequently on systems with appropriate monitoring intervals.

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/default-distro

File: server/src/test/java/org/elasticsearch/monitor/os/OsProbeTests.java [hunk 2]
```diff
@@ -254,6 +254,50 @@ public void testCgroupProbeWithMissingMemory() {
         assertNull(cgroup);
     }
 
+    public void testGetTotalMemFromProcMeminfo() throws Exception {
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/monitor/os/OsProbeTests.java:257]: Can we also add a test that does not stub out /proc/meminfo and verify that it gives us something > 0? It should run on debian 8 only.

**Review by henningandersen — APPROVED** [review]
LGTM, thanks for fixing this @danhermann 

I wonder if we should reenable various tests on debian 8 that were previously disabled due to this, for instance `TransportGetAutoscalingCapacityActionIT` and some of the ML rest tests? Can definitely also be handled in a follow-up.

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by danhermann** [comment]
Thanks, @henningandersen! I've made the changes you requested and will open another PR to re-enable the tests that were failing due to this issue. Let me know if you see anything else related to this that needs to be addressed.
