### PR TITLE
SQL: Verify Full-Text Search functions not allowed in SELECT

### LINKED ISSUE #47446: SQL: selecting a full-text function generates error
The desired behavior is a user friendly error message stating that full-text functions cannot be used as projections. Related to https://github.com/elastic/elasticsearch/issues/47365.

```
sql> SELECT MATCH(gender, 'F') FROM test_emp;
Server error [Server encountered an error [Cannot cast org.elasticsearch.xpack.sql.expression.predicate.fulltext.MatchQueryPredicate to org.elasticsearch.xpack.sql.expression.NamedExpression]. [java.lang.ClassCastException: Cannot cast org.elasticsearch.xpack.sql.expression.predicate.fulltext.MatchQueryPredicate to org.elasticsearch.xpack.sql.expression.NamedExpression
        at java.base/java.lang.Class.cast(Class.java:3606)
        at org.elasticsearch.xpack.sql.parser.AbstractBuilder.visitList(AbstractBuilder.java:63)
        at org.elasticsearch.xpack.sql.parser.LogicalPlanBuilder.visitQuerySpecification(LogicalPlanBuilder.java:129)
        at org.elasticsearch.xpack.sql.parser.LogicalPlanBuilder.visitQuerySpecification(LogicalPlanBuilder.java:64)
        at org.elasticsearch.xpack.sql.parser.SqlBaseParser$QuerySpecificationContext.accept(SqlBaseParser.java:1722)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at org.elasticsearch.xpack.sql.parser.SqlBaseBaseVisitor.visitQueryPrimaryDefault(SqlBaseBaseVisitor.java:125)
        at org.elasticsearch.xpack.sql.parser.SqlBaseParser$QueryPrimaryDefaultContext.accept(SqlBaseParser.java:1552)
        at org.elasticsearch.xpack.sql.parser.AbstractBuilder.typedParsing(AbstractBuilder.java:42)
        at org.elasticsearch.xpack.sql.parser.AbstractBuilder.plan(AbstractBuilder.java:53)
        at org.elasticsearch.xpack.sql.parser.LogicalPlanBuilder.visitQueryNoWith(LogicalPlanBuilder.java:95)
        at org.elasticsearch.xpack.sql.parser.LogicalPlanBuilder.visitQueryNoWith(LogicalPlanBuilder.java:64)
        at org.elasticsearch.xpack.sql.parser.SqlBaseParser$QueryNoWithContext.accept(SqlBaseParser.java:1362)
        at org.elasticsearch.xpack.sql.parser.AbstractBuilder.typedParsing(AbstractBuilder.java:42)
        at org.elasticsearch.xpack.sql.parser.AbstractBuilder.plan(AbstractBuilder.java:53)
        at org.elasticsearch.xpack.sql.parser.LogicalPlanBuilder.visitQuery(LogicalPlanBuilder.java:72)
        at org.elasticsearch.xpack.sql.parser.LogicalPlanBuilder.visitQuery(LogicalPlanBuilder.java:64)
        at org.elasticsearch.xpack.sql.parser.SqlBaseParser$QueryContext.accept(SqlBaseParser.java:1279)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:70)
        at org.elasticsearch.xpack.sql.parser.SqlBaseBaseVisitor.visitStatementDefault(SqlBaseBaseVisitor.java:34)
        at org.elasticsearch.xpack.sql.parser.SqlBaseParser$StatementDefaultContext.accept(SqlBaseParser.java:465)
        at org.elasticsearch.xpack.sql.parser.AbstractBuilder.typedParsing(AbstractBuilder.java:42)
        at org.elasticsearch.xpack.sql.parser.AbstractBuilder.plan(AbstractBuilder.java:53)
        at org.elasticsearch.xpack.sql.parser.AstBuilder.visitSingleStatement(AstBuilder.java:26)
        at org.elasticsearch.xpack.sql.parser.AstBuilder.visitSingleStatement(AstBuilder.java:15)
        at org.elasticsearch.xpack.sql.parser.SqlBaseParser$SingleStatementContext.accept(SqlBaseParser.java:185)
        at org.elasticsearch.xpack.sql.parser.AbstractBuilder.typedParsing(AbstractBuilder.java:42)
        at org.elasticsearch.xpack.sql.parser.AbstractBuilder.plan(AbstractBuilder.java:53)
        at org.elasticsearch.xpack.sql.parser.SqlParser.invokeParser(SqlParser.java:129)
        at org.elasticsearch.xpack.sql.parser.SqlParser.createStatement(SqlParser.java:66)
        at org.elasticsearch.xpack.sql.session.SqlSession.doParse(SqlSession.java:99)
```

### PR DESCRIPTION
**Pull request by matriv**
Add a verification that full-text search functions are not
allowed in the SELECT clause, so that a nice error message is
returned to the user early instead of an "ugly" exception.

Fixes: #47446

### CODE REVIEW

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java [hunk 1]
```diff
@@ -215,8 +216,16 @@ private static Failure fail(Node<?> source, String message, Object... args) {
         // if there are no (major) unresolved failures, do more in-depth analysis
 
         if (failures.isEmpty()) {
+            Set<Failure> localFailures = new LinkedHashSet<>();
             final Map<Attribute, Expression> collectRefs = new LinkedHashMap<>();
 
+            // Full-Text search function are not allowed in the SELECT clause
+            plan.forEachUp(p -> p.forEachExpressionsUp(e -> {
+                if (e instanceof FullTextPredicate) {
+                    localFailures.add(fail(e, "Cannot use a Full-Text search functions in the SELECT clause"));
```
Comment (astefan) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java]: The error message I think has several issues: why the capital letters for Full-Text, and why the plural `functions`?Also, if you look at our docs - https://www.elastic.co/guide/en/elasticsearch/reference/7.x/sql-functions-search.html - full-text search functions include `SCORE()` as well, but Score is not an `instanceof FullTextPredicate` so it wouldn't match this condition.

So, try to adjust the error message not to partially conflict with the documentation.

**Review by astefan — COMMENTED** [review]
LGTM in general, but the error message needs to be changed.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java (hunk 1 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java]: Thx, Rephrased the error message.
I chose not to refer to the exact usage in the user's query because it can be a large string, given the params that would be often used, e.g.:
```
QUERY('Man*', 'default_field=last_name;lenient=true', 'fuzzy_rewrite=scoring_boolean')
```

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java [hunk 2]
```diff
@@ -215,8 +216,19 @@ private static Failure fail(Node<?> source, String message, Object... args) {
         // if there are no (major) unresolved failures, do more in-depth analysis
 
         if (failures.isEmpty()) {
+            Set<Failure> localFailures = new LinkedHashSet<>();
             final Map<Attribute, Expression> collectRefs = new LinkedHashMap<>();
 
+            // Full-Text search function are not allowed in the SELECT clause
+            plan.forEachUp(p -> {
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/analysis/analyzer/Verifier.java]: Despite being a small snippet, can you please extract it into its own static method - it's easier to reason about its purpose before looking at its details?
Thanks.

**Review by costin — APPROVED** [review]
Nice catch. Thanks!
