### PR TITLE
Fail early if an index request has the wrong type

### LINKED ISSUE #77411: Index requests with incorrect types can cause confusing errors
Applies to all released 7x versions of elasticsearch.

1) Create an index (with no type) that contains a `foo` field mapped as `keyword`
2) Send an index request with type `bar` that contains a string `foo` field
3) The index action will notice that there is no `bar` type, so create an empty mapper which then dynamically assigns the `foo` field a text mapper
4) The indexing code will try and merge this new dynamic mapper into the root, and get an error because `foo` is mapped both as text and keyword: `mapping update rejected by primary - java.lang.IllegalArgumentException: mapper [foo] cannot be changed from type [keyword] to [text]`

This error is confusing because the actual cause of the problem is the incorrect type.  We should detect the type mismatch earlier and return a better error.

### PR DESCRIPTION
**Pull request by romseygeek**
If an index request contains a type that is different to the type defined on the
index, we fail the request with an error.  However, this check happens fairly
late on in the process, and if the index request has generated dynamic updates
that conflict with the existing mappings on the index then merge errors will
get thrown instead.  This is confusing to users, as it is not at all obvious why
these conflicting mappings have been generated.

This commit adds a check for valid types early in the indexing process, so that
requests with invalid types will be failed with a more informative error message.

Fixes #77411

### CODE REVIEW

**Comment by romseygeek** [comment]
Note that this applies only to 7x - in 8x types are either not present on the request at all or are stripped out by the rest compatibility layer.

**Comment by dnhatn** [comment]
Changes look good to me. Can we also have this validation for delete operations? Thanks @romseygeek.

File: server/src/main/java/org/elasticsearch/index/mapper/MapperService.java [hunk 1]
```diff
@@ -548,6 +548,18 @@ public DocumentMapper documentMapper(String type) {
         return null;
     }
 
+    public void validateType(String type) {
+        if (mapper == null) {
+            return;
+        }
+        if (DEFAULT_MAPPING.equals(type)) {
+            return;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:556]: Naive question: if `mapper.type()` is not `DEFAULT_MAPPING` (e.g. it's a 6.x index) then are we ok to proceed here?

Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java:556]: Looking at this again, that should be `SINGLE_MAPPING_TYPE`, not `DEFAULT_MAPPING` (which is something used for auto-creation of indices and should never be indexed into).  And we always resolve the type before calling `validateType()` so we can actually remove this branch entirely.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/index/mapper/MapperService.java]: Oh yeah I also thought this was a synonym for `"_doc"`. Looks good to me now.

File: server/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 2]
```diff
@@ -881,6 +881,7 @@ private IndexShardState changeState(IndexShardState newState, String reason) {
         long startTime = System.nanoTime();
         assert source.dynamicTemplates().isEmpty() || origin == Engine.Operation.Origin.PRIMARY :
             "dynamic_templates parameter can only be associated with primary operations";
+        mapperService.validateType(type);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/index/shard/IndexShard.java:884]: Another naive question (sorry): could we catch this in `MapperService#merge` rather than relying on callers checking they're not adding a type first? Not to say there's anything wrong with checking it here, just that there's a risk there's more code paths that aren't covered. Maybe not today but possibly in a future version.

Comment (romseygeek) [reply server/src/main/java/org/elasticsearch/index/shard/IndexShard.java:884]: Types are gone entirely in 8x so I'm not that concerned about future new code paths.  I did initially try detecting this in `MapperService#merge` but that ended up breaking loads of unit tests which aren't being careful with their types, so I felt that this was the best fix for the minimum footprint.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/index/shard/IndexShard.java:884]: Ok, makes sense, I also expect this won't change too much in what's left of the 7.x series. I would like this to be reviewed by someone who knows more about mappings than me, but this LGTM.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @romseygeek.
