### PR TITLE
ES|QL: Add random test query generator

### LINKED ISSUE #98768: ES|QL testing: random query generator/test
To catch corner cases like https://github.com/elastic/elasticsearch/issues/98404, it could be useful to have some kind of random query generator/test.

A simple proposal:
1. map all the supported commands/expressions/functions  and the available test indexes
2. map all the expected errors (Eg. validation exceptions)
3. define a `<max-depth>` for the generated queries
4. generate a one-command query (Eg. `from <random-index-pattern>`) based on the available indexes
5. run the query 
4.1. if it throws a valid error, return and succeed
4.2. if it throws an unexpected error, fail
4.3 if the query is `<max-depth>` commands deep, return and succeed
6. based on the query output (field names, maybe types; ignore the actual results), randomly generate a syntactically valid command using the mappings in (1) and append it to the query
7. iterate to (5)

Goals:
- catch unexpected exceptions and corner cases (layout errors, assertion errors, NPE, data loading problems, blind spots on query planning)
- rationalize the query errors (see point 2)

Non-goals:
- validate the results: since the query generation is randomized, checking the correctness of the results is out of scope

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/98768

~~DO NOT MERGE, fix below issues first!~~

Add a test that iteratively generates random queries starting from test indexes (CSV tests).
It's just string manipulation to create syntactically valid queries, no semantics at all (hence no validation of the results).
The intention is to test errors and corner cases in query planning and layout management, plus to spot wrongly managed exceptions.

Tests disabled by default, because there are still some known issues in the query planner that trigger failures.

Problems found: 

- [x] https://github.com/elastic/elasticsearch/issues/102061
- [x] https://github.com/elastic/elasticsearch/issues/102084
- [x] https://github.com/elastic/elasticsearch/issues/102083
- [x] https://github.com/elastic/elasticsearch/issues/102120
- [x] https://github.com/elastic/elasticsearch/issues/102121
- [x] https://github.com/elastic/elasticsearch/issues/102123

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java [hunk 1]
```diff
@@ -0,0 +1,360 @@
...
+            } else {
+                result.append(randomName(previousOutput));
+            }
+            result.append("}");
+        }
+        result.append("\"");
+        return result.toString();
+    }
+
+    private static String keep(List<Column> previousOutput) {
```
Comment (astefan) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java:165]: Here, you could easily (I hope) improve it by adding `*` or `fieldname*` or `*fieldname`.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java [hunk 2]
```diff
@@ -0,0 +1,360 @@
...
+        return previousOutput.get(randomIntBetween(0, previousOutput.size() - 1)).name();
+    }
+
+    private static String rename(List<Column> previousOutput) {
+        int n = randomIntBetween(1, Math.min(3, previousOutput.size()));
+        Set<String> proj = new HashSet<>();
+        List<String> names = previousOutput.stream().map(Column::name).collect(Collectors.toList());
+        for (int i = 0; i < n; i++) {
+            String name = names.remove(randomIntBetween(0, names.size() - 1));
+            proj.add(name + " AS " + randomAlphaOfLength(5));
```
Comment (astefan) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java:184]: Another idea is to rename as an existing name. I don't remember what restrictions we have in place for this but some food for thought maybe.

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java [hunk 3]
```diff
@@ -0,0 +1,360 @@
...
+        return " | drop " + proj.stream().collect(Collectors.joining(", "));
+    }
+
+    private static String sort(List<Column> previousOutput) {
+        int n = randomIntBetween(1, previousOutput.size());
+        Set<String> proj = new HashSet<>();
+        for (int i = 0; i < n; i++) {
+            proj.add(randomName(previousOutput));
+        }
+        return " | sort " + proj.stream().map(x -> x + " " + randomFrom("ASC", "DESC")).collect(Collectors.joining(", "));
```
Comment (astefan) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java:207]: An addition here: `NULLS FIRST/LAST`

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java [hunk 4]
```diff
@@ -0,0 +1,360 @@
...
+
+    private static String agg(List<Column> previousOutput) {
+        String name = randomNumericOrDateField(previousOutput);
+        if (name == null) {
+            return "count(*)";
+        }
+        return switch (randomIntBetween(0, 2)) {
+            case 0 -> "max(" + name + ")";
+            case 1 -> "min(" + name + ")";
+            default -> "count(*)";
```
Comment (astefan) [inline x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java:276]: You could also add a `count(name)`.

Comment (astefan) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java:276]: Another suggestion is `count_distinct`

File: x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java [hunk 5]
```diff
@@ -0,0 +1,360 @@
...
+        return items.get(randomIntBetween(0, items.size() - 1));
+    }
+
+    private static String expression(List<Column> previousOutput) {
+        // TODO improve!!!
+        return constantExpression();
+    }
+
+    public static String limit() {
+        return " | limit " + randomIntBetween(0, 10000);
```
[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java:307]: Actually it will work fine, it will just return 10k items at most

[the remark this answers is not in the document]
Comment (luigidellaquila) [reply x-pack/plugin/esql/qa/server/src/main/java/org/elasticsearch/xpack/esql/qa/rest/generative/EsqlQueryGenerator.java:307]: It makes sense to test it, I'll change it to 15k

**Comment by luigidellaquila** [comment]
TODO add more datasets, in particular with unsupported types

**Comment by luigidellaquila** [comment]
@elasticmachine test this please

**Review by craigtaverner — APPROVED** [review]
I looked through it, and thought it made sense. Since it is test-only and currently has the main test class disabled with `AwaitsFix`, it does not appear to be an issue to merge in my opinion.
