### PR TITLE
SQL: Allow long literals

### LINKED ISSUE #31750: _xpack returned sql_illegal_argument_exception
**Elasticsearch version** (`6.3`):

**Plugins installed**: [_xpack]

**JVM version** (`1.8.0_161-b14`):

**OS version** (`Linux 3.10.0-327.10.1.el7.x86_64`):

**Description of the problem including expected versus actual behavior**:
Got `sql_illegal_argument_exception` when getting data from elastic search using _xpack/sql.

uri: `http://${host}/_xpack/sql?format=json`

SQL:
```
select created_at, device_id from table1 where  created_at > 1527982201597 AND user_id = '12345678'
```

Error:

**Steps to reproduce**:
 1.   use the code (js) below to post a request.
```
let options = {
    method: 'POST',
    uri: `http://${hosts}/_xpack/sql?format=json`,
    body: {"query": `select created_at, device_id from table1 where  created_at > 1527982201597 AND user_id = '12345678'`},
    json: true
  };
  return rp(options);
```
 2. Got exception in the result. 
 The created_at is date type and `1527982201597` is milliseconds.

**Provide logs (if relevant)**:
```
{ error:
   { root_cause: [ [Object] ],
     type: 'sql_illegal_argument_exception',
     reason: '[1527982201597] out of [Int] range' },
    status: 500
 } 
```

### PR DESCRIPTION
**Pull request by costin**
Fix bug that caused integral literals to be only Integer (rejecting
Long). This commit fixes that and picks either an Integer or Long based
on size.

Closes #31750

### CODE REVIEW

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/ExpressionTests.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+import org.elasticsearch.xpack.sql.expression.Expression;
+import org.elasticsearch.xpack.sql.expression.Literal;
+import org.elasticsearch.xpack.sql.type.DataType;
+
+public class ExpressionTests extends ESTestCase {
+
+    private final SqlParser parser = new SqlParser();
+
+    public void testLiteralLong() throws Exception {
+        Expression lt = parser.createExpression(String.valueOf(Long.MAX_VALUE));
```
Comment (astefan) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/ExpressionTests.java]: Does it make sense to test for things like `+123` or `-123` (having the +/- sign added to the String expression)?

Comment (costin) [reply x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/parser/ExpressionTests.java]: Added a test for it (which uncovered an interesting case) - see below.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/DataTypeConversion.java [hunk 2]
```diff
@@ -407,7 +407,9 @@ public static Object convert(Object value, DataType dataType) {
 
         NUMERIC_TO_BOOLEAN(fromLong(value -> value != 0)),
         STRING_TO_BOOLEAN(fromString(DataTypeConversion::convertToBoolean, "Boolean")),
-        DATE_TO_BOOLEAN(fromDate(value -> value != 0));
+        DATE_TO_BOOLEAN(fromDate(value -> value != 0)),
+
+        BOOL_TO_LONG(fromBool(value -> value ? 1L : 0L));
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/DataTypeConversion.java]: My preference would be to move `BOOL_TO_LONG` up and start using it instead of `BOOL_TO_INT` for date conversions (we can't right now since the enum entry is defined after).
It's consistent and avoids the int to long conversion.

**Review by bpintea — APPROVED** [review]
LGTM

**Review by nik9000 — APPROVED** [review]
