### PR TITLE
Adjust warning for heap size bootstrap check

### LINKED ISSUE #56422: elasticsearch requires initial heap size === max heap size even if bootstrap.memory_lock=false
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.0

**Plugins installed**: none

**JVM version** (`java -version`):
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-2ubuntu116.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-2ubuntu116.04, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
$ uname -a
Linux worker1 4.15.0-96-generic #97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -d
Description:	Ubuntu 16.04.6 LTS

**Description of the problem including expected versus actual behavior**:
To reduce memory usage we would like to run elasticsearch with as little memory as possible. To make this possible, we'd need to set -Xms to much lower value than -Xmx. However, the check in BootstrapChecks.java always enforces -Xms == -Xmx. This is a bug and this code is missing a check similar to MlockallCheck which has

 if (BootstrapSettings.MEMORY_LOCK_SETTING.get(context.settings()) && !isMemoryLocked())
...

but the code in BootstrapCheckResult does not have similar check.

**Steps to reproduce**:
Set jvm.options initial and max heap usage to different values, for example:

-Xms50m
-Xmx1000m

**Provide logs (if relevant)**:

systemd[1]: Starting Elasticsearch...
elasticsearch[11874]: ERROR: [1] bootstrap checks failed
elasticsearch[11874]: [1]: initial heap size [52428800] not equal to maximum heap size [1048576000]; this can cause resize pauses and prevents mlockall from locking the entire heap

### PR DESCRIPTION
**Pull request by jasontedor**
Today the heap size check warns the user about two issues why they might care about the heap size check: resize pauses, and if memory locking is enabled. Yet, we unconditionally make mention of the memory locking reason, even if memory locking is not enabled. This can confuse some users, so we adjust the warning about memory locking to only display if memory locking is enabled.

Closes #56422

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java [hunk 1]
```diff
@@ -226,12 +226,22 @@ public BootstrapCheckResult check(BootstrapContext context) {
...
+                        "initial heap size [%d] not equal to maximum heap size [%d]; " +
+                            "this can cause resize pauses",
+                        getInitialHeapSize(),
+                        getMaxHeapSize());
+                } else {
+                    message = String.format(
                         Locale.ROOT,
                         "initial heap size [%d] not equal to maximum heap size [%d]; " +
-                                "this can cause resize pauses and prevents mlockall from locking the entire heap",
+                            "this can cause resize pauses and prevents memory locking from locking the entire heap",
```
Comment (rjernst) [inline server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java:241]: Shouldn't the memory locking part be in the other condition's message, since this is the *not* memory locked case?

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM
