### PR TITLE
Simplify get reindex API and fix integration tests

### LINKED ISSUE #144364: [CI] ReindexGetRelocationIT testGetReindexFollowsRelocation failing
**Build Scans:**
- [elasticsearch-intake #36041 / part1](https://gradle-enterprise.elastic.co/s/qrck3vjzxongw)
- [elasticsearch-pull-request #128497 / part-1](https://gradle-enterprise.elastic.co/s/zngo5r34zholo)

**Reproduction Line:**
```
./gradlew ":modules:reindex-management:internalClusterTest" --tests "org.elasticsearch.reindex.management.ReindexGetRelocationIT.testGetReindexFollowsRelocation" -Dtests.seed=E3396F9772CE34F4 -Dtests.locale=fil -Dtests.timezone=Europe/Zurich -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.reindex.management.ReindexGetRelocationIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testGetReindexFollowsRelocation'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [main] 2 failures in test testGetReindexFollowsRelocation (0.7% fail rate in 306 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #145931: [CI] ReindexGetRelocationIT testGetWaitForCompletionDuringRelocation failing
**Build Scans:**
- [elasticsearch-intake #37282 / part1](https://gradle-enterprise.elastic.co/s/x6ablcalfh4vs)
- [elasticsearch-pull-request #135714 / part-1](https://gradle-enterprise.elastic.co/s/fa2filnueuh3s)
- [elasticsearch-intake #37280 / part1](https://gradle-enterprise.elastic.co/s/g6bajxijshdla)
- [elasticsearch-intake #37278 / part1](https://gradle-enterprise.elastic.co/s/urhxlwkmoeary)
- [elasticsearch-pull-request #135714 / part-1](https://gradle-enterprise.elastic.co/s/sb7hpft7gawi6)
- [elasticsearch-pull-request #135707 / part-1](https://gradle-enterprise.elastic.co/s/hi7j6yap72dac)
- [elasticsearch-intake #37277 / part1](https://gradle-enterprise.elastic.co/s/tgxti7oqdyzra)
- [elasticsearch-pull-request #135709 / part-1](https://gradle-enterprise.elastic.co/s/sofc66q4eleb4)
- [elasticsearch-pull-request #135704 / part-1](https://gradle-enterprise.elastic.co/s/lbx3ngzmycmpg)
- [elasticsearch-pull-request #135707 / part-1](https://gradle-enterprise.elastic.co/s/5vq7udtvevhqy)

**Reproduction Line:**
```
./gradlew ":modules:reindex-management:internalClusterTest" --tests "org.elasticsearch.reindex.management.ReindexGetRelocationIT.testGetWaitForCompletionDuringRelocation" -Dtests.seed=81A85697A3A2DDDF -Dtests.locale=he-Hebr-IL -Dtests.timezone=Europe/Ljubljana -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.reindex.management.ReindexGetRelocationIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testGetWaitForCompletionDuringRelocation'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: wait and non-wait responses are identical
Expected: <GetReindexResponse{result=RelocatableReindexResult[original={"completed":true,"task":{"node":"yYEx9etdT9aJJS2M8WKDIw","id":422,"type":"transport","action":"indices:data/write/reindex","status":{"total":1080,"updated":0,"created":12,"deleted":0,"batches":4,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":18.0,"throttled_until_millis":0,"slices":[{"slice_id":0,"total":288,"updated":0,"created":3,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":4.5,"throttled_until_millis":0},{"slice_id":1,"total":250,"updated":0,"created":3,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":4.5,"throttled_until_millis":0},{"slice_id":2,"total":254,"updated":0,"created":3,"deleted":0,"batches":1,"version_conflic
[truncated]
```

**Issue Reasons:**
- [main] 3 consecutive failures in test testGetWaitForCompletionDuringRelocation
- [main] 3 consecutive failures in step part1
- [main] 1 consecutive failures in step part-1
- [main] 3 consecutive failures in pipeline elasticsearch-intake
- [main] 1 consecutive failures in pipeline elasticsearch-pull-request
- [main] 18 failures in test testGetWaitForCompletionDuringRelocation (3.5% fail rate in 513 executions)
- [main] 6 failures in step part1 (4.7% fail rate in 127 executions)
- [main] 12 failures in step part-1 (3.9% fail rate in 311 executions)
- [main] 6 failures in pipeline elasticsearch-intake (4.7% fail rate in 127 executions)
- [main] 8 failures in pipeline elasticsearch-pull-request (2.6% fail rate in 305 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by samxbr**
After the get task API was made relocation aware in https://github.com/elastic/elasticsearch/pull/145764, this change simplifies the `GET /_reindex/{task_id}`. Unnecessary chain-following logic and wrapper class are removed. 

As part of testing this refactoring, I included fixes for the related muted integration tests in this PR. Run IT 100 times to check they are not flaky.

Closes https://github.com/elastic/elasticsearch/issues/144364
Closes https://github.com/elastic/elasticsearch/issues/145931
Relates to https://github.com/elastic/elasticsearch-team/issues/2591

### CODE REVIEW

File: modules/reindex-management/src/main/java/org/elasticsearch/reindex/management/GetReindexResponse.java [hunk 1]
```diff
@@ -42,66 +43,61 @@ public class GetReindexResponse extends ActionResponse implements ToXContentObje
...
-    static XContentBuilder resultToXContent(final XContentBuilder builder, final Params params, final RelocatableReindexResult result)
-        throws IOException {
-        builder.field("id", result.originalTaskId().toString());
-        Optional<String> description = sanitizeDescription(result.description());
+    static XContentBuilder taskInfoToXContent(final XContentBuilder builder, final Params params, final TaskInfo info) throws IOException {
+        builder.field("id", info.originalTaskId().toString());
+        Optional<String> description = sanitizeDescription(info.description());
         if (description.isPresent()) {
             builder.field("description", description.get());
         }
```
Comment (PeteGillinElastic) [inline modules/reindex-management/src/main/java/org/elasticsearch/reindex/management/GetReindexResponse.java:92]: Entirely optional, but you could turn these two lines into one with `Optional.ifPresent()`.

**Review by PeteGillinElastic — APPROVED** [review]
Thanks!

File: modules/reindex-management/src/main/java/org/elasticsearch/reindex/management/GetReindexResponse.java (hunk 1 above)
Comment (samxbr) [reply modules/reindex-management/src/main/java/org/elasticsearch/reindex/management/GetReindexResponse.java:92]: That would be neat, but looks like `Optional.ifPresent()` complains because `builder.field` throws a checked `IOException`

Comment (PeteGillinElastic) [reply modules/reindex-management/src/main/java/org/elasticsearch/reindex/management/GetReindexResponse.java:92]: Bah, okay!

**Comment by PeteGillinElastic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.4|[](https://github.com/elastic/elasticsearch/pull/150772)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by PeteGillinElastic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.4|[](https://github.com/elastic/elasticsearch/pull/150776)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
