### PR TITLE
Fix and unmute VectorSystemPropertyTests

### LINKED ISSUE #110949: [CI] VectorSystemPropertyTests testSystemPropertyDisabled failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #3416 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/kixgradviemo2)
- [elasticsearch-periodic-platform-support #3416 / windows-2019_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/4t7rwqs2wqlp2)
- [elasticsearch-periodic-platform-support #3416 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/5cg636fjc2eeu)
- [elasticsearch-pull-request #26046 / part-1-windows](https://gradle-enterprise.elastic.co/s/dj72kiwwkddkg)

**Reproduction Line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testSystemPropertyDisabled'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.nativeaccess.VectorSystemPropertyTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Users\buildkite\.gradle\jdks\oracle_corporation-22-amd64-windows\jdk-22.0.1\bin\java" "execute")
```

**Issue Reasons:**
- [main] 4 failures in test testSystemPropertyDisabled (2.0% fail rate in 205 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit fixes and unmutes VectorSystemPropertyTests.

~I reverted the tests's superclass to `LuceneTestCase`, since there is no ES specifics needed. Rather than using the `@WithoutSecurityManager` anno, I created a test-specific `PrivilegedOperations.ProcessBuilderStart`, to avoid any security manager related permission issue.  If it still fails, then the issue is with file execute permission or process fork_and_exec restrictions.~

closes: https://github.com/elastic/elasticsearch/issues/110949

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
The test now fails with:

```
> Task :libs:native:test
VectorSystemPropertyTests > testSystemPropertyDisabled FAILED
    java.io.IOException: Cannot run program "C:\Users\buildkite\.gradle\jdks\oracle_corporation-22-amd64-windows.2\bin\java": CreateProcess error=1816, Not enough quota is available to process this command
        at __randomizedtesting.SeedInfo.seed([2E86C8E44FCD0D8E:5B42A2047C0D8BCB]:0)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:907)
        at org.elasticsearch.test.PrivilegedOperations.ProcessBuilderStart(PrivilegedOperations.java:87)
        at org.elasticsearch.nativeaccess.VectorSystemPropertyTests.testSystemPropertyDisabled(VectorSystemPropertyTests.java:55)
        Caused by:
        java.io.IOException: CreateProcess error=1816, Not enough quota is available to process this command
            at java.base/java.lang.ProcessImpl.create(Native Method)
            at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:500)
            at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
            at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
            ... 5 more
```

Is there some memory restriction in the environment or something ?

**Comment by ChrisHegarty** [comment]
We can just skip Windows, there is no native scorer on Windows anyway.

File: libs/native/src/test/java/org/elasticsearch/nativeaccess/VectorSystemPropertyTests.java [hunk 1]
```diff
@@ -27,13 +28,15 @@
 import static org.hamcrest.Matchers.containsString;
 import static org.hamcrest.Matchers.equalTo;
 
-@WithoutSecurityManager
-public class VectorSystemPropertyTests extends ESTestCase {
+public class VectorSystemPropertyTests extends LuceneTestCase {
```
Comment (rjernst) [inline libs/native/src/test/java/org/elasticsearch/nativeaccess/VectorSystemPropertyTests.java:31]: IMO we should keep ESTestCase as the base. Although I know we use LuceneTestCase in some places, having two different base classes makes building common test infrastructure difficult.

Other than the issue of needing to skip windows (and as you say, this wasn't supported on windows anyways), is there something about ESTestCase that inherently makes this test need LuceneTestCase?

Comment (rjernst) [reply libs/native/src/test/java/org/elasticsearch/nativeaccess/VectorSystemPropertyTests.java:31]: `tests.system_call_filter` is the recommended approach (along with disabling security manager). For example, we disable syscall filters in the server cli tests since we need to invoke java processes.

Comment (ChrisHegarty) [reply libs/native/src/test/java/org/elasticsearch/nativeaccess/VectorSystemPropertyTests.java]: Ok, cool. I updated the PR to use `tests.system_call_filter`, and keep the anno.

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM
