### PR TITLE
SQL: Failing Group By queries due to different ExpressionIds

### LINKED ISSUE #33361: SQL: grouping by a CASTed value doesn't work
The following query (where `hire_date` is of type DATE) will throw an exception - `SELECT CAST(YEAR(hire_date) AS VARCHAR) FROM test_emp GROUP BY CAST(YEAR(hire_date) AS VARCHAR) LIMIT 1`:

```
Server error [Server sent bad type [folding_exception]. Original type was [line 1:8: Cannot find grouping for 'CAST(YEAR(hire_date [UTC]))']. [FoldingException[line 1:8: Cannot find grouping for 'CAST(YEAR(hire_date [UTC]))']
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:310)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:195)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:188)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:182)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$10(Node.java:180)
        at org.elasticsearch.xpack.sql.tree.Node.transformChildren(Node.java:201)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:180)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:188)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:548)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:544)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:155)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130)
        at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:81)
        at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:38)
        at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:28)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:147)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:143)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:131)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.xpack.sql.analysis.index.IndexResolver.lambda$resolveWithSameMapping$3(IndexResolver.java:239)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:66)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:62)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:172)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.onResponse(TransportMasterNodeAction.java:169)
        at org.elasticsearch.action.admin.indices.get.TransportGetIndexAction.doMasterOperation(TransportGetIndexAction.java:142)
        at org.elasticsearch.action.admin.indices.get.TransportGetIndexAction.doMasterOperation(TransportGetIndexAction.java:50)
        at org.elasticsearch.action.support.master.info.TransportClusterInfoAction.masterOperation(TransportClusterInfoAction.java:52)
        at org.elasticsearch.action.support.master.info.TransportClusterInfoAction.masterOperation(TransportClusterInfoAction.java:34)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:109)
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:189)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:135)
```

whereas aliasing the CAST and using the alias inside the GROUP by works - `SELECT CAST(YEAR(hire_date) AS VARCHAR) c FROM test_emp GROUP BY c LIMIT 1;`

Trying the failing query from above with the `translate` API gives the following:

```
{
    "error": {
        "root_cause": [
            {
                "type": "folding_exception",
                "reason": "line 1:8: Cannot find grouping for 'CAST(YEAR(hire_date [UTC]))'"
            }
        ],
        "type": "folding_exception",
        "reason": "line 1:8: Cannot find grouping for 'CAST(YEAR(hire_date [UTC]))'"
    },
    "status": 400
}
```

### LINKED ISSUE #34543: SQL: grouping by values resulting from fields compared with constants
At the moment something like `select (3 < languages) as multi_language, count(*) from test_emp group by multi_language` doesn't work.  The exception is not entirely accurate in my opinion and the ES query used  in this scenario is very similar with the one from https://github.com/elastic/elasticsearch/issues/34400.

```
{
  "size": 0,
  "aggs": {
    "NAME": {
      "composite": {
        "sources": [
          {
            "product": {
              "terms": {
                "script": {
                  "source": "doc['languages'].value > 3",
                  "lang": "painless"
                }
              }
            }
          }
        ]
      }
    }
  }
}
```

### LINKED ISSUE #36074: SQL: Cannot GROUP BY when constant function is used
```
SELECT PI() * emp_no
FROM test_emp
GROUP BY 1;
```
throws:
```
java.sql.SQLException: Server sent bad type [folding_exception]. Original type was [line 1:13: Cannot find grouping for 'PI * (emp_no)']. [FoldingException[line 1:13: Cannot find grouping for 'PI * (emp_no)']
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:311)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:196)
	at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:188)
	at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:182)
	at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:188)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:554)
	at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:550)
	at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82)
	at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:155)
	at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130)
	at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:82)
	at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:38)
	at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:28)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:153)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:149)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
	at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:137)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
	at org.elasticsearch.xpack.sql.analysis.index.IndexResolver.lambda$resolveAsMergedMapping$3(IndexResolver.java:246)
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)
	at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:97)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### LINKED ISSUE #37044: SQL: grouping by an INTERVAL formula throws error
`date2` is a `date` field in ES. If I remove `1 *` and make the formula to be an interval added to a date, then I get the exception from https://github.com/elastic/elasticsearch/issues/37042. So, the multiplication seems to be the issue here...

```
sql> SELECT date2 + 1 * INTERVAL '1' DAY FROM calcs GROUP BY 1;                                                                                                                          
Server error [Server sent bad type [folding_exception]. Original type was [line 1:14: Cannot find grouping for '(date2) + 1 * INTERVAL '1' DAY']. [FoldingException[line 1:14: Cannot fin
d grouping for '(date2) + 1 * INTERVAL '1' DAY']                                                                                                                                         
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:312)                                                                                      
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:197)                                                                                      
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:188)                                                                                                    
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:182)                                                                                                              
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:188)                                                                                                              
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:560)                                                                                       
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:556)                                                                                       
        at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82)                                                                                     
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158)                                                                                          
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130)                                                                                                  
        at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:83)                                                                                                     
        at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:38)                                                                                                         
        at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:28)                                                                                                             
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:153)                                                                                     
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)                                                                                                  
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:149)                                                                                    
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)                                                                                                  
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:137)                                                                                       
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)                                                                                                  
        at org.elasticsearch.xpack.sql.analysis.index.IndexResolver.lambda$resolveAsMergedMapping$3(IndexResolver.java:246)                                                              
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:60)                                                                                                  
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)                                                                                        
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:60)                                                                                        
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$1(TransportFieldCapabilitiesAction.java:84)                                              
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:97)                                                    
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:93)                                                    
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)                                                                                        
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:60)                                                                                        
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:271)                              
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:255)                              
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1094)                                                         
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1175)                                                                
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1155)                                                                   
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54)                                                                                   
        at org.elasticsearch.action.support.HandledTransportAction$ChannelActionListener.onResponse(HandledTransportAction.java:93)                                                      
        at org.elasticsearch.action.support.HandledTransportAction$ChannelActionListener.onResponse(HandledTransportAction.java:77)                                                      
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:117)                                                         
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759)                                                        
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)                                                                                       
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)                                                                                     
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                                                                                     
        at java.base/java.lang.Thread.run(Thread.java:834)                                                                                                                               
]]                                                                                                                                                                                       
```

### LINKED ISSUE #40001: SQL: GROUP BY with function group returns error
This following statement works as expected: 
```select convert(truncate(extract(YEAR from "timestamp")), SQL_BIGINT) as yr from "kibana_sample_data_flights" group by yr;```

When the `yr` is swapped with the group expression it replaces, an exception is raised:
```
sql> select convert(truncate(extract(YEAR from "timestamp")), SQL_BIGINT) as yr from "kibana_sample_data_flights" group by convert(truncate(extract(YEAR from "timestamp")), SQL_BIGINT);
Server error [Server sent bad type [folding_exception]. Original type was [line 1:8: Cannot find grouping for 'convert(truncate(extract(YEAR from "timestamp")), SQL_BIGINT)']. [FoldingException[line 1:8: Cannot find grouping for 'convert(truncate(extract(YEAR from "timestamp")), SQL_BIGINT)']
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:321)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:206)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:196)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$10(Node.java:188)
        at org.elasticsearch.xpack.sql.tree.Node.transformChildren(Node.java:209)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:188)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:196)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:589)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:585)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130)
        at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:85)
        at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:38)
        at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:28)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:156)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:152)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$preAnalyze$2(SqlSession.java:140)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
        at org.elasticsearch.xpack.sql.analysis.index.IndexResolver.lambda$resolveAsMergedMapping$3(IndexResolver.java:245)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction.lambda$doExecute$1(TransportFieldCapabilitiesAction.java:84)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:97)
        at org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesAction$1.onResponse(TransportFieldCapabilitiesAction.java:93)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:68)
        at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:271)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:255)
        at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1108)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1189)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1169)
        at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54)
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:47)
        at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:30)
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:117)
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
]]
```

### LINKED ISSUE #40240: SQL: CAST and CONVERT sporadically generate errors when grouped by
```
sql> SELECT CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT) FROM test_emp GROUP BY CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT);
Server error [Server sent bad type [folding_exception]. Original type was [line 1:8: Cannot find grouping for 'CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT)']. [FoldingException[line 1:8: Cannot find grouping for 'CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT)']
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:321)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:206)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:196)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:196)
```

And same goes for CAST to the same data type:

```
sql> SELECT CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT) FROM test_emp GROUP BY CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT);
Server error [Server sent bad type [folding_exception]. Original type was [line 1:8: Cannot find grouping for 'CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT)']. [FoldingException[line 1:8: Cannot find grouping for 'CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT)']
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:321)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:206)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:196)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190)
```

BUT, same query with a different type to be casted to works:

```
sql> SELECT CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS INTEGER) FROM test_emp GROUP BY CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS INTEGER);
ABS(EXTRACT(YEAR FROM "birth_date"))                                                                                                           
------------------------------------                                                                                                           
null                                                                                                                                           
1952                                                                                                                                           
1953                                                                                                                                           
1954                                                                                                                                           
1955                                                                                                                                           
1956                                                                                                                                           
```

### LINKED ISSUE #41159: SQL: GROUPing BY EXTRACT of TIMESTAMP fails
This one might be similar (or identical with https://github.com/elastic/elasticsearch/issues/40639), but not 100% sure.

`SELECT EXTRACT(MINUTE FROM CONVERT("calcs"."datetime0", SQL_TIMESTAMP)) AS x FROM "calcs" GROUP BY x` fails with:

```
Server error [Server sent bad type [folding_exception]. Original type was [line 1:8: Cannot find grouping for 'EXTRACT(MINUTE FROM CONVERT("calcs"."datetime0", TIMESTAMP))']. [FoldingException[line 1:8: Cannot find grouping for 'EXTRACT(MINUTE FROM CONVERT("calcs"."datetime0", TIMESTAMP))']
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:319)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldAggregate.rule(QueryFolder.java:203)
        at org.elasticsearch.xpack.sql.tree.Node.lambda$transformUp$11(Node.java:196)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:190)
        at org.elasticsearch.xpack.sql.tree.Node.transformUp(Node.java:196)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:586)
        at org.elasticsearch.xpack.sql.planner.QueryFolder$FoldingRule.apply(QueryFolder.java:582)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor$Transformation.<init>(RuleExecutor.java:82)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.executeWithInfo(RuleExecutor.java:158)
        at org.elasticsearch.xpack.sql.rule.RuleExecutor.execute(RuleExecutor.java:130)
        at org.elasticsearch.xpack.sql.planner.QueryFolder.fold(QueryFolder.java:82)
        at org.elasticsearch.xpack.sql.planner.Planner.foldPlan(Planner.java:38)
        at org.elasticsearch.xpack.sql.planner.Planner.plan(Planner.java:28)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$physicalPlan$4(SqlSession.java:156)
        at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
        at org.elasticsearch.xpack.sql.session.SqlSession.lambda$optimizedPlan$3(SqlSession.java:152)
```

```
SELECT {fn CONVERT({fn TRUNCATE({fn EXTRACT(DAY FROM {fn CONVERT("calcs"."datetime0", SQL_TIMESTAMP)})},0)}, SQL_BIGINT)} AS x
FROM "calcs"
GROUP BY 1
```

```
SELECT {fn CONVERT({fn TRUNCATE({fn EXTRACT(YEAR FROM {fn CONVERT("calcs"."datetime0", SQL_TIMESTAMP)})},0)}, SQL_BIGINT)} AS x
FROM "calcs"
GROUP BY 1
```

### LINKED ISSUE #42041: SQL: Failing Group By queries due to different ExpressionIds
This is a meta issue to track the Group By queries that fail in the `QueryFolder`
because of the different ExpressionIds which results in not being able to find
the same expression in the `groupingContext` map.

- [ ] #41159
- [ ] #40001
- [ ] #40240
- [ ] #37044
- [ ] #36074
- [ ] #34543
- [ ] #33361
- [ ] https://github.com/elastic/elasticsearch/issues/46316

### LINKED ISSUE #46316: SQL: GROUPing BY conditional more complex CASE WHEN fails
The following query fails `SELECT (CASE WHEN bool0 = TRUE THEN '1' WHEN NOT bool0 = TRUE THEN '0' ELSE CAST(NULL AS STRING) END) AS x FROM calcs GROUP BY x` with

```
{
    "error": {
        "root_cause": [
            {
                "type": "folding_exception",
                "reason": "line 1:9: Cannot find grouping for 'CASE WHEN bool0 = TRUE THEN '1' WHEN NOT bool0 = TRUE THEN '0' ELSE CAST(NULL AS STRING) END'"
            }
        ],
        "type": "folding_exception",
        "reason": "line 1:9: Cannot find grouping for 'CASE WHEN bool0 = TRUE THEN '1' WHEN NOT bool0 = TRUE THEN '0' ELSE CAST(NULL AS STRING) END'"
    },
    "status": 400
}
```

While a simpler one - `SELECT (CASE WHEN bool0 = TRUE THEN '1' ELSE '0' END) AS x FROM calcs GROUP BY x` works as expected.

### PR DESCRIPTION
**Pull request by emasab**
Fix an issue that arises from the use of ExpressionIds as keys in a lookup map
that helps the `QueryTranslator` to identify the grouping columns. The issue is
that the same expression in different parts of the query (SELECT clause and GROUP BY clause) 
ends up with different ExpressionIds so the lookup fails. So, instead of ExpressionIds
use the hashCode() of NamedExpression.

Fixes: #41159
Fixes: #40001
Fixes: #40240
Fixes: #33361
Fixes: #46316
Fixes: #36074
Fixes: #34543
Fixes: #37044

Fixes: #42041

### CODE REVIEW

**Review by matriv — COMMENTED** [review]
Hello @emasab!

First of all apologies for the delay on picking up this PR and many thanks for your effort here.
The issue with the ExpressionIds is quite complicated and there are plans to solve it overall through a substantial refactoring. Your changes though, solve a substantial subset of the issues 
so we decided to go ahead and proceed with this fix. I've changed the title and description of the PR and link to the issues that it fixes.

For some cases (without aliases or numeric refs) queries still fail, e.g.:
```SELECT PI() * emp_no FROM test_emp GROUP BY PI() * emp_no ORDER BY PI() * emp_no LIMIT 10```

Moreover I'd like to ask from you to add some integration tests for the issues that this fix addresses:
In `agg.sql-spec` file: https://github.com/emasab/elasticsearch/blob/bugfix/42041-failing-group-by-queries/x-pack/plugin/sql/qa/src/main/resources/agg.sql-spec#L52 the following:
```
groupByCastScalar
SELECT CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT) FROM test_emp GROUP BY CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT) ORDER BY CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT) NULLS FIRST;
groupByCastScalarWithAlias
SELECT CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT) as "cast" FROM test_emp GROUP BY "cast" ORDER BY "cast" NULLS FIRST;
```
and in `agg.csv-spec` file: https://github.com/emasab/elasticsearch/blob/bugfix/42041-failing-group-by-queries/x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec#L220
the following:
```
// Fails for H2
groupByCastScalarWithNumericRef
SELECT CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT) FROM test_emp GROUP BY 1 ORDER BY 1 NULLS FIRST;

CAST(ABS(EXTRACT(YEAR FROM "birth_date")) AS BIGINT):l
------------------------------------------------------
null
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
;

groupByConvertScalar
SELECT CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT) FROM test_emp GROUP BY CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT) ORDER BY CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT) NULLS FIRST;


CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT):l
-----------------------------------------------------------
null
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
;


groupByConvertScalarWithAlias
SELECT CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT) as "convert" FROM test_emp GROUP BY "convert" ORDER BY "convert" NULLS FIRST;

convert:l
---------
null
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
;

groupByConvertScalarWithNumericRef
SELECT CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT) FROM test_emp GROUP BY 1 ORDER BY 1 NULLS FIRST;

CONVERT(ABS(EXTRACT(YEAR FROM "birth_date")), SQL_BIGINT):l
-----------------------------------------------------------
null
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
;

// AwaitsFix https://github.com/elastic/elasticsearch/issues/36074
//groupByConstantScalar
//SELECT PI() * emp_no FROM test_emp GROUP BY PI() * emp_no ORDER BY PI() * emp_no LIMIT 10;

//PI() * emp_no:d
//---------------
//31419.0681285515
//31422.2097212051
//31425.3513138587
//31428.4929065123
//31431.6344991659
//31434.7760918195
//31437.9176844731
//31441.0592771266
//31444.2008697802
//31447.3424624338
//;

groupByConstantScalarWithAlias
SELECT PI() * emp_no AS "value" FROM test_emp GROUP BY value ORDER BY value LIMIT 10;

value:d
-------
31419.0681285515
31422.2097212051
31425.3513138587
31428.4929065123
31431.6344991659
31434.7760918195
31437.9176844731
31441.0592771266
31444.2008697802
31447.3424624338
;

groupByConstantScalarWithNumericRef
SELECT PI() * emp_no FROM test_emp GROUP BY 1 ORDER BY 1 LIMIT 10;

PI() * emp_no:d
---------------
31419.0681285515
31422.2097212051
31425.3513138587
31428.4929065123
31431.6344991659
31434.7760918195
31437.9176844731
31441.0592771266
31444.2008697802
31447.3424624338
;
```

File: x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java [hunk 1]
```diff
@@ -779,6 +779,85 @@ public void testAllCountVariantsWithHavingGenerateCorrectAggregations() {
                         + "\"gap_policy\":\"skip\"}}}}}"));
     }
 
+    public void testGroupSelection() {
```
Comment (matriv) [inline x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/planner/QueryTranslatorTests.java]: It would be great to split this up to more methods with more descriptive names and add more tests so that all 3 cases (no alias, alias, numeric reference) are covered, similarly to the integration tests in my comment: https://github.com/elastic/elasticsearch/pull/43072#pullrequestreview-267772000
Of course some of the cases, as mentioned, should be skipped as they won't work even with this fix.

**Comment by emasab** [comment]
Hi @matriv , happy to hear from you. I understand, the checks to do are a lot before giving an ok. I'm going to include these integration tests and see if there is a simple fix for the failing query that you've highlighted.

**Comment by emasab** [comment]
I've fixed the groupByConstantScalar case too, mainly unifying the semantic of NamedExpression.equals to that of NamedExpression.hashCode . The ExpressionId is still there but is used only as a unique identifier for the object instance. I've changed the semantic of Failure.equals because now two NamedExpression are equal if they have the same tree even if the position in the source is different so Failure takes into account the source position not the parsed node.

**Comment by emasab** [comment]
Sorry, the latest commit

https://github.com/elastic/elasticsearch/pull/43072/commits/490201553ecff596ea5613dd3a4d616ed84ba094

even if more correct theorically because of the difference between hashCode and equals, solves the specified case and passes the unit tests, causes a lot of failures with the integration test org.elasticsearch.xpack.sql.qa.single_node.JdbcSqlSpecIT. The previous one 

https://github.com/elastic/elasticsearch/pull/43072/commits/87205638b7dd46e0ac7a9894ebee4a99561fac5b

is not affected

**Comment by emasab** [comment]
In the latest commit I've solved the integration tests failures while keeping the equals and hashCode methods consistent. The order by constant scalar is still excluded, With my previous commit there was an incomplete change to ResolveMissingRefs that made it work but I've reverted it because this other query failed:

`SELECT last_name FROM "test_emp" ORDER BY birth_date::TIME, emp_no LIMIT 5`

**Comment by emasab** [comment]
In the latest commit these is a fix for groupByConstantScalar case with ORDER BY, while keeping the equals consistent with the hashCode, and the integration tests successful

**Comment by emasab** [comment]
rebased on current master

**Comment by emasab** [comment]
In the latest commit there is a fix for the results ordering when there is a grouped ScalarFunctionAttribute in the ORDER BY clause, like:
`
SELECT PI() * emp_no FROM test_emp GROUP BY PI() * emp_no ORDER BY PI() * emp_no DESC LIMIT 10;`

**Comment by emasab** [comment]
rebased

**Comment by emasab** [comment]
solved issue with Pivot query and rebased

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java [hunk 2]
```diff
@@ -102,6 +103,32 @@ public static AttributeSet references(List<? extends Expression> exps) {
         return set;
     }
 
+    public static AttributeSet referencesExcept(Set<? extends Expression> exps,
+                                                AttributeSet except) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java]: could be on the same line I guess?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/gen/script/Param.java [hunk 3]
```diff
@@ -24,4 +26,18 @@ T value() {
     public String toString() {
         return format(null, "{{}={}}", prefix(), value);
     }
+
+
+    @Override
+    public int hashCode() {
+        if(this.value==null) return Objects.hashCode(null);
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/gen/script/Param.java]:
```suggestion
        if (this.value == null) {
            return Objects.hashCode(null);
        }
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/gen/script/Param.java [hunk 4]
```diff
@@ -24,4 +26,18 @@ T value() {
...
+        return this.value.hashCode();
+    }
+
+    @Override
+    public boolean equals(Object obj) {
+        if(!(obj instanceof  Param)) return false;
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/gen/script/Param.java]:
```suggestion
        if ((obj instanceof  Param) == false) {
            return false;
        }
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/gen/script/Param.java [hunk 5]
```diff
@@ -24,4 +26,18 @@ T value() {
...
+        if(this.value==null) return ((Param)obj).value == null;
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/gen/script/Param.java]:
```suggestion
        if (this.value == null) {
            return ((Param)obj).value == null;
        }
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/QueryContainer.java [hunk 6]
```diff
@@ -109,7 +110,7 @@ public QueryContainer(Query query,
         this.query = query;
         this.aggs = aggs == null ? Aggs.EMPTY : aggs;
         this.fields = fields == null || fields.isEmpty() ? emptyList() : fields;
-        this.aliases = aliases == null || aliases.isEmpty() ? AttributeMap.emptyAttributeMap() : aliases;
+        this.aliases = aliases == null || aliases.isEmpty() ? new HashMap<>() : aliases;
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/QueryContainer.java]: Why not `Collections.emptyMap()`?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Aggs.java [hunk 7]
```diff
@@ -121,16 +123,23 @@ public Aggs addAgg(PipelineAgg pipelineAgg) {
...
 
-    public GroupByKey findGroupForAgg(String groupOrAggId) {
+    public GroupByKey findGroupForAgg(Attribute attr) {
+        String id = attr.id().toString();
         for (GroupByKey group : this.groups) {
-            if (groupOrAggId.equals(group.id())) {
+            if (id.equals(group.id())) {
                 return group;
             }
+            if(attr instanceof ScalarFunctionAttribute) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Aggs.java]:
```suggestion
            if (attr instanceof ScalarFunctionAttribute) {
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Aggs.java [hunk 8]
```diff
@@ -121,16 +123,23 @@ public Aggs addAgg(PipelineAgg pipelineAgg) {
...
+                ScalarFunctionAttribute sfa = (ScalarFunctionAttribute) attr;
+                if (group.script()!=null && group.script().equals(sfa.script())) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/agg/Aggs.java]:
```suggestion
                if (group.script() !=null && group.script().equals(sfa.script())) {
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/gen/script/Params.java [hunk 9]
```diff
@@ -124,4 +124,15 @@ else if (p instanceof Var) {
...
\ No newline at end of file
+
+    @Override
+    public int hashCode() {
+        return this.params.hashCode();
+    }
+
+    @Override
+    public boolean equals(Object obj) {
+        if(!(obj instanceof  Params)) return false;
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/gen/script/Params.java]:
```suggestion
        if ((obj instanceof  Params) == false) {
            return false;
        }
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java [hunk 10]
```diff
@@ -47,7 +48,20 @@ public Pivot(Source source, LogicalPlan child, Expression column, List<NamedExpr
 
     @Override
     protected Pivot replaceChild(LogicalPlan newChild) {
-        return new Pivot(source(), newChild, column, values, aggregates);
+
+       java.util.function.Function<Expression, Expression> withQualifierNull = (Expression e)-> {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java]: I would extract this to a private static attribute.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java [hunk 11]
```diff
@@ -47,7 +48,20 @@ public Pivot(Source source, LogicalPlan child, Expression column, List<NamedExpr
 
     @Override
     protected Pivot replaceChild(LogicalPlan newChild) {
-        return new Pivot(source(), newChild, column, values, aggregates);
+
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java]: Could you please add some comment on why this is needed?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java [hunk 12]
```diff
@@ -102,6 +103,32 @@ public static AttributeSet references(List<? extends Expression> exps) {
...
+        AttributeSet ret = new AttributeSet();
+        while(exps.size()>0){
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java]: I don't get the logic here, why do you need the while loop and revisit the `exps` which have become `filteredExps`?

**Comment by matriv** [comment]
@elasticmachine test this please

**Review by matriv — COMMENTED** [review]
Hello @emasab,

Once again thanks a lot for your effort here.
There has been delay in getting back to you, as there were other features and bugs in our plate, and as stated before there is an ongoing effort of complete refactoring in the area of NamedExpression and ExpressionIds.

The state of the PR though looks good overall to me and would be nice to fix those issues independently of the refactoring that might take more time to be ready.

I left another round of comments and I'd like to do some more testing myself using your branch.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java (hunk 12 above)
Comment (emasab) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java]: It's a breadth-first search where some nodes are removed during the traversal. At each loop the exps represents the previous list of tree nodes and filteredExps the expressions that aren't in the except set. At the end of the loop exps is replaced with the children of each node. When a leaf is found, its references are added to ret.

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java (hunk 10 above)
Comment (emasab) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java]: done

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java (hunk 11 above)
Comment (emasab) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java]: done

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java [hunk 13]
```diff
@@ -40,14 +41,38 @@ public Pivot(Source source, LogicalPlan child, Expression column, List<NamedExpr
...
     }
 
     @Override
     protected Pivot replaceChild(LogicalPlan newChild) {
-        return new Pivot(source(), newChild, column, values, aggregates);
+
+        Expression newColumn = column;
+        List<NamedExpression> newAggregates = aggregates;
+
+        if(newChild instanceof EsRelation) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java]:
```suggestion
        if (newChild instanceof EsRelation) {
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java [hunk 14]
```diff
@@ -40,14 +41,38 @@ public Pivot(Source source, LogicalPlan child, Expression column, List<NamedExpr
         this.aggregates = aggregates;
     }
 
+    private static Expression withQualifierNull(Expression e){
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java]:
```suggestion
    private static Expression withQualifierNull(Expression e) {
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java [hunk 15]
```diff
@@ -40,14 +41,38 @@ public Pivot(Source source, LogicalPlan child, Expression column, List<NamedExpr
...
+
     @Override
     protected NodeInfo<Pivot> info() {
         return NodeInfo.create(this, Pivot::new, child(), column, values, aggregates);
     }
 
     @Override
     protected Pivot replaceChild(LogicalPlan newChild) {
-        return new Pivot(source(), newChild, column, values, aggregates);
+
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/plan/logical/Pivot.java]:
```suggestion
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java [hunk 16]
```diff
@@ -102,6 +103,31 @@ public static AttributeSet references(List<? extends Expression> exps) {
         return set;
     }
 
+    public static AttributeSet referencesExcept(Set<? extends Expression> exps, AttributeSet except) {
+        AttributeSet ret = new AttributeSet();
+        while(exps.size()>0){
+
+            Set<Expression> filteredExps = new LinkedHashSet<>();
+            for(Expression exp: exps){
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java]:
```suggestion
            for (Expression exp : exps) {
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java [hunk 17]
```diff
@@ -102,6 +103,31 @@ public static AttributeSet references(List<? extends Expression> exps) {
...
+                Expression attr = Expressions.attribute(exp);
+                if(attr==null || !except.contains(attr)){
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java]:
```suggestion
                if (attr == null || (except.contains(attr) == false)) {
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java [hunk 18]
```diff
@@ -102,6 +103,31 @@ public static AttributeSet references(List<? extends Expression> exps) {
         return set;
     }
 
+    public static AttributeSet referencesExcept(Set<? extends Expression> exps, AttributeSet except) {
+        AttributeSet ret = new AttributeSet();
+        while(exps.size()>0){
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java]:
```suggestion
        while (exps.size() > 0) {
```

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java [hunk 19]
```diff
@@ -102,6 +103,31 @@ public static AttributeSet references(List<? extends Expression> exps) {
         return set;
     }
 
+    public static AttributeSet referencesExcept(Set<? extends Expression> exps, AttributeSet except) {
```
Comment (matriv) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java]: Maybe a name with a verb, something `filterReferences` ?

**Review by matriv — COMMENTED** [review]
Thx for addressing the comments @emasab 
I left a few more, minor, regarding code formatting.

File: x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec [hunk 20]
```diff
@@ -246,6 +246,194 @@ TRUNCATE(YEAR("birth_date"), -2)
...
+null        |4.1415926535
+null        |3.1415926535
+F           |5.1415926535
+F           |4.1415926535
+F           |3.1415926535
+M           |5.1415926535
+M           |4.1415926535
+;
+
+groupByFieldAndConstantScalarWithAliasWithOrderByDescWithNullsFirst
```
[the remark this answers is not in the document]
Comment (matriv) [reply x-pack/plugin/sql/qa/src/main/resources/agg.csv-spec]: @emasab please don't forget to check this.

**Comment by emasab** [comment]
> Thx for addressing the comments @emasab
> I left a few more, minor, regarding code formatting.

I've set up the save action and the eclipseformat :)

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java (hunk 19 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java]: I would name it `excluded`.

Comment (emasab) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/expression/Expressions.java]: ok

**Review by matriv — APPROVED** [review]
LGTM. Thank you @emasab for your work, your patience and the effort and time spent on addressing the comments.

**Comment by matriv** [comment]
@elasticmachine test this please
