### PR TITLE
Remove `MockSinglePrioritizingExecutor`

### LINKED ISSUE #86880: [CI] VotingOnlyNodeCoordinatorTests testDoesNotElectVotingOnlyMasterNode failing
NB this doesn't reproduce on JDK18, but does on JDK19-ea:

```
$ $JAVA19_HOME/bin/java -version
openjdk version "19-ea" 2022-09-20
OpenJDK Runtime Environment (build 19-ea+22-1598)
OpenJDK 64-Bit Server VM (build 19-ea+22-1598, mixed mode, sharing)
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/znpdl3ta6vtjk/tests/:x-pack:plugin:voting-only-node:test/org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodeCoordinatorTests/testDoesNotElectVotingOnlyMasterNode

**Reproduction line:**
`./gradlew ':x-pack:plugin:voting-only-node:test' --tests "org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodeCoordinatorTests.testDoesNotElectVotingOnlyMasterNode" -Dtests.seed=4E0A5B0977C38D37 -Dtests.locale=ar-QA -Dtests.timezone=Australia/Yancowinna -Druntime.java=19`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodeCoordinatorTests&tests.test=testDoesNotElectVotingOnlyMasterNode

**Failure excerpt:**
```
java.lang.AssertionError: leaders
Expected: not an empty collection
     but: was <[]>

  at __randomizedtesting.SeedInfo.seed([4E0A5B0977C38D37:986A4BB31635BAE3]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.getAnyLeader(AbstractCoordinatorTestCase.java:786)
  at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:558)
  at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:539)
  at org.elasticsearch.cluster.coordination.votingonly.VotingOnlyNodeCoordinatorTests.testDoesNotElectVotingOnlyMasterNode(VotingOnlyNodeCoordinatorTests.java:50)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:1585)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
`MockSinglePrioritizingExecutor` contains a hack that stops working with
JDK19 which introduces a different way to start threads. This commit
removes the hack and captures the tasks to be executed as they're passed
to the executor instead.

It turns out this hack was also apparently swallowing some tripping
assertions, so this commit fixes those assertions.

Closes #86880

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/part-1 (known issue with Persian analyzer)

File: test/framework/src/main/java/org/elasticsearch/common/util/concurrent/DeterministicTaskQueue.java [hunk 1]
```diff
@@ -200,6 +200,35 @@ public void advanceTime() {
...
+        ) {
+            @Override
+            public void execute(Runnable command, final TimeValue timeout, final Runnable timeoutCallback) {
+                throw new AssertionError("not implemented");
+            }
+
+            @Override
+            public void execute(Runnable command) {
+                final var wrappedCommand = runnableWrapper.apply(command);
+                runnableWrapper.apply(() -> scheduleNow(wrappedCommand)).run();
```
Comment (henningandersen) [inline test/framework/src/main/java/org/elasticsearch/common/util/concurrent/DeterministicTaskQueue.java:227]: I would prefer to just have an explicit log context string passed in or an explicit wrapper, seems that would be less surprising if we ever use the wrapper for anything but adding the log context.

**Review by henningandersen — APPROVED** [review]
LGTM.

File: test/framework/src/main/java/org/elasticsearch/common/util/concurrent/DeterministicTaskQueue.java (hunk 1 above)
Comment (DaveCTurner) [reply test/framework/src/main/java/org/elasticsearch/common/util/concurrent/DeterministicTaskQueue.java:227]: I know what you mean but we use a non-log-context-related wrapper in the tests - it would be a bit of a pain to assert that we wrap things correctly otherwise especially given the ongoing move away from Log4J APIs.
