### PR TITLE
ESQL: Graceful handling of non-bool condition in the filter

### LINKED ISSUE #100049: ESQL: WHERE should gracefully handle non-boolean statements
### Description

A query like `from employees | where true` is perfectly valid. So is `from employees | where still_hired`. In other words, a simple boolean expression is accepted, even if that expression is a field. For fields `where [field_name]` is the short version of `where [field_name] == true`.

But, for fields that are not booleans `from employees | where salary` for example, ESQL throws an exception:

```
                "type": "class_cast_exception",
                "reason": "class org.elasticsearch.compute.data.IntVectorBlock cannot be cast to class org.elasticsearch.compute.data.BooleanBlock (org.elasticsearch.compute.data.IntVectorBlock and org.elasticsearch.compute.data.BooleanBlock are in unnamed module of loader java.net.FactoryURLClassLoader @c6a692e)"
```

The error message should be more user-friendly, like validating the parameters of regular functions.

### LINKED ISSUE #100409: [ES|QL] Error unhandled when using date math syntax with where command
### Elasticsearch Version

8.11.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

I would expect a clear message for the following ES|QL query:

```
from index | where 1 year
```

But what I get is:

```
[esql] > Unexpected error from Elasticsearch: illegal_argument_exception - Unrecognized class type class java.time.Period
```

### Steps to Reproduce

See above.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by costin**
Improve the Verifier to handle queries with non-boolean expressions
 used in the WHERE clause (where 10)
In the process improve the readability of the Verifier class by
 extracting the checks into their own methods

Fix #100049
Fix #100409

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java [hunk 1]
```diff
@@ -121,87 +122,128 @@ else if (p.resolved()) {
...
+            }
+            checkFilterConditionType(p, failures);
+            checkAggregate(p, failures);
+            checkRegexExtractOnlyOnStrings(p, failures);
+
+            checkRow(p, failures);
+            checkEvalFields(p, failures);
+
+            checkOperationsOnUnsignedLong(p, failures);
+            checkBinaryComparison(p, failures);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Verifier.java:137]: ++ to the refactoring, looks much nicer now.

**Review by alex-spies — COMMENTED** [review]
Took a look for good measure, LGTM!
