### PR TITLE
Make FilterAllocationDecider totally ignore tier-based allocation settings

### LINKED ISSUE #66679: FilterAllocationDecider handles exclude._tier filters not correctly
**Elasticsearch version**: master

**Plugins installed**: []

**JVM version (java -version)**: 14.0.1

**OS version (uname -a if on a Unix-like system)**: Mac OS 10.13.6

**Description of the problem including expected versus actual behavior**:

When we setup a cluster with only one node, and set the node as `data_hot` and `master`:

```
node.roles: [ data_hot, master ]
```
then we set cluster level shard allocation filter: `"cluster.routing.allocation.exclude._tier": "data_cold"`, 
finally, new index'shards canot be allocated because:

```
{
    "index":"z",
    "shard":1,
    "primary":true,
    "current_state":"unassigned",
    "unassigned_info":{
        "reason":"INDEX_CREATED",
        "at":"2020-12-21T09:35:07.850Z",
        "last_allocation_status":"no"
    },
    "can_allocate":"no",
    "allocate_explanation":"cannot allocate because allocation is not permitted to any of the nodes",
    "node_allocation_decisions":[
        {
            "node_id":"c7uiAGEAQTO3lY6MjGAGVQ",
            "node_name":"node1",
            "transport_address":"127.0.0.1:9300",
            "node_attributes":{
                "xpack.installed":"true",
                "transform.node":"false"
            },
            "node_decision":"no",
            "weight_ranking":1,
            "deciders":[
                {
                    "decider":"filter",
                    "decision":"NO",
                    "explanation":"node matches cluster setting [cluster.routing.allocation.exclude] filters [_tier:"data_cold"]"
                }
            ]
        }
    ]
}
```

**Steps to reproduce**:

1. setup a cluster with only one node:

```
node.roles: [ data_hot, master ]
```
2. PUT _cluster/settings

```
{
  "transient": {
    "cluster.routing.allocation.exclude._tier": "data_cold"
  }
}
```

3. Create a new index with setting `index.routing.allocation.include._tier_preference:"data_hot"`
4. GET _cluster/allocation/explain

### PR DESCRIPTION
**Pull request by dakrone**
Previously we treated attribute filtering for `_tier`-prefixed attributes a pass-through, meaning
that they were essentially always treated as matching in `DiscoveryNodeFilters.match`, however, for
exclude settings, this meant that the node was considered to match the node if a `_tier*` filter was
specified.

This commit prunes these attributes from the DiscoveryNodeFilters when considering the filters for
`FilterAllocationDecider` so that they are *only* considered in `DataTierAllocationDecider`.

Resolves #66679

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java [hunk 1]
```diff
@@ -88,6 +89,34 @@ private boolean matchByIP(String[] values, @Nullable String hostIp, @Nullable St
...
+        if (original == null) {
+            return null;
+        }
+
+        Map<String, String[]> newFilters = original.filters.entrySet().stream()
+            // Remove all entries that start with "_tier", as these will be handled elsewhere
+            .filter(entry -> {
+                String attr = entry.getKey();
+                if (attr != null && attr.startsWith("_tier")) {
+                }
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java:108]: oops, I think this is a leftover?

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java [hunk 2]
```diff
@@ -140,9 +140,54 @@ public void testFilterInitialRecovery() {
...
+            .put("index.routing.allocation.require._tier", "data_cold")
+            .put("index.routing.allocation.include._tier", "data_cold")
+            .put("index.routing.allocation.include._tier_preference", "data_cold")
+            .put("index.routing.allocation.exclude._tier", "data_cold")
+            .build(),
+            Settings.builder()
+                .put("cluster.routing.allocation.require._tier", "data_cold")
+                .put("cluster.routing.allocation.include._tier", "data_cold")
+                .put("cluster.routing.allocation.exclude._tier", "data_cold")
+                .build());
```
Comment (andreidan) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java:163]: Should we create a more realistic test case? Or add a bit of documentation as to what is this test testing. I don't understand why should any allocation decision be `YES` when `require._tier` and `exclude._tier` have the same value, yet we assert for `YES` decisions below

File: server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java [hunk 3]
```diff
@@ -88,6 +89,34 @@ private boolean matchByIP(String[] values, @Nullable String hostIp, @Nullable St
         return false;
     }
 
+    /**
+     * Removes any filters that should not be considered, returning a new
+     * {@link DiscoveryNodeFilters} object. If the filtered object has no
+     * filters after trimming, {@code null} is returned.
+     */
+    @Nullable
+    public static DiscoveryNodeFilters trim(@Nullable DiscoveryNodeFilters original) {
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java:98]: nit: maybe we should specify what we are trimming in the method name? (so the `FilterAllocationDecider` code is a bit more readbale without having to step into the `trim` method to see what exactly is removing). Maybe `trimTierFilters` or something similar?

**Review by andreidan — COMMENTED** [review]
Thanks for working on this @dakrone 

I left a couple of questions, but it generally looks good

File: server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java (hunk 1 above)
Comment (dakrone) [reply server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java:108]: whoops yep, leftover from debugging :X I'll remove

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java (hunk 2 above)
Comment (andreidan) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java:163]: Ah, we are testing an impossible configuration to test that it is ignored. Penny dropped eventually :)

File: server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java (hunk 3 above)
Comment (dakrone) [reply server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java:98]: Sure, I can rename that to make it clearer

**Review by andreidan — APPROVED** [review]
LGTM, thanks for fixing this Lee

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java (hunk 2 above)
Comment (dakrone) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/decider/FilterAllocationDeciderTests.java:163]: This is a unit test for only the `FilterAllocationDecider`, so in this case, we add all the `_tier*` settings that should be ignored, so the answer should always be "YES" because there are no filter rules other than the trimmed ones.

I added an integration test for this also.
