### PR TITLE
Tests: Skip Version.CURRENT for static bwc indexes

### LINKED ISSUE #10292: Tests fail when building ES
I've checked out ES source with v1.5.0 tag and when I try to build tests fail with the following tests:
* org.elasticsearch.bwcompat.RestoreBackwardsCompatTests.restoreOldSnapshots
* org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityTests.testAllVersionsTested

This happens on Mac OS X with Java 8 + Maven 3.2.5

The README advises to skip tests, but it's bad practice to routinely do this since this way contributors won't be able to get any confirmation that their code actually works apart from it being syntactically correct.

```
mvn clean package
...
Tests with failures:
  - org.elasticsearch.bwcompat.RestoreBackwardsCompatTests.restoreOldSnapshots
  - org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityTests.testAllVersionsTested


[INFO] JVM J0:     0.67 ..   541.62 =   540.95s
[INFO] JVM J1:     0.67 ..   541.47 =   540.80s
[INFO] JVM J2:     0.67 ..   558.75 =   558.08s
[INFO] JVM J3:     0.67 ..   541.54 =   540.87s
[INFO] Execution time total: 9 minutes 18 seconds
[INFO] Tests summary: 708 suites, 4699 tests, 2 failures, 70 ignored (59 assumptions)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:55 min
[INFO] Finished at: 2015-03-27T10:26:36+02:00
[INFO] Final Memory: 31M/1331M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.1.2:junit4 (tests) on project elasticsearch: Execution tests of goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.1.2:junit4 failed: /Users/marko/projects/3rd-party/elasticsearch/target/junit4-ant-7275726970577951678.xml:16: There were test failures: 708 suites, 4699 tests, 2 failures, 70 ignored (59 assumptions) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
~/projects/3rd-party/elasticsearch (5448160 ✔) ᐅ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)```

### PR DESCRIPTION
**Pull request by rjernst**
The current version is normally a snapshot while in development.
However, when the release process changes the snapshot flag to false,
this causes the static bwc tests to fail because they cannot
find an index for the current version.  Instead, this change
skips the current version, because there is no need to test
a verion's bwc against itself.

closes #10292

### CODE REVIEW

File: src/test/java/org/elasticsearch/bwcompat/OldIndexBackwardsCompatibilityTests.java [hunk 1]
```diff
@@ -79,6 +79,7 @@ public void testAllVersionsTested() throws Exception {
                 Version v = (Version)field.get(Version.class);
                 if (v.snapshot()) continue;
                 if (v.onOrBefore(Version.V_0_20_6)) continue;
+                if (v.equals(Version.CURRENT)) continue;
```
Comment (bleskes) [inline src/test/java/org/elasticsearch/bwcompat/OldIndexBackwardsCompatibilityTests.java]: can we have a comment as to why we do this?

File: src/test/java/org/elasticsearch/bwcompat/RestoreBackwardsCompatTests.java [hunk 2]
```diff
@@ -72,6 +72,7 @@ public void restoreOldSnapshots() throws Exception {
                 Version v = (Version) field.get(Version.class);
                 if (v.snapshot()) continue;
                 if (v.onOrBefore(Version.V_1_0_0_Beta1)) continue;
+                if (v.equals(Version.CURRENT)) continue;
```
Comment (bleskes) [inline src/test/java/org/elasticsearch/bwcompat/RestoreBackwardsCompatTests.java]: can we have a comment as to why we do this?

**Comment by bleskes** [comment]
LGTM. Left one minor comment.

File: src/test/java/org/elasticsearch/bwcompat/OldIndexBackwardsCompatibilityTests.java (hunk 1 above)
Comment (s1monw) [inline src/test/java/org/elasticsearch/bwcompat/OldIndexBackwardsCompatibilityTests.java]: maybe we should now have a method
```
public boolean skipVersion(Version) {
  return a // foo
            || b // bar
            || c; // baz
}
```

seems simpler?

Comment (rjernst) [inline src/test/java/org/elasticsearch/bwcompat/OldIndexBackwardsCompatibilityTests.java]: I think a function is overkill, having the logic in the loop is nice and direct. I added comments.
