### PR TITLE
Limit size of shardDeleteResults

### LINKED ISSUE #116379: Snapshot delete tasks do not complete if blobs-to-delete list exceeds 2GiB
When deleting snapshots, we accumulate a collection of blobs for post-commit deletion in a compressed `ReleasableBytesStreamOutput`, which has a size limit of 2GiB. If we reach this limit then the following message is logged:

```
[2024-11-03T07:36:42,183][WARN ][org.elasticsearch.repositories.blobstore.BlobStoreRepository] [REDACTED] [REDACTED] failed to delete shard data for shard [REDACTED][0]
java.lang.IllegalArgumentException: ReleasableBytesStreamOutput cannot hold more than 2GB of data
    at org.elasticsearch.common.io.stream.BytesStreamOutput.ensureCapacity(BytesStreamOutput.java:173) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.io.stream.BytesStreamOutput.writeBytes(BytesStreamOutput.java:84) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.io.Streams$FlushOnCloseOutputStream.writeBytes(Streams.java:220) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.io.stream.StreamOutput.write(StreamOutput.java:514) ~[elasticsearch-8.15.0.jar:?]
    at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:261) ~[?:?]
    at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210) ~[?:?]
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125) ~[?:?]
    at java.io.BufferedOutputStream.implWrite(BufferedOutputStream.java:222) ~[?:?]
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:200) ~[?:?]
    at org.elasticsearch.common.io.stream.OutputStreamStreamOutput.writeBytes(OutputStreamStreamOutput.java:29) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.io.stream.StreamOutput.writeBytes(StreamOutput.java:108) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.io.stream.StreamOutput.writeString(StreamOutput.java:443) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.io.stream.StreamOutput.writeString(StreamOutput.java:408) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$ShardBlobsToDelete$ShardSnapshotMetaDeleteResult.writeTo(BlobStoreRepository.java:1575) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$ShardBlobsToDelete.addShardDeleteResult(BlobStoreRepository.java:1623) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotsDeletion$IndexSnapshotsDeletion$ShardSnapshotsDeletion.deleteFromShardSnapshotMeta(BlobStoreRepository.java:1318) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotsDeletion$IndexSnapshotsDeletion$ShardSnapshotsDeletion.doRun(BlobStoreRepository.java:1283) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.15.0.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
    at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

If that happens then it looks like `org.elasticsearch.repositories.blobstore.BlobStoreRepository#resolveFilesToDelete` will also throw an exception, and it does so in contexts where such an exception will bubble up the stack without completing the relevant listener:

```
[WARN ][org.elasticsearch.snapshots.SnapshotsService] [REDACTED] [REDACTED] failed to complete snapshot deletion for [REDACTED] from repository [REDACTED]
java.lang.IllegalArgumentException: ReleasableBytesStreamOutput cannot hold more than 2GB of data
    at org.elasticsearch.common.io.stream.BytesStreamOutput.ensureCapacity(BytesStreamOutput.java:173) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.io.stream.BytesStreamOutput.writeBytes(BytesStreamOutput.java:84) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.io.Streams$FlushOnCloseOutputStream.writeBytes(Streams.java:220) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.io.stream.StreamOutput.write(StreamOutput.java:514) ~[elasticsearch-8.15.0.jar:?]
    at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:261) ~[?:?]
    at java.util.zip.DeflaterOutputStream.finish(DeflaterOutputStream.java:226) ~[?:?]
    at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:244) ~[?:?]
    at java.io.FilterOutputStream.close(FilterOutputStream.java:193) ~[?:?]
    at org.elasticsearch.common.io.stream.OutputStreamStreamOutput.close(OutputStreamStreamOutput.java:39) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$ShardBlobsToDelete.getBlobPaths(BlobStoreRepository.java:1638) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotsDeletion.resolveFilesToDelete(BlobStoreRepository.java:1408) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotsDeletion.cleanupUnlinkedShardLevelBlobs(BlobStoreRepository.java:1387) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotsDeletion.lambda$runWithUniqueShardMetadataNaming$1(BlobStoreRepository.java:1091) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:249) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:335) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:249) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.repositories.blobstore.BlobStoreRepository$10.clusterStateProcessed(BlobStoreRepository.java:2886) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.lambda$execute$0(MasterService.java:571) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.cluster.service.MasterService$ExecutionResult.onPublishSuccess(MasterService.java:956) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.cluster.service.MasterService$4.onResponse(MasterService.java:375) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.cluster.service.MasterService$4.onResponse(MasterService.java:370) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:269) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:39) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.15.0.jar:?]
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.15.0.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
    at java.lang.Thread.run(Thread.java:1570) ~[?:?]
    Suppressed: java.lang.IllegalArgumentException: ReleasableBytesStreamOutput cannot hold more than 2GB of data
        at org.elasticsearch.common.io.stream.BytesStreamOutput.ensureCapacity(BytesStreamOutput.java:173) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.common.io.stream.BytesStreamOutput.writeBytes(BytesStreamOutput.java:84) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.common.io.Streams$FlushOnCloseOutputStream.writeBytes(Streams.java:220) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.common.io.stream.StreamOutput.write(StreamOutput.java:514) ~[elasticsearch-8.15.0.jar:?]
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:261) ~[?:?]
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210) ~[?:?]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:125) ~[?:?]
        at java.io.BufferedOutputStream.implFlush(BufferedOutputStream.java:252) ~[?:?]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:240) ~[?:?]
        at java.io.FilterOutputStream.close(FilterOutputStream.java:184) ~[?:?]
        at org.elasticsearch.common.io.stream.OutputStreamStreamOutput.close(OutputStreamStreamOutput.java:39) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$ShardBlobsToDelete.getBlobPaths(BlobStoreRepository.java:1638) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotsDeletion.resolveFilesToDelete(BlobStoreRepository.java:1408) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotsDeletion.cleanupUnlinkedShardLevelBlobs(BlobStoreRepository.java:1387) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotsDeletion.lambda$runWithUniqueShardMetadataNaming$1(BlobStoreRepository.java:1091) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:249) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.action.support.SubscribableListener$SuccessResult.complete(SubscribableListener.java:386) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.action.support.SubscribableListener.tryComplete(SubscribableListener.java:306) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.action.support.SubscribableListener.setResult(SubscribableListener.java:335) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.action.support.SubscribableListener.onResponse(SubscribableListener.java:249) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository$10.clusterStateProcessed(BlobStoreRepository.java:2886) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.lambda$execute$0(MasterService.java:571) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.cluster.service.MasterService$ExecutionResult.onPublishSuccess(MasterService.java:956) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.cluster.service.MasterService$4.onResponse(MasterService.java:375) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.cluster.service.MasterService$4.onResponse(MasterService.java:370) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.action.ActionListenerImplementations$RunAfterActionListener.onResponse(ActionListenerImplementations.java:269) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:32) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:39) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[elasticsearch-8.15.0.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.15.0.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
```

We must avoid leaking this listener on such an exception.

### PR DESCRIPTION
**Pull request by joshua-adams-1**
Modifies `BlobStoreRepository.ShardBlobsToDelete.shardDeleteResults` to have a variable size depending on the remaining heap space rather than a hard-coded 2GB size which caused smaller nodes with less heap space to OOMe.

Relates to #131822
Closes #116379

Closes ES-12540

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 1]
```diff
@@ -1714,13 +1763,18 @@ synchronized void addShardDeleteResult(
                 assert false : e; // no IO actually happens here
                 throw new UncheckedIOException(e);
             }
+            // TODO - Catch the out of memory error
```
Comment (joshua-adams-1) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Do I need to do something here? There is no current `catch` clause for when `.writeTo` fails, and so continuing to do nothing here preserves existing behaviour, but I'm not sure if it falls under the jurisdiction of [ES-12540](https://elasticco.atlassian.net/browse/ES-12540)

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: We can't have `.writeTo` fail, because if it does then the stream will be in a corrupt state and we won't be able to close it gracefully, nor read it back.

Instead, we need to stop even writing to this data structure once it reaches a certain size. There'll be a certain amount of slop in this limit because closing the stream will still flush any remaining data and write the footer, but that only adds a constant amount of overhead so is acceptable.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 2]
```diff
@@ -1678,26 +1682,66 @@ void writeTo(StreamOutput out) throws IOException {
...
+                resources.add(LeakTracker.wrap((Releasable) shardDeleteResults));
+            } else {
+                this.shardDeleteResults = null;
+                this.compressed = null;
+            }
+
+        }
+
+        MemoryMXBean getMemoryMXBean() {
+            return ManagementFactory.getMemoryMXBean();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I don't think we should do this directly here, instead use a `Setting<RelativeByteSizeValue>`.

File: server/src/main/java/org/elasticsearch/common/io/stream/BytesStreamOutput.java [hunk 3]
```diff
@@ -171,8 +177,8 @@ private static void copyToArray(BytesReference bytesReference, byte[] arr) {
     }
 
     protected void ensureCapacity(long offset) {
-        if (offset > Integer.MAX_VALUE) {
-            throw new IllegalArgumentException(getClass().getSimpleName() + " cannot hold more than 2GB of data");
+        if (offset > this.maximumSize) {
+            throw new IllegalArgumentException(getClass().getSimpleName() + " has exceeded it's max size of " + this.maximumSize);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/common/io/stream/BytesStreamOutput.java]: This is still going to fail all writes when the stream reaches capacity, leaving it in a corrupt state. We need to be able to write the last blocks of data to this stream even after we've decided it's full.

I don't think we should be changing the `o.e.common.io.stream` subsystem at all in this PR.

Also nit: `its` not `it's` 😉

Comment (joshua-adams-1) [reply server/src/main/java/org/elasticsearch/common/io/stream/BytesStreamOutput.java]: If we've got a stream that's only 10 bytes away from being full, and we're attempting to write 20 bytes, how can we write this? In my head this warrants an IAE like currently thrown.

>I don't think we should be changing the o.e.common.io.stream subsystem at all in this PR.

How do you see the solution? I considered making a `BoundedBytesStreamOutput` class that had a size and then only wrote the bytes if there was capacity, if this is more aligned with your expectations, but it would have similar logic to this.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/BytesStreamOutput.java]: The super-pedantic solution would be to stop calling `new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed)` before we get to the point where flushing the last blocks of data would grow the stream beyond its limit.

But I don't think we need to be so precise here. Something like this is going to be fine in practice:

```java
if (shardDeleteResults.size() < limit) {
    new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
}
```

Comment (joshua-adams-1) [reply server/src/main/java/org/elasticsearch/common/io/stream/BytesStreamOutput.java]: That makes sense. Do you see any value in moving this logic into a `BoundedBytesStreamOutput` or similar class, where a maximum stream size is defined upfront, and writes only occur if there is capacity? 

I propose this because in the case of #131822, we attempted to write up to 2GB of blobs to a stream in a node with less than 2GB of heap space. For nodes with <2GB heap, surely every stream could result in the same overflow error? Is it not proactive to impose these restrictions now before we OOM in the future? If so, I would see value in having a class that abstracts this logic

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/common/io/stream/BytesStreamOutput.java]: There aren't many other places where we write a potentially-unbounded amount of data to an in-memory stream like this. For instance when constructing an outbound network message we're doing so from a graph of objects that are already in memory, and the wire protocol is typically more efficient than the in-memory layout of objects, so if the node has <2GiB of heap then we can't really get to a point where a transport message exceeds 2GiB. Moreover in that case simply throwing an exception during serialization is a pretty drastic last resort. Instead the caller needs to find a way to send the data it needs in smaller pieces

I'd rather we pushed these concerns to the callers, see e.g. https://github.com/elastic/elasticsearch/issues/124068. There's other problems with network messages being too large that hit even if OOMs aren't an issue, so we need to address these at higher levels.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 4]
```diff
@@ -1706,10 +1752,33 @@ synchronized void addShardDeleteResult(
...
             try {
                 shardGenerationsBuilder.put(indexId, shardId, newGeneration);
-                new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
-                resultCount += 1;
+
+                // Calculate how many bytes we want to write
+                int bytesToWriteIndexId = StreamOutput.bytesInString(indexId.getId());
+                int bytesToWriteShardId = StreamOutput.bytesInVInt(shardId);
+                int bytesToWriteBlobsToDelete = StreamOutput.bytesInStringCollection(blobsToDelete);
+                int totalBytesRequired = bytesToWriteIndexId + bytesToWriteShardId + bytesToWriteBlobsToDelete;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I reckon even this much up-front computation is overly pedantic. The limit is in practice going to be at least 10s-of-MiBs (after compression) and the amount of data we write per entry is almost always going to be no more than a few kiB (before compression). There's also (a bounded amount of) buffering involved in the write process, both in the `BufferedOutputStream` and in zlib itself, which adds up to several kiB that's not counted in `shardDeleteResults.size()`.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I can kinda see an argument for serializing `ShardSnapshotMetaDeleteResult#blobsToDelete` in a streaming fashion (i.e. not a length-prefixed array as it is today) so that we can check the limit before writing each blob name, truncating the collection if we hit the limit. I still think this is in YAGNI territory, these collections just aren't that large in practice anyway, but maybe if it's not too complex we can do that to put a firm constant bound on this memory usage?

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 5]
```diff
@@ -1678,26 +1687,63 @@ void writeTo(StreamOutput out) throws IOException {
...
+            }
+
+        }
+
+        /**
+         * Calculates the maximum size of the shardDeleteResults BytesStreamOutput.
+         * The size should at most be 2GB, but no more than 25% of the total remaining heap space
+         * @return The maximum number of bytes the shardDeleteResults BytesStreamOutput can consume in the heap
+         */
+        int calculateMaximumShardDeleteResultsSize(Settings settings) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Ah sorry I think I gave you duff advice earlier. I thought `RelativeBytesSizeValue` was the utility that dealt with converting settings from percentage-of-heap values to absolute `ByteSizeValue` values but now that I look more closely I see that that's not what this thing is for. I meant `Setting#memorySizeSetting`.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 6]
```diff
@@ -1678,26 +1687,63 @@ void writeTo(StreamOutput out) throws IOException {
...
+            long maxAllowedSizeInBytes;
+            if (configuredValue.isAbsolute()) {
+                maxAllowedSizeInBytes = configuredValue.getAbsolute().getBytes();
+            } else {
+                maxAllowedSizeInBytes = configuredValue.calculateValue(ByteSizeValue.ofBytes(Runtime.getRuntime().maxMemory()), null)
+                    .getBytes();
+            }
+
+            if (maxAllowedSizeInBytes > Integer.MAX_VALUE) {
+                return Integer.MAX_VALUE;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: We're allowing some slop in our limit (zlib buffers, `BufferedOutputStream` buffers, last-item overspill) so we have to reduce this max accordingly.

Comment (joshua-adams-1) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: For us to round down and set the max limit as 2GB, we have to have >8GB of heap memory (since we only want to utilise at most 25% of it), and so the other 75%+ can temporarily hold any buffers, especially as it's only a few KiB. Regarding last item overspill, the current implementation only writes if we have capacity for the *entire* object, and so there won't be any overspill, and it also won't trip the exception [here](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/io/stream/BytesStreamOutput.java#L175)

Comment (joshua-adams-1) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I guess to be super safe, if there's X% of space we want to keep clear for buffers, I can just modify the condition below to be:
```
if (shardDeleteResults.size() + totalBytesRequired <= shardDeleteResultsMaxSize - bufferSpace) {
```

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: > the other 75%+ can temporarily hold any buffers

Yeah it's not the temporary use of the buffers that's a problem, it's the fact that those buffers contain data that hasn't yet been written to `shardDeleteResults`, so isn't counted in `shardDeleteResults.size()` but which we will eventually need to write there.

If we carry on writing until `shardDeleteResults.size() == Integer.MAX_VALUE` then flushing even a single byte from those buffers into `shardDeleteResults` will error out. We need to stop when there's still enough room to clear out the buffers. We could do that by adjusting these limits on each iteration as you suggest, but that is pretty confusing to the reader when `shardDeleteResultsMaxSize`, `bufferSpace` and `totalBytesRequired` are all constants. I mean it probably doesn't matter much in terms of performance, arithmetic is cheap, but to me when I read that expression it's three separate things to go and investigate for potential writes rather than just the one constant defined up front.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Also NB `shardDeleteResults.size()` counts compressed bytes but `totalBytesRequired` is uncompressed bytes, it doesn't really make sense to add them. We cannot guarantee that the compressed representation will be smaller than the uncompressed one (indeed lossless compression always makes some input strings bigger) so this isn't even a right-side failure.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: > Regarding last item overspill, the current implementation only writes if we have capacity for the entire object,

Yeah, I'm saying [here](https://github.com/elastic/elasticsearch/pull/133558#discussion_r2322492180) that we don't want to do this. Consider checking the results size on each entry in the collection and truncating the collection early if needed.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 5 above)
Comment (joshua-adams-1) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: AFAICT, this still only specifies the % of memory that I want to use. I still need to actually get the memory, right? In this implementation I did `Runtime.getRuntime().maxMemory()` but this doesn't help when we're already at 90% max heap utilization since we would overflow long before our limit is hit. If I were to use `Runtime.getRuntime().freeMemory()` then I would get the % of the actual heap to be used (which is safer) but doesn't work well in the case that the heap subsequently frees itself up and I'm left with a small `shardDeletesResult` object.

A safety net would be to check the freeMemory before *every* write because even though our limit says we can write the object to the heap, in actuality we may not have capacity. Do you agree?

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 4 above)
Comment (joshua-adams-1) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: >There's also (a bounded amount of) buffering involved in the write process, both in the BufferedOutputStream and in zlib itself, which adds up to several kiB that's not counted in shardDeleteResults.size().

I will take this into account. Based on the Node.Js documentation [here](https://nodejs.org/api/zlib.html#zlib_memory_usage_tuning), the sizes are:
- Deflate requires 128K + 128K + a small buffer
- Inflate requires 32K + a small buffer
- There is an additional chunk size of 16K
For safety then I will round this up to 1MB of buffer space and factor this into the maths

>I reckon even this much up-front computation is overly pedantic. The limit is in practice going to be at least 10s-of-MiBs (after compression) and the amount of data we write per entry is almost always going to be no more than a few kiB (before compression)

I have two options:
1. Calculate the capacity upfront and only if we have space for the entire object then write it to the buffer
2. Check if we've exceeded the capacity before writing, but this is essentially checking whether the write *before* was the one to exceed the limit. This means we're guaranteed to have overspill, but bounded only to a single write 

I picked option 1 to be proactive and safe and guarantee we don't throw the exception in [BytesStreamOutput](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/common/io/stream/BytesStreamOutput.java#L175)

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 5 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: `Setting#memorySizeSetting` yields an absolute `ByteSizeValue`, no need for you to do any further computation.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 6 above)
Comment (joshua-adams-1) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: >Consider checking the results size on each entry in the collection and truncating the collection early if needed.

Are you suggesting that for an `ShardSnapshotMetaDeleteResult` [here](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L1655) we write the `indexId`, `shardId` and then as many of it's blobs as we can before hitting a limit? Is it preferable to partially write an object than not at all? It also raises the point again of how am I going to know that writing this final blob exceeds the limit without either checking we have capacity first, or writing and then checking if we've overspilled?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: > writing and then checking if we've overspilled

Yes, that. Blob names are all bounded in length, so any overspill from writing a blob name is also bounded.

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Maybe something like this wrapped around the output stream, watching the size of the buffer?

```java
public class TruncatingOutputStream extends FilterOutputStream {
    private final IntSupplier currentSizeSupplier;
    private final int maxSize;
    private boolean hasCapacity;

    public TruncatingOutputStream(OutputStream out, IntSupplier currentSizeSupplier, int maxSize) {
        super(out);
        this.currentSizeSupplier = currentSizeSupplier;
        this.maxSize = maxSize;
    }

    private boolean hasCapacity() {
        if (hasCapacity) {
            hasCapacity = currentSizeSupplier.getAsInt() < maxSize;
        }
        return hasCapacity;
    }

    @Override
    public void write(byte[] b) throws IOException {
        if (hasCapacity()) {
            super.write(b);
        }
    }

    @Override
    public void write(byte[] b, int off, int len) throws IOException {
        if (hasCapacity()) {
            super.write(b, off, len);
        }
    }

    @Override
    public void write(int b) throws IOException {
        if (hasCapacity()) {
            super.write(b);
        }
    }
}
```

This will just start discarding data as soon as it reaches capacity, so the overshoot will be at most `b.length`, and we know that `b` is a bounded buffer, so its compressed representation is also bounded.

Ofc this'll throw an exception on read, but that's ok we can handle that.

File: server/src/main/java/org/elasticsearch/common/io/stream/BoundedOutputStream.java [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+    public void write(int b) throws IOException {
+        if (closed == false && hasCapacity(1)) {
+            super.write(b);
+
+            /*
+                We only need to increment size here as both super.write(byte[] b) and
+                super.write(byte[] b, int off, int len) write each byte individually via this
+                method, and we have already checked in each respective method whether we have
+                sufficient capacity for that entire write
+             */
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/common/io/stream/BoundedOutputStream.java]: Writing data byte-by-byte is outrageously expensive - this is a common trap with `FilterOutputStream`. The overloads that take a whole `byte[]` need to pass this data on to similar bulk write calls against `out` rather than using `super.write()`.

File: server/src/main/java/org/elasticsearch/common/io/stream/BoundedOutputStream.java [hunk 8]
```diff
@@ -0,0 +1,73 @@
...
+            size++;
+        } else {
+            closed = true;
+            throw new BoundedOutputStreamFailedWriteException();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/common/io/stream/BoundedOutputStream.java]: I don't think we need an exception here, we can just keep on accepting (and ignoring) writes and then check to see if we dropped any data at the end.

File: server/src/main/java/org/elasticsearch/common/io/stream/BoundedOutputStream.java [hunk 9]
```diff
@@ -0,0 +1,73 @@
...
+    private boolean closed = false;
+
+    public BoundedOutputStream(OutputStream out, int maxSize) {
+        super(out);
+        this.maxSize = maxSize;
+        this.size = 0;
+    }
+
+    private boolean hasCapacity(int bytes) {
+        return size + bytes <= maxSize;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/common/io/stream/BoundedOutputStream.java]: This is bounding the size of the uncompressed data, which will in practice be much more restrictive than it needs to be to bound the size of the compressed data in most cases, whilst in theory not being restrictive enough in some cases given that lossless compression always makes some inputs larger. We need to consider the size of the compressed data instead.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 10]
```diff
@@ -1706,6 +1744,11 @@ synchronized void addShardDeleteResult(
...
             Collection<String> blobsToDelete
         ) {
+            if (compressed == null) {
+                // No output stream: skip writing, but still update generations
+                shardGenerationsBuilder.put(indexId, shardId, newGeneration);
+                return;
+            }
             try {
                 shardGenerationsBuilder.put(indexId, shardId, newGeneration);
                 new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
```
Comment (joshua-adams-1) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: We now write without caring whether we've overflowed or not

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 11]
```diff
@@ -1736,20 +1783,32 @@ public Iterator<String> getBlobPaths() {
...
             }
 
-            return Iterators.flatMap(Iterators.forRange(0, resultCount, i -> {
+            List<String> blobPaths = new ArrayList<>();
+            for (int i = 0; i < resultCount; i++) {
+                ShardSnapshotMetaDeleteResult shardResult;
                 try {
-                    return new ShardSnapshotMetaDeleteResult(input);
+                    shardResult = new ShardSnapshotMetaDeleteResult(input);
+                } catch (EOFException ex) {
```
Comment (joshua-adams-1) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: This is thrown because we've written half of an object, and the rest cannot be parsed since we've hit the end of the stream

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 12]
```diff
@@ -1736,20 +1783,32 @@ public Iterator<String> getBlobPaths() {
...
+                    // There was insufficient stream space to write this blob
+                    // All subsequent blobs will likewise be dangling
+                    logger.warn("Failure to clean up {} dangling blobs", resultCount - i);
```
Comment (joshua-adams-1) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Since we've lost this write I cannot retrieve for which `indexId` or `shardId` it was that has been left dangling, but I can determine how many writes we've lost

File: server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java [hunk 13]
```diff
@@ -798,4 +752,202 @@ public void testUuidCreationLogging() {
...
+        }
+    }
+
+    /*
+        There is sufficient heap space for some writes, but not all
+     */
+    @TestLogging(reason = "test includes assertions about logging", value = "org.elasticsearch.repositories.blobstore:WARN")
+    public void testShardBlobsToDeleteWithLimitedHeapSpace() {
+        // Limit the heap size so we force it to truncate the stream
+        int totalBytesRequired = randomIntBetween(1000, 10000);
```
Comment (joshua-adams-1) [inline server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java]: Arbitrarily chosen values, but tested with both bounds, and we are always guaranteed to be writing more data than we can hold

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 10 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I think we should check whether the `TruncatedOutputStream` is at capacity at this point and skip the increment of `resultCount` if so. That way we avoid the `EOFException` when trying to read the last, partial, object.

It'd also make sense to me to check whether the stream is already at capacity before even writing anything - no need to burn cycles on a write that is guaranteed to be a no-op.

Checking these conditions here would allow us to keep track of how many objects we're dropping, for a more accurate message later on.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 12 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: This'll report the number of _shards_ we won't be cleaning up, not the number of dangling blobs. It will be important to explain to the user why we skipped these blobs and what will happen now: it's not a _failure_ really, we deliberately skipped them because there were too many to keep track of them all, but note that any leftovers will be cleaned up by future delete operations.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 14]
```diff
@@ -1678,26 +1685,58 @@ void writeTo(StreamOutput out) throws IOException {
...
+         * Calculates the maximum size of the shardDeleteResults BytesStreamOutput.
+         * The size should at most be 2GB, but no more than 25% of the total remaining heap space.
+         * A buffer of 1MB is maintained, so that even if the stream is of max size, there is room to flush
+         * @return The maximum number of bytes the shardDeleteResults BytesStreamOutput can consume in the heap
+         */
+        int calculateMaximumShardDeleteResultsSize(Settings settings) {
+            long maxSizeInBytes = MAX_SHARD_DELETE_RESULTS_SIZE_SETTING.get(settings).getBytes();
+            int oneMBBuffer = 1024 * 1024;
+            if (maxSizeInBytes > Integer.MAX_VALUE) {
+                return Integer.MAX_VALUE - oneMBBuffer;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: If `maxSizeInBytes == Integer.MAX_VALUE` then we'll skip this and return `Integer.MAX_VALUE` which doesn't allow enough headroom.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 15]
```diff
@@ -1706,10 +1745,20 @@ synchronized void addShardDeleteResult(
             ShardGeneration newGeneration,
             Collection<String> blobsToDelete
         ) {
+            if (compressed == null) {
+                // No output stream: skip writing, but still update generations
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: AFAICT this only happens if someone sets `repositories.blobstore.max_shard_delete_results_size: 0` right? I don't think we need to treat that as a special case tho, it should be very rare to do this and everything will work ok even if the limit is zero, so I'd rather we didn't have these rare `null` cases lying around nor extra code to handle them like this.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 16]
```diff
@@ -1721,6 +1770,10 @@ public ShardGenerations getUpdatedShardGenerations() {
         }
 
         public Iterator<String> getBlobPaths() {
+            if (compressed == null || shardDeleteResults == null) {
+                // No output stream: nothing to return
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Likewise here I don't think we should change anything with respect to these values being `null`.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java (hunk 11 above)
Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: I'd rather we just didn't count the last partially-written object in `resultCount` rather than counting it and then throwing an exception here.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 17]
```diff
@@ -1736,20 +1789,36 @@ public Iterator<String> getBlobPaths() {
...
+                }
+            }
+            return blobPaths.iterator();
         }
 
         @Override
         public void close() {
+            if (resources.isEmpty()) {
+                return;
+            }
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Likewise here, let's always track these resources even if the limit is zero.

File: server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java (hunk 13 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java]: Hmm could we instead check `org.elasticsearch.repositories.blobstore.BlobStoreRepository.ShardBlobsToDelete#sizeInBytes` and keep going until at least this has reached the limit we chose (but maybe not going much further than that)? I think in most cases this test is going to do enormously more work than needed to verify what we're trying to verify.

File: server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java [hunk 18]
```diff
@@ -798,4 +752,202 @@ public void testUuidCreationLogging() {
...
+                final var countDownLatch = new CountDownLatch(1);
+                int blobCount = 0;
+                try (var refs = new RefCountingRunnable(countDownLatch::countDown)) {
+                    for (int index = between(0, 1000); index > 0; index--) {
+                        final var indexId = new IndexId(randomIdentifier(), randomUUID());
+                        for (int shard = between(1, 30); shard > 0; shard--) {
+                            final var shardId = shard;
+                            final var shardGeneration = new ShardGeneration(randomUUID());
+                            expectedShardGenerations.put(indexId, shard, shardGeneration);
+                            final var blobsToDelete = generateRandomBlobsToDelete(0, 100);
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java]: Max 1000 indices × max 30 shards × max 100 blobs is a max of 3M items. That seems like a lot. Does this really give us much more coverage than a smaller test?

A much more interesting test here would be to see what happens if we stop writing just shy of the limit, such that the final flush pushes us over. Could we instead pick a lower limit, write until we get very close to the limit (according to `shardBlobsToDelete.sizeInBytes()`) and then verify that we didn't lose anything?

File: server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java [hunk 19]
```diff
@@ -798,4 +752,202 @@ public void testUuidCreationLogging() {
...
+    @TestLogging(reason = "test includes assertions about logging", value = "org.elasticsearch.repositories.blobstore:WARN")
+    public void testShardBlobsToDeleteWithOutHeapSpace() {
+        IndexId indexId = new IndexId(randomIdentifier(), randomUUID());
+        int shardId = between(1, 30);
+        Collection<String> blobIds = generateRandomBlobsToDelete(0, 20);
+        ShardGeneration shardGeneration = new ShardGeneration(randomUUID());
+
+        final var expectedShardGenerations = ShardGenerations.builder().put(indexId, shardId, shardGeneration).build();
+
+        Settings.Builder settings = Settings.builder().put("repositories.blobstore.max_shard_delete_results_size", "0b");
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java]: Likewise here I think this can just be folded into `testShardBlobsToDeleteWithLimitedHeapSpace`.

**Review by DaveCTurner — COMMENTED** [review]
Thanks Josh, looking good, just a few more comments.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 20]
```diff
@@ -1736,16 +1785,20 @@ public Iterator<String> getBlobPaths() {
                 throw new UncheckedIOException(e);
             }
 
-            return Iterators.flatMap(Iterators.forRange(0, resultCount, i -> {
+            List<String> blobPaths = new ArrayList<>();
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Materializing this entire collection of paths as an `ArrayList<String>` is exactly what we're trying to avoid doing in the first place!

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 21]
```diff
@@ -1678,28 +1684,57 @@ void writeTo(StreamOutput out) throws IOException {
...
+         * @return The maximum number of bytes the shardDeleteResults BytesStreamOutput can consume in the heap
+         */
+        int calculateMaximumShardDeleteResultsSize(Settings settings) {
+            long maxHeapSizeInBytes = MAX_SHARD_DELETE_RESULTS_SIZE_SETTING.get(settings).getBytes();
+            int oneMBBuffer = 1024 * 1024;
+            int maxShardDeleteResultsSize = Integer.MAX_VALUE - oneMBBuffer;
+            if (maxHeapSizeInBytes > maxShardDeleteResultsSize) {
+                return maxShardDeleteResultsSize;
+            }
+            return (int) maxHeapSizeInBytes;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: This is a rather elaborate way to write `Math.min()` :) I'd suggest keeping it as a `long` throughout even though we know it will always be less than `Integer.MAX_VALUE`, but you can try a `Math.toIntExact` if you'd prefer.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 22]
```diff
@@ -1678,28 +1684,57 @@ void writeTo(StreamOutput out) throws IOException {
...
+        private final StreamOutput compressed;
 
         private final ArrayList<Closeable> resources = new ArrayList<>();
 
         private final ShardGenerations.Builder shardGenerationsBuilder = ShardGenerations.builder();
 
-        ShardBlobsToDelete() {
+        // Gets 25% of the heap size to be allocated to the shard_delete_results stream
+        public final Setting<ByteSizeValue> MAX_SHARD_DELETE_RESULTS_SIZE_SETTING = Setting.memorySizeSetting(
+            "repositories.blobstore.max_shard_delete_results_size",
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: You have to register this setting in `ClusterSettings`.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 23]
```diff
@@ -1678,28 +1684,57 @@ void writeTo(StreamOutput out) throws IOException {
...
+            "25%",
+            Setting.Property.NodeScope
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Could we make this a dynamic setting too?

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 24]
```diff
@@ -1708,8 +1743,22 @@ synchronized void addShardDeleteResult(
         ) {
             try {
                 shardGenerationsBuilder.put(indexId, shardId, newGeneration);
-                new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
-                resultCount += 1;
+                // Only write if we have capacity
+                if (shardDeleteResults.size() < this.shardDeleteResultsMaxSize) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Could we make this call `TruncatedOutputStream#hasCapacity`? No need for a comment that way, and also it's important that we use the same has-capacity computation as the underlying stream here.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 25]
```diff
@@ -1708,8 +1743,22 @@ synchronized void addShardDeleteResult(
...
+                    new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
+                    // We only want to read this shard delete result if we were able to write the entire object.
+                    // Otherwise, for partial writes, an EOFException will be thrown upon reading
+                    if (shardDeleteResults.size() < this.shardDeleteResultsMaxSize) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Likewise here, this should call `TruncatedOutputStream#hasCapacity`.

**Review by DaveCTurner — CHANGES_REQUESTED** [review]

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 26]
```diff
@@ -1708,8 +1743,22 @@ synchronized void addShardDeleteResult(
...
+                        resultCount += 1;
+                    }
+                } else {
+                    logger.warn(
+                        "Failure to clean up the following dangling blobs, {}, for index {} and shard {}",
+                        blobsToDelete,
+                        indexId,
+                        shardId
+                    );
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: We can't reasonably log every skipped blob at `WARN` like this - we've already captured several (compressed) GiB of blob names before getting to this point, so it wouldn't be surprising if there were several GiB more. We wouldn't expect users to go through these logs and delete the blobs manually - indeed we would strongly discourage that kind of behaviour.

Instead, let's log this at `DEBUG` and keep count of the number of blobs we skipped. Then at the end we can log at `WARN` how many blobs we've leaked.

Also nit it's not really a "failure", we're deliberately skipping this work because of resource constraints. We should mention in the user-facing `WARN` message that these dangling blobs will be cleaned up by subsequent deletes, and perhaps suggest that the master node needs a larger heap size to perform such large snapshot deletes in future.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 27]
```diff
@@ -1708,8 +1743,22 @@ synchronized void addShardDeleteResult(
...
-                new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
-                resultCount += 1;
+                // Only write if we have capacity
+                if (shardDeleteResults.size() < this.shardDeleteResultsMaxSize) {
+                    new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
+                    // We only want to read this shard delete result if we were able to write the entire object.
+                    // Otherwise, for partial writes, an EOFException will be thrown upon reading
+                    if (shardDeleteResults.size() < this.shardDeleteResultsMaxSize) {
+                        resultCount += 1;
+                    }
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: This `if` also needs an `else` to keep track of the blobs that leaked because we ran out of capacity during the write.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 28]
```diff
@@ -1708,8 +1739,26 @@ synchronized void addShardDeleteResult(
...
                 shardGenerationsBuilder.put(indexId, shardId, newGeneration);
-                new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
-                resultCount += 1;
+                // There is a minimum of 1 byte available for writing
+                if (this.truncatedShardDeleteResultsOutputStream.hasCapacity()) {
+                    new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
+                    // We only want to read this shard delete result if we were able to write the entire object.
+                    // Otherwise, for partial writes, an EOFException will be thrown upon reading
+                    if (this.truncatedShardDeleteResultsOutputStream.hasCapacity()) {
+                        successfullyWrittenBlobsCount += 1;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: This replaces `resultCount` but it's the count of the number of successfully recorded _shards_ not _blobs_.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 29]
```diff
@@ -1708,8 +1739,26 @@ synchronized void addShardDeleteResult(
...
+                    } else {
+                        leakedBlobsCount += 1;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Likewise this is recording the number of shards with leaked blobs rather than the number of leaked blobs. However, rather than just renaming the variable I think we should actually count the number of leaked blobs (i.e. `+= blobsToDelete.size()` here).

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 30]
```diff
@@ -1708,8 +1739,26 @@ synchronized void addShardDeleteResult(
...
+                    }
+                } else {
+                    logger.debug(
+                        "Unable to clean up the following dangling blobs, {}, for index {} and shard {} "
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java:1743]: This also applies to the other branch that increases `leakedBlobsCount`.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 31]
```diff
@@ -432,6 +433,14 @@ public static String getRepositoryDataBlobName(long repositoryGeneration) {
         Setting.Property.NodeScope
     );
 
+    // Defines the max size of the shard_delete_results stream as a percentage of available heap memory
+    public static final Setting<ByteSizeValue> MAX_HEAP_SIZE_FOR_SNAPSHOT_DELETION_SETTING = Setting.memorySizeSetting(
+        "repositories.blobstore.max_shard_delete_results_size",
+        "25%",
+        Setting.Property.Dynamic,
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java:445]: Yet more trappiness: you now need to register a listener for updates to this setting (e.g. call `clusterSettings.initializeAndWatch(...)`). You can get a `clusterSettings` from `clusterService.getClusterSettings()`. I think I'd be inclined to do that in the `BlobStoreRepository` constructor rather than doing it each time we create a `SnapshotsDeletion`.

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 32]
```diff
@@ -546,6 +560,11 @@ protected BlobStoreRepository(
             threadPool.executor(ThreadPool.Names.SNAPSHOT)
         );
         this.blobStoreSnapshotMetrics = new BlobStoreSnapshotMetrics(projectId, metadata, snapshotMetrics);
+        ClusterSettings clusterSettings = clusterService.getClusterSettings();
+        clusterSettings.initializeAndWatch(
+            MAX_HEAP_SIZE_FOR_SNAPSHOT_DELETION_SETTING,
+            status -> this.maxHeapSizeForSnapshotDeletion = status
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: Maybe apply the limit here on write (making the field an `int`) rather than each read?

```suggestion
            maxHeapSizeForSnapshotDeletion -> this.maxHeapSizeForSnapshotDeletion = Math.toIntExact(
                Math.min(maxHeapSizeForSnapshotDeletion.getBytes(), Integer.MAX_VALUE - ByteSizeUnit.MB.toBytes(1))
            )
```

File: server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java [hunk 33]
```diff
@@ -1708,8 +1744,31 @@ synchronized void addShardDeleteResult(
...
+                    // We only want to read this shard delete result if we were able to write the entire object.
+                    // Otherwise, for partial writes, an EOFException will be thrown upon reading
+                    if (this.truncatedShardDeleteResultsOutputStream.hasCapacity()) {
+                        resultsCount += 1;
+                    } else {
+                        writeTruncated = true;
+                    }
+                } else {
+                    writeTruncated = true;
+                }
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java]: A matter of taste, but consider extracting this section into its own method to clarify that we only get `false` on the branch that succeeded, all other paths lead to `true` (and maybe we should invert that so that `true` means "success").

```java
        private boolean writeBlobsIfCapacity(IndexId indexId, int shardId, Collection<String> blobsToDelete) throws IOException {
            // There is a minimum of 1 byte available for writing
            if (this.truncatedShardDeleteResultsOutputStream.hasCapacity()) {
                new ShardSnapshotMetaDeleteResult(Objects.requireNonNull(indexId.getId()), shardId, blobsToDelete).writeTo(compressed);
                // We only want to read this shard delete result if we were able to write the entire object.
                // Otherwise, for partial writes, an EOFException will be thrown upon reading
                if (this.truncatedShardDeleteResultsOutputStream.hasCapacity()) {
                    resultsCount += 1;
                    return false;
                }
            }

            return true;
        }
```

File: server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java [hunk 34]
```diff
@@ -798,4 +749,167 @@ public void testUuidCreationLogging() {
...
+                                    + "for more efficient cleanup."
+                            )
+                        );
+                    }
+                }
+
+                assertEquals(expectedShardGenerations.build(), shardBlobsToDelete.getUpdatedShardGenerations());
+                shardBlobsToDelete.getBlobPaths().forEachRemaining(s -> assertTrue(expectedBlobsToDelete.remove(s)));
+                assertThat(expectedBlobsToDelete, empty());
+                assertThat(shardBlobsToDelete.sizeInBytes(), lessThanOrEqualTo(Math.max(ByteSizeUnit.KB.toIntBytes(1), 20 * blobCount)));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java]: Hmm it's not really within the implied contract of this class to be able to iterate its contents and then try and append more items. We've already closed the underlying `compressed` stream by this point. I think we should defer these assertions until the end.

File: server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java [hunk 35]
```diff
@@ -798,4 +749,167 @@ public void testUuidCreationLogging() {
...
+
+                mockLog.assertAllExpectationsMatched();
+
+                // === Second, now capacity is exceeded, test whether subsequent writes are accepted without throwing an error === //
+
+                for (int i = 0; i < randomIntBetween(1, 20); i++) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java]: This is trappy, it's going to generate a new `randomIntBetween` on each iteration so you don't get a uniform distribution of values. Better to count down from `between(1,20)` to zero, or else extract a variable for the upper bound.

File: server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java [hunk 36]
```diff
@@ -798,4 +749,167 @@ public void testUuidCreationLogging() {
...
+            try (var mockLog = MockLog.capture(BlobStoreRepository.class)) {
+                final var expectedShardGenerations = ShardGenerations.builder();
+                final var expectedBlobsToDelete = new HashSet<String>();
+                CountDownLatch countDownLatch;
+                int blobCount = 0;
+
+                // === First, write blobs until capacity is exceeded === //
+
+                // While there is at least one byte in the stream, write
+                while (shardBlobsToDelete.sizeInBytes() < heapMemory) {
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java]: WDYT about iterating until `leakedBlobCount` reaches some target value here, rather than doing the two separate loops?

**Review by DaveCTurner — COMMENTED** [review]
Good stuff, I left only tiny nits about the production code and a few other comments about the testing.

File: server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java [hunk 37]
```diff
@@ -798,4 +749,114 @@ public void testUuidCreationLogging() {
...
+                CountDownLatch countDownLatch;
+                int blobCount = 0;
+
+                // Write while there is capacity, and then bound the number of leaked blobs
+                while (leakedBlobCount < 100) {
+                    // Generate the next blob to write
+                    final var indexId = new IndexId(randomIdentifier(), randomUUID());
+                    final var shardId = between(1, 30);
+                    final var shardGeneration = new ShardGeneration(randomUUID());
+                    // Always write at least one blob, guaranteeing that the shardDeleteResults stream increases in size
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/repositories/blobstore/BlobStoreRepositoryTests.java:788]: :+1: well spotted (in fact the stream grows anyway because we write the index ID, but that doesn't necessarily increase `leakedBlobCount`)

**Review by DaveCTurner — APPROVED** [review]
LGTM
