### PR TITLE
Tighten no pending scheduled refresh check

### LINKED ISSUE #39565: IndexShardIT#testPendingRefreshWithIntervalChange fails
IndexShardIT#testPendingRefreshWithIntervalChange fails on both master and 7.x. Failure does not seem to reproduce with the same seed.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+intake/365/console

```
./gradlew :server:integTest -Dtests.seed=170A6D9A6824A5B4 -Dtests.class=org.elasticsearch.index.shard.IndexShardIT -Dtests.method="testPendingRefreshWithIntervalChange" -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Africa/Libreville -Dcompiler.java=11 -Druntime.java=8
```

```
05:20:11 FAILURE 0.17s J3 | IndexShardIT.testPendingRefreshWithIntervalChange <<< FAILURES!
05:20:11    > Throwable #1: java.lang.AssertionError
05:20:11    > 	at __randomizedtesting.SeedInfo.seed([DF23BE067FF20969:44A0A86926C59400]:0)
05:20:11    > 	at org.elasticsearch.index.shard.IndexShardIT.testPendingRefreshWithIntervalChange(IndexShardIT.java:771)
05:20:11    > 	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by dnhatn**
Previously, we use ThreadPoolStats to ensure that the scheduledRefresh triggered by the internal refresh setting update is executed before we index a new document. With that change (#40387), this test did not fail for the last 3 months. However, using ThreadPoolStats is not entirely watertight as both "active" and "queue" count can be 0 in a very [small interval](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/concurrent/ThreadPoolExecutor.java#l1127) when ThreadPoolExecutor pulls a task from the queue but before marking the corresponding worker as active (i.e., [lock it](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/concurrent/ThreadPoolExecutor.java#l1128)).

Closes #39565

### CODE REVIEW

**Comment by dnhatn** [comment]
> java.lang.AssertionError: Failure at [painless/10_basic:109]: watch_record.state didn't match expected value:

@elasticmachine run elasticsearch-ci/2

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardIT.java [hunk 1]
```diff
@@ -771,14 +770,14 @@ public void testPendingRefreshWithIntervalChange() throws Exception {
...
-        assertBusy(() -> {
-            for (ThreadPoolStats.Stats stat : indexService.getThreadPool().stats()) {
-                if (stat.getName().equals(ThreadPool.Names.REFRESH) && (stat.getQueue() > 0 || stat.getActive() > 0)) {
-                    throw new AssertionError(); // cause assert busy to retry
-                }
-            }
-        });
+        // We need to ensure a `scheduledRefresh` triggered by the internal refresh setting update is executed before we index a new doc;
+        // otherwise, it will compete with the `scheduledRefresh` that we are going to verify. Since the refresh in single-node tests
+        // is a single thread executor, we can make sure that all scheduled refresh tasks are done by submitting a task then wait until
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/index/shard/IndexShardIT.java]: why is it a single thread executor? I can't see where this is enforced

**Review by ywelsch — COMMENTED** [review]
good catch.

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardIT.java (hunk 1 above)
Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardIT.java]: Sorry, I misread this.

Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardIT.java]: fixed in https://github.com/elastic/elasticsearch/pull/45025/commits/6c93e23c0019fa5b818d178a9528fb4d43dc7f81

**Comment by dnhatn** [comment]
run elasticsearch-ci/docs

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardIT.java [hunk 2]
```diff
@@ -771,20 +772,40 @@ public void testPendingRefreshWithIntervalChange() throws Exception {
...
+        // will be in the queue) to the refresh thread pool then wait until all of them are completed. Note that using ThreadPoolStats
+        // alone is not enough as both queue and active count can be 0 when ThreadPoolExecutor(see ThreadPoolExecutor#runWorker) just
+        // takes a task out the queue but before marking it active (i.e., lock the corresponding worker).
+        ThreadPoolExecutor refreshThreadPoolExecutor = (ThreadPoolExecutor) threadPool.executor(ThreadPool.Names.REFRESH);
+        int numTasks = refreshThreadPoolExecutor.getMaximumPoolSize() + 1;
+        CountDownLatch latch = new CountDownLatch(1);
+        for (int i = 0; i < numTasks; i++) {
+            refreshThreadPoolExecutor.execute(() -> {
+                try {
+                    latch.await();
```
Comment (ywelsch) [inline server/src/test/java/org/elasticsearch/index/shard/IndexShardIT.java]: I'm not sure why this would work. Would we not rather have to submit `refreshThreadPoolExecutor.getMaximumPoolSize()` number of tasks and use a `CyclicBarrier` with `refreshThreadPoolExecutor.getMaximumPoolSize() + 1` permits to make sure that there is no worker that might still be in the process of picking up the settings change refresh task?

Comment (dnhatn) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardIT.java]: It works due to the `assertBusy` at the end but yours's much simpler. I adopted it in  https://github.com/elastic/elasticsearch/pull/45025/commits/04774203852c10111c111135910a595a19d46ef5.

**Comment by dnhatn** [comment]
run elasticsearch-ci/1

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Thanks @ywelsch.
