### PR TITLE
Get from translog fails with large dense_vector

### LINKED ISSUE #104639: _mget error, vector's dimensions must be <= [1024]
### Elasticsearch Version

8.12

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Alibaba Cloud Linux 3.2104 LTS 64-bit

### Problem Description

Occasionally, an exception is returned when using the _mget API to retrieve documents：
ErrorCause: {"type":"illegal_argument_exception","reason":"Field [textVector] vector's dimensions must be <= [1024]; got 1536","root_cause":[{"type":"illegal_argument_exception","reason":"Field [textVector] vector's dimensions must be <= [1024]; got 1536"}]}

"mappings": {
      "dynamic": "strict",
      "_source": {
        "mode": "synthetic"
      },
      "properties": {
        "actId": {
          "type": "keyword"
        },
        "actPublishTime": {
          "type": "date"
        },
        "activityType": {
          "type": "keyword"
        },
        "docModifyTime": {
          "type": "date"
        },
        "firstCategoryIdList": {
          "type": "long"
        },
        "ghId": {
          "type": "keyword"
        },
        "goodsFirstPic": {
          "type": "keyword"
        },
        "pactId": {
          "type": "keyword"
        },
        "primaryCategory": {
          "type": "keyword"
        },
        "startActId": {
          "type": "keyword"
        },
        "text": {
          "type": "keyword",
          "index": false
        },
        "textVector": {
          "type": "dense_vector",
          "dims": 1536,
          "index": true,
          "similarity": "l2_norm"
        }
      }
    }

### Steps to Reproduce

1、Use dense_vector field.
2、Add documents.
3、Use _mget api.
Can not  stable reproduce 

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jimczi**
This change fixes the engine to apply the current codec when retrieving documents from the translog. We need to use the same codec than the main index in order to ensure that all the source data is indexable. The internal codec treats some fields differently, for instance dense_vectors are limited to 1024 dimensions in the default codec. This PR ensures that these customisations are applied when indexing document for translog retrieval.

Closes #104639

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by pxsalehi — APPROVED** [review]
LGTM, although I am not that familiar with `TranslogDirectoryReader`. Maybe @henningandersen or @tlrx can also give this a quick review.

File: server/src/test/java/org/elasticsearch/index/shard/ShardGetServiceTests.java [hunk 1]
```diff
@@ -114,6 +115,20 @@ public void testGetFromTranslogWithSyntheticSource() throws IOException {
...
+        for (int i = 0; i < vector.length; i++) {
+            vector[i] = randomFloat();
+        }
+        String docToIndex = Strings.format("""
+            {
+                "bar": %s,
+                "foo": "foo"
+            }
+            """, Arrays.toString(vector));
+        runGetFromTranslogWithOptions(docToIndex, "\"enabled\": true", docToIndex, "\"text\"", "foo", "\"dense_vector\"", false);
```
Comment (henningandersen) [inline server/src/test/java/org/elasticsearch/index/shard/ShardGetServiceTests.java:129]: It would be nice to also validate that we can read out the right dense vector value, though with the way it is implemented, it should hardly be an issue.

**Review by henningandersen — APPROVED** [review]
LGTM.

File: server/src/test/java/org/elasticsearch/index/shard/ShardGetServiceTests.java (hunk 1 above)
Comment (jimczi) [reply server/src/test/java/org/elasticsearch/index/shard/ShardGetServiceTests.java:129]: The test already checks that the retrieved source is identical: [source](https://github.com/elastic/elasticsearch/blob/d0263411cee3f258c4de7b5437c6b5149d24910b/server/src/test/java/org/elasticsearch/index/shard/ShardGetServiceTests.java#L187)
Do you think it's not enough?
