### PR TITLE
Fix node reduction pushdown tests for release tests

### LINKED ISSUE #139490: [CI] LocalLogicalPlanOptimizerTests testReductionPlanForTopNWithPushedDownFunctionsInOrder failing
**Build Scans:**
- [elasticsearch-periodic #11577 / release-tests](https://gradle-enterprise.elastic.co/s/trixgqiq4o66o)
- [elasticsearch-periodic #11577 / release-tests](https://gradle-enterprise.elastic.co/s/v2k64otvnn4v4)
- [elasticsearch-periodic-java-ea #112 / release-tests](https://gradle-enterprise.elastic.co/s/tt7xjsn52ivlo)
- [elasticsearch-pull-request #109767 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/f3j4jbbx6xwoe)
- [elasticsearch-pull-request #109751 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/o2vv7acukcjmw)
- [elasticsearch-pull-request #109674 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/b4bhzc6nxjkfy)
- [elasticsearch-pull-request #109641 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/g5nxiegwggzmi)
- [elasticsearch-pull-request #109613 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/2aqgmjjjbv7vc)
- [elasticsearch-periodic #11573 / release-tests](https://gradle-enterprise.elastic.co/s/xpqp6bim7kdqi)
- [elasticsearch-pull-request #109561 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/bopqw5gdalabm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.LocalLogicalPlanOptimizerTests.testReductionPlanForTopNWithPushedDownFunctionsInOrder" -Dtests.seed=D7B618077402F208 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=as -Dtests.timezone=America/Indiana/Winamac -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.optimizer.LocalLogicalPlanOptimizerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testReductionPlanForTopNWithPushedDownFunctionsInOrder'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an instance of org.elasticsearch.xpack.esql.core.expression.FieldAttribute
     but: <LENGTH(text)> is a org.elasticsearch.xpack.esql.expression.function.scalar.string.Length
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 2 consecutive failures in step checkpart3_release-tests
- [main] 10 failures in test testReductionPlanForTopNWithPushedDownFunctionsInOrder (5.0% fail rate in 202 executions)
- [main] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [main] 6 failures in step checkpart3_release-tests (75.0% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (100.0% fail rate in 2 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (5.5% fail rate in 109 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139491: [CI] LocalLogicalPlanOptimizerTests testReductionPlanForTopNWithPushedDownFunctions failing
**Build Scans:**
- [elasticsearch-periodic #11577 / release-tests](https://gradle-enterprise.elastic.co/s/trixgqiq4o66o)
- [elasticsearch-periodic #11577 / release-tests](https://gradle-enterprise.elastic.co/s/v2k64otvnn4v4)
- [elasticsearch-periodic-java-ea #112 / release-tests](https://gradle-enterprise.elastic.co/s/tt7xjsn52ivlo)
- [elasticsearch-pull-request #109767 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/f3j4jbbx6xwoe)
- [elasticsearch-pull-request #109751 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/o2vv7acukcjmw)
- [elasticsearch-pull-request #109674 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/b4bhzc6nxjkfy)
- [elasticsearch-pull-request #109641 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/g5nxiegwggzmi)
- [elasticsearch-pull-request #109613 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/2aqgmjjjbv7vc)
- [elasticsearch-periodic #11573 / release-tests](https://gradle-enterprise.elastic.co/s/xpqp6bim7kdqi)
- [elasticsearch-pull-request #109561 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/bopqw5gdalabm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.LocalLogicalPlanOptimizerTests.testReductionPlanForTopNWithPushedDownFunctionsInOrder" -Dtests.seed=D7B618077402F208 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=as -Dtests.timezone=America/Indiana/Winamac -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.optimizer.LocalLogicalPlanOptimizerTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testReductionPlanForTopNWithPushedDownFunctions'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an instance of org.elasticsearch.xpack.esql.core.expression.FieldAttribute
     but: <LENGTH(text)> is a org.elasticsearch.xpack.esql.expression.function.scalar.string.Length
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 2 consecutive failures in step checkpart3_release-tests
- [main] 10 failures in test testReductionPlanForTopNWithPushedDownFunctions (5.0% fail rate in 202 executions)
- [main] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [main] 6 failures in step checkpart3_release-tests (75.0% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (100.0% fail rate in 2 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (5.5% fail rate in 109 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139492: [CI] ReplaceDateTruncBucketWithRoundToTests testReductionPlanForTopNWithPushedDownFunctionsInOrder failing
**Build Scans:**
- [elasticsearch-periodic #11577 / release-tests](https://gradle-enterprise.elastic.co/s/trixgqiq4o66o)
- [elasticsearch-periodic #11577 / release-tests](https://gradle-enterprise.elastic.co/s/v2k64otvnn4v4)
- [elasticsearch-periodic-java-ea #112 / release-tests](https://gradle-enterprise.elastic.co/s/tt7xjsn52ivlo)
- [elasticsearch-pull-request #109767 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/f3j4jbbx6xwoe)
- [elasticsearch-pull-request #109751 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/o2vv7acukcjmw)
- [elasticsearch-pull-request #109674 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/b4bhzc6nxjkfy)
- [elasticsearch-pull-request #109641 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/g5nxiegwggzmi)
- [elasticsearch-pull-request #109613 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/2aqgmjjjbv7vc)
- [elasticsearch-periodic #11573 / release-tests](https://gradle-enterprise.elastic.co/s/xpqp6bim7kdqi)
- [elasticsearch-pull-request #109561 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/bopqw5gdalabm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.rules.logical.local.ReplaceDateTruncBucketWithRoundToTests.testReductionPlanForTopNWithPushedDownFunctionsInOrder" -Dtests.seed=D7B618077402F208 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=fr-Latn-FR -Dtests.timezone=Navajo -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.optimizer.rules.logical.local.ReplaceDateTruncBucketWithRoundToTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testReductionPlanForTopNWithPushedDownFunctionsInOrder'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an instance of org.elasticsearch.xpack.esql.core.expression.FieldAttribute
     but: <LENGTH(text)> is a org.elasticsearch.xpack.esql.expression.function.scalar.string.Length
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 2 consecutive failures in step checkpart3_release-tests
- [main] 10 failures in test testReductionPlanForTopNWithPushedDownFunctionsInOrder (5.0% fail rate in 202 executions)
- [main] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [main] 6 failures in step checkpart3_release-tests (75.0% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (100.0% fail rate in 2 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (5.5% fail rate in 109 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #139493: [CI] ReplaceDateTruncBucketWithRoundToTests testReductionPlanForTopNWithPushedDownFunctions failing
**Build Scans:**
- [elasticsearch-periodic #11577 / release-tests](https://gradle-enterprise.elastic.co/s/trixgqiq4o66o)
- [elasticsearch-periodic #11577 / release-tests](https://gradle-enterprise.elastic.co/s/v2k64otvnn4v4)
- [elasticsearch-periodic-java-ea #112 / release-tests](https://gradle-enterprise.elastic.co/s/tt7xjsn52ivlo)
- [elasticsearch-pull-request #109767 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/f3j4jbbx6xwoe)
- [elasticsearch-pull-request #109751 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/o2vv7acukcjmw)
- [elasticsearch-pull-request #109674 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/b4bhzc6nxjkfy)
- [elasticsearch-pull-request #109641 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/g5nxiegwggzmi)
- [elasticsearch-pull-request #109613 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/2aqgmjjjbv7vc)
- [elasticsearch-periodic #11573 / release-tests](https://gradle-enterprise.elastic.co/s/xpqp6bim7kdqi)
- [elasticsearch-pull-request #109561 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/bopqw5gdalabm)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.optimizer.rules.logical.local.ReplaceDateTruncBucketWithRoundToTests.testReductionPlanForTopNWithPushedDownFunctionsInOrder" -Dtests.seed=D7B618077402F208 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=fr-Latn-FR -Dtests.timezone=Navajo -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.optimizer.rules.logical.local.ReplaceDateTruncBucketWithRoundToTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testReductionPlanForTopNWithPushedDownFunctions'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: an instance of org.elasticsearch.xpack.esql.core.expression.FieldAttribute
     but: <LENGTH(text)> is a org.elasticsearch.xpack.esql.expression.function.scalar.string.Length
```

**Issue Reasons:**
- [main] 4 consecutive failures in step release-tests
- [main] 2 consecutive failures in step checkpart3_release-tests
- [main] 10 failures in test testReductionPlanForTopNWithPushedDownFunctions (5.0% fail rate in 202 executions)
- [main] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [main] 6 failures in step checkpart3_release-tests (75.0% fail rate in 8 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (100.0% fail rate in 2 executions)
- [main] 6 failures in pipeline elasticsearch-pull-request (5.5% fail rate in 109 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by carlosdelest**
Closes #139490
Closes #139491
Closes #139492
Closes #139493

Node reduction only happens on snapshot builds. Add guard on the corresponding optimization tests so they check they're on snapshot builds.

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -2104,6 +2105,7 @@ private static PhysicalPlan physicalPlan(LogicalPlan logicalPlan, Analyzer analy
     }
 
     public void testReductionPlanForTopNWithPushedDownFunctions() {
+        assumeTrue("Reduction is just enabled for snapshot builds", Build.current().isSnapshot());
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: Is there no capability that would correspond to this?

Without a capability, we're very likely to forget to update this test later to remove this `assumeTrue`.

**Review by alex-spies — APPROVED** [review]
Looks good, but maybe we can future-proof the tests for when the reduction gets released.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java (hunk 1 above)
Comment (carlosdelest) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: There is none AFAIU. We're using [query pragmas](https://github.com/elastic/elasticsearch/blob/1c1484391ccf603e568479a84c75db8b94622d39/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/QueryPragmas.java#L73) for node reduction.

Is there an alternative for detecting that?

Comment (ivancea) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: I see the pragma defaults to true. Doesn't it mean it should be active here by default?

Comment (ivancea) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: I don't think we did this before, but I was going to suggest that maybe we could change the snapshot check with a pragma check. Just to have a link between the feature and the test ignore.

The worst part of the "isSnapshot()" is that they're "hard" to find. Meanwhile, with a capability (Or a pragma), it's easier to trackfollowing references.

Of course, if it defaults to true, it wouldn't solve anything

Comment (carlosdelest) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: The pragma defaults to true - but I don't see them being active on release builds. 

Happy to include a different check, I'm just not sure on how to do it on a non-fragile way.

Comment (alex-spies) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: > I see the pragma defaults to true. Doesn't it mean it should be active here by default?

++. I think the late materialization in case of topn may still be turned off on snapshot - I thought we had a capability for that but couldn't find it.

@GalLalouche , we discussed that we wanted to [disable this on snapshot builds](https://github.com/elastic/elasticsearch/pull/132757#discussion_r2406005975), but I don't recall which mechanism we settled on to achieve this.

Comment (carlosdelest) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: @GalLalouche @alex-spies  I'd like to move this forward. Should we change the query pragma for a snapshot capability? Something else?

Comment (GalLalouche) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: It is indeed disabled for snapshot builds: https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/DataNodeComputeHandler.java#L195. It also depends on the aforementioned pragma, but there is no ad-hoc pragma just for Top N late materialization.

Comment (carlosdelest) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: Ah I see. Should we then change the dependency on snapshot builds for a Capability (enabled on snsapshots for now) so we can check for it on tests then?

Comment (carlosdelest) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java]: I gave it a go in cb6b571d6661cc3eb74ee9703004ad5dc513a62a - LMKWYT!

**Review by alex-spies — APPROVED** [review]
Thanks @carlosdelest , I think it's easier to track corresponding tests with the new capability.

@GalLalouche , are there other tests that were disable based simply on `Build.current().isSnapshot()`? If so, can we tie them to the new capability as well?

**Comment by GalLalouche** [comment]
> Thanks @carlosdelest , I think it's easier to track corresponding tests with the new capability.
> 
> @GalLalouche , are there other tests that were disable based simply on `Build.current().isSnapshot()`? If so, can we tie them to the new capability as well?

@alex-spies @carlosdelest There's `EsqlReductionLateMaterializationTestCase`, but I don't see where it explicitly depends on the `isSnapshot`. Can't hurt that add it there though.

**Comment by carlosdelest** [comment]
> @alex-spies @carlosdelest There's EsqlReductionLateMaterializationTestCase, but I don't see where it explicitly depends on the isSnapshot. Can't hurt that add it there though.

Nice, done in 8c90d18fad40824d53838d8dec8ba5ced0fbba82.
