### PR TITLE
ESQL: Fix columns ordering when pruning an INLINE STATS

### LINKED ISSUE #136797: ES|QL: INLINE STATS planning leads to "Output has changed"
With CSV dataset

```
from host_inventory | where  NOT false AND  NOT true | eval  RJWizhZgGm = null, jTXjCBjSCkoJ = "FRtR", `description` = null, `host.name` = true, host.os = to_lower(host.os), `host.version` = "GCReYnjoKJMDLJTN", nRZBIlWvfMtH = -1454596507, EGRvyKkionRJ = null, GymRrNCBbSc = 711051951, host.name = -1411015584 | drop host.os| rename nRZBIlWvfMtH as language_code | lookup join languages_lookup on language_code | mv_expand language_name | grok jTXjCBjSCkoJ "%{WORD:EGRvyKkionRJ} %{WORD:jTXjCBjSCkoJ} %{WORD:RJWizhZgGm}" | inline stats  `RJWizhZgGm` = present(host.name) by language_code | eval  RJWizhZgGm = host.name, `description` = GymRrNCBbSc + language_code
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "verification_exception",
                "reason": "Found 1 problem\nline 1:589: Output has changed from [[host.version{r}#13, GymRrNCBbSc{r}#19, host.name{r}#21, language_name{r}#55, EGRvyKkionRJ{r}#33, jTXjCBjSCkoJ{r}#35, language_code{r}#25, RJWizhZgGm{r}#42, description{r}#46]] to [[host.version{r}#13, language_code{r}#25, GymRrNCBbSc{r}#19, host.name{r}#21, language_name{r}#55, EGRvyKkionRJ{r}#33, jTXjCBjSCkoJ{r}#35, RJWizhZgGm{r}#42, description{r}#46]]. "
            }
        ],
        "type": "verification_exception",
        "reason": "Found 1 problem\nline 1:589: Output has changed from [[host.version{r}#13, GymRrNCBbSc{r}#19, host.name{r}#21, language_name{r}#55, EGRvyKkionRJ{r}#33, jTXjCBjSCkoJ{r}#35, language_code{r}#25, RJWizhZgGm{r}#42, description{r}#46]] to [[host.version{r}#13, language_code{r}#25, GymRrNCBbSc{r}#19, host.name{r}#21, language_name{r}#55, EGRvyKkionRJ{r}#33, jTXjCBjSCkoJ{r}#35, RJWizhZgGm{r}#42, description{r}#46]]. "
    },
    "status": 400
}
```

### PR DESCRIPTION
**Pull request by bpintea**
This fixes the incorrect ordering of the columns that can occur when INLINE STATS is pruned entirely, due to its calculated value being discarded (overshadowed).

Fixes #136797

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java [hunk 1]
```diff
@@ -1526,6 +1526,11 @@ public enum Cap {
          */
         GROK_MULTI_PATTERN,
 
+        /**
+         * Fix pruning of columns when shadowed in INLINE STATS
+         */
+        INLINE_STATS_PRUNE_COLUMN_FIX(INLINESTATS_V11.enabled),
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/EsqlCapabilities.java]:
```suggestion
        INLINE_STATS_PRUNE_COLUMN_FIX(INLINE_STATS.enabled),
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java [hunk 2]
```diff
@@ -140,7 +141,11 @@ private static LogicalPlan pruneColumnsInInlineJoinRight(InlineJoin ij, Attribut
         used.addAll(ij.references());
         var right = pruneColumns(ij.right(), used, true);
         if (right.output().isEmpty() || isLocalEmptyRelation(right)) {
-            p = ij.left();
+            // InlineJoin updates the order of the output, so even if the computation is dropped, the groups need to be pulled to the end
+            List<Attribute> newOutput = new ArrayList<>(ij.output());
+            AttributeSet leftOutputSet = ij.left().outputSet();
+            newOutput.removeIf(attr -> leftOutputSet.contains(attr) == false);
+            p = new EsqlProject(ij.source(), ij.left(), newOutput);
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java]:
```suggestion
            p = new Project(ij.source(), ij.left(), newOutput);
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java [hunk 3]
```diff
@@ -140,7 +141,11 @@ private static LogicalPlan pruneColumnsInInlineJoinRight(InlineJoin ij, Attribut
         used.addAll(ij.references());
         var right = pruneColumns(ij.right(), used, true);
         if (right.output().isEmpty() || isLocalEmptyRelation(right)) {
-            p = ij.left();
+            // InlineJoin updates the order of the output, so even if the computation is dropped, the groups need to be pulled to the end
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java]: I think this comment is putting an emphasis on re-ordering of the output elements, but in reality it's filtering the output based on the elements which are not needed anymore. The ordering is the same, only that some elements are filtered out.

**Review by astefan — APPROVED** [review]
LGTM. Left some minor comments, except the one with projection.

Also, I would add some variations to stats computations keepers and droppers:

```
ROW a = null, b = 0, c = "x", d = 1
| INLINE STATS a = MAX(c), d = MIN(c), e = AVG(b) by b
| EVAL a = c, d = 2

ROW a = null, b = 0, c = "x", d = 1
| INLINE STATS a = MAX(c), d = MIN(c), e = AVG(b), a = MIN(b) by b
| EVAL a = c, d = 2

ROW a = null, b = 0, c = "x", d = 1
| INLINE STATS a = MAX(c), d = MIN(c), e = AVG(b), a = MIN(b), f = MAX(b) by b
| EVAL a = c, d = 2
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java (hunk 3 above)
Comment (bpintea) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PruneColumns.java]: I've supplemented the comment.

**Comment by bpintea** [comment]
Thanks, Andrei.

> Also, I would add some variations to stats computations keepers and droppers:

I've added them, though with small completions, since all the computed values need to be overwritten -- only then does the bug show.
