### PR TITLE
Fix floating-point comparison in testRandomSamplerConsistentSeed method

### LINKED ISSUE #108841: [CI] RandomSamplerIT testRandomSamplerConsistentSeed failing
The test fails with what looks like a precision error.

```
Expected: <4.274308881754446>	
     but: was <4.274308881754445>
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/s7ltqwel6qgri/tests/:server:internalClusterTest/org.elasticsearch.search.aggregations.bucket.RandomSamplerIT/testRandomSamplerConsistentSeed

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.search.aggregations.bucket.RandomSamplerIT.testRandomSamplerConsistentSeed" -Dtests.seed=99C998C7BC4FC9DD -Dtests.locale=ga-IE -Dtests.timezone=NZ-CHAT -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.search.aggregations.bucket.RandomSamplerIT#testRandomSamplerConsistentSeed`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testRandomSamplerConsistentSeed'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.search.aggregations.bucket.RandomSamplerIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: <4.274308881754446>
     but: was <4.274308881754445>

  at __randomizedtesting.SeedInfo.seed([99C998C7BC4FC9DD:B89932E9FC6C40F8]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2188)
  at org.elasticsearch.search.aggregations.bucket.RandomSamplerIT.lambda$testRandomSamplerConsistentSeed$1(RandomSamplerIT.java:127)
  at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertResponse(ElasticsearchAssertions.java:375)
  at org.elasticsearch.search.aggregations.bucket.RandomSamplerIT.testRandomSamplerConsistentSeed(RandomSamplerIT.java:115)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

### PR DESCRIPTION
**Pull request by ivamly**
# Fix floating-point comparison in test Random Samples Consistent Seed method
## Description:
This pull request addresses an issue with floating-point precision in the testRandomSamplerConsistentSeed method. Previously, the test was comparing floating-point numbers for exact equality, which led to test failures due to minor precision errors.
## Changes:
Updated the testRandomSamplerConsistentSeed method to use a tolerance-based comparison for floating-point values.
Replaced exact equality checks with comparisons that account for minor discrepancies using a defined tolerance level (1e-14).
## Related Issues:
Closes #108841
## Checklist:

- [x]  Signed the Contributor License Agreement (CLA)
- [x]  Followed the contributor guidelines
- [x]  Built and tested your changes locally using gradle check
- [x]  Your pull request is against the main branch
- [x]  Verified that your submission targets an OS and architecture we support

### CODE REVIEW

**Comment by ivamly** [comment]
Hi,

I'm new to the open source community and excited to contribute. I apologize if my questions or contributions seem basic—I'm eager to learn and improve.

If there are any additional changes or improvements needed for this pull request, please let me know. I’m more than happy to make further adjustments or address any feedback you may have.

Thank you for your time and support!

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/RandomSamplerIT.java [hunk 1]
```diff
@@ -123,9 +124,12 @@ public void testRandomSamplerConsistentSeed() {
                     ),
                 response -> {
                     InternalRandomSampler sampler = response.getAggregations().get("sampler");
-                    assertThat(((Avg) sampler.getAggregations().get("mean_monotonic")).getValue(), equalTo(sampleMonotonicValue[0]));
-                    assertThat(((Avg) sampler.getAggregations().get("mean_numeric")).getValue(), equalTo(sampleNumericValue[0]));
-                    assertThat(sampler.getDocCount(), equalTo(sampledDocCount[0]));
+                    double monotonicValue = ((Avg) sampler.getAggregations().get("mean_monotonic")).getValue();
+                    double numericValue = ((Avg) sampler.getAggregations().get("mean_numeric")).getValue();
+                    long docCount = sampler.getDocCount();
+                    assertThat(Math.abs(monotonicValue - sampleMonotonicValue[0]) < tolerance, equalTo(true));
```
Comment (maxhniebergall) [inline server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/RandomSamplerIT.java:130]: This looks good, but I think it could be a bit better. If we use assertEquals instead of assertThat, I think we will get a slightly better error message if this fails. In junit.Assert there is an equals method for doubles which accepts a tolerance:

```suggestion
                    assertEquals(monotonicValue, sampleMonotonicValue[0], tolerance);
```

I would appreciate it if you would make this change.

**Review by maxhniebergall — COMMENTED** [review]
Thanks @ivamly, this change looks great! We very much appreciate your contribution!
There is a small change I would prefer before I approve your PR.

**Comment by maxhniebergall** [comment]
@elasticmachine test this

File: server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/RandomSamplerIT.java (hunk 1 above)
Comment (ivamly) [reply server/src/internalClusterTest/java/org/elasticsearch/search/aggregations/bucket/RandomSamplerIT.java:130]: Thanks for the feedback! I’ll update the PR in the next 30 minutes.

**Comment by ivamly** [comment]
Sorry if this is a basic question—I'm new to this process.

Do I need to add a changelog entry, set any labels, or take any other actions? Please let me know how I can help!

Thanks!

**Comment by maxhniebergall** [comment]
Yes, good point, there are some other things to do. Don't worry about the labels or changelogs too much, those can be handled by the elastician who reviews your PRs. I've added the `:ml` label because this is a change to a part of the code owned by the ML team. I've added the `>non-issue` label because this change only effects tests, and thus we don't need a changelog entry for it. I've added the `v8.16.0` label because that is the version of the next release.

**Review by maxhniebergall — APPROVED** [review]
Thanks for iterating! LGTM (looks good to me)!

**Comment by maxhniebergall** [comment]
@elasticmachine test this

**Comment by maxhniebergall** [comment]
Now we just wait for CI to finish running the tests, then we can merge this PR. Thanks for your contribution!

**Comment by ivamly** [comment]
Thanks for the explanations and for taking the time to help! It’s really helpful.
I'll start looking for other areas where I can contribute to the project.

**Comment by maxhniebergall** [comment]
Congrats on your first merged contribution to elasticsearch, @ivamly!
