### PR TITLE
Health Report API should not return RED for unassigned cold/frozen shards when data is available  #97606

### LINKED ISSUE #97606: Health Report API should not return RED for unassigned cold/frozen shards of ILM moves
### Elasticsearch Version

8.8.1+ but probably all versions

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

cloud

### Problem Description

This is a follow-up of [#97370](https://github.com/elastic/elasticsearch/issues/97370). 

In a case where disk spaces are reaching limits, if ILM suddenly tries to move a lot of hot shards to cold/frozen shards, it can tip the cluster health to RED because a lot of cold/frozen shards may be created and stay unassigned as long as there is not enough disk space. However, this is not a suitable indicator for service unavailability, since the data is still safely in the respective hot shards that are becoming cold/frozen, and will remain there until the cold/frozen shards are assigned so that searches can still search them.

Thus the [Health Report API](https://www.elastic.co/guide/en/elasticsearch/reference/8.8/health-api.html) should not return RED for unassigned cold/frozen shards of ILM moves.

### Steps to Reproduce

In a case where disk spaces are reaching limits, if ILM suddenly tries to move a lot of hot shards to cold/frozen shards, it can tip the cluster health to RED because a lot of cold/frozen shards may be created and stay unassigned (as long as there is not enough disk space).

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by gmarouli**
Quoting from the original ticket:

> We discussed this yesterday and a potential solution here is to report the fully and partially mounted indices health only if the source indices are missing (or red themselves).
e.g.

> if `restored-logs-2023.07.11-000024` is `RED` but `logs-2023.07.11-000024` is `GREEN` the health API returns GREEN
if `restored-logs-2023.07.11-000024` is `RED` AND `logs-2023.07.11-000024` is missing or `RED` itself, then the health API starts reporting on the health of the `restored-logs-2023.07.11-000024` (which would be `RED` already due to the source/original index being `RED` in the case when it still exists)

Fixes: https://github.com/elastic/elasticsearch/issues/97606

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java [hunk 1]
```diff
@@ -1532,6 +1534,150 @@ public void testLimitNumberOfAffectedResources() {
...
+            result,
+            equalTo(
+                createExpectedResult(
+                    GREEN,
+                    "This cluster has 1 unavailable primary shard.",
+                    Map.of("unassigned_primaries", 1, "started_primaries", 1),
+                    List.of(),
+                    List.of(
+                        new Diagnosis(ACTION_CHECK_ALLOCATION_EXPLAIN_API, List.of(new Diagnosis.Resource(INDEX, List.of(restoredIndex))))
+                    )
```
Comment (andreidan) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java:1580]: Is this at risk of causing confusion? I don't think GREEN should report problems, but perhaps the symptom should describe that even though we have one unavailable primary, it's a mounted index and the original index is still present?

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java [hunk 2]
```diff
@@ -1532,6 +1534,150 @@ public void testLimitNumberOfAffectedResources() {
...
+                    createExpectedResult(
+                        RED,
+                        "This cluster has 1 unavailable primary shard.",
+                        Map.of("unassigned_primaries", 1),
+                        List.of(
+                            new HealthIndicatorImpact(
+                                NAME,
+                                ShardsAvailabilityHealthIndicatorService.PRIMARY_UNASSIGNED_IMPACT_ID,
+                                1,
+                                "Cannot add data to 1 index [" + restoredIndex + "]. Searches might return incomplete results.",
```
Comment (andreidan) [inline server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java:1624]: Should we review the message in this context, given that the mounted index is consistently in a read-only state. Perhaps we could focus on mentioning how the search is impacted instead?
Similarly, the impacts should not contain INGEST ?

**Review by andreidan — COMMENTED** [review]
Thanks for working on this Mary. This is looking great. 

I left a few couple of questions around the messaging and diagnosis reporting.

**Comment by gmarouli** [comment]
Thank you @andreidan , I think you are right, we can improve our messaging, let me see what we can do. We might need separate diagnoses for certain cases. I will work something out.

**Comment by gmarouli** [comment]
Picking this up again.

**Comment by gmarouli** [comment]
@elasticmachine update branch

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java (hunk 2 above)
Comment (gmarouli) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java:1624]: About the impacts I agree, actually, I took it a bit further, I did not add any impacts here because the user is not experiencing any search or ingest impact.

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/part-2

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java (hunk 1 above)
Comment (gmarouli) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java]: I added one more sentence in case the only unavailable shards are the ones from the "green' frozen index. I think we can improve this in follow up work since we will probably fine grain the impacts as a bit more.

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
Test failure is unrelated: https://github.com/elastic/elasticsearch/issues/85697

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorService.java [hunk 3]
```diff
@@ -840,6 +864,14 @@ public String getSymptom() {
             } else {
                 builder.append("all shards available.");
             }
+            if (primaries.areAllAvailable()
+                && primaries.searchableSnapshotsState.searchableSnapshotWithOriginalIndexAvailable.isEmpty() == false) {
+                if (primaries.unassigned == 1) {
+                    builder.append(" This is a mounted shard and the original shard is available, so there is no data loss.");
+                } else {
+                    builder.append(" These are a mounted shard and the original shards are available, so there is no data loss.");
```
Comment (andreidan) [inline server/src/main/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorService.java:872]:
```suggestion
                    builder.append(" These are mounted shards and the original shards are available, so there are no data availability problems.");
```

**Review by andreidan — APPROVED** [review]
Thanks for fixing this Mary, left some super minor suggestions 🚀 

I believe it might be a bit more beneficial to focus on phrasing that emphasizes "data availability" rather than "data loss" (most - all I hope :) - deployments will have snapshots to protect against data loss)

File: server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java [hunk 4]
```diff
@@ -1532,6 +1534,157 @@ public void testLimitNumberOfAffectedResources() {
...
+        var service = createShardsAvailabilityIndicatorService(clusterState);
+
+        HealthIndicatorResult result = service.calculate(true, HealthInfo.EMPTY_HEALTH_INFO);
+        assertThat(
+            result,
+            equalTo(
+                createExpectedResult(
+                    GREEN,
+                    "This cluster has 1 unavailable primary shard. This is a mounted shard and the original "
+                        + "shard is available, so there is no data loss.",
```
[the remark this answers is not in the document]
Comment (gmarouli) [reply server/src/test/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorServiceTests.java:1576]: Nice, I like it.

File: server/src/main/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorService.java [hunk 5]
```diff
@@ -1048,4 +1099,35 @@ static List<Diagnosis.Resource> getRestoreFromSnapshotAffectedResources(
...
+        Set<String> getRedSearchableSnapshots() {
+            return Sets.difference(searchableSnapshotWithUnavailableShard, searchableSnapshotWithOriginalIndexAvailable);
+        }
+
+        // If the original index of a searchable snapshot with unavailable shards is available then we remove the searchable snapshot
+        // from the list of the unavailable searchable snapshots because the data is available via the original index.
+        void updateSearchableSnapshotWithAvailableIndices(Metadata clusterMetadata, Set<String> indicesWithUnavailableShards) {
+            for (String index : searchableSnapshotWithUnavailableShard) {
+                Settings indexSettings = clusterMetadata.index(index).getSettings();
+                String originalIndex = indexSettings.get(SearchableSnapshotsSettings.SEARCHABLE_SNAPSHOT_INDEX_NAME_SETTING_KEY);
```
[the remark this answers is not in the document]
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorService.java:1124]: I can add it, no objections, but out of curiosity, what is it offering? Theoretically, we would not be able to get here if it was null, because we need the settings to determine if it's a searchable snapshot.

[the remark this answers is not in the document]
Comment (andreidan) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorService.java:1124]: I'm a bit concerned about this line `clusterMetadata.index(index)` that could yield a `null` `IndexMetadata`.
It's that metadata that I'd like to assert it's not null (sorry my phrasing around the settings before was not precise enough). 

The assertion will give us a bit of protection against misusing the `updateSearchableSnapshotWithAvailableIndices` method with a different `Metadata` to the one we inspected the indices settings before.

[the remark this answers is not in the document]
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/cluster/routing/allocation/ShardsAvailabilityHealthIndicatorService.java:1129]: I will add it. No objections.

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by gmarouli** [comment]
@elasticmachine update branch
