### PR TITLE
Retry token creation on null httpInfo/transportInfo

### LINKED ISSUE #80922: Elasticsearch fails to generate kibana enrollment token on startup
This has been reported a couple of times already but I have been unable to figure out why it happens or reproduce it. The manifestation is that elasticsearch fails to generate and output a kibana enrollment token on startup and the following is logged:

```

[2021-11-19T13:14:07,824][ERROR][o.e.x.s.e.InternalEnrollmentTokenGenerator] [xxxxxxx] Failed to create enrollment when extracting HTTPS bound addresses
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.http.HttpInfo.getAddress()" because "httpInfo" is null
	at org.elasticsearch.xpack.security.enrollment.InternalEnrollmentTokenGenerator.getAllHttpAddresses(InternalEnrollmentTokenGenerator.java:188) ~[x-pack-security-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.xpack.security.enrollment.InternalEnrollmentTokenGenerator.assembleToken(InternalEnrollmentTokenGenerator.java:160) [x-pack-security-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.xpack.security.enrollment.InternalEnrollmentTokenGenerator.lambda$createKibanaEnrollmentToken$3(InternalEnrollmentTokenGenerator.java:127) [x-pack-security-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:136) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$0(NodeClient.java:107) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:176) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.tasks.TaskManager$1.onResponse(TaskManager.java:170) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:31) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$2(SecurityActionFilter.java:171) [x-pack-security-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.ActionListener$DelegatingFailureActionListener.onResponse(ActionListener.java:219) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:447) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.newResponseAsync(TransportNodesAction.java:181) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.nodes.TransportNodesAction.newResponse(TransportNodesAction.java:156) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.action.support.nodes.TransportNodesAction$AsyncAction.lambda$finishHim$0(TransportNodesAction.java:291) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:712) [elasticsearch-8.0.0-beta1.jar:8.0.0-beta1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

The relevant code is 

```java 
final NodesInfoRequest nodesInfoRequest = new NodesInfoRequest().nodesIds("_local")
            .addMetric(NodesInfoRequest.Metric.HTTP.metricName());
client.execute(NodesInfoAction.INSTANCE, nodesInfoRequest, ActionListener.wrap(response -> {
            assert response.getNodes().size() == 1;
            NodeInfo nodeInfo = response.getNodes().get(0);
            assembleToken(EnrollmentTokenType.KIBANA, nodeInfo.getInfo(HttpInfo.class), consumer);
}, e -> {
            LOGGER.error("Failed to create kibana enrollment token when retrieving local nodes HTTP info", e);
            consumer.accept(null);
}));
```

- we know it is a single node cluster and we ask the `_local` node. 
- we pass the HTTP metric in the request

For httpInfo to be null ( https://github.com/elastic/elasticsearch/blob/12ad399c488f0cc60e19b5e1b29c6d569cb4351a/server/src/main/java/org/elasticsearch/node/NodeService.java#L119) either HttpServerTransport is null and I can't see how this could be the case with default settings or (and most likely) this is a race and https://github.com/elastic/elasticsearch/blob/5e98ea427bc8bbc0120b099e501f425f1880a7b7/server/src/main/java/org/elasticsearch/http/AbstractHttpServerTransport.java#L155 hasn't finished yet so boundAddress is still `null`

Getting the full logs from a node where that happens will be helpful

### PR DESCRIPTION
**Pull request by jkakavas**
On node's initial startup, we attempt to create an enrollment
token for kibana (and potentially for other nodes). For doing so
we make internal requests to the NodeInfo API to get information
about the addresses the node is bound for http and transport layers.
We trigger this action on recovering the cluster state if the
security index doesn't already exist. There is, however,
no guarantee that our http and transport server component's (i.e.
Netty4HttpServerTransport) bindServer() method would have completed
and as such the boundAddress and thus the httpInfo/transportInfo
metric will be null.

This change adds retries (with exponential backoff) to our internal
client calls to the NodeInfo API to compensate for this race.

Resolves #80922

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/InitialNodeSecurityAutoConfiguration.java [hunk 1]
```diff
@@ -33,6 +36,7 @@
 public class InitialNodeSecurityAutoConfiguration {
 
     private static final Logger LOGGER = LogManager.getLogger(InitialNodeSecurityAutoConfiguration.class);
+    private static final BackoffPolicy BACKOFF_POLICY = BackoffPolicy.exponentialBackoff();
```
Comment (jkakavas) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/InitialNodeSecurityAutoConfiguration.java:39]: Given the lack of a better/more appropriate hook to trigger the token generation and the (admittedly only presumed in this point) scarcity of the manifestation of this, I think that the simplicity of a retry-with-backoffs solution is sufficient. Happy to discuss alternatives though

Comment (albertzaharovits) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/InitialNodeSecurityAutoConfiguration.java:39]: I took a close look at this.

I think the race is because the enrollment token generation starts when the `Node` is **instantiated** but the"tcp" and "http" transports, which are needed for the token to actually be created, only become available when the node **started**.

> Given the lack of a better/more appropriate hook to trigger the token generation

Ideally, the token generation should start when the state has been recovered without a `security` index (what we do today) AND the `ClusterPlugin#onNodeStarted` has been invoked on the `Security` plugin (at which point we know the transports are available). Basically, we are safe to trigger the generation of the enrollment token, when the last of these two actions completed (I thought of using a `CountDown(2)` for it).

I tried having a quick attempt at it to suggest here, but I couldn't get it to a small code change size, because the "when both of the two action completed" condition requires shifting around every line in the class `InitialNodeSecurityAutoConfiguration`.

If you agree with my train of thoughts above, I would suggest we open an enhancement request to avoid the polling you're introducing here (because we're in a bit of a hurry atm).

**Review by albertzaharovits — APPROVED** [review]
I have suggested we open an enhancement issue to improve so that we avoid polling for when the transports are initialized.
Otherwise LGTM.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/InitialNodeSecurityAutoConfiguration.java (hunk 1 above)
Comment (jkakavas) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/InitialNodeSecurityAutoConfiguration.java:39]: Yes, I do agree both with your suggestion on the proposed solution and to merge this as a stop-gap solution until we can figure out the implementation details. I was looking on `onNodeStarted` too when thinking about solutions, but it wasn't obvious to me either how to best make this change so that our action is triggered when both these are notified. Thanks for spending the time on proper possible solutions

Comment (jkakavas) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/InitialNodeSecurityAutoConfiguration.java:39]: I opened https://github.com/elastic/elasticsearch/issues/81160, happy to review if you get the cycles/time to look at it, otherwise I'll try to plan this for on of the following releases
