### PR TITLE
[test] Fix IndexShardTests#testScheduledRefresh

### LINKED ISSUE #101008: [CI] IndexShardTests testScheduledRefresh failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/bwrmwilszqh5q/tests/:server:test/org.elasticsearch.index.shard.IndexShardTests/testScheduledRefresh
**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.index.shard.IndexShardTests.testScheduledRefresh" -Dtests.seed=88A229401DB0EADC -Dtests.locale=en-MT -Dtests.timezone=Africa/Porto-Novo -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.shard.IndexShardTests&tests.test=testScheduledRefresh
**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([88A229401DB0EADC:7E376AAA492A3155]:0)
  at org.junit.Assert.fail(Assert.java:86)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.elasticsearch.index.shard.IndexShardTests.testScheduledRefresh(IndexShardTests.java:3875)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by arteam**
After we flushed the shard, we only make sure that the refresh call is propagated to the shard engine, but we can't be sure that the call is actually ends up in a shard refresh. The call in `InternalEngine#refresh` can return `false` if we couldn't acquire the lock on `ElasticsearchDirectoryReader`, because it's already being refreshed.

We can wrap the call in `assertBusy` to retry it in order to make sure that the shard eventually gets refreshed.

Resolves #101008

### CODE REVIEW

**Comment by fcofdez** [comment]
> The call in InternalEngine#refresh can return false if we couldn't acquire the lock on ElasticsearchDirectoryReader, because it's already being refreshed.

But this test concerns the `IndexShard` alone, meaning that there shouldn't be any background threads trying to refresh the shard (i.e. scheduled refreshes). Could you elaborate on which thread is calling refresh concurrently?

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java [hunk 1]
```diff
@@ -3927,9 +3926,11 @@ public void testScheduledRefresh() throws Exception {
         assertTrue(primary.searchIdleTime() >= TimeValue.ZERO.millis());
         primary.flushOnIdle(0);
         logger.info("--> scheduledRefresh(future5)");
```
Comment (kingherc) [inline server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: I have some questions related to the test (and not specifically to this line) that I don't understand:
* Why is `assertFalse(future4.actionGet());`? The comment before future4 says `while shard is search active and ensure scheduleRefresh(...) makes documen visible:`. So I am not sure why the scheduled refresh returns false? I think that the shard was search idle, and that's why the scheduled refresh is false. Right? We should probably correct that comment.
* Is the `primary.flushOnIdle(0);` actually flushing the shard? Doesn't flush also refresh? So how come `assertTrue(future5.actionGet());`? I would expect that since the shard was refreshed during the flush, that the scheduled refresh of future5 would return false.

Until I understand the test, I'm not sure I can follow the proposed solution. Any answers would be very helpful to me!

Comment (fcofdez) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: >  I think that the shard was search idle, and that's why the scheduled refresh is false. Right? We should probably correct that comment.

Yes, that's the reason why it returns false in this case, we should update the comment 👍.

>  Doesn't flush also refresh? 

Notice that the refresh executed after a flush concerns the internal searcher (https://github.com/elastic/elasticsearch/blob/6ae652f90e7b15d9eef81fa745da299d39845655/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L2225) whereas the scheduled refresh concerns the external searcher (https://github.com/elastic/elasticsearch/blob/6ae652f90e7b15d9eef81fa745da299d39845655/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L2020) hence the need for the explicit refresh.

If it's the flush thread racing against the scheduled refresh call what's causing this test failure, I'm not sure if the proposed solution will fix it, since it will return false always as the refresh will be a no-op.

Comment (kingherc) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: Thanks @fcofdez for the clarification, I see!

> If it's the flush thread racing against the scheduled refresh call what's causing this test failure, I'm not sure if the proposed solution will fix it, since it will return false always as the refresh will be a no-op.

Why is that? I think it actually may work. If there's a race with flush and refresh, the refresh may return false due to the race. But once the flush is executed, it makes `active` flag to be `false`, which should make the `scheduledRefresh()` finally refresh. So an assertBusy with scheduledRefresh should finally succeed. Right?

Comment (fcofdez) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: >  which should make the scheduledRefresh() finally refresh. So an assertBusy with scheduledRefresh should finally succeed. Right?

But if the refresh results in a no-op (there're no pending docs in the Lucene IndexWriter) the refresh will return false  , right?

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java [hunk 2]
```diff
@@ -3927,9 +3926,7 @@ public void testScheduledRefresh() throws Exception {
...
-        PlainActionFuture<Boolean> future5 = new PlainActionFuture<>();
-        primary.scheduledRefresh(future5);
-        assertTrue(future5.actionGet()); // make sure we refresh once the shard is inactive
+        assertTrue(primary.scheduledRefresh(ActionListener.noop())); // make sure we refresh once the shard is inactive
```
Comment (kingherc) [inline server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3929]: I preferred the assertBusy solution you did initially, which confirms that the refresh is truly executed.

The current code asserts the refresh is sent, but the refresh happens asynchronously and races with the subsequent searcher (so in some cases it might see 2 docs and in others 3 docs).

File: server/src/main/java/org/elasticsearch/index/shard/IndexShard.java [hunk 3]
```diff
@@ -3950,8 +3950,8 @@ ReplicationTracker getReplicationTracker() {
     /**
      * Executes a scheduled refresh if necessary. Completes the listener with true if a refresh was performed otherwise false.
      */
-    public void scheduledRefresh(ActionListener<Boolean> listener) {
-        ActionListener.run(listener, l -> {
+    public boolean scheduledRefresh(ActionListener<Boolean> listener) {
```
Comment (kingherc) [inline server/src/main/java/org/elasticsearch/index/shard/IndexShard.java:3953]: I don't think it's necessary to know we sent the refresh request or not. See my other comment, I believe the assertBusy solution was sufficient.

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java (hunk 1 above)
Comment (fcofdez) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: But for some reason there's another thread calling refresh and that's what's causing the test to fail, either the scheduled refresh is not able to acquire the reader manager lock or the scheduled refresh results in a no-op, in both cases I think that the assertBusy won't help with this. I would like for us to reproduce this issue with some sleeps or something.

File: server/src/main/java/org/elasticsearch/index/shard/IndexShard.java (hunk 3 above)
Comment (arteam) [reply server/src/main/java/org/elasticsearch/index/shard/IndexShard.java:3953]: Hey @kingherc! I liked the `assertBusy` option better, too, because we don't need to go the implementation details of `scheduledRefresh`. I also found that `SearchIdleIT` faced a a similar issue and the test worked around it by blocking the refresh pool which also seems quite hacky.

I've reverted my last commit and kept the `assertBusy` solution. It seems that it indeed should be reliable due the addition of the second document.

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java (hunk 1 above)
Comment (kingherc) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: Oh so far I thought we concluded that there's a race between the flush and the refresh. I didn't understand there was another refresh request going on. For my sake, where did we confirm/see this other refresh request (e.g., in the logs)?

File: server/src/main/java/org/elasticsearch/index/shard/IndexShard.java (hunk 3 above)
Comment (kingherc) [reply server/src/main/java/org/elasticsearch/index/shard/IndexShard.java:3953]: (I don't see the assertBusy yet.)

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java (hunk 1 above)
Comment (fcofdez) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: Looking more closely into the logs, it must be a concurrent refresh what's causing this, because the flush is executed _after_ the test fails:
```
[2024-03-21T12:21:28,090][INFO ][o.e.i.s.IndexShardTests  ] [testScheduledRefresh] --> scheduledRefresh(future5) |  
-- | --
  | [2024-03-21T12:21:28,090][TRACE][o.e.i.s.IndexShard       ] [testScheduledRefresh] [test][0] scheduledRefresh: refresh with source [schedule] |  
  | [2024-03-21T12:21:28,091][INFO ][o.e.i.s.IndexShardTests  ] [testScheduledRefresh] after test |  
  | [2024-03-21T12:21:28,093][TRACE][o.e.i.s.IndexShard       ] [org.elasticsearch.index.shard.IndexShardTests] [test][0] flush with FlushRequest{waitIfOngoing=false, force=false}
```
I think that @arteam should dig deeper into what's going on here.

Comment (kingherc) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: @fcofdez After looking at the logs you mentioned (thanks!), I believe it's not another refresh. But it's actually exactly because the flush may happen after the future5's refresh request! If the flush happens after the scheduledRefresh call, then the scheduledRefresh (similarly to future4) is not executed as it's still search idle (`active` is true). The flush is the operation that turns `active` to false, and is able to make the scheduledRefresh actually execute a refresh.

Thus, I think finally that the best solution is to do the following:

```
        long flushesBefore = primary.flushStats().getTotal();
        primary.flushOnIdle(0);
        assertBusy(() -> {
            assertThat(primary.flushStats().getTotal(), greaterThan(flushesBefore));
        });
```

Comment (fcofdez) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: but the log line ` [2024-03-21T12:21:28,090][TRACE][o.e.i.s.IndexShard       ] [testScheduledRefresh] [test][0] scheduledRefresh: refresh with source [schedule]` hints that the scheduled refresh goes through

File: server/src/main/java/org/elasticsearch/index/shard/IndexShard.java (hunk 3 above)
Comment (arteam) [reply server/src/main/java/org/elasticsearch/index/shard/IndexShard.java]: Sorry, the commit didn't get pushed due to network issues. Should be visible now.

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java (hunk 1 above)
Comment (kingherc) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: I see. Hmm, this is still a bit messy to the asyncronicity of the flush and the refresh. I believe this is still the issue rather than a second refresh. 

Here's one possibility I see that this could error:
- `flushOnIdle` sets `active` to false, but not yet schedules the flush.
- `scheduledRefresh` can go into `maybeRefresh` because it sees `active` as false.
- So we can now have two racing `InternalEngine#refresh()` calls (one with internal scope due to the flush, and one for external due to the scheduled refresh).
- At the same point, they do `if (store.tryIncRef()) {`, and the flush wins while the refresh does not win.

But indeed it seems worth @arteam to figure it out and confirm, e.g., by reproducing the issue somehow. To also ensure we don't have other refreshes.

Comment (arteam) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3928]: Let me try to see if I manage something similar to `SearchIdleIT#ensureNoPendingScheduledRefresh`

Comment (arteam) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3934]: @kingherc I've added a check that the flush finishes before the refresh and a check that there are no pending refreshes.

Comment (fcofdez) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3933]: > At the same point, they do if (store.tryIncRef()) {, and the flush wins while the refresh does not win.

@kingherc but the store shouldn't be closed while the test is running 🤔 (both flush and refresh should be able to incRef the store ref unless the shard is closing)

Comment (fcofdez) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3933]: The only possibility is that https://github.com/elastic/elasticsearch/blob/bdc65cbc901ae059ef67da9a76cac870fd8c1ea1/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L2046 returns `false` due to a concurrent refresh making this one a no-op.

Comment (kingherc) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3933]: @fcofdez , when I was quickly checking the code, I mistakenly thought `tryIncRef` does not have while-loop internally to retry, but it does, so my thinking was erroneous. Needs more in-depth investigation than my quick going-back-and-forth in the code finally :D 

Still I believe it was not the intention of the test to let both the flush & the refresh to race with each other. However, I cannot say for sure why the racing results in refresh returning false. It would be good to understand why @arteam , plus whether there's some other refresh going on as @fcofdez suggests. @arteam were you able to reproduce it? Maybe we can add some more tracing to see if another refresh is going on.

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java [hunk 4]
```diff
@@ -3925,8 +3926,12 @@ public void testScheduledRefresh() throws Exception {
         logger.info("--> ensure search idle");
         assertTrue(primary.isSearchIdle());
         assertTrue(primary.searchIdleTime() >= TimeValue.ZERO.millis());
+        long periodicFlushesBefore = primary.flushStats().getPeriodic();
         primary.flushOnIdle(0);
+        assertBusy(() -> assertThat(primary.flushStats().getPeriodic(), greaterThan(periodicFlushesBefore)));
+
         logger.info("--> scheduledRefresh(future5)");
+        ensureNoPendingScheduledRefresh();
```
Comment (kingherc) [inline server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3934]: If there's some spurious refresh being run, we cannot be sure it is at this exact spot.

Maybe a better approach would be to get the number of external refreshes before the future5, and asserting that after the scheduled refresh, it's incremented by 1.

Comment (arteam) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java]: @kingherc That's a great idea. I've replaced the hack with blocking the refresh thread pool with checking the refresh stats.

Comment (fcofdez) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java]: I would like to understand why the test was failing, in the logs of the test failures you can see that the flush is executed _after_ the assertion trips, so I'm not convinced about the flush being the issue here

**Comment by arteam** [comment]
@elasticmachine update branch

File: server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java [hunk 5]
```diff
@@ -3925,11 +3924,16 @@ public void testScheduledRefresh() throws Exception {
...
+        assertBusy(() -> assertThat(primary.flushStats().getPeriodic(), greaterThan(periodicFlushesBefore)));
+
+        long externalRefreshesBefore = primary.refreshStats().getExternalTotal();
         logger.info("--> scheduledRefresh(future5)");
-        PlainActionFuture<Boolean> future5 = new PlainActionFuture<>();
-        primary.scheduledRefresh(future5);
-        assertTrue(future5.actionGet()); // make sure we refresh once the shard is inactive
+        primary.scheduledRefresh(ActionListener.noop());
+        // We can't check whether scheduledRefresh returns true because it races with a potential
+        // refresh triggered by the flush. We just check that one the refreshes ultimately wins.
```
[the remark this answers is not in the document]
Comment (arteam) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3935]: @kingherc I'm not sure what we can investigate. There are always a probability of a refresh whether from a flush or from some other process. We can't deterministically check whether an individual refresh request will succeed. We can't even realistically control when the flush will be executed, since it's also asynchronous.

The test is suppose to check that a refresh goes through from `IndexShard#scheduledRefresh` to `engine.maybeRefresh` when the shard is no longer idle. Since don't have enough isolation to test that, we have to rely on eihter re-trying refreshes until one succeeds or checking refresh stats.

[the remark this answers is not in the document]
Comment (fcofdez) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3935]: If we think that the problem is the concurrent flush (I don't think that's the issue, since the flush logs _after_ the test fails) we should either try to reproduce it with sleeps or maybe inject a deterministic thread pool that allows us to control the execution order. Otherwise we risk not fixing the real issue for this test.

[the remark this answers is not in the document]
Comment (arteam) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3935]: @fcofdez The original test was never suppose to test that, it just tested that the refresh is actually gets triggered when the shard isn't idle. Here's original pull request from 2017 https://github.com/elastic/elasticsearch/pull/27500.

I still think it doesn't matter whether another refresh gets triggered by a flush or another background refresh, because we can't guarantee that any individual refresh call will return `true`.

So, the current change tries to mimic the original scenario for this PR (a sync flush followed by a refresh and check that some refresh has completed).

[the remark this answers is not in the document]
Comment (kingherc) [reply server/src/test/java/org/elasticsearch/index/shard/IndexShardTests.java:3935]: Should we sync on this in a short call?

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by fcofdez — APPROVED** [review]
LGTM

**Review by kingherc — APPROVED** [review]
LGTM. Please handle the two comments I mentioned before merging.

**Comment by arteam** [comment]
@kingherc Sorry about the auto merge, I will address your comments in a follow up PR!
