### PR TITLE
Warn about unlicensed realms if no auth token can be extracted

### LINKED ISSUE #61090: Realm authentication failures are not logged when anonymous access is enabled
When authentication fails, we [log](https://github.com/elastic/elasticsearch/blob/7.9/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/AuthenticationService.java#L594-L609) realms that have failed to authenticate the user as well as any realms that are skipped due to lack of license. 

However, when anonymous access is enabled and a request comes in without any credentials, the code [short-circuits](https://github.com/elastic/elasticsearch/blob/7.9/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/AuthenticationService.java#L556) to fallback to anonymous user and thus skips the above error logging code.

We should provide logging messages for usage of unlicensed realms in all cases to 1) send clear message to users that they have configured something that do not work; 2) help troubleshooting when it happens.

### PR DESCRIPTION
**Pull request by ywangd**
There are warnings about unlicense realms when user lookup fails. This PR adds the similar warnings for when no authentication token can be extracted from the request.

Resolves: #61090

### CODE REVIEW

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/AuthenticationService.java [hunk 1]
```diff
@@ -554,6 +554,13 @@ private void consumeToken(AuthenticationToken token) {
          */
         // pkg-private for tests
         void handleNullToken() {
+            List<Realm> unlicensedRealms = realms.getUnlicensedRealms();
+            if (unlicensedRealms.isEmpty() == false) {
+                logger.warn("No authentication token can be extracted using realms [{}]." +
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/AuthenticationService.java:559]: Can we avoid the `token` word? It leads people to look at the token service and ....

In the section below we say `No valid credentials found` which is terminology that could probably be adapted to work here.
```suggestion
                logger.warn("No authentication credential could be extracted using realms [{}]." +
```

**Review by tvernum — APPROVED** [review]
LGTM, pending removal of "token"
