### PR TITLE
Fix CrossClusterEsqlRCSEnrichUnavailableRemotesIT failing tests

### LINKED ISSUE #119910: [CI] CrossClusterEsqlRCS2EnrichUnavailableRemotesIT testEsqlEnrichWithSkipUnavailable failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #5818 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/k37z6hgwofdwg)
- [elasticsearch-periodic-platform-support #5808 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/ksuei2avuockm)
- [elasticsearch-periodic-platform-support #5768 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/hu7snhbwe3xjo)
- [elasticsearch-periodic-platform-support #5763 / windows-2019_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/5poavncgbqwwe)
- [elasticsearch-periodic-platform-support #5763 / windows-2022_checkpart4_platform-support-windows](https://gradle-enterprise.elastic.co/s/2anigsjodtxi4)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:security:qa:multi-cluster:javaRestTest" --tests "org.elasticsearch.xpack.remotecluster.CrossClusterEsqlRCS2EnrichUnavailableRemotesIT.testEsqlEnrichWithSkipUnavailable" -Dtests.seed=B016FE1422A86EB3 -Dtests.locale=en-SE -Dtests.timezone=America/Creston -Druntime.java=23
```

**Applicable branches:**
8.17

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.remotecluster.CrossClusterEsqlRCS2EnrichUnavailableRemotesIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testEsqlEnrichWithSkipUnavailable),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: "connect_transport_exception"
     but: was "node_disconnected_exception"
```

**Issue Reasons:**
- [8.17] 5 failures in test testEsqlEnrichWithSkipUnavailable (1.4% fail rate in 358 executions)
- [8.17] 2 failures in step windows-2022_checkpart4_platform-support-windows (16.7% fail rate in 12 executions)
- [8.17] 3 failures in step windows-2019_checkpart4_platform-support-windows (27.3% fail rate in 11 executions)
- [8.17] 4 failures in pipeline elasticsearch-periodic-platform-support (33.3% fail rate in 12 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by quux00**
Fixes https://github.com/elastic/elasticsearch/issues/119910

### CODE REVIEW

**Comment by pawankartik-elastic** [comment]
I have a question: is there a reason why this test failure occurs only on Windows? I tried to get this issue to reproduce this on a Windows machine but couldn't, even with the same seed.

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/CrossClusterEsqlRCS1EnrichUnavailableRemotesIT.java [hunk 1]
```diff
@@ -185,8 +187,7 @@ private void esqlEnrichWithSkipUnavailableTrue() throws Exception {
             Map<String, ?> failuresMap = (Map<String, ?>) remoteClusterFailures.get(0);
 
             Map<String, ?> reason = (Map<String, ?>) failuresMap.get("reason");
-            assertThat(reason.get("type").toString(), equalTo("connect_transport_exception"));
-            assertThat(reason.get("reason").toString(), containsString("Unable to connect to [my_remote_cluster]"));
```
Comment (smalyshev) [inline x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/CrossClusterEsqlRCS1EnrichUnavailableRemotesIT.java:189]: I wonder if we could keep the check that the error message mentions `my_remote_cluster` (if that's the case) maybe without requiring all other stuff to match.

Comment (quux00) [reply x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/CrossClusterEsqlRCS1EnrichUnavailableRemotesIT.java:189]: Since I'm not able to reproduce the failure, I'm hesitant to do that. We don't control what error messages come from the underlying transport layer, so testing for that doesn't test for anything we can change. The error message will be whatever the transport layer decides it wants it to be depending on what exact sequence of transport issues happened (and there can be many different errors from disconnected clusters). The key point of this test is that it reports some sort of disconnected/transport error rather than an ESQL verification exception which is what it was doing before [Pawan's fix](https://github.com/elastic/elasticsearch/pull/119750).

**Review by smalyshev — APPROVED** [review]
