### PR TITLE
Skip all geo point queries in plain highlighter

### LINKED ISSUE #17537: Invalid shift value (xx) in prefixCoded bytes (is encoded value really a geo point?)
Hi guys,

we have upgraded ElasticSearch from 2.3.0 and reindexed our geolocations so the latitude and longitude are stored separately. We have noticed that some of our visualisation started to fail after we add a filter based on geolocation rectangle. However, map visualisation are working just fine. The problem occurs when we include actual documents. In this case, we get some failed shards (usually 1 out of 5) and error: Invalid shift value (xx) in prefixCoded bytes (is encoded value really a geo point?).

Details:
Our geolocation index is based on:

    "dynamic_templates": [{
    ....
    {
            "ner_geo": {
              "mapping": {
                "type": "geo_point",
                "lat_lon": true
              },
              "path_match": "*.coordinates"
            }
          }],

The ok query with the error is as follows. If we change the query size to 0 (map visualizations example), the query completes without problem.

    {
      "size": 100,
      "aggs": {
        "2": {
          "geohash_grid": {
            "field": "authors.affiliation.coordinates",
            "precision": 2
          }
        }
      },
      "query": {
        "filtered": {
          "query": {
            "query_string": {
              "analyze_wildcard": true,
              "query": "*"
            }
          },
          "filter": {
            "bool": {
              "must": [
                {
                  "geo_bounding_box": {
                    "authors.affiliation.coordinates": {
                      "top_left": {
                        "lat": 61.10078883158897,
                        "lon": -170.15625
                      },
                      "bottom_right": {
                        "lat": -64.92354174306496,
                        "lon": 118.47656249999999
                      }
                    }
                  }
                }
              ],
              "must_not": []
            }
          }
        }
      },
      "highlight": {
        "pre_tags": [
          "@kibana-highlighted-field@"
        ],
        "post_tags": [
          "@/kibana-highlighted-field@"
        ],
        "fields": {
          "*": {}
        },
        "require_field_match": false,
        "fragment_size": 2147483647
      }
    }

Elasticsearch version**: 2.3.0
OS version**: Elasticsearch docker image with head plugin, marvel and big desk installed

Thank you for your help,
regards,
Jakub Smid

### PR DESCRIPTION
**Pull request by brwe**
Geo queries and plain highlighter do not seem to work well
together (https://issues.apache.org/jira/browse/LUCENE-7293)
so we need to skip all geo related queries when we highlight.

hopefully closes #17537

Only plain highlighter seems to be affected.
I am worried that we might need to take care of GeoPointInBBoxQueryImpl too although I do not see how a rewritten query can be used for highlighting, see TODO below. 

@nik9000 since this was your idea, maybe you want to take a look?

### CODE REVIEW

**Comment by nik9000** [comment]
LGTM. Highlighter is all hacks so another one won't hurt. Much.

File: core/src/main/java/org/elasticsearch/search/highlight/CustomQueryScorer.java [hunk 1]
```diff
@@ -87,6 +88,12 @@ protected void extractUnknownQuery(Query query,
             }
         }
 
+        protected void extract(Query query, float boost, Map<String, WeightedSpanTerm> terms) throws IOException {
+            // skip all geo queries, see https://issues.apache.org/jira/browse/LUCENE-7293 and
+            // https://github.com/elastic/elasticsearch/issues/17537
+            if (query instanceof GeoPointInBBoxQuery == false) {
```
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/search/highlight/CustomQueryScorer.java]: Do we also expose `GeoPointDistanceQuery` or `GeoPointInPolygonQuery`?

**Comment by mikemccand** [comment]
I left one comment, else LGTM.  Thanks @brwe!

File: core/src/main/java/org/elasticsearch/search/highlight/CustomQueryScorer.java (hunk 1 above)
Comment (mikemccand) [inline core/src/main/java/org/elasticsearch/search/highlight/CustomQueryScorer.java]: Sorry, nevermind: both of those queries also subclass `GeoPoinInBBoxQuery`, so this check is sufficient!

**Comment by s1monw** [comment]
LGTM too

**Comment by brwe** [comment]
Backported to 2.x here https://github.com/elastic/elasticsearch/commit/d2d670d96b3cbb054f5e4160bbc96345fdeb80ba and here https://github.com/elastic/elasticsearch/commit/13c3dd8f76787fc1c94f7edd09bf27879ac83dbc
