### PR TITLE
[Inference API] Wait for rate limit assignments to happen in rate limit calculator tests

### LINKED ISSUE #121294: [CI] InferenceServiceNodeLocalRateLimitCalculatorTests class failing
**Build Scans:**
- [elasticsearch-periodic #6153 / release-tests](https://gradle-enterprise.elastic.co/s/4ugwidz24dv5c)
- [elasticsearch-periodic #6146 / release-tests](https://gradle-enterprise.elastic.co/s/zcogrhp6i7xyk)
- [elasticsearch-periodic #6139 / release-tests](https://gradle-enterprise.elastic.co/s/5zt52arye5pp2)
- [elasticsearch-periodic #6132 / release-tests](https://gradle-enterprise.elastic.co/s/zcok7rlu5y3mw)
- [elasticsearch-periodic #6125 / release-tests](https://gradle-enterprise.elastic.co/s/vsoz6f2rgoiqi)
- [elasticsearch-periodic #6118 / release-tests](https://gradle-enterprise.elastic.co/s/andg4mc6mtvue)
- [elasticsearch-periodic #6111 / release-tests](https://gradle-enterprise.elastic.co/s/scufvd5tujvh2)
- [elasticsearch-pull-request #54447 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/t6wxc4bfwc34o)
- [elasticsearch-pull-request #54436 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/oqwynramcqs24)
- [elasticsearch-pull-request #54412 / checkpart2_release-tests](https://gradle-enterprise.elastic.co/s/fmfblac5h6s56)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.common.InferenceServiceNodeLocalRateLimitCalculatorTests.testRateLimits_Decrease_OnNodeJoin" -Dtests.seed=2BE643421E81E555 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=fil-Latn-PH -Dtests.timezone=America/Porto_Acre -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.common.InferenceServiceNodeLocalRateLimitCalculatorTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.xpack.inference.common.InferenceServiceNodeLocalRateLimitCalculatorTests),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: [org.elasticsearch.xpack.inference.common.InferenceServiceNodeLocalRateLimitCalculatorTests] should use [org.elasticsearch.xpack.inference.common.InferenceServiceNodeLocalRateLimitCalculator] as implementation for [org.elasticsearch.xpack.inference.common.InferenceServiceRateLimitCalculator]. Provided implementation was [org.elasticsearch.xpack.inference.common.NoopNodeLocalRateLimitCalculator].
Expected: an instance of org.elasticsearch.xpack.inference.common.InferenceServiceNodeLocalRateLimitCalculator
     but: <org.elasticsearch.xpack.inference.common.NoopNodeLocalRateLimitCalculator@6a8d4370> is a org.elasticsearch.xpack.inference.common.NoopNodeLocalRateLimitCalculator
```

**Issue Reasons:**
- [main] 7 consecutive failures in step release-tests
- [main] 4 consecutive failures in step checkpart2_release-tests
- [main] 18 failures in class org.elasticsearch.xpack.inference.common.InferenceServiceNodeLocalRateLimitCalculatorTests (3.2% fail rate in 570 executions)
- [main] 8 failures in step release-tests (72.7% fail rate in 11 executions)
- [main] 10 failures in step checkpart2_release-tests (66.7% fail rate in 15 executions)
- [main] 8 failures in pipeline elasticsearch-periodic (72.7% fail rate in 11 executions)
- [main] 9 failures in pipeline elasticsearch-pull-request (4.4% fail rate in 205 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by timgrein**
Fixes https://github.com/elastic/elasticsearch/issues/121294

`ensureStableCluster` doesn't guarantee that the nodes already processed the rate limit assignments, but only guarantees that each node:
- Responded to a health check
- Didn't timeout
- The cluster is fully connected

Therefore we need to wait (set the timeout to 15 seconds to begin with), which should give each node/calculator enough time to process the topology change and calculate the rate limit assignments. This is a pattern I saw throughout the whole ES codebase (using `assertBusy(() -> {...})`).

### CODE REVIEW

File: x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/common/InferenceServiceNodeLocalRateLimitCalculatorTests.java [hunk 1]
```diff
@@ -27,38 +27,36 @@
 @ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.SUITE, numDataNodes = 0)
 public class InferenceServiceNodeLocalRateLimitCalculatorTests extends ESIntegTestCase {
 
+    private static final Integer RATE_LIMIT_ASSIGNMENT_MAX_WAIT_TIME_IN_SECONDS = 15;
```
Comment (timgrein) [inline x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/common/InferenceServiceNodeLocalRateLimitCalculatorTests.java:30]: This is only used once, but I wanted to make it obvious that we've a timeout throughout this class. Therefore put it at the top as a constant.

**Review by jonathan-buttner — APPROVED** [review]
