### PR TITLE
Fix CCS cancellation test

### LINKED ISSUE #117568: [CI] CrossClustersCancellationIT testCancel failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #5110 / amazonlinux-2_platform-support-aws](https://gradle-enterprise.elastic.co/s/f4bgs5lzzntae)
- [elasticsearch-pull-request #43999 / part-3](https://gradle-enterprise.elastic.co/s/qza6zeatapmww)
- [elasticsearch-pull-request #43844 / part-3](https://gradle-enterprise.elastic.co/s/jwpv7gmqi6qi2)
- [elasticsearch-pull-request #43708 / part-3](https://gradle-enterprise.elastic.co/s/zwm74whycizne)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:internalClusterTest" --tests "org.elasticsearch.xpack.esql.action.CrossClustersCancellationIT.testCancel" -Dtests.seed=77BD499E34EA2944 -Dtests.locale=oc -Dtests.timezone=Indian/Christmas -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.action.CrossClustersCancellationIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testCancel),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Expected exception Exception but no exception was thrown
```

**Issue Reasons:**
- [main] 4 failures in test testCancel (1.1% fail rate in 364 executions)
- [main] 3 failures in step part-3 (2.3% fail rate in 131 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (2.3% fail rate in 131 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dnhatn**
We should have checked that all drivers were canceled, not cancellable (which is always true), before unblocking the compute tasks.

Closes #117568

### CODE REVIEW

**Review by smalyshev — APPROVED** [review]

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClustersCancellationIT.java [hunk 1]
```diff
@@ -179,19 +179,22 @@ public void testCancel() throws Exception {
...
-        assertBusy(() -> {
-            List<TaskInfo> drivers = client(REMOTE_CLUSTER).admin()
-                .cluster()
-                .prepareListTasks()
-                .setActions(DriverTaskRunner.ACTION_NAME)
-                .get()
-                .getTasks();
-            assertThat(drivers.size(), greaterThanOrEqualTo(1));
-            for (TaskInfo driver : drivers) {
-                assertTrue(driver.cancellable());
```
Comment (smalyshev) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClustersCancellationIT.java:191]: Tbh, it gave me a pause the first time I read it because I thought it's supposed to be cancellable always, why check it, but then I forgot about this. Thanks for addressing it!

**Comment by dnhatn** [comment]
Thanks @smalyshev.
