### PR TITLE
Do not track named queries that are null

### LINKED ISSUE #12683: common terms query containing only stopwords with a _name causes a null pointer exception
A common query containing only stopwords causes a NullPointerException if the query has a _name property.  This doesn't happen without the _name property, and doesn't happen with other types of queries.

```
# create index 
curl -XPOST localhost:9200/test -d '{
 "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "type1" : {
            "properties" : {
                "name" : { "type" : "string", "analyzer" : "stop" }
            }
        }
    }
}'
```

```
# common query with a stop word correctly returns no results
curl -XGET localhost:9200/test/type1/_search -d '{
    "query": {
        "common": {
            "name": {
                "query": "the"
            }
        }
    }
}'

{"took":35,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},
"hits":{"total":0,"max_score":null,"hits":[]}}
```
```
# common query with a _name causes a null pointer exception
curl -XGET localhost:9200/test/type1/_search -d '{
    "query": {
        "common": {
            "name": {
                "query": "the",
                "_name": "queryname"
            }
        }
    }
}'

{"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[vFIFOFczQTSxJJO-kobPBQ][test][0]: SearchParseException[[test][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{
    \"query\": {
        \"common\": {
            \"name\": {
                \"query\": \"the\",
                \"_name\": \"queryname\"
            }
        }
    }
}]]]; nested: NullPointerException[Query may not be null]; }]","status":400}muzio:~ brett$

```

```
# a regular match query doesn't have this problem
curl -XGET 10.4.4.118:9200/test/type1/_search -d '{
    "query": {
        "match": {
            "name": {
                "query": "the",
                "_name": "queryname"
            }
        }
    }
}'
```

### PR DESCRIPTION
**Pull request by jasontedor**
Adding a named query that is null can lead to a `NullPointerException`
when copying the named queries. This is due to an implementation detail
in [`QueryParseContent.copyNamedQueries`](https://github.com/elastic/elasticsearch/blob/d0abffc9acb9afddc83ae99ae17848b813fd918f/core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java#L188). In particular, this method uses
[`com.google.common.collect.ImmutableMap.copyOf`](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableMap.html#copyOf%28java.util.Map%29). A documented requirement
of [`ImmutableMap`](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableMap.html) is that none of the entries have a null key nor null
value. Therefore, we should not add such queries to the [`namedQueries`](https://github.com/elastic/elasticsearch/blob/d0abffc9acb9afddc83ae99ae17848b813fd918f/core/src/main/java/org/elasticsearch/index/query/QueryParseContext.java#L86)
map. This will not change any behavior since [`Map.get`](http://docs.oracle.com/javase/7/docs/api/java/util/Map.html#get%28java.lang.Object%29) returns null if no
entry with the given key exists anyway.

Closes #12683

### CODE REVIEW

File: core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryParserTest.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+                        .startObject(type)
+                            .startObject("properties")
+                                .startObject("name")
+                                    .field("type", "string")
+                                    .field("analyzer", "stop")
+                                .endObject()
+                            .endObject()
+                        .endObject()
+                    .endObject();
+        client().admin().indices().prepareCreate(index).addMapping(type, mapping).execute().actionGet();
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryParserTest.java]: I think you can shorten the mapping here: `addMapping(type, "name", "type=string, analyzer=stop"` that hurts my eyes less :)

File: core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryParserTest.java [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+        ensureGreen();
+
+        CommonTermsQueryBuilder commonTermsQueryBuilder =
+                new CommonTermsQueryBuilder("name", "the").queryName("query-name");
+
+        client().prepareSearch(index).setTypes(type).setQuery(commonTermsQueryBuilder).execute().actionGet();
```
Comment (javanna) [inline core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryParserTest.java]: shall we assert on something at the end?

**Comment by javanna** [comment]
left a couple of minor comments, fix looks good though!

**Comment by javanna** [comment]
LGTM

File: core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryParserTest.java (hunk 1 above)
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryParserTest.java]: Incorporated, thanks!

File: core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryParserTest.java (hunk 2 above)
Comment (jasontedor) [inline core/src/test/java/org/elasticsearch/index/query/CommonTermsQueryParserTest.java]: Agree, thanks!

**Comment by jasontedor** [comment]
@javanna Thanks for reviewing.
