### PR TITLE
Reject pathPrefix containing consecutive slashes

### LINKED ISSUE #117048: Malformed pathPrefix with consecutive trailing slashes
### Description
There is an issue with the cleanPathPrefix method where it doesn't properly handle cases where the pathPrefix contains consecutive trailing slashes, such as /base//path/. The current implementation removes only the last trailing slash, but this does not correctly handle the case where the path contains multiple trailing slashes.

### Steps to Reproduce
1. Pass a path like /base//path/ to the cleanPathPrefix method.
2. The method will remove the last trailing slash, but the resulting path will still have consecutive slashes, which is incorrect.

### Expected Behavior
The method should throw an `IllegalArgumentException` if the path contains consecutive trailing slashes, `e.g., /base//path/.`

### PR DESCRIPTION
**Pull request by reugn**
`RestClientBuilder.cleanPathPrefix` rejected only the special case where the input ended in two consecutive slashes. Embedded consecutive slashes were silently accepted: `/base//path/` was returned as `/base//path` and propagated verbatim into every request URI built by `RestClient.buildUri`.

This change validates the raw input for any `//` and throws `IllegalArgumentException`, consistent with the existing rejection of null, empty, and trailing-double-slash inputs. The Javadoc is updated to match, and the trailing-slash trim is now unconditional after validation.

Closes #117048

### CODE REVIEW

File: client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java [hunk 1]
```diff
@@ -224,10 +228,6 @@ public static String cleanPathPrefix(String pathPrefix) {
         // best effort to ensure that it looks like "/base/path" rather than "/base/path/"
         if (cleanPathPrefix.endsWith("/") && cleanPathPrefix.length() > 1) {
             cleanPathPrefix = cleanPathPrefix.substring(0, cleanPathPrefix.length() - 1);
-
-            if (cleanPathPrefix.endsWith("/")) {
```
Comment (drempapis) [inline client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java:228]: Have we lost this control? What should be the behavior of `/base/path/`

File: client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java [hunk 2]
```diff
@@ -216,6 +216,10 @@ public static String cleanPathPrefix(String pathPrefix) {
             throw new IllegalArgumentException("pathPrefix must not be empty");
         }
 
+        if (pathPrefix.contains("//")) {
```
Comment (drempapis) [inline client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java:219]: There may be more than two consecutive slashes, e.g. three or more.

Why did we choose to throw an exception instead of sanitizing the input?

Comment (reugn) [reply client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java:219]: `contains("//")` matches any run of 2+ slashes. Throwing is consistent with the method's existing behavior (it already throws on null/empty/trailing-//) and surfaces likely misconfiguration at startup rather than silently rewriting.

File: client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java (hunk 1 above)
Comment (reugn) [reply client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java:228]: No, the control is moved earlier and made stricter. `/base/path/` still normalizes to `/base/path` where the upfront `//` check passes and the trailing `/` is trimmed.

**Review by drempapis — APPROVED** [review]
LGTM!
