### PR TITLE
[ML] fixing feature reset integration tests

### LINKED ISSUE #71072: FeaturesIT » testResetFeatures
**Build scan**:
https://gradle-enterprise.elastic.co/s/wvcoydmkr7mf4
**Repro line**:
./gradlew ':client:rest-high-level:asyncIntegTest' --tests "org.elasticsearch.client.FeaturesIT.testResetFeatures" -Dtests.seed=DC0F6E0DE2734BED -Dtests.security.manager=true -Dtests.locale=uk -Dtests.timezone=Etc/GMT-8 -Druntime.java=11
**Reproduces locally?**:
eventually
**Applicable branches**:
master

**Failure excerpt**:
```
org.elasticsearch.client.FeaturesIT > testResetFeatures FAILED
    org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=runtime_exception, reason=Unable to reset machine learning feature as there are ingest pipelines still referencing trained machine learning models]
        at __randomizedtesting.SeedInfo.seed([DC0F6E0DE2734BED:8F8A2A76A94F6C54]:0)
        at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176)
        at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1933)
        at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1910)
        at org.elasticsearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:1826)
        at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:648)
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:390)
        at org.elasticsearch.client.RestClient$1.completed(RestClient.java:374)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

So, the ML tests didn't clean up their trained models or pipelines 🤦 fixing that

### PR DESCRIPTION
**Pull request by benwtrent**
previously created pipelines referencing ML models were not being appropriately deleted in upstream tests.

This commit ensures that machine learning removes relevant pipelines from cluster state after tests complete

closes https://github.com/elastic/elasticsearch/issues/71072

### CODE REVIEW

File: x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/TestFeatureResetIT.java [hunk 1]
```diff
@@ -44,20 +47,31 @@
...
+            }
+        }
     }
 
-    @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/71072")
     public void testMLFeatureReset() throws Exception {
         startRealtime("feature_reset_anomaly_job");
         startDataFrameJob("feature_reset_data_frame_analytics_job");
         putTrainedModelIngestPipeline("feature_reset_inference_pipeline");
+        createdPipelines.add("feature_reset_inference_pipeline");
```
Comment (przemekwitek) [inline x-pack/plugin/ml/qa/native-multi-node-tests/src/javaRestTest/java/org/elasticsearch/xpack/ml/integration/TestFeatureResetIT.java:68]: Should this line be executed before `putTrainedModelIngestPipeline`? Just in case sth goes wrong inside `putTrainedModelIngestPipeline` itself?
Also, would it make sense to move this line into the `putTrainedModelIngestPipeline` method?

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
Backported in initial ML backport for reset feature: https://github.com/elastic/elasticsearch/pull/71071
