### PR TITLE
Return docs when using nested mappings in archive indices

### LINKED ISSUE #90523: Archive indices < 6.1 and nested fields
Archive indices < 6.1 do not work together with nested fields. While the documentation makes sure not to claim support for nested fields, see https://www.elastic.co/guide/en/elasticsearch/reference/current/archive-indices.html#archive-indices-supported-field-types, it leads to a situation where the import still works yet none of the documents at all are returned by any query.

This is because indices before 6.1 did not have primary terms, but the default search context in ES 8 adds a FieldExistsQuery(SeqNoFieldMapper.PRIMARY_TERM_NAME) filter to the query:

https://github.com/elastic/elasticsearch/blob/f56126089ca4db89b631901ad7cce0a8e10e2fe5/server/src/main/java/org/elasticsearch/search/DefaultSearchContext.java#L284

### PR DESCRIPTION
**Pull request by ywelsch**
Archive indices < 6.1 do not work together with nested fields. While the documentation makes sure not to claim support for nested fields, see https://www.elastic.co/guide/en/elasticsearch/reference/current/archive-indices.html#archive-indices-supported-field-types, it leads to a situation where the import still works yet none of the documents at all are returned by any query (not even match_all). This is because indices before 6.1 did not have primary terms, but the default search context in ES 8 adds a FieldExistsQuery(SeqNoFieldMapper.PRIMARY_TERM_NAME) filter to the query:

https://github.com/elastic/elasticsearch/blob/f56126089ca4db89b631901ad7cce0a8e10e2fe5/server/src/main/java/org/elasticsearch/search/DefaultSearchContext.java#L284

This PR fixes the issue by adding basic support for nested fields so that it at least allows queries that are not leveraging the nested documents to work (i.e. allow extracting the documents e.g. to be reindexed).

Closes #90523

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/engine/LuceneChangesSnapshot.java [hunk 1]
```diff
@@ -62,21 +63,23 @@ final class LuceneChangesSnapshot implements Translog.Snapshot {
...
     private int storedFieldsReaderOrd = -1;
     private StoredFieldsReader storedFieldsReader = null;
 
     private final Thread creationThread; // for assertion
 
     /**
      * Creates a new "translog" snapshot from Lucene for reading operations whose seq# in the specified range.
-     *
-     * @param engineSearcher    the internal engine searcher which will be taken over if the snapshot is opened successfully
+     *  @param engineSearcher    the internal engine searcher which will be taken over if the snapshot is opened successfully
```
Comment (romseygeek) [inline server/src/main/java/org/elasticsearch/index/engine/LuceneChangesSnapshot.java:75]: nit: extra space?

**Review by romseygeek — APPROVED** [review]
LGTM. Thanks @ywelsch

**Comment by ywelsch** [comment]
Thanks @romseygeek!
