### PR TITLE
Propagate forceExecution when acquiring permit

### LINKED ISSUE #60359: Primary-replica resync can fail a busy primary
A primary-replica resync, which is triggered on a new primary after failover, will have a primary fail itself in case where it encounters an issue. As the resync is run by sending a primary action to the node itself, which is scheduled on the write thread pool, rejection from the write thread pool will cause the resync, and therefore the shard, to be failed.

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently the transport replication action does not propagate the force
execution parameter when acquiring the indexing permit. The logic to 
acquire the index permit supports force execution, so this parameter
should be propagate. Fixes #60359.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/index/shard/IndexShardOperationPermits.java [hunk 1]
```diff
@@ -341,9 +341,12 @@ synchronized boolean isBlocked() {
         private final ActionListener<Releasable> listener;
         private final String debugInfo;
         private final StackTraceElement[] stackTrace;
+        private final boolean forceExecution;
```
Comment (ywelsch) [inline server/src/main/java/org/elasticsearch/index/shard/IndexShardOperationPermits.java:344]: The changes in this file aren't used, and not necessary

**Review by ywelsch — COMMENTED** [review]
I've asked for changes of one file to be reverted, o.w. looking good

**Review by ywelsch — APPROVED** [review]
LGTM
