### PR TITLE
Handle nulls in OrdinalsGroupingOperator

### LINKED ISSUE #100109: ESQL: grouping by just a keyword ignores null values
### Description

Not sure if it's a regression or not but when grouping by just one keyword field, the null group is not returned:
```
from employees | stats by gender | sort gender 
```
should return [F, M, null] yet only [F, M] are.

It looks like the hashing function (whether ordinal or not) ends up dropping null along the way. 
This doesn't happen with multiple keys as long as the keyword is not the first key:

```
from employees | stats by languages, gender | sort desc
```

```
null | null
null | F
null | M
etc...
```

### PR DESCRIPTION
**Pull request by dnhatn**
This change introduces null handling in the OrdinalsGroupingOperator, replacing the current behavior which skips null keys. Ordinals are now incremented by 1, with 0 being used to represent null ordinals.

Closes #100109

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/part-2

File: x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/OrdinalsGroupingOperator.java [hunk 1]
```diff
@@ -448,4 +462,49 @@ public void close() {
...
+    static final class BlockOrdinalsReader {
+        private final SortedSetDocValues sortedSetDocValues;
+        private final Thread creationThread;
+
+        BlockOrdinalsReader(SortedSetDocValues sortedSetDocValues) {
+            this.sortedSetDocValues = sortedSetDocValues;
+            this.creationThread = Thread.currentThread();
+        }
+
+        IntBlock readOrdinalsAdded1(IntVector docs) throws IOException {
```
Comment (dnhatn) [inline x-pack/plugin/esql/compute/src/main/java/org/elasticsearch/compute/operator/OrdinalsGroupingOperator.java:475]: I moved this class to OrdinalsGroupingOperator since it's only used by this class and the new behavior (add 1 to the ordinals). We can generalize it later if necessary.

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java [hunk 2]
```diff
@@ -562,11 +555,6 @@ public void testFilterWithNullAndEvalFromIndex() {
         assertThat(results.columns(), hasItem(equalTo(new ColumnInfo("data", "long"))));
         assertThat(results.columns(), hasItem(equalTo(new ColumnInfo("data_d", "double"))));
         assertThat(results.columns(), hasItem(equalTo(new ColumnInfo("time", "long"))));
-
-        // restore index to original pre-test state
```
Comment (dnhatn) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionIT.java:566]: No need to delete docs in these tests. The index should be deleted after each test.

**Review by costin — APPROVED** [review]
LGTM - Thanks for the quick turn-around Nhat!

**Comment by dnhatn** [comment]
Thanks Costin!
