### PR TITLE
ESQL: Fix validation NPE in Enrich and add extra @Nullable annotations

### LINKED ISSUE #126253: [CI] EsqlClientYamlIT class failing
**Build Scans:**
- [elasticsearch-periodic #7417 / 8.11.4_bwc](https://gradle-enterprise.elastic.co/s/vjxc2fgavex54)
- [elasticsearch-periodic #7417 / 8.12.2_bwc](https://gradle-enterprise.elastic.co/s/eqoxqtpjagzus)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:mixed-cluster:v8.11.4#yamlRestTest" -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT" -Dtests.method="test {p0=esql/160_union_types/load two indices with incorrect conversion function, TO_LONG instead of TO_IP}" -Dtests.seed=516A5A7613A6660B -Dtests.bwc=true -Dtests.locale=gsw-CH -Dtests.timezone=Mexico/BajaNorte -Druntime.java=24
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: circuit breakers not reset to 0Expected a map containing
estimated_size_in_bytes: expected <0> but was <368>
         estimated_size: expected "0b" but was "368b"
               overhead: <1.0> unexpected but ok
    limit_size_in_bytes: <322122547> unexpected but ok
             limit_size: "307.1mb" unexpected but ok
                tripped: <0> unexpected but ok
```

**Issue Reasons:**
- [8.x] 2 consecutive failures in class org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT
- [8.x] 2 failures in class org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT (1.3% fail rate in 158 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #126297: [CI] EsqlClientYamlIT test {p0=esql/61_enrich_ip/IP strings} failing
**Build Scans:**
- [elasticsearch-periodic #7431 / 8.13.4_bwc](https://gradle-enterprise.elastic.co/s/4jwulzhp2nux2)
- [elasticsearch-periodic #7424 / 8.11.4_bwc](https://gradle-enterprise.elastic.co/s/dhddfv7mn2roc)
- [elasticsearch-periodic #7417 / 8.11.4_bwc](https://gradle-enterprise.elastic.co/s/vjxc2fgavex54)
- [elasticsearch-periodic #7417 / 8.12.2_bwc](https://gradle-enterprise.elastic.co/s/eqoxqtpjagzus)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:mixed-cluster:v8.13.4#yamlRestTest" -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT" -Dtests.method="test {p0=esql/61_enrich_ip/IP strings}" -Dtests.seed=FB8B6D3E6F751F1F -Dtests.bwc=true -Dtests.locale=am-ET -Dtests.timezone=Pacific/Funafuti -Druntime.java=24
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Desql%2F61_enrich_ip%2FIP%20strings%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [esql/61_enrich_ip:112]: expected [2xx] status code but api [esql.query] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"null_pointer_exception","reason":"Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.noText()\" because \"inputDataType\" is null","stack_trace":"org.elasticsearch.ElasticsearchException$1: Cannot invoke \"org.elasticsearch.xpack.esql.core.type.DataType.noText()\" because \"inputDataType\" is null\n\tat org.elasticsearch.server@8.19.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:707)\n\tat org.elasticsearch.server@8.19.0-SNAPSHOT/org.elasticsearch.ElasticsearchException.generateFailureXContent(ElasticsearchException.java:635)\n\tat org.elasticsearch.server@8.19.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.build(RestResponse.java:201)\n\tat org.elasticsearch.server@8.19.0-SNAPSHOT/org.elasticsearch.rest.RestResponse.<init>(RestResponse.java:160)\
[truncated]
```

**Issue Reasons:**
- [8.x] 4 failures in test test {p0=esql/61_enrich_ip/IP strings} (2.3% fail rate in 176 executions)
- [8.x] 2 failures in step 8.11.4_bwc (66.7% fail rate in 3 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic (100.0% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ivancea**
Fixes https://github.com/elastic/elasticsearch/issues/126253
Fixes https://github.com/elastic/elasticsearch/issues/126297

`inputDataType` may be null when in mixed cluster (<8.14). So `validateTypes()` should take that into account. Similar fix to https://github.com/elastic/elasticsearch/pull/116583

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java [hunk 1]
```diff
@@ -128,8 +129,8 @@ protected LookupResponse readLookupResponse(StreamInput in, BlockFactory blockFa
         return new LookupResponse(in, blockFactory);
     }
 
-    private static void validateTypes(DataType inputDataType, MappedFieldType fieldType) {
-        if (fieldType instanceof RangeFieldMapper.RangeFieldType rangeType) {
+    private static void validateTypes(@Nullable DataType inputDataType, MappedFieldType fieldType) {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java:132]: The `@Nullable` annotations are showing a warning here as expected. But they're not showing a warning on method calls. Not perfect, but well. I think they may still help (?)

**Review by craigtaverner — APPROVED** [review]
LGTM, although I'm assuming the annotations don't change anything and it's all in the `inputDataType == null` check.
