### PR TITLE
ESQL: Fix ExchangeSinkExec output type

### LINKED ISSUE #141654: ESQL: Incorrect ExchangeExecs in node reduce plan
This is a follow-up to an issue discovered in #141082. It seems that the `ExchangeExec` in `ComputeService.reductionPlan` is created using the old output attributes rather than the new one, and because the Exchange wrapping happens after the local optimization, we don't have a consistency check that verifies this isn't happening.

This is technically *fine*, since in reality the exchanges just pipe whatever pages they get, ignoring their declared output, but it *is* messy and should be fixed. In addition, we should add a consistency check (that only runs during tests) to ensure this doesn't happen again.

Possible lead: https://github.com/elastic/elasticsearch/blob/abce9512a7d0c84f2839391f86a52f009a3b73d9/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/LateMaterializationPlanner.java#L131
though there may be other places.

### PR DESCRIPTION
**Pull request by GalLalouche**
This PR fixes `ExchangeSinkExec` claiming to return the wrong output. This doesn't actually affect production, since the operator outputs whatever it receives anyway, but it's confusing, and looks bad in golden tests as well.
Also added a plan verification that only runs during tests to ensure this kind of thing doesn't happen again.

Resolves #141654.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java [hunk 1]
```diff
@@ -226,8 +228,6 @@ public static PhysicalPlan localPlan(
         LocalPhysicalPlanOptimizer physicalOptimizer,
         PlanTimeProfile planTimeProfile
     ) {
-        // TODO add a test assertion for the consistency checker (after https://github.com/elastic/elasticsearch/issues/141654, see
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java:240]: While the TODO here was at the top of the method, the consistency checker actually *fails* if run here, since the plan isn't consistent yet!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 2]
```diff
@@ -817,12 +819,32 @@ public static ReductionPlan reductionPlan(
                     // Fallback to the behavior listed below, i.e., a regular top n reduction without loading new fields.
                     .orElseGet(() -> runNodeLevelReduction ? placePlanBetweenExchanges.apply(topN.plan()) : defaultResult);
             case PlannerUtils.TopNReduction topN when runNodeLevelReduction -> placePlanBetweenExchanges.apply(topN.plan());
-            case PlannerUtils.ReducedPlan rp when runNodeLevelReduction -> placePlanBetweenExchanges.apply(rp.plan());
+            case PlannerUtils.ReducedPlan rp when runNodeLevelReduction -> {
+                PhysicalPlan reductionSource = new ExchangeSourceExec(
```
Comment (GalLalouche) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: This fix was necessary since otherwise the added assertions would fail.

File: change_commits.sh [hunk 3]
```diff
@@ -0,0 +1,10 @@
+git filter-branch --env-filter '
+  if [ "$GIT_COMMITTER_EMAIL" = "gal@pinecone.io" ]; then
+    export GIT_COMMITTER_NAME="Gal Lalouche"
+    export GIT_COMMITTER_EMAIL="gal.lalouche@elastic.co"
+  fi
+  if [ "$GIT_AUTHOR_EMAIL" = "gal@pinecone.io" ]; then
+    export GIT_AUTHOR_NAME="Gal Lalouche"
+    export GIT_AUTHOR_EMAIL="gal.lalouche@elastic.co"
+  fi
+' --tag-name-filter cat -- HEAD~1000..HEAD
```
Comment (idegtiarenko) [inline change_commits.sh]: I do not think this was added intentionally?

File: repeat.sh [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+   # Execute the command
+   eval $COMMAND_TO_RUN
+   # Check the exit code
+   if [ $? -ne 0 ]; then
+       echo "Command failed on iteration $i with exit code $?"
+       break
+   fi
+done
+
+echo "Loop finished."
```
Comment (idegtiarenko) [inline repeat.sh]: Is this script added intentionally? 
If so, could you please describe why it is needed?

File: change_commits.sh (hunk 3 above)
Comment (GalLalouche) [reply change_commits.sh]: Indeed it wasn't!

File: x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/plugin/golden_tests/LateMaterializationPlannerGoldenTests/testTopNWithMissingSortField/local_reduce_physical_optimization_data_driver.expected [hunk 5]
```diff
@@ -1,4 +1,4 @@
-ExchangeSinkExec[[emp_no{f}, hire_date{f}, salary{f}],false]
+ExchangeSinkExec[[_doc{f}, hire_date{r}],false]
 \_ProjectExec[[_doc{f}, birth_date{r} AS hire_date]]
   \_EvalExec[[null[DATETIME] AS birth_date]]
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/plugin/golden_tests/LateMaterializationPlannerGoldenTests/testTopNWithMissingSortField/local_reduce_physical_optimization_data_driver.expected]: This test is funky and a bit messed up, I think. It is quite confusing why the heck the `birth_date` is popping up here at all.

The test method uses `missingFieldStats("hire_date")`, suggesting that `hire_date` should be a missing field but all other fields are present.

However, `missingFieldStats` is broken. It says
```
    // Returns false for exists() for the specified field, simulating a missing field on the data node.
```
but the implementation constantly returns `false` for `exists` and `isIndexed`, regardless of the field name.

Which means that `birth_date` is considered missing, too, and is why a `null::datetime` was inserted for it.

Let's fix `missingFieldStats` to avoid further confusion.

Comment (alex-spies) [reply x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/plugin/golden_tests/LateMaterializationPlannerGoldenTests/testTopNWithMissingSortField/local_reduce_physical_optimization_data_driver.expected]: I'm going to push a fix.

File: x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/plugin/golden_tests/LateMaterializationPlannerGoldenTests/testTopNWithMissingSortField/local_reduce_physical_optimization_data_driver.expected [hunk 6]
```diff
@@ -1,4 +1,4 @@
-ExchangeSinkExec[[emp_no{f}, hire_date{f}, salary{f}],false]
-\_ProjectExec[[_doc{f}, birth_date{r} AS hire_date]]
-  \_EvalExec[[null[DATETIME] AS birth_date]]
+ExchangeSinkExec[[_doc{f}, hire_date{r}],false]
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/plugin/golden_tests/LateMaterializationPlannerGoldenTests/testTopNWithMissingSortField/local_reduce_physical_optimization_data_driver.expected]: thought: With and without my test fix, we have an interesting situation here: the exchange doesn't return a field attribute anymore, but a reference attribute (because we intentionally shadowed the `hire_date` with a `null` constant from an `EVAL` that was inserted for the missing field.

This is correct, but means we cannot assume that attribute type remains consistent for an exchange after optimization.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java:240]: If we fail here, IMO we handed an already inconsistent plan to localPlan and we shouldn't.
We do some surgery on the data and reduce plans before reaching here and fail to update the exchange. The added code below just goes and blindly says: "Oh, an exchange at the top! Better update its expected output!" - and then it checks plan consistency, which is now satisfied because we fixed it the moment before.

This is potentially masking a real problem by fixing a plan that was broken somewhere else.

I think we need to go and update the places where we perform surgery on the data and reduce plans, instead. If an inconsistent plan makes its way here, we failed somewhere else.
That said, the local physical plan consistency checker may check more than what's needed here. What absolutely should be consistent is that a plan node's referenced attributes need to be in the output of the children (and no duplicate names should be in the output of any plan node). This reduced consistency check is given by PlanConsistencyChecker#checkPlan and can be used here if needed.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java [hunk 7]
```diff
@@ -281,7 +281,13 @@ public static PhysicalPlan localPlan(
         });
 
         PhysicalPlan resultPlan = isCoordPlan.get() ? plan : localPhysicalPlan;
-
+        // This check is needed because in test code we sometimes invoke localPlan with a non-ExchangeSinkExec root.
+        if (resultPlan instanceof ExchangeSinkExec sink) {
+            resultPlan = sink.replaceChildAndUpdateOutput(sink.child());
+        }
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java]: My main concern, as mentioned above: this auto-fixes the plan blindly. I think this needs to be fixed at the place where the plan is made inconsistent to begin with.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java:240]: Moving the assertion here did not fail the single node spec tests. Neither did EsqlReductionLateMaterializationSingleNodeIT fail.

I'm going to push what I think we should have (consistency check right here) to see what other tests fail; then we can go from there.

File: x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/plugin/golden_tests/LateMaterializationPlannerGoldenTests/testTopNWithMissingSortField/local_reduce_physical_optimization_data_driver.expected [hunk 8]
```diff
@@ -1,4 +1,4 @@
-ExchangeSinkExec[[emp_no{f}, hire_date{f}, salary{f}],false]
-\_ProjectExec[[_doc{f}, birth_date{r} AS hire_date]]
-  \_EvalExec[[null[DATETIME] AS birth_date]]
+ExchangeSinkExec[[_doc{f}, hire_date{f}],false]
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/test/resources/org/elasticsearch/xpack/esql/plugin/golden_tests/LateMaterializationPlannerGoldenTests/testTopNWithMissingSortField/local_reduce_physical_optimization_data_driver.expected:1]: Well, without updating the exchange sink in `PlannerUtils#localPlan`, we get a more explicitly interesting situation: the hire date now _remains_ a field attribute (we expected that as output!) but the projection below provides a reference attribute. That's okay in case of missing fields.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 9]
```diff
@@ -822,12 +824,32 @@ public static ReductionPlan reductionPlan(
...
+                );
+            }
             default -> defaultResult;
         };
         if (planTimeProfile != null) {
             planTimeProfile.addReductionPlanNanos(System.nanoTime() - startTime);
         }
+        reductionPlan = new ReductionPlan(
+            reductionPlan.nodeReducePlan().replaceChildAndUpdateOutput(reductionPlan.nodeReducePlan().child()),
+            reductionPlan.dataNodePlan().replaceChildAndUpdateOutput(reductionPlan.dataNodePlan().child()),
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: This is an automatic, catch-all "fix my exchange, please". I don't think we should be having it. It also makes the verification below quite moot.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 10]
```diff
@@ -822,12 +824,32 @@ public static ReductionPlan reductionPlan(
                     // Fallback to the behavior listed below, i.e., a regular top n reduction without loading new fields.
                     .orElseGet(() -> runNodeLevelReduction ? placePlanBetweenExchanges.apply(topN.plan()) : defaultResult);
             case PlannerUtils.TopNReduction topN when runNodeLevelReduction -> placePlanBetweenExchanges.apply(topN.plan());
-            case PlannerUtils.ReducedPlan rp when runNodeLevelReduction -> placePlanBetweenExchanges.apply(rp.plan());
+            case PlannerUtils.ReducedPlan rp when runNodeLevelReduction -> {
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: I think these branches should still all use `placePlanBetweenExchanges`. The added code here is a fix-up to `placePlanBetweenExchanges` for Aggs, specifically, but it's actually generally correct. Let's not have 2 ways of placing a plan between exchanges.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 11]
```diff
@@ -822,12 +824,32 @@ public static ReductionPlan reductionPlan(
...
             planTimeProfile.addReductionPlanNanos(System.nanoTime() - startTime);
         }
+        reductionPlan = new ReductionPlan(
+            reductionPlan.nodeReducePlan().replaceChildAndUpdateOutput(reductionPlan.nodeReducePlan().child()),
+            reductionPlan.dataNodePlan().replaceChildAndUpdateOutput(reductionPlan.dataNodePlan().child()),
+            reductionPlan.localPhysicalOptimization()
+        );
+        if (Assertions.ENABLED) {
+            PhysicalVerifier.LOCAL_INSTANCE.verify(reductionPlan.nodeReducePlan(), reductionPlan.nodeReducePlan().child().output());
+            PhysicalVerifier.LOCAL_INSTANCE.verify(reductionPlan.dataNodePlan(), reductionPlan.dataNodePlan().child().output());
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: Aren't these assertions essentially duplicated because we pass the data node plan to `PlannerUtils#localPlan`?

They're not wrong, but maybe we shouldn't have both?

**Review by alex-spies — COMMENTED** [review]
Ok, done reviewing now. The productive changes look alright, ~except for the automatic "fix my exchanges, pls" in `ComputeService.java`. This shouldn't really be necessary and looks like a leftover.~

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java (hunk 9 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: Well, I was wrong. These are needed; but they're also duplicated because `LateMaterializationPlanner#planReduceDriverTopN` already updates the exchange sinks. I think we should only update the exchange sinks in one place (here).

Removed usages of `replaceChildAndUpdateOutput` from the `LateMaterializationPlanner` and kept only the usages here.

LateMaterializationGoldenTests, EsqlReductionLateMaterializationMultiNodeIT and the multi-node spec tests didn't fail so far. I'll push an update and will see if I broke it.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java (hunk 11 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: I'm going to remove the added assertion to PlannerUtils#localPlan since the plan consistency is already checked here.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java (hunk 10 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: Bleh, wrong again. For aggs, the exchange source is not sending the original output anymore, while for TopN it is.

This is actually fine, but I'll add a comment. And an assertion that the plan is an AggregateExec; because otherwise, assuming that the exchange source will send only the reduction plan's references is very wrong.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java:240]: As mentioned below, removing this check as it's duplicated.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java (hunk 11 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: I'm also going to check that the reduction source matches the data sink. They must match up as one is receiver and the other is sender, after all.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java (hunk 10 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: It's obviously late and I'm even less sure why this change was needed to begin with. Even for an agg, the input it will receive is exactly the output of the original exchange.

Changing the exchange source to the agg's refs thus looks wrong.

I expected the agg's references to require an update, though, as the AggregatorMode should change from Initial to intermediate. o.O

Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: I think it may not matter because for aggs, the reduction plan uses the intermediate version of the agg. The agg's references should be the same as the original exchange's outputs.

After simplifying this branch to its original version, I cannot reproduce a test failure. Not sure why this was put here to begin with. I'm going to go forward with the revert and push to see if anything else breaks, but I don't see why it would.

**Review by alex-spies — APPROVED** [review]
Ok, I simplified the PR a bit. If the tests still pass, we should be good to go.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java:240]: While the check is duplicated, I think it is showing actually broken plans.

I was able to reproduce this via `EsqlSecurityIT#testDataStreams`, `#testEnrich` and a couple others.

Worth understanding better.

Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java:240]: Gah, it's actually simple.

The sink's input at this point is a FragmentExec, and FragmentExec's output is the output of the contained logical plan - which can be an `Aggregate` (logical plan). That one is completely oblivious of the intermediate attributes that an AggregateExec is actually going to send.

That is maybe a bug in `FragmentExec.output`, as in, when it contains an Aggregate, it shouldn't just blindly trust the agg's output - it'd need to map the agg, first.

**Review by alex-spies — COMMENTED** [review]
Ok, in addition to the FragmentExec "lying" about its output, I can see that `TimeSeriesAggregateExec` has some peculiarities as well.

~I'd like to try and fix those before merging this, so we don't go and artificially declare factually inconsistent plans as consistent.~ **Update:** changed my mind; getting the exchanges consistent for aggs is surprisingly complex, given how we generate intermediate attributes. I think it's not worth fixing for now.

```
Found 1 problem
line -1:-1: Plan [TimeSeriesAggregateExec[[_tsid{m}#54, bucket(@timestamp, 1 hour){r}#55],[MIN($$cpu$MINOVERTIME$min_over_time(cpu){f$}#63,true[BOOLEAN],
PT0S[TIME_DURATION]) AS MINOVERTIME_$1#64, DIMENSIONVALUES(cluster{f}#60,true[BOOLEAN],PT0S[TIME_DURATION]) AS cluster#65, bucket(@timestamp, 1 hour){r}#55],
INTERMEDIATE,[_tsid{m}#54, bucket(@timestamp, 1 hour){r}#55, $$MINOVERTIME_$1$min{r}#66, $$MINOVERTIME_$1$seen{
r}#67, $$cluster$values{r}#68],66,BUCKET(@timestamp{f}#59,PT1H[TIME_DURATION])]] optimized incorrectly due to missing references [$$MINOVERTIME_$1$min{r}#66, $$MINOVERTIME_$1$seen{r}#67, $$cluster$values{r}#68]
java.lang.IllegalStateException: failed for plan
ExchangeSinkExec[[_tsid{m}#54, bucket(@timestamp, 1 hour){r}#55, $$MINOVERTIME_$1$min{r}#66, $$MINOVERTIME_$1$seen{r}#67, $$clu
ster$values{r}#68],true]
\_TimeSeriesAggregateExec[[_tsid{m}#54, bucket(@timestamp, 1 hour){r}#55],[MIN($$cpu$MINOVERTIME$min_over_time(cpu){f$}#63,true[BOOLEAN],
PT0S[TIME_DURATION]) AS MINOVERTIME_$1#64, DIMENSIONVALUES(cluster{f}#60,true[BOOLEAN],PT0S[TIME_DURATION]) AS cluster#65, bucket(@timestamp, 1 hour){r}#55],
INTERMEDIATE,[_tsid{m}#54, bucket(@timestamp, 1 hour){r}#55, $$MINOVERTIME_$1$min{r}#66, $$MINOVERTIME_$1$seen{
r}#67, $$cluster$values{r}#68],66,BUCKET(@timestamp{f}#59,PT1H[TIME_DURATION])]
  \_ExchangeSourceExec[[_tsid{m}#54, bucket(@timestamp, 1 hour){r}#55, $$MINOVERTIME_$1$min{r}#56, $$MINOVERTIME_$1$seen{r}#57, $$clu
ster$values{r}#58],true]
```

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 12]
```diff
@@ -820,14 +828,26 @@ public static ReductionPlan reductionPlan(
...
+            // Not a TopN - must be an agg or a limit
             case PlannerUtils.ReducedPlan rp when runNodeLevelReduction -> placePlanBetweenExchanges.apply(rp.plan());
-            default -> defaultResult;
+            default -> passThroughReduction;
         };
         if (planTimeProfile != null) {
             planTimeProfile.addReductionPlanNanos(System.nanoTime() - startTime);
         }
+        reductionPlan = new ReductionPlan(
+            reductionPlan.nodeReducePlan().replaceChildAndUpdateOutput(reductionPlan.nodeReducePlan().child()),
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java]: Actually, the output of the reduce plan must not update. It really has to stay the exact same as the original output.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java (hunk 1 above)
Comment (alex-spies) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/planner/PlannerUtils.java:240]: Nevermind, I recall now why we never implemented FragmentExec via the intermediateAttributes method in case of aggs. Because the latter re-generates new NameIds every time.

I think ensuring consistent exchanges for aggs runs into too many aggs-specific peculiarities. I think we should reduce the scope to just ensuring consistency for the late materialization case and call it a day.

**Comment by alex-spies** [comment]
Ok, I ended up reducing scope a little. There was a workaround in place to deal with aggs, I removed it, but excluded aggs from the consistency check for exchanges. The intermediate attributes for aggs and time series aggs make this just too complicated to be worth the effort.

- I reduced the exchange sink fix to just the known broken sinks in case of late materialization.
- I hardened the consistency check to ensure the overall output didn't change and the data driver outputs what the reduce driver requires.
- I fixed a test that was considering too many fields as missing.

Hope CI likes this now.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/LateMaterializationPlanner.java [hunk 13]
```diff
@@ -128,8 +128,7 @@ public static Optional<ReductionPlan> planReduceDriverTopN(
         }
         var updatedFragment = new Project(Source.EMPTY, withAddedDocToRelation, expectedDataOutput);
         FragmentExec updatedFragmentExec = fragmentExec.withFragment(updatedFragment);
-        // TODO This ignores the possible change in output, see #141654
-        ExchangeSinkExec updatedDataPlan = originalPlan.replaceChild(updatedFragmentExec);
+        ExchangeSinkExec updatedDataPlan = originalPlan.replaceChildAndUpdateOutput(updatedFragmentExec);
```
Comment (alex-spies) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/LateMaterializationPlanner.java:131]: Main fix here.

**Review by idegtiarenko — APPROVED** [review]

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plugin/LateMaterializationPlannerGoldenTests.java [hunk 14]
```diff
@@ -152,12 +152,18 @@ private static EsqlTestUtils.TestSearchStats missingFieldStats(String missingFie
...
+                return true;
             }
 
             @Override
             public boolean isIndexed(FieldAttribute.FieldName field) {
-                return false;
+                if (field.string().equals(missingField)) {
+                    return false;
+                }
+                return true;
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plugin/LateMaterializationPlannerGoldenTests.java]:
```suggestion
                return exists(missingField);
```

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plugin/LateMaterializationPlannerGoldenTests.java [hunk 15]
```diff
@@ -152,12 +152,18 @@ private static EsqlTestUtils.TestSearchStats missingFieldStats(String missingFie
         return new EsqlTestUtils.TestSearchStats() {
             @Override
             public boolean exists(FieldAttribute.FieldName field) {
-                return false;
+                if (field.string().equals(missingField)) {
+                    return false;
+                }
+                return true;
```
Comment (idegtiarenko) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/plugin/LateMaterializationPlannerGoldenTests.java]:
```suggestion
                return Objects.equals(field.string(), missingField) == false;
```

**Review by idegtiarenko — APPROVED** [review]
