### PR TITLE
Fix failure in AppendProcessorTests.testAppendingUniqueValueToScalar

### LINKED ISSUE #62411: AppendProcessorTests.testAppendingUniqueValueToScalar fails on casting
**Build scan**:
https://gradle-enterprise.elastic.co/s/tjxkfpkfk4p7s

**Repro line**:
 ./gradlew ':modules:ingest-common:test' --tests "org.elasticsearch.ingest.common.AppendProcessorTests.testAppendingUniqueValueToScalar" -Dtests.seed=7ADBC57E6F3321EC -Dtests.security.manager=true -Dtests.locale=mk-MK -Dtests.timezone=Greenwich -Druntime.java=11

**Reproduces locally?**:
yes

**Applicable branches**:
master  (have not tested others)

**Failure history**:

**Failure excerpt**:
```
> java.lang.IllegalArgumentException: field [Yb.񂉙񋢲.aQ.BFkPjlFm.mt7F4aWi] of type [java.lang.String] cannot be cast to [java.util.List]
        at __randomizedtesting.SeedInfo.seed([7ADBC57E6F3321EC:5156B1CAEC68E9FE]:0)
        at org.elasticsearch.ingest.IngestDocument.cast(IngestDocument.java:638)
        at org.elasticsearch.ingest.IngestDocument.getFieldValue(IngestDocument.java:115)
        at org.elasticsearch.ingest.common.AppendProcessorTests.testAppendingUniqueValueToScalar(AppendProcessorTests.java:186)

```

### PR DESCRIPTION
**Pull request by danhermann**
Fixes #62411

### CODE REVIEW

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/AppendProcessorTests.java [hunk 1]
```diff
@@ -179,7 +179,7 @@ public void testAppendingUniqueValueToScalar() throws Exception {
         String field = RandomDocumentPicks.addRandomField(random(), ingestDocument, originalValue);
 
         List<Object> valuesToAppend = new ArrayList<>();
-        String newValue = randomAlphaOfLengthBetween(1, 10);
+        String newValue = originalValue + randomAlphaOfLengthBetween(1, 10);
```
Comment (probakowski) [inline modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/AppendProcessorTests.java:182]: Maybe use `randomValueOtherThan`? It'll communicate intent better, I think

**Review by probakowski — APPROVED** [review]
LGTM, thanks for fixing this! Just small suggestion from my side

File: modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/AppendProcessorTests.java (hunk 1 above)
Comment (danhermann) [reply modules/ingest-common/src/test/java/org/elasticsearch/ingest/common/AppendProcessorTests.java]: Thanks, @probakowski! I didn't know about the `randomValueOtherThan` method.
