### PR TITLE
Optimize AsyncSearchErrorTraceIT to avoid failures

### LINKED ISSUE #137150: [CI] AsyncSearchErrorTraceIT testAsyncSearchFailingQueryErrorTraceTrue failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #11336 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/irsebjqzoh62s)
- [elasticsearch-periodic-platform-support #11332 / windows-2022_checkpart2_platform-support-windows](https://gradle-enterprise.elastic.co/s/gg2q2hankkbz6)

**Reproduction Line:**
```
gradlew ":x-pack:plugin:async-search:internalClusterTest" --tests "org.elasticsearch.xpack.search.AsyncSearchErrorTraceIT.testAsyncSearchFailingQueryErrorTraceTrue" -Dtests.seed=1DEC23647F2E1588 -Dtests.locale=hi-Latn-IN -Dtests.timezone=Africa/Maputo -Druntime.java=25
```

**Applicable branches:**
9.2

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.search.AsyncSearchErrorTraceIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testAsyncSearchFailingQueryErrorTraceTrue'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Shard [.async-search][0] is still locked after 5 sec waiting
```

**Issue Reasons:**
- [9.2] 2 consecutive failures in step windows-2022_checkpart2_platform-support-windows
- [9.2] 2 failures in test testAsyncSearchFailingQueryErrorTraceTrue (3.6% fail rate in 55 executions)
- [9.2] 2 failures in step windows-2022_checkpart2_platform-support-windows (100.0% fail rate in 2 executions)
- [9.2] 2 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by drempapis**
In some previous work ([#137078](https://github.com/elastic/elasticsearch/pull/137078)), we introduced changes that mitigated the `.async-search` shard lock issue. While that significantly reduced the frequency of the problem, a few [cases](https://es-delivery-stats.elastic.dev/app/r/s/MzePk) still persisted.

The error can occur when `HTTP` Response objects are not fully closed, or when persisted `.async-search` results (`keep_on_completion=true`) are not deleted. Either situation can leave file handles open long enough that the .async-search shard remains locked during cluster teardown, resulting in:

```
Shard [.async-search][0] is still locked after 5 sec waiting
```

This change further addresses the issue by preventing unreleased resources that cause `.async-search` shard lock failures:
- Deterministic HTTP response cleanup: all responses now fully consume the `HttpEntity`  to release connections.
- Async-search cleanup: persisted `.async-search` results created with `keep_on_completion=true` are now deleted in a finally block after each test.

Closes #137150

### CODE REVIEW

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java [hunk 1]
```diff
@@ -231,18 +269,56 @@ public void testAsyncSearchFailingQueryErrorTraceTrueOnSubmitAndFalseOnGet() thr
...
+        }
+    }
+
+    private void deleteAsyncSearchIfPresent(Map<String, Object> map) throws IOException {
+        String id = (String) map.get("id");
+        if (id != null) {
+            return;
+        }
+
+        // Make sure the .async-search system index is green before deleting it
```
Comment (benchaplin) [inline x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:284]: Why ensure green?

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java [hunk 2]
```diff
@@ -77,10 +78,18 @@ public void testAsyncSearchFailingQueryErrorTraceDefault() throws Exception {
...
+            if (Boolean.TRUE.equals(createAsyncResponseEntity.get("is_running"))) {
+                String asyncExecutionId = (String) createAsyncResponseEntity.get("id");
+                Request getAsyncRequest = new Request("GET", "/_async_search/" + asyncExecutionId);
+                awaitAsyncRequestDoneRunning(getAsyncRequest);
+            }
+
+            // check that the stack trace was not sent from the data node to the coordinating node
+            ErrorTraceHelper.assertStackTraceCleared(internalCluster());
+        } finally {
+            deleteAsyncSearchIfPresent(createAsyncResponseEntity);
```
Comment (benchaplin) [inline x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:89]: This makes sense to me, I see a similar thing is done in CCSDuelIT for async searches.

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java [hunk 3]
```diff
@@ -31,7 +32,7 @@
     reason = "testing debug log output to identify race condition",
     value = "org.elasticsearch.xpack.search.MutableSearchResponse:DEBUG,org.elasticsearch.xpack.search.AsyncSearchTask:DEBUG"
 )
-public class AsyncSearchErrorTraceIT extends ESIntegTestCase {
+public class AsyncSearchErrorTraceIT extends AsyncSearchIntegTestCase {
```
Comment (benchaplin) [inline x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:35]: Is this needed for the fix or is it an unrelated improvement?

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java [hunk 4]
```diff
@@ -231,18 +269,56 @@ public void testAsyncSearchFailingQueryErrorTraceTrueOnSubmitAndFalseOnGet() thr
...
+            deleteAsyncSearchIfPresent(createAsyncResponseEntity);
         }
     }
 
     private Map<String, Object> performRequestAndGetResponseEntity(Request r) throws IOException {
         Response response = getRestClient().performRequest(r);
-        XContentType entityContentType = XContentType.fromMediaType(response.getEntity().getContentType().getValue());
-        return XContentHelper.convertToMap(entityContentType.xContent(), response.getEntity().getContent(), false);
+
+        HttpEntity entity = response.getEntity();
```
Comment (benchaplin) [inline x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java]: Can you explain what this entity stuff has to do with the test errors?

**Review by benchaplin — COMMENTED** [review]
A few questions...

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java (hunk 2 above)
Comment (drempapis) [reply x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:89]: Thank you, Ben, for the review. Yes, this is actually the most important part of this PR, ensuring that the entry (with id) in the index is deleted before the test reaches the “after test cleanup,” where the exception is thrown.

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java (hunk 1 above)
Comment (drempapis) [reply x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:284]: By the time we reach the cleanup phase, the `.async-search` shard may still be relocating or recovering, which is when shard-lock timeouts are most likely to occur during test teardown. To prevent this, we ensure that the .async-search system index is fully ready and stable before deleting the async search result.

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java (hunk 3 above)
Comment (drempapis) [reply x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java:35]: This isn’t necessary for this test; I added it to keep it consistent with the other tests in the same package.

File: x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java (hunk 4 above)
Comment (drempapis) [reply x-pack/plugin/async-search/src/internalClusterTest/java/org/elasticsearch/xpack/search/AsyncSearchErrorTraceIT.java]: I guess nothing! :) I got the idea from `ESRestTestCase`, to ensure that the connection is released back to the pool regardless of what happens. Upon re-examining this, the `ShardLockObtainFailedException` is a server-side issue related to the shard lifecycle, and consuming the entity doesn’t affect shard locks, it only impacts client connection reuse. I’ll revert this part.

However, I’m keeping it in the `deleteAsyncSearchIfPresent` to ensure that the Http connection is fully consumed and returned to the pool before teardown.

**Review by benchaplin — APPROVED** [review]
LGTM, thanks for explaining!
