### PR TITLE
Fix testTracingCrossCluster

### LINKED ISSUE #112731: [CI] RemoteClusterSecurityWithApmTracingRestIT testTracingCrossCluster failing
**Build Scans:**
- [elasticsearch-periodic #4016 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/5e2ftumjcroqs)
- [elasticsearch-periodic #4013 / openjdk23_checkpart4_java-matrix](https://gradle-enterprise.elastic.co/s/ptxxzf4l5bh72)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:qa:multi-cluster:javaRestTest" --tests "org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityWithApmTracingRestIT.testTracingCrossCluster" -Dtests.seed=B4CE8F084EEF8709 -Dtests.locale=fi-FI -Dtests.timezone=Atlantic/Faeroe -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testTracingCrossCluster'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityWithApmTracingRestIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <[]>
     but: was <[name "indices:admin/resolve/cluster" and trace_id "0af7651916cd43dd8448eb211c80319c", name "GET /_resolve/cluster/{name}" and trace_id "0af7651916cd43dd8448eb211c80319c"]>
```

**Issue Reasons:**
- [main] 2 consecutive failures in step openjdk23_checkpart4_java-matrix
- [main] 2 failures in test testTracingCrossCluster (2.2% fail rate in 91 executions)
- [main] 2 failures in step openjdk23_checkpart4_java-matrix (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by jfreden**
The original failure was a JDK 23 / ByteBuddy incompatibility that prevented the APM agent from starting. That underlying issue has since been fixed by APM agent 1.55.0. However, a second issue made the test still fail:

In PR #130607, `TaskManager.maybeStartTrace` was changed to only start traces if a parent APM trace context already exists locally — i.e. transport actions are no longer auto-traced. For cross-cluster requests, the receiving cluster has no parent APM context, so the fulfilling cluster never produces a transaction for indices:admin/resolve/cluster. The original test's second assertion can never be satisfied.

Change: 
  1. `muted-tests.yml` — Removed the mute entry for testTracingCrossCluster.
  2. `x-pack/plugin/security/qa/multi-cluster/build.gradle` — Added clusterModules `project(':test:external-modules:test-apm-integration')` to expose `/_flush_telemetry` for deterministic flushing.
  3. `RemoteClusterSecurityWithApmTracingRestIT.java`:
    - Dropped the unsatisfiable fulfilling-cluster transport assertion; added Javadoc citing #130607.
    - Added a `/_flush_telemetry` call so the test no longer waits on the agent's batch interval.
    - Replaced the ignored-result `finished.await(...)` with `assertTrue(... finished.await(...))` so a future regression yields a clearer failure message including remaining unmet assertions.

Resolves: https://github.com/elastic/elasticsearch/issues/112731

### CODE REVIEW

File: x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityWithApmTracingRestIT.java [hunk 1]
```diff
@@ -147,7 +147,10 @@ public void testTracingCrossCluster() throws Exception {
         final Response response = client().performRequest(resolveRequest);
         assertOK(response);
 
-        finished.await(30, TimeUnit.SECONDS);
+        // Force the APM agent on the query cluster to flush so the test does not depend on the agent's batch interval.
+        assertOK(client().performRequest(new Request("GET", "/_flush_telemetry")));
```
Comment (n1v0lg) [inline x-pack/plugin/security/qa/multi-cluster/src/javaRestTest/java/org/elasticsearch/xpack/remotecluster/RemoteClusterSecurityWithApmTracingRestIT.java:151]: Kinda weird that it's a GET

**Review by n1v0lg — APPROVED** [review]
I have wanted to fix this test failure for over a year haha

Thanks for working on it!
