### PR TITLE
Fix simple query string serialization conditional

### LINKED ISSUE #38889: simple_query_string doesn't work with CCS between ES 6 and ES 5
**Elasticsearch version** (`bin/elasticsearch --version`): CCS between ES 6.5.1 and ES 5.6.2

**Plugins installed**: [ N/A ]

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Tested on Mac + Linux

**Description of the problem including expected versus actual behavior**:

When sending a `simple_query_string` query to an ES6 cluster to be run on a remote ES5 cluster via cross-cluster search, the query fails.

**Steps to reproduce**:

1. Spin up an ES 5.6.2 node (cluster-name: `es-562`)
2. Spin up an ES 6.5.1 node (cluster-name: `es-651`)
3. Create a test index on `es-562`
```
PUT test/doc/1
{
  "test": "John"
}
```
4. Set up CCS on `es-651`
```
PUT _cluster/settings
{
  "persistent": {
    "search": {
      "remote": {
        "es-562": {
          "seeds": [
            "localhost:9301"
          ]
        }
      }
    }
  }
}
```
5. Search john directly from `es-562` (no CCS)
``` 
POST test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "simple_query_string": {
            "query": "john",
            "fields": [
              "test"
            ]
          }
        }
      ]
    }
  }
}
```
**=> Document 1 is returned**

5. Search john from `es-651` (via CCS)
``` 
POST es-562:test/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "simple_query_string": {
            "query": "john",
            "fields": [
              "test"
            ]
          }
        }
      ]
    }
  }
}
```
**=> ERROR**
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Unknown NamedWriteable [org.elasticsearch.index.query.QueryBuilder][]"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "es-562:test",
        "node": "8Gql5xv_T7C8oXtPsWb4pQ",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "Unknown NamedWriteable [org.elasticsearch.index.query.QueryBuilder][]"
        }
      }
    ],
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Unknown NamedWriteable [org.elasticsearch.index.query.QueryBuilder][]",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Unknown NamedWriteable [org.elasticsearch.index.query.QueryBuilder][]"
      }
    }
  },
  "status": 400
}
```
Replacing `must` by `should` produces the same error.
Replacing `must` by `filter` yields another similar error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "unexpected byte [0x02]"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "es-562:test",
        "node": "8Gql5xv_T7C8oXtPsWb4pQ",
        "reason": {
          "type": "illegal_state_exception",
          "reason": "unexpected byte [0x02]"
        }
      }
    ],
    "caused_by": {
      "type": "illegal_state_exception",
      "reason": "unexpected byte [0x02]",
      "caused_by": {
        "type": "illegal_state_exception",
        "reason": "unexpected byte [0x02]"
      }
    }
  },
  "status": 500
}
```

Finally, it is also worth noting that replacing `simple_query_string` with `query_string` (whether `must`, `filter` or `should`) works and yields document 1. 

So it clearly seems that CCS doesn't like `simple_query_string` and that feels like a bug. I'm all ears if anyone has any idea. Thanks much in advance.

### PR DESCRIPTION
**Pull request by javanna**
Looks like #21504 introduced a serialization conditional for lenientSet,
but the PR was never backported to 5.x hence whenever simple query
string is serialized between 6.x and 5.6, it can't be read/written properly causing errors on the transport layer.

This commit updates the conditional to only read/write the field against
6.0+ versions which are aware of it.

Closes #38889

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/query/SimpleQueryStringBuilderTests.java [hunk 1]
```diff
@@ -754,4 +759,31 @@ private static IndexMetaData newIndexMeta(String name, Settings oldIndexSettings
...
+                SimpleQueryStringBuilder deserializedQuery = new SimpleQueryStringBuilder(in);
+                assertNotSame(queryBuilder, deserializedQuery);
+                assertEquals("query", deserializedQuery.value());
+                assertEquals(1, deserializedQuery.fields().size());
+                assertEquals("field", deserializedQuery.fields().keySet().iterator().next());
+            }
+        }
+    }
+
+    public void testReadFrom_5_6() throws IOException {
```
Comment (jimczi) [inline server/src/test/java/org/elasticsearch/index/query/SimpleQueryStringBuilderTests.java]: We should add a simple rest test for the `simple_query_string` as a follow up in master. This would have caught this bug if we had one.

**Review by jimczi — APPROVED** [review]
Ouch, thanks @javanna . I left one comment for a follow up to ensure that we have bwc tests for this query.

File: server/src/test/java/org/elasticsearch/index/query/SimpleQueryStringBuilderTests.java (hunk 1 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/index/query/SimpleQueryStringBuilderTests.java]: right, this unit test would have failed if we had it, but it only catches the bug when reading on 6.7 something that was written on 5.6. The other way around is much harder to test in 6.x cause we don't really have the reading code from 5.6.
