### PR TITLE
Do not use system properties when building the HttpAsyncClient

### LINKED ISSUE #27827: Rest client settings related to connections and keep alives are broken
In 5.6 we introduced a change to the rest client that told the apache client to use system properties for some settings (3e4bc027ebdba5dd1a0935a75b5218960f736f76). 

```
HttpAsyncClientBuilder httpClientBuilder = HttpAsyncClientBuilder.create().setDefaultRequestConfig(requestConfigBuilder.build())
                //default settings for connection pooling may be too constraining
                .setMaxConnPerRoute(DEFAULT_MAX_CONN_PER_ROUTE).setMaxConnTotal(DEFAULT_MAX_CONN_TOTAL).useSystemProperties();
```

This was introduced to force the client to use the system default `SSLContext`. Unfortunately this also leads the http client to use system properties for max connections, keep alive, and other configs. This means that our settings of `DEFAULT_MAX_CONN_PER_ROUTE` and `DEFAULT_MAX_CONN_TOTAL` are ignored. Additionally any settings that a user changes related to the client might be ignored (depending on the setting).

`org.apache.http.impl.nio.client.HttpAsyncClientBuilder.class`
```
            if (systemProperties) {
                String s = System.getProperty("http.keepAlive", "true");
                if ("true".equalsIgnoreCase(s)) {
                    s = System.getProperty("http.maxConnections", "5");
                    final int max = Integer.parseInt(s);
                    poolingmgr.setDefaultMaxPerRoute(max);
                    poolingmgr.setMaxTotal(2 * max);
                }
            } else {
                if (maxConnTotal > 0) {
                    poolingmgr.setMaxTotal(maxConnTotal);
                }
                if (maxConnPerRoute > 0) {
                    poolingmgr.setDefaultMaxPerRoute(maxConnPerRoute);
                }
            }
```

I think we need to configured the SSLContext specifically, opposed for forcing system properties for many settings.

@jaymode

### PR DESCRIPTION
**Pull request by jaymode**
This commit removes the usage of system properties for the HttpAsyncClient as this overrides some
defaults that we intentionally change. In order to set the default SSLContext to the system context
we set the SSLContext on the builder explicitly.

Closes #27827

### CODE REVIEW

File: client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java [hunk 1]
```diff
@@ -200,20 +202,25 @@ private CloseableHttpAsyncClient createHttpClient() {
...
-            httpClientBuilder = httpClientConfigCallback.customizeHttpClient(httpClientBuilder);
-        }
-
-        final HttpAsyncClientBuilder finalBuilder = httpClientBuilder;
-        return AccessController.doPrivileged(new PrivilegedAction<CloseableHttpAsyncClient>() {
-            @Override
-            public CloseableHttpAsyncClient run() {
-                return finalBuilder.build();
+                .setMaxConnPerRoute(DEFAULT_MAX_CONN_PER_ROUTE).setMaxConnTotal(DEFAULT_MAX_CONN_TOTAL)
+                .setSSLContext(SSLContext.getDefault());
```
Comment (tbrooks8) [inline client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java]: I just want to point out that this is slightly different from what is happening now. When it uses the system properties, Apache is calling `SSLContexts.createSystemDefault()`. Which does:

```
try {
    return SSLContext.getDefault();
} catch (final NoSuchAlgorithmException ex) {
    return createDefault();
}
```

And `createDefault()`:

```
try {
            final SSLContext sslcontext = SSLContext.getInstance(SSLContextBuilder.TLS);
            sslcontext.init(null, null, null);
            return sslcontext;
        } catch (final NoSuchAlgorithmException ex) {
            throw new SSLInitializationException(ex.getMessage(), ex);
        } catch (final KeyManagementException ex) {
            throw new SSLInitializationException(ex.getMessage(), ex);
        }
```

You know better than I if that change is okay. I just wanted to point it out.

**Review by Tim-Brooks — APPROVED** [review]
LGTM. One comment.

File: client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java (hunk 1 above)
Comment (jaymode) [reply client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java]: Thanks for looking into this. I was aware of it and the behavior change was intentional; I think the previous method was too lenient in that it silently ignored a bad parameter and swallowed the exception.
