### PR TITLE
Autoscale frozen tier into existence

### LINKED ISSUE #72771: Frozen shards remain UNASSIGNED if there is no frozen tier at the time of creation
**Elasticsearch version** (`bin/elasticsearch --version`):
7.13-Snapshot (on the cloud)

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
(Cloud)

**Description of the problem including expected versus actual behavior**:
This is a bit involved. And there appears to be 2 parts to this issue. I found these related issues when testing enabling a frozen tier through autoscaling (0 -> 1) in the cloud. 

Here is what I did:

**ISSUE 1**
1. Create a index
```
PUT test/_doc/1
{ "test" : "test" }
```
2. Create a snapshot based on that index
```
PUT /_snapshot/found-snapshots/snapshot_1?wait_for_completion=true
{
   "indices" : "test"
}
```
3. Mount that snapshot 
```
POST /_snapshot/found-snapshots/snapshot_1/_mount?wait_for_completion=true&storage=shared_cache
{
  "index": "test", 
  "renamed_index": "frozen_test1"
}
```

The first issue immediately presents itself - the new index `frozen_test1` will be UNASSIGNED and the entire cluster will be marked unhealthy `RED`. This is a serious issue because no cloud plans can be applied to an unhealthy cluster. More specifically, this means an autoscaling plan cannot be applied to enable the frozen tier so that the new index could be assigned. 

**ISSUE 2**
4. Continuing from the above, enable a frozen tier manually in the cloud UI
5. I would hope at this point the `frozen_test1` would be assigned since a frozen tier now exists.
6. Unfortunately, that is the not case; the index remains unassigned. 
```
GET _cluster/allocation/explain

{
  "index" : "frozen_test1",
  "shard" : 0,
  "primary" : true,
  "current_state" : "unassigned",
  "unassigned_info" : {
    "reason" : "NEW_INDEX_RESTORED",
    "at" : "2021-05-05T17:55:43.387Z",
    "details" : "restore_source[found-snapshots/snapshot_1]",
    "last_allocation_status" : "no"
  },
  "can_allocate" : "no",
  "allocate_explanation" : "cannot allocate because allocation is not permitted to any of the nodes",
  "node_allocation_decisions" : [
    {
      "node_id" : "EiaSvSZbRTKFMQXRwikVVg",
      "node_name" : "instance-0000000001",
      "transport_address" : "192.168.44.10:19963",
      "node_attributes" : {
        "logical_availability_zone" : "zone-0",
        "server_name" : "instance-0000000001.5fc50a1e728f4941bac1f662d41f5fee",
        "availability_zone" : "ece-zone-0",
        "xpack.installed" : "true",
        "data" : "frozen",
        "instance_configuration" : "data.frozen",
        "transform.node" : "false",
        "region" : "unknown-region"
      },
      "node_decision" : "no",
      "deciders" : [
        {
          "decider" : "restore_in_progress",
          "decision" : "NO",
          "explanation" : "shard has failed to be restored from the snapshot [found-snapshots:snapshot_1/KB3eQCZPQEKPQX86K6UxbA] because of [restore_source[found-snapshots/snapshot_1]] - manually close or delete the index [frozen_test1] in order to retry to restore the snapshot again or use the reroute API to force the allocation of an empty primary shard"
        }
      ]
    },
```

//cc @andrew-moldovan @zanbel @tobio

### PR DESCRIPTION
**Pull request by henningandersen**
This commit adds two related changes:
* ILM WaitForDataTierStep
* Autoscaling frozen_existence decider

The first part ensures that we wait mounting an index until a node that
can hold the index is available, avoiding a failed restore and red
cluster state. This is in particular important for the frozen phase, but
is done generically in the searchable snapshot action.

The second part triggers on indices in the ILM frozen phase to scale the
tier into existence by requiring a minimal amount of memory and storage.

Closes #72771

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java [hunk 1]
```diff
@@ -116,7 +116,6 @@ public String getSnapshotRepository() {
         // here before generating snapshots that can't be used if the user doesn't have the right license level.
         BranchingStep conditionalSkipActionStep = new BranchingStep(preActionBranchingKey, checkNoWriteIndex, nextStepKey,
             (index, clusterState) -> {
-                XPackLicenseState licenseState = XPackPlugin.getSharedLicenseState();
```
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java:119]: Can you explain why we need to move the license state back up into the top level instead of getting it here? It added quite a few lines injecting it into every ILM action

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java [hunk 2]
```diff
@@ -206,12 +205,17 @@ public String getSnapshotRepository() {
...
+            new CreateSnapshotStep(createSnapshotKey, waitForDataTierKey, client), cleanSnapshotKey, client);
 
-        // Now mount the snapshot to create the new index, if the skipGeneratingSnapshotStep determined a snapshot already existed that
+        MountSearchableSnapshotRequest.Storage storageType = getConcreteStorageType(mountSnapshotKey);
+
+        // If the skipGeneratingSnapshotStep determined a snapshot already existed that
         // can be used, it jumps directly here, skipping the snapshot generation steps above.
+        WaitForDataTierStep waitForDataTierStep =
+            new WaitForDataTierStep(waitForDataTierKey, mountSnapshotKey,
+                MountSearchableSnapshotRequest.getDataTiersPreference(storageType));
```
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java:216]: This is technically going to be sending the wrong preference, because the preference is either `data_cold,data_warm,data_hot` or `data_frozen` from the `getDataTiersPreference`, but actually if this is the hot phase, it will end up with a different preference:

https://github.com/elastic/elasticsearch/blob/c5b9fdea5bf7ac5988f7dde71a61754a1a3b50fb/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/MountSnapshotStep.java#L108-L111

**Review by dakrone — COMMENTED** [review]
I left some initial comments about the ILM-specific stuff

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java (hunk 1 above)
Comment (henningandersen) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java:119]: The problem is that `XPackPlugin.getSharedLicenseState()` is backed by a static `SetOnce` field making it unsuitable for use in tests. This pattern of passing in the `licenseState` was taken from ML. In CCR and Autoscaling, the `licenceState` is wrapped in a checker that is passed around instead. For ILM, the ML approach felt most natural since it allows any license check in the future.

I think there is no internal cluster tests today that trigger the `SearchableSnapshotAction`, however, I needed to add one in `FrozenExistenceDeciderIT`, necessitating this change.

If there is a different and/or better pattern for doing this I should be more than happy to adapt this.

File: x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycle.java [hunk 3]
```diff
@@ -187,7 +193,7 @@ protected Clock getClock() {
         ilmHistoryStore.set(new ILMHistoryStore(settings, new OriginSettingClient(client, INDEX_LIFECYCLE_ORIGIN),
             clusterService, threadPool));
         indexLifecycleInitialisationService.set(new IndexLifecycleService(settings, client, clusterService, threadPool,
-            getClock(), System::currentTimeMillis, xContentRegistry, ilmHistoryStore.get()));
+            getClock(), System::currentTimeMillis, xContentRegistry, ilmHistoryStore.get(), getLicenseState()));
```
[the remark this answers is not in the document]
Comment (henningandersen) [reply x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm/IndexLifecycle.java:196]: I believe not, since `XPackPlugin.licenseState` is a `SetOnce` object. Also, `XPackLicenseState` has an `update` method, which changes the `status` and is invoked from `LicenseService`. Must admit I am also not too familiar with the details, but I do believe this does not change behavior "in production".

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionState.java [hunk 4]
```diff
@@ -97,6 +97,15 @@ public static LifecycleExecutionState fromIndexMetadata(IndexMetadata indexMetad
...
     }
 
+    /**
+     * Return true if this index is in the frozen phase, false if not controlled by ILM or not in frozen.
+     * @param indexMetadata the metadata of the index to retrieve phase from.
+     * @return true if frozen phase, false otherwise.
+     */
+    public static boolean isFrozenPhase(IndexMetadata indexMetadata) {
+        Map<String, String> customData = indexMetadata.getCustomData(ILM_CUSTOM_METADATA_KEY);
+        return customData != null && TimeseriesLifecycleType.FROZEN_PHASE.equals(customData.get(PHASE));
```
[the remark this answers is not in the document]
Comment (henningandersen) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionState.java:107]: Yeah, I was deliberately micro-tuning this a bit, since it will be called rather heavily from the autoscaling decider and I felt like skipping the various object creations and map lookups etc. made sense.

[the remark this answers is not in the document]
Comment (dakrone) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionState.java:107]: Okay, if the performance difference is important enough, we might want to add a comment to make sure it doesn't get code-golfed down to a less optimal version in the future

**Comment by henningandersen** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionState.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (henningandersen) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecycleExecutionState.java]: ++, added in bfc5fa4bff9b0d0057a265bafbcc764d13e09e3d

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java (hunk 2 above)
Comment (henningandersen) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java]: thanks for noticing, fixed in 3d23644c27086a84dcb88c79a99fc6644da675f8

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForDataTierStep.java [hunk 5]
```diff
@@ -0,0 +1,101 @@
...
+        WaitForDataTierStep that = (WaitForDataTierStep) o;
+        return tierPreference.equals(that.tierPreference);
+    }
+
+    @Override
+    public int hashCode() {
+        return Objects.hash(super.hashCode(), tierPreference);
+    }
+
+    static final class Info implements ToXContentObject {
```
[the remark this answers is not in the document]
Comment (henningandersen) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/WaitForDataTierStep.java]: ++, fixed in 84b99ef3e8ab7a4f91fc8be95238c4a9fe9b65d8

**Review by dakrone — APPROVED** [review]
ILM parts LGTM, thanks for iterating on this Henning

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java [hunk 6]
```diff
@@ -92,6 +91,11 @@ public String getSnapshotRepository() {
 
     @Override
     public List<Step> toSteps(Client client, String phase, StepKey nextStepKey) {
+        throw new UnsupportedOperationException();
```
Comment (DaveCTurner) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java:94]: nit: `assert false` here too? For the record I'd rather just add the parameter to `toSteps()` everywhere rather than have this uncalled overload, i.e, the opposite of what we did in d4b2e32137b429275fc1372630fc33ce49bb3887.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/searchablesnapshots/MountSearchableSnapshotRequest.java [hunk 7]
```diff
@@ -109,6 +110,22 @@ public MountSearchableSnapshotRequest(StreamInput in) throws IOException {
         }
     }
 
+    /**
+     * Returns the preference for new searchable snapshot indices. When
+     * performing a full mount the preference is cold - warm - hot. When
+     * performing a partial mount the preference is only frozen
+     */
+    public static String getDataTiersPreference(Storage type) {
```
Comment (DaveCTurner) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/searchablesnapshots/MountSearchableSnapshotRequest.java:118]: nit/qq: why not an instance method on `Storage`?

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotActionTests.java [hunk 8]
```diff
@@ -47,15 +48,29 @@ public void testToSteps() {
         assertThat(steps.get(12).getKey(), is(expectedSteps.get(12)));
         assertThat(steps.get(13).getKey(), is(expectedSteps.get(13)));
         assertThat(steps.get(14).getKey(), is(expectedSteps.get(14)));
+        assertThat(steps.get(15).getKey(), is(expectedSteps.get(15)));
```
Comment (DaveCTurner) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotActionTests.java:51]: nit: what's the deal with all this unrolling?

**Review by DaveCTurner — APPROVED** [review]
LGTM I think, sorry it's taken a while to get my head around this. I left only trivial and optional comments.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotActionTests.java (hunk 8 above)
Comment (henningandersen) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotActionTests.java:51]: I mainly followed the same methodology. I will leave it to @dakrone to comment on the idea behind this?

Comment (dakrone) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotActionTests.java:51]: There's no reason these have to be unrolled, as long as we have the expected steps comparing them all at once is fine. I don't know why they were initially unrolled.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java (hunk 6 above)
Comment (henningandersen) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java:96]: See 63816a07d4ab7802b2be8b0721d99d1b31df1c3d. I left the overload as is.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/searchablesnapshots/MountSearchableSnapshotRequest.java (hunk 7 above)
Comment (henningandersen) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/searchablesnapshots/MountSearchableSnapshotRequest.java]: Doh, thanks, fixed in 32371ac45b6220d63bcaafdedc9b38f6ca4d5440

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecyclePolicy.java [hunk 9]
```diff
@@ -206,9 +207,10 @@ public XContentBuilder toXContent(XContentBuilder builder, Params params) throws
      *
      * @param client The Elasticsearch Client to use during execution of {@link AsyncActionStep}
      *               and {@link AsyncWaitStep} steps.
+     * @param licenseState
```
[the remark this answers is not in the document]
Comment (henningandersen) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/LifecyclePolicy.java]: I added a bit of doc in aec84ec87d84c33389d8883db3db61261ffb6cc7
