### PR TITLE
Ensure cancellation reason visible when task is canceled (#142079)

### LINKED ISSUE #142079: [CI] ReindexManagementClientYamlTestSuiteIT test {yaml=reindex/30_cancel_reindex/Cancel running reindex returns response and GET confirms completed} failing
**Build Scans:**
- [elasticsearch-intake #34354 / part1](https://gradle-enterprise.elastic.co/s/scatsm23vyh3q)
- [elasticsearch-pull-request #118392 / part-1](https://gradle-enterprise.elastic.co/s/2ycrynnaqckpu)
- [elasticsearch-pull-request #118171 / part-1](https://gradle-enterprise.elastic.co/s/mcmbdpt3o7tei)
- [elasticsearch-pull-request #118057 / part-1](https://gradle-enterprise.elastic.co/s/d4l4dpsklwgde)

**Reproduction Line:**
```
./gradlew ":modules:reindex-management:yamlRestTest" --tests "org.elasticsearch.reindex.management.ReindexManagementClientYamlTestSuiteIT.test {yaml=reindex/30_cancel_reindex/Cancel running reindex returns response and GET confirms completed}" -Dtests.seed=B99B4680CAF89268 -Dtests.locale=en-PG -Dtests.timezone=America/Jamaica -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.reindex.management.ReindexManagementClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('test%20%7Byaml%3Dreindex%2F30_cancel_reindex%2FCancel%20running%20reindex%20returns%20response%20and%20GET%20confirms%20completed%7D'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: java.lang.AssertionError: field [status.canceled] is null
```

**Issue Reasons:**
- [main] 4 failures in test test {yaml=reindex/30_cancel_reindex/Cancel running reindex returns response and GET confirms completed} (0.5% fail rate in 753 executions)
- [main] 3 failures in step part-1 (0.7% fail rate in 440 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.7% fail rate in 434 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by michalborek**
Although, the cancellation reason is set in a synchronized block the access to the `reason` variable is not synchronized so there operation is not atomic. 

By removing an additional field (`isCancelled`) and replacing its usage by comparing the `reason` to `null` we can achieve the same behavior without a risk of `reason` field being null when the task was canceled. 

To efficiently compare and set the `reason`, `java.lang.invoke.VarHandle` was used.

IMHO this is a genuine bug caught by a test that is currently muted. This PR fixes #142079 issue.

### CODE REVIEW

**Review by DaveCTurner — DISMISSED** [review]
Hmm, todays order of assignments is deliberate, according to the javadoc for `getReasonCancelled`:

> May also be null if the task was just cancelled since we don't set the reason and the cancellation flag atomically.

Instead, the expectation is that callers don't rely on the reason being set when the cancelled flag is, instead using something like `ensureNotCancelled` or `notifyIfCancelled` which should avoid the race.

Can you instead fix up the caller that's trying to access the reason in a racy way?

File: server/src/main/java/org/elasticsearch/tasks/CancellableTask.java [hunk 1]
```diff
@@ -112,12 +119,11 @@ public final <T> boolean notifyIfCancelled(ActionListener<T> listener) {
 
     @Override
     public String toString() {
-        return "CancellableTask{" + super.toString() + ", reason='" + reason + '\'' + ", isCancelled=" + isCancelled + '}';
+        return "CancellableTask{" + super.toString() + ", reason='" + reason + '\'' + ", isCancelled=" + isCancelled() + '}';
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/tasks/CancellableTask.java]: Could we have a single volatile read here? Otherwise we could have a string with a `null` reason but with `isCancelled` is `true`?

**Review by DaveCTurner — COMMENTED** [review]
Could you adjust `CancellableTasksTests` to demonstrate the bug that this fixes (i.e. that `getReasonCancelled` cannot return `null` after `isCancelled` returns `true`)?

File: server/src/main/java/org/elasticsearch/tasks/CancellableTask.java (hunk 1 above)
Comment (michalborek) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTask.java]: @DaveCTurner do you mean extract a `reason` to a var and use `reason != null` instead of `isCancelled()`?

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTask.java]: yep

Comment (DaveCTurner) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTask.java]: (this also deserves a test to make sure the string is always consistent)

Comment (michalborek) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTask.java]: In both cases, do you think of a kind of stress test (like ~1k iterations) trying to catch a faulty case?

Comment (michalborek) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTask.java]: Added two tests covering both cases.

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java [hunk 2]
```diff
@@ -601,6 +601,62 @@ public void testEnsureNotCancelled() throws Exception {
         );
     }
 
+    /**
+     * Regression test: previously isCancelled and reason were separate fields set non-atomically,
+     * so a reader could observe `isCancelled() == true` while `getReasonCancelled() == null`.
+     */
+    public void testReasonVisibleWhenCancelled() throws Exception {
+        final int iterations = 1000;
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java]: Once is enough really, it will run thousands of times in CI anyway.

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java [hunk 3]
```diff
@@ -601,6 +601,62 @@ public void testEnsureNotCancelled() throws Exception {
...
+            final AtomicReference<String> failure = new AtomicReference<>();
+            final CountDownLatch start = new CountDownLatch(1);
+
+            final Thread reader = new Thread(() -> {
+                safeAwait(start);
+                while (task.isCancelled() == false) {
+                    Thread.onSpinWait();
+                }
+                if (task.getReasonCancelled() == null) {
+                    failure.set("getReasonCancelled() returned null after isCancelled() returned true");
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java]: You can just assert it's not null here. An `AssertionError` on any thread will fail the test, no need to propagate it out to the test thread.

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java [hunk 4]
```diff
@@ -601,6 +601,62 @@ public void testEnsureNotCancelled() throws Exception {
...
+                while (task.isCancelled() == false) {
+                    Thread.onSpinWait();
+                }
+
+                String toString = task.toString();
+                if (toString.endsWith("reason='null', isCancelled=true}")) {
+                    failure.set("null reason when isCancelled() is true");
+                } else if (toString.endsWith("reason='test-reason', isCancelled=false}")) {
+                    failure.set("isCancelled false when reason is set");
+                }
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java]: This seems fragile, we might break this in future in ways that trip neither of those two conditions. WDYT about something like this instead?

```java
                assertThat(
                    task.toString(),
                    anyOf(endsWith("reason='null', isCancelled=false}"), endsWith("reason='test-reason', isCancelled=true}"))
                );
```

Also can we do this check in the `isCancelled() == false` loop? After the loop, we should be able to assert it `endsWith("reason='test-reason', isCancelled=true}")` alone.

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java (hunk 2 above)
Comment (michalborek) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java]: Removed

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java (hunk 3 above)
Comment (michalborek) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java]: Yes, that's true... I simplified both methods now

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java (hunk 4 above)
Comment (michalborek) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java]: This is a good idea, actually

Comment (michalborek) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java]: In the meantime I changed it to `not any of` but I like yours more

File: server/src/main/java/org/elasticsearch/tasks/CancellableTask.java
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/tasks/CancellableTask.java]: Do we need to be `synchronized` here any more? Likewise elsewhere in the class.

Comment (michalborek) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTask.java]: Good catch, it may not be, since once the "reason" change is visible it will never be switched back to null by another thread. I will think about it and remove it if I find no case it would make sense. Thanks!

Comment (michalborek) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTask.java]: Confirmed, in all the cases it looks safe not drop synchronization because we always check for result not being null (once it's visible it will never return another value).

I made the change.

**Review by DaveCTurner — APPROVED** [review]
LGTM thanks @michalborek !

File: server/src/main/java/org/elasticsearch/tasks/CancellableTask.java [hunk 5]
```diff
@@ -33,12 +45,8 @@ public CancellableTask(long id, String type, String action, String description,
...
-            if (this.isCancelled) {
-                return;
-            }
-            this.isCancelled = true;
-            this.reason = reason;
+        if (REASON_HANDLE.compareAndSet(this, null, reason) == false) {
+            return;
         }
         listeners.onResponse(null);
         onCancelled();
```
Comment (szybia) [inline server/src/main/java/org/elasticsearch/tasks/CancellableTask.java:52]: complete nit (don't implement this, just sharing what i would've done), a bit easier to read IMO

```suggestion
        if (REASON_HANDLE.compareAndSet(this, null, reason)) {
            listeners.onResponse(null);
            onCancelled();
        }

```

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java [hunk 6]
```diff
@@ -601,6 +603,48 @@ public void testEnsureNotCancelled() throws Exception {
...
+        final Thread reader = new Thread(() -> {
+            safeAwait(start);
+            while (task.isCancelled() == false) {
+                Thread.onSpinWait();
+            }
+            assertThat(
+                "toString should consistently render status and reason",
+                task.toString(),
+                anyOf(endsWith("reason='null', isCancelled=false}"), endsWith("reason='test-reason', isCancelled=true}"))
+            );
```
Comment (szybia) [inline server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java:640]: am i right in saying that after the while loop we can only get `reason='test-reason', isCancelled=true}`?

and within the while loop we can get both

```suggestion
            while (task.isCancelled() == false) {
                assertThat(
                    "toString should consistently render status and reason",
                    task.toString(),
                    anyOf(endsWith("reason='null', isCancelled=false}"), endsWith("reason='test-reason', isCancelled=true}"))
                );
            }
            assertThat(
                "toString should consistently render status and reason",
                task.toString(),
                endsWith("reason='test-reason', isCancelled=true}")
            );
```

basically same comment as David: https://github.com/elastic/elasticsearch/pull/144629#discussion_r2965872194

i guess not critical but IIUC stronger assertion to have

**Review by szybia — APPROVED** [review]
nice work! TIL more about VarHandle and Thread.onSpinWait :)

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java (hunk 6 above)
Comment (michalborek) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java:640]: Hm, the intention was slightly different. 

"Until the task isn't cancelled, I don't care. When it gets cancelled, it should be consistent."

File: server/src/main/java/org/elasticsearch/tasks/CancellableTask.java (hunk 5 above)
Comment (michalborek) [reply server/src/main/java/org/elasticsearch/tasks/CancellableTask.java:52]: I like it too but, I'd leave the current because this is the guard clause pattern. It is redundant and more explicit but shows the main flow

File: server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java (hunk 6 above)
Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java:640]: Ah yeah sorry I missed this. We _do_ care while the task is (recently) not cancelled that we do not see an inconsistent result, and once we know the task is definitely cancelled we must not see `isCancelled=false` again. So yes I'd rather we adjusted it as Szymon suggests.

Comment (michalborek) [reply server/src/test/java/org/elasticsearch/action/admin/cluster/node/tasks/CancellableTasksTests.java:640]: Since I prematurely hit Merge, I've prepared a PR for this: https://github.com/elastic/elasticsearch/pull/144716 :)
