### PR TITLE
ESQL: fix BlockAccountingTests and add a new filter test scenario

### LINKED ISSUE #100586: [CI] BlockAccountingTests testIntBlock failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/xdhkscy2pqu5q/tests/:x-pack:plugin:esql:compute:test/org.elasticsearch.compute.data.BlockAccountingTests/testIntBlock
**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:compute:test' --tests "org.elasticsearch.compute.data.BlockAccountingTests.testIntBlock" -Dtests.seed=1D163F8B24E19E90 -Dtests.locale=es-US -Dtests.timezone=Atlantic/Faeroe -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.compute.data.BlockAccountingTests&tests.test=testIntBlock
**Failure excerpt:**
```
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2

  at __randomizedtesting.SeedInfo.seed([1D163F8B24E19E90:55DDC8E9FAF29190]:0)
  at org.elasticsearch.compute.data.AbstractBlock.getValueCount(AbstractBlock.java:72)
  at org.elasticsearch.compute.data.IntArrayBlock.getValueCount(IntArrayBlock.java:20)
  at org.elasticsearch.compute.data.IntArrayBlock.filter(IntArrayBlock.java:60)
  at org.elasticsearch.compute.data.IntArrayBlock.filter(IntArrayBlock.java:20)
  at org.elasticsearch.compute.data.BlockAccountingTests.testIntBlock(BlockAccountingTests.java:164)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit fixes a failure in BlockAccountingTests, and adds a new filter test scenario that filters on the last position of a multivalue.

closes  #100586

### CODE REVIEW

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/BlockAccountingTests.java [hunk 1]
```diff
@@ -45,7 +45,7 @@ public void testBooleanVector() {
         Vector emptyPlusOne = new BooleanArrayVector(new boolean[] { randomBoolean() }, 1);
         assertThat(emptyPlusOne.ramBytesUsed(), is(alignObjectSize(empty.ramBytesUsed() + 1)));
 
-        boolean[] randomData = new boolean[randomIntBetween(1, 1024)];
+        boolean[] randomData = new boolean[randomIntBetween(2, 1024)];
```
Comment (ChrisHegarty) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/BlockAccountingTests.java:48]: subsequent filtering is on position 1, so we must have at least two positions in our data.

File: x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/BlockAccountingTests.java [hunk 2]
```diff
@@ -130,13 +130,11 @@ public void testBooleanBlock() {
         Block emptyPlusOne = new BooleanArrayBlock(new boolean[] { randomBoolean() }, 1, new int[] { 0 }, null, Block.MvOrdering.UNORDERED);
         assertThat(emptyPlusOne.ramBytesUsed(), is(alignObjectSize(empty.ramBytesUsed() + 1) + alignObjectSize(Integer.BYTES)));
 
-        boolean[] randomData = new boolean[randomIntBetween(1, 1024)];
-        int[] valueIndices = IntStream.range(0, randomData.length).toArray();
+        boolean[] randomData = new boolean[randomIntBetween(2, 1024)];
+        int[] valueIndices = IntStream.range(0, randomData.length + 1).toArray();
```
Comment (ChrisHegarty) [inline x-pack/plugin/esql/compute/src/test/java/org/elasticsearch/compute/data/BlockAccountingTests.java:134]: We're building block arrays directly in the test (rather than using a builder), and must construct a valid structured block so that we can filter on it. A block with firstValuesIndex must have a final element entry in to hold the end of the final position. This is why we +1 here - each position entry has just one entry, and the last has the final end position.  Note: builders do this for you, but we want to be more specific in this test. A separate test scenario verifies filtering on the final position.

**Review by dnhatn — APPROVED** [review]
LGTM. Thank you for fixing these tests.

**Review by nik9000 — APPROVED** [review]
