### PR TITLE
Move HTTP content aggregation from Netty into RestController

### LINKED ISSUE #120746: Indexing a single doc to a data stream bulk endpoint trips assertion and returns class cast exception
### Elasticsearch Version

Latest `main` branch

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

OSX

### Problem Description

Even though this is an invalid request, we shouldn't trip an assertion, and we shouldn't return a cryptic exception.

### Steps to Reproduce

First, create a data stream:

```
POST /logs-foo-bar/_doc
{
  "@timestamp": "2024-01-01",
  "message": "aoeu aoeu aoeu"
}
```

Then, try to index a doc, but accidentally add `…/_bulk` to the endpoint:

```
POST /logs-foo-bar/_doc/_bulk
{
  "@timestamp": "2024-01-01",
  "message": "aoeu aoeu aoeu"
}
```

### Logs (if relevant)

ES running in dev mode (assertions enabled) will then crash with:

```
[2025-01-23T09:44:59,734][ERROR][o.e.ExceptionsHelper     ] [runTask-0] fatal error java.lang.AssertionError: null
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.ExceptionsHelper.lambda$maybeDieOnAnotherThread$4(ExceptionsHelper.java:448)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.ExceptionsHelper.maybeDieOnAnotherThread(ExceptionsHelper.java:438)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.exceptionCaught(Netty4HttpPipeliningHandler.java:499)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4LeakDetectionHandler.channelRead(Netty4LeakDetectionHandler.java:38)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:120)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpContentSizeHandler.handleRequest(Netty4HttpContentSizeHandler.java:150)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpContentSizeHandler.channelRead(Netty4HttpContentSizeHandler.java:106)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpAggregator.channelRead(Netty4HttpAggregator.java:52)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpHeaderValidator.forwardData(Netty4HttpHeaderValidator.java:213)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpHeaderValidator.forwardFullRequest(Netty4HttpHeaderValidator.java:156)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpHeaderValidator$1.lambda$onResponse$0(Netty4HttpHeaderValidator.java:128)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.transport@4.1.115.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.common@4.1.115.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
[2025-01-23T09:44:59,735][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [runTask-0] fatal error in thread [elasticsearch-error-rethrower], exiting java.lang.AssertionError
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.HttpBody.asFull(HttpBody.java:42)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestRequest.content(RestRequest.java:313)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestRequest.requiredContent(RestRequest.java:341)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.action.document.RestIndexAction.prepareRequest(RestIndexAction.java:109)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:99)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:466)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:460)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.doHandleRequest(SecurityRestFilter.java:89)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$0(SecurityRestFilter.java:81)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:257)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.lambda$authenticateAndAttachToContext$3(SecondaryAuthenticator.java:99)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticate(SecondaryAuthenticator.java:109)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticateAndAttachToContext(SecondaryAuthenticator.java:90)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.intercept(SecurityRestFilter.java:75)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:460)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:624)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:307)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:488)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:584)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:461)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.handlePipelinedRequest(Netty4HttpPipeliningHandler.java:170)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:149)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4LeakDetectionHandler.channelRead(Netty4LeakDetectionHandler.java:38)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:120)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpContentSizeHandler.handleRequest(Netty4HttpContentSizeHandler.java:150)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpContentSizeHandler.channelRead(Netty4HttpContentSizeHandler.java:106)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpAggregator.channelRead(Netty4HttpAggregator.java:52)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpHeaderValidator.forwardData(Netty4HttpHeaderValidator.java:213)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpHeaderValidator.forwardFullRequest(Netty4HttpHeaderValidator.java:156)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpHeaderValidator$1.lambda$onResponse$0(Netty4HttpHeaderValidator.java:128)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.transport@4.1.115.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.common@4.1.115.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[2025-01-23T09:44:59,735][WARN ][o.e.h.AbstractHttpServerTransport] [runTask-0] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/[0:0:0:0:0:0:0:1]:9200, remoteAddress=/[0:0:0:0:0:0:0:1]:51276} java.lang.Exception: java.lang.AssertionError
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.exceptionCaught(Netty4HttpPipeliningHandler.java:504)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4LeakDetectionHandler.channelRead(Netty4LeakDetectionHandler.java:38)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:120)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpContentSizeHandler.handleRequest(Netty4HttpContentSizeHandler.java:150)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpContentSizeHandler.channelRead(Netty4HttpContentSizeHandler.java:106)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpAggregator.channelRead(Netty4HttpAggregator.java:52)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.codec@4.1.115.Final/io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpHeaderValidator.forwardData(Netty4HttpHeaderValidator.java:213)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpHeaderValidator.forwardFullRequest(Netty4HttpHeaderValidator.java:156)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpHeaderValidator$1.lambda$onResponse$0(Netty4HttpHeaderValidator.java:128)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.transport@4.1.115.Final/io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.common@4.1.115.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.common@4.1.115.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.AssertionError
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.HttpBody.asFull(HttpBody.java:42)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestRequest.content(RestRequest.java:313)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestRequest.requiredContent(RestRequest.java:341)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.action.document.RestIndexAction.prepareRequest(RestIndexAction.java:109)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:99)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:466)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController$1.onResponse(RestController.java:460)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.doHandleRequest(SecurityRestFilter.java:89)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.lambda$intercept$0(SecurityRestFilter.java:81)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:257)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.lambda$authenticateAndAttachToContext$3(SecondaryAuthenticator.java:99)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:247)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticate(SecondaryAuthenticator.java:109)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.authc.support.SecondaryAuthenticator.authenticateAndAttachToContext(SecondaryAuthenticator.java:90)
	at org.elasticsearch.security@9.0.0-SNAPSHOT/org.elasticsearch.xpack.security.rest.SecurityRestFilter.intercept(SecurityRestFilter.java:75)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:460)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController.tryAllHandlers(RestController.java:624)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:307)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:488)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:584)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:461)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.handlePipelinedRequest(Netty4HttpPipeliningHandler.java:170)
	at org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT/org.elasticsearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:149)
	at io.netty.transport@4.1.115.Final/io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	... 31 more
```

If you do _NOT_ have assertions enabled, you get this response:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "class_cast_exception",
        "reason" : "class org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream cannot be cast to class org.elasticsearch.http.HttpBody$Full (org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream is in module org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT of loader jdk.internal.loader.Loader @3cd206b5; org.elasticsearch.http.HttpBody$Full is in module org.elasticsearch.server@9.0.0-SNAPSHOT of loader 'app')"
      }
    ],
    "type" : "class_cast_exception",
    "reason" : "class org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream cannot be cast to class org.elasticsearch.http.HttpBody$Full (org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream is in module org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT of loader jdk.internal.loader.Loader @3cd206b5; org.elasticsearch.http.HttpBody$Full is in module org.elasticsearch.server@9.0.0-SNAPSHOT of loader 'app')"
  },
  "status" : 500
}
```

And this in the logs:

```
[2025-01-23T10:36:14,458][WARN ][r.suppressed             ] [Pelennor] path: /logs-foo-bar/_doc/_bulk, params: {pretty=true, index=logs-foo-bar, id=_bulk}, status: 500java.lang.ClassCastException: class org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream cannot be cast to class org.elasticsearch.http.HttpBody$Full (org.elasticsearch.http.netty4.Netty4HttpRequestBodyStream is in module org.elasticsearch.transport.netty4@9.0.0-SNAPSHOT of loader jdk.internal.loader.Loader @3cd206b5; org.elasticsearch.http.HttpBody$Full is in module org.elasticsearch.server@9.0.0-SNAPSHOT of loader 'app')
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.http.HttpBody.asFull(HttpBody.java:43)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestRequest.content(RestRequest.java:313)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.RestRequest.requiredContent(RestRequest.java:341)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.action.document.RestIndexAction.prepareRequest(RestIndexAction.java:109)
	at org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:99)
```

### PR DESCRIPTION
**Pull request by mhl-b**
Netty HTTP content aggregator appears to be not flexible for our needs. In some cases, like bulk API we need to bypass aggregation, and Netty's aggregator does not have any memory safety, like backpressure or circuit breaker. That means we always aggregate requests fully and occasionally run OOM.

This change moves aggregation from the Netty module into Server module, RestController. That means in netty code we no longer deal with fully aggregated requests and everything is a stream of chunks. RestController aggregates chunks when RestHandler indicates that stream is not supported via new flag. Opens up opportunity to apply backpressure/circuit-breaker per chunk basis for all REST handlers. Also simplifies implementation of new streaming handlers.

Once RestHandler is resolved in RestController we check if it supports stream content. If stream is supported then request proceeds to the Handler. If stream is not supported a new RestContentAggregator aggregates chunks, then replaces content of the RestRequest with aggregated content.

PR touches many files but essentially changes are:
- Removal of Netty4HttpAggregator and Bulk API predicates from Netty pipeline.
- Addition of RestContentAggregator and support for HTTP content replacement.
- Adjusting integ tests in netty and security modules to consume stream (AggregatingDispatcher) and not leak buffers.

closes #120746

### CODE REVIEW

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java [hunk 1]
```diff
@@ -119,10 +91,18 @@ public HttpBody body() {
...
     }
 
+    @Override
+    public void setBody(HttpBody body) {
+        if (body.isFull()) {
+            var contentLength = body.asFull().bytes().length();
+            HttpUtil.setContentLength(nettyRequest, contentLength);
+        }
+        this.content = body;
+    }
```
Comment (mhl-b) [inline modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java]: Changing mutability for the HTTP request body, I need to swap stream with full content after aggregation. References to original HTTP request spread roots too deep.

File: server/src/main/java/org/elasticsearch/rest/RestController.java [hunk 2]
```diff
@@ -389,6 +391,32 @@ public Map<String, HttpRouteStats> getStats() {
...
+                var aggChannel = new DelegatingRestChannel(restChannel) {
+                    @Override
+                    public RestRequest request() {
+                        return aggregatedRequest;
+                    }
+                };
+                try {
+                    dispatchRequest(aggregatedRequest, aggChannel, handler, methodHandlers, threadContext);
+                } catch (Exception e) {
+                    assert false : "exception must be handled in dispatchRequest";
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/rest/RestController.java]: Should we log an error here just in case it somehow happens in prod?

File: server/src/main/java/org/elasticsearch/rest/RestRequestAggregator.java [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+                    chunks = new ArrayList<>(); // allocate array only when there is more than one chunk
+                }
+                chunks.add(chunk);
+                stream.next();
+            } else {
+                if (chunks == null) {
+                    replaceBody(restRequest, chunk);
+                    result.accept(restRequest);
+                } else {
+                    var comp = CompositeBytesReference.of(chunks.toArray(new ReleasableBytesReference[0]));
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/rest/RestRequestAggregator.java]: Is it worth making `new ReleasableBytesReference[0]` a constant to avoid the allocation? Or will the compiler be clever enough to do that I wonder.

File: server/src/main/java/org/elasticsearch/rest/RestRequestAggregator.java [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+import java.util.ArrayList;
+import java.util.function.Consumer;
+
+public class RestRequestAggregator {
+
+    private final CircuitBreakerService circuitBreakerService;
+
+    public RestRequestAggregator(CircuitBreakerService circuitBreakerService) {
+        this.circuitBreakerService = circuitBreakerService;
+    }
```
Comment (nicktindall) [inline server/src/main/java/org/elasticsearch/rest/RestRequestAggregator.java]: Nit: do we use the circuitBreakerService in here? it doesn't look like it

**Review by nicktindall — COMMENTED** [review]
Nice tidy up, I will leave to the other reviewers to approve because they have more context, but LGTM

File: server/src/main/java/org/elasticsearch/rest/RestRequestAggregator.java (hunk 3 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestRequestAggregator.java]: I think it is smart enough to skip extra allocation. It still allocates array of the list size. Would be nice to have `CompositeBytesReference.of(List<Chunks>)`.

File: server/src/main/java/org/elasticsearch/rest/RestRequestAggregator.java (hunk 4 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestRequestAggregator.java]: My intention was to include CB in this PR. So I've done basic plumbing. But scope of CB appears fairly large. I will leave it as it is. CB will work as before, we fully aggregate content and then try breaker.

File: modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpServerTransportTests.java [hunk 5]
```diff
@@ -863,20 +861,11 @@ public void dispatchBadRequest(final RestChannel channel, final ThreadContext th
...
-        final HttpValidator httpValidator = (httpRequest, channel, validationListener) -> {
-            // assert that the validator sees the request unaltered
-            assertThat(httpRequest.uri(), is(uri));
-            if (randomBoolean()) {
-                validationListener.onResponse(null);
-            } else {
-                validationListener.onFailure(new ElasticsearchException("Boom"));
-            }
-        };
         try (
```
Comment (mhl-b) [inline modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpServerTransportTests.java:864]: Before, oversized requests that fail auth will be rejected at netty aggregator with size exception. Right now it will go through to the RestController, controller will send a response based on auth exception and close(discard) stream.

I think it's ok to have Auth exception with higher precedence than content size. But I think there is a possibility for an evil request with extremely large content that will be discarded, but we want to close channel sooner, rather than discarding content. If we want to keep previous behaviour I need to adjust Netty4HttpContentSizeHandler.

**Comment by mhl-b** [comment]
@DaveCTurner CI has been happy last 3 runs, with minor test fixes. It's ready for review. I will address audit logging in following PR if this one passes.

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java [hunk 6]
```diff
@@ -998,6 +1000,15 @@ public static BytesReference randomBytesReference(int length) {
         return CompositeBytesReference.of(slices.toArray(BytesReference[]::new));
     }
 
+    public ReleasableBytesReference randomReleasableBytesReference(int length) {
+        return new ReleasableBytesReference(randomBytesReference(length), new AbstractRefCounted() {
+            @Override
+            protected void closeInternal() {
+
+            }
+        });
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]: Can we leak-track these things?

```suggestion
        return new ReleasableBytesReference(randomBytesReference(length), LeakTracker.wrap(AbstractRefCounted.of(() -> {})));
```

File: test/framework/src/main/java/org/elasticsearch/http/AggregatingDispatcher.java [hunk 7]
```diff
@@ -11,13 +11,16 @@
...
 import org.elasticsearch.rest.RestChannel;
+import org.elasticsearch.rest.RestContentAggregator;
 import org.elasticsearch.rest.RestRequest;
 
-public class NullDispatcher implements HttpServerTransport.Dispatcher {
+public class AggregatingDispatcher implements HttpServerTransport.Dispatcher {
 
-    @Override
-    public void dispatchRequest(RestRequest request, RestChannel channel, ThreadContext threadContext) {
+    public void dispatchAggregatedRequest(RestRequest restRequest, RestChannel restChannel, ThreadContext threadContext) {}
```
Comment (DaveCTurner) [inline test/framework/src/main/java/org/elasticsearch/http/AggregatingDispatcher.java]: Can we assert this?

```suggestion
    public void dispatchAggregatedRequest(RestRequest restRequest, RestChannel restChannel, ThreadContext threadContext) {
        assert restRequest.isStreamedContent() == false;
    }
```

File: server/src/main/java/org/elasticsearch/rest/RestRequest.java [hunk 8]
```diff
@@ -291,11 +291,18 @@ public final String path() {
...
 
+    /**
+     * Returns content length in bytes. If length is unknown, for example,
+     * streamed content with chunked transfer-encoding then returns -1.
+     */
     public int contentLength() {
-        return httpRequest.body().asFull().bytes().length();
+        return switch (httpRequest.body()) {
+            case HttpBody.Full content -> content.bytes().length();
+            case HttpBody.Stream stream -> Math.toIntExact(httpRequest.contentLengthHeader());
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/rest/RestRequest.java]: I'm suspicious about this, are you sure we need it? I'd rather we only exposed the length of an aggregated body. My worry is that code which is processing a streaming body shouldn't be dependent on the content length since it's not always available, but with this lenience we might end up not covering the unavailable-length case properly in tests.

File: server/src/main/java/org/elasticsearch/rest/RestController.java [hunk 9]
```diff
@@ -389,6 +389,27 @@ public Map<String, HttpRouteStats> getStats() {
...
+        ThreadContext threadContext
+    ) throws Exception {
+        if (handler.supportsContentStream()) {
+            dispatchRequest(restRequest, restChannel, handler, methodHandlers, threadContext);
+        } else {
+            RestContentAggregator.aggregate(restRequest, (aggregatedRequest) -> {
+                try {
+                    dispatchRequest(aggregatedRequest, restChannel, handler, methodHandlers, threadContext);
+                } catch (Exception e) {
+                    // dispatchRequest already handles exceptions, this time we wont be able to send response
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/rest/RestController.java]: I don't understand this comment. If `dispatchRequest` is expected not to throw anything, should we `assert false : e` here?

File: server/src/main/java/org/elasticsearch/rest/RestContentAggregator.java [hunk 10]
```diff
@@ -0,0 +1,99 @@
...
+    }
+
+    private static class AggregationChunkHandler implements HttpBody.ChunkHandler {
+        final RestRequest restRequest;
+        final Consumer<RestRequest> result;
+        final HttpBody.Stream stream;
+        boolean closing;
+        ArrayList<ReleasableBytesReference> chunks;
+
+        private AggregationChunkHandler(RestRequest restRequest, Consumer<RestRequest> result) {
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/rest/RestContentAggregator.java]: naming nit:

```suggestion
        private AggregationChunkHandler(RestRequest restRequest, Consumer<RestRequest> resultConsumer) {
```

File: server/src/main/java/org/elasticsearch/rest/RestContentAggregator.java [hunk 11]
```diff
@@ -0,0 +1,99 @@
...
+                }
+            }
+        }
+
+        @Override
+        public void close() {
+            if (closing == false) {
+                closing = true;
+                if (chunks != null) {
+                    Releasables.close(chunks);
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/rest/RestContentAggregator.java:87]: If closed mid-aggregation, do we need some way to notify the handler? Conversely, if we got to the end of the aggregation, could we release the chunks earlier? AIUI we close the request when starting to send the response, which seems much later than necessary.

File: server/src/main/java/org/elasticsearch/http/HttpRequest.java [hunk 12]
```diff
@@ -30,6 +30,10 @@ enum HttpVersion {
 
     HttpBody body();
 
+    default void setBody(HttpBody body) {
+        throw new UnsupportedOperationException("not implemented");
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/http/HttpRequest.java]: `assert false` here too? This'd be a bug right? Although there's only 4 implementing classes (plus a few subclasses) so I'd prefer not to have a `default` implementation.

File: server/src/main/java/org/elasticsearch/http/HttpPreRequest.java [hunk 13]
```diff
@@ -64,4 +64,23 @@ default String header(String name) {
...
+     * and can be assumed as zero length.
+     */
+    default long contentLengthHeader() {
+        var lenstr = header("Content-Length");
+        if (lenstr == null) {
+            var encoding = header("Transfer-Encoding");
+            if (encoding != null && encoding.equals("chunked")) {
+                return -1;
+            } else {
+                return 0;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/http/HttpPreRequest.java]: Is this true? What requests might not have a `Content-Length` or `Transfer-Encoding` header exactly? I thought that'd not be allowed in HTTP/1.1, and in HTTP/1.0 a request without a `Content-Length` header would have a body that is terminated by the connection close.

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java [hunk 14]
```diff
@@ -119,10 +91,18 @@ public HttpBody body() {
         return content;
     }
 
+    @Override
+    public void setBody(HttpBody body) {
+        if (body.isFull()) {
```
Comment (DaveCTurner) [inline modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java]: Can we assert that we only ever replace a streaming body with a fully-aggregated body?

**Review by DaveCTurner — COMMENTED** [review]
I like it. I haven't quite finished reviewing the changes in detail but have left some comments from my first pass through.

File: server/src/main/java/org/elasticsearch/rest/RestController.java (hunk 9 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestController.java]: Not well written by me. It's a bit tricky. `dispatchRequest` catches errors and tries to send error response. But sending error response might fail too, at least we have a test that does that by injecting failure into sendResponse path, not sure that production code can throw there. Failing to send response can only go to the error log. 
Cannot re-throw Exception without wrapping into RuntimeException but that mess up error handling. "Cannot" means the whole chain need to have throw Exception signature which is pretty large.

File: server/src/main/java/org/elasticsearch/rest/RestContentAggregator.java (hunk 11 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestContentAggregator.java:87]: > If closed mid-aggregation, do we need some way to notify the handler?

I don't think so. Handlers that handle whole content shouldn't bother about incomplete requests. Thats the whole point of aggregation, keep it simple downstream, right?

> Conversely, if we got to the end of the aggregation, could we release the chunks earlier?

We release chunks at `prepareRequest`, if you remember we changed that few months ago https://github.com/elastic/elasticsearch/commit/7aa07f1a2a34c2bdf73863f51485616d598bc7e7. This close handler is for premature termination.

File: server/src/main/java/org/elasticsearch/http/HttpPreRequest.java (hunk 13 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/http/HttpPreRequest.java]: > What requests might not have a Content-Length or Transfer-Encoding header exactly?

For example GET request without body is allowed to not have either.

https://www.rfc-editor.org/rfc/rfc9110.html#section-8.6-5

>A user agent SHOULD NOT send a Content-Length header field when the request message does not contain content and the method semantics do not anticipate such data.

This if-condition might not be very precise, but it's practical. When `Transfer-Encoding` is present it is very likely `chunked`. And in this case `Content-Length` should be omitted. But if none of them present it should be zero length content.

File: server/src/main/java/org/elasticsearch/rest/RestRequest.java (hunk 8 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestRequest.java]: Agree. This is only used for the circuit breaker estimation. I can remove whole content-length changes, I don't think it's essential for this PR.

File: server/src/main/java/org/elasticsearch/rest/RestController.java (hunk 9 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestController.java]: Looking at this again, wrapping into RuntimeException might be a right thing to do. Let it bubble up to the pipelining http error handler. This will properly close channel.

File: server/src/main/java/org/elasticsearch/rest/RestContentAggregator.java (hunk 11 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestContentAggregator.java:92]: > do we need some way to notify the handler?

But this might be a good case for cancelation, when client closes channel after sending request but before getting response. I wouldnt do this in this PR, but stream content has right parts in place to propagate cancellation signal.

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java [hunk 15]
```diff
@@ -119,10 +90,14 @@ public HttpBody body() {
         return content;
     }
 
+    @Override
+    public void setBody(HttpBody body) {
+        this.content = body.asFull();
```
Comment (mhl-b) [inline modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java]: `body.asFull();` includes assertion

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java (hunk 6 above)
Comment (mhl-b) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java]:
```
:)

        return new ReleasableBytesReference(randomBytesReference(length), LeakTracker.wrap(new AbstractRefCounted() {
            @Override
            protected void closeInternal() {}
        }));
```

File: server/src/main/java/org/elasticsearch/rest/RestRequest.java (hunk 8 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestRequest.java]: Removed content-length changes https://github.com/elastic/elasticsearch/pull/129302/commits/c7bb93004c97bf60e85102b6717f8cf2a1f77ca5

File: server/src/main/java/org/elasticsearch/rest/RestController.java (hunk 9 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestController.java]: Rethrow exception https://github.com/elastic/elasticsearch/pull/129302/commits/43bf06a509d21563f67201823fef37308601754c

File: server/src/main/java/org/elasticsearch/rest/RestRequest.java (hunk 8 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/rest/RestRequest.java]: Added `hasContent` to the HTTP request, we need to know if content is present before aggregation happens, so I'm keeping logic for headers check. https://github.com/elastic/elasticsearch/pull/129302/commits/34e8881e7c5ad2b0f99b39364a361719bf525f3f

File: server/src/main/java/org/elasticsearch/http/HttpPreRequest.java (hunk 13 above)
Comment (mhl-b) [reply server/src/main/java/org/elasticsearch/http/HttpPreRequest.java]: Replaced with hasContent https://github.com/elastic/elasticsearch/pull/129302/commits/34e8881e7c5ad2b0f99b39364a361719bf525f3f

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java (hunk 15 above)
Comment (DaveCTurner) [reply modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java]: Sure, but can we also check that `this.content` is not already a fully-aggregated body?

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java [hunk 16]
```diff
@@ -131,33 +130,28 @@ public void channelRead(final ChannelHandlerContext ctx, final Object msg) {
...
-                if (msg instanceof LastHttpContent) {
-                    currentRequestStream = null;
-                }
             }
         } finally {
             if (shouldRead) {
                 ctx.channel().eventLoop().execute(ctx::read);
             }
+            if (msg instanceof LastHttpContent) {
+                currentRequestStream = null;
```
Comment (DaveCTurner) [inline modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpPipeliningHandler.java:150]: readability nit: this has to happen before the `ctx::read` above; of course it does today because we're already on the event loop so the dispatched `ctx::read` happens after this method returns but still it's confusing to write them in this order.

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java [hunk 17]
```diff
@@ -41,71 +38,57 @@
...
+    public Netty4HttpRequest(int sequence, io.netty.handler.codec.http.HttpRequest nettyRequest, HttpBody content) {
+        this(sequence, nettyRequest, content, new AtomicBoolean(false), null);
     }
 
-    private Netty4HttpRequest(int sequence, FullHttpRequest request, AtomicBoolean released, boolean pooled, HttpBody content) {
-        this(sequence, request, released, pooled, content, null);
-    }
-
-    private Netty4HttpRequest(
+    public Netty4HttpRequest(
```
Comment (DaveCTurner) [inline modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpRequest.java]: nit: probably a mistake to expose the `released` flag to the public

```suggestion
    private Netty4HttpRequest(
```

File: modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java [hunk 18]
```diff
@@ -411,8 +396,8 @@ protected boolean isContentAlwaysEmpty(HttpResponse msg) {
                         }
                         return super.isContentAlwaysEmpty(msg);
                     }
-                })
-                .addLast("aggregator", aggregator);
+                });
+            ch.pipeline().addLast(new Netty4HttpContentSizeHandler(decoder, handlingSettings.maxContentLength()));
```
Comment (DaveCTurner) [inline modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpServerTransport.java]: nit: may as well carry on chaining the `addLast` calls

```suggestion
                })
                .addLast(new Netty4HttpContentSizeHandler(decoder, handlingSettings.maxContentLength()));
```

File: server/src/main/java/org/elasticsearch/rest/RestRequest.java [hunk 19]
```diff
@@ -291,11 +291,14 @@ public final String path() {
...
     public boolean hasContent() {
-        return isStreamedContent() || contentLength() > 0;
+        return httpRequest.hasContent();
     }
 
     public int contentLength() {
-        return httpRequest.body().asFull().bytes().length();
+        return switch (httpRequest.body()) {
+            case HttpBody.Full content -> content.bytes().length();
+            case HttpBody.Stream stream -> 0;
```
Comment (DaveCTurner) [inline server/src/main/java/org/elasticsearch/rest/RestRequest.java]: I still think this is trappy, I'd much prefer it remained an error to call `contentLength` on a streaming request.

File: server/src/test/java/org/elasticsearch/rest/RestContentAggregatorTests.java [hunk 20]
```diff
@@ -0,0 +1,112 @@
...
+                Map.of("Content-Length", List.of(Integer.toString(size))),
+                HttpBody.fromBytesReference(randomBytesReference(size))
+            ),
+            new FakeHttpChannel(null)
+        );
+    }
+
+    public void testFullBodyPassThrough() {
+        var fullRequest = newRestRequest(between(1, 1024));
+        aggregate(fullRequest, (aggregated) -> assertEquals(fullRequest.content(), aggregated.content()));
```
Comment (DaveCTurner) [inline server/src/test/java/org/elasticsearch/rest/RestContentAggregatorTests.java]: We need to assert that the consumer is invoked, otherwise this will pass if `aggregate` doesn't. Also can we `assertSame`?

**Review by DaveCTurner — COMMENTED** [review]
One further comment on supporting `contentLength()` on a streaming request, and a few nits, otherwise this looks good to go.

**Review by DaveCTurner — APPROVED** [review]
LGTM
