### PR TITLE
[Test] Wait for cancellation before assertions

### LINKED ISSUE #134277: [CI] TransportNodesActionTests testConcurrentlyCompletionAndCancellation failing
**Build Scans:**
- [elasticsearch-periodic #10668 / encryption-at-rest](https://gradle-enterprise.elastic.co/s/2cotaq4r3nhko)
- [elasticsearch-periodic-platform-support #10658 / ubuntu-2204_platform-support-unix](https://gradle-enterprise.elastic.co/s/cq3tnzj6h5qqs)
- [elasticsearch-periodic-platform-support #10658 / debian-12_platform-support-unix](https://gradle-enterprise.elastic.co/s/qakedo776shms)
- [elasticsearch-periodic-platform-support #10652 / almalinux-8-aarch64_checkpart1_platform-support-arm](https://gradle-enterprise.elastic.co/s/whe55hfyhfvf2)
- [elasticsearch-periodic #10662 / concurrent-search-tests](https://gradle-enterprise.elastic.co/s/bjg43ir7hhqwe)
- [elasticsearch-periodic-platform-support #10652 / oraclelinux-9_platform-support-unix](https://gradle-enterprise.elastic.co/s/z3uxvk3mc45fa)
- [elasticsearch-pull-request #92622 / part-1](https://gradle-enterprise.elastic.co/s/f7sefoj2xnwdm)
- [elasticsearch-periodic-platform-support #10646 / debian-11_platform-support-unix](https://gradle-enterprise.elastic.co/s/6kpco42blspee)
- [elasticsearch-periodic #10638 / openjdk21_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/4xhwes6wxkybw)
- [elasticsearch-periodic-platform-support #10628 / oraclelinux-8_platform-support-unix](https://gradle-enterprise.elastic.co/s/gfex4vukbmvny)

**Reproduction Line:**
```
./gradlew ":server:test" --tests "org.elasticsearch.action.support.nodes.TransportNodesActionTests.testConcurrentlyCompletionAndCancellation" -Dtests.seed=FECA503F5B5CC7A1 -Dtests.locale=es-UY -Dtests.timezone=Europe/Andorra -Druntime.java=24
```

**Applicable branches:**
8.19

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.action.support.nodes.TransportNodesActionTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testConcurrentlyCompletionAndCancellation'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: null
```

**Issue Reasons:**
- [8.19] 2 consecutive failures in test testConcurrentlyCompletionAndCancellation
- [8.19] 31 failures in test testConcurrentlyCompletionAndCancellation (4.4% fail rate in 709 executions)
- [8.19] 2 failures in step encryption-at-rest (9.5% fail rate in 21 executions)
- [8.19] 2 failures in step ubuntu-2204_platform-support-unix (9.5% fail rate in 21 executions)
- [8.19] 2 failures in step debian-12_platform-support-unix (9.5% fail rate in 21 executions)
- [8.19] 3 failures in step oraclelinux-8_platform-support-unix (15.0% fail rate in 20 executions)
- [8.19] 2 failures in step sles-12_platform-support-unix (10.0% fail rate in 20 executions)
- [8.19] 3 failures in step almalinux-9_platform-support-unix (15.0% fail rate in 20 executions)
- [8.19] 2 failures in step part-1 (5.0% fail rate in 40 executions)
- [8.19] 2 failures in step graalvm-ce17_checkpart1_java-matrix (10.0% fail rate in 20 executions)
- [8.19] 3 failures in step almalinux-8-aarch64_checkpart1_platform-support-arm (15.0% fail rate in 20 executions)
- [8.19] 3 failures in step concurrent-search-tests (15.0% fail rate in 20 executions)
- [8.19] 2 failures in step debian-11_platform-support-unix (10.0% fail rate in 20 executions)
- [8.19] 8 failures in pipeline elasticsearch-periodic (38.1% fail rate in 21 executions)
- [8.19] 14 failures in pipeline elasticsearch-periodic-platform-support (66.7% fail rate in 21 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
Resolves: #134277

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java [hunk 1]
```diff
@@ -414,6 +421,11 @@ public void testConcurrentlyCompletionAndCancellation() throws InterruptedExcept
             assertNotNull("expect task cancellation exception, but got\n" + ExceptionsHelper.stackTrace(e), taskCancelledException);
             assertThat(e.getMessage(), containsString("task cancelled [simulated]"));
             assertTrue(cancellableTask.isCancelled());
+            // Wait for the latch, the listener for releasing node responses is called before it.
+            // We need to wait for the latch because the cancellation may be detected in CancellableFanOut#onCompletion with
+            // the responseHandled flag being true. The flag is set by the cancellation listener which is still in process of
+            // draining existing responses.
+            safeAwait(onCancelledLatch);
```
Comment (ywangd) [inline server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java:428]: It turns out we still need the latch. It was actually part of the original issue, i.e. the cancellation can comes in after all node responses are collected and right before the final response is sent. In this case, the final response is short circuited to be an exception while the cancellation listener is still doing work.

Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java:428]: Hmm ok I think I see, so you mean the final response can be sent in between these two lines:

https://github.com/elastic/elasticsearch/blob/a59c182f9f7e9d1bf3d6eecbc0e44f24ff91d053/server/src/main/java/org/elasticsearch/action/support/CancellableFanOut.java#L78-L80

On reflection this seems kinda surprising if not an outright bug: we generally prefer to delay sending the response until everything is released.

Comment (ywangd) [reply server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java:428]: Not the above lines. The final response (cancellation) can be sent at this line

https://github.com/elastic/elasticsearch/blob/6884dbb9b6a98170a1d041f5596070496b107783/server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java#L179

before the node responses are released by this line

https://github.com/elastic/elasticsearch/blob/6884dbb9b6a98170a1d041f5596070496b107783/server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java#L120

A potential alternative fix is to add a similar synchronized block to drain node responses right before the first line linked above. What do you think?

Comment (DaveCTurner) [reply server/src/test/java/org/elasticsearch/action/support/nodes/TransportNodesActionTests.java:428]: Ah yeah sorry this is all quite a tangle. I don't think it'll work to drain responses in `onCompletion` - we could already have drained them in the listener within `addReleaseOnCancellationListener` but still not quite released them yet.

On reflection it looks like there's other ways we can complete the final listener before releasing all the node-level responses, e.g. here:

https://github.com/elastic/elasticsearch/blob/74fd66c1f19314d46525b6ec515606f094d86466/server/src/main/java/org/elasticsearch/action/support/nodes/TransportNodesAction.java#L171-L173

Let's leave this alone then; I appreciate the comment in the test calling out that this is slightly odd.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.1|[](https://github.com/elastic/elasticsearch/pull/134866)|
|✅|9.0|[](https://github.com/elastic/elasticsearch/pull/134867)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/134868)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
