### PR TITLE
[ML] checking if p-tasks metadata is null before updating state

### LINKED ISSUE #41090: Error upgrading from (<= 6.5) to 6.7.x
While upgrading from version 6.5.x (or a previous version) to 6.7.x, there is a bug that puts a `null` value into the cluster metadata state in certain situations. 

If there exists any ML Anomaly jobs or Datafeeds and there are NO persistent tasks in the cluster state, then the ml config migration process puts a `null` value into the the new cluster state and attempts to update the state. This, of course, fails as the Diff check sees the null value and throws an NPE. 

This issue can be worked around in any of the following ways:
* Delete Jobs and datafeeds
* Set the cluster setting `xpack.ml.enable_config_migration` to `false`. It is a dynamic setting.
* Open any ML job so that a persistent task gets created. 

before setting `xpack.ml.enable_config_migration: true` again, the jobs either need to be deleted, or open one of the jobs. That will then allow the migration to take place.

### PR DESCRIPTION
**Pull request by benwtrent**
If `PersistentTasksCustomMetaData.TYPE` is null, we would put a `null` value in the cluster state, which will fail the `submitStateUpdateTask`.

This does a `null` check to verify it is non-null before adding it to the metadata. All of the other methods in the class that interact with a `PersistentTasksCustomMetaData` already do a null check

closes #41090

### CODE REVIEW

**Review by dimitris-athanasiou — COMMENTED** [review]
Looks good. I am not sure if this is testable, but if it is it would be nice to add a unit test that fails without the fix.

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/integration/MlConfigMigratorIT.java [hunk 1]
```diff
@@ -149,9 +152,14 @@ public void testMigrateConfigs() throws InterruptedException, IOException {
                 .routingTable(routingTable.build())
                 .build();
         when(clusterService.state()).thenReturn(clusterState);
-
+        List<MetaData.Custom> customs = new ArrayList<>();
         doAnswer(invocation -> {
                 ClusterStateUpdateTask listener = (ClusterStateUpdateTask) invocation.getArguments()[1];
+                ClusterState result = listener.execute(clusterState);
+                System.out.println(result);
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/integration/MlConfigMigratorIT.java]: herp derp :(

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM
