### PR TITLE
Continue registering pipelines after one pipeline parse failure.

### LINKED ISSUE #28269: [Ingest] Ingest Node cannot find pipeline that exists
I ran into an issue, which I cannot reproduce, where a set of ingest nodes were complaining that they could not find an ingest pipeline during an ordinary `_bulk` request that used it. This followed a single node cluster being upgraded from 6.1.1 to 6.1.2 by adding a new node, then decommissioning the old node. While trying to debug the issue, two other nodes were added, which were also ingest nodes.

I **was** able to see the Ingest pipeline by requesting it directly:

```http
GET /_ingest/pipeline/xpack_monitoring_6
```

as well as via the cluster state:

```http
GET /_cluster/state/metadata?filter_path=metadata.ingest.pipeline
```

In both cases, it returned the expected ingest pipeline:

```json
{
  "xpack_monitoring_6": {
    "description": "This is a placeholder pipeline for Monitoring API version 6 so that future versions may fix breaking changes.",
    "version": 6010099,
    "processors": []
  }
}
```

### Workaround

Fixing the issue was simple, but it's unclear what was actually wrong. Simply delete, then replace the exact same ingest pipeline with the same name (it's possible that the `DELETE` step is unnecessary):

```http
DELETE /_ingest/pipeline/xpack_monitoring_6

PUT /_ingest/pipeline/xpack_monitoring_6
{
  "description": "This is a placeholder pipeline for Monitoring API version 6 so that future versions may fix breaking changes.",
  "version": 6010099,
  "processors": []
}
```

From that point onward it began to work.

### PR DESCRIPTION
**Pull request by talevy**
Ingest has been failing to apply existing pipelines from cluster-state
into the in-memory representation that are no longer valid. One example of
this is a pipeline with a script processor. If a cluster starts up with scripting
disabled, these pipelines will not be loaded. Even though GETing a pipeline worked,
indexing operations claimed that this pipeline did not exist. This is because one
gets information from cluster-state and the other is from an in-memory data-structure.

Now, two things happen
1. suppress the exceptions until after other successfull pipelines are loaded
2. replace failed pipelines with a placeholder pipeline that carries the exception message 
in its description

If the pipeline execution service encounters a pipeline stub, it is known that
something went wrong at the time of pipeline creation and an exception was thrown to
the user at some point at start-up.

closes #28269.

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/ingest/PipelineStore.java [hunk 1]
```diff
@@ -81,16 +81,20 @@ void innerUpdatePipelines(ClusterState previousState, ClusterState state) {
         }
 
         Map<String, Pipeline> pipelines = new HashMap<>();
+        ArrayList<ElasticsearchParseException> exceptions = new ArrayList<>();
         for (PipelineConfiguration pipeline : ingestMetadata.getPipelines().values()) {
             try {
                 pipelines.put(pipeline.getId(), factory.create(pipeline.getId(), pipeline.getConfigAsMap(), processorFactories));
             } catch (ElasticsearchParseException e) {
-                throw e;
+                pipelines.put(pipeline.getId(), Pipeline.EMPTY);
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: I wonder if we can create a pipeline with a single `fail` processor. This fail processor can then contain the reason why the pipeline in question couldn't be loaded. This way there is no need to check the logs.

**Review by martijnvg — COMMENTED** [review]
This looks good @talevy! I left a suggestion on how to improve handeling these pipeline construction errors.

File: server/src/main/java/org/elasticsearch/ingest/PipelineStore.java (hunk 1 above)
Comment (talevy) [reply server/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: I like this, but I will try to do this in such a way that the pipeline isn't actually executed and is only used to store the exception. If I can't find a way to cleanly do that, then I will just let the pipeline run and fail

Comment (talevy) [reply server/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: ah, also, `fail` processor is inside `ingest-common` so that makes it slightly more annoying

**Comment by talevy** [comment]
@martijnvg I've updated to carry the exception's message and pass it on to the user at runtime. good call — way better than telling them to look at logs.

**Comment by talevy** [comment]
@elasticmachine please test this

**Comment by talevy** [comment]
jenkins test this please

**Comment by talevy** [comment]
@elasticmachine test this please

File: server/src/main/java/org/elasticsearch/ingest/PipelineStore.java [hunk 2]
```diff
@@ -81,16 +81,22 @@ void innerUpdatePipelines(ClusterState previousState, ClusterState state) {
         }
 
         Map<String, Pipeline> pipelines = new HashMap<>();
+        ArrayList<ElasticsearchParseException> exceptions = new ArrayList<>();
         for (PipelineConfiguration pipeline : ingestMetadata.getPipelines().values()) {
             try {
                 pipelines.put(pipeline.getId(), factory.create(pipeline.getId(), pipeline.getConfigAsMap(), processorFactories));
             } catch (ElasticsearchParseException e) {
-                throw e;
+                pipelines.put(pipeline.getId(), new Pipeline("invalid_" + pipeline.getId(), e.getMessage(),
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: what if we create a pipeline that throws the exception for us (fail processor is in a ingest-common, but it very simple to have that behaviour here too):

```java
pipelines.put(pipeline.getId(), substitutePipeline(pipeline.getId(), e));

private Pipeline substitutePipeline(String id, ElasticsearchParseException e) {
        String tag = e.getHeaderKeys().contains("processor_tag") ? e.getHeader("processor_tag").get(0) : null;
        String type = e.getHeaderKeys().contains("processor_type") ? e.getHeader("processor_type").get(0) : "unknown";
        String errorMessage = e.getDetailedMessage();
        Processor failureProcessor = new AbstractProcessor(tag) {
            @Override
            public void execute(IngestDocument ingestDocument) throws Exception {
                throw new IllegalStateException(errorMessage);
            }

            @Override
            public String getType() {
                return type;
            }
        };
        String description = "this is a place holder pipeline, because pipeline with id [" +  id + "] could not be loaded";
        return new Pipeline(id, description, null, new CompoundProcessor(failureProcessor));
    }
```

This way the if statement added `PipelineExecutionService.java` is not needed and this failure to load logic is in one place.

File: server/src/main/java/org/elasticsearch/ingest/PipelineStore.java [hunk 3]
```diff
@@ -81,16 +81,22 @@ void innerUpdatePipelines(ClusterState previousState, ClusterState state) {
         }
 
         Map<String, Pipeline> pipelines = new HashMap<>();
+        ArrayList<ElasticsearchParseException> exceptions = new ArrayList<>();
```
Comment (martijnvg) [inline server/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: s/ArrayList<ElasticsearchParseException>/List<ElasticsearchParseException> ?

**Review by martijnvg — COMMENTED** [review]
@talevy Cool! I left an additional suggestion on how to improve the error handling.

File: server/src/main/java/org/elasticsearch/ingest/PipelineStore.java (hunk 2 above)
Comment (martijnvg) [reply server/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: Note, I updated the above comment.

Also I think it is important to throw an IllegalStateException instead of a IllegalArgumentException, because the fact that we failed to load the pipeline at this stage is a real issue and this is the best way we can deal with it?

Comment (talevy) [reply server/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: The problem with this approach is that we will be put these substituted pipelines in PUT requests.

this will return true: https://github.com/elastic/elasticsearch/pull/28752/files#diff-fd6036d9f6ce14fecb8751a3adb9fc59R280

Comment (talevy) [reply server/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: hmm. nevermind.. for some reason I saw that test fail. I might have done something wrong or a different test failed

File: server/src/main/java/org/elasticsearch/ingest/PipelineStore.java (hunk 3 above)
Comment (talevy) [reply server/src/main/java/org/elasticsearch/ingest/PipelineStore.java]: updated

**Comment by talevy** [comment]
@martijnvg I've updated the PR to reflect your suggestion around inserting a placeholder pipeline that fails during execution

**Review by martijnvg — APPROVED** [review]
LGTM!

(The build only failed, because of a checkstyle violation)

Also I think we should backport this to the 5.6 branch. wdyt?

**Comment by talevy** [comment]
@martijnvg Once I merge into 6.x and master, I'll see how the backport looks for 5.6
