### PR TITLE
Fix sort on nanosecond date fields with missing values

### LINKED ISSUE #73763: Sorting descending on datefield with nanosecond-precision fails for missing values
**Elasticsearch version**: 7.13.1 (newest)

**Plugins installed**: None

**JVM version**: ES builtin,
openjdk 16 2021-03-16
OpenJDK Runtime Environment AdoptOpenJDK (build 16+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 16+36, mixed mode, sharing)

**OS version**: Windows 10, 64bit, version 2004, build 19041.985 

**Steps to reproduce**:
```
POST _bulk
{"index":{"_index":"test","_id":"1"}}
{"field1":"value1", "timestamp": "2021-06-04T13:50:00.000000001"}
{"index":{"_index":"test","_id":"2"}}
{"field1":"value2"}
```
And the query
```
GET test/_search
{
  "sort": {
    "timestamp": {
      "order": "desc",
      "format": "strict_date_optional_time_nanos",
      "numeric_type": "date_nanos"
    }
  }
}
```
**Expected behaviour**
I'd expect both docs to be returned without errors (first doc1, then doc2 with a missing timestamp)

**Actual behaviour**
```
{
  "error" : {
    "root_cause" : [ ],
    "type" : "search_phase_execution_exception",
    "reason" : "",
    "phase" : "fetch",
    "grouped" : true,
    "failed_shards" : [ ],
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "nanoseconds [-9223372036854775808] are before the epoch in 1970 and cannot be processed in nanosecond resolution"
    }
  },
  "status" : 400
}
```
**Observations**
- The error does not occur when sorting ascending, or including `"missing": "_first"` in the sort
- However, it *does* occur when sorting ascending *and* including `"missing": "_first"` in the sort
- When not specifying a format, no error occurs. However, this is tricky with a search_after (see https://www.elastic.co/guide/en/elasticsearch/reference/7.13/paginate-search-results.html#search-after)

My guess would be that missing values are filled in with a value "before any possible value" (to be first for ascending order, or last in descending order), but that this subsequently fails when showing as a formatted date.

### PR DESCRIPTION
**Pull request by cbuescher**
For missing values on date fields we use Long.MIN_VALUE by default. This is okay
when the resolution of the field is milliseconds. For nanoseconds though,
negative values can lead to IllegalArgumentExpections when we try to format them
internally.
This change fixes this by explicitely setting the minimum value to 0L (which
corresponds to 1970-01-01T00:00:00.000 for nanosecond resolution) when no other
explicit missing value is defined and the target numeric type is a nanosecond
type (this is true for nanosecond fields and when "numeric_type" is explicitely
set). This way we correct the behaviour for single typed indices and cases where
we are sorting across multiple indices with mixed "date" and "date_nanos" type
where "numeric_type" is set in the sort definition.

Closes #73763

### CODE REVIEW

**Comment by cbuescher** [comment]
@elasticmachine update branch

File: server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java [hunk 1]
```diff
@@ -83,6 +86,13 @@ public final SortField sortField(
         Nested nested,
         boolean reverse
     ) {
+        if (targetNumericType == NumericType.DATE_NANOSECONDS) {
+            // explicitly set missingValue if not set yet to prevent negative values that would cause invalid nanosecond range
+            if (sortMissingFirst(missingValue) || sortMissingLast(missingValue)) {
+                final boolean min = sortMissingFirst(missingValue) ^ reverse;
+                missingValue = min ? 0L : Long.MAX_VALUE;
+            }
+        }
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java:95]: This logic could move to `IndexNumericFieldData#missingObject` ? `IndexFieldData#missingObject` doesn't need to be final, we need to pick the value depending on the `targetNumericType`.

File: server/src/internalClusterTest/java/org/elasticsearch/search/sort/FieldSortIT.java [hunk 2]
```diff
@@ -868,6 +868,142 @@ public void testSortMissingStrings() throws IOException {
...
+                String format = null;
+                if (withFormat) {
+                    format = "strict_date_optional_time_nanos";
+                }
+
+                String index = "test*";
+                SearchResponse searchResponse = client().prepareSearch(index)
+                    .addSort(SortBuilders.fieldSort("mydate").order(SortOrder.ASC).setFormat(format).setNumericType("date_nanos"))
+                    .get();
+                assertHitsInOrder(searchResponse, new String[] { "1", "2", "4", "5", "3", "6" });
```
Comment (jimczi) [inline server/src/internalClusterTest/java/org/elasticsearch/search/sort/FieldSortIT.java:966]: A tiebreaker should be used to ensure that `3` is always sorted before `6` (same value otherwise).

File: server/src/internalClusterTest/java/org/elasticsearch/search/sort/FieldSortIT.java [hunk 3]
```diff
@@ -868,6 +868,142 @@ public void testSortMissingStrings() throws IOException {
...
+                searchResponse = client().prepareSearch(index)
+                    .addSort(
+                        SortBuilders.fieldSort("mydate")
+                            .order(SortOrder.ASC)
+                            .missing("_first")
+                            .setFormat(format)
+                            .setNumericType("date_nanos")
+                    )
+                    .get();
+                assertHitsInOrder(searchResponse, new String[] { "3", "6", "1", "2", "4", "5" });
```
Comment (jimczi) [inline server/src/internalClusterTest/java/org/elasticsearch/search/sort/FieldSortIT.java:977]: Same here

**Review by jimczi — CHANGES_REQUESTED** [review]
I left some comments.

File: server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java (hunk 1 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java:95]: I looked into this a bit and one problem is that I couldn't solve with this is that "missingObject" is part of `XFieldComparatorSource`, not `IndexFieldData`. That probably woudl mean overwriting it in special versions of LongValuesComparatorSource, and for the things I tried it wasn't always clear how to ther the "targetNumericType" from the sort (e.g. reduceType() returns `SortField.Type` that doesn't even differentiate between Long, Data and Datenanos like `IndexNumericFieldData.NumericType` does). Maybe I'm missing something but from what I tried this current location seems less complex to me.

**Comment by cbuescher** [comment]
@jimczi thanks for the review, I improved the tests and left a comment regarding moving the implementation logic elsewhere and the problems I encountered. If you have other suggestions please let me know, otherwise I hope its also okay if we leave it where it is.

File: server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java (hunk 1 above)
Comment (jimczi) [reply server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java:95]: The `targetNumericType` could be added to the `LongValuesSource` and checked in `missingObject` ? It's not really about complexity here, `missingObject` is called in several contexts so it needs a fix.

**Comment by cbuescher** [comment]
@jimczi I pushed another commit that adresses your latest comment, should be ready for another look I think

File: server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java [hunk 4]
```diff
@@ -151,21 +151,38 @@ private XFieldComparatorSource comparatorSource(
...
+        return new LongValuesComparatorSource(this, missingValue, sortMode, nested, targetNumericType);
     }
 
-    protected XFieldComparatorSource dateNanosComparatorSource(@Nullable Object missingValue, MultiValueMode sortMode, Nested nested) {
-        return new LongValuesComparatorSource(this, missingValue, sortMode, nested, dvs -> convertNumeric(dvs, DateUtils::toNanoSeconds));
+    protected XFieldComparatorSource dateNanosComparatorSource(
+        @Nullable Object missingValue,
+        MultiValueMode sortMode,
+        Nested nested,
+        NumericType targetNumericType
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java:176]: The targetNumericType is implicit here ?

File: server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java [hunk 5]
```diff
@@ -151,21 +151,38 @@ private XFieldComparatorSource comparatorSource(
...
         }
     }
 
-    protected XFieldComparatorSource dateComparatorSource(@Nullable Object missingValue, MultiValueMode sortMode, Nested nested) {
-        return new LongValuesComparatorSource(this, missingValue, sortMode, nested);
+    protected XFieldComparatorSource dateComparatorSource(
+        @Nullable Object missingValue,
+        MultiValueMode sortMode,
+        Nested nested,
+        NumericType targetNumericType
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/fielddata/IndexNumericFieldData.java:167]: The `targetNumericType` is implicit here, no need to add it.

File: server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java [hunk 6]
```diff
@@ -128,4 +131,16 @@ protected long docValue() {
...
         };
     }
+
+    @Override
+    public Object missingObject(Object missingValue, boolean reversed) {
+        if (targetNumericType == NumericType.DATE_NANOSECONDS) {
+            // special case to prevent negative values that would cause invalid nanosecond ranges
+            if (sortMissingFirst(missingValue) || sortMissingLast(missingValue)) {
+                final boolean min = sortMissingFirst(missingValue) ^ reversed;
+                return min ? 0L : Long.MAX_VALUE;
```
Comment (jimczi) [inline server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java:141]: We should use `DateUtils#MAX_NANOSECOND_INSTANT` as the max

**Review by jimczi — APPROVED** [review]
I left some minor comments, LGTM otherwise

File: server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java (hunk 6 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java]: We need the converted nanoseconds value of that Instant though I think, which should be the same as Long.MAX_VALUE? I introduced another constant (https://github.com/elastic/elasticsearch/pull/74760/commits/8c6df4892fe8c7244f78289c796f06b7610888d0#diff-09ba5f62fc8de8923f01213874ef48657920b2cc1428ff4f27f5f06169ee8f1aR207) in my last commit to not have to do that coversion every time, just if you want to check.

**Comment by cbuescher** [comment]
@elasticmachine update branch
