### PR TITLE
Clarified fielddata not supported for text fields error message

### LINKED ISSUE #89485: Enhancement of "Text fields are not optimised for operations ..." log message
### Description

Users may see the below log message under various circumstances,

> https://github.com/elastic/elasticsearch/blob/v8.3.3/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java#L899-L906
> Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [FIELD_NAME] in order to load field data by uninverting the inverted index. Note that this can use significant memory.

as people seem to have mentioned this message in [Elasticsearch](https://github.com/elastic/elasticsearch/issues?q=is%3Aissue+%22Text+fields+are+not+optimised+for+operations%22+), [Kibana](https://github.com/elastic/kibana/issues?q=is%3Aissue+%22Text+fields+are+not+optimised+for+operations%22+), and [Beats](https://github.com/elastic/beats/issues?q=is%3Aissue+%22Text+fields+are+not+optimised+for+operations%22+) GH issues as well as at [forums](https://discuss.elastic.co/search?q=%22Text%20fields%20are%20not%20optimised%20for%20operations%22).

I don't intend to suggest revise of this well-known message but want to propose an insertion of contextual information - i.e. field and index name to clarify where to start troubleshooting at a glance.

**Proposal**

```diff
diff --git a/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java b/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
index 045be484f09..74df90ffc0f 100644
--- a/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
+++ b/server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java
@@ -909,7 +909,8 @@ public class TextFieldMapper extends FieldMapper {
             } else if (operation == FielddataOperation.SEARCH) {
                 if (fielddata == false) {
                     throw new IllegalArgumentException(
-                        "Text fields are not optimised for operations that require per-document "
+                        "Field data is disabled on [" + name() + "] in [" + fieldDataContext.fullyQualifiedIndexName() + "]. "
+                            + "Text fields are not optimised for operations that require per-document "
                             + "field data like aggregations and sorting, so these operations are disabled by default. Please use a "
                             + "keyword field instead. Alternatively, set fielddata=true on ["
                             + name()
```

If this proposal sounds reasonable, please let me know, and I will open PRs accordingly. Thanks.

### PR DESCRIPTION
**Pull request by sakurai-youhei**
Clarify where to start troubleshooting on IllegalArgumentException by telling the field and index name.

Closes #89485

### CODE REVIEW

**Comment by sakurai-youhei** [comment]
I need the following support from reviewers.

- Which is the preferred use of `name()`?
  1. Call it as many as necessary, as the overhead is ignorable.
  2. Combine them into `String name = name();`.
  3. Replace the second call with `it`.
- How to kick off backport PR in a good manner after this PR? I will appreciate any reference/documentation.

Thanks.

**Comment by javanna** [comment]
Hi @sakurai-youhei thanks for your contribution, I am a bit surprised that no tests are failing after changing the error message, maybe existing tests rely on substring. It would be good to update existing tests though to test the entire error message including the part that you added. Could you do that? We will take care of the rest, backporting etc. By the way the changelog too, it normally does not need editing, as it takes the needed info from the PR itself. Maybe you could update the title of the PR to something more descriptive like "Clarified fielddata not supported for text fields error message"?

**Comment by sakurai-youhei** [comment]
Hi @javanna Thank you for your support.

- test code: That's because I drafted https://github.com/elastic/elasticsearch/issues/89485 as minimum as possible plus not to break anything carefully. But I've updated the test code as per your advice. :)
- backporting, etc: I appreciate it very much!
- changelog: I didn't know how things work. I see, I leave as it is.
- title: Your suggestion saves me because I couldn't find anything that meets the balance between descriptivity and length.

File: server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java [hunk 1]
```diff
@@ -532,7 +532,12 @@ public void testFielddata() throws IOException {
             IllegalArgumentException.class,
             () -> disabledMapper.fieldType("field").fielddataBuilder(FieldDataContext.noRuntimeFields("test"))
         );
-        assertThat(e.getMessage(), containsString("Text fields are not optimised for operations that require per-document field data"));
+        assertThat(
+            e.getMessage(),
+            containsString(
+                "Field data is disabled on [field] in []. Text fields are not optimised for operations that require per-document field data"
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java:538]: could you check why the index name is empty in the returned error? Is it a bug or is it due to the setup of the test?

Comment (sakurai-youhei) [reply server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java:538]: Because the empty string is specified to `fullyQualifiedIndexName` here (line 42).
https://github.com/elastic/elasticsearch/blob/43e2852016fa28d2892324291c4de14bfc62fa73/server/src/main/java/org/elasticsearch/index/fielddata/FieldDataContext.java#L33-L42
I think this happens only under unordinary situations like tests, as the use cases indicate.

Comment (javanna) [reply server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java:538]: can you provide a different fielddatacontext instance here and specify the index so that we can test that we get it back as part of the error?

Comment (sakurai-youhei) [reply server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java]: I've pushed a change accordingly. Hope it meets the intention.

Comment (javanna) [reply server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java]: yes, thanks!

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 2]
```diff
@@ -909,7 +909,11 @@ public IndexFieldData.Builder fielddataBuilder(FieldDataContext fieldDataContext
             } else if (operation == FielddataOperation.SEARCH) {
                 if (fielddata == false) {
                     throw new IllegalArgumentException(
-                        "Text fields are not optimised for operations that require per-document "
+                        "Field data is disabled on ["
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:912]: super minor nit: could you remove the whitespace between Field and data? I've seen that that's how we refer to it in our docs and I would prefer to keep that consistent.

File: server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java [hunk 3]
```diff
@@ -530,9 +530,15 @@ public void testFielddata() throws IOException {
...
         Exception e = expectThrows(
             IllegalArgumentException.class,
-            () -> disabledMapper.fieldType("field").fielddataBuilder(FieldDataContext.noRuntimeFields("test"))
+            () -> disabledMapper.fieldType("field")
+                .fielddataBuilder(new FieldDataContext("index", null, null, MappedFieldType.FielddataOperation.SEARCH))
+        );
+        assertThat(
+            e.getMessage(),
+            containsString(
+                "Field data is disabled on [field] in [index]. Text fields are not optimised for operations that require per-document field data"
```
Comment (javanna) [inline server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java:539]: checkstyle complained about this line, not sure if you've already addressed it, but we have a hard limit of 140 characters per line. Can you double check?

Comment (sakurai-youhei) [reply server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java]: My apologies for this kind of noise; I thought IntelliJ's code formatting fixes everything automatically, but I find it doesn't actually for this case. Sorry.

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java (hunk 2 above)
Comment (sakurai-youhei) [reply server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:912]:
```suggestion
                        "Fielddata is disabled on ["
```

File: server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java [hunk 4]
```diff
@@ -530,9 +530,16 @@ public void testFielddata() throws IOException {
...
         Exception e = expectThrows(
             IllegalArgumentException.class,
-            () -> disabledMapper.fieldType("field").fielddataBuilder(FieldDataContext.noRuntimeFields("test"))
+            () -> disabledMapper.fieldType("field")
+                .fielddataBuilder(new FieldDataContext("index", null, null, MappedFieldType.FielddataOperation.SEARCH))
+        );
+        assertThat(
+            e.getMessage(),
+            containsString(
+                "Field data is disabled on [field] in [index]. "
```
Comment (sakurai-youhei) [inline server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java:539]:
```suggestion
                "Fielddata is disabled on [field] in [index]. "
```

File: server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java [hunk 5]
```diff
@@ -909,7 +909,11 @@ public IndexFieldData.Builder fielddataBuilder(FieldDataContext fieldDataContext
...
+                            + name()
+                            + "] in ["
+                            + fieldDataContext.fullyQualifiedIndexName()
+                            + "]. Text fields are not optimised for operations that require per-document "
                             + "field data like aggregations and sorting, so these operations are disabled by default. Please use a "
```
Comment (sakurai-youhei) [inline server/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java:917]: @javanna Is this `field data` ok to have the white space between the words? If so, I will leave this as it is. Otherwise, I will also change here and the corresponding part in the test.

File: server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java (hunk 3 above)
Comment (javanna) [reply server/src/test/java/org/elasticsearch/index/mapper/TextFieldMapperTests.java]: no worries, happens to me as well once in a while.

**Review by javanna — APPROVED** [review]
LGTM thanks @sakurai-youhei !

**Comment by pmontepagano** [comment]
Is this going to be backported to ES 7.17 ?

**Comment by javanna** [comment]
hi @pmontepagano we don't plan on backporting this change. We only backport critical fixes to 7.17.
