### PR TITLE
Avoid a race condition while waiting for pre warm to finish on SearchableSnapshotDirectoryTests

### LINKED ISSUE #60813: SearchableSnapshotDirectoryTests#testNonCachedFilesAreExcludedFromRecoveryState fails
**Build scan**:

https://gradle-enterprise.elastic.co/s/rve5theumtlaw/console-log?task=:x-pack:plugin:searchable-snapshots:test

**Repro line**:

    
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testNonCachedFilesAreExcludedFromRecoveryState" -Dtests.seed=F1D689E910ABDDD7 -Dtests.security.manager=true -Dtests.locale=ar-SA -Dtests.timezone=Asia/Macau -Druntime.java=8
--
```

**Reproduces locally?**:

No, after many hundreds of retries.

**Applicable branches**:

Only seen on `7.x` so far.

**Failure history**:

Only once so far.

**Failure excerpt**:

```
org.elasticsearch.index.store.SearchableSnapshotDirectoryTests > testNonCachedFilesAreExcludedFromRecoveryState FAILED
    java.lang.AssertionError: 
    Expected: <DONE>
         but: was <FINALIZE>
        at __randomizedtesting.SeedInfo.seed([F1D689E910ABDDD7:9F0EA6FE12244832]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.lambda$testNonCachedFilesAreExcludedFromRecoveryState$29(SearchableSnapshotDirectoryTests.java:829)
        at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testDirectories(SearchableSnapshotDirectoryTests.java:622)
        at org.elasticsearch.index.store.SearchableSnapshotDirectoryTests.testNonCachedFilesAreExcludedFromRecoveryState(SearchableSnapshotDirectoryTests.java:826)

```

### PR DESCRIPTION
**Pull request by fcofdez**
`assertExecutorIsIdle` was prone to races and it was possible that the conditions were true before the pre-warm phase finished. This PR waits until the pre-warm flag is set on `SearchableSnapshotRecoveryState`.

Closes #60813

### CODE REVIEW

File: x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/indices/recovery/SearchableSnapshotRecoveryState.java [hunk 1]
```diff
@@ -37,7 +37,7 @@ public synchronized RecoveryState setStage(Stage stage) {
         return super.setStage(stage);
     }
 
-    public synchronized void preWarmFinished() {
+    public synchronized void setPreWarmFinished() {
```
Comment (DaveCTurner) [inline x-pack/plugin/searchable-snapshots/src/main/java/org/elasticsearch/indices/recovery/SearchableSnapshotRecoveryState.java:40]: Naming nit, I think we should call this `preWarmComplete` (here and related names) rather than `preWarmFinished` since if there are any failures the prewarming process still finishes, although the shard was not completely prewarmed.

```suggestion
    public synchronized void setPreWarmComplete() {
```

**Review by DaveCTurner — COMMENTED** [review]
Makes sense, thanks. I suggested a different name but otherwise LGTM.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by fcofdez** [comment]
jenkins test this please
