### PR TITLE
Rewind ILM if create-snapshot fails to take snapshot

### LINKED ISSUE #75401: ILM's searchable_snapshot action can get "stuck" attempting to create a snapshot with a duplicate name, requiring the move-to-step API to unstick
I've observed this twice, though with limited capability to gather information, and I don't have steps to reproduce at this time (though I haven't tried very hard).

Observed on 7.13.2 only so far, but with a sample size of two that's not necessarily an indication it's the only impacted version.

The primary indicator that the index is "stuck" this way is an error message similar to:
```
invalid_snapshot_name_exception: [my-index-lt7xdseariqi0ld_6clspq] Invalid snapshot name [my-index-lt7xdseariqi0ld_6clspq], snapshot with the same name already exists
```

When this occurs, the index will be stuck in the `create-snapshot` step, repeatedly trying to create the snapshot, but failing because a `PARTIAL` snapshot already exists with that name. The ILM retry API leads to the same result. Deleting the snapshot causes the index to move on to the `mount-snapshot`, which then fails because the expected snapshot doesn't exist.

The only workaround that I've found so far is to use the move-to-step API to move the index back to the `generate-snapshot-name` step to force a new snapshot name to be generated, like so:
```
POST _ilm/move/restored-metricbeat-7.12.1-2021.05.10-000004
{
  "current_step": { 
    "phase": "cold",
    "action": "searchable_snapshot",
    "name": "ERROR"
  },
  "next_step": { 
    "phase": "cold",
    "action": "searchable_snapshot",
    "name": "generate-snapshot-name"
  }
}
```

It would be nice if ILM could detect when this happens and automatically generate a new snapshot name before retrying, rather than trying over and over with the same name, forcing manual intervention.

Stack trace for completeness, although I don't think this will be terribly useful:
```
InvalidSnapshotNameException[[my-index-lt7xdseariqi0ld_6clspq] Invalid snapshot name [my-index-lt7xdseariqi0ld_6clspq], snapshot with the same name already exists]
at org.elasticsearch.snapshots.SnapshotsService.ensureSnapshotNameAvailableInRepo(SnapshotsService.java:630)
at org.elasticsearch.snapshots.SnapshotsService.access$4700(SnapshotsService.java:119)
at org.elasticsearch.snapshots.SnapshotsService$2.execute(SnapshotsService.java:416)
at org.elasticsearch.repositories.blobstore.BlobStoreRepository$1.execute(BlobStoreRepository.java:393)
at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:691)
at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:313)
at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:208)
at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:62)
at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:140)
at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673)
at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241)
at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)

### PR DESCRIPTION
**Pull request by andreidan**
This fixes the case when the `create-snapshot` step fails because it treats
a partial snapshot as a failure, hence the step will be retried and every retry
will fail as the snapshot already exists in the repository.

This makes the step report "incomplete" and have ILM rewind to the `cleanup-snapshot`
step in order to first delete the existing (partial) snapshot and create a fresh one.

The change is quite big due to changing the signature of `AsyncActionStep#performAction`
to not use ActionListener<Boolean> (the implicit invariant was that as all steps should've 
return `true` since https://github.com/elastic/elasticsearch/pull/73796) but to use `ActionListener<Void>`. 
This also deletes `AsyncActionBranchingStep` because it was unfit for purpose given the 
new *explicit* binary state (success or failure) for async steps - which was the source of the bug 
this commit is fixing.

I have explored keeping the `AsyncActionBranchingStep` and making it abstract, but this is not feasible
as `CreateSnapshotStep` extends `AsyncRetryDuringSnapshotActionStep` already.

Fixes #75401

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine update branch

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/CleanupShrinkIndexStepTests.java [hunk 1]
```diff
@@ -72,8 +72,8 @@ public void testPerformActionDoesntFailIfShrinkingIndexNameIsMissing() {
         CleanupShrinkIndexStep cleanupShrinkIndexStep = createRandomInstance();
         cleanupShrinkIndexStep.performAction(indexMetadata, clusterState, null, new ActionListener<>() {
             @Override
-            public void onResponse(Boolean complete) {
-                assertThat(complete, is(true));
+            public void onResponse(Void unused) {
+                assertTrue("onResponse must be called", true);
```
Comment (dakrone) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/CleanupShrinkIndexStepTests.java:76]: I don't think we need this assert since it's basically a noop now (`assert true`)? Should we just add a `fail("reason");` to the `onFailure` handler below?

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/CleanupShrinkIndexStepTests.java [hunk 2]
```diff
@@ -136,8 +136,8 @@ public void testDeleteSkippedIfManagedIndexIsShrunkAndSourceDoesntExist() throws
             CleanupShrinkIndexStep step = new CleanupShrinkIndexStep(randomStepKey(), randomStepKey(), client);
             step.performAction(shrunkIndexMetadata, clusterState, null, new ActionListener<>() {
                 @Override
-                public void onResponse(Boolean complete) {
-                    assertThat(complete, is(true));
+                public void onResponse(Void complete) {
+                    assertTrue("onResponse must be called", true);
```
Comment (dakrone) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm/CleanupShrinkIndexStepTests.java:140]: Same about this one

**Review by dakrone — APPROVED** [review]
LGTM thanks Andrei! I left two really minor comments

**Comment by andreidan** [comment]
@elasticmachine update branch
