### PR TITLE
[ES|QL] Fix MMR release test using subqueries

### LINKED ISSUE #144077: [CI] VerifierTests testMMRLimitedInput failing
**Build Scans:**
- [elasticsearch-periodic #11985 / release-tests](https://gradle-enterprise.elastic.co/s/tqcykenohtoca)
- [elasticsearch-periodic #11985 / release-tests](https://gradle-enterprise.elastic.co/s/rouh3n6q2mqzi)
- [elasticsearch-pull-request #127601 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/brtxncuzxc53g)
- [elasticsearch-pull-request #127566 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/nig673wc43cau)
- [elasticsearch-pull-request #127351 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/7kxzlg577mqe2)
- [elasticsearch-pull-request #127333 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/b6ak3tbjvafp4)
- [elasticsearch-pull-request #127291 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/fgbpkqcu4ksny)
- [elasticsearch-pull-request #127258 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/6jtn3g5etb3jg)
- [elasticsearch-pull-request #127211 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/vm3jtbn26m3de)
- [elasticsearch-pull-request #127202 / checkpart3_release-tests](https://gradle-enterprise.elastic.co/s/d5hlmnwfe2l4a)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.analysis.VerifierTests.testMMRLimitedInput" -Dtests.seed=59700DEF7E317431 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=bn -Dtests.timezone=Asia/Khandyga -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.analysis.VerifierTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testMMRLimitedInput'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
junit.framework.AssertionFailedError: Unexpected exception type, expected VerificationException but got org.elasticsearch.xpack.esql.parser.ParsingException: line 1:6: no viable alternative at input '('
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 10 consecutive failures in step checkpart3_release-tests
- [main] 12 failures in test testMMRLimitedInput (2.9% fail rate in 416 executions)
- [main] 2 failures in step release-tests (100.0% fail rate in 2 executions)
- [main] 10 failures in step checkpart3_release-tests (100.0% fail rate in 10 executions)
- [main] 10 failures in pipeline elasticsearch-pull-request (3.6% fail rate in 278 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ioanatia**
closes https://github.com/elastic/elasticsearch/issues/144077 
related https://github.com/elastic/elasticsearch/issues/144086

we need an explicit capability check when we test MMR with subqueries.

I won't add the `test-release` label to the PR, since other unrelated tests are failing too.
So I just tested this with:

```
./gradlew ":x-pack:plugin:esql:test" --tests "org.elasticsearch.xpack.esql.analysis.VerifierTests.testMMRLimitedInput" -Dbuild.snapshot=false  -Dtests.jvm.argline="-Dbuild.snapshot=false"  -Dlicense.key=x-pack/license-tools/src/test/resources/public.key
```

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java [hunk 1]
```diff
@@ -3790,8 +3790,6 @@ public void testUnsupportedMetadata() {
     }
 
     public void testMMRDiversifyFieldIsValid() {
-        assumeTrue("MMR requires corresponding capability", EsqlCapabilities.Cap.MMR_V2.isEnabled());
```
Comment (ioanatia) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/VerifierTests.java:3793]: cap is always enabled - these checks can be removed.

**Review by carlosdelest — APPROVED** [review]
Thanks for fixing!
