### PR TITLE
ESQL: Disallow empty lists in named params, only

### LINKED ISSUE #147448: ESQL: NPE Cannot invoke "org.elasticsearch.xpack.esql.core.type.DataType.isCounter()" because "t" is null
### Elasticsearch Version

9.4.0, probably present in older versions

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

OSX

### Problem Description

This throws a NPE:

```
POST /_query
{
    "query": "ROW v = 1 | WHERE MV_CONTAINS(?x, [1, 2])",
    "params": [{"x": []}]
}

java.lang.NullPointerException: Cannot invoke "org.elasticsearch.xpack.esql.core.type.DataType.isCounter()" because "t" is null
    at org.elasticsearch.xpack.esql.core.type.DataType.isRepresentable(DataType.java:739)
    at org.elasticsearch.xpack.esql.core.expression.TypeResolutions.lambda$isRepresentableExceptCountersDenseVectorAggregateMetricDoubleAndHistogram$3(TypeResolutions.java:93)
    at org.elasticsearch.xpack.esql.core.expression.TypeResolutions.isType(TypeResolutions.java:246)
    at org.elasticsearch.xpack.esql.core.expression.TypeResolutions.isType(TypeResolutions.java:234)
    at org.elasticsearch.xpack.esql.core.expression.TypeResolutions.isType(TypeResolutions.java:213)
    at org.elasticsearch.xpack.esql.core.expression.TypeResolutions.isRepresentableExceptCountersDenseVectorAggregateMetricDoubleAndHistogram(TypeResolutions.java:91)
    at org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvContains.resolveType(MvContains.java:153)
...
```

which I think it shouldn't. Probably related to what data type we are assigning empty list query parameters?

Funnily this works:

```
POST /_query
{                                                         
    "query": "ROW v = 1 | WHERE MV_CONTAINS(?x, [1, 2])",
    "params": [{"x": null}]                                
}
```

### Steps to Reproduce

Given already

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by alex-spies**
Fix https://github.com/elastic/elasticsearch/issues/147448. Likely not a proper long-term fix.

Disallow empty lists `[]` in named query parameters but keep them enabled in positional parameters, as there may be legitimate queries with `[]` in positional parameters that are working today.

The effect is that users see a 400 rather than a 500 error, which esp. improves alerting based on server errors. 

AI-assisted PR.

### CODE REVIEW

**Review by fang-xing-esql — APPROVED** [review]
LGTM, thanks for fixing it!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/RequestXContent.java [hunk 1]
```diff
@@ -426,6 +426,15 @@ private static void checkParamValueValidity(
                 );
                 return;
             }
+            if (valueList.isEmpty()) {
+                errors.add(
+                    new XContentParseException(
+                        loc,
+                        "Parameter [" + entry.getKey() + "] is an empty list. Empty lists are not allowed as named parameter values"
```
Comment (astefan) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/action/RequestXContent.java]: Based on error messages that ESQL usually has, I recommend "Empty lists are not allowed as named parameter values. Got parameter [......] with value [.....]."

**Review by astefan — APPROVED** [review]
LGTM.
With a consistency nit related to messaging.

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks @alex-spies!
