### PR TITLE
Use consistent view of realms for authentication

### LINKED ISSUE #30301: [CI] testSecurityActionsByLicenseType: Failed to execute phase [query]
In https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+multijob-unix-compatibility/os=fedora/16/console, `org.elasticsearch.license.LicensingTests#testSecurityActionsByLicenseType` failed. The `REPRODUCE LINE` doesn't reproduce a failure:

```
./gradlew :x-pack:plugin:security:test -Dtests.seed=993121463E9AC0EF -Dtests.class=org.elasticsearch.license.LicensingTests -Dtests.method="testSecurityActionsByLicenseType" -Dtests.security.manager=true -Dtests.locale=sr -Dtests.timezone=Africa/Accra
```

This stack trace appears, but there's nothing obviously related to it in the rest of the logs:

```
Failed to execute phase [query], all shards failed
  at __randomizedtesting.SeedInfo.seed([993121463E9AC0EF:5C5ECE7262D69883]:0)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:288)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:128)
  at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:249)
  at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:101)
  at org.elasticsearch.action.search.InitialSearchPhase.access$100(InitialSearchPhase.java:48)
  at org.elasticsearch.action.search.InitialSearchPhase$2.lambda$onFailure$1(InitialSearchPhase.java:222)
  at org.elasticsearch.action.search.InitialSearchPhase.maybeFork(InitialSearchPhase.java:176)
  at org.elasticsearch.action.search.InitialSearchPhase.access$000(InitialSearchPhase.java:48)
  at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:222)
  at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73)
  at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
  at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:527)
  at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1095)
  at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1188)
  at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1172)
  at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:66)
  at org.elasticsearch.action.search.SearchTransportService$6$1.onFailure(SearchTransportService.java:385)
  at org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:341)
  at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:335)
  at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:329)
  at org.elasticsearch.search.SearchService$3.doRun(SearchService.java:1019)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:724)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by jaymode**
This change updates the authentication service to use a consistent view
of the realms based on the license state at the start of
authentication. Without this, the license can change during
authentication of a request and it will result in a failure if the
realm that extracted the token is no longer in the realm list. This
manifests in some tests as an authentication failure that should never
really happen; one example would be the test framework's transport
client user should always have a successful authentication but in the
LicensingTests this can fail and will show up as a
NoNodeAvailableException.

Additionally, the licensing tests have been updated to ensure that
there is consistency when changing the license. The license is changed
by modifying the internal xpack license state on each node, which has
no protection against be changed by some pending cluster action. The
methods to disable and enable now ensure we have a green cluster and
that the cluster is consistent before returning.

Closes #30301

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/license/LicensingTests.java [hunk 1]
```diff
@@ -304,23 +300,60 @@ private static void assertElasticsearchSecurityException(ThrowingRunnable runnab
...
-    public static void disableLicensing() {
-        disableLicensing(License.OperationMode.BASIC);
-    }
-
-    public static void disableLicensing(License.OperationMode operationMode) {
-        for (XPackLicenseState licenseState : internalCluster().getInstances(XPackLicenseState.class)) {
-            licenseState.update(operationMode, false, null);
-        }
+    private void disableLicensing() throws InterruptedException {
+        // do this in an await busy since there is a chance that the enabled action is not held in place by a node and the node
```
Comment (tvernum) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/license/LicensingTests.java]: I don't follow what `not held in place` means in this comment.

**Review by tvernum — APPROVED** [review]
LGTM, except that I don't follow one of the code comment.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/license/LicensingTests.java (hunk 1 above)
Comment (jaymode) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/license/LicensingTests.java]: You're right, this is not clear. I updated the comment, but essentially I am saying the update performed to the license gets overwritten
