### PR TITLE
Fix MetricsApmIT.testApmIntegration histogram assertions

### LINKED ISSUE #115415: [CI] MetricsApmIT testApmIntegration failing
**Build Scans:**
- [elasticsearch-periodic #4626 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/r5p4mwtuql4ts)
- [elasticsearch-periodic #4616 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/2tsugjqy2jj2k)
- [elasticsearch-periodic #4596 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/x7x5wa4wraujg)
- [elasticsearch-periodic #4591 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/tkb7lvf73qata)
- [elasticsearch-periodic #4586 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/epn23lvoyxfca)
- [elasticsearch-periodic #4581 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/shaan6q6ganq4)

**Reproduction Line:**
```
./gradlew ':test:external-modules:test-apm-integration:javaRestTest' --tests "org.elasticsearch.test.apmintegration.MetricsApmIT.testApmIntegration" -Dtests.seed=C717C31120754CEC -Dtests.locale=ms-ID -Dtests.timezone=Asia/Colombo -Druntime.java=23
```

**Applicable branches:**
8.15

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.test.apmintegration.MetricsApmIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testApmIntegration),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Timeout when waiting for assertions to complete. Remaining assertions to match: {es.test.async_long_counter.total=es.test.async_long_counter.total <1>, es.test.long_gauge.current=es.test.long_gauge.current <1>, es.test.long_counter.total=es.test.long_counter.total a numeric value within <0.001> of <1.0>, es.test.async_double_counter.total=es.test.async_double_counter.total a numeric value within <0.001> of <1.0>, es.test.long_histogram.histogram=es.test.long_histogram.histogram <2>, es.test.double_histogram.histogram=es.test.double_histogram.histogram <2>, es.test.double_gauge.current=es.test.double_gauge.current a numeric value within <0.001> of <1.0>, es.test.double_counter.total=es.test.double_counter.total a numeric value within <0.001> of <1.0>}
```

**Issue Reasons:**
- [8.15] 6 consecutive failures in step openjdk23_checkpart1_java-matrix
- [8.15] 6 failures in test testApmIntegration (2.2% fail rate in 273 executions)
- [8.15] 6 failures in step openjdk23_checkpart1_java-matrix (100.0% fail rate in 6 executions)
- [8.15] 6 failures in pipeline elasticsearch-periodic (60.0% fail rate in 10 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ldematte**
Assertions on histograms did not account for data being sent by the agent on different messages.
Upgrade to the agent with https://github.com/elastic/elasticsearch/pull/115194 probably exacerbated the issue, but we already had some random failures in the past (hence the extensive logs), which are now probably explained

Closes https://github.com/elastic/elasticsearch/issues/115415

### CODE REVIEW

File: test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java [hunk 1]
```diff
@@ -91,21 +88,35 @@ public void testApmIntegration() throws Exception {
...
+                        var counts = ((Collection<Integer>) samplesObject.get("counts")).stream().mapToInt(Integer::intValue).sum();
+                        var remaining = histogramAssertion - counts;
+                        if (remaining == 0) {
                             logger.info("{} assertion PASSED", key);
-                            sampleAssertions.remove(key);
+                            histogramAssertions.remove(key);
                         } else {
-                            logger.error("{} assertion FAILED: {}", key, sampleObject.get("value"));
+                            logger.info("{} assertion PENDING: {} remaining", key, remaining);
+                            histogramAssertions.put(key, remaining);
```
Comment (prdoyle) [inline test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java:113]: If I understand these changes, I think what's happening is that each key could have multiple samples, and together they should add up to the expected quantity?

Have you considered scanning the samples to aggregate a summary of the _actual_ results, and then assert that this equals the _expected_ results? That is a more typical pattern for unit tests, and might be easier for others to follow, rather than a loop that interleaves mutating data structures with assertions.

Comment (ldematte) [reply test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java:113]: That's true, it would be nicer, but has the downside of being more time consuming. 

Today we are reading samples and counting down till zero, so as soon as we have enough data (can be all in the first message), we good. Otherwise we keep listening for more data and check again until TIMEOUT.
If we aggregate and then check against expected, we will have first to wait until TIMEOUT, then check (sure we can have an assertBusy, but that is more or less the same, only with multiple timeouts).

In the worst scenario this is the same, but the test usually is quicker and pass as soon as we meet the criteria.

Comment (ldematte) [reply test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java:113]: That said, I did a minimal change to fix the test, and I have to say I also find the mutating data structures with assertions pattern very very strange.
Probably it would be better to rewrite this test in a way similar to what you suggest (with assertBusy), but I would leave it for a followup PR.

Comment (prdoyle) [reply test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java:113]: Makes sense!

Comment (prdoyle) [inline test/external-modules/apm-integration/src/javaRestTest/java/org/elasticsearch/test/apmintegration/MetricsApmIT.java:113]: I think this test will fail to notice if there are too many samples with the given `key`, because as soon as the count hits zero, the entry is removed, and thereafter, we do no more checks. The existing logic also had this bug.

Also, style-wise, this could use `map.computeIfPresent` if you find that cleaner at all:

```
histogramAssertions.computeIfPresent(key, (k, old) -> {
    int counts = WHATEVER;
    var remaining = old - counts;
    if (remaining == 0) {
        return null;
    } else {
        return remaining;
    }
});
```

**Review by prdoyle — APPROVED** [review]
The logic looks correct to me, as far as it goes. It has no more bugs than the original code, and fixes a known problem.
