### PR TITLE
Removes Set Policy API in favour of setting index.lifecycle.name directly

### LINKED ISSUE #34302: [ILM] set policy for index API does not work if index is on complete step for a phase
Steps to reproduce:
1. Create two policies:
```
PUT _ilm/my_lifecycle2
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_age": "30s"
          }
        }
      },
      "warm": {
        "actions": {
          "forcemerge": {
            "max_num_segments": 1
          },
          "allocate": {
            "number_of_replicas": 1
          }
        }
      },
      "delete": {
        "minimum_age": "2m",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}

PUT _ilm/my_lifecycle3
{
  "policy": {
    "phases": {
      "hot": {
        "actions": {
          "rollover": {
            "max_age": "30s"
          }
        }
      },
      "warm": {
        "actions": {
          "forcemerge": {
            "max_num_segments": 1
          },
          "allocate": {
            "number_of_replicas": 1
          }
        }
      },
      "delete": {
        "minimum_age": "2m",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}
```
2. Create an index template and an index for the policies using `my_lifecycle3`:
```
PUT _template/my_template
{
  "index_patterns": ["test-*"],
  "settings": {
    "number_of_shards": 2,
    "number_of_replicas": 0,
    "index.lifecycle.name": "my_lifecycle3",
    "index.lifecycle.rollover_alias": "test-alias"
  }
}

PUT test-000001
{
  "aliases": {
    "test-alias":{
      "is_write_index": true
    }
  }
}
```

3. Wait for the `test-000001` index to complete all actions in the warm phase
4. Try to move `test-000001` to use `my_lifecycle2`:
```
PUT test-000001/_ilm/my_lifecycle2
```
5. Observe error response:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "[complete] is not a valid action for phase [warm] in lifecycle type [timeseries]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "[complete] is not a valid action for phase [warm] in lifecycle type [timeseries]"
  },
  "status": 400
}
```

Maybe we should go back to letting users set the `index.lifecycle.name` setting on the update settings API now that there are no restrictions on when the policy can be changed on an index?

### PR DESCRIPTION
**Pull request by colings86**
Still to do:

- [x] Add a test for changing the policy using the update settings API and checking the new policy is used after the current phase completes

Closes #34302

### CODE REVIEW

**Comment by dakrone** [comment]
If we're doing this in the setting, I think we should remove the `RemovePolicyForIndexAction` also, and have a listener on the `index.lifecycle.name` setting that does what we need as "teardown" for an index when the setting is removed (set to `null`).

We could do it as a followup though. What do you think?

File: x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunnerTests.java [hunk 1]
```diff
@@ -1522,91 +1420,6 @@ public Result isConditionMet(Index index, ClusterState clusterState) {
...
-            return Objects.equals(index, task.getIndex()) &&
-                    Objects.equals(policy, task.getPolicy())&&
-                    Objects.equals(currentStepKey, task.getCurrentStepKey()) &&
-                    Objects.equals(cause.getClass(), task.getCause().getClass()) &&
-                    Objects.equals(cause.getMessage(), task.getCause().getMessage());
-        }
-
-    }
-
-    private static class SetStepInfoUpdateTaskMatcher extends ArgumentMatcher<SetStepInfoUpdateTask> {
```
Comment (gwbrown) [inline x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/indexlifecycle/IndexLifecycleRunnerTests.java]: This class is being used by the code in #34206

File: client/rest-high-level/src/test/java/org/elasticsearch/client/IndexLifecycleIT.java [hunk 2]
```diff
@@ -63,31 +59,9 @@
 import static org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertAcked;
 import static org.hamcrest.Matchers.equalTo;
 import static org.hamcrest.Matchers.hasItems;
-import static org.hamcrest.Matchers.is;
 
 public class IndexLifecycleIT extends ESRestHighLevelClientTestCase {
 
-    public void testSetIndexLifecyclePolicy() throws Exception {
```
Comment (gwbrown) [inline client/rest-high-level/src/test/java/org/elasticsearch/client/IndexLifecycleIT.java]: Might be worth replacing this test case with one that makes sure changing the lifecycle policy via the settings API works as expected (i.e. actually runs the new policy)

**Review by AthenaEryma — COMMENTED** [review]
A couple minor comments, otherwise LGTM (though I second @dakrone's comment, and pending tests passing).

Also, ++ for `+9 −1,884`.

File: client/rest-high-level/src/test/java/org/elasticsearch/client/IndexLifecycleIT.java (hunk 2 above)
Comment (colings86) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/IndexLifecycleIT.java]: Agreed, that was the intention of the outstanding task in the description

Comment (gwbrown) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/IndexLifecycleIT.java]: My bad, I misread that task.

Comment (colings86) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/IndexLifecycleIT.java]: NP. My intention was to have this as a server side test rather than a test in the HLRC because its testing ILM functionality rather than the client or the API. Does that work for you or do you feel strongly this should be tested as part of the client?

Comment (gwbrown) [reply client/rest-high-level/src/test/java/org/elasticsearch/client/IndexLifecycleIT.java]: I’m good with testing it server side

**Review by dakrone — COMMENTED** [review]
LGTM

**Comment by colings86** [comment]
@talevy @gwbrown I added the test mentioned int he description, could you take a look?

**Comment by talevy** [comment]
@colings86 yup, will take a look today. hopefully the conflicting files are minimal

**Review by talevy — COMMENTED** [review]
I took a look at it, overall looks good to me!

the only reason I didn't approve is because this still has some conflicts with upstream.

**Comment by colings86** [comment]
@elasticmachine test this please

**Review by talevy — APPROVED** [review]
LGTM
