### PR TITLE
Fix SnapshotMetricsIT race conditions

### LINKED ISSUE #132731: [CI] SnapshotMetricsIT testSnapshotAPMMetrics failing
**Build Scans:**
- [elasticsearch-intake #26770 / part1](https://gradle-enterprise.elastic.co/s/5glty6wqfbpzu)
- [elasticsearch-intake #26764 / part1](https://gradle-enterprise.elastic.co/s/3jdrtbspqhn7k)
- [elasticsearch-pull-request #85309 / part-1](https://gradle-enterprise.elastic.co/s/mqdrbduxkmqgy)
- [elasticsearch-intake #26750 / part1](https://gradle-enterprise.elastic.co/s/btkzl622op3cw)
- [elasticsearch-intake #26738 / part1](https://gradle-enterprise.elastic.co/s/zmfjchpaixz4k)
- [elasticsearch-intake #26739 / part1](https://gradle-enterprise.elastic.co/s/ahyyqxueniypm)
- [elasticsearch-pull-request #85107 / part-1](https://gradle-enterprise.elastic.co/s/igaumbku5ct2e)
- [elasticsearch-pull-request #85057 / part-1](https://gradle-enterprise.elastic.co/s/unmkg3vme3vjc)
- [elasticsearch-intake #26688 / part1](https://gradle-enterprise.elastic.co/s/rrbnddhpykjxe)
- [elasticsearch-pull-request #85052 / part-1](https://gradle-enterprise.elastic.co/s/w2rz7onzmkbhk)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.repositories.SnapshotMetricsIT.testSnapshotAPMMetrics" -Dtests.seed=4A9ABF7AFE27508A -Dtests.locale=ku -Dtests.timezone=Australia/Canberra -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.SnapshotMetricsIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testSnapshotAPMMetrics'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: <1L>
     but: was <0L>
```

**Issue Reasons:**
- [main] 13 failures in test testSnapshotAPMMetrics (12.9% fail rate in 101 executions)
- [main] 6 failures in step part1 (31.6% fail rate in 19 executions)
- [main] 7 failures in step part-1 (12.7% fail rate in 55 executions)
- [main] 6 failures in pipeline elasticsearch-intake (31.6% fail rate in 19 executions)
- [main] 7 failures in pipeline elasticsearch-pull-request (13.0% fail rate in 54 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
Attempt at fixing race condition(s) in the `SnapshotMetricsIT`

Thanks @JeremyDahlgren for troubleshooting this

Fixes #132731

### CODE REVIEW

File: server/src/internalClusterTest/java/org/elasticsearch/repositories/SnapshotMetricsIT.java [hunk 1]
```diff
@@ -132,7 +135,7 @@ public void testSnapshotAPMMetrics() throws Exception {
         }
 
         // wait for snapshot to finish to test the other metrics
-        awaitNumberOfSnapshotsInProgress(0);
+        safeGet(snapshotFuture);
```
Comment (nicktindall) [inline server/src/internalClusterTest/java/org/elasticsearch/repositories/SnapshotMetricsIT.java:125]: I think if we wait for the response to be received that should mean the metrics should be written? (note `waitForCompletion=true` above now)

I'm running in a loop to try and confirm that now

**Review by mhl-b — APPROVED** [review]
LGTM

File: server/src/internalClusterTest/java/org/elasticsearch/repositories/SnapshotMetricsIT.java (hunk 1 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/repositories/SnapshotMetricsIT.java:125]: This introduced a source of flakiness in the tension between the throttling and `safeGet`. If the setting was too high, we exceeded the `safeGet` timeout, if the setting was too low, we didn't see any throttling.

For this reason I've [moved out the test for the throttling metrics to another test](https://github.com/elastic/elasticsearch/pull/132780/commits/f034e1d3a4b4923c521e8a8a2448370f97acf82e). It has more complexity to ensure we see throttling and we don't run too long.

**Comment by nicktindall** [comment]
@JeremyDahlgren I think the additional ceremony is necessary to make a timely and reliable throttling metrics test. I broke it out into its own test because I didn't want to muddy the waters in the existing one with all the extra steps. I'm running `SnapshotMetricsIT` on repeat on a GCP machine to see if it holds.

See now we set the `max_bytes_per_sec` much lower to ensure throttling, but then once we've seen throttling we remove the limits to allow the snapshot/restore to complete in a reasonable amount of time.

File: server/src/internalClusterTest/java/org/elasticsearch/repositories/SnapshotMetricsIT.java [hunk 2]
```diff
@@ -215,14 +178,127 @@ public void testSnapshotAPMMetrics() throws Exception {
...
+            assertThat(getTotalClusterLongCounterValue(SnapshotMetrics.SNAPSHOT_RESTORE_THROTTLE_DURATION), greaterThan(0L));
+        });
+
+        final long restore_ts2 = System.currentTimeMillis();
+        // Remove restore throttling
+        createRepository(
+            repositoryName,
+            "mock",
+            repositorySettings.put(BlobStoreRepository.MAX_RESTORE_BYTES_PER_SEC.getKey(), ByteSizeValue.ZERO)
+        );
```
Comment (JeremyDahlgren) [inline server/src/internalClusterTest/java/org/elasticsearch/repositories/SnapshotMetricsIT.java]: Is it significant that `verify` is omitted here, which will default to `true`, while the previous `createRepository()` calls explicitly set it to `false`?  Is this to save time and just verify at the end?

I see this is a PUT when I drill down, but `createOrUpdateRepository()` or `putRepository()` might help when reading.  Just an observation though, this method and overrides have been around a long time.

**Review by JeremyDahlgren — APPROVED** [review]
LGTM.  I had this in a loop also and couldn't get a failure.  @mhl-b had also reviewed earlier, he might want to double check since the updates.

File: server/src/internalClusterTest/java/org/elasticsearch/repositories/SnapshotMetricsIT.java (hunk 2 above)
Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/repositories/SnapshotMetricsIT.java]: Yeah I set it to false because verify makes it take longer, when all we're trying to do is turn off the throttling. Good pick up, I've set it to false in 62f193515471240a8eeaf15b220fed51ac51b61b

Sadly overnight the test failed on line 105, another race condition where the snapshot thread blocks in the repo. before the `SNAPSHOTS_STARTED` counter is incremented. I'll fix that and run for another day again 🙄

Comment (nicktindall) [reply server/src/internalClusterTest/java/org/elasticsearch/repositories/SnapshotMetricsIT.java]: > I see this is a PUT when I drill down, but createOrUpdateRepository() or putRepository() might help when reading. Just an observation though, this method and overrides have been around a long time.

Agree on the naming, I won't do that as part of this PR but I might follow up with a second one (it will probably add lots of noise)
