### PR TITLE
Convert flaky yml tests to EsRestTestCases

### LINKED ISSUE #47275: [CI] IndexLifecycleRestIT {yaml=ilm/40_explain_lifecycle/Test All Indexes Lifecycle Explain} failure
The test failed in one of my PR build:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/7623/console
but I can see some intermittent failures though the build is not available.
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part2/1195/console

```
./gradlew ':x-pack:plugin:ilm:qa:rest:restTestRunner' \
--tests "org.elasticsearch.xpack.ilm.IndexLifecycleRestIT.test {yaml=ilm/40_explain_lifecycle/Test All Indexes Lifecycle Explain}" \
-Dtests.seed=147FD374FCB1376A \
-Dtests.security.manager=true \
-Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP \
-Dtests.timezone=Indian/Cocos \
-Dcompiler.java=12 \
-Druntime.java=11
```

with error
```
org.elasticsearch.xpack.ilm.IndexLifecycleRestIT > test {yaml=ilm/40_explain_lifecycle/Test All Indexes Lifecycle Explain} FAILED
14:29:13     java.lang.AssertionError: Failure at [ilm/40_explain_lifecycle:218]: field [indices.index_with_policy_that_doesnt_exist.step_info.reason] is null
14:29:13 
14:29:13         Caused by:
14:29:13         java.lang.AssertionError: field [indices.index_with_policy_that_doesnt_exist.step_info.reason] is null
```

### PR DESCRIPTION
**Pull request by andreidan**
We've had several failures in the yml ILM tests because ILM doesn't run in a deterministic way
and we can't wait for it to run in the yml test. The latest failure, `field [indices.another_index.phase] is null`,
is another symptom. 

This PR converts the ILM yml tests that rely on ILM having run (eg. successful explain api 
output tests for managed indices, valid and invalid move to step api tests that specify the 
correct current step) into `ESRestTestCase` tests that make use of the `assertBusy` primitive.

Resolves #47275 
Relates to https://github.com/elastic/elasticsearch/issues/53488

### CODE REVIEW

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java [hunk 1]
```diff
@@ -0,0 +1,206 @@
...
+            .put(IndexMetadata.SETTING_NUMBER_OF_REPLICAS, 0)
+            .put(LifecycleSettings.LIFECYCLE_NAME, missingPolicyName));
+
+        assertBusy(() -> {
+            Map<String, Map<String, Object>> explain = explain(client(), this.index + "*", false, false);
+            assertManagedIndex(explain.get(firstIndex));
+            assertManagedIndex(explain.get(secondIndex));
+            assertUnmanagedIndex(explain.get(unmanagedIndex));
+
+            Map<String, Object> explainIndexWithMissingPolicy = explain.get(indexWithMissingPolicy);
```
Comment (dakrone) [inline x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:168]: I think we could probably put this one is a second `assertBusy` so that we don't end up doing two explains when we only need to do one

**Review by dakrone — APPROVED** [review]
LGTM, I left some really minor comments, thanks!

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java (hunk 1 above)
Comment (andreidan) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/ilm/ExplainLifecycleIT.java:168]: There's only one explain API call in this assertBusy. I believe it's ok to leave it in one `assertBusy` call.

File: x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/TimeSeriesRestDriver.java [hunk 2]
```diff
@@ -228,6 +242,15 @@ public static void createIndexWithSettings(RestClient client, String index, Stri
         ensureGreen(index);
     }
 
+    public static void createIndexWithSettingsNoAlias(RestClient client, String index, Settings.Builder settings) throws IOException {
```
[the remark this answers is not in the document]
Comment (andreidan) [reply x-pack/plugin/ilm/qa/multi-node/src/javaRestTest/java/org/elasticsearch/xpack/TimeSeriesRestDriver.java:245]: I've renamed the method `createIndexWithSettings` with signature:
```
    public static void createIndexWithSettings(RestClient client, String index, Settings.Builder settings) throws IOException {
```

I think piggybacking this use case on the helper that has the `alias` and `useWriteIndex` parameters by making both `@Nullable` over complicates the logic (and we'd end up passing 2 `null` parameters).

What do you think?

**Comment by andreidan** [comment]
@elasticmachine update branch
