### PR TITLE
NETWORKING: Make RemoteClusterConn. Lazy Resolve DNS

### LINKED ISSUE #28858: Remote cluster DNS cached indefinitely
I'm finding that cross cluster search doesn't continuously resolve hostnames and instead caches the addresses indefinitely. Correct me if I'm wrong in my analysis but it appears that hostnames for the seeds are only resolved upon node startup and update to the seed list. I'm seeing this at https://github.com/elastic/elasticsearch/blob/v6.3.2/server/src/main/java/org/elasticsearch/transport/RemoteClusterService.java#L318 and https://github.com/elastic/elasticsearch/blob/v6.3.2/server/src/main/java/org/elasticsearch/transport/RemoteClusterService.java#L333.

This makes cross cluster search impossible to use in any environment with changing IP's such as a containerized environment.

The best idea I have for a workaround is to have each node routinely ping it's own /_remote/info endpoint and whenever an empty seeds list appears from it being disconnected, dynamically remove the seed from the cluster settings, and re-add it.

### PR DESCRIPTION
**Pull request by original-brownbear**
* Lazy resolve DNS (i.e. `String` to `DiscoveryNode`) to not run into indefinitely caching lookup issues (provided the JVM dns cache is configured correctly as explained in https://www.elastic.co/guide/en/elasticsearch/reference/6.3/networkaddress-cache-ttl.html)
   * Changed `InetAddress` type to `String` for that higher up the stack
   * Passed down `Supplier<DiscoveryNode>` instead of outright `DiscoveryNode` from `RemoteClusterAware#buildRemoteClustersSeeds` on to lazy resolve DNS when the `DiscoveryNode` is actually used (could've also passed down the value of `clusterName = REMOTE_CLUSTERS_SEEDS.getNamespace(concreteSetting)` together with the `List<String>` of hosts, but this route seemed to introduce less duplication and resulted in a significantly smaller changeset).
* Closes #28858

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java [hunk 1]
```diff
@@ -48,8 +49,12 @@
     /**
      * A list of initial seed nodes to discover eligible nodes from the remote cluster
      */
-    public static final Setting.AffixSetting<List<InetSocketAddress>> REMOTE_CLUSTERS_SEEDS = Setting.affixKeySetting("search.remote.",
-        "seeds", (key) -> Setting.listSetting(key, Collections.emptyList(), RemoteClusterAware::parseSeedAddress,
+    public static final Setting.AffixSetting<List<String>> REMOTE_CLUSTERS_SEEDS = Setting.affixKeySetting("search.remote.",
```
Comment (chernecov) [inline server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: I am stranger here, so sorry if I am wrong, but it would be more readable:
```
public static final Setting.AffixSetting<List<String>> REMOTE_CLUSTERS_SEEDS = Setting.affixKeySetting(
    "search.remote.",
    "seeds",
    (key) -> Setting.listSetting(
        key, Collections.emptyList(),
        s -> {
            // validate seed address
            RemoteClusterAware.parseSeedAddress(s);
            return s;
        },
        Setting.Property.NodeScope, Setting.Property.Dynamic
    )
);
```

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: No worries, I don't think there's much of a wrong or right here :) I tend to agree with your suggested style but if you look around the codebase you will find that my style is what's used pretty much everywhere so I went with the consistent approach here.

Comment (chernecov) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: Huh, I see now.
That's completely fine then.
Consistency is a very good thing, your're right.
Thanks.

Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: @original-brownbear I use the style suggested by @chernecov. 😇

**Review by jasontedor — CHANGES_REQUESTED** [review]
I skimmed this and the general approach looks right. I think what is missing though, sorry if I overlooked, is a test that shows that we are now resolve addresses on demand? That is, that at least we (independent of what the JVM might be doing), no longer cache addresses.

File: server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java (hunk 1 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: Hehe that's all I needed to hear :) Will reformat

**Comment by original-brownbear** [comment]
@jasontedor thanks for taking a look :)

You didn't overlook anything, I was a bad one for not adding a test => added one now though :)
=> This should be good for another look.

**Comment by original-brownbear** [comment]
hold off a few minutes with the review, seems the new test is unstable in some way -> fixing

**Comment by original-brownbear** [comment]
@jasontedor should be stable/good to review now. Sorry for the noise :)

File: server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java [hunk 2]
```diff
@@ -48,9 +49,19 @@
...
-        "seeds", (key) -> Setting.listSetting(key, Collections.emptyList(), RemoteClusterAware::parseSeedAddress,
-            Setting.Property.NodeScope, Setting.Property.Dynamic));
+    public static final Setting.AffixSetting<List<String>> REMOTE_CLUSTERS_SEEDS = Setting.affixKeySetting(
+        "search.remote.",
+        "seeds",
+        key -> Setting.listSetting(
+            key, Collections.emptyList(),
+            s -> {
+                // validate seed address
+                RemoteClusterAware.parseSeedAddress(s);
```
Comment (jasontedor) [inline server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: So this seems problematic. It means, for example, if a host fails to resolve, we mark the setting as invalid. Yet, it could resolve for us later?

**Review by jasontedor — CHANGES_REQUESTED** [review]
I have a concern about how we validate the seed node setting now.

File: server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java (hunk 2 above)
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: @jasontedor yea, I guess we could leave it out. I mainly just added this because there was an explicit test for this behavior.
I guess we could just delete it and drop the validation. I could go either way here:
Yes this could resolve later, so maybe it's fine not to validate. On the other hand, you could make an annoying typo in a hostname and now you won't catch it right away. Probably a question of how often and if someone would ever configure a hostname that doesn't resolve yet. Also, if you don't have the DNS caching ttl configured, not having this check is kind of annoying because it will never resolve and you might rather want this to fail right away 
=> You decide :)

Comment (jasontedor) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: If a hostname fails to resolve at time of use (i.e., when we try to connect to the remote cluster), we would have a failure message in the logs indicating the problem? That is, the unknown host exception would be there?

I lean towards saying we leave the lookup out of validation, yet I think the remainder of the validation is good.

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: @jasontedor sounds good will adjust accordingly in a bit :)

Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: @jasontedor done in https://github.com/elastic/elasticsearch/pull/32764/commits/a22994a5df08e006c7d1cf770bdb9762d3a80bec, extracted the port parsing from the address parsing to get all validation except for the hostname lookup into a separate method :)

**Review by jasontedor — APPROVED** [review]
LGTM. I left a few comments, but no need for another round.

**Review by jasontedor — COMMENTED** [review]
Oh, one more nit.

File: server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java [hunk 3]
```diff
@@ -48,9 +49,19 @@
...
+        "search.remote.",
+        "seeds",
+        key -> Setting.listSetting(
+            key, Collections.emptyList(),
+            s -> {
+                // validate seed address
+                parsePort(s);
+                return s;
+            },
+            Setting.Property.NodeScope, Setting.Property.Dynamic
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: sure will do :)

File: server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java [hunk 4]
```diff
@@ -65,18 +76,19 @@ protected RemoteClusterAware(Settings settings) {
...
             Collectors.toMap(REMOTE_CLUSTERS_SEEDS::getNamespace, concreteSetting -> {
                 String clusterName = REMOTE_CLUSTERS_SEEDS.getNamespace(concreteSetting);
-                List<DiscoveryNode> nodes = new ArrayList<>();
-                for (InetSocketAddress address : concreteSetting.get(settings)) {
-                    TransportAddress transportAddress = new TransportAddress(address);
-                    DiscoveryNode node = new DiscoveryNode(clusterName + "#" + transportAddress.toString(),
-                        transportAddress,
-                        Version.CURRENT.minimumCompatibilityVersion());
-                    nodes.add(node);
+                List<Supplier<DiscoveryNode>> nodes = new ArrayList<>();
```
[the remark this answers is not in the document]
Comment (original-brownbear) [reply server/src/main/java/org/elasticsearch/transport/RemoteClusterAware.java]: sure will do :)

**Comment by original-brownbear** [comment]
@jasontedor thanks addressed all points => will merge once green :)

**Comment by original-brownbear** [comment]
Jenkins test this
