### PR TITLE
Took time and cluster details get updated for coordinator only query operations

### LINKED ISSUE #114014: Took time is not being set in ESQL responses when LIMIT 0 is used
### Elasticsearch Version

8.16

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

All

### Problem Description

Took time is not being set in ESQL responses when LIMIT 0 is used.
Took-nanos header is still being set, however.
The LIMIT 0 pathway is bypassing the location where took time is set.

### Steps to Reproduce

FROM foo | LIMIT 0

(using JSON response)

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by quux00**
The ComputeService.runCompute pathway for coordinator only operations 
(such as `FROM foo | LIMIT 0`) get updated with overall took time and, 
for cross-cluster operations, cluster metadata.

Fixes https://github.com/elastic/elasticsearch/issues/114014

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java [hunk 1]
```diff
@@ -247,6 +251,26 @@ public void execute(
         }
     }
 
+    private static void updateExecutionInfoAfterCoordinatorOnlyQuery(long queryStartNanos, EsqlExecutionInfo execInfo) {
+        long tookTimeNanos = System.nanoTime() - queryStartNanos;
+        execInfo.overallTook(new TimeValue(tookTimeNanos, TimeUnit.NANOSECONDS));
+        if (execInfo.isCrossClusterSearch()) {
+            for (String clusterAlias : execInfo.clusterAliases()) {
+                // The local cluster 'took' time gets updated as part of the acquireCompute(local) call in the coordinator, so
+                // here we only need to update status for remote clusters since there are no remote ComputeListeners in this case.
```
Comment (nik9000) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:260]: It's probably worth saying something about how we didn't need the remote clusters at all in this situation.

I'm not sure how you can write an ESQL that does this by the way.

Comment (nik9000) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:260]: Ah! That's right. `LIMIT 0`. We resolve the remote clusters so we can get type information from them, but then we never need them.

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClustersQueryIT.java [hunk 2]
```diff
@@ -339,6 +340,108 @@ public void testSearchesWhereNonExistentClusterIsSpecifiedWithWildcards() {
...
+
+            EsqlExecutionInfo.Cluster localCluster = executionInfo.getCluster(LOCAL_CLUSTER);
+            assertThat(localCluster.getIndexExpression(), equalTo("nomatch*"));
+            // TODO: in https://github.com/elastic/elasticsearch/issues/112886, this will be changed to be SKIPPED
+            assertThat(localCluster.getStatus(), equalTo(EsqlExecutionInfo.Cluster.Status.SUCCESSFUL));
+            assertThat(localCluster.getTook().millis(), greaterThanOrEqualTo(0L));
+            assertThat(localCluster.getTook().millis(), lessThanOrEqualTo(overallTookMillis));
+        }
+    }
+
```
Comment (nik9000) [inline x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClustersQueryIT.java:444]: Do you think it's worth adding another test that uses `ROW` instead of the remote cluster? Just to make sure we don't do something *crazy* in the presence of a remote cluster.

**Review by nik9000 — APPROVED** [review]

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClustersQueryIT.java (hunk 2 above)
Comment (quux00) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClustersQueryIT.java:444]: We actually have some of those in the RestEsqlIT tests and I recently had to adjust the tests to match the new took value: https://github.com/elastic/elasticsearch/pull/114075/files#diff-26c21ef143a22a30c09971081f1373ffbd9b89ca3f2bfcc722e69c57a7b78682R120

Those "ROW" queries can't be cross-cluster right? If that's right then the RestEsqlIT test is sufficient I think.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java (hunk 1 above)
Comment (quux00) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/plugin/ComputeService.java:260]: I'll update the code comment to specifically mention the "LIMIT 0" usage so it's clear to future readers/maintainers.

File: x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClustersQueryIT.java (hunk 2 above)
Comment (quux00) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClustersQueryIT.java:444]: I don't think you can do cross-cluster and ROW based on reading the docs and experimenting, so I think that the existing RestEsqlIT tests cover the ROW scenario sufficiently?

Comment (nik9000) [reply x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/CrossClustersQueryIT.java:444]: Yeah, ROW never touches the remote clusters. It's all good.
