### PR TITLE
Fix remote cluster credential secure settings reload  

### LINKED ISSUE #111543: Reloading remote cluster credentials via API fails for users with `manage` privilege
### Elasticsearch Version

8.13.0 or higher.

### Java Version

_bundled_

### Problem Description

The [Nodes reload secure settings API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-reload-secure-settings.html) requires the `manage` cluster privilege. 

In clusters running versions >=8.13.0, however, it fails to reload remote cluster credentials for the [API key-based remote cluster security model](https://www.elastic.co/guide/en/elasticsearch/reference/current/remote-clusters-api-key.html), unless users have the `all` cluster privilege (or `manage` AND `manage_security`). 

Any call made by a user with only `manage` results in the following error message:

```
"reason" : "action [cluster:admin/xpack/security/remote_cluster_credentials/reload] is unauthorized for user [<...>] with effective roles [<...>], this action is granted by the cluster privileges [manage_security,all]"
```

This error message is misleading since all secure settings, apart from remote cluster credentials, still reload successfully for users with only `manage` cluster privileges.

To reload remote cluster credentials, the workaround is to make the reload request with a user with the `all` cluster privilege (or `manage` AND `manage_security`).

Reloading other secure settings is still possible with only the `manage` cluster privilege, and the reported error can be ignored. 

This is a regression introduced by: https://github.com/elastic/elasticsearch/pull/103215

### Steps to Reproduce

Create role and user with `manage` privilege:

```
PUT /_security/role/role
{
    "cluster": [
        "manage"
    ]
}

PUT /_security/user/user
{
    "password": "<...>",
    "roles": ["role"]
}
```

Call the reload settings API with that user:

```
POST /_nodes/reload_secure_settings
```

This will result in an error message with failure reason:

```
"reason" : "action [cluster:admin/xpack/security/remote_cluster_credentials/reload] is unauthorized for user [user] with effective roles [role], this action is granted by the cluster privileges [manage_security,all]"
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by n1v0lg**
Due to the `cluster:admin/xpack/security` action name prefix, the internal action `cluster:admin/xpack/security/remote_cluster_credentials/reload` to reload remote cluster credentials fails for users that have the `manage` cluster privilege. This does not align with our documentation and the overall permission requirements for reloading secure settings.  

This PR renames the action to match the `manage` privilege. Since this is a local-only action there are no BWC concerns with this rename. 

Fixes: https://github.com/elastic/elasticsearch/issues/111543

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/action/admin/cluster/node/reload/TransportNodesReloadSecureSettingsAction.java [hunk 1]
```diff
@@ -123,6 +123,7 @@ protected NodesReloadSecureSettingsResponse.NodeResponse nodeOperation(
             final List<Exception> exceptions = new ArrayList<>();
             // broadcast the new settings object (with the open embedded keystore) to all reloadable plugins
             pluginsService.filterPlugins(ReloadablePlugin.class).forEach(p -> {
+                logger.debug("Reloading plugin [" + p.getClass().getSimpleName() + "]");
```
Comment (n1v0lg) [inline server/src/main/java/org/elasticsearch/action/admin/cluster/node/reload/TransportNodesReloadSecureSettingsAction.java:126]: Seems useful for future debugging...

**Comment by n1v0lg** [comment]
@elasticmachine update branch

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java [hunk 2]
```diff
@@ -2202,13 +2202,19 @@ private void reloadRemoteClusterCredentials(Settings settingsWithKeystore) {
...
-        getClient().execute(
-            ActionTypes.RELOAD_REMOTE_CLUSTER_CREDENTIALS_ACTION,
-            new TransportReloadRemoteClusterCredentialsAction.Request(settingsWithKeystore),
-            future
-        );
-        future.actionGet();
+        // Run this action in system context -- it was authorized upstream and should not be tied to end-user permissions
+        final ThreadContext ctx = getClient().threadPool().getThreadContext();
+        assert ctx != null : "Thread context must be set for reload call";
+        try (ThreadContext.StoredContext ignore = ctx.stashContext()) {
```
Comment (jakelandis) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java:2208]: Can we stash the context and mark as system context from `TransportNodesReloadSecureSettingsAction` instead of here ? It feels off that we can call this method directly from anywhere that we can reference  Security#reload and the work will be done in the system context, possibly having never run any authz. 

Since the expectation is that work is implicitly allowed as a sub action from  `TransportNodesReloadSecureSettingsAction`, I think having `TransportNodesReloadSecureSettingsAction` mark it as the system context is more correct since. It would also apply to all other sub reload actions, but that I think is also more correct since the permissions to use `TransportNodesReloadSecureSettingsAction` need to converge to a single permission.

Alternatively, I think we could change `RELOAD_REMOTE_CLUSTER_CREDENTIALS_ACTION` to an actual "internal:" action, helping to re-inforce that this is sub action / implementation detail of another action. But that would I prefer keeping the action name as-is and ensuring that the flip to system context is a bit more isolated to it's usage.

**Review by jakelandis — CHANGES_REQUESTED** [review]
Question about where we should mark it as the system context.

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java (hunk 2 above)
Comment (n1v0lg) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java:2208]: I included it here primarily because it's an implementation detail that it's an action to begin with -- most other reload calls happen at the "service" layer and are not subject to authz at all -- it would be the same here if we had access to the right services within the Security plugin (we'd just call `RemoteClusterService.reload(...)` without the action workaround, but unfortunately, `RemoteClusterService` is not available in Security. To me it actually feels _more_ isolated to have it here.

However, I don't feel strongly -- `TransportNodesReloadSecureSettingsAction` is a fine place to switch to system context (though we'll have to double-check that we're not somehow switching back out of it along the way) -- let me know if you strongly prefer `TransportNodesReloadSecureSettingsAction` instead and I pull the switch over there.

Comment (n1v0lg) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/Security.java]: Discussed on Slack -- switching to system context in `TransportNodesReloadSecureSettingsAction` has several downsides. 

Since `Security#reload` is a public method that could (in theory) be called in a context that did not ensure proper authz it's however better to also avoid the system context switch inside reload.

To accommodate this, we've decided to simply rename the action to have a prefix that's covered by `manage`. Since it's a local-only action there are not BWC concerns with this.

**Review by jakelandis — APPROVED** [review]
LGTM, thanks for the iterations. 

(super nitpick: the PR description "Due to a missing system context switch,..." part is a bit misleading now)

**Comment by n1v0lg** [comment]
@elasticmachine update branch
