### PR TITLE
Fix APM configuration file delete

### LINKED ISSUE #89439: APM secret token briefly exists in plain text
PR #88443 implemented a tracer using the Elastic APM Java agent. As discussed in the PR, it was necessary to write a temporary config file for the agent, in order to configure settings that cannot be dynamically set at runtime. Although this config file is rapidly deleted again, it is not ideal that we have to do it at all.

We need to investigate alternatives, which will require a conversation with the APM team about alternative approaches to configure the agent.

### PR DESCRIPTION
**Pull request by grcevski**
When we launch Elasticsearch with the APM monitoring agent, we create a temporary configuration file to securely pass the API key or secret. This temporary file is cleaned up on Elasticsearch Node creation.

After we renamed the APM module, the delete logic didn't get updated, which means we never delete the file anymore.

This PR:
 - fixes the APM module pattern match when we delete, while adding support for absolute paths
 - adds additional delete safety net on failed node start
 - adds tests for ensuring that the naming dependency isn't broken again.

After reviewing the possible ways to pass options to the APM agent, I think the current design is the best way to pass options to the APM Java agent at the moment. Even if we worked around the issues with the Security manager and we attached the agent instead of using the command line, the agent upon attach seems to be writing a configuration file anyway: https://github.com/elastic/apm-agent-java/blob/main/apm-agent-attach/src/main/java/co/elastic/apm/attach/ElasticApmAttacher.java#L115.

Closes https://github.com/elastic/elasticsearch/issues/89439

### CODE REVIEW

File: distribution/tools/server-cli/src/main/java/org/elasticsearch/server/cli/APMJvmOptions.java [hunk 1]
```diff
@@ -253,7 +275,12 @@ private static Path writeApmProperties(Path tmpdir, Map<String, String> properti
      */
     @Nullable
     private static Path findAgentJar() throws IOException, UserException {
-        final Path apmModule = Path.of(System.getProperty("user.dir")).resolve("modules/apm");
```
Comment (grcevski) [inline distribution/tools/server-cli/src/main/java/org/elasticsearch/server/cli/APMJvmOptions.java:256]: I did resolve("modules").resolve("apm") to be Windows friendly.

File: server/src/main/java/org/elasticsearch/node/Node.java [hunk 2]
```diff
@@ -1135,24 +1139,23 @@ protected Node(
...
      */
     @SuppressForbidden(reason = "Cannot guarantee that the temp config path is relative to the environment")
-    private void deleteTemporaryApmConfig(JvmInfo jvmInfo) {
+    public static void deleteTemporaryApmConfig(JvmInfo jvmInfo, BiConsumer<Exception, Path> errorHandler) {
         for (String inputArgument : jvmInfo.getInputArguments()) {
             if (inputArgument.startsWith("-javaagent:")) {
                 final String agentArg = inputArgument.substring(11);
                 final String[] parts = agentArg.split("=", 2);
-                if (parts[0].matches("modules/x-pack-apm-integration/elastic-apm-agent-\\d+\\.\\d+\\.\\d+\\.jar")) {
+                if (parts[0].matches(".*modules/apm/elastic-apm-agent-\\d+\\.\\d+\\.\\d+\\.jar")) {
```
Comment (grcevski) [inline server/src/main/java/org/elasticsearch/node/Node.java:1151]: I had to add `.*` to make sure this works with absolute paths.

File: distribution/tools/server-cli/src/main/java/org/elasticsearch/server/cli/APMJvmOptions.java [hunk 3]
```diff
@@ -166,13 +166,18 @@ static List<String> apmJvmOptions(Settings settings, @Nullable KeyStoreWrapper k
...
         // because then the agent won't try to reload the file, and we can remove it after startup.
-        options.add("-javaagent:" + agentJar + "=c=" + tmpProperties);
+        options.add(agentCommandLineOption(agentJar, tmpProperties));
 
         dynamicSettings.forEach((key, value) -> options.add("-Delastic.apm." + key + "=" + value));
 
         return options;
     }
 
+    // package private for testing
```
Comment (grcevski) [inline distribution/tools/server-cli/src/main/java/org/elasticsearch/server/cli/APMJvmOptions.java:176]: These small methods are extracted so that I can prove the tests use whatever is used in the code (given we have the cross file dependency with Node).

**Review by pugnascotia — APPROVED** [review]
LGTM, apologies for the break 🙏

File: distribution/tools/server-cli/src/test/java/org/elasticsearch/server/cli/APMJvmOptionsTests.java [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+        var agentPath = APMJvmOptions.findAgentJar(makeFakeAgentJar().toAbsolutePath().toString());
+        var tempFile = APMJvmOptions.createTemporaryPropertiesFile(agentPath.getParent());
+        var commandLineOption = APMJvmOptions.agentCommandLineOption(agentPath, tempFile);
+        var jvmInfo = mock(JvmInfo.class);
+        doReturn(new String[] { commandLineOption }).when(jvmInfo).getInputArguments();
+        assertTrue(Files.exists(tempFile));
+        Node.deleteTemporaryApmConfig(jvmInfo, (e, p) -> fail("Shouldn't hit an exception"));
+        assertFalse(Files.exists(tempFile));
+
+        Files.delete(agentPath);
```
Comment (thecoop) [inline distribution/tools/server-cli/src/test/java/org/elasticsearch/server/cli/APMJvmOptionsTests.java:53]: Should this be done regardless of test status? Or maybe in test class cleanup?

**Comment by grcevski** [comment]
@elasticsearchmachine run CLA

**Comment by grcevski** [comment]
@elasticsearchmachine test this please
