### PR TITLE
Fix error applying `ignore_malformed` to boolean values

### LINKED ISSUE #11498: [Bug] 'ignore_malformed' applied to a malformed (boolean) numeric field does not work
When I try to index a doc with a boolean field that's mapped as numeric, even with ìgnored_malformed`set to`true`, an exception is raised.

Repro steps:
##### Create a new index:

```
curl -XPUT localhost:9200/myindex
```

which yields `{ "acknowledged" : true }`
##### Create a mapping for a type in that index, with one integer field that has `ignore_malformed` set to true and coerce set to `true`

```
curl -XPUT localhost:9200/myindex/_mapping/mytype -d
'{
    "mytype": {
      "properties": {
        "foo": {
        "type": "integer",
        "ignore_malformed": true,
        "coerce": false
        }
      }
  }
}'
```

which yields `{ "acknowledged" : true }`
##### Index one document with a field whose value is false

```
curl -XPUT localhost:9200/myindex/mytype/one -d
'{
  a: 3,
  foo: false
}'
```

which yields an exception:

```
{
"error" : "MapperParsingException[failed to parse [foo]]; nested: JsonParseException[Current token (VALUE_FALSE) not numeric, can not use numeric value accessors at [Source: [B@3a98c595; line: 3, column: 13]]; ",
"status" : 400
}
```

According to `ignored_malformed: true`, even if false is not an integer, the doc should get indexed anyway.

### PR DESCRIPTION
**Pull request by cbuescher**
The `ignore_malformed` option currently works on numeric fields only when the
bad value isn't a string value but not if it is a boolean. In this case we get a
parsing error from the xContent parser which we need to catch in addition to the
field mapper.

Closes #11498

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/index/mapper/NumberFieldMapperTests.java [hunk 1]
```diff
@@ -218,45 +220,39 @@ protected void doTestDecimalCoerce(String type) throws IOException {
...
-        assertEquals(mapping, mapper.mappingSource().toString());
-
-        ThrowingRunnable runnable = () -> mapper.parse(new SourceToParse("test", "type", "1", BytesReference
-                .bytes(XContentFactory.jsonBuilder()
-                        .startObject()
-                        .field("field", "a")
-                        .endObject()),
-                XContentType.JSON));
-        MapperParsingException e = expectThrows(MapperParsingException.class, runnable);
+            Object malformedValue = randomBoolean() ? "a" : false;
```
Comment (jtibshirani) [inline server/src/test/java/org/elasticsearch/index/mapper/NumberFieldMapperTests.java]: Instead of using randomization, it might be good to always test both values through a for loop. We just added some guidance to our testing docs around avoiding randomized testing for coverage: https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc#bad-practices

File: server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java [hunk 2]
```diff
@@ -1042,7 +1044,7 @@ protected void parseCreateField(ParseContext context, List<IndexableField> field
         } else {
             try {
                 numericValue = fieldType().type.parse(parser, coerce.value());
-            } catch (IllegalArgumentException e) {
+            } catch (IllegalArgumentException | JsonParseException e) {
```
Comment (jtibshirani) [inline server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java]: I haven't tested this, but I wanted to check that this will not introduce too much leniency? In particular, I'm wondering what happens if we try to pass a JSON object to a numeric field with `ignore_malformed` enabled.

**Review by jtibshirani — COMMENTED** [review]
This looks good to me overall, I left a question to make sure I understand the approach.

File: server/src/test/java/org/elasticsearch/index/mapper/NumberFieldMapperTests.java (hunk 1 above)
Comment (cbuescher) [reply server/src/test/java/org/elasticsearch/index/mapper/NumberFieldMapperTests.java]: Sure

File: server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java (hunk 2 above)
Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java]: The way the parser works, anything that's not a number or string token after the field name should throw an error. If "swallowing" that token with ignore_malformed leads to unparseable xcontent afterwards we will still throw an error. I think that's what should happen.

Comment (jtibshirani) [reply server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java]: Thanks for clarifying. What would you think about adding a check whether the token is a value, as in if (ignoreMalformed.value() && parser.currentToken().isValue()) { ... }? That way a user would get a clear, localized error like "Current token (START_OBJECT) not numeric", as opposed to a more difficult one to track down like "Malformed content, found extra data after parsing: END_OBJECT".

Comment (cbuescher) [reply server/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java]: The problem with that is that the code actually throwing the exception is in the jackson library. The only way I could think of to do this is either have some logic taking apart the exception or pre-checking the token in NumberFieldMapper. I'd try to avoid the former, was the later what you had in mind? We'd need to test for (and accept) all value tokens here basically?

**Comment by cbuescher** [comment]
@jtibshirani thanks for the review, I added the check for the token type you suggested and added a test where the malformed field value is an object. The current implementation will throw erros in numeric fields `foo` like:
```
{
   foo: { "someField" : "someValue" } 
}
```
regardless of the `ignore_malformed` setting. Not sure if that is what the user would expect here. As an alternative we could skip the whole object in case `ignore_malformed` is true. What do you think is the more intuitive behaviour in these edge cases?

**Review by jtibshirani — APPROVED** [review]
Thanks @cbuescher, this looks good to me. My intuition is that the whole object should be skipped, but it might make sense to address the object case in a future PR since there is a separate issue for it with quite a bit of discussion (#12366).

**Comment by cbuescher** [comment]
@jtibshirani thanks for the review, and +1 to tackling the object case as a follow up, e.g. when tackling the issue you linked.
