### PR TITLE
Always error out if CCS expression shows up when CCS is not supported

### LINKED ISSUE #138987: Endpoints that are not cross-cluster enabled should always error out with qualified index expressions
### Elasticsearch Version

8.x, 9.x

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Any

### Problem Description

For Elasticsearch APIs that take an index expression, some are cross-cluster enabled (e.g., `_search`) and some are not (`_mapping`).

For the endpoints that are not cross-cluster enabled, when they receive a qualified index expression (e.g., `clusterA:myindex`), an error is returned:

```
GET blogs,remote1:blogs/_mappings

// response:
    "type": "illegal_argument_exception",
    "reason": "Cross-cluster calls are not supported in this context but remote indices were requested: [remote1:blogs]"
```

However, when ignore_unavailable is set to true, this error message is no longer displayed and instead the API will process any local indices that were present:

```
GET blogs,remote1:blogs/_mappings?ignore_unavailable=true

// response gives the blogs mappings of the local cluster only
{
  "blogs": {
    "mappings": {
      "properties": {
        "authors": {
          "properties": {
            "company": {
              "type": "text",
```

This is incorrect behavior. The `ignore_unavailable` setting should not be controlling whether this error message is returned. `ignore_unavailable` should control how to behave with respect to whether concrete indices are present or not on a cluster, but for endpoints that are not cross-cluster enabled at all, requesting a remote cluster is always a violation of the contract of that endpoint and thus should always result in an error.

### Steps to Reproduce

See Problem Description section above.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by smalyshev**
This patch decouples `ignore_unavailable` from "CCS not supported" error when trying to resolve index expression. `IndexNameExpressionResolver` can not resolve remote expressions, and for most code paths, it is the right thing to return an error when such expression is supplied. For some code paths, it may be OK to ignore such expressions, at least for now, but in either case, `ignore_unavailable` should have nothing to do with it. 

This patch tries to preserve the functionality in most places which misuse `IndexNameExpressionResolver` by trying to sent it remote indices, but we'd need to go back and fix those eventually. 

Closes: https://github.com/elastic/elasticsearch/issues/138987

### CODE REVIEW

File: server/src/main/java/org/elasticsearch/search/SearchFeatures.java [hunk 1]
```diff
@@ -35,6 +35,7 @@ public Set<NodeFeature> getFeatures() {
     public static final NodeFeature SEARCH_WITH_NO_DIMENSIONS_BUGFIX = new NodeFeature("search.vectors.no_dimensions_bugfix");
     public static final NodeFeature SEARCH_RESCORE_SCRIPT = new NodeFeature("search.rescore.script");
     public static final NodeFeature NEGATIVE_FUNCTION_SCORE_BAD_REQUEST = new NodeFeature("search.negative.function.score.bad.request");
+    public static final NodeFeature INDICES_BOOST_REMOTE_INDEX_FIX = new NodeFeature("search.indices_boost_remote_index_fix");
```
Comment (quux00) [inline server/src/main/java/org/elasticsearch/search/SearchFeatures.java:38]: (asking to learn) Why does this need to go into a NodeFeature?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformUpdater.java [hunk 2]
```diff
@@ -335,17 +337,19 @@ private static void updateTransformConfiguration(
         final String destinationIndex = config.getDestination().getIndex();
         String[] dest = indexNameExpressionResolver.concreteIndexNames(clusterState, IndicesOptions.lenientExpandOpen(), destinationIndex);
 
-        String[] src = indexNameExpressionResolver.concreteIndexNames(
-            clusterState,
-            IndicesOptions.lenientExpandOpen(),
-            true,
-            config.getSource().getIndex()
-        );
+        // FIXME: what do we do with remote indices?
```
Comment (quux00) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformUpdater.java:340]: Can we have @prwhelan look at this?
Transforms do work cross-cluster so will they ever call this pathway when going cross-cluster?
I presume if they do call this now because `IndicesOptions.lenientExpandOpen()` no error is thrown, but what currently happens to the remote indices when called this way? The new code just drops them so that might break something?

**Review by quux00 — COMMENTED** [review]
I left a few questions.

I think it would make sense to have Pat Whelan review the TransformUpdater code and Luigi review the org/elasticsearch/xpack/ql/index/IndexResolver.java changes.

File: server/src/main/java/org/elasticsearch/search/SearchFeatures.java (hunk 1 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/search/SearchFeatures.java:38]: Why did you make it a node feature? I am wondering if an API capability is more appropriate.

**Review by gmarouli — COMMENTED** [review]
Let me start by saying that I completely agree with splitting the semantics of `ignore_unavailable` and remote expressions.

However, I am a bit concerned with the impact of this specific change. If I understand correctly, after this change the majority of our APIs will not accept remote expressions.

Personally, I do not know which APIs are allowed to accept remote expressions and which ones are not. I think if we move forward with this change we need to make it more clear in the code and add tests that capture this as well. 

Can we elaborate on this a bit more? For example:

```
public Set<ResolvedExpression> resolveExpressions(ProjectMetadata project, String... expressions) {
        return resolveExpressions(project, IndicesOptions.lenientExpandOpen(), false, expressions);
        return resolveExpressions(project, IndicesOptions.lenientExpandOpen(), false, true, expressions);
    }
```

allows remote expressions, why does it allow? Should we mention it in the comments that this should only be used in certain situations? I understand that this was an already pretty obscure method so this is not related to this change, it's just uncovered by this change :)

**Comment by smalyshev** [comment]
@gmarouli 
> If I understand correctly, after this change the majority of our APIs will not accept remote expressions.

Not sure about majority, but code using `IndexNameExpressionResolver` won't accept remote expressions, unless they use the specific flag to enable it. This does not remove any functionality - since `IndexNameExpressionResolver` never supported remote expressions - just makes this explicit. In some cases it may cause errors where there were none previously - like with `indices_boost` - but that's a good thing because it never actually worked, and the absence of an error is the bug we want to fix. 

> allows remote expressions, why does it allow? 

Some of our code uses `IndexNameExpressionResolver` with mixed expressions, relying on it to just ignore remote expressions. This is not exactly correct, but it looks like that's the intent of the code. Ideally, we'd rewrite it to not do that, but I don't want to make this particular fix too complex and it's not strictly speaking needed to fix the immediate bug.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformUpdater.java (hunk 2 above)
Comment (smalyshev) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformUpdater.java:340]: This is not the transform itself, it's just configuration validation. It should be using different API I presume since the one it uses does not support remote indices, while transform itself does. But for now it'd just mean it is incomplete validation, it will not fail the transform itself. I.e. if the remote index is good, the transform would work, if it's not good, it would fail, but instead of failing on validation, as intended, it will fail later in runtime. Which could happen anyway, as somebody could delete an index after configuring the transform, but ideally we'd have a proper validation here.

File: server/src/main/java/org/elasticsearch/search/SearchFeatures.java (hunk 1 above)
Comment (smalyshev) [reply server/src/main/java/org/elasticsearch/search/SearchFeatures.java:38]: I'm not sure how to make it work as API capability - which API would this capability relate to? This happens across multiple APIs... I could link it to a random API, e.g. `_mappings` but is that more correct?

Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/search/SearchFeatures.java:38]: I think we should link it to all the affected APIs, shouldn't we?

**Comment by gmarouli** [comment]
> Not sure about majority, but code using IndexNameExpressionResolver won't accept remote expressions

Almost every API is using the `IndexNameExpressionResolver`. So, this has the potential of breaking a lot of requests that in the past would have returned a partial response. Do you understand my concern?

**Comment by smalyshev** [comment]
> Almost every API is using the `IndexNameExpressionResolver`. So, this has the potential of breaking a lot of requests that in the past would have returned a partial response. Do you understand my concern?

I totally understand your concern. You can use this API in a variety of ways though. The thing is, if you pass a remote index to it, it is supposed to throw. And it will never resolve it properly. The latter has always been the case, so if some API uses it and expects it to resolve remote indices, it is already broken. Fortunately, I didn't and the tests do not reveal any cases where it really happens - except _maybe_ `indices_boost` case where it's marginal (and it **is** currently broken with remote indices, unfortunately). So, I think other APIs use it in a way that it was supposed to be used - to resolve only local indices. Except some APIs that I am fixing in this pull, which were kind of sloppy doing this, and relied on just shutting up the errors and not reporting them. 

Now, can there be more corner cases where other APIs are relying on the same thing and aren't covered by tests? There could be. But that means they are *already* broken now, and the only way we can detect it (instead of users just silently getting wrong results in their responses) is to provide an identifiable error where it happens, and then when this error pops up, fix it. Short of reimplementing `IndexNameExpressionResolver` to actually feature full support for remote indices, which will be a considerable lift, I see no other way of handling it.

File: server/src/main/java/org/elasticsearch/search/SearchFeatures.java (hunk 1 above)
Comment (smalyshev) [reply server/src/main/java/org/elasticsearch/search/SearchFeatures.java:38]: All the APIs that use index resolution? Or can use index boosts? That could be a lot of them, and I am not sure how to practically do that. I don't think just having a test justifies changing every API that uses a feature (I am not even sure there's a way to reliably find them?), there should be some better way, unless I miss something?

File: server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java [hunk 3]
```diff
@@ -993,7 +999,7 @@ public static void assertExpressionHasNullOrDataSelector(String expression) {
      * Resolve an array of expressions to the set of indices and aliases that these expressions match.
      */
     public Set<ResolvedExpression> resolveExpressions(ProjectMetadata project, String... expressions) {
```
Comment (gmarouli) [inline server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java]: Please, rename this method to indicate that it allows remote expressions. It is not clear without checking the implementation of the method and because it changes the default behaviout, it's easy to misuse it.

File: server/src/main/java/org/elasticsearch/search/SearchFeatures.java (hunk 1 above)
Comment (gmarouli) [reply server/src/main/java/org/elasticsearch/search/SearchFeatures.java:38]: > All the APIs that use index resolution? Or can use index boosts? 

I was referring to the APIs that use index resolution but their behaviour changes with this. 

> That could be a lot of them, and I am not sure how to practically do that.

Considering that this is only relevant for testing, so I would add it to the APIs you are testing, in this case the mapping, the index boosts and any other you choose to test.

Unless I am mistaken API capabilities were the recommended way to capture API (and behaviour) changes. Do you think that's not the case?

File: rest-api-spec/build.gradle [hunk 4]
```diff
@@ -113,4 +113,5 @@ tasks.named("yamlRestCompatTestTransform").configure ({ task ->
   task.skipTest("search/140_pre_filter_search_shards/prefilter on non-indexed date fields", "prefiltering can now use skippers on dv-only fields")
   // Expected deprecation warning to compat yaml tests:
   task.addAllowedWarningRegex("Use of the \\[max_size\\] rollover condition has been deprecated in favour of the \\[max_primary_shard_size\\] condition and will be removed in a later version")
+  task.skipTest("search/40_indices_boost/Remote expressions not supported in indices boost", "Recent fix, old version do not support it")
```
Comment (gmarouli) [inline rest-api-spec/build.gradle]: If this is a new test, why do we need this?

**Comment by gmarouli** [comment]
> Now, can there be more corner cases where other APIs are relying on the same thing and aren't covered by tests? There could be. But that means they are already broken now, and the only way we can detect it (instead of users just silently getting wrong results in their responses) is to provide an identifiable error where it happens, and then when this error pops up, fix it.

I am not saying that this "ignoring of remote indices" behaviour was tested and documented, but it is how it has been working and in the code it looked like a conscious choice. We can revise that choice (fwiw I also find it cleaner to consider this behaviour a bug). 

However, because it is working like this now, and it is possible that users might have remote expressions that have flew under the radar because of `ignore_unavailable: true`, we should consider the trade-offs before proceeding, that's all.

**Comment by quux00** [comment]
> I am not saying that this "ignoring of remote indices" behaviour was tested and documented, but it is how it has been working and in the code it looked like a conscious choice. We can revise that choice (fwiw I also find it cleaner to consider this behaviour a bug).
> 
> However, because it is working like this now, and it is possible that users might have remote expressions that have flew under the radar because of `ignore_unavailable: true`, we should consider the trade-offs before proceeding, that's all.

@gmarouli - I created the [issue for this](https://github.com/elastic/elasticsearch/issues/138987) as a bug, not a breaking change, after discussing it with Najwa and Jason Tedor.  Given the surface area of the change that you and Stas are highlighting here, I spoke with Jason again today about it and our question is - is there a usage from a user that wouldn't be considered incorrect behavior to start with?

For example, are all the cases where users would now start getting an error (with this code change) ones where they are referencing a remote index in an endpoint that is not cross-cluster enabled, such as `GET logs,remote1:logs/_mapping`?  If yes, and they added `ignore_unavailable=true` just to bypass an error, that is incorrect usage to start with, so we should address it both on the backend and the client side (adjust their queries).  Or is there a case you know of where the user is correctly using an API and might now get an error with the changes in this PR?

**Comment by gmarouli** [comment]
> I spoke with Jason again today about it and our question is - is there a usage from a user that wouldn't be considered incorrect behaviour to start with?

I do not know why this was implemented like this and there were no documented use cases in the code as far as I know. I do not know what we have communicated to the users about this either. So, my answer is I do not know, and I do not have someone in mind to redirect you to. 

> is there a case you know of where the user is correctly using an API and might now get an error with the changes in this PR

I doubt this, but I cannot say it with certainty. In the past when fixing a bug that would change a silent fail to an error, we considered the element of surprise to some users, and that could influence the choice of fixing the bug or letting it be. This is what I am asking, to double check that the benefit of fixing this behaviour outweighs the possibility of surprising some users.

**Review by gmarouli — COMMENTED** [review]
Apologies for the late code review, I thought I had submitted it 😶‍🌫️

File: rest-api-spec/build.gradle (hunk 4 above)
Comment (smalyshev) [reply rest-api-spec/build.gradle]: Maybe we don't anymore, let me check

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java [hunk 5]
```diff
@@ -742,22 +743,36 @@ public void resolveAsSeparateMappings(
...
+                    }
+                }));
+            }
         }));
 
     }
 
+    /**
+     * Filter out remote index expressions.
+     * TODO: SQL Metadata commands currently do not support remote indices.
```
Comment (quux00) [inline x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java:766]: Do we need to handle this in this PR? If not, how urgent is the follow-up?

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformUpdater.java (hunk 2 above)
Comment (quux00) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformUpdater.java:340]: I think we should coordinate with @prwhelan to agree to the longer term solution and create a JIRA/GH issue for it so it can go in someone's (ML?) backlog.

File: x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java (hunk 5 above)
Comment (smalyshev) [reply x-pack/plugin/ql/src/main/java/org/elasticsearch/xpack/ql/index/IndexResolver.java:766]: The tests in x-pack/plugin/sql/qa/server/src/main/resources/multi-cluster-with-security/multi-cluster-command-sys.csv-spec do not support remote aliases, so I don't think we need to fix it here. As for fixing it in general, I think we need to ask the Analytics team, but given as it has been there for a while and nobody complained, it's probably not very high priority.

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformUpdater.java (hunk 2 above)
Comment (smalyshev) [reply x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/action/TransformUpdater.java:340]: OK I'll make a JIRA for this.

**Review by quux00 — APPROVED** [review]
LGTM. Let's go ahead with merging.
