### PR TITLE
Fix handling of points_only with term strategy in geo_shape

### LINKED ISSUE #31707: Can’t change settings for an index with a geo_shape field using term strategy
**Elasticsearch version**: 6.3.0

**Plugins installed**: Vanilla found.io installation

**JVM version**: Vanilla found.io installation

**OS version**: Vanilla found.io options

**Description of the problem including expected versus actual behavior**:
When creating an index with a field of type geo_shape that uses the term strategy, I've observed some strange behaviors (this is in hosted 6.3.0).

Creating an index with a geoshape field set to term strategy takes just over 30 seconds (feeling very much like a timeout), but does ultimately report success. However, if you subsequently try to change any settings, you get a mapper parsing error about the original supposedly successfully created mapping having an unsupported points_only field (whether or not not you explicitly specified it, or just got it from using the term strategy).

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create mapping 
```
PUT /example
{
  "mappings": {
    "doc": {
      "properties": {
        "location": {
          "type": "geo_shape",
          "tree": "quadtree",
          "precision": "10m",
          "strategy": "term"
        }
      }
    }
  }
}
```
 2. Change a setting
 ```
PUT /example/_settings
{
 "settings": {"refresh_interval": "-1"} 
}
```
Response 
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Mapping definition for [location] has unsupported parameters:  [points_only : true]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [doc]: Mapping definition for [location] has unsupported parameters:  [points_only : true]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Mapping definition for [location] has unsupported parameters:  [points_only : true]"
    }
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by imotov**
Fixes 2 issues that together cause errors during index creation
with geo_shapes that use the term strategy. The term strategy changes
the default for points_only parameter, but this wasn't taken into
account during serialization. So, setting the term strategy would add
`"points_only": true` to serialization. At the same time if the term
strategy would also cause the `points_only` setting to be not marked as
a processed element during parsing, which would cause index creation to
fail with the error: `Mapping definition for [location] has unsupported`
`parameters:  [points_only : true]`.

Fixes #31707

### CODE REVIEW

**Comment by imotov** [comment]
Not sure if it should be backported to 6.3 as well. It seems to be a pretty bad issue essentially making `strategy: term` unusable.

File: server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java [hunk 1]
```diff
@@ -230,13 +231,18 @@ public GeoShapeFieldMapper build(BuilderContext context) {
...
-                    && builder.fieldType().strategyName.equals(SpatialStrategy.TERM.getStrategyName()) == false) {
-                    boolean pointsOnly = XContentMapValues.nodeBooleanValue(fieldNode, name + "." + Names.STRATEGY_POINTS_ONLY);
-                    builder.fieldType().setPointsOnly(pointsOnly);
+                } else if (Names.STRATEGY_POINTS_ONLY.equals(fieldName)) {
+                    pointsOnly = XContentMapValues.nodeBooleanValue(fieldNode, name + "." + Names.STRATEGY_POINTS_ONLY);
                     iterator.remove();
                 }
             }
+            if (pointsOnly != null) {
+                if (builder.fieldType().strategyName.equals(SpatialStrategy.TERM.getStrategyName()) && pointsOnly == false) {
```
Comment (jpountz) [inline server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java]: `pointsOnly == false` is using reference equality on an object, it works because Boolean.valueOf(boolean) returns singletons, but let's still try to compare the wrapped boolean instead?

**Review by jpountz — APPROVED** [review]

File: server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java (hunk 1 above)
Comment (imotov) [reply server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java]: I might be wrong, but I was under impression that this changed recently (around v1.5). According to the [spec](https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.21.2) "If one of the operands is of type Boolean, it is subjected to unboxing conversion." So, I don't think we have a reference equality, but instead auto-unboxing of `pointsOnly` and boolean comparison with `false`. I also looked at the bytecode for this line and if I am reading it correctly it looks like unboxing and jump if nonzero.
```
    LINENUMBER 240 L40
    ALOAD 4
    INVOKEVIRTUAL org/elasticsearch/index/mapper/GeoShapeFieldMapper$Builder.fieldType ()Lorg/elasticsearch/index/mapper/GeoShapeFieldMapper$GeoShapeFieldType;
    INVOKESTATIC org/elasticsearch/index/mapper/GeoShapeFieldMapper$GeoShapeFieldType.access$000 (Lorg/elasticsearch/index/mapper/GeoShapeFieldMapper$GeoShapeFieldType;)Ljava/lang/String;
    GETSTATIC org/elasticsearch/common/geo/SpatialStrategy.TERM : Lorg/elasticsearch/common/geo/SpatialStrategy;
    INVOKEVIRTUAL org/elasticsearch/common/geo/SpatialStrategy.getStrategyName ()Ljava/lang/String;
    INVOKEVIRTUAL java/lang/String.equals (Ljava/lang/Object;)Z
    IFEQ L41
    ALOAD 5
    INVOKEVIRTUAL java/lang/Boolean.booleanValue ()Z
    IFNE L41
```
What do you think?

Comment (jpountz) [reply server/src/main/java/org/elasticsearch/index/mapper/GeoShapeFieldMapper.java]: I didn't know that, thanks for checking!

**Comment by jpountz** [comment]
LGTM
