### PR TITLE
TransportClient: Add exception when using plugin.types, to help migration to addPlugin

### LINKED ISSUE #15693: NPE when using the delete-by-query plugin from the TransportClient
I installed the delete-by-query plugin on the elasticsearch server and verified that it works fine using the REST interface:

```JSON
DELETE /index/type/_query?routing=18
{
  "query": { 
    "term": {
      "id": 1558
    }
  }
}
```

However when I try to use the delete-by-query plugin from the `TransportClient`  I get an NPE. 

```JAVA
DeleteByQueryResponse response = new DeleteByQueryRequestBuilder(client, DeleteByQueryAction.INSTANCE)
  .setIndices(index)
  .setTypes(type)
  .setRouting(18)
  .setQuery(QueryBuilders.termQuery("id", id))
.execute().actionGet();
```

Exception: 
```JAVA
java.lang.NullPointerException
	at org.elasticsearch.client.transport.support.TransportProxyClient$1.doWithNode(TransportProxyClient.java:58)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:212)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:283)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
	at org.elasticsearch.action.deletebyquery.DeleteByQueryRequestBuilder.execute(DeleteByQueryRequestBuilder.java:172)
```

I also added `plugin.types=org.elasticsearch.plugin.deletebyquery.DeleteByQueryPlugin` to the `TransportClient` settings.

This is with the 2.1.1 version of the Java API and ES Server

### PR DESCRIPTION
**Pull request by rjernst**
closes #15693

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/client/transport/TransportClient.java [hunk 1]
```diff
@@ -113,6 +113,9 @@ public Builder addPlugin(Class<? extends Plugin> pluginClass) {
          * Builds a new instance of the transport client.
          */
         public TransportClient build() {
+            if (settings.get("plugin.types") != null) {
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClient.java]: Just check the `settings` when they are set on the builder and throw an `IllegalArgumentException` there?

File: core/src/main/java/org/elasticsearch/client/transport/TransportClient.java [hunk 2]
```diff
@@ -113,6 +113,9 @@ public Builder addPlugin(Class<? extends Plugin> pluginClass) {
...
+                throw new IllegalArgumentException("plugin.types is no longer supported. Use the addPlugin method on TransportClient.");
```
Comment (jasontedor) [inline core/src/main/java/org/elasticsearch/client/transport/TransportClient.java]: If not throwing when the `settings` are passed to the builder, maybe `IllegalStateException` since `IllegalArgumentException` is really meant for method parameters gone bad?

**Comment by jasontedor** [comment]
@rjernst Left a couple questions, otherwise LGTM.

**Comment by rjernst** [comment]
I moved the check as suggested.

**Comment by rjernst** [comment]
Pushed to 2.2 as well: b82c86a
