### PR TITLE
[TEST] Fix log tail mocking in native process unit tests

### LINKED ISSUE #56796: [CI] AbstractNativeProcessTests.testWriteRecord fails with failed interaction assertion
We've had three failures in the past 24 hours.

```
org.elasticsearch.xpack.ml.process.AbstractNativeProcessTests > testWriteRecord FAILED
    org.mockito.exceptions.verification.NoInteractionsWanted: 
    No interactions wanted here:
    -> at org.elasticsearch.xpack.ml.process.AbstractNativeProcessTests.terminateExecutorService(AbstractNativeProcessTests.java:78)
    But found this interaction:
    -> at org.elasticsearch.xpack.ml.process.AbstractNativeProcess.detectCrash(AbstractNativeProcess.java:129)
    Actually, above is the only interaction with this mock.
        at __randomizedtesting.SeedInfo.seed([BBFE72CBFBEC019:913B7E1C30BA478B]:0)
        at org.elasticsearch.xpack.ml.process.AbstractNativeProcessTests.terminateExecutorService(AbstractNativeProcessTests.java:78)
```

**Build scan**:
https://gradle-enterprise.elastic.co/s/zvwew6dsczjcs/tests/:x-pack:plugin:ml:test/org.elasticsearch.xpack.ml.process.AbstractNativeProcessTests/testWriteRecord#1
https://gradle-enterprise.elastic.co/s/64gvt3l54h67w/tests/:x-pack:plugin:ml:test/org.elasticsearch.xpack.ml.process.AbstractNativeProcessTests/testWriteRecord#1
https://gradle-enterprise.elastic.co/s/gneku5hpymwgu/tests/:x-pack:plugin:ml:test/org.elasticsearch.xpack.ml.process.AbstractNativeProcessTests/testWriteRecord#1

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.process.AbstractNativeProcessTests.testWriteRecord" -Dtests.seed=BBFE72CBFBEC019 -Dtests.security.manager=true -Dtests.locale=vi-VN -Dtests.timezone=Europe/Zurich -Dcompiler.java=14 -Druntime.java=11
```

**Reproduces locally?**:
Didn't reproduce locally for m.

**Applicable branches**:
Looks like we have failures on `master` and `7.x`

### PR DESCRIPTION
**Pull request by droberts195**
This is a followup to #56632. Tests that had to be changed
to mock the C++ log handler more accurately need to be more
careful about when that stream ends, as ending of that
stream is used to detect crashes in the production system.

Fixes #56796

### CODE REVIEW

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcessTests.java [hunk 1]
```diff
@@ -82,29 +87,34 @@ public void testStart_DoNotDetectCrashWhenNoInputPipeProvided() throws Exception
...
+            // Not detecting a crash is confirmed in terminateExecutorService()
         }
     }
 
     public void testStart_DoNotDetectCrashWhenProcessIsBeingKilled() throws Exception {
         try (AbstractNativeProcess process = new TestNativeProcess()) {
             process.start(executorService);
             process.kill();
-            wait.countDown();
+            mockNativeProcessLoggingStreamEnds.countDown();
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcessTests.java:109]: Should it be in the `finally` block just like the other tests? If not, what's the difference?

Comment (droberts195) [reply x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcessTests.java:109]: This is testing what happens if the process is killed.  The finally block will run after `close()`.

This does actually create an inefficiency, in that if `start()` or `kill()` throws an exception then the countdown won't happen and the `@After` method will block for 10 seconds waiting for the countdown that will never come.

This was always a problem even before my changes, but I will change the test so that it doesn't use a try-with-resources so this can be avoided.

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcessTests.java [hunk 2]
```diff
@@ -43,18 +43,23 @@
     private ProcessPipes processPipes;
     private Consumer<String> onProcessCrash;
     private ExecutorService executorService;
-    private CountDownLatch wait = new CountDownLatch(1);
+    // This must be counted down at the point where a real native process would terminate, thus
+    // causing an end-of-file on the stream tailing its logs.  This will be:
+    // 1) After close() for jobs that stop gracefully
+    // 2) After kill() for jobs that are forcefully terminated
+    // 3) After a simulated crash when we test simulated crash
+    private CountDownLatch mockNativeProcessLoggingStreamEnds = new CountDownLatch(1);
```
Comment (przemekwitek) [inline x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcessTests.java:51]: `final`?

**Review by przemekwitek — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcessTests.java (hunk 1 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/test/java/org/elasticsearch/xpack/ml/process/AbstractNativeProcessTests.java:109]: > This does actually create an inefficiency, in that if `start()` or `kill()` throws an exception then the countdown won't happen and the `@After` method will block for 10 seconds waiting for the countdown that will never come.

Actually this isn't true.  Terminating the threadpool will interrupt all the threads in it, and that will exit the countdown `await()` with an `InterruptedException`.  So it wouldn't block for 10 seconds.

Still I will change the code as it obviously wasn't clear what was going on.
