### PR TITLE
[Test] make cluster state blocking more reliable in IndicesStoreIntegrationTests.indexCleanup() 

### LINKED ISSUE #11989: [CI] fix IndicesStoreIntegrationTests.indexCleanup
Despite many efforts to fix this test it still fails every now and then. The reason for failure does not seem to be the result of a bug but more a test issue. The test uses slow cluster state processing disruption to simulate cluster state processing delays when shards are deleted from a node due to relocation and this disruption sometimes seems to block more than just the needed cluster state update. 
Latest failure is here: http://build-us-00.elastic.co/job/es_core_1x_suse/958/
I will mute this until we have a better way to test this.

### PR DESCRIPTION
**Pull request by brwe**
IndicesStoreIntegrationTests.indexCleanup() tests if the shard files on disk are actually removed
after relocation. In particular it tests the following:
Whenever a node deletes a shard because it was relocated somewhere else, it first
checks if enough other copies are started somewhere else. The node sends a
ShardActiveRequest to the nodes that should have a copy.
The nodes that receive this request check if the shard is in state STARTED in which case
they respond with true. If they have the shard in POST_RECOVERY they register a cluster state
observer that checks at each update if the shard has moved to STARTED and respond with true when
this happens.

To test that the cluster state observer mechanism actually works, the latter can be triggered by
blocking the cluster state processing when a recover starts and only unblocking it shortly
after the node receives the ShardActiveRequest.

This is more reliable than using random cluster state processing delays
because the random delays make it hard to reason about different timeouts
that can be reached.

closes #11989

### CODE REVIEW

**Comment by brwe** [comment]
@bleskes can you take a look?

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java [hunk 1]
```diff
@@ -306,4 +307,46 @@ public boolean apply(Object o) {
...
+            this.disruption = disruption;
+            this.logger = logger;
+        }
+
+        @Override
+        public void receivedRequest(long requestId, String action) {
+            if (action.equals(IndicesStore.ACTION_SHARD_EXISTS)) {
+                try {
+                    // wait a little to make sure cluster first shard active request fails. This should trigger registering a state observer.
+                    sleep(50);
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: I'm not sure this does what you want? it blocks the thread handling the request. Maybe use latches here to signal events and control the disruption from the test? I think it will also be clearer to read.

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java [hunk 2]
```diff
@@ -306,4 +307,46 @@ public boolean apply(Object o) {
...
+                } catch (InterruptedException e) {
+                    logger.info("Interrupted while waiting", e);
+                }
+                logger.info("received: {}, will stop blocking cluster state processing", action);
+                disruption.stopDisrupting();
+            }
+            if (action.equals(RecoveryTarget.Actions.PREPARE_TRANSLOG)) {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: can we use org.elasticsearch.indices.recovery.RecoverySource.Actions#START_RECOVERY ? it's a better indication that the recovery is started.

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java [hunk 3]
```diff
@@ -115,24 +119,19 @@ public void indexCleanup() throws Exception {
...
-            disruption = new SlowClusterStateProcessing(node_3, getRandom(), 0, 0, 1000, 2000);
+            SingleNodeDisruption disruption = new BlockClusterStateProcessing(node_3, getRandom());
             internalCluster().setDisruptionScheme(disruption);
-            disruption.startDisrupting();
+            MockTransportService transportServiceNode3 = (MockTransportService) internalCluster().getInstance(TransportService.class, node_3);
+            transportServiceNode3.addTracer(new Tracer(disruption, logger));
         }
         internalCluster().client().admin().cluster().prepareReroute().add(new MoveAllocationCommand(new ShardId("test", 0), node_1, node_3)).get();
         clusterHealth = client().admin().cluster().prepareHealth()
                 .setWaitForNodes("4")
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: why wait for nodes?

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java [hunk 4]
```diff
@@ -69,6 +73,7 @@ protected Settings nodeSettings(int nodeOrdinal) { // simplify this and only use
                 // which is between 1 and 2 sec can cause each of the shard deletion requests to timeout.
                 // to prevent this we are setting the timeout here to something highish ie. the default in practice
                 .put(IndicesStore.INDICES_STORE_DELETE_SHARD_TIMEOUT, new TimeValue(30, TimeUnit.SECONDS))
+                .put(TransportModule.TRANSPORT_SERVICE_TYPE_KEY, MockTransportService.class.getName())
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: can we reduce the publishing timeout here, to speed the test. It now takes at least 30s because of the disruption, right?

**Comment by bleskes** [comment]
Looks great. Left some comments.

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java (hunk 1 above)
Comment (brwe) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: uh. indeed....will change

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java (hunk 4 above)
Comment (brwe) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: cluster state updates are now only blocked between relocation start and end and relocation does not seem to need a new cluster state to finish. if another cluster state is published it will only be delayed for as long as relocation takes. the test now takes about 2s.

**Comment by brwe** [comment]
Thanks for the review! I addressed all comments. Let me know if this is what you meant with the latches for signaling.

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java [hunk 5]
```diff
@@ -306,4 +327,45 @@ public boolean apply(Object o) {
...
+     * respond with "true". If they have the shard in POST_RECOVERY they register a cluster state
+     * observer that checks at each update if the shard has moved to STARTED.
+     * To test that this mechanism actually works, this can be triggered by blocking the cluster
+     * state processing when a recover starts and only unblocking it shortly after the node receives
+     * the ShardActiveRequest.
+     */
+    static class ReclocationStartEndTracer extends MockTransportService.Tracer {
+        private final ESLogger logger;
+        private final CountDownLatch beginRelocationLatch;
+        private final CountDownLatch endRelocationLatch;
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: can we name this recievedShardExistsRequest?

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java [hunk 6]
```diff
@@ -143,6 +158,10 @@ public void indexCleanup() throws Exception {
 
     }
 
+    private void moveShardFromNode1ToNode3(String node_1, String node_3) {
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: can inline this method? it's just a one liner and the name is kind of funky - node 1 and node 3 are baked into it.

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java (hunk 4 above)
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: fair enough

File: core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java [hunk 7]
```diff
@@ -115,24 +123,31 @@ public void indexCleanup() throws Exception {
...
+            disruption.stopDisrupting();
+        } else {
+            moveShardFromNode1ToNode3(node_1, node_3);
         }
-        internalCluster().client().admin().cluster().prepareReroute().add(new MoveAllocationCommand(new ShardId("test", 0), node_1, node_3)).get();
         clusterHealth = client().admin().cluster().prepareHealth()
-                .setWaitForNodes("4")
                 .setWaitForRelocatingShards(0)
                 .get();
+        logClusterState();
```
Comment (bleskes) [inline core/src/test/java/org/elasticsearch/indices/store/IndicesStoreIntegrationTests.java]: do we need this?

**Comment by bleskes** [comment]
LGTM. Left some minor comments. No need for another review..
