### PR TITLE
Fixed incomplete JSON body on count request making org.elasticsearch.rest.action.RestActions#parseTopLevelQueryBuilder go into endless loop

### LINKED ISSUE #26083: Node blocked due to malformed JSON on _count API
**Elasticsearch version**:
5.5.1

**Plugins installed**:
ingest-geoip, ingest-user-agent, x-pack

**JVM version**:
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)

**OS version**:
Linux e012087cca9f 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
_count API doesn't return a 400 status "parsing_exception" error when sending data matching `".*"` regex pattern.

**Steps to reproduce**:
```
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -d docker.elastic.co/elasticsearch/elasticsearch:5.5.1

curl -XGET -u elastic:changeme -H 'Content-Type: application/json' http://localhost:9200/*/_count -d '""'

# (don't forget to kill the container to save your CPU :-)
```

FYI:
- _search works with the same data (`""`) returning a 400 status "parsing_exception" error
- _count returns same error on data like `a`, `"`, etc. but the problem occurs with data matching `".*"` regex pattern

### PR DESCRIPTION
**Pull request by original-brownbear**
Took a shot at #26083 here :) 

The problem is that `parser.nextToken()` will return `null` when hitting the end a JSON string. So if the String is partly valid like an empty string:

```java
for (XContentParser.Token token = parser.nextToken(); token != XContentParser.Token.END_OBJECT; token = parser.nextToken()) {
```

will loop forever because `nextToken()` will keep returning `null`.
You can see this by one core going to 100% load while a request like:

```sh
curl -XGET  -H 'Content-Type: application/json' http://localhost:9200/\*/_count -d '""'
```

blocks forever.

In `5.2` this seems to have been caught in the logic guessing the content type of the request and the above example returned:

```sh
{"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to derive xcontent"}],"type":"parse_exception","reason":"Failed to derive xcontent"},"status":400}%
```

Since this is no longer the cause of the problem, I took a shot at a more appropriate error and it now returns:

```sh
"error":{"root_cause":[{"type":"parsing_exception","reason":"Failed to parse","line":1,"col":1}],"type":"parsing_exception","reason":"Failed to parse","line":1,"col":1,"caused_by":{"type":"e_o_f_exception","reason":"Unexpected end of JSON request body."}},"status":400}%
```

Fixes #26083

### CODE REVIEW

File: core/src/main/java/org/elasticsearch/rest/action/RestActions.java [hunk 1]
```diff
@@ -244,6 +245,9 @@ private static QueryBuilder parseTopLevelQueryBuilder(XContentParser parser) {
         try {
             QueryBuilder queryBuilder = null;
             for (XContentParser.Token token = parser.nextToken(); token != XContentParser.Token.END_OBJECT; token = parser.nextToken()) {
+                if (token == null) {
+                    throw new EOFException("Unexpected end of JSON request body.");
```
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: I'd rather like to have a check outside the parsing loop that asserts that the first token the parser emmits is XContentParser.Token.START_OBJECT. I think its save to assume we are expecting full json objects. I'd also just throw a ParsingException in that case.

File: core/src/test/java/org/elasticsearch/rest/action/RestActionsTests.java [hunk 2]
```diff
@@ -66,6 +66,14 @@ public void testParseTopLevelBuilderEmptyObject() throws IOException {
         }
     }
 
+    public void testParseTopLevelBuilderMalformedJson() throws IOException {
+        String requestBody = "\"\"";
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/rest/action/RestActionsTests.java]: Can you add a test for the cases `"\"someString\""` and maybe also make sure that we don't barf for the empty String, but simply return null like in the case of "{}"?

**Review by cbuescher — CHANGES_REQUESTED** [review]

**Comment by cbuescher** [comment]
@original-brownbear thanks, I left two small comments. I was suprised to see that we allow creating XContentParser instances from input Strings like `"foo"`, I would have expected the Jackson JsonFactory to barf on that. I talked to @tlrx about this and unfortunately there is some open debate about whether a single string value is considered as valid JSON, otherwise I would prefer to reject request bodies of that kind altogether but that doesn't seem to be an option atm.

File: core/src/main/java/org/elasticsearch/rest/action/RestActions.java (hunk 1 above)
Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: @cbuescher but if we just verify that the first token is` XContentParser.Token.START_OBJECT`, we'll still see this infinite loop for `"{"` for example. Do you mean we want to accept that?
Is it really a good idea to have the behavior of `org.elasticsearch.rest.action.RestActions#parseTopLevelQueryBuilder` be to loop forever on part of a valid JSON request? :)

Comment (tlrx) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: > we'll still see this infinite loop for "{" for example.

I'd expect the parser to throw an exception on this?

> Is it really a good idea to have the behavior of org.elasticsearch.rest.action.RestActions#parseTopLevelQueryBuilder be to loop forever on part of a valid JSON request? :)

Of course not, and this is not what @cbuescher said.

Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: @tlrx

> I'd expect the parser to throw an exception on this?

Currently, it doesn't  throw on half a valid JSON request that's where my confusion was coming from. Also just goes into the infinite loop then.

Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: I just implemented the tests @cbuescher asked for below (good call obviously it started throwing on empty string now too :)).
The best fix I see that includes the empty string case as well would be to do this:

```java
            if (parser.nextToken() == null) {
                return null;
            }
            for (XContentParser.Token token = parser.nextToken(); token != XContentParser.Token.END_OBJECT; token = parser.nextToken()) {
                if (token == null) {
                    throw new ParsingException(parser.getTokenLocation(), "Failed to parse");
                }
```

if the first token isn't a `XContentParser.Token.START_OBJECT` the parser throws eventually anyways and we handle the empty string case without much code, how about it? :)

Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: updated the PR with the above suggestion

File: core/src/test/java/org/elasticsearch/rest/action/RestActionsTests.java (hunk 2 above)
Comment (original-brownbear) [reply core/src/test/java/org/elasticsearch/rest/action/RestActionsTests.java]: Extended tests to cover this :)

File: core/src/main/java/org/elasticsearch/rest/action/RestActions.java (hunk 1 above)
Comment (cbuescher) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: That won't loop forever, as far as I can see this will run into a JsonEOFException because if the unmatched brackets eventually.

Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: @cbuescher I tried it out by hand:

```sh
curl -XGET  -H 'Content-Type: application/json' http://localhost:9200/\*/_count -d '"{"'
```

blocks forever

Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: Worse yet, it prevents ES from exiting even after I kill `curl`

Comment (cbuescher) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: Thats a String token though...

Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: Wops my bad :) you're right, '{' dies just fine.
So basically we have `return null` if the first token is `null` (to cover the empty string case), throw if it's not null and not `ContentParser.Token.START_OBJECT` and leave the loop untouched? :)

Comment (cbuescher) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: ++

Comment (cbuescher) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: And because this is really a bit confusing (I was suprised by some of this myself), maybe add some of the above cases in tests. Or wdyt @tlrx

Comment (tlrx) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: @cbuescher I agree

Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: @cbuescher @tlrx done :) Added all the discussed cases here https://github.com/elastic/elasticsearch/pull/26680/files#diff-2098a5df6345871e4c3fdb934d3f9f49R72

File: core/src/main/java/org/elasticsearch/rest/action/RestActions.java [hunk 3]
```diff
@@ -243,6 +243,12 @@ public RestResponse buildResponse(NodesResponse response, XContentBuilder builde
     private static QueryBuilder parseTopLevelQueryBuilder(XContentParser parser) {
         try {
             QueryBuilder queryBuilder = null;
+            XContentParser.Token first = parser.nextToken();
+            if (first == null) {
+                return null;
+            } else if (first != XContentParser.Token.START_OBJECT) {
+                throw new ParsingException(parser.getTokenLocation(), "Failed to parse");
```
Comment (cbuescher) [inline core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: Can you make the message a little bit more descriptive, since we know whats wrong in this case?

File: core/src/test/java/org/elasticsearch/rest/action/RestActionsTests.java [hunk 4]
```diff
@@ -59,10 +60,21 @@ public void testParseTopLevelBuilder() throws IOException {
...
+            }
+        }
+    }
+
+    public void testParseTopLevelBuilderMalformedJson() throws IOException {
+        for(String requestBody : Arrays.asList("\"\"", "\"someString\"", "{", "\"{\"")) {
+            try (XContentParser parser = createParser(JsonXContent.jsonXContent, requestBody)) {
+                ParsingException exception =
+                    expectThrows(ParsingException.class, () -> RestActions.getQueryContent(parser));
+                assertEquals("Failed to parse", exception.getMessage());
```
Comment (cbuescher) [inline core/src/test/java/org/elasticsearch/rest/action/RestActionsTests.java]: If the error message is different, maybe you can differentiate between the case where we detect a missing START_OBJECT and the case where the underlying Jackson parser throws.

**Review by cbuescher — COMMENTED** [review]
Thanks for the change, I left two other small comments regarding the error message and the corresponding test. The rest looks good to me.

File: core/src/main/java/org/elasticsearch/rest/action/RestActions.java (hunk 3 above)
Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: @cbuescher sure, how about `"Invalid JSON object, first token must be '{' but was 'VALUE_STRING'"` ?

File: core/src/test/java/org/elasticsearch/rest/action/RestActionsTests.java (hunk 4 above)
Comment (original-brownbear) [reply core/src/test/java/org/elasticsearch/rest/action/RestActionsTests.java]: @cbuescher sure already done locally, just waiting for an answer on the above :)

**Comment by javanna** [comment]
Question: is this a problem with the count api only? Seems like the same could happen with any API, or do we have protection in other places already?

File: core/src/main/java/org/elasticsearch/rest/action/RestActions.java (hunk 3 above)
Comment (cbuescher) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: It doesn't have to be JSON, we support Yaml, Cbor and Smile, so better to say we expected the beginning of an object or something along those lines.

**Comment by cbuescher** [comment]
@javanna As far as I can see the code path in question here (RestActions.getQueryContent()) is used by RestValidateQueryAction, RestCountAction (incl. the cat variant) and the RestExplainAction. In other places, e.g. for parsing in SearchSourceBuilder we already seem to have similar checks: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L962

**Comment by cbuescher** [comment]
> Seems like the same could happen with any API, or do we have protection in other places already?

And yes, I talked to @tlrx before and it seems we fixed some of these cases on a case by case basis, there might be other places left to check though, but this is outside of the scope of this PR I think. I would have prefered that XContent#createParser would reject these cases already but that seems not to be the case and more difficult to change.

File: core/src/main/java/org/elasticsearch/rest/action/RestActions.java (hunk 3 above)
Comment (cbuescher) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: Maybe do sth. similar as this: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L962

Comment (original-brownbear) [reply core/src/main/java/org/elasticsearch/rest/action/RestActions.java]: yea that looks perfect, sec adjusting :)

**Comment by original-brownbear** [comment]
@cbuescher exception message adjusted :)

**Review by cbuescher — APPROVED** [review]
@original-brownbear thanks a lot, looks good to me now. Let's just wait for CI to pass, there were some failures earlier on that I think were unrelated but just to be sure. 
Also, would you squash and shorten the commit title a little bit before merging? Since running into this bug can be quiet nasty, I think we should backport it to all active 6.x branches and the current 5.6 branch.

**Comment by original-brownbear** [comment]
Build all green here https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/4516/, squashing

**Comment by original-brownbear** [comment]
@cbuescher done, squashed with shorter commit message :)

**Comment by cbuescher** [comment]
@original-brownbear thanks, do you want to merge and do the backport or should I do it?

**Comment by original-brownbear** [comment]
@cbuescher I don't know how you guys are handling merging and backporting, probably safest for your repo if you do it this time around :)

**Comment by cbuescher** [comment]
@original-brownbear thanks again for this fix, I rewrote the commit message a bit and will merge this to the active 6.x branches and 5.6 now.

**Comment by original-brownbear** [comment]
@cbuescher thanks!
