### PR TITLE
[Transform] do not fail checkpoint creation due to global checkpoint mismatch

### LINKED ISSUE #48379: [ML] Unnecessary transform warning message is logged very often
Spotted in 7.4.0

In a multi-node environment, when running a continuous transform, the following warning is spammed in the logs occasionally:
```
[instance-0000000009] [some_transform_id] data frame transform encountered an exception: 
java.lang.RuntimeException: Failed to retrieve checkpoint due to Failed to create checkpoint
	at org.elasticsearch.xpack.dataframe.transforms.DataFrameTransformTask$ClientDataFrameIndexer.lambda$createCheckpoint$17(DataFrameTransformTask.java:1084) [data-frame-7.4.0.jar:7.4.0]
	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:70) [elasticsearch-7.4.0.jar:7.4.0]
...
```

After @hendrikmuhs investigated this, we found out that this is due to a mismatch of global checkpoints for the same shard (replicas). This is by design and it's nothing to worry about but the transform is paranoid and throws an exception. It should be safe to ignore the mismatch and e.g. take the max of all global checkpoints.

As a result, we should remove this message as it is unnecessary.

### PR DESCRIPTION
**Pull request by hendrikmuhs**
Take the max if global checkpoints mismatch instead of throwing an exception. It turned out global 
checkpoints can mismatch by design

fixes #48379

Severity: checkpoint creation can fail due to this issue in rare cases, however checkpoint creation is retried

### CODE REVIEW

File: x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java [hunk 1]
```diff
@@ -189,10 +189,11 @@ protected void getIndexCheckpoints (ActionListener<Map<String, long[]>> listener
...
                     if (checkpoints.containsKey(shard.getShardRouting().getId())) {
-                        // there is already a checkpoint entry for this index/shard combination, check if they match
-                        if (checkpoints.get(shard.getShardRouting().getId()) != globalCheckpoint) {
-                            throw new CheckpointException("Global checkpoints mismatch for index [" + indexName + "] between shards of id ["
-                                    + shard.getShardRouting().getId() + "]");
+                        // there is already a checkpoint entry for this index/shard combination
+                        // it's possible that replica shards report a different/higher global checkpoints
+                        // This is by design and not a problem, take the max() for this case
+                        if (checkpoints.get(shard.getShardRouting().getId()) < globalCheckpoint) {
+                            checkpoints.put(shard.getShardRouting().getId(), globalCheckpoint);
```
Comment (benwtrent) [inline x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/checkpoint/DefaultCheckpointProvider.java]: this whole if clause could then be changed to something similar to 
```
checkpoints.compute(shard.getShardRouting().getId(), (shardId, cp) -> (cp == null) ? globalCheckpoint : Math.max(cp, globalCheckPoint))
```

**Review by benwtrent — APPROVED** [review]
minor simplification suggestion
