### PR TITLE
Fix terminate_after not honored for aggs when size=0

### LINKED ISSUE #126665: terminate_after is not honour when size = 0 and query has aggregations
When a query is not collecting hits (size = 0) and contains aggregations,  it does not honour the parameter `terminate_after` if defined. There are different incarnations of this bug depending on the value of `track_total_hits`. The two I have found out are:

1) if `track_total_hits` is false it will never terminate early and will completely ignore the `terminate_after` parameter.

2) if `track_total_hits` is true it might collect more documents that the one defined in `terminate_after` parameter.
iff one or more segments fully match the query (we are collecting all doxuments of that segment).

There might more edge cases.

### PR DESCRIPTION
**Pull request by reugn**
The fix adds `terminateAfterChecker == NO_OP_TERMINATE_AFTER_CHECKER` to the shortcut condition (that returned the aggs leaf collector unwrapped when the top docs collector early-terminated), ensuring that when `terminate_after` is active, collection always goes through `CompositeLeafCollector` where the per-document threshold check enforces early termination for aggregations.

Fixes #126665

### CODE REVIEW

**Review by spinscale — APPROVED** [review]

**Comment by reugn** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|9.4|[](https://github.com/elastic/elasticsearch/pull/146623)|
|✅|9.3|[](https://github.com/elastic/elasticsearch/pull/146624)|
|✅|9.2|[](https://github.com/elastic/elasticsearch/pull/146625)|
|✅|8.19|[](https://github.com/elastic/elasticsearch/pull/146626)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

File: server/src/main/java/org/elasticsearch/search/query/QueryPhaseCollector.java [hunk 1]
```diff
@@ -172,9 +172,11 @@ public LeafCollector getLeafCollector(LeafReaderContext context) throws IOExcept
...
         final LeafCollector aggsLeafCollector = alf;
 
-        if (topDocsLeafCollector == null && minScore == null) {
-            // top docs collector early terminated, we can avoid wrapping as long as we don't need to apply min_score.
-            // post_filter and terminate_after do not matter because they not applied to aggs collection anyways.
+        if (topDocsLeafCollector == null && minScore == null && terminateAfterChecker == NO_OP_TERMINATE_AFTER_CHECKER) {
+            // top docs collector early terminated, we can avoid wrapping as long as we don't need to apply min_score
+            // or check terminate_after. terminate_after must still be enforced via CompositeLeafCollector to limit
+            // the number of documents collected by the aggs collector.
+            // post_filter does not matter because it is not applied to aggs collection anyway.
```
Comment (javanna) [inline server/src/main/java/org/elasticsearch/search/query/QueryPhaseCollector.java:179]: I was trying to remember how this all works, and this fix seems appropriate: if only terminate after is set, but we don't collect docs, the top docs leaf collector is null, hence there is no additional overhead around collecting docs, but we leverage the terminate after checks that the composite leaf collector performs, on top of the aggs collection.

When it comes to using a combination of post filter and terminate after, I have some doubts, but I believe it's a super rare edge case. Post filter only affects docs collection and we are only collecting aggs. Should the terminate after check count all visited docs or only those that match the post filter? I believe we currently honour the post filter, and perhaps that's ok?

Comment (javanna) [reply server/src/main/java/org/elasticsearch/search/query/QueryPhaseCollector.java:179]: Great to see this issue fixed by the way, thanks!
