### PR TITLE
Fix `testPurgeCacheEntriesForDatabase` on Windows

### LINKED ISSUE #129635: [CI] GeoIpCacheTests testPurgeCacheEntriesForDatabase failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #8850 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/lhtmg7j274e6y)
- [elasticsearch-periodic-platform-support #8850 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/6bgzulh2phvvs)
- [elasticsearch-periodic-platform-support #8844 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/4enwfzobxsrbm)
- [elasticsearch-periodic-platform-support #8844 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/p2pwkrd5lzcdm)
- [elasticsearch-periodic-platform-support #8838 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/sjerhzgmw53qy)
- [elasticsearch-periodic-platform-support #8838 / windows-2025_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/bi5myvkrmyvwg)

**Reproduction Line:**
```
gradlew ":modules:ingest-geoip:test" --tests "org.elasticsearch.ingest.geoip.GeoIpCacheTests.testPurgeCacheEntriesForDatabase" -Dtests.seed=149993FC2FC4DA5 -Dtests.locale=ff-Latn-MR -Dtests.timezone=Pacific/Port_Moresby -Druntime.java=24
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.ingest.geoip.GeoIpCacheTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testPurgeCacheEntriesForDatabase),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected null, but was:<Mock for AbstractResponse, hashCode: 1755769235>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testPurgeCacheEntriesForDatabase
- [main] 3 consecutive failures in step windows-2025_checkpart1_platform-support-windows
- [main] 3 consecutive failures in step windows-2022_checkpart1_platform-support-windows
- [main] 6 failures in test testPurgeCacheEntriesForDatabase (3.1% fail rate in 192 executions)
- [main] 3 failures in step windows-2025_checkpart1_platform-support-windows (100.0% fail rate in 3 executions)
- [main] 3 failures in step windows-2022_checkpart1_platform-support-windows (100.0% fail rate in 3 executions)
- [main] 3 failures in pipeline elasticsearch-periodic-platform-support (100.0% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by PeteGillinElastic**
Our hypothesis is that the path is not round-tripping on Windows. This fixes the test by always using the canonical string for the path, when inserting and when purging.

Closes #129635

### CODE REVIEW

File: modules/ingest-geoip/src/test/java/org/elasticsearch/ingest/geoip/GeoIpCacheTests.java [hunk 1]
```diff
@@ -140,23 +141,24 @@ public void testPurgeCacheEntriesForDatabase() {
         GeoIpCache cache = new GeoIpCache(100);
         ProjectId projectId1 = randomUniqueProjectId();
         ProjectId projectId2 = randomUniqueProjectId();
-        String databasePath1 = "path/to/db1";
-        String databasePath2 = "path/to/db2";
+        // Turn the path strings into Paths to ensure that
```
Comment (prdoyle) [inline modules/ingest-geoip/src/test/java/org/elasticsearch/ingest/geoip/GeoIpCacheTests.java]: This comment seems a bit incomplete.

In any case, this might not even need a comment. It seems natural to use `Path` instead of `String` in a test exercising paths. 🤷‍♂️

**Review by prdoyle — APPROVED** [review]
The test seems reasonable, and looks like what we do elsewhere to accommodate Windows. If it passes `test-windows` then I think we're good to go.

File: modules/ingest-geoip/src/test/java/org/elasticsearch/ingest/geoip/GeoIpCacheTests.java (hunk 1 above)
Comment (prdoyle) [reply modules/ingest-geoip/src/test/java/org/elasticsearch/ingest/geoip/GeoIpCacheTests.java]: On the other hand, there are lots of `toString` which might lead someone to wonder: wouldn't this be simpler if it just used strings? So perhaps a comment is warranted after all.

Comment (PeteGillinElastic) [reply modules/ingest-geoip/src/test/java/org/elasticsearch/ingest/geoip/GeoIpCacheTests.java]: Yeah, I wanted to avoid the risk that something thinks they can safely simplify it, and the test passes the pre-merge checks, and we revert the fix.

Comment (PeteGillinElastic) [reply modules/ingest-geoip/src/test/java/org/elasticsearch/ingest/geoip/GeoIpCacheTests.java]: And thanks!

**Review by nielsbauman — APPROVED** [review]

**Comment by PeteGillinElastic** [comment]
Okay, I have made three attempts to get CI to pass, and I think it's failed three different times (at least two different times). The most recent one is in `:build-tools-internal:test` where five methods in `ReleaseNotesGeneratorTest` are failing. This PR is only touching one unit test, under `:modules:ingest-geoip:test`, which appears to be passing. So I'm going to go ahead and merge.
