### PR TITLE
[Transforms] fix bug when unsetting retention policy

### LINKED ISSUE #87688: [Transform] Error when removing retention policy
**Found in version**
- Observed in 8.2.3, but might exist longer

**Steps to reproduce**
On a multi node cloud cluster (might also work on a local multi node cluster):
- Create a transform with a retention policy
- Update the transform and remove the retention policy

**Expected result**
- The retention policy is removed

**Actual result**
- This sometimes results in an error:
```
An error occurred calling the API endpoint to update transforms.
Bad Request: [illegal_argument_exception: [illegal_argument_exception] Reason: 
Unknown NamedWriteable [org.elasticsearch.xpack.core.transform.transforms.RetentionPolicyConfig][null_retention_policy]]:
Unknown NamedWriteable [org.elasticsearch.xpack.core.transform.transforms.RetentionPolicyConfig][null_retention_policy]
```

**Additional information**
- Quote from slack discussion with @benwtrent:
  > It wouldn’t happen if you hit a node that can execute the update immediately without serializing to a different node

### PR DESCRIPTION
**Pull request by benwtrent**
It is currently not possible to unset the retention policy in a typical multi-node cluster. 

This commit fixes that bug. If unsetting the retention policy failed, it would fail looking like the following error:

```
An error occurred calling the API endpoint to update transforms.
Bad Request: [illegal_argument_exception: [illegal_argument_exception] Reason: 
Unknown NamedWriteable [org.elasticsearch.xpack.core.transform.transforms.RetentionPolicyConfig][null_retention_policy]]:
Unknown NamedWriteable [org.elasticsearch.xpack.core.transform.transforms.RetentionPolicyConfig][null_retention_policy]
```

closes: https://github.com/elastic/elasticsearch/issues/87688

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackClientPlugin.java [hunk 1]
```diff
@@ -534,6 +535,11 @@ public List<NamedWriteableRegistry.Entry> getNamedWriteables() {
                     TransformField.TIME.getPreferredName(),
                     TimeRetentionPolicyConfig::new
                 ),
+                new NamedWriteableRegistry.Entry(
```
Comment (davidkyle) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackClientPlugin.java:538]: `TransformNamedXContentProvider` is also missing the `NullRetentionPolicyConfig` named writable

Comment (benwtrent) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackClientPlugin.java:538]: @davidkyle it isn't required. This thing is never written to XContent. But I can add it for completeness.

Comment (davidkyle) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackClientPlugin.java:538]: Please do I think it is worth having to avoid a similar problem in future

**Review by davidkyle — APPROVED** [review]
LGTM
