### PR TITLE
Fix concurrent refresh of tokens

### LINKED ISSUE #54289: It's not possible to use newly refreshed access token while the "original" refresh token is still being processed
It seems we hit an issue somewhere in a token management subsystem. The issue description is a bit confusion, but here are the steps to reproduce:

1. Generate access/refresh token pair with a short lifetime (used `15s` in my tests)
2. Wait till access token expires
3. Simultaneously send two refresh token requests
4. When first request completes try to use newly refresh token within a request to `_authenticate` endpoint

It happens so that at the step `4.` first refresh request is still in progress and request to `_authenticate` with newly refreshed token at the same time fails with the following error:

> HTTP/1.1 401 Unauthorized  (application/json)
> WWW-Authenticate: Bearer realm="security"
> WWW-Authenticate: ApiKey
> WWW-Authenticate: Basic realm="security" charset="UTF-8"

> {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_security/_authenticate]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_security/_authenticate]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\"

/cc @jkakavas

### PR DESCRIPTION
**Pull request by jkakavas**
Our handling for concurrent refresh of access tokens suffered from
a race condition where:

1. Thread A has just finished with updating the existing token
document, but hasn't stored the new tokens in a new document
yet
2. Thread B attempts to refresh the same token and since the
original token document is marked as refreshed, it decrypts and
gets the new access token and refresh token and returns that to
the caller of the API.
3. The caller attempts to use the newly refreshed access token
immediately and gets an authentication error since Thread a still
hasn't finished writing the document.

This commit changes the behavior so that Thread B, would first try
to do a Get request for the token document where it expects that
the access token it decrypted is stored(with exponential backoff)
and will not respond until it can verify that it reads it in the
tokens index. That ensures that we only ever return tokens in a
response if they are already valid and can be used immediately

It also adjusts
TokenAuthIntegTests#testRefreshingMultipleTimesWithinWindowSucceeds
to test authenticating with the tokens each thread receives,
which fails without the fix.

Resolves: #54289

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/TokenAuthIntegTests.java [hunk 1]
```diff
@@ -387,8 +386,11 @@ public void testRefreshingMultipleTimesWithinWindowSucceeds() throws Exception {
         }
         completedLatch.await();
         assertThat(failed.get(), equalTo(false));
-        // Assert that we only ever got one access_token/refresh_token pair
-        assertThat(tokens.stream().distinct().collect(Collectors.toList()).size(), equalTo(1));
+        // Assert that we only ever got one anot(contccess_token/refresh_token pair
```
Comment (ywangd) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/TokenAuthIntegTests.java:389]: `anot(contccess_token` - probably some random extra keystrokes?

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/TokenAuthIntegTests.java [hunk 2]
```diff
@@ -387,8 +386,11 @@ public void testRefreshingMultipleTimesWithinWindowSucceeds() throws Exception {
...
+        assertThat((int) tokens.stream().distinct().count(), equalTo(1));
+        // Assert that all requests from all threads could authenticate at the time they received the access token
+        // see: https://github.com/elastic/elasticsearch/issues/54289
+        assertThat(authStatuses, not(hasItem(RestStatus.UNAUTHORIZED)));
```
Comment (ywangd) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/TokenAuthIntegTests.java:393]: nits: alternatively, maybe we could verify all statuses are `OK` since `getAuthenticationResponseCode` always returns `OK` when no exception is thrown. It feels more precise.

**Review by ywangd — APPROVED** [review]
A few minor comments. Otherwise LGTM

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/TokenAuthIntegTests.java (hunk 2 above)
Comment (jkakavas) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/authc/TokenAuthIntegTests.java:393]: I was thinking in terms of testing for the bug this is solving but these all should be OK so I see your point, will address

**Comment by jkakavas** [comment]
Ping @tvernum

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java [hunk 3]
```diff
@@ -1092,10 +1095,51 @@ void decryptAndReturnSupersedingTokens(String refreshToken, RefreshTokenStatus r
...
+                        client.threadPool().schedule(
+                            () -> getTokenDocAsync(tokenDocId, tokensIndex, actionListener),
+                            backoff.next(), GENERIC);
+                    } else {
+                        logger.warn("could not get token document [{}] that should have been created after all retries",
+                            tokenDocId);
+                        onFailure.accept(invalidGrantException("could not refresh the requested token"));
+                    }
+                };
+                getTokenDocAsync(tokenDocId, tokensIndex, new ActionListener<>() {
```
Comment (tvernum) [inline x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java:1115]: I think this, and the call above should explicitly _not_ fetch the source since we only care about an exists check.

**Review by tvernum — APPROVED** [review]
LGTM, with 1 suggestion for optimization

File: x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java (hunk 3 above)
Comment (jkakavas) [reply x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java:1115]: Yes, agreed ! Thanks
