### PR TITLE
Add slicing mode and fix operation-level reindex metrics

### LINKED ISSUE #138258: Reindex metrics can be inaccurate with slicing enabled
### Elasticsearch Version

8.16+ (Reindex metrics [introduced in 8.16](https://github.com/elastic/elasticsearch/pull/111845))

### Problem Description

[Reindex metrics](https://github.com/elastic/elasticsearch/blob/main/modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java) are currently emitted per slice if slicing is enabled, and emitted per whole operation if slicing is disabled. This leads to confusion because the meaning of metric like `es.reindex.duration.histogram` are different based on whether slicing is used in a reindex operation. It also leads to inaccurate metrics as the metrics for per operation and per slice are mixed together.

### Potential solution
Split the reindex metrics for operation level and per-slice level. Since each slice is an independent `BulkByScrollAction`, it may require adding a ref counting listener to record the operation level metrics after all slices are completed.

### Steps to Reproduce

Add slicing (eg. `reindex().setSlices(5).source("source")...`) in [this test](https://github.com/elastic/elasticsearch/blob/aa955f797803dd6cb73afda3bcd88bef1cbc592e/modules/reindex/src/internalClusterTest/java/org/elasticsearch/index/reindex/ReindexPluginMetricsIT.java#L156) will cause the test to fail with 5 metric counts instead of 1.

### PR DESCRIPTION
**Pull request by samxbr**
Adds a `es_reindex_slicing_mode` dimension to existing reindex metrics to capture what type of slicing is being used. Also fixed the reindex metrics to be operation-level, meaning each API call to reindex will count as a single reindex metric. Reindex with multiple slices will only emit a single metric instead of one per slice.

Closes https://github.com/elastic/elasticsearch/issues/138258
Closes https://github.com/elastic/elasticsearch-team/issues/2375

### CODE REVIEW

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java [hunk 1]
```diff
@@ -74,9 +78,47 @@ public void recordFailure(boolean remote, Throwable e) {
...
+        // slices resolved automatically from source index shard count (e.g. ?slices=auto)
+        AUTO("auto"),
+        // reindex request specifies a fixed slice count (e.g. ?slices=4)
+        FIXED("fixed"),
+        // reindex request specifies a slice id (e.g. "slice": { "id": 0, "max": 4 })
+        MANUAL("manual"),
+        // no slicing (e.g. ?slices=1)
+        NONE("none");
+
+        private final String value;
```
Comment (PeteGillinElastic) [inline modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java]: Nit: We could ditch this field and have `value()` return `name().toLowerCase(Locale.ROOT)`, couldn't we?

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java [hunk 2]
```diff
@@ -74,9 +78,47 @@ public void recordFailure(boolean remote, Throwable e) {
...
+        public String value() {
+            return value;
+        }
+    }
+
+    /**
+     * Determines the {@link SlicingMode} from a reindex request.
+     */
+    public static SlicingMode resolveSlicingMode(ReindexRequest request) {
+        if (request.getSearchRequest().source() != null && request.getSearchRequest().source().slice() != null) {
```
Comment (PeteGillinElastic) [inline modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java]: Nit: Do you know of a reason why `request.getSearchRequest().source()` would ever be null? I can't see why it would be, and it look like `ReindexRequest.validate()` will throw an NPE if it is. If I'm right, you can remove that check and fractionally simplify the code.

**Review by PeteGillinElastic — COMMENTED** [review]
Thanks Sam. This LGTM as it stands. But you have a merge conflict, and if that's with Szymon's change to implement relocation with slicing then I suspect that there might be some non-trivial work to be done in `Reindexer` to resolve it. (You already have a bunch of — unavoidably — fiddly stuff with multiply nested callbacks, and I have a nasty feeling that stuff has changed under you.) I think it's better if we hold off on approval until that's done.

Once you've dealt with the conflict, it might also be a good idea to ping Szymon and get him to look specifically at the changes to the callbacks in `Reindexer` as he probably knows that better than me.

**Comment by samxbr** [comment]
> Thanks Sam. This LGTM as it stands. But you have a merge conflict, and if that's with Szymon's change to implement relocation with slicing then I suspect that there might be some non-trivial work to be done in `Reindexer` to resolve it. (You already have a bunch of — unavoidably — fiddly stuff with multiply nested callbacks, and I have a nasty feeling that stuff has changed under you.) I think it's better if we hold off on approval until that's done.
> 
> Once you've dealt with the conflict, it might also be a good idea to ping Szymon and get him to look specifically at the changes to the callbacks in `Reindexer` as he probably knows that better than me.

Yeah I did expect there will be some conflict with Szymon's PR. @szybia to have a look as well

File: modules/reindex/src/internalClusterTest/java/org/elasticsearch/index/reindex/ReindexPluginMetricsIT.java [hunk 3]
```diff
@@ -211,13 +215,80 @@ public void testReindexMetricsWithBulkFailure() throws Exception {
...
+            assertThat(histograms.size(), equalTo(1));
+            assertThat(histograms.getFirst().attributes().get(ATTRIBUTE_NAME_SLICING_MODE), equalTo("auto"));
+            assertThat(histograms.getFirst().attributes().get(ATTRIBUTE_NAME_SOURCE), equalTo(ATTRIBUTE_VALUE_SOURCE_LOCAL));
+
+            List<Measurement> completions = testTelemetryPlugin.getLongCounterMeasurement(REINDEX_COMPLETION_COUNTER);
+            assertThat(completions.size(), equalTo(1));
+            assertNull(completions.getFirst().attributes().get(ATTRIBUTE_NAME_ERROR_TYPE));
+            assertThat(completions.getFirst().attributes().get(ATTRIBUTE_NAME_SLICING_MODE), equalTo("auto"));
+            assertThat(completions.getFirst().attributes().get(ATTRIBUTE_NAME_SOURCE), equalTo(ATTRIBUTE_VALUE_SOURCE_LOCAL));
         });
```
Comment (PeteGillinElastic) [inline modules/reindex/src/internalClusterTest/java/org/elasticsearch/index/reindex/ReindexPluginMetricsIT.java:329]: For completeness, should we have a test with manual slicing?

**Review by PeteGillinElastic — COMMENTED** [review]
This LGTM, but I'd also like @szybia to weigh in.

File: modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java [hunk 4]
```diff
@@ -516,14 +518,24 @@ private void assertReindexSuccessMetricsOnNode(final String nodeName, final bool
...
-                ? ReindexMetrics.ATTRIBUTE_VALUE_SOURCE_REMOTE
-                : ReindexMetrics.ATTRIBUTE_VALUE_SOURCE_LOCAL;
-            assertThat(completion.attributes().get(ReindexMetrics.ATTRIBUTE_NAME_SOURCE), equalTo(expectedSource));
+        assertThat(completions.size(), equalTo(1));
+        assertNull(completions.getFirst().attributes().get(ReindexMetrics.ATTRIBUTE_NAME_ERROR_TYPE));
+        final String expectedSource = isRemote ? ReindexMetrics.ATTRIBUTE_VALUE_SOURCE_REMOTE : ReindexMetrics.ATTRIBUTE_VALUE_SOURCE_LOCAL;
+        assertThat(completions.getFirst().attributes().get(ReindexMetrics.ATTRIBUTE_NAME_SOURCE), equalTo(expectedSource));
+        SlicingMode slicingMode = null;
+        if (slices == 0) {
+            slicingMode = SlicingMode.AUTO;
```
Comment (szybia) [inline modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java:597]: given my test does `slices = randomIntBetween(1, 5)`, don't think this will ever get tested here

i guess forgot about testing auto-slicing here, thoughts on adding that? i guess we could leave this as is for simplicity sake given tested elsewhere, but might also be nice for having auto-slicing tested here

i believe will need something like
1. `slices = randomIntBetween(0, 5)`
2. update `startAsyncThrottledLocalReindexOnNode` to set slices to `slices == 0 ? "auto" : Integer.toString(slices)`
3. update the `slices >= 2` checks/ternaries to `slices >= 2 || (slices == 0 && shards >= 2)`

WDYT?

File: modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java [hunk 5]
```diff
@@ -28,6 +28,7 @@
 import org.elasticsearch.plugins.Plugin;
```
Comment (szybia) [inline modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java:28]: given we're changing metrics, anything else we need to consider? 

1. do we have some existing dashboards that need updating
2. personal learning: what's the policy for changing metrics, no BwC concerns we need to think about?

File: modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java [hunk 6]
```diff
@@ -170,12 +170,20 @@ public void execute(BulkByScrollTask task, ReindexRequest request, Client bulkCl
...
                 reindexSslConfig,
                 request,
-                workerListenerWithRelocationAndMetrics(listenerWithRelocations, startTime, request.getRemoteInfo() != null),
+                workerListenerWithRelocationAndMetrics(listenerWithRelocations, task, request, startTime),
                 remoteVersion
             );
             searchAction.start();
         };
 
+        final ActionListener<BulkByScrollResponse> responseListener = wrapWithMetrics(
```
Comment (szybia) [inline modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java]: i'm assuming here you're handling both 1) leader with slices and 2) single slice so that they both record metrics but not individual slices

given we're going from `all workers record metrics` to `only leader/single slice records`, is there a way we can combine and only have one metric listener here? `workerListenerWithRelocationAndMetrics` made sense before but now it's a bit confusing

WDYT? lmk if i'm missing something, i'd have to play around with this in order to see whether it's doable and my point makes sense

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java [hunk 7]
```diff
@@ -74,9 +79,37 @@ public void recordFailure(boolean remote, Throwable e) {
...
-    private Map<String, Object> getAttributes(boolean remote) {
+    public enum SlicingMode {
+        // slices resolved automatically from source index shard count (e.g. ?slices=auto)
+        AUTO(),
+        // reindex request specifies a fixed slice count (e.g. ?slices=4)
+        FIXED(),
+        // reindex request specifies a slice id (e.g. "slice": { "id": 0, "max": 4 })
+        MANUAL(),
+        // no slicing (e.g. ?slices=1)
+        NONE();
```
Comment (szybia) [inline modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java]: real nit
```suggestion
        AUTO,
        // reindex request specifies a fixed slice count (e.g. ?slices=4)
        FIXED,
        // reindex request specifies a slice id (e.g. "slice": { "id": 0, "max": 4 })
        MANUAL,
        // no slicing (e.g. ?slices=1)
        NONE;
```

**Review by szybia — COMMENTED** [review]
initial review, haven't scanned tests yet 🚀

File: modules/reindex/src/test/java/org/elasticsearch/reindex/ReindexerTests.java [hunk 8]
```diff
@@ -309,6 +375,48 @@ private BulkByScrollResponse reindexResponseWithResumeInfo() {
...
 
+    private static BulkByScrollTask createNonSlicedWorkerTask() {
+        BulkByScrollTask task = new BulkByScrollTask(
+            1,
+            "test_type",
+            "test_action",
+            "test",
+            TaskId.EMPTY_TASK_ID,
+            Collections.emptyMap(),
+            false
```
Comment (szybia) [inline modules/reindex/src/test/java/org/elasticsearch/reindex/ReindexerTests.java]: nit, my thinking around dummy values is unless it's actually required for test, random?

same for others

```suggestion
            randomNonNegativeLong(),
            randomAlphaOfLength(10),
            randomAlphaOfLength(10),
            randomAlphaOfLength(10),
            TaskId.EMPTY_TASK_ID,
            Map.of(),
            randomBoolean()
```

File: modules/reindex/src/test/java/org/elasticsearch/reindex/ReindexMetricsTests.java [hunk 9]
```diff
@@ -40,64 +47,102 @@ public void createMetrics() {
...
-        // first metric
-        metrics.recordTookTime(secondsTaken, false);
+        metrics.recordTookTime(secondsTaken, false, SlicingMode.NONE);
 
         List<Measurement> measurements = registry.getRecorder().getMeasurements(InstrumentType.LONG_HISTOGRAM, REINDEX_TIME_HISTOGRAM);
         assertEquals(1, measurements.size());
         assertEquals(secondsTaken, measurements.getFirst().getLong());
         assertEquals(ATTRIBUTE_VALUE_SOURCE_LOCAL, measurements.getFirst().attributes().get(ATTRIBUTE_NAME_SOURCE));
+        assertEquals(
+            SlicingMode.NONE.name().toLowerCase(Locale.ROOT),
```
Comment (szybia) [inline modules/reindex/src/test/java/org/elasticsearch/reindex/ReindexMetricsTests.java]: nit, could just literal to save on LocS/complexity

same for others

```suggestion
            "none",
```

File: modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java (hunk 5 above)
Comment (samxbr) [reply modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java:28]: Good questions.
1. there's a reindex dashboard, the changes in this PR is compatible, so we don't need to update it. Though it would be nice to add a graph to aggregate reindex by slicing mode.
2. I considered this a bug in [the issue](https://github.com/elastic/elasticsearch/issues/138258) I opened, if we agreed than we should be fine to fix it without bwc concern

File: modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java (hunk 4 above)
Comment (samxbr) [reply modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java:597]: Let me give it a try adding test for auto

File: modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java (hunk 6 above)
Comment (samxbr) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java]: Good point, looking at it I think we could probably get rid of `workerListenerWithRelocationAndMetrics`

File: modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java
Comment (szybia) [inline modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java]: two Qs, from a higher-level without me needing to delve deeper into it:
1. is there a reason we've `listenerWithRelocations` here rather than `responseListener`?
2. thanks for removing `workerListenerWithRelocationAndMetrics`, that's one part of my comment, but with that gone, is there a reason we can't have the following at the top and pass `responseListener` everywhere? 🤔 what i'm thinking is `wrapWithMetrics` seems smart enough now to skip any metrics recordings where we don't want them
```java
        final ActionListener<BulkByScrollResponse> listenerWithRelocations = listenerWithRelocations(task, request, listener);
        final ActionListener<BulkByScrollResponse> responseListener = wrapWithMetrics(
            listenerWithRelocations,
            reindexMetrics,
            task,
            request,
            startTime
        );
```

File: modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java (hunk 4 above)
Comment (szybia) [reply modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java:597]: given you have tests for auto elsewhere, and this if is never triggered, thoughts on removing it and falling back to `fail("invalid slices value: " + slices);`?

this code makes it seem to readers that AUTO could happen here, but AFAICT that's not possible in this test

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java [hunk 10]
```diff
@@ -29,6 +32,8 @@ public class ReindexMetrics {
     public static final String ATTRIBUTE_VALUE_SOURCE_LOCAL = "local";
     public static final String ATTRIBUTE_VALUE_SOURCE_REMOTE = "remote";
 
+    public static final String ATTRIBUTE_NAME_SLICING_MODE = "es_reindex_slicing_mode";
```
Comment (szybia) [inline modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:35]: strikes me as a non-consistent name for an attribute, given the other names, look more like a metric name, thoughts?

```suggestion
    public static final String ATTRIBUTE_NAME_SLICING_MODE = "slicing_mode";
```

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java [hunk 11]
```diff
@@ -74,9 +79,37 @@ public void recordFailure(boolean remote, Throwable e) {
...
+        // reindex request specifies a fixed slice count (e.g. ?slices=4)
+        FIXED,
+        // reindex request specifies a slice id (e.g. "slice": { "id": 0, "max": 4 })
+        MANUAL,
+        // no slicing (e.g. ?slices=1)
+        NONE
+    }
+
+    /**
+     * Determines the {@link SlicingMode} from a reindex request.
```
Comment (szybia) [inline modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:94]: nit, just to indicate this shouldn't be called with a sliced/worker ReindexRequest

```suggestion
     * Determines the {@link SlicingMode} from initial reindex request.
```

File: modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java [hunk 12]
```diff
@@ -264,80 +272,77 @@ private void closeRestClientAndRun(RestClient restClient, Runnable onCompletion)
...
-                var bulkExceptionSample = Optional.ofNullable(bulkByScrollResponse.getBulkFailures())
-                    .stream()
-                    .flatMap(List::stream)
-                    .map(BulkItemResponse.Failure::getCause)
-                    .findFirst();
-                if (searchExceptionSample.isPresent() || bulkExceptionSample.isPresent()) {
-                    // record only the first sample error in metric
-                    Throwable e = searchExceptionSample.orElseGet(bulkExceptionSample::get);
-                    metrics.recordFailure(isRemote, e);
+                if (bulkByScrollResponse.getTaskResumeInfo().isPresent()) {
```
Comment (szybia) [inline modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java:303]: thoughts on leaving in my comment? might be nice for understanding

```suggestion
                // note: implicitly relies on TaskResumeInfo only being populated if a suitable node exists for relocating to.
                if (bulkByScrollResponse.getTaskResumeInfo().isPresent()) {
```

File: modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java [hunk 13]
```diff
@@ -264,80 +272,77 @@ private void closeRestClientAndRun(RestClient restClient, Runnable onCompletion)
...
+                        .map(BulkItemResponse.Failure::getCause)
+                        .findFirst();
+                    if (searchExceptionSample.isPresent() || bulkExceptionSample.isPresent()) {
+                        Throwable e = searchExceptionSample.orElseGet(bulkExceptionSample::get);
+                        metrics.recordFailure(isRemote, slicingMode, e);
+                    } else {
+                        metrics.recordSuccess(isRemote, slicingMode);
+                    }
                     listener.onResponse(bulkByScrollResponse);
+                } finally {
```
Comment (szybia) [inline modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java:329]: i'd say a nit given unlikely, but if for whatever reason we error in this try

should we catch exception, call onFailure, and not recordDuration here (will be called in onFailure)

i guess thinking could mean a failure slipping through in metrics 🤔

File: modules/reindex/src/test/java/org/elasticsearch/reindex/ReindexerTests.java [hunk 14]
```diff
@@ -121,9 +127,52 @@ public void testWrapWithMetricsSearchFailure() {
...
+        BulkByScrollTask task = createNonSlicedWorkerTask();
+
+        var wrapped = Reindexer.wrapWithMetrics(listener, metrics, task, reindexRequest(), randomNonNegativeLong());
+
+        BulkByScrollResponse response = reindexResponseWithResumeInfo();
+        wrapped.onResponse(response);
+
+        verify(listener).onResponse(response);
+        verify(metrics, never()).recordSuccess(anyBoolean(), any());
+        verify(metrics, never()).recordFailure(anyBoolean(), any(), any());
```
Comment (szybia) [inline modules/reindex/src/test/java/org/elasticsearch/reindex/ReindexerTests.java]: nit

```suggestion
        verifyNoMoreInteractions(metrics);
```

**Review by szybia — COMMENTED** [review]
looks great! thinking last batch of comments

File: modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java (hunk 4 above)
Comment (samxbr) [reply modules/reindex-management/src/internalClusterTest/java/org/elasticsearch/reindex/management/ReindexRelocationIT.java:597]: I think it's worth testing relocation with auto slicing too, added that. 

I also ended up splitting the single local test into multiple tests. The fixed-sliced/non-sliced/auto-sliced/auto-but-not-sliced cases are distinct enough I think we shouldn't rely on randomness to hit each of them.

File: modules/reindex/src/internalClusterTest/java/org/elasticsearch/index/reindex/ReindexPluginMetricsIT.java (hunk 3 above)
Comment (samxbr) [reply modules/reindex/src/internalClusterTest/java/org/elasticsearch/index/reindex/ReindexPluginMetricsIT.java:329]: Sure, added.

File: modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java (hunk 12 above)
Comment (samxbr) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java:303]: Added some details to `getTaskResumeInfo` itself, which is probably a better place

File: modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java (hunk 13 above)
Comment (samxbr) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java:329]: I would say if there's an exception here where we don't expect one, then it's a bug. I'd rather it surfaces as a 5xx error and we fix the bug than handling it.

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java (hunk 10 above)
Comment (samxbr) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:35]: Metric attribute names are validated in `MetricValidator`, `es(_<segment>)+` is the recommended naming convention according to `NAMING.md`

Comment (samxbr) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:35]: The validation and convention are introduced after the earlier reindex metrics, ideally we should migrate other metrics to the new convention too later

Comment (PeteGillinElastic) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:35]: Yeah, the `es_` prefix is required now, as I discovered the hard way :-). The previous ones have been grandfathered in as exceptions in the validator, but we shouldn't add more.

We could probably drop the `reindex` though, as this thing is only used as an attributed to metrics with `reindex` in their names, i.e. `es_slicing_mode`?

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java (hunk 11 above)
Comment (samxbr) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:94]: It's a bit confusing IMO. It could be called on a sliced worker request (`slices=1`), it will just return `none` which is correct.

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java (hunk 10 above)
Comment (samxbr) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:35]: > Always use es_ as the root segment to easily discover ES attributes. Follow with a module name, team or area of code, e.g. snapshot, repositories, indices, threadpool using existing terminology (whether singular and plural)

So according to their convention, `es_reindex_slicing_mode` feels a little bit better with a module/area of code prefix

File: modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java
Comment (samxbr) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/Reindexer.java]: Yeah you are right, we can consolidate them, updated.

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java (hunk 10 above)
Comment (szybia) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:35]: > Always use es_ as the root

where is this written? (curious)

**Review by szybia — APPROVED** [review]
looks great! ty

File: modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java (hunk 10 above)
Comment (PeteGillinElastic) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:35]: Thanks for that quote Sam, I agree that including `reindex` makes sense. I wasn't going off any documentation, I was going off the exception that got thrown when I didn't have the `es_` prefix and looking at the regex that was being enforced by that validation code.

Comment (samxbr) [reply modules/reindex/src/main/java/org/elasticsearch/reindex/ReindexMetrics.java:35]: > Always use es_ as the root
>> where is this written? (curious)


https://github.com/elastic/elasticsearch/blob/main/modules/apm/NAMING.md
