### PR TITLE
[Inference API] Address AuthorizationTaskExecutorIT failures

### LINKED ISSUE #138012: [CI] AuthorizationTaskExecutorIT testCreatesChatCompletion_AndThenCreatesTextEmbedding failing
**Build Scans:**
- [elasticsearch-intake #33227 / part2](https://gradle-enterprise.elastic.co/s/qk4nkkpgbmqbi)
- [elasticsearch-periodic #11703 / openjdk25_checkpart2_java-matrix](https://gradle-enterprise.elastic.co/s/upjnu3svkfk6w)
- [elasticsearch-pull-request #112655 / part-2](https://gradle-enterprise.elastic.co/s/jbon23u3rygbi)
- [elasticsearch-intake #32938 / part2](https://gradle-enterprise.elastic.co/s/eipwwt3ga7bp2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:internalClusterTest" --tests "org.elasticsearch.xpack.inference.integration.AuthorizationTaskExecutorIT.testCreatesChatCompletion_AndThenCreatesTextEmbedding" -Dtests.seed=5ED64512FA0FA041 -Dtests.locale=nn -Dtests.timezone=America/Argentina/Jujuy -Druntime.java=25
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.inference.integration.AuthorizationTaskExecutorIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!('testCreatesChatCompletion_AndThenCreatesTextEmbedding'),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: 
Expected: is <2>
     but: was <1>
```

**Issue Reasons:**
- [main] 4 failures in test testCreatesChatCompletion_AndThenCreatesTextEmbedding (1.6% fail rate in 243 executions)
- [main] 2 failures in step part2 (4.3% fail rate in 46 executions)
- [main] 2 failures in pipeline elasticsearch-intake (4.3% fail rate in 46 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
This commit addresses failures in `AuthorizationTaskExecutorIT`.

  1. test `testCreatesChatCompletion_AndThenCreatesTextEmbedding` now waits for the second endpoint to be created. As the second endpoint is discovered by the `AuthorizationPoller` we need to wait for the new endpoint to be stored.
  2. tests based on `testEndpointGetsUpdated_GivenFingerprintChanged` now wait for inference system indices to be green (have their shards initialized) after the endpoint is stored. The latter guarantees the indices would have been created so that the `ensureGreen` call works as expected.

Closes #138012
Closes #144249

### CODE REVIEW

File: x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/AuthorizationTaskExecutorIT.java [hunk 1]
```diff
@@ -408,6 +423,7 @@ private void testEndpointGetsUpdated_GivenFingerprintChanged(String originalFing
             assertThat(updated.endpointMetadata().internal().fingerprint(), is(updatedFingerprint));
         });
 
+        deleteEndpoints(modelRegistry, Set.of(endpointId));
```
Comment (jonathan-buttner) [inline x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/AuthorizationTaskExecutorIT.java:426]: Hmm is `endpointId` a non-preconfigured endpoint? Shouldn't it already be deleted in the `shutdown()`?

**Review by jonathan-buttner — APPROVED** [review]

File: x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/AuthorizationTaskExecutorIT.java (hunk 1 above)
Comment (jonathan-buttner) [reply x-pack/plugin/inference/src/internalClusterTest/java/org/elasticsearch/xpack/inference/integration/AuthorizationTaskExecutorIT.java:426]: We chatted offline, `endpointId` is a random string
