### PR TITLE
Fixed rounding of bounds in scaled float comparison

### LINKED ISSUE #27189: scaled_float has precision problem
Describe the feature:

Elasticsearch version (bin/elasticsearch --version):
5.0.1, Build: 080bb47/2016-11-11T22:08:49.812Z

Plugins installed: []

JVM version (java -version):
1.8.0_131
OS version (uname -a if on a Unix-like system):
CentOS release 6.5
Description of the problem including expected versus actual behavior:
Results from inner_hits named "a" should be returned only if my_parent's key equal 3.
Steps to reproduce:

Please include a minimal but complete recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc. The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

```
PUT test
{
  "mappings": {
    "type": {
      "properties": {
        "scaled_float_field": {
          "type": "scaled_float",
          "scaling_factor": 100
        }
      }
    }
  }
}
POST _bulk
{"update": {"_index": "test","_type": "type","_id": "1"}}
{"doc": {"scaled_float_field": 0.1},"doc_as_upsert": true}
POST test/_search
{
  "query": {
    "range": {
      "scaled_float_field": {
        "lt": 0.1
      }
    }
  }
}
```
result
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "test",
        "_type": "type",
        "_id": "1",
        "_score": 1,
        "_source": {
          "scaled_float_field": 0.1
        }
      }
    ]
  }
}
```

As Document mentions [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html), scaled_float is stored as long type. Why it also has precision problem?

### PR DESCRIPTION
**Pull request by original-brownbear**
This fixes #27189 I think:

* Fixed by switching the order of operations between `nextDown`, `nextUp` and multiplication by the scaling factor to reduce rounding errors. Now the error incurred by `nextUp` and `nextDown` doesn't propagate into the multiplication by the scaling factor, whereas without this change the error incurred when multiplying two `double` can cancel out the `Math.nextDown` step as seen in the example below  
  * Added unit tests for the example in #27189 in which we were hit by 

```java
Math.floor(Math.nextDown(0.1) * 100.0) = 10.0
```

while

```java
Math.floor(Math.nextDown(0.1 * 100.0)) = 9.0
```

### CODE REVIEW

File: modules/mapper-extras/src/test/java/org/elasticsearch/index/mapper/ScaledFloatFieldTypeTests.java [hunk 1]
```diff
@@ -124,6 +124,22 @@ public void testRangeQuery() throws IOException {
...
+        assertEquals("scaled_float:[-9223372036854775808 TO 9]", scaledFloatQ.toString());
+    }
+
+    public void testRoundsLowerBoundCorrectly() {
+        ScaledFloatFieldMapper.ScaledFloatFieldType ft = new ScaledFloatFieldMapper.ScaledFloatFieldType();
+        ft.setName("scaled_float");
+        ft.setScalingFactor(100.0);
+        Query scaledFloatQ = ft.rangeQuery(-0.1, null, false, true, null);
+        assertEquals("scaled_float:[-9 TO 9223372036854775807]", scaledFloatQ.toString());
+    }
```
Comment (jpountz) [inline modules/mapper-extras/src/test/java/org/elasticsearch/index/mapper/ScaledFloatFieldTypeTests.java]: I expanded your assertions a bit if you are ok with them:

```
    public void testRoundsUpperBoundCorrectly() {
        ScaledFloatFieldMapper.ScaledFloatFieldType ft = new ScaledFloatFieldMapper.ScaledFloatFieldType();
        ft.setName("scaled_float");
        ft.setScalingFactor(100.0);
        Query scaledFloatQ = ft.rangeQuery(null, 0.1, true, false, null);
        assertEquals("scaled_float:[-9223372036854775808 TO 9]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(null, 0.1, true, true, null);
        assertEquals("scaled_float:[-9223372036854775808 TO 10]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(null, 0.095, true, false, null);
        assertEquals("scaled_float:[-9223372036854775808 TO 9]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(null, 0.095, true, true, null);
        assertEquals("scaled_float:[-9223372036854775808 TO 9]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(null, 0.105, true, false, null);
        assertEquals("scaled_float:[-9223372036854775808 TO 10]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(null, 0.105, true, true, null);
        assertEquals("scaled_float:[-9223372036854775808 TO 10]", scaledFloatQ.toString());
    }

    public void testRoundsLowerBoundCorrectly() {
        ScaledFloatFieldMapper.ScaledFloatFieldType ft = new ScaledFloatFieldMapper.ScaledFloatFieldType();
        ft.setName("scaled_float");
        ft.setScalingFactor(100.0);
        Query scaledFloatQ = ft.rangeQuery(-0.1, null, false, true, null);
        assertEquals("scaled_float:[-9 TO 9223372036854775807]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(-0.1, null, true, true, null);
        assertEquals("scaled_float:[-10 TO 9223372036854775807]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(-0.095, null, false, true, null);
        assertEquals("scaled_float:[-9 TO 9223372036854775807]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(-0.095, null, true, true, null);
        assertEquals("scaled_float:[-9 TO 9223372036854775807]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(-0.105, null, false, true, null);
        assertEquals("scaled_float:[-10 TO 9223372036854775807]", scaledFloatQ.toString());
        scaledFloatQ = ft.rangeQuery(-0.105, null, true, true, null);
        assertEquals("scaled_float:[-10 TO 9223372036854775807]", scaledFloatQ.toString());
    }
```

**Review by jpountz — APPROVED** [review]
I left a comment about testing more cases, but your change looks good to me.

File: modules/mapper-extras/src/test/java/org/elasticsearch/index/mapper/ScaledFloatFieldTypeTests.java (hunk 1 above)
Comment (original-brownbear) [reply modules/mapper-extras/src/test/java/org/elasticsearch/index/mapper/ScaledFloatFieldTypeTests.java]: @jpountz thanks for reviewing, I like adding some more assertions :) I'll just add those to this PR?

Comment (jpountz) [reply modules/mapper-extras/src/test/java/org/elasticsearch/index/mapper/ScaledFloatFieldTypeTests.java]: Yes please!

**Comment by original-brownbear** [comment]
@jpountz added you assertions :)

**Comment by dakrone** [comment]
Thanks @original-brownbear, I'll wait for CI to finish and then merge this

**Comment by original-brownbear** [comment]
Rebased this one just now since it failed the BWC tests here https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/5329/console

**Comment by original-brownbear** [comment]
@dakrone now it's green :)
