### PR TITLE
ES|QL: Skip CASE function from InferIsNotNull rule checks

### LINKED ISSUE #112704: ES|QL NULL check in CASE clause breaks later WHERE
### Elasticsearch Version

8.15.1

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Docker

### Problem Description

Using a `WHERE` statement after a `CASE` clause gives very strange and unexpected behavior. It's somewhat hard to explain, but the steps to reproduce should explain the situation well. 

### Steps to Reproduce

1. Bring up a fresh Docker cluster from scratch, running 8.15.1
2. Ingest a few documents:
    ```
    POST _bulk
    {"index":{"_index":"test"}}
    {"val": 1}
    {"index":{"_index":"test"}}
    {"val": 2}
    {"index":{"_index":"test"}}
    {"val": 3}
    {"index":{"_index":"test"}}
    {"val": 4}
    {"index":{"_index":"test"}}
    {} // This doc has no value for val
    ```
3. Run a query that includes a `NULL` check in the `CASE` clause:
    ```
    POST /_query?format=txt
    {
    "query": """
        FROM test
        | KEEP val
        | EVAL eval = CASE(
            val == 0, null,
            val % 2 == 0, "val is even",
            val % 2 != 0, "val is odd",
            val IS NULL, "val is null")
        | SORT val
    """
    }
    ```
4. Observe that the output includes all documents and that the `eval` column has a value for all rows but the first:
    ```
    #! No limit defined, adding default limit of [1000]
        val      |     eval
    ---------------+---------------
    0              |null
    1              |val is odd
    2              |val is even
    3              |val is odd
    4              |val is even
    null           |val is null
    ```
5. Add a `WHERE` clause that operates on the `eval` column to only include rows where `eval` is not `null`:
    ```
    POST /_query?format=txt
    {
    "query": """
        FROM test
        | KEEP val
        | EVAL eval = CASE(
            val == 0, null,
            val % 2 == 0, "val is even",
            val % 2 != 0, "val is odd",
            val IS NULL, "val is null")
        | SORT val
        | WHERE eval IS NOT NULL
    """
    }
    ```
6. Observe that the row where `val` is `0` and `eval` is `null` is correctly excluded, but that the row where `val` is `null` and `eval` is `val is null` is (incorrectly) missing:
    ```
    #! No limit defined, adding default limit of [1000]
        val      |     eval
    ---------------+---------------
    1              |val is odd
    2              |val is even
    3              |val is odd
    4              |val is even
    ```
7. Change the `WHERE` clause that operates on the `eval` column to use `LIKE`:
    ```
    POST /_query?format=txt
    {
    "query": """
        FROM test
        | KEEP val
        | EVAL eval = CASE(
            val == 0, null,
            val % 2 == 0, "val is even",
            val % 2 != 0, "val is odd",
            val IS NULL, "val is null")
        | SORT val
        | WHERE eval LIKE "*"
    """
    }
    ```
8. Observe that the row for `eval` with the value `val is null` is still (incorrectly) missing:
    ```
    #! No limit defined, adding default limit of [1000]
        val      |     eval
    ---------------+---------------
    1              |val is odd
    2              |val is even
    3              |val is odd
    4              |val is even
    ```
9. Change the `WHERE` clause that operates on the `eval` column to use a different `LIKE` pattern:
    ```
    POST /_query?format=txt
    {
    "query": """
        FROM test
        | KEEP val
        | EVAL eval = CASE(
            val == 0, null,
            val % 2 == 0, "val is even",
            val % 2 != 0, "val is odd",
            val IS NULL, "val is null")
        | SORT val
        | WHERE eval LIKE "value*"
    """
    }
    ```
10. Observe that the row for `eval` with the value `val is null` now shows correctly:
    ```
    #! No limit defined, adding default limit of [1000]
        val      |     eval
    ---------------+---------------
    1              |val is odd
    2              |val is even
    3              |val is odd
    4              |val is even
    null           |val is null
    ```
11. Revert back to the query used in step 5, but add a `LIMIT` statement somewhere before the `WHERE` statement:
    ```
    POST /_query?format=txt
    {
    "query": """
        FROM test
        | KEEP val
        | EVAL eval = CASE(
            val == 0, null,
            val % 2 == 0, "val is even",
            val % 2 != 0, "val is odd",
            val IS NULL, "val is null")
        | SORT val
        | LIMIT 10
        | WHERE eval IS NOT NULL
    """
    }
    ```
12. Observe that the row for `eval` with the value `val is null` now shows correctly (where it did not show in step 6):
    ```
        val      |     eval
    ---------------+---------------
    1              |val is odd
    2              |val is even
    3              |val is odd
    4              |val is even
    null           |val is null
    ```

Conclusion:

The best workaround seems to be to use a `LIKE` statement with some pattern other than `"*"` that matches all expected values (which is not always possible). Using the `LIMIT` fix will not work for large datasets.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by astefan**
Fixes https://github.com/elastic/elasticsearch/issues/112704 by excluding `case` function from the `InferIsNotNull` local optimizer rule, because of the potential complexity of the `case` logic conditions.

### CODE REVIEW

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferIsNotNull.java [hunk 1]
```diff
@@ -106,6 +107,6 @@ private boolean doResolve(Expression exp, AttributeMap<Expression> aliases, Set<
     }
 
     private static boolean skipExpression(Expression e) {
-        return e instanceof Coalesce;
+        return e instanceof Coalesce || e instanceof Case;
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferIsNotNull.java:110]: Nit: in case any other change is required to the PR, maybe move the comment from the call site as function javadoc/comment.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java [hunk 2]
```diff
@@ -516,6 +484,66 @@ public void testIsNotNullOnFunctionWithTwoFields() {
...
+        var limit = as(plan, Limit.class);
+        var filter = as(limit.child(), Filter.class);
+        var inn = as(filter.condition(), IsNotNull.class);
+        assertThat(Expressions.names(inn.children()), contains("x"));
+        var eval = as(filter.child(), Eval.class);
+        filter = as(eval.child(), Filter.class);
+        inn = as(filter.condition(), IsNotNull.class);
+        assertThat(Expressions.names(inn.children()), contains("emp_no"));
+        var source = as(filter.child(), EsRelation.class);
+    }
```
Comment (bpintea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java:517]: (just checking: these are moved only, right?)

**Review by bpintea — APPROVED** [review]
Lgtm

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java (hunk 2 above)
Comment (astefan) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LocalLogicalPlanOptimizerTests.java:517]: Yes, sorry. I forgot to add a comment after I created the PR.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferIsNotNull.java (hunk 1 above)
Comment (luigidellaquila) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferIsNotNull.java:110]: It would be nice to understand why these two functions are special, at least with a comment, and eventually extract a general rule (a flag interface or a method in the Expression class to identify the functions that fall into this category).
The only patterns I can see are:
- both have `Nullability.UNKNOWN` (but also BinaryLogic does, yet it's not listed here). The javadoc mentions unknown nullability as well: `Simplify IsNotNull targets by resolving the underlying expression to its root fields with unknown nullability`...
- both return the value of one of the expressions passed as params (but other functions do as well, eg. `GREATEST()`)

Can you please elaborate a bit on this?

**Review by luigidellaquila — COMMENTED** [review]
Thanks @astefan, it works and it fixes a problem, so it's a 👍 for me, but I'd like to have a bit more context (at least a comment) on the logic behind this functions blacklist

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferIsNotNull.java (hunk 1 above)
Comment (astefan) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferIsNotNull.java:110]: After spending some time on this issue when it was initially reported, my thinking is the following:
- Nullability has nothing to do with this optimization. Nullability is most useful in the LogicalPlanOptimizer to shortcircuit folding to `null` expressions. At this point, in the **local** logical optimizer, the **Nullability did its job**.
- the fact that Nullability is the same (and unknown) for these two functions (for `coalesce` it can also be `false`) is a fact indeed, but conceptually speaking I think it's **not relevant**
- these two functions have special behavior in the sense that they can mess up the `is not null` predicate when it's used on them. They can accept complex expressions where the **fields** used can also be checked for `null`. For example, `case (x is null,.....) is not null` cannot be transformed in `case(....) is not null AND x is not null` because there is already an expression that contradicts `x is null`.
  - I have tried to come up with a smarter way of evaluating the expressions inside a `case` and determine if the fields there end up as `x is null` but it proved to be more complicated and I found this not worth the effort **now**. Maybe we can come back to this and be smarter about `case` and `coalesce` but we need a stronger reason to do it. Also, this bug is serious enough that it warrants this simple exclusion and fix.
- the _flag interface or a method in the Expression class_ at this point in the life of ES|QL (where we welcome any contribution from outside) is, imo, not warranted: we will make the behavior of a function more complex than it needs and it will confuse contributors even more. For now, I prefer to have this logic centralized in an optimization rule. Functions land should be a more approachable one, optimization rules are left for advanced logic and knowledge.

I will add a comment in the PR for this method, @bpintea also mentioned this.

Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferIsNotNull.java:110]: > these two functions have special behavior in the sense that they can mess up the is not null

I don't completely agree with this statement. These two functions mess up with this rule, not with `IsNotNull`.

> They can accept complex expressions where the fields used can also be checked for null

This is closer to the point IMHO: the real peculiarity is that these functions have a custom behavior with null inputs, ie. even if one input is null, the function can still be not null, so `func(input1, input2, ...) IS NOT NULL` is *not* equivalent to `input1 IS NOT NULL and func(input1, input2, ...) IS NOT NULL`. 
I think we can easily express this as a method.

The danger comes from the fact that this is an implementation detail, peculiar to each function. 
Or better, it's how our code generator creates evaluators (`Coalesce` and `Case` have a custom evaluator, not generated).
This makes the risk pretty low for now, that's why IMHO it's still good as a fix, but IMHO we should make this rule more robust as a follow-up.

> the flag interface or a method in the Expression class at this point in the life of ES|QL (where we welcome any contribution from outside) is, imo, not warranted: we will make the behavior of a function more complex than it needs and it will confuse contributors even more

My concern is that a contributor could introduce a new function with a similar behavior, and will unintentionally break this rule. 

> Also, this bug is serious enough that it warrants this simple exclusion and fix.
💯

**Review by luigidellaquila — APPROVED** [review]
LGTM, let's move it forward.
See also my comment below, IMHO there is margin for improvements

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferIsNotNull.java (hunk 1 above)
Comment (luigidellaquila) [reply x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/local/InferIsNotNull.java:110]: > the flag interface or a method in the Expression class at this point in the life of ES|QL (where we welcome any contribution from outside) is, imo, not warranted: we will make the behavior of a function more complex than it needs and it will confuse contributors even more

My concern is that a contributor could introduce a new function with a similar behavior, and will unintentionally break this rule. 

Anyway, for

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/part-4

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/bwc-snapshots
