### PR TITLE
Handle failure to release retention leases in ILM

### LINKED ISSUE #39181: ILM needs to account for the possibility that removing the retention leases on the leader can fail
When ILM is managing a following index, it will attempt to perform an unfollow action on the follower. It can be however that the unfollow action succeeds to make the index into a non-following index, yet the unfollow action completes with an error. This can occur if the follower was not able to remove the retention leases on its leader (e.g., a network connectivity issue). ILM on the following side should accept this possibility and not put the lifecycle into an error state. This can be determined when the unfollow action fails with an `ElasticsearchException` with the metadata `es.failed_to_remove_retention_leases`. 

Relates #34648
Relates #39088

### PR DESCRIPTION
**Pull request by AthenaEryma**
It is possible that the Unfollow API may fail to release shard history
retention leases when unfollowing, so this needs to be handled by the
ILM Unfollow action. There's nothing much that can be done automatically
about it from the follower side, so this change makes the ILM unfollow
action simply ignore those failures.

Resolves https://github.com/elastic/elasticsearch/issues/39181

### CODE REVIEW

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStep.java [hunk 1]
```diff
@@ -25,7 +31,19 @@ void innerPerformAction(String followerIndex, Listener listener) {
                 assert r.isAcknowledged() : "unfollow response is not acknowledged";
                 listener.onResponse(true);
             },
-            listener::onFailure
+            exception -> {
+                if (exception instanceof ElasticsearchException
+                        && ((ElasticsearchException) exception).getMetadata("es.failed_to_remove_retention_leases") != null) {
+                    List<String> leasesNotRemoved = ((ElasticsearchException) exception)
+                        .getMetadata("es.failed_to_remove_retention_leases");
+                    logger.debug("Failed to remove leader retention lease(s) {} while unfollowing index [{}], " +
```
Comment (jasontedor) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStep.java]: I wonder if this should be warn?

Comment (gwbrown) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStep.java]: I wouldn't be opposed to making this `warn`, I only made it `debug` because it looks like [TransportUnfollowAction already emits a warning](https://github.com/elastic/elasticsearch/pull/39088/files#diff-93f9315523c24e85103be733259dad9fR129) in this case.

Comment (martijnvg) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStep.java]: Both unfollow execution and ilm policy execution happen on the elected master node, so I think logging twice a warning is not needed here.

Comment (jasontedor) [reply x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStep.java]: Okay, that is fair.

**Review by jasontedor — COMMENTED** [review]
The production code looks good, but yeah, let us see some tests.

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/CcrIndexLifecycleIT.java [hunk 2]
```diff
@@ -0,0 +1,171 @@
...
+
+        // Disrupt requests to remove retention leases for these random shards
+        final Set<Integer> shardIds =
+            new HashSet<>(randomSubsetOf(
+                randomIntBetween(1, numberOfShards),
+                IntStream.range(0, numberOfShards).boxed().collect(Collectors.toSet())));
+
+        final ClusterStateResponse followerClusterState = followerClient().admin().cluster().prepareState().clear().setNodes(true).get();
+        try {
+            for (final ObjectCursor<DiscoveryNode> senderNode : followerClusterState.getState().nodes().getNodes().values()) {
```
Comment (martijnvg) [inline x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/CcrIndexLifecycleIT.java]: Alternatively this test can also set `cluster.remote.leader_cluster.seeds` setting to `null` via cluster update settings api, which disables the follower cluster to communicate to the leader cluster.  (this test would then also need to extend overwrite `configureRemoteClusterViaNodeSettings()` and return false).

I think this is a bit cleaner, as it it requires fewer lines of code and doesn't involve interacting with mock transport service. But since this is a common practice in other tests, I think it is okay for this test too. Just wanted to mention the alternative. Also the upside of the current approach, is that it is a more realistic simulation of when the leader cluster isn't reachable from the follower cluster in production.

**Review by martijnvg — COMMENTED** [review]
The tests and production code look good to me. 

I just wonder whether the location of the `CcrIndexLifecycleIT` is the right place. Currently it resides in the ccr module (the reason that this works is because ccr module has a testCompile dependency on the monitoring module and the monitoring module has a testCompile dependency on the ilm module). However this integration test tests whether the `UnfollowFollowIndexStep` handles the `es.failed_to_remove_retention_leases` metadata on a exception correctly. So from that perspective ideally this integ test should reside in the ilm module. (we would do that then need to add a testCompile dependency to ccr in ilm module). What do you think?

File: x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/CcrIndexLifecycleIT.java (hunk 2 above)
Comment (gwbrown) [reply x-pack/plugin/ccr/src/test/java/org/elasticsearch/xpack/ccr/CcrIndexLifecycleIT.java]: Thanks - I'll try this. If that's the case, then this might not need to be a `CcrIntegTestCase` and we could roll it into the existing REST-based test cases in the ILM module, rather than having to add a dependency on CCR.

I didn't like that this test was in CCR, rather than ILM, but I wanted to get eyes on the code, and it can always be moved.  I'll look into this and update this PR moving this test into the ILM module one way or another.

**Comment by gwbrown** [comment]
@martijnvg After working with this a bit, I wasn't able to get setting `cluster.remote.leader_cluster.seeds` to `null` to work in a REST test, so I went about trying to move that test case to `ilm`, but ran into some issues with adding a dependency on CCR.

Adding a `testCompile` dependency on CCR's test classes to ILM produces jar hell failures, I think because of exactly what you mentioned: CCR depends on ILM transitively via monitoring.  Let's sync up tomorrow and figure out if there's something we can do about this that I'm missing, or if we just have to live with this test being in a weird place.

File: x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStep.java (hunk 1 above)
Comment (dakrone) [inline x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStep.java]: Super minor but we usually don't capitalize log messages

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStepTests.java [hunk 3]
```diff
@@ -112,4 +113,47 @@ public void onFailure(Exception e) {
...
+            return null;
+        }).when(client).execute(Mockito.same(UnfollowAction.INSTANCE), Mockito.any(), Mockito.any());
+
+        Boolean[] completed = new Boolean[1];
+        Exception[] failure = new Exception[1];
+        UnfollowFollowIndexStep step = new UnfollowFollowIndexStep(randomStepKey(), randomStepKey(), client);
+        step.performAction(indexMetadata, null, null, new AsyncActionStep.Listener() {
+            @Override
+            public void onResponse(boolean complete) {
+                completed[0] = complete;
```
Comment (dakrone) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStepTests.java]: I understand we want to be able to mutate these things here, but I think I'd rather see `AtomicBoolean` and `AtomicReference` for these, since it's cleaner what's going on and reduces the chance of hitting an `ArrayIndexOutOfBoundsException` if this test gets refactored in the future.

Comment (dakrone) [reply x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/indexlifecycle/UnfollowFollowIndexStepTests.java]: Or using Lucene's `SetOnce` would work too I think

**Review by dakrone — APPROVED** [review]
LGTM, I left two minor comments

**Comment by gwbrown** [comment]
Thanks @dakrone, fixed!
