### PR TITLE
Fix clearing of lastSuccessfulAuthCache when clear all realm cache API is called

### LINKED ISSUE #86650: Clear all realm cache should also invalidate lastSuccessfulAuthCache
The [ClearRealmCache API](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-clear-cache.html) evicts users from caching realms. It should also clear the [lastSuccessfulAuthCache](https://github.com/elastic/elasticsearch/blob/fcfb04392cfdf6f3ae35587ce0f4ed6522cef05a/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/AuthenticationService.java#L97) in the process. 

But it fails to do that if the realm is specified as a wildcard, i.e. the following request clear all realm caches, but not the lastSuccessfulAuthCache ([relevant code](https://github.com/elastic/elasticsearch/blob/fcfb04392cfdf6f3ae35587ce0f4ed6522cef05a/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheAction.java#L85-L90)):

```
POST _security/realm/*/_clear_cache
```

But it does clear lastSuccessfulAuthCache if concrete realm name is specified, e.g. the following request clear both the reserved realm cache and the lastSuccessfulAuthCache ([relevant code](https://github.com/elastic/elasticsearch/blob/fcfb04392cfdf6f3ae35587ce0f4ed6522cef05a/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheAction.java#L92-L100)):

```
POST _security/realm/reserved/_clear_cache
```

#### Steps to reproduce the issue
1. Enable both file and native realm on a node and make sure file is before native in the realm chain
2. Create a native user `foo` and authenticate with it.
3. Add a file user `foo` with the same password and wait for the node to auto-load the file
4. Clear realm cache with `POST _security/realm/*/_clear_cache`
5. Authenticate with `foo`, but the realm is still `native` (_incorrect behaviour_)
6. Clear the realm cache with `POST _security/realm/reserved/_clear_cache`
7. Authenticate with `foo`, this time the realm is `file` (_correct behaviour_)

### PR DESCRIPTION
**Pull request by slobodanadamovic**
This PR adds missing call to clear last successful authentication cache,
when clear all realm cache action is called.

Fixes #86650

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+        action = mockClearRealmCacheAction(realms, authenticationService);
+    }
+
+    public void testSingleUserCacheCleanupForAllRealms() {
+
+        final String user = "test";
+
+        // When no realm is specified we should clear all realms.
+        // This is equivalent to using a wildcard (*) instead of specifying realm name in query.
+        final String[] realmsToClear = new String[] {};
```
Comment (ywangd) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java:61]: I think we can random from either empty string array or null, e.g.
```suggestion
        final String[] realmsToClear = randomFrom(Strings.EMPTY_ARRAY, null);
```

Same applies to other empty realm/user array

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java [hunk 2]
```diff
@@ -0,0 +1,179 @@
...
+        ClearRealmCacheRequest.Node clearCacheRequest = mockClearCacheRequest(realmsToClear, usersToClear);
+
+        ClearRealmCacheResponse.Node response = action.nodeOperation(clearCacheRequest, mock(Task.class));
+        assertThat(response.getNode(), notNullValue());
+
+        // We expect that caches of all realms are cleared for the given user,
+        // including last successful cache in the authentication service.
+        verify(fileRealm).expire(user);
+        verify(nativeRealm).expire(user);
+        verify(authenticationService).expire(user);
```
Comment (ywangd) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java:72]: We could also assert `expireAll` is not called.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java [hunk 3]
```diff
@@ -0,0 +1,179 @@
...
+        ClearRealmCacheRequest.Node clearCacheRequest = mockClearCacheRequest(realmsToClear, usersToClear);
+
+        ClearRealmCacheResponse.Node response = action.nodeOperation(clearCacheRequest, mock(Task.class));
+        assertThat(response, notNullValue());
+
+        // We expect that only native cache is cleared,
+        // including last successful cache in the authentication service.
+        verify(nativeRealm).expire(user);
+        verify(fileRealm, times(0)).expire(user);
+        verify(authenticationService).expire(user);
```
Comment (ywangd) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java:91]: Same here, negative assertion for `expireAll` could be helpful.

**Review by ywangd — APPROVED** [review]
LGTM

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java [hunk 4]
```diff
@@ -0,0 +1,179 @@
...
+            realms,
+            authenticationService
+        );
+    }
+
+    private TestCachingRealm mockRealm(String name) {
+        TestCachingRealm realm = mock(TestCachingRealm.class);
+        when(realm.name()).thenReturn(name);
+        return realm;
+    }
```
[the remark this answers is not in the document]
Comment (slobodanadamovic) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java:141]: Unfortunately, we can't. Reason is because `Realms` holds `Realm` objects not `CachingRealm`. 
I thought of using `CachingUsernamePasswordRealm` instead, but this abstract class has made `expire` and `expireAll` methods final. Hence why I decided to introduce `TestCachingRealm`.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java (hunk 1 above)
Comment (slobodanadamovic) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java:61]: Good suggestion. Thanks.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java (hunk 2 above)
Comment (slobodanadamovic) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java:72]: Makes total sense. Will do.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (ywangd) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/realm/TransportClearRealmCacheActionTests.java:148]: All good. Thanks for the explanation.
