### PR TITLE
Retry internally when CAS upload is throttled [GCS]

### LINKED ISSUE #116546: [CI] GCSSnapshotRepoTestKitIT testRepositoryAnalysis failing
**Build Scans:**
- [elasticsearch-periodic #4807 / third-party_gcs](https://gradle-enterprise.elastic.co/s/ev2cm23s75uum)
- [elasticsearch-periodic #4797 / third-party_gcs](https://gradle-enterprise.elastic.co/s/wtzpnzwejykge)

**Reproduction Line:**
```
./gradlew ':x-pack:plugin:snapshot-repo-test-kit:qa:gcs:javaRestTest' --tests "org.elasticsearch.repositories.blobstore.testkit.GCSSnapshotRepoTestKitIT.testRepositoryAnalysis" -Dtests.seed=958EC26E665DFFC9 -Dtests.locale=ps-AF -Dtests.timezone=America/Argentina/Jujuy -Druntime.java=22
```

**Applicable branches:**
8.15

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.repositories.blobstore.testkit.GCSSnapshotRepoTestKitIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testRepositoryAnalysis),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:45521], URI [/_snapshot/repository/_analyze?blob_count=10&seed=-605332933961545440&max_blob_size=1mb&timeout=120s&concurrency=4], status line [HTTP/1.1 500 Internal Server Error]
{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[repository] register [test-register-contended-xiI4LAB9TV2RWCIUoShEZA] should have value [10] but instead had value [OptionalBytesReference[MISSING]]"}],"type":"repository_verification_exception","reason":"[repository] analysis failed, you may need to manually remove [temp-analysis-GYCHMvHuREKM3vd994Bsuw]","caused_by":{"type":"repository_verification_exception","reason":"[repository] register [test-register-contended-xiI4LAB9TV2RWCIUoShEZA] should have value [10] but instead had value [OptionalBytesReference[MISSING]]"}},"status":500}
```

**Issue Reasons:**
- [8.15] 2 failures in test testRepositoryAnalysis (2.3% fail rate in 87 executions)
- [8.15] 2 failures in step third-party_gcs (66.7% fail rate in 3 executions)
- [8.15] 2 failures in pipeline elasticsearch-periodic (50.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by nicktindall**
Fixes #116546

I've only changed the case where we are throttled trying to upload the new register contents, because currently that was the only place we returned `MISSING` when we were throttled. Do we think it'd make more sense to start the whole CAS again in the event that ANY of the requests are throttled?

It looks like by default, GCS is configured with

initial retry delay = 1s
retry delay multiplier = 2
max retry delay = 32s
max attempts = 6

So by adding another layer of retries, this CAS could end up taking some time. By default I allowed two retries, which will take the maximum time out to 96s.

### CODE REVIEW

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java [hunk 1]
```diff
@@ -691,28 +696,46 @@ OptionalBytesReference compareAndExchangeRegister(
...
-                if (statusCode == RestStatus.PRECONDITION_FAILED.getStatus() || statusCode == RestStatus.TOO_MANY_REQUESTS.getStatus()) {
+                if (statusCode == RestStatus.PRECONDITION_FAILED.getStatus()) {
                     return OptionalBytesReference.MISSING;
                 }
+                if (statusCode == RestStatus.TOO_MANY_REQUESTS.getStatus()) {
+                    finalException = ExceptionsHelper.useOrSuppress(finalException, serviceException);
+                    if (retries.hasNext()) {
+                        try {
+                            // noinspection BusyWait
+                            Thread.sleep(retries.next().millis());
```
[the remark this answers is not in the document]
Comment (DaveCTurner) [reply modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageBlobStore.java:728]: Sleeping seems ok here to me, if we're being throttled on a CAS then we probably shouldn't be freeing up the thread to do some other blob-store operation.

**Review by DaveCTurner — APPROVED** [review]
LGTM

Just checking my understanding tho, the Azure implementation already does what we want right?

**Comment by nicktindall** [comment]
> LGTM
> 
> Just checking my understanding tho, the Azure implementation already does what we want right?

This problem was unique due to the way GCP relied on the outer scope to do the retry (on throttling, it simulated a failure to CAS which would trigger a re-attempt). Azure doesn't do that, instead if it gets throttled it'll propagate that error out. We don't have any retries beyond those built into the client, but as far as I know we haven't seen the analysis test fail.

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageRepository.java [hunk 2]
```diff
@@ -56,10 +58,33 @@ class GoogleCloudStorageRepository extends MeteredBlobStoreRepository {
...
+    static final Setting<Integer> RETRY_THROTTLED_CAS_MAX_NUMBER_OF_RETRIES = Setting.intSetting(
+        "throttled_cas_retry.maximum_number_of_retries",
+        2,
+        0
+    );
+    static final Setting<TimeValue> RETRY_THROTTLED_CAS_MAXIMUM_DELAY = Setting.timeSetting(
+        "throttled_cas_retry.maximum_delay",
+        TimeValue.timeValueSeconds(5),
+        TimeValue.ZERO
+    );
```
Comment (ywangd) [inline modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageRepository.java:79]: Are these settings registered anywhere?

**Comment by ywangd** [comment]
Should this be labelled as `>enhancement` instead of `>test`?

File: modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageRepository.java (hunk 2 above)
Comment (nicktindall) [reply modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageRepository.java:79]: No, also I should document them 👍

Comment (ywangd) [reply modules/repository-gcs/src/main/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageRepository.java:79]: Scratch that. I forgot repository metadata are not true settings.

**Comment by nicktindall** [comment]
> Should this be labelled as `>enhancement` instead of `>test`?

I guess it should given that it changes actual behaviour. Will update.

**Comment by ywangd** [comment]
> Azure doesn't do that, instead if it gets throttled it'll propagate that error out

IIUC, with this PR, GCP implementation should also do the same after the retry exhausted, right? I think one main difference from the previous behaviour is that we will get a clear exception which helps troubleshooting instead of a return value of `OptionalBytesReference[MISSING]`.
