### PR TITLE
Ensure we mark store as corrupted if we fail to read the segments info

### LINKED ISSUE #11226: CorruptedFileTest#testReplicaCorruption fails
This test fails since we get into a cycle of trying to recover the primary from replica 1 and replica 2 which are corrupted, and never end up reaching the non corrupted previous primary shard

### PR DESCRIPTION
**Pull request by s1monw**
This commit also reenables CorruptedFileTest#testReplicaCorruption which had
a missing `GatewayAllocator.INDEX_RECOVERY_INITIAL_SHARDS: "one"` setting.

Closes #11226

### CODE REVIEW

**Comment by s1monw** [comment]
@kimchy can you look

File: src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java [hunk 1]
```diff
@@ -38,6 +38,7 @@
 import org.elasticsearch.env.NodeEnvironment;
 import org.elasticsearch.index.shard.ShardId;
 import org.elasticsearch.index.shard.ShardStateMetaData;
+import org.elasticsearch.index.store.Store;
```
Comment (kimchy) [inline src/main/java/org/elasticsearch/gateway/TransportNodesListGatewayStartedShards.java]: I think it's a leftover import

**Comment by kimchy** [comment]
minor comment, lgtm
