### PR TITLE
QA: Create xpack yaml features

### LINKED ISSUE #30933: YML Testing: Add `distribution` support to `skip`
We've been reusing our yml tests against different Elasticsearch distributions for a long time and we've been skipping tests that are broken against distributions using `tests.rest.blacklist`. While `tests.rest.blacklist` *works* it is suboptimal because the "normal" place to look for a skipped tests is in the test source code rather than in the `build.gradle` file. So I'd like to add `skip: distribution` style support. It'd look like this:
```
    - skip:
        distribution: zip
        reason: xpack creates some templates that make this test not pass
```

We'd like this sooner rather than later because we're starting to reuse the yml tests for distributions. It'd also be super nice to have this for #30665.

### PR DESCRIPTION
**Pull request by nik9000**
This creates a YAML test "features" that indices if the cluster being
tested has xpack installed (`xpack`) or if it does *not* have xpack
installed (`no_xpack`). It uses those features to centralize skipping
a few tests that fail if xpack is installed.

The plan is to use this in a followup to skip docs tests that require
xpack when xpack is not installed. We *plan* to use the declaration
of required license level on the docs page to generate the required
`skip`.

Closes #30933.

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 1]
```diff
@@ -91,13 +94,38 @@
...
+                NamedXContentRegistry.EMPTY, DeprecationHandler.THROW_UNSUPPORTED_OPERATION,
+                response.getEntity().getContent())) {
             return parser.map();
         }
     }
 
+    /**
+     * Does the cluster being tested have xpack installed?
+     */
+    public static boolean hasXPack() throws IOException {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I made this `static` so that we could use it easily from `feature`. I feel like if `client()` is static then this can be.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 2]
```diff
@@ -91,13 +94,38 @@
     /**
      * Convert the entity from a {@link Response} into a map of maps.
      */
-    public Map<String, Object> entityAsMap(Response response) throws IOException {
+    public static Map<String, Object> entityAsMap(Response response) throws IOException {
```
Comment (nik9000) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: I made this static so I could make `hasXPack` static. There was no need for it to use the fancy registries provided by `createParser`.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/integration/MlRestTestStateCleaner.java [hunk 3]
```diff
@@ -41,7 +39,7 @@ private void deleteAllDatafeeds() throws IOException {
         final Response datafeedsResponse = adminClient.performRequest(datafeedsRequest);
         @SuppressWarnings("unchecked")
         final List<Map<String, Object>> datafeeds =
-                (List<Map<String, Object>>) XContentMapValues.extractValue("datafeeds", testCase.entityAsMap(datafeedsResponse));
+                (List<Map<String, Object>>) XContentMapValues.extractValue("datafeeds", ESRestTestCase.entityAsMap(datafeedsResponse));
```
Comment (nik9000) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ml/integration/MlRestTestStateCleaner.java]: Checkstyle forced me to change this and the rest of the changes to this file come about because of the change here.

File: x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/rollup/RollupRestTestStateCleaner.java [hunk 4]
```diff
@@ -75,7 +73,7 @@ private void waitForPendingTasks() throws Exception {
     @SuppressWarnings("unchecked")
     private void deleteAllJobs() throws Exception {
         Response response = adminClient.performRequest("GET", "/_xpack/rollup/job/_all");
-        Map<String, Object> jobs = testCase.entityAsMap(response);
+        Map<String, Object> jobs = ESRestTestCase.entityAsMap(response);
```
Comment (nik9000) [inline x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/rollup/RollupRestTestStateCleaner.java]: Checkstyle forced me to change this and the rest of the changes to this file come about because of the change here.

File: test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java [hunk 5]
```diff
@@ -91,13 +94,38 @@
...
+    /**
+     * Does the cluster being tested have xpack installed?
+     */
+    public static boolean hasXPack() throws IOException {
+        RestClient client = adminClient();
+        if (client == null) {
+            throw new IllegalStateException("must be called inside of a rest test case test");
+        }
+        Map<?, ?> response = entityAsMap(client.performRequest(new Request("GET", "_nodes/plugins")));
+        Map<?, ?> nodes = (Map<?, ?>) response.get("nodes");
```
Comment (hub-cap) [inline test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java]: Do we need to do any null checks here? Im a-ok not doing it given we always know it will come back w/ the data we want/need. I know its just a call to `_nodes/plugins` so I assume this is legit.

File: test/framework/src/main/java/org/elasticsearch/test/rest/yaml/Features.java [hunk 6]
```diff
@@ -53,11 +56,23 @@ private Features() {
...
+            for (String feature : features) {
+                if (feature.equals("xpack")) {
+                    if (false == ESRestTestCase.hasXPack()) {
+                        return false;
+                    }
+                } else if (feature.equals("no_xpack")) {
+                    if (ESRestTestCase.hasXPack()) {
+                        return false;
+                    }
+                } else if (false == SUPPORTED.contains(feature)) {
```
Comment (hub-cap) [inline test/framework/src/main/java/org/elasticsearch/test/rest/yaml/Features.java]: any reason we just dont `return SUPPORTED.contains(feature)` for the last if branch?

**Review by hub-cap — APPROVED** [review]
LGTM, nits.

**Comment by nik9000** [comment]
Backported to 6.x. I do not plan to backport to 6.3.
