### PR TITLE
ESQL: Support intra-row field references in ROW command

### LINKED ISSUE #140119: ESQL: ROW not allowing using of previously-declared fields
While a query like this with EVAL works:
```
ROW x = 0 | EVAL x = 4, y = 2, z = x + y
```

This same query with ROW fails:
```
ROW x = 4, y = 2, z = x + y
```

With:
```
Unknown column [x], Unknown column [y]
```

### PR DESCRIPTION
**Pull request by kanoshiou**
## Summary
This PR fixes an issue where valid ESQL `ROW` commands failed when a field referenced a previously defined field within the same command (e.g., `ROW x = 4, y = 2, z = x + y`).

## Changes
- **LogicalPlanBuilder**: Removed the call to `mergeOutputExpressions` in `visitRowCommand`. We now intentionally defer duplicate field handling and reference resolution to the Analyzer.
- **AnalyzerRules**: Updated `ResolveRefs` to specifically **not** skip `Row` nodes, even if they flag as `resolved()` (which happens when they only contain literals).
- **Analyzer**: Implemented `resolveRow` within the `ResolveRefs` rule. This logic mimics `resolveEval` but for literals:
    - It iterates through the fields sequentially.
    - It allows later fields to resolve references to earlier fields by substituting them with their defined expressions.
    - It handles field shadowing by removing earlier definitions if a duplicate name is encountered.

## Related Issue
Closes #140119

### CODE REVIEW

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 1]
```diff
@@ -10783,4 +10783,172 @@ public void testDoubleInlineStatsPrunning_With_MV_Functions() {
...
+
+    /**
+     * <pre>{@code
+     * Limit[1000[INTEGER],false,false]
+     * \_LocalRelation[[b{r}#89, a{r}#91],Page{blocks=[
+     * IntVectorBlock[vector=ConstantIntVector[positions=1, value=2]],
+     * IntVectorBlock[vector=ConstantIntVector[positions=1, value=3]]]}]
+     * }</pre>
+     */
+    public void testRowFieldResolutionShadowing() {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:10063]: Can you add another test with a combination of a expression + shadowing? Something like this, which is allowed in EVAL:
```
ROW a = 1, b = 2, a = a + b
```

Edit: I just saw you added this case as a CSV test, so feel free to ignore this comment!

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 2]
```diff
@@ -1185,6 +1209,57 @@ private LogicalPlan resolveEval(Eval eval, List<Attribute> childOutput) {
...
+         * Field shadowing is supported:
+         * <pre>
+         * ROW x = 5, y = x * 2, x = y + 1
+         * - First x = 5 is defined
+         * - y = x * 2 resolves to y = 5 * 2 = 10
+         * - Second x = y + 1 resolves to x = 10 + 1 = 11
+         * - Final output: y = 10, x = 11 (first x is removed)
+         * </pre>
+         */
+        private LogicalPlan resolveRow(Row row) {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: This is mostly identical to resolveEval right? Is the only difference the final return? Can we merge the functions, or extract the logic from both? So whatever we do with Eval, works here too

**Review by ivancea — COMMENTED** [review]
Thanks for jumping into this! Looks good to me, but I'll ask first somebody else with more expertise to take a look at this code

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java:1]: Also, can we have a failing test like: `ROW a = b + c, b = 1, c = 2`

**Comment by kanoshiou** [comment]
Thank you for your review, @ivancea! Failing test has now been added!

In https://github.com/elastic/elasticsearch/pull/140217/commits/9c70b68f2930d2f9b344ae7d09d093d8f5025cef, I have refactored the redundant logic from `resolveEval` and `resolveRow`. I also implemented an optimization to expand aliases directly—for example, transforming `eval a = 1, b = a + 1` into `eval a = 1, b = 1 + 1`.

However, this change requires updates to a large number of tests. While some of the resulting optimized plans look correct, others are less intuitive. I am unsure if I should restrict this logic's scope to the `ROW` command only; I would appreciate some guidance on this.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 3]
```diff
@@ -8643,11 +8644,17 @@ public void testToDatePeriodToTimeDurationWithField() {
         e = expectThrows(VerificationException.class, () -> planTypes("""
             from types | EVAL x = keyword, y = date + x::date_period"""));
         assertTrue(e.getMessage().startsWith("Found "));
-        assertEquals("1:43: argument of [x::date_period] must be a constant, received [x]", e.getMessage().substring(header.length()));
+        assertEquals(
+            "1:23: argument of [x::date_period] must be a constant, received [keyword]",
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java]: This change is not correct as `1:23` corresponds to `keyword`, not `x::date_period`. The error is in 1:43, as it was before.
Whatever changes we make to the plan, the errors should always correctly point to the user-provided query, and the line/column numbers must be coherent with the "received" text

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceRowAsLocalRelation.java [hunk 4]
```diff
@@ -30,6 +30,7 @@ protected LogicalPlan rule(Row row, LogicalOptimizerContext context) {
         List<Object> values = new ArrayList<>(fields.size());
         fields.forEach(f -> values.add(f.child().fold(context.foldCtx())));
         var blocks = BlockUtils.fromListRow(PlannerUtils.NON_BREAKING_BLOCK_FACTORY, values);
-        return new LocalRelation(row.source(), row.output(), LocalSupplier.of(blocks.length == 0 ? new Page(0) : new Page(blocks)));
+        // When Row has no fields, we still need 1 row for downstream Eval operations to work on
+        return new LocalRelation(row.source(), row.output(), LocalSupplier.of(blocks.length == 0 ? new Page(1) : new Page(blocks)));
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/ReplaceRowAsLocalRelation.java]: Is this required for this PR's changes? I fear this could have further implications, or some untested behaviour

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PropagateEvalFoldables.java [hunk 5]
```diff
@@ -55,10 +56,10 @@ public LogicalPlan apply(LogicalPlan plan, LogicalOptimizerContext ctx) {
                     }
                 });
             }
-            // Apply the replacement inside Filter and Eval (which shouldn't make a difference)
+            // Apply the replacement inside Filter, Eval and Row (which shouldn't make a difference)
             // TODO: also allow aggregates once aggs on constants are supported.
             // C.f. https://github.com/elastic/elasticsearch/issues/100634
-            if (p instanceof Filter || p instanceof Eval) {
+            if (p instanceof Filter || p instanceof Eval || p instanceof Row) {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/rules/logical/PropagateEvalFoldables.java:62]: Is this pruning required too?

**Review by ivancea — CHANGES_REQUESTED** [review]
Again, sorry for the delay! We had a discussion about this issue, and concluded that it's worth doing (There was a parallel initiative regarding multi-ROWs in process).

I see the extra pieces, like column pruning, cause some test changes and side-effects. Even if they would be good to have, I wouldn't add them in this PR.

Ideally, this PR should affect only ROW. Having other plan changes may lead to the subtle introduction of bugs or unexpected cases, plus a more complex review process. Better to do them in continuation PRs unless they're needed for this functionality

**Comment by kanoshiou** [comment]
Thanks for the feedback, @ivancea!

I’ve narrowed the scope to intra-row references as suggested. I personally feel the extra functionality is a very useful 'nice-to-have' for the ROW command, but I agree it's better to keep this PR clean. I’ve pushed the updates for your review!

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 6]
```diff
@@ -6262,12 +6264,14 @@ public void testInlineStatsWithRow() {
...
         assertThat(
             localRelation.output(),
             containsIgnoringIds(
-                new ReferenceAttribute(EMPTY, "salary", INTEGER),
-                new ReferenceAttribute(EMPTY, "emp_no", INTEGER),
-                new ReferenceAttribute(EMPTY, "gender", KEYWORD)
+                new ReferenceAttribute(EMPTY, null, "salary", INTEGER, Nullability.FALSE, null, false),
+                new ReferenceAttribute(EMPTY, null, "emp_no", INTEGER, Nullability.FALSE, null, false),
+                new ReferenceAttribute(EMPTY, null, "gender", KEYWORD, Nullability.FALSE, null, false)
+
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java]: Aren't these changes redundant?

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java [hunk 7]
```diff
@@ -341,6 +341,59 @@ public void testRowAttributeResolution() {
...
+        assertEquals("z", zField.name());
+        assertThat(zField.child(), instanceOf(Add.class));
+        Add addExpr = (Add) zField.child();
+        assertThat(addExpr.left(), instanceOf(Literal.class));
+        assertThat(addExpr.right(), instanceOf(Literal.class));
+        assertEquals(4, ((Literal) addExpr.left()).value());
+        assertEquals(2, ((Literal) addExpr.right()).value());
+    }
+
+    public void testRowWithUnresolvableForwardReferences() {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/analysis/AnalyzerTests.java:472]: Can we add a self-reference failing test too? `ROW a = a`

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java [hunk 8]
```diff
@@ -9836,6 +9836,173 @@ public void testPushDownLimitInForkPastEvalAndMvExpand() {
...
+     * <pre>{@code
+     * Limit[1000[INTEGER],false,false]
+     * \_LocalRelation[[a{r}#4, b{r}#7, c{r}#11, d{r}#15],Page{blocks=[
+     * IntVectorBlock[vector=ConstantIntVector[positions=1, value=10]],
+     * IntVectorBlock[vector=ConstantIntVector[positions=1, value=20]],
+     * IntVectorBlock[vector=ConstantIntVector[positions=1, value=30]],
+     * IntVectorBlock[vector=ConstantIntVector[positions=1, value=10]]]}]
+     * }</pre>
+     */
+    public void testRowFieldResolutionMultipleRefs() {
```
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:9877]: nit: Can we check the `LocalRelation` values in some of the tests? At least once, to ensure proper folding in unit tests

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java [hunk 9]
```diff
@@ -1418,6 +1420,37 @@ private LogicalPlan resolveEval(Eval eval, List<Attribute> childOutput) {
...
+            List<Alias> newFields = new ArrayList<>();
+            boolean changed = false;
+            for (Alias field : row.fields()) {
+                Alias result = (Alias) field.transformUp(UnresolvedAttribute.class, ua -> fieldExpressions.getOrDefault(ua.name(), ua));
+
+                changed |= result != field;
+                newFields.add(result);
+
+                if (result.resolved()) {
+                    fieldExpressions.put(result.name(), result.child());
```
Comment (ivancea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java]: In the current implementation, for `ROW a = FN(1), b = a`, the `UnresolvedAttribute` `a` is replaced with the actual expression `FN(1)`. The unexpected side-effect of this is non-deterministic functions making `a` and `b` now having different values.

I'm not aware of existing public non-deterministic functions, but for example we have the `Random`, which is for internal use only, and would probably make this "problem" visible.

Now, I'm not sure if this is worth worrying now, or if we already have this problem in EVAL or in other planning steps. We could fold the values here before inserting them in the map. I guess that would add quite some complexity though. WDYT @astefan?

If we decide to go with it, we could reuse the `Random()` function in an `AnalyzerTest`, probably

**Review by ivancea — COMMENTED** [review]
LGTM! Some minor test nits and one "major" topic before merging

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java
Comment (ivancea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1]: The random() cases added to Analyzer tests check structure, but not results. Can you add a test like the one on AnalyzerTests, here, so it's resolved to a LocalRelation, and we can assert that, for `ROW a = random(10000), b = a`, both `a` and `b` have the same value?

Not sure how complicated this will be, as random isn't foldable afaik. Honestly, given this fact, it may be a bad function to try, as I suppose ROW will fail trying to fold it? If that's the case, ignore this, I think we're good at least until another function like that appears

**Review by ivancea — APPROVED** [review]
LGTM!

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java
Comment (astefan) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1]: Added test

Comment (astefan) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizerTests.java:1]: Thank you for the review @ivancea
