### PR TITLE
Fix testIncorrectPasswordHashingAlgorithm

### LINKED ISSUE #66824: testIncorrectPasswordHashingAlgorithm failures
**Build scan**:

Example https://gradle-enterprise.elastic.co/s/skfubyliw3wqe

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.action.user.TransportChangePasswordActionTests.testIncorrectPasswordHashingAlgorithm" -Dtests.seed=D78AA09ED8362D41 -Dtests.security.manager=true -Dtests.locale=hi-IN -Dtests.timezone=Pacific/Chuuk -Druntime.java=8
```
**Reproduces locally?**: yes

**Applicable branches**: master, 7.11, 7.x

**Failure history**:

**Failure excerpt**:

Aggressive replacement in https://github.com/elastic/elasticsearch/pull/64024. We need to ensure that the hasher selected for hashing in the beginning of the tests is not the same that is set in passwordHashingSettings for the test to make sense.

### PR DESCRIPTION
**Pull request by BigPandaToo**
We need to make sure that the hasher selected for hashing in the 
beginning of the tests is not the same that is set in 
passwordHashingSettings for the test to make sense.

Resolve: #66824

### CODE REVIEW

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/user/TransportChangePasswordActionTests.java [hunk 1]
```diff
@@ -169,7 +169,7 @@ public void testIncorrectPasswordHashingAlgorithm() {
         TransportService transportService = new TransportService(Settings.EMPTY, mock(Transport.class), null,
             TransportService.NOOP_TRANSPORT_INTERCEPTOR, x -> null, null, Collections.emptySet());
         Settings passwordHashingSettings = Settings.builder().put(XPackSettings.PASSWORD_HASHING_ALGORITHM.getKey(),
-            randomFrom("pbkdf2_50000", "pbkdf2_100000", "bcrypt11", "bcrypt8", "bcrypt")).build();
+            randomFrom("pbkdf2_50000", "pbkdf2_100000", "bcrypt11", "bcrypt8", "bcrypt4")).build();
```
Comment (jkakavas) [inline x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/user/TransportChangePasswordActionTests.java:172]: These still can be the same as the one returned by getFastHashingAlgorithmForTest. We need to use a randomFrom in both places with different contents

**Comment by jkakavas** [comment]
Added @ywangd as I'm off for 2 more weeks

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/user/TransportChangePasswordActionTests.java (hunk 1 above)
Comment (jkakavas) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/user/TransportChangePasswordActionTests.java:172]: I take the comment back:) still leave this up to Yang

Comment (tvernum) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/user/TransportChangePasswordActionTests.java:172]: Or `randomOtherThan` ? (drive by comment, I haven't checked the underlying logic)

**Comment by tvernum** [comment]
I've added `v7.11.1` because this is failing in CI for the 7.11 branch too.

File: x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/user/TransportChangePasswordActionTests.java (hunk 1 above)
Comment (tvernum) [reply x-pack/plugin/security/src/test/java/org/elasticsearch/xpack/security/action/user/TransportChangePasswordActionTests.java:172]: I've looked now.
I'd propose:
```
        final String systemHash = randomValueOtherThan(hasher.name(), 
            () -> randomFrom("pbkdf2_50000", "pbkdf2_100000", "bcrypt11", "bcrypt8", "bcrypt"));
        Settings passwordHashingSettings = Settings.builder().put(XPackSettings.PASSWORD_HASHING_ALGORITHM.getKey(), systemHash).build();```
```

**Review by tvernum — APPROVED** [review]

**Comment by ywangd** [comment]
I am backporting this to 7.11 #66978
