### PR TITLE
SQL: Fix bug with JDBC timezone setting and DATE type

### LINKED ISSUE #39915: SQL: JDBC always uses timezone=UTC for requests to server
JDBC always uses `UTC` as the timezone param for requests sent to the server,
regardless of the `?timezone=XXX` used in the connection string.

This is a bug, as all calculations with date/times (eg. scalar functions applies on top of them like DAY_OF_MONTH)  are done with `UTC` timezone, and they potentially give wrong results, and those
operations cannot be translated and fixed in the client JDBC (which still holds the correct timezone passed from the params), as the original information of the exact timestamp is lost.

### PR DESCRIPTION
**Pull request by matriv**
Previously, JDBC's REST call to the server was always sending `UTC`
instead of the timezone passed through connection string/properties.

Moreover the conversion to `java.sql.Date` was problematic as a
calculation on the epoch millis was used to set the time to 00:00:00.000
and the timezone info was lost. This caused the resulting `java.sql.Date`
object which is always using the JVM's timezone (no matter what timezone
setting is used in the connection string/properties) to be wrongly created.

Fixes: #39915

### CODE REVIEW

File: x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcHttpClient.java [hunk 1]
```diff
@@ -50,7 +49,7 @@ boolean ping(long timeoutInMs) throws SQLException {
 
     Cursor query(String sql, List<SqlTypedParamValue> params, RequestMeta meta) throws SQLException {
         int fetch = meta.fetchSize() > 0 ? meta.fetchSize() : conCfg.pageSize();
-                SqlQueryRequest sqlRequest = new SqlQueryRequest(sql, params, null, Protocol.TIME_ZONE,
+                SqlQueryRequest sqlRequest = new SqlQueryRequest(sql, params, null, conCfg.timeZone().toZoneId(),
```
Comment (costin) [inline x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcHttpClient.java]: I would open up zoneId through a package protected setter - no need to go through the public timeZone() which keeps making a conversion between internal classes - that's mainly for public consumption.

File: x-pack/plugin/sql/jdbc/src/test/java/org/elasticsearch/xpack/sql/jdbc/TypeConverterTests.java [hunk 2]
```diff
@@ -41,9 +44,22 @@ public void testDoubleAsNative() throws Exception {
     }
 
     public void testTimestampAsNative() throws Exception {
-        ZonedDateTime now = ZonedDateTime.now(Clock.tick(Clock.system(ZoneId.of("Z")), Duration.ofMillis(1)));
-        assertThat(convertAsNative(now, EsType.DATETIME), instanceOf(Timestamp.class));
-        assertEquals(now.toInstant().toEpochMilli(), ((Timestamp) convertAsNative(now, EsType.DATETIME)).getTime());
+        ZonedDateTime now = ZonedDateTime.now(Clock.tick(Clock.system(UTC), Duration.ofMillis(1)));
```
Comment (costin) [inline x-pack/plugin/sql/jdbc/src/test/java/org/elasticsearch/xpack/sql/jdbc/TypeConverterTests.java]: Maybe extract this into a method - `now(ZoneId)`?

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/DataType.java [hunk 3]
```diff
@@ -43,7 +43,7 @@
     OBJECT(        "object",         JDBCType.STRUCT,    -1,                0,                 0,  false, false, false),
     NESTED(        "nested",         JDBCType.STRUCT,    -1,                0,                 0,  false, false, false),
     BINARY(        "binary",         JDBCType.VARBINARY, -1,                Integer.MAX_VALUE, 0,  false, false, false),
-    DATE(                            JDBCType.DATE,      Long.BYTES,        10,                10, false, false, true),
+    DATE(                            JDBCType.DATE,      Long.BYTES,        24,                24, false, false, true),
```
Comment (costin) [inline x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/DataType.java]: Why increase the precision of date? it doesn't have a time component...

**Review by costin — APPROVED** [review]
LGTM

File: x-pack/plugin/sql/jdbc/src/test/java/org/elasticsearch/xpack/sql/jdbc/TypeConverterTests.java (hunk 2 above)
Comment (astefan) [reply x-pack/plugin/sql/jdbc/src/test/java/org/elasticsearch/xpack/sql/jdbc/TypeConverterTests.java]: I think we used to have a `now` method in SQL somewhere, but if I remember well, it got moved. Searching the ES code, I found `org.elasticsearch.common.time.DateUtils.nowWithMillisResolution()`.

**Review by astefan — COMMENTED** [review]
Shouldn't there by tests that cover these scenarios? (DAY_OF_WEEK depending on the time zone, WEEK_OF_MONTH and other similar functions)

File: x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/DataType.java (hunk 3 above)
Comment (matriv) [reply x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/type/DataType.java]: Because we do return the whole date (e.g. 2019-03-12 00:00:00+10:00)
as DATE is internally a ZonedDateTime and we do want to show the timezone.

This was a mistake here as in the docs is correctly set to 24:
https://github.com/elastic/elasticsearch/blob/master/docs/reference/sql/language/data-types.asciidoc

File: x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcDateUtils.java [hunk 4]
```diff
@@ -47,7 +51,9 @@ static long asMillisSinceEpoch(String date) {
     }
     
     static Date asDate(String date) {
-        return new Date(utcMillisRemoveTime(asMillisSinceEpoch(date)));
+        ZonedDateTime zdt = ISO_WITH_MILLIS.parse(date, ZonedDateTime::from);
+        ZoneId zoneId = zdt.getZone();
+        return new Date(zdt.toLocalDate().atStartOfDay(zoneId).withZoneSameInstant(zoneId).toInstant().toEpochMilli());
```
[the remark this answers is not in the document]
Comment (matriv) [reply x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/JdbcDateUtils.java]: It's replaced with `atStartOfDay` with the correct timezone vs the calculation that there was there before that was done on UTC millis so it was setting the start of date in UTC instead of the actual tz (`2019-03-12 00:00:00+00:00` instead for example `2019-03-13 00:00:00+10:00`)

**Review by astefan — APPROVED** [review]
LGTM

**Comment by matriv** [comment]
Backported to `7.x.` with 4e9657f93fbda0d4d1560024019e5128dd53447a
to `7.0` with 3c74a319f96ec55b4cf72e6a4ac508b86dc936af
to `6.7` with 7611210633b1aeb67aeb56111a7031eaae4cdc43
to `6.6` with cfda2c0a8fecaabe39d91070685f048d3eead0b2
