### PR TITLE
[ES|QL] Skip validating remote cluster index names in parser

### LINKED ISSUE #114201: [ES|QL] CCS index with quotes fails
### Elasticsearch Version

8.16

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 22.6.0

### Problem Description

When we are wrapping a CCS index with quotes it fails with "Invalid index name: <index> must not contain :"

Image

Wrapping a normal index with quotes works fine so this is a weird behavior. Also the error is confusing. CCS indexes are described with :

### Steps to Reproduce

1. Ensure that you have a CCS index
2. Use the esql api to query this index with quotes : `from "remote_cluster:index"`

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves: #114201

Skip the validation of index names in parser if it is from a remote cluster.

Reduce the scope of #112081 to local indices only.

It is mainly because the behavior of invalid indices names on remote cluster is inconsistent with local cluster, for example these commands below pass even though the index name is invalid or remote cluster does not exists. 

```
FROM *:invalid#index
FROM *fake:invalid#index
```

It is better to defer the validation of remote cluster indices names to later phase or until the pattern is clear.

### CODE REVIEW

**Comment by bpintea** [comment]
> Resolves: https://github.com/elastic/elasticsearch/issues/114201

Not sure if that needs resolving: the grammar allows FROM with unquoted_index | quoted_index | unquoted_remote_cluster:(unquoted_index | quoted_index). So if smth is quoted only, that has to be an index.

**Comment by bpintea** [comment]
> It is better to defer the validation of remote cluster indices names to later phase

But will it not eventually fail anyways? In my understanding the point was to not allow later phases to execute, if we know it's for nothing.
However, if the failure is drastically different and we want to keep consistency, that could be a reason to skip the validation, but is that the case?

**Comment by astefan** [comment]
> > It is better to defer the validation of remote cluster indices names to later phase
> 
> But will it not eventually fail anyways? In my understanding the point was to not allow later phases to execute, if we know it's for nothing. However, if the failure is drastically different and we want to keep consistency, that could be a reason to skip the validation, but is that the case?

The story is more complex than this :-). I am in favor of skipping the validation of anything related to CCS. See [this discussion](https://github.com/elastic/elasticsearch/issues/112886) for more context. Depending on `skip_available` setting we might or might not fail a query to a remote cluster.

**Review by astefan — APPROVED** [review]
LGTM

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java [hunk 1]
```diff
@@ -357,7 +358,12 @@ public void testInlineStatsWithoutGroups() {
     }
 
     public void testStringAsIndexPattern() {
-        for (String command : List.of("FROM", "METRICS")) {
+        List<String> commands = new ArrayList<>();
+        commands.add("FROM");
+        if (Build.current().isSnapshot()) {
```
Comment (bpintea) [inline x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:363]: Are the tests run in non-snapshot code? Can stay as is, was just wondering.

File: x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/IdentifierBuilder.java [hunk 2]
```diff
@@ -71,6 +75,9 @@ private static void validateIndexPattern(String indexPattern, EsqlBaseParser.Ind
         String[] indices = indexPattern.split(",");
         boolean hasExclusion = false;
         for (String index : indices) {
+            if (isRemoteIndexName(index)) { // skip the validation if there is remote cluster
```
Comment (bpintea) [inline x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/parser/IdentifierBuilder.java:78]: This check is a bit baffling unless you dig in the grammar to understand that when quoting an index pattern, this can actually contain a remote index pattern, which is accepted downstream. I guess a comment (somewhere) would be nice to the next reader, but can also be merged as is without it.

**Review by bpintea — APPROVED** [review]
Lgtm

**Review by costin — APPROVED** [review]
LGTM - please backport this to 8.16 also.

File: x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java (hunk 1 above)
Comment (fang-xing-esql) [reply x-pack/plugin/esql/src/test/java/org/elasticsearch/xpack/esql/parser/StatementParserTests.java:363]: It doesn't have the `assumeTrue` for snapshot, just be to cautious.

**Comment by fang-xing-esql** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/114959)|
|✅|8.16|[](https://github.com/elastic/elasticsearch/pull/114960)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)
