### PR TITLE
[ML] Tolerate total_search_time_ms not mapped in get datafeed stats

### LINKED ISSUE #46437: ML jobs disappeared on UI after upgrading to 7.4.0 BC
Steps to reproduce:
 - Created and ran some ml jobs on 7.3.1, 
 - Upgrade the cluster to 7.4.0 BC3, 
 - After upgrade, all pre-upgraded ml jobs disappeared from UI (either machine learning->job management or management->jobs list), and there is an error shown:

image

Expect:
All ml jobs are shown on UI.

### PR DESCRIPTION
**Pull request by droberts195**
ML users who upgrade from versions prior to 7.4 to 7.4 or later
will have ML results indices that do not have mappings for the
total_search_time_ms field.  Therefore, when searching these
indices we must tolerate this field not having a mapping.

Fixes #46437

### CODE REVIEW

**Comment by droberts195** [comment]
This is marked `>non-issue` as it is a fix to code that has never been released.  But it is fixing a very bad bug and needs to go into 7.4.0.

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java [hunk 1]
```diff
@@ -525,7 +525,8 @@ private SearchRequestBuilder createLatestDatafeedTimingStatsSearch(String indexN
             .setSize(1)
             .setIndicesOptions(IndicesOptions.lenientExpandOpen())
             .setQuery(QueryBuilders.idsQuery().addIds(DatafeedTimingStats.documentId(jobId)))
-            .addSort(SortBuilders.fieldSort(DatafeedTimingStats.TOTAL_SEARCH_TIME_MS.getPreferredName()).order(SortOrder.DESC));
+            .addSort(SortBuilders.fieldSort(DatafeedTimingStats.TOTAL_SEARCH_TIME_MS.getPreferredName())
+                .unmappedType("double").order(SortOrder.DESC));
```
Comment (benwtrent) [inline x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java]: @droberts195 there is also a sort on `bucket_count` in this file. Is that one going to cause problems as well? I am currently trying to find it in the mappings.

Comment (benwtrent) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java]: Ah, it looks like the field is there from `DataCounts` previously.

**Review by benwtrent — APPROVED** [review]

File: x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java (hunk 1 above)
Comment (droberts195) [reply x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsProvider.java]: Good thought.  I just double checked and it doesn't, because `bucket_count` is also a field in `data_counts` documents that have existed since 5.4.  So it would have the correct mappings in any results index that has been created by any released version of ML.  Of course, it could break the job stats endpoint in the case of a results index created manually with incomplete mappings, but we have many sorts where that could happen.  Since this PR is green I'd rather merge as-is to fix the critical problem.  If we decide we want to make _all_ our sorts more robust to incomplete mappings we can do that in a followup.

**Comment by przemekwitek** [comment]
Thanks for fixing that @droberts195 !
