### PR TITLE
Make MockLogAppender threadsafe

### LINKED ISSUE #106425: [CI] SingleNodeDiscoveryIT testCannotJoinNodeWithSingleNodeDiscovery failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/a5dvvhunctzui/tests/:server:internalClusterTest/org.elasticsearch.discovery.single.SingleNodeDiscoveryIT/testCannotJoinNodeWithSingleNodeDiscovery

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.discovery.single.SingleNodeDiscoveryIT.testCannotJoinNodeWithSingleNodeDiscovery" -Dtests.seed=EDFBA5FF9920092C -Dtests.locale=ga-IE -Dtests.timezone=Pacific/Saipan -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.discovery.single.SingleNodeDiscoveryIT#testCannotJoinNodeWithSingleNodeDiscovery`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCannotJoinNodeWithSingleNodeDiscovery'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.discovery.single.SingleNodeDiscoveryIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: (an empty collection or iterable containing [a string starting with "JNDI lookup class is not available because this JRE does not support JNDI. JNDI string lookups will not be available, continuing configuration.", a string starting with "JMX runtime input lookup class is not available because this JRE does not support JMX. JMX lookups will not be available, continuing configuration. "] or iterable containing [a string starting with "JMX runtime input lookup class is not available because this JRE does not support JMX. JMX lookups will not be available, continuing configuration. "])
     but: was <[Attempted to append to non-started appender mock]>

  at __randomizedtesting.SeedInfo.seed([EDFBA5FF9920092C:120F4759CD49A567]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2147)
  at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:718)
  at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:524)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at org.junit.rules.RunRules.evaluate(RunRules.java:20)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by rjernst**
Adding and removing appenders in Log4j is not threadsafe. Yet some tests rely on capturing logging by adding an in memory appender, MockLogAppender. This commit makes the mock logging threadsafe by creating a new, singular appender for mock logging that delegates, in a threadsafe way, to the existing appenders created. Confusingly MockLogAppender is no longer really an appender, but I'm leaving clarifying that for a followup so as to limit the scope of this PR.

closes #106425

### CODE REVIEW

File: test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java [hunk 1]
```diff
@@ -31,12 +33,35 @@
 /**
  * Test appender that can be used to verify that certain events were logged correctly
  */
-public class MockLogAppender extends AbstractAppender {
+public class MockLogAppender {
```
Comment (ldematte) [inline test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java:36]: Q: since this is no longer an appender, could this break things in serverless? (if tests there use something like `Loggers.addAppender(mockAppender)`)

File: test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java [hunk 2]
```diff
@@ -243,29 +269,38 @@ public String toString() {
...
         }
         return () -> {
-            for (final var logger : loggers) {
-                Loggers.removeAppender(logger, this);
+            isAlive.set(false);
+            for (String logger : loggers) {
+                mockAppenders.compute(logger, (k, v) -> {
+                    assert v != null;
+                    v.remove(this);
+                    return v.isEmpty() ? null : v;
```
Comment (ldematte) [inline test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java:301]: TIL: compute remappingFunction returning null removes the mapping. Nice!

File: test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java [hunk 3]
```diff
@@ -31,12 +33,35 @@
 /**
  * Test appender that can be used to verify that certain events were logged correctly
  */
-public class MockLogAppender extends AbstractAppender {
+public class MockLogAppender {
 
+    private static final Logger logger = LogManager.getLogger(MockLogAppender.class);
```
Comment (ldematte) [inline test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java:38]: I don't understand why do we need this. What I'm missing?

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java [hunk 4]
```diff
@@ -259,6 +259,7 @@ public static void resetPortCounter() {
         // TODO: consolidate logging initialization for tests so it all occurs in logconfigurator
         LogConfigurator.loadLog4jPlugins();
         LogConfigurator.configureESLogging();
+        MockLogAppender.init();
```
Comment (ldematte) [inline test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:262]: This needs to be called every time we (re) configure log4j in tests, right?
So besides the special case above, ESTestCase (should) cover all, correct?

**Review by ldematte — COMMENTED** [review]
Looks very nice, I have left a couple of questions

File: test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java [hunk 5]
```diff
@@ -31,12 +33,35 @@
...
+    private static final Map<String, List<MockLogAppender>> mockAppenders = new ConcurrentHashMap<>();
+    private static final RealMockAppender parent = new RealMockAppender();
     private final List<WrappedLoggingExpectation> expectations;
+    private final AtomicBoolean isAlive = new AtomicBoolean(true);
```
Comment (thecoop) [inline test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java:42]: Does this need to be an AtomicBoolean? Couldnt it just be a `volatile boolean`?

Comment (thecoop) [reply test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java:42]: Same in `WrappedLoggingExpectation`

**Review by pgomulka — APPROVED** [review]
LGTM

File: test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java (hunk 1 above)
Comment (rjernst) [reply test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java:36]: It will "break" things, but I have the necessary changes ready.

File: test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java (hunk 3 above)
Comment (rjernst) [reply test/framework/src/main/java/org/elasticsearch/test/MockLogAppender.java:38]: Leftover from debugging, will remove

File: test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java (hunk 4 above)
Comment (rjernst) [reply test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java:262]: Yep, any tests subclassing LuceneTestCase directly will need to call it if they use MockLogAppender.

**Review by thecoop — APPROVED** [review]

**Review by DaveCTurner — COMMENTED** [review]
LGTM2 but I haven't looked at this very deeply so I'll leave the final approval to the other reviewers.

**Review by ldematte — APPROVED** [review]
LGTM 2! Nice change!

**Comment by ldematte** [comment]
(btw, CI test failure looks related but should be fixable)
